### ISSUE TITLE
NO GPS in QGC

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#10014]
why is this?

![2018-07-24 14-45-42](https://user-images.githubusercontent.com/40378941/43121764-6f512310-8f51-11e8-93a2-6b8fb9d5893b.png)

analyze have data .but showwing NO GPS

**Comment by MariliG** [comment]
Hi,  
It seems that for some reason the position estimator did not initialize. 
Can you please share the log file?

**Comment by roseyangyu** [comment]
I solve that. Because the fix_type is not receive.
