### ISSUE TITLE
Description or unit Error for parameter COM_VEL_FS_EVH

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#10028]
https://github.com/PX4/Firmware/blob/9a7195cb2d7df8e4e8b9af51031d7e77a9842e09/src/modules/commander/commander_params.c#L747
https://github.com/PX4/Firmware/blob/9a7195cb2d7df8e4e8b9af51031d7e77a9842e09/src/modules/commander/commander_params.c#L750

Seems that the unit of this parameter should be m/s, right?

**Comment by dagar** [comment]
Yes, good catch. Can you open a PR?

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/pull/10071
