### ISSUE TITLE
Safety switch not changing its state

### ISSUE THREAD

**Issue by shabhu18** [PX4/Firmware#10036]
my system
pixhawk 2.1
px4 version : 1.8
gps+compass+safety switch is connected in GPS1 port of pixhawk 2.1

Issue : The safety switch doesn't changes its state to arm state. No console output .

how to debug this stuff.

**Comment by dagar** [comment]
Can you check the circuit breaker parameters?

To debug start with `listener safety` via nsh.

**Comment by santiago3dr** [comment]
I ran a test on a 2.1 cube
flashed 1.8.0 stable and then current master
both look to be engaging the safety switch properly
![v3-stable](https://user-images.githubusercontent.com/13203106/43226763-928ceb46-9011-11e8-80a4-b5f0f75d7420.JPG)
![v3-master](https://user-images.githubusercontent.com/13203106/43226773-974ad03a-9011-11e8-93f4-8592c505f83b.JPG)

@shabhu18 what are the leds on the GPS module doing?

**Comment by shabhu18** [comment]
i get the following if i so listener safety

TOPIC: safety instance 0 #1
 safety_s
	timestamp: 361180857 (0.021590 seconds ago)
	safety_switch_available: 1
	safety_off: 0
	override_available: 0
	override_enabled: 0

The state doesn't change even if i change safety switch for a while.

meanwhile on QGC i get the following
[11:08:11 522] Emergency: Mag 0 fail : Timeout
[11.08.25 512] critcal: PREFLIGHT FAIL :MAG SENSOR INCONSTANT

**Comment by santiago3dr** [comment]
given mag 0 is giving error,s it might be a problem with the connector or GPS module... does the gps portion work properly?

**Comment by shabhu18** [comment]
I disabled the safety switch in software it worked .
