### ISSUE TITLE
Dive when switching to AltHold with MPC_THR_HOVER set to 0.6

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#10040]
**Describe the bug**
Setting MPC_THR_HOVER to 0.6, my quad hovers at RC channel 0.5 (a bit overloaded vehicle). When I now switch to AltHold (with LIDAR attached), the thrust setpoint is set to 0.5 which causes a drop of the vehicle. After correction by RC (and going back to RC = 0.5), AltHold works perfectly at thrust 0.6. Position mode is set to 'smooth'. 

**Expected behavior**
I assumed that with MPC_THR_HOVER = 0.6, the set point of thrust is set to 0.6 instead of 0.5.

**Log Files and Screenshots**
I will share log later. 

<img width="1024" alt="hover" src="https://user-images.githubusercontent.com/7580193/43212346-0109cea0-9034-11e8-930b-95d5b07b1719.png">

**Comment by dagar** [comment]
Which version of PX4?

**Comment by ecmnet** [comment]
It was latest master 1.8 , FMUv5 (PixHawk 4).

**Comment by ecmnet** [comment]
Works with latest master
