### ISSUE TITLE
RC SBUS

### ISSUE THREAD

**Issue by garfieldG** [PX4/Firmware#10052]
It seems like there are two places that handle rc, One is in px4io driver and one is in px4fmu driver.
It's seems asymmetrical which might cause issues when using boards with no IO cpu, for example in px4io driver the rssi is addressed while in px4fmu it's not (in case of sbus mode) and the parameters that should handle it are compiled only when using px4io driver.

Isn't it more logical change it to one place that handles RC?

**Comment by LorenzMeier** [comment]
Yes, we need to consolidate more of that (bringing more into the parsing libraries that we already have for the different protocols). Would you be interested in taking a stab at that?

**Comment by garfieldG** [comment]
I can look at it, not sure that I know the code hyrarchy enough in order to do that
