### ISSUE TITLE
fetch_file.py is broken

### ISSUE THREAD

**Issue by keenanjohnson** [PX4/Firmware#10053]
It would appear that the [fetch_file.py](https://github.com/PX4/Firmware/blob/master/Tools/fetch_file.py) script is currently broken.

It appears that the script is checking for an "OK" message before receiving the file.

![image](https://user-images.githubusercontent.com/2559382/43276221-d6bc00fc-90b8-11e8-883c-141bdd84eca5.png)

However, [this commit](https://github.com/PX4/Firmware/commit/0fdd2b9feac05775553a53475b99b9bf6de6c6d3#diff-83bc6fdf121621e05f2288d011d138ddL66) changed that message header from "OK" to  "File size:"

![image](https://user-images.githubusercontent.com/2559382/43276203-c7fc7088-90b8-11e8-9372-7ac08f43b44b.png)

**Comment by LorenzMeier** [comment]
Can you just use MAVLink FTP? If you need that script to work, can you send a PR to fix?

**Comment by keenanjohnson** [comment]
What is MAVLink FTP? How do I use that?

**Comment by LorenzMeier** [comment]
Widgets -> Onboard Files gives you all files. Otherwise use the log download:

<img width="1018" alt="screen shot 2018-07-27 at 00 05 43" src="https://user-images.githubusercontent.com/1208119/43291189-e9cc9f80-9130-11e8-8423-31090fb85c97.png">

**Comment by mhkabir** [comment]
You don't need actually need a screen or QGC. You can implement the mavlink FTP protocol in a custom script as needed. https://mavlink.io/en/protocol/ftp.html

As for the broken tooling, it would be great if you could send a PR removing it or fixing it. It seems like an easy fix, either way.
