### ISSUE TITLE
PX4 Stable v1.8.1 Planning

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#10064]
PX4 Firmware v1.8.0 + back ported bug fixes.

https://github.com/PX4/Firmware/milestone/28

 - https://github.com/PX4/Firmware/pull/9905
 - https://github.com/PX4/Firmware/pull/9910 (arguably way more than bug fixes)
 - https://github.com/PX4/Firmware/pull/9850
 - https://github.com/PX4/Firmware/pull/9925
 - https://github.com/PX4/Firmware/pull/9941
 - https://github.com/PX4/Firmware/pull/10020
 - https://github.com/PX4/Firmware/pull/10041
 - https://github.com/PX4/Firmware/pull/10024
 - https://github.com/PX4/Firmware/pull/10063
 - https://github.com/PX4/Firmware/pull/10231

Proposed branching `stable` -> `release/1.8`.
 https://github.com/PX4/Firmware/compare/stable...release/1.8?expand=1

**Comment by dagar** [comment]
TODO:
 - review all issues and PRs since v1.8.0 release.
 - changelog generator (automate)
 - github releases automate from Jenkins (post binaries + changelog)

**Comment by davids5** [comment]
@dagar should we add the LED https://github.com/PX4/Firmware/pull/10579 ?

**Comment by dagar** [comment]
Yes, and consider if a Pixhawk 4 mini backport is viable.

**Comment by dagar** [comment]
Release v1.8.1 published https://github.com/PX4/Firmware/releases/tag/v1.8.1
