### ISSUE TITLE
cmake version check fails cmake ver >= 3.10.x (e.g. Ubuntu 18.04)

### ISSUE THREAD

**Issue by fibr** [PX4/Firmware#10069]
The current `Tools/check_cmake.sh` identifies cmake 3.10.2 (e.g. standard on ubuntu 18.04) as cmake 3.1 and throws a fit. 

This is the offending line
`if [[ $cmake_ver == *" 2.8"* ]] || [[ $cmake_ver == *" 2.9"* ]] || [[ $cmake_ver == *" 3.0"* ]] || [[ $cmake_ver == *" 3.1"* ]]`

I don't have cmake 3.1 around and can't reference that version string, perhaps it should say `$cmake_ver == *" 3.1."* ]]`?

**Comment by dagar** [comment]
We dropped that script a couple releases ago. Now cmake checks the cmake version.

Can you try newer PX4 stable (v1.8.0)?

**Comment by fibr** [comment]
Aha, I knew I was missing something. Yep, thanks for that note.
