### ISSUE TITLE
question about EKF2 fusing gps+vision

### ISSUE THREAD

**Issue by Changliu52** [PX4/Firmware#10062]
Hi @mhkabir @dagar @priseborough ,

I just need some clarifications since there are no clear guide yet for 1.8.0
In order to have the EKF2 to fuse GPS + vision at the same time, does the EKF2_AID_MASK has to be : use_GPS + vision_position_fusion + rotate_external_vision?

Will it fuse GPS and vision if the EKF2_AID_MASK is use_GPS + vision_position_fusion, and I send a pre-aligned vision pose? I remember before it only does the switching between GPS and Vision instead of fusion, is it still the same now with this mask?

**Comment by mhkabir** [comment]
> In order to have the EKF2 to fuse GPS + vision at the same time, does the EKF2_AID_MASK has to be : use_GPS + vision_position_fusion + rotate_external_vision?

Yes.

> Will it fuse GPS and vision if the EKF2_AID_MASK is use_GPS + vision_position_fusion, and I send a pre-aligned vision pose?

Yes.

>  I remember before it only does the switching between GPS and Vision instead of fusion, is it still the same now with this mask?

No, now it fuses the vision as a velocity update when GPS is being used. It no longer does a hard switch.

**Comment by Changliu52** [comment]
Interesting! Thanks.

**Comment by LorenzMeier** [comment]
Please use the forum to ask questions - you can link the forum thread here.

**Comment by mhkabir** [comment]
> Will it also fuse gps correctly considering the local_pose is not relative to the true north anymore in this case, by computing the gps offset pose relative to local pose?

No it will not.
