### ISSUE TITLE
Catkin build not supported !!

### ISSUE THREAD

**Issue by zubair123khan** [PX4/Firmware#10089]
**Describe the bug**
While building the package using catkin build, i am getting eror related to ecl.h missing. Can anyone please tel me why px4 Firmware still does not support catkin environment.

**Comment by dagar** [comment]
It's a build system error that needs to be fixed. Once fixed we need a very simple catkin build test in our CI system (http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/activity) to ensure it stays working.

**Comment by dagar** [comment]
Duplicate https://github.com/PX4/Firmware/issues/9554
