### ISSUE TITLE
command denied(241) issue while calibration.

### ISSUE THREAD

**Issue by rahulsharma11** [PX4/Firmware#10086]
Hi all,
I am using pixhawk mini with the latest stable v1.8.0. I have used external GPS as new firmware supports with external compass. While calibration in qgroundcontrol3.3.2, there is a warning of "command denied (241)" which occurs 3-4 times but the calibration goes on. Can't realy say its a bug or something else.

After calibration completion, there is another warning -
"External GPS with large offset". I have aligned the gps and pixhawk with the same direction keeping both arrow indication in same direction. Don't kow about that also.

After all this, it flies well, but when i do log analysis there are numbers of error and warnings-
Sensor MAG#0 failed; reconfiguring sensor prioities.
Remaining sensors after failover event #0 ; Mag#0 priority1 .
Does this affect inside?
I can share the log file too if required.
Thanks.

**Comment by LorenzMeier** [comment]
I’m closing this - there is an issue template for a reason. Please open a new issue and read the template this time and follow the instructions.

Thanks!
