### ISSUE TITLE
Pixhawk get to Brick mode after selecting Quad H4 680

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#10099]
**Describe the bug**
Playing with pixhawk 4 I have selected 'Quad H4 680' airframe on QGC.
After that, the Pixhawk does the start-up tune, but not much more.
There is no communication with the PC Via USB, so I can't change parameters and so.
The only way that I found to recover the Pixhawk is by putting rc.txt on the SD card with 'param reset' commnad on it.

**To Reproduce**
select 'Quad H4 680' airframe on QGC.
Tested twice, no other frame has been tested, or other Pixhawk HW.

**Comment by dagar** [comment]
Have you successfully used this airframe before?

**Comment by BazookaJoe1900** [comment]
@dagar - No, I don't have this frame and ddidn't use it. I just wanted to look at the parameters of that frame.
