### ISSUE TITLE
Add the ability to reset all parameters from QGC even if system is not any more booting properly

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#10095]
**Describe problem solved by the proposed feature**
If you set parameters such that the system doesn't boot properly, the only way to recover is to wipe the storage.

**Describe your preferred solution**
We need some way to reset the parameters on boot as the first instruction. One approach would be to set a magic value in the backup RAM in the bootloader (via QGC), then wipe the flash once the application boots fully.

**Describe possible alternatives**
A dual storage for a configuration that you can switch back and forth.

**Comment by dagar** [comment]
"Safe Mode"

**Comment by dagar** [comment]
Anyone monitoring FRAM usage?

**Comment by LorenzMeier** [comment]
I'm casually monitoring it and we're far off the limits still. We might want to tear down the waypoints partition sometime soon.

**Comment by davids5** [comment]
@LorenzMeier I may not understand the issue well.  

Why not just you put an sd card in with '/etc/rc.txt` that has `param reset` 

Would something like this work or do you feel more is needed?

At the top of rcS
check param BOOTING 
if it does not exist create param BOOTING = 1
else if set and == 3 do param reset and reboot.
if it is < 3  the increment it BOOTING = BOOTING + 1
...
at the end of rcS
delete param BOOTING

**Comment by LorenzMeier** [comment]
Because whenever I ask people to do that they get it wrong and it doesn't work for them. For a controls engineer only a GUI is a reliable way to do things. They are used to graphically clicking blocks in Simulink, not console commands or making sure files are in the exactly right location with the right name and content.

**Comment by dagar** [comment]
Maybe we should talk about the specific use case and workflow?

I'm wondering about...
 - an absolute minimal init that gets you mavlink + parameters (QGC)
 - something physical that could initiate a full reset
 - do we try to detect a bootloop and then do something?

**Comment by BazookaJoe1900** [comment]
It might be related to what happened to me at case #10099 [Pixhawk get to Brick mode after selecting Quad H4 680]
