### ISSUE TITLE
MAV_CMD_NAV_LAND_LOCAL denied although local position available

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#10102]
**Describe the bug**
MAV_CMD_NAV_LAND_LOCAL is denied with message 'Precision landing denied, land manually' although local position available. Using the command MAV_CMD_NAV_LAND without GPOS sends however the correct message 'Landing at current position' but the vehicle keeps in LOITER.

**Expected behavior**
If LPOS is available MAV_CMD_NAV_LAND_LOCAL should land according to the specified parameters.
Alternatively, MAV_CMD_NAV_LAND should land at current position with LPOS only.

**Comment by mhkabir** [comment]
Precision land, as it is implementers currently, needs global position.

I have a branch somewhere where it's hacked to work in local frame only. It's mostly about how the controllers don't process local setpoints when in AUTO mode. (Precland is a submode of AUTO)

**Comment by ecmnet** [comment]
What was the idea behind this separate mode? Local landing could be driven either by tags (as precision land does) or by other accurate LPOS sources, like vision. 

@dagar I agree to your statement, that the whole GPOS,LPOS thing needs to be revised - including the possibility to send a GlobalHome to EKF2 and control position locally by then.

**Comment by AlexKlimaj** [comment]
I think we just saw this same bug with the latest master. RTL and Land were not getting obeyed.

**Comment by ndepal** [comment]
> @ndepal how did you want this to work?

@dagar That appears to be a bug. If `VEHICLE_CMD_*` in `vehicle_command.msg` are supposed to match mavlink's `MAV_CMD_*`, does that mean we can't even really have a `VEHICLE_CMD_NAV_PRECLAND`? How does `MAV_CMD_NAV_LAND_LOCAL` work if it doesn't have a matching `VEHICLE_CMD_*`?

**Comment by dagar** [comment]
I believe it should be a superset.

**Comment by ecmnet** [comment]
Solved
