### ISSUE TITLE
'Reject AUTO HOLD' when switching to POSHOLD via RC with LPOS only

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#10101]
**Describe the bug**
Switching to position hold via RC returns message 'Reject AUTO HOLD' but still switches to POSHOLD. This appears if only LPOS is available (e.g. EKF2 and vision positioning feed).

**Expected behavior**
No message expected if LPOS is available.

**Comment by dagar** [comment]
This can be fixed in the state machine fairly easily. We just need to be careful to still require global for FW.

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L277

**Comment by ecmnet** [comment]
Solved
