### ISSUE TITLE
Failure to takeoff in Gazebo HITL for fixed-wing airframe 

### ISSUE THREAD

**Issue by zanemountcastle** [PX4/Firmware#10118]
**Describe the bug**
SITL work wonderfully on Gazebo for fixed-wing airframes. However, when running HITL on PX4 v1.8.0 using the HILStar plane, the plane refuses to take off, even with a mission loaded, the plane armed and the plane in "Mission" mode.

I have found the PX4 documentation to be somewhat contradictory on the status of fixed wing support for HITL on Gazebo. It is very possible that I am trying something that just doesn't work.

**To Reproduce**
1. Following (this)[https://github.com/PX4/Devguide/blob/master/en/simulation/hitl.md] guide, I cloned the firmware, and built Gazebo using
```
make posix_sitl_default gazebo
```
2. With the first terminal still running, I ran,
```
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/posix_sitl_default
```
3. I changed `serialEnabled` and `hil_mode` parameters to true in `Tools/sitl_gazebo/models/plane/plane.sdf`. I also ensured that the `serialDevice` parameter was correct.
4. Finally I quit the two original terminals, opened a new one and ran,
```
gazebo Tools/sitl_gazebo/worlds/plane.world
```
Here is a screenshot of what happens when I run this: 

<img width="730" alt="screen shot 2018-08-01 at 7 56 24 pm" src="https://user-images.githubusercontent.com/9016615/43559926-0844fe4c-95c5-11e8-8cb3-57b54870a2f0.png">

Nevertheless, `gzclient` opens and all seems to be working.

5. I opened QGC, connected to Gazebo automatically over UDP, and loaded a mission.
6. I attempted to start the mission and the plane successfully armed, but did not move. Instead, it sat there until I manually disarmed it. 

**Expected behavior**
I expected the plane to simulate an actual takeoff instead of sitting still.

**Log Files and Screenshots**
When I tried downloading the log file, I received an error.

**Drone (please complete the following information):**
- This HITL simulation is running on a Pixhawk 2.1 with PX4 v1.8.0.

**Comment by roseyangyu** [comment]
I have same bug to you.Have you solved?

**Comment by zanemountcastle** [comment]
Nope, I was never able to figure it out. 😕

**Comment by TiagoAvelino** [comment]
I have the same bug too, any discovery, comments here please

**Comment by akkiconnect** [comment]
A quick workaround is to use PX4 version 1.7.0 (https://github.com/PX4/Firmware/releases/tag/v1.7.0)
Was able to perform Gazebo HITL of Quadcopter

**Comment by S259420** [comment]
@akkiconnect Hello, how did you donwgraded to PX4 1.7.0? Where you able to takeoff the copter using PX41.7.0?

**Comment by pranavn248** [comment]
@S259420 You can just download the 1.7.0 firmware from PX4's github and upload it manually using QGC I think. I was able to take off in SITL mode as well when I used this version as.

**Comment by S259420** [comment]
@pranavn248 Thankyou for the firmware information. I can takeoff in SITL, the problem is takeoff in  HITL.

**Comment by TSC21** [comment]
https://dev.px4.io/en/simulation/hitl.html#compatible_airframe

**Comment by matteoscanavino** [comment]
@TSC21 I know that page... HITL is supported for copter with Gazebo. However, I still have takeoff problem...

**Comment by S259420** [comment]
@akkiconnect what kind of sensor failures? I didn't experience problems with sensors...
