### ISSUE TITLE
static error in altitude setpoint

### ISSUE THREAD

**Issue by samirrite** [PX4/Firmware#10137]
Hi there,

Flying with a fixed wing, I meet some problem with tecs algorithm, I'm trying to tune it, throttle and pitch looks to work properly in most of cases except one :

When altitude setpoint is a ramp (climbing or descending), i've a steady state error around 10 meters.
This is not due to the airplane capacity, this can be achieve in RC mode, and also if I ask for a ramp steeper.
When altitude setpoint is stable, the airplane reach it easily.
 Is that due to the first order IIR filter for integrator ? Does it need a second order ? Or maybe there is a couple of parameters that can fix it.
Thank you

**Comment by chamois94** [comment]
It seems same altitude tracking error than 3 years ago here https://github.com/PX4/Firmware/issues/2980.

Do you think tuning FF gain will do the trick ?

**Comment by chamois94** [comment]
Ardupilot uses an approach removing lag https://github.com/ArduPilot/ardupilot/commit/597273cfffc1d6ae935c6fb40a35cb58626456ed#diff-b6ecb54e20c4b89219bde19a4b8e93ee. I think it is not very elegant. What do you think?

**Comment by priseborough** [comment]
Not very elegant, but it works. A more accurate alternative alternative during flare and hold off, is to simultaneously track vertical accln, velocity and position in the height controller, where these are obtained from a PD controller tracking a reference trajectory. The height controller then generates a vertical acceleration demand , which is converted to a flight path rate using TAS. Flight path rate demand is then be converted to pitch rate demand using a lead/lag filter to compensate for the time constant from pitch rate to flight path rate.

**Comment by chamois94** [comment]
@priseborough  if I understand correctly you'll change the height rate setpoint into a height acceleration setpoint  by completely modifying  _update_height_setpoint to increase by an order of magnitude 1 the control loop ? Only for landing or in every case ?

**Comment by chamois94** [comment]
@priseborough do you think implementing your trajectory tracking for landing slope phase is also a good idea ?
