### ISSUE TITLE
Auto Return to Home Based on Flight Time

### ISSUE THREAD

**Issue by keenanjohnson** [PX4/Firmware#10168]
**Describe problem solved by the proposed feature**
A useful failsafe might be adding an auto return to home after a certain time has elapsed. This is particularly useful in systems that don't have any battery status information due to hardware constraints.

**Describe your preferred solution**
Ideally there would be a parameter to enable or disable this feature. Then there would be a parameter that sets the time after-which the vehicle should return home.

It seems fine if the pilot wants to regain control after this has been triggered.

**Comment by dagar** [comment]
Would it still trigger in any manual mode? Maybe a warning first would be prudent.
