### ISSUE TITLE
Set Servo Mission mav command does not seem to work.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#10177]
Hello guys,

We are trying to use Set Servo Mission command without success.

![image](https://user-images.githubusercontent.com/12617619/43746652-34794874-99ee-11e8-9288-88612d927f86.png)

Here we use channel 3 presuming the channel we use here are AUX channels.

This way on arming the servo goes to 1500 but then on set servo waypoint on ch 3 at 2000us nothing happens. The servo does not release.

The servo is connected always at AUX ch 3 just we change the way point set servo channel parameter from 1 - 6 and tried each setting with 2000us and 1000us in flight.

Nothing happens the drop servo just does not move at all on set servo mission point.

Are we missing something? I clearly do not see any way I should initialize the payload servo from the mixer.

Any help would be appreciated with this issue. We are in an emergency right now with this drop on target.

We use 1 month old master of QGC and 1.8 PX4 stable.

QGC is Windows version.

Any ideas?

**Comment by dagar** [comment]
I wouldn't be surprised if this feature has deteriorated. Do you happen to have a log that can be shared? I want to look for the command followed by any corresponding errors.

**Comment by minominium** [comment]
Ummm....dear tubeme, did you solve the problem?

I too expriencing same issue that servo is not functioned in mission mode.

All the settings are just same, except our servo is connected to AUX Pin 1.

And in QGC, we tried with changing AUX Pin, or PWM term.

If you reached the solution, please comment me. Thanks!

**Comment by kpetrykin** [comment]
Hello!

Maybe [this pull-request](https://github.com/PX4/Firmware/pull/10320) will help?

**Comment by GaoGeolone** [comment]
@tubeme Everything goes well on the drone, but it failed to work on the fixed-wing UAV. Please give me a hand. @kpetrykin

**Comment by tubeme** [comment]
@GaoGeolone It does not work in VTOL as well.

**Comment by GaoGeolone** [comment]
@tubeme maybe it is the fw_att_control that affect the performance in fixed-wing UAVs when I set servo.
![image](https://user-images.githubusercontent.com/33696048/49740685-bcc11380-fccf-11e8-8638-e6f206244e5e.png)
