### ISSUE TITLE
UAVCAN broadcast cost too much cpu.

### ISSUE THREAD

**Issue by ToppingXu** [PX4/Firmware#10171]
**Describe the bug**
When using a uavcan esc, the cpu cost increase a lot, and finally I found it is caused by publisher.broadcast() function. And it is also increased by the mixer output channel count.
https://github.com/PX4/Firmware/blob/master/src/modules/uavcan/uavcan_main.cpp#L971
https://github.com/PX4/Firmware/blob/master/src/modules/uavcan/actuators/esc.cpp#L168

**To Reproduce**
1.enable uavcan esc.
2. update the mixer output to more than 6 six channel.
3. power on.
4. using top command to see the cpu load.

**Expected behavior**
Can anybody help improve the uavcan driver.

**Comment by LorenzMeier** [comment]
Definitely, something we're interested in making more efficient. @davids5 @pavel-kirienko Do you have immediate suggestions?

**Comment by pavel-kirienko** [comment]
My immediate suggestion is to profile the firmware using the Poor Man's Sampling Profiler https://github.com/PX4/Firmware/blob/master/platforms/nuttx/Debug/poor-mans-profiler.sh

The sudden CPU load increase at more than 6 ESC is because a large number of channels forces the protocol stack to use multi-frame transfers, which are costlier.

**Comment by ToppingXu** [comment]
@pavel-kirienko yes, but we have to use multi-frame transfers, the cpu load increase too much up to 30% and even more, I thought it used a block way to send message on can driver layer.

**Comment by pavel-kirienko** [comment]
I'm not saying that multi-frame transfers are to be avoided - they are supported just for the use cases like yours. Let's have a look at the profile and see where to go next. Can you keep the profiler running for an hour or so?

**Comment by ToppingXu** [comment]
I am not available here today, and I will do it tomorrow

**Comment by ToppingXu** [comment]
@pavel-kirienko So far, I am not able to use flamegraph. 
![image](https://user-images.githubusercontent.com/19683240/43758491-d75ddee6-9a4e-11e8-8ec8-50b6efefcc88.png). Can you give some detail. I do need your help, thanks.

**Comment by pavel-kirienko** [comment]
The usage info is provided in the header comment: https://github.com/PX4/Firmware/blob/master/platforms/nuttx/Debug/poor-mans-profiler.sh#L3-L18

The options are not documented but their purpose can be understood just by looking at the code. Sorry, there is no proper documentation for that tool!

**Comment by ToppingXu** [comment]
can you show me what command you use. Below is what I used.
![image](https://user-images.githubusercontent.com/19683240/43779038-e4451af8-9a89-11e8-886b-4eec73b31a76.png)

**Comment by pavel-kirienko** [comment]
This might help - as it turns out, I did publish some docs but forgot about that: https://dev.px4.io/en/debug/profiling.html

**Comment by dagar** [comment]
@ToppingXu @pavel-kirienko I also started adding cmake level helpers. https://github.com/PX4/Firmware/blob/master/platforms/nuttx/CMakeLists.txt#L309-L325

    make px4fmu-v4pro_default profile

**Comment by ToppingXu** [comment]
@dagar I use make px4fmu-v4pro_default profile still show "ERROR: No stack counts found
"

**Comment by dagar** [comment]
@ToppingXu make sure gdb is setup to connect with the attach in .gdbinit.

**Comment by ToppingXu** [comment]
hope this may help you solve the problem

**Comment by pavel-kirienko** [comment]
@ToppingXu please attach SVG. Also, how many samples did you record?

**Comment by hamishwillee** [comment]
@dagar Re https://github.com/PX4/Firmware/issues/10171#issuecomment-411072443  it is worth updating the docs.

Would I be correct in thinking that
```
make px4fmu-v4pro_default profile
```
1.  gets flamegraph, adds it to the path, then runs the sampler for 1000 points?
2. This replaces all the usage and setup stuff in the docs?
3. This runs on the development computer right, and only on linux/mac (not windows)?

**Comment by pavel-kirienko** [comment]
P. 2 not true - this does not replace the usage info. With longer profiling
sessions the script has to be run multiple times with `--append`. Also it
should be possible to change the number of samples.

**Comment by ToppingXu** [comment]
@pavel-kirienko I ran 10000 sample point, and there are some error point due to the screen lock process.
the attached is the svg file.

**Comment by pavel-kirienko** [comment]
@ToppingXu the image failed to attach properly. Try zipping it first.

**Comment by ToppingXu** [comment]
@pavel-kirienko [
[pmpn-flamegraph.svg.zip](https://github.com/PX4/Firmware/files/2272548/pmpn-flamegraph.svg.zip)

](url)

**Comment by davids5** [comment]
@pavel-kirienko @ToppingXu use `VERBOSE=1 make <target>` to see what options your build is built with.
 See the MakeFile for [VERBOSE](https://github.com/PX4/Firmware/blob/master/Makefile#L85)

**Comment by hamishwillee** [comment]
@pavel-kirienko Thanks for comment on docs above. I have added a new section on basic use, and pushed implementation section (detailed usage) to bottom. Assumption is that it is easier to set up and use the toolchain, and that people can try that quickly then move on to the more detailed usage. 

https://github.com/PX4/Devguide/pull/577

**Comment by pavel-kirienko** [comment]
@ToppingXu no, but we could use help with this: https://github.com/UAVCAN/libuavcan_stm32/issues/1

I don't have time to code that right now, but I would happily accept a pull request.

**Comment by ToppingXu** [comment]
@pavel-kirienko  You know I am a beginner on uavcan and was not able to change what you mentioned. Can you help when you have time.
