### ISSUE TITLE
Is altimeter (LidarLite) compensating the roll/pitch?

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#10195]
Is the estimation of the terrain altitude considering the attitude of the UAV?
Any pointer to the code?
What happen if I put the altimeter on a stabilized gimbal such that it always point downward?

**Comment by CarlOlsson** [comment]
> Is the estimation of the terrain altitude considering the attitude of the UAV?

Yes, it is [here](https://github.com/PX4/ecl/blob/master/EKF/terrain_estimator.cpp#L122)

> What happen if I put the altimeter on a stabilized gimbal such that it always point downward?

You will need to change the code to not account for the tilt angle

**Comment by mhkabir** [comment]
@tuloski please use the forum for further questions.

**Comment by MariliG** [comment]
Hey @tuloski I found your question very interesting, so I created a post on the forum [here](http://discuss.px4.io/t/is-altimeter-lidarlite-compensating-the-roll-pitch/7450).
