### ISSUE TITLE
GNSS: monitoring of satellite info

### ISSUE THREAD

**Issue by Kynos** [PX4/Firmware#1022]
New generations of GNSS potentially report a larger number of satellites, which exceeds the current structures.

MAX-M8 NAV-SVINFO has been observed to contain up to 49 sat blocks.

Sat monitoring data (strictly: data not required nor used for navigation) is currently located in two areas:

A) Parts of struct vehicle_gps_position_s, intermixed with data used for navigation. In particular, this struct contains 5 arrays with 20 entries each for sat id, "used/notused for nav", elevation, azimuth and SNR. Those arrays are indexed by their position in the last received NAV-SVINFO msg.

B) sdlog2 logging message structs log_GS0A_s, log_GS0B_s, log_GS1A_s and log_GS1B_s with 16 SNR values each. Those are indexed by the Sat ID (0..31) which is a GPS only concept and will not easily adapt for other GNSS sats with IDs up to 255.

**Comment by LorenzMeier** [comment]
@Zefz Position accuracy data might be interesting.

**Comment by Zefz** [comment]
This is already available on M8 gps using the PVT message types. I think for older Ublox versions one might have to enable a separate message (something like NAV-SOL for fix solution perhaps).

**Comment by LorenzMeier** [comment]
Closing, stale.
