### ISSUE TITLE
SITL default does not start with latest master

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#10228]
Starting SITL with 'make posix_sitl_ekf2 jmavsim' does not start SITL correctly on OSX.
Refer to the shell output below:

sitl_bin: /Users/ecmnet/PixHawk/src/Firmware/build/posix_sitl_ekf2/bin/px4
rcS_path: posix-configs/SITL/init/ekf2
debugger: none
program: jmavsim
model: none
src_path: /Users/ecmnet/PixHawk/src/Firmware
build_path: /Users/ecmnet/PixHawk/src/Firmware/build/posix_sitl_ekf2
**empty model, setting iris as default**
SITL COMMAND: /Users/ecmnet/PixHawk/src/Firmware/build/posix_sitl_ekf2/bin/px4 /Users/ecmnet/PixHawk/src/Firmware/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t /Users/ecmnet/PixHawk/src/Firmware/test_data
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
**Error: Unknown model 'iris'**
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
INFO [Unknown] Creating symlink /Users/ecmnet/PixHawk/src/Firmware/ROMFS/px4fmu_common -> /Users/ecmnet/PixHawk/src/Firmware/build/posix_sitl_ekf2/tmp/rootfs/etc

- - -

**Comment by dagar** [comment]
Thanks for reporting, things are going to be a little messy while the startup is unified across platforms.

Try `make posix_sitl_default jmavsim`. The per estimator targets will be gone soon. The posix_sitl_config config already contains all of them. https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d-posix/rcS#L65-L72

**Comment by ecmnet** [comment]
`make posix_sitl_default jmavsim` returns the same error, however.

**Comment by dagar** [comment]
Are you on a Mac? I tried it on Ubuntu. It looks like a problem with grep usage here https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d-posix/rcS#L44.

![image](https://user-images.githubusercontent.com/84712/44097014-c2ad4ee4-9faa-11e8-8837-006f0d43f9f1.png)

**Comment by ecmnet** [comment]
Yes, on a Mac...
