### ISSUE TITLE
SITL orb poll failing intermittently 

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#10220]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-nuttx_adc_dma/2/pipeline/55/
![image](https://user-images.githubusercontent.com/84712/44005185-45f52da4-9e3d-11e8-8211-17a3bfc807d5.png)

http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-nuttx_adc_dma/2/pipeline/57
![image](https://user-images.githubusercontent.com/84712/44005193-552c0ac2-9e3d-11e8-860c-eef17c15293e.png)

Plenty of other examples if you look under Firmware-SITL_tests (PX4 ROS mission tests) recent activity. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/activity

**Comment by dagar** [comment]
Possibly related https://github.com/PX4/Firmware/pull/10030

**Comment by LorenzMeier** [comment]
Can we please do all temp files if possible in working folder.

**Comment by dagar** [comment]
> @dagar do jenkins build run in parallel and is the /tmp directory shared between the instances?

No, to keep it simple it's always 1 job per machine.
