### ISSUE TITLE
Can we check GCC/compiler version in builds?

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#10239]
AFAIK we only "guarantee" against a particular version of GCC. It would be good if the toolchain could warn against incorrect GCC, and possible consequences.

In particular, I'm hoping that a warning might reduce the number of people who complain about FMUv2 out of flash issues because they aren't using the right version.

**Comment by dagar** [comment]
We could do this afternoon a toolchain update so that the actual GCC version will be known (major, minor, patch). 

That being said, I suspect people are going to miss/ignore the warning, and I think an actual failure would be too strict.

**Comment by hamishwillee** [comment]
Yes, a failure would be too strict. 

You're right that most people will miss the warning. Still, I tend to read through those things when things go wrong.

Up to you though.

**Comment by dagar** [comment]
Let's add the warning and see if anyone notices. The toolchain update here provides access to the compiler version. https://github.com/PX4/Firmware/pull/9808
