### ISSUE TITLE
snapdragon801  ERROR [Unknown] Error opening startup file, does not exist: etc/init.d/rcS

### ISSUE THREAD

**Issue by zhaoxiaowei1013** [PX4/Firmware#10244]
when  i run 
```
./px4 mainapp.config
```
```
INFO  [Unknown] Creating symlink mainapp.config -> /home/linaro/etc
ERROR [Unknown] Error opening startup file, does not exist: etc/init.d/rcS
```
```
-- PX4 VERSION: v1.8.0-879-g01744a9ef
-- CONFIG: posix_eagle_default
```

**Comment by yl5006** [comment]
this is PATH problem, relative path

**Comment by RomanBapst** [comment]
Maybe related to posix shell work of @bkueng

**Comment by RomanBapst** [comment]
https://github.com/PX4/Firmware/pull/10173

**Comment by bkueng** [comment]
> Maybe related to posix shell work of @bkueng

Correct. You need to make sure `${PX4_SOURCE_DIR}/ROMFS` is uploaded as well (here: https://github.com/PX4/Firmware/blob/master/platforms/posix/CMakeLists.txt#L49) and change the start command to something like `./px4 -s mainapp.config`
@zhaoxiaowei1013 @yl5006 can you try that?
@julianoes fyi

**Comment by zhaoxiaowei1013** [comment]
@bkueng  when i use ```./px4 -s mainapp.config```
it works ok, thanks.
