### ISSUE TITLE
Cannot control Set_position_target_local_ned.afx ，afy， afz ，alone

### ISSUE THREAD

**Issue by tonight123** [PX4/Firmware#10255]
**Describe the bug**
A clear and concise description of the bug.
Offboard cannot control AFX Afy AFZ alone, even if I force values in the code
if (!offboard_control_mode.ignore_acceleration_force) {
 pos_sp_triplet.current.acceleration_valid = true;
 pos_sp_triplet.current.a_x = 0.2;//set_position_target_local_ned.afx;
 pos_sp_triplet.current.a_y = 0.2;//set_position_target_local_ned.afy;
 pos_sp_triplet.current.a_z = 0.2;//set_position_target_local_ned.afz;
}
**To Reproduce**

1. Drone switched on '...'
1. Uploaded mission '....' (attach QGC mission file)
1. Took off '....'
1. See error

**Expected behavior**

**Log Files and Screenshots**
_Always_ provide a link to the flight log file:

* Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)).
* Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).

Add screenshots to help explain your problem.

**Drone (please complete the following information):**

* Describe the type of drone.
* Photo of the IMU / autopilot setup if possible.

**Additional context**

**Comment by mhkabir** [comment]
There is no acceleration control implemented currently.
