### ISSUE TITLE
U-blox GNSS: choice of Dynamic Platform Model

### ISSUE THREAD

**Issue by Kynos** [PX4/Firmware#1025]
U-blox GNSS and the PX4 driver allow selecting the Dynamic Platform Model. From the u-bloc specs:

> u-blox positioning technology supports different dynamic platform models (see table below) to adjust the navigation engine to the expected application environment. These platform settings can be changed dynamically without performing a power cycle or reset. The settings improve the receiver's interpretation of the measurements and thus provide a more accurate position output. Setting the receiver to an unsuitable platform model for the given application environment is likely to result in a loss of receiver performance and position accuracy.

Currently the Dynamic Platform Model is set to "Airborne <2g".

This mode was apparently chosen based on the u-blox specs mentioning "higher dynamics" for the airborne models.

Drawbacks of the airborne models, also based on the u-blox specs:

- altitude and velocity ranges: 10- to 100-fold above small UAV ranges

- sanity check type: Altitude only (Velocity not checked)

- max. position deviation: Large (less precision with the intent to filter out high process noise)

It might be beneficial to evaluate other Dynamic Platform Models to find out which one would be most appropriate to the Velocity and Precision requirements of small UAV, and especially to compare position noise in static hover and normal flight and also maximum lag of reported GNSS positions behind observed positions for fast/dynamic flight.

As the u-blov GNSS allows changing the Dynamic Platform Model setting at any time, it might even be worthwhile to switch models for the current flight situation (for example, fast flight or static precision hover).

**Comment by LorenzMeier** [comment]
Closing, as we're running fine right now.
