### ISSUE TITLE
How to launch a command or a module with mavlink/mavros?

### ISSUE THREAD

**Issue by MatteoTadiello** [PX4/Firmware#10269]
How can I use an external offboard ros program to launch a personal module to the AUV?
I have created a module and I need to use it with multiple drones so i have to run this module in all the drones, how can I do this? 
Do I need an external offboard program that send the command to all the drones or is better to run this module in another way?

**Comment by hamishwillee** [comment]
Hi Matteo,

This system is for firmware bugs and enhancement, not "help". Please repost on the discussion forums: http://discuss.px4.io/c/software-development

You might also want to look at the documentation: http://dev.px4.io/en/ros/ - there is some information about multi-drone setups.
