### ISSUE TITLE
NXPhlite: firmware not uploading starting from commit c2fcef8

### ISSUE THREAD

**Issue by Nielesonimusso** [PX4/Firmware#10309]
Using QGroundControl (Daily Build version `c7a171eb0 2018-08-21 20:40:28 -0400`), I have been unable to fully upload the PX4 firmware while building from a commit later than d0f733d (so the issue starts at commit c2fcef8). When I attempt to upload, the verification step fails with a CRC mismatch, resulting in the following log (when uploading a build of c2fcef8):

    QGroundControl can upgrade the firmware on Pixhawk devices, SiK Radios and PX4 Flow Smart Cameras.
    Plug in your device via USB to start firmware upgrade.
    Found device: PX4 NXPHlite v3.x
    Connected to bootloader:
    Version: 5
    Board ID: 28
    Flash size: 2072576
    Downloading firmware...
    From: /home/niels/src/Firmware/build/nuttx_nxphlite-v3_default/nxphlite-v3_default.px4
    Download complete
    MAV_AUTOPILOT = 12
    Successfully decompressed parameter_xml
    Successfully decompressed airframe_xml
    Successfully decompressed image
    Erasing previous program...
    Erase complete
    Programming new version...
    Program complete
    Verifying program...
    Error: CRC mismatch: board(0x47ab3584) file(0xf902b46f)
    Upgrade cancelled

**Comment by dagar** [comment]
@Nielesonimusso this should be resolved by https://github.com/PX4/Firmware/commit/790356ef6ddd54b002e4d887a6872fbd270020e1

Could you retest?

**Comment by Nielesonimusso** [comment]
Sorry, haven't updated this issue yet. Indeed, the issue is solved by this commit!
