### ISSUE TITLE
Control AUX outputs directly

### ISSUE THREAD

**Issue by malik-aliyev-94** [PX4/Firmware#10335]
Hi. We have posted a topic on discuss.px4.io. We also wrote to slack, but did not get answer. 
The topic is: http://discuss.px4.io/t/create-software-to-control-camera-gimbal/7621

We want to develop a software, that able to control camera and gimbal. We are able to control only yaw and pitch now using vmount and dronecore sdk.

We want to control zoom and auto tracking also, but we are not able to do that. The questions are:
The main question is how to control AUX outputs directly. E.g. use aux4 output to control zoom of the camera.

1. Can we use more than 2 aux outputs to control camera & gimbal (by pwm signal)
2. What do you mean under "We ONLY support trigger on pins 5 and 6 when simultanously using AUX for actuator output" ?
3. How can we send a command to desired aux output ? e.g. Use aux4 output to control zoom of the camera.
It is very important to get quick reply, we rely on your support ! 
Thanks !

**Comment by hamishwillee** [comment]
I have attempted to answer this in your discussion board post
