### ISSUE TITLE
Battery ADC parameters default values always overridden

### ISSUE THREAD

**Issue by nslogan** [PX4/Firmware#10344]
**Describe the bug**

The following parameters are impacted by this behavior:

* BAT_A_PER_V
* BAT_CNT_V_CURR
* BAT_CNT_V_VOLT
* BAT_V_DIV

All of these parameters have a default value of "-1.0"; however, the firmware overrides this value and instead substitutes the board default. In QGroundControl, after resetting all parameters, these parameters appears in red to indicate they are of non-default value.

**To Reproduce**

This was discovered on a PixHawk 2 Cube running PX4 1.8.0 (release).

1. Connect to PixHawk via QGroundControl
1. Navigate to Vehicle Setup page
1. Tools > Reset all to defaults > Reset
1. Check Battery Calibration page
1. The four parameters listed above are red, having been set to the board default by the firmware

Alternatively:

1. Connect to PixHawk via QGroundControl
1. Navigate to Vehicle Setup page
1. Attempt to set BAT_A_PER_V to "-1.0" or click "Reset to default"
1. The parameter appears unchanged, remaining at the board default of "15.39103031"

**Expected behavior**

This may be the expected behavior; however, this is not very clear [per the documentation](https://dev.px4.io/en/advanced/parameter_reference.html#BAT_A_PER_V). Additionally, this behavior prevents future updates to the default value from happening because the value of "-1.0" has been cleared. The firmware does not provide feedback that this is happening, which is also confusing, given that the documentation does not provide a valid range for this parameter (e.g. 0 > MAX_VALUE).

**Log Files and Screenshots**

![image](https://user-images.githubusercontent.com/1211698/44682079-438b0280-a9f7-11e8-92e6-81c240042b42.png)

This was discovered on a PixHawk 2 Cube running PX4 1.8.0 (release).

**Additional context**

I have located in the firmware where these values are being overridden: `/src/modules/sensors/parameters.cpp`

For example, here is where `BAT_CNT_V_CURR` is overridden.

```c
// 96443b3:/src/modules/sensors/parameters.cpp:389
/* scaling of ADC ticks to battery current */
if (param_get(parameter_handles.battery_current_scaling, &(parameters.battery_current_scaling)) != OK) {
PX4_WARN("%s", paramerr);

} else if (parameters.battery_current_scaling < 0.0f) {
/* apply scaling according to defaults if set to default */
parameters.battery_current_scaling = (3.3f / 4096);
param_set_no_notification(parameter_handles.battery_current_scaling, &parameters.battery_current_scaling);
}
```

**Comment by dagar** [comment]
Thanks for raising the issue with details. We need some other mechanism for overriding these defaults.

Expanding on this https://github.com/PX4/Firmware/blob/master/cmake/configs/nuttx_px4fmu-v2_lpe.cmake#L3 with a cleaner interface could work.
