### ISSUE TITLE
Mavlink v1/v2 autonegotiate with Sik radio review

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#10358]
Should mavlink (PX4 + QGC) automatically select v1 in the presence of an older Sik radio that doesn't support mavlink v2?

I've been seeing a lot of logs from setups with Sik radios that are missing RADIO_STATUS and in v2 mode, resulting in poor performance.

@bkueng @DonLakeFlyer @LorenzMeier any input?

**Comment by DonLakeFlyer** [comment]
It should already do that. @LorenzMeier Implemeneted a while ago. I not fully up to date on how it works. Basics are it sends a mavlink 2 ping type of message to the radio. if the radio responds it supports 2 if not, it doesn.t. Then QGC uses that to determine what to do with the connection.

**Comment by dagar** [comment]
Then it appears to not be working.

**Comment by hamishwillee** [comment]
@dagar Docs for what is supposed to happen for [SiK here](https://mavlink.io/en/guide/mavlink_version.html#semi-transparent-legacy-radios)

**Comment by LorenzMeier** [comment]
@dagar Did you update your SiK radios via QGC? Watch the firmware URL, it should come off the PX4 AWS bucket.

**Comment by dagar** [comment]
Yes I've updated mine, but it's the large existing user base I'm worried about.
