### ISSUE TITLE
SITL test intermittent failures

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#10352]
The SITL mission tests are periodically failing due to anomalies detected by the ecl analysis script. FW is the most frequent, but VTOL is also failing.

https://logs.px4.io/plot_app?log=88a0abf0-78bf-430b-8867-5821e8595f76
![image](https://user-images.githubusercontent.com/84712/44729947-de461880-aaad-11e8-9379-4735065ee985.png)

http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-vehicle_trajectory_waypoint-limit/6/pipeline

Do we need to relax the script or is this something that should be adjusted in the gazebo models?

**Comment by dagar** [comment]
More examples
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/94/pipeline/
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/92/pipeline/
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/88/pipeline

**Comment by dagar** [comment]
- http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-10179/12/pipeline

**Comment by priseborough** [comment]
The high frequency accel noise appears high relative to what we see on most flight vehicles, but I was able to find a vehicle log with equivalent levels. I will raise a PR to adjust the thresholds and also improve the analysis script message to indicate which quantity has failed.

HF accel vibe from sim log

![hf accel sim](https://user-images.githubusercontent.com/3596952/44817855-20946480-ac2a-11e8-9c40-9b569ff8b31d.png)

HF accel vibe from flight log

![hf accel flight](https://user-images.githubusercontent.com/3596952/44817873-3b66d900-ac2a-11e8-9916-031e7c46cddf.png)

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/Firmware/pull/10366
