### ISSUE TITLE
Make command on Macbook Pro 2018 with macOS High Sierra 10.13.6 doesn't work

### ISSUE THREAD

**Issue by LeoMustafaNXP** [PX4/Firmware#10368]
**Describe the bug**
I try to build the nxphlite Firmware on a MacBook Pro 2018 with macOS High Sierra 10.13.6.
I get the following bug.

`LeoMacBookPro:Firmware leutrimmustafa$ make nxphlite-v3_default
ninja: Entering directory /Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default
[249/874] ROMFS: copying extras
FAILED: ROMFS/romfs_extras.stamp 
cd /Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default/ROMFS && /usr/local/Cellar/cmake/3.12.1/bin/cmake -E make_directory /Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default/genromfs/extras/ && /usr/local/Cellar/cmake/3.12.1/bin/cmake -E copy_directory /Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default/romfs_extras/ /Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default/genromfs/extras/ && /usr/local/Cellar/cmake/3.12.1/bin/cmake -E touch romfs_extras.stamp
Error copying directory from "/Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default/romfs_extras/" to "/Users/leutrimmustafa/Desktop/PX4/Firmware/build/nuttx_nxphlite-v3_default/genromfs/extras/".
[262/874] Generating nuttx/drivers/libdrivers.a
ninja: build stopped: subcommand failed.
make: *** [nxphlite-v3_default] Error 1
LeoMacBookPro:Firmware leutrimmustafa$ `

**Software versions**
- cmake version 3.12.1
- GNU Make 3.81
- PX4 Firmware from the master branch 
- MacBook Pro 2018 (15-inch) with macOS High Sierra 10.13.6

thank you for your support.

**Comment by LorenzMeier** [comment]
@davids5

**Comment by tops4u** [comment]
I just tested this (slightly different HW though). 

- MacBookPro 13" 2017 (Modell 14,1)
- cmake version 3.10.0
- GNU Make 3.81
- Latest Master from today

Make Output: 
```
-- PX4 VERSION: v1.8.0-1061-g924611016
-- CONFIG: nuttx_nxphlite-v3_default
-- Build Type: MinSizeRel
(...)
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/bin/arm-none-eabi-gcc
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Found PY_jinja2: /Library/Python/2.7/site-packages/jinja2  
-- C compiler: arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
-- C++ compiler: arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
-- PX4 ECL: Very lightweight Estimation & Control Library v0.9.0-583-g56b8bb0
-- Using C++11
(....)
```

Works like a charm.

**Comment by reddigfabian** [comment]
Having the same exact issue as @LeoMustafaNXP with same exact specs/versions.

**Comment by fredowski** [comment]
Hi, I have the same problem when running `make px4fmu-v4_default` with this setup
  * MacOS 10.13.6
  * cmake 3.12.1
  * make 3.81

The release notes for cmake 3.12 

https://cmake.org/cmake/help/v3.12/release/3.12.html#id1

say that `cmake copy_diretory` now fails when the source directory does not exist. The previous behavior was that the target directory was created empty.

**Comment by reddigfabian** [comment]
Looks like downgrading cmake solves this issue. Not yet tested to see if the firmware is fully functional

**Comment by fredowski** [comment]
I tried to build with cmake 3.11.4 and then the build works.

**Comment by fredowski** [comment]
With the following patch I can build also with cmake 3.12.1:

```
diff --git a/ROMFS/CMakeLists.txt b/ROMFS/CMakeLists.txt
index 94cd9cf98..ff489d62b 100644
--- a/ROMFS/CMakeLists.txt
+++ b/ROMFS/CMakeLists.txt
@@ -105,7 +105,7 @@ endif()
 
 add_custom_command(OUTPUT romfs_extras.stamp
        COMMAND ${CMAKE_COMMAND} -E make_directory ${romfs_gen_root_dir}/extras/
-       COMMAND ${CMAKE_COMMAND} -E copy_directory ${PX4_BINARY_DIR}/romfs_extras/ ${romfs_gen_root_dir}/extras/
+       COMMAND if [ -d  ${PX4_BINARY_DIR}/romfs_extras ]; then  ${CMAKE_COMMAND} -E copy_directory ${PX4_BINARY_DIR}/romfs_extras/ ${romfs_gen_root_dir}/extras/ \; fi
        COMMAND ${CMAKE_COMMAND} -E touch romfs_extras.stamp
        DEPENDS
                ${romfs_gen_root_dir}/init.d/rcS
```

**Comment by mhkabir** [comment]
@fredowski Can you please send a PR with that patch? Thanks!
