### ISSUE TITLE
SITL with Gazebo and ROS does not receive data

### ISSUE THREAD

**Issue by christiansprecher** [PX4/Firmware#10370]
When launching SITL in Gazebo with a ROS wrapper, it does not receive data over the UDP port.
I followed the last part of the [tutorial](https://dev.px4.io/en/simulation/ros_interface.html) (section What's Happening Behind the Scenes).

When running `no_sim=true make posix_sitl_default gazebo` and `roslaunch gazebo_ros empty_world.launch world_name:=$(pwd)/Tools/sitl_gazebo/worlds/iris.world`, the first terminal stops at 

`INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..`

When running `make posix_sitl_default gazebo`, everything works as expected.
This occurs on the master branch as well as on the releases v1.8.0 until v1.7.0-rc0. The last working version is release v1.6.5. 

System:
Ubuntu 16.04
Gazebo 7.14
Mavros and Mavlink newest version from Github
PX4 Release 1.7.0 and later

**Comment by dagar** [comment]
Once this is fixed let's get a simple ROS test in CI to keep it working.

FYI @TSC21 @lamping7
