### ISSUE TITLE
EKF2 Rejecting Rangefinder

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#10390]
@priseborough After some more investigation of the optical flow issues I was having, I tracked them down to the `distance_bottom` estimate. I am using a TFMini rangefinder, which initially had some driver issues, which I fixed here : https://github.com/PX4/Firmware/pull/10319. There may be additional issues, but they aren't obvious from visually inspecting the data.

The EKF still doesn't seem to like the rangefinder data. As soon as the vehicle is armed and takes off, the terrain estimate goes invalid.

Here is a log (from boot) : https://logs.px4.io/plot_app?log=26e73c13-304d-497a-8d48-19b8c3b35f63
My branch is off v1.8 Stable, and should work with replay.

@Antiheavy FYI.

**Comment by mcsauder** [comment]
@dakejahl

**Comment by mhkabir** [comment]
Fixed on ecl master by : https://github.com/PX4/ecl/commit/a7245229cbc3916f66be9d948875ff019dc41d5f
