### ISSUE TITLE
[Intel Aero]: Arms but non responsive attitude

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#10406]
booted, waited for about 2 minutes, successfully armed and motors spun up to idle but copter non responsive to throttle input

https://logs.px4.io/plot_app?log=12385dd2-7b2a-4cff-a7b7-711d50a7a270
https://logs.px4.io/plot_app?log=332bc3b6-2bae-4503-95b2-b4dadda12d42

seeing errors in log [mc_pos_control] Stabilized-Ctrl failed with error: Activation Failed

**Comment by bkueng** [comment]
The log doesn't contain any baro data. Do you have another Aero that you can cross-test?

**Comment by dagar** [comment]
@santiago3dr when were you last able to fly this vehicle? Do you have the log?

**Comment by santiago3dr** [comment]
flashed todays master 33e68b3 and had the same non responsive throttle on the first attempt:
https://logs.px4.io/plot_app?log=4bbc9f6f-74d4-4a7d-bb35-116469d99ba5

ran a few power cycles and got it to work
https://logs.px4.io/plot_app?log=469b7600-3554-414f-bce2-7dbfe9d2e69c

no error messages on qgroundcontrol on unresponsive nor on successful flight
