### ISSUE TITLE
Navigator: Land/RTL quad flys towards home lat/lot/alt

### ISSUE THREAD

**Issue by dakejahl** [PX4/Firmware#10412]
**Describe the bug**
Auto modes `land` and `rtl` cause quad to fly directly towards home lat/lon/alt. This is the third time I've seen this in two weeks. I've seen it ~10 times since the introduction of FlightTasks. We are flying ~7 hours a week, so this is a very rare edge case bug. Logging either dies completely or drops out when this happens. I finally have a partial log (2 minute long dropout) of a flight where this happened. 

**To Reproduce**
1. Takeoff using mode `takeoff`
2. Fly around in position mode
3. Issue `land` or `rtl`
4. This behavior will persist through a land/disarm/arm/takeoff

**Log Files and Screenshots**
https://review.px4.io/plot_app?log=7955d3de-31c9-4434-b30d-cb31fadefb32

**Additional context**
I am pretty sure `takeoff` is causing the bug. I am fairly certain `navigator` gets stuck in a loop somewhere, this would explain the logger dropouts due to thread starvation (navigator priority is higher than logger). I am guessing all `auto` modes will cause this, we only use `land` and `rtl`, but both of those modes do the same thing, fly right towards home.

**Comment by dagar** [comment]
I missed the comment about logging dying when you described this earlier. Does that happen 100%?

**Comment by dagar** [comment]
@bkueng any thoughts on the logger dropout?

**Comment by dakejahl** [comment]
@dagar This is the first time we have gotten a log from a flight with this bug. All of the other flights where this bug popped up the log has either been missing completely, the file is corrupted, or the log just ends immediately after `takeoff`.

**Comment by dakejahl** [comment]
![selection_001](https://user-images.githubusercontent.com/37091262/45047802-54f78e80-b037-11e8-9363-90e8573e1f01.png)

**Comment by dakejahl** [comment]
logger_sd_write has pretty much the same max loop time as navigator (70ms difference)

**Comment by bkueng** [comment]
Can you try with a different [SD card](https://dev.px4.io/en/log/logging.html#sd-cards)? Which one are you using at the moment?

**Comment by dakejahl** [comment]
We're using https://www.oempcworld.com/mm5/merchant.mvc?Screen=PROD&Product_Code=500303&Store_Code=oem&gclid=EAIaIQobChMIsYGl252k3QIVnEwNCh1RlgSFEAYYASABEgLFSvD_BwE

I can get a different SD card and test this... Are you thinking maybe `navigator` is attempting to read a mission that isn't there or something of that nature?

**Comment by dakejahl** [comment]
Haven't seen this since September, FlightTasks has seen lots of good work since then. Closing this.
