### ISSUE TITLE
External compass not detected from time to time

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#1045]
John Brown reported issues with external compass detection on Pixhawk
(https://groups.google.com/forum/#!topic/px4users/oSryUMyXuj0)

I checked his logs and can confirm that internal compass was used in "bad" flight (large interference with power lines and completely wrong calibration). John, please provide more details: compass model, boot logs from SERIAL5.

**Comment by LorenzMeier** [comment]
We have the compass ID implemented by now. Just need to store this during calibration as parameter and we're good.

**Comment by LorenzMeier** [comment]
Implemented partially here, handled now in QGC: https://github.com/mavlink/qgroundcontrol/issues/1427
