### ISSUE TITLE
about baudrate of serial

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#10450]
I want to control the telem 1 to stop sending mavlink message,I want telem 1 to output the message that is Custom-Defined.And how do I do to config the baudrate of serial4/5?

**Comment by julianoes** [comment]
May I ask what piece of hardware you are referring to? That way we can figure out what your requests map to in code.

**Comment by roseyangyu** [comment]
I used pixhawk 2,I want to config telem1 and serial4/5.I hope the telem1 don't output mavlink so much so that I can make it output the message that is I need.And the baudrate of serial4/5 how to config?

**Comment by roseyangyu** [comment]
In  QGC ,I can't fiind the parameter to config that

**Comment by bkueng** [comment]
FYI this will make the UARTs configurable: https://github.com/PX4/Firmware/pull/10337

**Comment by roseyangyu** [comment]
I‘m exciting very much! Thank you very much! @julianoes and @bkueng

**Comment by roseyangyu** [comment]
but I have not rc.mavlink. I use v1.8.0.

**Comment by julianoes** [comment]
> but I have not rc.mavlink. I use v1.8.0.

Same thing there:
https://github.com/PX4/Firmware/blob/v1.8.0/ROMFS/px4fmu_common/init.d/rcS#L604

**Comment by roseyangyu** [comment]
I have  config UART7 and UART8 to 115200,but It seems that the baud rate has not changed.It still is 57600.

**Comment by roseyangyu** [comment]
config telem1 sucessfully! thank you again

**Comment by julianoes** [comment]
@roseyangyu have you done a `make clean` after changing the defconfig?

**Comment by roseyangyu** [comment]
oh i'm sorry.thank you very much
