### ISSUE TITLE
NXPhlite - PWM output does not change after arming

### ISSUE THREAD

**Issue by dk7xe** [PX4/Firmware#10469]
**Describe the bug**
PWM output does not change after arming. Motors don't spin.

**To Reproduce**
1. Power up Hovergames drone
1. press safety switch
3. arm

**Expected behavior**
Motors spin with minimum throttle setting

**Log Files and Screenshots**
![pwm_info](https://user-images.githubusercontent.com/3907200/45430241-45b2b980-b6a5-11e8-83e4-0d41cc06ad2e.jpg)

**Drone (please complete the following information):**
- NXP Hovergames drone
- NXPhlite rev B
- master branch as of 5th of September

**Additional context**
na

**Comment by LorenzMeier** [comment]
@bkueng Could you please have a quick look?

**Comment by Nielesonimusso** [comment]
same issue as #10318

**Comment by lericson** [comment]
This is also a dup of #10457

**Comment by lericson** [comment]
Which I by the way show the error and a fix in

**Comment by dk7xe** [comment]
It is working now with `ce31a4` from git.
![capture](https://user-images.githubusercontent.com/3907200/45670106-3b1f7680-bb22-11e8-9583-2566bc3ccf37.PNG)
