### ISSUE TITLE
Standard VTOL gazebo simulation goes wild

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#10471]
**Problem:**
After doing a make clean simulation works. It does not work anymore if you try to run it a second time without a make clean in between. This time it will go wild right after arming.

**Steps to reproduce**

```
make clean
make posix_sitl_default gazebo_standard_vtol
```

quit the app

`make posix_sitl_default gazebo_standard_vtol`

arm the drone and see it going wild

**Comment by MatejFranceskin** [comment]
This commit caused the regression:
SITL: move all models to unified rcS startup and remove old scripts
https://github.com/PX4/Firmware/commit/273988c124d68031c300dcdcac1c4b4150d432de
