### ISSUE TITLE
POSIX_SITL Bug - Symbol Lookup Error [UPDATE]

### ISSUE THREAD

**Issue by shreks7** [PX4/Firmware#10487]
**Describe the bug**
Downloaded the latest Firmware
Tried running
`make posix_sitl_default gazebo`

Gazebo crashes with the error - 

> gzserver: symbol lookup error: /usr/lib/x86_64-linux-gnu/gazebo-7.0/plugins/libgazebo_gps_plugin.so: undefined symbol: _ZN8gps_msgs4msgs7SITLGpsC1Ev

PX4 keeps waiting for the UDP port 14560

I am running
Gazebo-7 (that comes with ROS)
Ubuntu 16.04

**Comment by shreks7** [comment]
Reinstalling Gazebo fixed the problem.

**Comment by fabrizioschiano** [comment]
@shreks7 I know it is a long time ago but could you detail a bit more what did you do to _reinstall gazebo_ ? 

Thanks!
