### ISSUE TITLE
NXPHlite - Drotek Sirius compass not support

### ISSUE THREAD

**Issue by dk7xe** [PX4/Firmware#10496]
**Describe problem solved by the proposed feature**
For robodronerace mid of October in Rapperswil NXP hovergames drones will be used with NXPhlite und Drotek Sirius RTK GPS - https://drotek.com/shop/en/u-blox/856-sirius-gps.html
LIS3MDL magnetometer of Sirius GPS is not recognized by current FW in master for NXPhlite.

**Describe your preferred solution**
Enable support of LIS3MDL magnetometer

**Additional context**
Internal MAG can not be used due to spikes on z axis.

![capture](https://user-images.githubusercontent.com/3907200/45618509-3c936500-ba76-11e8-90ec-e26005dd9ce9.PNG)

**Comment by dk7xe** [comment]
Compass is working now. Thank you!
![capture](https://user-images.githubusercontent.com/3907200/45669815-740b1b80-bb21-11e8-9424-e50406158529.PNG)

**Comment by davids5** [comment]
Fixed in  #10500
