### ISSUE TITLE
NXPhlite - FW update via GQC does not work

### ISSUE THREAD

**Issue by dk7xe** [PX4/Firmware#10507]
**Describe the bug**
FW update of NXPhlite is cancelled with error `Error: Sync: Send Command: Invalid sync response: 0xfe 0x3e`
![capture](https://user-images.githubusercontent.com/3907200/45667784-d280cb80-bb1a-11e8-81b6-06abf5b936ba.PNG)

**To Reproduce**
1. Start QGC and go to Firmware
2. plug NXPhlite in via USB
3. See error 

**Expected behavior**
FW update process starts

**Drone (please complete the following information):**
- NXP Hovergames drone
- NXPhlite rev B 

**Additional context**
Operating System is Windows 7
QGC nightly dd2ec from 2018-09-10 17:39:45 -0400
NXPhlite bootloader as of 2018-09-04
px4fmu.inf adjusted to detect NXPhlite
[px4fmu.zip](https://github.com/PX4/Firmware/files/2391401/px4fmu.zip)

As workaround FW flashing via segger tool to 0x6000 is still possible.

**Comment by dk7xe** [comment]
With latest QGC version db73c 2018-09-17 16:22:47 -0400 the error is
`Error: Sync: Send Command: Get Command Response: Timeout waiting for bytes to be available`
![capture](https://user-images.githubusercontent.com/3907200/45669273-d6631c80-bb1f-11e8-96a6-37c5a48237f1.PNG)

**Comment by LorenzMeier** [comment]
This needs to be in the px4driver.msi which needs to be signed - but we don't have the tooling for that in the repo. We will need to re-create that.

**Comment by LorenzMeier** [comment]
Starting point: https://docs.microsoft.com/en-us/windows/desktop/msi/windows-installer-examples

**Comment by jarivanewijk** [comment]
The Windows driver that's installed with the latest daily build of QGC still doesn't work. What's the current status of the driver? It's a bit unclear because the other issue was closed?

**Comment by inezbangar** [comment]
I am having a similar problem when trying to update the Pixhawk 1. Is there a way to get around this or fix it?

**Comment by jarivanewijk** [comment]
This should be almost fixed in QGroundControl daily build: https://github.com/mavlink/qgroundcontrol/issues/7360

The bootloader has been updated by David Sidrane. PX4 builds for FMUK66 are available in the build system. QGC has been updated to detect FMUK66 and has the right firmware URLs. Only thing left is the integration into the px4driver.msi, the right definitions were added to the drivers at Mission Planner but still have to be pulled into QGC as far as I know. 

However, the PX4 side should be ready.

**Comment by jarivanewijk** [comment]
This is fixed now. QGroundControl 3.5.4 supports FMUK66 and with a recent bootloader FW update should work just fine.

**Comment by dk7xe** [comment]
This issue can be closed
