### ISSUE TITLE
Quadcopter PID Tuning

### ISSUE THREAD

**Issue by RR2-IP2** [PX4/Firmware#10504]
Hi,

I am attempting to follow the [PX4 PID Tuning Guide](https://docs.px4.io/en/advanced_config/pid_tuning_guide_multicopter.html), however, I am not sure how to recreate the log plots shown in the guide.

The only plot even roughly close to this that I know how to get is using the Analyze widget in QGroundControl, but I don't know how to find the yaw/pitch/roll setpoint data.  Without the setpoint data, the plots will be significantly less useful in the tuning process. 

I am new to drone development so I am sorry if this is a very fundamental question.  Any help would be greatly appreciated!

Thanks in advance,
Justin

**Comment by bkueng** [comment]
Hi Justin

The plots are from [flight review](http://review.px4.io), an online log analysis tool. See https://docs.px4.io/en/getting_started/flight_reporting.html.

**Comment by RR2-IP2** [comment]
Perfect, thank you @bkueng

**Comment by bkueng** [comment]
Closing it then.
