### ISSUE TITLE
logger Check assertion failure for other ramification.

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#10518]
**Describe the bug**

I found this on NXPHlite-v3 while debugging hardfaults. 

**Assertion failed at file:semaphore/sem_holder.c line: 915 task: logger**

This needs to be checked, it may be nothing because there is a reboot.

![image](https://user-images.githubusercontent.com/1945821/45721254-2e1f7900-bb5c-11e8-875f-42ffdfccf52f.png)

**To Reproduce**
1. Enable CONFIG_DEBUG_FEATURES and CONFIG_DEBUG_ASSERTIONS
```
-# CONFIG_DEBUG_FEATURES is not set
+CONFIG_DEBUG_FEATURES=y
+
+#
+# Debug SYSLOG Output Controls
+#
+CONFIG_DEBUG_ERROR=y
+CONFIG_DEBUG_INFO=y
+# CONFIG_DEBUG_WARN is not set
+CONFIG_DEBUG_ASSERTIONS=y
```
2. type reboot on console
3. See error
*I had to remove the DBUGASSERTS in the gpio driver to get the system running.

**Expected behavior**
This may be fine as the reset will clean up the system.

**Comment by davids5** [comment]
These needed removal to test as they art overzealous
```
diff --git a/arch/arm/src/kinetis/kinetis_pingpio.c b/arch/arm/src/kinetis/kinetis_pingpio.c
index b887920816..76abf0db53 100644
--- a/arch/arm/src/kinetis/kinetis_pingpio.c
+++ b/arch/arm/src/kinetis/kinetis_pingpio.c
@@ -69,9 +69,6 @@ void kinetis_gpiowrite(uint32_t pinset, bool value)
   unsigned int port;
   unsigned int pin;
 
-  DEBUGASSERT((pinset & _PIN_MODE_MASK) == _PIN_MODE_GPIO);
-  DEBUGASSERT((pinset & _PIN_IO_MASK) == _PIN_OUTPUT);
-
   /* Get the port number and pin number */
 
   port = (pinset & _PIN_PORT_MASK) >> _PIN_PORT_SHIFT;
@@ -113,8 +110,6 @@ bool kinetis_gpioread(uint32_t pinset)
   unsigned int pin;
   bool         ret = false;
 
-  DEBUGASSERT((pinset & _PIN_MODE_MASK) == _PIN_MODE_GPIO);
-  DEBUGASSERT((pinset & _PIN_IO_MASK) == _PIN_INPUT);
 
   /* Get the port number and pin number */
 

```

**Comment by bkueng** [comment]
A quick code inspection did not reveal anything: waiting threads are woken up and stopped before a semaphore/mutex is destroyed.
Could it be that you ran in a timeout due to the debugging?

**Comment by davids5** [comment]
@bkueng - Thanks for looking.

> Could it be that you ran in a timeout due to the debugging?

I do not think so. I can have a closer look after I figure out the hard fault from hell!

**Comment by julianoes** [comment]
@davids5 what's the status here?

**Comment by davids5** [comment]
@julianoes - there was a recent change in nuttx that should be back ported. It fixes this.  It is it a super low priority and we will get it on the next uptake. So let's close this unless it is getting in someone else's way.
