### ISSUE TITLE
[vio-pipeline] Add vision velocity estimation fusion to EKF2

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#10512]
**Purpose:** Get full use of the odometry pipeline by adding linear and angular velocity fusion to EKF2.

**Concerns:** @priseborough maybe you want to add some details on how can this be achieved?

**Comment by TSC21** [comment]
@mhkabir FYI.

**Comment by TSC21** [comment]
@jkflying FYI

**Comment by v01d** [comment]
Hi, having this issue open means that currently the odometry message does not fuse the velocity? 
Also, is it possible/planned to support velocity-only vision estimate input so that velocity-only offboard control is performed?

**Comment by v01d** [comment]
Now that 1.9.0 is close to being released I would like to re-ask my previous question, in case situation is different. I'm trying the RC and it would seem that the velocity component from the odometry from VIO is not used. Is this supported in any other way?

**Comment by TSC21** [comment]
> Now that 1.9.0 is close to being released I would like to re-ask my previous question, in case situation is different. I'm trying the RC and it would seem that the velocity component from the odometry from VIO is not used. Is this supported in any other way?

Still open for development. If you feel you can give a contribution, I will be happy to review and bring others to take a look as well.

**Comment by TSC21** [comment]
> so that velocity-only offboard control is performed?

Note: this has nothing to do with the fact that EKF2 fuses vision velocity estimates or not. You can use velocity control by closing the loop on the offboard side (knowing the position).

**Comment by TSC21** [comment]
Still relevant

**Comment by mhkabir** [comment]
Fixed.
