### ISSUE TITLE
mpu9250 in px4fmu-v2

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#10521]
Do we support any px4fmu-v2 derivatives that have an mpu9250 and can't be "upgraded" to px4fmu-v3 (bootloader update)?

Unless there's a good example I propose we disable the mpu9250 in px4fmu-v2 to save about 11 kB of flash and find a way to painlessly get any affected users through the bootloader update (QGC prompt to set SYS_BL_UPDATE).

https://github.com/PX4/Firmware/pull/10355#issuecomment-422597424
https://github.com/PX4/Firmware/pull/10519

**Comment by bkueng** [comment]
> Do we support any px4fmu-v2 derivatives that have an mpu9250 and can't be "upgraded" to px4fmu-v3 (bootloader update)?

I don't know of any boards.
Now that we have the BL update we can also start thinking about removing the VTOL modules for example.

**Comment by davids5** [comment]
>Do we support any px4fmu-v2 derivatives that have an mpu9250 and can't be "upgraded" to px4fmu- > (bootloader update)?

RE: bootloader update:
The bootloader for fmuv3 and fmuv2 are **now** EXACTLY the same. @LorenzMeier created the V3 bootloader build to avoid the "Where the V3 bootloader question" Originally it did not do the silicon check, but it does now.

**Comment by tubeme** [comment]
We have such a board! awav/mro X2.1 arhitechture is v2+ mpu9250. But I think there could be some optimization. Can we put the v3 bootloader to our board? 

We still have this pending https://github.com/PX4/Firmware/pull/8138, with regard to the boot scripts.

**Comment by bkueng** [comment]
@tubeme you can update the BL, instructions are here: https://docs.px4.io/en/advanced_config/bootloader_update.html, and then check if you can flash the v3 target.

**Comment by tubeme** [comment]
Thanks @bkueng I have a problem following this manual. My board is AUAV X2.1 and in the master firmware there is no SYS_BL_UPDATE. Is there a BIN version somewhere so I can flash with JTAG? The chip is  STM32F427 Cortex M4 with FPU
168 MHz/256 KB RAM/2 MB Flash so for sure it has 2MB flash.

**Comment by bkueng** [comment]
Ah I see. The AUAV X2.1 has a different build target and thus is not affected by this.

**Comment by tubeme** [comment]
Yes and ur chip is rev.3 so the new bootloader should work.

**Comment by davids5** [comment]
AUAV X2.1 has its own bootloader. https://github.com/PX4/Bootloader - do not use the V2 or V3 bootloader on the AUAV X2.1. The AUAV X2.1 is not compatible with FMUv2 it has hardware differences that will cause the board not to function (inputs on V2 are used as outputs on the X2.1) So you must uses the correct bootloader so it loads the correct FW.  

See https://docs.px4.io/en/flight_controller/mro_x2.1.html and follow the instructions there.
