### ISSUE TITLE
Error building Copter: uavcangen returned 1 error code

### ISSUE THREAD

**Issue by icoblue** [PX4/Firmware#10546]
**Been trying to find a way to build on Windows for three days now and so far none of the dev wiki documentation or any of the videos or any of the tutorials help. I am building using Cygwin and pixhawk toolchain.

I have made it all the way to a valid configure, with results as below:**

_XYZ@DESKTOP-XYZ36E4 /cygdrive/d/ardupilot
$ ./waf configure --board px4-v2
Setting top to                           : /cygdrive/d/ardupilot
Setting out to                           : /cygdrive/d/ardupilot/build
Autoconfiguration                        : enabled
Setting board to                         : px4-v2
Checking for program 'arm-none-eabi-ar'  : /cygdrive/d/pixhawk_toolchain/toolchain/bin/arm-none-eabi-ar
Using toolchain                          : arm-none-eabi
Checking for 'g++' (C++ compiler)        : /cygdrive/d/pixhawk_toolchain/toolchain/bin/arm-none-eabi-g++
Checking for 'gcc' (C compiler)          : /cygdrive/d/pixhawk_toolchain/toolchain/bin/arm-none-eabi-gcc
Checking for c flags '-MMD'              : yes
Checking for cxx flags '-MMD'            : yes
Checking for HAVE_CMATH_ISFINITE         : no
Checking for HAVE_CMATH_ISINF            : no
Checking for HAVE_CMATH_ISNAN            : no
Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : no
Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : no
Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : no
Checking for header endian.h                   : not found
Checking for header byteswap.h                 : not found
Checking for program 'cmake'                   : /usr/bin/cmake
Checking cmake version                         : 3.6.2
Checking for program 'ninja, ninja-build'      : not found
Checking for program 'make'                    : /usr/bin/make
Checking for program 'python'                  : /usr/bin/python
Checking for python version >= 2.7.0           : 2.7.14
Checking for program 'python'                  : /usr/bin/python
Checking for python version >= 2.7.0           : 2.7.14
Source is git repository                       : yes
Update submodules                              : yes
Checking for program 'git'                     : /usr/bin/git
Gtest                                          : STM32 boards currently don't support compiling gtest
Checking for program 'arm-none-eabi-size'      : /cygdrive/d/pixhawk_toolchain/toolchain/bin/arm-none-eabi-size
Benchmarks                                     : disabled
Unit tests                                     : disabled
Checking for program 'rsync'                   : /usr/bin/rsync
'configure' finished successfully (2.035s)_

**Final step should be:

./waf Copter

but it doesn't work. I have tried everything I can find on google and the Ardupilot wiki and these forums, but every time I try to build, I get " uavcangen returned 1 error code "  and,**

_"build failed
  -> task in 'uavcan' failed (exit status 1):
 {task 7696554579320: uavcangen CoarseOrientation.uavcan,Timestamp.uavcan,1010.ArrayCommand.uavcan,1011.Status.uavcan,Command.uavcan,1000.Solution.uavcan,1001.MagneticFieldStrength.uavcan,1002.MagneticFieldStrength2.uavcan,1003.RawIMU.uavcan,1020.TrueAirspeed.uavcan,1021.IndicatedAirspeed.uavcan,1025.AngleOfAttack.uavcan,1026.Sideslip.uavcan,1027.RawAirData.uavcan,1028.StaticPressure.uavcan,1029.StaticTemperature.uavcan,1040.AngularCommand.uavcan,1041.GEOPOICommand.uavcan,1044.Status.uavcan,Mode.uavcan,1110.Temperature.uavcan,1030.RawCommand.uavcan,1031.RPMCommand.uavcan,1034.Status.uavcan,1060.Fix.uavcan,1061.Auxiliary.uavcan,1062.RTCMStream.uavcan,1063.Fix2.uavcan,ECEFPositionVelocity.uavcan,1070.Command.uavcan,1071.Status.uavcan,1129.FuelTankStatus.uavcan,1120.Status.uavcan,CylinderStatus.uavcan,1080.BeepCommand.uavcan,1081.LightsCommand.uavcan,RGB565.uavcan,SingleLightCommand.uavcan,1090.PrimaryPowerSupplyStatus.uavcan,1091.CircuitStatus.uavcan,1092.BatteryInfo.uavcan,1050.Measurement.uavcan,1100.ArmingStatus.uavcan,2000.GlobalNavigationSolution.uavcan,1.GetNodeInfo.uavcan,2.GetDataTypeInfo.uavcan,341.NodeStatus.uavcan,4.GetTransportStats.uavcan,4.GlobalTimeSync.uavcan,5.Panic.uavcan,5.RestartNode.uavcan,6.AccessCommandShell.uavcan,CANIfaceStats.uavcan,DataTypeKind.uavcan,HardwareVersion.uavcan,SoftwareVersion.uavcan,16370.KeyValue.uavcan,16383.LogMessage.uavcan,LogLevel.uavcan,1.Allocation.uavcan,30.AppendEntries.uavcan,31.RequestVote.uavcan,390.Discovery.uavcan,Entry.uavcan,15.Begin.uavcan,380.Indication.uavcan,40.BeginFirmwareUpdate.uavcan,45.GetInfo.uavcan,46.GetDirectoryEntryInfo.uavcan,47.Delete.uavcan,48.Read.uavcan,49.Write.uavcan,EntryType.uavcan,Error.uavcan,Path.uavcan,10.ExecuteOpcode.uavcan,11.GetSet.uavcan,Empty.uavcan,NumericValue.uavcan,Value.uavcan,2010.Broadcast.uavcan,63.Call.uavcan,Protocol.uavcan -> }
 (run with -v to display more information)_

**If anyone has any idea what i'm doing wrong here, I'm completely out of disjointed tutorials to follow.

Thanks in advance!**

**Comment by proficnc** [comment]
Your trying to build Ardupilot....
Maybe ask for assistance on the ardupilot forums?
