### ISSUE TITLE
Benewake TFmini laser rangefinder reports abnormal height when signal strenght is below minimum threshold

### ISSUE THREAD

**Issue by gianni-carbone** [PX4/Firmware#10569]
Rangefinder TFmini driver reports 655 meters above ground in some circumstances.
The problem occurs when the sensor detects a signal strenght below minimum threshold (default 20).
In this case the data message meets the device specification returning height 0xFFFF corresponding to 655 meters above ground. _The device specifications say, when the signal strenght is below minimum threshold, the low and high bytes for the height in the packet data are set to 0xFF 0xFF indicating, this way, invalid height._

The parser code is not configured to manage the event and reports the height buffer "as is" and signal quality unchanged = unknown for default of driver.

**To Reproduce**
on the workbench you can easly reproduce the problem
1. Connect TFmini laser rangefinder to the flight controller and configure it
2. Link the flight controller to Qgroundcontrol station
3. Open analyze and check DISTANCE_SENSOR.current_distance
4. Point sensor to a flat surface far enough in the sensing range of device
4. Using a dark cardboard or similar object start to slowly cover incrementally one of the sensor lens, simulating an event of signal strenght degradation. The cardboard must stay in contact with the sensor body from start to the full coverage of lense avoiding reflection. This tecnique reproduce a possible event of obtructing object, i.e. a floating wire or strap moving to the lens, during flight.
5. when the lens is quite completely covered the reported distance goes to 655 meters

Note: I suffers this problem during flight, I do not know for what reason if for optical obstruction or insufficient power to the sensor

**Expected behavior**
A signal quality degradation to 0 quality and distance to default value expected.

**Hardware:** 
Pixhawk clone HK32
Benewake TFmini laser rangefinder

**Additional info:**
**I'm testing a bug fix** that implements effective report.signal_quality and return current_distance = 0 and signal_quality = 0 when the signal strenght is below minimum threshold value. Actually the new code seems to work fine it calculates and return the signal quality too.
I will do a pull request as soon as possible

**Comment by mhkabir** [comment]
Please do a PR, thanks a lot!
