### ISSUE TITLE
Image Trigger Capture Time Measurement Design

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#10576]
As discussed in the dev call, lets use this issue to sort out the different discussions.
@DanielePettenuzzo @m0oz @davids5  please list your requirements and thoughts

Related:
https://github.com/PX4/Firmware/pull/10295

**Comment by sanderux** [comment]
check if this is filled: https://mavlink.io/en/messages/common.html#CAMERA_TRIGGER

**Comment by davids5** [comment]
I reviewed fmu v5 - the capture on FMU_CAP1-FMU_CAP3 and TIM5_SPARE_4 are not supported in the code base as of yet. So this set of requirements is timely. As is https://github.com/PX4/Firmware/pull/10534

Depending on the requirements, we should consider the following on V5.

1. Treating the capture channels as capture only. 
   This may require extending the table size MAX_IO_TIMERS and MAX_TIMER_IO_CHANNELS in an arch or board specific way to not bourden the small footprint devices.

2. The typedef for the allocation table will need to be increased to more bits.

3. Add Support for capture on chan 7 & 8 to FMU modes.
