### ISSUE TITLE
Trajectory Generator

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#10575]
Initial investigation and algorithm prototype is done here: https://github.com/Auterion/trajectory_generator

First discussions on dev call 2018-09-26

**Comment by bresch** [comment]
From @MaEtUgR :
> Here is the Smoothing Library located: https://github.com/PX4/Firmware/tree/master/src/lib/FlightTasks/tasks/Utility
It would be probably best if you could add your calculations in a C++ library class in the same way.
Here's the call to the library then for the manual position controlled smoothed flight: https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/ManualPositionSmooth/FlightTaskManualPositionSmooth.cpp#L55-L64

**Comment by thomasgubler** [comment]
Status (via @bresch ): first draft/WIP implementation is getting tested in SITL

**Comment by bresch** [comment]
Here is the WIP branch:
https://github.com/bkueng/Firmware/tree/trajectory_smoothing
I'm currently developing the [time synchronization](http://www.reflexxes.ws/software/typeiirml/v1.2.6/docs/page__synchronization_behavior.html) needed to provide nice straight lines.

**Comment by bresch** [comment]
Time synchronization is done, here is a simulation result on jMAVSim: https://logs.px4.io/plot_app?log=4fc1e3f0-f9ba-48a1-ad78-f2495fc9cbe7

**Comment by LorenzMeier** [comment]
Awesome!
