### ISSUE TITLE
Bug in FrSky SBUS failsafe

### ISSUE THREAD

**Issue by mijarck** [PX4/Firmware#10571]
As reported already here the "no pulses" failsafe of FrSky receivers like X8R has a random issue where failsafe flag of the SBUS frame is cleared but data values of some channels show 0 instead of correct channel value
 
https://github.com/ArduPilot/ardupilot/issues/9400

- Hopefully by switching off and on the transmitter enough many times and checking the SBUS frames before and after the frames having failsafe flag on

Expected behavior
- SBUS frames having incorrect data dropped

**Comment by Nurffe** [comment]
Probably somewhat same issue but other way around can be seen here where failsafe is triggered. Failsafe is set to "no pulses" but still zero is sent for certain channels (5, 9, 10, 11, 12, 14). There is no preset failsafe set in receiver itself so it's unknown why these random channels are set to zero which is then converted to 874 in FC

Here are snapshots from logs

Showing lines and timestamps for radio fs trigger
![2018-09-27_12-41-39](https://user-images.githubusercontent.com/34690104/46138142-d071e780-c253-11e8-80b8-0108c1c1fc6d.png)

Showing lines and timestamps for incorrect channel values
![2018-09-27_12-41-10](https://user-images.githubusercontent.com/34690104/46138186-eb445c00-c253-11e8-81c1-6ea309ac7d94.png)


Error state only lasts ~400ms and happens shortly after failsafe is triggered. Seeing this happen *after* failsafe has been recognized by FC makes me believe there might actually be something in arducopter code itself and not just receiver doing weird things. Ardu shouldn't take nonsense inputs when failsafe flag is already on

**Comment by dagar** [comment]
Hi @mijarck,

Which flight controller and firmware version?

**Comment by mijarck** [comment]
Was seen with Pixhawk 2.1 and Ardupilot initially. Then repeated on table with receiver only. Didn’t dare to fly too far (where failsafe kicks in) with PX4. Either didn’t tried debugging further about the behaviour on PX4. 

Just for the reference here’s the fix made to ArduPilot master: https://github.com/ArduPilot/ardupilot/pull/10216
