### ISSUE TITLE
Always "Preflight failed mag sensors inconsistent"

### ISSUE THREAD

**Issue by Seeelefant** [PX4/Firmware#10592]
**Describe the bug**
Whatever I do, I get a  "Preflight failed mag sensors inconsistent" even after choosing various Compass Rotations

**To Reproduce**
I have a Pixhawk 2.4.8 chinese clone and Zubax GNSS2, however the internal and the external mag are always out of synch.
1. Drone switched on '...'
2. Uploaded mission '....' (attach QGC mission file)
3. Took off '....'

**Expected behavior**

**Log Files and Screenshots**
*Always* provide a link to the flight log file:
- Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)).
- Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).
https://review.px4.io/plot_app?log=b61f86bb-56b9-45b7-bbbe-b534063c9e47
https://review.px4.io/plot_app?log=35372fd1-0d36-4bdd-9b47-d822d05bc22f
https://review.px4.io/plot_app?log=284d24d7-22a1-4643-8f00-62cc0ef3f47a

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

**Additional context**

**Comment by YCH188** [comment]
@Seeelefant Have you solve the problem, I have the same problem when setting up.

**Comment by Seeelefant** [comment]
Please take a look on https://github.com/PX4/Firmware/issues/10621, here I did a deeper analysis  and we are not alone in the world with this problem ;-) .
