### ISSUE TITLE
Tailsitter SITL test failure

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#10590]
The SITL test for the tailsitter is failing and needs proper inspection and fixing.

**Comment by dagar** [comment]
It appears to be returning to the back transition waypoint as a multicopter (very slowly), then timing out.

![image](https://user-images.githubusercontent.com/84712/46210668-5dbe4600-c2ff-11e8-883f-ad0d8ce260d2.png)

https://logs.px4.io/plot_app?log=1226a9e6-edef-40dd-b631-87dd95ec9c0f
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master_fmu_more_cap_modes/2/pipeline

**Comment by dagar** [comment]
Increasing the timeout might be an acceptable temporary fix until we figure out what's wrong with VTOL navigation.

https://github.com/PX4/Firmware/tree/pr-sitl_tailsitter

**Comment by bresch** [comment]
Strange thing, if I run the CI mission locally, I don't have the same result:
Tailsitter:
https://logs.px4.io/plot_app?log=ea1cf52d-2894-4a16-a099-0f7447afc354
VTOL Standard:
https://logs.px4.io/plot_app?log=f01e18c4-cb18-46cd-bba9-16db6bb693a4

**Comment by LorenzMeier** [comment]
Parameters on the CI system?

**Comment by bresch** [comment]
![tailsitter_ci](https://user-images.githubusercontent.com/14822839/46211599-3c2b8180-c334-11e8-9178-e74f48c6c07d.png)

"Return to back transition waypoint" is apparently not commanded

**Comment by dagar** [comment]
@bresch Can you try tailsitter several times? The failure is intermittent.

**Comment by dagar** [comment]
Here's a fresh one where VTOL standard failed, but tailsitter passed.
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/land_detector_cleanup_fixes/1/pipeline
