### ISSUE TITLE
Recovery with manual control impossible - no throttle control

### ISSUE THREAD

**Issue by ChrisHughes** [PX4/Firmware#10615]
Firmware 1.8.0 on Pixracer using Spektrum DXe for control.

Doing some testing of a custom range finder configuration to gain indoor z stability in position hold / guided modes.

In some situations the device went 'runaway' in Position Hold mode due to incorrect parameters.

In these instances, it seems that after switching the controller back to manual mode, the throttle stick was inactive and the motors would refuse to spin until after the drone had fallen to the ground.

Hoping to find some way around this so that mid-air recovery is possible as a fall of this nature can easily cause damage to hardware.

A flight log is attached where the device mis-interpreted its Z position and climbed indefinitely before being switched back to manual control at the end of the flight. 

[log001.ulg.zip](https://github.com/PX4/Firmware/files/2432446/log001.ulg.zip)

**Comment by bkueng** [comment]
Hi

The log only shows Manual flight control, and no Position Hold. The commanded RC throttle is correctly passed to the output (actuator controls). Is this the correct log?
Did the motors stop in-air? If so, you need to increase PWM_MIN.

Also you have quite high vibration levels in z direction that you should fix.
