### ISSUE TITLE
Upgrading through QGC seems to flash the wrong firmware.

### ISSUE THREAD

**Issue by Williangalvani** [PX4/Firmware#10625]
Flashing new firmware on a PX4 FMU V2:

- Flashing PX4 **beta 1.7.4** reads **1.8.0** 
( QGCdownloads from [/**beta**/px4fmu-v2_default.px4](http://px4-travis.s3.amazonaws.com/Firmware/beta/px4fmu-v2_default.px4))

- Flashing PX4 **stable 1.8.0** reads **1.8.0dev** 
(QGC downloads from [/**stable**/px4fmu-v2_default.px4](http://px4-travis.s3.amazonaws.com/Firmware/stable/px4fmu-v2_default.px4))

- Flashing PX4 **master 1.8.0** reads **1.8.0dev** 
(QGC downloads from [/**master**/px4fmu-v2_default.px4](http://px4-travis.s3.amazonaws.com/Firmware/master/px4fmu-v2_default.px4))

By "reads" I mean what it shows on the summary page.

I'm building QGC from latest master.
And I'm opening the issue here because QGC seems to be looking to the files at the right place.

**Comment by dagar** [comment]
Thanks for reporting, I'll look at fixing this.

**Comment by tubeme** [comment]
@Hey Daniel we have this problems almost at every new release. Is there any permanent solution?

**Comment by tecdee** [comment]
The issue is still not solved. I still cannot load 1.8.2, as QGC still loads 1.8.1.

**Comment by julianoes** [comment]
@tecdee can you check again?

**Comment by julianoes** [comment]
No response, closing.
