### ISSUE TITLE
Add ROS  melodic containers for CI

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#10633]

**Comment by TSC21** [comment]
Already exists (https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_ros) and being used upstream - https://github.com/PX4/Firmware/blob/master/.ci/Jenkinsfile-compile#L17

**Comment by TSC21** [comment]
Also `sitl_gazebo` is already using the latest: https://github.com/PX4/sitl_gazebo/pull/234
