### ISSUE TITLE
I get Error [px4flow] PASS when I run px4flow test in mavlink console! (PX4Flow+EKF2)

### ISSUE THREAD

**Issue by rhamrah** [PX4/Firmware#10671]
Hi,
I am using an optical flow sensor which has a sonar, plus EKF estimator, not using GPS. The flow sensor is connected to a Pixhawk through I2C port. The QGC version I am using is 3.4.4 the latest one, and the PX4 firmware is 1.8.0dev for a zmr250 racer airframe. I've also set all required parameters in qgrouncontrol as:
```
EKF_AID_MASK = 2,
EKF_HGT_MODE = Range sensor,
SENS_FLOW_ROT = YAW 270 deg,
...
```
and I am receiving and seeing all optical flow data on Mavlink Inspector in QGC, but I do not know the reason of `ERROR [px4flow] PASS ` I get in Mavlink console of QGC, and what it means! In Mavlink console, when I start px4flow it says:
`WARN [px4flow] already started`
When I stop it and start it again, it says:
```
INFO [px4flow] scanning I2C buses for device..
PX4FLOW on I2C bus 1 at 0x42 (bus: 100 KHz, max: 400 KHz)
PX4FLOW not primary range device, not advertising
```
What it shows when I run `px4flow info` is:

![screenshot from 2018-10-09 14-48-34](https://user-images.githubusercontent.com/27831881/46691437-ee840400-cbd2-11e8-8ecb-6ef7ce989fb1.png)

When I run `px4flow test`, it shows:

![screenshot from 2018-10-09 13-49-08](https://user-images.githubusercontent.com/27831881/46691575-3e62cb00-cbd3-11e8-9cbc-e0db9a6603e0.png)

and ends up with `ERROR [px4flow] PASS `. 
Can you please let me know what this error is, and why px4flow is not considered as the primary range device?!
I've also flown the drone, and when I switch to Altitude mode the drone flies up vertically and it seems px4flow sensor doesn’t work properly. Please let me know if you have experienced similar issue, and how to fix it?

**Comment by davids5** [comment]
@rhamrah I think it is a bug. The macro used to print the result should be PX4_INFO() https://github.com/PX4/Firmware/blob/master/src/drivers/px4flow/px4flow.cpp#L933 but this fle has not been reworked: errx needs to be expunghed and the correct PX4_{INFO|ERR...} macros used.

**Comment by rhamrah** [comment]
> @rhamrah I think it is a bug. The macro used to print the result should be PX4_INFO() https://github.com/PX4/Firmware/blob/master/src/drivers/px4flow/px4flow.cpp#L933 but this file has not been reworked: errx needs to be expunghed and the correct PX4_{INFO|ERR...} macros used.

Thanks David for your comment. I think I have a similar issue with LidarLite. I can see values of `Distance_sensor` in Mavlink inspector and I also see `range_finder0` when I run `ls /dev` , but in console I receive following errors and warnings:

![screenshot from 2018-10-23 11-50-00](https://user-images.githubusercontent.com/44004328/47373469-ef7c6180-d6b9-11e8-8678-6d5d86f8105a.png)

and the drone does not get armed. How can I fix it?

and also for connecting a FTDI cable to a Pixhawk 2 in order to screen the driver on a terminal, which port of Pixhawk 2 should I use as Serial 5 (like what is said in https://dev.px4.io/en/debug/system_console.html)? I used GPS2 but it did not work!

**Comment by hamishwillee** [comment]
@rhamrah I think Serial 5 is the one labelled [Debug here](https://docs.px4.io/en/flight_controller/pixhawk-2.html#debug-ports) - there should be enough info at that link (or the pinout linked from that doc) to confirm.

**Comment by rhamrah** [comment]
> @rhamrah I think Serial 5 is the one labelled [Debug here](https://docs.px4.io/en/flight_controller/pixhawk-2.html#debug-ports) - there should be enough info at that link (or the pinout linked from that doc) to confirm.

Thanks Hamish for your response. I just found out that Serial 5 is actually the CONS port which stands for console (http://www.hex.aero/wp-content/uploads/2016/07/DRS_Pixhawk-2-17th-march-2016.pdf , page 15). It has three pins GND, RX, and TX respectively. I connected a FTDI cable to those pins and I could screen that port in a terminal window.

**Comment by hamishwillee** [comment]
THanks @rhamrah - CONS makes sense once I look at the diagram again :-)

**Comment by davids5** [comment]
Hmm - I never realized the console appeared 2 places.  I have alway used the Drone code debug connector.

The first version of the Drone code debug connector using a SUR connector (SM06B-SURS-TF(LF)(SN)-ND) is wired as:

![image](https://user-images.githubusercontent.com/1945821/47463381-e6af8c80-d79a-11e8-90dd-bfebd95145f8.png)
Not it does not provide the CPU (Target voltage) but 5V

The current Drone code debug connector is ired the same but uses the SM06B-SRSS-TB(LF)(SN) connector.

![image](https://user-images.githubusercontent.com/1945821/47463466-28403780-d79b-11e8-8f15-d55af4191a3a.png)

**Comment by hamishwillee** [comment]
@proficnc Hi Philip, see the comments above. There has been some confusion about what ports are used for debugging and what connectors to use - ie there is CONS, DEBUG, EDISON DEBUG. 

Do you think you guys could update the Cube docs to clarify? 
Suggestion, update the [Debug ports](https://docs.px4.io/en/flight_controller/pixhawk-2.html#debug-ports) section to:
- state the use of each of the above ports - ie cable to use, what they are wired to - anything you need to actually use them
- In this section add diagram showing CONS port too. 
- Explain the differences.
