### ISSUE TITLE
GPS_RAW_INT -- time since boot vs unix epoch

### ISSUE THREAD

**Issue by dakejahl** [PX4/Firmware#10700]
![selection_010](https://user-images.githubusercontent.com/37091262/47045194-762bbe80-d14f-11e8-9fce-1d23ed521f0b.png)

I'm not sure when this changed from UNIX epoch to time since boot, we only just noticed it. Is there a way to configure this? We'd really like to use the GPS time to sync our offboard clock.

**Comment by mhkabir** [comment]
> We'd really like to use the GPS time to sync our offboard clock.
