### ISSUE TITLE
Nano Talon crash

### ISSUE THREAD

**Issue by Avysuarez** [PX4/Firmware#10722]
Today I flew the nano talon with the new airframe parameters, I started to fly in stabilized, when I changed to auto the plane accelerated and it went into tailspin, i could not recover it and it crashed. The damage is the frame, @mrpollo  can we order a frame, I will coordinate with Tony to send you the information. @dagar  any thoughts? @fredowski 
[
![img_3256](https://user-images.githubusercontent.com/12182176/47172437-55cf4180-d2c0-11e8-9778-b168147249a9.JPG)
]
(https://review.px4.io/plot_app?log=1e1e2a7a-db41-4f48-9a53-a1be968563bd)

**Comment by fredowski** [comment]
O.k. that one crashed... Looking at the pitch in flight review, the plane cannot follow your pitch requests. In addition your pitch mixer input (actuator control) is more or less always positive. Is your center of gravity o.k.?

**Comment by Avysuarez** [comment]
Before the crash, I made a flight and the plane flew very well, the center of gravity was OK.

**Comment by fredowski** [comment]
Do you have a flight log of the flight which was o.k.? Which setup did you use for that flight? Before I introduced the Mini Talon airframe, I used the Albatross A-Tail including the parameters but with reversed servos and flipped V-Tail servo connection. How did you setup the nano talon?

**Comment by fredowski** [comment]
Thanks for the info. Did you use the same hardware setup, i.e. were the servos attached to the same outputs? I noticed a difference in the two setups with respect to the yaw.

![nano-talon-albatross-setup](https://user-images.githubusercontent.com/1280457/47381782-1447f780-d701-11e8-9693-2a5f9dddd339.JPG)
![nano-talon-vtail-setup](https://user-images.githubusercontent.com/1280457/47381794-1b6f0580-d701-11e8-8cd0-2980bc210fed.JPG)

A positive yaw in the albatross setup results in a negative average for output 2 and 3. A positive yaw in the x-uav mini talon (vtail) setup results in a positive average output. I you left the hardware unchanged, then you should see that the yaw control works in the wrong direction compared to your alabatros setup. Could you maybe check even with the broken frame if the Yaw works correctly?

For my setup with the mini talon I had to flip the V-Tail Servos to make it work with the Albatros setup, i.e. MAIN3 was V-Tail left and MAIN4 was V-Tail right. The X-UAV Mini Talon airframe setup is designed to have the servo connections as described in the manual: https://dev.px4.io/en/airframes/airframe_reference.html That means MAIN3 is V-Tail right and MAIN4 is V-Tail left. But depending on your exact servo behaviour and mechanical setup, this might be different in your nano talon.

**Comment by fredowski** [comment]
Thanks!
