### ISSUE TITLE
DANGEROUS: VEHICLE_CMD_DO_REPOSITION broken on master

### ISSUE THREAD

**Issue by dakejahl** [PX4/Firmware#10757]
Had a Drone fly into a pole and smash into the ground when issuing a VEHICLE_CMD_DO_REPOSITION. I looked at the log and everything looked fine. This is broken on current `master` 294af5daada2fa08da8d9f1c4310779683fe9750
https://review.px4.io/plot_app?log=cc6bccfc-44a5-4eca-bc2f-7a4be13a0a7a
![selection_019](https://user-images.githubusercontent.com/37091262/47468014-45ceca80-d7b6-11e8-8a72-808d278e3b66.png)

As you can see we were just adjusting the altitude setpoint and nothing else.

I then tested this in SITL using `make posix_sitl_default gazebo` and issued via QGroundControl a **`goto`** command and saw the vehicle fly to the new location, but then fly super far an a random direction for a while, then returns back to that location, wanders around a bit more, flys off in the opposite direction... then I got bored of watching.
![selection_020](https://user-images.githubusercontent.com/37091262/47468301-c8a45500-d7b7-11e8-8acc-f1d56e639669.png)

Isn't CI supposed to catch these types of bugs? This is extremely concerning to me.

**Comment by dagar** [comment]
Do you know when it last worked?

> Isn't CI supposed to catch these types of bugs?

Yes, but it's mainly testing core controller and mission functionality so far. Every feature like this we care about needs targeted testing to prevent these kind of regressions.

**Comment by bkueng** [comment]
> This is extremely concerning to me.

Agreed.

Fix is here: https://github.com/PX4/Firmware/pull/10760

**Comment by dakejahl** [comment]
Awesome, thanks for the quick fix.
