### ISSUE TITLE
Offboard yaw movement causes loss of vertical height EKF2

### ISSUE THREAD

**Issue by ChrisHughes** [PX4/Firmware#10764]
PX4 1.8.0 dev + commits up to around mid-september (27b2dad1)

PX4Flow and TFMini lidar, no GPS, indoor flight.

Device holds position in air after mavlink commanded takeoff. When device is commanded to perform a yaw manoeuvre it progressively looses vertical height throughout the course of that manoeuvre. This is tested in real flight, not SITL.

Simplified code describing the actions performed (based on dronekit)

```
# Takeoff
vehicle.arm_and_takeoff(1.5)
# Wait for vehicle to reach target altitude
time.sleep(5)
# Send target_local_NED commands prior to setting offboard mode
for i in range(10):
bitmask = 0b0000001111111111
msg = vehicle.message_factory.set_position_target_local_ned_encode(
0, # time_boot_ms (not used)
self.target_system_id, self.target_component_id,
mavutil.mavlink.MAV_FRAME_LOCAL_NED, # frame
bitmask,
0, # North
0, # East
0, # Down
0, 0, 0, # x, y, z velocity in m/s (not used)
0, 0, 0, # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
0, 0) # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
# send command to vehicle
vehicle.send_mavlink(msg)
time.sleep(0.25)
# Perform a 360 degree rotation
start_yaw = vehicle.attitude.yaw
for i in range(20):
        time.sleep(0.25)
bitmask = 0b0000000111111111
yaw_rate = 0.3
yaw = start_yaw + 18 * i * 0.0174533
msg = vehicle.message_factory.set_position_target_local_ned_encode(
0, # time_boot_ms (not used)
self.target_system_id, self.target_component_id,
mavutil.mavlink.MAV_FRAME_LOCAL_NED, # frame
bitmask,
0, # North
0, # East
0, # Down
0, 0, 0, # x, y, z velocity in m/s (not used)
0, 0, 0, # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
yaw, yaw_rate) # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
# send command to vehicle
vehicle.send_mavlink(msg)
# Land
vehicle.mode = VehicleMode("LAND")
time.sleep(4)
vehicle.armed = False
```

Flight log:
https://logs.px4.io/plot_app?log=d79c2235-4891-458e-8c9d-4e910504bc9f

Drone HW:
Pixracer / FMUv4
PX4Flow
TFMini

Would greatly appreciate any help in identifying the issue here, is it an issue with how I'm interacting with mavlink via the bitmask, or is there an issue with the firmware or parameters themselves?

Thanks!

**Comment by Jaeyoung-Lim** [comment]
@ChrisHughes This might be a hardware limitation on demanding a yaw rate too high.

Is this also a problem wehn the yaw rate is lower?

**Comment by caomxin** [comment]
Hi ChrisHughes, Have you tested the code in the simulation e.g. Gazebo?

**Comment by farhangnaderi** [comment]
> PX4 1.8.0 dev + commits up to around mid-september ([27b2dad](https://github.com/PX4/Firmware/commit/27b2dad1fb4f30455067ec1381cd0df857b5be6a))
> 
> PX4Flow and TFMini lidar, no GPS, indoor flight.
> 
> Device holds position in air after mavlink commanded takeoff. When device is commanded to perform a yaw manoeuvre it progressively looses vertical height throughout the course of that manoeuvre. This is tested in real flight, not SITL.
> 
> Simplified code describing the actions performed (based on dronekit)
> 
> ```
> # Takeoff
> vehicle.arm_and_takeoff(1.5)
> # Wait for vehicle to reach target altitude
> time.sleep(5)
> # Send target_local_NED commands prior to setting offboard mode
> for i in range(10):
> bitmask = 0b0000001111111111
> msg = vehicle.message_factory.set_position_target_local_ned_encode(
> 0, # time_boot_ms (not used)
> self.target_system_id, self.target_component_id,
> mavutil.mavlink.MAV_FRAME_LOCAL_NED, # frame
> bitmask,
> 0, # North
> 0, # East
> 0, # Down
> 0, 0, 0, # x, y, z velocity in m/s (not used)
> 0, 0, 0, # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
> 0, 0) # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
> # send command to vehicle
> vehicle.send_mavlink(msg)
> time.sleep(0.25)
> # Perform a 360 degree rotation
> start_yaw = vehicle.attitude.yaw
> for i in range(20):
> time.sleep(0.25)
> bitmask = 0b0000000111111111
> yaw_rate = 0.3
> yaw = start_yaw + 18 * i * 0.0174533
> msg = vehicle.message_factory.set_position_target_local_ned_encode(
> 0, # time_boot_ms (not used)
> self.target_system_id, self.target_component_id,
> mavutil.mavlink.MAV_FRAME_LOCAL_NED, # frame
> bitmask,
> 0, # North
> 0, # East
> 0, # Down
> 0, 0, 0, # x, y, z velocity in m/s (not used)
> 0, 0, 0, # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
> yaw, yaw_rate) # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
> # send command to vehicle
> vehicle.send_mavlink(msg)
> # Land
> vehicle.mode = VehicleMode("LAND")
> time.sleep(4)
> vehicle.armed = False
> ```
> 
> Flight log:
> https://logs.px4.io/plot_app?log=d79c2235-4891-458e-8c9d-4e910504bc9f
> 
> Drone HW:
> Pixracer / FMUv4
> PX4Flow
> TFMini
> 
> Would greatly appreciate any help in identifying the issue here, is it an issue with how I'm interacting with mavlink via the bitmask, or is there an issue with the firmware or parameters themselves?
> 
> Thanks!

Same here. Any solution?
