### ISSUE TITLE
Pixhawk 4 with RTK HERE + GPS

### ISSUE THREAD

**Issue by Haeryangkim** [PX4/Firmware#10778]
Hi,
I'm planning to use Pixhawk 4 with RTK here + GPS

But it seems HERE+ GPS support Pixhawk 2 directly (support Pixhawk 3 by changing cable).

I can't find any information about Pixhawk 4 with related to RTK GPS.
Is there any tutorial for this?

Thanks.

**Comment by Haeryangkim** [comment]
@Jaeyoung-Lim  I checked the document including the pinout map of pixhawk, I'm just wondering what the Korean pixhawk official seller says the here + RTK is for pixhwak 2 (I assume that is just cable problem). Therefore, I need to double-check it before I buy the expensive stuff.

**Comment by Jaeyoung-Lim** [comment]
@Haeryangkim I wasn't aware that there was a 'official' seeler for pixhawk in Korea.

Anyway, the hardware version(pixhawk2= fmuv3) is what matters more than the actual numbering on the name. Pixhawk 4 is fmuv5.

The firmware supports RTK, so it should also work with pixhawk4.

**Comment by proficnc** [comment]
There are two official resellers in S.Korea for the Cube and Here products. (Formally Pixhawk 2) 
The cube is FMUv2 and FMUv>5 depending on colour. 
However, the Here is compatible with all Cube and PX4 related hardware. Just may need to set up a cable depending on what hardware you have.
Plug and play with the cube of all versions

**Comment by rmtorre** [comment]
Hello guys

I have the same issue. I have a Pixhawk 4 and a Here+ RTK. Does anyone knows if is just a pinout problem? Any updates, please?

Thanks

**Comment by Phil4771** [comment]
Hi everybody, same problem for me
Anybody contacted holybro?
Any update?

**Comment by Phil4771** [comment]
![Here+Pinout](https://user-images.githubusercontent.com/65064042/81469073-4d609380-91e3-11ea-8358-bd26b04d9b4a.png)

i Will try to do this

**Comment by Phil4771** [comment]
Pixhawk 4 UART & 12C B port has the same pinout than pixhawk 3 pro
[Pixhawk4-Pinouts.pdf](https://github.com/PX4/Firmware/files/4603041/Pixhawk4-Pinouts.pdf)
