### ISSUE TITLE
LPE setup problem

### ISSUE THREAD

**Issue by YuYangguang** [PX4/Firmware#10771]
I want to use the vicon system as the external position estimator. Therefore, I follow the guide [guide](http://dev.px4.io/en/ros/external_position_estimation.html). However,in the latest vesion of the Firmware, I couldn't find the corresponding parameters, such as ATT_EXT_HDG_M. I use the command 
"make px4fmu-v2_lpe" to build the code. Is there anything wrong

**Comment by jgoppert** [comment]
ATT_EXT_HDG_M is defined by attitude_estimator_q. Make sure that att_est_q it is being built. In general we are nolonger supporting LPE and recommend you move to EKF2.

**Comment by vkotaru** [comment]
So, does EKF2 support mocap_pose_estimate?

Thanks

**Comment by hamishwillee** [comment]
@vkotaru 

> So, does EKF2 support mocap_pose_estimate?

Looks like it: http://dev.px4.io/en/tutorials/motion-capture-vicon-optitrack.html#ekf2
