### ISSUE TITLE
Pixhawk 4 mini backports for v1.8

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#10793]
* [ ] https://github.com/PX4/Firmware/issues/10034
 * [ ] https://github.com/PX4/Firmware/pull/10579

  - In particular look at px4fmu-v5 manifest issues

**Comment by dagar** [comment]
@jinger26

**Comment by jinger26** [comment]
@jamming FYI

**Comment by jinger26** [comment]
@dagar are we planning a 1.8.2 release?

**Comment by jinger26** [comment]
@dagar @davids5  since we decided not to do backport, can we tag this for 1.9 and close this item?
