### ISSUE TITLE
UAVCAN config

### ISSUE THREAD

**Issue by Avysuarez** [PX4/Firmware#10797]
@pavel-kirienko @mhkabir 
I working with a new build, with UAVCAN ESC and GPS of zubax, I already all connected and I made the configuration of the ESC, the copter arming but I can't configure the order of the motors, because I have a problem with the uavcan motor assignment, when I press the button to start the assignment the pixhawk does not anything. 
<img width="887" alt="esccaluav" src="https://user-images.githubusercontent.com/12182176/47823032-a2386980-dd23-11e8-9a20-9a99f86efc98.PNG">
this is the message that QGC shows me. 
Already tried with the different options of the UAVCAN_ENABLE parameter and nothing. 
https://www.youtube.com/watch?v=RFgwBKcr1qU
what could be the problem?

**Comment by mhkabir** [comment]
Are you using Myxas? If so, they don't support automatic enumeration. Slack me and I can guide to through the manual setup process.

**Comment by bresch** [comment]
@Avysuarez Here's a good document to read: https://forum.zubax.com/t/quick-start-guide-for-myxa-v0-1/911

**Comment by Avysuarez** [comment]
I have the same issue, already followed all the instruction that @mhkabir gave me, and the vehicle only flips on the takeoff. The assignments and the rotation directions of the motors it's correct. I don't know what else could it be. 
This is a video of the ESC #1 
<img width="283" alt="esc1 1" src="https://user-images.githubusercontent.com/12182176/48450456-111db580-e75b-11e8-90b5-08bb98bef694.PNG">
<img width="314" alt="esc1 2" src="https://user-images.githubusercontent.com/12182176/48450462-1975f080-e75b-11e8-99b8-94e423ff716a.PNG">
