### ISSUE TITLE
Mavlink status shows wrong baudrate

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#10806]
Very minor bug.
I started MAVlink instance on ttyACM0 @ 1000000 baud (standard MAVlink instance).
When sending the command "mavlink status" it returns the instance with an error. In particular it returns:

"transport protocol: serial (/dev/ttyACM0 @2000000)"  <-- it says 2000000 instead of 1000000.

**Comment by dakejahl** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L764-L776
