### ISSUE TITLE
land mode bug

### ISSUE THREAD

**Issue by qikai820** [PX4/Firmware#10801]
**Describe the bug**
land speed all along is land_speed
（mc_pos_control_main.cpp line 2439）
        float vel_limit = math::gradual(altitude_above_home,
 _slow_land_alt2.get(), _slow_land_alt1.get(),
 _land_speed.get(), _vel_max_down.get());

```
_vel_sp(2) = math::min(_vel_sp(2), vel_limit);
```

when land mode _vel_sp(2)=land_speed=0.7
so vel_limitis always greater than _vel_sp(2) 

**To Reproduce**

1. position mode fly over alt1 (200)
1. start land mode then You will find that it is very slow at any height.

**Expected behavior**

**Log Files and Screenshots**
_Always_ provide a link to the flight log file:

* Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)).
* Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).

Add screenshots to help explain your problem.

**Drone (please complete the following information):**

* Describe the type of drone.
* Photo of the IMU / autopilot setup if possible.

**Additional context**

**Comment by dakejahl** [comment]
How does the vehicle know where ground is without a range sensor? I've talked about changing this to obey range finder data if available, but it hasn't been enough of a priority to get it done in good way. If you'd like a fix, try replacing the function `FlightTaskAutoMapper::_generateLandSetpoints()` in _src/lib/FlightTasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp_ to this:
```
void FlightTaskAutoMapper::_generateLandSetpoints()
{
	// limit vertical downwards speed (positive z) close to ground
	// for now we use the altitude above home and assume that we want to land at same height as we took off
	float vel_limit_down = math::gradual(-_position(2),
					     MPC_LAND_ALT2.get(), MPC_LAND_ALT1.get(),
					     MPC_LAND_SPEED.get(), MPC_Z_VEL_MAX_DN.get());

	// Keep xy-position and go down with landspeed
	_position_setpoint = Vector3f(_target(0), _target(1), NAN);
	_velocity_setpoint = Vector3f(Vector3f(NAN, NAN, vel_limit_down));
	// set constraints
	_constraints.tilt = MPC_TILTMAX_LND.get();

	_constraints.speed_down = MPC_Z_VEL_MAX_DN.get();
	_constraints.landing_gear = vehicle_constraints_s::GEAR_DOWN;
}
```

**Warning:** This means it will obey these altitude limits based on absolute altitude (as provided by the gps/baro) which does not respect any changes in local elevation. 

i.e: you fly up to the top of a hill and issue `land`.... your drone full speeds into the ground.
