### ISSUE TITLE
EKF GPS fusion timeout - reset to GPS

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#10826]
Version：
FW：1.8.0
FC：v2
gps：RTK
I have set EKF2_HGT_MODE to gps.But when I test RTK,it warnning EKF GPS fusion timeout - reset to GPS  and EKF GPS fusion timeout - reset to baro.How do I solve this warnning?

**Comment by xdwgood** [comment]
Suggest: you can see PX4/ECL and find `EKF GPS fusion timeout - reset to baro`
Please aslo provide log link. 
https://logs.px4.io/plot_app?log=279de7aa-6a7b-408c-9ab9-a9a6b9e5fae0

I am also interested this issue,so commented on it.
I noticed this: 
![screenshot from 2018-11-13 11-23-17](https://user-images.githubusercontent.com/24932258/48389006-8f1b9580-e736-11e8-9cad-640fd761b5ae.png)

@mhkabir  @priseborough  Could you have a look ? thanks :smiley:

**Comment by roseyangyu** [comment]
I have solve this problem when I set rate to 5HZ
