### ISSUE TITLE
no execption check after malloc

### ISSUE THREAD

**Issue by kang-dongwook** [PX4/Firmware#10821]
There is no exception check after invoking malloc()
at line 146 of Firmware/platform/posix/src/px4_layer/px4_posix_tasks.cpp 
and line 149 of Firmware/platform/qurt/src/px4_layer/px4_qurt_tasks.cpp.

A counter example of exception check followed by malloc is 
line 180 and 182 of Firmware/src/lib/mixer/mixer_simple.cpp.

thanks.

**Comment by bkueng** [comment]
Thanks. Can you add those and create a pull request?
