### ISSUE TITLE
macOS SITL broken after daemon change

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#10839]
SITL doesn't work anymore on macOS.

`git bisect` points to #10766.

I'll look into it.

**Comment by julianoes** [comment]
Turns out the daemon client returns immediately and that's what's probably causing the segfault as well as other issues I'm seeing.

**Comment by julianoes** [comment]
It looks like this is an issue that we get `poll` for `POLLHUP` too early on macOS. It looks like poll is not equal to poll, it all depends on the OS: https://www.greenend.org.uk/rjk/tech/poll.html

**Comment by m-ou-se** [comment]
What's the minimal init script or commands you run to reproduce this?

**Comment by m-ou-se** [comment]
I'd be very surprised if POLLHUP comes too early. It coming too late (well, not at all) could make sense, if on Mac the shutdown() doesn't trigger it. But in that case you shouldn't experience much problems, only that the thread doesn't get killed when the client disconnects.

**Comment by m-ou-se** [comment]
I was looking at the wrong `shutdown`. It wasn't the `shutdown` of the server thread that caused the problem, but the `shutdown(WR)` of the *client*. But that one is not really needed. Removing it should solve the problem: https://github.com/PX4/Firmware/pull/10846
