### ISSUE TITLE
Does the loiter_unlim waypoint loiter radius set not working?

### ISSUE THREAD

**Issue by goodman110110110** [PX4/Firmware#10836]
When I use the LOITER_UNLIM waypoint, I set the loiter radius as 100m.
![_20181113200658](https://user-images.githubusercontent.com/18226775/48412649-4092e900-e780-11e8-83ee-6fba04c34ef5.jpg)

The plane will loiter around the waypoint in the mission mode, but the loiter radius is not fixed.
When I change the cruise speed higher in real time, loiter radius will be changed bigger and not fixed also.
![_20181113200603](https://user-images.githubusercontent.com/18226775/48412508-dbd78e80-e77f-11e8-9df3-4ad7f29524f5.jpg)
![_20181113200647](https://user-images.githubusercontent.com/18226775/48412565-032e5b80-e780-11e8-9402-67aa426adb91.jpg)

Question: The loiter radius set is not working?

**Comment by hamishwillee** [comment]
I *THINK* that for fixed wing the radius parameter is being ignored and that the radius is coming from parameter [NAV_LOITER_RAD](https://dev.px4.io/en/advanced/parameter_reference.html#NAV_LOITER_RAD).

The documents *say* that `NAV_LOITER_RAD` is just the default, but on quick scan of the code it looks like it might be always used.

@dagar Is that correct, and if so, why don't we respect the loiter radius from the mission?

**Comment by goodman110110110** [comment]
When I change the parameter NAV_LOITER_RAD, the loiter radius is also not changed.
It seems the NAV_LOITER_RAD can not change the radius also. @hamishwillee

**Comment by hamishwillee** [comment]
Limited knowledge sorry. Hope maybe @dagar can comment.
