### ISSUE TITLE
LED driver TCA62724FMG  stop production

### ISSUE THREAD

**Issue by jamming** [PX4/Firmware#10834]
TOSHIBA LED driver TCA62724FMG stop production right now. I2C controlled RGB LED driver NCP5623BMUTBG of Onsemi is good substitute for TCA62724FMG. NCP5623BMUTBG is easy to buy. So it's a good idea to change the drivers to support it.
Basic RGB appliation of  NCP5623BMUTBG can be seen in the following link.
'https://github.com/jamming/image/blob/master/NCP5623B-LED-driver.png'

**Comment by tubeme** [comment]
Actually we created a LED with another driver chip. NXP one. The first PCB is ready to be tested. We can share it. We new the TOSH stopped the production, because we wanted to make our LED with this chip so there were only stocks left here and there one year ago I suppose not anymore.

**Comment by dagar** [comment]
A driver for the ncp5623c was recently contributed. https://github.com/PX4/Firmware/pull/10889
