### ISSUE TITLE
multi-vehicle simulation sensor

### ISSUE THREAD

**Issue by matteoscanavino** [PX4/Firmware#10851]
Hello! 
I am following the guide on multi-vehicle simulation: https://dev.px4.io/en/simulation/multi-vehicle-simulation.html.
Everything works well and I was able to insert the swarm on my world file.
Now I'd like to add a camera to one of the iris  but I don't know how to do that. I know that for each vehicle inside the launch file I can add tag to define mavlink_upd_port, pose, vehicleID.... do I have to specify a tag for the camera?
Does anyone has experience? I didn't find any documentation on this topic and I don't have experience...
Thankyou in advance

**Comment by hamishwillee** [comment]
The docs we have on [camera in gazebo are here](https://dev.px4.io/en/simulation/gazebo.html#video-streaming). I have not tried this out.

**Comment by hamishwillee** [comment]
@S259420 I'm not a developer and I don't know anything about this topic. You're going to have to wait for some real help :-). The people I linked might be good ones to talk to. @TSC21 might also have some insight.

**Comment by S259420** [comment]
@hamishwillee  Thanks a lot! :)

**Comment by lbegani** [comment]
> @lbegani - Any ideas on setting up Gazebo camera for multiple vehicles in a multi-vehicle simulation. Even knowing this is not supported would be useful ....

I am not sure how it works with multi-vehicle simulation. My understanding is that you add a camera sensor in the model's sdf file, specify the properties and you will have the camera frames published on the gazebo topic. For reference check - `Firmware/Tools/sitl_gazebo/models/typhoon_h480/typhoon_h480.sdf ` . Try adding camera sensor in the model and see if it works.

**Comment by S259420** [comment]
@lbegani For a multivehicle, an urdf file is needed instead of the sdf...

**Comment by matteoscanavino** [comment]
@helenol @burrimi @birchera @devbharat @andre-nguyen 
Hello, could you please explain how to use  "component_snippets.xacro"? I've found it is called by iris_base.xacro. It should allow to set a camera  sensor and create an urdf for themultivehicle simulation. I've found you contributed to component_snippets.xacro, any suggestion would be appreciated. 
Thankyou in advance
