### ISSUE TITLE
Add parameters to define sensor priorities

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#10859]
As discussed in the dev call on 14.11.2018 with @dagar and @davids5 

**Issue we want to solve**
A developer or experienced user should be able to easily choose which instance of gyro/accel/mag should be used as the primary instance. Some flight controllers have vibration isolated and hard-mounted sensors at the same time and therefore we should allow the user to chose which sensor to use primarily.

**Suggestion**
We could add parameters for each sensor instance that define the priority of that sensor. Initially, those parameters could be set to reflect the current priority scheme. However, one would be able to change priorities via those parameters.

Example:
CAL_GYRO0_PRIO: ...
CAL_GYRO1_PRIO:...

**Comment by dagar** [comment]
Would the priority set (and reset) during calibration?
