### ISSUE TITLE
Running a mission from a CI fails because home position is hardcoded in header file

### ISSUE THREAD

**Issue by vincedjango** [PX4/Firmware#10874]
**Describe the bug**
Running a mission from a CI tool fails with the error below if the first waypoint specified in your .plan has a distance higher than 900m with value _lat_home_ and _lon_home_ hardcoded in 
_firmware/Tools/sitl_gazebo/include/gazebo_gps_plugin.h_.

```
FCU: First waypoint too far away: 9522903 meters, 900 [0m
```

**To Reproduce**

1. Look at _.plan_ file attached to this message [Trabuco Test 1.plan.txt](https://github.com/PX4/Firmware/files/2597623/Trabuco.Test.1.plan.txt)
1. In Jenkins, execute it with this step:

```
steps
{
sh 'test/rostest_px4_run.sh mavros_posix_test_mission.test mission:=TrabucoTest1 vehicle:=iris'
}
```

**Expected behavior**

1. In the _.plan_ file attached to this issue, I specified these data

```
"plannedHomePosition": [
33.66607036681994,
-117.56787594684947,
351
]
```

1. The takeoff position is set in the file: _firmware/Tools/sitl_gazebo/src/gazebo_gps_plugin.cpp_ at line 234,235

```
} else {
lat_rad = lat_home;
lon_rad = lon_home;
}
```

Then line 234,234 are set at line 68,76 (of the same file)

```
if (env_lat) {
gzmsg << "Home latitude is set to " << env_lat << ".\n";
lat_home = std::stod(env_lat) * M_PI / 180.0;
}
if (env_lon) {
gzmsg << "Home longitude is set to " << env_lon << ".\n";
lon_home = std::stod(env_lon) * M_PI / 180.0;
}
```

1. As you can see, the longitude and latitude are set from an environment variable. This environment variable is set in _firmware/Tools/sitl_gazebo/include/gazebo_gps_plugin.h_ at line 94,95,96

```
double lat_home = 47.397742 * M_PI / 180.0; // rad
double lon_home = 8.545594 * M_PI / 180.0; // rad
```

1. You can now see that my home position set in my _.plan_ file is ignored and because my first waypoint is far away (+900m) from the home position hardcoded in _gazebo_gps_plugin.h_, I get the error mentioned above.

**Comment by lamping7** [comment]
This doesn't seem like a firmware issue. It is how the sitl_gazebo submodule specifies it. The environment variables can be used in the Jenkins step to specify your home: `PX4_HOME_LAT`, `PX4_HOME_LON`, and `PX4_HOME_ALT`.

Alternatively, if we want to handle it, we could write a script to parse the plan and set these automatically before ROS is launched, but this seems clunky. Any ideas on a better approach?
