### ISSUE TITLE
Strange drift on velocity tracking

### ISSUE THREAD

**Issue by limhyon** [PX4/Firmware#10881]
https://logs.px4.io/plot_app?log=06cbb7ce-198a-45ff-9e9f-557143f20b93

Here is the log.
Around 2:00, there is a significant divergence on velocity tracking, but until then, it is fine.

P.S.
https://logs.px4.io/plot_app?log=a14f4203-1ad1-4a58-a9ee-cfde69bf0d9a
another log too.

**Comment by MaEtUgR** [comment]
@limhyon Do you have any more detailed information? Like what did you see happening which wasn't expected? Did it drift off like a flyaway or just fly wobbly?

**Comment by MaEtUgR** [comment]
I just saw that at 1:58 it quickly detects ground contact which could be either the cause or a consequence of the altitude divergence.

**Comment by MaEtUgR** [comment]
> I was testing GPS hovering
> and it maintained position quite well
> but suddenly, it moves in one direction straight
> so that I changed to stabilize mode

**Comment by dakejahl** [comment]
It's because of **EKF_RNG_AID**. I don't understand the exact mechanism of failure, but things go severely wrong when you toggle between baro and range finder. 
![selection_004](https://user-images.githubusercontent.com/37091262/48811735-4d698c80-ecec-11e8-9a2f-2b38c5ef5fbc.png)

**Comment by LorenzMeier** [comment]
@priseborough FYI

**Comment by MaEtUgR** [comment]
@limhyon Is this problem still present? There were a lot of changes and fixes, I wouldn't know which one exactly is related.

**Comment by bresch** [comment]
There have been a lot of bug fixes and refactoring in the switch between different sources of height fusion. I didn't see this issue anymore, closing.
