### ISSUE TITLE
Bad param meta data: VT_AIRSPD_RULE is UINT but min is set with float value

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#10896]
Latest QGC complaining about bad metadata:
```PX4ParameterMetaDataLog: Invalid min value, name: "VT_AIRSPD_RULE"  type: 5  min: "0.0"  error: "Invalid number"```

**Comment by dagar** [comment]
Thanks for reporting Don, fixed in https://github.com/PX4/Firmware/pull/10897.

**Comment by dagar** [comment]
FYI @RomanBapst
