### ISSUE TITLE
About fly mission

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#10915]
I have set a mission.But I have a problem.I hope vechicle to hold 3 secs after take a photo.But the command is hold frist,than take a photo.How do I set up to give priority to taking pictures?
![default](https://user-images.githubusercontent.com/40378941/48999027-492bec00-f190-11e8-9747-5e49b3e29a31.png)

like this?I want the hold-command to be after take photo
![default](https://user-images.githubusercontent.com/40378941/48999065-6c569b80-f190-11e8-8331-f6fa9aef3861.png)

**Comment by hamishwillee** [comment]
@DonLakeFlyer Is this a QGC issue or a Firmware issue?

**Comment by hamishwillee** [comment]
@roseyangyu  This is a support question, not an issue. If Don's answer is not sufficient for you, then please expand on the question in our add to our [forum/chat channels](https://docs.px4.io/en/#support) (Github is for bugs, not questions).

**Comment by roseyangyu** [comment]
thank you for your help
