### ISSUE TITLE
tone_alarm is not compiled anymore

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#10925]
It seems that since the board reorg, tone_alarm is no longer getting compiled for SITL.

I wonder if anyone actually uses this because I have never used this and I don't know how it works.

FYI @dagar 
```
etc/init.d-posix/rcS: line 184: tone_alarm: command not found
```

**Comment by LorenzMeier** [comment]
We need to fix that. It was helpful because it emits strings for the tones it plays.
