### ISSUE TITLE
Teraranger laser on Pixhawk 2.1 requires to change the I2C BUS (PX4 1.8.2)

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Firmware#10932]
**Describe the bug**
On Pixhawk 2.1, we need to change the TERARANGER_BUS to `PX4_I2C_BUS_ONBOARD` for it to work on the I2C port (2) of the Pixhawk 2.1.

https://github.com/PX4/Firmware/blob/v1.8.2/src/drivers/distance_sensor/teraranger/teraranger.cpp#L74

**To Reproduce**
1. Connect the teraranger on the Pixhawk2.1 port (I2C 2) as in the documentation.
2. Enable the driver (SENS_EN_TRANGER)
3. Check the keyword 'distance' in the Analyze widdget
4. See that the distance sensor is not recognized.

**To Fix Temporary**
1. Change the teraranger bus in the code [teraranger.cpp#L74](
https://github.com/PX4/Firmware/blob/v1.8.2/src/drivers/distance_sensor/teraranger/teraranger.cpp#L74) by `PX4_I2C_BUS_ONBOARD`
2. Connect the teraranger on the Pixhawk2.1 port (I2C 2) as in the documentation.
3. Enable the driver (SENS_EN_TRANGER)
4. Check the keyword 'distance' in the Analyze widdget
5. See that the distance sensor is recognized and works

NOTE: Don't forget to power the laser with ~3S battery

**Firmware**
PX4 1.8.2

**Comment by DanielePettenuzzo** [comment]
There was a fix on master a couple months ago where the teraranger driver is started with the -a flag so that it can scan all available busses. This was not included in the latest release. It will probably be in the next 1.9 release. For now you would have to try the master branch to fix this issue.
