### ISSUE TITLE
Master branch firmware (fmu v3) cannot drive all sensors

### ISSUE THREAD

**Issue by cuhome** [PX4/Firmware#10961]
I downloaded the master firmware from qgc and found that it is not normal. It only recognizes ms5611 and other sensors are not being driven normally.
![fmu_v3](https://user-images.githubusercontent.com/31507501/49325986-60028200-f586-11e8-87b3-5f1f46ded269.png)
 I found a strange problem with a version number of 1.80dev instead of 1.81 or 1.82. But it shouldn't be an old firmware because it has added a new rgb driver.
fmu_v3
I tested pixhawk, cube, and pixhack, and have the same problem*

**Comment by jinger26** [comment]
@dagar @davids5

**Comment by dagar** [comment]
It's the `HW arch` string.

After the board refactor the fmu-v3 string came from the board model, instead of the previously hardcoded FMU_V2. As a result it's not entering rc.sensors.

**Comment by dagar** [comment]
This is fixed in https://github.com/PX4/Firmware/pull/10960, which gets rid of the majority of the startup version checks and in general should make things simpler.

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/Firmware/pull/10960

**Comment by cjk7713** [comment]
#10960
