### ISSUE TITLE
BUG: QGC does not show most parameters

### ISSUE THREAD

**Issue by baumanta** [PX4/Firmware#10972]
**Describe the bug**
QGC does not see most of the parameters

**To Reproduce**
1. Flash Pixhawk 4 with Firmware (any commit laster than 161cf7f5d92abba0b1b862d7aaa0939cb69d42bb)
2. Open QGC and try to search for a parameter MPC_...

**Expected behavior**
WI would expect to see and be able to modify the parameters over QGC

**Additional context**
I used git bisect to find the responsible commit and it seems to be this one:

commit 161cf7f5d92abba0b1b862d7aaa0939cb69d42bb
Author: Daniel Agar <daniel@agar.ca>
Date:   Fri Nov 30 21:01:29 2018 -0500
    shellcheck fix rc.autostart return and improve globbing

**Comment by dagar** [comment]
The multicopter controllers must not be starting. Looking...

**Comment by dagar** [comment]
The last commit (https://github.com/PX4/Firmware/commit/161cf7f5d92abba0b1b862d7aaa0939cb69d42bb) to commit shellcheck happy also broke nsh (nuttx).
