### ISSUE TITLE
HITL jMAVSim: MSG: Preflight Fail: Position unknown

### ISSUE THREAD

**Issue by JMshare** [PX4/Firmware#10988]
**Describe the bug**
The HITL with jMAVSim keeps printing 
`MSG: Preflight Fail: Position unknown.`.

It seems it lets me arm but immediately it says 
`MSG: Takeoff detected`,
`MSG: CRITICAL NAVIGATION FAILURE - CHECK SENSOR CALIBR`.

The sensors readings in the GCS are all over the place.
![screen shot 2018-12-05 at 13 11 00](https://user-images.githubusercontent.com/22155994/49516430-7ca5ff00-f891-11e8-98aa-9585e589f9e2.png)

Running on fmu-v5 with the current master [https://github.com/PX4/Firmware/commit/a5fa3eda302ca0ecd8b6938b3fbe940ae659a76c](http://url), following the instructions on [https://dev.px4.io/en/simulation/hitl.html](http://url), calling `./Tools/jmavsim_run.sh -q -d /dev/tty.usbmodem1 -b 921600 -r 250` on MAC.

I am using the HIL Quadcopter X airframe and QGroundControl v3.4.4.

I think it worked fine few days ago but not sure if I used the same QGC version then.

**EDIT**
In the current QGC developer build I get the same error and it looks like this.
![screenshot 2018-12-07 at 14 33 39](https://user-images.githubusercontent.com/22155994/49653670-94b28580-fa2d-11e8-9e58-7c87b7de1073.png)

**Comment by E666GT** [comment]
I meet the same error as you did. Have you get Any solution to it? Thanks

**Comment by JMshare** [comment]
Unfortunately not

**Comment by E666GT** [comment]
Thank you, if I got any progress I'll let you know

**Comment by ironman03** [comment]
I have same the proplem? you can help me? please

**Comment by julianoes** [comment]
When it happens, does the frame rate shown in the bottom left go to around 5 fps?

**Comment by ironman03** [comment]
I solved the problem, because I was not calibratedcompass properly. 
After calib, the copter has arm and no error.

**Comment by julianoes** [comment]
Great thanks for reporting this.

**Comment by JMshare** [comment]
> I solved the problem, because I was not calibrated compass properly.
> After calib, the copter has arm and no error.

You are saying I need to calibrate compass for HITL?
