### ISSUE TITLE
UAVCAN SETUP

### ISSUE THREAD

**Issue by Avysuarez** [PX4/Firmware#10984]
@dagar @mhkabir @RomanBapst @mrpollo @Tony3dr 
I have some issues with the uavcan setup, I followed the instructions for the setup and I've only managed to fly like this. The vehicle has some oscillations, when I accelerate is when it oscillates more and falls.
These are the parameters of the setup. 
UAVCAN Test
Assignment ESC's
Motor 1: 0
Motor 2: 1
Motor 3: 2
Motor 4: 3
Nodeid
Motor 1: 11
Motor 2: 12
Motor 3: 13
Motor 4: 14

![image](https://user-images.githubusercontent.com/12182176/49477313-60db2400-f7d1-11e8-9fd4-da2f04a65412.png)
![image](https://user-images.githubusercontent.com/12182176/49477353-88ca8780-f7d1-11e8-9bba-0678d64de01e.png)
![image](https://user-images.githubusercontent.com/12182176/49477376-9b44c100-f7d1-11e8-96e1-c5dc160cb7b4.png)
This is a flight video.
https://youtu.be/uKX-MOZG7ww

Any suggestions?

**Comment by jinger26** [comment]
@pavel-kirienko ?

**Comment by mhkabir** [comment]
The vehicle PIDs are tuned too high compared to the response characteristics of the ESC.

Seems like the either Myxas are much slower than the standard PWM ESCs the system is tuned with, or there is a massive latency somewhere in the chain.

**Comment by DanielePettenuzzo** [comment]
We had the same behaviour when we started. On our setup we had to increase the current_ctl_bw parameter to 0.12 after @pavel-kirienko 's suggestion. This will decrease the slew rate. If you still have this behaviour then you need to slightly detune the vehicle so that we don't demand as much from the esc's. 

Motor indexes and node ids look good.

Moreover can you please let Pavel know about any information that you think is missing in the myxa documentation.

**Comment by pavel-kirienko** [comment]
Increase `m.voltage_ramp` (start with 30) and set `m.current_ctl_bw` to 0.1. More info in the docs.

**Comment by Tony3dr** [comment]
We tested the UAVCAN copter but this time on the field, it flew better but it does not work in position and mission, the GPS registers up 24 sats. Even then it does not work.

This is a log of the flight:
https://review.px4.io/plot_app?log=5b3f576a-b07d-48ae-baab-d58f2561b710

Video of the flight:
https://www.youtube.com/watch?v=IUT5dC-MriM&feature=youtu.be

@dagar @mhkabir @pavel-kirienko @RomanBapst can someone check out the log and provide feedback.

Thanks, everyone.

**Comment by mhkabir** [comment]
Vibrations are pretty bad
