### ISSUE TITLE
fmu-v5: ERROR [pwm] can't open /dev/pwm_output0

### ISSUE THREAD

**Issue by JMshare** [PX4/Firmware#10981]
**Describe the bug**
All the ESCs start beeping on startup and never stop if the battery is connected.
In the QGroundControl Mavlink Console I type pwm info and get:
`ERROR [pwm] can't open /dev/pwm_output0`

My board is px4_fmu-v5. Compiling and uploading from the current master [https://github.com/PX4/Firmware/commit/e69049ec4183d820c6f716be1577df2ad07194b8](http://url)

I can say that it worked well around two weeks ago, and it works without this issue on the v1.8.2 release. 
![screen shot 2018-12-04 at 20 01 04](https://user-images.githubusercontent.com/22155994/49469487-90088a00-f7ff-11e8-9826-b55d793db28c.png)

**Drone (please complete the following information):**

* Pixhawk 4 on DJI F450 quad_x airframe

**Comment by dagar** [comment]
@JMshare this should be fixed in https://github.com/PX4/Firmware/pull/10983
Thanks for reporting.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/10983
