### ISSUE TITLE
SD Card maximum capacity.

### ISSUE THREAD

**Issue by Louisdirk** [PX4/Firmware#10994]
@LorenzMeier @simonegu @bkueng
I and trying to use 64GB Sandisk Extreme PRO U3 SDCard but failed to mount.
So what's the maximum capacity supported in NuttX?
Thank you.

**Comment by hamishwillee** [comment]
I don't know, but FYI, these are recommended: http://dev.px4.io/en/log/logging.html#sd-cards

**Comment by Louisdirk** [comment]
Yes, I saw that. I put 32GB one in the same board it's OK.
So I am confusing whether NuttX support higher capacity SDcard as my project requires.

**Comment by bkueng** [comment]
@davids5 can probably help.

**Comment by davids5** [comment]
I would say that nuttx is in compliance with SD Memory Card Specifications Version 2.0
So 32GB

`The Secure Digital eXtended Capacity (SDXC) format, announced in January 2009 and defined in version 3.01 of the SD specification, supports cards up to 2 TB (2048 GB), compared to a limit of 32 GB for SDHC cards in the SD 2.0 specification.`

**Comment by hamishwillee** [comment]
FYI, added information about SD card max size to the [user guide basic concepts](https://github.com/PX4/px4_user_guide/pull/399) and Devguide [logging topic](https://github.com/PX4/Devguide/pull/686).

**Comment by hamishwillee** [comment]
Closing as answered.

**Comment by Louisdirk** [comment]
Thank you all.
@davids5 When will version 3.01 of the SD specification be supported? Or can you please give me some advice if I implement it by myself?

**Comment by mhkabir** [comment]
@Louisdirk what is your use case?

**Comment by Louisdirk** [comment]
@davids5 That sounds enormous work. Let me start to understand the details of the Specification.
@mhkabir Just a case needs a mount of logs.

Thank you.

**Comment by Louisdirk** [comment]
@davids5 That sounds enormous work. Let me start to understand the details of the Specification.
@mhkabir Just a case needs a mount of logs.

Thank you.
