### ISSUE TITLE
Pixhawk 4 SD card issues.

### ISSUE THREAD

**Issue by Avysuarez** [PX4/Firmware#11034]
@dagar @mrpollo 
I have an issue with the pixhawk 4, does not detect the sd card and it does not save logs or missions, sometimes it sounds like it does not have an sd card. I already tried with different SD cards! I think its a hardware issue. 
this is a video
https://youtu.be/5lwJyh13hk8

**Comment by mrpollo** [comment]
@jinger26 have you heard of this before?

**Comment by bys1123** [comment]
Looks like it's because of sd card slot, please contact your distributor.

**Comment by Tony3dr** [comment]
@jinger26 can we please request a replacement? Thanks.
