### ISSUE TITLE
PREFLIGHT FAIL: NO MAG SENSOR 0

### ISSUE THREAD

**Issue by Addy0265** [PX4/Firmware#11045]
Hi all,
I just got a new Intel Aero RTF drone. Upon updating the flight controller firmware to 1.6.5, I get a preflight fail error in QGroundControl while calibrating the controller. I've tried updating the firware to the stable releases 1.7.3 and 1.8.1 but still I get the same error.
The flight controller used to work out of the box without any updates, so I am pretty sure the hardware is fine.
I found out by looking into other threads on this forum that this might happen because of the firmware version and 1.6.5 was concluded to be a stable version which had everything working fine. But, it doesnt work for me.

Kindly help!

**Comment by AlexisTM** [comment]
Can you ensure your external GPS/mag is connected?

**Comment by Addy0265** [comment]
Yes, I haven't touched the hardware.
It was working before updating the firmware (All sensors were fine, I even operated it using a RC)  and just after updating it, while running calibration in QGroundControl, it throws this error.

**Comment by julianoes** [comment]
@Addy0265 is this still a problem with 1.9?

**Comment by Addy0265** [comment]
> 
> 
> @Addy0265 is this still a problem with 1.9?

Hi, the issue was fixed.
There was sme connection issue with the GPS/MAG module.
I tried re-soldering the connections but it still didn't work.
So I replaced it wit another GPS module of the same make and I was able to calibrate it.
