### ISSUE TITLE
survey control lost at turn point

### ISSUE THREAD

**Issue by albert21martins** [PX4/Firmware#11041]
Performing a survey, we saw a weird behaviour at the first turn point. Reaching the turning point, the copter started to tumble violently and loose height. Quickly toggling to altitude and then position to stop the mission didn't stop the behaviour. The machine crashed into the ground tumbling, stayed grounded for a few seconds, and took off again, now hovering stable in position mode.

The tumbling seems to start with a jump of the yaw setpoint. At mission start the machine had a successfully yaw into flight direction however.

The tuning and general reaction tested before the survey in position and altitude mode seemed very stable.

Any hints on possible reasons are very appreciated!

https://review.px4.io/plot_app?log=c7976cfc-d926-4596-ae1a-44c4e216800b

**Comment by julianoes** [comment]
Sorry that we missed this. @albert21martins did you find out what happened?
