### ISSUE TITLE
Intel Aero flashing problem

### ISSUE THREAD

**Issue by altshuler** [PX4/Firmware#11049]
Hello,
I compiled the latest version from master for Intel Aero RTF.
I'm used this command:
make intel_aerofc-v1_default

After flashing the flight controller is not running and when
I tried to flash stable version the bootloader enters in infinite loop
when it tries different baudrates.  
My compiler version is 7.2.1.
Is somebody experienced with this issue ?

Best regards
Evgeny

**Comment by julianoes** [comment]
@altshuler sorry for the late response. Has this been resolved in the meantime?

**Comment by altshuler** [comment]
The issue is solved. 
Thanks !
