### ISSUE TITLE
logger orb subscribe multi error

### ISSUE THREAD

**Issue by cimbar** [PX4/Firmware#11065]
**Description**
In flight logs, orb_subscribe_multi error messages come out with many arguments. It relates with logger and there is no error message on QGC while flying. There wasn't this error at older flights with same SD card and the SD card is Samsung EVO so it shouldn't be a SD card read/write issue. Both v1.8.0 and v.1.8.2 Firmware versions were tried and same result. I couldn't see any influence of this error on flight but it is worrying. Is there any idea what's the source of this error and how can i solve this issue?

**Log Files and Screenshots**
Such examples:
https://logs.px4.io/plot_app?log=6cf7f9bf-fc44-4ea5-a2fd-1caff84fd214
https://logs.px4.io/plot_app?log=6f76d5cd-4698-4870-bedb-469bc7a5f1f5
![screenshot from 2018-12-18 11-37-32](https://user-images.githubusercontent.com/39306725/50142284-cf80ad00-02ba-11e9-8b8a-b0b9a83205f1.png)

**Comment by Louisdirk** [comment]
@cimbar. I had the same issue. @davids5, could you help to figure out the reason?

**Comment by davids5** [comment]
@cimbar , @Louisdirk - it look like there are not enough FD or there is a memory corruption that makes it seem that way. 

@dagar are there a parameters to turn on and off different logging streams? 

@cimbar posting your parameters would help troubleshoot this.

You can try to increase [CONFIG_NFILE_DESCRIPTORS](https://github.com/PX4/Firmware/blob/master/boards/px4/fmu-v3/nuttx-config/nsh/defconfig#L784)  by increments of 4 and see if that solves your problem. But keep in mind that may result in lower free RAM.

**Comment by dagar** [comment]
Yes it's `SDLOG_PROFILE` that controls the groups. You can't log everything at the same time unfortunately.
