### ISSUE TITLE
serial port test

### ISSUE THREAD

**Issue by manotroll** [PX4/Firmware#11085]
how can I test the serial ports of px4 in a simple way?
because m8n is working on the pc and is not on px4

**Comment by manotroll** [comment]
I bought another module because m6n is working although m8n funsione in the computer

**Comment by dlarue** [comment]
That's one way for it to go away....

**Comment by julianoes** [comment]
Sorry for the late response here.

How do you check "is working"? Can you do `gps status` in Mavlink shell to check what's up?

And when you connect to the GPS via computer, can you use the uBlox tool to check the settings of the GPS? Maybe some setting is incompatible with what the PX4 driver tries to do.

**Comment by manotroll** [comment]
so I bought another GPS and solved it but the same GPS still works on the pc

**Comment by dlarue** [comment]
what got me was how the GPS i had connected worked in Betaflight but would not work in PX4... This was on an omnibus

**Comment by manotroll** [comment]
But there's another problem with the
