### ISSUE TITLE
RunCam Split Mini in px4?

### ISSUE THREAD

**Issue by manotroll** [PX4/Firmware#11082]
is it possible to use the RunCam Split Mini in px4?
How do I make her serial connection on px4?
it can be shared with the miniosd since runcan would practically not receive external commands 
How do other open-source controllers already support RunCam not add this support to px4?

**Comment by mhkabir** [comment]
Please use discuss.px4.io for such questions.

**Comment by mhkabir** [comment]
From a first pass, it seems it would not be hard to add a driver for it.

**Comment by manotroll** [comment]
I do not know how to program
so how would it help?

**Comment by manotroll** [comment]
RunCam Support (Customer Services)

Dec 22, 10:08 CST
Sorry for that Split mini  doesn't support PWM control. 

Regards,
Stella T.
RunCam Customer Service

as it does not support pwm control would not it be possible to add its support?
if it was compatible many would use it I already think that the controllers that supports px4 have more serial than others
