### ISSUE TITLE
New simulator TCP link do not work with Windows Cygwin Toolchain

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#11090]
I saw @julianoes updated the simulator_mavlink.cpp file yesterday. #10648 Thanks for your work.

And I tried in Cygwin toolchain, seems not work well.

error:
```bash
WARN  [simulator] Failed sending mavlink message: Address family not supported by protocol
```

![image](https://user-images.githubusercontent.com/4748411/50377416-01e22f80-0658-11e9-857d-e5831cc31e01.png)

**Comment by bys1123** [comment]
I think this bug is around here:

[simulator_mavlink.cpp](https://github.com/PX4/Firmware/blob/a1fc44d1f03969614a22019ab61af61848a271d7/src/modules/simulator/simulator_mavlink.cpp)
start line 654:
```
	struct sockaddr_in _myaddr {};
	_myaddr.sin_family = AF_INET;
	_myaddr.sin_addr.s_addr = htonl(INADDR_ANY);
	_myaddr.sin_port = htons(port);
```

**Comment by MaEtUgR** [comment]
When I revert simulator and jMAVsim back to UDP it's even worse. I don't see the `Address faily not supported error` anymore but that's probably because the simulator is hanging. At least when I try to use `uorb top` everything freezes completely.

**Comment by TSC21** [comment]
It can be related with the lockstep instead. @julianoes

**Comment by julianoes** [comment]
I think I had fixed this and maybe stashed it away. It could be that we need to use `send(` instead of `sendto` on Win. Let me check.
