### ISSUE TITLE
reset SITL pragmatically  

### ISSUE THREAD

**Issue by walid19** [PX4/Firmware#11107]
I am using px4 with sitl , i need to restart the drone position after it touches some obstacle, in the same time i need to reset the sitl node to update the drone states, how can i reset the SITL node programmatically?

**Comment by julianoes** [comment]
Sorry, that's currently not possible.

**Comment by heleidsn** [comment]
> I am using px4 with sitl , i need to restart the drone position after it touches some obstacle, in the same time i need to reset the sitl node to update the drone states, how can i reset the SITL node programmatically?

Hello, did you solved this problem? I have the same problem...

**Comment by julianoes** [comment]
As written, currently not implemented.
