### ISSUE TITLE
Question with land detector

### ISSUE THREAD

**Issue by KeyneZzz** [PX4/Firmware#11108]
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L167

Why is it a less than sign? According to the note, if landed time more than the threshold, it should be a certain landed state for a long time so using a widen  acceptance.

**Comment by julianoes** [comment]
@RomanBapst would be good if you could have a look here.

**Comment by julianoes** [comment]
@KeyneZzz do you mind checking this again? And then it would be good to share a link with a git hash, so that the line doesn't change when the file changes (permanent link).

**Comment by julianoes** [comment]
Closing until we get an answer.
