### ISSUE TITLE
!!!Bug: Unable to create new file on PX4 file system!!!

### ISSUE THREAD

**Issue by xiaofyao** [PX4/Firmware#11113]
**Describe the bug**
Unable to create new file on PX4 file system.
When I used FTP to upload file to PX4 file system, I found that I could not create a new file on PX4 file system.
**To Reproduce**
call this function to create a new file on PX4 file system, but failed:
`open(filename,  O_CREAT | O_EXCL | O_WRONLY, PX4_O_MODE_666);`

**Comment by julianoes** [comment]
Sorry for the late answer. In what directory did you try to create the file? What is `filename` for your case?

**Comment by julianoes** [comment]
Closing because there was no follow up.
