### ISSUE TITLE
Unable to upload v1.8.2 via QGroundcontrol

### ISSUE THREAD

**Issue by Seeelefant** [PX4/Firmware#11148]
**Describe the bug**
This one is a followup to [Unable to build v1.8.2 from source](https://github.com/PX4/Firmware/issues/11146):

Thanks, at least the make px4fmu-v3_default was working.

- Trying  to upload the generated file via qgroundcontrol reproducible leads to

![image](https://user-images.githubusercontent.com/30323691/50798152-96df5c80-12d7-11e9-9e8d-73e686f8f1e5.png)

- Trying  to upload the "last stable version 1.8.2" via qgroundcontrol always flashes (without any further problems) version 1.8.1

- Your  master brach seems to bee quite unstable, whereas the recommended approach is to introduce a development branch and keep the master branch stable according to A successful Git branching model

Please advice
--Seeelefant

**Expected behavior**

**Log Files and Screenshots**
*Always* provide a link to the flight log file:
- Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/getting_started/flight_reporting.html)).
- Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/).

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

**Additional context**

**Comment by julianoes** [comment]
Hi @Seeelefant has this been resolved in the meantime?

**Comment by Seeelefant** [comment]
Hi @julianoes,
this has been resolved. It was a (timing ?) problem with intermediate USB-hub. After connecting directly to my PC it was working.
Best
--Seeelefant

**Comment by julianoes** [comment]
Good to know, thanks for the note @Seeelefant!
