### ISSUE TITLE
Low data update rate on aero

### ISSUE THREAD

**Issue by HowICanBeWithYou** [PX4/Firmware#11168]
I use the Intel-Aero Drone.
At first ,I flashed the firmware by fallowing https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-setup,everything works well. However , when i want to change the code to fit the needs of our project , i found that all update rate of data  become lowly. So I upload the firmware from https://github.com/intel-aero/Firmware and do not change any things. But I got the same results. All the data update slowly in different level. I need to use the data of distance sensor ,but the data update so slow that did not match the real distance.
Do I need change something before I upload the firmware.
I'm a beginner at this area,please give some advice.
Thanks in advance!

**Comment by julianoes** [comment]
I'm not sure who still can help you with the Intel Aero. Intel doesn't seem to be supporting it anymore and the product itself is discontinuied.
