### ISSUE TITLE
mpu9250 not starting on px4_fmu-v4 (and likely others)

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#11162]
This is likely more fallout from expanding the existing mpu9250 driver to support the icm20948 (https://github.com/PX4/Firmware/pull/10116) and follow up fixes (https://github.com/PX4/Firmware/pull/11020)

Noticed by Jenkins (http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-update_src%2Flib%2Fecl/70/pipeline/79/#step-102-log-53).

![image](https://user-images.githubusercontent.com/84712/50773809-ce122700-125f-11e9-8d06-27bb7b948c72.png)

FYI @dakejahl @DanielePettenuzzo @flochir

**Comment by dakejahl** [comment]
Do these buses have the mpu9250/6500/20948 on them? I noticed the driver was now trying to start on every bus and just failing if device not present.

**Comment by dagar** [comment]
That's an mRo pixracer on the hardware test rack with only an mRo GPS connected (https://store.mrobotics.io/mRo-GPS-u-Blox-Neo-M8N-HMC5983-Compass-p/mro-gps003-mr.htm), dronecode debug (SWD + serial console), and USB power.

**Comment by dakejahl** [comment]
Does that variant have the mpu9250 on i2c? That screenshot is of i2c start failing

**Comment by dakejahl** [comment]
Looks like the mpu9250 is started without a `bus_id` opt arg and thus it attempts to start on all busses.
https://github.com/PX4/Firmware/blob/master/boards/px4/fmu-v4/init/rc.board#L84-L89

**Comment by dakejahl** [comment]
![selection_014](https://user-images.githubusercontent.com/37091262/50785002-99f13300-126c-11e9-8af6-be70182add43.png)
And bus 3 corresponds to `MPU9250_BUS_SPI_INTERNAL`

**Comment by dakejahl** [comment]
This is with a pixracer, not sure the version (not printed on the silk screen) but it's one of those little red boards

**Comment by flochir** [comment]
Omitting the bus on the driver call shouldn't cause a fail though, just a chance of starting an unintended device with maybe wrong parameters.

**Comment by flochir** [comment]
@dakejahl Ok, I see it now. I think that happens now because the probe() function of mpu9250_i2c.cpp was disabled in #11020. It gets called implicitly by interface->init() in line 232 of main.cpp. This way, the driver itself only got instanciated when the device was already detected, and a fail of init() actually meant a fail. Now that can also be caused by the device not being present.

**Comment by flochir** [comment]
Added a new whoami-based version of device probe in I2C interface probe to PR: #11173
@dagar @dakejahl Can you try if this fixes the issue?

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/Firmware/pull/11173
