### ISSUE TITLE
v1.9.0 Release notes + Changelog

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#11175]
Team Work :tada: 

![team work](https://media.giphy.com/media/l3q2Wl7Wpz09Z5hfi/giphy-downsized.gif)

Getting ready for v1.9.0 it's time to put together the list of changes that went into the making of v1.9.0 (more changes are still coming in the next few days), this post is meant for discussion on what goes into the release notes and the summary section of the release notes.

### READ BELOW
:arrow_down: :arrow_down: :arrow_down: 

- - -
# Release notes
WIP

# Change Log
# Changelog
## [v1.9.0](https://github.com/PX4/Firmware/tree/v1.9.0) (2019-04-10)
[Full Changelog](https://github.com/PX4/Firmware/compare/v1.8.2...v1.9.0)

**Implemented enhancements:**

* Oversampling rate for MPL3115A2 pressure sensor [\#11296](https://github.com/PX4/Firmware/issues/11296)
* Appveyor: Enable build matrix for parallel CI targets [\#11802](https://github.com/PX4/Firmware/pull/11802) ([MaEtUgR](https://github.com/MaEtUgR))
* Altitude FlightTask based on jerk-limited trajectory generator [\#11744](https://github.com/PX4/Firmware/pull/11744) ([bresch](https://github.com/bresch))
* commander: PreflightCheck: check for 'airspeed' topic only on the 'airspeedCheck' [\#11722](https://github.com/PX4/Firmware/pull/11722) ([TSC21](https://github.com/TSC21))
* Update submodule ecl to latest Sat Mar 23 12:39:14 UTC 2019 [\#11710](https://github.com/PX4/Firmware/pull/11710) ([dagar](https://github.com/dagar))
* NuttX include Kconfiglib \(python\) and compress all defconfigs [\#11672](https://github.com/PX4/Firmware/pull/11672) ([dagar](https://github.com/dagar))
* Obstacle Avoidance prearm checks and log health status [\#11638](https://github.com/PX4/Firmware/pull/11638) ([cmic0](https://github.com/cmic0))
* containers add Queue and testing [\#11574](https://github.com/PX4/Firmware/pull/11574) ([dagar](https://github.com/dagar))
* ekf2: Split static pressure correction into separate RH and LH ellipsoids [\#11545](https://github.com/PX4/Firmware/pull/11545) ([priseborough](https://github.com/priseborough))
* Reintroduce slow down when landing manually [\#11540](https://github.com/PX4/Firmware/pull/11540) ([MaEtUgR](https://github.com/MaEtUgR))
* Modularize Attitude Control [\#11308](https://github.com/PX4/Firmware/pull/11308) ([MaEtUgR](https://github.com/MaEtUgR))
* \[WIP\] QMC5883 Magnetometer Driver [\#11140](https://github.com/PX4/Firmware/pull/11140) ([dlwalter](https://github.com/dlwalter))

**Fixed bugs:**

* ECL breaks gazebo when there is a lidar [\#11812](https://github.com/PX4/Firmware/issues/11812)
* Continuous "Data link lost" messages in SITL [\#11794](https://github.com/PX4/Firmware/issues/11794)
* Log stopped after first flight with SDLOG\_MODE = 2 [\#11774](https://github.com/PX4/Firmware/issues/11774)
* sitl\_gazebo build broken on macOS [\#11757](https://github.com/PX4/Firmware/issues/11757)
* Spurious MANUAL CONTROL LOST on Pixracer [\#11739](https://github.com/PX4/Firmware/issues/11739)
* NuttX builds on MacOS and Windows always start from scratch [\#11734](https://github.com/PX4/Firmware/issues/11734)
* Firmware upload on macOS broken [\#11720](https://github.com/PX4/Firmware/issues/11720)
* Firmware upload often on fails on FMU v4/v5 with timeout or invalid operation [\#11704](https://github.com/PX4/Firmware/issues/11704)
* fmu-v3/4/5 not building on Arch Linux [\#11702](https://github.com/PX4/Firmware/issues/11702)
* Accelerometer calibration problem on FMUV5 [\#11695](https://github.com/PX4/Firmware/issues/11695)
* Propellers small rotation during rebooting from QGC on copter [\#11685](https://github.com/PX4/Firmware/issues/11685)
* High CPU load on Pixhawk 4 \(fmu-v5\) [\#11604](https://github.com/PX4/Firmware/issues/11604)
* Must reboot Pixhawk Between Missions [\#11588](https://github.com/PX4/Firmware/issues/11588)
* Pixhawk 4 and Pikhawk 4mini v5 not disarming. [\#11569](https://github.com/PX4/Firmware/issues/11569)
* Takeoff not responding properly in position control [\#11452](https://github.com/PX4/Firmware/issues/11452)
* LPE Q Estimator external heading fusion not handling lack of external data [\#11433](https://github.com/PX4/Firmware/issues/11433)
* Issue with Master\_vehicle crash [\#11408](https://github.com/PX4/Firmware/issues/11408)
* SITL intermittent failure: \[Err\] \[gazebo\_mavlink\_interface.cpp:1018\] poll timeout [\#11380](https://github.com/PX4/Firmware/issues/11380)
* Tangent exit not working correctly for Fixed Wing loiters [\#11317](https://github.com/PX4/Firmware/issues/11317)
* CI stack check timeout [\#11289](https://github.com/PX4/Firmware/issues/11289)
* FW SITL intermittent failure [\#11257](https://github.com/PX4/Firmware/issues/11257)
* crazyflie 2.0 qgc comm not working [\#11226](https://github.com/PX4/Firmware/issues/11226)
* Multicopter takes off in HOLD on ground [\#11197](https://github.com/PX4/Firmware/issues/11197)
* HITL regression: sensors running and publishing [\#11179](https://github.com/PX4/Firmware/issues/11179)
* HITL regression with jMAVSim [\#11165](https://github.com/PX4/Firmware/issues/11165)
* mpu9250 not starting on px4\_fmu-v4 \(and likely others\) [\#11162](https://github.com/PX4/Firmware/issues/11162)
* remove std::vector usage [\#11152](https://github.com/PX4/Firmware/issues/11152)
* Unable to biuld px4 on beaglebone blue nativ [\#11150](https://github.com/PX4/Firmware/issues/11150)
* PX4 SITL mission tests intermittent failures [\#11144](https://github.com/PX4/Firmware/issues/11144)
* mavlink 0 \(USB\) abnormal cpu usage [\#11125](https://github.com/PX4/Firmware/issues/11125)
* Commander spams the nsh console on SITL [\#11118](https://github.com/PX4/Firmware/issues/11118)
* Poor Fixed Wing flight performance in v1.9-alpha \(SITL\) [\#11116](https://github.com/PX4/Firmware/issues/11116)
* Snapdragon build fails at runtime \(related to time functions\) [\#11110](https://github.com/PX4/Firmware/issues/11110)
* Increase stacks in drivers identified by stackcheck builds [\#11818](https://github.com/PX4/Firmware/pull/11818) ([jkflying](https://github.com/jkflying))
* Update submodule ecl to latest Mon Apr 8 13:38:20 UTC 2019 [\#11814](https://github.com/PX4/Firmware/pull/11814) ([dagar](https://github.com/dagar))
* drivers/px4fmu initialize all arrays [\#11780](https://github.com/PX4/Firmware/pull/11780) ([dagar](https://github.com/dagar))
* revert FlightTasks: fix mission DO\_CHANGE\_SPEED [\#11779](https://github.com/PX4/Firmware/pull/11779) ([bresch](https://github.com/bresch))
* fw\_pos\_control\_l1 reset internal takeoff and landing state when arming [\#11762](https://github.com/PX4/Firmware/pull/11762) ([dagar](https://github.com/dagar))
* cmake nuttx use wrapper script to call "make olddefconfig" [\#11715](https://github.com/PX4/Firmware/pull/11715) ([dagar](https://github.com/dagar))
* PX4Accelerometer apply sensor rotation before scaling [\#11713](https://github.com/PX4/Firmware/pull/11713) ([dagar](https://github.com/dagar))
* nuttx: update submodule [\#11705](https://github.com/PX4/Firmware/pull/11705) ([julianoes](https://github.com/julianoes))
* Trajectory generator fixes [\#11647](https://github.com/PX4/Firmware/pull/11647) ([bresch](https://github.com/bresch))
* FlightTaskAuto - Recover position control after local position reset [\#11636](https://github.com/PX4/Firmware/pull/11636) ([bresch](https://github.com/bresch))
* Use ecl library version with recent bug fixes and enhancements. [\#11630](https://github.com/PX4/Firmware/pull/11630) ([priseborough](https://github.com/priseborough))
* navigator fix FW loiter tangent exit [\#11576](https://github.com/PX4/Firmware/pull/11576) ([dagar](https://github.com/dagar))
* VTOL: fix roll inversion [\#11382](https://github.com/PX4/Firmware/pull/11382) ([jlecoeur](https://github.com/jlecoeur))

**Closed issues:**

* Logger out of FD \(VTOL\) [\#11810](https://github.com/PX4/Firmware/issues/11810)
* Pixhawk4 won't bootup with current master [\#11786](https://github.com/PX4/Firmware/issues/11786)
* Don`t work roslaunch px4 posix\_sitl.launch [\#11761](https://github.com/PX4/Firmware/issues/11761)
* esc.cpp : esc\_status\_sub\_cb\(const uavcan::ReceivedDataStructure\<uavcan::equipment::esc::Status\> &msg\) functionality [\#11746](https://github.com/PX4/Firmware/issues/11746)
* PX4 "Recject Auto mission" and "Reject auto takeoff" [\#11741](https://github.com/PX4/Firmware/issues/11741)
* Airspeed sensor \( MS5611 \) reading varies up to 3m/s in a closed room [\#11740](https://github.com/PX4/Firmware/issues/11740)
* Incorrect Dev Call info on PX4 / Dronecode properties [\#11735](https://github.com/PX4/Firmware/issues/11735)
* MINIMOSD throttle still 0%, flight mode doens't change [\#11733](https://github.com/PX4/Firmware/issues/11733)
* Disable F7 cache and check Si version and Param to force on [\#11731](https://github.com/PX4/Firmware/issues/11731)
* UTM\_GLOBAL\_POSITION only sent in case of MavLink connection to QGC [\#11718](https://github.com/PX4/Firmware/issues/11718)
* Weekly Digest \(17 March, 2019 - 24 March, 2019\) [\#11714](https://github.com/PX4/Firmware/issues/11714)
* DSDL compiler error [\#11711](https://github.com/PX4/Firmware/issues/11711)
* ACCELS INCONSISTENT - CHECK CAL on Pixhawk4 [\#11709](https://github.com/PX4/Firmware/issues/11709)
* The SF11/C is not publish the distance data when the PX4Flow Smart Camera is connected. [\#11690](https://github.com/PX4/Firmware/issues/11690)
* serial/generate\_config.py YAML deprecation warning [\#11666](https://github.com/PX4/Firmware/issues/11666)
* UTM\_GLOBAL\_POSITION Message for collision avoidance is not send on Pixhawk4 with FW 1.9.0beta [\#11656](https://github.com/PX4/Firmware/issues/11656)
* Iris optical flow can not take off in Gazebo simulator [\#11648](https://github.com/PX4/Firmware/issues/11648)
* Matlab px4 firmware bug on build [\#11645](https://github.com/PX4/Firmware/issues/11645)
* Weekly Digest \(3 March, 2019 - 10 March, 2019\) [\#11614](https://github.com/PX4/Firmware/issues/11614)
* SITL, Model: plane, \[Err\] \[gazebo\_mavlink\_interface.cpp:1166\] Error opening serial device: open: No such file or directory [\#11598](https://github.com/PX4/Firmware/issues/11598)
* Type of file airframe + error when building code UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 38: ordinal not in range\(128\) [\#11585](https://github.com/PX4/Firmware/issues/11585)
* Bug: velocity setpoint goes out of 0 during hovering with smooth position control in manual pos control [\#11583](https://github.com/PX4/Firmware/issues/11583)
* Cannot build code: make: \*\*\* \[px4\_fmu-v3\_default\] Error 1 [\#11578](https://github.com/PX4/Firmware/issues/11578)
* Weekly Digest \(24 February, 2019 - 3 March, 2019\) [\#11577](https://github.com/PX4/Firmware/issues/11577)
* Gazebo SITL simulation build fail in macOS [\#11553](https://github.com/PX4/Firmware/issues/11553)
* Error make aerofc-v1\_default on px4\_atomic.h [\#11552](https://github.com/PX4/Firmware/issues/11552)
* Wrong UDP Port when using -t argument [\#11544](https://github.com/PX4/Firmware/issues/11544)
* Weekly Digest \(17 February, 2019 - 24 February, 2019\) [\#11532](https://github.com/PX4/Firmware/issues/11532)
* CI: Xvfb not starting [\#11523](https://github.com/PX4/Firmware/issues/11523)
* some hardware communication problem [\#11510](https://github.com/PX4/Firmware/issues/11510)
* Replay is broken in master [\#11501](https://github.com/PX4/Firmware/issues/11501)
* NXP FMUK66 - RGB LED not working when Pixhawk 4 GPS \(with LED\) plugged in [\#11500](https://github.com/PX4/Firmware/issues/11500)
* vtol front transition height drop [\#11474](https://github.com/PX4/Firmware/issues/11474)
* Tilting angle parameter range check [\#11473](https://github.com/PX4/Firmware/issues/11473)
* AUX1 pass through from RC channel !!! [\#11464](https://github.com/PX4/Firmware/issues/11464)
*  Engines not running [\#11461](https://github.com/PX4/Firmware/issues/11461)
* Problem in spawning multiple drones in Gazebo [\#11458](https://github.com/PX4/Firmware/issues/11458)
*  I tried to compile the 1.8 version program.Use this command “make px4fmu-v5\_default” 。I need your help. It reminds me of this information.thanks！ [\#11450](https://github.com/PX4/Firmware/issues/11450)
* Mavros not able to communicate with PX4 SITL after the latest upgrades. [\#11443](https://github.com/PX4/Firmware/issues/11443)
* CI Firmware/master is broken [\#11440](https://github.com/PX4/Firmware/issues/11440)
* Weekly Digest \(3 February, 2019 - 10 February, 2019\) [\#11425](https://github.com/PX4/Firmware/issues/11425)
* Not stable in position mode [\#11413](https://github.com/PX4/Firmware/issues/11413)
* sitl with gazebo: error opening serial device [\#11393](https://github.com/PX4/Firmware/issues/11393)
* Snapdragon flight Machine Vision SDK Version Compatibility [\#11375](https://github.com/PX4/Firmware/issues/11375)
* "tests time" hangs and fails to recover in current Firmware/master [\#11361](https://github.com/PX4/Firmware/issues/11361)
* EKF2 local\_position doesn't initialize without mag sensor [\#11359](https://github.com/PX4/Firmware/issues/11359)
* MAVLink ATTITUDE and other messages empty when vision is being fused [\#11358](https://github.com/PX4/Firmware/issues/11358)
* fmu handle sensor\_reset, peripheral\_reset, i2c in board [\#11348](https://github.com/PX4/Firmware/issues/11348)
* Authentication [\#11345](https://github.com/PX4/Firmware/issues/11345)
* Failsafe Robustness Tests [\#11344](https://github.com/PX4/Firmware/issues/11344)
* Flight Mode Tests / Missions [\#11343](https://github.com/PX4/Firmware/issues/11343)
* Navigator Rewrite [\#11342](https://github.com/PX4/Firmware/issues/11342)
* Pixhack v5: Main PWM Glitch [\#11326](https://github.com/PX4/Firmware/issues/11326)
* Gazebo SITL and PX4 not handling simulated wind correctly [\#11319](https://github.com/PX4/Firmware/issues/11319)
* Weekly Digest \(20 January, 2019 - 27 January, 2019\) [\#11307](https://github.com/PX4/Firmware/issues/11307)
*  uavcan\_main.hpp - error in \_master\_timer on fmu-v5 but not fmu-v2; [\#11304](https://github.com/PX4/Firmware/issues/11304)
* CI ROS test timeout [\#11290](https://github.com/PX4/Firmware/issues/11290)
* Replace the atomic `hrt\_elapsed\_time` call with a non-atomic call [\#11245](https://github.com/PX4/Firmware/issues/11245)
* Weekly Digest \(12 January, 2019 - 19 January, 2019\) [\#11244](https://github.com/PX4/Firmware/issues/11244)
* Ekf2 doesn't use data from sensors immediatly [\#11240](https://github.com/PX4/Firmware/issues/11240)
* Pixhack v5 does not boot config related [\#11223](https://github.com/PX4/Firmware/issues/11223)
* Multi-Vehicle Simulation Error [\#11217](https://github.com/PX4/Firmware/issues/11217)
* CUAVv5 upload error? [\#11208](https://github.com/PX4/Firmware/issues/11208)
* px4\_fmu-v2 cannot be the first argument. [\#11204](https://github.com/PX4/Firmware/issues/11204)
* Gazebo Core Dump [\#11186](https://github.com/PX4/Firmware/issues/11186)
* Problem installing Gazebo on Ubuntu "FAILED: CMakeFiles/gazebo\_imu\_plugin.dir/src/gazebo\_imu\_plugin.cpp.o /usr/bin/c++" [\#11182](https://github.com/PX4/Firmware/issues/11182)
* Problem installing Gazebo "FAILED: CMakeFiles/gazebo\_imu\_plugin.dir/src/gazebo\_imu\_plugin.cpp.o /usr/bin/c++" [\#11181](https://github.com/PX4/Firmware/issues/11181)
* Hi, has any one been able to run PX4 on beaglebone blue? [\#11149](https://github.com/PX4/Firmware/issues/11149)
* Unable to build v1.8.2 from source [\#11146](https://github.com/PX4/Firmware/issues/11146)
* Snapdragon timestamp offset [\#11134](https://github.com/PX4/Firmware/issues/11134)
* Compilation in cygwin unable to find external include path mentioned in cmakelist [\#11119](https://github.com/PX4/Firmware/issues/11119)
* Mavros setpoint\_raw/attitude [\#11103](https://github.com/PX4/Firmware/issues/11103)
* ERROR \[px4\] Error opening startup file, does not exist: etc/init.d/rcS [\#11100](https://github.com/PX4/Firmware/issues/11100)

**Merged pull requests:**

* Add back pwm out sim module so HITL simulation works again. [\#11826](https://github.com/PX4/Firmware/pull/11826) ([lovettchris](https://github.com/lovettchris))
* logger reduce default topics [\#11813](https://github.com/PX4/Firmware/pull/11813) ([dagar](https://github.com/dagar))
* omnibus: fix unreliable SD card access [\#11808](https://github.com/PX4/Firmware/pull/11808) ([bkueng](https://github.com/bkueng))
* cmake use ${PYTHON\_EXECUTABLE} for mixer test [\#11807](https://github.com/PX4/Firmware/pull/11807) ([dagar](https://github.com/dagar))
* mixer move test\_mixer\_multirotor into cmake [\#11806](https://github.com/PX4/Firmware/pull/11806) ([dagar](https://github.com/dagar))
* vscode add empty kit to quiet user prompt [\#11805](https://github.com/PX4/Firmware/pull/11805) ([dagar](https://github.com/dagar))
* Appveyor cleanup [\#11804](https://github.com/PX4/Firmware/pull/11804) ([MaEtUgR](https://github.com/MaEtUgR))
* Update mavlink submodule v2.0 to latest Sun Apr 7 09:26:15 UTC 2019 [\#11803](https://github.com/PX4/Firmware/pull/11803) ([dagar](https://github.com/dagar))
* make: tests\_avoidance add prerequisite [\#11797](https://github.com/PX4/Firmware/pull/11797) ([lamping7](https://github.com/lamping7))
* Standardising mavlink message strings [\#11796](https://github.com/PX4/Firmware/pull/11796) ([potaito](https://github.com/potaito))
* commander: fix toggling datalink lost and regained [\#11795](https://github.com/PX4/Firmware/pull/11795) ([julianoes](https://github.com/julianoes))
* sitl\_gazebo: update submodule [\#11793](https://github.com/PX4/Firmware/pull/11793) ([julianoes](https://github.com/julianoes))
* fmuv5:Move stage 0 dache disable to later in boot [\#11791](https://github.com/PX4/Firmware/pull/11791) ([davids5](https://github.com/davids5))
* init.d-posix: re-use rc.logging [\#11790](https://github.com/PX4/Firmware/pull/11790) ([julianoes](https://github.com/julianoes))
* NuttX delete accidental tone\_alarm copy [\#11784](https://github.com/PX4/Firmware/pull/11784) ([dagar](https://github.com/dagar))
* Update submodule sitl\_gazebo to latest Wed Apr 3 12:38:08 UTC 2019 [\#11783](https://github.com/PX4/Firmware/pull/11783) ([dagar](https://github.com/dagar))
* Update submodule mavlink v2.0 to latest Wed Apr 3 12:38:14 UTC 2019 [\#11782](https://github.com/PX4/Firmware/pull/11782) ([dagar](https://github.com/dagar))
* cmake nuttx use defconfig matching config label if available [\#11781](https://github.com/PX4/Firmware/pull/11781) ([dagar](https://github.com/dagar))
* cmake fix NuttX and ROMFS build dependencies [\#11777](https://github.com/PX4/Firmware/pull/11777) ([dagar](https://github.com/dagar))
* logger increase stack 3600 -\> 3700 bytes [\#11775](https://github.com/PX4/Firmware/pull/11775) ([dagar](https://github.com/dagar))
* VSCode: move vscode specific .gitignore entries to the folder [\#11773](https://github.com/PX4/Firmware/pull/11773) ([MaEtUgR](https://github.com/MaEtUgR))
* FlightTasks: fix mission DO\_CHANGE\_SPEED [\#11772](https://github.com/PX4/Firmware/pull/11772) ([julianoes](https://github.com/julianoes))
* multicopter land detector: make threshold for \_has\_low\_thrust [\#11771](https://github.com/PX4/Firmware/pull/11771) ([RomanBapst](https://github.com/RomanBapst))
* M7 dcache ctrl via a parameter [\#11769](https://github.com/PX4/Firmware/pull/11769) ([davids5](https://github.com/davids5))
* Whitespace fixes - Delete trailing whitespace, newlines to quiet git hooks [\#11766](https://github.com/PX4/Firmware/pull/11766) ([mcsauder](https://github.com/mcsauder))
* rcS: add airframe parameter versioning and extend SYS\_AUTOCONFIG [\#11760](https://github.com/PX4/Firmware/pull/11760) ([bkueng](https://github.com/bkueng))
* \[LGTM\] Using "NewStyle" class for Python [\#11756](https://github.com/PX4/Firmware/pull/11756) ([AlexisTM](https://github.com/AlexisTM))
* Stop RC Loss alarm on reconnect [\#11745](https://github.com/PX4/Firmware/pull/11745) ([potaito](https://github.com/potaito))
* adis16497: fix TEMP\_OUT scaling [\#11742](https://github.com/PX4/Firmware/pull/11742) ([ThijsRay](https://github.com/ThijsRay))
* mavlink autopilot\_version: add vendor version [\#11730](https://github.com/PX4/Firmware/pull/11730) ([bkueng](https://github.com/bkueng))
* vtol\_att\_control: remove unused subscription variable [\#11727](https://github.com/PX4/Firmware/pull/11727) ([CarlOlsson](https://github.com/CarlOlsson))
* SITL: interim fix for replay [\#11725](https://github.com/PX4/Firmware/pull/11725) ([julianoes](https://github.com/julianoes))
* start px4flow after all rangefinders \(including the ones going throug… [\#11724](https://github.com/PX4/Firmware/pull/11724) ([DanielePettenuzzo](https://github.com/DanielePettenuzzo))
* added aux6 RC channel [\#11723](https://github.com/PX4/Firmware/pull/11723) ([RomanBapst](https://github.com/RomanBapst))
* px\_uploader.py: check for pyserial [\#11721](https://github.com/PX4/Firmware/pull/11721) ([julianoes](https://github.com/julianoes))
* px\_uploader.py: write timeout workaround [\#11719](https://github.com/PX4/Firmware/pull/11719) ([julianoes](https://github.com/julianoes))
* px4\_fmu-v3 include icm20948 \(Here+ compass\) [\#11712](https://github.com/PX4/Firmware/pull/11712) ([dagar](https://github.com/dagar))
* replay: fix issue when original logfile had topics with zero timstamps [\#11708](https://github.com/PX4/Firmware/pull/11708) ([CarlOlsson](https://github.com/CarlOlsson))
* update matrix library submodule [\#11706](https://github.com/PX4/Firmware/pull/11706) ([mrivi](https://github.com/mrivi))
* vscode updates [\#11699](https://github.com/PX4/Firmware/pull/11699) ([dagar](https://github.com/dagar))
* mavlink\_receiver: ignore BATTERY\_STATUS of other system [\#11698](https://github.com/PX4/Firmware/pull/11698) ([okalachev](https://github.com/okalachev))
* mc\_pos\_control: correct tilt parameter limits [\#11696](https://github.com/PX4/Firmware/pull/11696) ([MaEtUgR](https://github.com/MaEtUgR))
* fix bmi055: increase DLPF from 62.5 to 500 [\#11694](https://github.com/PX4/Firmware/pull/11694) ([bkueng](https://github.com/bkueng))
* New naming convention of variables linked to a parameter [\#11686](https://github.com/PX4/Firmware/pull/11686) ([bresch](https://github.com/bresch))
* logging: add SDLOG\_MODE = -1 to disable logging completely [\#11684](https://github.com/PX4/Firmware/pull/11684) ([bkueng](https://github.com/bkueng))
* px4\_fmuv5:Extend probes to CAP pins [\#11679](https://github.com/PX4/Firmware/pull/11679) ([davids5](https://github.com/davids5))
* update cmake NuttX helper save behaviour \(oldconfig, menuconfig, etc\) [\#11678](https://github.com/PX4/Firmware/pull/11678) ([dagar](https://github.com/dagar))
* Tools/upload\_log: change default upload to public flightreport [\#11675](https://github.com/PX4/Firmware/pull/11675) ([JohannesBrand](https://github.com/JohannesBrand))
* ist8310.cpp: remove unused variable\(Clean up\) [\#11673](https://github.com/PX4/Firmware/pull/11673) ([xdwgood](https://github.com/xdwgood))
* vscode minor updates [\#11671](https://github.com/PX4/Firmware/pull/11671) ([dagar](https://github.com/dagar))
* Whitespace fixes to quiet git hook. [\#11669](https://github.com/PX4/Firmware/pull/11669) ([mcsauder](https://github.com/mcsauder))
* serial/generate\_config.py specify full loader [\#11667](https://github.com/PX4/Firmware/pull/11667) ([dagar](https://github.com/dagar))
* Replace math::min\(\) and additional limit logic with math::constrain\(\) calls [\#11658](https://github.com/PX4/Firmware/pull/11658) ([mcsauder](https://github.com/mcsauder))
* lockstep\_scheduler: check if mutex is still valid [\#11655](https://github.com/PX4/Firmware/pull/11655) ([julianoes](https://github.com/julianoes))
* mixer\_multirotor.py: fixes for Python3 [\#11653](https://github.com/PX4/Firmware/pull/11653) ([julianoes](https://github.com/julianoes))
* HIL fixes for gazebo & jMAVSim [\#11652](https://github.com/PX4/Firmware/pull/11652) ([bkueng](https://github.com/bkueng))
* jMAVSim submodule update [\#11651](https://github.com/PX4/Firmware/pull/11651) ([bkueng](https://github.com/bkueng))
* Jenkins hardware testing add nxp\_fmuk66-v3 [\#11642](https://github.com/PX4/Firmware/pull/11642) ([dagar](https://github.com/dagar))
* perf convert to c++ and enable -Wcast-align [\#11641](https://github.com/PX4/Firmware/pull/11641) ([dagar](https://github.com/dagar))
* mc\_pos\_control limit to 50 Hz [\#11639](https://github.com/PX4/Firmware/pull/11639) ([dagar](https://github.com/dagar))
* Trajectory generator-based FlightTasks - Handle position and velocity resets from EKF [\#11637](https://github.com/PX4/Firmware/pull/11637) ([bresch](https://github.com/bresch))
* mavlink update to latest and enable address-of-packed-member warning [\#11633](https://github.com/PX4/Firmware/pull/11633) ([dagar](https://github.com/dagar))
* Correct links to example docs [\#11632](https://github.com/PX4/Firmware/pull/11632) ([hamishwillee](https://github.com/hamishwillee))
* Delete Simulator class subscription vars that are not used and add orb\_unsubscribe\(\) calls. [\#11631](https://github.com/PX4/Firmware/pull/11631) ([mcsauder](https://github.com/mcsauder))
* Delete extra newline character in qmc5883/CMakeLists.txt to quiet git hook [\#11627](https://github.com/PX4/Firmware/pull/11627) ([mcsauder](https://github.com/mcsauder))
* Add iris benchmarking [\#11626](https://github.com/PX4/Firmware/pull/11626) ([nicovanduijn](https://github.com/nicovanduijn))
* uorb top: add 'uorb top -1' to run only once [\#11622](https://github.com/PX4/Firmware/pull/11622) ([bkueng](https://github.com/bkueng))
* Fix RC RSSI reading on FMUv4 \(pixracer\) [\#11616](https://github.com/PX4/Firmware/pull/11616) ([svpcom](https://github.com/svpcom))
* removed non used \_getMaxCruiseSpeed [\#11615](https://github.com/PX4/Firmware/pull/11615) ([BazookaJoe1900](https://github.com/BazookaJoe1900))
* Deprecate `\_hil\_frames` and `\_old\_timestamp` member vars and dead logic from MavlinkReceiver class - \(Break apart PR\#11274 into easily verifiable steps - Step 6\) [\#11612](https://github.com/PX4/Firmware/pull/11612) ([mcsauder](https://github.com/mcsauder))
* Migrate a few more var initializations from the Mavlink class constructor list to declarations. [\#11610](https://github.com/PX4/Firmware/pull/11610) ([mcsauder](https://github.com/mcsauder))
* Jenkins update SITL tests coverage to correct base container [\#11609](https://github.com/PX4/Firmware/pull/11609) ([dagar](https://github.com/dagar))
* Whitespace formatting in mavlink\_main.cpp/h and begin migrating variable initialization. [\#11608](https://github.com/PX4/Firmware/pull/11608) ([mcsauder](https://github.com/mcsauder))
* jenkins: update all image tags to 2019-03-08 [\#11606](https://github.com/PX4/Firmware/pull/11606) ([lamping7](https://github.com/lamping7))
* Jenkins add SITL tests AddressSanitizer [\#11603](https://github.com/PX4/Firmware/pull/11603) ([dagar](https://github.com/dagar))
* Lockstep scheduler: shutdown fixes / work-arounds [\#11601](https://github.com/PX4/Firmware/pull/11601) ([bkueng](https://github.com/bkueng))
* Update submodule jMAVSim to latest Wed Mar 6 00:38:35 UTC 2019 [\#11597](https://github.com/PX4/Firmware/pull/11597) ([dagar](https://github.com/dagar))
* Update submodule mavlink v2.0 to latest Wed Mar 6 00:38:42 UTC 2019 [\#11596](https://github.com/PX4/Firmware/pull/11596) ([dagar](https://github.com/dagar))
* ekf2 update setGpsData usage [\#11594](https://github.com/PX4/Firmware/pull/11594) ([dagar](https://github.com/dagar))
* Complete Simulator class mavlink handle\_message\_XXX\(\) method implementations. [\#11593](https://github.com/PX4/Firmware/pull/11593) ([mcsauder](https://github.com/mcsauder))
* Pr ground effect zone [\#11592](https://github.com/PX4/Firmware/pull/11592) ([EliaTarasov](https://github.com/EliaTarasov))
* RTL fix RTL\_TYPE param metadata group [\#11587](https://github.com/PX4/Firmware/pull/11587) ([dagar](https://github.com/dagar))
* Delete unnecessary `\#includes` from mavlink\_main.cpp and relocate two `\#defines` to mavlink\_main.h [\#11580](https://github.com/PX4/Firmware/pull/11580) ([mcsauder](https://github.com/mcsauder))
* CONTRIBUTING:Fix up code.html link to goto master [\#11579](https://github.com/PX4/Firmware/pull/11579) ([hamishwillee](https://github.com/hamishwillee))
* Fix link to code style guide [\#11566](https://github.com/PX4/Firmware/pull/11566) ([mortenfyhn](https://github.com/mortenfyhn))
* simulator: fix to set system and component IDs as defined in params [\#11565](https://github.com/PX4/Firmware/pull/11565) ([gamoreno](https://github.com/gamoreno))
* Redefine Simulator::handle\_message\(\) prototype and create Simulator::set\_publish\(\) method. [\#11564](https://github.com/PX4/Firmware/pull/11564) ([mcsauder](https://github.com/mcsauder))
* Smooth avoidance output [\#11561](https://github.com/PX4/Firmware/pull/11561) ([mrivi](https://github.com/mrivi))
* Commander datalinks lost failsafe handing [\#11550](https://github.com/PX4/Firmware/pull/11550) ([cmic0](https://github.com/cmic0))
* Jenkins re-enable Catkin and Colcon builds [\#11465](https://github.com/PX4/Firmware/pull/11465) ([dagar](https://github.com/dagar))
* CI: SITL test run: select ROS version based on ROS\_DISTRO [\#11338](https://github.com/PX4/Firmware/pull/11338) ([lamping7](https://github.com/lamping7))
* \[Breaking Change\]fmuk66-v3: Only Support Rev BX11 [\#11267](https://github.com/PX4/Firmware/pull/11267) ([davids5](https://github.com/davids5))

\* _This Changelog was automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)_

**Comment by mrpollo** [comment]
@dagar this is the output of the changelog generator tool, let me know if there's anything missing

**Comment by hamishwillee** [comment]
I'm not sure about how useful that is and what is enhancements vs PRs. The fact that it misses that we implemented Collision Prevention and Obstacle avoidance in missions is a worry.

**Comment by hamishwillee** [comment]
@mrpollo It might not have missed them, just put them in wrong place - and the PR titles don't really capture the significance of particular features. #10785 is collision prevention. Not sure about obstacle avoidance.

**Comment by Antiheavy** [comment]
this one seems significant: https://github.com/PX4/Firmware/pull/10738

**Comment by TSC21** [comment]
@dakejahl ECL is platform independent.

**Comment by mrpollo** [comment]
@dakejahl @TSC21 If the ECL submodule was updated it should be reflected here in some way and we can link to the ECL project for details on the update, same for every other submodule, thanks for bringing this up.

@hamishwillee I totally see where you are coming from here, I'm with you on this one `changelog != release notes`.

**Comment by E666GT** [comment]
Great Work!

**Comment by mrpollo** [comment]
Just pushed an update!

**Comment by jinger26** [comment]
@dagar , change log is updated now, we need to distill this into high level release note.

**Comment by hamishwillee** [comment]
@mrpollo @MaEtUgR Is orbit mode going in? https://github.com/PX4/Firmware/pull/10907

**Comment by 1Gump** [comment]
I don't know if this is valid for this this log, but a big reason I need this update is for the **lidarlite v3hp functionality** - it didn't work in 1.8.2

**Comment by MaEtUgR** [comment]
@hamishwillee Orbit is in and QGC also supports the command since last release. Good catch, I don't know where it got lost.

**Comment by mrpollo** [comment]
That's a great catch @hamishwillee 

Everyone, please help us review the changelog for any missing features, we should be as accurate as possible.

**Comment by hamishwillee** [comment]
@mrpollo You are planning on creating a high level overview part to these notes right - in line with https://discuss.px4.io/t/what-to-expect-from-1-9-release/11117/3 ?
