### ISSUE TITLE
HITL regression: sensors running and publishing

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#11179]
There seems to be a regression for HITL. In HITL mode (with `SYS_HITL` set to 1), the real hardware sensors are running and publishing.

@dagar @bkueng

**Comment by dagar** [comment]
That should be fixed by https://github.com/PX4/Firmware/pull/11044

**Comment by dagar** [comment]
Any interest in getting HIL running on the hardware test rack?

**Comment by julianoes** [comment]
> Any interest in getting HIL running on the hardware test rack?

Yes. Can I reproduce one item out of the rest locally though?

**Comment by julianoes** [comment]
@bkueng is this still an issue?

**Comment by bkueng** [comment]
Fixed as far as I have tested lately.
