### ISSUE TITLE
Heartbeat base_mode reports MAV_MODE_FLAG_HIL_ENABLED

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#11188]
Pixracer
Version: Stable 1.8.1

When the UAV is in Manual mode disarmed, the base_mode field of Heartbeat message is:
"113" or "0111 0001" binary, that indicates that the following flags are true:

 * MAV_MODE_FLAG_CUSTOM_MODE_ENABLED
 * MAV_MODE_FLAG_STABILIZE_ENABLED
 * **MAV_MODE_FLAG_HIL_ENABLED**
 * MAV_MODE_FLAG_MANUAL_INPUT_ENABLED

I think it's an error that the HIL flag is enabled, since it's the real autopilot and not some hardware in the loop.

**Comment by julianoes** [comment]
Ok odd, and the param `SYS_HITL` is not set to 1?

**Comment by julianoes** [comment]
I just tested this in SITL with 1.8.1 and `base_mode` is 81, so HIL is off.

**Comment by julianoes** [comment]
I then tested with a Pixhawk and the `base_mode` 113 when `SYS_HITL` is set to 1 and 81 if `SYS_HITL` is set to 0 (after a reboot).

As I can tell, this seems all correct.

**Comment by tuloski** [comment]
Actually I found many parameters not standard, including SYS_HITL which was enabled. But I never touched them. What can modify those params? Flashing a new firmware?

**Comment by julianoes** [comment]
That's odd. To reset them, I think you can do `param reset`, see:
https://dev.px4.io/en/middleware/modules_command.html#param

**Comment by julianoes** [comment]
Closing, please re-open if this is still an issue.
