### ISSUE TITLE
make is failed for the PX4 Firmware 1.6.5

### ISSUE THREAD

**Issue by ChaiYiWonder** [PX4/Firmware#11195]
Please help me,When i make px4fmu-v2_default ,i met a problem as follows:

```
FAILED: cd /home/chaiyi/src/Firmware/build_px4fmu-v2_default/px4fmu-v2 && /bin/rm -rf /home/chaiyi/src/Firmware/build_px4fmu-v2_default/px4fmu-v2/NuttX/nuttx/nuttx-export && /usr/bin/make --quiet --no-print-directory -C /home/chaiyi/src/Firmware/build_px4fmu-v2_default/px4fmu-v2/NuttX/nuttx -r CONFIG_ARCH_BOARD=px4fmu-v2 export >nuttx_build.log && cmake -E touch /home/chaiyi/src/Firmware/build_px4fmu-v2_default/px4fmu-v2/nuttx_export.stamp
stdio/lib_sscanf.c: In function 'vsscanf':
stdio/lib_sscanf.c:419:28: error: this statement may fall through [-Werror=implicit-fallthrough=]
                       sign = true;
                            ^
stdio/lib_sscanf.c:420:21: note: here
                     case 'u':
                     ^~~~
cc1: all warnings being treated as errors
make[2]: *** [bin/lib_sscanf.o] Error 1
make[1]: *** [libc/libc.a] Error 2
ninja: build stopped: subcommand failed.
Makefile:164: recipe for target 'px4fmu-v2_default' failed
make: *** [px4fmu-v2_default] Error 1
```

**Comment by julianoes** [comment]
How come you are still using 1.6.5 which was released in Jul 12, 2017? I don't think that's recommended or supported any more.

As we're moving to newer compilers, more warnings are added which can lead to warning errors like this. The easiest solution is to remove `-Werror` which makes warning throw build errors here:
https://github.com/PX4/Firmware/blob/48df19c8dfa145a16278b48e2aff0a4eda74feda/cmake/px4_add_common_flags.cmake#L66

Alternatively you can fix the actual compile error:
https://stackoverflow.com/questions/51453742/how-to-fix-this-statement-may-fall-through-werror-implicit-fallthrough
