### ISSUE TITLE
px4_fmu-v2 cannot be the first argument.

### ISSUE THREAD

**Issue by E666GT** [PX4/Firmware#11204]
**Describe the bug**
Making procedure was ok.
Today after somehow change of release by using
`git checkout v1.8.1` or `git checkout v1.9.0-alpha`
then when I use
`make px4_fmu-v4_default`
or
`make px4_fmu-v2_default`
I meet make fail error:
`evan@EvanUbuntu16:~/src/Firmware$ make px4_fmu-v2
Makefile:378: *** "px4_fmu-v2 cannot be the first argument. Use 'make help|list_config_targets' to get a list of all possible [configuration] targets."。 `

This error also happens with v4:
`evan@EvanUbuntu16:~/src/Firmware$ make px4_fmu-v4_default
Makefile:378: *** "px4_fmu-v4_default cannot be the first argument. Use 'make help|list_config_targets' to get a list of all possible [configuration] targets."。 `

although It works with `make posix`,with making successful result.

I meet this problem on various computers, while dealing with versions. And can't find a way to repair this problem.

**Expected behavior**
Make successful as before.

**Additional context**

What the problem with this? and what's the supposed operation to change the firmware version?
Thanks for your team's work!

**Comment by TSC21** [comment]
That command only works for upstream master. Use `make px4fmu-v2_default` - https://dev.px4.io/v1.8.2/en/setup/building_px4.html.
