### ISSUE TITLE
Tiltrotor SITL interrmittant failure

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#11213]
Originally reported in https://github.com/PX4/Firmware/issues/11144

New failures -
 - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-2swhoop-params/3/pipeline

> Different issue, tiltrotor arming failing due to accels. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-11136/4/pipeline/81
> 
> ![image](https://user-images.githubusercontent.com/84712/50703875-830bd000-1023-11e9-84c1-955c9948209f.png)
> 
> What's going on with the vibration in the tiltrotor model?
> 
> From the failure log - https://logs.px4.io/plot_app?log=33db160e-75a1-413c-9401-9bda6daa063b
> ![image](https://user-images.githubusercontent.com/84712/50704053-09281680-1024-11e9-99fb-255e3a00c938.png)
> 
> From a successful log - https://logs.px4.io/plot_app?log=a20570ad-bd94-446d-b910-f56e441610b5
> ![image](https://user-images.githubusercontent.com/84712/50704081-1d6c1380-1024-11e9-8906-9a46c923ddeb.png)

@RomanBapst any ideas?

**Comment by dagar** [comment]
More failures.
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/pr-update_src%2Flib%2FDriverFramework/5/pipeline/80

**Comment by lamping7** [comment]
Good to close @dagar?

**Comment by dagar** [comment]
Actually no, I've seen it a couple times in the last week or so. I'll record any new occurrences here.

**Comment by dagar** [comment]
Here's a fresh one. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-11668/5/pipeline


![image](https://user-images.githubusercontent.com/84712/54477959-7c4bc700-47e3-11e9-9705-557a67218aa5.png)

**Comment by EliaTarasov** [comment]
@dagar i think it's just the P-component for the tilting actuators is too large. Oscillations due to high P-values causes high-frequency jumping on the ground and sometimes accelerometer range becomes too large. I set P equals 10 and this issue disappeared.

**Comment by julianoes** [comment]
Looks like #11912.
