### ISSUE TITLE
fun cub quad vtol

### ISSUE THREAD

**Issue by hassansabbah1** [PX4/Firmware#11218]
hi i want to use quad vtol with qgc but i have some questions. i using h tail plane and which airframe is well for it. my vtol is 15 kg quad rotor can take off it but for transition and cruise speed 
what should be my rate ratio. i dont have airspeed sensor i using disable airspeed parameter but for transition duration what should be i set. and for big vtol pid parameters do i need to change?

**Comment by julianoes** [comment]
This is not really an issue, so I suggest to ask that sort of question in https://discuss.px4.io. And the more background or description or photos you give the better the chance for a good response.
