### ISSUE TITLE
Add support for STATUSTEXT_LONG

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#11225]
[STATUSTEXT_LONG](https://mavlink.io/en/messages/common.html#STATUSTEXT_LONG) was added to the MAVLink spec. It allows longer than 40 char status messages. 

My assumption was that PX4 would use this in preference to [STATUSTEXT](https://mavlink.io/en/messages/common.html#STATUSTEXT) except when talking to a MAVLink 1 system, and that QGC would support reading both messages.

**Comment by hamishwillee** [comment]
FYI, support for this goes into QGC in https://github.com/mavlink/qgroundcontrol/pull/7152

**Comment by hamishwillee** [comment]
FYI, not sure whether or not this is needed because the event's interface should be used for many of the use cases that justified this message's existence.

**Comment by hamishwillee** [comment]
On the other hand ...

**Comment by hamishwillee** [comment]
I think next time round will allow this to lapse. We're now coming up to the point where events interface should exist.

**Comment by julianoes** [comment]
STATUSTEXT_LONG  is dead, next come chunks:
https://github.com/mavlink/mavlink/pull/1295

**Comment by hamishwillee** [comment]
Thanks. Closing this, and opening a new one: https://github.com/PX4/Firmware/issues/14169
