### ISSUE TITLE
Switch from GCC 4.6 to 4.7 results in fprintf timing glitches

### ISSUE THREAD

**Issue by fibr** [PX4/Firmware#1122]
We've been tracking this issue for a while here and finally collected enough evidence:

Switching from GCC 4.6 to GCC 4.7, fprintf starts causing timing glitches. See comparison DT plot below (same code, same hardware) (Thanks to @mazahner for the plot/data)

![image](https://cloud.githubusercontent.com/assets/3940694/3486697/d339f396-044c-11e4-8ac6-2cd6ba921bd8.png)

These glitches "leak" into other file-writing threads, even if they don't use fprintf. However, non-fprintf file writing works fine on its own.

To complicate things, while going back to 4.6 could help (and a good way to troubleshoot), some code has been introduced that doesn't compile in 4.6. See e.g. class-decl initializers in gps_helper.h. Toolchain flexibility remains important in light of these issues and it might be a good idea to stick to 4.6 compatibility.

Has anyone experienced similar fprintf issues and does anyone have any pointers to resolving this?
Thanks in advance.
-sergei

**Comment by LorenzMeier** [comment]
@davids5 This could be related again to the busy handling of the card.

**Comment by LorenzMeier** [comment]
Now after fixing the SPI code, re-testing this would be nice. I suspect you get fine results now on master.
