### ISSUE TITLE
the wind static barometric pressure correction

### ISSUE THREAD

**Issue by int32cn** [PX4/Firmware#11235]
At EFK2_main.cpp run function, the wind static barometric pressure correction is calculated as following:

const float pstatic_err = 0.5f * airdata.rho *
    (K_pstatic_coef_x * x_v2) + (_K_pstatic_coef_y.get() * y_v2) + (_K_pstatic_coef_z.get() * z_v2);

And according the air static barometric pressure formula，P = 0.5 * ro * V ^2;
So I 'm wondering here maybe missing a brace, the code above should be as the following:
const float pstatic_err = 0.5f * airdata.rho *
   ( (K_pstatic_coef_x * x_v2) + (_K_pstatic_coef_y.get() * y_v2) + (_K_pstatic_coef_z.get() * z_v2));

**Comment by CarlOlsson** [comment]
This is still an issue.
Pinging @RomanBapst just so it does not get forgotten

**Comment by RomanBapst** [comment]
@CarlOlsson thanks for mentioning this, I will fix it today.

**Comment by RomanBapst** [comment]
@int32cn Thanks for raising this!
