### ISSUE TITLE
Replace the atomic `hrt_elapsed_time` call with a non-atomic call

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#11245]
Almost nobody really need an atomic call to `hrt_elapsed_time` but lots of location in the code use the function as a convenience call. We should introduce an atomic option to reduce IRQ jitter and CPU load in the system.

**Comment by dagar** [comment]
Is it easier to start from the other end and identify where hrt_elapsed_time in a critical section actually matters?

**Comment by LorenzMeier** [comment]
I did that already, and it's pretty much 0.1% of the calls needing this. Hence instead of inducing a massive diff I would switch those over.
