### ISSUE TITLE
Target system and component fail serial mavlink

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#11255]
I have a serial to the pixracer which sends MAVlink messages with protocol v1.0.
I'm sending a COMMAND_LONG message and it's received correctly, but the parsing fails here: https://github.com/PX4/Firmware/blob/755eb6a2e9bc3598f994593af15ca095e54055c4/src/modules/mavlink/mavlink_receiver.cpp#L551

because it results a wrong target system and component.
Debugging it seems that it requires a target system == 1 (as specified in the params of the autopilot) and target_component == 1 or == 0 (all components).
The problem is that the mavlink message received has target and component == 0, but I verified the message sent and it includes the correct system and component. I can't understand where those values are being dropped and changed to 1.
Is there something else I should do at MAVlink protocol (the sender) to communicate the target system and component other than inside the messages sent?
Any idea where those values can be dropped and set at 0?

**Comment by julianoes** [comment]
Sorry for the late response.
@tuloski you would have to share the code that sends these commands for us to help.
