### ISSUE TITLE
Level horizon calibration transients

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#11275]
**Describe the bug**
It seems like the board rotation parameters are set to zero prior to performing the attitude calibration. In some cases this can cause attitude transients which impact the average measured attitude.

I'll follow up with a plot if not already with a fix.

**Comment by RomanBapst** [comment]
@sanderux FYI

**Comment by julianoes** [comment]
@RomanBapst is this still an issue?

**Comment by julianoes** [comment]
@RomanBapst it would be good if you can follow up on these things, thanks.

**Comment by RomanBapst** [comment]
@julianoes This problem was reported by @sanderux and I created this issue so that we don't forget about it. I have just tried to do a level calibration with a 30 degrees offset on both roll and pitch and the level horizon calibration worked just fine. The algorithm was waiting long enough for the transient of the attitude solution to decay.
Given that this is the only issue I've ever seen about this and I cannot reproduce the problem I'm going to close this.
@sanderux If you have a log of a failure case please share it here and we can have a look at it.

**Comment by RomanBapst** [comment]
@julianoes @sanderux  This should now be fixed for good since @bkueng did changes to the calibration routine such that the calibration is performed relative to the current board offset.
https://github.com/PX4/Firmware/pull/13666#pullrequestreview-326119932
