### ISSUE TITLE
Pixhack v3 hardware issues

### ISSUE THREAD

**Issue by Tony3dr** [PX4/Firmware#11276]
After completing the set up for the Pixhack v3, we have the following issues:
1. Doesn't detect compass
2. Inconsistent compass and accelerometer 
3. The vehicle does not arm

Please see video below:
https://www.youtube.com/watch?v=xb6wUPhIn3U&feature=youtu.be

We have tried on stable and Master. @jinger26 @mrpollo @dagar @cuhome

**Comment by cuhome** [comment]
Please enter ver all in mavlink console. Get version information.

**Comment by cuhome** [comment]
![20190123085937](https://user-images.githubusercontent.com/31507501/51575511-542f9e00-1eed-11e9-9bae-88afe8a45712.jpg)

**Comment by cuhome** [comment]
@dagar Because the chip was discontinued, the hmc5983 was removed and ncp5623c was used as the LED driver chip. For a better distinction, we named it pixhack v3x.

**Comment by Tony3dr** [comment]
![image 25](https://user-images.githubusercontent.com/39415493/51636055-20647080-1f0d-11e9-9558-0f5bd345d832.png)

**Comment by cuhome** [comment]
@Tony3dr 
![_20190124084332](https://user-images.githubusercontent.com/31507501/51646605-3a0cc300-1fb4-11e9-8d8f-9273653ccb01.png)

**Comment by cuhome** [comment]
Please enter ls dev. Is there a mag0?

**Comment by cuhome** [comment]
@Tony3dr I have no problem from your picture. I can't see your video. Can you send the video file to my email address? The email address is hongle@cuav.net.

**Comment by hamishwillee** [comment]
@cuhome If you can find a player, the tunes are here: https://github.com/PX4/Firmware/blob/master/src/lib/tunes/tune_definition.desc#L86

**Comment by julianoes** [comment]
@Tony3dr has this been resolved?
