### ISSUE TITLE
local_position_estimator and position_estimator_inav basic support or deprecation

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#11300]
Currently EKF2 (ecl/EKF) is the default estimator for all platforms, but we still have the local_position_estimator (LPE), and position_estimator_inav in tree. Likely both still have small (stubborn?) user base. 

LPE can be enabled with the `SYS_MC_EST_GROUP` parameter.

I feel strongly that we either need to add a minimal support baseline for these estimators (simple testing) or start deprecating them. We're not helping users or the perception of PX4 in general by dragging things along that are unsupported, and quite possibly unsafe to use.

### Options

1. Minimal baseline for upstream inclusion
   1. simple SITL tests
   2. occasional flight test
   3. volunteer willing to commit to reviewing all LPE and INAV labelled issues
   4. (later) new c++ interface to enforce estimator publishing requirements.
      - example: many parts of the system use the `sensor_bias` (https://github.com/PX4/Firmware/blob/master/msg/sensor_bias.msg) message, but neither LPE or INAV publish it.

2. Begin deprecation
   1. move to examples
   2. remove or modify SYS_MC_EST_GROUP parameter to prevent direct user usage
   3. delete entirely after a major release or two in examples

**Comment by dagar** [comment]
I'd like to implement one of the options before the next stable release of PX4 (v1.9.0).

**Comment by TSC21** [comment]
On it. I will start with LPE and set a MC mission box test.

**Comment by LorenzMeier** [comment]
I think its time to deprecate - the level of QA on these is really poor compared to the rest of the system and its becoming a reputation risk. We can't drag them along if there are not developers using them and really depending on them. I would remove INAV for 1.9.

**Comment by hamishwillee** [comment]
FYI only, this has a docs implication in the devguide.

**Comment by dagar** [comment]
We've dropped position_estimator_inav.
