### ISSUE TITLE
Gazebo SITL and PX4 not handling simulated wind correctly

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#11319]
As pointed out by @CHschizo in this other issue post here: https://github.com/PX4/Firmware/issues/11116#issuecomment-452724619  the wind estimate and flight performance isn't working correctly in Gazebo SITL.  See screenshot below of the vehicle tracking offset to the intended location east-west cross-track error, but tracking okay north-south cross-track error.

this is using the default PX4 Gazebo Plane model

![image](https://user-images.githubusercontent.com/12117027/51811200-7d478a00-2271-11e9-8cfd-924e9d1fec08.png)

**Comment by TSC21** [comment]
@Antiheavy everything sitl_gazebo related would be better put under sitl_gazebo repo issues.
Also can you elaborate on "isn't working correctly"? Thanks

**Comment by Antiheavy** [comment]
moving to the proper repo here: https://github.com/PX4/sitl_gazebo/issues/287
