### ISSUE TITLE
Organize codes of px4_raspberrypi_* in developer specific folder?

### ISSUE THREAD

**Issue by SalimTerryLi** [PX4/Firmware#11320]
Due to the condition that px4_raspberrypi_* and emlid_navio were splitted, it' s possible to maintain the pure branch of raspi. But developers who work on raspi without navio HATs mostly work separately with their own configuration of hardware.

Now the board specific code are moved into boards/ . I' m asking to create something like: 
boards/px4/raspberrypi/[developer's name]/src/    // for developer' s personalized code
boards/px4/raspberrypi/src/    // for reusable codes

Or, any maintainer focused on this branch?

**Comment by dagar** [comment]
What's an example of generic raspberry pi code with no appropriate home?

**Comment by SalimTerryLi** [comment]
A direct example is src/drivers/rpi_rc_in/ . It was merged incompletely from someone' s project, missing some extern codes. Besides, adc & actual control & rc input & some other sensors will perform their function in unpredictable forms too. Though these extra sensors have not been employed, it woull be a possibility. Raspi platform has too much freedom to expand its function, but its developers rarely work on the same branch.
I hope that codes can be reused by other platform but at first they should have a place to exist.

**Comment by SalimTerryLi** [comment]
> 
> 
> What's an example of generic raspberry pi code with no appropriate home?

A direct example is src/drivers/rpi_rc_in/ . It was merged incompletely from someone' s project, missing some extern codes. Besides, adc & actual control & rc input & some other sensors will perform their function in unpredictable forms too. Though these extra sensors have not been employed, it woull be a possibility. Raspi platform has too much freedom to expand its function, but its developers rarely work on the same branch.
I hope that codes can be reused by other platform but at first they should have a place to exist.

**Comment by dagar** [comment]
Wouldn't that be an example of something that's effectively only for the plain raspberry pi (currently px4/raspberrypi)? Something with a navio2 already has PPM in through sysfs.

**Comment by SalimTerryLi** [comment]
> 
> 
> Wouldn't that be an example of something that's effectively only for the plain raspberry pi (currently px4/raspberrypi)? Something with a navio2 already has PPM in through sysfs.

Yes, that is what I' m talking about. Navio2 has its own fixed hardware configuration, which forms its development. But the plain raspberry pi does not. Developers can provide many kinds of solutions they prefered.
