### ISSUE TITLE
HITL in Pixhawk 4

### ISSUE THREAD

**Issue by siddux** [PX4/Firmware#11340]
Hi, 

I'm trying to run HITL in pixhawk 4 using the master version of px4. I follow the steps on the guide but QGC doesn't connect to pixhawk and gazbo. Is it a problem with this version or I am missing something?

**Comment by colafly** [comment]
I think this is because of
https://discuss.px4.io/t/hitl-simulation/6638/23

so you can try to downgrade and see if you still seeing issues
