### ISSUE TITLE
"tests time" hangs and fails to recover in current Firmware/master

### ISSUE THREAD

**Issue by mcsauder** [PX4/Firmware#11361]
**Describe the bug**
From a console, run "tests time" the test will hang indefinitely.

**To Reproduce**
From a console, run "tests time" the test will hang indefinitely.

**Expected behavior**
The test should execute properly. :)

**Log Files and Screenshots**
![image](https://user-images.githubusercontent.com/2497951/52098303-afb3f880-258b-11e9-856b-6fc375aeee44.png)

**Drone (please complete the following information):**
pixhawk4 (fmu-v5)

Please let me know if I can provide any additional information!

-Mark

**Comment by LorenzMeier** [comment]
@bkueng This sounds like we should follow up in detail.

**Comment by mcsauder** [comment]
@bkeung, the test was functional after this commit: 3859bbb3b0abdfa1314bb070e4d4aa4aec5d883b

@davids5, somewhere in the next stack of commits it is broken, but many of the commits will not build for me so I cannot determine easily where the breakage occurs.

I do not know if the breakage is in the unit test or in the code.  I hope this helps.

**Comment by davids5** [comment]
@mcsauder Fixed in https://github.com/PX4/Firmware/pull/11414
