### ISSUE TITLE
VEHICLE_CMD_DO_REPOSITION scaling check invalid for negative lat/lon

### ISSUE THREAD

**Issue by blutack** [PX4/Firmware#11364]
**Describe the bug**
VEHICLE_CMD_DO_REPOSITION [attempts to do a sanity check](https://github.com/PX4/Firmware/blob/225115087510c6287fc1d28593f240fe3c214269/src/modules/navigator/navigator_main.cpp#L356) to handle both scaled and unscaled lat/lon. If the lat or lon are over 1000, the value is assumed to be scaled and divided down. However, this check is not valid for locations south of the equator or west of the meridian because the values will be negative and therefore below 1000.

```
rep->current.lat = (cmd.param5 < 1000) ? cmd.param5 : cmd.param5 / (double)1e7;
rep->current.lon = (cmd.param6 < 1000) ? cmd.param6 : cmd.param6 / (double)1e7;
```

One way to correct the bug could be:

```
rep->current.lat = (abs(cmd.param5) < 1000) ? cmd.param5 : cmd.param5 / (double)1e7;
rep->current.lon = (abs(cmd.param6) < 1000) ? cmd.param6 : cmd.param6 / (double)1e7;
```

On it's own this would not be a particularly serious issue, as sending scaled up values via COMMAND_LONG is invalid. However, the default simulation locations are in regions where this bug does not occur. Therefore, code which appears to work correctly in sim can cause a flyaway in real flight.

**To Reproduce**
1. Send a COMMAND_LONG with LAT and LON as integers multiplied by 10^7 with negative latitude or longitude
2. Aircraft will attempt to fly off to an impossible location setpoint (example 50.0001, -2400000)

**Expected behavior**
Aircraft should not attempt to fly to an impossible location.
It should either:
a) correctly scale down values which are negative
b) do not do the sanity check at all, in which case invalid lat/lon would also fail in simulation
c) reject the reposition command if values are not in expected valid ranges for lat/lon

**Comment by julianoes** [comment]
Oh wow, thanks for raising this!

**Comment by blutack** [comment]
No problem @julianoes and thanks for unmarking it, it's not major but one of those things that can bite.

If you let me know the preferred option (a, b, c) for resolving I'm happy to open a pull request.

Also reading back my original report, sanity check is probably the wrong phrase to use!

**Comment by julianoes** [comment]
Right, so a) would be the first quick fix I'd say.

Then, I would argue that DO_REPOSITION should be documented on the MAVLink level that it always needs to be a COMMAND_INT, and then we could start to reject COMMAND_LONG.

**Comment by hamishwillee** [comment]
@julianoes Don't let this stop you but ...

> Then, I would argue that DO_REPOSITION should be documented on the MAVLink level that it always needs to be a COMMAND_INT, and then we could start to reject COMMAND_LONG.

FWIW I'd reject COMMAND_LONG for this message straight away. 

For the mavlink docs we can easily enough doc individual cases, but I think that people are unlikely to check this. I'd rather look at the LONG vs INT problem holistically - perhaps get rid of the COMMAND_LONG altogether. Maybe use markup and tooling to reject use of the wrong message at the mavgen library level. 

There is an outstanding issue on this topic: https://github.com/mavlink/mavlink/issues/1090

**Comment by garfieldG** [comment]
Hi, 

wanted to know is there something new regarding this issue? 

regarding the use of reposition only with command_int - I think it should be rethink , as for now it's possible to send a new reposition command with no lat and lon (NAN), but it's possible only with command_long. I think it's something that should be reconsider so that we don't loose this ability.

**Comment by hamishwillee** [comment]
@garfieldG Looks like Julian suggested option a is best (https://github.com/PX4/Firmware/issues/11364#issuecomment-511469527) - so PR?

**Comment by BazookaJoe1900** [comment]
this issue
