### ISSUE TITLE
EKF2_AID_MASK -- Optical Flow With no GPS -- LeddarOne -- IntelAero

### ISSUE THREAD

**Issue by gmetts** [PX4/Firmware#11387]
When attempting to arm and takeoff using optical flow in an indoor lab using a LeddarOne sensor on the Intel Aero with the standard downward facing camera, the position lock command fails its check and refuses to take off. Previously I understand that running this EKF2 setup was not possible but I have reason to believe that it may have been patched in. At this point, I am unsure whether it is supported and the problem is user error or if a position lock is required. Has anyone made this setup work? If so, can they share the settings that gave them their positive results? If this particular set up has a known issue, is there a supported optical flow framework using the intel aero to achieve localization in GPS deprived environments?

**Comment by r1b4z01d** [comment]
I am having the same issue with the Lidar Lite V3. Have you been able to over come this? I am on V1.8.2 but trying V1.6.5 today.

**Comment by gmetts** [comment]
No we currently are pursuing using the IR cameras in the lab to run it using visual fusion so that we can get results on our control system. The environment that we would like to operate the drone in will have limited access to absolute position methods though. However I've read the Lite has chronic problems. I've seen people have success with optical flow when flown in conjunction with GPS but I haven't seen anyone state that they've managed to fully use flow
