### ISSUE TITLE
SITL intermittent failure: param indices changing during sync

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#11384]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/593/pipeline/

![image](https://user-images.githubusercontent.com/84712/52305119-57ea0880-2962-11e9-9225-e68be5395e67.png)

**Comment by dagar** [comment]
Not sure yet, looking at adding debugging to catch the change. Anything that isn't using the new param wrapper (px4_params.h) or doing a param_find immediately is suspect.

**Comment by dagar** [comment]
Example: https://github.com/PX4/Firmware/blob/master/src/modules/simulator/simulator_mavlink.cpp#L1051-L1055

**Comment by dagar** [comment]
Another suspect - https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L430

**Comment by LorenzMeier** [comment]
`param_find` is also comparatively expensive and should not be run regularly.

**Comment by dagar** [comment]
Hack to help find offenders - https://github.com/PX4/Firmware/tree/pr-mavlink_param_sync_hacks

**Comment by dagar** [comment]
I think this one might also be related to lock step, at least why we're catching it regularly now. Something to do with sleep (now px4_sleep) before lock step is fully working? @julianoes FYI

![screen shot 2019-02-05 at 6 30 39 pm](https://user-images.githubusercontent.com/84712/52311202-3003a080-2974-11e9-8132-528e8c2ac05a.png)

**Comment by LorenzMeier** [comment]
Dev call: Needs analysis on boot and fixes for offending nested param find calls.

**Comment by dagar** [comment]
Still need to keep an eye on this one.

**Comment by dagar** [comment]
@julianoes This is still a problem.

![image](https://user-images.githubusercontent.com/84712/53178435-daf49b00-35bf-11e9-9045-06f04744c873.png)

**Comment by dagar** [comment]
Another example.
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-11505/2/pipeline
![image](https://user-images.githubusercontent.com/84712/53342762-bb6db300-38dc-11e9-813f-de54679405af.png)

**Comment by mrivi** [comment]
@julianoes @dagar we see a lot of this errors
```bash
[ WARN] [1554283456.615858849, 13.772000000]: PR: request param #419 timeout, retries left 2, and 1 params still missing
[ WARN] [1554283456.616271258, 13.772000000]: PR: Param RC16_MIN (418/559): <value><double>1000</double></value> different index: 419/560

when retrieving the px4 paramters from mavlink/mavros on the avoidance side. 
Is there anything we can do about it ?

**Comment by julianoes** [comment]
@dagar I haven't seen this in a while.

**Comment by dagar** [comment]
Likewise, but there's still nothing fundamentally preventing it. How about we get the "hack" (https://github.com/PX4/Firmware/pull/11388) into an acceptable state for merging and move on? At least then we'd capture it in logs if it did happen in the field.

The alternative is locking the param system during mavlink param sync.

**Comment by dagar** [comment]
I believe this has been resolved.
