### ISSUE TITLE
sitl with gazebo: error opening serial device

### ISSUE THREAD

**Issue by jlkjiji** [PX4/Firmware#11393]
Hi.
I switched to stable branch and run "make posix_sitl_default gazebo" but got error message as "error opening serial device".
![screenshot from 2019-02-06 11-20-07](https://user-images.githubusercontent.com/47377147/52322998-482bfc00-2a16-11e9-844e-8d52cec885bf.png)
And then followed as:
![screenshot from 2019-02-06 11-58-10](https://user-images.githubusercontent.com/47377147/52323139-da340480-2a16-11e9-94de-10cfbc6f7570.png)
While the hil simulation with gazebo is working properly.
I have tried connecting my pixhawk then "make posix_sitl_default gazebo" and it worked just like hil mode.
Can anybody help?

**Comment by cesar-source** [comment]
Hi @Alaric-F 

I'm having the same issue... were you able to resolve your problem?

**Comment by julianoes** [comment]
Could it be that you still have `serialEnabled` in your iris.sdf file after HITL?

**Comment by cesar-source** [comment]
Ah yes, I missed that. Thanks for that!

**Comment by hsrfeyzullah** [comment]
How exactly did you solve the problem?

**Comment by hsrfeyzullah** [comment]
How exactly did you solve the problem?@cesar-source

**Comment by cesar-source** [comment]
@hsrfeyzullah under the `mavlink_interface` plugin in the .sdf file, there should be a `serialEnabled` tag. I set this to 0 and it worked!
