### ISSUE TITLE
Issue with Master_vehicle crash

### ISSUE THREAD

**Issue by Tony3dr** [PX4/Firmware#11408]
Today we tested Master v1.9.0 (beta) (7f3b1700) with the Pixracer, Pixhawk 4 mini, Pixhawk 4. Created mission. The vehicle armed good, took off. At 30 meters the vehicle started spinning and came down to the ground. Resulted in a crash. Same behavior for all 3 platforms. 

1. Uploaded mission
1. Drone switched on
1. Vehicle armed
1. Took off
1. Elevated to 30 meters
1. vehicle started spinning out of control
1. The vehicle came down and crashed

Pixracer:
https://review.px4.io/plot_app?log=4f0c2692-5f27-4d83-bfbd-765bf48a989e

Pixhawk 4 Mini:
https://review.px4.io/plot_app?log=53fa724b-906d-4e93-87fe-5a4f4c2a50b8

Pixhawk 4:
https://review.px4.io/plot_app?log=69f42b00-6259-4a97-96c1-bd8f06b4d29d

@dagar

**Comment by mhkabir** [comment]
Potentially https://github.com/PX4/Firmware/pull/11376

**Comment by dagar** [comment]
Wow, ouch. Looking.

**Comment by dagar** [comment]
In both cases (fmu-v4 and fmu-v5) the pc points to math::max (mathlib/math/Limits.hpp:72) called from navigator MissionBlock::get_time_inside().

https://github.com/PX4/Firmware/blob/c3d6a042e6332792fe85a1121c08fefa7dbfcb43/src/modules/navigator/mission_block.cpp#L480-L491

**Comment by dagar** [comment]
This is easy enough to fix once off, but I'm looking for a most exhaustive solution (compiler warning perhaps).

**Comment by dagar** [comment]
Newer gcc has `-Waddress-of-packed-member`.

**Comment by dagar** [comment]
WIP fixes in https://github.com/PX4/Firmware/pull/11411

**Comment by dagar** [comment]
We need to do a quick pass of packed structure usage looking for anything that might take the address of a  member, create a reference, or pass it into a function that does.

This includes navigator (mission_item), mavlink (anything from the mavlink spec), and a few drivers.
