### ISSUE TITLE
Not stable in position mode

### ISSUE THREAD

**Issue by kapoorshivam100** [PX4/Firmware#11413]
We use GitHub issues only to discuss PX4 bugs and new features. For
questions about using PX4 or related components, please use [PX4 Discuss](http://discuss.px4.io/).

Thanks!

**Comment by kapoorshivam100** [comment]
In my case , in the position mode on increasing the throttle above 50 percent it stabilize for a sec and then starts increasing altitude and throttle on his own...
what could be the posssible error??

**Comment by mhkabir** [comment]
Please follow the issue template.
