### ISSUE TITLE
MC - Loops maneuvers when MPC_XY_CRUISE > MPC_XY_VEL_MAX

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#11420]
Reducing the MPC_XY_VEL_MAX to lower value then MPC_XY_CRUISE make the drone to fly in very strange way, it makes "loops" and fly backwards every few seconds.

This was tested on simulator only.
https://logs.px4.io/plot_app?log=14e8cf1c-2fca-4cf8-ba0d-26ea8c5dd5d1
To reproduce:
• Run simulator, with default parameters
• takeoff and fly-to remote location
• everything normal
• set MPC_XY_VEL_MAX 2
• you will see that every ~10 second the drone fly back, do some strange loop
• set MPC_XY_ CRUISE 2
• the drone fly slow, but ok
![image](https://user-images.githubusercontent.com/29940676/52518803-73525d80-2c59-11e9-96f4-b1143cfea0af.png)

**Comment by dagar** [comment]
@bresch @Stifael any input here?

**Comment by bresch** [comment]
Ouch, we should force cruise < max

**Comment by BazookaJoe1900** [comment]
@bresch how can you 'force' that? is it ok by you to change the parameter flash value if it doesn't apply the rule? or just whereever it being get() do the constrain?

**Comment by bresch** [comment]
Usually we constrain the parameter when we read using `.get()` and change the parameter using a `.set(val)`.

**Comment by BazookaJoe1900** [comment]
@bresch for MPC_XY_CRUISE, there is no single point where we read the parameter and can modify it, it uses the new px4_params defined that I am not sure  where I can rightlly fix that.

**Comment by bresch** [comment]
Don't close that

**Comment by BazookaJoe1900** [comment]
I am not sure what fixed this behavior but it doesn't happens on current master enymore.
@bresch you can check this too and close

**Comment by bresch** [comment]
Fixed by #12404
