### ISSUE TITLE
LPE Q Estimator external heading fusion not handling lack of external data

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [PX4/Firmware#11433]
I am using an LPE with an external vision system and yaw information fused in Q Estimator. It works pretty well even without a mag sensor (this currently does not work in EKF2). The problem is that my external estimator can have up to a few seconds pauses in which no new yaw data is published.
I have found out that if the last yaw position is e.g. x radian the Q Estimator is still converging to this number even if gyro has correctly reported 90-degree turn.

1. PX4 with LPE estimator, external vision estimator and external vision yaw fused in Q Estimator.
2. Turn off mag sensor.
3. Let the `ATTITUDE.yaw` converge to `VISION_POSITION_ESTIMATE.yaw`.
4. Turn off external vision system.
4. Rotate the autopilot 90 degrees.
5. Watch `ATTITUDE.yaw` converge back to the last data reported by the external vision system.

Expected behavior:
The Q estimator should turn off external vision data if last message is too old.

This screenshot should explain it:
![qestimator1](https://user-images.githubusercontent.com/12136404/52566830-0d0d3c80-2e0b-11e9-9eb1-8b5d7908d53f.png)

I have a fix ready and will create a PR after tests.

**Comment by TSC21** [comment]
@ArkadiuszNiemiec a PR with a fix is welcomed, yes. Thanks

**Comment by ArkadiuszNiemiec** [comment]
@TSC21 I have tested the #11436 in flight and it works perfectly. Here's the screenshot of the data generated in the same way as the previous one:
![qestimator2](https://user-images.githubusercontent.com/12136404/52570726-56ae5500-2e14-11e9-9e5e-85ea2a71f623.png)
