### ISSUE TITLE
CI Firmware/master is broken

### ISSUE THREAD

**Issue by vincedjango** [PX4/Firmware#11440]
**Describe the bug**
How I noticed it is that I created a PR to fix a crash in a python script _mission_test.py_ https://github.com/PX4/Firmware/pull/11439 . My PR cannot be pushed nor reviewed because all the builds fail. The builds fail on something completely different and unrelated to my change.

The error is the same on all the target.
```
+ make px4_fmu-v4_default

Makefile:396: *** "px4_fmu-v4_default cannot be the first argument. Use 'make help|list_config_targets' to get a list of all possible [configuration] targets.".  Stop.

script returned exit code 2
```

http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/PR-11439/1/pipeline/10

**To Reproduce**
1. Execute CI with the current JenkinsFile used.

**Expected behavior**
```
+ make px4_fmu-v4_default

Makefile:396: *** "px4_fmu-v4_default cannot be the first argument. Use 'make help|list_config_targets' to get a list of all possible [configuration] targets.".  Stop.

script returned exit code 2
```

**Comment by mrpollo** [comment]
@vincedjango master seems to be fine this is an issue with your PR #11439 

[Jenkins activity report](http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/activity)

![jenkins](https://user-images.githubusercontent.com/317648/52591960-15a94700-2dfa-11e9-8813-a48de750755d.png)
