### ISSUE TITLE
Add support for MAV_CMD_REQUEST_MESSAGE

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#11441]
Added in https://github.com/mavlink/mavlink/pull/1079, `MAV_CMD_REQUEST_MESSAGE` is a one-shot version of MAV_CMD_SET_MESSAGE_INTERVAL that you can use to ask for a single response. It is a generic replacement for other specific messages we use for this behaviour.

Action is to add implementation for MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES, MAV_CMD_REQUEST_CAMERA_INFORMATION, MAV_CMD_REQUEST_CAMERA_SETTINGS, MAV_CMD_REQUEST_STORAGE_INFORMATION.

Request should return the usual set of MAV_RESULTS, with MAV_RESULT_UNSUPPORTED if particular message is not handled.

@dogmaphobic FYI, because many of those messages are yours.

**Comment by hamishwillee** [comment]
Still desirable.

**Comment by hamishwillee** [comment]
Note, this duplicates https://github.com/mavlink/mavlink/pull/1180

**Comment by hamishwillee** [comment]
We're going to :-)

**Comment by dayjaby** [comment]
> Request should return the usual set of MAV_RESULTS, with MAV_RESULT_UNSUPPORTED if particular message is not handled.

are you sure about UNSUPPORTED? MAV_CMD_REQUEST_MESSAGE *is* (or rather will be) supported. I think DENIED makes more sense according to the current wording in the mavlink documentation.

**Comment by hamishwillee** [comment]
@dayjaby You're correct: `MAV_CMD_REQUEST_MESSAGE` itself is supported, so returning [MAV_RESULT_UNSUPPORTED](https://mavlink.io/en/messages/common.html#MAV_RESULT_UNSUPPORTED) is definitely incorrect (denied is correct).

My original thinking here was that we'd use unsupported to indicate that streaming a particular message is unsupported vs just that they might have additional params that need to be set. But creating an inconsistency in API use like this is not smart. Thanks for pointing this out.

**Comment by hamishwillee** [comment]
This has been done. Since not every message can be streamed/emitted, the default behaviour is to return "denied" for messages for which a stream base class has not been created. Creating a base class is trivially easy though, if needed.
