### ISSUE TITLE
Takeoff not responding properly in position control

### ISSUE THREAD

**Issue by bresch** [PX4/Firmware#11452]
@MaEtUgR I create this Issue to keep track of what we discussed on slack.

**Describe the bug**
While armed in position control with the throttle stick low, the flight task generates a negative setpoint. When now the user moves the throttle stick above 50%, the setpoint has to go positive before triggering the smooth takeoff. However, with the dynamics of the smooth flight tasks, this takes and depends of some parameters such as the max down velocity, vertical acceleration and jerk limitations.
I see two ways to solve that:
1. Make the flight task aware of the current state (the flight task will then not output a downward sertpint while on ground)
2. Modify the constraint in mc_pos_control and feet it back to the flight task (I tried that on a branch)
The problem is that both solutions introduce a feedback to the flight task and I know that @stifael wanted to avoid that. Do you have an other solution? 

**To Reproduce**
In position control mode (using a smoothing FlightTask with low vertical acceleration and jerk)
Set the throttle stick to low
Arm and wait a few seconds
Raise the stick above 50%, it will take some time before taking off

To avoid this issue :
- Use a spring-loaded throttle stick or center the throttle stick before arming and use an arm switch
- Arm and directly center the throttle stick

**Expected behavior**
The drone should takeoff as soon as the throttle stick is above 50%

**Log Files and Screenshots**
![takeoff_delay](https://user-images.githubusercontent.com/14822839/52703607-03a4e100-2f7f-11e9-987c-fcd97645893d.png)

**Proposed solution**
I tried the 2nd solution proposed in the description and limit the downward velocity constraint while the vehicle is on ground, here is the result:
![smooth_takeoff_refactor](https://user-images.githubusercontent.com/14822839/52703817-7dd56580-2f7f-11e9-98ea-db9ad85ed406.png)

@Stifael I know that you want to avoid having feedback to the FlightTask, but I can't find a cleaner solution. Let's discuss that here.

**Comment by bresch** [comment]
Note that having feedback to the FlightTask will make #10659 easy to fix.

**Comment by Stifael** [comment]
I mean it really depends what kind of feedback it is. For instance, if the vehicle is landed and not in smooth-takeoff, the flighttask reactivate itself (https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L736). During this reactivation, the setpoint-smoothing could be turned off

**Comment by Stifael** [comment]
Just guessing: you probably could reset the smoothing in [here](https://github.com/PX4/Firmware/blob/master/src/lib/FlightTasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp#L41)

**Comment by bresch** [comment]
@Stifael The problem with the reactivate strategy is that I disabled it for the SmoothVel FlightTask because it can't reach the required velocity setpoint to trigger smooth takeoff in one `dt`. Can I maybe add a condition for smooth takeoff on the jerk setpoint?
