### ISSUE TITLE
Is there a propeller break protection function?

### ISSUE THREAD

**Issue by zhuchunwu** [PX4/Firmware#11483]
For a six-axis aircraft, when there is a problem with the power on one of the axis, such as a propeller break, motor or ESC failure, there should be the ability to continue flying. So, I would like to ask a question: In the absence of remote control, such as in offboard or auto mission mode, if a propeller is broken, can the aircraft continue to fly? Does the px4 code have protection against this situation?

If px4 doesn't have this feature yet, is there any plan to develop this feature in the future?

**Comment by julianoes** [comment]
For the flight controller to react to a propeller/motor/ESC failure it first would have to detect it. This requires ESCs with feedback which are not very common yet. Once there is feedback appropriate action could be taken. This is currently not implemented yet and there is no active work towards that just yet.

One thing to cope better with failures like this e.g. with a hexacopter or octocopter is to fly with higher integral (I-term) gains which means that the PID controllers can compensate for loss of power over time. However, this can also lead to worse performance in general, so it's a trade-off to make, and it needs to be tested for each airframe.
