### ISSUE TITLE
Minimum value for MIS_YAW_ERR parameter?

### ISSUE THREAD

**Issue by ktskt** [PX4/Firmware#11496]
**Describe the bug**
Dear developers.

I think MIS_YAW_ERR should have some minimum value --- definitely not zero.
Otherwise, a drone may be stuck in the sky.

**To Reproduce**
param set MIS_YAW_ERR  0.0 or small value.

**Expected behavior**
Drone may be stuck in the sky

**Drone (please complete the following information):**
SITL iRiS+ model (1.8.1)

**Comment by julianoes** [comment]
Feel free to make a pull request to fix it.
