### ISSUE TITLE
Replay is broken in master

### ISSUE THREAD

**Issue by roangel** [PX4/Firmware#11501]
**Description of the bug:**
When trying to replay a logfile with one of the latest versions of master (b104b55ceccf7b), I get the following:
![image](https://user-images.githubusercontent.com/21340299/53007251-2891cc00-3437-11e9-8370-4a6eccf1ff48.png)

There is the line: Replay done (published 0 msgs, 0.000 s)

The resulting file took 0.000 s to replay, and then when I plot the replayed file, the topics are empty.

When I try to replay the same file in stable (V1.8.2), I get:
![image](https://user-images.githubusercontent.com/21340299/53006976-a2758580-3436-11e9-8f03-f049f2808cd9.png)

which is normal behaviour. I can read the output file normally.

With some other files I even get some messages published but still 0.000 s:
![image](https://user-images.githubusercontent.com/21340299/53006817-43177580-3436-11e9-9325-c06c4e29576b.png)

**Comment by bkueng** [comment]
> When trying to replay a logfile with one of the latest versions of master ([b104b55](https://github.com/PX4/Firmware/commit/b104b55ceccf7b794fe626ca8c8e967a7d77096f)), I get the following:

As the warning shows you the message format changed, and it's not possible to replay that file. You need to replay it with the same (or similar) version as it was recorded with, or add a compatibility layer in https://github.com/PX4/Firmware/blob/master/src/modules/replay/replay_main.cpp#L364.

> With some other files I even get some messages published but still 0.000 s:

Have you looked at the log file? 0 would mean it was just very fast (small log?).
