### ISSUE TITLE
Offboard: Fixed Wing Position Controller does not output Thrust

### ISSUE THREAD

**Issue by troffel1** [PX4/Firmware#11512]
Hi there,

Somewhat related to closed issues and merged fixes: [#5927](https://github.com/PX4/Firmware/issues/5927), [#630](https://github.com/mavlink/mavros/issues/630), and [#6112](https://github.com/PX4/Firmware/pull/6112).

**For fixed wing offboard control**
(CASE I): fw_pos_control_l1 does not generate thrust setpoints after receiving velocity setpoints in position setpoint triplet topic. 
(CASE II): Vehicle does not enter offboard mode or arms after sending separate thrust setpoints

**To reproduce**

1. Similar to the [offboard example](https://dev.px4.io/en/ros/mavros_offboard.html), send:
(CASE I):

```
mavros_msgs::PositionTarget target;
target.header.stamp = ros::Time::now();
target.coordinate_frame = 8;
target.type_mask=0b011111000111;
target.velocity.x=0;
target.velocity.y=10;
target.velocity.z=0;
target.yaw_rate = 0.05;
```

or, 
(CASE II):

```
mavros_msgs::Thrust targetthrust;
targetthrust.header.stamp = ros::Time::now();
targetthrust.thrust = 0.5;
```

(CASE I): Fixed wing enters OFFBOARD mode and arms. position_setpoint_triplet topic contains desired velocity.
(CASE II): Fixed wing does not enter OFFBOARD mode and does not arm. 

(CASE I): vehicle_attitude_setpoint topic contains different roll & yaw setpoints while in OFFBOARD mode, no thrust setpoint generated 
(CASE II): same as in 2.

**Expected behavior**
Just as for the multicopter Iris and the VTOL, which took off and displayed behavior as expected with this method (with positive velocity.z setpoint).

Is this a bug, or am I doing something wrong? 

**Log Files**
(CASE I) https://review.px4.io/plot_app?log=3dd4e868-a89b-40e2-a886-651c61ba0869
CASE II) https://review.px4.io/plot_app?log=d9769efa-a316-41b7-8cd7-8697eb293604

Thanks!

**Comment by Jaeyoung-Lim** [comment]
@troffel1 In case of attitude setpoints, it is now working after #12311 #12149
