### ISSUE TITLE
Copter cant fly with following z setpoint

### ISSUE THREAD

**Issue by E666GT** [PX4/Firmware#11530]
I make some changes in Firmware/src/ pos control module. I set up a setpoint of z, then I thought I maybe see the copter fly with the setpoint. For example, I set z＝-3, but it obviously flies much much higher. What's the supposed problem？
![88a9c911-9f99-4205-bfda-cee7d886b3d5](https://user-images.githubusercontent.com/44794635/53282109-28af0600-376e-11e9-827f-050c34f26a09.png)

Hardware Pixhawk
Version: 1.9.0a

**Comment by E666GT** [comment]
Here is the DIY code, start from line 206th.
https://github.com/E666GT/Firmware/blob/v190a_setout/src/modules/mc_pos_control/PositionControl.cpp

**Comment by julianoes** [comment]
Sorry for the late response here but I'm not sure anyone has time to review or debug your custom code here. Hopefully you could resolve your issue in the meantime.

If you have this issue with the default/unchanged code than that would be something we would have to have a closer look at.
