### ISSUE TITLE
Wrong UDP Port when using -t argument

### ISSUE THREAD

**Issue by hxdnshx** [PX4/Firmware#11544]
**Describe the bug**
When I use `-t IPAddress` argument of command `mavlink start`, pixhawk(SITL) connect to GCS automatically, but with a random port number(such as 49224), rather than the value of argument `-u PortNumber` or the default value. This unwanted behaviour cause GCS unable to send any command to pixhawk.

**To Reproduce**

1. Luanch a px4 docker container
>docker run -it --privileged -p 14562:14556/udp --name=mycontainer px4io/px4-dev-ros:lat
est bash
2. Clone px4 firmware
>git clone --recursive https://github.com/PX4/Firmware.git
3. Build,Source and launch(From [documention](https://dev.px4.io/v1.8.2/en/simulation/multi-vehicle-simulation.html))
>cd Firmware/
>make posix_sitl_default gazebo
4. Start a new mavlink connection in px4 shell
>px4> mavlink start -x -u 14557 -t 192.168.1.2 -o 14550 -r 4000000
5. Open GCS, and check whether GCS can receive any parameter from pixhawk
https://i.loli.net/2019/02/26/5c74bed5cd11d.png

Note:It seems only occurs in Windows Docker? 

**Expected behavior**
Pixhawk connect to GCS with correct port.

**Comment by bkueng** [comment]
> Note:It seems only occurs in Windows Docker?

This could indeed be docker-related. The code does not do anything different in terms of ports when you specify a target IP. Can you look at the network traffic?

**Comment by hxdnshx** [comment]
You're right.
I set the wrong host IP which isn't in the Docker network. So every udp packet send to host are processed by NAT.
In conclusion, for any users who using `-t` parameter, you should use the host IP Address in 'vEthernet (DockerNAT)' network.
Thanks.
