### ISSUE TITLE
Gazebo SITL simulation build fail in macOS

### ISSUE THREAD

**Issue by feemi** [PX4/Firmware#11553]
**Describe the bug**
I am not able to successfully build and run sitl simulation on gazebo due to some errors. Probably because of opencv 4.0.1 dependency.

**Environment**
MacOS Mojave 10.14.3
Brew packages upgraded.
firmware: master branch

**To Reproduce**
1. Checkout master branch
2. build with command make px4_sitl gazebo_standard_vtol

**Expected behavior**
Firmware must be built and gazebo should be opened.

**Log Files and Screenshots**
[px4-build-error-mac.log](https://github.com/PX4/Firmware/files/2910028/px4-build-error-mac.log)

**Comment by TSC21** [comment]
You need to downgrade OpenCV to version 3 or bellow.
