### ISSUE TITLE
VTOL return mode produces its own waypoint

### ISSUE THREAD

**Issue by lingbuweibu** [PX4/Firmware#11558]
I use VTOL flight mission, when the end of the mission, the aircraft changes RTL mode, fixed wing hovering high at home point, which is still within the normal range. When the altitude reaches the return altitude, the aircraft convert to rotator and flies towards another waypoint. It is shown on the web page that there is a mission point at that place. There is no actual mission point at all. What is the situation? I use the 1.8.1 generation code, code bug？[https://logs.px4.io/plot_app?log=78dc7c89-db18-4482-8201-f7c026b32d4d](http://url)

**Comment by julianoes** [comment]
A mission item with an RTL command is added at the end if RTL is enabled as part of the mission setup. That's expected.
