### ISSUE TITLE
Pixhawk 4 and Pikhawk 4mini v5 not disarming.

### ISSUE THREAD

**Issue by Junkim3DR** [PX4/Firmware#11569]
**Description**
UAV is not disarming manually nor automatically, same issue when using Kill Switch.
Changed to Stable firmware and disarm functions where working as expected.

**Log Files**
Pixhawk 4mini v5 _Commmit:_ 0df34af1
https://review.px4.io/plot_app?log=b69fc363-d90d-49d1-8cf4-ecb6122f3202&fbclid=IwAR2DQunVucBs96HvJiQ9KvGzdutroVqC33kkPLZk8crRz0QyFi97vb1qy2Q

Pikhawk 4 v5 _Commmit:_ 0df34af1
https://review.px4.io/plot_app?log=e715787a-7f9f-45d4-9947-e5b0e1576773&fbclid=IwAR3dsmfYIADvrCuK_24NColLyb5a2E1UnXGX25eYMjg21_FRJSy3evWkG_4

**Drone**
- Multicopter.
- DJI Flame Wheel F450.
@dagar

**Comment by dagar** [comment]
How were you attempting to disarm? Do you recall the last time this was working correctly (without going all the way back to stable)?

**Comment by dagar** [comment]
The kill switch was bouncing. What's the history of these exact setups?

![screen shot 2019-03-01 at 6 29 32 pm](https://user-images.githubusercontent.com/84712/53672321-04609700-3c50-11e9-8350-f4cd3fd9f49e.png)

Other oddities.
 - the estimator stops responding on the first attempted disarm. 
![screen shot 2019-03-01 at 6 34 16 pm](https://user-images.githubusercontent.com/84712/53672472-b1d3aa80-3c50-11e9-93da-2a4adc54a01a.png)
 - no cpuload

**Comment by dagar** [comment]
Just noticed the logger watchdog activated (which explains some of the other problems), but doesn't tell us what the core problem is.

![screen shot 2019-03-01 at 6 38 40 pm](https://user-images.githubusercontent.com/84712/53672601-450ce000-3c51-11e9-9f00-a0aad175c90a.png)

**Comment by dagar** [comment]
There's something running in LPWORK that's misbehaving.

![screen shot 2019-03-01 at 7 55 10 pm](https://user-images.githubusercontent.com/84712/53674439-f6187800-3c5b-11e9-9a82-7d803813307c.png)

**Comment by dagar** [comment]
@Junkim3DR could you comment on the status lights and buzzer? Can you verify if they're working or not? Any differences compared to stable?

**Comment by dagar** [comment]
It's something related to `mtd` on fmu-v5. The param save is blocking (LPWORK).

**Comment by dagar** [comment]
Last working commit. https://github.com/PX4/Firmware/commit/0d170a0eaf51adec6deb550642228f80c97b3c1f

**Comment by dagar** [comment]
@davids5 https://github.com/PX4/Firmware/commit/0846059646990fd4fbe4a884dbd1a8ff46d559c1 is the culprit. 

Many thanks to @mcsauder for the hands on debugging.

**Comment by dagar** [comment]
GPIO_nARMED conflicts with SPI2 SCK (FRAM).

![screen shot 2019-03-02 at 4 43 21 pm](https://user-images.githubusercontent.com/84712/53687991-52d26c00-3d0a-11e9-8533-4dcac6c8fc6f.png)

![screen shot 2019-03-02 at 4 44 36 pm](https://user-images.githubusercontent.com/84712/53687998-801f1a00-3d0a-11e9-8917-5185ad40d488.png)

**Comment by mcsauder** [comment]
@dagar , #11575.

Thanks for localizing that!

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/Firmware/pull/11575
