### ISSUE TITLE
FW idle rpm after arming too high

### ISSUE THREAD

**Issue by MiguelSpare** [PX4/Firmware#11586]
Hello,

I installed the PX4 1.8.2 on a Pixhawk controlling a plane.
When I arm the controller, motor starts to spin at too high RPM. It is not a problem before takeoff, but it is a problem to land as it is always pushing when I try to slow down.
I calibrated several times the ESC, tried to modify FW_THR_IDLE, FW_THR_MIN, but motor spins always at 1200RPM.
I "googled" and found several issues related to multicopters, but nothing about Fixed Wings.

Does anybody have any idea how to lower this RPM?

Thanks in advance

**Comment by julianoes** [comment]
Check the param https://dev.px4.io/v1.9.0/en/advanced/parameter_reference.html#PWM_MAIN_MIN4 (or whatever param maps to the output to the motor).
