### ISSUE TITLE
SITL, Model: plane, [Err] [gazebo_mavlink_interface.cpp:1166] Error opening serial device: open: No such file or directory

### ISSUE THREAD

**Issue by libi95** [PX4/Firmware#11598]
**Describe the bug**
Sitl simulation of the plane model doesn't work properly, since the gazebo_mavlink_interface doesn't seem to be able to open the serial device.
 
http://discuss.px4.io/t/sitl-gazebo-plane-error-with-gazebo-mavlink-interface/9852

**To Reproduce**
execute: 
~/src/Firmware$ make -j4 px4_sitl_default gazebo_plane
on command line.

**Expected behavior**
usual Sitl simulation: Opening of Gazebo with world/model + conection to PX4 over QGC

**Drone (please complete the following information):**
- (Not relevant for issue but need SITL to alter model for) Project Dipper (focus project at ETH)
https://dipper.ethz.ch/

**Screenshots**

![screenshot from 2019-03-06 16-52-38](https://user-images.githubusercontent.com/39123851/53894482-76f6bb80-4030-11e9-879c-1d4fd2ebacab.png)
![screenshot from 2019-03-06 16-52-49](https://user-images.githubusercontent.com/39123851/53894483-76f6bb80-4030-11e9-888e-d478c222f3a8.png)
![screenshot from 2019-03-06 16-52-55](https://user-images.githubusercontent.com/39123851/53894486-76f6bb80-4030-11e9-88c6-21b1548846b5.png)
![screenshot from 2019-03-06 16-52-58](https://user-images.githubusercontent.com/39123851/53894487-778f5200-4030-11e9-844d-d7a8e61b229c.png)
![screenshot from 2019-03-06 16-53-03](https://user-images.githubusercontent.com/39123851/53894488-778f5200-4030-11e9-8878-dea9f2ef6e85.png)

**Comment by lamping7** [comment]
I'm not sure if this is your problem, but that error is usually caused when the PATHs aren't setup correctly. I'd need to test the make targets.

**Comment by libi95** [comment]
After installing the latest version of Ubuntu (18.04 LTS) the Simulation worked properly. It then was an issue related to my system, so the original code must be working properly. Sry for that and thanks for your reply!!
