### ISSUE TITLE
mavlink forward question

### ISSUE THREAD

**Issue by ToppingXu** [PX4/Firmware#11591]
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L2518

I think it should be "message_buffer_mark_read(read_count);"
@julianoes can you confirm?
Thanks

**Comment by julianoes** [comment]
@ToppingXu can you add some context for me to understand please?

Here are some questions that you could try to answer:
What is the problem that you ran into? What was expected but what happened instead? Why  is it required? What is the change?

**Comment by ToppingXu** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L2467

it will lose some data. "message_buffer_mark_read(available)"  this will mark all date readed but we only parsed one message.

**Comment by julianoes** [comment]
Hmm.

Do you know what this does?
```
available = message_buffer_get_ptr((void **)&read_ptr, &is_part);
```

**Comment by ToppingXu** [comment]
Correct me if l was wrong

**Comment by ToppingXu** [comment]
But when parse the second part it will stop if got a full msg. And available value is the whole data len.

**Comment by ToppingXu** [comment]
Sorry, l understand it now. Thanks for your support

**Comment by julianoes** [comment]
So it's correct? I was going to have an in-depth look  when I have time.

**Comment by julianoes** [comment]
Closing as stale.
