### ISSUE TITLE
Log EKF output from initialization

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#11605]
The estimated states are not logged until EKF2 declares tilt_align = true. This is suboptimal since it makes it hard to discover issues with the EKF initialization such as https://github.com/PX4/ecl/pull/586

**Comment by dagar** [comment]
We'd need to make sure they're properly marked as invalid.

**Comment by CarlOlsson** [comment]
Still an issue

**Comment by dagar** [comment]
You should be seeing `estimator_status` from the beginning (which has the states). Are you talking about also wanting to see `vehicle_attitude` and `vehicle_local_position`?

**Comment by CarlOlsson** [comment]
yeah I was thinking about the output from the output predictor data before tilt align. But it is a very specific thing and I guess is not relevant enough to keep this open for now
