### ISSUE TITLE
VTOL position control in FW cannot control thrust

### ISSUE THREAD

**Issue by melisab** [PX4/Firmware#11628]
In VTOL plane after transitioning to FW mode in position control it seems that the throttle up and down doesn't increase or reduce the cruise speed. Is there any setting I missed?

Also, in position control or altitude control, with a 12V battery (3 cells), the automatic cruise speed (ground speed) is around 20 meters per second, depending on the wind. At that speed the current draw is around 10A. But with a 16V battery (4 cells), the automatic cruise speed (ground speed) is around 30 meters per second and the current draw jumps up to around 20A. With 30% higher voltage and double the current, the power output of the airplane is almost 3 times higher. Why would the cruise speed change with different battery voltage?

**Comment by RomanBapst** [comment]
@melisab Please provide a log file.

**Comment by julianoes** [comment]
Closing until we get a log file.
