### ISSUE TITLE
Loaded firmware for board id: 50,0 size: 1657824 bytes (80.31%), waiting for the bootloader

### ISSUE THREAD

**Issue by NiranjanRavi1993** [PX4/Firmware#11624]
Hi,
    I have a **pixhawk 4**  board with me. I am using **px4 flight stack**. I was flashing my code into the device. It was working fine.
But all of a sudden this started happening:

**niranjan@niranjan-Predator-G3-571:~/Firmware$ make px4_fmu-v5_default upload
ninja: Entering directory `/home/niranjan/Firmware/build/px4_fmu-v5_default'
[2/3] uploading px4**
**Loaded firmware for board id: 50,0 size: 1657824 bytes (80.31%), waiting for the bootloader...**

It keeps on waiting and no response from the board. I tried changing the USB, unplugging and re-plugging. It did not help. Still, the issue persists.

I then opened **Qgroundcontrol**. This time the board got detected the upgrade was successful. But my code changes were not present. The simple_app fie was also not shown up in the **Mavlink console.** 
I am pretty sure my code is not getting dumped to the board.
 How do I fix it? I saw earlier issues regarding this and I tried the above troubleshooting methods.
But nothing helped.
Can someone please help me solve this issue?
Regards
Niranjan

**Comment by Bunborn** [comment]
Hi, did you ever find a solution?

**Comment by NiranjanRavi1993** [comment]
Yes, it was a quick fix. Take a fresh patch and redo the process but upload the binary file through ground control software.

**Comment by ljemakers** [comment]
Hi, I'm going through the same thing as you. I'd like to get some help on how you solved it.


![bootload](https://user-images.githubusercontent.com/46621106/88804241-945d9400-d1e8-11ea-9fdc-103c6b21551f.png)

**Comment by jmurraylouw** [comment]
Did anybody find a different solution?
I have the same problem with the Pixhawk4 Mini.

It does not work to use v3 or v2.

**Comment by vibes99** [comment]
Hi, I'm also going through a similar problem. Has anyone been able to resolve it? 
Currently using Pixhawk4 mini board and trying to flash the code onto the controller.

**Comment by Juno-cyber** [comment]
meet this problem too,I can upload .px4 file from QGC,but can not easily use make.. command.
it's not convenient,
