### ISSUE TITLE
sending global position in offboard mode

### ISSUE THREAD

**Issue by garfieldG** [PX4/Firmware#11625]
Hi,

Posting this issue again, the first one closed automatically with no response https://github.com/PX4/Firmware/issues/10917

I encountered a situation in which my drone reports it's position in global ( using POSITION_TARGET_GLOBAL_INT message), but receives position commands from offboard in local (SET_POSITION_TARGET_LOCAL_NED).
Because of the situation POSITION_TARGET_GLOBAL_INT that is reported to the GCS contains zeros in lat_int, lon_int and alt fields.

I investigated it a little and noticed that it happens due to the fact that while the fcc is in offboard mode the only place that position_setpoint_triplet is published from is mavlink_receiver when receiving SET_POSITION_TARGET_LOCAL_NED message and there is no reference to current.lat, current.lon and current.alt there.

**Comment by julianoes** [comment]
Thanks for raising this. So you are saying that lat/lon here are not populated here?

https://github.com/PX4/Firmware/blob/59c555aec36aa5b1c1edac8d0d09fb90a36a3722/src/modules/mavlink/mavlink_messages.cpp#L3141-L3150

**Comment by garfieldG** [comment]
@julianoes Exactly, only with zeros.
