### ISSUE TITLE
UTM_GLOBAL_POSITION Message for collision avoidance is not send on Pixhawk4 with FW 1.9.0beta

### ISSUE THREAD

**Issue by NAmmann** [PX4/Firmware#11656]
Tying to use the UTM_GLOBAL_POSITION message for collision avoidance with Pixhawk4 and PX4 FW 1.9.0beta. But the MavLink Inspector does not show the message. Not on the telemetry one nor two port.

**Comment by LorenzMeier** [comment]
I checked and it is enabled on both channels. So it looks like one of the conditions to send it is not met.

**Comment by LorenzMeier** [comment]
Code: https://github.com/PX4/Firmware/blob/0b4751d03167c4ee147f2e91a94f9919baea70e1/src/modules/mavlink/mavlink_messages.cpp#L1692-L1879

Stream config: https://github.com/PX4/Firmware/blob/6672284871d4cd4163e99d68e75831d0495f58c8/src/modules/mavlink/mavlink_main.cpp#L1677

**Comment by NAmmann** [comment]
What are the exact conditions to be met for activating the sending of the message?

**Comment by LorenzMeier** [comment]
There are no conditions according to the code. I was wondering if your link might be saturated? What is the output of "mavlink status"?

**Comment by NAmmann** [comment]
Zur Zeit habe ich eine USB und D2X Verbindung.
![mavlink status](https://user-images.githubusercontent.com/28739585/54545470-09d51580-49a2-11e9-8ab5-a79084ab3d53.PNG)

**Comment by NAmmann** [comment]
Oh. And this is from a Pixhawk2 Cube. I wanted to check if my problem is just with the Pixhawk 4. And it turns out, that it is not.

**Comment by NAmmann** [comment]
Hier nun der Mavlink Status beim Pixhawk 4: ![mavlink status](https://user-images.githubusercontent.com/28739585/54546039-3178ad80-49a3-11e9-9293-86df662d659f.PNG)
Das zweite Device ist das D2X, auf welchem die UTM_GLOBAL_POSITION Nachricht relevant ist.

**Comment by eyeam3** [comment]
I tested this on the bench and receive the UTM_GLOBAL_POSITION on telem1 and telem2. What version of QGC do you use when running Mavlink Inspector?

**Comment by dk7xe** [comment]
https://github.com/PX4/Firmware/issues/11718

**Comment by dk7xe** [comment]
Similar issue on NXP_FMUK66_V3 #11718

**Comment by NAmmann** [comment]
Updating the QGC to a version understanding the message and setting MAV_PROTO_VER = 2 solves the problem.
