### ISSUE TITLE
error loading <rosparam> tag in px4_config.yaml

### ISSUE THREAD

**Issue by senthilarul** [PX4/Firmware#11662]
I tried running the px4 sitl on gazebo with mavros and encountered this issue:

```
error loading <rosparam> tag:
        file /home/catkin_ws/src/mavros/mavros/launch/px4_config.yaml contains invalid YAML:
could not determine a constructor for the tag '!degrees'
in "<string>", line 63, column 27:
angular_velocity_stdev: !degrees 0.02
^
XML is <rosparam command="load" file="$(arg config_yaml)"/>
The traceback for the exception was written to the log file
```

I have previous tried running the multi uav simulation and had no trouble with it. Recently I had to create a fresh installation on a new computer and I am having trouble running mavros and px4 sitl together. How should I rectify this issue?

Any help is appreciated. Thanks in advance.

**Comment by Dines97** [comment]
I have the same issue with you, I also made a clean ubuntu installation. In addition, I can say that I initially used ubuntu 16.04.5 (Everything worked here) and was updated to 16.04.6 (And here it is not)

**Comment by AnnaMiG** [comment]
I am having the same issue. Does anybody know why this is happening?

**Comment by tmarkmann** [comment]
I solved the issue by downgrading PyYAML from 5.1 to 3.13 manually with "pip uninstall PyYAML" and "pip install PyYAML==3.13"

**Comment by mrivi** [comment]
I can confirm that downgrading PyYAML from 5.1 to 3.13 works

**Comment by julianoes** [comment]
I ran into this today as well. What is this exclamation mark for?

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/55475078-c5638f80-55c7-11e9-8679-74ea5a3d7b4e.png)
I have the same issue.

**Comment by julianoes** [comment]
For now a workaround is to change:
```
diff --git a/mavros/launch/px4_config.yaml b/mavros/launch/px4_config.yaml
index d199f17..a3edcce 100644
--- a/mavros/launch/px4_config.yaml
+++ b/mavros/launch/px4_config.yaml
@@ -60,7 +60,7 @@ imu:
   frame_id: "base_link"
   # need find actual values
   linear_acceleration_stdev: 0.0003
-  angular_velocity_stdev: !degrees 0.02
+  angular_velocity_stdev: "!degrees 0.02"
   orientation_stdev: 1.0
   magnetic_stdev: 0.0
 
@@ -211,7 +211,7 @@ odometry:
 # px4flow
 px4flow:
   frame_id: "px4flow"
-  ranger_fov: !degrees 6.8  # 6.8 degreens at 5 meters, 31 degrees at 1 meter
+  ranger_fov: "!degrees 6.8"  # 6.8 degreens at 5 meters, 31 degrees at 1 meter
   ranger_min_range: 0.3     # meters
   ranger_max_range: 5.0     # meters
```

but I assume that changes behavior and is not the right fix.

**Comment by jsalvador4** [comment]
I also have a similar error, is there any solution to fix in this case?
![image](https://user-images.githubusercontent.com/6030455/55786667-ff93cc00-5ab4-11e9-89c1-27046d0fc75a.png)

**Comment by julianoes** [comment]
@jsalvador4 see my answer above.

**Comment by julianoes** [comment]
Check what's causing your issue and see what xan fix it.

**Comment by w0rt4** [comment]
https://github.com/mavlink/mavros/commit/1e9d805632eb6133c46859104f0fcec2778accdc#diff-1081d05fe29e8c7f51693863fe64cd9f
@jsalvador4 this should fix your issue (in my case i have exactly the same error and it helps)

**Comment by jsalvador4** [comment]
@w0rt4 Thanks, worked fine!
