### ISSUE TITLE
The SF11/C is not publish the distance data when the PX4Flow Smart Camera is connected.

### ISSUE THREAD

**Issue by bozkurthan** [PX4/Firmware#11690]
**Describe the bug**
Hello, I'm using SF11/C for distance sensor and PX4Flow Optical Flow Camera in Pixhawk 2.1 (Cube). I don't have an ultrasonic module on PX4Flow. My setup is shown below.

![IMG!UNITO-UNDERSCORE!20190321!UNITO-UNDERSCORE!105005](https://user-images.githubusercontent.com/44507545/54739097-dbd11a80-4bc7-11e9-8723-1a7211c8508c.jpg)

![IMG!UNITO-UNDERSCORE!20190321!UNITO-UNDERSCORE!105054](https://user-images.githubusercontent.com/44507545/54739101-decc0b00-4bc7-11e9-8b79-ac263ae04ccc.jpg)

Like images PX4Flow Camera is connected to I2C and SF11/C is connected to Telemetry 1.
The bug is revealed when I connected both of sensor to Pixhawk. SF11/C publishes distance sensor when PX4FLow Camera isn't connected. But, When I connect the PX4Flow to Pixhawk, PX4Flow publishes Zero distance which mentioned before this issue https://github.com/PX4/Flow/issues/101. In addition SF11/C cannot communicate Pixhawk when PX4Flow is connected.

Without PX4Flow Camera `sf0x test` and Current Distance Analyze
![WITHOUT FLOW](https://user-images.githubusercontent.com/44507545/54739686-15a32080-4bca-11e9-91ca-975a9b9f976e.png)
![WITHOUT FLOW ANALYZE](https://user-images.githubusercontent.com/44507545/54740006-15efeb80-4bcb-11e9-8d57-360bba649224.png)

With PX4Flow Camera`sf0x test` and Current Distance Analyze
![WITH FLOW](https://user-images.githubusercontent.com/44507545/54739700-22c00f80-4bca-11e9-830b-d509b85f9c4d.png)
![WITH FLOW ANALYZE](https://user-images.githubusercontent.com/44507545/54740009-17b9af00-4bcb-11e9-84aa-990f4d9f4f50.png)

In documentations, Laser Altimeters sensor can be connect instead of Ultrasonic module. But, I didn't find any schematic for this. 

I examined the drivers of PX4Flow and SF0X. They have same definition for Uorb distance_report topic. 

PX4FLOW:
https://github.com/PX4/Firmware/blob/14ef009aabf5723b1a9f8fe5489844c961f05fab/src/drivers/px4flow/px4flow.cpp#L554-L566

SF0X:
https://github.com/PX4/Firmware/blob/14ef009aabf5723b1a9f8fe5489844c961f05fab/src/drivers/distance_sensor/sf0x/sf0x.cpp#L514-L528

Also they have same id for publishing. I tried to give different ID but it didn't work.
Furthermore, I just commented lines on PX4Flow. However, it didn't work as well.

**To Reproduce**

1. Connect SF11/C to Pixhawk Telemetry 1 and configure
1. Can be able to see Current Distance
1. Connect PX4FLow to Pixhawk I2C
1. See Current Distance Value Zero

**Expected behavior**
Pixhawk can be able to see correct distance values when PX4Flow and SF11/C are connected.

**Comment by bozkurthan** [comment]
@dagar fyi.
I wasn't able to test on I2C bus with same setup (I don't have 1 more I2C connector for this). But today I able to test with poor connection on I2C bus. 
The problem is that PX4Flow and SF11/C must connect on same I2C bus because of PX4Flow driver. So, it can be close. 
Here correct setup:
![IMG_20190322_153250](https://user-images.githubusercontent.com/44507545/54824804-0a7ced00-4cbd-11e9-82ce-99046d81524b.jpg)

![IMG_20190322_153318](https://user-images.githubusercontent.com/44507545/54824813-0cdf4700-4cbd-11e9-93ea-f4149f7fd0ff.jpg)



In addition, maybe it can be add for future request. (PX4FLow on I2C, SF11/C on Uart) Should I open new Issue or can we continue on this?

**Comment by hamishwillee** [comment]
This also looks related: https://github.com/PX4/Firmware/issues/11227

**Comment by bozkurthan** [comment]
As far as I understand, it is not same issue. @60ericleal60 couldn't get any data from PX4Flow camera but I could. I just have problem with distance sensor.

**Comment by 60ericleal60** [comment]
There is a solder bridge you need to fill to power the distance sensor.

**Comment by bozkurthan** [comment]
You are right. I saw that bridge and I tried to connect SF11/C to it with poor connection but data didn't come Qgroundcontrol. I'll try again with solder.

**Comment by bozkurthan** [comment]
This issue is fixed at #11724 by @DanielePettenuzzo .  I'm closing and will continue on #11689
