### ISSUE TITLE
Vehicle did not respond to request for parameters

### ISSUE THREAD

**Issue by crossa** [PX4/Firmware#11701]
QGC says vehicle did not respond to request for parameters,can not display full interface when connect to pixhawk via telemetry 
The issue appeared after QGC@3.2.3. px4@1.7.2

I found if both 'Emit heatbeat' and 'Request' start of MAVLink telemetry streams' checked in qgc, the loss rete of packet grower up to 90%

 I try to flash the follwing firmware into my pixhwak

px4 1.8.2
the lastest stable version of nuttx-arducopter for pixhawk
ArduCopter 3.6.7 without nuttx
The results are clear.

If using px4@1.8.2 and nuttx-arducopter, both QGC and APM planner can't get all the parameter via radio telemetry.

When using nuttx-arducopter , APM planner still can't get all the parameter via radio telemetry

But the ArduCopter without nuttx works fine !

What changes had been done since px4@1.7.2?
Is the configration of mavlink correct in the firmware?
Is the lunch order of the script located in  init.d  correct? 

https://github.com/mavlink/qgroundcontrol/issues/7301

@julianoes @LorenzMeier @bkueng @dogmaphobic

**Comment by dogmaphobic** [comment]
@crossa How is the Pixhawk connected to QGC?

>I found if both 'Emit heatbeat' and 'Request' start of MAVLink telemetry streams' checked in qgc, the loss rete of packet grower up to 90%

@dagar This sounds like https://github.com/PX4/Firmware/issues/11674

**Comment by crossa** [comment]
QGC connect to pixhawk via radio telemtey and the telemetry is a replica of 3dr 915m radio telemetry. In fact, it is just a wireless serial port.

This issue appeared since px4@1.7.2 released.


I  have tried ardupilot without nuttx provided by apm planner and I find it works fine.

The issue just appears when using the firmware provided by qgc via firmware upgrade.

I find the issues only appears when using the firmware contains rtos.

@dogmaphobic dagar@

**Comment by LorenzMeier** [comment]
Can you take a picture of the autopilot and radio and upload it here please?

**Comment by crossa** [comment]
Ok, here are the pictures.  Was the configuration of mavlink submodule be changed since px4@1.72？

@LorenzMeier 

![pixhawk](https://user-images.githubusercontent.com/10145675/54892386-55c91280-4eec-11e9-8b84-b0ed07b4f531.jpg)
![board](https://user-images.githubusercontent.com/10145675/54892428-785b2b80-4eec-11e9-8c23-00a91da04992.jpg)
![TB2raj2XR7c61BjSZFIXXcZmVXa_!!593796903](https://user-images.githubusercontent.com/10145675/54892432-7abd8580-4eec-11e9-94f7-d5ba0f28aa37.jpg)

**Comment by dagar** [comment]
More Sik radios without flow control.

**Comment by crossa** [comment]
Was the radio telementry without flow control avaliable for the laster statble version of px4 ？

@dagar @LorenzMeier

**Comment by Bosuwort** [comment]
I have the same issue. It always happens that the vehicle can recieve the command from mavlink console at first but have no response later, especially when it transitions to mission mode. I have tried different radio telemetry but it did not work.

**Comment by Bosuwort** [comment]
> I have the same issue. It always happens that the vehicle can recieve the command from mavlink console at first but have no response later, especially when it transitions to mission mode. I have tried different radio telemetry but it did not work.

I fixed it. My custom module occupied too much operation resource and other commands can't be received by the vehicle. I added usleep(500000) in it and there's no issues any more.
