### ISSUE TITLE
ACCELS INCONSISTENT - CHECK CAL on Pixhawk4

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#11709]
**Describe the bug**
I tried master branch today, because of #11694 looks pretty cool. but I got ACCELS INCONSISTENT - CHECK CAL when I tried to arm the copter.

I also tried re-cal and reset parameters, it was not work either.

I tried different Pixhawk4, error is the same.

**To Reproduce**
1. Flash master firmware on Pixhawk4.
2. Press safety switch.
3. Try to arm on radio

**Drone (please complete the following information):**
- DIY F450
- Pixhawk 4

**Comment by bys1123** [comment]
Looks like issue #11695 is the same problem.

**Comment by bys1123** [comment]
Update: It's not real 1.9.0beta1, I didn't roll back submodules successfully.
So, this bug is in one submodule.

**Comment by dagar** [comment]
Thanks for reporting @bys1123. I'll use the existing https://github.com/PX4/Firmware/issues/11695 to track the issue. If you have any additional data please attach it there. This is a blocking issue for the v1.9.0 release.
