### ISSUE TITLE
Pixracer external compass not detected with PX4 (and IS detected with Ardupilot)

### ISSUE THREAD

**Issue by copterspace** [PX4/Firmware#11736]
Pixracer R14 + Radiolink TS100 GPS module (compass QMC5883L, https://ru.aliexpress.com/item/TS100-M8N-gps/32845084683.html). 
QGC v3.4.4.
When I flash Ardupilot firmware via QGC - the board does detect external compass OK.
Then I flash this board with PX4 firmware - it does not detect external compass.

**To Reproduce**
1. Flash pixracer with Ardupilot 
![2019-03-28_10-50-49](https://user-images.githubusercontent.com/38784273/55138231-6bd50e00-514c-11e9-9eb3-5e9cb721e614.png)
![2019-03-28_10-51-36](https://user-images.githubusercontent.com/38784273/55138235-7099c200-514c-11e9-8528-f2e939e205e7.png)

2. See external compass 
![2019-03-28_10-53-09](https://user-images.githubusercontent.com/38784273/55138253-78596680-514c-11e9-8965-6a06d10f7377.png)
![2019-03-28_10-54-22](https://user-images.githubusercontent.com/38784273/55138258-7beced80-514c-11e9-8422-2717071a52f5.png)

3. Flash Pixracer with PX4 flight stack
![2019-03-28_10-55-39](https://user-images.githubusercontent.com/38784273/55138270-81e2ce80-514c-11e9-9801-882bc262ed3f.png)
![2019-03-28_10-56-31](https://user-images.githubusercontent.com/38784273/55138278-85765580-514c-11e9-8679-24116b826b1e.png)

4. External compass not detected
![2019-03-28_10-57-02](https://user-images.githubusercontent.com/38784273/55138291-8ad3a000-514c-11e9-966a-da3850c6fc05.png)
![2019-03-28_10-58-54](https://user-images.githubusercontent.com/38784273/55138304-93c47180-514c-11e9-85f5-f5231ae0a04c.png)

**Expected behavior**
Detect this compass with PX4 firmware, same good as Ardupilot.

It seems to be the same problem described in https://github.com/PX4/Firmware/issues/7607. I followed the recommendation "use QGC", but it did not help.
It also seems to be reason of problem I described here - http://discuss.px4.io/t/ekf2-yaw-diverging/10190 - because I used only internal compass, but it works badly.

**Comment by copterspace** [comment]
Actually, driver for QMC5883L is developed, but not yet available in stable release: https://github.com/PX4/Firmware/pull/11140
Another aspect is that it is removed from autostart (https://github.com/PX4/Firmware/pull/11140/commits/c16c3b113ec521046252e366d3c7a9f7b451578b), even if I download developers release in QGC - must start it manually before it can be calibrated:
`qmc5883 start`

I downloaded fresh PX4 repository, added qmc5883 to autostart (https://github.com/PX4/Firmware/pull/11140/commits/c16c3b113ec521046252e366d3c7a9f7b451578b) - now it is visible in QGC: 
![2019-03-28_15-39-35](https://user-images.githubusercontent.com/38784273/55155034-c469d280-516f-11e9-8407-2966e7c7097e.png)


Now will resume the flight tests...

**Comment by copterspace** [comment]
Flight test passed very good.
https://logs.px4.io/plot_app?log=08b75f05-133b-41d5-b940-4ba07247f7d1
I think, you may close this after you add QMC5883L compass driver + autostart to official release.

**Comment by bkueng** [comment]
@dagar shouldn't we enable autostart so that we get it tested?

**Comment by copterspace** [comment]
yes, surely, imho, you should. 
Because if you do not enable autostart - the only way to test it is to start it manually - then it resets after FCU reboots. It is very inconvenient way on real flying drone (you may not have an access to FCU console in the field).
Another way - add autostart to the source code and recompile custom firmware file - which I did. But it may be not very clear way for other users.

**Comment by dagar** [comment]
> @dagar shouldn't we enable autostart so that we get it tested?

Yes, if someone has tested it lets get it added to autostart.
