### ISSUE TITLE
Trim parameter incorrect if using z: in the mixer

### ISSUE THREAD

**Issue by raygamero** [PX4/Firmware#11732]
On 1.7 and 1.8 Pixhawk 1 and Pixhawk 4. If using a mixer that has a Z: line (empty line placeholder) the trim does not recognize that as an empty line.
For example:  If I have a tilt rotor VTOL aircraft with the following channels in the main mixer:
1. Quad Motor
2. Quad Motor
3. Quad Motor
4. Quad Motor
5. Aileron
6. Elevator
7. Empty slot (Z:) 
8. Rudder

In order to trim the rudder servo, I need to change PWM_MAIN_TRIM7.
If multiple lines with z: are present, then the trim parameter would be that many places off.

To reproduce this error:  Find a airframe with mixer that has a z: with another servo after it (or make a custom mixer).  Try to trim that servo on the channel after the z: and observe that it is not the correct one.

**Comment by julianoes** [comment]
Is this still an issue with master? Since a new release 1.9 is coming out soon I don't think much time can be spent on this on older releases.
