### ISSUE TITLE
Incorrect Dev Call info on PX4 / Dronecode properties

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#11735]
An increasing number of users have been reporting incorrect dev call information on some of our properties; please use this issue to track any reports from users.

**Comment by julianoes** [comment]
According to @hamishwillee and from what I can see this is fixed.

**Comment by hamishwillee** [comment]
The docs are definitely fixed - there is just ONE copy now of dev call info, and that is in the master docs .

I'm closing this as "Fixed for now"
