### ISSUE TITLE
PX4Flow integration vetting

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1174]
@DrTon there are two big improvements for PX4FLOW currently in the pipeline: One is a speed increase by 50% done by @dominiho (please push this to Github, and do a PR for code review) and we'll probably change the lens to 12 mm default. Both steps together will give you ~3 m/s forward speed at 1m altitude (sensor running at 500 Hz now!).

Given that this will improve the results greatly, could you please validate that the setup is operational? I don't have a spare unit at hand right now.

I will also go ahead and start the appropriate drivers as default (will do a PR for it). There is no reason we shouldn't support this as a default feature, now that the flow measurements improved to a level where they are useful for everybody.

**Comment by LorenzMeier** [comment]
@kd0aij You're currently happily flying with flow position hold, correct?

**Comment by kd0aij** [comment]
Did some tuning today with 12" props and a 3S battery in the 450. (threw a 10" blade in flight last night, that log is interesting...)
Here's the post-tuning log (adjusted P and D gains for MPC XY, Z)
http://dash.oznet.ch/view/inkEkbCxckV2djZVPGCmEk
* Position hold is working pretty well at 1 to 2m altitude; 
 * what is the max recommended altitude with the stock lens and sonar?
* Should there be a plot for the "distance sensor"?

**Comment by kd0aij** [comment]
a plot from the log above, showing GPS vs LPOS x,y,z

**Comment by kd0aij** [comment]
can't reliably reproduce the above behaviour, even with consistently good flow quality.

**Comment by kd0aij** [comment]
Problems with flow and POSCTL breakage were caused by parameter values being corrupted, or else just changing unexpectedly. The second part of the following video definitely shows behavior with INAV and the Q attitude estimator running. Downward looking Mobius camera to show motion relative to ground, but not that this camera isn't gimballed, so some of the apparent motion will be due to pitch and roll. Log for the second part: https://copy.com/favuQPsmWxQMTVx0
https://youtu.be/fyI7NhFi5f0

**Comment by kd0aij** [comment]
outdoor test of POSCTL with flow yesterday with release_v1.0.0 failed; need to check whether this only works in master

**Comment by kd0aij** [comment]
repeated Posctl test with latest release_v1.0.0 and GPS position hold is good, but flow still isn't.
Checked flow sensor rotation parameter; still correct.

**Comment by kd0aij** [comment]
Need to change the parameter default to 0.0 so that acro mode behavior is normal by default.

**Comment by LorenzMeier** [comment]
Could we get a log of that? I'd love to help hunting down the root cause.

**Comment by kd0aij** [comment]
Logs: https://copy.com/UWMajC7f9kw02rdz
First one is with lens cap on, second with lens cap off.

**Comment by kd0aij** [comment]
Reflashed PX4flow with stable using QGC, verified focus, tested with and without GPS outdoors. Same behavior as last test: won't hold position using optical flow. Seems to fly off in random directions, definitely not toilet-bowling.

**Comment by kd0aij** [comment]
comparing raw flow data to GPS velocity for both working and non-working flow-based position control shows no obvious difference in the flow data:
![nonworkingflow](https://cloud.githubusercontent.com/assets/2300221/8223515/e7661f48-1535-11e5-9b63-1f5a93e7a556.png)
![workingflow](https://cloud.githubusercontent.com/assets/2300221/8223516/e7665c88-1535-11e5-9bf5-9264196a8280.png)

**Comment by LorenzMeier** [comment]
Thanks everybody for contributing!
