### ISSUE TITLE
esc.cpp : esc_status_sub_cb(const uavcan::ReceivedDataStructure<uavcan::equipment::esc::Status> &msg) functionality

### ISSUE THREAD

**Issue by NiranjanRavi1993** [PX4/Firmware#11746]
Hi,
   I am trying to make modifications to understand how 

> 
void UavcanEscController::esc_status_sub_cb(const uavcan::ReceivedDataStructure<uavcan::equipment::esc::Status> &msg)

the above function works. I could see it is been called from uavcan_main.cpp but i could not see any execution for this method when i run my code in qgroundcontrol. I went through the documentation but still could not figure out what i am missing over here. Can someone tell me how to acess this "private" method? 

Thanks and Regards
Niranjan

**Comment by mrpollo** [comment]
Please post questions or support requests on  our forums http://discuss.px4.io/ we use Github Issues for bug submissions only at this time.
