### ISSUE TITLE
Crash, uncontrolled,  also unstable altitute mode. 1.8.2

### ISSUE THREAD

**Issue by Mutoryu** [PX4/Firmware#11753]
Hello. I need a help to understand what happaned to the drone, is it my fault or a bug?

as you can see in the log - drone became unstable and uncontroled.. i didnt know what to do and tried rtl mode. after that drone crashed.
checked everything after crash, nothing loose, nothing disconected or broken, just one propeller..

i know it have some vibrations, its my first drone on f450 frame. Soon, good motors and propellers will arrive..
now its standart f450 frame with 2212 motors and 1045 props.
FC - holybro pixhawk 4. GPS is mounted on long shaft far from any cables..
this log as a crash log
https://logs.px4.io/plot_app?log=7dad6869-c9d4-40ad-b93a-b589033f2c3c

Also had a problem with altitude mode.
on first seconds the drone is like going down with spikes.. 
can see on this log:
https://logs.px4.io/plot_app?log=f87cb0b2-cc71-4328-904b-89cda390b377
on actuator controls the thrust is jumping..
Hope for your help. 
Thanks!

**Comment by cmic0** [comment]
I quickly checked about the altitude hold issue: From log seems that you are hovering at about 35% throttle, while your MPC_THR_HOVER is set to 0.5. This may lead some altitude hold issues..I'd try to adjust the parameter to 0.35.
