### ISSUE TITLE
Fixed wing mission and altitude transition fail

### ISSUE THREAD

**Issue by dannyfpv** [PX4/Firmware#11759]
Vehicle Information:
Airframe: Phantom FPV Flying Wing
Hardware: | PX4_FMU_V3 (V2)
Software Version: | v1.9.0 (beta) (25bf4ba7)
Steps:

1.  Vehicle arms 
1. Take off is smooth

Notes: Flight as expected, but once the mission plan (automated) is triggered, fixed-wing accelerates towards the ground with the nose facing down.

PR #10179 and Master same issues.
https://review.px4.io/plot_app?log=d1c75dae-a1fe-4fc6-b6aa-20cb1f979aa8
Initially, we thought it was the hardware. Last week we did several reboots and inspected the hardware. We tested again today and the same issue persisted.

Video of the issue below:
https://www.youtube.com/watch?v=CdgrCeFI8A0&feature=youtu.be
@dagar what could be the issue?

**Comment by dagar** [comment]
Could you share the mission you planned? Either the file or a screenshot of QGroundControl.

According to the log the waypoint altitude was about 66 meters and when you engaged mission mode you were at 228 meters.

![image](https://user-images.githubusercontent.com/84712/55671555-3a042b80-585f-11e9-81e3-13edfd8548be.png)

**Comment by dannyfpv** [comment]
<img width="1920" alt="Screen Shot 2019-04-08 at 7 09 53 AM" src="https://user-images.githubusercontent.com/31113129/55730738-c0d71680-59cd-11e9-9aa9-7cedb4533a0f.png">

It was flown at a high altitude for testing but the same issue can be seen while flying at low altitude.

**Comment by dagar** [comment]
Could you go to the plan screen to show the altitudes?

**Comment by dannyfpv** [comment]
<img width="1920" alt="Screen Shot 2019-04-08 at 12 11 05 PM" src="https://user-images.githubusercontent.com/31113129/55750204-a6b22e00-59f7-11e9-9ae2-028eb31447d0.png">
plan screen

**Comment by dannyfpv** [comment]
another log fron fixed wing
https://review.px4.io/plot_app?log=1b3c6d44-fd45-4044-a154-172aa87b2609

**Comment by LorenzMeier** [comment]
Did you calibrate the airspeed sensor? If yes, then it should have been impossible to install the tubing incorrectly, which seems to be the root cause here. You have negative airspeed.

<img width="860" alt="Screen Shot 2019-04-13 at 17 20 12" src="https://user-images.githubusercontent.com/1208119/56081697-82e45300-5e10-11e9-875e-809ea9042971.png">

**Comment by dannyfpv** [comment]
After some calibration attempts the air sensor was ready to be tested on flight, there no issues and worked correctly in mission mode.
<img width="762" alt="Screen Shot 2019-04-15 at 9 03 15 AM" src="https://user-images.githubusercontent.com/31113129/56217093-79790780-6017-11e9-808c-f653993a9e1f.png">https://review.px4.io/plot_app?log=cbc1e07b-fbc9-43ac-9723-969d190265f0
