### ISSUE TITLE
Sensor data is passed to the flight controller

### ISSUE THREAD

**Issue by jumppp** [PX4/Firmware#11758]
I am a newbie
I want to transfer sensor data (such as barometer) to the PIX4 flight controller. What should I do? What are the steps and references?
Thank you!

**Comment by julianoes** [comment]
Hi there!

Have you seen these docs? https://dev.px4.io/en/concept/architecture.html

For questions like this it's probably more appropriate to use the forum: http://discuss.px4.io
Also, it helps if you try to describe what problem you are trying to solve. The more context or background we have the better we can help.

**Comment by jumppp** [comment]
@julianoes thank you very much！！
