### ISSUE TITLE
-Werror=cast-align problem on beaglebone_blue_cross

### ISSUE THREAD

**Issue by teknokita** [PX4/Firmware#11751]
I just tried build px4 master branch for beaglebone_blue and get this error:
-Werror=cast-align

**To Reproduce**
make beaglebone_blue_cross 
using tool and lib:
-gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf
-librobotcontrol_1.0.4

get error:
librobotcontrol -> include/rc/mavlink/common/../protocol.h:280:49: error: cast from ‘const char*’ to ‘const uint16_t* {aka const short unsigned int*}’ increases required alignment of target type [-Werror=cast-align]

fix with -Wno-cast-align
file: Firmware/cmake/px4_add_common_flags.cmake
![px4_add_common_flags](https://user-images.githubusercontent.com/1979708/55295144-0f1b7100-5434-11e9-80de-1e7c90133ece.jpg)

**Comment by dagar** [comment]
We need to get Beaglebone into the CI system.

@teknokita you can fix this by ignoring the warning (-Wno-cast-align) on a per module/driver basis. 

Example: https://github.com/PX4/Firmware/blob/0b548fa6849e7a608b4c120fb66a760e51806056/src/drivers/distance_sensor/sf1xx/CMakeLists.txt#L37

**Comment by julianoes** [comment]
@dagar we do now have a beaglebone in CI, right?

**Comment by dagar** [comment]
> @dagar we do now have a beaglebone in CI, right?

Yes.
