### ISSUE TITLE
Don`t work roslaunch px4 posix_sitl.launch

### ISSUE THREAD

**Issue by archee8** [PX4/Firmware#11761]
After updating Firmware, MAVROS and MAVLink roslaunch px4 posix_sitl.launch dont work. There is no iris.sdf in the firmware/Tools/sitl_gazebo/models. I add old version iris.sdf but it did not help. roslaunch px4 posix_sitl.launch conclusion:
`... logging to /home/archee/.ros/log/ec8c8c32-553c-11e9-80fb-f49634e9b2e0/roslaunch-KhazetdinovPC-19970.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://KhazetdinovPC:43333/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    sitl (px4/px4)
    vehicle_spawn_KhazetdinovPC_19970_3293164669616101250 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [19980]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ec8c8c32-553c-11e9-80fb-f49634e9b2e0
process[rosout-1]: started with pid [19993]
started core service [/rosout]
process[sitl-2]: started with pid [20017]
INFO  [px4] Creating symlink /home/archee/src/Firmware/ROMFS/px4fmu_common -> /home/archee/.ros/etc
0 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
process[gazebo-3]: started with pid [20033]
process[gazebo_gui-4]: started with pid [20045]
  SYS_AUTOSTART: curr: 0 -> new: 10016
process[vehicle_spawn_KhazetdinovPC_19970_3293164669616101250-5]: started with pid [20051]
  BAT_N_CELLS: curr: 0 -> new: 3
  CAL_ACC0_ID: curr: 0 -> new: 1376264
  CAL_ACC1_ID: curr: 0 -> new: 1310728
  CAL_ACC_PRIME: curr: 0 -> new: 1376264
  CAL_GYRO0_ID: curr: 0 -> new: 2293768
  CAL_GYRO_PRIME: curr: 0 -> new: 2293768
  CAL_MAG0_ID: curr: 0 -> new: 196616
  CAL_MAG_PRIME: curr: 0 -> new: 196616
  COM_DISARM_LAND: curr: -1.0000 -> new: 0.1000
  COM_OBL_ACT: curr: 0 -> new: 2
  COM_OF_LOSS_T: curr: 0.0000 -> new: 5.0000
  COM_RC_IN_MODE: curr: 0 -> new: 1
  EKF2_ANGERR_INIT: curr: 0.1000 -> new: 0.0100
  EKF2_GBIAS_INIT: curr: 0.1000 -> new: 0.0100
  MC_PITCH_P: curr: 6.5000 -> new: 6.0000
  MC_PITCHRATE_P: curr: 0.1500 -> new: 0.2000
  MC_ROLL_P: curr: 6.5000 -> new: 6.0000
  MC_ROLLRATE_P: curr: 0.1500 -> new: 0.2000
  MPC_HOLD_MAX_Z: curr: 0.6000 -> new: 2.0000
  MPC_Z_VEL_I: curr: 0.0200 -> new: 0.1500
  MPC_Z_VEL_P: curr: 0.2000 -> new: 0.6000
  MPC_XY_P: curr: 0.9500 -> new: 0.8000
  MPC_XY_VEL_P: curr: 0.0900 -> new: 0.2000
  MPC_XY_VEL_D: curr: 0.0100 -> new: 0.0160
  MPC_JERK_MIN: curr: 8.0000 -> new: 10.0000
  MPC_ACC_HOR_MAX: curr: 10.0000 -> new: 3.0000
  NAV_ACC_RAD: curr: 10.0000 -> new: 2.0000
  NAV_DLL_ACT: curr: 0 -> new: 2
  RTL_DESCEND_ALT: curr: 30.0000 -> new: 5.0000
  RTL_LAND_DELAY: curr: -1.0000 -> new: 5.0000
  RTL_RETURN_ALT: curr: 60.0000 -> new: 30.0000
  SDLOG_PROFILE: curr: 3 -> new: 131
  SDLOG_DIRS_MAX: curr: 0 -> new: 7
  SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
  SENS_DPRES_OFF: curr: 0.0000 -> new: 0.0010
* RTL_DESCEND_ALT: curr: 5.0000 -> new: 10.0000
* RTL_LAND_DELAY: curr: 5.0000 -> new: 0.0000
  PWM_MAX: curr: 2000 -> new: 1950
  PWM_MIN: curr: 1000 -> new: 1075
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
INFO  [simulator] Waiting for simulator to connect on TCP port 4560
[ INFO] [1554205577.751135192]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1554205577.752282861]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1554205577.793745793]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1554205577.796162296]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
SpawnModel script started
[INFO] [1554205578.040690, 0.000000]: Loading model XML from file
[INFO] [1554205578.041053, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[INFO] [1554205579.247766, 0.000000]: Calling service /gazebo/spawn_sdf_model
[ INFO] [1554205579.303058700, 0.024000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1554205579.508342, 0.156000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1554205579.526820011, 0.172000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1554205579.534449823, 0.180000000]: Physics dynamic reconfigure ready.
[ INFO] [1554205579.591393652, 0.236000000]: Physics dynamic reconfigure ready.
[vehicle_spawn_KhazetdinovPC_19970_3293164669616101250-5] process has finished cleanly
log file: /home/archee/.ros/log/ec8c8c32-553c-11e9-80fb-f49634e9b2e0/vehicle_spawn_KhazetdinovPC_19970_3293164669616101250-5*.log
`

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/55531558-7a3ba080-56dd-11e9-9479-a3519b098a07.png)
I tried master branch yesterday, works well.

**Comment by archee8** [comment]
I tried master branch but in firmware directory dont have iris.sdf. I copy iris.sdf from old version firmware but i get error than launch posix_sitl

**Comment by lamping7** [comment]
How did you build the firmware? The model gets generated when you build the `sitl_gazebo` submodule. There are different make commands that do this depending on what you're trying to do. But, basically you need to build `sitl_gazebo`. `make px4_sitl_default sitl_gazebo` will build it without launching gazebo.

**Comment by archee8** [comment]
i use this command from dev.px4.io
`make posix_sitl_default gazebo`
`source ~/catkin_ws/devel/setup.bash`    // (optional)
`source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/posix_sitl_default`
`export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)`
`export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo`
`roslaunch px4 posix_sitl.launch`

**Comment by lamping7** [comment]
`posix_sitl_default` has been deprecated. Try `px4_sitl_default`. I can open an issue to fix the docs. Thanks for pointing it out.

**Comment by archee8** [comment]
thank you! everything is working!
