### ISSUE TITLE
Permanent slope during transition

### ISSUE THREAD

**Issue by DavidBouSaba** [PX4/Firmware#11787]
Hello,

We use a PX4 quad X tailsitter configuration and we have the following issue:

For all the transitions tests we made (manual or missions you can see a picture below), the aircraft was never finishing the transition (staying dark pink and never going to light pink on the log meaning full fw mode not reach) and having a stable maintained pitch angle at the end of this transition of 90-74,5 = 14,5°).

![image](https://user-images.githubusercontent.com/48712201/55532368-edc5b980-56ad-11e9-801c-ec7038357565.png)

We please have 2 questions:

- Why the transition is not fully accomplished?
- Where this angle of 14,5° could come from (we have no offset or parameter with this value (the picth offet we have is set to 0)?

Thanks in advance,

**Comment by julianoes** [comment]
Sorry for the late response. Is this still an issue? And if yes, could you add link to a log?

**Comment by julianoes** [comment]
Closing because there is no log so far.
