### ISSUE TITLE
Pixhawk4 won't bootup with current master

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#11786]
**Describe the bug**
Pixhawk4  will not bootup with current master, all fmu led is off after bootloader.

**To Reproduce**
1. Flash master firmware

**Additional context**
I tried flash Ardupilot for reset parameters, an re-flash, it's not work either.

**Comment by bkueng** [comment]
Same for me. #11769 seems to be responsible, before that it boots.
@davids5 can you have a look?

Console output:
```
up_assert: Assertion failed at file:irq/irq_unexpectedisr.c line: 65 task:
```

**Comment by davids5** [comment]
@bkueng @bys1123 - Thank you for reporting the issues.  I have fixed it here https://github.com/PX4/Firmware/pull/11791
