### ISSUE TITLE
Unable to enable flow control on telem1 port in pixhawk 2

### ISSUE THREAD

**Issue by myeabhishek** [PX4/Firmware#11801]
I am working on swarm of drones. In order for my telemetries to work, I need to enable flow control on telem1 port. 

As per the code in mavlink_main.cpp it should be enabled by default, however, on running "mavlink status" on shell it tells me that flow control is off.

Can anyone please help?

**Comment by julianoes** [comment]
Are you sure that your telemetry radios support flow control? Can you add a picture of your radios and the wiring?

**Comment by julianoes** [comment]
Closing because no response came back.
