### ISSUE TITLE
Mavlink instance does not start on telem2 automatically

### ISSUE THREAD

**Issue by fpvaspassion** [PX4/Firmware#11819]
My copter is equipped with Odroid computer with web camera dedicated to detect Aruco marker, on Odroid side i have Python script establishing connection with Pixhawk , waiting a heratbeat from flight controller and then starting to send vision_position_estimate messages if marker is visible.
 It work fine with stable firmware, but when i tried to do the same  with Master - i discovered than the i need to manually start Mavlink instance for /dev/ttyS2 manually in console of QGC.

**To Reproduce**
Connect any device with Python and Mavlink library to telem2 port of Pixhawk, then execute following code
**...
master = mavutil.mavlink_connection(opts.device, baud=opts.baudrate)
print "Waiting for PX4 heartbeat..."
master.wait_heartbeat()
print "PX4 connected!"
...**
Code will stop on this waiting until you connect via QGC to telem1 port and in console executo following command 
**mavlink start -d /dev/ttyS2**
After that Python script will output message "PX4 connected!"

**Expected behavior**
Mavlink instance on telem2 should start automaticly, like in Stable version of Firmware

**Comment by bkueng** [comment]
All UARTs are now configurable on master: https://dev.px4.io/master/en/companion_computer/pixhawk_companion.html
