### ISSUE TITLE
RTL Cone

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/Firmware#11822]
**Describe problem solved by the proposed feature**
If you fly your vehicle close to the home/rally position but have the RTL altitude set to 60m to be sure to not hit a tree when you fly further away it will go up to 60m and back down.

**Describe your preferred solution**
We should implement an inverted cone below which the vehicle only goes as high as the distance horizontal distance to home or give it a configurable slope.

FYI @bresch

**Comment by bresch** [comment]
fixed by #12382
