### ISSUE TITLE
Vision position estimate message not visible in MAVlink Inspector in QGC

### ISSUE THREAD

**Issue by fpvaspassion** [PX4/Firmware#11820]
**Describe the bug**
Normally (in Stable Firmware) when Pixhawk receive Vision_position_estimate message it is visible in QGC in MAVlink Inspector and you can see the frequency of reception.
   With Master Firmware it is not visible, but copter sucessfully receive and fuse Vision position estimate messages during the flight.

**To Reproduce**
1.Start QGC and open MAVlink Inspector widjet 
2. Upload Stable Firmware into Pixhawk, then power on it and connect to companion computer sending Vision position estimate message.
3. Observe in MAVlink Inspector Vision position estimate and his frequency, if you will hide optical marker - you will see decrease of frequency of receiption of Vision position estimate message.
4. Upload Master Firmware into Pixhawk and repeat all actions from #2.
5. In MAVlink Inspector Vision position estimate message will never appear.

**Expected behavior**
Presence of information about Vision_position_estimate messages in Mavlink inspector.

**Comment by TSC21** [comment]
@fpvaspassion `VISION_POSITION_ESTIMATE` loopback was [removed and replaced some time ago by an optional `ODOMETRY` loopback](https://github.com/PX4/Firmware/commit/cfd1be584eb3240632adbc6ef803c1ef976d621a), which can be set using `MAV_ODOM_LP` parameter.
