### ISSUE TITLE
v1.9 changelog 

### ISSUE THREAD

**Issue by jinger26** [PX4/Firmware#11831]
Need to create changelog for v1.9 release, similar to this: https://github.com/PX4/Firmware/issues/9593

**Comment by mrpollo** [comment]
Changelog is tracked on #11175 I just updated the comment with latest changelog

**Comment by julianoes** [comment]
According to devcall:
@LorenzMeier will pick this up and finalize and publish his notes.

**Comment by LorenzMeier** [comment]
https://docs.google.com/document/d/1DAkW4Wy8q7MhsM6aXkyqa9AKVHXxE8AYLx20rS9pKJ4/edit

**Comment by julianoes** [comment]
@LorenzMeier can be closed, right?
