### ISSUE TITLE
distance_sensor timestamp from MAVLink OPTICAL_FLOW_RAD is wrong

### ISSUE THREAD

**Issue by gamoreno** [PX4/Firmware#11840]
When PX4FLOW is connected to PX4 through MAVLink (e.g., through a USB port), the timestamp assigned to the distance_sensor is wrong. Instead of using the time at which the MAVLink OPTICAL_FLOW_RAD message was received or the timestamp generated by PX4FLOW, it uses the integration_time_us of the OPTICAL_FLOW_RAD message, which is not a timestamp but the duration of a time interval over which sensor readings were integrated. Furthermore, the unit conversion is wrong. The source of this problem is [in this line](https://github.com/PX4/Firmware/blob/95a0803b149770b8d1a5817611cd55e43a4ad296/src/modules/mavlink/mavlink_receiver.cpp#L628)

`d.timestamp = _mavlink_timesync.sync_stamp(flow.integration_time_us * 1000); /* ms to us */`

One consequence of this bug is that when the drone is on the ground, that integration_time_us, and consequently the timestamp assigned to distance_sensor, is 0 because the image is out of focus. Regardless of that, the sonar reading is valid, but because it has a timestamp of 0, then ekf2 doesn't use it.

I think it should be possible to switch to altitude mode using the sonar before taking off, but due to this issue, it is not possible and one can only switch to altitude mode after taking off, when the position with the flow tracking is available. This is with EKF2_HGT_MODE set to rangefinder. Regardless of this, this wrong timestamp could cause other problems.

**Comment by mhkabir** [comment]
Can you send a PR? Thanks!
