### ISSUE TITLE
vl53lxx is not work with other board except Crazyflie

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#11842]
**Describe the bug**
The driver only detect PX4_I2C_BUS_EXPANSION without other I2C buses.

https://github.com/px4/firmware/blob/0b4751d03167c4ee147f2e91a94f9919baea70e1/src/drivers/distance_sensor/vl53lxx/vl53lxx.cpp#L72

**Comment by bys1123** [comment]
Try to fix:
I modified rc.board_sensors, add new line `vl53lxx start`.
Also `#define VL53LXX_BUS_DEFAULT PX4_I2C_BUS_EXPANSION2` in vl53lxx's drive.

Plug my module to I2C A, Pixhawk4 will not boot up successfully.
Buzzer music is normal, FMU ACT will not blink, I/O B/E light up.

**Comment by bys1123** [comment]
I deleted `vl53lxx start`
Boot success, I tried start this driver in Console, still not work.
The bus setting looks right, I got i2c read like this:
![image](https://user-images.githubusercontent.com/4748411/56116376-39bf0b00-5f98-11e9-8721-88300c9d7952.png)

**Comment by bys1123** [comment]
Tested on 1.8.2:
```
nsh> vl53lxx start
VL53LXX i2c::transfer returened -125
ERROR [vl53lxx] driver start failed
```

**Comment by bys1123** [comment]
Tried `vl53lxx start -a` on master branch firmware. Still not work.
I2C A port has no response.
This also break my console connection.

**Comment by mcsauder** [comment]
@bys1123 , could you post the console output when you manually start the driver with `vl53lxx start -a` ?

**Comment by bys1123** [comment]
continue in #11932
