### ISSUE TITLE
BMI055 IMU driver reports incorrect temperature

### ISSUE THREAD

**Issue by dmillard-TD** [PX4/Firmware#11854]
The BMI055 IMU driver is reporting incorrect temperature results.
I've been discussing it on the forum here:
http://discuss.px4.io/t/pixhawk-4-temperature-compensation-failure/10226/10

All testing was performed on a Pixhawk 4 in an industrial environment chamber.

I've inspected the driver source and found that there is indeed a problem with the code that fills the report buffer with the temperature value.  The gyro driver always reports 0, and the accel driver is reporting some value between 23.0 and 23.9 no matter what the actual temperature is.

I've modified the driver code to read the temperature correctly using the slope and offset specified in the BMI055 datasheet.  I'll submit a PR after I've finished testing it.

**Comment by dagar** [comment]
Thanks for reporting @dmillard-TD. I can quickly review and test once the PR is available.

**Comment by dagar** [comment]
If possible I'd like to get this into v1.9.0.

**Comment by dmillard-TD** [comment]
PR #11867 submitted.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/11867
