### ISSUE TITLE
SD Card does not mount on v1.8.2 (pixhawk 4)

### ISSUE THREAD

**Issue by echoGee** [PX4/Firmware#11860]
**Describe the bug**
The SD card does not mount on a Pixhawk 4. Unable to determine if this is a software issue or hardware. 

**To Reproduce**
1. Upload v1.8.2 stock firmware on pixhawk 4
2. power cycle autopilot with the stock 4GB SD card
3. Connect Qground control 
4. See if SD card is mounted using the _mount_ command on nsh. Only _/etc_ and _/proc_ is mounted. _/fs/microsd_ is not mounted
5. Trying to mount the SD card using _mount -t vfat /dev/mmcsd0 /mnt/fs_ crashes pixhawk 

**Expected behavior**
The SD card should be mounted. _mount_ command on NSH should return the _/fs/microsd_ as a mounted directory.
Alternatively, if this is a hardware problem with the pixhawk 4, there needs to be a way to identify and isolate this. Verified that the SD card works with a different pixhawk 4. 

**Log Files and Screenshots**
No log files are available since SD card can

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
Not mounted on a drone yet

**Alternative approaches tried to debug the issue:**

1. Uploaded master and beta branches to pixhawk 4. This however prevented the pixhawk from booting up.

**Comment by mhkabir** [comment]
Can you try with a different SD card?

That said, attempting to mount should never crash the flight controller.

**Comment by echoGee** [comment]
I did try with a different card. Same effect.

**Comment by julianoes** [comment]
> Uploaded master and beta branches to pixhawk 4. This however prevented the pixhawk from booting up.

Which version of master was this. Can you try again and paste the git hash here?

**Comment by echoGee** [comment]
> > Uploaded master and beta branches to pixhawk 4. This however prevented the pixhawk from booting up.
> 
> Which version of master was this. Can you try again and paste the git hash here?

This one . 
commit c0a1f5b72f99ae0170f3cfde03ddbdb25a8c1c68
Author: baumanta <tanja@auterion.com>
Date:   Wed Apr 17 19:20:29 2019 +0200

    Collision prevention improvements (#11866)
    
    * match max vel in col-prev to regular pos ctrl
    * change warning criterium to avoid float error
    * disable push back from obstacles
    * use floats consistently

**Comment by echoGee** [comment]
Hi, anyone able to take a look at this ?

**Comment by julianoes** [comment]
How is the SD card formatted that you are trying to use?

**Comment by echoGee** [comment]
It is fat32 formatted. I've tried other sd cards with fat32 formatting

**Comment by julianoes** [comment]
Sounds like faulty hardware, not sure what to do about it. If you have a Dronecode debug probe (or something similar) you could get the startup output.
https://dev.px4.io/en/debug/system_console.html

**Comment by echoGee** [comment]
@julianoes : We found a way to get the debug probe and attaching the files here. 

A snapshot of the comparison of the debug probe:
Left: Debug probe without SD card. Right: Debug probe with SD card
![image](https://user-images.githubusercontent.com/518314/57813180-3bb5ee80-773d-11e9-9feb-4df4c0947108.png)

[DebugProbeWithSDCard.txt](https://github.com/PX4/Firmware/files/3184631/DebugProbeWithSDCard.txt)
[DebugProbeWithoutSDCard.txt](https://github.com/PX4/Firmware/files/3184632/DebugProbeWithoutSDCard.txt)

**Comment by davids5** [comment]
@echoGee - I would try curren master. If it does not run, and does not boot the px4io, nor mounts the SD card, I would say it is a HW problem and you should contact Holybro.

**Comment by echoGee** [comment]
@davids5 I tried with master. Same problem. I've tried contacting Holybro. Yet to hear from them.

**Comment by davids5** [comment]
I have asked them to give you a hand on Slack. You should get a response from them here

**Comment by davids5** [comment]
@echoGee 

please send email to productservice@holybro.com with invoice

**Comment by arthurfromholybro** [comment]
> @julianoes : We found a way to get the debug probe and attaching the files here.
> 
> A snapshot of the comparison of the debug probe:
> Left: Debug probe without SD card. Right: Debug probe with SD card
> ![image](https://user-images.githubusercontent.com/518314/57813180-3bb5ee80-773d-11e9-9feb-4df4c0947108.png)
> 
> [DebugProbeWithSDCard.txt](https://github.com/PX4/Firmware/files/3184631/DebugProbeWithSDCard.txt)
> [DebugProbeWithoutSDCard.txt](https://github.com/PX4/Firmware/files/3184632/DebugProbeWithoutSDCard.txt)

Please write to productservice@holybro.com, our tech team will help you. Thanks!
