### ISSUE TITLE
Critical service bulletin for Cubes Purchased between January 2019 to present

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#11868]
As describe in this [link ](https://discuss.cubepilot.org/t/sb-0000002-critical-service-bulletin-for-cubes-purchased-between-january-2019-to-present/406)there is a critical issue with some cubes

I think its importent to follow the discution there, if it relevant, to identify such cubes and alert the user if he uses them.

I don't know more than what this link say....

> 
> It has come to our attention, that there is an anomaly with sensor readings on some recent cubes.
> 
> This is an unfolding investigation, more details will be added as they come to light.
> 
> If your vehicle is fitted with a CUBE BLACK with the the following symptoms, DO NOT FLY. Wait for further instructions.
> 
> Your Cube is fitted with Three Gyros, Three Accelerometers, two Barometers, two internal Compasses.
> If any of these sensors are missing at startup, you must not fly the vehicle.
> 
> to tell what is fitted…
> 
> Open mission planner and connect to your cube.
> go to the full parameter list
> 
> Look for the following parameters and check that they match the examples
> INS_ACC_ID = 1442082
> INS_ACC2_ID = 1114914
> INS_ACC3_ID = 1442826
> 
> INS_GYR_ID = 2359586
> INS_GYR2_ID = 2229282
> INS_GYR3_ID = 2360330
> 
> If these do not match, ground your vehicle immediately.
> 
> Please keep an eye on this notice for further instructions. There will be an update to mission planner, and to Ardupilot coming to assist in determining if your Cube is affected by this fault.
> 
> We are sorry about this situation, and will endeavour to follow up with solutions as soon as possible
> Thank you
> 
> Philip Rowse

**Comment by rickyh777** [comment]
Does/can PX4 report a notice similar to the new functionality added to arducopter?

**Comment by BazookaJoe1900** [comment]
No comments?
This seems like serious issue. I haven't hear about someone in PX4 that encounter crash because of that issue. but its seems like just matter of time.

**Comment by mhkabir** [comment]
PX4 handles this safely if it occurs in-flight. It will also prevent arming and ground the vehicle (require recalibration) if a sensor is missing at bootup. See https://px4.slack.com/archives/C3GFT2QS3/p1555699096001500 and following messages.

**Comment by BazookaJoe1900** [comment]
@mhkabir, so in that case, and if someone else can approve you can close the issue

**Comment by julianoes** [comment]
I think @bkueng looked into this and can comment.

**Comment by bkueng** [comment]
This is serious and I have looked into it, see https://github.com/PX4/Firmware/pull/11922 for reference.
Closing this, but feel free to reopen if you experience problems.
