### ISSUE TITLE
Airspeed sensor not work on Pixhawk4 I2C A

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#11884]
**Describe the bug**
Current Airspeed sensor only opened on PX4_I2C_BUS_EXPANSION, but most of users will connect their airspeed sensor on I2C A (PX4_I2C_BUS_EXPANSION2) first. It will not works. Makes users very confused.

Code is here, but I didn't get how to change this driver, not similar with other I2C device.
https://github.com/PX4/Firmware/blob/master/src/lib/drivers/airspeed/airspeed.h#L48

**Comment by LorenzMeier** [comment]
@bkueng Could you please look into this?

**Comment by bkueng** [comment]
That should already be working, @DanielePettenuzzo fixed that, and I quickly tested it.
The airspeed sensor is only started for fixed-wing or vtols.
Are you testing master, and which airspeed sensor do you use?

**Comment by bys1123** [comment]
@bkueng It's 4525DO on master branch for VTOL.
