### ISSUE TITLE
A question of yaw setpoint

### ISSUE THREAD

**Issue by JoeyLeeNPU** [PX4/Firmware#11882]
I have a position mode flight in the GPS outdoor environment, I control the yaw angle, but in the flight log, the yaw set-point is different from the signal sent by the remote control. The drone's yaw is set to zero autonomously.
The data is in my log attached.
How should I do for this, is it a bug?
[log_11_2019-4-21-10-31-04.zip](https://github.com/PX4/Firmware/files/3101116/log_11_2019-4-21-10-31-04.zip)

**Comment by julianoes** [comment]
@JoeyLeeNPU sorry for the late response.

Can you please upload the log to https://logs.px4.io and then link it here. And can you describe what sort of params you used to make this work.
