### ISSUE TITLE
Pyserial versioning check fails in px_uploader.py

### ISSUE THREAD

**Issue by Jwitty07** [PX4/Firmware#11885]
When trying to upload the latest firmware, the upload fails with error 
`Error: pyserial not installed!
    (Install using: sudo pip install pyserial)
`
However, I already have this installed, both with python 2.7 and python 3.6.

I found that the version of pyserial that I have does not use the  `serial.__version__` syntax for checking the version, but rather uses `serial.VERSION`. Pyserial cannot be upgraded because part of my Linux system relies on this.

**Comment by julianoes** [comment]
@Jwitty07 thanks for reporting and the information.

Could you please test if it works with the change here: #11887

**Comment by Jwitty07** [comment]
The fix works. Thanks!

**Comment by julianoes** [comment]
Cool, thanks for testing @Jwitty07.
