### ISSUE TITLE
ERROR: Board can accept larger flash images

### ISSUE THREAD

**Issue by gogogoKKK** [PX4/Firmware#11900]
I tried to flash the program to my pix falcon on ubuntu 16.04 using 
`make  px4_fmu-v2_default upload`.
However, I get the error and failed

_ERROR: Board can accept larger flash images (2080768 bytes) than board config (1032192 bytes). Please use the correct board configuration to avoid lacking critical functionality._

When I used 
`make  px4_fmu-v3_default upload`, 
it works. Is there something wrong with the version of FMU?

Thanks for your hint.

**Comment by LorenzMeier** [comment]
No, you did what you were supposed to do.
