### ISSUE TITLE
Unstable fly in position mode

### ISSUE THREAD

**Issue by GigaFlopsis** [PX4/Firmware#11902]
Hello.  I'm trying to launch a group of drones but I have a lift.  For reasons unknown to me, the drone twitches in height.
Link to the problem: https://youtu.be/zt_FhqYDk1I

I use last beta px4 fmu.
This problem occurs on several drones in a pose and hold mode.
I spent changing the source height measurement, but it did not help.

Frame: f450
Autopilot: Pixhawk 2.4.6  (fmu-v2-beta)

**Comment by julianoes** [comment]
Please share the version of the firmware you are using and upload a log where the problem occurs to logs.px4.io and share the link, thanks.

**Comment by GigaFlopsis** [comment]
Hello. I helped increase the parameter MPC_Z_VEL_P to 0.4

**Comment by julianoes** [comment]
Ok, thanks for sharing. So the issue is resolved?

**Comment by GigaFlopsis** [comment]
Yeas. Thanks!
