### ISSUE TITLE
micro_rtps bridge fails to build

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Firmware#11901]
**Describe the bug**

If `fastrtpsgen` is in the PATH (and `FASTRTPSGEN_DIR` is not set), then the build fails with:

> generate_microRTPS_bridge.py: error: argument -f/--fastrtpsgen-dir: expected one argument

while the `generate_microRTPS_bridge.py` autodetects properly the presence of `fastrtpsgen`.

**To Reproduce**
1. Have `fastrtpsgen` in the PATH and `FASTRTPSGEN_DIR` not set.
2. Run `make px4_fmu-v3_rtps`

**Expected behavior**

The Firmware builds.

**Additional context**

This is due to the option `--fastrtpsgen-dir` to be set to `FASTRTPSGEN_DIR` in the CMakeLists.txt. Therefore if `FASTRTPSGEN_DIR` is not set, argparse fails. 

https://github.com/PX4/Firmware/blob/a9c3bce20da57e2fdd9c3ad630892506677ca377/src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt#L76

If the line is commented `generate_microRTPS_bridge.py` succeeds.

**Comment by TSC21** [comment]
This needs a condition here where it checks if `FASTRTPSGEN_DIR` is set and if not, looks on the default path. Will add that asap.

**Comment by AlexisTM** [comment]
I have another solution, allowing no data for argparse, using `nargs='?'`
