### ISSUE TITLE
PX4 CMD: Unexpected command 22, result 0 

### ISSUE THREAD

**Issue by mahdinobar** [PX4/Firmware#11919]
### Issue details

I use MAVROS node to translate MAVLink messages into ROS messages so I  can communicate between ROS and Gazebo through PX4. The problem is when the commander offboard control phase finishes, I receive the warning **CMD: Unexpected command 22, result 0** then the drone lands, whereas I should continue the flight based on the velocity command from my ROS node. So my question is what does this warning message mean and how it can be corrected?

### MAVROS version and platform

Mavros: 0.18.4
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

PX4
Version: v1.8.2

**Comment by julianoes** [comment]
Are you continuously sending the offboard commands or do you stop sending them?
The unexpected command 22 is: https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_TAKEOFF

**Comment by julianoes** [comment]
@mahdinobar could you follow up here please?

**Comment by julianoes** [comment]
I'm going to close this because there was no follow up.
