### ISSUE TITLE
Add CI tests for rover

### ISSUE THREAD

**Issue by ItsTimmy** [PX4/Firmware#11954]
**Describe problem solved by the proposed feature**
With ongoing work on PX4 support for rovers (#9533), we need CI tests to make sure rover functionality is stable

**Describe your preferred solution**
Add mission tests in CI

**Comment by lamping7** [comment]
Once the model you want gets in and you have a good .plan to use, feel free to ping me to assist on getting it Jenkins.

**Comment by julianoes** [comment]
This has been done!
