### ISSUE TITLE
Datalink lost with termination enabled leads to termination

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#11971]
According to https://discuss.px4.io/t/px4-mission-mode-crash/10847/2 it looks like flight termination is triggered if datalink is lost and we're in mission mode even if GPS and RC are ok.

The message in this case says: "DL and GPS lost: flight termination".

https://github.com/PX4/Firmware/blob/7ec6f0dca6ec604e5a62707e487ad754a23ded7a/src/modules/commander/Commander.cpp#L2231-L2242

FYI: @LorenzMeier @dagar

**Comment by bresch** [comment]
This will be fixed in PR #10179  here: https://github.com/PX4/Firmware/pull/10179/commits/57b527778f9bf3c3ba6bd9df81f9eb6ee6ea65c7

**Comment by dagar** [comment]
We need a minimal fix for v1.9.0.

**Comment by julianoes** [comment]
@bresch can you make a PR with just 57b5277, I think that's covering it for 1.9.0.
