### ISSUE TITLE
unable to start  mission : vehicle not  ready

### ISSUE THREAD

**Issue by sampathkumarch** [PX4/Firmware#11986]
https://discuss.px4.io/t/unable-to-start-mission-vehicle-not-ready/10896

**Comment by sampathkumarch** [comment]
sir please help me . why not given to me reply tell me sir

**Comment by hamishwillee** [comment]
@sampathkumarch 

> why not given to me reply tell me sir

The issue was closed because this is a place for bug reports and feature requests - is not a place for you to post support requests. You have correctly created a discussion board issue. Additional information and questions should go in that issue.

**Comment by sampathkumarch** [comment]
Thank you for your response, but where is the discussion this issue iam
post for it

**Comment by hamishwillee** [comment]
Pardon? In _your_ top post https://github.com/PX4/Firmware/issues/11986#issue-441587312 -  see https://discuss.px4.io/t/unable-to-start-mission-vehicle-not-ready/10896

**Comment by hamishwillee** [comment]
If that isn't your post, then please create a new one. We can't help you in the defect tracker.

**Comment by sampathkumarch** [comment]
Ok sir  .what do I do now?

**Comment by sampathkumarch** [comment]
Ok sir, what I do now

**Comment by hamishwillee** [comment]
Create a post in https://discuss.px4.io with all the details of your setup - vehicle, flight controller, autopilot, autopilot version, ground station, what you have tried. Everything you can think of that might be relevant to the problem.

**Comment by hamishwillee** [comment]
The information you have put in this issue looks good, but it can't be posted here, because this is for bugs, and at the moment all we know is that you have a problem. That might be due to your setup or something else.
