### ISSUE TITLE
Add PixyCam2 driver for Rover

### ISSUE THREAD

**Issue by igalloway** [PX4/Firmware#11993]
For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/).

**Describe problem solved by the proposed feature**
NXP will use the PixyCam as for a simple car configuration which is able to stay inside the lines on either side of a race track. This is development that will be used for student competitions. 

**Describe your preferred solution**
Driver in PX4 that provides access to PixyCam pre-programmed functions

**Describe possible alternatives**
Alternative would be for PixyCam to use the SDK to command the FMU. But this is not preferred.

**Additional context**
Leo Mustafa (NXP) has started a driver and communications between the Pixy and PX4, so there is a solid starting point

**Comment by jarivanewijk** [comment]
As mentioned, some basic code already exists (not publicly available). We need to figure out if can release it and if it is worth it to bring it upstream.

**Comment by jpt48** [comment]
Good morning,
We are currently having a file error issue when we try to compile the code. it may be worth saying that the px4_config.h file it is in the correct directory, any suggestions ?? Thank you
![error](https://user-images.githubusercontent.com/44036409/67881024-bddc7880-fb0d-11e9-929e-b08a438432e4.PNG)

**Comment by bkueng** [comment]
@jpt48 the include paths changed on master: `<px4_config.h>` --> `<px4_platform_common/px4_config.h>`

**Comment by jpt48** [comment]
@bkueng Thank you, the errors were cleared. 
We have come across another issues if anyone may have input. The FMU took the updated firmware with Pixy cam code. To test it we are trying to get feedback through QGC mavlink and this its all we get back. Thank you.
![Image 11-18-19 at 11 48 AM](https://user-images.githubusercontent.com/44036409/69076582-6b4df800-09f9-11ea-9c4e-eba17b91d210.jpg)

**Comment by bkueng** [comment]
What output do you expect? Might be best to open a pull request (even if not finished yet), so we can look at the code.

**Comment by jarivanewijk** [comment]
(Note that the PixyCam driver has been available at https://github.com/NXPHoverGames/PixyCam for a while now. Should we again bring up the discussion whether to bring this into PX4?)

**Comment by julianoes** [comment]
@jarivanewijk we're always open for pull requests but I'm not sure if you can convince someone to work on this for you.

**Comment by jarivanewijk** [comment]
@igalloway @KatrinMoritz - Is this still something we want to merge into PX4 eventually? Otherwise this issue can be closed.

**Comment by KatrinMoritz** [comment]
Yes, we want this. And I will do this PR soon.

**Comment by KatrinMoritz** [comment]
@jarivanewijk @igalloway @julianoes the issue can be closed. There will be no PR for the Pixycam driver.
