### ISSUE TITLE
unable to start a mission : vehicle is not ready

### ISSUE THREAD

**Issue by sampathkumarch** [PX4/Firmware#11997]
i am using pixhawk 4 
 i want to fly a my fixed wing plane in autopilot mode that why am not using RC control so i do COM_RC_IN_MODE  is set no rc(SET 2) and NAV_RCL_ACT is disabled .
 system also that's way am using CBRK disable the usb cable . now am given a way points and upload it then get a message is start the mission . i get a another error message unable to start a mission : vehicle is not ready how can resolve this

**Comment by hamishwillee** [comment]
@sampathkumarch This is still not the right place to post your support queries. Please post them in https://discuss.px4.io/

When someone has evaluated the query and worked out whether it is really a bug in our our code THEN you will be asked to create a bug.
