### ISSUE TITLE
px4_fmu-v2_multicopter has no tones

### ISSUE THREAD

**Issue by MotoLab** [PX4/Firmware#12012]
**Describe the bug**
The v1.9.0-rc1 build of px4_fmu-v2_multicopter does not generate any speaker tones.

**To Reproduce**
Install v1.9.0-rc1 and power it up. No tones are generated.

**Expected behavior**
Normal behavior is startup tone, initialization complete tone, and safety switch tones.

**Additional context**
Adding tone_alarm to the multicopter.cmake file corrects the problem. This problem probably exists int the fixedwing and rover targets as well, as they are lacking the tone_alarm in their .cmake files.

**Comment by dagar** [comment]
Thanks, for reporting. Fixed in https://github.com/PX4/Firmware/pull/12013
