### ISSUE TITLE
Serial naming: Give UART 6 a name (maybe TELEM 6 or something can describe its function)

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#12020]
**Describe the bug**
PX4 usually call the UART port TELEMx or GPSx on Flight controllers. But here is UART 6 show up.

**Expected behavior**
It should have name describe it's purpose.

**Log Files and Screenshots**
![image](https://user-images.githubusercontent.com/4748411/57721074-db2f9e80-76b5-11e9-8187-d6ad90432e75.png)

**Comment by bkueng** [comment]
This is for boards that don't have a label, like Omnibus. It's a generic UART, you can attach anything.
