### ISSUE TITLE
Log download speed too low via telem2 port.

### ISSUE THREAD

**Issue by myeabhishek** [PX4/Firmware#12039]
I am trying to download logs via telem2 port. Log download speed is too low(3 kBps). By increasing baud rate to 921600 I am able to reach 50KBps which is still too low. How can I download logs faster say 200KBps or more?

**Comment by julianoes** [comment]
I think you can answer best here @bkueng.

**Comment by bkueng** [comment]
50KB/s sounds about right and you won't get much more than that with 921600 baud.
