### ISSUE TITLE
Wrong roll and pitch setpoint in LAND

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#12048]
Hi ,
There is a wrong roll and pitch setpoint during land . what is reason ? how we can solve this problem ?
https://review.px4.io/plot_app?log=39cd6fbc-f0d8-4532-8703-dee80d50c8ab

![](https://discuss.px4.io/uploads/default/original/2X/b/b2b944899f00b685fd60e015f47e618f89f89d65.png)

**Comment by hamishwillee** [comment]
I am closing because this area is for defects, not technical support (at this point all you have is potentially a tuning issue). Suggest you repost on the forums.
