### ISSUE TITLE
PID in attitude - multicopter

### ISSUE THREAD

**Issue by alexcherpi** [PX4/Firmware#12051]
For multicopter there is now a P gain for the attitude controller (and PID for Rate controller). Would it be possible to have PID as well for the attitude controller?

**Comment by bresch** [comment]
It is possible but normally not required: when the rate controller is well tuned, you can achieve really good attitude tracking with tat simple P controller. Especially for the integral that is already implicitly there, I don't see why you would need a second one.

What problem are you facing that you want to solve with a PID attitude controller? Please provide a log.

**Comment by alexcherpi** [comment]
Hi bresch, 
Indeed you're right the integral is there through the rate control Integral term.
Our drone is now flying, our bug was hardware (very vicious).
Many thanks!
