### ISSUE TITLE
'tune_control play -m "XXX"' is not working

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#12059]
**Describe the bug**
tune_control play -m can't play customize tune on mater, tested 1.8.2 works fine

**To Reproduce**
1. Use MAVLink console 
2. Enter " tune_control play -m "MFT200CDEFGAB" "

**Expected behavior**
Play custom tune

**Log Files and Screenshots**
![image](https://user-images.githubusercontent.com/4748411/58294890-04aba100-7dff-11e9-907e-78ca7ebbf87d.png)

**Comment by bkueng** [comment]
I have fixed this in https://github.com/PX4/Firmware/pull/12063, can you test it?

**Comment by bys1123** [comment]
@bkueng So fast, thanks, I'll test it later.
