### ISSUE TITLE
Bash Windows upload the build firmware broken

### ISSUE THREAD

**Issue by huangwen0907** [PX4/Firmware#12055]
I follow the [matlab/psp Setup and Configuration](https://ww2.mathworks.cn/help/supportpkg/px4/setup-and-configuration.html?s_tid=CRUX_lftnav
)and install the build environment. Now it can build sucessfully but can not upload the build .px4 into my hardware pixhawk-v2 (I can upload it through my 16.04 ubuntu system, so the hardware is ok ).
![pic](https://user-images.githubusercontent.com/22727672/58158357-dd44bf00-7cac-11e9-8d68-eb963c59179c.png)

**FYI:** 
> I download the Firmware [mathworks/PX4-Firmware](https://github.com/mathworks/PX4-Firmware)  and use the `arm-none-eabi-gcc 5.4.1 201609019` version. 
In the windows system, qgroundcontrol  can connect my pixhawk, so the serial com is ok.

**Comment by huangwen0907** [comment]
@MaEtUgR  Hi, Matthias, I am appreciate that you can give  me some suggestions here as I know you are working in the windows system. 

Now I want to upload the build firmware through the windows's bash.

**Comment by hamishwillee** [comment]
@huangwen0907 

Bash is not "officially" supported, but what we know about using it is here: https://dev.px4.io/en/setup/dev_env_windows_bash_on_win.html#build-firmware

As stated:

> You can flash the custom firmware on Windows using QGroundControl or Mission Planner (it is not possible to directly flash the firmware from within the bash shell using the upload command).

In this case "not possible" means that I couldn't get it to work. As this is not "supported" probably no one else will have the time to work out whether it can be done, and if so how.

**Comment by hamishwillee** [comment]
I am therefore closing this as a "known issue".
