### ISSUE TITLE
since some days ago,jmavsim need to calibration sensor.

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#12060]
Since some days ago,jmavsim need to calibration sensor.Two PC is both to need to calibration sensor.How do I solve that ? Oris a bug?

**Comment by julianoes** [comment]
Please describe the steps to reproduce this problem. And what is the error message, and which error needs calibration?

**Comment by roseyangyu** [comment]
![图片](https://user-images.githubusercontent.com/40378941/58558586-cde8e700-8253-11e9-9468-b25ff9736664.png)
as this and can't arm
![图片](https://user-images.githubusercontent.com/40378941/58558689-11435580-8254-11e9-9caa-72a55d3dbec0.png)

**Comment by roseyangyu** [comment]
> ![图片](https://user-images.githubusercontent.com/40378941/58558586-cde8e700-8253-11e9-9468-b25ff9736664.png)
> as this and can't arm
> ![图片](https://user-images.githubusercontent.com/40378941/58558689-11435580-8254-11e9-9caa-72a55d3dbec0.png)

FW is 1.9.0 and 1.7

**Comment by julianoes** [comment]
@roseyangyu is this still an issue?

**Comment by roseyangyu** [comment]
yes,I don't solve that in old code.I can run jmavsim normal just by re-download source code.
