### ISSUE TITLE
FW_LND_THRTC_SC description messed up

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#12124]
Not sure if this is the correct place to report this.  The Param description for FW_LND_THRTC_SC seems messed up on dev/px4.io   lots of ="" stuck in the text

see screenshot:
![image](https://user-images.githubusercontent.com/12117027/58661864-86636900-82ee-11e9-8427-19469e5f7ba4.png)

**Comment by dagar** [comment]
I bet it's the less than here. https://github.com/PX4/Firmware/blob/e4926373e6febe9d6c133975f40bee8c605db5e2/src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c#L399
