### ISSUE TITLE
Infinitely flying up during RTL

### ISSUE THREAD

**Issue by anandbaskaran** [PX4/Firmware#12138]
We have been flying mission mode with the stable release 1.8.2 of PX4 (with Pixhawk 4: fmu-v4) between two points that are 700m away. We used RTK GPS, and a barometer for position and altitude estimation. The drone took off (to the altitude of 25m) and started towards the next waypoint. 

A few seconds later, the manual pilot engaged `RTL Home` and the drone started to climb up with full throttle. Due to fast climb and far distance the communication with RC pilot was lost. Fast discharge of battery with full throttle engaged safe land mode. However, the drone did not land in the home position. Unfortunately, we were not able to retrieve logs from the drone’s autopilot. 

[Just the drone status logs were recovered](https://github.com/PX4/Firmware/files/3240429/dronelogs.recovered.txt)
`NOTE:` RTL_RETURN_ALT param was set to 15.0m. 

-------------------------------------------

To understand what happened similar tests have been conducted in a simulation. And at times we have observed comparable behavior as described in the following screenshots:
![Settings in QGC](https://user-images.githubusercontent.com/6847984/58691917-a72ecb80-838d-11e9-9c54-dd353790cba9.jpeg)

When the RTL Home is engaged the drone goes up to the altitude of 30m (instead of 15m). After drone reaches the home waypoint, the drone loses its GPS and lands randomly. 
![QGC RTL](https://user-images.githubusercontent.com/6847984/58692169-51a6ee80-838e-11e9-86db-d3fa3f6aaed8.jpeg)

Please find the corresponding status logs below: 
![Status Logs](https://user-images.githubusercontent.com/6847984/58692216-71d6ad80-838e-11e9-88c7-91030d4f9935.jpeg)

This issue of GPS loss is obtained once in a while during the simulation and we could not identify the way of repeatability. However, flying back at 30m (instead of 15m happens almost always). In reality, the drone flew at least above 100m.

**Comment by jkflying** [comment]
The landing position issue is fixed here, I believe: https://github.com/PX4/Firmware/pull/12032

However I'm not sure about the altitude of RTL issue.

**Comment by julianoes** [comment]
Can you check these params?
https://dev.px4.io/en/advanced/parameter_reference.html#RTL_RETURN_ALT
https://dev.px4.io/en/advanced/parameter_reference.html#RTL_DESCEND_ALT

**Comment by julianoes** [comment]
@anandbaskaran has this ever happened again? And if yes, could you upload a log?
I don't know how to reproduce this.

**Comment by anandbaskaran** [comment]
@julianoes It did not happen again. However, we also started using v1.9.0, which had a new issue that it automatically engages kill switch. I will post it along with the logs.

**Comment by julianoes** [comment]
> new issue that it automatically engages kill switch

Ok please create a new issue for this. I'll close this issue, you can re-open it if it happens again.
