### ISSUE TITLE
Telemetry Uplink not working if sd card disconnected accidentally

### ISSUE THREAD

**Issue by caomuqing** [PX4/Firmware#12130]
**Describe the bug**
A clear and concise description of the bug.
A flight plan is pre-planned and uploaded to the vehicle. Before flight, sd card reads ok. During auto mission, the SD card accidentally lost connection(not sure why), then the telemetry uplink also does not function anymore, meaning whatever command sent from QGC will not be executed by the UAV at all(an error will be prompted). However, the downlink is still ok, meaning the uav data is still available in real time in QGC.

**To Reproduce**
1. simply turn on the drone on ground
2. disconnect the sd card while autopilot is on
3. try to send command from QGC
4. the error appears

**Comment by bkueng** [comment]
Thanks for the report. Can you be more specific on the commands you send and errors that you see? Which PX4 version is that?

A quick test in HIL confirms there are issues when ejecting the SD card during a mission: the `read` syscall [here](https://github.com/PX4/Firmware/blob/master/src/modules/dataman/dataman.cpp#L629) did not return anymore (I tested on a Pixracer and Pixhawk 4). Consequently RTL does not work anymore, but I can still switch modes via QGC and take control via RC.
@davids5 can you have a look?

**Comment by caomuqing** [comment]
I have tried changing mode command, mission upload command, both does not work. the PX4 version is 1.8.2.
![5E7CC404CAE98E5B8C5668EA1EEA9671](https://user-images.githubusercontent.com/8552623/58947012-a517a300-87b9-11e9-815f-e382cac53101.jpg)
![A2CF3936815EB3CBCF133F494B9C3709](https://user-images.githubusercontent.com/8552623/58947022-ac3eb100-87b9-11e9-8c94-5838408c2e22.jpg)

**Comment by bkueng** [comment]
Can you try with v1.9.0? Which hardware do you use?
In which order did you send the commands? Can you try only a mode switch after disconnecting the SD card?
