### ISSUE TITLE
VTOL airframes don't start up

### ISSUE THREAD

**Issue by sfuhrer** [PX4/Firmware#12158]
After flashing master on a pixhawk4 and selecting a VTOL frame (eg standard vtol, autostart 13000) it doesn't start up cleanly (eg it is no able to connect to QGC). Other airframes work (eg 2100 or 4001).

It seems to be something mixer related, as the start up works (get connection to QGC) if I skip the mixer loading via "set MIXER skip" and "set MIXER_AUX skip" in the config file.

@dagar @RomanBapst @MaEtUgR

**Comment by dagar** [comment]
Do you recall the last time this specific configuration (airframe + board) worked?

Shot in the dark, could you try https://github.com/PX4/Firmware/issues/12158 quickly?

**Comment by sfuhrer** [comment]
Well with 1.9 it for example works, didn't check anything more recent.

And yes, with #12158 it works also fine.

**Comment by Tony3dr** [comment]
@dagar we are having similar issues with the Convergence, Pixhawk 4 mini. The telemetry on the vehicle is not sending the data, no connection on the Master branch. The last time we flew the unit was on PR [12096](https://github.com/PX4/Firmware/pull/12096). We just recently got the unit up and running.

**Comment by MaEtUgR** [comment]
I'm currently this happens because NuttX hits the maximum number of 32 tasks and everything after that is not started anymore. We had the problem today on a multicopter with multiple MAVLink instances as well. If you look at the startup in the console you see all commands failing after a certain point.

@dagar I think you already know this problem exists.

**Comment by dagar** [comment]
Can you try https://github.com/PX4/Firmware/pull/12230?

**Comment by sfuhrer** [comment]
I've directly tried current master, as I've seen that #12230 is already merged. And yes, VTOL now works again.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/12230.

**Comment by dannyfpv** [comment]
I Tested master  on Pixhawk4 mini V5 vtol 
Modes Tested 

Position Mode: no issue 
Altitude Mode: no issue 
Stabilized Mode: no issue 
Mission Plan Mode: no issue 
-RTL: no issue 
transsition mode: no issue

log:
https://review.px4.io/plot_app?log=16fc215a-ab05-4e05-9313-fbf05f54e633
