### ISSUE TITLE
Compass calibration fail PixRacer V4 on Master 

### ISSUE THREAD

**Issue by Tony3dr** [PX4/Firmware#12193]
**Describe the bug**
Uploaded PR [#12120](https://github.com/PX4/Firmware/pull/12120) tried to arm and had an error "compass Inconsistent". Performed the compass calibrations and got error message "Error: failed to get current calibration 2". Uploaded  Master branch ac44584. To replicate the issue performed calibrations and got the same message, "Error: failed to get current calibration 2". Tried on Stable ea48cd4, performed the calibrations and went through successfully. Vehicle armed and had no issues.  
**To Reproduce**
1. Upload Master branch or PR
2. Perform compass calibration
3. Failed calibrations 

**Expected behavior**
The expected behavior is for the vehicle to pass the calibrations and able to arm the vehicle.
**Log Files and Screenshots**
<img width="960" alt="error" src="https://user-images.githubusercontent.com/39415493/58993834-89090700-87a3-11e9-9d66-fa505e8772a1.png">
@dagar There seems to be an error when uploading the log on Flight Review. 
<img width="960" alt="error al cargar log" src="https://user-images.githubusercontent.com/39415493/58994274-cc17aa00-87a4-11e9-961e-060511c72f9a.png">

**Additional** context
The last working log
https://review.px4.io/plot_app?log=116ede6d-d632-4836-91a7-fced724c82be--

**Comment by dagar** [comment]
Fix in https://github.com/PX4/Firmware/pull/12195
