### ISSUE TITLE
here2 GNSS gps compatible with Firmware v.1.8.0 

### ISSUE THREAD

**Issue by jbourne15** [PX4/Firmware#12208]
Are the magnetometers in the Here2 GNNS gps compatible with px4 firmware v1.8.0?

**Comment by dagar** [comment]
Please try v1.9.0. Support for this magnetometer was added post v1.8.0.

**Comment by dagar** [comment]
@hamishwillee worth capturing in docs when support for each thing appeared?

**Comment by hamishwillee** [comment]
@dagar That happens automatically - when support is added for a new product, a corresponding page must be added in the user guide to master (and will be copied whenever a new version is released). So if a product is not in the guide in a version you can assume it is not supported in that version.

It is the responsibility of whoever adds support to a board to make sure this page is created. I can help with that, but I need info on the board, links to ownership of board, instructions on how to connect it. 

This broke down in this case - I have been waiting on @profincnc to help create a page https://github.com/PX4/px4_user_guide/issues/474

From now on let's just create a minimal placeholder page that states at least that we support the product. Done here: https://github.com/PX4/px4_user_guide/pull/502
