### ISSUE TITLE
Check longitudinal wraps

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1220]
We should check that the transition from -180 to 180 longitude wraps correctly.

**Comment by tumbili** [comment]
Problems found so far:
- SITL longitude is not wrapped
- navigation logic does not work with wrapped longitude because wrapping is not considered in the l1 waypoint navigation, see e.g. https://github.com/PX4/ecl/blob/5e0a229ee8bf09430051090f58f71c95fa4755f0/l1/ecl_l1_pos_controller.cpp#L364

**Comment by tumbili** [comment]
@LorenzMeier I've investigated this quite a bit and came to the following conclusion:
The longitude coordinate is nowhere wrapped in the code, however, crossing the international datum line in a mission or in position control mode does no harm. The l1 position control code is actually designed to handle unwrapped longitude coordinates.

**Comment by tumbili** [comment]
Still need to test this for multicopters, since they use different navigation logic based on local position.

**Comment by sanderux** [comment]
@tumbili I guess there is no other alternative but for you to go to Fiji and test this. :)

**Comment by tumbili** [comment]
@sanderux Hehe, holidays in Fiji would be nice :)
Just gave this a test on SITL for multicopters and there does not seem to be an issue there either.

**Comment by tumbili** [comment]
Closing this as no issues found.
