### ISSUE TITLE
High RAM usage on Pixhawk 2.1 Cube

### ISSUE THREAD

**Issue by DanielePettenuzzo** [PX4/Firmware#12203]
We have noticed that in the last few weeks the memory usage on the Cube has increased by over 7kB and now with the same setup we had working, we already run out of RAM at boot. 

@sfuhrer can share the two commits from master that we tested. One from last week and one from a couple weeks ago. Please also share a log so that we can reproduce the same exact setup (in terms of parameters).

From the top of my head I can say that we were running VTOL (so both multicopter and fixed wind modules) and we had two MAVLink instances running, one of which was TELEM2 with high rates going to the companion computer. 

Is this RAM increase expected and if yes how can we decrease it so that we can still fly VTOL with the cube?

**Comment by DanielePettenuzzo** [comment]
FYI @RomanBapst

**Comment by dagar** [comment]
I'll take a look at your log once it's posted, but you're likely seeing the memory cost of the new WQ and the corresponding thread pre bus. This was expected and it's why [uORB changes](https://github.com/PX4/Firmware/pull/12040) were pursued at roughly the same time, which will win back a lot more memory (hopefully soon).

If anyone would like to help with the transition please test and review PRs related to uORB::Subscription and the new WQ.

 - https://github.com/PX4/Firmware/pull/12123 <- most important
 - https://github.com/PX4/Firmware/pull/12176
 - https://github.com/PX4/Firmware/pull/12186
 - https://github.com/PX4/Firmware/issues/12068
   - Once everything is moved out of Nuttx HPWORK and LPWORK we can disable them in most configurations and save another few kB.

**Comment by sfuhrer** [comment]
Here's the log: https://review.px4.io/plot_app?log=06617924-5fd8-4142-8617-2d0d8a18eba6
It was with master from last Friday, 43e3fc707de823f. RAM is at 99%. 

Before we were flying with https://github.com/sfuhrer/Firmware/tree/Babyshark (close to master in mid April). We already had RAM at around 95%, so the RAM difference is about 10kB.

**Comment by dagar** [comment]
This is the other effort that has the potential to save a large amount of memory soon. 
https://github.com/PX4/Firmware/pull/12207

In particular for the VTOL case I believe we could have all 5 controllers (mc_att_control, mc_pos_control, fw_att_control, fw_pos_ctrl_l1, vtol_att_control) that are currently separate tasks moved to run out of 2 WQ threads. This will save something like 10-15 kB (completely separate from the savings mentioned above in https://github.com/PX4/Firmware/issues/12203#issuecomment-499703008) and slightly reduce cpu usage.

**Comment by julianoes** [comment]
@DanielePettenuzzo still an issue?

**Comment by sfuhrer** [comment]
> @DanielePettenuzzo still an issue?

No, with the recent WQ changes not an issue anymore.
