### ISSUE TITLE
NuttX STM32F7 write-back dcache

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#12216]
Due to ARM 1259864 data corruption eratta we currently have the dcache disabled on stm32f7. One solution is to switch to write-back data cache configuration, but this is currently broken for other reasons (starting at our own px4io driver https://github.com/PX4/Firmware/pull/12075).

 - https://nuttx.org/doku.php?id=wiki:howtos:port-drivers_stm32f7#write-back_vs_write-through_d-cache

**Comment by LorenzMeier** [comment]
@davids5 Is there a quick path to get there?

**Comment by davids5** [comment]
I had spent a little bit of time on this before discussing it with Daniel. It's really just a matter of spending the time to ferret out all of the issues. The obvious ones that hard faults will be the first. Second Step would be figuring out the subtle bugs due to misalignment
