### ISSUE TITLE
UAV don't follwing the waypoints in mission mode

### ISSUE THREAD

**Issue by sampathkumarch** [PX4/Firmware#12262]
Hi , am using px4 firmware of pixhawk4 
Am using airframe is standred plane ( without rudder)
I put in all sensors. I fly with is manual mode and stabilize mode then after a give the waypoints for mission plane. I put pitch degree is 10 . When am start the mission the UAV tack a tack off but it go always  left direction am given straight waypoint . And wrong ways point then after automatically pitch down so am convert into stabilize mode safely landed .why it's go wrong path. Any parameter are issued . place help me

**Comment by mhkabir** [comment]
Please follow the issue template.

**Comment by sampathkumarch** [comment]
How to resolve this issue?.please tell me
