### ISSUE TITLE
Copter lose altitude and start yaw in mission mode

### ISSUE THREAD

**Issue by MKargus0** [PX4/Firmware#12291]
When I start mission on my drone (px4fmuv5 1.9 ) after some time it start lose altitude and start yaw
I do not know what caused this behavior
This is my fligt log
https://review.px4.io/plot_app?log=c8276346-7889-41ae-a4a8-a21089a8da89
ALTITUDE POSITION and STABILIZED modes working normal
Can you help me with this problem? Thank you.

**Comment by RomanBapst** [comment]
@MKargus0 at first glance it looks like an actuator problem. The drone demands full thrust but nothing happens. Also there is a build up of yaw rate which is somehow not counter acted.
