### ISSUE TITLE
EKF2_RNG_A_HMAX, EKF2_RNG_A_VMAX missing units in parameter meta data

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#12305]
https://discuss.px4.io/t/units-m-of-ft-for-range-aid-params/11464

**Comment by hamishwillee** [comment]
@priseborough The units for [EKF2_RNG_A_HMAX](https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_params.c#L1145) and EKF2_RNG_A_VMAX is just metres right?
