### ISSUE TITLE
[load_mon] pga460 low on stack!

### ISSUE THREAD

**Issue by danielghirst** [PX4/Firmware#12301]
**The bug**
The drone will occasionally disarm and drop out of the sky when the ‘return home’ command is given. I believe it is the result of a memory issue. Whenever the drone does drop out of the sky the log files are corrupted, so I am not able to see the warnings before it disarms. The last few times I have attempted to reproduce the problem I have been getting “[load_mon] pga460 low on stack!” warning. The warning is displayed only in normal flight. I’m wondering if the warning is the same memory problem creating the drone to disarm at times.  

**To Reproduce**
1. Drone switched on 
2. Took off in position mode
3. Fly away  and then hit return home. 
4. See drone fall or the warning in the flight log

**Expected behavior**
The drone is expected to return home, land and then disarm. 

**Log Files and Screenshots**
[Screen Shot 2019-06-17 at 10.22.03 AM.pdf](https://github.com/PX4/Firmware/files/3298154/Screen.Shot.2019-06-17.at.10.22.03.AM.pdf)

Link to the flight log file:
https://review.px4.io/plot_app?log=5da7db09-05fe-4a89-a1b3-776b634e0972

**Drone (please complete the following information):**
- Teal One with stable 1.9.0

**Comment by dakejahl** [comment]
These problems are unrelated. You need to increase your stack size in the pga460 driver.

You need to reduce your RAM consumption if you are getting hardfaults during flight. Try disabling the extra mavlink streams.
