### ISSUE TITLE
Request for differential drive robot control

### ISSUE THREAD

**Issue by rishab26201** [PX4/Firmware#12310]
Hey,
So I was wondering if it would be possible to create/integrate differential drive bots/rovers like husky rover with Px4, along with the existing Ackerman steering based rover.

Thanks

**Comment by SalimTerryLi** [comment]
Currently there is no difference between these two. You can simply apply to a differential one by replacing the [mixer file](https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers/generic_differential_rover.main.mix)

**Comment by julianoes** [comment]
This has been fixed. There is an "airframe" config for the AION robot.
