### ISSUE TITLE
Can't get the distance data of the PX4_Flow and sonar

### ISSUE THREAD

**Issue by Martz19** [PX4/Firmware#12312]
![Screenshot from 2019-06-20 12-35-22](https://user-images.githubusercontent.com/50084151/59873106-863c1380-9358-11e9-92d1-04ec54fe8ac1.png)

**Comment by julianoes** [comment]
@Martz19 has this been resolved in the meantime?

**Comment by Martz19** [comment]
Yes, thanks.

Josue Martinez Martinez
Undergradute Computer Engineering Student
Department of Electrical and Computer Engineering
Universidad Ana G. Mendez Recinto de Gurabo
Phone: (787)-517-6189
