### ISSUE TITLE
Can't find who trows "PREFLIGHT FAIL: EKF INTERNAL CHECKS"

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#12336]
I got this error and it's well documented here: https://docs.px4.io/en/flying/pre_flight_checks.html,
but I'd like to change the firmware to understand which problem is of the many possibles.
The problem is that I'm unable to find anything in the code that seem to send that error with mavlink_log_critical(). It would be nice if someone could point me at the right code. Thanks.

**Comment by julianoes** [comment]
You can find it if you look in v1.8.2:
https://github.com/PX4/Firmware/blob/v1.8.2/src/modules/commander/PreflightCheck.cpp#L561
