### ISSUE TITLE
No feedback about mag declination

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#1234]
I think this is a bit dangerous:
https://github.com/PX4/Firmware/blob/94c69e11ae1ec44c80eec1c979201c7d7e51cdb0/src/modules/attitude_estimator_ekf/attitude_estimator_ekf_main.cpp#L480

We are essentially not sure if has extracted the mag declination from the lookup table or whether it uses the parameter value.

Stumbled upon when investigating this email:
https://groups.google.com/forum/#!topic/px4users/zKkBFsW6FH8

**Comment by LorenzMeier** [comment]
I would argue that a GPS fix in the log (or home position set) guarantees that the declination is from the table. I'm closing this.
