### ISSUE TITLE
Unable to arm the drone

### ISSUE THREAD

**Issue by deepanshgoyal0718** [PX4/Firmware#12347]
My python file corresponding to the launch file contains the following commands:
print "Arming"
result = arming_srv(value=True)
print result
.
.
.
.
arming_srv = rospy.ServiceProxy("/mavros/cmd/arming", CommandBool)

But still when I execute the file the value of result printed is False. Please help me debug this.

**Comment by Pedro-Roque** [comment]
@deepanshgoyal0718 can you check QGC or the log for any errors that might not allow your vehicle to arm?

**Comment by hamishwillee** [comment]
Closing. User has not responded to basic follow up query.
