### ISSUE TITLE
px4_fmu-v5x support

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#12340]
TODOS:

- [x] Drivers
  - [ ]  Digital power module 
    - [x]    Add INA226
    - [ ]   Support
- [x]  BMI088
- [x]  ISM330
- [x]  BMP388
- [ ]  ~~A71CH~~ SE050

**Comment by dagar** [comment]
Initial board support. https://github.com/PX4/Firmware/pull/12135

**Comment by davids5** [comment]
@ItsTimmy  - has all the Power module / Battery work been upstream to support the Dual brick Digital power module?

@dinomani - The dual brick Digital power module needs integration and testing to get this issues closed.

**Comment by ItsTimmy** [comment]
Yes, the INA226 work (with support for multiple bricks) has been merged: https://github.com/PX4/Firmware/pull/12673
