### ISSUE TITLE
Multicopters: Implement position control as velocity feedforward and position hold, not carrot

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1238]
@DrTon Before you start reading this 8). We're not going to rewrite the commander and multicopter position controller for this in the first round. We first find out how to do it right, then learn, then rewrite it to clean up the architecture after we found out how the architecture should look like. This will allow our users to benefit instantly and will ensure we end up with a better solution, because we've understood the problem well before re-doing the architecture.

@sirPerna @julianoes This issue is to track the position control.

Instead of "moving a carrot" like done here, we propose to change to a velocity based control model.
https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L824

It would be more intuitive to map the stick position directly to velocity and to add these checks to make things really convenient. We want this to be intuitive, which is not the same thing as correct or precise - if we make it intuitive, users will be able to fly precisely because its easy to use.
  * If the stick is centered (deadzone), hold position at current position
  * If the stick is off-center, command a desired velocity. Max stick = max manual velocity
  * Limit at all times the acceleration. This means that if the user changes direction, the system should not accelerate / decelerate with 3g (even if it could), instead it should decelerate with a configurable maximum acceleration and then stop
  * *Never go back*. The system should not move against its motion vector. If the user commands 10 m/s and then centers the stick, it should slow down at maximum acceleration and then hold. We can make the maximum acceleration a dependency of the maximum velocity. Setting the max. velocity will make the system then more aggressive or less aggressive.

**Comment by v01d** [comment]
If I may chime in, I also believe its is really valuable to have at least the option of a "velocity" flight mode. Under this mode I would not expect any position hold, but velocity hold. This is much more intuitive for manual control than position. The problem with the latter is that the position setpoint, after being ,over with the the sticks is not "visible". On the other hand, under velocity control, I know that if I let go of the stick, I expect an immediate stop action. I think this is also safer for low altitude flying using px4flow. Maybe position makes more sense using GPS at higher altitude.

On the other hand, a velocity controller is also useful in off board mode. I believe current offboard velocity setpoint is actually a position setpoint move rate, which is kind of misleading.

**Comment by LorenzMeier** [comment]
Please feel free to test this PR:

https://github.com/PX4/Firmware/pull/2305

-Lorenz

**Comment by julianoes** [comment]
Is this done or still todo?

**Comment by LorenzMeier** [comment]
Done since a very long time.
