### ISSUE TITLE
Px4(1.9.0) support the offboard mode for fixed wing or not?

### ISSUE THREAD

**Issue by zhanghouxin07** [PX4/Firmware#12383]
Hi there,

I'am research the fixed wing platform about PX4. However, I can enter the offboard mode with FW in simulation. The Developer guide says that Fw is not supported by PX4, but someone say the FW can be used on FW.

Thank you for your help!!

Thanks!

**Comment by hamishwillee** [comment]
@RomanBapst Can you confirm whether this is correct, and if not, in which version offboard control for fixed wing was implemented. In https://docs.px4.io/master/en/flight_modes/offboard.html we say:
![image](https://user-images.githubusercontent.com/5368500/60473738-e795a800-9cb1-11e9-8646-643022a06c2b.png)

**Comment by zhanghouxin07** [comment]
I try to enter the offboard mode again. I complete it successfully. the developer guide of px4 may be a little out of style. 
thx

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Fixed wing offboard mode has only started work since #12149 and #12311 

Only attitude setpoints (attitude, bodyrates) are supported at this point.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim Thanks very much - I've added docs in https://github.com/PX4/px4_user_guide/pull/506

As a general rule, an undocumented feature is no feature at all :-). So if you add something, please document, ask me for help, or as a last resort add a docs issue.

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Thanks for the input. I will try to make more of the features I work on to be shown in the documentation
