### ISSUE TITLE
Error in startup script in lockstep simulation with floating point PX4_SIM_SPEED_FACTOR

### ISSUE THREAD

**Issue by fabianschilling** [PX4/Firmware#12400]
Using a floating point `PX4_SIM_SPEED_FACTOR` as described in the Devguide (https://dev.px4.io/master/en/simulation/#simulation_speed) results in the following error:

```
INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
etc/init.d-posix/rcS: 165: etc/init.d-posix/rcS: Illegal number: 0.5
ERROR [px4] Startup script returned with return value: 512
```

The error is caused by performing calculations with built-in shell math (which only supports integer arithmetic) in lines 165, 169, and 173 in `ROMFS/px4fmu_common/init.d-posix/rcS`.

To reproduce, issue: `PX4_SIM_SPEED_FACTOR=0.5 make posix gazebo `. Setting `PX4_SIM_SPEED_FACTOR` to integer values results in the expected behavior.

A simple solution would be to use `bc` for both integer and floating point calculations in the `rcS` file.

**Comment by julianoes** [comment]
Thanks for the issue and fix!
