### ISSUE TITLE
Mavlink FTP is too slow

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#1241]
Download speed via USB is only ~10kbytes/s, this makes it completely useless for logs download. Using `fetch_log.py` I got ~250kbytes/s, not very fast but usable. Need to think how to improve download speed. On of the problem I see is that ALL encapsulated data packets (even ACKs) have the same size. Need to use variable size encapsulated data packets or introduce new messages for FTP.

**Comment by LorenzMeier** [comment]
This has been addressed with a 30x speedup, which is about the max you can get through the USB interface we're using.
