### ISSUE TITLE
Unable to arm my drone

### ISSUE THREAD

**Issue by raph12345** [PX4/Firmware#12422]
Hello everyone
I recently mounted a drone based pixhawk 4 (holybro) but today my drone refuses to arm and I really do not understand why.
my drone was flying very well in 1.9.0 and it seems to me that the problem occurred following the update in 1.9.1 because I have not made a parameter change in-temp.
I do not know what it can come from yet I searched the forum if solutions had been found on this kind of problem.

my gps seems to work:

![gps](https://user-images.githubusercontent.com/52594432/60753325-bf1eee00-9fd0-11e9-8c61-1d9a72f0ed97.PNG)

below the result of a ls /dev and a ms5611 start

![Annotation 2019-07-02 212244](https://user-images.githubusercontent.com/52594432/60753331-cc3bdd00-9fd0-11e9-967a-e3ca5549f9d0.png)

quoted qgroundcontrol software does not show me error

![qground](https://user-images.githubusercontent.com/52594432/60753334-d958cc00-9fd0-11e9-99c8-84c7210d3b98.PNG)

![qground2](https://user-images.githubusercontent.com/52594432/60753335-dbbb2600-9fd0-11e9-9c70-701a45dcf899.PNG)

in the logs I see 2 error
[E] at :0 - “serialnmea: No known GPS device found. Specify the COM port via QT_NMEA_SERIAL_PORT.”
[E] at C:\projects\qgroundcontrol\src\PositionManager\PositionManager.cpp:139 - “QGCPositionManager error 1”

but I’m not sure my problem comes from there … because I’m not sure I understand the error messages either

looking for this or this QT_NMEA_SERIAL_PORT parameter could be changed i have to try modified the serial port baudrate

![gps_baud](https://user-images.githubusercontent.com/52594432/60753339-eb3a6f00-9fd0-11e9-9e7f-b10817417ed0.PNG)

and when restarting qgroundcontrol displays the error below.

![crc](https://user-images.githubusercontent.com/52594432/60753344-f5f50400-9fd0-11e9-8415-15a10e918f2b.PNG)

here are the logs. (rename log.pdf in log.txt to see it)
[log.pdf](https://github.com/PX4/Firmware/files/3364511/log.pdf)

If anyone could take a look at it and tell me why I can not arm my drone it would be nice!

thank you

**Comment by julianoes** [comment]
Is there no message when it refuses to arm?

**Comment by raph12345** [comment]
Hi 
the only messages I have are those in the log file. 
I activated the logs to be able to retrieve them on the sd card  because the drone is not connected in usb at this time. 
the LED of my gps antenna is blue and when I try to arm via the switch the led flashes quickly in white and then turns blue again ... normally when the drone is armed the led is green. 
is there a way to increase the log level on the sd? 
I admit to being stuck there Thank you for your help :)

**Comment by hamishwillee** [comment]
Blue means armed with no GPS lock: http://docs.px4.io/en/getting_started/led_meanings.html

I presume you have tried this outside where you know you have a great GPS signal. 

You're best off connecting to QGC via USB or a telemetry module. I don't know much about the logs.

**Comment by julianoes** [comment]
Note that you can't arm with USB attached unless you disable the circuit breaker:
https://dev.px4.io/en/advanced/parameter_reference.html#CBRK_USB_CHK

**Comment by julianoes** [comment]
@raph12345 is this resolved?

**Comment by raph12345** [comment]
Yes you can close.

My pixhawk was Dead, after exchange its ok.
