### ISSUE TITLE
preflight fail baro sensor 0 missing 

### ISSUE THREAD

**Issue by raph12345** [PX4/Firmware#12423]
Hello,

recently I have this error message in QGC that appears when I try to arm my drone while it is connected with a USB cable to my PC.

what is this error message?

thank you

**Comment by bresch** [comment]
Hello @raph12345 which autopilot hardware do you have? Some boards don't have a barometer. Can you open QGC, go to the MAVLink console and enter `sensors status'? You should directly see if there is a barometer connected and working or not.

**Comment by raph12345** [comment]
hi bresh,

I use a pixhawk 4 (holybro) and the latest version of firmware 1.9.1.

below the result of the command sensor status:
![sensor_status](https://user-images.githubusercontent.com/52594432/60767530-bbb36180-a0b9-11e9-9f11-3e0cba800085.PNG)

I turned off the barometer and restarted and I tried to arm the drone but without result ...
![chek](https://user-images.githubusercontent.com/52594432/60767571-249ad980-a0ba-11e9-866b-2e304180b265.PNG)

in QGC where can I find the preflight cheklistlist?

**Comment by hamishwillee** [comment]
> in QGC where can I find the preflight cheklistlist?

https://docs.qgroundcontrol.com/en/SettingsView/General.html#miscellaneous

"Use preflight checklist" checkbox

**Comment by LorenzMeier** [comment]
Your hardware is faulty. It should have a baro, but it isn't detected. Ask the vendor for a replacement.
