### ISSUE TITLE
Auto-estimate hover throttle

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#12439]
Setting the correct hover throttle seems to be a consistent issue for users and is a source of a common frustration. We need to implement an estimator that takes current vertical velocity and estimates hover throttle for a given system. Once it is estimated, the parameter should be set so that on next takeoff it is already correct.

This is also relevant for commercial models where people add/remove large cameras and will certainly forget to adjust the vehicle settings.

**Comment by dagar** [comment]
What about the voltage drop over a flight?

**Comment by bresch** [comment]
@cmic0 Can you give links to you dev branch, prototype script and ref papers of your hover throttle estimator please?

**Comment by bresch** [comment]
@dagar Voltage drop compensation only works if you have it calibrated (feedforward compensation). Here we want an estimator that basically learns the hover thrust such that the user doesn't even need to specify the hover thrust via a parameter and that self-adjusts during flight.

**Comment by dagar** [comment]
> @dagar Voltage drop compensation only works if you have it calibrated (feedforward compensation). Here we want an estimator that basically learns the hover thrust such that the user doesn't even need to specify the hover thrust via a parameter and that self-adjusts during flight.

I'm talking about the hover thrust changing over the course of a flight as a result of the battery discharge (on typical hobby ESCs). The estimated (and committed) hover thrust by the end of a flight will then be off on the next flight with a fresh battery. Yes it will be adjusted again, but it might not be correct at takeoff. Mainly just curious if that's a consideration.

![Screen Shot 2019-07-11 at 3 31 46 PM](https://user-images.githubusercontent.com/84712/61079501-03efbe00-a3f1-11e9-8fb6-c85f0d697d27.png)
https://logs.px4.io/plot_app?log=b33c30d5-3816-4cfd-9ca4-2296948ca7bb

![Screen Shot 2019-07-11 at 3 33 38 PM](https://user-images.githubusercontent.com/84712/61079688-53ce8500-a3f1-11e9-8674-ee7b8b5be415.png)

**Comment by Antiheavy** [comment]
Changes in density altitude (different days, different weather, different locations) could play a significant roll here as well.

**Comment by jkflying** [comment]
This is also a consideration for any cargo drone with a payload.

**Comment by julianoes** [comment]
Notes from the devcall (correct me if I get it wrong):
- This should probably not be implemented in the controller but in some estimator, e.g. land_detector.
- This is work in progress and will need quite some testing.
- This hopefully makes it into v1.10.

**Comment by bresch** [comment]
I'll start to work again on that in about 1-2 Current WIP here: https://github.com/Auterion/Flight_Control_Prototyping_Scripts/pull/3
