### ISSUE TITLE
VTOL front transition direction

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#12455]
Currently the user has two possibilities to plan a front transition:

1) Use VTOL Takeoff waypoint: This is a combined takeoff and transition waypoint. The vehicle can transition in arbitrary directions, e.g. it does not align with the next waypoint. The idea is to use this type of waypoint with the weathervane feature such that the vehicle will automatically turn and transition into the wind.

2) Use dedicated transition waypoint. In this case the vehicle transitions into the direction of the next waypoint. The target heading is enforced before a transition can commence.

Issue:
- if you enable weathervane using option 2) and the wind direction is not aligned with the next waypoint then the transition will never occur as the vehicle does not even attempt to turn towards the traget heading (due to weathervane active).
- if the user uses option 1) he should be able to specify whether he wants the vehicle to align with the direction of the next waypoint after reaching transition altitude.
- if enforcing a transition heading then a strategy needs to be implemented how the vehicle can try (for a certain amount of time) to achieve the target heading. If it cannot be achieved the transition should be aborted.

**Comment by sfuhrer** [comment]
closing, as mostly solved with https://github.com/PX4/Firmware/pull/12630
