### ISSUE TITLE
Add option to force disarmed values when CBRK_IO_SAFETY is set

### ISSUE THREAD

**Issue by jlecoeur** [PX4/Firmware#12457]
**Describe problem solved by the proposed feature**
It is sometimes desired to lock all outputs to the disarmed values when disarmed. This is not possible when the safety switch is disabled (by setting CBRK_IO_SAFETY). In this case, the system is either in prearmed or in armed mode, and the servos are always free to move.

**Describe your preferred solution**
Add an option to lock all outputs to the disarmed values when in prearmed mode. This could be a parameter named CBRK_IO_PREARMED:
- `CBRK_IO_PREARMED = 0`: current behaviour
- `CBRK_IO_PREARMED = 42`: all outputs locked to disarmed values when disarmed or prearmed.

**Describe possible alternatives**
- force disarmed values when CBRK_IO_SAFETY is set and the system is not armed. This would be an easier solution, but might break someone's workflow.

**Additional context**
The current behaviour is based on the assumption that (i) rotor commands are scaled with thrust command, like it is the case for multirotors, and (ii) flap motion is harmless.
However this is not always true:
- a rotor can be mixed to roll only. It is thus not stopped by a low thrust value, and starts spinning unexpectedly. This can be dangerous.
- servos may drive heavy/large parts, which are better locked when disarmed.

**Comment by julianoes** [comment]
FYI @bresch
