### ISSUE TITLE
vision fusion  + ekf2  

### ISSUE THREAD

**Issue by lgh5054** [PX4/Firmware#12459]
hello 

And ekf2_aid_mask 8
sys_companion (921600)
ekf2_eva_Noise 0.20
ekf2_evp_Noise 0.20
ekf2_ev_delay 175.0ms
I watched the paramedics

When viewing the mavros/local_position/pose value, Even if you stay still, you lose your position.
Is this a s problem  a connection speed problem with the pixhawk2 and tx2 board?

position value x y 0
![60888461-caed0780-a291-11e9-8f52-fbb9b8cc6aab](https://user-images.githubusercontent.com/35057391/61015803-2a4d3380-a3c8-11e9-80ea-e8bac7697c77.png)
#
![60888395-a8f38500-a291-11e9-8835-6ca9e8b7edd1](https://user-images.githubusercontent.com/35057391/61015810-30431480-a3c8-11e9-88f3-3013e602901d.png)

**Comment by mhkabir** [comment]
Please follow the issue template.
