### ISSUE TITLE
mission_state won't change after call save_mission_state

### ISSUE THREAD

**Issue by ToppingXu** [PX4/Firmware#12460]
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L1541

should here need to add one line like:
mission_state.current_seq = _current_mission_index;

**Comment by dagar** [comment]
Hi @ToppingXu, could you open a pull request with the change? https://help.github.com/en/articles/creating-a-pull-request

**Comment by ToppingXu** [comment]
@dagar pull request done.

**Comment by julianoes** [comment]
Fixed by #12468.
