### ISSUE TITLE
Jenkins intermittant failure (Catkin build on ROS workspace)

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#12475]
The "Catkin build on ROS workspace" job in the top level Jenkins pipeline has started failing intermittently (both PRs and master).

### Master
![Screen Shot 2019-07-14 at 1 01 44 PM](https://user-images.githubusercontent.com/84712/61186806-8f5a9080-a637-11e9-845f-32088b5c23e1.png)
http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/activity?branch=master

### Typical failure output.

![Screen Shot 2019-07-14 at 1 02 33 PM](https://user-images.githubusercontent.com/84712/61186814-abf6c880-a637-11e9-977d-21fd8fc66894.png)
Example: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/master/1127/pipeline

@TSC21 could you take a look?

**Comment by lamping7** [comment]
I pulled the docker image, ran the same steps as Jenkins and ran the test numerous times without failure. Let's try to catch something in a log.

**Comment by lamping7** [comment]
It seems that px4 is shutting down when it shouldn't. #12483

**Comment by lamping7** [comment]
This looks good now.
