### ISSUE TITLE
Simulating a wifi drone through jMavsim

### ISSUE THREAD

**Issue by wuxianshen** [PX4/Firmware#12487]
I try to simulate a wifi drone following the instructions @
http://dev.px4.io/master/en/simulation/jmavsim.html#simulating-a-wifi-drone
Run "sudo make broadcast jmavsim" at the Firmware directory, but prompting "broadcast cannot be the first argument".
Is there any mistakes in my action or has this feature been removed?

**Comment by julianoes** [comment]
@wuxianshen Thanks for raising this issue. This is indeed not working according to the docs anymore.
What exactly are you trying to simulate? Or what is your setup?

@dagar do you know the new make target for this? Or has this been removed?

**Comment by wuxianshen** [comment]
@julianoes  Thanks!  I am trying to simulate px4 on one Linux PC and run offboard control code on another windows PC... 
Actually this special requirement does not make real sense ...
Thank you very much !!!

**Comment by julianoes** [comment]
@wuxianshen You can also just run the simulation as normal and then set the param `MAV_BROADCAST` to 1 to enable broadcast.

**Comment by wuxianshen** [comment]
Thanks @julianoes !
Yeah this really works, but I should use the 14550 port for connecting the uav (No data @ 14540 port), which I thought to be customized for QGC.
So there is nothing different between connection through QGC and offboard control?  We can just use the 14550 port as an alternative for offboard contorl?
Thank you!

**Comment by julianoes** [comment]
So you're saying that you would like to have 14540 broadcast as well?

In that case, remove the `-m onboard` from here:
https://github.com/PX4/Firmware/blob/aaad71faab6bdb507bb9525f1c9d64edc33632bc/ROMFS/px4fmu_common/init.d-posix/rcS#L249

Alternatively, to connect to a certain IP you can also add `-t IP` to `mavlink start`.
