### ISSUE TITLE
Bad position control - need help, log included

### ISSUE THREAD

**Issue by yoosun116** [PX4/Firmware#12499]
Hello, i’m very new to using px4 and recently having serious problems in flight test.

I’m using pixhawk 4, px4 firmware v1.9.1 with Qgroundcontrol for with DJI f450 frame.
Additionally, for altitude measurement, i added TFmini Lidar sensor and changed corresponding parameters.

I basically followed px4 official guide and left all other settings in default.
So i expected my drone to fly well, but as shown in the log below, when i arm and switch to position mode, it actually does not follow my setpoint command at all…

https://logs.px4.io/plot_app?log=fb60b53e-bfec-43f8-890d-4a4b9e94cfe4

I think it needs significant performance tuning or something,
Can anyone diagnose this problem?
Any help is appreciated.
Thank you

p.s. I added a new log. This time i tried hold mode and failed.
When i arm with stabilized mode to takeoff, it seems no problem.
However right after i switch to hold when the drone is in the air, it never holds position and instead it diverges from the setpoint. It fell down again and a prop is broken this time (i have enough spare though).....

https://logs.px4.io/plot_app?log=3ecb6fb7-5b8c-4663-a348-a482a01b8159

What should i do to deal with this?

p.s.2  another log with a clip, same setting as above and with OFFBOARD mode with raspberrypi & mavros

https://logs.px4.io/plot_app?log=1e2e1b0c-d53c-4e77-8c87-bda714aacd6b
https://www.youtube.com/watch?v=hgdZA9_xj88

apparantly it shows bad xyz setpoint tracking.

**Comment by julianoes** [comment]
For this sort of issue my guess is usually that your compass heading is not accurate due to magnetic interference or bad calibration.

I suggest that you do a static test (without flying) and make sure the heading of the drone is correct within 10 degrees or so.

**Comment by julianoes** [comment]
@yoosun116 did you find anything in a static test?

**Comment by julianoes** [comment]
No answer, closing.
