### ISSUE TITLE
Rover SITL test failing

### ISSUE THREAD

**Issue by ItsTimmy** [PX4/Firmware#12490]
**Describe the bug**
Some PRs are failing the Rover SITL test, without having changed any functionality related to the rover. For example, [here](http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-12389/7/pipeline/). This is caused by an issue with the timing of the `actuator_controls_0` topic and Gazebo.

**Expected behavior**
The test should pass.

**Log Files and Screenshots**
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-12389/7/pipeline/

**Drone (please complete the following information):**
- SITL `gazebo_rover`

**Additional context**
This rover test was added recently, in #12117

**Comment by julianoes** [comment]
Strange, do you understand what the timing issue is?

**Comment by ItsTimmy** [comment]
It seems that, because the system is running in lockstep, Gazebo expects an `actuator_controls_0` message to be published after every sensor reading. In the fixed wing and multicopter attitude controllers, this is no problem, because their timing is driven by polling sensor data. However, `rover_pos_control`'s timing is independent of everything. It's still 250Hz, but perhaps not _exactly_ 250Hz. So there may come a time by random chance where Gazebo wants to provide a second sensor reading before a new `actuator_controls_0` message has come in, but `rover_pos_control` wants to wait an extra millisecond or so to publish the message, so there's a deadlock.

I'll fix this by making the timing depend on polling sensor data.
