### ISSUE TITLE
Here 2 magnetometer not detected as external on Pixhawk Cube

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#12548]
Setup:
Pixhawk 2.1 + Here 2 GPS

Issue:
External magnetometer connected via I2C gives data but the sensor is detected as internal.

**Comment by julianoes** [comment]
Notes from devcall:

- The Pixhawk seems detected correctly but presumably the logic in the driver is wrong.
- Next step: figure out which driver is used and check there.

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/Firmware/pull/12554.
