### ISSUE TITLE
Auto sensor reading after pixhawk startup

### ISSUE THREAD

**Issue by bthnekn** [PX4/Firmware#12550]
Hi guys is there any method for sending messages through mavlink console while pixhawk startup or when pixhawk armed.

ı have a sensor called usharp patch from aerotenna like ulanding radar distance sensor ı am reading data when ı write "usharp_patch start" to the mavlink console and watch the data with analyze section. So ı am wondering can ı send that "usharp_start" message to mavlink console when ı power the pixhawk?

Well, maybe changing flight mode features will do that but ı dont know how to change flight mode features either.

btw sensor's driver is uploaded to the pixhawk but ı dont know who  did that ı'll publish the driver as soon as find the driver file

**Comment by julianoes** [comment]
Do I understand correctly that you just want to do a nsh command on startup to start a sensor?

If you're already compiling your own code, you can add the command to the startup here:
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS

**Comment by bthnekn** [comment]
Yes just try to add a new command. Normally I write "usharp_patch start" command manually via mavlink console in qground control.What I want is actually this starting process of the sensor triggered with startup like the compass or gyro (sensor dont need calibration btw)

Thank a lot for your help ı will examine your link 

![123](https://user-images.githubusercontent.com/53266788/61850034-dfe5af80-aebb-11e9-9d58-e8ac5405166e.png)

**Comment by mhkabir** [comment]
I'm closing this as a solution has been posted, please use discuss.px4.io if you need further help.

**Comment by mhkabir** [comment]
Also see https://dev.px4.io/v1.9.0/en/concept/system_startup.html
