### ISSUE TITLE
EKF2 not resetting position state when stopping GPS use and EV is already running

### ISSUE THREAD

**Issue by artifactz** [PX4/Firmware#12558]
**Description**
"Failsafe enabled: no local position" when EKF2 switches from GPS to external vision. You can read [my diary on discuss.px4.io](https://discuss.px4.io/t/outdoor-indoor-gps-slam-no-local-position/11958), which is a lot more detailed.

**To Reproduce**
1. drone with GPS and SLAM, visual odometry or similar via `/mavros/vision_pose`, `VISION_POSITION_ESTIMATE` or similar
2. `EKF2_AID_MASK` is GPS + EV_POS + EV_YAW
3. take off, hover/fly for at least 30 seconds (due to some internal EKF2 checks, see forum post)
4. fly into a GPS-denied area (tunnel, hall etc.)

**Expected behavior**
EKF2 recognizes a decrease in GPS quality and switches to EV as primary localization source.
Because GPS was bad and EV can be imperfect as well, it needs to reset its position state, to avoid failing `_vel_pos_test_ratio` checks.

**Log File**
https://logs.px4.io/plot_app?log=b7f5fb21-808a-42eb-844d-18901eb24620

**Screenshot**
![plot](https://user-images.githubusercontent.com/4330620/61888191-65408280-af03-11e9-9327-5da45ed42127.png)

* `pos_test_ratio` explodes as soon as stopping GPS use
* EKF states[7..8] (position) are only reset after dead reckoning and failsafe

**Drone**
- rotary wing

**Comment by julianoes** [comment]
@priseborough would be great if you could comment.

**Comment by mhkabir** [comment]
@artifactz is your vision yaw in the NED frame?

**Comment by artifactz** [comment]
@mhkabir My vision yaw is in ENU, because I use Mavros:

> ROS uses ENU frames as convention, therefore position feedback must be provided in ENU.
(https://dev.px4.io/v1.9.0/en/ros/external_position_estimation.html)

Is that incorrect?

**Comment by LorenzMeier** [comment]
@jkflying Could you please assist the review?
