### ISSUE TITLE
Changing airframes script does not perform a new binary building

### ISSUE THREAD

**Issue by hyonlim** [PX4/Firmware#12563]
**Describe the bug**
Changing airframe script does not make build system perform new binary packing.

**To Reproduce**
1. Compile whole repository
2. Change only ROMFS/px4fmu_common/init.d/airframes/* (any randomly chosen file)
3. Build repository again - it does not perform new binary build.

**Expected behavior**
This should generate a new binary that reflect changes

**Comment by dagar** [comment]
This should be fixed as of https://github.com/PX4/Firmware/pull/12525. Can you try current master?

**Comment by jlecoeur** [comment]
I believe this was fixed, @hyonlim feel free to reopen if you still have this issue.
