### ISSUE TITLE
This can lead unnecessary detection of px4flow.

### ISSUE THREAD

**Issue by hyonlim** [PX4/Firmware#12571]
**Describe the bug**
This mandatory execution of px4flow will check i2c bus with address given (0x42), but it does not perform actual sensor identity check. When there is any device with address 0x42, it will recognize it as px4flow and outputs wrong data.

**To Reproduce**
In the hardware put any i2c device with address 0x42

**Expected behavior**
Even though there is a response on the address, it should check whether the device is px4flow or not.

**Comment by dagar** [comment]
Let's add a parameter to start px4flow rather than probing every boot.

**Comment by dagar** [comment]
PR adding a parameter. https://github.com/PX4/Firmware/pull/12633

**Comment by hamishwillee** [comment]
Will need to be added to http://docs.px4.io/master/en/sensor/px4flow.html#pixhawk-setup

**Comment by Ken-Thorburn** [comment]
Hey, I can't find the parameter sens_en_px4flow within px4 1.9.2. If this parameter hasn't rolled out yet, I am unable to get the sensor working anyway https://github.com/PX4/Firmware/issues/12911
