### ISSUE TITLE
Battery voltage drop should be compensated before filtering

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#1260]
Voltage drop compensation (https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander_helper.cpp#L321) applyed to filtered voltage. It's incorrect and results large noise. Need to do compensation before filtering, in sensors app. Also need to review coefficients, because for my MC setup remaining battery estimation based on compensated voltage is more noisy than voltage itself.

**Comment by tumbili** [comment]
@LorenzMeier @DrTon I don't understand why we do not use the measured current compensating for the voltage drop. Based on a simple serial internal resistance mode the estimated battery voltage would be:
V_bat = V_meas + Current * R_internal

Throttle is correlated with current but the relation changes very much during a flight.
Did you try this approach and were there any problems with it?

**Comment by LorenzMeier** [comment]
The internal resistance of a LiPo battery varies wildly between models, ages and qualities. A quantitative test would be great, but its similar to double-integrating the accelerometer: Yes, it does work, but only when considering real-world offsets 8).

**Comment by tumbili** [comment]
I understand you point but have you actually tried it?

**Comment by LorenzMeier** [comment]
Yes, but not enough to say it's impossible. Just saying it's hard and needs consideration. The smart battery solo has is probably the better approach, but availability is an issue.

**Comment by DrTon** [comment]
I tried it. See "Battery" processor in FlightPlot. If you carefully tune "resistance" by log it works perfectly, but resistance changes, not only between models etc., but also with temperature, and very strongly! So after tuning for one flight - another flight with the same battery will give significantly different result. Of course, some average value can be used, but the this voltage correction can be off by 50% easily and will not give big improvement. The best choice is to look at discharged current IMO, voltage will never give stable and accurate results. BTW, all long range FPV pilots (when bad battery estimation == crash) use discharged current as primary indicator, and voltage just as health indicator of battery.

**Comment by LorenzMeier** [comment]
I've now added the consumed current via the BATTERY_STATUS MAVLink message. That's IMHO the best estimate we can provide and the same as the FPV pilots add.
I also verified that the voltage scaling is not done on the filtered voltage - so closing this one.
https://github.com/PX4/Firmware/commit/83fdb9931a0a9dd209566102bd873a274f4db6ed
