### ISSUE TITLE
is vehicle_visual_odometry the same as vehicle_vision_position? 

### ISSUE THREAD

**Issue by totomyl** [PX4/Firmware#12644]
Hello, 

I am using a motion capture system (mocap optitrack) to track the position of my drone indoors. When I am looking at the logs in flightplot I can only find a bunch of vehicle_visual_odometry fields in the list. Is this supposed to be the same thing as vehicle_vision_position? 

log here: [https://drive.google.com/open?id=1l4K-gR95Y18OR-Y5cK7DbhAv_2HAxofR](http://url)

**Comment by mhkabir** [comment]
Yes.
