### ISSUE TITLE
Pixhawk 2 reverted to 1.8.2

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#12656]
I had a pixhawk 2 with 1.9.2 flashed. I was doing some tests (sd card scripts, mavlink link, ...) and at some point QGC reported me something like "You have an old firmware 1.8.2, please move to recent stable release 1.9.2", and in the Firmware section it was written 1.8.2.
To be on the safe side I flashed again 1.9.2 then I had problems arming because it required accel calibration (but the sensor tab on QGC was green and the parameters for accel calibrations were there). After a new accel calibration it was fine.

The only "weird" things that I did were:

- Power on the Pixhawk once without SD card.
- When powering on with a battery I had a loose connection so it powered on and off quickly multiple times in short amount of time.

but I don't think that should impact the firmware.

**Comment by julianoes** [comment]
@tuloski have you found out more here?

It's physically not possible that it would just "revert" from 1.9.2 to 1.8.2 without someone reflashing it.
