### ISSUE TITLE
Rate / attitude controller tuning

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1268]
The fixed wing attitude controller tuning depends on getting the rate P, I and outer loop correct. As we have no rate control mode (yet), its however challenging to tune the rate controller correctly independently of the P / feedforward gain.

Paul found a way to link the two gains statically, which makes tuning much less error prone:
https://github.com/PX4/Firmware/blob/fw_att/src/lib/ecl/attitude_fw/ecl_pitch_controller.cpp#L72

While we will want to carefully understand the approach, its in many ways elegant - because at the end of the day the performance of a controller is the combined theoretical performance + the ability to tune it, and this fixed coupling prevents users from getting bad results because they try to change the pitch response with the wrong gain.

**Comment by thomasgubler** [comment]
We still want this eventually but it's a feature request and nobody picked it up. Closing.
