### ISSUE TITLE
Implement support to MAV_CMD commands #21 and #22

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#1281]
Hi,

Right now it's allowed to send, by `mavros` (here: https://github.com/vooon/mavros/blob/master/mavros/src/plugins/command.cpp#L269 and here: https://github.com/vooon/mavros/blob/master/mavros/scripts/mavcmd#L80), commands that use `MAV_CMD_NAV_LAND` and 	`MAV_CMD_NAV_TAKEOFF` to respectively land and take-off. Soon, it will also allow to land and take-off on the current GPS position (already working to get take-off/land in local position).

They are both working but always get `FCU: command unsupported: 21` or `FCU: command unsupported: 22`, since they are not supported in the firmware side.

I ask if someone can add support for this commands in the PX4 side or, at least, give some guidance on how to implement them. I'm not really used to the PX4 code structure/API.

Thanks in advance!

**Comment by TSC21** [comment]
@LorenzMeier I see that you have support for `MAV_CMD_NAV_TAKEOFF` in https://github.com/PX4/Firmware/blob/c62ae87c69963a4880c990c02000fd09e9b228f4/src/modules/mavlink/mavlink_mission.cpp, but where's the support for `MAV_CMD_NAV_LAND`. I see that you added https://github.com/PX4/Firmware/blob/c62ae87c69963a4880c990c02000fd09e9b228f4/src/modules/uORB/topics/mission.h#L59, but if the command is comming from a Mavlink msg, how can it be translated in this case?

**Comment by TSC21** [comment]
This is just to be aware of how I'm going to implement https://github.com/mavlink/mavlink/pull/401 in the loop.

**Comment by tinito** [comment]
Hi, I would like to implement the multicopter takeoff on firmware side for local navigation, but I have a couple of questions:
1) is it implemented for GPS navigation, or it is missing even in that case? If it is implemented, where is the code? I can't find it, the only references for SETPOINT_TYPE_TAKEOFF are in the fixed wings position controller code
2) which takeoff strategy would be the best? Now I'm trying to takeoff by sending velocity setpoints via mavros, and switching to position control when the copter reaches the given altitude. Anyway this is not reliable: the transition between the two modes is not smooth at all, and sometime the copter start drifting a lot and I have also experienced a couple of flips

**Comment by LorenzMeier** [comment]
We have this now.
