### ISSUE TITLE
Stopping/Slowing at each Waypoint

### ISSUE THREAD

**Issue by Dan-Moss** [PX4/Firmware#12845]
The aircraft slows to 1 m/s at each waypoint, even in a straight line. 
Firmware Version 1.9.2 on Black Cube

![image](https://user-images.githubusercontent.com/50102283/63950634-425e3c80-ca74-11e9-8af2-c3a0a48c356c.png)
![image](https://user-images.githubusercontent.com/50102283/63950697-66ba1900-ca74-11e9-89a2-75ed354fc19b.png)

Param Changes:
![image](https://user-images.githubusercontent.com/50102283/63950915-c9abb000-ca74-11e9-998b-3371c04c982e.png)
NAV_ACC_RAD = 15

I'd expect changing the Cruise and Cruise 90 would allow the aircraft to pass through the waypoints without slowing, similar to the acceptance radius but it seems to not be working?

https://discuss.px4.io/t/flight-throuh-waypoint-without-stopping-in-multirotor-mode/9883
https://discuss.px4.io/t/px4-missions-avoid-stopping-at-every-waypoint/10982
Others seem to have this issue

**Comment by mhkabir** [comment]
@bresch

**Comment by bresch** [comment]
Hi @Dan-Moss , this has been improved post 1.9.2 and is fixed by  #12505 
You can try the Master development branch, feedback is welcomed!

**Comment by Dan-Moss** [comment]
Thanks for replying @bresch , will build and test shortly (i guess there is no instant way to get px4_fmu-v3_default.px4) . I will close this issue for now then?

**Comment by mhkabir** [comment]
You can use QGC to flash the Developer build, which is autobuilt from master.

**Comment by Dan-Moss** [comment]
@mhkabir when reconnecting to update firmware i'm getting:
Found device: PX4 FMU V2
Error: Sync: Send Command: Invalid sync response: 0xfe 0x10
Upgrade cancelled

v3.5.4 Qground
Tried a variety of PC's, Laptops and USB Cables?

**Comment by mhkabir** [comment]
@dagar any clues?

**Comment by Dan-Moss** [comment]
using http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/activity/ i was able to get the build and it behaves correctly visually (Yay :D ) but the log shows:
![image](https://user-images.githubusercontent.com/50102283/64079747-185e8180-cce3-11e9-9016-d2198b7e1ab0.png)
