### ISSUE TITLE
VTOL thrust during backtransition

### ISSUE THREAD

**Issue by sfuhrer** [PX4/Firmware#12877]
While performing a transition from FW to MC in airspeed less mode, the thrust of the MC should linearly ramp up, starting when the transition is started. Instead, there is some little peak of MC throttle, then about 1s nothing, then a jump to about 30%:

![image](https://user-images.githubusercontent.com/26798987/64128148-55934400-cdb5-11e9-986a-cf2e208cf7d2.png)

**Comment by dlwalter** [comment]
sfuhrer - outstanding.  I was just running into this exact issue last week.

**Comment by sfuhrer** [comment]
@dlwalter do you still experience this issue? As far as I can say (don't have a lot of airspeed less flights) we don't with recent code.

**Comment by dlwalter** [comment]
I haven't seen it in actual flight - I only saw this on the bench and that was months ago.

**Comment by sfuhrer** [comment]
> I haven't seen it in actual flight - I only saw this on the bench and that was months ago.

Okay, same for me actually (at least the plot above was from a bench setup). I think it was related to the land detector detecting landing (which is fair, given that the vehicle is on the ground^^). 

Closing this then.
