### ISSUE TITLE
OFFBOARD mode docs

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#1288]
Hi,

I would like to get some info regarding the `OFFBOARD` mode, pointing out:

- [x] How to activate it in QGS and how to properly configure an RC switch to it (since http://pixhawk.org/users/system_modes/mode_switch_config doesn't make reference to OFFBOARD mode)
- [x] How it is implemented, i.e. if I switch to it (via RC switch or QGC), what's it's behaviour? Does it stay in **position hold and hovering** waiting for offboard commands?

Regarding `offboard2_externalsetpointmessages` and https://github.com/PX4/Firmware/pull/1151:
- [ ] Is it already testable and how can it be tested (a proper procedure to test it based on OFFBOARD behaviour currently implemented)
- [x] What kind of control can already be issued? pos, vel (linear and angular=attitude rate), accel,... ?

@LorenzMeier, @thomasgubler can you give some points here? If you give some guidelines regarding the above I wouldn't mind to do get some documentation ready to add to PX4 docs.
Thanks in advance!

**Comment by dreamkeep** [comment]
Hi @TSC21 ,
          what is the firmare version you used for px4 offboard test?

**Comment by TSC21** [comment]
@dreamkeep this thread is kinda hold but right now you can use current master to do offboard control.
I'm closing this since it's already documented in https://pixhawk.org/dev/offboard_control and https://pixhawk.org/dev/offboard_control/testing.
