### ISSUE TITLE
Rover SITL 

### ISSUE THREAD

**Issue by sarahToonsi** [PX4/Firmware#12893]
Hi everyone!

We were trying to test the rover simulator by sending RC override commands through mavros, however we could not succeed in doing that.
We are running:
roslaunch px4 mavros_posix_sitl.launch fcu_url:="udp://:14540@127.0.0.1:14557" gcs_url:="udp://:14540@127.0.0.1:14557" vehicle:=rover
We do not see the values we publish in:  /mavros/rc/out. I believe we are missing sth like configuring a specific parameter or sth else.

**Comment by julianoes** [comment]
@Jaeyoung-Lim you might know these mavros cli args.

**Comment by Jaeyoung-Lim** [comment]
@sarahToonsi I believe you need to look at `/mavros/rc/in` which shows the input of the RC controls
