### ISSUE TITLE
where to set vehicle parameters in jmavsim

### ISSUE THREAD

**Issue by Wonderful99668** [PX4/Firmware#12913]
Hi, since I am running sitl mode in jmavsim to test customized controller, and I want to set **system parameters such as vehicle mass, inertia etc.** to make simulation results close to the quad performance in the real world, which files or folders should I go? Thx

**Comment by julianoes** [comment]
jMAVSim is fairly simple in terms of physics. If you want better simulation fidelity I suggest to use Gazebo instead and look at how the models are defined there.

For the jMAVSim source, have a look here: https://github.com/PX4/jMAVSim/tree/master/src/me/drton/jmavsim.
