### ISSUE TITLE
VTOL: no control in FW after transition in ALT control

### ISSUE THREAD

**Issue by sfuhrer** [PX4/Firmware#12910]
reproducable in sitl: take off in alt, switch to FW. Not possible to change flight direction.

sitl log:
https://review.px4.io/plot_app?log=a60bffd8-f43f-4ca1-b59e-18d7dbe46bc9

flight log:
https://review.px4.io/plot_app?log=a14d1d71-bb8c-4438-a0bb-6ae8daed4190

**Comment by sfuhrer** [comment]
fyi @dagar @RomanBapst

**Comment by sfuhrer** [comment]
Throttle goes to 0 after transition to FW is complete (even though throttle stick is at 50%)
![image](https://user-images.githubusercontent.com/26798987/64378917-0e63b800-d02e-11e9-8187-97e68daccd72.png)

**Comment by dlwalter** [comment]
I run into a similar issue but only when I don't have a good GPS lock.  Fixed wing/altitude I cannot get throttle, roll, or pitch to respond unless I have X number of satellites.

**Comment by sfuhrer** [comment]
should be fixed when https://github.com/PX4/Firmware/pull/12920 is merged
