### ISSUE TITLE
Rounding error @ interdrone

### ISSUE THREAD

**Issue by Stifael** [PX4/Firmware#12922]
**Describe the bug**
Lost money during roulette.

**To Reproduce**
1. Go to Rio lobby at 4:30pm
2. Put 5 dollars on red
3. Wait
4. If you won, go back to step 2
5. You will observe that you just lost your money

**Expected behavior**
Become rich and famous

**Actual behavior**
Remain poor

**Additional context**
Happens @ interdrone

**Comment by Stifael** [comment]
Fyi @JonasVautherin

**Comment by dlwalter** [comment]
This is a feature.

**Comment by hamishwillee** [comment]
@Stifael we probably need to talk about "Waking up in Vegas", but for now this is a "Not Going to Fix"
