### ISSUE TITLE
pose_estimator_inav - get's flow validation just one

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#1294]
Hi,

I have detected that in the current implementation of `pose_estimator_inav`, I get a positive flow validation just once (the first one). Then, after losing that validation, I'm not able to get it again. I already tried to also add the proper brackets [here](https://github.com/PX4/Firmware/commit/9e099b42fadffe466547512aed2edf26dafed8d4), with no effect.

@DrTon can you please help to figure out why does inav just get's a flow `valid` once? My `quality` values are stable and above the threshold of validation. Just when it drops to zero (and then flow timewout) and then I get it again to good values, the system doesn't receive `valid` again.

By the way, I don't seem to get the sonar into the estimation properly. Please, if you may, check https://groups.google.com/forum/#!topic/px4users/3lxTOz_-GmE. The idea is to cancel baro and just use sonar+vision altitudes.

Thanks in advance!

**Comment by LorenzMeier** [comment]
Outdated.
