### ISSUE TITLE
FMUv4: CPU load > 95%

### ISSUE THREAD

**Issue by nicovanduijn** [PX4/Firmware#12974]
**Describe the bug**
With current master, I'm seeing > 96% CPU load on FMUv4 (pixracer), leading to log dropouts etc.

It seems that the load is high on boot, and then drops to around ~80% after a few seconds, and increases back to 95% when arming.

Tested with 270e12a4dfbe5ea24035483beabca90f3bd4b18d

I have not yet found the time to check other FMUs.

**To Reproduce**
Just flash a pixracer and arm it.

**Log File**
https://review.px4.io/plot_app?log=695a3060-e155-4622-b625-d5b870a50871

**Comment by dagar** [comment]
* mavlink (2 instances) ~= 17% cpu
       * Can you run `mavlink status streams` on a full operational system? I would guess we this could be trimmed.
       * https://github.com/PX4/Firmware/pull/12967 might save a small amount
  * wq:rate_ctrl (inner loop + output module) ~= 11%
       * This can be decreased slightly by setting `IMU_GYRO_RATEMAX` to 400 (your PWM_RATE)

**Comment by nicovanduijn** [comment]
Here's the output of `mavlink status streams`: (Sorry for the screenshot, QGC doesn't let me copy-paste)

![image](https://user-images.githubusercontent.com/14265408/65048363-43440900-d964-11e9-93e2-1b6968f8d7b2.png)
![image](https://user-images.githubusercontent.com/14265408/65048409-53f47f00-d964-11e9-9378-baa209017cdc.png)

**Comment by dagar** [comment]
![image (3)](https://user-images.githubusercontent.com/84712/65051599-61474480-d937-11e9-9fa9-87fe61b4c974.png)

**Comment by dagar** [comment]
Should be resolved, although there's plenty of room for further improvement.
