### ISSUE TITLE
nuttx sitl simulation

### ISSUE THREAD

**Issue by Wonderful99668** [PX4/Firmware#12981]
Since I am doing Pixhawk drone development, and there are different libraries in posix and nuttx. 
So I am asking, can sitl mode compile **Nuttx host** instead of **POSIX host**?
If so, how can I modify the cmake file?

**Comment by hamishwillee** [comment]
Closing, as this is a support question, best asked here: https://discuss.px4.io/

The simple answer is no, but why would you want to? SITL is for the simulator. If you want to simulate on hardware then see http://dev.px4.io/master/en/simulation/simulation-in-hardware.html
