### ISSUE TITLE
CM8JL65 switches uORB instance mid-air

### ISSUE THREAD

**Issue by nicovanduijn** [PX4/Firmware#12987]
**Describe the bug**
I've seen a bug where the distance sensor CM8JL65 switches the uORB topic it is publishing on, mid-air. This doesn't seem to bother EKF2 much, but it still doesn't sound like a great idea.

This was seen when testing a rebased version of https://github.com/PX4/Firmware/pull/12950, but I don't think the issue is related to the PR.

Would be interesting to know if anybody has seen similar behavior with other sensors, or if this is more likely a bug in the CM8JL65 driver.

**Screenshots**
![image](https://user-images.githubusercontent.com/14265408/65228612-1100eb80-dacb-11e9-93e1-cefa6e4880f9.png)

**Logs**
[Log file](https://review.px4.io/plot_app?log=c5c192d0-ae47-4bbc-a8de-2c887bddaf87)

**Comment by kamilritz** [comment]
I have experienced the same:

**Screenshot**
![Screenshot from 2019-09-19 11-30-32](https://user-images.githubusercontent.com/23532607/65232194-0cd7cc80-dad1-11e9-98f2-ff3fb0cc74fe.png)
 **Logs**
[Log file](https://review.px4.io/plot_app?log=bd994025-2312-4ee9-a7b2-f6ab2d65c6b8)

**Comment by dagar** [comment]
Could you try https://github.com/PX4/Firmware/pull/12993?

**Comment by dagar** [comment]
If I look in Flightplot or dump the data to csv I see a 2nd instance of distance_sensor, but it only publishes 2 data points. Is this a plotjuggler bug?

**Comment by nicovanduijn** [comment]
This is weird, if I use FlightPlot instead of plotjuggler, I see something slightly different.
PlotJuggler:
- 3 Instances of distance sensor: `distance_sensor`, `distance_sensor_0` and `distance_sensor_1`. With instance 1 holding just two samples as you described.
![image](https://user-images.githubusercontent.com/14265408/65486288-56932f00-dea4-11e9-87bd-9ec4963da4ac.png)

- In flightPlot it seems that the two instances `distance_sensor` and `distance_sensor_0` get fused. There is no `distance_sensor` anymore, but the weird instance with just two samples still exists:
![image](https://user-images.githubusercontent.com/14265408/65486411-a70a8c80-dea4-11e9-8832-97eeba57b990.png)

**Comment by dagar** [comment]
Can you try again with master?

**Comment by julianoes** [comment]
No answer given, closing.
