### ISSUE TITLE
Yawrate in Offboard Stopped Working

### ISSUE THREAD

**Issue by Pedro-Roque** [PX4/Firmware#12980]
**Describe the bug**
Yawrate commands sent through mavros/setpoint_raw/attitude as bodyrates in Z, with appropriate mask, stopped working. 

**To Reproduce**
1. Drone switched on
2. Publish a command on mavros/setpoint_raw/attitude with a yawrate and correct mask
3. The vehicle does not respond to yawrate commands

**Expected behavior**
The vehicle should rotate according to the bodyrate Z command

**Log Files and Screenshots**
Here goes a folder with 2 rosbags and the flight logs:
https://drive.google.com/open?id=1jufiucPZ2O7UPZHpCZfKG8gnDEj1XmIC

**Drone (please complete the following information):**
- Hover 1 Frame
- Pixhawk Radiolink, with v3 bootloader and v1.9.2 stable

**Additional context**
Recorded on a MoCap enabled arena at KTH Smart Mobility Lab.

**Comment by Pedro-Roque** [comment]
@Jaeyoung-Lim @mhkabir @MaEtUgR

**Comment by Pedro-Roque** [comment]
Update: in SITL, with IRIS, it checks out fine, that is, the system responds as expected! 

I am using the Generic Quadrotor X frame. Something I should be careful with? Maybe I should change the yaw gain?

**Comment by Pedro-Roque** [comment]
Update: Flying with master does not show the issue! Just successfully flied with mas flashed without any problems. Maybe there was something missing on the v1.9.2 stable...

Anyhow, I will follow @dagar 's suggestion and add a test for this next week - hopefully before next release.

**Comment by MaEtUgR** [comment]
> tried to test SITL, but get compass #0 uncalibrated immediately once I try to arm the vehicle.
Do a make clean if that happens with SITL, it's an incompatibility of the configuration that requires rebuilding after switching the branch across a certain point.

**Comment by Pedro-Roque** [comment]
Will do, next week though! :)

**Comment by Jaeyoung-Lim** [comment]
@Pedro-Roque Any updates?

**Comment by Pedro-Roque** [comment]
@Jaeyoung-Lim not yet but not forgotten. Just need to finish some stuff on my research and then will look into this.

**Comment by julianoes** [comment]
Bump :smile:

**Comment by Pedro-Roque** [comment]
Not forgotten @julianoes ! I'm just trying to dodge deadlines these days, but I'll come back to this as soon as I can

**Comment by Pedro-Roque** [comment]
Issue fixed and tests added. Closing
