### ISSUE TITLE
Rover - Aion Robotics R1 UGV issues with executing position setpoints 

### ISSUE THREAD

**Issue by sarahToonsi** [PX4/Firmware#12990]
Hi, 
I was trying to send position waypoints to a differential steering vehicle with the PX4 frame set us : 
  Aion Robotics R1 UGV 
I am working with a Pixhawk 2 cube and publishing waypoints through mavros to the topic: mavros/setpoint_position/local
My vehicle starts to move but it never steers even when the waypoints is to its right or left. It keeps going forward or backward with full throttle and I don't have a clear description to its random movement. I'm working in the lab with a Mocap system and my position settings are fine. 
The parameters that  I changed in Qground control are only for the EKF to use vision instead of GPS and for setting up the companion computer.

**Comment by julianoes** [comment]
Could you please upload a log to logs.px4.io and link it here? Thanks.

**Comment by sarahToonsi** [comment]
>  logs.px4.io

https://logs.px4.io/plot_app?log=04064ce8-7e43-4e3d-af40-d6c098599da2

**Comment by julianoes** [comment]
FYI @ItsTimmy @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@sarahToonsi The rover position controller requires you to have a GPS fix.

**Comment by LorenzMeier** [comment]
Original issue captures this already. This is not a real issue but rather a requirement.
