### ISSUE TITLE
FW 1.9.2 can't find ms5525 sensor

### ISSUE THREAD

**Issue by minhnguyne** [PX4/Firmware#13013]
Hello,
I'm using QGroundControl (FW 1.9.2) to configure mRo Next-Gen MS5525 Airspeed sensor with the Pixracer r15, but it is giving me this error. 

![image](https://user-images.githubusercontent.com/51135337/65467932-489fc880-de28-11e9-8847-528056a06216.png)

I have already gone through this similar thread, but the same issue still occurs
https://github.com/PX4/Firmware/issues/12375
Any help would be greatly appreciated, 
Thank you!

**Comment by mcsauder** [comment]
Hi @minhnguyne , I'm on the road this week, but I'll be able to test with a pixracer this weekend and get back to you with anything I learn.  If you figure anything out in the meantime let me know!

**Comment by minhnguyne** [comment]
Okay, thank you!

**Comment by minhnguyne** [comment]
It works now. I've rewired the MS5525 wires back into the Pixracer. I think the issue was that the SCL and SDA wires were swapped and/or unsecured. Thanks for your quick reply!
