### ISSUE TITLE
If executing "make px4fmu-v5_default" would cover the modification of the code

### ISSUE THREAD

**Issue by zmitchn** [PX4/Firmware#13011]
I changed some codes in commander.cpp. And executing "make px4fmu-v5_default" will execute "git clone", thus, will this execution covers my modification.

And if not, what did git clone to the local repo?

**Comment by julianoes** [comment]
Sorry, that doesn't make any sense. `make px4fmu-v5_default` certainly won't overwrite your changes. You will have to add exact steps how we can reproduce your problem, otherwise we'll have to close this.
