### ISSUE TITLE
RDDRONE-FMUK66 Parameters not being saved on some units

### ISSUE THREAD

**Issue by igalloway** [PX4/Firmware#13019]
**Describe the bug**
Pameters, settings, calibration lost after power cycle

**To Reproduce**
Reported from HoverGames Participant(s) - validation in progress

https://community.nxp.com/thread/511481
https://www.hackster.io/contests/hovergames/discussion/posts/5394#challengeNav

Problems saving parameters to FMUK66. I am able to load bootloader and firmware, once I select my air frame and reboot, config all sensors and reboot once more all settings are gone. This is my first venture into PX4 and would like to know if there is just something I am missing. 

I have tried multiple firmware versions as well as different versions of QGroundControl. HoverGames also provided a preloaded VM with required utilities and that is also providing the same results.

I have also tried erasing entire FMU via the debugger module and flashing both bootloader and firmware this way.

The drone will work fine until it is rebooted, which I then have to start like it is a new FMU. Wondering if I may have a bad unit. 

**Drone (please complete the following information):**
- HoverGames KIT-HGDRONEK66 with RDDRONE-FMUK66

**Additional context**
Validating this issue with new boards. We have had 3 reports so far. Will report back here,but wanted to note it in case it turns out to be software related.

**Comment by davids5** [comment]
@igalloway Tested on master with REV c HW.  Params are AOK.

I can we do a postmortem on the device that is failing if you send it to me.

**Comment by davids5** [comment]
@igalloway Oh by the way 75b2053243cb569c1347686fd56e33459e095efb removed uavcan by accident. @dagar will restore it.

**Comment by igalloway** [comment]
Comment : @igalloway I'm on board #2 with the same issue. Were you able to find out if it's a manufacturing issue, and if so, can you provide any details? I'm hesitant to request another replacement before we get this figured out, especially if it's something that I can correct on my end. I get similar results as @physicsman on both boards. An SD card with dataman, a mission_log folder, and a log folder.

**Comment by igalloway** [comment]
I'll try to get one of the failing board asap

**Comment by igalloway** [comment]
Note: Confirmation by a 3rd party today that earlier code on the same board  **does not** fix the issue.

**Comment by davids5** [comment]
That would indicate HW as does my test on Rev C. master 9/25 and QGC. (Prior I was just testing from command line. `set param xxxx yyyy'  and reboot check that is was still set.) Looking forward to receiving failing HW.

**Comment by igalloway** [comment]
Thanks @davids5 for the investigation. It was determined that indeed this is a result of bad FRAM chips. We will investigate the source. 
The chips in question are marked correctly, but report back as a larger 64K part instead of the expected 16K.  This can be confirmed with `mtd erase` command. 
David created a temporary branch of code that also reported the JEDEC ID of the chip.
Possible causes:
 - bad chip/wear/old lot/ not passing qual/ not programmed internal mask correctly?
- grey market part by Contract manufacturer.

All current inventory will be tested. Our CM will be informed and an additional test at their facility will be implemented.
We will attempt to contact the manufacturer of this part for further diagnosis. This FRAM was not an NXP part.
