### ISSUE TITLE
Use of Offboard API in SITL and HITL

### ISSUE THREAD

**Issue by 02yogesh16** [PX4/Firmware#13029]
Hello all, 

I am a newbie to this field and is stuck in SITL and HITL using Gazebo. My question is what is the exact function of the OffBoard API like MAVROS/MAVSDK being used by PX4 in SITL/HITL?
Also are these API needed for real world flying of the Quadrotor?  

For reference please see this High level diagram for SITL https://dev.px4.io/master/en/simulation/#simulator-mavlink-api 
https://dev.px4.io/master/en/simulation/ros_interface.html

**Comment by hamishwillee** [comment]
This is an bug or feature tracker, so not the right place for support queries. Please ask again in the discussion boards where we will be happy to respond: https://discuss.px4.io/
