### ISSUE TITLE
VTOL mission can't be continued after QuadChute

### ISSUE THREAD

**Issue by sfuhrer** [PX4/Firmware#13035]
When a QuadChute is triggered, the vehicle immediately starts with a RTL. The mission can't be continued (also not when first switched into position control mode). 

Only Change Altitude action available:
![image](https://user-images.githubusercontent.com/26798987/65752663-8729d180-e10d-11e9-8c0a-e04c5bc2ca1f.png)

Wouldn't it be better if after a Quadchute, the vehicle stays in hold mode (for a parameter-defined amount of time), before starting a RTL? And that the operator always has the option to continue the mission.

Further, I noticed different RC override behavior: In return mode after a QuadChute, RC override with moving the sticks works, whereas during a normal RTL (e.g. triggered by the RTL slider) one has to switch the flight mode (e.g. into position mode) to be able to take over. Is that so by design?

**Comment by LorenzMeier** [comment]
On the RTL question: That is by design. Otherwise users abort RTL as the result of any failsafe action my fiddling around with the sticks without noticing. That way a low battery RTL gets aborted by an inexperienced user and they crash with empty batteries.

**Comment by julianoes** [comment]
> That way a low battery RTL gets aborted by an inexperienced user and they crash with empty batteries.

Before crashing we still switch to landing though, right?

**Comment by moreba1** [comment]
Vtol plane Stall cause QuadChute be acticvated . so i will to transition to FW again in RTL mode ,but i can not . in my opinion changing mode and transitions must be allowed in all conditions.
