### ISSUE TITLE
CUAV V5+_Accel inconsistent

### ISSUE THREAD

**Issue by Tony3dr** [PX4/Firmware#13083]
**Describe the bug**
We are getting this constant error message of Accel inconsistent error with the CUAV V5+. We did all the calibrations, then try to arm again and again mark Accel inconsistent. We did a complete reset in the flight controller did the calibrations and the same issue. 

**Log Files and Screenshots**
<img width="960" alt="CUAV+ Accels inconsistent" src="https://user-images.githubusercontent.com/39415493/66089260-64dfeb80-e533-11e9-93a4-3610550da5ba.png">

Log: 
https://review.px4.io/plot_app?log=37067a71-b746-4f44-8013-8c4fe57b3bfa

Last working flight log: 
https://review.px4.io/plot_app?log=66332487-04b5-47f5-b1a3-a241e23a4dd7  

**Drone (please complete the following information):**
- FC- CUAV V5+
- Frame- DJI f450
- GPS- NEO V2
![CUAV close pic](https://user-images.githubusercontent.com/39415493/66089507-7970b380-e534-11e9-8a08-7fc280ed0082.jpg)

**Additional context**
Today we tried the Master branch but I had already tried it in Stable & a PR and still the same error, I also changed the GPS from the working unit Nano CUAV but it remains the same.
@dagar what could be the issue?

**Comment by LorenzMeier** [comment]
@MaEtUgR This is a real issue that we should solve with priority.

**Comment by dagar** [comment]
One minor thing to consider here is if we can now afford to log all sensor data by default at a low rate. Currently these issues are often difficult or impossible to debug in default logs.

**Comment by Zainpeng** [comment]
@Tony3dr Is this a mistake in the constant use of flight control? And then it doesn't disappear?

**Comment by Tony3dr** [comment]
> @Tony3dr Is this a mistake in the constant use of flight control? And then it doesn't disappear?
@Zainpeng I would not say constant use since the error message does not let us fly. Since the issue started showing we are not able to use that flight controller.

**Comment by dagar** [comment]
This appears to be a real issue with the icm20689 on the CUAV v5+ (and nano).

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/15004.
