### ISSUE TITLE
QGC _altitude issues_CUAV Nano

### ISSUE THREAD

**Issue by Tony3dr** [PX4/Firmware#13148]
**Describe the bug**
We have noticed the altitude issues on the CUAV Nano this issue was noted on QGC altitude reading. (and relative altitude) not being displayed correctly. 

**To Reproduce**
1. Drone switched on
2. Uploaded mission
3. Takeoff, Position Mode 
4. Switch from Position mode to Mission mode 
4. See altitude reading on QGC

**Log Files and Screenshots**
Log Nano V5:   
https://review.px4.io/plot_app?log=e3d7bc0a-891d-4ecf-8ebd-01afb7630ab7
![nano V5](https://user-images.githubusercontent.com/39415493/66510657-4d03ec80-ea8a-11e9-8544-4bf23e4d8059.jpg)
![nano V5](https://user-images.githubusercontent.com/39415493/66510679-5725eb00-ea8a-11e9-84a6-876ba6643988.jpg)

**Drone (please complete the following information):**
FC- CUAV Nano 
Frame: F450 frame
GPS- NEO V2
![f450_cuav5_nano_complete](https://user-images.githubusercontent.com/39415493/66511077-1e3a4600-ea8b-11e9-90dd-80041808b8cc.jpg)

**Additional context**
The vehicle flight performance is well but the altitude is off by approximately 10 to 13 meters.@dagar what could be the issue?

**Comment by MaEtUgR** [comment]
I have multiple CUAV nano board here so I might be able to reproduce quickly.

**Comment by Tony3dr** [comment]
> I have multiple CUAV V5 nano board here so I might be able to reproduce quickly.
@MaEtUgR were you able to reproduce the issue? Thanks

**Comment by cuhome** [comment]
I tested it, but I didn't find the height of the error.
Logs:
Https://logs.px4.io/plot_app?log=19572b33-284d-457d-8028-a792349e8641

**Comment by cuhome** [comment]
![微信图片_20191111165225](https://user-images.githubusercontent.com/31507501/68574878-dcdff080-04a5-11ea-8874-b4027e95bb65.jpg)
![微信图片_20191111165217](https://user-images.githubusercontent.com/31507501/68574885-dfdae100-04a5-11ea-9292-a1399afa1755.jpg)

**Comment by MaEtUgR** [comment]
I have a similar problem on a Pixhawk 4 mini setup. It was flying perfectly before and without any change at some point it began reading strange diverging altitude even when stationary on the desk and with freshly calibrated accelerometer.

I made a log from boot today with latest master when rebooting just after calibration: https://logs.px4.io/plot_app?log=d3d0d46b-b850-4225-97a6-812aee45ff56

**Comment by MaEtUgR** [comment]
I quickly checked flashing 1.9.0 and I have the same problem. Let's analyze the log.

**Comment by MaEtUgR** [comment]
Logs for comparison from the testing team's setup (thanks @Tony3dr !):
https://review.px4.io/plot_app?log=d8b837a4-1881-4895-b9b1-1df9008b5237
https://review.px4.io/plot_app?log=a5f8141a-6991-4217-8520-426b533bfff2

**Comment by MaEtUgR** [comment]
Thanks to @kamilritz for looking into the logs. He found that the malicious drifting altitude in the tests on the bench come directly from the barometer... I wonder why certain boards have this a lot more than others. We should test if it's temperature dependent or see if the data sheet mentions some compensation.

**Comment by MaEtUgR** [comment]
Is this problem still present? I'd assume this was fixed in the meantime because there were various related issues addressed e.g. accelerometer bias drifting https://github.com/PX4/ecl/pull/749, fusing height multiple times https://github.com/PX4/ecl/pull/767 and a lot more that I don't know of. The platform Holybro QAV250 with pixhawk 4 mini that I had problems with doesn't show them anymore. Please reopen if you see it again.

**Comment by Tony3dr** [comment]
> Is this problem still present?
> 
> I'd assume this was fixed in the meantime because there were various related issues addressed e.g. accelerometer bias drifting [PX4/ecl#749](https://github.com/PX4/ecl/pull/749), fusing height multiple times [PX4/ecl#767](https://github.com/PX4/ecl/pull/767) and a lot more that I don't know of. The platform Holybro QAV250 with pixhawk 4 mini that I had problems with doesn't show them anymore.
> 
> Please reopen if you see it again.

@MaEtUgR the issue can be closed, we haven't seen this issue anymore. Thanks for all the helop!
