### ISSUE TITLE
[fixedwing]throttle_ramp_time should to be configurable

### ISSUE THREAD

**Issue by jinchengde** [PX4/Firmware#13146]
throttle_ramp_time is hard code as 2 seconds in
https://github.com/PX4/Firmware/blob/master/src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp#L61

and if we used that for fixed wing runway takeoff, it is not safe in ground if we have so quickly accelerate, the plane may turned over because the reverse twist from propeller

of course, that maybe no problem for other type of takeoff like catapult

so, I suggest throttle_ramp_time could be take as parameter for configure

**Comment by julianoes** [comment]
@jinchengde feel free to propose a pull request for this.

**Comment by jinchengde** [comment]
@julianoes https://github.com/PX4/Firmware/pull/13154

**Comment by jinchengde** [comment]
done
