### ISSUE TITLE
Feature Request: Flip Mode

### ISSUE THREAD

**Issue by Seeelefant** [PX4/Firmware#13155]
Within PX4 I am missing a "Flip Mode" like in ArduCopter:
"...the Vehicle will flip on its roll or pitch axis depending upon the pilot’s roll and pitch stick position. Vehicle will rise for 1 second and then rapidly flip. The vehicle will not flip again until the switch is brought low and back to high."

**Comment by hamishwillee** [comment]
This is an open source project, which means that a mode like this will be developed if some member of the community sees it as valuable. If you want to create a PR to deliver the feature I'm sure we'd accept it :-)

**Comment by mhkabir** [comment]
As Hamish said, we'll happily accept this feature if you decide to develop it and send a PR. Closing this for now.

**Comment by Seeelefant** [comment]
Thank you, I am not if I have time for such a project. Anybody willing to join?
