### ISSUE TITLE
VISION_POSITION_ESTIMATE structure not congruent 

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#1315]
In https://github.com/PX4/Firmware/blob/master/src/modules/uORB/topics/vision_position_estimate.h, there's a type of structure that I don't think it's right. According to https://pixhawk.ethz.ch/mavlink/#VISION_POSITION_ESTIMATE, it should have x,y,z and roll,pitch,yaw fields (which is also what is in the `vehicle_vicon_position.h`).

Also, according to this, also a `modules/uORB/topics/vision_speed_estimate.h` can be created to receive the speed estimates.

Note: I found this issue when writing code for sdlog2 so to get the vision estimates logged also.

**Comment by LorenzMeier** [comment]
Closing since fixed / outdated.

**Comment by TSC21** [comment]
@LorenzMeier thanks. A fix was added in https://github.com/PX4/Firmware/pull/2096. Lacks testing though.
