### ISSUE TITLE
Derivative gain for fixedwing attitude control

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#13168]
Hi

There is need for derivative gain for fixedwing attitude control for tailess planes .

https://github.com/PX4/Firmware/issues/12886

**Comment by julianoes** [comment]
Please create an issue with some background information, some suggestions how something could be done, what sort of problem you're trying to solve, etc.. With just this one sentence I don't know what to do with this.

And "there is need" doesn't mean anything will just create that for you, so if you need it soon, it's best to create a pull request. Thanks.

**Comment by RomanBapst** [comment]
@moreba1 I think I understand what you are trying to say. But you should show some evidence first, e.g. plot for rate vs rate setpoints form this vehicle. Maybe we can suggest some changes in tuning parameters.
