### ISSUE TITLE
Time UTC usec goes backward

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#13177]
Analyzing a log I noticed that the field vehicle_gps_position_0.time_utc_usec goes backward of around 1 second, causing a "misalignment" of 2 seconds.

I have no idea if that is due to PX4 logger, to uOrb delay or to GPS data being erroneously calculated. I'm pretty sure it's not the GPS itself sending wrong data.

Any idea?

I can't share the log, but below is the image of the data on FlightPlot.

<img width="960" alt="UTC_delay" src="https://user-images.githubusercontent.com/6544139/66736195-d3dd0e80-ee68-11e9-9ef7-a81506fd46de.png">

**Comment by julianoes** [comment]
I think this expected. GPS is estimating position and UTC time. It makes sense that not just the position but also the time will get updated as a GPS signal improves.

**Comment by tuloski** [comment]
It might be, but a 2s error is HUGE for GPS, so I'm not sure that is the cause.
2s error has the same order of magnitude of 1Km positioning error.
