### ISSUE TITLE
Attitude Quaternion Stream with invalid quaternion

### ISSUE THREAD

**Issue by mrivi** [PX4/Firmware#13182]
Since PR #12596 , the Firmware sends the mavlink message ATTITUDE_QUATERNION with an invalid (0, 0, 0, 0) quaternion until the ekf2 starts to publish the `vehicle_attitude`. 
The mavlink message is published bacause the condition is that either `vehicle_angular_velocity`  or `vehicle_attitude` is updated and `vehicle_angular_velocity`  is always ready before the attitude. 

https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_messages.cpp#L1289

For ROS user, this leads to a bunch of error messages on start up
``` bash 
[ERROR] [1569826119.454300726, 0.856000000]: Ignoring transform for child_frame_id "fcu" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 0.000000 0.000000 0.000000)
```

I have tried to publish an invalid quaternion (NAN, NAN, NAN, NAN) but I get the same error message because ROS requires the quaternion to be valid and this value is accessed multiple times across multiple MAVROS plugins. 

I assume the OR condition in the update decision was a conscious choice. How can we prevent to send out invalid quaternions?

**Comment by dagar** [comment]
Sending the rate data before attitude is available (or if it stops) was a minor benefit we can live without. https://github.com/PX4/Firmware/pull/13184
