### ISSUE TITLE
Rover position control overrides offboard ActuatorControl

### ISSUE THREAD

**Issue by jbeyerstedt** [PX4/Firmware#13192]
Setting actuator control values with MAVSDK does not affect the actual PWM outputs with a rover. When using QGC to monitor the raw PWM values, the PWM value is only set correctly in one MAVLink message, but mostly it's 0 (PWM value of 1500 us).

However, when the `rover_pos_control` module ist stopped, the offboard control affects the PWM values as expected.

(Setting Attitude set points (with [this MAVSDK-Python example](https://github.com/mavlink/MAVSDK-Python/blob/master/examples/offboard_attitude.py)) wasn't working as expected either. But I haven't taken a further look at that problem.)

**Comment by Jaeyoung-Lim** [comment]
@jbeyerstedt I think this is because the rover position control does not handle the case where the actuator control is enabled.

**Comment by jbeyerstedt** [comment]
@Jaeyoung-Lim Thats also what I got from the rover call.

I will try to add support for offboard actuator_controls this week. Can you assign me?

I'll open another issue for attitude set points, because that will be a bigger issue. We might also need some help/ hints there.
