### ISSUE TITLE
Steps for new aircraft creation 

### ISSUE THREAD

**Issue by gitgkk** [PX4/Firmware#13213]
Dear Ladies & Gentlemen,
I'm designing a new VTOL aircraft. It has 8 VTOL motors and one tail motor as pusher.  
I have seen pixhawk airframe references and defined my own file but don't know how to go beyond that. I found that configuration needs to be modified in the code.
What  steps are to be followed to define one using pixhawk firmware. Are there scripts which can do that job for me? What system of units does pixhawk follow SI or Metric (for distance, angle etc.)?

Thanks for your responses. 
Kashyap

**Comment by hamishwillee** [comment]
See: http://dev.px4.io/master/en/airframes/adding_a_new_frame.html

Closing, as discussion is more appropriate to https://discuss.px4.io/
