### ISSUE TITLE
[MC land detector] In the hold mode, the firmware 1.9.2 and 1.10 will have a throttle equal to 0(MC)

### ISSUE THREAD

**Issue by tonight123** [PX4/Firmware#13229]
In the hold mode, the firmware 1.9.2 and 1.10 will have a throttle equal to 0, which changes quickly, resulting in a high degree of control. Highly controlled in firmware 1.8.2
1，firmware 1.9.2
![bokeh_plot(1)](https://user-images.githubusercontent.com/3964252/67097424-a8ea1600-f1ec-11e9-9e58-ad5fb3abea2e.png)
![bokeh_plot](https://user-images.githubusercontent.com/3964252/67097425-a8ea1600-f1ec-11e9-9e1b-8020cf200006.png)
![bokeh_plot3](https://user-images.githubusercontent.com/3964252/67097427-a982ac80-f1ec-11e9-8ec3-df5bfda94d19.png)
2,firmware 1.10

![bokeh_plot](https://user-images.githubusercontent.com/3964252/67097483-c9b26b80-f1ec-11e9-8558-1efd9aad2dba.png)
3,firmware 1.8.2
![bokeh_plot](https://user-images.githubusercontent.com/3964252/67097495-d0d97980-f1ec-11e9-8b07-8779dac09a63.png)

**Comment by julianoes** [comment]
Thanks for the issue. Can you please attache a link to the logfile? Or please share the "Velocity" plot.

**Comment by MaEtUgR** [comment]
@tonight123 It looks from the pictures (a link to the log would give more insights) that your vehicle is well powered and can hover with ~26% thrust. Try adjusting the parameter `MPC_THR_HOVER` to `0.26` and it will likely solve the problem.

Explanation: The vehicle is by default assuming you need ~50% throttle to hover. If you give a lot less thrust but it's not falling it assumes you have contact with the ground and cuts the thrust to land but if you're in air it detects to be suddenly falling and catches again to not crash.

Future solutions for that reoccurring problem:
1. Estimate the hover thrust on the fly such that the user does not have to adjust. Here's the first draft for that: https://github.com/Auterion/Flight_Control_Prototyping_Scripts/pull/3
2. Improve the land detector to directly track the tracking of measured acceleration to thrust such that it's more robust on highly different vehicles.

**Comment by tonight123** [comment]
@MaEtUgR in firmware v1.9.0 like PX4 V1.9.0 and Later: Attitude Control and Takeoff Issues #12484
takeoff： mpc_tko_ramp_t =0,it's going to take off quickly.
Starting counterclockwise after take-off, probably because rate i is too big, i is currently 0.2
