### ISSUE TITLE
Rover: Add support for attitude set points (for offboard control)

### ISSUE THREAD

**Issue by jbeyerstedt** [PX4/Firmware#13239]
The movement control loops (currently just the `rover_pos_control` module) only support position setpoints, but no attitude setpoints. Therefore the `rover_pos_control` module has to be extended or a new module has to be created.
But first, support for actuator_control setpoints should be fixed (#13192).

**To be discussed**: What values should be controlled by an attitude control loop?
Yaw and velocity or just yaw and throttle/ thrust?
The second option would be easier to implement and in line with the MAVSDK API documentation of the [offboard mode attitude setpoints](https://mavsdk.mavlink.io/develop/en/api_reference/structmavsdk_1_1_offboard_1_1_attitude.html).
If we want to control the velocity, some kind of positioning system or odometry (e.g. wheel encoders #12351) are needed. But that's more suitable for a velocity setpoint (which is part of position control).

As far as I know, there a two control modes in offboard:
- attitude control
- position or velocity control (in local or global NED coordinates)

Manual control (via offboard actuator_controls or RC remote) must also be considered (see #13192), but that is actually no control loop at a rover.

**Comment by Jaeyoung-Lim** [comment]
@jbeyerstedt To make it more consistent with the multirotor attitude setpoints, I believe the following setpoints would make sense.

1. throttle/thrust with yaw setpoints.
2. throttle/thrust with yaw rate setpoints. 

You can look at how velocity tracking is being used in #13225 for supporting velocity setpoints for rover.

**Comment by jbeyerstedt** [comment]
I agree with @Jaeyoung-Lim about the different control modes, that should be implemented.

> throttle/thrust with yaw setpoints.

Attitude setpoints have been added in #13323 and will be fixed by #13427. 

Is there a special reason, why the attitude setpoints only allow forward driving? Because for our rover we also need to drive backwards.

**Comment by Jaeyoung-Lim** [comment]
@jbeyerstedt We are not handling the case when the rover is driving backwards, in that case we need to reverse the steering angle so it takes the shortest route and not the other way around

**Comment by jbeyerstedt** [comment]
I just added driving backwards for attitude control. See #13429

**Comment by Jaeyoung-Lim** [comment]
Closing as this is now supported as per #13429
