### ISSUE TITLE
Can't load node in gazebo

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#13245]
I add a velodyne_simulator in iris_base.xacro.
code like this
`  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" hz="10" samples="440" gpu="${gpu}">
    <origin xyz="0 0 0.4" rpy="0 0 0" />
  </VLP-16>`
and during the build.There is a error "[FATAL] [1571729499.142875683]: A ROS node for Gazebo has not been initialized, unable to load plugin. Load the Gazebo system plugin 'libgazebo_ros_api_plugin.so' in the gazebo_ros package)
"
and gazebo is running.
![图片](https://user-images.githubusercontent.com/40378941/67277592-b90a3a00-f4f9-11e9-91a5-f4ed4b82046d.png)
Rostopic of velodyne don't publish.Please help me solve that.Thanks

**Comment by Jaeyoung-Lim** [comment]
@roseyangyu You might need to translate the description file to sdf

**Comment by roseyangyu** [comment]
> @roseyangyu You might need to translate the description file to sdf

I have run "roslaunch px4 posix_sitl.launch" follow [this](https://dev.px4.io/v1.9.0/zh/simulation/ros_interface.html).I solve that
