### ISSUE TITLE
Throttle issue

### ISSUE THREAD

**Issue by pifordi** [PX4/Firmware#13252]
deleted topic

**Comment by bresch** [comment]
FYI @sfuhrer  @RomanBapst

**Comment by semihyildirim** [comment]
If autopilot try to connect altitude so give maximum pitch after transition, because of minimum pitch commanded throttle must be lowest value. According to this idea, minimum throttle(%40) may be overshoot for achieving these strategy. 

In previous flight, transition airspeed is lower than this flight so the plane was more slow. The autopilot could be achieve in lower speeds but in this flight the plane had more speed because of higher transition airspeed.

**Comment by semihyildirim** [comment]
The following line of codes could be affect these behaviour? 

https://github.com/PX4/Firmware/blob/26364d44c91672d101349ff5825358017f7db3df/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

Line number between: 1300- 1316

**Comment by RomanBapst** [comment]
@semihyildirim Thanks for reporting this!
I need to investigate why the throttle is kept at minimum for such a long time after transition. I would expect it to go to cruise throttle, not min throttle.
Anyway, I think there is something else not quite right with this setup.
After the transition the aircraft pitches down but the setpoint commands pitch up. It's weird that even when airspeed increases to high values that there is no pitch response at all. 
Your trim airspeed is set to 19m/s but even at 26 m/s I see no response from the pitch loop, even though the controller demands pitch up.
Either your vehicle is very nose heavy or your control surfaces are very ineffective.

I will follow up on the throttle issue, can you follow up on the no pitch response issue?

**Comment by RomanBapst** [comment]
![image](https://user-images.githubusercontent.com/7610489/67550451-d06a4280-f706-11e9-8dbb-3c78650a40a6.png)

**Comment by semihyildirim** [comment]
Look at the ground speed and see highwr speeds.

**Comment by semihyildirim** [comment]
I want to learn why min pitch down and min throttle commanded by pixhawk, you say that why the plane would not able to pitch up? 
I think the plane want to correct altitude error but do it agressively. Is it true or not?

**Comment by RomanBapst** [comment]
@semihyildirim Ground speed does not matter, airspeed is important for your plane to fly.
Again, form what I see in the logs the controller demands pitch up, check it!
Why is the plane not able to follow the setpoint? Maybe your pitch controller is not tuned properly.

**Comment by semihyildirim** [comment]
Sorry, issue closed wrongly.

**Comment by semihyildirim** [comment]
In addition, the pitch controller affects pitch down and pitch up movements. The autopilot give pitch down command within 0sn but it give pitch up command within 3-4sn. Why? If I increase pitch controller, pitch down commaded more agressively?  Is it right?
