### ISSUE TITLE
IMU Low pass filtering

### ISSUE THREAD

**Issue by Dapingguo001** [PX4/Firmware#13251]
Why not use filtered data in downsampling？If the vibration of the aircraft is large, and the UAV has buffeting with the original data, can the filtered data be used for downsampling?

![图片](https://user-images.githubusercontent.com/30037811/67375509-4fe7fc80-f5b5-11e9-824f-f55190e83405.png)

**Comment by bresch** [comment]
Hi @Dapingguo001 for the ekf it's better to have unfiltered data as it can deal with noise really well, better than with the frequency-dependant delay (lag) that the Butterworth filter would add. Furthermore, down-sampling the data is already low-passing the data (the average filter is a low-pass filter).
