### ISSUE TITLE
Failure to build PX4 with cm8jl65 driver

### ISSUE THREAD

**Issue by jordancoult** [PX4/Firmware#13250]
**Bug Description**
When trying to build for px4_fmu-v2_default with the cm8jl65 driver added to default.cmake, I get an error which prevents the build from finishing (see screenshots). Everything builds fine when I leave default.cmake as-is.

**To Reproduce**
1. Clone master
2. Add the line `distance_sensor/cm8jl65` to the drivers section of /Firmware/boards/px4/fmu-v2/default.cmake
3. Navigate to /Firmware
4. Run `make px4_fmu-v2_default`

**Expected Behavior**
PX4 should build successfully unless there is a flash overflow.

**Additional Info**
I set up the development environment by following the official instructions on a clean Ubuntu 18.04 VM. 

**Full Console Output**
![Capture1](https://user-images.githubusercontent.com/33331023/67355444-1f985380-f50c-11e9-932a-51f217b9bdcf.PNG)
![Capture2](https://user-images.githubusercontent.com/33331023/67355494-35a61400-f50c-11e9-9030-85519af80f74.PNG)

**Comment by mcsauder** [comment]
Hi @jordancoult , I was able to reproduce your issue, thanks for reporting it!  Let me know if PR #13258 solves your issue!

**Comment by jordancoult** [comment]
Hi @mcsauder, thanks for the help. I tried your source branch and the build threw a different error: 

"Error: PX4 version too low, expected at least v1.9.0
Check the git tag (current tag: 'v1.7.3')"

It seems that your branch has outdated tags. To fix this, I cloned fresh from master and applied your changes and the build was successful.

**Comment by mcsauder** [comment]
Hi @jordancoult , I have fetched `PX4/Firmware` 's  upstream tags and pushed them to my fork.  You should no longer see the tag issue.  Thanks for validating the patch!

**Comment by mcsauder** [comment]
Hi @jordancoult , I have fetched `PX4/Firmware` 's  upstream tags and pushed them to my fork.  You should no longer see the tag issue.  Thanks for validating the patch!

**Comment by mcsauder** [comment]
Closing. Fixed with #13258!
