### ISSUE TITLE
LL40LS driver cause crash

### ISSUE THREAD

**Issue by hyonlim** [PX4/Firmware#13280]
**Describe the bug**
With current master & Pixhawk4 combo, when LL40LS app started command line interface stopped. If LL40LS app is set to started during boot, nsh command is not working.

**To Reproduce**
1. Flash master
2. Connect LL40LS to i2c
3. Set SENS_EN_LL40LS Enabled
4. See console output (via console cable)

**Expected behavior**
When type a command on nsh, command should work.

**Log Files and Screenshots**
Attached.
![Screenshot from 2019-10-27 14-21-24](https://user-images.githubusercontent.com/6064011/67630114-972c0100-f8c5-11e9-9c43-ff4a776d42fa.png)

**Comment by dagar** [comment]
@mcsauder have you successfully used the LL40LS on i2c recently?

**Comment by dagar** [comment]
@hyonlim would you be able to get the full boot output from the beginning?

**Comment by dagar** [comment]
This is a bit of a leap, but one possibility is we may need to increase `CONFIG_MAX_TASKS`. 

https://github.com/PX4/Firmware/compare/master...dagar:pr-task_max?expand=1

**Comment by hyonlim** [comment]
https://github.com/PX4/Firmware/pull/13285 solves this problem. Thanks!
