### ISSUE TITLE
Battery failsafe does not cause DESCEND if local position not available

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#13291]
**Bug description**
Once the battery level reaches critical value the system tries to execute an RTL or LANDING, whichever is configured. The same process is repeated once the battery level reaches emergency level.
However, if no local position is available (altitude is available) then no failsafe will be executed, even if the battery is totally drained.
https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L343

**Alternative**
How about handling this case similar to when the vehicle loses RC signal and no local position is available (altitude is available)? In that case the system does a controlled descend.

**Screenshot from SITL testing on lastest master**
- allowed SITL to drain battery to 0
- enabled low battery failsafe (land)
- stopped gpssim such that only altitude but not xy position is valid

![image](https://user-images.githubusercontent.com/7610489/67660508-3cdf7e80-f95f-11e9-8914-19777ba98cad.png)

**Comment by RomanBapst** [comment]
@julianoes I'm not quite sure if this is somewhat by design or just because battery failsafe and rc loss failsafe are handled at different locations in the commander.
The RC loss failsafe sets a new nav state while the battery failsafe changes the internal state of the commander.

**Comment by julianoes** [comment]
> just because battery failsafe and rc loss failsafe are handled at different locations in the commander.

Yes that's probably why!

**Comment by dagar** [comment]
The dream would be to capture all of these details into a single state chart.
