### ISSUE TITLE
BAT_A_PER_V und BAT_V_DIV missing

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#13292]
**Describe the bug**
When I open the Power Tab in QGC 3.5.4 against PX4 SITL (8f910f84358b0da6ad79231080c63f3542408bc1) I get the warning:

"Parameters are missing from firmware. You may be running a version of firmware QGC does not work correctly with or your firmware has a bug in it. Missing params: -1:BAT_A_PER_V, -1:BAT_V_DIV"

**To Reproduce**
1. Start SITL
2. Open QGC and go to Settings -> Power tab.

**Expected behavior**
No warning should be displayed.

**Log Files and Screenshots**

![Selection_059](https://user-images.githubusercontent.com/1419688/67663622-386a9400-f966-11e9-938e-34b9a8474e9f.png)

**Comment by julianoes** [comment]
```
6a0f5249f825effc6a516596aea7ccc4b8c70cc2 is the first bad commit
commit 6a0f5249f825effc6a516596aea7ccc4b8c70cc2
Author: Daniel Agar <daniel@agar.ca>
Date:   Mon Oct 21 13:40:23 2019 -0400

    sensors: split out analog battery handling to new standalone battery_status module
```

**Comment by dagar** [comment]
Short term we can shift the analog battery parameters so that they're still present in SITL (which has no analog batteries).

I think we need to maintain a list of params QGC depends on.

**Comment by dagar** [comment]
Longer term we'll need to do something QGC side for vehicles that only have digital power modules or even v5x that's somewhere in between (cell configuration, but no ADC to configure).

**Comment by dagar** [comment]
This also makes me wonder about automated testing between QGC and actual PX4 rather than just a mock link.

**Comment by dagar** [comment]
@DonLakeFlyer / @dogmaphobic can we start thinking about how to update the QGC power configuration gui for future systems that don't have analog power modules to configure?

**Comment by dagar** [comment]
Going into v1.10 - https://github.com/PX4/Firmware/pull/13301
