### ISSUE TITLE
SITL tests safe landing intermittent failure

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#13334]
- http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests_ASan/detail/master/878/pipeline

![image](https://user-images.githubusercontent.com/84712/67964165-3149bd00-fbd6-11e9-9aa1-663f6250572d.png)

I'll add more examples and output as these appear.

**Comment by TSC21** [comment]
I have no clear idea of what's causing this but looking at the build logs I also see a poll timeout on the mavlink interface. @mrivi any ideas?

**Comment by dagar** [comment]
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-13337/6/pipeline

**Comment by mrivi** [comment]
this is seems more like a real failure. I need to look into this.

**Comment by mrivi** [comment]
I cannot see the CI logs. The link sends me to a white empty jenkins page

**Comment by julianoes** [comment]
> I cannot see the CI logs. The link sends me to a white empty jenkins page

Try a couple of times or hit Ctrl+R. Jenkins seems to be that way :sob:.

**Comment by julianoes** [comment]
This is apparently still happening.

**Comment by dagar** [comment]
Here's a new one. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/1636/pipeline

![image](https://user-images.githubusercontent.com/84712/68304271-6c833a80-0073-11ea-9bfb-536c3d06967f.png)

https://logs.px4.io/plot_app?log=dfa49546-b53e-4c85-9ef9-bdd202e6099f

**Comment by julianoes** [comment]
@dagar but that's something new. That's not the poll error.

**Comment by julianoes** [comment]
@mrivi can you check this one?

**Comment by julianoes** [comment]
What about this one?
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-13405/1/pipeline

**Comment by dagar** [comment]
Here's a new one (no poll timeout). http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-13420/2/pipeline

**Comment by julianoes** [comment]
@dagar would this matter?

```
`ERROR [mavlink] [timesync] Time jump detected. Resetting time synchroniser.
```

**Comment by dagar** [comment]
Here's a fresh one. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-13629/1/pipeline

https://logs.px4.io/plot_app?log=d324dadd-6988-41d1-972f-1789704b5891

![image](https://user-images.githubusercontent.com/84712/69824660-7ca5ba00-11da-11ea-97fa-adbe33d01445.png)

![image](https://user-images.githubusercontent.com/84712/69824666-84655e80-11da-11ea-9607-b0682bacede1.png)

**Comment by julianoes** [comment]
I haven't seen this in a while? Is this still an issue @dagar @mrivi ?
