### ISSUE TITLE
[WIP] v1.10.0 Release Notes + Changelog

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#13366]
# v1.10 Release Notes

It's that time again. We need to band together to bring forward the best release the community can give. Help us represent your work better to the world if you have a feature you worked endless hours, and you think it should be part of the high-level release notes, please let us know in a comment below.

## Teamwork

![Teamwork](https://media.giphy.com/media/65HR2UL6nn6XMSUoRA/giphy.gif)

## Community we need your help

Please review the changelog and help us identify anything that should be part of the high-level release notes.

---

# NOTE: This is still considered Work In Progress

### Highlights
* DShot Support with Telemetry (PR [#12854](https://github.com/PX4/Firmware/pull/12854), [Docs](https://docs.px4.io/master/en/peripherals/dshot.html))
* 1kHz rate loop (param IMU_GYRO_RATEMAX)
* Cone-based RTL ([Docs](https://docs.px4.io/master/en/flight_modes/return.html#return_altitude))
### Migration Guide
* DEPRECATED: Throttle PID Attenuation (TPA) (PR [#13208](https://github.com/PX4/Firmware/pull/13208))
   * Deprecated in favor of [Thrust Curve](https://docs.px4.io/master/en/config_mc/pid_tuning_guide_multicopter.html#thrust_curve) compensation.
### Multicopter
* Rate integrator improvements (PR [#12296](https://github.com/PX4/Firmware/pull/12296))
* Navigator bugfix for setpoint publication (PR [#13588](https://github.com/PX4/Firmware/pull/13588))
### VTOL
* VTOL front transition heading handling improvements (PR [#12630](https://github.com/PX4/Firmware/pull/12630))
* RTL: By default enable return via landing pattern for deterministic back-transition (PR [#12746](https://github.com/PX4/Firmware/pull/12746))
* VTOL GPS fix bank loiter (PR [#12778](https://github.com/PX4/Firmware/pull/12778))
* VTOL fix RTL started during front transition (PR [#13727](https://github.com/PX4/Firmware/pull/13727))
### Rover
* Enable Offboard support for Rover position control
### PX4/ECL - Estimators improvement
* Mag inconsistency check (PR [#12334](https://github.com/PX4/Firmware/pull/12334))
### PX4/Drivers
* UAVCAN sensor drivers for battery and optical flow
### PX4/Avoidance
* Safe Landing Planner
* Collision Prevention Improvements
### Simulation
* Simulation-In-Hardware (PR [#11835](https://github.com/PX4/Firmware/pull/11835), [Docs](https://dev.px4.io/master/en/simulation/simulation-in-hardware.html))
* jMAVSim headless/no-GUI option (jMAVSim [PR #105](https://github.com/PX4/jMAVSim/pull/105))
### Logging improvements
* AUX1-RC-channel-based logging via SDLOG_MODE (PR [#12100](https://github.com/PX4/Firmware/pull/12100))
* Logging of system bootup messages, and dmesg tool (on boards with enough RAM) (PR [#11792](https://github.com/PX4/Firmware/pull/11792))
### Onboard computer / middleware improvements
* Bugfixes in uORB topic initialization (PR [#13589](https://github.com/PX4/Firmware/pull/13589))
### Failsafe / commander improvements
* Bugfixes for failsafe corner cases (PRs [#13143](https://github.com/PX4/Firmware/pull/13143), [#13294](https://github.com/PX4/Firmware/pull/13294))
### OS/NuttX
The release includes a change from [NuttX-7.28 ](https://bitbucket.org/nuttx/nuttx/src/48d1d9d84f18461aba2eeaf39cae3aafce2fce4d/ReleaseNotes#lines-20687) to [NuttX-7.29](https://bitbucket.org/nuttx/nuttx/src/101f3bddecb70cfb8dc78c5b4fad98f3480ae399/ReleaseNotes#lines-21789)
See [NuttX release notes](https://bitbucket.org/nuttx/nuttx/src/101f3bddecb70cfb8dc78c5b4fad98f3480ae399/ReleaseNotes#lines-21789) for the details of changes in NuttX-7.29 details.

Included as backports are:
* STM32:F7 i2C fixes
  * State and interrupt storm fixes.
* Serial Single wire mode has moved to NuttX
* Fix for "z" in printf
* kinetis:i2c transfer ensure correct result returned.
* kinetis_i2c_transfer released the mutex then fetched the state, this resulted in returning the correct results.
* STM32F4 and STM32F7 SD card hang on card eject fixed
* stm32f7:ethernet add timeout on MAC reset

### Updated Supported Hardware
* Holybro Kakute F7 board support (PR [#12440](https://github.com/PX4/Firmware/pull/12440), [Docs](https://docs.px4.io/master/en/flight_controller/kakutef7.html))
* Kopis 2 Airframe configuration (PR [#12549](https://github.com/PX4/Firmware/pull/12549))

## v.1.10.0 Changelog
https://gist.github.com/mrpollo/3af778f7f6cdbad1f0433ba18b4b7204

**Comment by bkueng** [comment]
@mrpollo what is the difference to this doc: https://docs.google.com/document/d/1n6agfdgzk0SfvW61l3vbsMTBj7nT-JIaKsf5hQFs69E/edit?pli=1?

**Comment by mrpollo** [comment]
Goot catch @bkueng, as of now, this issue is the source of truth, we can port over any missing info from the doc. 

cc @jinger26

**Comment by mrpollo** [comment]
From @davids5 

```
The release includes a change from NuttX-7.28 NuttX-7.29
See NuttX release notes Release Notes for the details of changes in NuttX-7.29 details.
------------------------
Included as back ports are:
STM32:F7 i2C fixes
 State and interrupt storm fixes.
Serial Single wire mode has moved to NuttX
Fix for "z" in printf
kinetis:i2c transfer ensure correct result returned.        kinetis_i2c_transfer released the mutex then fetched
      the state, this resulted in returning the correct
      results.
STM32F4 and STM32F7 SD card hang on card eject fixed
stm32f7:ethernet add timeout on MAC reset```

**Comment by mrpollo** [comment]
@davids5 I updated the release notes per your comment on Slack, thanks for your help.

Can you please make sure I got the links right?

**Comment by davids5** [comment]
@mrpollo - Thank you. minor changes - Done

**Comment by RomanBapst** [comment]
@mrpollo I updated the vtol section.

**Comment by bkueng** [comment]
Thanks @mrpollo

**Comment by MaEtUgR** [comment]
@mrpollo Nice! I added a comment about TPA for migration.
**EDIT:** and mag inconsistency check improvement.

**Comment by julianoes** [comment]
@dagar I think we should mention all the VSCode support.

**Comment by ThomasRigi** [comment]
@mrpollo can you add #12778 to the failsafe bugfixes?

**Comment by mrpollo** [comment]
Thanks @ThomasRigi I added your fix to the release notes.

**Comment by mrpollo** [comment]
Hey Mr stable bot, how timely of you. ⏱
