### ISSUE TITLE
VTOL: UAVCAN for servo doesn't work

### ISSUE THREAD

**Issue by GigaFlopsis** [PX4/Firmware#13410]
At the moment, not full functionality of signal publishing for uavcan actuators is implemented.
In the UAVCAN mode, the signal output for the actuators does not work, the signal goes only to the motors of the MC mode.

For example I use:
 - fmu: px4 master  
 - type: Generic Quadplane VTOL type
in UAVCAN I see
FW mode "cmd: [6440, 2942, 1, 7032, 6147, 4096]"
MC mode "cmd: [6045, 1, 6191, 4177, 6147, 4095, 1, 1]"

As you may have noticed only 6 out of  9 срфтуды are sent to the bus.

**Comment by julianoes** [comment]
FYI @pavel-kirienko

**Comment by GigaFlopsis** [comment]
I conducted a number of experiments with different firmware versions (master, v1.92, v1.10-rc1). As I have found out, none of the firmwares outputs the plane signal to uavcan.  

fow expamle FW mode: 
cmd: [0, 0, 0, 0, 6147, 4095, 0, 0]

**Comment by RicardoM17** [comment]
@GigaFlopsis did you manage to get to the bottom of this? Was it fixed or did you find a solution?

**Comment by GigaFlopsis** [comment]
Hello. I found a solution. 
I added next line in Firmware/ROMFS/px4fmu_common/init.d/airframes/...

> set OUTPUT_MODE uavcan_esc
> set OUTPUT_AUX_DEV /dev/uavcan/esc
