### ISSUE TITLE
GPS time cleanup

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#1343]
Now ubx driver uses UTC time, but stores it to `time_gps_usec` field of `vehicle_gps_position`:
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/topics/vehicle_gps_position.h#L82

It's confusing, because "GPS time" (week and seconds) is not the same as UTC and differs from UTC by 16 seconds. (See http://leapsecond.com/java/gpsclock.htm)

I think we should use UTC time everywhere so just need to fix field name and comment.

@pavel-kirienko, what about time reported by CAN GPS?

**Comment by LorenzMeier** [comment]
Fixed by #1570.
