### ISSUE TITLE
Yaw not following ROI in mission

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#13458]
Autopilot: Pixracer

Firmware: 1.9.2

I tried many combinations of parameters, and different waypoint (with camera, without camera, ...) but it seems that in no way the multicopter uses the yaw to track a ROI. The yaw always points to the next waypoint.
I have a gimbal with only pitch, and the pitch seems correct, but no way about the yaw.
Is there a secret combo of parameters, or simply the feature got broken on 1.9.2?

PS: I think the key parameter here is MIS_MNT_YAW_CTL, which according to the description should be disabled, but I tried both enabled and disabled.

PS2: I'm wondering if the mixer has something to do with it

**Comment by dagar** [comment]
Could you verify if this is the case in current master or the v1.10 release candidate (https://github.com/PX4/Firmware/releases/tag/v1.10.0-rc1)?

**Comment by tuloski** [comment]
I'll test it today.

**Comment by tuloski** [comment]
Also the overall mission is working really badly:

- Sometimes it doesn't enter in mission flight mode from RC switch. I have to switch 2-3 times
-Sometimes it doesn't see the waypoint as reached so the quadrotor stops.
-Sometimes it does yaw pirouettes (360 on yaw)

I'll try to revert back to 1.9.1 or 1.8.2.

**Comment by tuloski** [comment]
Tested on simulator:

- On 1.9.2 and 1.9.1 it **doesn't work** properly
- On 1.8.2 it's **working** properly

Something got messed up in the middle.

**Comment by julianoes** [comment]
FYI @bresch

**Comment by julianoes** [comment]
@tuloski can you check 1.10?

**Comment by tuloski** [comment]
I tested the latest release and it's working there.
