### ISSUE TITLE
v1.10.0-rc quadcopter doesn't take off in HITL/jMAVsim 

### ISSUE THREAD

**Issue by langrind** [PX4/Firmware#13471]
**Describe the bug**
Set up HITL simulation with jMAVsim on Ubuntu 18.04,  Pixhawk 4 with v1.10.0-rc, locally built px4_fmu-v5-multicopter. 

**To Reproduce**
1. Follow the recipe from [px4 website](https://dev.px4.io/v1.9.0/en/simulation/hitl.html#jmavsimgazebo-hitl-environment)
2. Using Manual/Stabilized mode, arm vehicle and apply throttle
3. Vehicle does not take off
4. Mavlink shell (`listener` command) shows actuator_outputs_1 with *valid* values and actuator_outputs_0 with 0 values

**Expected behavior**
SERVO_OUTPUT_RAW or HIL_ACTUATOR_CONTROLS should follow actuator_outputs_1 and the vehicle should take off in simulation

**Log Files and Screenshots**
[Flight Review Link](https://review.px4.io/plot_app?log=8890b998-3b24-4a96-af5a-da4c10910bff)

Add screenshots to help explain your problem.

**Drone:**
- Pixhawk4 running in HITL Quad Mode
- Photo of the IMU / autopilot setup if possible.
![IMG_8020](https://user-images.githubusercontent.com/11541631/68861820-46d0e380-06ba-11ea-98e2-76585b3bb031.JPG)

**Comment by julianoes** [comment]
That's not good but thanks for the detailed report!

**Comment by langrind** [comment]
Originally I stated : "MAVLink inspector in QGC shows no HIL_ACTUATOR_CONTROLS, and SERVO_OUTPUT_RAW values are all 0".

But this is misleading. The MAVLink Inspector in QGC can only show the messages forwarded by jMAVSim. What's more interesting is:

1) Once the problem is happening, kill the simulator
2) Connect QGC to the Pixhawk via USB
3) Use the MAVLink inspector

This shows:

* HIL_ACTUATOR_CONTROLS _is_ generated by the Pixhawk, but it is all zeros
* SERVO_OUTPUT_RAW flips back and forth between all-zeros sometimes and correct (or at least sensible) values other times

It seems to me that the publication of uOrbs actuator_outputs instance 0 and instance 1 is confusing the mavlink module's generation of HIL_ACTUATOR_CONTROLS and SERVO_OUTPUT_RAW. 

```
listener actuator_outputs

TOPIC: actuator_outputs 2 instances

Instance 0:
 actuator_outputs_s
	timestamp: 712451977  (0.010010 seconds ago)
	noutputs: 8
	output: [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]

Instance 1:
 actuator_outputs_s
	timestamp: 712226919  (0.236525 seconds ago)
	noutputs: 12
	output: [1358.0000, 1408.0000, 1515.0000, 1323.0000, 1500.0000, 1500.0000, 900.0000, 900.0000, 1500.0000, 1500.0000, 1500.0000, 1500.0000, 0.0000, 0.0000, 0.0000, 0.0000]
```

If only instance 0 was published, and it had the correct values, I bet it would work.

Also, I tested a Pixhawk 2.1 (Cube) running px4_fmu-v3_default, and the behavior was 100% identical.

**Comment by langrind** [comment]
This change causes the HIL_ACTUATOR_CONTROLS mavlink message to have non-zero values, and now the drone takes off in jMAVSim and I can fly around Zurich crashing into virtual trees:

```
langrind@nik:~/Firmware$ git diff
diff --git a/src/modules/mavlink/mavlink_messages.cpp b/src/modules/mavlink/mavlink_messages.cpp
index 61a55b8b22..4e258c6165 100644
--- a/src/modules/mavlink/mavlink_messages.cpp
+++ b/src/modules/mavlink/mavlink_messages.cpp
@@ -3065,7 +3065,7 @@ private:
 protected:
        explicit MavlinkStreamHILActuatorControls(Mavlink *mavlink) : MavlinkStream(mavlink),
                _status_sub(_mavlink->add_orb_subscription(ORB_ID(vehicle_status))),
-               _act_sub(_mavlink->add_orb_subscription(ORB_ID(actuator_outputs))),
+              _act_sub(_mavlink->add_orb_subscription(ORB_ID(actuator_outputs), 1)),
                _act_time(0)
```

I wonder if this is the correct fix?

**Comment by langrind** [comment]
https://github.com/PX4/Firmware/pull/13488 is my proposed fix
