### ISSUE TITLE
Firmware version is weird number

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#13472]
When I run the simulation with gazebo and mavros (using IRIS model), on QGC I see a weird version for the firmware (something like 48.3.4). Where is this number coming from and why is it there? Should't it be related to the PX4/Firmware number, so something like 1.9.2?

**Comment by dagar** [comment]
Make sure you have all the tags locally. 

`git fetch --all --tags`

**Comment by tuloski** [comment]
I'll try that, but in which repo? Firmware or sitl?
But just for knowledge where is that number coming from? Mavlink from the autopilot?

**Comment by dagar** [comment]
In `Firmware`. It's set at build time based on the git tags you have locally (git tag -l).

**Comment by tuloski** [comment]
Ok, but how does QGC get it?

**Comment by dagar** [comment]
Over mavlink from firmware. https://mavlink.io/en/messages/common.html#AUTOPILOT_VERSION
