### ISSUE TITLE
[FW]Fixed wing can't land to home point when I choose RTL mode

### ISSUE THREAD

**Issue by xdwgood** [PX4/Firmware#13480]
Run `make px4_sitl_default gazebo_plane`

My operation flow: start gazebo FW simulation --> upload a FW landing point ---> send take off command ---> switch mode to RTL

FW can't land  after I use the latest master branch.

sitl log : https://logs.px4.io/plot_app?log=e409a27b-aa70-4ddd-a7b0-f3118a4e6a41  （I added some debug code for debugging.）

**EDIT** : Please use this same log link as the master branch:    https://logs.px4.io/plot_app?log=5c633144-1470-4bd1-af18-68d189d75a7e

What parameters can be set, when I choose RTL mode, the fixed wing can automatically land to the ground.

I have read this carefully: https://docs.px4.io/master/en/flight_modes/return.html#fixed-wing-fw

**Comment by xdwgood** [comment]
@RomanBapst  Do you know the correct parameter configuration? Thank you

**Comment by Antiheavy** [comment]
RTL_TYPE =1 is typically the best option for fixed wing. It uses the mission landing pattern to RTL.

**Comment by xdwgood** [comment]
@Antiheavy  thanks your replay
I also try set RTL_TYPE =1, but still not land when I switch RTL mode.

How should I set the mission land?

**Comment by Antiheavy** [comment]
Huh. Did you upload a mission with a landing pattern?  See https://docs.px4.io/master/en/flight_modes/return.html

**Comment by xdwgood** [comment]
@Antiheavy  FW can land when I choose mission mode and add a landing point.
just like this: 
![Screenshot from 2019-11-16 10-32-01](https://user-images.githubusercontent.com/24932258/68986764-a4e9fc00-085d-11ea-83a5-a947b0a05434.png)

But when I choose RTL mode, FW will not land but hover.
Sorry, I still don't understand what I should do, I just want to get an RTL similar to the rotor (automatic landing to the takeoff point).

**Comment by Antiheavy** [comment]
Are you simulating a fixed wing or a VTOL aircraft?  I don’t understand how a forced wing could hover. There must be something strange with your setup, I just can’t tell what.

**Comment by xdwgood** [comment]
> Are you simulating a fixed wing or a VTOL aircraft? 

FW

> There must be something strange with your setup,

maybe,But I have not changed other parameters.

Anyway, thank you again for your reply.

**Comment by Antiheavy** [comment]
@xdwgood I notice that you are using the very latest daily build versions of QGC.  I know there are a lot of changes happening right now with the mission planning section.  Have you tried this with the official released version?  Maybe there is a bug with the landing pattern in the daily builds?
http://qgroundcontrol.com/downloads/

**Comment by xdwgood** [comment]
@Antiheavy  I tried to use the released version of qgc. After executing rtl, the drone will not land, and do circular motion at 100 meters.

**Comment by Antiheavy** [comment]
> and do circular motion at 100 meters.

does it do this around the Home location or somewhere else?

**Comment by xdwgood** [comment]
> does it do this around the Home location or somewhere else?

@Antiheavy  it around the Home location

**Comment by Antiheavy** [comment]
do you get errors when trying to upload the mission to the autopilot?

**Comment by xdwgood** [comment]
I have not updated the mission. My operation flow is: commander take off--> switch RTL mode

**Comment by xdwgood** [comment]
Or currently px4 does not support automatic landing in rtl mode, we have to upload a mission and then execute rtl?

**Comment by Antiheavy** [comment]
huh... i'm unfamiliar with these new log messages:
![image](https://user-images.githubusercontent.com/12117027/69001876-13ee4180-08ac-11ea-845b-cc1f8c24216d.png)

I wonder if something is broken with the new RTL stuff around safe points.  @sfuhrer can you take a look at this?

**Comment by xdwgood** [comment]
@sfuhrer   @Antiheavy 
My operation flow: start gazebo FW simulation --> upload a FW landing point ---> send take off command ---> switch mode to RTL

log link：  https://logs.px4.io/plot_app?log=5c633144-1470-4bd1-af18-68d189d75a7e

![Screenshot from 2019-11-17 10-06-34](https://user-images.githubusercontent.com/24932258/69001992-ed1f2200-0922-11ea-800c-79f6eaf67c7f.png)

In the log print information, the landing has been prompted, but in the simulation, the drone has been flying forward without landing.

![6666](https://user-images.githubusercontent.com/24932258/69002004-248dce80-0923-11ea-8831-200537136bb8.png)

**Comment by sfuhrer** [comment]
Hi @xdwgood,

I've just tried it with the same setup as you described, and it worked for me as expected (landing at mission landing).

https://review.px4.io/plot_app?log=693a3338-5cb1-4059-9f0e-48a261ff8146
https://review.px4.io/plot_app?log=c8686c3f-23c4-4090-bfb0-b62cc32df9c4

Looking at the logged messages of your flight I can only think of that the mission (in your case landing point) upload failed for some reason. It looks like it has no mission landing, and thus chooses Home to go to in the RTL. Ofc it doesn't land there, but circles. I'm wondering though why it then says "Landing at destination" - it should instead should say "RTL: completed, loitering". I just checked, that's what you get when you RTL in a flight without any mission planned.

Did you check if you get any mission feasibility errors while uploading or when starting the flight? And did you also try with a complete mission, meaning with takeoff, normal wp and then the mission landing?

**Comment by Antiheavy** [comment]
If you were using RTL_TYPE 1 it should force you to use the mission landing in all except certain cases like you deleted the mission mid-flight or something. 

Another weird thing is I’d expect to see a logged message that says something like “unable to use mission landing, returning to Home”

Also, the weird thing is that you should not even be able to takeoff in an auto mode if the vehicle does not have a valid mission.

**Comment by sfuhrer** [comment]
> Also, the weird thing is that you should not even be able to takeoff in an auto mode if the vehicle does not have a valid mission

That was the case, I had to trigger takeoff over the command line as the mission was not valid (only had a landing pattern but no takeoff). What was your exact procedure @xdwgood ?

**Comment by xdwgood** [comment]
> That was the case, I had to trigger takeoff over the command line as the mission was not valid (only had a landing pattern but no takeoff). What was your exact procedure @xdwgood ?

@sfuhrer   I send the takeoff through the command line:
`Commander takeoff`

> And did you also try with a complete mission, meaning with takeoff, normal wp and then the mission landing?

yes，I have tried a mission(wp) and will land automatically when the drone is executed.

Clarify my detailed operation again:  start gazebo FW simulation -->open qgc---> upload a FW landing point ---> send take off command by `commander takeoff` ---> switch mode to RTL--->FW can't land


@Antiheavy @sfuhrer  Thanks Reply

**Comment by sfuhrer** [comment]
@xdwgood this was the exact same procedure I used in [this](https://review.px4.io/plot_app?log=693a3338-5cb1-4059-9f0e-48a261ff8146) flight. In your [first log](https://logs.px4.io/plot_app?log=e409a27b-aa70-4ddd-a7b0-f3118a4e6a41) you seem to have RTL_TYPE=0, in which case it is normal that it will go to home and loiter there. In your [second log](https://logs.px4.io/plot_app?log=5c633144-1470-4bd1-af18-68d189d75a7e) though, with RTL_TYPE=1, the logged messages indicate that it actually did go to the mission landing. Was this not the case?

**Comment by xdwgood** [comment]
>  the logged messages indicate that it actually did go to the mission landing. Was this not the case?

But the FW did not land, but continued to fly straight.

**Comment by sfuhrer** [comment]
@xdwgood could you maybe try again? To see if it reproducible. As I couldn't reproduce it so far.

**Comment by xdwgood** [comment]
@Antiheavy @sfuhrer 
I updated the code and tried again, everything worked fine, FW landed on the ground. I am sorry to bother you, thank you for your reply, thank you.
