### ISSUE TITLE
PX4 SITL max motor speed

### ISSUE THREAD

**Issue by waytry** [PX4/Firmware#13506]
__Describe the question__  
I was trying to use a custom quadcopter model in PX4 SITL. I created a sdf file for the Crazyflie 
 to replace the default iris sdf model. And I successfully launched the PX4 SITL by following [Launching Gazebo with ROS Wrappers](https://dev.px4.io/master/en/simulation/ros_interface.html#launching-gazebo-with-ros-wrappers).  Basically what I did was
```
cd <Firmware_clone>
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo
roslaunch px4 mavros_posix_sitl.launch vehicle:="crazyflie"
```

In the SITL, the PX4 node sends motor speed to the Gazebo simulation (the gazebo_motro_model plugin in particular). As the crazyflie has max motor speed of 3000 rev/s differs from the 1100 rev/s of iris, I wanted to modify this parameter in PX4 firmware. I tried to search "max motor speed" and "max rotor speed". But couldn't find a parameter to specify the max motor speed. Is there a way to modify the max motor speed?

Thanks

**Comment by julianoes** [comment]
Did you check in https://github.com/PX4/sitl_gazebo/ ?

**Comment by julianoes** [comment]
Closing, there was no response.

**Comment by mta32** [comment]
Heyy!

Can you please send me the sdf model that you have written.I am Having trouble creating my own.
I would appreciate that.

**Comment by mta32** [comment]
Heyy!

Can you please send me the crazyflie.sdf file that you had written.I am having trouble creating my own.I would really appreciate that.
