### ISSUE TITLE
Help understand inconsistency in altitudes

### ISSUE THREAD

**Issue by tuloski** [PX4/Firmware#13514]
I've been analyzing some logs and I always see this "problem".

![AltInconsistency](https://user-images.githubusercontent.com/6544139/69132849-24253d00-0ab5-11ea-96e5-26515cad3548.jpg)

The various altitude measures have some inconsistency IMO.
For example the local_position.z (PINK) is not at zero when arming (on ground), but it has an offset of around 8 meters. You can see the real altitude from ground in black from the distance_sensor.
Also the vehicle_global_position.alt (BLUE) seems to have the same offset w.r.t. baro data and vehicle_gps_position.alt. The first is at around 57 meters, while the latters at around 49 meters.

Another weird thing is that the "relative alt" I see on QGC matches almost perfectly the distance_sensor, so my questions are:

- Isn't the "relative alt" in QGC taken from local_position.z? If not which data is sent for it?
- Is it normal that the local_position.z doesn't reset to 0 when arming?
- Why those offsets? Is it just the baro drifting?

The overall problem of all this, is that during AUTO modes, the altitude references are always wrong and the copter never reaches the desired waypoint because the reference and the altitude used to check the acceptance radius differ of that offset.

**Comment by julianoes** [comment]
> Isn't the "relative alt" in QGC taken from local_position.z? If not which data is sent for it?

It uses the relative altitude to the home position.

> Is it normal that the local_position.z doesn't reset to 0 when arming?

local_position is initialized when the EKF initializes but not reset on arming.

> Why those offsets? Is it just the baro drifting?

Not sure. 

> ... the copter never reaches the desired waypoint because the reference and the altitude used to check the acceptance radius differ of that offset.

The waypoints should still be reached. Are you sure about this? And can you reproduce it in SITL? Or do you have a logfile to show it?

**Comment by julianoes** [comment]
I'm closing this because there was not follow up. Re-open if you have answers.
