### ISSUE TITLE
Rate problems on custom streams

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#1351]
I'm running some mavlink streams in custom mode, at high rates :
HIGHRES_IMU - 200 Hz
ATTITUDE - 200 Hz
OPTICAL_FLOW - 50 Hz

I have achieved full throughput previously (sometime in July, master at that time) But recently though, I have only been getting 80% of the requested rate.  I can get higher rates by requesting above the actual requirement.

With 100Hz HIGHRES_IMU and ATTITUDE and 50Hz OPTICAL_FLOW, I get this:
![capture2](https://cloud.githubusercontent.com/assets/5557676/4152246/f0a39f60-344c-11e4-8da8-6fcbed7581cb.PNG)

This is true for direct connection via USB. Streams started via custom rc.usb

Kabir

**Comment by dagar** [comment]
@mhkabir Please reopen if still relevant.
