### ISSUE TITLE
Hey everyone, I am having trouble to find a MAVlink command to obtain the rssi of the remote control (in the demonstrator I am protyping, I use RC as the beacon I want to track). Do you have any suggestion, ideally a command python that read the RC rssi?

### ISSUE THREAD

**Issue by Babars7** [PX4/Firmware#13548]
For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/).

**Describe problem solved by the proposed feature**
A clear and concise description of the problem, if any, this feature will solve. E.g. I'm always frustrated when ...

**Describe your preferred solution**

**Describe possible alternatives**
A clear and concise description of alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots for the feature request here.

**Comment by feemi** [comment]
Please pay attention to issue template. You should use forum for these kind of questions. http://discuss.px4.io/
