### ISSUE TITLE
Weird Gyro bias values on thermal compensation

### ISSUE THREAD

**Issue by feemi** [PX4/Firmware#13551]
**Describe the bug**
Gyro 1 has weird values when doing offboard calibration. We tried couple of different cube autopilots.

**To Reproduce**
1.  Do offboard calibration
2. Run process_sensor_caldata.py program

**Expected behavior**
Gyro 1 bias values should be similar to other sensors

**Log Files and Screenshots**
<img width="1571" alt="Screen Shot 2019-11-21 at 19 01 06" src="https://user-images.githubusercontent.com/1747208/69354527-5095b080-0c91-11ea-8b29-599e11017009.png">
[log002.ulg.pdf](https://github.com/PX4/Firmware/files/3875585/log002.ulg.pdf)

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
- Pixhawk Cube 2.1 fmu-v3
- px4 v1.9.2

**Comment by mhkabir** [comment]
This is because the Bosch sensors only report temperatures to the nearest degree. Performance should be unaffected.

**Comment by feemi** [comment]
Thanks @mhkabir I am closing the issue
