### ISSUE TITLE
Error message "unable to read from microSD" when flying a mission with "jump to item"

### ISSUE THREAD

**Issue by sfuhrer** [PX4/Firmware#13592]
**Describe the bug**
When flying a mission on a VTOL with a "jump to item" in it, it does what it is supposed to do (go back to selected item and then continue the mission from there on again), but it gives the following error message every time it reaches the "jump to item" waypoint:
![image](https://user-images.githubusercontent.com/26798987/69558813-2d2c7780-0fa9-11ea-8d0d-f8b3859a2831.png)

https://review.px4.io/plot_app?log=e3b60ca9-d232-46d3-99f4-65220f2360b2

**Comment by julianoes** [comment]
I can reproduce the issue with multicopter SITL.
