### ISSUE TITLE
how to set board_id

### ISSUE THREAD

**Issue by chinahuangyong** [PX4/Firmware#13604]
We use GitHub issues only to discuss PX4 bugs and new features. For
questions about using PX4 or related components, please use [PX4 Discuss](http://discuss.px4.io/).

how to set board_id in the file[Firmware/boards/px4/fmu-v5]

Thanks!

**Comment by dagar** [comment]
The ID can be changed here. https://github.com/PX4/Firmware/blob/a7fbaefd837b2947545d79b6ace42b1d2114ac52/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L47-L52
