### ISSUE TITLE
Can we get the GPS signal from a single satellite and use it during flight?

### ISSUE THREAD

**Issue by Vishranthee** [PX4/Firmware#13656]
I did not get proper GPS signal due to absence of 3D fix. Is it possible to get the approximate lat and long and use it for maneuver?

**Comment by julianoes** [comment]
For a minimal GPS signal you need signal from at least 4 satellites (3D plus time), anything below doesn't work. And to actually fly that's barely enough which is why PX4 has much stricter requirements on the GPS solution.
