### ISSUE TITLE
camera_feedback build failed on RPi

### ISSUE THREAD

**Issue by SalimTerryLi** [PX4/Firmware#13654]
**Describe the bug**
`src/modules/camera_feedback` cannot be built by execute `make px4_raspberrypi_cross`.

**To Reproduce**
Simply build for RPi can reproduce.

**Expected behavior**
It should pass the build.

**Log Files and Screenshots**
[Here](https://paste.ubuntu.com/p/RmRVZpDvWX/)

**Comment by julianoes** [comment]
@dagar I guess we don't have a RPi build in CI?

**Comment by dagar** [comment]
> @dagar I guess we don't have a RPi build in CI?

Apparently not, let's get that fixed.
