### ISSUE TITLE
LPE_FUSION does not show up 

### ISSUE THREAD

**Issue by netgittemp** [PX4/Firmware#13669]
Hi, I am using PX MINI 4, and I am integrating PX4 with companion computer and PX4FLOW.
To do that, I am changing parameters using QGC with usb connection.
However, `LPE_FUSION` parameter does not show up.

How can I set `LPE_FUSION` parameter?

The funny thing is with PX4 Gazebo simulation.
Once I run `$ sudo make px4_sitl gazebo_iris`, I can find `LPE_FUSION` in QGC > Parameters.
After that, if I run `$ sudo make px4_sitl gazebo_iris_opt_flow`, I can find `LPE_FUSION` in QGC > Parameters as well.
However, I run `$ sudo make px4_sitl gazebo_iris_opt_flow` again, then `LPE_FUSION` does not show up... Is it the issue only for me??

I hope somebody help me.
Also, it would be thankful if you advise me what parameters do I have to change for using PX4FLOW.

Thank you.

P.S. `LPE_FAKE_ORIGIN` and `MPC_ALT_MODE` do not show up neither.

**Comment by TSC21** [comment]
@netgittemp we have discontinued LPE. Please use EKF2 instead and set the correct fusion flag for it - https://dev.px4.io/master/en/advanced/parameter_reference.html#EKF2_AID_MASK. The OF params that you can tune have the `EKF2_OF_` suffix, but I advise you to use the default ones for now.
To use the PX4Flow, make sure that for your your board you have `SENS_EN_PX4FLOW` set to `1` and that `SENS_FLOW_ROT` matches the correct sensor orientation of your board with respect to the aircraft frame.

**Comment by netgittemp** [comment]
Hi @TSC21 ,
Thank you for your kind reply.
It is very helpful. Thank you so much.

I have one more issue, and it is kind of bug report.

In [Return Mode](https://docs.px4.io/v1.9.0/en/flight_modes/return.html) page, it is described that the quadrotor goes up to [RTL_RETURN_ALT](https://docs.px4.io/v1.9.0/en/advanced_config/parameter_reference.html#RTL_RETURN_ALT) and move to the home position, then the quadrotor descend to the [RTL_DESCEND_ALT](https://docs.px4.io/v1.9.0/en/flight_modes/return.html#RTL_DESCEND_ALT). When the quadrotor reach to [RTL_DESCEND_ALT](https://docs.px4.io/v1.9.0/en/flight_modes/return.html#RTL_DESCEND_ALT), it will hold the position for [RTL_LAND_DELAY](https://docs.px4.io/v1.9.0/en/flight_modes/return.html#RTL_LAND_DELAY) before landing.

For your information, I set the RTL_* parameters as shown in the following figure;

![param_RTL](https://user-images.githubusercontent.com/57019818/70156428-ea8e2d80-1681-11ea-9d68-65ec5666d0e9.png)

Could you check it for me?
If you would like to make this as bug report, Then I will make another post for this issue.

Thank you.
