### ISSUE TITLE
Yaw during takeoff

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#13675]
**Describe the bug**
Sometimes I observe a multicopter doing a strange yaw back and forth right during takeoff.

**To Reproduce**
Do many takeoff in SITL and every now and then it's visible.

**Expected behavior**
It should not yaw during takeoff, period.

**Log Files and Screenshots**
![17_39_47-yaw-on-takeoff](https://user-images.githubusercontent.com/1419688/70135447-64c2b000-168a-11ea-976a-6f576dc582fb.png)
![14_03_52-yaw-on-takeoff](https://user-images.githubusercontent.com/1419688/70135449-64c2b000-168a-11ea-8778-48dca6c56703.png)

https://logs.px4.io/plot_app?log=907be591-f04b-4187-8e5a-153435b0bfe1
https://logs.px4.io/plot_app?log=bb0b86a5-a23c-4acd-a88a-fda4a8b6b78c

**Drone (please complete the following information):**
- The logs are from a VTOL takeoff without weathervane activated, however, I've also seen the behaviour with iris.

**Comment by mwiatt** [comment]
On takeoff, I have seen a yaw of around 5 - 10 degrees after the copter reaches around 2m in alt. I don't remember similar behavior with 1.9.2. Not sure if this is the same bug.

See this log, around 5:28.65:

https://logs.px4.io/plot_app?log=36040896-dbc3-48d4-baab-ec18c0ed29bd

![image](https://user-images.githubusercontent.com/4399188/70162763-10600600-1673-11ea-8130-76cd8c71cfa3.png)

**Comment by MaEtUgR** [comment]
I recently also saw a strange twitch in SITL on master when doing takeoff. Just a wild guess because of what changed recently: Might be related to https://github.com/PX4/Firmware/pull/13430. Someone up to verify until I find the time to do tests myself?

**Comment by mwiatt** [comment]
I was looking back at some of my old flight logs and this is an interesting one from 1.9.2. You can see that the estimated yaw a step change on takeoff but the flight controller does not react to it.

https://logs.px4.io/plot_app?log=c57c04e0-a6bd-4f04-9fe2-eb986cbcc1b4

![image](https://user-images.githubusercontent.com/4399188/70166498-bf074500-1679-11ea-920c-70abe1ecade3.png)

**Comment by MaEtUgR** [comment]
There can be yaw resets from the estimator in case it realizes after takeoff that the global yaw heading estimate was not accurate e.g. because of magnetic interference. That could also be something realted to the issue here.

> but the flight controller does not react to it

What would you expect to see as a reaction in terms of this plot? Do you expect the setpoint to switch as well since you're flying in manual and basically don't care about the absolute global heading accuracy and want your vehicle to not correct for it?

**Comment by mwiatt** [comment]
> Do you expect the setpoint to switch as well since you're flying in manual
I was flying in Mission mode at the time of the step change in yaw estimate. I wouldn't expect the yaw setpoint to change. I was just pointing out that 1.9.2 and 1.10.0 react differently to the step change. Sorry I wasn't clear.

**Comment by MaEtUgR** [comment]
In the logs posted by @julianoes it's really strange that the yaw setpoint switches to zero even though the task produces no jumps. This means it has to be some logic of the position controller itself which should basically only forward yaw setpoints.
<img width="515" alt="yaw_trajectory" src="https://user-images.githubusercontent.com/4668506/70334147-24f3f800-1845-11ea-90db-5937845fb44c.PNG">

**Comment by julianoes** [comment]
Fixed in #13965.
