### ISSUE TITLE
V1.10 hp_default low on stack

### ISSUE THREAD

**Issue by FlavioTonelli** [PX4/Firmware#13691]
During some preliminary test with 1.10RC2 I got a hp_default low on stack warning.
I can't unfortunately reproduce this behavior right now.

Here is the flight log : https://review.px4.io/plot_app?log=fd552709-201a-4904-aa05-a32a49c8a50b

**Comment by mwiatt** [comment]
Same, but I dont get it all the time.

With low stack:

https://logs.px4.io/plot_app?log=28b95b8c-e567-4e13-b546-338f91c4e8b3

Without:

https://logs.px4.io/plot_app?log=a8662dfc-e6f1-453a-9c9d-8ca576b93340

**Comment by FlavioTonelli** [comment]
I was probably unclear but I don't get all the time as well.

**Comment by dagar** [comment]
I'll bump it to silence the warning.
https://github.com/PX4/Firmware/pull/13707
