### ISSUE TITLE
Once camera_capture on, no fmu pwm outputs

### ISSUE THREAD

**Issue by hyonlim** [PX4/Firmware#13724]
**Describe the bug**
When a system is using FMU output as main PWM and camera_capture running, no motor spin when it is armed.

**To Reproduce**
1. Set FMU PWM as main output
2. Run camera_capture and on
3. Try to arm

**Expected behavior**
Motor should spin but it is not. If I do $ fmu test and arm again, it spins.

**Comment by julianoes** [comment]
This looks like the usual configuration issue between output and input pins.

I think what you should try is to use something like `fmu mode_...` to configure `fmu` to only use and configure some of the pins and then run `camera_capture` on the remaining pins.

**Comment by julianoes** [comment]
Anyone there?
