### ISSUE TITLE
Device driver for barometer DPS310

### ISSUE THREAD

**Issue by Vishranthee** [PX4/Firmware#13720]
@dagar In the devide driver wirteen for barometer ( https://github.com/PX4/Firmware/blob/master/src/drivers/barometer/dps310/DPS310.cpp ) , I am unable to understand the following lines functionality. Can you please elaborate on this?

_sample_perf(perf_alloc(PC_ELAPSED, MODULE_NAME": read")),
	_comms_errors(perf_alloc(PC_COUNT, MODULE_NAME": comm errors"))

**Comment by dagar** [comment]
Those are performance (aka perf) counters that you can see by running `dps310 status` or simply `perf` to see them systemwide. In this case they track the average sampling time and a simple error count.
