### ISSUE TITLE
camera trigger messages in mavlink

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#13723]
Hi

does px4 send camera trigger positions send by mavlink ? 
, i do not see camera signs in qgroundcontrol in survey mission mode .

**Comment by julianoes** [comment]
I don't think `camera_trigger` sends the `CAMERA_IMAGE_CAPTURED` message. I guess this could/should be added to the mavlink module.

**Comment by julianoes** [comment]
Should we add that @DanielePettenuzzo?

**Comment by ndepal** [comment]
`camera_feedback` publishes `ORB_ID(camera_capture)` which is translated to the `CAMERA_IMAGE_CAPTURED` mavlink message. I don't know what QGC does/is supposed to do with this information.

**Comment by julianoes** [comment]
`CAMERA_IMAGE_CAPTURED` would show a photo icon in QGC.

**Comment by moreba1** [comment]
but i don't see photo icon in QGC. should we use feedback from camera hot shoe to see icons ?

**Comment by moreba1** [comment]
@ndepal 
@julianoes 
https://github.com/mavlink/qgroundcontrol/issues/8216#issuecomment-575943525

Don Gange : "QGC will only show image capture points if CAMERA_IMAGE_CAPTURED.capture_result == 1 which indicates a successful capture according to mavlink spec. In the screen shown above you can see that CAMERA_IMAGE_CAPTURED.capture_result equals -1 which isn't even a valid value for that field. So as far as I can tell QGC is working correctly."

**Comment by hamishwillee** [comment]
@julianoes Who should be assigned owner to this - either to close or progress?

**Comment by julianoes** [comment]
@hamishwillee whoever has a setup and can make and test the required changes :man_shrugging:.

**Comment by hamishwillee** [comment]
Well, it definitely needs to be fixed, so I have hit the pinned button.
