### ISSUE TITLE
Sign Pixhawk board with COA

### ISSUE THREAD

**Issue by Javad97** [PX4/Firmware#13748]
How to generate auth.c to sign pixhawk board
reference to this documentation https://ardupilot.org/dev/docs/how-to-use-the-auth-command-to-sign-a-pixhawk-board-with-your-certificate-of-authenticity.html#firmware

Thanks!

**Comment by julianoes** [comment]
Are you using PX4 or ArduPilot?

**Comment by Javad97** [comment]
Iam using ardupilot.

**Comment by julianoes** [comment]
Ok, in that case I suggest that you ask in the [ArduPilot forums](https://discuss.ardupilot.org/) or on the [ArduPilot GitHub](https://github.com/ArduPilot/ardupilot). I don't think PX4 has much to do with this.

**Comment by Javad97** [comment]
Actually I am a beginner, so I choose ardupilot although I didn't know about the auth signing commands.
can you explain to me how can it done with px4 firmware?

**Comment by julianoes** [comment]
I don't think we're doing/using that right now.

What are you trying to achieve?

**Comment by Javad97** [comment]
I want to assign a public/private key for the flight control board.

**Comment by julianoes** [comment]
Taking a step back, what problem are you trying to solve?
