### ISSUE TITLE
setpoint_raw details about implementation

### ISSUE THREAD

**Issue by QING-ML** [PX4/Firmware#13791]
when we use setpoint_raw/attitude to controll MAV, How long does this given thrust have influence in MAV? 
so,Does frequence of publish of attitude and thrust have a important role in this controll method?

**Comment by julianoes** [comment]
> How long does this given thrust have influence in MAV?

Generally in offboard control a setpoint remains until you send the next setpoint. Also note that you need to send offboard setpoints continuously at least twice per second but if possible much faster.

> Does frequence of publish of attitude and thrust have a important role in this controll method?

Yes, for attitude control you need to have a fast rate for smooth control, for velocity or position control it is not as critical.

A good place to ask these sort of questions is also on https://slack.px4.io or https://discuss.px4.io.
