### ISSUE TITLE
SD card data logging ! ERROR [logger] Failed to add topic <sensor_accel>

### ISSUE THREAD

**Issue by SebastienFerrero** [PX4/Firmware#13816]
hello, need help thanks
I got the following error
ERROR [logger] Failed to add topic <sensor_accel>
I try to add a topic by folloing this

Configuration
The list of logged topics can be customized with a file on the SD card. Create a file etc/logging/logger_topics.txt on the card with a list of topics (For SITL, it's build/px4_sitl_default/tmp/rootfs/fs/microsd/etc/logging/logger_topics.txt):

<topic_name>, <interval>
https://dev.px4.io/v1.9.0/en/log/logging.html

![image](https://user-images.githubusercontent.com/50665886/71584846-8448dd80-2b4f-11ea-90ea-85b165cac0ff.png)

I'm affecting start-up from sd card with the following script

usleep 1000
uorb start
usleep 1000
tone_alarm start
usleep 1000
px4io start
#gps start -f           #Starts GPS driver and Fake a GPS signal (useful for testing)  
usleep 1000
sh /etc/init.d/rc.sensors
usleep 1000
ekf2 start
usleep 1000
mtd start
usleep 1000
param load /fs/mtd_params
usleep 1000
logger start -f
usleep 1000
#px4_simulink_app start

**Comment by bkueng** [comment]
Hi
You need to remove the brackets (`<`).
