### ISSUE TITLE
Standard VTOL model mismatch between simulation and visualization

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/Firmware#13817]
**To Reproduce**
You can run the stadard_vtol model with the following command
```
make px4_sitl gazebo_standard_vtol
```
The visualization shows a flying wing model with rotors attached. However, 
- The standard_vtol model has a rudder and elevator that has lift and drag: https://github.com/PX4/sitl_gazebo/blob/master/models/standard_vtol/standard_vtol.sdf#L570
- The mixer is using the elevator and elevons don't provide pitch commands: https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers-sitl/standard_vtol_sitl.main.mix 

Applying pitch manual inputs do not make the elevons move

![Screenshot from 2019-12-30 15-41-17](https://user-images.githubusercontent.com/5248102/71586596-1682be80-2b1b-11ea-872e-b3337a45a9c9.png)

Would it be more desirable to change the mixers and model as a flying wing model with rotors? or should we switch the mesh to a more appropriate model (maybe a cessna with rotors)?

What does `standard_vtol` supposed to mean?

**Possible solutions**
- a) Modify the `standard_vtol` mixer so that it has elevons and modify the gazebo model appropriately
- b) Modify the `standard_vtol` visualization to a quad plane

@sfuhrer @RomanBapst FYI

**Comment by Jaeyoung-Lim** [comment]
This seems to be due to a limit coming from the aerodynamics modeled in gazebo

**Comment by frontw** [comment]
Hi! What a limit and how it was resolved?
Is there a Gazebo model of VTOL with ailerons and tail rudder and elevator available?

**Comment by frontw** [comment]
Here is standard VTOL visually correct model https://www.youtube.com/watch?v=Ifn4k6Rtkrc.
Where to find it? Why it is not used?
