### ISSUE TITLE
How do you solve for px4 bouncing off the ground

### ISSUE THREAD

**Issue by love-mj** [PX4/Firmware#13813]

**Comment by 60ericleal60** [comment]
Are you attempting to traverse very near the ground or actually touching the ground?

**Comment by love-mj** [comment]
![th3zj-2y6i6 (1)](https://user-images.githubusercontent.com/37679671/72308715-f5dc6c00-36b7-11ea-8a2c-e40eb89c3baf.gif)

**Comment by julianoes** [comment]
It's not clear what the problem is.  @love-mj please fill out the issue template, or at least provide enough description for us  to understand.

**Comment by julianoes** [comment]
Closing, there was no follow up.
