### ISSUE TITLE
PARAM_SET in SITL take a second on Mac OS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#13826]
This points to something being off with locking or priorities (and not just on Mac OS, but it is just showing there).

**Comment by LorenzMeier** [comment]
@bkueng @julianoes I have a hunch that during SITL boot the fact that lockstep is active does interfere with app boot up until the system is fully running.

**Comment by julianoes** [comment]
I can't reproduce this on my Mac. Which SITL vehicle are you using? How are you testing or measuring this? Which version?

**Comment by julianoes** [comment]
Closing as there was response and I haven't seen this myself.
