### ISSUE TITLE
can't view gazebo video in qground control 

### ISSUE THREAD

**Issue by liangpu597** [PX4/Firmware#13829]
I want to view gazebo video in qgc.
I follow the instance in: https://dev.px4.io/v1.9.0/en/simulation/gazebo.html
My Step is :

Enable the GStreamer Plugin (if disabled) by changing the BUILD_GSTREAMER_PLUGIN option to "ON" in /Tools/sitl_gazebo/CMakeLists.txt (as shown below):
option(BUILD_GSTREAMER_PLUGIN "enable gstreamer plugin" "ON")

make clean
make px4_sitl gazebo_typhoon_h480

I open qgc and in settings-> general -> video source
and its no video available. I can't find other choice.
my gazebo version is : 9.10
QGC version is : v3.5.4

**Comment by liangpu597** [comment]
I have solved , thanks

**Comment by ChenXL765** [comment]
hi, I think I had the same problem as you, so i want to know how did you solve it. Thank you very much!
