### ISSUE TITLE
SITL issues

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#13868]
Throwing in some things I noticed when testing in SITL with jmavsim on lastest master.

- [x] console hangs when you do a "sensors stop"
According to @julianoes this is expected as everything stops due to lockstep stopping

- [ ]  If you stop the simulator from publishing mag data and then try to takeoff you get a PreflightFail indicating that there is no valid mag data. But the system does not stop you from taking off, is this intentionally?

Furthermore, I tried to debug first issue using gdb but had not luck getting something to work.

![image](https://user-images.githubusercontent.com/7610489/71824773-63cad700-30ab-11ea-8f6a-73c5c9ccf13d.png)

**Comment by julianoes** [comment]
Can you create two separate issues please? This is hard to manage like that.

**Comment by dagar** [comment]
>  If you stop the simulator from publishing mag data and then try to takeoff you get a PreflightFail indicating that there is no valid mag data. But the system does not stop you from taking off, is this intentionally?

@RomanBapst definitely not intentional, and could be more than a SITL bug.

**Comment by RomanBapst** [comment]
@dagar Ok, will investigate further

**Comment by RomanBapst** [comment]
@dagar Ok, apparently it does it because the arming state is set to IN_AIR_RESTART when you do a commander takeoff. It works properly when you send a takeoff command from QGC.
Not sure if that is intentional again :-D
