### ISSUE TITLE
How to control AX-12A Dynamixel servomotor using The Pixhawk ?

### ISSUE THREAD

**Issue by islamdib** [PX4/Firmware#13879]
hello everyone,
so I have four servomotor AX-12A Dynamixel, I want to control them using The pixhawk.
The first problem is that this kind of servomotor is inteligent ,so it has an ID (like a name).
I tried to control them with arduino with the serial port TX and all is right.
but I've no idea to  how use it with Pixhawk,
please enyhelp?

**Comment by hamishwillee** [comment]
This area is for bugs and enhancement requests. Please raise on the discussion boards (linked from [here](https://docs.px4.io/master/en/#support).
