### ISSUE TITLE
Duplicate UUID on real FC board

### ISSUE THREAD

**Issue by cjffly** [PX4/Firmware#13882]
**Describe the bug**
I happen to have 2 flight control boards (CUAV v5+) with same uid. According to #10059 , we can change the uuid by changing the MAV_SYS_ID. However, no mater what MAV_SYS_ID I assigned to these two board, they still have the same UUID when I use MAVSDK system.get_uuid() to read them. 

**Expected behavior**
If I change the MAV_SYS_ID, the UUID should change accordingly based on #10059.

When I use QGC's mavlink inspector->autopilot_version->uid, it turns out to be the same number of what MAVSDK returns to me when I use system.get_uuid(). The uid2 shows different number though.

**Comment by bkueng** [comment]
@julianoes isn't the SDK using uid2?

**Comment by julianoes** [comment]
> @julianoes isn't the SDK using uid2?

Not yet unfortunately, see: https://github.com/mavlink/MAVSDK/pull/694

**Comment by julianoes** [comment]
Thanks for the issue. I'm closing this but will track it over here: https://github.com/mavlink/MAVSDK/issues/984
