### ISSUE TITLE
Missing aid mask in EKF2

### ISSUE THREAD

**Issue by shabhu18** [PX4/Firmware#13905]
We use GitHub issues only to discuss PX4 bugs and new features. For
questions about using PX4 or related components, please use [PX4 Discuss](http://discuss.px4.io/).

Px4 version: 1.10
Bitmask: as in  developer guide 

    0: use GPS
    1: use optical flow
    2: inhibit IMU bias estimation
    3: vision position fusion
    4: vision yaw fusion
    5: multi-rotor drag fusion
    6: rotate external vision
    7: GPS yaw fusion
    8: vision velocity fusion

Bitmask displayed in QGC

    0: use GPS
    1: use optical flow
    2: inhibit IMU bias estimation
    3: vision position fusion
    4: vision yaw fusion
    5: multi-rotor drag fusion
    6: rotate external vision
    7: GPS yaw fusion
   

Missing Vision velocity fusion in QGC with version 1.10 . Am i missing something ?

Thanks!

**Comment by hamishwillee** [comment]
I thought perhaps the docs might be wrong, but it looks like this is definitely in the code: https://github.com/PX4/Firmware/blob/v1.10.0-rc3/src/modules/ekf2/ekf2_params.c#L604

**Comment by shabhu18** [comment]
Here are the screenshot of my QGC 
![Screenshot from 2020-01-13 10-44-52](https://user-images.githubusercontent.com/8255663/72234407-ec3d0080-35f2-11ea-8415-3322ebe5c1c9.png)
![Screenshot from 2020-01-13 10-45-40](https://user-images.githubusercontent.com/8255663/72234409-ee9f5a80-35f2-11ea-9eb8-0738c2ffa67e.png)

The list of ekf_aid_mask pram list are different . Is there any other way to enable it ??

**Comment by hamishwillee** [comment]
@bkueng Any ideas. The param is in a PX4v1.10rc but not in Firmware,

**Comment by bkueng** [comment]
You need to use QGC daily or upload the firmware via QGC to get the metadata.
Or you can use `Advanced settings` and directly set the value.

**Comment by hamishwillee** [comment]
@bkueng That sounds wrong. I thought there was a new QGC supposed to accompany every release?

**Comment by bkueng** [comment]
Yes there usually is.

**Comment by hamishwillee** [comment]
OK. Then closing this as resolved.
