### ISSUE TITLE
make fail because nuttx submodule

### ISSUE THREAD

**Issue by lfeng17** [PX4/Firmware#13923]
If I use git submodule update --init --recursive, it reports:

fatal: reference is not a tree: 4c2da2935399ca17eae0c9ad4e8822cb8efc2b0d
Unable to checkout '4c2da2935399ca17eae0c9ad4e8822cb8efc2b0d' in submodule path 'platforms/nuttx/NuttX/nuttx'

**Comment by dagar** [comment]
Can you provide more detail? Which version of PX4/Firmware?

**Comment by xdwgood** [comment]
yes,I encountered the same problem. 
I encountered this error when I tried to compile the latest master branch:
```
fatal: reference is not a tree: 4c2da2935399ca17eae0c9ad4e8822cb8efc2b0d
Unable to checkout '4c2da2935399ca17eae0c9ad4e8822cb8efc2b0d' in submodule path 'platforms/nuttx/NuttX/nuttx'
fatal: reference is not a tree: 4c2da2935399ca17eae0c9ad4e8822cb8efc2b0d
Unable to checkout '4c2da2935399ca17eae0c9ad4e8822cb8efc2b0d' in submodule path 'platforms/nuttx/NuttX/nuttx'

```
Latest master branch

**Comment by xdwgood** [comment]
same as issue: https://github.com/PX4/NuttX/issues/80

**Comment by xdwgood** [comment]
I try `git reset --hard  commit number` , Found that since this PR was merged, the problem occurred

https://github.com/PX4/Firmware/pull/13787

**Comment by julianoes** [comment]
Fixed.
