### ISSUE TITLE
macOS gazebo_sitl build broken after a Qt update

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#13950]
This is a heads up that currently the build of the gazebo plugins is broken after a `brew upgrade`.

With Qt 5.14 on macOS, I get the following:

```
cd /Users/travis/Firmware/build/px4_sitl_default/build_gazebo/include && /usr/local/opt/qt/bin/moc @/Users/travis/Firmware/build/px4_sitl_default/build_gazebo/include/moc_gazebo_video_stream_widget.cpp_parameters

usr/local/Cellar/tbb/2020_U0/include/tbb/tbb_profiling.:28: Parse error at "{"
```

More info:
https://github.com/PX4/homebrew-px4/pull/47
https://bugreports.qt.io/browse/QTBUG-80990
https://bitbucket.org/osrf/gazebo/issues/2681/moc-compilation-error-with-qt-514-tbb

I'm hoping that this will be resolved by a patch for Gazebo or Qt.

**Comment by LorenzMeier** [comment]
https://github.com/PX4/sitl_gazebo/pull/396
