### ISSUE TITLE
Camera feedback wiring documentation

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#13980]
Hi

There is not a documentation for camera feedback setting up , wiring and testing between camera and pixhawk autopilot pins .

https://github.com/mavlink/qgroundcontrol/issues/8216#issuecomment-575943525

**Comment by moreba1** [comment]
@Antiheavy 
Hi
do you know camera feedback setup ?

**Comment by moreba1** [comment]
https://github.com/PX4/Firmware/issues/8247
https://discuss.px4.io/t/camera-triggering-feedback/7764/5
https://discuss.px4.io/t/camera-feedback-wiring-and-setting/13569/5

**Comment by hamishwillee** [comment]
Camera triggering is documented in https://docs.px4.io/master/en/peripherals/camera.html . Hotshoe support has not been added (I believe - @DanielePettenuzzo can you please confirm?)

**Comment by moreba1** [comment]
@AuterionWrikeBot  @DanielePettenuzzo

**Comment by hamishwillee** [comment]
Yes, confirmed - hotshoe support not yet present. @DanielePettenuzzo will get it in at some point.

**Comment by moreba1** [comment]
@hamishwillee 
Can anyone else help?

**Comment by hamishwillee** [comment]
Nope. Essentially this feature does not exist, which sux because much of the work was done and has been allowed to lapse. 
So if you need really need this you might have to implement it yourself.

**Comment by hamishwillee** [comment]
This is going to be partially covered by this update: https://github.com/PX4/px4_user_guide/pull/781

Essentially prior to FMUv5 the camera capture feedback is provided via Other FMU PWM pin 6 (hardcoded) for camera capture. FMUv5 uses a hard coded point. The camera_trigger mavlink message gets emitted when the capture is triggered AND on capture.

For MAVLink cameras obviously things aren't wired up at all, but the camera emits a message when it captures.

**Comment by moreba1** [comment]
"Some cameras can provide image capture signaling to a flight controller camera-capture pin (this enables more accurate image timestamp than the time that the trigger command is sent)."

What is the requirement of signal of camera to capture pin ? can we connect the hot-shoe signal of the camera directly?

**Comment by hamishwillee** [comment]
@bkueng ^^^ https://github.com/PX4/Firmware/issues/13980#issuecomment-679241698

**Comment by bkueng** [comment]
> can we connect the hot-shoe signal of the camera directly?

Yes I think so. I've never done this myself though.

**Comment by moreba1** [comment]
> 
> 
> > can we connect the hot-shoe signal of the camera directly?
> 
> Yes I think so. I've never done this myself though.

Where is related code? I will see that how signal input defined? (voltage pulse change value )

**Comment by hamishwillee** [comment]
I've updated the docs in https://github.com/PX4/px4_user_guide/pull/807

The simple answer is that you cannot just connect a hotshoe direct to the  camera capture pin because the voltage levels are not likely to be compatible. There are however hotshoe adapters that you can use.

I believe the info is now correct though I have a final request for confirmation of the voltage level the pin expects: https://github.com/PX4/px4_user_guide/pull/807#issuecomment-700316410
