### ISSUE TITLE
navigator bug: "Takeoff to x meters above home." after mission ended

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#14011]
When navigator executes a mission with a landing waypoint, **after** the mission ends, QGC shows "Takeoff to x meters above home.".
Reproducible 100% in SITL.

**To Reproduce**
1. simple mission with landing waypoint at the end
2. run the mission and wait until landed and disarmed

The problem is that navigator resets the mission after disarming (`need_to_reset_mission()`), and then already sets the first mission item again (`set_mission_items()`), which leads to a user message. We can defer calling `set_mission_items()` until we're armed again, but then mc_pos_control goes into failsafe with a warning (which I don't think it should, as it's disarmed) and I want to avoid unnecessary complex logic.

It's not clear to me why navigator does not just switch to land mode, as it does for RTL.
RTL does not have that issue because of the mode switch.

**Comment by dagar** [comment]
@RomanBapst any input here (given you've just been through this logic)?
