### ISSUE TITLE
Periodic cutoff of local position from EKF2

### ISSUE THREAD

**Issue by ashwinsushil** [PX4/Firmware#14137]
**Describe the bug**
I am observing periodic cutoff of local position data from the EKF2 with the setup as mentioned below. 

At the cut-offs, the optical flow is giving valid data.

**Setup**
1. Intel aero drone
2. PX4 v1.9.2 with PX4Flow driver enabled
3. Px4Flow
4. Parameters:
  * EKF2_AID_MASK = 2 (Optical flow)
  * EKF2_HGT_MODE = Barometer
 5. Teraranger One data sent from a computer companion to FCU through mavros.

**To Reproduce**
Steps to reproduce the behaviour:
1. Flash an intel aero drone with v1.9.2 PX4 firmware with PX4 driver enabled.
2. Connect PX4Flow over the telemetry port on the intel aero drone.
3. Visualize the local_position data on QGroundControl
4. Initially, the local position data gives good data then the periodic cut-off starts after 10-30 secs or so.

**Screenshots**
![image](https://user-images.githubusercontent.com/34656643/74168687-641a3d00-4c2a-11ea-9519-f4471e4eb408.png)

**Logs**
Here are the [logs](https://review.px4.io/plot_app?log=9ef87b3b-5ed0-456b-9589-342e9630713a).

The .ulg file can be found here [intel-ulg-file.tar.gz](https://github.com/PX4/Firmware/files/4184783/intel-ulg-file.tar.gz).

I was hoping someone could provide some suggestions to start debugging this issue.
Ashwin

**Comment by julianoes** [comment]
This looks indeed very wrong. Could it be that the flow orientation is incorrect or something trivial like that?

**Comment by ashwinsushil** [comment]
Hey, @julianoes  I usually use an IRIS+ drone for R&D. Checked the mounting/physical-orientation on the IRIS+ and the SENS_FLOW_ROT is set to Yaw 270(default) which seems to be working well. The intel drone (which is having this issue) is set up exactly the same way. So I don't think it is the orientation. 

Additional info: I am getting good data on the OPTICAL_FLOW_RAD.integrated_x and OPTICAL_FLOW_RAD.integrated_y when this phenomenon occurs.

For those who are interested to know about the mounting of PX4flow [here](https://docs.px4.io/v1.9.0/en/sensor/px4flow.html#mountingorientation) is the link

**Comment by julianoes** [comment]
I would suggest to use master because some improvements for flying with Flow have been merged but I'm not sure if master still works on Intel Aero. The problem is that Intel Aero is not supported anymore by Intel.
