### ISSUE TITLE
EKF does not switch to secondary GPS if main fails

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#14223]
**Describe the bug**
If a vehicle has two GPS modules connected and the main one fails while it has a higher fix type than the secondary GPS the EKF will not switch to only use the secondary GPS but stop fusing GPS completely.

**To Reproduce**
Collect a replay logfile with a vehicle using two GPS modules. Stop publishing of the first GPS module when it has a higher fix than the secondary GPS

![image](https://user-images.githubusercontent.com/7795133/75173236-dca2f280-572e-11ea-8a6d-73f9f5f60b78.png)

**Expected behavior**
The EKF should switch to only use the secondary GPS

**Additional context**
https://github.com/PX4/Firmware/blob/f3fefd7d9372ec98d404e2e99da2e251114a2d7e/src/modules/ekf2/ekf2_main.cpp#L953-L988

The problem is that `_gps_state[0].fix_type` is never updated after the GPS failure so `_gps_select_index` will never be set to one

**Comment by CarlOlsson** [comment]
It also happens the other way around, and even if the GPS modules have the same fix type

**Comment by julianoes** [comment]
FYI @DanielePettenuzzo

**Comment by CarlOlsson** [comment]
solved by https://github.com/PX4/Firmware/pull/14278
