### ISSUE TITLE
Error while simulating px4 using gazebo simulator on ubuntu 18.04 linux

### ISSUE THREAD

**Issue by Sneha-hub115** [PX4/Firmware#14225]
Hi,
I'm getting the following issues while simulating px4 using gazebo simulator on ubuntu 18.04 linux. I followed the instructions from here: ([http://dev.px4.io/v1.9.0/en/setup/dev_env_linux.html]. Please let me know the solution for this issue.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_LIBRARIES (ADVANCED)
    linked by target "gazebo_vision_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_uuv_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_lidar_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_geotagged_images_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_controller_interface" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "sensor_msgs" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_sonar_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_opticalflow_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "std_msgs" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_imu_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_opticalflow_mockup_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "mav_msgs" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "nav_msgs" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_wind_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "physics_msgs" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_gimbal_controller_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_mavlink_interface" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_motor_model" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_catapult_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_multirotor_base_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_magnetometer_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_barometer_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_gst_camera_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_irlock_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_gps_plugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "gazebo_video_stream_widget" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo
    linked by target "LiftDragPlugin" in directory /home/unicita/src/Firmware/Tools/sitl_gazebo

-- Configuring incomplete, errors occurred!
See also "/home/unicita/src/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
See also "/home/unicita/src/Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeError.log".
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-configure 
cd /home/unicita/src/Firmware/build/px4_sitl_default/build_gazebo && /usr/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DSEND_VISION_ESTIMATION_DATA=ON -GNinja /home/unicita/src/Firmware/Tools/sitl_gazebo && /usr/bin/cmake -E touch /home/unicita/src/Firmware/build/px4_sitl_default/external/Stamp/sitl_gazebo/sitl_gazebo-configure
ninja: build stopped: subcommand failed.
Makefile:205: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1

Thanks!

**Comment by julianoes** [comment]
```
NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_LIBRARIES (ADVANCED)
```

You are missing some gstreamer dependencies. I would suggest to re-run the setup script as described here:
https://dev.px4.io/master/en/setup/dev_env_linux_ubuntu.html#sim_nuttx

**Comment by Sneha-hub115** [comment]
Thank you.
