### ISSUE TITLE
Mag/baro rates in SITL unrealistic

### ISSUE THREAD

**Issue by jkflying** [PX4/Firmware#14220]
SITL gazebo sensor rates are very different from real hardware. Baro, mag etc are all published at 250Hz, the same as the gyro/accel, instead of ~50Hz as real sensors would do.

Why is this an issue?

- It makes eg. profiling difficult.
- Vehicles behave differently

**Comment by LorenzMeier** [comment]
That indeed seems like a pretty significant thing to change to improve SITL. @TSC21 publishing every 5th measurement seems like a trivial change and it would be great to see this being executed swiftly.

**Comment by TSC21** [comment]
Tomorrow is done.
