### ISSUE TITLE
EKF2: GPS blending offset not decreased to zero if one module lose fix

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#14232]
**Describe the bug**
When using GPS blending we calculate a position offset to apply to each measurement in order to smooth out the data we push into the EKF in case of fast varying GPS accuracy metrics. However, if one GPS module lose fix we don't decrease this value but keep applying the last calculated offset indefinetly.

**To Reproduce**
Collect a replay logfile with two GPS modules connected. During replay, force one GPS module to lose fix.

**Expected behavior**
The GPS data we push into the EKF should converge to the GPS module still working if the other lose fix.

**Log Files and Screenshots**
A horizontal position offset is added to one GPS module to more easy illustrate the issue. At t=100s the main GPS lose fix.
![image](https://user-images.githubusercontent.com/7795133/75258979-95c50380-57e7-11ea-85bf-093f65bbd32c.png)

**Comment by julianoes** [comment]
@DanielePettenuzzo is this the same that you found?

**Comment by DanielePettenuzzo** [comment]
I'm not sure. They could be related

**Comment by CarlOlsson** [comment]
solved by https://github.com/PX4/Firmware/pull/14278
