### ISSUE TITLE
logger module generates incompatible timestamp for logger_status message

### ISSUE THREAD

**Issue by priseborough** [PX4/Firmware#14230]
This line

https://github.com/PX4/Firmware/blame/master/src/modules/logger/logger.cpp#L817

generates timestamps during ekf2 replay for the logger_status.timestamp that uses a different datum to the other log messages. The result is that when two commonly used plotting packages FlightPlot and Flight Review are used, the time axis displayed expands to a range that makes the plots unreadable.

This could be avoided if logger_status.timestamp was obtained from the time stamp of the last message processed when logging replay data.

**Comment by dagar** [comment]
It's maybe a bit of a hack, but replay is already a special build time option, so I think we can just skip logger_status entirely in that case.

In general I'm trying to get to timestamps per message being actual uORB metadata corresponding to publication time (atomically) and not whatever timestamp we slap on or propagate through. I'll keep replay in mind before proposing anything on that front.
