### ISSUE TITLE
EKF2: GPS blending seems to give wrong output for fast changing position meas.

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#14251]
**Describe the bug**
If the position measurement of one GPS module changes fast the output of the blending algorithm gives a faulty output

**To Reproduce**
Here is a replay logfile with two GPS modules connected. At t=80s a position offset is added to gps0 (blue). The red line is the internal GPS blended state and the green line is the output of the blending algorithm that we push into ECL
![image](https://user-images.githubusercontent.com/7795133/75425029-2d3e6980-5942-11ea-89fd-2f5675600661.png)

**Expected behavior**
The offset between the output signal and the internal blended gps state should be monotonically decreasing.

**Additional context**
The issue seems to originate from the fact that we account for the blending weights twice, once in the calculation of the offset between the _gps_output[0-1] and the _gps_blended_state, and once in the offset between the _gps_output[2] and the _gps_blended_state

**Comment by bresch** [comment]
FYI @DanielePettenuzzo

**Comment by CarlOlsson** [comment]
solved by https://github.com/PX4/Firmware/pull/14278
