### ISSUE TITLE
How to stabilize the quadrotor using matlab simulink to change firmware

### ISSUE THREAD

**Issue by islamdib** [PX4/Firmware#14266]
Hello,
I've tried to change in Pikhawk firmware using Qt but I didn't understand how to do.
Now Im working with simulink. In Mathworks there are non response to quastions about this topic.

My problem is that rotors haven't the same speed. so I think that I have to change PID parameters in the first part. I don't know where to find original PID paramaters in order to change them.

In the second part , I didn't understand the command calculation formula:
idle_PWM = uint16(1000);
% Quad X
 M1 = uint16(((Roll + Pitch - Yaw) / 2 * Thrust + Thrust) * single(1000)) + idle_PWM;
 M2 = uint16(((-Roll + Pitch + Yaw) / 2 * Thrust + Thrust) * single(1000)) + idle_PWM;
 M3 = uint16(((-Roll - Pitch - Yaw) / 2 * Thrust + Thrust) * single(1000)) + idle_PWM;
 M4 = uint16(((Roll - Pitch + Yaw) / 2 * Thrust + Thrust) * single(1000)) + idle_PWM;

I will be hopefull if you help me.
Thank you in advance.

![Capture](https://user-images.githubusercontent.com/56603746/75611401-8660f580-5b1a-11ea-985c-f65240c44a9e.PNG)

**Comment by mhkabir** [comment]
Please use discuss.px4.io for questions.
