### ISSUE TITLE
Latest Stable 1.10.1 can't bootup on fmuv3

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#14361]
Tested with Holybro the latest stable 1.10.1 can flash on 3DR Pixhawk Mini & Holybro Pix32 w/ fmuv3 bl, but can't bootup
![image](https://user-images.githubusercontent.com/4748411/76387889-cf2e6f00-63a2-11ea-8c34-e5862232e2c7.png)

**Comment by julianoes** [comment]
@bys1123 any way you could get the console boot log? Or `dmesg` output?

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/77784022-cc1aca80-7094-11ea-9abc-c17df2a80184.png)
@julianoes

**Comment by julianoes** [comment]
Seems like the IO fails to connect. Can you try to boot it up while keeping the safety button pressed to force an IO update?

**Comment by bys1123** [comment]
@julianoes It works, is this normal? or maybe need some change in code?

**Comment by julianoes** [comment]
@bys1123 so now it works? No it's not normal, it shouldn't happen :confused:.

**Comment by bys1123** [comment]
@julianoes Yes, keep press safety button on bootup will work. if not , autopilot will not bootup after firmware flash.

**Comment by julianoes** [comment]
Ok, so even after it has once flashed correctly. Odd. Is that only the case with this hardware or can you reproduce with other hardware as well?

I can try to reproduce with my old Pixhawk here, not sure if that would be the same.

**Comment by bys1123** [comment]
reproduced on lots of fmuv3

**Comment by bys1123** [comment]
Also get few report say 1.10.1 can running on their 3DR Pixhawk mini

**Comment by julianoes** [comment]
I've tried stable on a Pixfalcon which is still fmu-v2 and `px4io status` worked for me once I had a airframe selected (quadcopter). `px4io` was not started without a aiframe selected. I'm not sure if that's supposed to be that way or if it's a bug.
