### ISSUE TITLE
distance_sensor tfmini can't work

### ISSUE THREAD

**Issue by jinchengde** [PX4/Firmware#14368]
**Describe the bug**
FW version 1.10.1 work good
in master , tf mini can't get the data from MAVLINK, no distance sensor
![image](https://user-images.githubusercontent.com/5361334/76492233-b12c4180-646a-11ea-96aa-1ec4554d6eaf.png)
and listener the distance_sensor 
![image](https://user-images.githubusercontent.com/5361334/76492293-cef9a680-646a-11ea-9406-2155c080756b.png)
the current_distance in topic can't change any more if you move the distance sensor

**Comment by 473867143** [comment]
My TFMiNi can work well.
To reproduce:
1. take a newly flashed Pixhawk4 board with PX4 1.10.0 stable
2. Plug TFMiNi LIDAR to Serial 4 port (UART &I2CB)
3. Connect the board to USB
4. Launch QGC, set SENS_TFMINI_CFG to 'TELEM/SERIAL 4 ', and set EKF2_HGT_MODE to 'Range sensor',finaly reboot the board.
5. Open analyze widget, the distance sensor variable will be present.

![image](https://user-images.githubusercontent.com/26379380/77138943-f249d480-6aae-11ea-9db8-61d8b061e16c.png)

hopefully it helped you!

**Comment by jinchengde** [comment]
> My TFMiNi can work well.
> To reproduce:
> 
> 1. take a newly flashed Pixhawk4 board with PX4 1.10.0 stable
> 2. Plug TFMiNi LIDAR to Serial 4 port (UART &I2CB)
> 3. Connect the board to USB
> 4. Launch QGC, set SENS_TFMINI_CFG to 'TELEM/SERIAL 4 ', and set EKF2_HGT_MODE to 'Range sensor',finaly reboot the board.
> 5. Open analyze widget, the distance sensor variable will be present.
> 
> ![image](https://user-images.githubusercontent.com/26379380/77138943-f249d480-6aae-11ea-9db8-61d8b061e16c.png)
> 
> hopefully it helped you!

yes, the stable version is OK(include v1.10.1), but the develop versin in master can't work.

**Comment by bkueng** [comment]
This should be fixed in https://github.com/PX4/Firmware/pull/14423. @jinchengde can you test master again?

**Comment by jinchengde** [comment]
@bkueng it works

**Comment by bkueng** [comment]
Thanks for testing. Closing this.
