### ISSUE TITLE
QGC freezes if I build my modified px4 firmware with px4_fmu-v5_defualt 

### ISSUE THREAD

**Issue by Mitchell-Lee-93** [PX4/Firmware#14376]
Hello,

I modified the px4 code to make a flight controller for 6DOF tilting hexacopter. 
The modified code had no problem with QGC when I used pixhawk2(make with 'fmu-v3_default'), but if I use pixhawk4(make with 'fmu-v5_default'), QGC freezes. 

To fix it, I changed 'fmu-v5_default' to make it almost the same with 'fmu-v3_default' but still didn't worked
With some tests, I figured it out that it is related to 'mixer' inside SYSTEMCMS at 'fmu-v5_default'.
It only works well with QGC if I exclude the 'mixer'. The funny thing is 'fmu-v3_default' also has 'mixer' inside SYSTEMCMS and it's working fine with QGC.

Would you give me any help with this? For information, I made a bit change with the mixer in the lib directory. To reduce the flash memory, I erased all the unused '.toml' files and deleted 'HelicopterMixer, NullMixer and SimpleMixer' files which were also unused. Also, I changed related source files and CMake files. But not sure it makes the problem since it seems to be working well with pixhawk2.

Thank you in advance,
Best,
HG LEE

**Comment by julianoes** [comment]
Can you describe what exactly happens when "QGC freezes"? And can you document the steps how I could reproduce this? Thanks.
