### ISSUE TITLE
v1.11.0 Release Notes

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#14402]
# v1.11 Release Notes

Following the great stability improvements on v1.10, the PX4 team is preparing for a new release which will see lots of quality of life improvements, as well as internal robustness in the system architecture to allow for easier board configuration.

# Release Notes
## Highlights
* Major sensor calibration improvements ([Gyro](https://github.com/PX4/Firmware/pull/13632), [Mag](https://github.com/PX4/Firmware/pull/13623), [Level](https://github.com/PX4/Firmware/pull/13666))

### Migration Guide
* **DEPRECATED:** VTOL is no longer supported in FMUv2 hardware
### Hardware Support
* [Holybro Durandal](http://docs.px4.io/master/en/flight_controller/durandal.html), (Manufacturer Supported)
* [NXP IMX-RT, S32K](https://nxp.gitbook.io/ucans32k146/), (Manufacturer Supported)
* [Holybro PIX32V5](http://docs.px4.io/master/en/flight_controller/holybro_pix32_v5.html), (Manufacturer Supported)
* [Cube Yellow](http://docs.px4.io/master/en/flight_controller/cubepilot_cube_yellow.html), (Manufacturer Supported)
* [Cube Orange](http://docs.px4.io/master/en/flight_controller/cubepilot_cube_orange.html), (Manufacturer Supported)
* [CUAV X7](http://doc.cuav.net/flight-controller/x7/en/), (Manufacturer Supported)
* [CUAV X7 Pro](http://doc.cuav.net/flight-controller/x7/en/x7-pro.html), (Manufacturer Supported)
* [CUAV Nora](http://doc.cuav.net/flight-controller/x7/en/nora.html), (PR #15536) (Manufacturer Supported)
### Drivers
* Enable SPI DMA adds centralized DMA map (PR #14207)
* Move primary IMU to new InvenSense driver (PR #14356)
  * FMUv5, FMUv5x
  * ModalAI_fv-v1
* Drivers CLI interface consolidation (PR  #14386 )
### System Architecture
* Board config simplifications for SPI & I2C (PR #14221) and PWM timers (#13871)
* Adds UAVCAN node `cannode` (PR #14148)
* Adds CAN interface runtime (PR #14367)
### Multicopter
* New hover thrust estimator (PR #13981)
* XYZ-synchronized motion in auto modes (diagonal climb) (PR #13596)
* New Notch filter (PR #13549)
* Acceleration feedforward (PR #14212)
* Mag power compensation (PR #14457, [Docs](https://docs.px4.io/master/en/advanced_config/compass_power_compensation.html))
* Takeoff failure detection (PR #14428, [Docs](https://docs.px4.io/master/en/config/safety.html#failure_detector))
* Horizontal velocity limit close to ground (PR #13561, [Parameter](https://dev.px4.io/master/en/advanced/parameter_reference.html#MPC_LAND_VEL_XY))
### VTOL
* Tiltrotor: Use tilt to accelerate the vehicle forward while in hover (PR #13779)
* Weather vane improvements (PR #13782)
* Active path and deceleration tracking during transitions (PR #14405)
### Fixed Wing
* Improved airspeed failure detection (PR #12353)
* Enables fallback estimation without airspeed sensor. (PR #12887)
### Rover
* Major improvements to offboard control
* Enable offboard attitude setpoints (PR #13323)
* Enable offboard velocity setpoints (PR #13225)
* Enable ActuatorControl setpoints in offboard mode (PR #13314)
### Underwater Vehicles
* New mixers for underwater vehicles Generic & HippoCampus (PR #14079)
* New UUV default specific parameters and autostarting (PR #14079)
* New Mixer for UUVs with X-shaped thruster configuration (PR #14079)
* New `uvv_att_control` controller for UUV attitude control (PR #14079)
### PX4/ECL - Estimators improvement
* Emergency Yaw recovery using EKF-GSF estimator (PR PX4/ecl#766)
* Pre-flight accel bias estimation stability fixes (PR PX4/ecl#818)
### Onboard computer / middleware improvements
* Adds ROS 2 Dashing and Eloquent support to the microRTPS bridge (PR #13907)
* Adds ROS 2 Foxy support to the microRTPS bridge (PR #15227}
* Adds time sync to the microRTPS bridge (PR #14297)
* UART link data stream fixed in the microRTPS bridge (PR #15354)
### PX4/Avoidance
* Smoother flight planning with improved repeatability (PR PX4/Avoidance#555)
* Bezier trajectory avoidance interface (PR #14279)
* Bugfixes and improvements
### Simulation
* Multi-Vehicle simulation with Gazebo
* Adds support for multiple distance sensor instances. (PR #14143)
* Adds support for UUV vehicles. (PR #14079)
* Adds support for boats. (PR PX4/sitl_gazebo#409 )
* Adds Catapult and Hand launch support for fixed-wing. (PR PX4/sitl_gazebo#393 )
### Failsafe / Commander / Navigation improvements
* New Hover Thrust estimator (PR #13981)
* Commander, Navigator state clean-up (PR #14307)
* Navigator fixes heading drift after takeoff (PR #13965)
* Enable RC-Override in Take-off (PR  #14022)
* Takeoff failure detection (PR #14428)
* Pre-flight check: Disable mag field strengh check via parameter (COM_ARM_MAG_STR) (PR #13766)
### Failsafe / Commander / Navigation improvements
* New Hover Thrust estimator (PR #13981)
* Commander, Navigator state clean-up (PR #14307)
* Navigator fixes heading drift after takeoff (PR #13965)
* Enable RC-Override in Take-off (PR  #14022)
* Takeoff failure detection (PR #14428)
* Pre-flight check: Disable mag field strengh check via parameter (COM_ARM_MAG_STR) (PR #13766)
### OS/NuttX
The release includes a change from [NuttX-7.29 ](https://bitbucket.org/nuttx/nuttx/src/101f3bddecb70cfb8dc78c5b4fad98f3480ae399/ReleaseNotes#lines-21789) to [NuttX-8.2](https://bitbucket.org/nuttx/nuttx/src/efff9b9438e69ea6c70e879b7ee4d49bff1b0988/ReleaseNotes#lines-25651)
See [NuttX release notes](https://bitbucket.org/nuttx/nuttx/src/efff9b9438e69ea6c70e879b7ee4d49bff1b0988/ReleaseNotes#lines-25651) for the details of changes in NuttX-8.2 details.

Included as backports are:
* STM32[F4 F7 H7]
  * spi_exchange (no DMA) with for STM32xx_SPI_DMATHRESHOLD
* STM32[F7 H7]
  * SDMMC internal pull up usage fixed 
  * Add check_format tooling 
  * nxstyle - output compiler like error format
* STM32H7
  * fix stm32h7x3xx_dmamux.h: add missing underscore to defines
* STM32F7
  * stm32f7:Add Serial Tx DMA 
  * stm32f7:ethernet: Add some delays so that ifup() does not
* NXP IMX-RT, S32K
  * S32K add support for Nxp drone boards
  * imxrt: Adds the ability to run from OCRAM
  * imxrt: Add USB Device support for i.MX RT
  * imxrt: added missing i2c prescale mask
  * imxrt: interrupt serial storm, add DTCM and set up I and
  * imxrt: Allow clock setting for SPI and I2C from board.h.
  * imxrt:lpi2c Fix interrupt storm on failed write. 
  * imxrt:lpi2c ensure that on an error status reflects it. 
  * imxrt:lpi2c imxrt_lpi2c_reset uses GPIO with SION 
  * imxrt:gpio Support readback on OUT GPIO 
  * imxrt1020-evk: Enable the GPIO based CD.
  * imxrt:lpspi: Fixed race on register setting. 
  * imxrt:lpspi: Remove hack setting LPSPI1 daisy irrespective 
  * imxrt:lpi2c.c:Added configurations to fine tune LPI2C Time 
  * IMXRT106x USDHC: Support regular GPIO for CD and inversion. 
  * IMXRT106x:pinout add ALT 8 GPIO_GPT2_COMPARE3 & fix GPIO_G 
  * IMXRT106x:pinout add ALT 8 GPIO_GPT1_CAPTURE[1|2] 
  * Kinetis renamed TJA1100 to TJA110X registers

## v.1.11.0 Changelog

https://gist.github.com/mrpollo/7173f6c89d2fdacb923eb4481b486e41

**Comment by bresch** [comment]
I'm not exactly sure what should go under "Highlights". Shouldn't be the "overall best improvements and new features" ?
Enable RC-Override in Take-off (PR #14022) and Pre-flight check: Disable mag field strengh check via parameter (COM_ARM_MAG_STR) (PR #13766) are minor modifications and shouldn't be here.


Other comments:
> Emergency Yaw recovery using EKF-GPS estimator

EKF-**GSF**

> Navigation improvements

**Navigator** improvements

> New hover thrust estimator (

https://github.com/PX4/Firmware/pull/13981

**Comment by jinger26** [comment]
Is "Computer Vision & Autonomy" redundant to "PX4/Avoidance"?

**Comment by mrpollo** [comment]
Thanks for the edits @bresch, please let me know if the changes work for you.

@jinger26 Yes. A remnant of the last release notes, not sure I remember what was going on there right now. Take a look `->` [PX4 v1.10.0](https://github.com/PX4/Firmware/releases/tag/v1.10.0). It's gone now, thank you.

**Comment by mrpollo** [comment]
add to notes please 

https://github.com/PX4/Firmware/pull/14473

**Comment by mrpollo** [comment]
add to notes please

https://github.com/PX4/Firmware/pull/14405

**Comment by mrpollo** [comment]
update notes 

https://github.com/PX4/Firmware/pull/14473

**Comment by ThomasRigi** [comment]
Is dual battery support in v1.11? https://github.com/PX4/Firmware/pull/12551 and https://github.com/PX4/Firmware/pull/12034 

They're not in the list (yet)

**Comment by hamishwillee** [comment]
@mrpollo FMI is this ever going to release?

**Comment by jinger26** [comment]
Add to supported hardware:
Holybro PIX32V5
HEX Yellow/Orange?
CUAV X7, X7Pro, Nora?

verify with @dagar

**Comment by mrpollo** [comment]
Thanks, everyone, the release notes are finally complete.
