### ISSUE TITLE
Return To Home failure

### ISSUE THREAD

**Issue by NicoNelli** [PX4/Firmware#14466]
Hi everyone,

I wanted to test the RTL using my VTOL Quad Tailsitter and I was on branch master. When I called the RTL, the vehicle was in FW. So the vehicle started going back and then it did the transition back to MC just before landing (till now everything was fine). The vehicle started going down (2 m) and it started drifting horizontally. I called again the RTL and it reached again the return point, it went down a bit and then it drifted again. The third times I triggered the RTL everything was fine and the vehicle landed. I repeated this several time and always the same behaviour. 
Could you please give me some advices about this strange behaviour ?
Thanks to everyone, I also shared here the logs.  

https://logs.px4.io/plot_app?log=5056e92a-e9a8-47bd-9581-34669d4f7158

**Comment by julianoes** [comment]
FYI @RomanBapst

**Comment by RomanBapst** [comment]
@NicoNelli I think you have a problem with your remote control. The channel mapped to RTL glitches once in a while and would explain why the vehicle goes out of RTL.
![image](https://user-images.githubusercontent.com/7610489/77647219-1443cb00-6f77-11ea-8204-f6d399c74e28.png)

**Comment by NicoNelli** [comment]
Thanks @RomanBapst for the quick reply. I did that in purpose. 
The very first time I called the RTL i saw the drone drifting. 
Based on that I said: let's try to call again and again the RTL and see what happens.
Accordingly I did again the test and after calling three times the RTL the vehicle was able to land successfully.

**Comment by RomanBapst** [comment]
@NicoNelli So is there still an issue or can we keep this closed?

**Comment by NicoNelli** [comment]
@RomanBapst there is still the issue. 
Maybe I did not explain it in a very good way but the spikes that can be seen in the RTL channel actually were triggered by me. During a flight test, I called the RTL and the drone started going back and when it reached the landing point, it descended for ~ two meters and it drifted. I retriggered again the RTL and same behaviour. The third time I triggered the RTL the drone landed successfully.
![position_x](https://user-images.githubusercontent.com/39304410/77998400-554e2d80-7331-11ea-8eb7-043473417454.png)
![position_z](https://user-images.githubusercontent.com/39304410/77998422-6139ef80-7331-11ea-94bc-d8bae97bf44f.png)

Looking at the local positions x and z for instance, we can see that after I triggered the RTL the drone went down and then it drifted. The third time I triggered the RTL the drone landed.

**Comment by NicoNelli** [comment]
@RomanBapst do you have suggestions in that matter ? Thanks a lot

**Comment by dayjaby** [comment]
I observed the same fault (https://discuss.px4.io/t/drone-flies-away-during-rtl/15373). Firmware version: 1.9.2 with slight modifications (but nothing RTL related) on a hexacopter (no vtol!)

Which firmware version did you use?

![Screenshot from 2020-04-11 16-50-17](https://user-images.githubusercontent.com/164396/79047077-d43a4480-7c14-11ea-80f3-9a4db557ef67.png)

**Comment by dagar** [comment]
If there's still a problem here could you please validate against current PX4 and open a new issue with logs?

**Comment by dayjaby** [comment]
@dagar In our case it stopped occuring in a long time and we had now several months of good test flights on the same firmware version, the same location. On some days however (~october 2019), it happened frequently.

In my log, it didn't drift out of RTL, but the estimation drifted away (and also the drone in reality), even though the setpoint remained constant.

**Comment by NicoNelli** [comment]
@dagar ok I will do it. Thanks a lot

**Comment by dayjaby** [comment]
https://github.com/PX4/Firmware/issues/13956 has the same kind of drift during RTL.

**Comment by dagar** [comment]
> #13956 has the same kind of drift during RTL.

Thanks @dayjaby. I've added https://github.com/PX4/Firmware/issues/13956 as a v1.11 release blocker. Any additional data or testing you can add to the issue usually doesn't hurt.
