### ISSUE TITLE
Error: No module named packaging when using catkin build

### ISSUE THREAD

**Issue by ashirsat** [PX4/Firmware#14506]
Hi,

I am trying to build PX4 Firmware tags/v1.10.0 on ubuntu 18.04 running ros-melodic.

I am unable to build the package using catkin build.

I have checked that I have installed packaging module from python3.
Any clue on how to resolve this issue?

Thanks

**Comment by TSC21** [comment]
If you are building with catkin then you need Python2.

**Comment by ashirsat** [comment]
Hey @TSC21 ,
That solved my issue. 

Thanks!!
