### ISSUE TITLE
Questions about the algorithm of ekf2 in Px4 firmware 

### ISSUE THREAD

**Issue by yefeng93** [PX4/Firmware#14511]
I have a question about the ekf2 algorithm in Px4 firmware, that is, what measurement is used to fuse pitch and roll attitude in ekf2. For example, the previous EKF can use accelerometer and gyroscope fusion to output pitch roll attitude, but there is no accelerometer involved in the fusion in ekf2.

**Comment by CarlOlsson** [comment]
Hi!
The IMU data is considered inputs in EKF2 so you are right, accelerometer and gyroscope data is not fused as measurements, but it is still used to infer the attitude of the vehicle (in combination with all other sensors)
If you have any more questions don't hesitate to ask on the [forum](https://discuss.px4.io/)
