### ISSUE TITLE
Threads not found

### ISSUE THREAD

**Issue by pradhannihar** [PX4/Firmware#14516]
I am trying to include a TensorFlow compiled file of my model, into px4. The compiled fill uses google's absl library which further uses Threads lib. While everything works fine for SITL, I am getting "Thread not found" error during building the code for fmu-v3.

**Comment by julianoes** [comment]
I would argue that's not really an "issue" as such with PX4 code. It's more that you are trying to add functionality and you ran into problems doing so.

I suggest to ask questions like this in the forum: discuss.px4.io. And when you do so, please add some more information, such as the console output, and also check where this "thread check" happens in the code that you added.
