### ISSUE TITLE
Arming State Machine unexpected cases "Transition denied:"

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/Firmware#14527]
**Describe the bug**
The arming state machine 
https://github.com/PX4/Firmware/blob/73f7243bc8350664864685d1a0adbeaaa2f2c5e5/src/modules/commander/state_machine_helper.cpp#L59-L73
is working and unit tested but in some use cases the state machine can get called with illegal transitions and the user is presented with an unexpected message saying "Transition denied:" from
https://github.com/PX4/Firmware/blob/73f7243bc8350664864685d1a0adbeaaa2f2c5e5/src/modules/commander/state_machine_helper.cpp#L237

This issue tries to track those cases since they seem to unveil common problems.

**To Reproduce**
- `Transition denied: SHUTDOWN to INIT` / `Transition denied: SHUTDOWN to ARMED`
1. Power drone with battery and power module such that it measures a battery voltage and state
2. Plug autopilot to computer via USB
3. Unplug battery
4. The autopilot tries to shutdown but the board doesn't support shutdown (tested on a Pixhawk 4).
5. ![image (2)](https://user-images.githubusercontent.com/4668506/77922850-e07fe280-72a1-11ea-87d2-eb462f476355.png)
6. The autopilot is in SHUTDOWN state and any attempt to calibrate or arm will trigger one of the messages.

- `Transition denied: ARMED to INIT`
https://github.com/PX4/Firmware/issues/14158 describes this case
1. Arm and start flying the drone
2. Open the Radio tab in QGC
3. 
![image](https://user-images.githubusercontent.com/4668506/77923727-1d98a480-72a3-11ea-9883-d65a6d1722e9.png)

- `Transition denied: ARMED to SHUTDOWN`
(That one I'm not sure if it got solved already.)
1. Use a power supply to bench test your drone or configure the battery to be completely empty before it actually is to avoid damaging any battery
2. Bench test arm and start flying the drone
3. Let the battery deplete completely by lowering the voltage of the supply or getting into a critical battery state through configuration.
4. The drone can attempt to shut down in air

**Expected behavior**
The guards for the transitions and the messaging that enables debugging should stay as they are since they prevent further safety-critical problems. But the calls to the state machine should be revised such that it's highly unlikely the user is ever bothered with a transition guard message.

**Comment by tacdin** [comment]
I'm having the same problem. I would be glad if you can direct the developers and users. It is very frustrating to get this error. No operations can be performed.

**Comment by dagar** [comment]
Should be fixed by https://github.com/PX4/Firmware/pull/14825.

**Comment by MaEtUgR** [comment]
It is, see https://github.com/PX4/Firmware/pull/14825#issuecomment-624658878
