### ISSUE TITLE
fmu-v4_cannode stuck in boot loop

### ISSUE THREAD

**Issue by JacobCrabill** [PX4/Firmware#14547]
Sometime recently the cannode build target for the Pixracer (fmu-v4) was broken.  It will boot, but upon connecting a Zubax Babel board to the CAN port, the Babel will show that the cannode gets stuck in an infinite reboot loop.  It will briefly show up as initializing, then power off and disappear from the UAVCAN GUI, show up again as initializing, etc.

This commit still works: [pull/14444/d14fc944](https://github.com/PX4/Firmware/pull/14444/commits/d14fc944c0a1eb185173fd607e429bb5178ce85b)

But as of last Friday at least (and I tried yesterday as well) master does not work.

@dakejahl

**Comment by dakejahl** [comment]
Can you describe your test setup? I just tested this on a Pixracer with a GPS attached and everything works as expected.

**Comment by JacobCrabill** [comment]
Hmm.  Using commit [2b82b471](https://github.com/PX4/Firmware/commit/2b82b471c1ec4baf9fa4aeacb6788bf0109c1db4)? I'll give that another try.

**Comment by dakejahl** [comment]
Yup whatever the latest commit is

**Comment by JacobCrabill** [comment]
Still doesn't work for me; I just get this in the UAVCAN GUI when connected to a Babel:
![image](https://user-images.githubusercontent.com/5885545/78063063-7409ef80-7344-11ea-9fd4-9c57458a97e4.png)

It stays in the "INITIALIZATION" mode for a second or two then goes away.  And now after a few minutes, it's no longer rebooting itself at all is doesn't appear on the CAN bus at all.

Using an mRobotics Pixracer; brand-new purchase from last week.

**Comment by JacobCrabill** [comment]
Oh, interesting.  I removed the micro-USB cable, replug the CAN cable, and now it works 🤔

**Comment by JacobCrabill** [comment]
Somewhere the handling of USB power on this must have changed.  All of my prior testing has been with just leaving the USB cord plugged in.

At any rate, it's looking good now!
![image](https://user-images.githubusercontent.com/5885545/78063749-8b95a800-7345-11ea-9798-871c6dafce8c.png)

**Comment by dakejahl** [comment]
Do you have a FTDI to hook into the console? The USB cable being plugged in should make no difference, I've got mine plugged in with a USB as well.

**Comment by JacobCrabill** [comment]
I do; which connector/pins expose the console on the Pixracer?

**Comment by dakejahl** [comment]
It's part of the pixhawk debug port
https://dev.px4.io/v1.9.0/en/debug/system_console.html

**Comment by JacobCrabill** [comment]
Ah, I see it.  I have a DroneCode Probe; I'll give that a try later when I have time.

**Comment by JacobCrabill** [comment]
Well I rebased @dakejahl's airspeed branch on top of master (actually this branch here: https://github.com/volans-i/Firmware/tree/pr-uavcan-airspeed) and it all works now 🤷‍♂️
![image](https://user-images.githubusercontent.com/5885545/78208335-f8e62d80-7458-11ea-9981-edcab8f5e92d.png)
