### ISSUE TITLE
[Gazebo][Tailsitter] Drone angle is unstable when fw to mc

### ISSUE THREAD

**Issue by xdwgood** [PX4/Firmware#14588]
**Describe the bug**
I used the latest mastre branch and performed the gazebo_tailsitter test. I found that when I choose fw to mc, the drone attitude is unstable!

I'm not sure if this is a simulation problem? Or is there a mistake in the recent changes?

**To Reproduce**

1. make px4_sitl gazebo_tailsitter
2. open QGC ,send takeoff
3. switch mc to fw
4. Wait a minute
5. switch fw to mc
6. see unstable angle(by gazebo display)

**Expected behavior**
have stable back-transmission

**Log Files and Screenshots**
https://logs.px4.io/plot_app?log=25a0b4df-5602-4274-8d8f-b933c0dff8ac

![11111](https://user-images.githubusercontent.com/24932258/78357807-aa659a00-75e4-11ea-88d8-13998196e639.png)

**Comment by xdwgood** [comment]
@sfuhrer could you have a look？ thanks

**Comment by xdwgood** [comment]
I tried v1.10 and everything works fine in gazebo

**Comment by sfuhrer** [comment]
@xdwgood good to know that the problem isn't there on the release. It could be that there was some underlying problem in gazebo that was fixed since. 
Do you still want to keep this issue open? Have you also done real flight testing with the release?

**Comment by xdwgood** [comment]
I plan to make a flight to the master branch, but I found this in the simulation, I am worried about the safety of outdoor flight.
So am I trying to understand that this is just a simulation problem?....But I'm not sure yet. I tried v1.11.0-BETA1 and had the same problem ...
@sfuhrer  Could you see the same problem with the gazebo simulation on your computer?

**Comment by sfuhrer** [comment]
@xdwgood sorry for the late reply, this kind of slipped. 
I just also tried in SITL, didn't have issues (beside a very jumpy airspeed reading). Maybe that was causing issues in your case. 
Did you also fly with a real tailsitter lately?

**Comment by xdwgood** [comment]
@sfuhrer   

>  Did you also fly with a real tailsitter lately?


yes, I tried a real flight and it worked well.
