### ISSUE TITLE
imu rotation issue

### ISSUE THREAD

**Issue by NicolasM0** [PX4/Firmware#14612]
**Describe the bug**
The first IMU of my cube black have a bad rotation.

**To Reproduce**
- flash a cube black with master
- (reset all acc off to 0 and scale to 1 and reboot)
- see estimated orientation or sensors measures (my cube was leveled) :
![image](https://user-images.githubusercontent.com/59083163/78683411-890bf300-78ef-11ea-9aee-1b321347a1aa.png)

**Expected behavior**
Acc 0 should measure about -9.81m/s/s not +9.81

**Log Files and Screenshots**
https://logs.px4.io/plot_app?log=9531c76c-abd9-4656-9fd1-3d50dbc8ced5

**Additional context**
@bkueng it was ok at 2f3174abb0ee2503a94d8b41b99e729fc1946ebb and not after 532ccd18ad2d82f72a33d1c0915a50b49f53eada

Another issue happened when I tried to calibrated the acceleros with this issue: scales of imu 1 and 2 were negative.
Shouldn't be great to have test on this

**Comment by dagar** [comment]
I'm not seeing this on current master (https://github.com/PX4/Firmware/commit/4e0441ab0b9487d3bcd87cdc3373575c0fb1c9f1) or master just before we switched to the new Invensense IMU drivers (https://github.com/PX4/Firmware/commit/7b12a215650935c144c7b58ad731172a17c897d9).

![Screenshot from 2020-04-07 11-20-48](https://user-images.githubusercontent.com/84712/78687731-7cbd7100-78c2-11ea-950a-b7d23aa4abe0.png)

![Screenshot from 2020-04-07 11-25-40](https://user-images.githubusercontent.com/84712/78687784-89da6000-78c2-11ea-80bb-97561be256e6.png)

Is this a new cube?

**Comment by NicolasM0** [comment]
ok works now on 4e0441ab0b9487d3bcd87cdc3373575c0fb1c9f1
thank you !
I retried on 4cdc58ce8da43d2b193719982be091929267b4d0 were I was before and still have the issue.
The few commits between these should have fixed that

**Comment by NicolasM0** [comment]
no not a new cube

**Comment by NicolasM0** [comment]
@dagar I am not sure of what you mean by a "new cube"

**Comment by dagar** [comment]
> @dagar I am not sure of what you mean by a "new cube"

There's apparently a new version of the Cube black (Cube Black+ ?) that changed the sensors (mpu9250 is end of life), but I don't know the details.

**Comment by NicolasM0** [comment]
> > @dagar I am not sure of what you mean by a "new cube"
> 
> There's apparently a new version of the Cube black (Cube Black+ ?) that changed the sensors (mpu9250 is end of life), but I don't know the details.

I think this cube is about 1 year old
