### ISSUE TITLE
Simtoo Moment drone (Hoshi 007 Pro)

### ISSUE THREAD

**Issue by JMB18000** [PX4/Firmware#14648]
I'm searching some tracks to reprogramming the Simtoo Moment drone (Hoshi 007 Pro) a foldable drone who is sell 65 Euros (!!!) with a Snapdragon 801 inside but his original firmware is full bugged..
Somebody can help me...?
![w](https://user-images.githubusercontent.com/63533131/79062730-098a7500-7c9d-11ea-9828-42d901eddf14.jpg)

**Comment by JMB18000** [comment]
![w (1)](https://user-images.githubusercontent.com/63533131/79062866-09d74000-7c9e-11ea-8151-a06bd899ed59.jpg)

**Comment by julianoes** [comment]
I would say this is not a PX4 issue as such but could be an interesting discussion.

I suggest that you ask that question in discuss.px4.io.
