### ISSUE TITLE
[VTOL] Front transition deviates

### ISSUE THREAD

**Issue by ThomasRigi** [PX4/Firmware#14718]
**Describe the bug**
During the front transition, the drone rolls into the wrong direction and deviates from the expected path. Observed in SITL, probably linked to https://github.com/PX4/Firmware/pull/14405 @RomanBapst 

**To Reproduce**
1. Run SITL: `make px4_sitl gazebo_standard_vtol`
2. Launch a mission with a vtol takeoff and transition waypoint 
3. Observe

**Expected behavior**
The drone should face / fly towards the front transition waypoint 

**Log Files and Screenshots**
Log file: (transition northwards) https://logs.px4.io/plot_app?log=af78e5c4-99fc-46fb-924c-c706a9fe6964

Similar behaviour when transitioning towards East or South:
![image](https://user-images.githubusercontent.com/48206725/79860129-6dfeb000-83d2-11ea-84d6-19be4600bafd.png)

**Drone (please complete the following information):**
- SITL standard VTOL on Gazebo
- run on master from 20.04.2020

**Additional context**
Going through the code changes of https://github.com/PX4/Firmware/pull/14405, I additionally noticed the hard coded limit in https://github.com/PX4/Firmware/blob/809b45eac89cd89cb20a9a5cba646396ef136730/src/modules/vtol_att_control/vtol_type.cpp#L193 that I would prefer to have as a parameter and a comment that should be adapted at https://github.com/PX4/Firmware/blob/809b45eac89cd89cb20a9a5cba646396ef136730/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L1579 to include the transitions.

I think there is also a problem with the yaw alignment when the drone initiates the transition. It still rotates at around 45°/s in the log shared above. But that's I guess a separate point.

**Comment by RomanBapst** [comment]
@ThomasRigi Please have a look at [my PR](https://github.com/PX4/Firmware/pull/14727), it should fix this issue.
