### ISSUE TITLE
GPS # of satellites used dropped to 16 (u-blox M9N)

### ISSUE THREAD

**Issue by limhyon** [PX4/Firmware#14722]
**Describe the bug**
I was cherry-picking up 
https://github.com/PX4/GpsDrivers/commit/cf87129bd341eb56222117bf5b75c18e01ddd500

to test M9N module. But as soon as PX4 firmware boots and send few commands to M9N, the number of satellites used on M9N dropped to 16 (fixed number) from around 30~32 satellites.

**To Reproduce**
1. Connect u-center to M9N with USB port.
2. Wait PX4 booted.
3. Check u-center.

**Expected behavior**
It should have maximum number of satellites observed.

**Comment by julianoes** [comment]
FYI @bkueng

**Comment by ryanjAA** [comment]
Cherrypicked and same result. 16 sats Max. Tried a different firmware in same location at the same time and more than 16 sats so not hardware.

**Comment by bkueng** [comment]
Apparently this is indeed a hardware restriction (in combination with how we configure it): with 10Hz update rate you only get up to 16 satellites. Reducing to 5Hz allows to go higher.

I reduced to 5Hz, so we can use more satellites: https://github.com/PX4/GpsDrivers/pull/57

**Comment by ryanjAA** [comment]
Tested at 25hz and still limited to 16 sats. Tested at 5hz and no limitation so unfortunately it is a hardware constraint. https://github.com/PX4/GpsDrivers/pull/57 Breaks functionality with the M9N (as a few other things are added in the PR) but testing this with the previous driver change works fine with the reduced hz changes.

**Comment by dagar** [comment]
> Tested at 25hz and still limited to 16 sats. Tested at 5hz and no limitation so unfortunately it is a hardware constraint. [PX4/GpsDrivers#57](https://github.com/PX4/GpsDrivers/pull/57) Breaks functionality with the M9N (as a few other things are added in the PR) but testing this with the previous driver change works fine with the reduced hz changes.

I'm just curious, are you gathering and comparing any other metrics along with the satellite count and output data rate?

**Comment by ryanjAA** [comment]
What specifically? HDOP and VDOP? HDOP drops by half when going from 16 to 22-24 sats and when hitting 29+ starts to decrease further.

<img width="448" alt="Screen Shot 2020-04-25 at 10 15 19 PM" src="https://user-images.githubusercontent.com/31726584/80385663-f74b3200-886b-11ea-8930-d8b9ff659c2a.png">
<img width="485" alt="Screen Shot 2020-04-25 at 3 24 45 PM" src="https://user-images.githubusercontent.com/31726584/80385666-f7e3c880-886b-11ea-82e8-79b96e2e5beb.png">

**Comment by julianoes** [comment]
Fixed in https://github.com/PX4/GpsDrivers/pull/57, right?

**Comment by bkueng** [comment]
Correct, thanks Julian.
