### ISSUE TITLE
EKF2 velocity estimate wrong - v1.11-beta

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#14735]
**Describe the bug**
We are flying in indoor environments with VIO, and while testing recently, discovered that the EKF's velocity estimate significantly differed from that provided by the vision system. We don't know if this is a new issue, or whether this already existed before, since we have not flown this setup so extensively before. We also only recently plumbed the vision system's velocity estimate through to PX4, so it's easy to confirm the issue now.

*EDIT: older logs (~1 mo old - upstream `d7a9b123e6b84df4a7c01daaac64706c39abd3d7`) don't show this velocity offset, and have lower vibration levels. I think the on-sensor DLPF was disabled between then and now.* https://logs.px4.io/plot_app?log=ff62827a-7eff-45c6-b2e6-6ea22cd087c6

![image](https://user-images.githubusercontent.com/5557676/80012224-f8aae200-849a-11ea-8594-8472c7f0853b.png)

**Expected behavior**
The velocity estimate matches the one provided by the vision system, which is accurate and has been benchmarked against groundtruth. Also the vehicle was flying in a straight line, and that velocity offset wasn't actually there in real life.

**Log Files and Screenshots**
Here are two logs from boot illustrating the issue. The first one is without velocity fusion enabled, and the second one is with velocity fusion enabled (which doesn't make much of a difference).

1. EKF2_AID_MASK = 24 (ev pos, ev yaw): https://logs.px4.io/plot_app?log=6eb5a9cb-a4e9-4b4a-89eb-e71e11419670
2. EKF2_AID_MASK = 280 (ev pos, ev yaw, ev vel): https://logs.px4.io/plot_app?log=dcb3b53b-07d2-4db9-a118-592ef82d5cba

These are both replayable. Our branch is based on upstream `746b3124abe9df486c6d88a3d9ec0c438e63654d`

#### First log
Accel bias estimate:
![image](https://user-images.githubusercontent.com/5557676/80014423-470db000-849e-11ea-9028-a36471ee2864.png)

Velocity estimates:
![image](https://user-images.githubusercontent.com/5557676/80014748-bb485380-849e-11ea-9c1d-a0703bd55958.png)

#### Second log
Accel bias estimate:
![image](https://user-images.githubusercontent.com/5557676/80014567-7a503f00-849e-11ea-940e-11f289aad6bf.png)

Velocity estimate:
![image](https://user-images.githubusercontent.com/5557676/80014810-d6b35e80-849e-11ea-9c49-2de800e50f8d.png)

#### Last good log
https://logs.px4.io/plot_app?log=ff62827a-7eff-45c6-b2e6-6ea22cd087c6

Based on upstream `d7a9b123e6b84df4a7c01daaac64706c39abd3d7`

**Drone (please complete the following information):**
- 550 sized carbon quadcopter.
- Hardmounted Pixhawk 4.

**Comment by dagar** [comment]
The accel (icm20649) calibration changed quite a bit. Notably there's no longer a huge x offset. This was also seen in https://github.com/PX4/Firmware/pull/14676#issuecomment-617512387. I'd say there was something bogus in the old mpu6000 driver. 

### Old
```
CAL_ACC0_XOFF, -1.0432920455932617
CAL_ACC0_XSCALE, 0.9367385506629944
CAL_ACC0_YOFF, 0.07577945291996002
CAL_ACC0_YSCALE, 0.9988186955451965
CAL_ACC0_ZOFF, -0.09410905838012695
CAL_ACC0_ZSCALE, 0.9868613481521606
```

### New
```
CAL_ACC0_XOFF, -0.052748680114746094
CAL_ACC0_XSCALE, 0.9987621903419495
CAL_ACC0_YOFF, 0.08501672744750977
CAL_ACC0_YSCALE, 0.9985091686248779
CAL_ACC0_ZOFF, -0.08153867721557617
CAL_ACC0_ZSCALE, 0.9868456125259399
```

**Comment by LorenzMeier** [comment]
@dagar I would add code to wipe the params on update. The factory calibration of the ICM20649 is so good that you're better off having none.

**Comment by mhkabir** [comment]
@RomanBapst @bresch @kamilritz @jkflying Can you have a look?

**Comment by dagar** [comment]
The integrated data in the accel x axis looks questionable in sensor_combined.

![Screenshot from 2020-04-24 10-02-20](https://user-images.githubusercontent.com/84712/80221082-c8864f00-8612-11ea-897a-4fe45ffd7871.png)



![Screenshot from 2020-04-24 10-01-24](https://user-images.githubusercontent.com/84712/80221000-a68ccc80-8612-11ea-8314-c101c7eaf427.png)

This is where the estimated bias (~0.2 m/s) is coming from.

![Screenshot from 2020-04-24 10-03-32](https://user-images.githubusercontent.com/84712/80221144-e2279680-8612-11ea-9171-25c0d8abfd4b.png)


![Screenshot from 2020-04-24 10-04-19](https://user-images.githubusercontent.com/84712/80221234-fbc8de00-8612-11ea-888d-a36ebcb229b6.png)


I've tried to replicate this on another fmu-v5, but no success so far. It seems like it could be a numerical problem.

**Comment by mhkabir** [comment]
Happened again on master: https://logs.px4.io/plot_app?log=6a006545-b3bf-446f-9baf-f89c5fcfb542

Same vehicle, with @dagar's new fix attempts, and a fixed companion computer fan (so lower vibrations on ground)

![image](https://user-images.githubusercontent.com/5557676/80447370-3cf91080-88e7-11ea-8e83-c2d5fb9a729a.png)

**Comment by bresch** [comment]
@mhkabir Your VIO system seems to provide a velocity estimate with a variance of 5 m2/s2
![2020-04-28_10-49-39_01_plot](https://user-images.githubusercontent.com/14822839/80467289-e79c1e00-893d-11ea-8ef3-bc3ba2cd2075.png)

**Comment by bresch** [comment]
@mhkabir Your VIO system seems to provide a velocity estimate with a variance of 5 m2/s2 (std dev: 2.2m/s). A typical GPS gives velocity aiding with an accuracy of 0.5m/s. ![2020-04-28_10-49-39_01_plot](https://user-images.githubusercontent.com/14822839/80467289-e79c1e00-893d-11ea-8ef3-bc3ba2cd2075.png)

**Comment by kamilritz** [comment]
@bresch @mhkabir  Oh that is for sure not optimal. This remembers me of a bug that I wanted to fix inside the velocity-in-body-frame PR (, which is not merged yet). I am sorry for not creating a single PR for the bug fix. Can you spot the [bug](https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_main.cpp#L1126-L1128)?

**Comment by mhkabir** [comment]
@bresch Good catch with the variances. What you're looking at is actually the _position_ variance, thanks to the above bug. This is fishy regardless (such a large position variance is not right), and seems to be something on our side, looking into it.

**Comment by mhkabir** [comment]
There seems to have been a bunch of separate issues in play here:

**Comment by mhkabir** [comment]
There seem to have been a bunch of issues in play simultaneously here:
- Accelerometer bias estimates were exploding, which seems to have been fixed thanks to @dagar (https://github.com/PX4/Firmware/pull/14752 and https://github.com/PX4/Firmware/pull/14765)
- Our vision position variances were wrong, found thanks to @bresch. We will fix this properly on our side longer term, for now using a fixed variance using `EKF2_NOISE_MD` seems to work just fine.
- Vision velocity fusion was using the wrong variances, which is fixed thanks to @kamilritz (https://github.com/PX4/Firmware/pull/14779)

Thanks for all the help everyone!
