### ISSUE TITLE
Fixed Wing Trim Parameter in Manual Mode

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#1473]
At the moment "TRIM_ROLL", "TRIM_PITCH" and "TRIM_YAW" are not used when the plane operates in full manual mode. Why not and are there any alternative parameters?

**Comment by LorenzMeier** [comment]
That's because of the manual override of IO. We would need to send these params over as well. Entirely possible, just not done yet.

**Comment by LorenzMeier** [comment]
Resolved, yay!
