### ISSUE TITLE
ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by pkyadav73199** [PX4/Firmware#14775]
**Describe the bug**
I am trying to simulate UAV using px4 with mavros node but i am getting error while launching gazebo.

ninja: build stopped: subcommand failed.
Makefile:205: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1

**To Reproduce**
mkdir -p ~/src
cd ~/src
git clone https://github.com/PX4/Firmware.git
cd Firmware
git submodule update --init --recursive
make px4_sitl gazebo

**Expected behavior**
I am getting the error after running the above code.

**Comment by julianoes** [comment]
There should be more error than that. Can you paste all the output? And also try a clean build?

**Comment by pkyadav73199** [comment]
-- PX4 version: v1.11.0-beta1-93-g70329ce
-- PX4 config file: /home/edith/src/Firmware/boards/px4/sitl/default.cmake
-- PX4 config: px4_sitl_default
-- PX4 platform: posix
-- PX4 lockstep: enabled
-- cmake build type: RelWithDebInfo
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building for code coverage
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- build type is RelWithDebInfo
-- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-267-g8a9d961
-- Configuring done
-- Generating done
-- Build files have been written to: /home/edith/src/Firmware/build/px4_sitl_default
[7/745] git submodule src/drivers/gps/devices
[10/745] Generating mixer_multirotor.generated.h
FAILED: cd /home/edith/src/Firmware/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py -f /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[10/745] Generating mixer_multirotor_6dof.generated.h
FAILED: cd /home/edith/src/Firmware/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py --sixdof -f /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor_6dof.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[10/745] Generating mixer_multirotor_normalized.generated.h
FAILED: cd /home/edith/src/Firmware/build/px4_sitl_default/src/lib/mixer/MultirotorMixer && /usr/bin/python3 /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py --normalize -f /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/dodeca_bottom_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/dodeca_top_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_t.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/hex_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_cox.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_cox_wide.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/octa_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_deadcat.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_h.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_plus.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_s250aq.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_vtail.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_wide.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x_cw.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_x_pusher.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/quad_y.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/tri_y.toml /home/edith/src/Firmware/src/lib/mixer/MultirotorMixer/geometries/twin_engine.toml -o mixer_multirotor_normalized.generated.h
Failed to import toml: No module named 'toml'

You may need to install it using:
    pip3 install --user toml

[10/745] Generating uORB topic headers
FAILED: cd /home/edith/src/Firmware/msg && /usr/bin/python3 tools/px_generate_uorb_topic_files.py --headers -f actuator_armed.msg actuator_controls.msg actuator_outputs.msg adc_report.msg airspeed.msg airspeed_validated.msg battery_status.msg camera_capture.msg camera_trigger.msg cellular_status.msg collision_constraints.msg collision_report.msg commander_state.msg cpuload.msg debug_array.msg debug_key_value.msg debug_value.msg debug_vect.msg differential_pressure.msg distance_sensor.msg ekf2_timestamps.msg ekf_gps_drift.msg ekf_gps_position.msg esc_report.msg esc_status.msg estimator_innovations.msg estimator_sensor_bias.msg estimator_status.msg follow_target.msg geofence_result.msg gps_dump.msg gps_inject_data.msg home_position.msg hover_thrust_estimate.msg input_rc.msg iridiumsbd_status.msg irlock_report.msg landing_gear.msg landing_target_innovations.msg landing_target_pose.msg led_control.msg log_message.msg logger_status.msg manual_control_setpoint.msg mavlink_log.msg mission.msg mission_result.msg mount_orientation.msg multirotor_motor_limits.msg obstacle_distance.msg offboard_control_mode.msg onboard_computer_status.msg optical_flow.msg orb_test.msg orb_test_large.msg orb_test_medium.msg orbit_status.msg parameter_update.msg ping.msg position_controller_landing_status.msg position_controller_status.msg position_setpoint.msg position_setpoint_triplet.msg power_button_state.msg power_monitor.msg pwm_input.msg qshell_req.msg qshell_retval.msg radio_status.msg rate_ctrl_status.msg rc_channels.msg rc_parameter_map.msg rpm.msg safety.msg satellite_info.msg sensor_accel.msg sensor_accel_fifo.msg sensor_accel_integrated.msg sensor_accel_status.msg sensor_baro.msg sensor_combined.msg sensor_correction.msg sensor_gyro.msg sensor_gyro_fifo.msg sensor_gyro_integrated.msg sensor_gyro_status.msg sensor_mag.msg sensor_preflight.msg sensor_selection.msg servorail_status.msg subsystem_info.msg system_power.msg task_stack_info.msg tecs_status.msg telemetry_status.msg test_motor.msg timesync.msg timesync_status.msg trajectory_bezier.msg trajectory_waypoint.msg transponder_report.msg tune_control.msg uavcan_parameter_request.msg uavcan_parameter_value.msg ulog_stream.msg ulog_stream_ack.msg vehicle_acceleration.msg vehicle_air_data.msg vehicle_angular_acceleration.msg vehicle_angular_velocity.msg vehicle_attitude.msg vehicle_attitude_setpoint.msg vehicle_command.msg vehicle_command_ack.msg vehicle_constraints.msg vehicle_control_mode.msg vehicle_global_position.msg vehicle_gps_position.msg vehicle_imu.msg vehicle_land_detected.msg vehicle_local_position.msg vehicle_local_position_setpoint.msg vehicle_magnetometer.msg vehicle_odometry.msg vehicle_rates_setpoint.msg vehicle_roi.msg vehicle_status.msg vehicle_status_flags.msg vehicle_trajectory_bezier.msg vehicle_trajectory_waypoint.msg vtol_vehicle_status.msg wheel_encoders.msg wind_estimate.msg yaw_estimator_status.msg -i /home/edith/src/Firmware/msg -o /home/edith/src/Firmware/build/px4_sitl_default/uORB/topics -e templates/uorb -t /home/edith/src/Firmware/build/px4_sitl_default/msg/tmp/headers -q
Failed to import em: No module named 'em'

You may need to install it using:
    pip3 install --user empy

[10/745] Generating git version header
ninja: build stopped: subcommand failed.
Makefile:205: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1

**Comment by mhkabir** [comment]
The compile error output above tells you what to do, please read it.

**Comment by julianoes** [comment]
```
pip3 install --user empy
```

**Comment by pkyadav73199** [comment]
Thanks a lot .
It works.
I have done simulation successfully .
