### ISSUE TITLE
airspeed_selector noisy startup

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#14807]
``` Console
INFO  [airspeed_selector] No airspeed sensor detected. Switch to non-airspeed mode.
WARN  [airspeed_selector] Airspeed: switched from sensor 0 to -1

WARN  [airspeed_selector] Airspeed: switched from sensor -1 to 1
```

@sfuhrer let's adjust this so there aren't unnecessary warnings in good setups.

**Comment by Antiheavy** [comment]
keep all that information as INFO for the logs though!

**Comment by dagar** [comment]
> keep all that information as INFO for the logs though!

To clarify, I only want to get rid of that unnecessary output on startup. The airspeed selector should be able to cleanly initialize into airspeed mode at first unless the sensors are actually missing.

**Comment by sfuhrer** [comment]
Agree, that's annoying, not sure when it started. @dagar have you seen it also outside of SITL? 
https://github.com/PX4/Firmware/pull/14811 would be a potential fix, though a bit hacky.

**Comment by sfuhrer** [comment]
Let's close this, as it has been fixed with https://github.com/PX4/Firmware/pull/14811
