### ISSUE TITLE
Frsky Telemetry not working on Holybro Kakute F7

### ISSUE THREAD

**Issue by benjinne** [PX4/Firmware#14802]
When trying to use any of the UARTs on the Kakute, and configuring TEL_FRSKY_CONFIG to the matching tx pin **no sensors** (other than rxbat and rssi) are discovered on my transmitter (a Jumper T16). 

**To Reproduce**
1. Set TEL_FRSKY_CONFIG
2. Discover new Sensors on transmitter

**Expected behavior**
A list of sensors should be displayed on the transmitter

**Other steps I tried*
1. using the non-inverted smart-port pad on my r-xsr
2. verifying packets are being sent using "frsky_telemetry status"
3. changing the mode using "frsky_telemetry -m" to both sport and sport_single
4. tried rewiring to UARTs 1,2,3,6 and changing TEL_FRSKY_CONFIG

**Comment by dagar** [comment]
Any thoughts on this @bkueng?

**Comment by bkueng** [comment]
Yes it requires NuttX changes to make this work on F7 - I'm still waiting on @davids5 for testing it.

**Comment by justas-** [comment]
Affects Kakute F7 AIO as well.

**Comment by benjinne** [comment]
> Affects Kakute F7 AIO as well.

That's what I'm using

**Comment by bys1123** [comment]
@bkueng Is this F7 NuttX change required include fmuv5?

**Comment by justas-** [comment]
Are there any updates on this?

**Comment by davids5** [comment]
Sorry - I am running behind on getting to it.

**Comment by davids5** [comment]
The fix for this is un https://github.com/PX4/Firmware/pull/15492 that was merged. If this is not resolved please re-open
