### ISSUE TITLE
Homebrew px4-sim SHA256 broken

### ISSUE THREAD

**Issue by LordHelmchen324** [PX4/Firmware#14822]
I am trying run `brew install px4-sim`on macOS 10.15.4. I get this error message:

==> Installing px4-sim from px4/px4
==> Installing dependencies for px4/px4/px4-sim: px4-sim-gazebo and px4-sim-jmavsim
==> Installing px4/px4/px4-sim dependency: px4-sim-gazebo
==> Downloading https://raw.githubusercontent.com/PX4/Firmware/master/Tools/px4.
Already downloaded: /Users/jankaiser/Library/Caches/Homebrew/downloads/7be7daca52fab83c40ed326bdcf732c0060cdc0b9d97e0d94f1e71856982d00b--px4.py
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 48199ee9ff392eff8a1efcd177e2c10f4a4dfd9877e52e13b1f3540d5dfedac9
  Actual: dafe6a32d270c48cbd42960adb2155bd5f60d1aec8cb644b10f8cafc0c8d2e8f
 Archive: /Users/jankaiser/Library/Caches/Homebrew/downloads/7be7daca52fab83c40ed326bdcf732c0060cdc0b9d97e0d94f1e71856982d00b--px4.py
To retry an incomplete download, remove the file above.

I have tried fully reinstalling Homebrew as well as following the above instructions to delete the given file. I believe this is the same issue as #14744 but for the `px4-sim` recipe.

**Comment by TSC21** [comment]
@LordHelmchen324 yes. Can you please make a PR for it (updating the SHA)? Thanks!
