### ISSUE TITLE
Callibration error

### ISSUE THREAD

**Issue by ayu135** [PX4/Firmware#1483]
I had this issue earlier and now i have seen two more people have the same issue on the forum so i thought it would be wise to raise it here. Even after callibrating the pixhawk on a level surface when i switch off and put it on there is significant error. Even on a flat surface it shows around 20 degree tilt. Please look into this
Here are the corresponding threads:
https://groups.google.com/forum/#!topic/px4users/2qhI4PHNuNI
https://groups.google.com/forum/#!topic/px4users/B58n2pfOuY4

**Comment by itayguy** [comment]
HI, Lorenz
I also might have calibration problem , which begins right after moving from disarm to arm .
the pitch drifts
I opened a topic in drones discuss 
https://groups.google.com/forum/#!topic/drones-discuss/cKUqlg7AUxo
and
https://groups.google.com/forum/#!topic/drones-discuss/gUZzy8FokRs

the logs are inside.
maybe its related
