### ISSUE TITLE
Optical flow position hold

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1484]
@DrTon With the recent improvements in the flow codebase, it would be great to give optical flow another go. It has a much wider dynamic range and we've corrected a few smaller bugs. I also have a mode filter for ultrasound ready for testing here:
https://github.com/PX4/Flow/pull/29

**Comment by alexbuyval** [comment]
What is current situation with this issue? Early I tried to fly with the arducopter flight stack. I used the Paul's EKF with px4flow (https://www.youtube.com/watch?v=-00xReoty80). However, I would like to move the PX4 flight stack. Which branch should I use for position hold with optical flow?

**Comment by LorenzMeier** [comment]
@alexbuyval The flow support for the filter is in, but I need to have another pass over the interface this weekend until its ready for testing / joining development. You can help us by testing this branch:
https://github.com/PX4/Firmware/pull/1770

Note that you have to comment out the attitude / inav filter there and enable the att_pos filter instead:
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.mc_apps#L7-L9

**Comment by alexbuyval** [comment]
@LorenzMeier  I was trying to switch to POSHLD mode, but I have got 'REJECT POSHOLD' messages every time when I tried. I found in code that there are conditions:
``` 	
case vehicle_status_s::MAIN_STATE_POSCTL:
		/* need at minimum local position estimate */
		if (status->condition_local_position_valid ||
		    status->condition_global_position_valid) {
			ret = TRANSITION_CHANGED;
		}
```
I dived further and found that 'status->condition_local_position_valid' depends on '_gps_initialized' flag.
Unfortunately I haven't got the GPS receiver on my drone. 
So does it mean that I cannot use poshold mode without the GPS with only px4flow sensor? Or there is parameter which allows to disable gps checking (like in ardupilot code)?

**Comment by Zefz** [comment]
Yes the current EKF filter doesn't properly support local position estimation without GPS (the code needs to be updated to handle the case for Optical Flow). The code in question is here: https://github.com/PX4/Firmware/blob/f26a1cb3f1e9fcc1e4ad6efed07b210b4e652564/src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp#L810-L814 (there is even a TODO comment there about your exact issue).

The optical flow module needs to tell the EKF that it is active and working so that the EKF can fuse it to determine local position.

**Comment by jlian** [comment]
I haven't seen any updates on this for a while, just wondering if there has been any progress in this issue? I got my Pixhawk+PX4Flow setup the other day and had success with loiter mode outdoors but not indoors. 

I'm very interested to see this working. Is there anything I can help with?

**Comment by LorenzMeier** [comment]
@jlian We're currently actively working on integrating a new binary supporting higher-resolution KLT flow:
https://github.com/PX4/Flow/pull/65

Apart from that there is preliminiary support for the updated flow module in INAV in master.

**Comment by LorenzMeier** [comment]
Working great with INAV now.
