### ISSUE TITLE
Build parameter code from xml file

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#1485]
Issue: QGroundControl now depends on the parameter meta data to drive it's user interface. In order to do that it needs clean, high-quality parameter meta data. I would also like to add additional meta data to parameters such as: read-only, increment for spin-box ui, enums for combo-box ui and so forth. The current doc comment, python parser mechanism is too error prone to guarantee that high-quality meta data without even more complicated parsing logic. As just one example: Currently you will get duplicated parameters in the xml file, due to the fact that the parser does not understand #ifdef's. Each duplicate in some case represent the parameter for a specific autopilol type. There is no way for QGC to know which one is the right one.

I would like to propose moving the parameter definitions and meta data out of the code and into xml files. Each module would have it's own parameter xml file which is then parsed at build time and creates the parameter c++ code. A python xml file parser is much easier to write and validate. Also an xml file is much easier to work with from a standpoint of adding new meta data variants. I also think that looking at a parameter xml file to understand the parameter set is also easier to read. 

I'd be happy to make the change.

**Comment by LorenzMeier** [comment]
Doing that today.
