### ISSUE TITLE
I have the screenshot out. Please see the screenshot below. The third one shows the missing parameters

### ISSUE THREAD

**Issue by hpyeah** [PX4/Firmware#14866]
![W8}EEWE8UQ(6W06C2AMT%U3](https://user-images.githubusercontent.com/42979228/81378343-b7bcf980-9139-11ea-8a02-132dc722e2bd.jpg)
![6R`@GVY1 6NXAHG F3JN~_U](https://user-images.githubusercontent.com/42979228/81378370-c1def800-9139-11ea-89db-4cda54fa2aac.jpg)
![3 08S0U}7)7}4KHLF))3X0I](https://user-images.githubusercontent.com/42979228/81378383-c7d4d900-9139-11ea-9a80-93c6df1f62e1.jpg)

**Comment by julianoes** [comment]
@hpyeah ok what exactly is the issue here?

**Comment by julianoes** [comment]
No follow up, closing.
