### ISSUE TITLE
Ubuntu toolchain setup script fails

### ISSUE THREAD

**Issue by Franky333** [PX4/Firmware#14888]
**Describe the bug**
When running the Ubuntu setup script (Tools/setup/ubuntu.sh) on Ubuntu 20.04, the script stops running at this line: https://github.com/PX4/Firmware/blob/0a4e7142ee7baa14cc50ea86d5a13b1933d5d5e4/Tools/setup/ubuntu.sh#L144

**To Reproduce**
Run the script on Ubuntu 20.04, after installing the NuttX dependencies it stops. When replacing the line linked above with GCC_FOUND_VER=0, the installation continues as expected.

**Comment by julianoes** [comment]
@Franky333 can you check again?

**Comment by Franky333** [comment]
@julianoes Not sure why but now I get this error before the toolchain installation: 
`./ubuntu.sh: line 149: [: missing `]'
And then the toolchain gets installed even though I already have it installed.
It seems like I had the same problem in my original report (where I didn't have the toolchain already installed) but instead of printing the error message the script just finished without doing anything else.

**Comment by julianoes** [comment]
I just tried this in a fresh Ubuntu 18.04 docker and it worked just fine.

How did you download your `ubuntu.sh` file? Can you try the one downloaded with the repository?

**Comment by Franky333** [comment]
I used a fresh download of the repository and launched the script from there.
Maybe the version of bash I am using (5.0.16(1)-release) behaves differently than yours?

**Comment by hamishwillee** [comment]
@julianoes I can reproduce in a VM - see duplicate https://github.com/PX4/Firmware/issues/14916

I think it is something to do with the Grep of the version and the addition of "+x" but I don't understand this bit of the code. Hoping you can work out why it is falling over.

**Comment by julianoes** [comment]
Sorry, I overlooked the error. Now I can reproduce it.
