### ISSUE TITLE
RC override on SITL not working

### ISSUE THREAD

**Issue by KimHyungSub** [PX4/Firmware#14890]
**Describe the bug**
I try to override RC channels on SITL by using mavutil. But, it seems likely to me that PX4 does not properly handle the overridden RC channels. I also noticed that many people already suffered from the same issues (#9782 / https://discuss.px4.io/t/sending-rc-channels-override-to-px4/15120 / https://discuss.px4.io/t/unable-to-send-rc-commands-to-px4/6844).

After I overrode the RC channels, GCS showed correct overridden RC values as below.
![RC_override](https://user-images.githubusercontent.com/21173273/81620561-34f6a180-93ba-11ea-88e9-53b1dc781d43.png)

I also confirmed that MavlinkReceiver::handle_message_rc_channels_override() well received the RC override messages and then published uORB message as shown in below. 
![Mavlink_code_1](https://user-images.githubusercontent.com/21173273/81620920-0d540900-93bb-11ea-9f37-ccd76a5a000a.png)
![Mavlink_code_2](https://user-images.githubusercontent.com/21173273/81620922-0f1dcc80-93bb-11ea-890b-7d544451d3fa.png)

Can you guys help me to solve the issue? I need to simulate manual control. Without the manual control, we can only test few flight modes which do not require a RC controller.

**Expected behavior**
Drone follows the overridden RC channels.

**Drone (please complete the following information):**
- SITL with gazebo

**Log Files and Screenshots**
- PX4 Flight Review: https://logs.px4.io/plot_app?log=ab307a9b-de33-4273-8ea2-3c1a75af7427

**Comment by dagar** [comment]
Typically MANUAL_CONTROL (https://mavlink.io/en/messages/common.html#MANUAL_CONTROL) is preferred over faking RC.

**Comment by dagar** [comment]
> it seems likely to me that PX4 does not properly handle the overridden RC channels

Can you expand on this? What's the actual problem? Did you try going through RC calibration?

Instead of the printf can you try `listener input_rc` and `listener manual_control_setpoint`?

**Comment by KimHyungSub** [comment]
@dagar Thanks Dagar! I solved the problem using RC calibration using rc_channels_override_send().

**Comment by ceasergarcia** [comment]
@KimHyungSub I'm having the same issue. After an RC calibration, it is still not handling the override command. Do you mind posting a code snippet on how you created the override command?
