### ISSUE TITLE
Typhoon h480 gimbal direction

### ISSUE THREAD

**Issue by keep9oing** [PX4/Firmware#14902]
Hi, I firstly run the sitl with typhoon h480 that following instruction.

http://dev.px4.io/master/en/simulation/gazebo.html

To simulate Typhoon, I use the command

**make px4_sitl gazebo_typhoon_h480**

However, when the gazebo turn on the gimbal looks back of the uav.
What's the problem and how do I resolve it?

![Screenshot from 2020-05-14 21-09-11](https://user-images.githubusercontent.com/31655488/81934663-480fa880-962a-11ea-817f-57b1f1b3b4dd.png)

Thank you.

**Comment by julianoes** [comment]
FYI @Jaeyoung-Lim
