### ISSUE TITLE
ImportError('No module named toml',)

### ISSUE THREAD

**Issue by liangpu597** [PX4/Firmware#14918]
My system is : ubuntu 16.04
First， I Use :` pip install toml`
and I clone px4, use:
`make px4_sitl_default gazebo`
and errors:
`Failed to import toml: No module named 'toml'`
`You may need to install it using:`
`    pip3 install --user toml`

and I try open a shell:

> python

> import toml

and Found toml is already installed, but it  errors in px4.

please tell me how to solve? thank you!

**Comment by bys1123** [comment]
px4 is using python3

**Comment by liangpu597** [comment]
> px4 is using python3

if this, how to solve? thank you!

**Comment by bys1123** [comment]
`pip3 install --user toml`

**Comment by liangpu597** [comment]
@bys1123 
ok , i follow your way. changed the default python version from 2 to 3, and follow the error pip3 install ***. and try again: `make px4_sitl_default gazebo`.  
and errors:   

> tony@tony-Inspiron-3542:~/PX4_Firmware$ make px4_sitl_default gazebo
> -- PX4 version: v1.11.0-beta1
> -- PX4 config file: /home/tony/PX4_Firmware/boards/px4/sitl/default.cmake
> -- PX4 config: px4_sitl_default
> -- PX4 platform: posix
> -- PX4 lockstep: enabled
> -- cmake build type: RelWithDebInfo
> -- The CXX compiler identification is GNU 5.4.0
> -- The C compiler identification is GNU 5.4.0
> -- The ASM compiler identification is GNU
> -- Found assembler: /usr/bin/cc
> -- Check for working CXX compiler using: Ninja
> -- Check for working CXX compiler using: Ninja -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler using: Ninja
> -- Check for working C compiler using: Ninja -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Building for code coverage
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
> -- build type is RelWithDebInfo
> -- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-255-g47624a0
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/tony/PX4_Firmware/build/px4_sitl_default
> [7/740] git submodule src/drivers/gps/devices
> [10/740] git submodule src/lib/ecl
> [11/740] git submodule mavlink/include/mavlink/v2.0
> [206/740] git submodule Tools/sitl_gazebo
> [214/740] Performing configure step for 'sitl_gazebo'
> -- install-prefix: /usr/local
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler using: Ninja
> -- Check for working C compiler using: Ninja -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler using: Ninja
> -- Check for working CXX compiler using: Ninja -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Performing Test COMPILER_SUPPORTS_CXX17
> -- Performing Test COMPILER_SUPPORTS_CXX17 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX14
> -- Performing Test COMPILER_SUPPORTS_CXX14 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX11
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX0X
> -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
> -- Using C++14 compiler
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   system
> --   thread
> --   filesystem
> --   chrono
> --   date_time
> --   atomic
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'bullet>=2.82'
> --   Found bullet, version 2.83
> -- Found Simbody: /usr/include/simbody  
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> --   system
> --   filesystem
> --   program_options
> --   regex
> --   iostreams
> --   date_time
> --   chrono
> --   atomic
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
> -- Boost version: 1.58.0
> -- Looking for OGRE...
> -- OGRE_PREFIX_WATCH changed.
> -- Checking for module 'OGRE'
> --   Found OGRE, version 1.9.0
> -- Found Ogre Ghadamon (1.9.0)
> -- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
> -- Looking for OGRE_Paging...
> -- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
> -- Looking for OGRE_Terrain...
> -- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
> -- Looking for OGRE_Property...
> -- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
> -- Looking for OGRE_RTShaderSystem...
> -- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
> -- Looking for OGRE_Volume...
> -- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
> -- Looking for OGRE_Overlay...
> -- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so (Required is at least version "2.3.0") 
> -- Config-file not installed for ZeroMQ -- checking for pkg-config
> -- Checking for module 'libzmq >= 4'
> --   Found libzmq , version 4.1.4
> -- Found ZeroMQ: TRUE (Required is at least version "4") 
> -- Checking for module 'uuid'
> --   Found uuid, version 2.27.0
> -- Found UUID: TRUE  
> -- Checking for module 'tinyxml2'
> --   Found tinyxml2, version 2.2.0
> -- Looking for dlfcn.h - found
> -- Looking for libdl - found
> -- Found DL: TRUE  
> -- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
> -- Checking for module 'gts'
> --   Found gts, version 0.7.6
> -- Found GTS: TRUE  
> -- Checking for module 'libswscale'
> --   Found libswscale, version 3.1.101
> -- Found SWSCALE: TRUE  
> -- Checking for module 'libavdevice >= 56.4.100'
> --   Found libavdevice , version 56.4.100
> -- Found AVDEVICE: TRUE (Required is at least version "56.4.100") 
> -- Checking for module 'libavformat'
> --   Found libavformat, version 56.40.101
> -- Found AVFORMAT: TRUE  
> -- Checking for module 'libavcodec'
> --   Found libavcodec, version 56.60.100
> -- Found AVCODEC: TRUE  
> -- Checking for module 'libavutil'
> --   Found libavutil, version 54.31.100
> -- Found AVUTIL: TRUE  
> -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
> -- Checking for module 'jsoncpp'
> --   Found jsoncpp, version 1.7.2
> -- Found JSONCPP: TRUE  
> -- Checking for module 'yaml-0.1'
> --   Found yaml-0.1, version 0.1.6
> -- Found YAML: TRUE  
> -- Checking for module 'libzip'
> --   Found libzip, version 1.0.1
> -- Found ZIP: TRUE  
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
> -- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") 
> -- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
> -- Checking for module 'gstreamer-1.0 >= 1.0'
> --   
> -- Checking for module 'gstreamer-base-1.0 >= 1.0'
> --   
> -- Found GStreamer: GSTREAMER_INCLUDE_DIRS;GSTREAMER_LIBRARIES;GSTREAMER_VERSION;GSTREAMER_BASE_INCLUDE_DIRS;GSTREAMER_BASE_LIBRARIES (Required is at least version "1.0") 
> -- Checking for module 'OGRE'
> --   Found OGRE, version 1.9.0
> -- Building klt_feature_tracker without catkin
> -- Building OpticalFlow with OpenCV
> -- Found MAVLink: /home/tony/PX4_Firmware/mavlink/include (found version "2.0") 
> -- catkin DISABLED
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
> -- Checking for module 'protobuf'
> --   Found protobuf, version 2.6.1
> -- Gazebo version: 9.13
> -- Found GStreamer: adding gst_camera_plugin
> -- Found GStreamer: adding gst_video_stream_widget
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> GSTREAMER_LIBRARIES (ADVANCED)
>     linked by target "LiftDragPlugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_gst_camera_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_parachute_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_catapult_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_barometer_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_wind_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_geotagged_images_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_opticalflow_mockup_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_magnetometer_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "sensor_msgs" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_irlock_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_video_stream_widget" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_controller_interface" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "std_msgs" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_gps_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_usv_dynamics_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_sonar_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "mav_msgs" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "nav_msgs" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_lidar_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_opticalflow_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_mavlink_interface" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_uuv_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_vision_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_multirotor_base_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_imu_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_gimbal_controller_plugin" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "physics_msgs" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
>     linked by target "gazebo_motor_model" in directory /home/tony/PX4_Firmware/Tools/sitl_gazebo
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/tony/PX4_Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
> See also "/home/tony/PX4_Firmware/build/px4_sitl_default/build_gazebo/CMakeFiles/CMakeError.log".
> [251/740] Building CXX object platform...CMakeFiles/px4_daemon.dir/client.cpp.o
> FAILED: cd /home/tony/PX4_Firmware/build/px4_sitl_default/build_gazebo && /usr/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DSEND_VISION_ESTIMATION_DATA=ON -GNinja /home/tony/PX4_Firmware/Tools/sitl_gazebo && /usr/bin/cmake -E touch /home/tony/PX4_Firmware/build/px4_sitl_default/external/Stamp/sitl_gazebo/sitl_gazebo-configure
> [251/740] Building CXX object platform...on/CMakeFiles/px4_daemon.dir/pxh.cpp.o
> ninja: build stopped: subcommand failed.
> Makefile:198: recipe for target 'px4_sitl_default' failed
> make: *** [px4_sitl_default] Error 1

**Comment by bys1123** [comment]
Suggest use ubuntu 18.04 or 20.04 to build px4 1.10 and later.

**Comment by liangpu597** [comment]
> Suggest use ubuntu 18.04 to build px4 1.10 and later.

～～～～ there is any way to solve it ?
I have to change from ubuntu 16.04 to 18.04?

**Comment by julianoes** [comment]
@liangpu597 

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_LIBRARIES (ADVANCED)
```
https://github.com/PX4/Firmware/blob/b5cc3c4ef5d287b9bddebf2d86ef2ae683443df6/Tools/setup/ubuntu.sh#L189-L204

**Comment by julianoes** [comment]
I'm going to close this. Please comment again if this is still a problem.
