### ISSUE TITLE
./Tools/setup/ubuntu.sh: line 149: [: missing `]'

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#14916]
https://github.com/PX4/Firmware/blob/master/Tools/setup/ubuntu.sh#L149

Tested on ubuntu 18.04 @ vmware and ubuntu 18.04 @ wsl.
will get this warning: ```./Tools/setup/ubuntu.sh: line 149: [: missing `]'```
This bug will cause can't detect arm-gcc already installed, will download again.

I'm not professional on this, don't know how to fix this.

**Comment by hamishwillee** [comment]
Me either, but I can reproduce it. 
@julianoes How's your debugging of bash scripts?
