### ISSUE TITLE
VTOL  QuadPlane: Change propeller rotation for MC

### ISSUE THREAD

**Issue by GigaFlopsis** [PX4/Firmware#14934]
Due to the design features, we are forced to use a reverse rotation of the propellers to compensate for the torque of the engines. 

In the standard configuration, the MC mode rotates the propellers inward. How do you feel about adding the MC_REVERSE_YAW parameter?
I have already implemented this function in my branch and debugged it on real tests.

**Comment by bresch** [comment]
@GigaFlopsis You can make a custom config and use the the `quad_h` mixer instead of `quad_x` to have the inverted props: 
https://docs.px4.io/v1.9.0/en/airframes/airframe_reference.html#quadrotor-h

**Comment by GigaFlopsis** [comment]
In this case, the question is not relevant.
