### ISSUE TITLE
memory overflow during make px4_sitl gazebo

### ISSUE THREAD

**Issue by bharath7kumar** [PX4/Firmware#14943]
RAM Overflows and laptop hangs when I try make px4_sitl gazebo. It overflows every time while  building the file "gazebo_wind_plugin.cpp.o". make px4_sitl jmavsim works well on the other hand. How do I go about this issue

Laptop Specs:

8gb RAM
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
1 physical processor; 4 cores; 8 threads
OS: Ubuntu 18.04

Logs:

```
bharath@bharathslaptop:~/Firmware$ make px4_sitl gazebo
-- PX4 version: v1.11.0-beta2-27-ge409ec0038
-- PX4 config file: /home/bharath/Firmware/boards/px4/sitl/default.cmake
-- PX4 config: px4_sitl_default
-- PX4 platform: posix
-- PX4 lockstep: enabled
-- cmake build type: RelWithDebInfo
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building for code coverage
-- ccache enabled (export CCACHE_DISABLE=1 to disable)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- build type is RelWithDebInfo
-- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-286-g24f2e60
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bharath/Firmware/build/px4_sitl_default
[0/743] git submodule src/drivers/gps/devices
[1/743] git submodule src/lib/ecl
[2/743] git submodule mavlink/include/mavlink/v2.0
[5/743] git submodule Tools/sitl_gazebo
[12/743] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Using C++17 compiler
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'bullet>=2.82'
--   Found bullet, version 2.87
-- Found Simbody: /usr/include/simbody  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Boost version: 1.65.1
-- Looking for OGRE...
-- OGRE_PREFIX_WATCH changed.
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found suitable version "3.0.0", minimum required is "2.3.0") 
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.2.5
-- Found ZeroMQ: TRUE (Required is at least version "4") 
-- Checking for module 'uuid'
--   Found uuid, version 2.31.1
-- Found UUID: TRUE  
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.0.0
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Found DL: TRUE  
-- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
-- Checking for module 'gts'
--   Found gts, version 0.7.6
-- Found GTS: TRUE  
-- Checking for module 'libswscale'
--   Found libswscale, version 4.8.100
-- Found SWSCALE: TRUE  
-- Checking for module 'libavdevice >= 56.4.100'
--   Found libavdevice , version 57.10.100
-- Found AVDEVICE: TRUE (Required is at least version "56.4.100") 
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Found AVFORMAT: TRUE  
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Found AVCODEC: TRUE  
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Found AVUTIL: TRUE  
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.58.0") 
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Found JSONCPP: TRUE  
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.1.7
-- Found YAML: TRUE  
-- Checking for module 'libzip'
--   Found libzip, version 1.1.2
-- Found ZIP: TRUE  
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Found OpenCV: /usr (found version "3.2.0") 
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Checking for module 'gstreamer-1.0 >= 1.0'
--   Found gstreamer-1.0 , version 1.14.5
-- Checking for module 'gstreamer-base-1.0 >= 1.0'
--   Found gstreamer-base-1.0 , version 1.14.5
-- Found GStreamer: GSTREAMER_INCLUDE_DIRS;GSTREAMER_LIBRARIES;GSTREAMER_VERSION;GSTREAMER_BASE_INCLUDE_DIRS;GSTREAMER_BASE_LIBRARIES (Required is at least version "1.0") 
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- Found MAVLink: /home/bharath/Firmware/mavlink/include (found version "2.0") 
-- catkin DISABLED
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread;-lpthread (found version "3.0.0") 
-- Checking for module 'protobuf'
--   Found protobuf, version 3.0.0
-- Gazebo version: 9.13
-- Found GStreamer: adding gst_camera_plugin
-- Found GStreamer: adding gst_video_stream_widget
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bharath/Firmware/build/px4_sitl_default/build_gazebo
[739/743] Performing build step for 'sitl_gazebo'
[12/100] Generating /home/bharath/Firm...sitl_gazebo/models/sf10a/sf10a-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/sf10a/sf10a.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/sf10a/sf10a-gen.sdf
[13/100] Generating /home/bharath/Firm...s/sitl_gazebo/models/c920/c920-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/c920/c920.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/c920/c920-gen.sdf
[14/100] Generating /home/bharath/Firm...ls/mb1240-xl-ez4/mb1240-xl-ez4-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4-gen.sdf
[15/100] Generating /home/bharath/Firm...models/3DR_gps_mag/3DR_gps_mag-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag-gen.sdf
[16/100] Generating /home/bharath/Firm..._gazebo/models/px4flow/px4flow-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/px4flow/px4flow.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/px4flow/px4flow-gen.sdf
[17/100] Generating /home/bharath/Firm..._gazebo/models/pixhawk/pixhawk-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/pixhawk/pixhawk.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/pixhawk/pixhawk-gen.sdf
[18/100] Generating /home/bharath/Firm...models/matrice_100/matrice_100-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/matrice_100/matrice_100.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/matrice_100/matrice_100-gen.sdf
[28/100] Generating /home/bharath/Firm...s/sitl_gazebo/models/r200/r200-gen.sdf
/home/bharath/Firmware/Tools/sitl_gazebo/models/r200/r200.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/r200/r200-gen.sdf
[37/100] Generating /home/bharath/Firm...Tools/sitl_gazebo/models/iris/iris.sdf

[37/100] Building CXX object CMakeFile...lugin.dir/src/gazebo_wind_plugin.cpp.o
```
I interrupted at this point to get the logs just before it hangs

**Comment by julianoes** [comment]
Generally, this is a RAM issue. So you should be able to work around it by having more RAM available.

Alternatively, you could try to build with `-j2` instead of e.g. `-j8`, however, I need to find out how that argument can be passed to the Gazebo build.

**Comment by bharath7kumar** [comment]
I was able to build with the same laptop a few months back. But it is not working now. I tried make px4_sitl gazebo -j1, it still used all the eight threads.

**Comment by julianoes** [comment]
@dagar how can we pass the `-jX` argument to the sitl_gazebo build?

**Comment by dagar** [comment]
> @dagar how can we pass the `-jX` argument to the sitl_gazebo build?

Passed through here somehow. https://github.com/PX4/Firmware/blob/6c16a29d26b2c79d63f1459be361c8972399d9ce/platforms/posix/cmake/sitl_target.cmake#L34-L47

**Comment by BazookaJoe1900** [comment]
The high needs of RAM when compiling the SITL happens to me too. In my case I am working with VM that if I don't give the VM more then 12GB of RAM its start to use cache.
Also the duration of building the SITL can be few long minutes.
is that normal? is there might be some faulty build argument that can be changed?
I tried to find one but couldn't.

**Comment by julianoes** [comment]
> Passed through here somehow. 

@dagar that's the part I'm confused about :smile:

**Comment by julianoes** [comment]
I'm generally confused about the parallel build. I've tried going to the basics and removed `ninja` and disabled `ccache` and just `make px4_sitl -j1` already used 2-4 cores building :confused:.

**Comment by julianoes** [comment]
Ok, I have a fix coming up that actually allows to configure how parallel the build should happen.

**Comment by julianoes** [comment]
With #14971 you can now build with fewer cores in order to avoid running out of RAM:

```
make px4_sitl gazebo -2
```

**Comment by shu-bamma** [comment]
> With #14971 you can now build with fewer cores in order to avoid running out of RAM:
> 
> ```
> make px4_sitl gazebo -2
> ```

same issue...dosen't help my case.

**Comment by cdbharath** [comment]
> > With #14971 you can now build with fewer cores in order to avoid running out of RAM:
> > ```
> > make px4_sitl gazebo -2
> > ```
> 
> same issue...dosen't help my case.

pull the commit that is mentioned in this thread. It worked for my case.

**Comment by shu-bamma** [comment]
> > > With #14971 you can now build with fewer cores in order to avoid running out of RAM:
> > > ```
> > > make px4_sitl gazebo -2
> > > ```
> > 
> > 
> > same issue...dosen't help my case.
> 
> pull the commit that is mentioned in this thread. It worked for my case.

@cdbharath  thanks for the response..i am pretty new to this stuff so bear with me.
you mean the latest one right??
Makefile: fix j for clang-tidy calls

**Comment by dagar** [comment]
@shu-bamma from a clean state (make distclean) can you build and capture the full output with the error message?

**Comment by shu-bamma** [comment]
> @shu-bamma from a clean state (make distclean) can you build and capture the full output with the error message?



> RAM Overflows and laptop hangs when I try make px4_sitl gazebo. It overflows every time while building the file "gazebo_wind_plugin.cpp.o". make px4_sitl jmavsim works well on the other hand. How do I go about this issue
> 
> Laptop Specs:
> 
> 8gb RAM
> Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
> 1 physical processor; 4 cores; 8 threads
> OS: Ubuntu 18.04
> 
> Logs:
> 
> ```
> bharath@bharathslaptop:~/Firmware$ make px4_sitl gazebo
> -- PX4 version: v1.11.0-beta2-27-ge409ec0038
> -- PX4 config file: /home/bharath/Firmware/boards/px4/sitl/default.cmake
> -- PX4 config: px4_sitl_default
> -- PX4 platform: posix
> -- PX4 lockstep: enabled
> -- cmake build type: RelWithDebInfo
> -- The CXX compiler identification is GNU 7.5.0
> -- The C compiler identification is GNU 7.5.0
> -- The ASM compiler identification is GNU
> -- Found assembler: /usr/bin/cc
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Building for code coverage
> -- ccache enabled (export CCACHE_DISABLE=1 to disable)
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
> -- build type is RelWithDebInfo
> -- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-286-g24f2e60
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/bharath/Firmware/build/px4_sitl_default
> [0/743] git submodule src/drivers/gps/devices
> [1/743] git submodule src/lib/ecl
> [2/743] git submodule mavlink/include/mavlink/v2.0
> [5/743] git submodule Tools/sitl_gazebo
> [12/743] Performing configure step for 'sitl_gazebo'
> -- install-prefix: /usr/local
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Performing Test COMPILER_SUPPORTS_CXX17
> -- Performing Test COMPILER_SUPPORTS_CXX17 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX14
> -- Performing Test COMPILER_SUPPORTS_CXX14 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX11
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
> -- Performing Test COMPILER_SUPPORTS_CXX0X
> -- Performing Test COMPILER_SUPPORTS_CXX0X - Success
> -- Using C++17 compiler
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Boost version: 1.65.1
> -- Found the following Boost libraries:
> --   system
> --   thread
> --   filesystem
> --   chrono
> --   date_time
> --   atomic
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'bullet>=2.82'
> --   Found bullet, version 2.87
> -- Found Simbody: /usr/include/simbody  
> -- Boost version: 1.65.1
> -- Found the following Boost libraries:
> --   thread
> --   system
> --   filesystem
> --   program_options
> --   regex
> --   iostreams
> --   date_time
> --   chrono
> --   atomic
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
> -- Boost version: 1.65.1
> -- Looking for OGRE...
> -- OGRE_PREFIX_WATCH changed.
> -- Checking for module 'OGRE'
> --   Found OGRE, version 1.9.0
> -- Found Ogre Ghadamon (1.9.0)
> -- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
> -- Looking for OGRE_Paging...
> -- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
> -- Looking for OGRE_Terrain...
> -- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
> -- Looking for OGRE_Property...
> -- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
> -- Looking for OGRE_RTShaderSystem...
> -- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
> -- Looking for OGRE_Volume...
> -- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
> -- Looking for OGRE_Overlay...
> -- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found suitable version "3.0.0", minimum required is "2.3.0") 
> -- Config-file not installed for ZeroMQ -- checking for pkg-config
> -- Checking for module 'libzmq >= 4'
> --   Found libzmq , version 4.2.5
> -- Found ZeroMQ: TRUE (Required is at least version "4") 
> -- Checking for module 'uuid'
> --   Found uuid, version 2.31.1
> -- Found UUID: TRUE  
> -- Checking for module 'tinyxml2'
> --   Found tinyxml2, version 6.0.0
> -- Looking for dlfcn.h - found
> -- Looking for libdl - found
> -- Found DL: TRUE  
> -- FreeImage.pc not found, we will search for FreeImage_INCLUDE_DIRS and FreeImage_LIBRARIES
> -- Checking for module 'gts'
> --   Found gts, version 0.7.6
> -- Found GTS: TRUE  
> -- Checking for module 'libswscale'
> --   Found libswscale, version 4.8.100
> -- Found SWSCALE: TRUE  
> -- Checking for module 'libavdevice >= 56.4.100'
> --   Found libavdevice , version 57.10.100
> -- Found AVDEVICE: TRUE (Required is at least version "56.4.100") 
> -- Checking for module 'libavformat'
> --   Found libavformat, version 57.83.100
> -- Found AVFORMAT: TRUE  
> -- Checking for module 'libavcodec'
> --   Found libavcodec, version 57.107.100
> -- Found AVCODEC: TRUE  
> -- Checking for module 'libavutil'
> --   Found libavutil, version 55.78.100
> -- Found AVUTIL: TRUE  
> -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.58.0") 
> -- Checking for module 'jsoncpp'
> --   Found jsoncpp, version 1.7.4
> -- Found JSONCPP: TRUE  
> -- Checking for module 'yaml-0.1'
> --   Found yaml-0.1, version 0.1.7
> -- Found YAML: TRUE  
> -- Checking for module 'libzip'
> --   Found libzip, version 1.1.2
> -- Found ZIP: TRUE  
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
> -- Found OpenCV: /usr (found version "3.2.0") 
> -- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
> -- Checking for module 'gstreamer-1.0 >= 1.0'
> --   Found gstreamer-1.0 , version 1.14.5
> -- Checking for module 'gstreamer-base-1.0 >= 1.0'
> --   Found gstreamer-base-1.0 , version 1.14.5
> -- Found GStreamer: GSTREAMER_INCLUDE_DIRS;GSTREAMER_LIBRARIES;GSTREAMER_VERSION;GSTREAMER_BASE_INCLUDE_DIRS;GSTREAMER_BASE_LIBRARIES (Required is at least version "1.0") 
> -- Checking for module 'OGRE'
> --   Found OGRE, version 1.9.0
> -- Building klt_feature_tracker without catkin
> -- Building OpticalFlow with OpenCV
> -- Found MAVLink: /home/bharath/Firmware/mavlink/include (found version "2.0") 
> -- catkin DISABLED
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread;-lpthread;-lpthread (found version "3.0.0") 
> -- Checking for module 'protobuf'
> --   Found protobuf, version 3.0.0
> -- Gazebo version: 9.13
> -- Found GStreamer: adding gst_camera_plugin
> -- Found GStreamer: adding gst_video_stream_widget
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/bharath/Firmware/build/px4_sitl_default/build_gazebo
> [739/743] Performing build step for 'sitl_gazebo'
> [12/100] Generating /home/bharath/Firm...sitl_gazebo/models/sf10a/sf10a-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/sf10a/sf10a.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/sf10a/sf10a-gen.sdf
> [13/100] Generating /home/bharath/Firm...s/sitl_gazebo/models/c920/c920-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/c920/c920.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/c920/c920-gen.sdf
> [14/100] Generating /home/bharath/Firm...ls/mb1240-xl-ez4/mb1240-xl-ez4-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4-gen.sdf
> [15/100] Generating /home/bharath/Firm...models/3DR_gps_mag/3DR_gps_mag-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag-gen.sdf
> [16/100] Generating /home/bharath/Firm..._gazebo/models/px4flow/px4flow-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/px4flow/px4flow.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/px4flow/px4flow-gen.sdf
> [17/100] Generating /home/bharath/Firm..._gazebo/models/pixhawk/pixhawk-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/pixhawk/pixhawk.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/pixhawk/pixhawk-gen.sdf
> [18/100] Generating /home/bharath/Firm...models/matrice_100/matrice_100-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/matrice_100/matrice_100.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/matrice_100/matrice_100-gen.sdf
> [28/100] Generating /home/bharath/Firm...s/sitl_gazebo/models/r200/r200-gen.sdf
> /home/bharath/Firmware/Tools/sitl_gazebo/models/r200/r200.sdf.jinja -> /home/bharath/Firmware/Tools/sitl_gazebo/models/r200/r200-gen.sdf
> [37/100] Generating /home/bharath/Firm...Tools/sitl_gazebo/models/iris/iris.sdf
> 
> [37/100] Building CXX object CMakeFile...lugin.dir/src/gazebo_wind_plugin.cpp.o
> ```
> 
> I interrupted at this point to get the logs just before it hangs

@dagar this is the EXACT error and machine configurations i have , then in #14971 @julianoes claimed to have fixed it but you pointed out about the CI failing and from then on i did not follow your chats. In this fix he has made a total of 4 commits, which one should i pull was my doubt (if any of them actually fix the problem that is)
Thanks

**Comment by julianoes** [comment]
I only see this now. @shu-bamma you're right. It does not actually work for the Gazebo case.

**Comment by julianoes** [comment]
It is now using the number of cores on your system, see: https://github.com/PX4/PX4-Autopilot/commit/52bb99688f4c828aa95e5e337269880cfca94f50

**Comment by offjangir** [comment]
The build is not over yet, let the machine run for a while I have good harware specs it took about  40-45 mins after it hangs . make worked without specifying cores. Sit back and let it process.
