### ISSUE TITLE
Git clone doesn't download some particular files

### ISSUE THREAD

**Issue by Mridul1009** [PX4/Firmware#14968]
When I git clone this repo, I can't seem to download a few files in the Tools folder. Namely:
flightgear_bridge
jMAVSim
sitl_gazebo

These folders are downloading but not the subfiles
How to solve it?
Thanks!

**Comment by TSC21** [comment]
https://dev.px4.io/master/en/setup/building_px4.html#get_px4_code.

In your case since you cloned already: `git submodule update --init --recursive`.

**Comment by Mridul1009** [comment]
That worked
Thank you!
