### ISSUE TITLE
feature request : Add CRUISE mode for fixedwings

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#14975]
Hi

we need a cruise mode for fixed-wing . it is like Position mode however airspeed must be fixed and be Independent from throttle stick . this mode can decrease workload of the pilot and prevent from stall.

**Comment by bresch** [comment]
@moreba1 Do you need this because you need to use the throttle stick for something else? Usually, flying at cruise speed is made easy using a spring-loaded throttle stick.

**Comment by moreba1** [comment]
> 
> 
> @moreba1 Do you need this because you need to use the throttle stick for something else? Usually, flying at cruise speed is made easy using a spring-loaded throttle stick.

No, I will use a tablet for GCS and don't use RC . in some situations there is a need to change mode to position for switching a VTOL between Fixedwing and Multirotor.

**Comment by bresch** [comment]
@moreba1 Ok, so you have a joystick, right?

I'm trying to understand why you would need this mode.
> this mode can decrease workload of the pilot

If you don't want to let the pilot change the speed, you can set cruise = min = max airspeed. Does he need to change it sometimes?

> and prevent from stall

If TECS (altitude + speed controller) is tuned properly, the plane won't stall, even with the throttle stick at 0 and full pitch up.

**Comment by moreba1** [comment]
> @moreba1 Ok, so you have a joystick, right?

Yes

> If you don't want to let the pilot change the speed, you can set cruise = min = max airspeed. Does he need to change it sometimes?

Yes, we can limit the range of airspeed. and it will fly with the minimum airspeed at 0 throttle.

**Comment by bresch** [comment]
Cool, I'll close the issue then. Feel free to reopen if something is still not clear.
