### ISSUE TITLE
Error when running ubuntu_sim_ros_melodic.sh script

### ISSUE THREAD

**Issue by daylanc** [PX4/Firmware#14984]
Hello,

Not sure if I'm posting this in the correct section, but I am running into issues when running the following command: `bash ubuntu_sim_ros_melodic.sh` script from the following installation website: https://dev.px4.io/master/en/setup/dev_env_linux_ubuntu.html

I successfully installed Gazebo and JMAVSim using the `bash ./Tools/setup/ubuntu.sh` script, and seem to have installed ROS Melodic from the first part of the `ubuntu_sim_ros_melodic.sh` script, but run into the following errors:

![Screenshot from 2020-05-26 17-31-41](https://user-images.githubusercontent.com/34255535/82974964-e7139900-9f76-11ea-89e3-b41c16777cd3.png)
![Screenshot from 2020-05-26 17-32-27](https://user-images.githubusercontent.com/34255535/82974973-eb3fb680-9f76-11ea-8f88-3be50cfe7e42.png)

Hopefully someone could help me understand what dependencies i am missing or if I missed something during the installation steps.

Thanks!

**Comment by julianoes** [comment]
It says `No module named future`.

Can you try `pip install --user future`.

**Comment by daylanc** [comment]
@julianoes Thanks for the reply. after running your suggested command, it seems like I could install 1 of 6 packages. Here's the next error I get:

![Screenshot from 2020-05-27 12-36-19](https://user-images.githubusercontent.com/34255535/83079054-ae2b0100-a016-11ea-8d5f-32d5781e0176.png)

**Comment by TSC21** [comment]
> @julianoes Thanks for the reply. after running your suggested command, it seems like I could install 1 of 6 packages. Here's the next error I get:
> 
> ![Screenshot from 2020-05-27 12-36-19](https://user-images.githubusercontent.com/34255535/83079054-ae2b0100-a016-11ea-8d5f-32d5781e0176.png)

Are you sure that the install scripts didn't run into any errors?

**Comment by TSC21** [comment]
Also why are you building MAVROS from source? If you want to do that you need to follow the propper procedures so that the dependencies are installed: https://github.com/mavlink/mavros/tree/master/mavros#source-installation

**Comment by daylanc** [comment]
@TSC21 I was following the Environment Setup page to get started: https://dev.px4.io/master/en/setup/dev_env_linux_ubuntu.html

Not sure if this is the correct way to get started with PX4 and simulation or not

**Comment by TSC21** [comment]
> @TSC21 I was following the Environment Setup page to get started: https://dev.px4.io/master/en/setup/dev_env_linux_ubuntu.html
> 
> Not sure if this is the correct way to get started with PX4 and simulation or not

OK and where in that documentation you read that MAVROS is to be installed from source?

**Comment by daylanc** [comment]
@TSC21 I wasn't trying to install MAVROS from source. That's the error I received when I ran `bash ubuntu_sim_ros_melodic.sh`

**Comment by TSC21** [comment]
> @TSC21 I wasn't trying to install MAVROS from source. That's the error I received when I ran `bash ubuntu_sim_ros_melodic.sh`

Ok. So does any other error appear before the setup reaches to that stage?

**Comment by daylanc** [comment]
Here's my entire output:

![1](https://user-images.githubusercontent.com/34255535/83080031-dae01800-a018-11ea-841e-15288aad6ddc.png)
![2](https://user-images.githubusercontent.com/34255535/83080034-dddb0880-a018-11ea-8978-63862b3aeb51.png)
![3](https://user-images.githubusercontent.com/34255535/83080036-dfa4cc00-a018-11ea-8ec9-c185b7eb64ef.png)
![4](https://user-images.githubusercontent.com/34255535/83080037-e2072600-a018-11ea-8144-b0bae2ecea9d.png)

**Comment by TSC21** [comment]
`rosdep: command not found` means that you probably don't have the ROS distro `setup.bash` properly source or even not properly installed.

**Comment by TSC21** [comment]
Also, try to manually install and setup rosdep - check section 1.6.1 in http://wiki.ros.org/melodic/Installation/Ubuntu.

**Comment by daylanc** [comment]
@TSC21 manually installing rosdep seemed to be the solution. All 6 packages were built successfully. I wonder why this wasn't done with the `bash ubuntu_sim_ros_melodic.sh` script? I started this install with a clean install of Ubuntu 18.04.

**Comment by TSC21** [comment]
> @TSC21 manually installing rosdep seemed to be the solution. All 6 packages were built successfully. I wonder why this wasn't done with the `bash ubuntu_sim_ros_melodic.sh` script? I started this install with a clean install of Ubuntu 18.04.

@hamishwillee

**Comment by hamishwillee** [comment]
Can someone here create a PR to update it as needed - since you know what needs to happen. I'm happy to test it afterwards.

**Comment by hamishwillee** [comment]
@daylanc @TSC21 Neither of you able to update the script?

**Comment by TSC21** [comment]
Fix in https://github.com/PX4/Devguide/pull/1045. @hamishwillee sorry for the delay.

**Comment by hamishwillee** [comment]
Thanks Nuno!

**Comment by jmurraylouw** [comment]
This is still a problem. I just ran `bash ubuntu_sim_ros_melodic.sh` on a clean install on Ubuntu 18 and it gives the same error.

Running:
```
sudo rosdep init
rosdep update
```
also solved the problem.

Maybe the updated script wasn't uploaded to where it is download from? (`wget https://raw.githubusercontent.com/PX4/Devguide/master/build_scripts/ubuntu_sim_ros_melodic.sh`)
