### ISSUE TITLE
ERROR [sensors] fewer accels than calibrations, resetting all CAL_GYROx_ID

### ISSUE THREAD

**Issue by cesarecaputi** [PX4/Firmware#15006]
Hi,
while launching the px4_sitl/mavros launch file I got this error:

ERROR [sensors] fewer accels than calibrations, resetting all CAL_GYROx_ID
INFO  [commander] LED: open /dev/led0 failed (22)
INFO  [init] Mixer: etc/mixers/quad_x.main.mix on /dev/pwm_output0

Does anyone know how to fix it? Thanks

**Comment by dagar** [comment]
Is this still a problem with current master?

This error and the forced calibration reset will actually go away entirely with https://github.com/PX4/Firmware/pull/14776, although it's weird you're seeing it at all with SITL.

**Comment by mhkabir** [comment]
@dagar this is the same as I saw in https://github.com/PX4/Firmware/issues/10686#issuecomment-639178521

Removing the old parameter file fixed it.

**Comment by dagar** [comment]
I believe this is fixed in master.
