### ISSUE TITLE
tailsitter vtol frnot/back transmission failed (no pitch set value is generated)

### ISSUE THREAD

**Issue by xdwgood** [PX4/Firmware#15037]
**Describe the bug**
When I used tailsitter to fly, I found that **sometimes**(Sometimes it can enter successfully, in the same flight) even if I switch, vtoll can not enter the fw mode

**To Reproduce**
1. use master branch fly(tailsitter vtol)
2. in altitude mode and try transmission(mc to fw) 
3. The drone pitch angle has not changed, there is no tilt acceleration

**Expected behavior**
Every time a customer uses a stick for transmission, vtol should enter the transmission state correctly

**Log Files and Screenshots**
https://logs.px4.io/plot_app?log=4df87c34-da2f-46be-b612-ddcc13b135c8

![840347981](https://user-images.githubusercontent.com/24932258/83841898-55551a00-a734-11ea-9430-6e67fcd8b502.jpg)

**Additional context**
I found that fw to mc sometimes fails when I try to send a transfer command using the remote control. I will do some investigations to see where the problem is. I now suspect 

numerical calculations under certain extreme conditions? (eg:at the start of transmission, the actual/setpoint angle of pitch are both 0)

here: https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/tailsitter.cpp#L206-L218

Because I compared the two switches, the only difference I found was that the drone angle/setpoint angle was close to 0 before the failed transmission started

FYI: @sfuhrer  :smiley:

**Comment by xdwgood** [comment]
Is there any problem with the numerical calculations under certain extreme conditions? (At the start of transmission, the actual angle of pitch and the set angle are both 0)

here:   https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/tailsitter.cpp#L206-L218

Because I compared the two switches, the only difference I found was that the drone angle/setpoint angle was close to 0 before the failed transmission started

**Comment by xdwgood** [comment]
When the transmission is run in altitude mode, the setpoint angle value generated by mc and fw is not published　herer: https://github.com/PX4/Firmware/blob/master/src/modules/mc_att_control/mc_att_control_main.cpp#L329
https://github.com/PX4/Firmware/blob/master/src/modules/fw_att_control/FixedwingAttitudeControl.cpp#L141

So I am curious about the meaning of the check here: https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_att_control_main.cpp#L436

On the other hand about this check: `updated() `should be used, right?(Instead of` update()`)　https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_att_control_main.cpp#L401-L402

My idea is to remove this check because the angle setting in the conversion stage is generated independently by vtol control....

Back to this question, I suspect that this has not been run for some reason:　https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_att_control_main.cpp#L437

**Comment by sfuhrer** [comment]
@xdwgood Did I understand correct, that the issue is this spike in the transition switch log?
![image](https://user-images.githubusercontent.com/26798987/84199559-ad2db100-aaa5-11ea-8d1e-8d2e44ecfa80.png)
Or what exactly? If it's the switch, then this is not really VTOL related, but rather a RC problem no?

**Comment by xdwgood** [comment]
@sfuhrer  
https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/tailsitter.cpp#L216

The calculated `tilt` sometimes has problems. I checked it using the `PX4_ISFINITE(tilt)` function and found this problem.
![Screenshot from 2020-07-16 20-06-54](https://user-images.githubusercontent.com/24932258/87669086-ec83a780-c79f-11ea-9b97-21d0e70e83f9.png)

Corresponding code

![２１１２](https://user-images.githubusercontent.com/24932258/87669153-09b87600-c7a0-11ea-96b9-2701b7fc51a1.png)

**Comment by xdwgood** [comment]
No setpoint value is generated when the value check fails(8)

**Comment by xdwgood** [comment]
fix here: https://github.com/PX4/Firmware/pull/15352!
