### ISSUE TITLE
Compile with gazebo error

### ISSUE THREAD

**Issue by codevegan** [PX4/Firmware#15039]
I am using ubuntu 18.04 and gazebo 9. I have finished the jmavsim simulation， now i want to try with gazebo， i used the command as follows and failed

    
![Screenshot from 2020-06-05 14-35-16](https://user-images.githubusercontent.com/61835796/83844718-14f89a80-a73a-11ea-8585-368014d2218e.png)

**Comment by julianoes** [comment]
Can you try:
```
make clean
sudo apt-get update
sudo apt-get upgrade
make px4_sitl gazebo
```

**Comment by codevegan** [comment]
Thanks, It have been fixed.
