### ISSUE TITLE
OneShot broken on master

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#15043]
This is how the signal looks like, and apparently the ESC's don't like it:
![image](https://user-images.githubusercontent.com/281593/83882967-25f9d980-a743-11ea-8fcb-8a446e88ad12.png)
The problem is the 2 callbacks in the pwm driver, the rate controller output and RC (the signal is fine when shutting off RC).

I have not checked when it broke exactly, just that it is not aa380f351fa01edfce71533c7eaefec4ff6446ee.

**Comment by dagar** [comment]
Two immediate ideas that come to mind.

1. Add a special case in the `mixer_module` to not register additional callbacks after actuator_controls_0/actuator_controls_1 if they're part of the mix.
2. Add a low level (minimum interval?) protection for `oneshot`. Are there well defined requirements?

**Comment by dagar** [comment]
I'll also add a simple minimum interval (maximum rate) mechanism to `WorkItem`.
