### ISSUE TITLE
PX4 cube mission planner setting (using xbee  S2C pro module )

### ISSUE THREAD

**Issue by sinanoksuz** [PX4/Firmware#15205]
ı  use px4 cube , ı use telemetry as two Xbee S2C pro  (router coordinator)  But there is some issue , this is my setting on XCTU programs  
![r_yeristasyonu-usbdriver-com7_5cd2255084e56](https://user-images.githubusercontent.com/5104622/85462409-19340d00-b5ae-11ea-9b92-8b0541da60aa.jpg)

![r_iha1_5cd225a12d808](https://user-images.githubusercontent.com/5104622/85462396-16d1b300-b5ae-11ea-8e59-a6e9ac02a8a0.jpg)
![r_networkingcoordinator_5cd224930b850](https://user-images.githubusercontent.com/5104622/85462397-176a4980-b5ae-11ea-93de-0b4cb5cb4a26.jpg)
![r_routeradressing_5cd2250fe62bc](https://user-images.githubusercontent.com/5104622/85462399-176a4980-b5ae-11ea-8b00-958a15ea3c54.jpg)
![r_routernetworking_5cd2250ee2939](https://user-images.githubusercontent.com/5104622/85462401-1802e000-b5ae-11ea-8dfe-550c1660d71c.jpg)
![r_serialinterfacingcoordinator_5cd22492302aa](https://user-images.githubusercontent.com/5104622/85462403-189b7680-b5ae-11ea-943d-d8494ede3be6.jpg)
![r_xctu-genelekran_5cd22405876ee](https://user-images.githubusercontent.com/5104622/85462406-189b7680-b5ae-11ea-8a83-6c6a5731113c.jpg)

![r_adrssingcoordinator_5cd22493942a0](https://user-images.githubusercontent.com/5104622/85462389-1507ef80-b5ae-11ea-8842-94d98759fefd.jpg)
![r_drone-usbdriver-com6_5cd2255147a1a](https://user-images.githubusercontent.com/5104622/85462394-16391c80-b5ae-11ea-98ea-ddec525e6819.jpg)

Can you Help me . What kind of issue in this situation  ?  there is issue on missionplanner program)

**Comment by julianoes** [comment]
This GitHub repository is for PX4. Your issue presumably has to do with MissionPlanner which works with ArduPilot (and not PX4).

I would ask your question in: https://github.com/ArduPilot/MissionPlanner

**Comment by sinanoksuz** [comment]
okey thank you
