### ISSUE TITLE
V1.11.0 CBRK_VTOLARMING = 159753 doesn´t apply

### ISSUE THREAD

**Issue by taileron** [PX4/Firmware#15212]
The new in 1.11.0 introduced [CBRK_VTOLARMING](http://docs.px4.io/master/en/advanced_config/parameter_reference.html#CBRK_VTOLARMING) doesn't apply  

set from 0 to 159753 it should allow to arm in FW mode

It shows only an error not arming ... Vtol switch engaged

To do better research for #15155 I noticed that the necessary CBRK has no function

**Comment by julianoes** [comment]
FYI @sfuhrer @RomanBapst

**Comment by hamishwillee** [comment]
FYI @sfuhrer

**Comment by sfuhrer** [comment]
@taileron thanks for reporting that, https://github.com/PX4/Firmware/pull/15283 should fix it.

**Comment by taileron** [comment]
fixed: pr-VTOL-switch-check-arming now allows to arm with tx arm switch in fw mode if this CBRK is set
https://review.px4.io/plot_app?log=df6c7f49-d3e0-4373-9e13-bc48a8c9c85e
