### ISSUE TITLE
Comment fix

### ISSUE THREAD

**Issue by George-avy** [PX4/Firmware#15253]
https://github.com/PX4/Firmware/blob/400c44b5ef692838aa6f6ac040eb0dff7536b2e8/src/lib/rc/sbus.h#L64

Actually at 100kbps, 25bytes per frame and 8E2 (12bits per character) UART configuration , frame duration is exactly 3ms:

     25chars * 12bits/char / 100000bits/s = 3ms

**Comment by George-avy** [comment]
Same here: https://github.com/AvyFly/PXAvy/blob/stable_candidate/src/lib/rc/sbus.cpp#L306

**Comment by julianoes** [comment]
Thanks for the note. We would appreciate a pull request with your suggested changes, thanks.

**Comment by George-avy** [comment]
> Thanks for the note. We would appreciate a pull request with your suggested changes, thanks.
Yeah, I know...

**Comment by nrogelio** [comment]
Hi George-avy,

I hope you don't mind I created a PR to add your changes.

Best Regards.

**Comment by George-avy** [comment]
> Hi George-avy,
> 
> I hope you don't mind I created a PR to add your changes.
> 
> Best Regards.

Why would I mind? Good job!
