### ISSUE TITLE
Issue with PWM output of throttle channel 

### ISSUE THREAD

**Issue by githuweeee** [PX4/Firmware#15260]
I am testing the PWM OUTPUT at 1kHz with airframe setup Axial Racing 10 AX10. The desired PWM ouputs is variable from 0% to 100%. I set the PWM_MIN to 1 us and 
PWM_MAX to 999 us.

#
param set PWM_MIN 1
param set PWM_MAX 999
param set MAV_TYPE 10
param set PWM_RATE 1000
param set MIXER IO_pass
#
Yaw, Pitch and Roll channel are all good, but the throttle channel output varies from 500 us to 999 us.  How can I fix this?

**Comment by gepopa10** [comment]
Hi,

what voltages did you get with this method on the PWM signal pins?
