### ISSUE TITLE
Travis CI: Rewrite unit tests in G test framework

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1526]
The existing unit tests (Firmware/unittests) are written without any test framework and lack proper return value checking (they are in fact test harnesses). Moving them to G test would be a great first step, and then adding more checks.

**Comment by LorenzMeier** [comment]
@dagar Here are the current math tests:
https://github.com/PX4/Firmware/blob/master/src/systemcmds/tests/test_mathlib.cpp

The quick fix would be to add + -, etc. What do you think about the architecture? Right now most tests are bundled in the tests app. Does that make sense, or should we split them up to to unit tests? I've documented the different test systems here:
https://pixhawk.org/dev/unit_tests

**Comment by LorenzMeier** [comment]
@jgoppert Would you be willing to lend a hand with creating an automated HIL script based on your HIL work (https://github.com/PX4/HIL)? The overall setup I have in mind is similar to the auto test of APM (http://autotest.diydrones.com), however run on the actual hardware.
We do have hardware connected to a test system which executes on pushes and PRs, so its actually reasonably easy to set up if you can run it locally fine. The auto test code might serve as inspiration, I would appreciate if we could retain clarity about licenses though (if you pull in code, we need to license our own test system as GPL). https://github.com/diydrones/ardupilot/tree/master/Tools/autotest

**Comment by jgoppert** [comment]
I'll be glad to work on this. I would like to move away from JSBSim to a native python FDM to make is more x-platform. Having something similar to APM auto-test would be very valuable. This was the basis of my existing PX4/HIL work.

I think at some point using uORB as a basis for a simple C++ SIL would also be possible. I started work on a python SIL using uORB but haven't finished it yet. I know there is also work on a uORB based ROS SIL but I haven't looked at this closely yet.

**Comment by LorenzMeier** [comment]
@jgoppert The hardware test is now up and running, so all infrastructure would be in place. We can now extend this to more sensor / unit tests and HIL.

@dagar If you want to / need to have some of the unit tests on HW you will now get auto-feedback as well, similar to Travis.

![schnappschuss 2015-01-11 16 26 06](https://cloud.githubusercontent.com/assets/1208119/5695686/e614ea28-99ae-11e4-9bc0-d5785c073fcd.png)

**Comment by dagar** [comment]
That's awesome. To start with I'll make sure the existing tests will actually cause a failure if something goes wrong.

**Comment by LorenzMeier** [comment]
Done on master
