### ISSUE TITLE
STM32H7 CAN driver UAVCAN GlobalTimeSyncMaster pub conflict

### ISSUE THREAD

**Issue by mirkix** [PX4/Firmware#15305]
**Describe the bug**
When using a STM32H7 based autopilot like the HEX CubeOrange with UAV-CAN it publish `ERROR UAVCAN GlobalTimeSyncMaster pub conflict` messages.

**To Reproduce**
1. Load PX4 master on a CubeOrange
2. Enable UAV-CAN `param set UAVCAN_ENABLE 2`
3. Connect SLCAN Interface to CubeOrange
4. Start UAVCAN GUI Tool
5. Get Error Message in UAVCAN GUI Tool

**Log Files and Screenshots**
![Screenshot from 2020-07-10 11-34-20](https://user-images.githubusercontent.com/10398007/87140837-6993b600-c2a2-11ea-8a9a-7d20a2e4ce61.png)

**Comment by mirkix** [comment]
@JacobCrabill

**Comment by JacobCrabill** [comment]
Hmm, I can give this a look next week perhaps.

**Comment by JacobCrabill** [comment]
Just took a brief look at it; this comment in GlobalTimeSyncMaster may hold the key to the issue:

```
/**
 * Please read the specs to learn how the time synchronization works.
 *
 * No more than one object of this class is allowed per node; otherwise a disaster is bound to happen.
 *
 * NOTE: In order for this class to work, the platform driver must implement
 *       CAN bus TX loopback with both UTC and monotonic timestamping.
 *
 * Ref. M. Gergeleit, H. Streich - "Implementing a Distributed High-Resolution Real-Time Clock using the CAN-Bus"
 *
 * TODO: Enforce max one master per node
 */
```

Specifically: **NOTE: In order for this class to work, the platform driver must implement CAN bus TX loopback with both UTC and monotonic timestamping.**

I don't know when I'll have free time to look into this, but this could give another developer a clue on where to start digging into the driver.
