### ISSUE TITLE
qgroundcontrol error: Motor test command not supported

### ISSUE THREAD

**Issue by jimdgit** [PX4/Firmware#15313]
**Describe the bug**
When you try and perform the motor test from the UI you get " Motor test command not supported"
**To Reproduce**
Click props not installed then move a slider.
You get the yellow error toast " Motor test command not supported'
**Expected behavior**
The motor turns on.

PX4 FMU V5
PX PRO v1.10.1 Stable Release

**Comment by julianoes** [comment]
Motor testing is added with v1.11 as far as I know.

**Comment by jimdgit** [comment]
Ok with 1.11 Beta 2 I get "motor test denied"

**Comment by julianoes** [comment]
Cool, thanks for the feedback.

**Comment by bkueng** [comment]
Just to clarify you did not arm, but just press the safety button, correct?

**Comment by jimdgit** [comment]
Yes that’s exactly right just the safety button.
