### ISSUE TITLE
[VTOL] Not yawing towards VTOL Takeoff & Transition waypoint

### ISSUE THREAD

**Issue by ThomasRigi** [PX4/Firmware#15409]
**Describe the bug**
The VTOL is no longer yawing towards the VTOL Takeoff & Transition waypoint. This causes the mission to fail, triggering RTL (which then itself has a bug).
@RomanBapst 

**To Reproduce**
1. Checkout current master (aa7735c)
2. `make px4_sitl gazebo_standard_vtol`
3. Load a mission with a VTOL Takeoff & Transition waypoint, e.g. [square vtol.zip](https://github.com/PX4/Firmware/files/4967632/square.vtol.zip)
4. Start the mission and observe.

**Expected behavior**
The drone should yaw towards the waypoint and then transition.

**Log Files and Screenshots**
https://logs.px4.io/plot_app?log=44529271-2e29-4827-a09a-64d78b725c6d (RTL)

**Drone (please complete the following information):**
Gazebo standard_vtol

**Comment by dagar** [comment]
Do you happen to know when this last worked as expected/desired?

**Comment by ThomasRigi** [comment]
Most recent I have tested is on PR #15034 (June 04). Something in between must have gone wrong.

**Comment by sfuhrer** [comment]
It was this one: https://github.com/PX4/Firmware/pull/15358.
