### ISSUE TITLE
feature request : calculate terrain alt (AGL alt) during flight

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#15461]
Hi

For flying in some locations like mountains and valley, it is better that we have terrain alt. method of calculating terrain alt in px4 is using sonar and lasers. but there is a different method that we can use to monitor and manually avoid collision with the ground.
we have AMSL alt from GPS and the alt of the ground can be extracted from internet free sources with qgroundcontrol and save information area of mission it and upload to sd card.
so terrain alt can be calculated during flight and display in the ground station.

**Comment by bkueng** [comment]
Hi

I'm currently working on that, namely terrain data upload to the SD card, which then can be used for example during RTL.

**Comment by moreba1** [comment]
https://github.com/PX4/Firmware/issues/14265
