### ISSUE TITLE
How to add new vehicles?

### ISSUE THREAD

**Issue by KrisRadowski** [PX4/Firmware#15481]
Hey, I'm trying to add Iris modification; currently I made SDF file and model.config file; when I tried to start simulation, it's failed with error:
```
ninja: error: unknown target 'gazebo_iris_with_4sensors'
Makefile:224: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1
```
I made yesterday topic on discussion site here: https://discuss.px4.io/t/how-to-add-own-drone-as-build-target/17960, but since there's no response there, I decided to write about it here

Thanks! (and sorry for problems ;) )

**Comment by julianoes** [comment]
I've answered in the forum :).
