### ISSUE TITLE
Issues using VSCode

### ISSUE THREAD

**Issue by ghostSAS** [PX4/Firmware#15498]
Hi I tried to follow the instruction page to use VSCode as the IDE, and tried to make `px4_simple_app.c`. But I noticed several issues:
1. `#include <uORB/topics/sensor_combined.h> #include <uORB/topics/vehicle_attitude.h>`raise errors due to cannot find path. I even cannot these header files in Firmware that I can included as the path to `cmakelists.txt`. Actually, it seems only firmware V1.0 has `/topics/..` directory, but not for later versions. The only similar one that I can find is `sensor_combined.msg`, but it is not the correct one that should be included.
2. If I persist to `Cmake: Build Target` for `px4-fmu_v5` I got the following error:

> [main] Building folder: px4_simple_app px4-fmu_v5
> [main] Configuring folder: px4_simple_app 
> [main] Configuring folder: px4_simple_app 
> [proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/local/bin/arm-none-eabi-gcc-7.3.1 -H/Users/ys/Zeng_Lab/Tailsitter/Firmware/src/examples/px4_simple_app -B/Users/ys/Zeng_Lab/Tailsitter/Firmware/src/examples/px4_simple_app/build -G Ninja
> [cmake] Not searching for unused variables given on the command line.
> [cmake] CMake Warning (dev) in CMakeLists.txt:
> [cmake]   No project() command is present.  The top-level CMakeLists.txt file must
> [cmake]   contain a literal, direct call to the project() command.  Add a line of
> [cmake]   code such as
> [cmake] 
> [cmake]     project(ProjectName)
> [cmake] 
> [cmake]   near the top of the file, but after cmake_minimum_required().
> [cmake] 
> [cmake]   CMake is pretending there is a "project(Project)" command on the first
> [cmake]   line.
> [cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
> [cmake] 
> [cmake] -- The C compiler identification is GNU 7.3.1
> [cmake] -- The CXX compiler identification is GNU 7.3.1
> [cmake] -- Checking whether C compiler has -isysroot
> [cmake] -- Checking whether C compiler has -isysroot - yes
> [cmake] -- Checking whether C compiler supports OSX deployment target flag
> [cmake] -- Checking whether C compiler supports OSX deployment target flag - no
> [cmake] -- Detecting C compiler ABI info
> [cmake] -- Detecting C compiler ABI info - failed
> [cmake] -- Check for working C compiler: /usr/local/bin/arm-none-eabi-gcc-7.3.1
> [cmake] -- Check for working C compiler: /usr/local/bin/arm-none-eabi-gcc-7.3.1 - broken
> [cmake] CMake Error at /usr/local/Cellar/cmake/3.18.1/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
> [cmake]   The C compiler
> [cmake] 
> [cmake]     "/usr/local/bin/arm-none-eabi-gcc-7.3.1"
> [cmake] 
> [cmake]   is not able to compile a simple test program.
> [cmake] 
> [cmake]   It fails with the following output:
> [cmake] 
> [cmake]     Change Dir: /Users/ys/Zeng_Lab/Tailsitter/Firmware/src/examples/px4_simple_app/build/CMakeFiles/CMakeTmp
> [cmake]     
> [cmake]     Run Build Command(s):/usr/local/bin/ninja cmTC_cc451 && [1/2] Building C object CMakeFiles/cmTC_cc451.dir/testCCompiler.c.o
> [cmake]     [2/2] Linking C executable cmTC_cc451
> [cmake]     FAILED: cmTC_cc451 
> [cmake]     : && /usr/local/bin/arm-none-eabi-gcc-7.3.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_cc451.dir/testCCompiler.c.o -o cmTC_cc451   && :
> [cmake]     /usr/local/Cellar/gcc-arm-none-eabi/20180627/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol arch_paths_first; defaulting to 0000000000008018
> [cmake]     /usr/local/Cellar/gcc-arm-none-eabi/20180627/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): In function `exit':
> [cmake]     exit.c:(.text.exit+0x2c): undefined reference to `_exit'
> [cmake]     collect2: error: ld returned 1 exit status
> [cmake]     ninja: build stopped: subcommand failed.
> [cmake]     
> [cmake]     
> [cmake] 
> [cmake]   
> [cmake] 
> [cmake]   CMake will not be able to correctly generate this project.
> [cmake] 
> [cmake] 
> [cmake] CMake Warning (dev) in CMakeLists.txt:
> [cmake]   No cmake_minimum_required command is present.  A line of code such as
> [cmake] 
> [cmake]     cmake_minimum_required(VERSION 3.18)
> [cmake] 
> [cmake]   should be added at the top of the file.  The version specified may be lower
> [cmake]   if you wish to support older CMake versions for this project.  For more
> [cmake]   information run "cmake --help-policy CMP0000".
> [cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
> [cmake] 
> [cmake] -- Configuring incomplete, errors occurred!
> [cmake] See also "/Users/ys/Zeng_Lab/Tailsitter/Firmware/src/examples/px4_simple_app/build/CMakeFiles/CMakeOutput.log".
> [cmake] See also "/Users/ys/Zeng_Lab/Tailsitter/Firmware/src/examples/px4_simple_app/build/CMakeFiles/CMakeError.log".

3. The interesting thing is I succeeded to run `make px4-fum_v5 upload` in the shell. 

Many thanks for any suggestions!

**Comment by dagar** [comment]
Can you retry with current master? You need to select the variant and build at least once before intellisense will be able to find generated things like "uORB/topics/vehicle_attitude.h" and then fully function.
