### ISSUE TITLE
Where can I find the references paper for the pose estimation program in EKF2

### ISSUE THREAD

**Issue by zhanqx1024** [PX4/Firmware#15507]
Hello, I want to use vision for the external position estimation. I have set the Parameters EKF2_AID_MASK in QGroundControl, which of the bits in position 3 to enable vision position fusion, and the bits in position 4 to enable vision yaw fusion.

I get the pose estimation from my vision algorithm. Then I publish the position and orientation data via the publish node "/mavros/vision_pose/pose", I have flyed in a strong magnetic shielded environments, I can see the yaw from QGroundControl is not correct, so I put the drone static. But I find the yaw pointer from the QGroundControl have rotation, I subscribe the topic of "/mavros/imu/data", "/mavros/local_postion/pose", and "/aloam_high_frec"(which is my vision algorithm caculated pose node), I find the yaw data of "/mavros/local_position/pose" is almost the same to that from "mavros/imu/data", so I  want to know what could be the cause of this problem. I read the "Firmware/src/module/ekf_main.cpp" and the "Firmware/src/lib/ecl/EKF/ekf.cpp", I  can't find the implementation of the following functions: "predictCovriance()", "runYawEKFGSF()", "controlFusionModes()" and  "runTerrainEstimator()". !
![program](https://user-images.githubusercontent.com/55472563/89624894-859e6d80-d8c9-11ea-8284-f301acfe9b87.png)

I also want to know the principle of ekf2 program realization, I have read the paper of "a linear kalman Filter for MARG Orientation Estimation Using the Algebric Quaternion Algorithm" and "the Estimation of IMU and MARG orientation using a gradient descent algorithm". I have understood the pose estimation of  MARG sensor. But I want to know more about the fusion of the vision  and the MARG sensor, so where can I find references for the pose estimation program in EKF2? 

My email address is 1930739@tongji.edu.cn, I am very pleasure of your reply. Thank you very much!

**Comment by zhanqx1024** [comment]
![program](https://user-images.githubusercontent.com/55472563/89624744-46701c80-d8c9-11ea-9ff0-384247853eba.png)
Sorry ,the image of program|690x422 can't show, I reupload it

**Comment by julianoes** [comment]
Have you seen this?
https://github.com/PX4/ecl/tree/master/EKF/documentation

**Comment by bresch** [comment]
@zhanqx1024 You should be able to use your IDE or grep to find the definition of those function, if not, you can also search in GitHub: https://github.com/PX4/ecl/search?q=predictCovariance&unscoped_q=predictCovariance
