### ISSUE TITLE
FMUK66 UDP telemetry stream terminating after a few seconds

### ISSUE THREAD

**Issue by dk7xe** [PX4/Firmware#15580]
**Describe the bug**
MavLink Telemetry stream via UDP over T1 ethernet port on FMUK66 is terminating with current PX4 master after a few seconds. This was not the case with https://github.com/PX4/Firmware/pull/15154 

**To Reproduce**
1. adjust /etc/extras.txt on SDcard of FMUK66 with "mavlink start -x -u 14550 -r 200000 -t 10.0.0.5 -m onboard" where -t flag defines IP address of computer running QGC.
2. connect ethernet cable via T1 media converter to T1 ethernet port on FMUK66.
3. Set own computer IP to 10.0.0.5
4. Open QGC on computer
5. connect to FMUK66 via USB and set MAV_BROADCAST parameter to 2 - Only multicast
6. disconnect USB and power FMU from battery
7. reboot FMUK66 
8. telnet into FMU (FMUK66 has 10.0.0.2 as default IP) to verify connection
9. FMU sends Mavlink data to QGC via UDP over T1 ethernet port
10. after a few seconds mavlink stream terminates 
11. revert PX4 FW on FMUK66 to commit [df73662](https://github.com/PX4/Firmware/commit/df73662d66d7c767b11e1d8256cfdd12e1ac203c)
12. reboot FMUK66
13. FMU sends Mavlink data to QGC via UDP over T1 ethernet port without interruption

**Expected behavior**
Expectation is that UDP data stream via T1 ethernet port runs stable with current master as it was implemented with commit [df73662](https://github.com/PX4/Firmware/commit/df73662d66d7c767b11e1d8256cfdd12e1ac203c).

**Log Files and Screenshots**
na

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
NXP test drone 
FMUK66 with PX4 master
NavQ companion computer

**Additional context**
My test setup
![grafik](https://user-images.githubusercontent.com/3907200/90625632-2d952e80-e21a-11ea-8acd-2069ca327b80.png)
QGC is on linux machine in local network as 192.168.0.101.

Same happens when QGC is connected directly via T1 media converter to FMU. somwhere between commit [df73662](https://github.com/PX4/Firmware/commit/df73662d66d7c767b11e1d8256cfdd12e1ac203c) and now an change has been applied to let the UDP stream terminate after a while.

**Comment by dk7xe** [comment]
@davids5 is this something you can look at please?

**Comment by dk7xe** [comment]
hmm.. RTFM.. looks like MAV_BROADCAST set to 1 solves the problem.

**Comment by dk7xe** [comment]
Ok, the problem is solved for me if i set the MAV_BROADCAST parameter to 2 - Only multicast

**Comment by dk7xe** [comment]
Ok, the problem is solved for me if i set the MAV_BROADCAST parameter to 2 - Only multicast

**Comment by dk7xe** [comment]
Ok, the problem is solved for me if i set the MAV_BROADCAST parameter to 2 - Only multicast

**Comment by dk7xe** [comment]
@davids5 - Hi David, now it's an issue again. May you please look at that. Something has happened between between commit df73662 and now.

**Comment by davids5** [comment]
@dk7xe - I can get to it the latter half of the week

**Comment by davids5** [comment]
@dk7xe See https://github.com/PX4/NuttX/pull/116 once that merges I will do a Firmware update.

**Comment by dk7xe** [comment]
Hi @davids5  PX4/NuttX#116 has been merged already. Have u done the FW update?

**Comment by davids5** [comment]
@dk7xe yes 

You can see what is on master of Firmware by following https://github.com/PX4/Firmware/tree/master/platforms/nuttx/NuttX

to nuttx, then list commits 

https://github.com/PX4/NuttX/commits/ec20f2e6c5cc35b2b9bbe942dea55eabb81297b6

**Comment by dk7xe** [comment]
Thanx David. Meanwhile successfully tested.
