### ISSUE TITLE
Non-existant BAT1_x and BAT2_x params in 1.10.1

### ISSUE THREAD

**Issue by nbelanger99** [PX4/Firmware#15584]
The [Param Reference](https://dev.px4.io/v1.10/en/advanced/parameter_reference.html) for v1.10 stable shows BAT1_x and BAT2_x parameters, yet they don't seem to exist in the codebase, nor can they be acessed through the Nutshell when flashed on a Pixhawk 4 (fmu-v5_default).

**Comment by hamishwillee** [comment]
Correct. This was a bug in the docs, which should update shortly: https://github.com/PX4/Devguide/pull/1078

FYI the parameter docs are autogenerated generated from Firmware master and go into docs master. When new firmware is released we take a snapshot of docs master. If this is not timed carefully the parameters may include software that does not match the actual release.

What I have done is regnerated the parameters page from the v1.10.2 tag in Firmware. Note, the user guide was correct in this respect already.
