### ISSUE TITLE
Support for multiple batteries

### ISSUE THREAD

**Issue by nbelanger99** [PX4/Firmware#15583]
I have a Pixhawk 4 running 1.10.1, and I'm not seeing BAT1_x or BAT2_x params in QGC or through the Nutshell. When trying to set them through the shell, it says they don't exist. Are those params left out of the fmu_v5 build or something? If so, why?

Those params also don't show up in the source code. Are [the docs](https://dev.px4.io/v1.10/en/advanced/parameter_reference.html) incorrect?

**Comment by hamishwillee** [comment]
Not supported in v1.10. See comment in https://github.com/PX4/Firmware/issues/15584

Apologies.
