### ISSUE TITLE
imu temperature measurement (v1.11.0rc)

### ISSUE THREAD

**Issue by NicolasM0** [PX4/Firmware#15582]
**Describe the bug**
Version hardware: CUAV V5+
Version software: 1.11.0rc and current master (e2e72fd81e2f02c28a786e9fb5099284d0f3bd3e)

IMU temperature measurements are not correct:
- one accel temperature is inconsistent for temperature bellow about 30°C 
- one gyro temperature is nan (for all tested temperature)

It was ok with v1.10

![gyro](https://user-images.githubusercontent.com/59083163/90648725-3138ad80-e23a-11ea-8dfd-a064573af1d8.png)
![accel_m_30deg](https://user-images.githubusercontent.com/59083163/90648728-3138ad80-e23a-11ea-93c1-5afee46e090a.png)
![accel_p_30deg](https://user-images.githubusercontent.com/59083163/90648730-31d14400-e23a-11ea-9355-efce212b1f07.png)

**Comment by mrpollo** [comment]
@CUAVcaijie @jinger26 are you aware of any issues?

**Comment by cuhome** [comment]
@dagar @davids5 1.11.0 RC firmware does the temperature information of BMI055; the code has this bug.

**Comment by cuhome** [comment]
@gitfishup   Please initiate a new merge request to fix it.

**Comment by gitfishup** [comment]
You can see this link https://github.com/PX4/Firmware/pull/15638. I have submitted a pull request. @NicolasM0

**Comment by gitfishup** [comment]
It works well.
![a031c6a1f6f49de4889dfd458ab2001](https://user-images.githubusercontent.com/69180601/91535015-15718d80-e945-11ea-80db-bd929f0f8651.png)

**Comment by dagar** [comment]
> one accel temperature is inconsistent for temperature bellow about 30°C

Looks like the BMI055 accel, I'll check the driver.

> one gyro temperature is nan (for all tested temperature)

That's because the BMI055 (and BMI088) gyro doesn't have a temperature sensor.

**Comment by dagar** [comment]
I believe I have a fix for the BMI055 accel temperature. https://github.com/PX4/Firmware/pull/15640

For the BMI055 gyro in the past the temperature it reported was actually being pulled from the accel. In the new driver the accel and gyro are scheduled separately since they're effectively 2 separate sensors (each has a chip select, drdy, slightly different output data rate, etc). 

If the lack of temperature in the BMI055 gyro is a problem for either temperature calibration or an IMU heater I was thinking of adding explicit support for those functions to respect other temperature sources.

**Comment by dagar** [comment]
I've fixed the accel temperature reading in https://github.com/PX4/Firmware/pull/15640.

With regards to the BMI055 gyro lack of temperature sensor I'm not sure it's much of a problem. If you look in my last comment (https://github.com/PX4/Firmware/pull/15640#issuecomment-683125028) you'll see that the BMI055 gyro is actually quite stable with respect to temperature.

**Comment by NicolasM0** [comment]
> I've fixed the accel temperature reading in #15640.
> 
> With regards to the BMI055 gyro lack of temperature sensor I'm not sure it's much of a problem. If you look in my last comment ([#15640 (comment)](https://github.com/PX4/Firmware/pull/15640#issuecomment-683125028)) you'll see that the BMI055 gyro is actually quite stable with respect to temperature.


Onboard thermal calibration never stop (I think it is linked to this nan temperature)

**Comment by dagar** [comment]
> Onboard thermal calibration never stop (I think it is linked to this nan temperature)

If you're in a position to test that quickly let's update it to ignore these cases. In general we really can't assume everything has a valid temperature.
