### ISSUE TITLE
Could not find px4 using the following names:

### ISSUE THREAD

**Issue by saad2121** [PX4/Firmware#15590]
when i am running the command 
```
make posix_sitl_default gazebo
```
I am getting error as below.

CMake Error at CMakeLists.txt:31 (find_program):
  Could not find px4 using the following names:

-- Configuring incomplete, errors occurred!
See also "/home/saad/catkin_quad/src/Firmware/build/posix_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
See also "/home/saad/catkin_quad/src/Firmware/build/posix_sitl_default/build_gazebo/CMakeFiles/CMakeError.log".
[160/592] Building CXX object src/lib/...iles/controllib.dir/BlockLowPass.cpp.o
ninja: build stopped: subcommand failed.
Makefile:148: recipe for target 'posix_sitl_default' failed
make: *** [posix_sitl_default] Error 1

**Comment by bamboosdu** [comment]
Did you solve the problem? I meet the same problem.
If you solved it, could you share me with your solution.

**Comment by shonigmann** [comment]
for what it's worth, I ran into this issue after running "make clean"; couldn't find a direct solution but reinstalling PX4 (per https://dev.px4.io/v1.9.0/en/setup/dev_env_linux_ubuntu.html) fixed things for me

**Comment by Jaeyoung-Lim** [comment]
The problem is that you have the firmware directory inside catkin_ws

**Comment by sycamore-yu** [comment]
I meet the same problem too,the key of the problem is the version of cmake.The profile recommand cmake version from 3.10to 3.16.I change my cmake version from 3.27to 3.15 and problem sovled.The way change cmake version is build soft connection
