### ISSUE TITLE
Rename src/templates/module to something else

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#15593]
When writing a new module it is nice to start with the template module in [src/template/module](https://github.com/PX4/Firmware/tree/master/src/templates/module), however the fact that it is called "module" makes it cumbersome since you can't just search and replace to change the name to what you want.
We should rename the template module to something else than module

**Comment by bkueng** [comment]
Suggestions?

**Comment by CarlOlsson** [comment]
hm not sure... maybe
```
example_app
example_module
template_app
template_module
```

**Comment by bkueng** [comment]
`template_module` sounds good.
