### ISSUE TITLE
SITL: Master doesn't build on ubuntu 18.04

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#15603]
I get this:
```
parallels@parallels:~/repos/Firmware$ PX4_SIM_SPEED_FACTOR=2 HEADLESS=1 make px4_sitl_default gazebo_iris
[0/4] Performing build step for 'sitl_gazebo'
ninja: error: '/usr/lib/x86_64-linux-gnu/libignition-common1.so.1.0.1', needed by 'libmav_msgs.so', missing and no known rule to make it
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-build 
cd /home/parallels/repos/Firmware/build/px4_sitl_default/build_gazebo && /usr/bin/cmake --build /home/parallels/repos/Firmware/build/px4_sitl_default/build_gazebo -- -j2
ninja: build stopped: subcommand failed.
Makefile:217: recipe for target 'px4_sitl_default' failed
make: *** [px4_sitl_default] Error 1
```

I reran the tools installs script and same thing.

The ignition on my machine has moved past 1.0.1. I am up to date on 18.04:
![Screen Shot 2020-08-22 at 11 50 21 AM](https://user-images.githubusercontent.com/5876851/90963591-b6f06f00-e46d-11ea-9794-573805b73aff.png)

**Comment by Jaeyoung-Lim** [comment]
Can you try installing libignition-common-dev?

**Comment by DonLakeFlyer** [comment]
It's already installed:
![Screen Shot 2020-08-24 at 11 22 46 AM](https://user-images.githubusercontent.com/5876851/91081592-357b1700-e5fc-11ea-9ccf-d4f0c4483a06.png)

![Screen Shot 2020-08-24 at 11 22 57 AM](https://user-images.githubusercontent.com/5876851/91081606-39a73480-e5fc-11ea-8ea1-358ed8124979.png)

**Comment by Jaeyoung-Lim** [comment]
@DonLakeFlyer I think this is something on your system, since we can build it on container environments on 18.04

Which version of gazebo are you running?

**Comment by DonLakeFlyer** [comment]
> Which version of gazebo are you running?

Don't know. Whatever gets installed by the PX4 scripts. This is a clean 18.04 VM with the px4 dev toolchain installed on it.

**Comment by DonLakeFlyer** [comment]
Something broke recently I think with one of the latest 18.04 updates. Wait: I do have android studio on here as well.

**Comment by DonLakeFlyer** [comment]
Gazebo says 9.14.0

**Comment by Jaeyoung-Lim** [comment]
@DonLakeFlyer Okay, stange.

It looks like it simply can't find `libignition-common1.so.1.0.1'`

**Comment by DonLakeFlyer** [comment]
So I just updated master again. And then did a `make distclean` and built again and of course it works now. No idea why. I had tried that multiple time before and now suddenly it works. Anyway, sorry for the fire drill. Not sure what was happening.

**Comment by Jaeyoung-Lim** [comment]
@DonLakeFlyer Glad to hear that it was fixed!
