### ISSUE TITLE
Error while using another world 

### ISSUE THREAD

**Issue by Kush0301** [PX4/Firmware#15642]
Im getting an error while passing another world as an argument in the `mavros_posix_sitl.launch`. Im using PX4 with Ros melodic and Gazebo 9.
`roslaunch px4 mavros_posix_sitl.launch world=iris_vision` is the command that Im using.

![Screenshot from 2020-08-28 21-47-04](https://user-images.githubusercontent.com/50519473/91590888-ab271000-e979-11ea-9886-2ccd8329e81d.png)

**Comment by Jaeyoung-Lim** [comment]
@Kush0301 There is no such world as `iris_vision` : https://github.com/PX4/sitl_gazebo/tree/master/worlds
