### ISSUE TITLE
Check that the RTC time is set correctly by GPS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1565]
Current master has RTC support. It will retain the wall clock for a few days on FMUv2 hardware. Without setting it initially, it currently reads:

```
nsh> date
Jan 01 00:08:27 2000
```

The GPS driver has support for setting the time. It would be interesting to know if the date output changes.

**Comment by LorenzMeier** [comment]
@sjwilks In case you can get lock with a setup that has a terminal connected it might be a quick test.

**Comment by bansiesta** [comment]
This works for me, even after a power cycle.

**Comment by LorenzMeier** [comment]
So you're getting a 2015 date, not 2000, correct?

**Comment by LorenzMeier** [comment]
With current master - I fixed series 6-7 receivers just half an hour ago.

**Comment by mhkabir** [comment]
I tested with my timesync system, and I confirm that the date is correctly set by the companion computer. Uses similar method of setting as GPS.

**Comment by LorenzMeier** [comment]
Also works here:
```
nsh> date
Jan 04 11:08:57 2015
```
