### ISSUE TITLE
gpio_led not working 

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#1569]
I was trying to use the gpio_led app as a reference for GPIO control on the aux pins (on FMUv2.) 
https://github.com/PX4/Firmware/blob/master/src/modules/gpio_led/gpio_led.c
After scratching my head for some time on why my custom app wouldn't stay started, I tried running the default gpio_led app. 
It doesn't provide sufficient introspection on where it fails, but is probably when it tries to open the GPIO device (PX4FMU_DEVICE_PATH) After starting, if I try to stop it, I get `gpio_led : not running`
It fails here, as I could make out from my app : https://github.com/PX4/Firmware/blob/master/src/modules/gpio_led/gpio_led.c#L215

**Comment by LorenzMeier** [comment]
You will likely need to start the FMU app: ```fmu mode_gpio```. Refer to its documentation.

**Comment by LorenzMeier** [comment]
Closing since we start the FMU app now as default.
