### ISSUE TITLE
Set up RTC / time correctly in presence of GPS AND companion computer

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1571]
@mhkabir This one seems naturally for you. Currently your time sync code and the GPS driver both call the system time interface. We would need to work out who has precedence.

Note that the GPS time runs off the GPS time pulse which in turn runs off atomic clocks in space. So the odds that the companion computer time is more accurate goes to zero. In fact, we actually would want to sync it its time based on GPS time if possible.

**Comment by mhkabir** [comment]
@LorenzMeier The GPS clock gets precedence. I made sure that happens. The companion clock is only used one time when the first time message arrives, to get the clock in PX4 correct for logs, etc. . It is not augmented further. If GPS is present, GPS driver keeps correcting.

That reminds me, I need to PR to sdlog2 for it to use the time from RTC, and not directly from GPS.

**Comment by mhkabir** [comment]
Also, the companion clock is skewed to conform to GPS time if a certain ROS node is running.

**Comment by LorenzMeier** [comment]
Wohoo! Awesome. Closing.
