### ISSUE TITLE
Possible bug in TECS

### ISSUE THREAD

**Issue by EliaTarasov** [PX4/Firmware#15722]
Possible bug [in SKE derivative](https://github.com/PX4/Firmware/blob/master/src/lib/tecs/TECS.cpp#L253) calculation.

If `SKE_setpoint = 0.5f * _TAS_setpoint_adj * _TAS_setpoint_adj` 
then it's derivative is `_SKE_rate_setpoint = _TAS_setpoint_adj  * _TAS_rate_setpoint` accodring to the chain rule.

**Comment by sfuhrer** [comment]
I agree, and opened a PR: https://github.com/PX4/Firmware/pull/15735

**Comment by sfuhrer** [comment]
Closing, see argumentation in https://github.com/PX4/Firmware/pull/15735.
