### ISSUE TITLE
Power redundancy not met: 0 instead of 1

### ISSUE THREAD

**Issue by neo0605-d** [PX4/Firmware#15725]
Hello. Have installed firmware 1.11.0. Conducted calibration of sensors, radios, motors. Does not allow switching on motors (arm), error: power redundancy not met: instead of 1
![Screenshot_2020-09-12-20-25-56-541_org mavlink qgroundcontrol](https://user-images.githubusercontent.com/71229675/93026015-79fe3f00-f60b-11ea-9eee-aafb9f288452.jpg)

**Comment by dagar** [comment]
Which flight controller and how is it powered?

**Comment by neo0605-d** [comment]
Pixhawk 2.4.8 controller, powered by a power distribution Board.
![M_092_0x180_b5f](https://user-images.githubusercontent.com/71229675/93029868-2ac60780-f627-11ea-935a-593ed5c81c1d.jpg)

**Comment by dagar** [comment]
> Pixhawk 2.4.8 controller, powered by a power distribution Board.
> ![M_092_0x180_b5f](https://user-images.githubusercontent.com/71229675/93029868-2ac60780-f627-11ea-935a-593ed5c81c1d.jpg)

If you can capture a log from boot (SDLOG_MODE) and share it https://logs.px4.io/ I'll take a closer look. Make sure the log includes attempting to arm.

**Comment by neo0605-d** [comment]
Thank you in advance. I'll do it tomorrow. Good time of day.

**Comment by ryanjAA** [comment]
@neo0605-d set COM_POWER_COUNT to 0 from 1 and that warning will go away. This should either be set to 0 as standard or be board specific in the future.

**Comment by dagar** [comment]
@ryanjAA it's counting the number of bricks, with the default set to 1 (no redundancy). Is it not actually working that way?

**Comment by ryanjAA** [comment]
Interesting. No, it’s not working that way on v3 and v5 (pix1 and p4). Had to set to 0 to work although pix 4 testing will need to double check but I believe so. Definitely on pix 1.

**Comment by ryanjAA** [comment]
Just checked (looked at logs). Works on pix 4. Not on pix 1.

**Comment by neo0605-d** [comment]
Hello. Thank you very much for your help!!!!!!! Everything worked, I will test it on the street

**Comment by YANG-DEMIN** [comment]
Hello, I meet the same problem. A few days ago,  i changed the battery capacity and calibrated the power module. When i change back the battery, the problem arise. After several times calibration, it did not work. 
Finally, **I flashed the Firmware, it worked again**.

**Comment by ryanjAA** [comment]
You have this working with 1.11 and com_power_count set to 1? Which Pixhawk are you using? It works on Pixhawk 4 but not 1.

**Comment by ssnake** [comment]
Firmware 1.11 and pixhawk v2 setting COM_POWER_COUNT to 0 helped. Thanks

**Comment by paulr4** [comment]
I'm having this problem too, on a Pixhawk 2.4.8. The COM_POWER_COUNT = 0 suggestion worked for me, but shouldn't this ticket stay open until the fix suggested by @neo0605-d is implemented?

> @neo0605-d set COM_POWER_COUNT to 0 from 1 and that warning will go away. It’s just checking that you have a redundant power source. This should either be set to 0 as standard or be board specific in the future.

**Comment by Hr-Senerity** [comment]
I have also encountered this issue. Setting it to 0 is helpful, but is there any other risk or has the issue been fixed with 1.15
Firmware: fmu-v3 v1.15.0 stable
Flight Control: Pixhawk 2.4.8
