### ISSUE TITLE
Make motor_test motor index 1 based

### ISSUE THREAD

**Issue by justas-** [PX4/Firmware#15721]
For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/).

**Describe problem solved by the proposed feature**
motor_test application in nsh is a great way to verify that motors are connected in a right order and turn in a right direction. *However* -m parameter (motor number) is 0-based. This is not consistent with the Frame Reference and dshot command, both of which use 1-based indexing.

**Describe your preferred solution**
motor_test command's -m parameter should be 1-based.

**Describe possible alternatives**
As this is binary decision, there are no (sane) alternatives to consider.

**Additional context**
N/A

I can make a pull-request for this feature, if the dev team will find it useful.

**Comment by bkueng** [comment]
Yes I was considering doing that as well, a PR is welcome.
