### ISSUE TITLE
Inspect and get rid of usleep calls in USB stream setup

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1573]
This file has usleeps() between stream setups, which doesn't make sense. We should find out why those where needed, and see if the true cause has been addressed and fixed by now.
https://github.com/PX4/Firmware/blob/usbmanualcontrol/ROMFS/px4fmu_common/init.d/rc.usb

**Comment by Zefz** [comment]
@LorenzMeier I think you can close this as it has been resolved in https://github.com/PX4/Firmware/commit/90afddbdc8e04f606963acdb88273be477ddd6e7

**Comment by LorenzMeier** [comment]
Right, thanks!
