### ISSUE TITLE
SENS_BOARD_ROT values is not consistent with Rotation enum

### ISSUE THREAD

**Issue by lukegluke** [PX4/Firmware#15771]
SENS_BOARD_ROT parameter description starting 26
https://github.com/PX4/Firmware/blob/dc507ee54419aa9db5d54e8bd181d6ee3ec8e93b/src/modules/sensors/sensor_params.c#L134-L143

is not consistent with Rotation enum
https://github.com/PX4/Firmware/blob/09af5e0637e626895f92e36e665eb7835c6730b7/src/lib/conversion/rotation.h#L78-L98

**Comment by dagar** [comment]
Thanks @lukegluke, good catch.

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/pull/15784
