### ISSUE TITLE
X Quad: CubeOrange / DShot AUX-4 output not mapped correctly

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#15801]
**Describe the bug**
Using 1.11 release, I have a strange behavior with DShot and CubeOrange on a X-Quad. When armed Motor 4 is spinning at 50%. Other Motors/Outputs work correctly. Using QGC motor-test, Motor 4 is not controllable at all (does not spin). With NSH motor_test, (motor_test test -m 4 -p 20) the motor does not start as well. However using motor_test test **-m 5** -p 20, the motor spins and seems to be controllable. Motors are connected to AUX in DShot mode as described in the documentation with IO = 0 set. Motor 4 is connected to AUX-4. Seems to be a kind of mapping issue between AUX4 and AUX5 on CubeOrange.

**Comment by dagar** [comment]
We need to verify the timers and the dshot motor assignment.

https://github.com/PX4/Firmware/blob/0a607bdc676a62a3839a833897e983e9dc944d29/boards/cubepilot/cubeorange/src/timer_config.cpp#L41-L48

https://github.com/PX4/Firmware/blob/0a607bdc676a62a3839a833897e983e9dc944d29/boards/cubepilot/cubeorange/src/board_config.h#L148

**Comment by dagar** [comment]
Can you comment on anything else? Have you done anything that would verify the mapping of AUX1,2,3? Have you tried PWM output?

**Comment by dagar** [comment]
FYI @mirkix @JacobCrabill

**Comment by dagar** [comment]
Ha, looks like inherited copypasta from the Holybro Durandal, the first STM32H7 board we supported.

**Comment by ecmnet** [comment]
PWM output works fine. No issues here. Think it is related to https://github.com/PX4/Firmware/blob/0a607bdc676a62a3839a833897e983e9dc944d29/boards/cubepilot/cubeorange/src/board_config.h#L148

**Comment by dagar** [comment]
> PWM output works fine. No issues here. Think it is related to

Yes I think so as well, can you give https://github.com/PX4/Firmware/pull/15802 a try?

**Comment by ecmnet** [comment]
I can confirm that the fix works for me. Perfect!

**Comment by dagar** [comment]
Fixed by https://github.com/PX4/Firmware/pull/15802. Thanks for the quick feedback @ecmnet.
