### ISSUE TITLE
Store sensor ID during calibration, fail preflight check if ID changes

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1583]
This is to address #1045. The device ID is already filled correctly, so this one should be fairly quick / easy.

@bansiesta Interested? Anyone else interested? Its nice self-contained.

**Comment by LorenzMeier** [comment]
Initial code hint:
https://github.com/PX4/Firmware/blob/master/src/drivers/device/device.cpp#L100-L104

**Comment by hauptmech** [comment]
I'm looking at this but not sure if I have the systems knowledge yet. If someone else can beat me to it, please do.

**Comment by hauptmech** [comment]
When redundant mags are used one would need a calibration for each sensor.

What is being stored is not a sensor ID but rather sensor bus and type. It is possible for field hardware changes (swap 3DR GPS for instance) to allow the preflight to pass. 

Unfortunately I think few of the sensor have true unique id's. An interesting approach might be to collect signatures of the sensors (essentially an online collection of the calibration data) and warn when the signature goes outside the bounds of the expected calibration.

**Comment by LorenzMeier** [comment]
Thanks for helping out there! All implemented now.
