### ISSUE TITLE
Pixhawk cube + GPS Here modul, not detecting magnetometer

### ISSUE THREAD

**Issue by MartinStokelj** [PX4/Firmware#15835]
**Describe the bug**
Cube does not calibrate external magnetometer on GPS Here module

**To Reproduce**
Connect GPS Here module and start compass calibration

**Expected behavior**
It should detect external magnetometer

**Log Files and Screenshots**
![untitled](https://user-images.githubusercontent.com/30079270/94401703-4a9f1480-016b-11eb-85a6-079d65d625a9.png)
Debug console output:
[putty.txt](https://github.com/PX4/Firmware/files/5290515/putty.txt)

**Drone (please complete the following information):**
VTOL DetlaQuad
QGroundControl can upgrade the firmware on Pixhawk devices, SiK Radios and PX4 Flow Smart Cameras.
Plug in your device via USB to start firmware upgrade.
Found device: PX4 FMU V2
Connected to bootloader:
Version: 5
Board ID: 255
Flash size: 2080768
Downloading firmware...
From: http://px4-travis.s3.amazonaws.com/Firmware/stable/px4fmu-v3_default.px4

**Additional context**
Output without Here module (airspeed detected but not visible on i2cdetect)
ms5525_airspeed #0 on I2C bus 2 (external, equal to '-b 2')
nsh>
nsh> i2cdetect
Scanning I2C bus: 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
nsh>

Output with Here module (airspeed, rgbled detected and I think also magnetometer)
rgbled #0 on I2C bus 1 (external, equal to '-b 1')
ms5525_airspeed #0 on I2C bus 2 (external, equal to '-b 2')
nsh> i2cdetect
Scanning I2C bus: 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- 55 -- -- -- -- -- -- -- -- -- -- **probably rgbled?**
60: -- -- -- -- -- -- -- -- -- 69 -- -- -- -- -- -- **probably icm20948?**
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
nsh>

![Mag0](https://user-images.githubusercontent.com/30079270/94414524-bd64bb80-017c-11eb-8570-f34ba88607ed.png)

@dagar tagging you as you wanted

**Comment by dagar** [comment]
Looks like it's the `icm20948` on I2C which has an ak09916 magnetometer. 

We have a driver for both the icm20948 and ak09916, so I believe the problem in this case is that the icm20948 needs to be configured in i2c passthrough mode so that the ak09916 is directly on available on the bus.

**Comment by MartinStokelj** [comment]
So what can I do?

nsh> ak09916 status
INFO  [SPI_I2C] Not running
nsh> icm20948 status
INFO  [SPI_I2C] Not running
nsh>

**Comment by dagar** [comment]
2 Options
1) extend the existing icm20948 to work on I2C
     - at the moment I'd say we actually don't want this because that extra external IMU on I2C probably isn't usable for flight and we don't currently have a mechanism to treat it differently
2) create a very simple icm20948_i2c that simply places the device in I2C passthrough mode so that the ak09916 is available directly on the I2C bus, then start the standalone ak09916 driver.

**Comment by MartinStokelj** [comment]
According to https://docs.px4.io/master/en/assembly/quick_start_cube.html
The recommended GPS modules are the Here and Here+, both of which incorporate a GPS module, Compass, Safety Switch and LEDs.
But it looks like this do not work anymore without modifications?

I have also DroTek (Ublox GPS + compass) which works fine and is correctly detected with PX4, should I use this one instead of Here module?

**Comment by dagar** [comment]
> I have also DroTek (Ublox GPS + compass) which works fine and is correctly detected with PX4, should I use this one instead of Here module?

Yes, the vast majority of these GPS modules are all the same ublox m8n.

I'll look into fixing the icm20948.

**Comment by MartinStokelj** [comment]
So even DroTek  didn't work. It has found the external magnetometer but the GPS was not working. I have ordered Here2 and now both borks, GPS and external mag on I2C.

**Comment by dagar** [comment]
Thanks for the update, I'll try to have the icm20948 on i2c fully working soon.
