### ISSUE TITLE
Popcorntime/Trakt.tv

### ISSUE THREAD

**Issue by TonyWhi7e** [PX4/Firmware#1586]
When i put my account on that space to get the 'automatically scrobble episodes' thing, it appears the loading icon, and then i get a red cross, saying that is not synced. I made my account on Trakt.tv without using a social net.. I don't know if is problem os an update or something wrong with the plug-in, somebody give me any advice or tip whatever please! and thanks! (:

**Comment by thomasgubler** [comment]
Please post your issue to the correct repository and not some random one on github.
