### ISSUE TITLE
Missing Parameters in 1.11

### ISSUE THREAD

**Issue by ryanjAA** [PX4/Firmware#15872]
There are several parameters that are quasi missing in 1.11 stable.

I say quasi as they are in the firmware but do not always show up in QGC.

com_power_count is listed and present in 1.11 (https://github.com/PX4/Firmware/blob/71db0903a910d35a18f10d74c851446a6f66d61f/src/modules/commander/commander_params.c#L926)  but not in https://dev.px4.io/v1.11/en/advanced/parameter_reference.html

Some occasions (after several hard, not soft reboots) the parameter shows but I can not recreate making it show up routinely or by a specific method yet.

A param set com_power_count X when the parameter is not showing up yields an error message that the parameter is not present on the vehicle.

My short term workaround is not realistic (I've aded the parameter as a specific vehicle parameter so when setting autoconfig to vehicle standards, it populates the necessary parameters but this still disappears after a soft reboot, is does however enable changing it prior). 

Additionally, the com_arm_ekf_XXX parameters do not show up as well.

This is discussed here https://px4.slack.com/archives/C0W2KUFFT/p1601402558029700 but as com_power_count is causing problems for users, it is important that this parameter be exposed, aside from the fact that something is not working correctly.

This has been tried on multiple pixhawk 1 units and computers with the same result. Anecdotally, the presence of the  parameters may be related to soft and hard rebooting of the system.

**Comment by dagar** [comment]
It's likely the timing of initial param sync with commander not checking these things immediately. Let me take a look.
