### ISSUE TITLE
PX4 problems

### ISSUE THREAD

**Issue by AppalachianWarrior** [PX4/Firmware#15895]
HI all! I am new to using the PX4 on my drone. I was flying it the other day and got a "Critical Navgation Error" message and it then crashed into the ground. Can someone please tell me where / what the issue might be? Where would i start looking for the issue?
I did read the flight log material on the PX4 website, but i feel it was not as clear.

Here is the link to the logs:
https://review.px4.io/plot_app?log=4c1799e3-5484-4b4c-a737-bf88d6tef4c#Nav-Local-Position-X

Thank you

**Comment by dagar** [comment]
That log only has a few seconds of flight and doesn't contain "Critical Navgation Error". It's also not clear which version of PX4 this is as its a custom commit, but based on the perf counters it's not current.
