### ISSUE TITLE
mRo v2.1 and Taoglas GPS

### ISSUE THREAD

**Issue by netkimjh** [PX4/Firmware#15907]
Hi,

I am struggling for integrating Taoglas GPS with mRo v2.1.
I confirmed the GPS is powered and working well with Ardupilot. 
But the problem is Taoglas GPS is not powered with any PX4 version.
The GPS is connected GPS/I2C port (UART 4, Serial 3)

FYI,
[mRo v2.1](https://docs.px4.io/master/en/flight_controller/mro_x2.1.html)
[Taoglas GPS](https://store.mrobotics.io/ProductDetails.asp?ProductCode=mro-gps003-mr)

Do you have any solution for this matter?

**Comment by LorenzMeier** [comment]
There is no reason why it should not work.

@bkueng I have ordered the unit.

**Comment by dagar** [comment]
@netkimjh I've used just about every version of every GPS from mRo with PX4 and I'm not aware of any current problems. You can see an old subset here https://github.com/PX4/Firmware/pull/15120.

Which version of PX4 exactly? Can you check the back of you mRo GPS to see if it's an m8n or m9n?

**Comment by netkimjh** [comment]
@LorenzMeier and @dagar ,

I am using mRo v2.1 FCU. #15120 seems like not using mRo V2.1

1. Flashed and tested PX4 version from 1.9.0 to 1.11.1. Tried mro_x21_default.px4, auav_x21_default.px4, and px4_fmu-v2_default.px4.
(I downgraded the firmware from 1.11 due to crash of BAT parameter with QGC.)
2. NEO-M8N-0-10

I cannot see any light on GPS with PX4, so I checked the voltage of the port and confirmed that it outputs 5v.

**Comment by bkueng** [comment]
@netkimjh what's the output of `gps status`?

**Comment by dagar** [comment]
> I was not able to see any light on GPS with PX4, so I checked the voltage of the port and confirmed that it outputs 5v.

I'm not wondering if you're referring to the RGB LED on top of the unit rather than the GPS itself. It looks like the ncp5623c has another possible I2C address. Can you try https://github.com/PX4/Firmware/pull/15918?

**Comment by netkimjh** [comment]
@bkueng @dagar ,
I am sorry that I cannot check it this week.
I will check and let you know next week.
Thanks.

**Comment by bkueng** [comment]
I received the unit, it's indeed just the LED startup that's missing: `rgbled_ncp5623c start -X -q -a 0x38`

**Comment by netkimjh** [comment]
@bkueng Hey, I meant there is not only no RGB LED, also not working gps. In QGC, I cannot see any GPS data with it. What should I try?

@dagar is there any update?

**Comment by bkueng** [comment]
> @bkueng Hey, I meant there is not only no RGB LED, also not working gps. In QGC, I cannot see any GPS data with it. What should I try?

As I wrote above, please provide the output of `gps status`. See https://docs.qgroundcontrol.com/master/en/analyze_view/mavlink_console.html for how to access the shell.

**Comment by netkimjh** [comment]
@bkueng 
I understand, and I received the following result.

![gps_status_v1 9 0](https://user-images.githubusercontent.com/13003647/96764971-f7a23100-13a7-11eb-8dc8-87065df2acd6.png)

So, it was working, and there was no RGB LED.. and I have "No GPS Lock for Vehicle"..

Thank you for clarifying this issue.

**Comment by bkueng** [comment]
Correct, this looks all good.

**Comment by netkimjh** [comment]
@bkueng 
OK.
So far, I tried Firmware version 1.9.0, but it seems like not support mRo x2.1. So now I am using mro_x21_default v1.11.1.
However, it seems like esc calibration has an issue, correct?
I tried to use the esc calbiration in QGC, but there is an error that "Timeout waiting for battery".
 
Could you confirm it for me?

Thank you.
