### ISSUE TITLE
Setting max roll and pitch for multirotor

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#15968]
Hi

Is it possible that we set a limit for roll and pitch angle fot multirotor and vtols ? ( during takeoff , landing and mission )

 In some condition roll and pitch setpoints have large values.

**Comment by dagar** [comment]
> Is it possible that we set a limit for roll and pitch angle fot multirotor and vtols ? ( during takeoff , landing and mission )
> 
> In some condition roll and pitch setpoints have large values.

Take a look at MPC_TILTMAX_LND, MPC_TILTMAX_AIR, MPC_MAN_TILT_MAX.

 - https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_MAN_TILT_MAX
 - https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_TILTMAX_AIR
 - https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_TILTMAX_LND
