### ISSUE TITLE
FMUv5: DMA allocation error on notes?

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#15988]
I am not sure but it possible that there is some error on the DMA allocation on board FMUv5:

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L181

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L208

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L216

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L225

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L231

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L233

https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/nsh/defconfig#L236

but on the DMA table notes, there written different channels:
https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/include/board_dma_map.h#L53
https://github.com/PX4/Firmware/blob/224be8ba2473d334466316a9dee1bdaf332ca90d/boards/px4/fmu-v5/nuttx-config/include/board_dma_map.h#L77

meaning USART6_TX_2 and USART8_TX_2 are written on the table, but not on the defconfig.
is that on Intentionally? some kind of place-holder?

**Comment by dagar** [comment]
The table (documentation) is out of date.

**Comment by BazookaJoe1900** [comment]
I will update it, there are some more data that can be filled

**Comment by BazookaJoe1900** [comment]
moved to PR: fmu-v5: fix DMAmap #15989
