### ISSUE TITLE
BAT_V_DIV not affects voltage on Pixhawk4 w/ px4 1.11.1

### ISSUE THREAD

**Issue by bys1123** [PX4/Firmware#15986]
**Describe the bug**
Set BAT_V_DIV to any value, battery voltage and percentage won't change.

**Log Files and Screenshots**
![image](https://user-images.githubusercontent.com/4748411/96331545-b3095380-1090-11eb-8ce1-bee75d84ed9f.png)

**Comment by moreba1** [comment]
use BAT1_V_DIV parameter.

**Comment by bys1123** [comment]
Thanks, I'll try it later.
