### ISSUE TITLE
PositionControl _thr_sp saturation fail

### ISSUE THREAD

**Issue by NicolasM0** [PX4/Firmware#16029]
Reproducible in v1.10 but not on master (should not be on v1.11 but not tested)

We crashed a drone because of this: in really high winds, the vertical thrust saturate and it horizontal thrust saturation disappeared so the drone began to tilt to compensate the wind and start going down very quickly (and crashed). 

In PositionControl.cpp/_velocityController function (on v1.10 branch), when vertical thrust is superior to MPC_THR_MAX, it is saturated to MPC_THR_MAX. But horizontal thrust max saturation become NAN, resulting in no horizontal saturation.
I can reproduce `_param_mpc_thr_max.get() * _param_mpc_thr_max.get() - _thr_sp(2) * _thr_sp(2)` beginning slightly < 0
So as the square root of this is used ...

On master and 1.11, vertical thrust is also saturated to MPC_THR_MAX and then the calculation is split  as : 
```
const float thrust_max_squared = _lim_thr_max * _lim_thr_max;
const float thrust_z_squared = _thr_sp(2) * _thr_sp(2);
float thrust_max_xy = sqrtf(thrust_max_squared - thrust_z_squared);
```
It seems to be enough to fix the bug but do you think adding a check on the sign before applying sqrtf can be useful.

If yes, I can rebase my changes on master and do a PR

**Comment by dagar** [comment]
I would suggest opening the PR so we can discuss it there. I'd also rather err on the side of caution (carrying checks that might not strictly be necessary).
