### ISSUE TITLE
missing log files

### ISSUE THREAD

**Issue by AIdev014** [PX4/Firmware#16049]
**Describe the bug**
I erased all the log files of my previous flights and after that I made many flights but I am not able to see the new log files for those flights, even after refreshing.

Even on installing new QG I cannot find logs

![Screenshot (31)](https://user-images.githubusercontent.com/59429656/97137065-eaf05500-177a-11eb-9870-9e501347eaf7.png)

**Comment by bresch** [comment]
@AIdev014 If they exist, you should be able to find them directly on the SD card. If there is nothing, try another SD card.

**Comment by AIdev014** [comment]
@bresch I can see folder but it is empty

**Comment by AIdev014** [comment]
well I formatted and again loaded px4 firmware and then I can see my log files
