### ISSUE TITLE
Adjust handling of L1 radius

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1609]
Right now the navigation logic is not consistent. Need to adjust L1 radius / switch point. This is what we initially had and what is required to guarantee reachability.

**Comment by thomasgubler** [comment]
We still have the functions to calculate this value min(wp_radius, l1_distance) in the l1 controller. It's just a matter of feeding the navigation_capabilities topic into the navigator mission_block.

**Comment by thomasgubler** [comment]
The value is calculated and published here: https://github.com/PX4/Firmware/blob/master/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp#L1474

I suggest to publish the l1_distance as turn distance and then calculate min(wp_radius, turn_distance) in the navigator where the wp_radius is anyway available.

**Comment by LorenzMeier** [comment]
@thomasgubler Thanks!

**Comment by LorenzMeier** [comment]
Implemented and fixed, closing.
