### ISSUE TITLE
Servo gimbal controller

### ISSUE THREAD

**Issue by anton-matosov** [PX4/Firmware#1610]
Hi everyone,

I am starting developing servo gimbal controller.
I plan to adopt code from the AMP project:
https://github.com/diydrones/ardupilot/tree/master/libraries/AP_Mount
or at least use it as a reference.

You are welcome to post any objections or proposals into this ticket.

**Comment by LorenzMeier** [comment]
Sounds great! We currently can't accept GPL code into the codebase, as its incompatible with BSD. So you would need to write it yourself.

Note that I wrote a servo gimbal controller a year ago. Give me a day to dig it out and put it onto a branch.

**Comment by anton-matosov** [comment]
Ok. I missed the incompatible licenses. Thanks for pointing me on that.

I will wait for your code of gimbal controller to start with.

**Comment by anton-matosov** [comment]
Hi,
Did you get a chance to find the code of your gimbal controller?

**Comment by anton-matosov** [comment]
@LorenzMeier do you have any updates?

**Comment by LorenzMeier** [comment]
Yep, sorry about that. Will do this tomorrow morning as soon as possible.

**Comment by anton-matosov** [comment]
Ok, thanks.

**Comment by anton-matosov** [comment]
@LorenzMeier do you have any updates? =)

**Comment by LorenzMeier** [comment]
Sorry about the latency on this!
Here it is:
https://github.com/PX4/Firmware/pull/1643

Many months have passed since I last used it, but it did work fine back then.

**Comment by anton-matosov** [comment]
Thanks. Really good starting point for me =)

**Comment by LorenzMeier** [comment]
@anton-matosov What's your current status on this? Did you continue with it?

**Comment by anton-matosov** [comment]
Hi, not really. I have no spare time for this project =(

**Comment by LorenzMeier** [comment]
We have this in.
