### ISSUE TITLE
Increase coverage of hardware tests

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1648]
@dagar The board now executes the px4fmu-v2_test binary on each PR / commit. It would be great to extend the coverage by adding more tests to ROMFS/px4fmu-v2_test/../rcS. A string of "TESTS FAILED" will make the check logic fail the CI test.

![2015-01-12 12 59 07 pm](https://cloud.githubusercontent.com/assets/1208119/5702485/348071e4-9a5b-11e4-9c49-6bfd88cbe828.png)

**Comment by LorenzMeier** [comment]
@dagar I did a bunch in the recent tests. Interested in DroidPlanner / Android GCS support?

**Comment by dagar** [comment]
@LorenzMeier I'm very interested in Android GCS, but I'm not sure where PX4 fits in with Tower (aka droidplanner 3) and 3dr services. Is QGC on Android the long term plan?

I'm going to try and tackle PR #1492 this weekend (and verify on my new hex).
