### ISSUE TITLE
Automate static verification

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/Firmware#1666]
PX4 Firmware Coverity Scan page: https://scan.coverity.com/projects/3966

Since PX4 builds are already automated with Travis CI, static verification can be automated as well: https://scan.coverity.com/projects/3966/builds/new?tab=travis_ci

**Comment by LorenzMeier** [comment]
@bkueng

**Comment by dagar** [comment]
Mostly implemented. Push to the coverity branch and it will run automatically.
