### ISSUE TITLE
Fix issues discovered by Coverity

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/Firmware#1675]
See https://scan.coverity.com/projects/3966 - the latest analysis has been run on a combined build Firmware+NuttX; some issues look quite suspicious.

This blocks https://github.com/PX4/Firmware/pull/1660, because some of the discovered issues can be the cause of the crashes described there.

This wiki page describes how to submit a build to Coverity: https://pixhawk.org/dev/configuring_coverity_scan_cross_build

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by LorenzMeier** [comment]
@bkueng
