### ISSUE TITLE
S3 Links not operational

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1684]
Hi Daniel,

These links here seem to have "Firmware" twice in the URL, leading to broken links:
http://px4-travis.s3.amazonaws.com/Firmware/master/index.html

**Comment by dagar** [comment]
directory/index.html (javascript) in CI-Tools handles creating the s3 directory index.
Fixed here https://github.com/PX4/CI-Tools/commit/806e975ab80dba5da5fba4ae90556e7b6aa0777b

PX4/Firmware should be fixed once a master, beta, or stable travis build runs.

**Comment by dagar** [comment]
Working: http://px4-travis.s3.amazonaws.com/Firmware/master/index.html

**Comment by LorenzMeier** [comment]
Awesome, closing!
