### ISSUE TITLE
S3 storage should print link to uploaded files

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1702]
Although it seems to upload, its kind of hard to guess where the files went based on this output: https://travis-ci.org/PX4/Firmware/builds/48318362#L7279

It would be nice to echo the link to the directory so testers can directly download the build.

**Comment by dagar** [comment]
The build you linked to is a pull request, which isn't uploaded to s3. Only non PR builds of master/beta/stable are uploaded and then s3cmd prints the URL, but travis folds the output. If we move after_script: to the end of the script: section it will echo everything without folding.
https://travis-ci.org/PX4/Firmware/builds/48338203#L7273

Did you want all builds to upload?
