### ISSUE TITLE
nuttx-bringup: multicopter: motors won't spin

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#1706]
@davids5 This needs more investigation. I flashed the nuttx-bringup branch onto a pixhawk on a multicopter. I can arm but the motors won't spin if I throttle up. It seems that the controller is running correctly and publishing meaningful data to the actuator controls uorb topic.

Is this a known issue or do you wan't me to investigate further? (E.g. look at pwm output, mixer, ...)

**Comment by Zefz** [comment]
Tried having your RC *off* when powering your multicopter? Only turn on the RC *after* you hear the confirmation sound of the ESC power-up.

**Comment by davids5** [comment]
@thomasgubler This is the first report of it. Anything you can do to isolate it would be very much appreciated.

**Comment by sjwilks** [comment]
@Zefz that's the same symptom I had in #1649. Does a sleep after starting commander help?

**Comment by davids5** [comment]
@thomasgubler I just pushed a fix that deals with the communications with the pio. I can imagine that this issue you're seeing might have been related. Would you please retest with the latest nuttn_bringup  9dcd7ef35e0beb8f30f3901759210f14a64287ff

**Comment by thomasgubler** [comment]
@davids5 unfortunately that didn't help. I will investigate this a bit more...

**Comment by thomasgubler** [comment]
The issue is that the mixer is not loaded correctly because some variables ate not expanded in the rc.interface script. Fixed in #1708
