### ISSUE TITLE
PWM min limit 1300

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#1732]
I recently tried to set the minimum PWM value to 1500 but it always got "stuck" at 1300. There's a max min limit defined here: https://github.com/PX4/Firmware/blob/master/src/drivers/drv_pwm_output.h#L80

Why is this limit necessary?

The reason I tried to set min to 1500 is the servo for a parachute release. It needs 2 states: "normal" and failsafe. For the normal position I set "disarmed" and "
min" PWM values. I know I could also adjust the servo in this case, but I'm wondering about the max min limit anyway..

**Comment by bansiesta** [comment]
This max min limit was supposed to prevent users from entering too high minimum values, so to ensure "safe" values. I see that for your use case this doesn't really make sense. I guess you could change it to 1500.

**Comment by AndreasAntener** [comment]
Thanks, I feel it's not necessary at all, same for the "min. max. limit". What's "safe"? ;)
It should only check if the values make sense regarding the other values (e.g. min limit lower than max limit). Maybe it also does that already, didn't check.

**Comment by bansiesta** [comment]
Yes, it's not "safe" anyway :)

**Comment by LorenzMeier** [comment]
@AndreasAntener PR welcome.

**Comment by LorenzMeier** [comment]
I changed this to 1600 for max low and 1400 for min high so this should be resolved now.
