### ISSUE TITLE
modification of EST_BUF_SIZE at position_estimator_inav module

### ISSUE THREAD

**Issue by stmoon** [PX4/Firmware#1738]
Hi,,

While analyzing the position_estimator_inav module, I found the EST_BUF_SIZE is not correct.
The buffer was created for estimation of position and velocity by using GPS, flow, .... 

The GPS and flow timeout is 0.5s. So... The buffer should store the estimated data at least during 0.5s.
However, the EST_BUF_SIZE is stored  only during 0.25s.
so How about change the EST_BUF_SIZE  500000 / PUB_INTERVAL  ? 

Thanks in advance 

Best Regards,
Moon 

----------------------------------------------------------------------------------------------------------------------------------------
https://github.com/PX4/Firmware/blob/master/src/modules/position_estimator_inav/position_estimator_inav_main.c#L77
#define PUB_INTERVAL 10000	// limit publish rate to 100 Hz
#define EST_BUF_SIZE 250000 / PUB_INTERVAL		// buffer size is 0.5s

**Comment by LorenzMeier** [comment]
Do you have further feedback / comments on this?
