### ISSUE TITLE
multiplatform/ros sitl: add mavros interface

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#1745]

**Comment by mhkabir** [comment]
@thomasgubler  Would adding mavros as a whole actually benefit us? Perhaps it would be better if we  adapted a inteface from the mavros communications core ("libMavConn")
https://github.com/mavlink/mavros/tree/master/libmavconn

**Comment by thomasgubler** [comment]
The idea is to have a drop in replacement so that the sitl really acts like
the real system. I have to look at libmavconn though.

**Comment by thomasgubler** [comment]
ok it probably makes sense to use libmavconn directly on the sitl side. The plan is something like this:
```
any custom ros app <--> mavros <--> |UDP| <--> [new node with libmavconn] <--> controller
```

The lefthand side is the part which goes on the companion computer on the real system

**Comment by thomasgubler** [comment]
I added a (skeleton) mavlink node here: https://github.com/PX4/Firmware/tree/ros_mavlink
