### ISSUE TITLE
MC attitude control: gains falsely initialized?

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#1759]
Connected battery and noticed that elvons did only respond slightly to my TX pitch commands (used the Caipirinha VTOL). Logs confirmed that ATTC.Pitch was at most 8% of the max value although pitch rate error was huge. Controller gains were untouched.
Unplugged and replugged the battery and all of a sudden everything was ok again.
Log is here: http://dash.oznet.ch/view/ktMUxGX8espdDHWvma49hD
Please download and analyse with FlightPlot, LOG Muncher won't show!

P.S. Vtol control module used mc_att_controller for attitude control

**Comment by LorenzMeier** [comment]
@tumbili It might very well be fixed in 0fd11b7. Let me know if rebasing on master fixes it for you.

**Comment by tumbili** [comment]
I will have to test it over the next days, the problem only occured rarely.

**Comment by kd0aij** [comment]
What was the reason for closing?

**Comment by tumbili** [comment]
@kd0aij After all this time I have never witnessed this problem again.
