### ISSUE TITLE
Logmuncher does not stomach VTOL logs any more

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1785]
http://dash.oznet.ch/view/WigWANKzeUfnZz3D4BncD3

Unclear yet why / what, need time to look into it.

**Comment by SimonWilks** [comment]
I'll take a look into this.

**Comment by SimonWilks** [comment]
It looks like there is a log breakage introduced in #1734 

Something looks like it might be fishy here: https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2_messages.h#L471-L472

@tumbili  was the intention that the second line replace the first?

**Comment by tumbili** [comment]
Yes, I guess that was the intention :-/

**Comment by tumbili** [comment]
Would you like me to do a PR or do you want to fix it?

**Comment by SimonWilks** [comment]
Can you? I'm away from my laptop now.

Thanks.

**Comment by tumbili** [comment]
Sure, thanks for your help!

**Comment by SimonWilks** [comment]
Fixed via #1791

**Comment by LorenzMeier** [comment]
Thanks! Closing.
