### ISSUE TITLE
*.mix file doesnt work with more than 8 output-chanels

### ISSUE THREAD

**Issue by severinleuenberger** [PX4/Firmware#1805]
When i mixed more than 8 output-chanels with the *.mix-file, the output doesnt work anymore. 
On SBUS i do not get any signal on any servo by using 9 or more output-mix-chanels. 
I think it doesnt work with pwm either, but i am not sure on pwm. 

Best, Severin

**Comment by severinleuenberger** [comment]
to describe the goal: it would be great to have at least 12 or better 16 chanels on the mix-file.

**Comment by severinleuenberger** [comment]
hopefully, i can test this week...

**Comment by LorenzMeier** [comment]
This has been implemented and tested, closing.
