### ISSUE TITLE
sercon fails on start

### ISSUE THREAD

**Issue by mazahner** [PX4/Firmware#1833]
Using current px4/Firmware stable with corresponding Nuttx submodule didn't let my code start. 
I found that commenting out "sercon" in Firmware/ROMFS/px4fmu_common/init.d/rcS line 11, fixed it and everything is happy as before. 

best, Markus

**Comment by LorenzMeier** [comment]
I don't think this is real, closing. There are no other reports - maybe you're misinterpreting the "USB not available state" as an error?
