### ISSUE TITLE
Flight modes

### ISSUE THREAD

**Issue by Vavooon** [PX4/Firmware#1835]
I'm wondering why i should use 4 channels for flight mode selection. 
Is such way better than APM 6pos switch?

**Comment by LorenzMeier** [comment]
You don't have to use several channels, although many people find it easier than setting up mixing. Here is an example how to use a single channel:
http://www.pixhawk.org/peripherals/radio-control/opentx/single_channel_mode_switch

The graphic configurator will support this soon as well.

Please use the mailing list for questions:
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.interface#L120

**Comment by Vavooon** [comment]
Thanks a lot!
Sorry for the incorrect place for the question.
