### ISSUE TITLE
Offboard velocity setpoints broken on master

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#1856]
We have reports that https://github.com/PX4/Firmware/pull/1786 introduced a regression that disables offboard velocity setpoints.

More tests are needed.

**Comment by blackcoder** [comment]
@thomasgubler did you find a solution for this bug ?

**Comment by thomasgubler** [comment]
No, I didn't see it directly in the code and I currently don't have the setup ant time to reproduce it.

**Comment by blackcoder** [comment]
No worries, I had a quick look at the code, nothing is obvious there, the logic is correct, it must be some hard to find bug.

**Comment by xuliren** [comment]
Hi, I'm testing the offboard velocity function under an indoor-vicon testbed. Currently the uav can do the offboard position control very well, but the velocity control are not working. After reading the source code, I found that https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L715 is converting the velocity control into an position control, I think it might not that proper to to so.

**Comment by supermice** [comment]
@xuliren  What's the status now? Does the master firmware fixed the velocity control problem?

**Comment by aerialhedgehog** [comment]
I tried flying this yesterday and did not get any response from my hex
while sending velocity commands.

On Sat, Jun 27, 2015 at 10:27 PM, super_mice <notifications@github.com>
wrote:

> @xuliren <https://github.com/xuliren> What's the status now? Does the
> master firmware fixed the velocity control problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PX4/Firmware/issues/1856#issuecomment-116195767>.
>



-- 
 - Trent Lukaczyk
   Stanford University Engineering
   Cornell University Engineering 2010
   twl26@stanford.edu

**Comment by aerialhedgehog** [comment]
i was flying master, using the c_uart_interface example
https://github.com/mavlink/c_uart_interface_example

On Wed, Jul 1, 2015 at 1:27 PM, Trent Lukaczyk <twl26@stanford.edu> wrote:

> I tried flying this yesterday and did not get any response from my hex
> while sending velocity commands.
>
> On Sat, Jun 27, 2015 at 10:27 PM, super_mice <notifications@github.com>
> wrote:
>
>> @xuliren <https://github.com/xuliren> What's the status now? Does the
>> master firmware fixed the velocity control problem?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PX4/Firmware/issues/1856#issuecomment-116195767>.
>>
>
>
>
> --
>  - Trent Lukaczyk
>    Stanford University Engineering
>    Cornell University Engineering 2010
>    twl26@stanford.edu
>



-- 
 - Trent Lukaczyk
   Stanford University Engineering
   Cornell University Engineering 2010
   twl26@stanford.edu

**Comment by AndreasAntener** [comment]
I think I found the missing piece: #2527
