### ISSUE TITLE
Better status feedback via MAVLink

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1861]
* Populate status flags in VEHICLE_STATUS
  * Send AUTOPILOT_VERSION on boot
  * Send AUTOPILOT_VERSION on MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES command.

**Comment by DonLakeFlyer** [comment]
Just tracking this one since I can add autopilot version to vehicle summary in QGC when it shows up.

**Comment by tumbili** [comment]
@LorenzMeier From what I see the status flag population is already done, it's just that not every sensor publishes the "subsystem_info" topic yet.

**Comment by LorenzMeier** [comment]
Yeah, that subsystem_info topic might not be the ultimate solution. I have to think about that one.

**Comment by TSC21** [comment]
mavros is waiting for this message support also: https://github.com/mavlink/mavros/issues/246

**Comment by LorenzMeier** [comment]
I'm closing this for now since the current reporting is already decent. We can still improve long term.
