### ISSUE TITLE
Check fly-forward setting of EKF for multicopters.

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1871]
@priseborough What do we need to obey when using the mag offset estimation on multicopters in the test harness?

**Comment by LorenzMeier** [comment]
@Zefz this will be relevant for you: You should set ekf->inhibitMagStates to *true* if these conditions are met:

  * The airframe type is a multicopter
  * ekf->accNavMag is below some threshold - because only if the copter is accelerating the mag offset is observable.

It would be great if you would be interested to look into this, as its relevant for your use case.

**Comment by LorenzMeier** [comment]
@Zefz have you noticed this issue?

**Comment by Zefz** [comment]
I can take a look into this. Seems like a simple enough fix.
