### ISSUE TITLE
d-term in  ECL_RollController::control_bodyrate

### ISSUE THREAD

**Issue by friekopter** [PX4/Firmware#1880]
I just wonder why there is only a proportional and integral term in the ECL_RollController::control_bodyrate but there is no differential part. Is there any reason not adding that?

The reason for looking at this is that I still have sometimes low frequency roll oscillations with my Q Cam-Flyer, even after trying many different parameter combinations.
So my hope is to fix this issue with adding d-term damping in the controller. I already added the code but need good weather for a testflight.

**Comment by LorenzMeier** [comment]
The body rate is already the D term / dimension. Low frequency oscillations would be a problem of your P controller or a too low P gain on the body rate controller.

We won't be adding a D term here. We can't measure angular acceleration, and differentiating the angular velocity is really not great from a noise perspective.

I'm closing this one, but I'd be happy to further assist with your tuning via email.
