### ISSUE TITLE
Enable auto-mkfatfs on SD card mount fail

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1897]
If the SD card fails to mount the system boots in a bad state. We should try to recover as far as possible.

**Comment by LorenzMeier** [comment]
This is implemented, but booting without SD card fails. We should be booting fine, but just not log.

**Comment by LorenzMeier** [comment]
#2019 addresses the rest of it.

**Comment by tumbili** [comment]
@LorenzMeier Can we close this?
