### ISSUE TITLE
Parameters autosave

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#1903]
The "Tower" Android App appears to have no "param save" function, just "upload" and "download" which equate to "set" and "get", respectively.
It seems desirable to add an autosave capability which would write the current parameter set to ROM after a delay of perhaps 200msec, to limit the frequency of ROM updates.

**Comment by LorenzMeier** [comment]
I have implemented this, and it is in master. Thanks for pushing this! Closing.
