### ISSUE TITLE
Pixhawk4

### ISSUE THREAD

**Issue by BigMoneyLloyd** [PX4/Firmware#1909]
Greetings Tron Friends. My Name is Lloyd Brown. I am a student at ECPI University, Virginia Beach campus. I am doing my first Hexcopter build with the Turnigy 9XR  Radio and the orange JRX 2.4GHZ dsm2/dsmx transmitter module.  The University purchased The Pixhawk PX4 flight controller, and it will only operate 4 of the 6 motors. I was told By a senior student that the flight controller needed a certificate of authenticity (COA ) in order to be able to properly download the hexcopter firmware for the PX4 Pixhawk Flightcontroller. please help! My home number is (757) 340-0017

**Comment by LorenzMeier** [comment]
Please ask questions on the mailing list. This here is for actual issues.
