### ISSUE TITLE
Script/Code Duplication in ROS/SITL install scripts

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#1910]
@AndreasAntener We need to find a way to have only one script for dependencies etc.

https://github.com/PX4/containers/tree/master/docker/ros-indigo/px4-ros-full

vs.

https://github.com/PX4/Firmware/tree/master/Tools/ros

**Comment by AndreasAntener** [comment]
Yeah that's a pity..
Maybe we can sync the scripts and I can reference them from the Docker installation. But I have to check how, because Docker only allows using stuff from sub directories (where the Dockerfile is located).

**Comment by AndreasAntener** [comment]
@thomasgubler I'll try move the install scripts into PX4/containers and reference it from there. So I can use them for the Docker installation. At the same time I'll try to switch to latest MAVROS because of #1979
