### ISSUE TITLE
Bug in SITL manual_input node

### ISSUE THREAD

**Issue by devbharat** [PX4/Firmware#1924]
Wrong axes index parameter is assigned to the manual_input.x on Line 54 https://github.com/PX4/Firmware/blob/master/src/platforms/ros/nodes/manual_input/manual_input.cpp

```_n.param("map_x", _param_axes_map[0], 4);```

it should be 

```_n.param("map_x", _param_axes_map[0], 1);```

the struct ```sensor_msgs::JoyConstPtr &msg``` has no ```msg->axes[4]```, it's index goes from 0 to 3
That is why it isn't taking x axis inputs from stick in SITL simulation.

**Comment by AndreasAntener** [comment]
Discussed with @devbharat:
Without a joystick, arrays in Joy message might not have as many values as the Xbox mapping expects. Mapping can be changed with parameters: https://pixhawk.org/dev/ros/sitl#joystick_configuration
