### ISSUE TITLE
Mixer: Re-evaluate limit enforcement

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1925]
Reported by @kd0aij. At thrust close to 1 the actuator outputs seem to dip to min.

![out0_0-3_overflow](https://cloud.githubusercontent.com/assets/1208119/6672365/59c689d8-cc0c-11e4-90e5-888d928eb37b.png)

**Comment by kd0aij** [comment]
Unable to reproduce the problem in manual attitude control mode:
![full_throttle](https://cloud.githubusercontent.com/assets/2300221/6720713/598a18ce-cd8b-11e4-9f49-ae87d494a1d1.png)
commit 59ebc99,  branch limitAutoRPrates

**Comment by LorenzMeier** [comment]
I'm not surprised that you can't, because for the saturation to occur you would need to set rates instantaneously, which is is almost impossible by just twiddling an RC stick.

**Comment by kd0aij** [comment]
Just rechecked the logs: same mode in both, manual attitude control

**Comment by tumbili** [comment]
@kd0aij Can you share a link to the log.

**Comment by kd0aij** [comment]
first log: https://copy.com/dZ6jHciEUuhOULZo
second log: https://copy.com/ekAYIlWe29NdGPpN

**Comment by kd0aij** [comment]
BTW, I've accidentally caused integer overflows in MatrixPilot, which is mostly implemented on DSP hardware; results are usually quite exciting for a very short time :)

**Comment by LorenzMeier** [comment]
@tumbili The proposed approach is along the lines of this algorithm. You need to implement it partially at least in the controller to lock integrals from building up.

CASE A: Slew rate limiting: Last attitude setpoint and current attitude setpoint differ by more than e.g. 30 degrees OR the requested angular rate is relatively high AND the mixer reports hitting a limit:
  * Limit demanded angular rate to a fixed threshold in controller (e.g. 200 dps)
  * Limit demanded attitude to an attitude max. 15 deg or so from current attitude
  * Lock all integral gains

This forces the system into a slew rate limiting mode and ensures that higher-level controllers do not build up integrals.

CASE B: Flip-prevention: Current attitude and setpoint differ by e.g. more than 20 degrees (NOTE: The limit in degrees here has to be higher than in slew rate limit mode so that slew rate limiting always triggers first). This mode might loose or gain altitude.

  * If hitting high limit: Reduce throttle to 60-80% of the demanded value to allow higher spread
  * If hitting low limit: Increase throttle to 120-160% of the current value

This should allow the system to recover if it was close to flipping.

**Comment by LorenzMeier** [comment]
Fixed in master.
