### ISSUE TITLE
Matrix.hpp 

### ISSUE THREAD

**Issue by devbharat** [PX4/Firmware#1963]
In file lib/mathlib/math/Matrix.hpp
```
#if defined(__PX4_ROS)
	/**
	 * set data from boost::array
	 */
	void set(const boost::array<float, 9ul> d) {
	set(static_cast<const float*>(d.data()));
	}
#endif
```

Shouldn't this be in Matrix<3,3> class rather than general Matrix<M,N> ?

**Comment by thomasgubler** [comment]
yep this seems a bit off, maybe we can also generalize set(...)

**Comment by devbharat** [comment]
Am using this for now.
