### ISSUE TITLE
windows toolchain installer nsis error

### ISSUE THREAD

**Issue by joeyfezster** [PX4/Firmware#1967]
Hey, i've tried downloading the windows toolchain installer from 3 different computers, and still get the same error.

is there a different source i could get it from?

**Comment by joeyfezster** [comment]
FIX: control panel -> region -> administrative -> change system locale -> choose acording to local language -> restart pc

**Comment by LorenzMeier** [comment]
Thanks for the solution - but you haven't shared the error in the first place?

**Comment by joeyfezster** [comment]
i just opened the installer, and it gave the nsis error in a message box.
no details.

the fix is based on previous encounters with the same error

**Comment by alielectric** [comment]
your location that the installer is located has more than a defined characters, copy it some where else than run the setup
