### ISSUE TITLE
SITL commander app bug ?

### ISSUE THREAD

**Issue by devbharat** [PX4/Firmware#1972]
I observed that the vehicle_status.arming_state always remains 0 (in fact, has impulse like response to arming/disarming) despite the commander setting it to armed or disarmed. The arm flag in vehicle_control_mode switches correctly. 

I changed the msg_vehicle_status from a local variable to a private variable of the class (like it is for vehicle control mode) and now vehicle_status.arming_state switches correctly.

**Comment by LorenzMeier** [comment]
Could you send a pull request for this?

**Comment by LorenzMeier** [comment]
Fixed.
