### ISSUE TITLE
please modify .gitignore file 

### ISSUE THREAD

**Issue by stmoon** [PX4/Firmware#1985]
when I add a new topic, I recognize new file in topic is ignored by .gitignore file.
could you please tell me why the directory is inserted in .gitignore file? 
if there is no reason, how about remove the "src/module/uORB/topic/*" item in .gitignore file?

**Comment by LorenzMeier** [comment]
The method to add new topics has changed. I just updated the docs, please follow the guide here:
http://www.pixhawk.org/dev/add_uorb_topic
