### ISSUE TITLE
Enable MS5611 driver on NavIO+ shield

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1996]
MS5611 driver reporting current pressure / temp on RPI2 on PX4 shell application.

**Comment by mhkabir** [comment]
@tumbili Any progress on any of the hardware interfacing? :)

**Comment by tumbili** [comment]
@mhkabir Hi Kabir. I just came back from my vacation. I will try to run the stack on the hardware and see if I can interface the sensors. Last time I tried it the new vdev environment still had a lot of issues but things have very much improved right now.
