### ISSUE TITLE
ms5611: bug in reset code

### ISSUE THREAD

**Issue by KIrill-ka** [PX4/Firmware#2007]
According to ms5611 datasheet ms5611 requires 2.8ms delay after issuing a reset command.
The driver code calls start_cycle immediately.

    if (ret != OK) {
    //log("measure error %d", ret);
    /* issue a reset command to the sensor */
    _interface->ioctl(IOCTL_RESET, dummy);
    /* reset the collection state machine and try again */
    start_cycle();
    return;
    }
In it's turn start_cycle schedules measurement cycle in 1 tick.

    work_queue(HPWORK, &_work, (worker_t)&MS5611::cycle_trampoline, this, 1);
Sometimes this causes sequence of resets until the system becomes busy enough to delay for 2+ ms.
I sniffed i2c bus with logic analyzer before finding this. For me that sequence of resets cause random failures of ArduPlane baro initialization.
I've added more delay to work_queue call above to fix the problem.
       work_queue(HPWORK, &_work, (worker_t)&MS5611::cycle_trampoline, this, USEC2TICK(2800));

**Comment by LorenzMeier** [comment]
Thanks! So you are using the MS5611 on a FMUv1 or on an external bus?

**Comment by KIrill-ka** [comment]
The board is called "captain 3 pro". It's quite similar to FMUv1 (same cpu, mpu6500@spi, lsm303d@spi, ms5611@i2c, AT45DB, spi microsd). It was rather easy to port ardupilot to this board.

**Comment by mhkabir** [comment]
@KIrill-ka Do you have a link for your board?

**Comment by KIrill-ka** [comment]
http://www.aliexpress.com/item/STM32F405-flight-control-sensor-module-MS5611-MPU6500-LSM303-axis-flight-control-module-offer-four-axis-source/32259957338.html
I didn't find where the design is originating from. It comes with CD which includes the schematic.
