### ISSUE TITLE
Radio Channel reset and can't arm?

### ISSUE THREAD

**Issue by wangsen1312** [PX4/Firmware#2009]
I just update the PX4's firmware and calibrate all the sensors and radio. But every time I reboot the pixhawk, I can't arm the arducopter, it always show  ARM: THR below FS, I get and find the parameters for the Throttle became 899, it should be 1119 after my calibration. 
Can anyone give me some suggestion?

**Comment by DonLakeFlyer** [comment]
Which exact parameter?

**Comment by wangsen1312** [comment]
@DonLakeFlyer  The Throttle channel will reset to 889 every time when I reboot? can I hard code the parameter? Thank you very much!!

**Comment by DonLakeFlyer** [comment]
Which exact parameter are you talking about? There are multiple throttle parameters.

**Comment by wangsen1312** [comment]
![default](https://cloud.githubusercontent.com/assets/11545246/7098129/cca926ca-dfaa-11e4-95e1-ad9ca159601c.PNG)
The throttle In this picture always reset? Thank you!

**Comment by DonLakeFlyer** [comment]
Sorry. You're in the wrong place. You need to be in the APM forums for Mission Planner or APM Planner. This is for users of the px4fmu firmware (not APM firmware) and or QGroundControl.
