### ISSUE TITLE
Validate EKF attitude estimation during hand/catapult launch

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#2015]
![launch3](https://cloud.githubusercontent.com/assets/2300221/7108787/8f58dcee-e14d-11e4-9bb3-c60f3ad32e1a.png)
This plot shows a negative-going spike of approximately 10 degrees in the pitch attitude estimate coincident with the forward acceleration of a hand launch. Logfile: http://dash.oznet.ch/view/FSCop8iEPryB6oPxsQhFqN
I don't think this pitch deviation is real, based on observation of the actual hand launch trajectory.
A catapult launch will be performed to collect additional data.

**Comment by LorenzMeier** [comment]
You were flying 7f9138f400dc9efcb86fbbd44907fcda5681b1fb, which was lacking https://github.com/PX4/Firmware/commit/368a21ddab652ede39ffee3bd0a4f8e770fd0c8d, which in turn lead to a wrong strap down fusion of accelerations. I'm pretty sure if you re-do the test on the bench with master this will be gone.

**Comment by kd0aij** [comment]
Thanks Lorenz. I thought I had that fix, but must have forgotten to reflash the Ninox after merging.

**Comment by kd0aij** [comment]
Catapult launch test with recent master:
Firmware Version	4b34221, log: http://dash.oznet.ch/view/2tKinhfPJVz3sT4okLRuhk
![catlaunch](https://cloud.githubusercontent.com/assets/2300221/7143849/e96a373a-e29e-11e4-95e0-1187947a9c1b.png)

I think the few degrees of upward pitch on acceleration are probably real. Video coming soon.

**Comment by kd0aij** [comment]
catapult launch video: http://youtu.be/Px7PTE8WC9A

**Comment by kd0aij** [comment]
![catlaunch_gyro](https://cloud.githubusercontent.com/assets/2300221/7158892/79a7b330-e33b-11e4-9eea-aa40ee613f11.png)

This plot indicates that the EKF pitch estimate agrees well with the integral of the pitch axis gyro.
Closing.
