### ISSUE TITLE
Offboard Position Control: Not setting the velocity ignore flags makes controller cut throttle: offboard velocity setpoints do not work

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#2036]
See https://github.com/mavlink/mavros/issues/273#issuecomment-93316957

**Comment by LorenzMeier** [comment]
See https://github.com/PX4/Firmware/pull/1983 and please contribute to testing if you are affected by this.

**Comment by aerialhedgehog** [comment]
bench testing worked for me, for both offboard velocity and position control.  offboard control is also is also working on master, is this expected?

**Comment by mhkabir** [comment]
@aerialhedgehog Position control should work as expected on master, but not velocity control.

**Comment by TSC21** [comment]
What's the status on this?

**Comment by LorenzMeier** [comment]
Fixed on master, closing.
