### ISSUE TITLE
3D mode for fixed wing

### ISSUE THREAD

**Issue by friekopter** [PX4/Firmware#2040]
I propose a new mode for fixed wing aircraft: Roll, pitch and yaw control rotation rate in the coresponding body frame axes. Throttle is passed through, or maybe autopilot comes into play as soon as there is not enough propeller moment.
This is similar to ACRO mode in APM Plane.
Not sure if that was already discussed somewhere else.

**Comment by thomasgubler** [comment]
We could map the multicopter ACRO mode to this

**Comment by dagar** [comment]
FW acro mode implemented!
