### ISSUE TITLE
low memory on FMUv1

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#2071]
recent master: Not enough memory available for 2 mavlink instances. Must use nsh console to stop mavlink on telemetry port prior to attempting to connect with QGC over USB.

**Comment by LorenzMeier** [comment]
I feared that one - need to set up auto testing for FMUv1. I don't have an obvious fix to offer at this point.

**Comment by kd0aij** [comment]
discovered and raised that issue on a Chromebook :)

**Comment by philipoe** [comment]
Having the same issue here. Either when starting a second mavlink instances, or in our case even when just startin additional (custom = our own) drivers for external devices. Are there any plans to improve RAM consumption again to make e.g. 2 mavlink instances work on FMUv1?

**Comment by LorenzMeier** [comment]
I believe recent improvements brought everything back down to operational. Ping me if not.
