### ISSUE TITLE
Cut back number of text messages

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2072]
We want the system to only spit out useful text info, not all it happens to find. This is important for situational awareness. To give a recent extreme example: The engine failure of a Quantas A380 (the engine came apart mid-flight) led to a check list of text messages which took the Co-Pilot over 20 minutes to work through. All it really was trying to say was that the engine failed, and that parts flying out of it had taken out other aircraft systems.

@DonLakeFlyer This will also help with your calibration issue, although we should enforce the constraints you have also on the tech level, as discussed.

**Comment by LorenzMeier** [comment]
http://en.wikipedia.org/wiki/Qantas_Flight_32

**Comment by bansiesta** [comment]
Is this targeted at mavlink_log_info/critical or warnx/printf?

**Comment by LorenzMeier** [comment]
Log info

**Comment by LorenzMeier** [comment]
We did this pretty much already and will continue - closing this for now.
