### ISSUE TITLE
Implement battery failsafe

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2099]
It it would be nice for the user to specify a battery charge threshold at which the vehicle enters RTL mode.

**Comment by tumbili** [comment]
@AndreasAntener @thomasgubler FYI

**Comment by severinleuenberger** [comment]
Please consider, that RTL is not always the best and most secure method for operations. 
We would appreciate if you leave a door open to not use this function (perhaps use 0.0v for RTL - means desabling RTL). Thanks.

**Comment by tumbili** [comment]
@severinleuenberger Sure, this will be optional and probably disabled by default.

**Comment by AndreasAntener** [comment]
About the OBC failsafe, regarding the discussion yesterday:
https://pixhawk.org/users/failsafe

I'm not saying that this has to be exposed to the user in QGC, I think it's good to limit that to the very basic options. But it makes sense to consider all failsafe options in the firmware implementation so the whole state handling is in one place.

(Thomas is better suited to point at the code if necessary :))

**Comment by thomasgubler** [comment]
The 2 most important pointers to the code:
  1. Here the detected failures are evaluated and a mode is requested from the navigator (search the individual variables e.g. gps_failure to see how they are set https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L1637)  https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L529
  2. here the mode set above is evaluated https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_main.cpp#L425 you can see that already some parameters are evaluated as well (for switching between normal and OBC mode)

The first part is more concerned about which state we *can* go in given the sensors/subsystems which still are healthy. The 2nd one is about *what* we do exactly in this state

**Comment by tumbili** [comment]
@thomasgubler Thanks for the pointers, I will look into it and probably get back to you.

**Comment by LorenzMeier** [comment]
@tumbili This is something you should really, really look into next week.

**Comment by LorenzMeier** [comment]
Done!
