### ISSUE TITLE
python import error:  No module named genmsg.template_tools

### ISSUE THREAD

**Issue by molyswu** [PX4/Firmware#2103]
Hi,
I compile all a project on the PX4Firmware,have error for following :
make all
python import error:  No module named genmsg.template_tools.

what's it reson?

thank you for your help!

.

**Comment by LorenzMeier** [comment]
The wiki documentation is complete, if you install the PX4 toolchain following it you should get all Python modules resolved.

**Comment by molyswu** [comment]
l install the PX4 toolchain ,and get all Python modules resolved
