### ISSUE TITLE
Build the firmware with Eclipse ,error occurs ...

### ISSUE THREAD

**Issue by dragonmind** [PX4/Firmware#2128]
@tumbili Hi ! 
   I have build the px4 firmware with Eclipse,and then error occurs.I want use the mb12xx sonar sensor.I have edited the code in "/px4/Firmware/src/modules/position_estimator_inav/position_estimator_inav_main.c "like this:

	struct range_finder_report reportrange;
	memset(&reportrange, 0, sizeof(reportrange));

       int vehicle_sonarrange_sub=orb_subscribe(ORB_ID(sensor_range_finder));
......
      when I biuld the firmware,error occurs. The error information is as follows:
     d:/px4/Firmware/src/modules/position_estimator_inav/position_estimator_inav_main.c:1134:1: error:            the frame size of 3528 bytes is larger than 3500 bytes [-Werror=frame-larger-than=]...
     I have no idea with this issue.

**Comment by LorenzMeier** [comment]
You can increase the frame size here:
https://github.com/PX4/Firmware/blob/master/src/modules/position_estimator_inav/module.mk

If you do, make sure to watch the stack size (by running "top" on the NSH shell).
