### ISSUE TITLE
Stale git version on incremental builds

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2148]
If you build the firmware and only do incremental builds, the commit SHA that's later used in sdlog2 won't change.

**Comment by dagar** [comment]
It's passed as a define. I'm not sure how to make the current build system pick up on that change. Maybe we could write it to a header (and setup header deps) or another c file?

**Comment by AndreasAntener** [comment]
Just quoting @kd0aij , might be an option
> we should add a "touch" to the makefile to force recompiling sdlog2 and ver

**Comment by kd0aij** [comment]
I'm pretty inept with "make", but this caused sdlog2.c to be recompiled:
$(shell touch src/modules/sdlog2/sdlog2.c)
I inserted it in the makefile immediately following "export GIT_DESC"

**Comment by kd0aij** [comment]
created PR #2149 with makefile change

**Comment by LorenzMeier** [comment]
This is fixed on master. Thanks @kd0aij for your PR, fixed it in a similar fashion.
