### ISSUE TITLE
Multirotor PID tuning guide out of date

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2155]
From @Zefz:
https://pixhawk.org/users/multirotor_pid_tuning should be updated to include the new FF gains on rates. (e.g MC_PITCHRATE_FF).

**Comment by Zefz** [comment]
@tumbili How would you approach tuning the FF for rate gains?

**Comment by tumbili** [comment]
@Zefz This is a good question. You could tune the system to get a good response without feedforward. Then you could add some small feed-forward and see how it improves the tracking performance.

**Comment by LorenzMeier** [comment]
@tumbili This is something to resolve today together.

**Comment by LorenzMeier** [comment]
Given the last tuning session the current state is probably just fine.
