### ISSUE TITLE
C++ std::abs is not available when compiling C++ modules

### ISSUE THREAD

**Issue by molysgaard** [PX4/Firmware#2158]
When using std::abs in code within a module, a compilation error:
```
/Firmware/src/modules/test_module/test_module_main.cpp: In function 'int test_module_main(int, char**)':
/Firmware/src/modules/test_module/test_module_main.cpp:8:18: error: 'abs' is not a member of 'std'
     printf("%d", std::abs(0.1));
```

A minimal test module showing the issue is in the following commit: https://github.com/molysgaard/Firmware/commit/fbce2040c0465435de41b2e85d66f9f7f987fdcf

Would be nice if people could fork off https://github.com/molysgaard/Firmware/tree/cpp-abs-test branch cpp-abs-test and verify the issue.

Anyone have thought about why this happens, I find it very odd that PX4 somehow changes the C++ stl?

It should be noted that this keeps certain parts of Eigen from compiling.

**Comment by bansiesta** [comment]
I looked at this, and all I see is that std::abs should definitely be in cmath like you assumed. I don't know why this happens.

As a workaround you can always use: ```std::fabs()```
