### ISSUE TITLE
Wrong GPS coordinates conversion in HIL mode

### ISSUE THREAD

**Issue by s3erjaeh** [PX4/Firmware#2168]
File: [src/modules/mavlink/mavlink_receiver.cpp](../blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1363):1363 & 1364

Wrong convertion from:
[int32_t   mavlink_hil_state_quaternion_t::lat; ///< Latitude, expressed as * 1E7](https://github.com/mavlink/c_library/blob/master/common/mavlink_msg_hil_state_quaternion.h#L12)
to:
[double   vehicle_global_position_s::lat; /**< Latitude in degrees](https://github.com/PX4/Firmware/blob/d8b64a05d725bd2d231d270114d3541f8d10cb6f/src/modules/uORB/topics/vehicle_global_position.h#L66)

EXISTING:
[hil_global_pos.lat = hil_state.lat;](../blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1363)
FIX:
hil_global_pos.lat = hil_state.lat * 1e-7;

**Comment by LorenzMeier** [comment]
Thanks for reporting. On future reports, sending a pull request would be appreciated, but if a text report is the maximum you can do that's good as well.

Fixed in 66b87ac.
