### ISSUE TITLE
Level Calibration Not Reliable

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#2244]
I am still seeing 0.3 g x acc on level ground after doing a level cal. Manually setting BOARD_ROT_Y fixed this for me.

**Comment by kd0aij** [comment]
level cal worked ok for me on my f450 quad and Caipi_vtol

**Comment by tumbili** [comment]
@jgoppert Could you put the vehicle level and check your euler angles. Can you then check if after the calibration the board offset values are more or less equal to these?

**Comment by tumbili** [comment]
@jgoppert And what board rotation do you have?

**Comment by LorenzMeier** [comment]
@jgoppert Can't replica this. Will close this unless we get more feedback.

**Comment by jgoppert** [comment]
OK

**Comment by edkoch** [comment]
I don't know if the issue I am seeing is the same as what has been reported here, but as I mentioned in the dev call the other day I am not able to keep a level calibration on my quad for very long. I am using the latest QGC and when I both calibrate the gyro and do the new level horizon calibration the level looks great as can be seen in the enclosed image, but after flying once or twice it gets out of wack and I have to recalibrate it again. I did not see this behavior with RC8.

In the enclosed diagrams I show a nice level view after a calibration and then also show the level after a couple of flights.

![screen shot 2015-06-01 at 4 24 21 pm](https://cloud.githubusercontent.com/assets/1964544/7972137/f33c235e-09fe-11e5-8914-ad2a045306a8.png)
![screen shot 2015-06-01 at 5 26 22 pm](https://cloud.githubusercontent.com/assets/1964544/7972143/ffb20aea-09fe-11e5-87ca-a3322ac5cfd4.png)
![screen shot 2015-06-01 at 1 40 56 pm](https://cloud.githubusercontent.com/assets/1964544/7972152/0a6d10d8-09ff-11e5-97c4-6e430fd36b23.png)

**Comment by tumbili** [comment]
@edkoch How is your Pixhawk attached to the frame? Any chance that it could move?

**Comment by tumbili** [comment]
@edkoch I don't want to start speculating but I remember to have had a similar issue with a Pixhawk with damaged sensors.

**Comment by edkoch** [comment]
My platform is a 3DR X8 and I have not changed the Pixhawk mounting. It uses double sided foam tape so I guess it is a little pliable, but it should remain consistent from flight to flight. I have also been wondering if there could be a HW problem. I actually have a few Pixhawks on hand so I’ll swap it out and see if the problem persists.


-ed

**Comment by tumbili** [comment]
@edkoch Yes, please do so!

**Comment by edkoch** [comment]
I finally had a chance to swap out the pixhawk and after a couple of flights I don’t seem to be having the same problems that I was having. I’ll keep an eye on it, but perhaps I do have some bad HW.


-ed

**Comment by LorenzMeier** [comment]
@jgoppert I'm closing this, please reopen if you continue to see this.
