### ISSUE TITLE
NuttX HIL (actuator_control output in MAVLink app) not operational on master

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2249]
@mcharleb I don't have the details yet, but something is not working as on stable / release_v1.0.0 branches when trying to run HIL.

**Comment by davids5** [comment]
check cxx_initalizers

**Comment by davids5** [comment]
If the bug was mavlink_if0: invalid data rate '(null)'  I think https://github.com/PX4/Firmware/pull/2334  will fix it

**Comment by LorenzMeier** [comment]
@davids5 Fix through 3f4b5fc, which was unrelated. Thanks!
