### ISSUE TITLE
Loading params for Linux

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2262]
@mcharleb Currently we use px4_open for opening the parameter file which will not work because the file is a real device and not a virtual one. I have changed the calls in my branch but I'm not sure if I should do a PR. Do you want to create a virtual node for it or should I replace all those calls with "open"?

**Comment by mcharleb** [comment]
Please make them use ::open now. Initially QuRT didn't support a filesystem
so I was using px4_open and close to get around that.

-Mark

**Comment by tumbili** [comment]
Fixed via #2263, closing
