### ISSUE TITLE
If the mission does get rejected initially, the fixed mission is still never executed

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2275]
Try by setting the first waypoint too far initially, then move it closer. It still will never accept it.

**Comment by tumbili** [comment]
@LorenzMeier I rather have the problem that it always accepts it.

**Comment by tumbili** [comment]
@LorenzMeier Do you agree that we should move the check to the mission feasibility check?

**Comment by LorenzMeier** [comment]
Yes, that makes sense.

**Comment by tumbili** [comment]
@LorenzMeier Actually not, because the home distance is not know a priori.

**Comment by tumbili** [comment]
@LorenzMeier I'm just rebuilding QGC, it won't let me send commands.

**Comment by tumbili** [comment]
But I tested on the other pc and it seems to work there. Couldn't yet reproduce the problem.

**Comment by tumbili** [comment]
Works for me. I first set the waypoint far away and it complained. Moving the waypoint close enough made it accept the mission.

**Comment by LorenzMeier** [comment]
Was it already flying then?

**Comment by tumbili** [comment]
No. There is no difference between fw and mc right?

**Comment by tumbili** [comment]
I'm testing mc with jMAVSim.

**Comment by tumbili** [comment]
What were you testing on?

**Comment by LorenzMeier** [comment]
HIL on fixed wing. I can't reproduce either right now, so closing this. Sorry for the confusion!

**Comment by LorenzMeier** [comment]
Ok, got it. This is after a jump in position in HIL. Looks like the auto mode is suffering from some sort of NaN state that never gets reset.

**Comment by tumbili** [comment]
@LorenzMeier What do you mean by jump in position?

**Comment by LorenzMeier** [comment]
I traced this back to my HIL setup generating NaN states in the system. Need a better detector: https://github.com/PX4/Firmware/issues/2291
