### ISSUE TITLE
Fix yaw limiting in new mixer

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2279]
Currently we can have the situation that the mixer goes into failsafe mode and gives up on yaw when exceeding its possible spread. While that is the right fail-safe strategy, its not great for manual acrobatic flying.

**Comment by LorenzMeier** [comment]
@tumbili This here does not look correct - the comment says it scales yaw, but in fact the math there replaces the commanded yaw entirely, not taking the original yaw demand into account:
https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/mixer/mixer_multirotor.cpp#L306-L320

We probably should also retain some yaw demand, e.g. scale down the demand up until some threshold, e.g. 0.1 or 0.05. Anything below that threshold still gets mixed even when the system is approaching the limits. The idea is to maintain the yaw heading with some minimal contribution, but not to allow heading changes any more.

This should fix the usage problems @AndreasAntener was describing.

**Comment by tumbili** [comment]
@LorenzMeier No I don't think so. Just above you see that yaw is mixed in. Now if we see that the mixing in of yaw caused our output to violate bounds we just just the yaw which will lead to the output being on the bound. You don't need to yaw command anymore for that.

**Comment by LorenzMeier** [comment]
So in other words it subtracts a scaled yaw? In that case we would just need to limit the subtracted quantity so that it doesn't subtract so much that we loose all yaw authority. I have no idea about the right magic number for this though, nor do I have a better / solid idea not involving magic numbers.

**Comment by tumbili** [comment]
The math is like this (I left away the scales):

out = R + P + thrust + Y -> e.g out is negative now

we want out to be exactly 0 not negative, so we set it to 0 and solve for Yaw:

Y = - (R + P + thrust)

**Comment by tumbili** [comment]
I think for full thrust the case is clear: we have to dedicate some thrust to yaw control, meaning that if the user wants to go full thrust up and yawing at the same time he will have to give some thrust away to yawing. But for the rest I would say we should leave it as is.

**Comment by LorenzMeier** [comment]
The problem is that users who fly full throttle and pitch forward loose yaw control. That's absolutely deadly during manual flying, so we have to fix that.

**Comment by tumbili** [comment]
@LorenzMeier I just did I flight where I allow to give 0.15 thrust away to yaw. Was able to do full thrust pitch forward, yaw tracked well. However, to change yaw during full thrust is not possible since 15 % is too little.

**Comment by tumbili** [comment]
Here is the log  http://dash.oznet.ch/view/devkueALTqXyBCghqhueyV

**Comment by tumbili** [comment]
@LorenzMeier If you use flightplot and look at the motor outputs at 233s you can see very nicely what the mixer does.

**Comment by LorenzMeier** [comment]
Is it not possible to change yaw or does it loose the yaw tracking? I think no change is fine, but it shouldn't loose the yaw angle.

**Comment by tumbili** [comment]
@LorenzMeier It does not loose it (although the tracking could be a bit better). I'm going to  play with this param. In one extreme case I will set it high so if you apply full thrust and yaw you should get a low thrust value and see it yawing (commanded). We will have to agree on a value which makes sense.

**Comment by tumbili** [comment]
![mixer](https://cloud.githubusercontent.com/assets/7610489/8033361/0a7ebdf0-0dde-11e5-85be-3d59bee069cb.png)

**Comment by tumbili** [comment]
Notice the spike in the motor outputs at 233s

**Comment by LorenzMeier** [comment]
@tumbili Where is the branch / PR for this?

**Comment by tumbili** [comment]
@LorenzMeier Oh, forgot to push it. Just going for another test flight (removing position controller carrot approach and then will push everything)

**Comment by LorenzMeier** [comment]
Addressed in b571d704883d850242b879d02b86fcb6907941e6.

**Comment by LorenzMeier** [comment]
@AndreasAntener Reopening, please put the log in here.

**Comment by AndreasAntener** [comment]
These logs should show it:
http://dash.oznet.ch/view/M8SyLmxiT7hmvJ3ZaGXRnD
http://dash.oznet.ch/view/uZ9XE9DKtGRJzvvaeeVfaF

**Comment by LorenzMeier** [comment]
http://dash.oznet.ch/view/M8SyLmxiT7hmvJ3ZaGXRnD#AS_Yaw_PLOT Does only show minor yaw spikes - is this what you're referring to? Was this with off board control?

**Comment by AndreasAntener** [comment]
This was all manual. Judging from the ground, the yaw error was about 15-20 degrees before we let go of pitch. I'm pretty sure that it happened in those flights. If there's time maybe we can to a dedicated test for that today.

**Comment by LorenzMeier** [comment]
I think you want this fix for off board anyway:
https://github.com/PX4/Firmware/pull/2341

If you test it we can merge it relatively quickly.

The manual throttle target should have been limited to 90%, so I need to check why its not.

**Comment by LorenzMeier** [comment]
The issue was the thrust compensation when pitched. We already had a limit on the other end, and I've just updated the default param value:
https://github.com/PX4/Firmware/pull/2343

It would be great if you could test that one.

**Comment by AndreasAntener** [comment]
Ah, thanks. I guess then we flown with max thrust 1 again.

**Comment by AndreasAntener** [comment]
Looks good now, thanks :)
