### ISSUE TITLE
Add ability to load/save parameter subsets to a file.

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#2286]
This is a feature request. It would facilitate sharing parameters between users and airframes, and make initial setup easier and less error-prone.

**Comment by DonLakeFlyer** [comment]
You can load parameter subsets fine. Just delete what you don't want from the file and load it. Saving a subset seems like a really low pro thing.

**Comment by kd0aij** [comment]
Thanks, it was not apparent to me that one could hack the parameter file
with impunity.

On Fri, Jun 5, 2015 at 7:17 PM, Don Gagne <notifications@github.com> wrote:

> You can load parameter subsets fine. Just delete what you don't want from
> the file and load it. Saving a subset seems like a really low pro thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PX4/Firmware/issues/2286#issuecomment-109493891>.
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by LorenzMeier** [comment]
I will close this, but if you find a good place in the docs to add a clear hint it would be appreciated.
