### ISSUE TITLE
Difficulties with yawrate to lock heading hold

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2299]
@LorenzMeier, @tumbili 
Here's a log from todays flight: http://dash.oznet.ch/view/TcrueUA3R433rTXvWn3vKB
(latest release_v1.0.0 merged with the osd branch)

Yawrate changes a lot during the flight, so it switched always in and out of heading hold (while always in posctl). That caused the heading to converge to 0. Same as I saw in HIL

My yawrate is oscillating a lot, I'm not sure if you can set the threshold high enough for that:
![screen shot 2015-06-07 at 20 56 59](https://cloud.githubusercontent.com/assets/5750020/8025464/47c59cfa-0d58-11e5-8b0a-5625a0b3dafd.png)
What do you think?

Here you see the convergence:
![screen shot 2015-06-07 at 20 58 58](https://cloud.githubusercontent.com/assets/5750020/8025477/791c3c32-0d58-11e5-9304-d4a543df51df.png)

**Comment by tumbili** [comment]
@AndreasAntener Yeah I'm stupid, I implemented it the wrong way. I'm fixing it.

**Comment by tumbili** [comment]
@AndreasAntener Hope this fixed it https://github.com/PX4/Firmware/pull/2300

**Comment by AndreasAntener** [comment]
Cool :) going to try it soon

**Comment by kd0aij** [comment]
@AndreasAntener I tested POSCTL on my Ninox flying wing yesterday, and it seemed to work correctly. I had made one small change: #2301 Perhaps there is less tail wag with my plane (how can you wag your tail if you don't have one? call it yaw oscillation :)

![ninox_yaw](https://cloud.githubusercontent.com/assets/2300221/8035229/f381edd4-0dab-11e5-8384-7abc7996e6f2.png)

**Comment by AndreasAntener** [comment]
;) I know my FX-61 oscillates in yaw quite a bit after turns..

Hm, if I look at your yaw rate, you should have experienced the same problem as me..

**Comment by kd0aij** [comment]
you're right; added yawrate to my plot. Same magnitude as yours; +/-0.5 rad/sec
![ninox_yawrate](https://cloud.githubusercontent.com/assets/2300221/8036468/3ef1c718-0db5-11e5-8b99-b6c1ebe98b8b.png)

**Comment by tumbili** [comment]
@kd0aij @AndreasAntener Well with the fix I pushed today it shouldn't matter anyway. As long as your yawrate comes close to zero at some point everything is fine. (should be :-))

**Comment by LorenzMeier** [comment]
@tumbili Is this one resolved?

**Comment by tumbili** [comment]
@LorenzMeier I think so. It worked fine on Thursday when we tested it.

**Comment by LorenzMeier** [comment]
Reopening this after some more testing by ada suggests the lock-on still might need some work.

**Comment by AndreasAntener** [comment]
http://dash.oznet.ch/view/v98KHkQvYTRnRpEyjrBjPR
Marked the 2 spots here:
<img width="1379" alt="screen shot 2015-07-05 at 23 24 31" src="https://cloud.githubusercontent.com/assets/5750020/8516074/83332d9e-23af-11e5-8218-6ca962276f6f.png">
(yaw is scaled by 0.5)

**Comment by LorenzMeier** [comment]
I think the fails were actually on other occasions. The location you've marked was counter-steering to a strong motion, but it actually stabilised the course over ground.

<img width="630" alt="screen shot 2015-07-06 at 09 58 39" src="https://cloud.githubusercontent.com/assets/1208119/8518064/f44322c0-23c6-11e5-9695-c528456e09e8.png">

**Comment by LorenzMeier** [comment]
I've pushed a fix for the delayed lock here:
https://github.com/PX4/Firmware/commit/fd63ba7b898b95469b62f6f3f42f12e042aae619

Closing this for now.

**Comment by AndreasAntener** [comment]
Ok, I can see the delayed lock because of the bad yaw behaviour of my Phantom after rolls (which I didn't notice in flight).

But about the 2 spots I marked: are you saying this is a tuning issue?
About stabilizing COG: what I'm missing in the log is the heading that it gets locked onto. Then we would see the exact moment of the lock, and of course the COG it wants to hold.
