### ISSUE TITLE
FW manual control actuator sensitivity param

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2307]
In aircraft capable of generating large control throws (e.g. 3D fixed wing aircraft), it is normal to setup the RC TX with "dual rates" with low rates normal for takeoff and landing. But, when flying in stabilized modes, the autopilot maps 100% input to maximum roll and pitch angles. This necessitates switching to high rates for normal stabilized flight, if the programmed maximum angles are to be achieved, and can be a source of confusion if a plane has been set up "properly" for manual flight. **This confusion is easily prevented by clearly documenting the need for high rates in stabilized modes.**

But, in an emergency requiring manual intervention, this means the pilot will have to deal with high rates immediately after switching to manual mode. Some RC transmitters may be programmed to change rates according to flight mode, and in this case the rate switch can be set up such that it is reversed in stabilized modes, with low rates being the default in manual mode. Similar capability could be provided by additional scaling parameters which apply to RC roll/pitch/yaw inputs when in manual mode, effectively providing "low rate" in manual mode.

Of course, some emergencies might require high rates for a successful recovery...

**Comment by LorenzMeier** [comment]
How about just recommending expo in general on the transmitter? That together with a default max angle of 55 degrees for attitude control should pretty much fix all the issues.

**Comment by kd0aij** [comment]
oops, I edited the first comment (description), not realizing it would still be blamed on @tumbili 
@LorenzMeier Regarding expo, I use it for both high and low rates on my 3D aircraft... expo doesn't eliminate the need (desire?) for low rates

**Comment by tumbili** [comment]
@LorenzMeier @LorenzMeier I will do it, should be quick work.

**Comment by tumbili** [comment]
Implemented in #4787
