### ISSUE TITLE
FW Loiter Radius not working?

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2308]
http://dash.oznet.ch/view/Ygp8Hg78EniX7oRfS8kcZM

**Comment by LorenzMeier** [comment]
Its not the loiter radius - there is more to it. Either on this airframe or in general - the roll angle is completely ignoring the roll setpoint:
http://dash.oznet.ch/view/Ygp8Hg78EniX7oRfS8kcZM#AS_Roll_PLOT

**Comment by kd0aij** [comment]
Looks like the setpoint maxes out at about 45 degrees, and actual roll is a little less.
Is there a gain parameter which would increase the commanded roll angle?

**Comment by LorenzMeier** [comment]
I'm closing this, since its not really an issue but a logging / plotting / gain tuning thing which confused us.
