### ISSUE TITLE
VICON_POSITION_ESTIMATE vs ATT_POS_MOCAP

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#2313]
Right now I think we have two messages that serve the same purpose. If one wants to add support for one of this messages (I'm aware that `vicon_position_estimate` can already be handled in the mavlink receiver but `att_pos_mocap` can't) in the estimators, for which one should one move to? Shouldn't one of those be removed?

According to the current implementation, `att_pos_mocap` should fit better the purpose, as attitude is sent in quaternion representation. (also the name is more adequate, as VICON is not the only existing mocap system).

**Comment by LorenzMeier** [comment]
Please use att_pos_mocap as suggested and remove vicon message support in the process.
