### ISSUE TITLE
RTL landing on fixedwing radio loss

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2323]
From @kd0aij: RTL flew at 42m above home. On reaching home location announced RTL: landing and continued flying forever at 40% throttle.

Switching off RC resulted in landing sequence.

**Comment by kd0aij** [comment]
actually I entered RTL in both cases by switching off the TX
At the first airport in Xplane, the flyaway occurred. After changing airports and restarting QGC/pixhawk, a correct landing sequence occurred. Don't know what was different besides the Xplane location.

**Comment by LorenzMeier** [comment]
If I don't switch off the TX RTL works fine via command. So curious to see if it works with TX loss.

**Comment by LorenzMeier** [comment]
@kd0aij Would you mind testing in HIL again? We've fixed a bunch of mission related smaller issues which combined could lead to the error you were seeing.

**Comment by kd0aij** [comment]
This was working correctly for me in HIL as of 2 days ago :)

**Comment by LorenzMeier** [comment]
Ok, closing this then, thanks!
