### ISSUE TITLE
FW: Change RTL height not possible

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2324]

**Comment by LorenzMeier** [comment]
In my testing the RTL height worked as expected: It defined the minimum altitude, but if the plane was higher, it returned at the higher altitude.

**Comment by tumbili** [comment]
@LorenzMeier Might have confused RTL loiter alt with RTL return alt. Testing in some minutes.

**Comment by LorenzMeier** [comment]
@tumbili Did you end up testing this? What's the outcome? I can't second this in HIL.

**Comment by tumbili** [comment]
@LorenzMeier I think I changed the wrong param. I'm sure I already tested this but will try again in one of the flights today.
