### ISSUE TITLE
Send message with "above ground level altitude"

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2338]
Especially when flying relative altitude items the user will chant to double check conveniently if the plane flies at the correct altitude.

**Comment by LorenzMeier** [comment]
@dogmaphobic @DonLakeFlyer the AGL altitude is quite relevant during normal operation - probably something to have as a big number in the HUD.

**Comment by dogmaphobic** [comment]
I currently capture altitude data from MAVLINK_MSG_ID_VFR_HUD. That gives us AMSL, WGS84 and Relative. What exactly is *Relative* altitude? Where would I get AGL altitude?

**Comment by LorenzMeier** [comment]
The ALTITUDE message is now part of the MAVLink spec and could be used.

**Comment by LorenzMeier** [comment]
Done!
