### ISSUE TITLE
POSIX: Heavy use of #ifdefs

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2359]
I think this made initially sense, but it would be good to reduce the number of #ifdefs in the port. I'm referring to statements like:

```C
#ifdef __PX4_NUTTX
	register_driver(MAVLINK_LOG_DEVICE, &fops, 0666, NULL);
#else
	register_driver(MAVLINK_LOG_DEVICE, NULL);
#endif
```

**Comment by mcharleb** [comment]
Unless the NuttX port is going to switch to VDev vs CDev we need ifdefs or
separate files for each port (which is much harder to maintain).

**Comment by mcharleb** [comment]
I supposed the CDev implementation could use the same args for register_driver and just pass dummy values for the 2nd and 3rd args but that seems less clear.

**Comment by LorenzMeier** [comment]
Much improved.
