### ISSUE TITLE
Takeoff help not yet working

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2394]

**Comment by tumbili** [comment]
![tecs](https://cloud.githubusercontent.com/assets/7610489/8179496/479f8a2c-1417-11e5-807c-7d777ace15e8.png)

**Comment by tumbili** [comment]
@LorenzMeier Flew straight into the ground although altitude setpoint was set 50m above ground and climbout request was explicitly set in function do_takeoff_help

**Comment by tumbili** [comment]
The crash happened at about 26.25 seconds.

**Comment by tumbili** [comment]
See #2395

**Comment by LorenzMeier** [comment]
Could you also graph the effective throttle and effective pitch, along with the commanded pitch? That would tell us much more how it went wrong.

**Comment by tumbili** [comment]
Ok, will do. I can tell you now that thrust was full and pitch was in the negative area.

**Comment by tumbili** [comment]
Closing this, tested.
