### ISSUE TITLE
FMUv1 does not boot (master)

### ISSUE THREAD

**Issue by bansiesta** [PX4/Firmware#2408]
The FMUv1 does not currently boot in master. It beeps and freezes after reporting ```command px4flow not found```. This is a regression from stable where it still works.

**Comment by LorenzMeier** [comment]
@mcharleb @davids5 I'll debug this, but you should be aware of the regression.

**Comment by mcharleb** [comment]
Is this after makefile changes, or something else?

**Comment by LorenzMeier** [comment]
I'm not sure. The FMUv1 setup is not widely used, and so it can take some time until a regression is found. I didn't have time to bring my HW test harness back up to speed.

**Comment by LorenzMeier** [comment]
Closed via 5e27b7b.

**Comment by bansiesta** [comment]
Yep, works again, thanks!
