### ISSUE TITLE
MC_att_controller yaw setpoint movement

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2409]
Currently the mc attitude controller moves the yaw setpoint in the direction of the current yaw angle if the error is too large. We have a mixer which handles priorities for the control of the axes and thrust.
So we could try removing this logic in the controller. This would also get ride of the annoying fact that the copter tends to change it's orientation after heavy manoeuvres.

**Comment by tumbili** [comment]
@kd0aij This is related to your flip experiments.

**Comment by kd0aij** [comment]
I'll test the idea when I get a chance.

**Comment by LorenzMeier** [comment]
Fixed / implemented on release and master.
