### ISSUE TITLE
mad yaw rotation 

### ISSUE THREAD

**Issue by taogashi** [PX4/Firmware#2413]
Hi all,
     My SingleCopter experienced a mad rotation around z axis, I've checked the log and found something interesting, but still don't know the cause of this behavior. 
![screen shot 2015-06-18 at 3 38 22 pm](https://cloud.githubusercontent.com/assets/4775141/8227207/ba9c657e-15d7-11e5-846a-a36a5f9f912a.png)
As the legend shows, yaw_rate_setpoint, attitude_controller_output_yaw, yaw_rate and rc_ch3 are plotted. There is an apparent rising of yaw_rate, which is not intended.

a normal log looks like:
![screen shot 2015-06-18 at 4 20 58 pm](https://cloud.githubusercontent.com/assets/4775141/8227295/c8b97498-15d8-11e5-8b08-5c959b3e7282.png)

I think there is a considerable latency between yaw_rate and attitude_controller_output_yaw. But I don't think it's the cause of the mad rotation.

**Comment by DrTon** [comment]
Maybe wrong props rotation direction? Post raw log please.

**Comment by taogashi** [comment]
Hi @DrTon raw log is [here](https://github.com/taogashi/dragon)

**Comment by taogashi** [comment]
log001.px4log is the mag one, log002.px4log the normal, :)

**Comment by LorenzMeier** [comment]
@taogashi When you refer to "SingleCopter" what do you mean by that? Does it have single rotor?

**Comment by taogashi** [comment]
@LorenzMeier ducted fan VTOL actually. The bug can't be reproduced... we are taking more analyses to find the answer. Thx

**Comment by LorenzMeier** [comment]
Stale, closing.
