### ISSUE TITLE
Test all flight modes with a quad

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2415]
We need to verify that none of the fixed wing fixes did create regressions for multicopters.

**Comment by tumbili** [comment]
@LorenzMeier I can do this as soon as I have my quad back.

**Comment by tumbili** [comment]
@sjwilks Do you have bandwidth to test this? ;-)

**Comment by AndreasAntener** [comment]
He's going to use your quad ;)

**Comment by tumbili** [comment]
@AndreasAntener Sure :-D

**Comment by sjwilks** [comment]
Today should work.

**Comment by LorenzMeier** [comment]
@sjwilks Something to do during food-coma maybe? 8)

**Comment by sjwilks** [comment]
We tested both v1 and v2 setups today. Ada will post the results tonight.
In general all good.

**Comment by AndreasAntener** [comment]
Test report is submitted, just missing the F450 logs :) (btw, my qav didn't log half the flights.. missing the mission and the *cough* flip)
