### ISSUE TITLE
POSIX: Sim environment makes assumptions about startup order

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2416]
@molecule @mcharleb Based on my testing the sim environment seems to make assumptions about startup order to make the network connections. I need to create a reproducible test case, but my current impression is that I need to fix jMAVSim to constantly send something to the UDP port of the simulator, or to fix the simulator to start up immediately. It takes 30 seconds until it boots for me, so I'm not 100% clear yet what the conditions are.

**Comment by tumbili** [comment]
@LorenzMeier The simulator waits for a first message of jmavsim before it starts.
