### ISSUE TITLE
POSIX: Sensor sim produces imperfect data

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2430]
@mcharleb The data we get from the sim must be distorted in time, scale or axis assignment. The performance is significantly worse compared to HIL.

**Comment by tumbili** [comment]
@LorenzMeier Will look into this.

**Comment by LorenzMeier** [comment]
A test shows that this only affects the dynamic attitude estimation: The system interprets ~1.5 radians as 0.6 radians, so it systematically underestimates the real rotation. This is either a time delta issue or a scaling issue of the converted values.

**Comment by tumbili** [comment]
@LorenzMeier The simulated drivers are using a timestamp which they generate themselves. I will replace that one with the timestamp of the HIL sensor message.

**Comment by tumbili** [comment]
Also I checked the interval in which data is coming from the simulator and got on average 3ms.

**Comment by LorenzMeier** [comment]
The stopgap fix was this one:
https://github.com/PX4/Firmware/pull/2455

But the real fix is to block the command handler until the thread it launched returned.

**Comment by tumbili** [comment]
Related to #2465

**Comment by LorenzMeier** [comment]
@mcharleb I've traced this now to the HRT implementation and/or the gyro driver not delaying the sensor reads as much as it should. the inter-loop times are at 1 KHz, but should be at 250 Hz:
```
WARN  last run: 813 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 883 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 980 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 956 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 133 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 511 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 784 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
WARN  last run: 685 (file /home/drone/src/Firmware/src/modules/sensors/sensors.cpp line 2201)
```

**Comment by mcharleb** [comment]
This should have been fixed with the latest batch of changes. The code that did the limiting to 250Hz was ifdefed out for the posix build. I tested it and it seems to work for me.

**Comment by LorenzMeier** [comment]
Fixed.
