### ISSUE TITLE
POSIX: Default setup needs to avoid standard ports

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2433]
@molecule The POSIX port uses port 14550 for the SIM, but this is the default port of QGroundControl and widely used throughout the industry. I've moved the SIM to port 14560 on master, please update the docs and your internal use and let me know when this issue can be closed.

**Comment by mhkabir** [comment]
* @mcharleb

**Comment by LorenzMeier** [comment]
Resolved on master.
