### ISSUE TITLE
[TECS] Overspeeding while descending

### ISSUE THREAD

**Issue by boosfelm** [PX4/Firmware#2530]
In this [TECS test flight!] (http://dash.oznet.ch/view/6LjHagRDXf29tCtiK2mU2E) when strongly descending the speed control first slows down too much and then speeds up way too much, looks almost like an oscillation of the TECS to me. Basically an extreme throttle up leads to the downward acceleration. Could this be coupled to FW_T_VERT_ACC and a threshold of 0.7g for AccX. Definitely minimum airspeed was not hit.
![92c3c7e4-222b-11e5-8547-c2f4e22c6dba](https://cloud.githubusercontent.com/assets/6023217/8511198/587f0c3c-230d-11e5-8a0a-d0db02f23424.png)

The behaviour is reproducible with different speeds (15, 20, 13 m/s) at 590, 710 and 795.

**Comment by LorenzMeier** [comment]
Fixed.
