### ISSUE TITLE
[TECS] Excessive pitch up when engaging TECS

### ISSUE THREAD

**Issue by boosfelm** [PX4/Firmware#2531]
When engaging TECS in fw at 366s in [this flight!] (http://dash.oznet.ch/view/6LjHagRDXf29tCtiK2mU2E), the plane pitches up strongly and ASP and AF diverge. Looks like the AsF dropped to 4 m/s while the AsSP stays at 15 m/s.
![13f68aa4-222c-11e5-9f40-21762aaf5b7f](https://cloud.githubusercontent.com/assets/6023217/8511211/117e6494-230e-11e5-827e-ea4701453ad4.png)
![8f99a772-222c-11e5-8434-8d0f7f8ae63d](https://cloud.githubusercontent.com/assets/6023217/8511212/1384721a-230e-11e5-8003-06bc0056fb03.png)

**Comment by LorenzMeier** [comment]
Fixed in #2590. Please report any remaining TECS issues in a new issue.
