### ISSUE TITLE
Zero throttle in FW ALT/POSCTL results in actual 0 throttle (in-flight)

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2535]
Was this recently introduced/is intended? Or should this only be the case for landed state?

**Comment by AndreasAntener** [comment]
http://dash.oznet.ch/view/v98KHkQvYTRnRpEyjrBjPR

**Comment by LorenzMeier** [comment]
Yes, as intended. Since ALTCTL / POSCTL are user-facing modes we need the user to retain control over throttle.
