### ISSUE TITLE
rviz problem

### ISSUE THREAD

**Issue by plusangel** [PX4/Firmware#2539]
Dear friends,

I have to admit that I'm newbie and maybe what I ask is not so serious and related to the development. My problem is that when I launch in ros worlds like:

roslaunch rotors_gazebo ardrone_house_world.launch 
and the ardrone with:

roslaunch px4 ardrone.launch ns:="ardrone"
or any other launch files in rviz when I add the robot model there are errors with all the frames marked as "No transform from [] to [world]. World is my fixed frame. I'm sure that I missing something important.  Can you help me?

Thanks in advance

**Comment by LorenzMeier** [comment]
Will look into this.

**Comment by LorenzMeier** [comment]
Outdated.
