### ISSUE TITLE
Missing iris_*_world_with_joy.launch

### ISSUE THREAD

**Issue by weiweikong** [PX4/Firmware#2541]
Hi,
     just tested PX4 ROS SITL Setup, following the guide from https://pixhawk.org/dev/ros/sitl#joystick_configuration. But failed when I tried
```
roslaunch px4 gazebo_iris_house_world.launch
```
or 
```
roslaunch px4 gazebo_iris_outdoor_world.launch
```

Checking the launch file `Firmware/launch/gazebo_iris_outdoor_world.launch` and `Firmware/launch/gazebo_iris_house_world.launch`, it seems two other launch files, `iris_outdoor_world_with_joy.launch` and `iris_outdoor_world_with_joy.launch`, are missing.

**Comment by LorenzMeier** [comment]
Thanks for reporting. I'm currently reworking this and will have something more wrapped up tomorrow.

**Comment by kPanesar** [comment]
Any updates on this issue? The repository still seems to be missing the files.

**Comment by weiweikong** [comment]
@kPanesar you could try other launch file or build a new world for it.

**Comment by kPanesar** [comment]
@weiweikong True, I was just wondering if it there were any updates as it has been a few months. Thanks!

**Comment by LorenzMeier** [comment]
Outdated.
