### ISSUE TITLE
Do not arm if USB is connected.

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2543]

**Comment by LorenzMeier** [comment]
@kd0aij We will implement this soon to prevent people from doing stupid things with off board control. That will break the AUAV support, so someone needs to look into that in general. I will ask Phil for a recent one for cross testing.

**Comment by kd0aij** [comment]
Tridge has added a "stat" call to the APM check as a workaround for existing X2s. I assume it's been tested: https://github.com/diydrones/ardupilot/commit/f4a9f9876fa2bb7803a838110580eae15ffb91ee

**Comment by abvgeej** [comment]
Do not want

**Comment by kd0aij** [comment]
@abvgeej Sometimes terse is bad :)

**Comment by LorenzMeier** [comment]
Implemented.
