### ISSUE TITLE
Lidar Lite PWM autostart regression

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#2560]
On master, the lidar lite pwm driver / pwm input, doesn't work. It works if I disable autostart (SENS_EN_LL40LS)  and start the drivers manually, so I think it must be a timing / init order issue?

**Comment by jgoppert** [comment]
I just confirmed that disabling SENS_EN_LL40LS
and adding 

```bash
pwm_input start
ll40ls start pwm
```

to extras.txt still works.

**Comment by LorenzMeier** [comment]
This should fix it, could you re-try and report back?
https://github.com/PX4/Firmware/commit/a17310bf33c12b2468da416876f4a22b955f18ee

**Comment by jgoppert** [comment]
I've got to wait a bit for testing. Will check it out though.
