### ISSUE TITLE
New log format

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#2565]
New PX4 log format
===============

The log format is self-describing, i.e. parser should know only base algorithm of decoding, all information about structure of messages contained in the log.

Features:

 - Message body size up to 256 bytes
 - Message name + fields types/names string size up to 256 bytes
 - Fixed-size arrays support
 - Multi topics support: up to 128 separate streams of one type with "active" marker

Encoding
--------

Log stream consists of messages. Each message starts with `msg_type` byte:

```
	uint8_t msg_type;		// Message type
	PACKET msg_body;		// Body
```

There are following types of packets:

##### FORMAT (0x46, 'F'): message format

**FORMAT** packet contains information about name and format of the message, i.e. types and names of all fields.

```
	uint8_t msg_id;			// Message ID
	uint8_t size;			// Message size
	uint8_t format_len;		// Size of format string
	char format[256];		// Message format string
```

Stream generator must write formats for all used messages at stream start.

Message format string has following format:

```
<message_name>:<field type> <field_name>;...;<field type> <field_name>;
```

`field_type` is C type. Supported types are:

 - int8_t
 - uint8_t
 - int16_t
 - uint16_t
 - int32_t
 - uint32_t
 - int64_t
 - uint64_t
 - float
 - double
 - bool
 - char

Also supported fixed-size arrays of values: `<type>[<size>]`. Array of `char`s should be interpreted by parser as null-terminated, UTF-8 encoded string.
Some examples:

```
uint8_t mode;
float[3] position;float[3] velocity;
char[128] message;
```

##### TIME (0x54, 'T'): timestamp

**TIME** packet contains only timestamp:

```
	uint64_t timestamp;		// Timestamp, in microseconds
```

This packet must be placed before each snapshot indicating timestamp for all following DATA packets.

##### DATA (0x44, 'D'): payload messages

**DATA** message contains message ID and payload:

```
	uint8_t msg_id;			// Message ID
	BODY body;				// Payload struct
```

Payload (`BODY body;`) is encoded C struct with little-endian numbers.

##### MULTIDATA (0x4d, 'M'): multi payload messages

**MULTIDATA** message contains message ID, multi ID and payload:

```
	uint8_t msg_id;			// Message ID
	uint8_t multi_id;		// Multi ID
	BODY body;				// Payload struct
```

"Multi" messages may be used to log multiple streams of one type of data. E.g. we have a system with two gyros, published on topics `GYRO[2]` (with priority 0) and `GYRO[5]` (with priority 10). `GYRO[2]` topic is high priority and must be used as source if available. `GYRO[5]` must be used only in case of timeout on `GYRO[2]`. Currently used topic called **active**.

To log these two topics, message format must be defined only once, with flag `is_multi = 1`. Corresponding payload messages must be prefixed with `multi_id = 2` and `multi_id = 5`. Also active topic must be marked with 7 bit set in `multi_id`. So in result `multi_id = 0x80 | 2` for `GYRO[2]` and `multi_id = 5` for `GYRO[5]`. Parser should show to user aggregated `GYRO` stream, containing data from `GYRO[2]` or `GYRO[5]` depending on `active` flag.

Stream example
==============

Example stream in high level representation:

```
FORMAT: msg_id=0, is_multi=0, size=64, format="VERSION:char[32] firmware;char[32] hardware"
FORMAT: msg_id=1, is_multi=1, size=12, format="GYRO:float[3] value"
FORMAT: msg_id=2, is_multi=1, size=12, format="ACCEL:float[3] value"
FORMAT: msg_id=3, is_multi=0, size=2, format="STATUS:bool armed;uint8_t mode"
DATA: msg_id=0, body={"1.2.3", "PX4FMUv2"}
TIME: timestamp=12345
MULTIDATA: msg_id=1, multi_id=130, body={value=[0.21, 0.32, -0.15]}	// Active
MULTIDATA: msg_id=1, multi_id=5, body={value=[0.22, 0.31, -0.13]}
DATA: msg_id=3, body={armed=false, mode=3}
TIME: timestamp=16442
MULTIDATA: msg_id=1, multi_id=5, body={value=[0.22, 0.31, -0.13]}
MULTIDATA: msg_id=2, multi_id=129, body={value=[0.72, -0.21, 9.78]}
```

**Comment by kd0aij** [comment]
What is the intended use of the timestamp message? I assume this is to save space in the log by reducing redundancy for groups of messages with identical timestamps.
But the current sdlog2 implementation is throwing away timestamps on critical data such as IMU sensor readings by not writing timestamp messages frequently enough. Does this new format provide a way to guarantee that the timestamps are correct for each and every data sample?

**Comment by pavel-kirienko** [comment]
@DrTon @LorenzMeier Does this affect the tasks that @againagainst is about to start working on?

**Comment by LorenzMeier** [comment]
Yes. Its probably going to be required in order to make the code generation efficient because it addresses severe limitations of the current logging format.

**Comment by DrTon** [comment]
>What is the intended use of the timestamp message? I assume this is to save space in the log by reducing redundancy for groups of messages with identical timestamps.

Exactly, timestamps logic is the same as in sdlog2.

>But the current sdlog2 implementation is throwing away timestamps on critical data such as IMU sensor readings by not writing timestamp messages frequently enough. Does this new format provide a way to guarantee that the timestamps are correct for each and every data sample?

Current sdlog2 implementation writes samples with fixed rate, e.g. 100Hz. If topic rate is e.g. 500Hz then 4 of 5 samples will be skipped anyway and writing "correct" timestamp for each fifth sample will not help, the data will be still not full. I.e. we have snapshots of all topics, and timestamp is time of snapshot, not of the update on individual topic. In new logger implementation we are going to leave this approach (fixed log rate and skipping messages on too frequent topics).

Logging at full rate, without skipping any updates is not possible with current hardware/OS, bitrate is too high and writing eats too much CPU. Also it's not possible with current unbuffered uORB implementation, any small lag in logger and some data will be lost. So it's better to NOT guarantee writing 100% of updates but just write at fixed guaranteed rate.

**Comment by DrTon** [comment]
And some thoughts about logger format. This will not change logic but just binary representation of the data. There are following types of the messages:

 - message format description
 - timestamp
 - business message, normal (topic data)
 - business message, multi (for multi-topics, includes instance ID)

Parser must know how to parse each type of the messages, including timestamp. So packing timestamp as business message is useless. The same for message format. And format for normal and multi messages are also a bit different.

What about adding "message type" field to header, e.g. instead of magic num? So we will have these 4 base message types + many types for normal/multi business message. I suspect that generator and parser code will be more clear and short in this case.

**Comment by kd0aij** [comment]
I like to do Fourier analysis of things like accelerometer data. This normally relies on a uniform sampling interval, but correct results can be achieved (with some difficulty) using non-uniform sampling. But this is only possible if the timestamps are preserved. That requires including the timestamp in the message.

I see that sdlog2 is using a circular buffer in front of the SD card, similar to my own implementation in MatrixPilot. Experience with MatrixPilot has shown that a 0.25 second buffer is the minimum required to prevent dropouts;  a recent px4log of mine represents about 35K bytes/second throughput, and the default buffer size of 8K is slightly below that minimum requirement.  But I see that 12K bytes is being allocated for fmuv2 at sdlog2 startup in rc.logging, so that looks OK.

For my purposes, it would be desirable to support configuring logging so that the available throughput can be utilized for high fidelity recording of a subset of messages e.g. each and every IMU sensor reading (with the correct individual timestamps).

**Comment by DrTon** [comment]
>I like to do Fourier analysis of things like accelerometer data. This normally relies on a uniform sampling interval, but correct results can be achieved (with some difficulty) using non-uniform sampling. But this is only possible if the timestamps are preserved. That requires including the timestamp in the message.

>For my purposes, it would be desirable to support configuring logging so that the available throughput can be utilized for high fidelity recording of a subset of messages e.g. each and every IMU sensor reading (with the correct individual timestamps).

Yes, correct individual timestamps will help only if some topic logged at full rate. Anyway if timestamps will be included in topic body you will have both snapshot timeout and individual timeout. But I don't think that it's necessary. Once you will have full rate data for accel topic you can simply assume that sampling is uniform with good precision, ignoring logger timestamps (with some jitter in this case), because actually it is implemented this way in driver. On other hand, if data logged at not full rate you can assume that logger samples at lower but uniform rate :)

**Comment by DrTon** [comment]
Logger format reworked, IMO it's more clean now. Still under question:

- Format string: "uint32_t value" looks a bit long, may be use one-char type aliases as in old format ("i value")?
- We need some recommended metadata messages formats for version, parameters etc to make parsers more simple and universal in future.
- Need to think about parameters writing. Currently all parameters written as float, but it would be good to preserve type.

@LorenzMeier, what do you think?

**Comment by kd0aij** [comment]
Good point about being able to assume uniform sampling with some jitter.
But what is the use of logging unfiltered sensor data at less than the sampling rate?

**Comment by DrTon** [comment]
>But what is the use of logging unfiltered sensor data at less than the sampling rate?
It's still good for simulation, checking of estimators etc. Yes, results will be more noisy, but anyway.

**Comment by kd0aij** [comment]
except the "noise" will be aliasing

**Comment by DrTon** [comment]
Format updated again. Now log generator (C++11) and parser (Java) implemented, look good, but need some cleanup, will be published soon.

**Comment by LorenzMeier** [comment]
On master.
