### ISSUE TITLE
Total energy demand excessively high on transition to loiter

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2588]
In this log the total energy is excessively high on the transition to loiter, despite the setpoint being the current altitude:
http://dash.oznet.ch/view/LGYBNoS6ihSzL6adGy4UPV

**Comment by LorenzMeier** [comment]
@kd0aij This log here would probably benefit from this change as well:
http://dash.oznet.ch/view/GvQbFTUNCWXHDotTfyz6hV

**Comment by kd0aij** [comment]
@LorenzMeier Thanks, already noted in the associated flight report.
