### ISSUE TITLE
Log folder named "sessNNN" with 3D gps fix

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#2619]
Branch beta:
log folder "sess004" showed a creation date of 2015-07-28 on the SD card, and creation dates of files within the folder also reflected the correct UTC time

**Comment by AndreasAntener** [comment]
Same here today, sessionXXX folders with correct creation/modification date

**Comment by SimonWilks** [comment]
@LorenzMeier any ideas on where to look on this one? This is almost all we ever see now. There is often a timestamp on the log file itself so the system seems to have a GPS timestamp but it isn't making it through to the logger.

**Comment by LorenzMeier** [comment]
Here is the dir creation:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L444-L452

**Comment by LorenzMeier** [comment]
GPS timestamp gets copied here:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L1335-L1339

And time conversion is here:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L410

The system defaults to only use GPS time.
