### ISSUE TITLE
[ll40ls] Validate current LidarLite driver with the new LidarLite v2

### ISSUE THREAD

**Issue by andre-nguyen** [PX4/Firmware#2624]
Self explanatory I guess. Looks like pwm works. Need to check i2c.

**Comment by dragonmind** [comment]
Hi, andre-nguyen!
Dose the LidarLite v2 work normally with its I2C bus on current pixhawk!
Appreciating your help! Thank!

**Comment by andre-nguyen** [comment]
It's in the wiki
https://pixhawk.org/peripherals/rangefinder

**Comment by proficnc** [comment]
A new driver needs to be written for the V2.. Connection is the same.

**Comment by LorenzMeier** [comment]
Done, thanks to tridge. In master.
