### ISSUE TITLE
Can the LIDAR LITE V2 laser rangefinder work with the I2C bus on pixhawk normally?

### ISSUE THREAD

**Issue by dragonmind** [PX4/Firmware#2635]
Hi !
  I have a LIDAR LITE V2 laser rangefinder .I want to use it with its I2C bus on pixhawk to realize UAV altitude control. Can it work with the I2C bus on pixhawk normally? How can I start the sensor driver?

Appreciating for your help! Thank you !

**Comment by dragonmind** [comment]
Hi, andre-nguyen @andre-nguyen 
I have a LIDAR LITE V2 laser rangefinder .Does it work normally with its I2C bus on current pixhawk ?
Thank!

**Comment by mhkabir** [comment]
Duplicate, #2624. Closing.
Essentially, we need to rewrite the driver with the new i2c interface on the V2. No more ack/nack rubbish.
