### ISSUE TITLE
Do not exit boot on NSH command failure

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2639]
NSH should offer a command to continue to execute a script even if the last command failed.

**Comment by davids5** [comment]
Closed via https://github.com/PX4/Firmware/pull/6985

set +e will ignore the error and not exit the script.

It can be set once at top of the init script or bracket a command
```
set +e
this_command_will_fail_and_not_cause_the_script_ to_exit
set -e
now_this_command_will_fail_and_cause_the_script_ to_exit
```
