### ISSUE TITLE
AUX ports currently broken

### ISSUE THREAD

**Issue by SimonWilks** [PX4/Firmware#2644]
@LorenzMeier just in case you missed my not so obvious comment on the PR, this change da4d8a5c2b9ff220877caa976671a46a887bdd78 breaks AUX port usage.

Checking for the existence of ```/dev/pwm_output1``` looks like it will always fail since ```/dev/pwm_output1``` doesn't exist until ```fmu mode_pwm``` is executed.

Perhaps this check can be done further down before the mixer loads or just do with using the ```SYS_USE_IO``` parameter?

**Comment by LorenzMeier** [comment]
Fixed.
