### ISSUE TITLE
Implement NSH over MAVLink 

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2650]
@tridge has added a wrapper packet to the protocol and implemented it for APM here, and it looks super useful as it deconflicts the USB port and makes it easier to access NSH in general.
https://github.com/diydrones/ardupilot/blob/master/libraries/AP_HAL_PX4/NSHShellStream.cpp

**Comment by LorenzMeier** [comment]
@julianoes needs collaboration with @DonLakeFlyer and @dogmaphobic on the QGC side.

**Comment by bkueng** [comment]
done
