### ISSUE TITLE
Mavlink rate management over USB erratically imposing low limits, never scales back up without telemetry_status updates

### ISSUE THREAD

**Issue by NaterGator** [PX4/Firmware#2658]
I recently pulled stable and master and noticed some mavlink message rates were randomly running slower than normal. The mavlink rate would not always decrease by the same factor from boot to boot, nor would it always be impacted.

After a bit of debugging I believe this is attributable to 79910ce7e04f45ab28bf6dbae17f9d6224215ce2; mavlink status indicated that rate mult on the USB interface was at 0.05 when rates were most severely impacted. 

I haven't spent too much time digging into exactly what is going on, but one concern I have is the update_rate_mult call [here](https://github.com/PX4/Firmware/blob/5fd88f4d3e1c581003bce7345c1be69fcbf82123/src/modules/mavlink/mavlink_main.cpp#L1712) could occur before any mavlink messages have been selected for streaming. If that is the case I believe we'll divide by zero [here](https://github.com/PX4/Firmware/blob/5fd88f4d3e1c581003bce7345c1be69fcbf82123/src/modules/mavlink/mavlink_main.cpp#L1355). fminf should protect us from nefarious floating point behavior.

Haven't gotten to the root of what is randomly causing degraded rate limits on boot, but wanted to get this in the tracker and mention that an absence of telemetry_status updates prevents the rate limit from ever recovering once it has been limited.

**Comment by LorenzMeier** [comment]
This is fixed on stable / master / beta.
