### ISSUE TITLE
EKF att pos estimator: bug in coning error correction

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#2663]
In these two lines of code (https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/estimator_22states.cpp#L273)

```
    // Save current measurements
    Vector3f  prevDelAng = correctedDelAng;

    // Apply corrections for earths rotation rate and coning errors
    // * and + operators have been overloaded
    correctedDelAng   = correctedDelAng - Tnb*earthRateNED*dtIMU + 8.333333333333333e-2f*(prevDelAng % correctedDelAng);
```

`(prevDelAng % correctedDelAng) == 0`, isn't it? So compensation doesn't work actually. Would be interesting to hear from Paul how it should work and fix this, because I suspect that coning errors add significant part to integration error.

**Comment by LorenzMeier** [comment]
@priseborough Would you mind having a look? This file 1:1 from the current test harness.
