### ISSUE TITLE
Logging somethimes not working on master.

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2688]
While testing the VTOL code we realized that many logs (not all, just the important ones) are corrupted.
Flightplot complains about e.g. "Unknown message type: 47". The unknown message type is not always the same.

**Comment by LorenzMeier** [comment]
There is no message with index 47.

**Comment by LorenzMeier** [comment]
@tumbili Please cross-test this branch.

**Comment by AndreasAntener** [comment]
Flightplot has difficulties always after the same messages, for example:
```
Unknown message type: 63
Message before null: VISN 17236521
Message before that: ATTC 17236521

Unknown message type: 61
Message before null: VISN 68439553
Message before that: ATTC 68439553

Unknown message type: 127
Message before null: VISN 75210376
Message before that: ATTC 75210376
```

I couldn't spot anything in the logging code that points to a problem with these messages (formats). I don't know if Logmuncher reports the same errors but ignores them.

**Comment by tumbili** [comment]
@AndreasAntener Seems like the logparser is not detecting the ATTC1 message. It is there in the log but he does not see it. I'm checking why right now.

**Comment by tumbili** [comment]
@LorenzMeier @AndreasAntener Got it! Vision and ATTC1 have the same ID

**Comment by tumbili** [comment]
We should have a script which checks that no ID is used two times.

**Comment by LorenzMeier** [comment]
Fixed.
