### ISSUE TITLE
Future Flash space issue due to PX4_WARN in NuttX build

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2690]
nsh> WARN  52790675   timed out (file /Users/lorenzmeier/src/Firmware/src/modules/navigator/navigator_main.cpp line 340)

The filename will eat a lot of flash space in storage. @mcharleb Could you provide a NuttX-level macro which does not include the file? Thanks!

**Comment by mcharleb** [comment]
That code no longer exists.

**Comment by mcharleb** [comment]
Nuttx can set whatever log verbosity it wants.

**Comment by LorenzMeier** [comment]
Fixed.
