### ISSUE TITLE
Log AUX outputs

### ISSUE THREAD

**Issue by SimonWilks** [PX4/Firmware#2697]
We should be logging all aux outputs. This will be particularly useful for VTOLs as all fixed wing controls run over these.

**Comment by xueyingmo** [comment]
Do you solve this problem,can we log all aux outputs now?

**Comment by SimonWilks** [comment]
Not yet but thanks for the reminder.

**Comment by tubeme** [comment]
Another reminder here... :)

**Comment by SimonWilks** [comment]
See #3413

**Comment by AndreasAntener** [comment]
Fixed on master
