### ISSUE TITLE
px4-fmu_v1 not starting with master

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2698]
It seems like it's not booting completely.

**Comment by tumbili** [comment]
Tested with beta and then it works.

**Comment by CornerOfSkyline** [comment]
I meet the same problem.  When I flash the maseter into pixhawk. The IO B/E LED flash quickly, and the ESC plug in the main pwm out is warning.

**Comment by CornerOfSkyline** [comment]
Did this problem have been solved?

**Comment by LorenzMeier** [comment]
@CornerOfSkyline it should be improved now on master, worth re-testing. I tested beta to work fine yesterday.
