### ISSUE TITLE
Logged motor outputs of deactivated motors are not "0"

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2726]
@tumbili  I'm not sure if this is really an issue (we see no symptoms), the disabled motors during fixed-wing flight with a VTOL configuration don't seem to stay at the lowest level but change slightly. Would be good to know if this is a problem or not.

Firefly example from an old log (http://dash.oznet.ch/view/SxJPFGEGfW9dwVrSPuXLvb):
![screen shot 2015-08-19 at 16 35 21](https://cloud.githubusercontent.com/assets/5750020/9359245/92222248-4690-11e5-9ebd-6cb893980dd7.png)

Or here (http://dash.oznet.ch/view/jy9DdoXST5zy3X4uoKPhs4):
![screen shot 2015-08-19 at 16 39 16](https://cloud.githubusercontent.com/assets/5750020/9359340/ec37eab0-4690-11e5-944a-f6153b771f1f.png)

Referring to out2 and out3 in the charts that overlap.

**Comment by SimonWilks** [comment]
Here is a plot that @deadhurricane shared on gitter: 

![actuators](https://cloud.githubusercontent.com/assets/10983630/9359673/9f8dae00-4692-11e5-816f-4fb4df940717.png)

Looks like we have a leak on disabled motors ;)

**Comment by tumbili** [comment]
@AndreasAntener @SimonWilks I think I know what the reason for the leak is:

effective_pwm[i] = control_value * (max_pwm[i] - min_pwm[i])/2 + (max_pwm[i] + min_pwm[i])/2;
/* last line of defense against invalid inputs */
if (effective_pwm[i] < min_pwm[i]) {
	effective_pwm[i] = min_pwm[i];
} else if (effective_pwm[i] > max_pwm[i]) {
	effective_pwm[i] = max_pwm[i];
}

This is the code which makes sure that the outputs satisfy the pmw limits. In the first line our control signal is mapped to the range [min_pwm, max_pwm]. So the values for the motors are going to move inside this very small range, (e.g. 900-950) but they are never going to be out of the range which is our requirement. So everything is fine.

**Comment by tumbili** [comment]
BTW, you find the code here https://github.com/PX4/Firmware/blob/2a8402edb1313d8e70301b8045bf0b5132a4c7ff/src/modules/systemlib/pwm_limit/pwm_limit.c#L196

**Comment by tumbili** [comment]
@AndreasAntener @SimonWilks Closing this as it doesn't pose an issue.

**Comment by AndreasAntener** [comment]
:+1: thanks for having a look
