### ISSUE TITLE
FW: plane goes into endless dive if airspeed sensor fails

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2729]
I landed my fw in the grass which probably clogged my airspeed sensor. After re-takeoff the plane always dived towards the ground in ALTCTL mode. Looking at the log the airspeed sensor show values which are way too low for what I flew.

Log:
http://dash.oznet.ch/view/4ChvyQdeEWpBwaHErYNEni

**Comment by AndreasAntener** [comment]
Ha! You found one more reason to change something about this speed/altitude weight for alt/posctl modes in fixed wing.
https://github.com/PX4/Firmware/issues/2030

**Comment by AndreasAntener** [comment]
It's too bad we didn't yet work out the final approach to solving this, but I think the ideas are there in the issue I referenced.

**Comment by tumbili** [comment]
@AndreasAntener Yes true, although this time the extra flavour of an airspeed sensor providing wrong data comes into play :-)

**Comment by AndreasAntener** [comment]
Sure, my first comment was a little overhasty. It's just a pity that my fixed wing flight testing in this area dropped to the bottom of the todo list, and I haven't tried any of the ideas yet. So, I'm done spamming this issue :)

**Comment by LorenzMeier** [comment]
It needs an airspeed failure detector.

**Comment by LorenzMeier** [comment]
This is a log showing complete failure of the airspeed sensor. The airspeed sensor has been calibrated before and was indicating values when blowing into it on the ground.
Log: http://dash.oznet.ch/view/pFDAKzzFivKPvwXwqtwwGK

**Comment by LorenzMeier** [comment]
Same as on previous release, closing.
