### ISSUE TITLE
Current master is not working with PX4FMU_v1

### ISSUE THREAD

**Issue by limhyon** [PX4/Firmware#2757]
Hi,
I downloaded current master to my PX4FMU_V1, but it is not working.
Also tested with two different PX4FMU_V1, the result is same.
It is frozen during boot. I attached log file as follows.

I also tested with QGC.
Stable version - WORKED
Beta version - WORKED
Current master - NOT WORKING
v1.0.0 tag - WORKING

[Start of Log]

[boot] Enabling IN12/13 instead of SPI2
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nsh: mount: mount failed: No such device
nsh: mkfatfs: mkfatfs failed: I/O error
nshterm [6:70]
param: selected parameter default file /fs/mtd_params
[param] Loaded: /fs/mtd_params
 0:   RC_MAP_THROTTLE: match
 1000.0000000:   RC3_MIN: match
 0:   RC_MAP_ROLL: match
 1000.0000000:   RC1_MIN: match
 0:   RC_MAP_PITCH: match
 1000.0000000:   RC2_MIN: match
 0:   RC_MAP_YAW: match
 1000.0000000:   RC4_MIN: match
rgbled: no RGB led on bus #3
blinkm: I2C init failed
blinkm: init failed
 1:   SYS_USE_IO: match
 0:   SYS_AUTOSTART: match
[i] No autostart
PX4IO_i2c on I2C bus 2 at 0x1a (bus: 100 KHz, max: 400 KHz)
px4io: check CRC failed: -1: Invalid argument
PX4IO_i2c on I2C bus 2 at 0x1a (bus: 100 KHz, max: 400 KHz)
telem> Failed to communicate with IO, abort.
px4io: driver init failed
px4io: px4io is not started, still attempting upgrade
PX4IO_i2c on I2C bus 2 at 0x1a (bus: 100 KHz, max: 400 KHz)
[PX4IO] using firmware from /etc/extras/px4io-v1_default.bin
[PX4IO] bootloader not responding
PX4IO_i2c on I2C bus 2 at 0x1a (bus: 100 KHz, max: 400 KHz)
px4io: check CRC failed: -1: Invalid argument
[i] ERROR: PX4IO not found
[i] ERROR: PX4IO not found, disabling output
ver hwcmp match: PX4FMU_V1
dataman: Could not open data manager file /fs/microsd/dataman
dataman: dataman start failed
param: Error: Parameter UAVCAN_ENABLE not found.
param: Error: Parameter UAVCAN_ENABLE not found.
[i] UAVCAN_ENABLE is 0
MS5611_I2C on I2C bus 2 at 0x76 (bus: 100 KHz, max: 400 KHz)
ms5611: no device on bus 2
ms5611: driver start failed
adc init done
MPU6000 on SPI bus 1 at 3 (1000 KHz)
L3GD20 on SPI bus 1 at 1 (11000 KHz)
hmc5883: no device on bus 2
HMC5883_I2C on I2C bus 2 at 0x1e (bus: 100 KHz, max: 400 KHz)
meas_airspeed: no MS4525 airspeed sensor connected
ets_airspeed: no ETS air

[End of Log]

**Comment by LorenzMeier** [comment]
Please re-run make distclean && make archives and rebuild - let us know if the issue persists then.

**Comment by LorenzMeier** [comment]
Note that your microSD is no good:
nsh: mount: mount failed: No such device

**Comment by LorenzMeier** [comment]
Closing this, as FMUv1 is tested.
