### ISSUE TITLE
posctl under wind computes a really distant setpoint

### ISSUE THREAD

**Issue by v01d** [PX4/Firmware#2774]
Today, trying posctl with px4flow outside, where there was some wind which I had to fight when on altctl, after switching to posctl, the multicopter wanted to go away in the direction of the wind. After looking at the logs I found that the setpoint could be set as far as 9m away.

After looking at how the setpoint is computed when entering posctl, I saw that both velocity and thrust are used to estimate a continuous setpoint. The problem I see is that thrust is assumed to be an acceleration. Under wind, thrust is used to actually stay with small velocity, so in this case this would be incorrect. Maybe it would be better to use actual acceleration of the vehicle, if desired.

**Comment by AndreasAntener** [comment]
Should be resolved since we are not shifting the position setpoint anymore but using desired velocities.
