### ISSUE TITLE
Fixed wing attitude stabilization becomes unstable with GPS issues

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2777]
@severinleuenberger: reporting your issue with GPS in stabilized here. @tumbili  as discussed.
Log: http://dash.oznet.ch/view/LgdXyaqoAPrzWtGv94VMHk

According to Severing the plane became unstable in stabilized after which he switched out to manual where it was flying normally.

![screen shot 2015-08-28 at 10 33 10](https://cloud.githubusercontent.com/assets/5750020/9542397/9ef8add4-4d70-11e5-94a2-89937803ead4.png)

It seems when GPS eph/epv goes beyond 10 the problem started. This should make the EKF estimator stop usign GPS: https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp#L1376 . `requiredAccuracy` is doubled after the first fix (from 5 to 10)

**Comment by severinleuenberger** [comment]
I have to say, that I mounted an old cheap GPS on that day in my big turlte fixed wing airplane. And not having a good GPS seems to lead to a very shaky and unstable flight performance in althold. My gut feeling would say, that in ALTHOLD mode the scaling factor of the GPS against the other sensors are overweightened. Better trust more to the baro and gyro / acc / airspeed sensor, and leave in case of uncertainity the GPS out of the calculation. Just my 2 cent based on some assumptions. 

One day later, where I mounted an expensive goog GPS again, the aircraft was flying very nicely again.

**Comment by LorenzMeier** [comment]
Its not that simple. You will crash if you continue to fly circles in one direction when you don't use GPS for attitude estimation. Fundamentally for all robots its garbage in = garbage out.

**Comment by severinleuenberger** [comment]
Circles would be ok, because that is not fundamentally a critical flight situation. But I had problem with pitch there as well, the plane was flying waves like on high waves on water. If the fmu alanyzes bad gps health, it should basically switch to STABILIZED mode. Just a suggestion.

**Comment by AndreasAntener** [comment]
Severin, the problem is that IF you fly circles continuously, you need GPS to correct attitude.

@LorenzMeier The estimators should at least not get into bad state if GPS fails (as long as you don't fly circles). I'm a little worried else that a multirotor will fall out of the sky when it flies underneath a tree.

**Comment by AndreasAntener** [comment]
@tumbili @LorenzMeier Something to consider in the current EKF iteration? I think this is still an issue.

**Comment by LorenzMeier** [comment]
We will look at this with the new estimator. Not before.

**Comment by tumbili** [comment]
@AndreasAntener @LorenzMeier Just did a test with SITL. Everything working smooth with the q estimator and inav, whereas the ekf just goes totally crazy. Complains all the time about excessive gyro offsets.

**Comment by tumbili** [comment]
Tried using the ekf with SITL for multirotors, there it segfaults.

**Comment by AndreasAntener** [comment]
@tumbili thanks already for testing :)

**Comment by tumbili** [comment]
Switching to ekf2!
