### ISSUE TITLE
SITL startup script

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2795]
@mcharleb @LorenzMeier At the moment we are trying to configure streams from the SITL startup script. This does not work because at that moment the mavlink instance is still waiting for the udp connection and thus is not functional yet.

**Comment by LorenzMeier** [comment]
This points to the need for the waiting to be implemented differently. There is no reason for it to reject stream config commands while its not streaming anything yet.

**Comment by tumbili** [comment]
@LorenzMeier I actually tried to shift the initialization of the udp further down where the instance already exists but then I don't get any parameters anymore in QGC. The streams work fine.

**Comment by LorenzMeier** [comment]
Is this fixed now?

**Comment by tumbili** [comment]
Yes, fixed with #2796
