### ISSUE TITLE
Make landed/inair state available to offboard computers

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2797]
AFAIK there is currently no MAVLink message that has a flag for this

**Comment by LorenzMeier** [comment]
Lets solve it as you suggested. Will update MAVLink here and in QGC once Travis is done.

**Comment by AndreasAntener** [comment]
Ok, will quickly recode the message impl so it's ready.

**Comment by AndreasAntener** [comment]
Fixed in #2950
