### ISSUE TITLE
Disable floating point exceptions for POSIX

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2802]

**Comment by mcharleb** [comment]
@tumbili What is this issue trying to resolve?

**Comment by tumbili** [comment]
@LorenzMeier Maybe you can explain better.

**Comment by LorenzMeier** [comment]
@mcharleb It seems that math exceptions exit the application in POSIX, rather than to continue the calculation with the invalid result. So far our model is to guard against math errors in the application logic, rather than to throw exceptions and exit.
