### ISSUE TITLE
Issues when using new QGC Joystick mode

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#2806]
QGC Joystick mode defaults to COM_RC_IN_MODE=1 which causes the follow problems:
- COM_RC_IN_MODE gets reset each time you reboot due to "param set COM_RC_IN_MODE 2" being the hill startup scripts. I don't think the firmware you be changing this parameter automatically. Let the user do it, either through param edit, or through QGC Joystick enable.
- COM_RC_IN_MODE=1 doesn't seem to ahve rc checks full cauterized. Example here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L536 causes vehicle to go into failsafe when using joystick. Not sure if there are others like this.

**Comment by LorenzMeier** [comment]
Fixed on master.
