### ISSUE TITLE
POSIX thread priority management

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2820]
@LorenzMeier I think for posix SCHED_PRIORITY_DEFAULT is already defined to be the max possible priority. So the statement "SCHED_PRIORITY_DEFAULT + 5" probably brakes it.
Should we define it differently?

**Comment by LorenzMeier** [comment]
That would be a bug of the define. Is should be == (max - min) / 2

**Comment by LorenzMeier** [comment]
Fixed in 9a30fb7.

**Comment by LorenzMeier** [comment]
Please re-test.

**Comment by tumbili** [comment]
@LorenzMeier Shouldn't it be min + (max - min) / 2 ?

**Comment by LorenzMeier** [comment]
yep, was too hasty. Fixing.

**Comment by LorenzMeier** [comment]
Done. Please re-test. Also need to look what min and max are.

**Comment by tumbili** [comment]
@LorenzMeier Works

**Comment by tumbili** [comment]
@LorenzMeier min is 1, max is 99

**Comment by LorenzMeier** [comment]
Its +- 127 for NuttX. So there is some work needed to replace the magic numbers with defines which correctly map the ranges. I've renamed this issue and left it open.
