### ISSUE TITLE
Adding a nex uorb topic issue

### ISSUE THREAD

**Issue by Royalcheese** [PX4/Firmware#2827]
Hello !
I tried to add a new uorb topic for new estimator application, following this tutorial : https://pixhawk.org/dev/add_uorb_topic

The first and following builds fail, with this error : 
'''/Firmware_last/Tools/genmsg/src/genmsg/template_tools.py", line 157, in generate_from_file
    assert False, "Uknown file extension for %s"%input_file
AssertionError: Uknown file extension for /home/clementperrousset/dev/Firmware_last/msg/px4_estimation.msg~
make: *** [generateuorbtopicheaders] Error 1'''

The build fail even removing the modification.. I guess the python path is kept in memory.
Any help would be great to solve this problem, thanks a lot in advance !

best regards,
RC

**Comment by LorenzMeier** [comment]
The error message says it all: The generator fell over the temporary file ending in ~. Just delete it. Feel free to send a patch to auto-delete backup files. Better switch to an editor not using them in the first place.
