### ISSUE TITLE
Takeoff issue using launch detection

### ISSUE THREAD

**Issue by lidbom** [PX4/Firmware#2829]
Unable to autonomously take off from launcher since the throttle goes to zero for a short period of time just after launch. The Pixhawk does seem to detect the acceleration from the catapult since it goes from the pre-throttle value to zero when sensing it is being launched. However, it does not take off (max throttle) unless measuring high enough wind speeds.  Have tried to re-calibrate, move and even replaced the airspeed sensor without being able to get rid of the behavior.  I've attached plot from the flight log of a typical case. 

Launch Detection parameter:
LAUN_CAT_A = 10
LAUN_CAT_T = 0.05
LAUN_CAT_MDEL = 0
LAUN_THR_PRE = 0.2

Default land detection parameters
 
![launch_plot](https://cloud.githubusercontent.com/assets/11291552/9758958/26caa636-56ea-11e5-830d-93dce4b31641.png)

**Comment by LorenzMeier** [comment]
We changed this a lot since, fixed.
