### ISSUE TITLE
Add uavcav bootloader output to travis

### ISSUE THREAD

**Issue by pkocmoud** [PX4/Firmware#2867]
Can someone modify the travis build script to include the uavcan booloaders in it?

**Comment by davids5** [comment]
For nuttx_next we need to include the bootloader bin files in the zip or have a tool to extract the bins from the px4 files.

**Comment by davids5** [comment]
We also need to consider adding the boot loader image to the application or creating bootloader update APP

**Comment by LorenzMeier** [comment]
Done.
