### ISSUE TITLE
[TECS] Pitch down when engaging alt ctrl for first time

### ISSUE THREAD

**Issue by mswingtra** [PX4/Firmware#2893]
During flight test, when altitude position control has been engaged airplane started to pitch down. The pitch integral reached high negative value at that time. We flew with master 3724947 and we used TECS fix https://github.com/PX4/Firmware/pull/2783
![pitchdown](https://cloud.githubusercontent.com/assets/13371589/10044681/286114ee-61fd-11e5-90c6-4558b6ad94a3.png)

Logging: http://logs.uaventure.com/view/Mz4PbA4F32q9ekaH85xudP

**Comment by tumbili** [comment]
@mswingtra Are you sure you are using the right version? We are logging the pitch and the thrust integrator for TECS but I can't see it in LogMuncher?

**Comment by mswingtra** [comment]
It seems that there has changed something in logging upstream, and since we update roughly once a month we did not have that change this time. We will have it by the next flight, so then we can provide more data. For now, either this issue can be kept open and we'll update it ASAP, or we'll reopen it in two-three weeks.

**Comment by AndreasAntener** [comment]
@tumbili we noticed a TECS init issue today, with latest master. We did 2 flights, when POSCTL was engaged the first time we had a huge pitch integrator:
![screen shot 2015-10-01 at 17 37 52](https://cloud.githubusercontent.com/assets/5750020/10225726/60556b3a-6864-11e5-828a-6e026d64bad6.png)
![screen shot 2015-10-01 at 17 38 00](https://cloud.githubusercontent.com/assets/5750020/10225730/62a2840e-6864-11e5-851f-e4529f9c15bb.png)
Log: http://logs.uaventure.com/view/oFMJ6Etfx2XsZA6zdLkypc

**Comment by tumbili** [comment]
@AndreasAntener Thanks for reporting! Seems like this issue is still present after all.

**Comment by LorenzMeier** [comment]
This here might be another instance of it:
http://logs.uaventure.com/view/CRzMpDoUvSshcFPY8wNXUA

**Comment by LorenzMeier** [comment]
So we should really have fixed this now. Patch is on master.
