### ISSUE TITLE
stable does not build after 485f0d03

### ISSUE THREAD

**Issue by v01d** [PX4/Firmware#2903]
I don't understand the commit, it appears to use "myoptarg" which is not defined and thus compilation fails.

**Comment by mcharleb** [comment]
"myoptarg" is usually used (local var) with px4_getopt (which is thread safe).

**Comment by v01d** [comment]
But, does it build for you?

**Comment by LorenzMeier** [comment]
I reverted on stable. Please pull

**Comment by mcharleb** [comment]
I am not sure what branch this is? Master? I have been working off cmake-2
for a while.

**Comment by v01d** [comment]
Thanks. I had reverted on my local clone and started building also.
