### ISSUE TITLE
INAV [UAVCAN?] GPS timeout

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#2911]
I tried getting some sort of a stable/flyable/reliable setup up today which wouldn't need debugging, flashed master to a fresh Pixhawk, running a Zubax GNSS over UAVCAN.
I currently keep getting messages of ```[inav] gps timeout``` spamming the shell and over mavlink. This seemed to be the behavior that occurs if another driver publishing on the same topic, but I stopped the native GPS driver, and the issue still persists. I think this is a regression introduced in the new UAVCAN updates. Could someone please confirm that they can reproduce this behavior (@Aperture-Laboratories @AndreasAntener @SimonWilks ) ? 
And while we're at it, could we maybe setup some form of a real test rig to test every commit against UAVCAN on a Pixhawk? Because honestly, I'm ready to spend *some* debugging time getting things to work, but this is getting frustrating to have have issues continuously with one thing or the other. I would probably now prefer to settle for classic serial GPS considering the amount of time sunk trying to get everything working.
On a side note, the UAVCAN external compass use seems to be malfunctioning as well, probably because of the CAN issue. I'm not sure how I can check what exactly is wrong, but the external compass is being ignored again.

**Comment by pavel-kirienko** [comment]
Hi Kabir, could you describe please your configuration, namely the value of `SYS_AUTOSTART`, whether you're using any additional init scripts, and the exact commit on master which triggers your timeouts. Thanks.

**Comment by mhkabir** [comment]
SYS_AUTOSTART - 10019
No additional scripts, just verbatim master @ 05a08252ff3f29b5ac684e97531a26a09e1310a9

**Comment by pavel-kirienko** [comment]
Can confirm, there was a regression in master. I'm looking into it.

**Comment by pavel-kirienko** [comment]
@LorenzMeier any chance we could extend the existing hardware testing suite with UAVCAN peripherals?

**Comment by LorenzMeier** [comment]
Yes, that's certainly possible. But more importantly we need an active and invested maintainer.

**Comment by mhkabir** [comment]
I'd like to be an active and interested maintainer :) Seeing as I'm
sinking enough time into this already, I'd be one of the happiest to
see this working out.

**Comment by LorenzMeier** [comment]
Hi Kabir,

A maintainer needs to go in, debug and fix things as well as providing tests to ensure quality. You have been a great tester and raised a lot of issues, but I'd like to encourage you to make the last step and move to provide fixes.

Thanks!

**Comment by pavel-kirienko** [comment]
Bisection shows that the regression appeared with https://github.com/PX4/Firmware/pull/2895. I wasn't able to find the root cause yet.

FYI @davids5

**Comment by pavel-kirienko** [comment]
https://github.com/PX4/Firmware/pull/2914

**Comment by mhkabir** [comment]
Closing this, since it's actually #2915 now. And timeouts are fixed by the current hacky state.

**Comment by pavel-kirienko** [comment]
Yesp, this one has actually been resolved with #2914.
