### ISSUE TITLE
FMUv1 does not boot 

### ISSUE THREAD

**Issue by friekopter** [PX4/Firmware#2921]
The FMUv1 does not currently boot in master and beta. It beeps and freezes.
It boots in stable.

**Comment by LorenzMeier** [comment]
Could you try this branch?
https://github.com/PX4/Firmware/pull/2967

It frees significant RAM.

**Comment by friekopter** [comment]
try as soon I can build again.

Date: Sat, 10 Oct 2015 08:08:39 -0700
