### ISSUE TITLE
SITL: Sometimes apps are not built

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2941]
At times I get a preflight error telling me that there is no gyro. This make sense because the "gyrosim" command does not even exist. To solve the problem you have to build again.

**Comment by tumbili** [comment]
@mcharleb Any idea what could be going on?

**Comment by mcharleb** [comment]
The apps.h file is likely not being regenerated.

**Comment by tumbili** [comment]
@mcharleb This always happens after a make clean.

**Comment by jgoppert** [comment]
Cmake build should be on master soon and doesn't have this problem.

**Comment by tumbili** [comment]
@jgoppert Yes, we solved this with @mcharleb today but we anyway don't need it anymore.
