### ISSUE TITLE
Mavlink Default  Streams sent to QGC for REAL TIME PLOTTING  Not working

### ISSUE THREAD

**Issue by RamDG** [PX4/Firmware#2943]
There are some default streams sent in "normal mode" 
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L1638.

but all of them are not available in QGC. I changed mode and still i am not able to get the other streams in QGC .

i want to stream "ATT_POS_MOCAP" and stop streaming  VFR_HUD 
where should i make changes in 
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp

i tried extras.txt and rc.usb method but nothing is happening ......even i removed all steamings from rc.usb  but i am still getting the default streams.

**Comment by LorenzMeier** [comment]
Outdated.
