### ISSUE TITLE
Parameters lost after reboot

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2946]
I flashed master, changed a parameter (sys_autostart) on the shell and executed `reboot`. I think the reboot happened before the auto save happened (at least before I saw the message). After the reboot all parameter values were gone.

I manage to do this quite often lately, especially on the PH2. There must be some corner case I constantly hit.. Maybe "during" the autosave?

**Comment by LorenzMeier** [comment]
Just tested this. If you power cycle during autosave there is nothing we can do. The same way as you cannot reset your computer while editing a file.
