### ISSUE TITLE
Buzzing when RC is not configured.

### ISSUE THREAD

**Issue by bostikforever** [PX4/Firmware#2963]
After configuring the sensors using QCGroundControl, PixFalcon starts to buzz. This buzzing stops once RC is configured.

The mode switch configuration check triggers the buzz.

**Comment by mhkabir** [comment]
@AndreasAntener Weren't you seeing something similar after the CMake switch?

**Comment by AndreasAntener** [comment]
@bostikforever was this with latest cmake master?

**Comment by LorenzMeier** [comment]
Yep, latest master.
