### ISSUE TITLE
Bad dependencies for parameters.xml

### ISSUE THREAD

**Issue by mcharleb** [PX4/Firmware#2972]
@jgoppert @LorenzMeier 
make posix
Then have a look at build_posix_sitl_simple/CMakeFiles/xml_gen.dir/build.make

parameters.xml depends on EVERY file under Firmware/src including all example directories, all of Eigen, all platform specific code, and src/lib/dspal. The path passed to the parameter generation script needs to be more specific.

These excess dependencies are breaking a build of qurt following a build for posix.

**Comment by dagar** [comment]
Would `*_params.c` catch everything?

**Comment by DonLakeFlyer** [comment]
That would seem dangerous to me. Param define macros can be anywhere.

**Comment by dagar** [comment]
I should have grepped first. Yes, they're all over the place.
modules/mavlink/mavlink.c, modules/fixedwing_backside/params.c, modules/sdlog2/sdlog2.c, etc

**Comment by DonLakeFlyer** [comment]
Is it worth the effort for the time saved to have dependencies on this?

**Comment by LorenzMeier** [comment]
well, the trivial fix is to exclude external libraries. Then we'll see what we end up with.

@mcharleb We need to get integration testing up and running for your platform, there is no other way to maintain this. Is there someone on your end with *significant* time available to get this up with me?

**Comment by LorenzMeier** [comment]
Fixed by @mcharleb - thanks!
