### ISSUE TITLE
Sensor-level HIL doesn't work anymore with X-Plane and master

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2977]
If I have sensor-level HIL enabled the HUD values "twitch" heavily when the plane sits still. The values spike to impossible values as soon as the plane starts moving. Almost like all the values are scaled by a large factor.

I can't say when this could have been introduced, had a long break from HIL. QGC version doesn't seem to matter (same with 2.7.1 and master).

**Comment by LorenzMeier** [comment]
Fixed in QGC and Firmware master. Thanks!
