### ISSUE TITLE
Improve TECS performance

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2980]
![auto_landing](https://cloud.githubusercontent.com/assets/7610489/10430143/dfb273f4-70fd-11e5-8c11-ac7c28233de1.png)

**Comment by tumbili** [comment]
The picture above shows altitude tracking before and during a landing phase.
@AndreasAntener @SimonWilks We could maybe investigate some time on tuning the TECS the next time we fly assuming attitude control is performing well. I hope we can reduce the overshoot a bit.
I will also look at the throttle problem on the ground today.

**Comment by LorenzMeier** [comment]
@tumbili First step is to tune the P and FF gains.
