### ISSUE TITLE
STM32F4Discovery Firmware Pinout for PWM

### ISSUE THREAD

**Issue by Pedro-Roque** [PX4/Firmware#2986]
Hello all,

I am looking for some explanation on PWM I/O for STM32F4Discovery Firmware port. The board.h is here:
https://github.com/PX4/Firmware/blob/master/nuttx-configs/px4-stm32f4discovery/include/board.h

I can't understand if the PWM channels on the firmware support all channels / pins on the hardware.

Best regards, and lots of kudos!

**Comment by Pedro-Roque** [comment]
Up @LorenzMeier

**Comment by LorenzMeier** [comment]
If you use a dev board you're supposed to know how to read OS / timer configs and schematics. Otherwise use a low-cost autopilot like the Pixfalcon, which will be less expensive than your dev board + sensor breakouts.

**Comment by Pedro-Roque** [comment]
@LorenzMeier , I know how to read those, but what I need to know is if the hardware timers are all available on the PX4 Firmware for this board.

**Comment by LorenzMeier** [comment]
src/drivers/px4fmu has all the details on PWM generation.
