### ISSUE TITLE
SITL master broken

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2987]
SITL is broken with the latest master, already a while ago.
I have confirmed that this has nothing to do with the noise addition to jMAVSim because I flew successfully with a stable version of the firmware which we used for the ELC workshop
https://github.com/PX4/Firmware/tree/stable_workshop_elc

**Comment by tumbili** [comment]
The problem seems to be related to the velocity estimate of the position controller.
If you have a look at the estimated velocities and the gps velocities you can see a huge mismatch.
Attitude estimation seems to be fine. If I remove the bias estimation (no compensation) then the quad flies much better but still the logs show that the estimation does not work properly.

Another thing that I've realized is that the loggs suggests gps data to come in at very irregular time instances and also with huge delays ( > 1s). However if I put a printf in the estimator where position gets updated I get a very regular 5Hz pattern or so.

**Comment by mswingtra** [comment]
Hi @tumbili, @devbharat asked me to post these here. He used attitude_estimator_ekf in SITL. Basically for most of the sessions estimated velocities and gps velocities are pretty similar to each other as it should be. 

SITL:
![sitl_x](https://cloud.githubusercontent.com/assets/13371589/10478543/ac6f4cbc-725e-11e5-8a48-c6c9f7b1fb94.png)
![sitl_y](https://cloud.githubusercontent.com/assets/13371589/10478548/afb655be-725e-11e5-9ac9-8d0c8dce6565.png)
![sitl_z](https://cloud.githubusercontent.com/assets/13371589/10478402/7d8d4be8-725d-11e5-9e30-ea73ae797e21.png)

**Comment by tumbili** [comment]
@devbharat @mswingtra Thats strange! I tried flying ekf with latest SITL master with latest jMAVSim and the quad just shakes around like crazy.

**Comment by devbharat** [comment]
That is what I had reported to you a few days ago, and also on the devcall. These logs (if fact any flying sitl log) are those done before we updated the subtree. 

You are correct about the shakes around like crazy, both jmavsim and gazebo.

**Comment by jgoppert** [comment]
I didn't realize we had sitl logging. Is this documented somewhere?  Does
sdlog2 just work?

**Comment by devbharat** [comment]
Yes, you can check the command in sitl init rcs. It's the same I think.

**Comment by tumbili** [comment]
![master_problem](https://cloud.githubusercontent.com/assets/7610489/10513899/fcf00c16-734a-11e5-8efd-f0224b18b791.png)

**Comment by tumbili** [comment]
@LorenzMeier @devbharat This is a log showing the difference between the broken master and working beta. I flew both in jMAVSim in manual, applying full thrust and at some point setting thrust to zero again. So the settings was almost the same in both flights. I have plotted most of the relevant data for velocity estimation in the z axis. All data looks consistent, I can't see anything abnormal. Note however, that the velocity estimate from the log of master is wrong (figure on the left side).

**Comment by tumbili** [comment]
@devbharat Fixed by this #3000  Can you do a test and close if the issue is fixed for you?

**Comment by devbharat** [comment]
Thanks, will check and close.

**Comment by tumbili** [comment]
I checked this using INAV and jMAVSim. Everything went well, POSCTRL, AUTO, ...
However, I tried using the ekf and that gives me a segfault.
