### ISSUE TITLE
SITL: double check logging app

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2992]
@LorenzMeier @mcharleb As mentioned in #2987 there might be a problem with logging.
There is also a problem with argument handling in posix, e.g this gives a segmentation fault:
sdlog2 start -r 100 -e -t -a -b 10

however, this works
sdlog2 start -r 100 -b 10 -e -t -a

A printf shows that with the first method the argument for the option "b" is empty. So it looks like there may be some limit of arguments to pass for posix.

**Comment by tumbili** [comment]
I haven't spent too much time on this but also I believe I haven't seen the effect of different logging rates in the logs.

**Comment by mcharleb** [comment]
@tumbili Yes, I think there is a limit in the parsed args. Is there a safe upper limit?

**Comment by LorenzMeier** [comment]
We need at least 8 args.

**Comment by LorenzMeier** [comment]
@mcharleb How many args are you supporting now?

**Comment by mcharleb** [comment]
src/platforms/posix/main.cpp:
```
vector<string> appargs(8);
```

**Comment by LorenzMeier** [comment]
Bumped it to 10, closing.
