### ISSUE TITLE
building master on windows is broken

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#2997]
After building and flashing the current master in windows I get this error in QGroundControl.

![screenshot 2015-10-14 14 19 36](https://cloud.githubusercontent.com/assets/84712/10493390/d80adf1a-727e-11e5-8fbd-4381d9c45f61.png)

**Comment by dagar** [comment]
These parameters are present in the generated build_px4fmu-v2_default\src\modules\param\px4_parameters.c and header.

**Comment by dagar** [comment]
It looks like a problem with the init scripts.

**Comment by LorenzMeier** [comment]
Yes, it requires a boot with the serial console enabled. I suspect that line ending issue on Windows.

**Comment by dagar** [comment]
I can't find any line ending differences in all of build_px4fmu-v2_default/tmp/ROMFS/px4fmu_common/init.d/, but rc.autostart is missing.
