### ISSUE TITLE
"lgamma" function not recognized under GCC 4.9.x

### ISSUE THREAD

**Issue by ir-jon** [PX4/Firmware#3022]
During build of target "make px4fmu-v2_default", build fails at ~60% of dependency scan. Error occurs in <random.h>, which is included in "Firmware/src/modules/ekf_att_pos_estimator/estimator_22states.cpp" via <algorithm.h> on Line 46. Tested on "arm-none-eabi-gcc 4.9.3 20150529 (release)" running under Ubuntu 14.04 LTS. Full error message below:

![error](https://cloud.githubusercontent.com/assets/13561055/10585776/dfc36fce-764d-11e5-988e-70445b60c663.png)

**Comment by v01d** [comment]
I found the same problem recently, after inadvertently updating my gcc-arm. I had 4.9 2014_q4 (which was working) and with 2015_q2 it was broken. I reverted and everything went back to normal. 
If it is not possible to fix the problem with this compiler, maybe it would be nice to report an error during building that this compiler is not supported.

**Comment by LorenzMeier** [comment]
A simple patch would have done 8).

**Comment by v01d** [comment]
Sorry, I'm lost, does that commit fix this?
