### ISSUE TITLE
Transplant PX4 to stm32f4discovery error

### ISSUE THREAD

**Issue by dongdongbh** [PX4/Firmware#3027]
Following https://pixhawk.org/modules/stm32f4discovery to Transplant PX4 to stm32f4discovery on windows,when i type "make archives",it prompt "No rule to make 'archives'. stop.".   Is there some makefile missed? How should solve this issue?

**Comment by lchish** [comment]
This is a duplicate of the bug I posted just before you #3026 you can work around this at the moment by checking out an older version of the git repository.

**Comment by LorenzMeier** [comment]
Closing this in favour of #3026.
