### ISSUE TITLE
Code stability in air on master

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3046]
@tumbili Unfortunately it looks like we have a stability issue which is isolated to fixed wing aircraft on master.

I suspect the stack size of the EKF estimator. I have adjusted it downward recently after intensely reviewing in-flight stack usage. But its possible there is a code path that I missed during that review. We need to come up with an approach to reproduce this on the bench.

**Comment by LorenzMeier** [comment]
We need to address this issue ASAP to make test-flights safer again: https://github.com/PX4/Firmware/issues/3003

**Comment by LorenzMeier** [comment]
I've pushed a hotfix in 7fd6d2d. That brings the stack back to the same level as on stable, and most likely fixes the issue.

**Comment by LorenzMeier** [comment]
In a crash log on stable the user had connected what looks like USB before he flew. We need to think about the implications of that.

**Comment by tumbili** [comment]
Some facts about the crash flight:
- I had the autopilot connected over usb before the flight (did not use telemetry)
- I did not check

**Comment by tumbili** [comment]
@LorenzMeier Notice also that the ekf is not working at all on SITL for fw whereas the other estimators work fine with the same setup.

**Comment by AndreasAntener** [comment]
Just flown master: http://logs.uaventure.com/view/bzijw7axp3j9Tpqk4sGtXb
Had no problems. My goal actually was to reproduce #2893 but the problem didn't occur.

**Comment by tumbili** [comment]
Closing, as test flights went without any problems.
