### ISSUE TITLE
Refresh preflight checks after joystick calibration

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3050]
@LorenzMeier  After calibrating the radio in SITL and setting the flight modes, you cannot arm the vehicle. This message appears in QGC:
Critical: command temporarily rejected: 400

You have to restart SITL in order to make it arm. So it seems like the commander does not redo the preflight checks after calibration.

**Comment by LorenzMeier** [comment]
This should be fixed in 8647854.

**Comment by tumbili** [comment]
Fixed in master, closing!
