### ISSUE TITLE
Gazebo sim does not connect to SITL on Mac

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3074]
Reproducable at 100% in Mac OS, to some extent on Linux.

**Comment by jgoppert** [comment]
I noticed on my ubuntu 14.04 laptop where the environmental variables are set in my .bashrc and I followed the original build direction that it starts up fine. While, on my ubuntu 14.04 desktop, where I didn't set the variables and am relying on the sitl_run.sh script to build the ros extension, that it fails to communicate with gazebo.

**Comment by tumbili** [comment]
For me gazebo just starts randomly. The command is executed but nothing happens.

**Comment by LorenzMeier** [comment]
Fixed.
