### ISSUE TITLE
Verify multicopter position control performance

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3094]
@tumbili This is to track the symptoms you've seen.

**Comment by tumbili** [comment]
Postion control performance in the GLOBAL y axis is bad, x axis is very good.

**Comment by LorenzMeier** [comment]
One particular observation is that some of the local -> global transformations are based on yaw setpoint, not current yaw. So the position control performance can depend on yaw tracking, which is not good.

**Comment by LorenzMeier** [comment]
The map projection / reprojection math should be checked. Did you fix any of that for fixed wing?

**Comment by tumbili** [comment]
No, I just introduced new functions, didn't change any of the existing ones.

**Comment by LorenzMeier** [comment]
That was not the question. The question is if the existing functions suffer from a similar deficiency.

**Comment by tumbili** [comment]
![pos_control_problem](https://cloud.githubusercontent.com/assets/7610489/10819457/785bfac4-7e48-11e5-93ce-125d7fbf7454.png)

**Comment by tumbili** [comment]
Could also be an estimation problem. This plot shows the derivative of the position (x,y) vs. the velocities. The errors in the y axis are much larger than the ones in the x axis.

**Comment by tumbili** [comment]
Ok, if you compare gps velocity with estimated velocity on both axes then the problem is obvious the estimation (possibly caused by false sensor data).

**Comment by tumbili** [comment]
Got it, the calculation of the lat, lon values in sitl_gazebo is not correct. It works for once direction because the longitude value of Zurich is relatively small.

**Comment by tumbili** [comment]
Solved, closing
