### ISSUE TITLE
Publish all distance sensors via MAVLink

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3097]
@mhkabir @LorenzMeier 
Since all the distance sensors are now publishing thanks to Kabir, #3085, I guess updating the `DISTANCE_SENSOR` message for MAVLink is now the next step. It should subscribe to every instance and publish all with a different ID. Receivers would then need to filter according to type and/or ID.

Will the instance IDs actually stay the same over boots?

For reference, related issues: https://github.com/PX4/Firmware/issues/2480, https://github.com/PX4/Firmware/issues/2297

**Comment by dagar** [comment]
Does this need additional mavlink DISTANCE_SENSOR messages or is publishing with different ids acceptable?

**Comment by mhkabir** [comment]
We already do this.
