### ISSUE TITLE
CMake Error at Firmware/CMakeLists.txt

### ISSUE THREAD

**Issue by zshn25** [PX4/Firmware#3099]
I followed the instructions from https://pixhawk.org/dev/ros/sitl

I created and configured the workspace manually. Everything went well untill the last step.

When I run catkin_make, it gave the following error messages

```
CMake Error at Firmware/CMakeLists.txt:158 (include):
  include could not find load file:

    configs/nuttx_px4fmu-v2_default


CMake Error at Firmware/CMakeLists.txt:170 (message):
  configs/nuttx_px4fmu-v2_default must implement px4_os_prebuild_targets


-- Configuring incomplete, errors occurred!
See also "/home/zee/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/zee/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

**Comment by killerlayup** [comment]
I have the same issue, pls help me

**Comment by devbharat** [comment]
Can you try the updated documentation at dev.px4.io ? Do you specifically want to compile the firmware for ros, or just want a general sitl setup(provided in the updated doc on the link above) ?

**Comment by zshn25** [comment]
I want to compile the Firmware for ROS which includes SITL too.

**Comment by killerlayup** [comment]
I want to compile the Firmware for ROS which includes SITL too.

**Comment by devbharat** [comment]
I am not sure, but I guess the ROS compilation has some issues right now, you could go to previous commit master before the CMake branch was merged in.

**Comment by blackcoder** [comment]
Same issue here, anyone knows what changes introduced this recently ?

**Comment by killerlayup** [comment]
Same issue here, anyone knows what changes introduced this recently ?

**Comment by jgoppert** [comment]
It still works. The ros build is tested on every commit. Try "make ros"

**Comment by killerlayup** [comment]
@jgoppert  you mean 'rosmake ?

**Comment by zshn25** [comment]
Still the same error. 
![screenshot from 2015-11-04 15 26 32](https://cloud.githubusercontent.com/assets/5270999/10934903/a2bd28b4-8308-11e5-9c76-b337aba76841.png)

Please help!!

**Comment by killerlayup** [comment]
@zshn25 
do you have free time? 
we can discuss on gitter.im if you want to

**Comment by killerlayup** [comment]
here is my gitter link:
https://gitter.im/killerlayup/jMAV

**Comment by jonbinney** [comment]
The basic problem I'm seeing with the ROS build (that gets run when `catkin_make` is called) is that `Firmware/CMakeLists.txt` assumes that CMAKE_SOURCE_DIR is the Firmware directory, but in the case of catkin_make, that isn't the case.

In a catkin workspaces, you typically have:
```
workspace_root_folder/
    src/
       /Firmware
       /Some_other_ROS_repo
       ....
```

Catkin seems to set CMAKE_SOURCE_DIR to `workspace_root_folder/src/`
Changing CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR gets me a bit further, but then it fails with:
```
CMake Error: File /home/jbinney/ws/px4/src/cmake/posix/apps.h_in does not exist.
CMake Error at Firmware/cmake/posix/px4_impl_posix.cmake:104 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  Firmware/src/firmware/posix/CMakeLists.txt:4 (px4_posix_generate_builtin_commands)


fatal: Not a git repository (or any of the parent directories): .git
-- GIT_DESC = 
CMake Error at Firmware/cmake/common/px4_base.cmake:710 (string):
  string sub-command SUBSTRING requires four arguments.
Call Stack (most recent call first):
  Firmware/CMakeLists.txt:332 (px4_create_git_hash_header)
```

**Comment by jonbinney** [comment]
I wasn't too clear in the previous comment; I was referring to chaging line https://github.com/PX4/Firmware/blob/b3bb8adbc5d3498bb95865820ec7a62bbf14c28e/CMakeLists.txt#L156 to replace CMAKE_SOURCE_DIR with CMAKE_CURRENT_SRC_DIR

**Comment by won13y** [comment]
catkin_make --cmake-args -DCONFIG=ros_sitl_simple

**Comment by brandonr49** [comment]
Has this been fixed?
I just had the same error zshn25 posted.

**Comment by brandonr49** [comment]
Nevermind. This was my mistake.

**Comment by LorenzMeier** [comment]
We changed the way how things work, so closing this.
