### ISSUE TITLE
This error is how so?

### ISSUE THREAD

**Issue by agnd** [PX4/Firmware#3103]
Last month, I directed pixhawk.org installed on a Web page tool chain, starting as usual, I can normally compiled firmware, but soon after the emergence of a variety of error messages about "Cmake" in compiling the new firmware, the latest error message tips like this:
$ make archives
Tools/check_cmake.sh: line 2: cmake: command not found
.....
But I did a search on pixhawk.org website to any Windows environment toolchain installation tutorial on Cmake all installation steps and there is no change from last month, I compile correctly since, how is this going?

**Comment by dagar** [comment]
Hi @agnd 
The PX4 build system now uses cmake, which you can download and install here.
https://cmake.org/download/

With the new cmake build system you just need to type `make` and it will do the equivalent of `make archives; make px4fmu-v2_default` in the old build system.
