### ISSUE TITLE
Position control with GPS and Optical Flow

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3108]
I think there is a problem using optical flow and gps with inav.
If the vehicle goes into position control without having a gps fix yet strange things can happen once you get a gps fix.
@ChristophTobler Can you provide the link to the log so that we can fix this problem?

**Comment by ChristophTobler** [comment]
yes, i'll do it tomorrow. I think the problem occurs if gps gets a connection, loses it and then connects again (-> not the same position anymore).

**Comment by ChristophTobler** [comment]
here it is: http://logs.uaventure.com/view/2j3HTNCAC5k42bnc5Gf72e

I guess it has to do with the gps init. I'll have a look at it tomorrow.
