### ISSUE TITLE
Detect takeoff using accel

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3116]
We should use the accel to trigger takeoffs faster for fixed wing.

**Comment by mhkabir** [comment]
Any reason we can't do this for multirotors as well? Because currently, even raising the throttle a bit gives false takeoff detections.

**Comment by LorenzMeier** [comment]
Fixed in #3184. Its not so trivial for multicopters since you don't throw them and therefore doesn't really apply.
