### ISSUE TITLE
git version reported by systemcmd "ver" is not necessarily correct

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#3130]

**Comment by kd0aij** [comment]
unable to reproduce

**Comment by kd0aij** [comment]
git version does not update when e.g. adding a new config file to ROMFS/.../init.d

**Comment by dagar** [comment]
I believe the git version is only set at configure time (running cmake). If you just want a quick fix you can touch any CMakeLists.txt and cmake will rerun the configure the next time any part of the build is invoked.

If you want it to always be correct then we need to change this https://github.com/PX4/Firmware/blob/master/cmake/common/px4_base.cmake#L702
to be a custom_command and then add dependencies.

**Comment by kd0aij** [comment]
Verified that both "touch CMakeLists.txt && make" is equivalent to "cmake build_px4fmu-v2_default && make", and both regenerate the git hash header. Since that adds less than 2 seconds to my compiles it works for me.

**Comment by kd0aij** [comment]
@dagar I've been reading about CMake, and it looks to me as though the new custom_command to generate build_git_version.h, will have to invoke a new CMake script which contains the body of the existing create_git_hash_header function. But I don't see how to specify the dependencies; what we want is to know whether the git hash has changed, but I guess we have to ask git about that. Would it be too crude to make it dependent on a non-existent target?

**Comment by davids5** [comment]
In the past this was solved by saving the SHA to a file and diff ing the contents. If it changed then the dependants were built.

**Comment by kd0aij** [comment]
@davids5 I don't understand. The problem is that the git SHA is written to a file only at configure time. Was "the past" before the switch to cmake?

**Comment by davids5** [comment]
Yes, before the switch to cmake.

**Comment by AndreasAntener** [comment]
Hey, could we just to 'rm build_git_version.h' somewhere in the cmake file? We should fix that again..

**Comment by kd0aij** [comment]
I think this needs to be addressed by a dev who knows cmake. My questions above have gone unanswered for 3 months, so it won't be me.

**Comment by LorenzMeier** [comment]
Fixed.

**Comment by kd0aij** [comment]
@LorenzMeier It would be nice to have a pointer to the fix for things like this.
