### ISSUE TITLE
RTL vector: Store takeoff vector, allow for correct return logic

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3137]
@AndreasAntener @tumbili I have added to MAVLink and our onboard struct a "takeoff vector" which points from the takeoff position into the direction of the takeoff. Right now the vector is not yet set or used.

The goal is that we have two RTL modes, depending on a setting: RTL flies to the end of the vector at some minimum altitude, then lands. That would take a multicopter to the ground the way it took off (e.g. if you took off at an angle to avoid a tree it would take off the same way). For a fixed wing it would land in the same approach path.

If you set a parameter, you could reconfigure it to land in the _opposite_ direction with the Z-component mirrored on the ground. That should bring you straight onto the runway threshold.

**Comment by dagar** [comment]
Are you referring to approach_{x, y, z} in HOME_POSITION? What were you thinking for actually setting the vector? In particular for FW runway or hand launch.
