### ISSUE TITLE
Check CONFIG_ARCH_BOARD_XXXXX constructs

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#3146]
The cmake conversion did not propagate the following 

ARCHDEFINES += -DCONFIG_ARCH_BOARD_$(CONFIG_BOARD) 

While this should be OK as long as we maintain our defconfig files (by hand) to ALWAYS have CONFIG_ARCH_BOARD_XXXXX (make oldconfig will break this, and I have to hand merge) it may be good to visit all the #if CONFIG_ARCH_BOARD_XXXXX constructs and ensure a compile time failure will result if missing.

**Comment by dagar** [comment]
Does this still need to be fixed?

**Comment by davids5** [comment]
This was fixed in the PR that expunged the #if CONFIG_ARCH_BOARD from the code base. I also added a tool to preserver the CONFIG_ARCH_BOARD etal through oldconfig and menuconfig for board configs not know to NuttX.

The remaining are 
![image](https://cloud.githubusercontent.com/assets/1945821/24928006/9909c8be-1e9c-11e7-9039-673493661cf7.png)
![image](https://cloud.githubusercontent.com/assets/1945821/24928038/ad7fb150-1e9c-11e7-863f-fff8ace48a5d.png)

Which all look OK for NuttX

I do not see 
CONFIG_ARCH_BOARD_RPI
CONFIG_ARCH_BOARD_SIM
set - If you can validate those we can close this.

**Comment by davids5** [comment]
Now that most all the CONFIG_ARCH_BOARD_XXXXX are gone! This is no longer an issue on 1.7
