### ISSUE TITLE
SITL broken on master

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#3147]
I have been unable to track it down yet, but somewhere in the following patch, we broke SITL

https://github.com/PX4/Firmware/compare/4345d8...b3554f

@tumbili, @LorenzMeier

**Comment by jgoppert** [comment]
I think this looks suspicious: https://github.com/PX4/Firmware/compare/4345d8...b3554f#diff-0da809c04c1d76a5907b7198828781edL825

The low pass filter is being removed.

**Comment by jgoppert** [comment]
I think I found it:

```c++
		/* Attitude rates for control state */
+		ctrl_state.roll_rate = _lp_roll_rate.apply(_rates(0));
+
+		ctrl_state.pitch_rate = _lp_pitch_rate.apply(_rates(1));
+
+		ctrl_state.roll_rate = _rates(2);  <------------- OOOPS
```

+1 for getting SITL running for travis.

**Comment by kd0aij** [comment]
Looks like that explains why I broke a few props today :)

**Comment by LorenzMeier** [comment]
Ugh, this was clearly a dev process fail we will debrief.

@kd0aij Would you mind re-checking if its fixed now?

**Comment by LorenzMeier** [comment]
If its not, beta holds a super recent but stable state.

**Comment by kd0aij** [comment]
beta flies OK. Will test master next.
Master is now OK on the QAV250.
