### ISSUE TITLE
Add gzserver to Jenkins, run integration tests

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3149]
TODOs
- [x] prepare new Docker containers with complete PX4 dev stack, build on Docker hub
- [x] get MAVROS tests to run on new SITL
- [x] increase volume size on sitl01
- [x] check why this segfault occurs: #3895 
- [x] configure 2 new jobs (analogue to the old ones) on Jenkins that use the new container
- [ ] get DroneKit mission check to run
- [x] document Docker and Jenkins setup in dev guide, copy whats still relevant from the old docs: https://pixhawk.org/dev/ros/sitl_ci_setup?s[]=sitl&s[]=testing
- [x] update build name reported by jenkins (continuous-integration/sitl/pr)
- [ ] push test logs to logmuncher
- [ ] during rostest standard out gets filled with up to 100mb non printable chars
- [ ] there seems to be an issue with rostest reporting, non unicode chars in xml files

**Comment by dagar** [comment]
Do you still want this?

**Comment by LorenzMeier** [comment]
Absolutely! We want to run auto-missions, either in Jenkins or Travis. A DroneKit script went into master which allows to command it and we just need the shell script architecture and CI system install routines now. Then we could do SITL flights on every commit.

**Comment by dagar** [comment]
Having used gazebo twice now I'm fairly confident travis-ci is not up to the task. What's the sitl01.dronetest.io hardware like?
If you install all the packages I can do the rest of the setup through the web interface.

**Comment by AndreasAntener** [comment]
@dagar 
sitl01.dronetest.io currently runs the multiplatform sim with ROS + Gazebo inside a Docker container. I think it can handle Gazebo + PX4.

Are you familiar with Docker? If we create a new Docker container for POSIX SITL we don't have to install packages :)
https://github.com/PX4/containers

**Comment by dagar** [comment]
My vague understanding of docker was that it solved a problem I managed to avoid by just sticking with the same flavour and version of linux everywhere. Maybe it's time to take a closer look.

**Comment by AndreasAntener** [comment]
;) I can help getting you started by adding a new container and give you access to Jenkins so you can have a look at how it's instrumented (it's not the perfect setup but functional).

**Comment by AndreasAntener** [comment]
@dagar : https://github.com/PX4/containers/pull/19

**Comment by AndreasAntener** [comment]
@dagar this is the branch with the updated tests and test run scripts: https://github.com/PX4/Firmware/tree/posix_sitl_ci
I added a TODO list in this issues description from what I think is still open. It would be awesome if we can get this going soon.

**Comment by dagar** [comment]
Opening a pull request to test jenkins.

**Comment by AndreasAntener** [comment]
POSIX SITL integration testing is merged to master, all PRs need to rebase. The old multiplatform ROS build is still functional but will not be tested anymore.
As soon as I have the dev guide update I'll close this and open new issues for the rest of the todos above.

**Comment by AndreasAntener** [comment]
Updated docs, added remaining issues.
