### ISSUE TITLE
Smart RTL

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3152]
@vilhjalmur89 It might be a good start for your implementation to first tackle a very basic problem: We want to log the current position and re-trace our steps back to some origin upon a command to return to the starting position.

Essentially I'm trying to pose a smaller problem so you can get up to speed on tools before we start to solve the global problem. Going through that process will ensure that what you build works on the real system. We can discuss this on Tuesday.

@tumbili Please track this and assist where needed on system integration.

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/pull/5745
