### ISSUE TITLE
UAVCAN parameter bridge shall not assume that every connected node implements configuration services

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/Firmware#3159]
Currently, if a node that does not implement configuration services is connected to the bus, the UAVCAN parameter bridge causes QGC to display a scary error box saying that it could not retrieve parameters and that the reason is probably a problem in the firmware.

The UAVCAN parameter bridge should detect nodes that do not implement configuration services and simply ignore them. The simplest way to handle it is to just give up retrieving parameters after the first unsuccessful attempt.

@bendyer

**Comment by LorenzMeier** [comment]
Closing as stale.
