### ISSUE TITLE
UAVCAN parameter bridge loses exactly one parameter

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/Firmware#3162]
@bendyer  The issue could also be caused by QGC, but that is much less likely.

I have tested on two different kinds of nodes, Zubax GNSS and PX4ESC. The former has 19 configuration parameters, but QGC lists only 18 (`gnss.warn_sats` is missing). The latter has 37 configuration parameters, but QGC lists only 36 (`light_index` is missing).

**Comment by bendyer** [comment]
Confirmed it's my fault. PR inbound.
