### ISSUE TITLE
Something about Mag calibration

### ISSUE THREAD

**Issue by lishidetiankong** [PX4/Firmware#3164]
Hi Lorenz Meier:
        I attempt to apply pixhawk Mag calibration method to calibrate LSM303d in order to obtain  an accurate course, however, every time there must be a deviation exist no matter how exact I do the calibration procedure when I compare it to electric gyrocompass.
        (1)  I find out that in path "../Firmware/Tools/Matlab/plot_mag.m" provide a method to calculate the offset of mag.  could you give me a set of sample data like mag0_raw3.csv...mag1_raw3.csv... mag0_cal3.csv...mag1_cal3.csv and so on.
          Or how could I obtain the sample date through pixhawk itself ??
        (2) I find out that pixhawk calibratie at most 3 mag only one time. for example, pixhawk use  accelerometer inside MPU6000 to calibrate mag inside LSM303D, because MPU6000 launth first.  so we did'nt use accelerometer  inside LSM303D to calibrate Mag inside LSM303D. I think this method simplify procedure of calibration though, but reduce accurtion of mag inside LSM303D.
         If I use accelerometer  inside LSM303D to calibrate Mag inside LSM303D, in theory, the accuration of LSM303D will improved or not ??
        This is my understand about LSM303D. if there is something error ,please point to me. 
         thank you very much!

**Comment by LorenzMeier** [comment]
Your assumption is not correct, the accel is not linked to the mag calibration quality, nor does it matter which accel is used with which mag.

1) The sample data is printed on the NSH console. You need to capture it there to run the Matlab script.

2) That is not correct. The accel is not used in the bias estimation.
