### ISSUE TITLE
gps invalid/inexistent -> green pulsing light remains

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#3173]
the light of the pixhawk remains green even when there is no gps signal any more (or invalid)
-> should turn blue again

**Comment by mhkabir** [comment]
Ah, It is actually checking for home position valid, no longer GPS valid, since : 
https://github.com/PX4/Firmware/commit/4de6012f12d94d3ca4e83b6cc2cf59e7b8461e96

**Comment by LorenzMeier** [comment]
Yuck. It should do both.

**Comment by LorenzMeier** [comment]
Check both

**Comment by mhkabir** [comment]
Sec, fixing.
