### ISSUE TITLE
UAVCAN sensors start up slowly

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/Firmware#3175]
Delay from power on to the point where UAVCAN sensor feeds are active varies between 4 and 9 seconds. The expected delay is approximately 5 seconds plus sensor initialization time (generally insignificant), so it is unclear where the extra 4 seconds of the worst case come from. The 5 second baseline is caused by the bootloader initialization delay.

Additional info at https://github.com/PX4/Firmware/pull/3171.

**Comment by mhkabir** [comment]
Can we not reduce the 5 second bootloader delay?

**Comment by pavel-kirienko** [comment]
Can't repro with the latest master and Zubax GNSS 2. @mhkabir please re-open if the issue still stands.
