### ISSUE TITLE
Significant rotation imprecision in get_rot_matrix()

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3179]
This function:
https://github.com/PX4/Firmware/blob/16b6b3caa2e152888bc942dbe723cfab3320d526/src/lib/conversion/rotation.cpp#L43-L51

Returns this for identity:

```
1.000, 0.000, -0.025,
0.000, 1.000, 0.011,
0.025, -0.011, 1.000
```

**Comment by tumbili** [comment]
@LorenzMeier I cannot reproduce this in SITL. Did you try this on NuttX?

**Comment by LorenzMeier** [comment]
yep, this was NuttX. So its probably the ARM Matrix stuff.

**Comment by tumbili** [comment]
'''
float cp = cosf(pitch);
		float sp = sinf(pitch);
		float sr = sinf(roll);
		float cr = cosf(roll);
		float sy = sinf(yaw);
		float cy = cosf(yaw);

		data[0][0] = cp * cy;
		data[0][1] = (sr * sp * cy) - (cr * sy);
		data[0][2] = (cr * sp * cy) + (sr * sy);
		data[1][0] = cp * sy;
		data[1][1] = (sr * sp * sy) + (cr * cy);
		data[1][2] = (cr * sp * sy) - (sr * cy);
		data[2][0] = -sp;
		data[2][1] = sr * cp;
		data[2][2] = cr * cp;
'''

This is how the function looks. Does that mean that the trigonometric functions are not performing well? Or am I missing something?

**Comment by tumbili** [comment]
I can't see any arm specific functions involved.

**Comment by LorenzMeier** [comment]
@pavel-kirienko I think you had a rotation offset set from the level calibration routine. All unit tests pass.
