### ISSUE TITLE
UAVCAN -Wfatal error

### ISSUE THREAD

**Issue by swatza** [PX4/Firmware#3190]
![terminal report](https://cloud.githubusercontent.com/assets/15744640/11185426/b954b9ca-8c4a-11e5-8938-e985cfff1db1.PNG)

Does anyone have a solution to the above problem?

**Comment by mhkabir** [comment]
What GCC version is this on?

**Comment by swatza** [comment]
Not on a linux machine: mingw32

**Comment by pavel-kirienko** [comment]
@swatza GCC version can be obtained by executing `gcc --version` (add necessary toolchain prefix before `gcc`, e.g. `arm-none-eabi-gcc`).

This issue should be fixed by https://github.com/PX4/Firmware/pull/3192, but I'm still curious about what GCC version triggers that error.

**Comment by swatza** [comment]
4.6.2

**Comment by pavel-kirienko** [comment]
I'm not sure if GCC 4.7 is still supported. The toolchain installation pages recommend 4.8.x. Anyway, you can use the patch I have linked above, it should fix the build even if you're keen to stick to 4.7. 

Feel free to re-open if it didn't help.
