### ISSUE TITLE
Issue when build Arducopter Firmware on Win 7

### ISSUE THREAD

**Issue by tuanback** [PX4/Firmware#3193]
make px4-v2 
// BUILDROOT=/e/Workspace/C++/ardupilot/Build.ArduCopter HAL_BOARD=HAL_BOARD_PX4 HAL_BOARD_SUBTYPE= TOOLCHAIN=NATIVE EXTRAFLAGS=-DGIT_VERSION="e18181e5" -DNUTTX_GIT_VERSION="d48fa307" -DPX4_GIT_VERSION="c3406165" -DUAVCAN=1
Checking modules
make[1]: Entering directory `/e/Workspace/C++/ardupilot/modules/PX4Firmware'
Skipping submodules. NUTTX_SRC is set to /e/Workspace/C++/ardupilot/modules/PX4NuttX/nuttx/
%% Configuring NuttX for px4fmu-v2
%% Exporting NuttX for px4fmu-v2
LN: include/arch to arch/arm/include
LN: include/arch/board to configs/px4fmu-v2/include
LN: include/arch/chip to arch/arm/include/stm32
LN: arch/arm/src/board to configs/px4fmu-v2/src
LN: arch/arm/src/chip to arch/arm/src/stm32
LN: include/apps to ../apps/include
Register: sercon
Register: serdis
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
Register: sysinfo
make[5]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
make[4]: Nothing to be done for `context'.
CC:  os_start.c
arm-none-eabi-gcc.exe: error: /cygdrive/c/px4/toolchain/msys/1.0/home/DoThanhTuan/.ccache/tmp/os_start.tmp.DoThanhTuan-PC.1200.i: No such file or directory
make[1]: Leaving directory `/e/Workspace/C++/ardupilot/modules/PX4Firmware'
arm-none-eabi-gcc.exe: fatal error: no input files
compilation terminated.
make[3]: *** [os_start.o] Error 1
make[2]: *** [sched/libsched.a] Error 2
make[1]: *** [/e/Workspace/C++/ardupilot/modules/PX4Firmware/Archives/px4fmu-v2.export] Error 2
make: *** [/e/Workspace/C++/ardupilot/modules/PX4Firmware/Archives/px4fmu-v2.export] Error 2

Could you guys please tell me how to solve this issue?

**Comment by LorenzMeier** [comment]
Please ask the APM dev team for APM support.
