### ISSUE TITLE
Tablet-only flight

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3198]
We should work towards demonstrating tablet-only flight for multicopters, VTOL and planes in AUTO. We should address all usability issue with that along the way.

Important configuration options to set:

  * COM_DISARM_LAND: Auto-disarm in seconds after landing. Set to 3 for testing

**Comment by tnedev** [comment]
We are now flying tablet only with a fixed wing and without lidar. No general stoppers except fragility of the takeoff/land with a few glitches. 
Hopefully I will be able to check the new improvements in a few hours.

**Comment by tnedev** [comment]
@LorenzMeier  I think a better switching between the different command interfaces will be very useful. Mainly that you could have your RC ON while using the tablet and fast switch to RC control if needed.

**Comment by LorenzMeier** [comment]
@tnedev Thanks, that's helpful feedback.

**Comment by LorenzMeier** [comment]
We have this now covered, you can fly with only a tablet.
