### ISSUE TITLE
mpu6000 driver:Investigate if 'test' function causes register checking to find a false faults 

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#3212]
While developing  https://github.com/PX4/Firmware/commit/51a7a51d9f0ed290596030d31b16e37ba4fd323d

I noticed the the register checking fails on a test command. 

This needs to be debugged

**Comment by dagar** [comment]
Still an issue?

**Comment by davids5** [comment]
I have not tested it on latest master.

**Comment by davids5** [comment]
@dagar - yet it was. See https://github.com/PX4/Firmware/pull/7024

**Comment by dagar** [comment]
Was mpu9250 copied from mpu6000. Any overlap here? https://github.com/PX4/Firmware/issues/5446

**Comment by davids5** [comment]
@dagar - yes - I would think it is the same issue. I did a pass on the 9250 in the PR, but I am not set up to test it. I asked @pkocmoud if he could give it a go. Do you have HW with the 9250 you can check it on?

**Comment by davids5** [comment]
@dagar, @LorenzMeier 

One more thing. The root cause was not the test. It was the reset after the test. Now there is a drop out of collecting samples during the test for ~30 ms. Will that be an issue?

**Comment by dagar** [comment]
Yes, I have a pixhawk 2.1 I could use for testing.
