### ISSUE TITLE
GPS spike detector

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3217]
We will need a GPS spike detector which does several things and probably can be a standalone thing like the terrain estimator. Maybe this is also something LPE already handles.

  * It detects excess acceleration suggested by GPS
  * It estimates the resulting velocity and position offset
  * It allows to remove that offset over some time as the GPS estimate slowly recovers / comes back

**Comment by LorenzMeier** [comment]
Log with spike happening:
http://logs.uaventure.com/view/Cp3XkZ2EAvjA4W4xi4sRDk#Velocity_PLOT

**Comment by kd0aij** [comment]
@LorenzMeier It looks to me as though the velocity plot is correct. Also, I'd appreciate an answer to the question I asked in https://github.com/PX4/Firmware/issues/2790#issuecomment-157434584; if I'm right that log exposes a bug in the altitude control logic.

**Comment by LorenzMeier** [comment]
@tumbili Could you have a look? Is this what you fixed here? https://github.com/PX4/Firmware/pull/3229

**Comment by LorenzMeier** [comment]
Will be done in EKF2.
