### ISSUE TITLE
mpu6000 & mpu9250 IOCTL and how/when the HW low pass filter is updated are different 

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#3240]
While adding the integration used on mpu6000 to the mpu9250  I noticed a difference in the mpu6000 & mpu9250 IOCTLs and how/when the HW low pass filter is updated. I believe the mpu9250 is a fork of the mpu6000. But the mpu9250 has a different way (IOCTL) of manipulating the HW LPF and when it is done. See https://github.com/PX4/Firmware/pull/3232 for more background.

Compare 
https://github.com/PX4/Firmware/blob/master/src/drivers/mpu9250/mpu9250.cpp#L1202-L1213
https://github.com/PX4/Firmware/blob/master/src/drivers/mpu9250/mpu9250.cpp#L1294-L1305

To 
https://github.com/PX4/Firmware/blob/master/src/drivers/mpu6000/mpu6000.cpp#L1361-L1368

These differences need to be resolved.

**Comment by LorenzMeier** [comment]
Fixed.
