### ISSUE TITLE
Multicopter mode switch: Review controller state

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3254]
It seems like multicopter mode switches can lead to wild swings in the attitude setpoint, potentially causing NaN values in the attitude controller. We have to understand where these come from.

**Comment by LorenzMeier** [comment]
@tumbili FYI

**Comment by tumbili** [comment]
At a first glance it looks like the desired acceleration in the mc pos controller is initialized to a large value causing the extreme attitude setpoint. Part of the calculation is a derivative which is suspicious.
Both logs show this behaviour so I hope we can easily reproduce this.

**Comment by scott-eddy** [comment]
This [diagram](https://github.com/PX4/Devguide/blob/master/book/images/diagrams/commander-flow-diagram.png) might be help the discussion.  The diagram was put in the devguide with the addition of Rattitude mode.

**Comment by tumbili** [comment]
Sorry, my comment was meant for another issue.

**Comment by LorenzMeier** [comment]
Fixed.
