### ISSUE TITLE
Control state broke vtol airspeed

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3264]
The VTOL stack has been using INAV as a default until now. The problem is that the attitude estimator_q does not write airspeed data into the control state topic which at the moment makes it unusable for fixed wing operation.
The question (until we get the new ekf in and running) is if we want to switch to using the ekf for VTOL or if we want the attitude estimator q to subscribe to airspeed and put the value into the control state topic?
@LorenzMeier @yyassa

**Comment by yyassa** [comment]
What about channeling the raw pitot measurement over inav and publishing it from there as ctrl_state.airspeed? (as the inav is not estimating wind)

**Comment by tumbili** [comment]
@yyassa I think that's what we're going to do but we need to do it in the q estimator

**Comment by yyassa** [comment]
Sure, I can do the fix quickly.

General question: As far as I understand you cannot publish  part of a topic from one module and the other part from a different one?

**Comment by LorenzMeier** [comment]
No, you can't.
