### ISSUE TITLE
Sudden magnetic declination change screws up yaw estimation

### ISSUE THREAD

**Issue by muharred** [PX4/Firmware#3270]
On init and in cases where magnetic declination changes considerably in one leap attitude estimation by yaw slowly reacts to the change and during the time accumulates false gyro bias (because mag angle adds declination instantly, but gyro doesn't register any rotation). This bias, in turn causes yaw estimation to overshoot the new level and can cause unstable yaw for more than a minute after init.
Steps to reproduce: boot with instant logging enabled and with noticeable mag declination stored in ATT_MAG_DECL parameter. Wait 1.5 minute, modify the parameter or start fake GPS. Notice slow yaw reaction with overshoot.

Screenshot comparing raw mag angle (with NED projection) and yaw estimation (declination was changed from 6.0979 to -6.0979 and back and then fake GPS was turned on):

![yawvsmag](https://cloud.githubusercontent.com/assets/8501086/11407219/1667f1ce-93ba-11e5-9037-a841534d5f76.png)

**Comment by LorenzMeier** [comment]
Thanks for reporting! The fix will be to reset the filter state to the current roll, pitch and heading (based on the mag) once the declination parameter changes.

**Comment by muharred** [comment]
I've added pull request with proposed fix that seemed to do the trick for me.

**Comment by tumbili** [comment]
Closing, fixed in #3271
