### ISSUE TITLE
How to debug using eclipse with J-link and new cmake firmware 

### ISSUE THREAD

**Issue by dongdongbh** [PX4/Firmware#3293]
I want to debug the firmware using eclipse,with j-link SWD mode,then I follow the tutorial on :https://pixhawk.org/dev/jtag/segger_j-link,and where there load app with "firmware.elf",but in new cmake firmware,there is no "firmware.elf" file,there just "firmware_nuttx.bin",and it can't use when i try.my "J-Link GDB Server" is OK in SWD mode.

And how to debug in eclipse with new firmware?

**Comment by dongdongbh** [comment]
How to get ".elf" file?

**Comment by davids5** [comment]
The firmware_nuttx file with no extension is the elf file
