### ISSUE TITLE
ICM20608 'sefltest' registers different to MPU6000

### ISSUE THREAD

**Issue by ksschwabe** [PX4/Firmware#3294]
@tridge 

I see that you are currently making changes to the MPU6000 driver to make it compatible with the ICM20608 MPU. Although most of the registers are the same for reading out the data, there are differences in the self-test registers. I think if you currently run `mpu6000 factorytest` with the ICM20608 chip it will "fail".

**Comment by LorenzMeier** [comment]
@davids5 Medium priority for your queue.

**Comment by LorenzMeier** [comment]
We're using the sensor, fixed.
