### ISSUE TITLE
Prepend task name to PX4_WARN() on all OS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3298]
@mcharleb here is how to get the thread name (I will merge a change to master in a sec which sets it in px4_task_spawn). It would be great if we could rework PX4_INFO and warn to always prepend the thread name since that makes the error messages substantially more informative.

The same would be good for PX4_WARN() for NuttX, since warnx() does do that and its the main reason we haven't cut over the rest of the system to PX4_WARN().

```C
const unsigned NAMELEN = 32;
char thread_name[NAMELEN] = {};
(void)pthread_getname_np(pthread_self(), thread_name, NAMELEN);
PX4_WARN("%s: error message abc", thread_name);
```

**Comment by julianoes** [comment]
Done as part of #4709.
