### ISSUE TITLE
The function meaning of `reset_pos_sp()` and `reset_altsp()` in mc_pos_control_main.cpp

### ISSUE THREAD

**Issue by weiweikong** [PX4/Firmware#3306]
After reading the `mc_pos_control_main.cpp`, I did not total understand the meaning of `reset_pos_sp() `and `reset_alt_sp()` functions. According to the comments in the project, it seems to reset the position setpoint and altitude setpoint. 

The codes are,
https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L634-L656.

```
...
void
MulticopterPositionControl::reset_pos_sp()
{
	if (_reset_pos_sp) {
		_reset_pos_sp = false;
		/* shift position setpoint to make attitude setpoint continuous */
		_pos_sp(0) = _pos(0) + (_vel(0) - PX4_R(_att_sp.R_body, 0, 2) * _att_sp.thrust / _params.vel_p(0)
					- _params.vel_ff(0) * _vel_sp(0)) / _params.pos_p(0);
		_pos_sp(1) = _pos(1) + (_vel(1) - PX4_R(_att_sp.R_body, 1, 2) * _att_sp.thrust / _params.vel_p(1)
					- _params.vel_ff(1) * _vel_sp(1)) / _params.pos_p(1);
		mavlink_log_info(_mavlink_fd, "[mpc] reset pos sp: %d, %d", (int)_pos_sp(0), (int)_pos_sp(1));
	}
}

void
MulticopterPositionControl::reset_alt_sp()
{
	if (_reset_alt_sp) {
		_reset_alt_sp = false;
		_pos_sp(2) = _pos(2) + (_vel(2) - _params.vel_ff(2) * _vel_sp(2)) / _params.pos_p(2);
		mavlink_log_info(_mavlink_fd, "[mpc] reset alt sp: %d", -(int)_pos_sp(2));
	}
}
...
```

Trying to write the equation from the code, I still not catch the point. The equation was shown as the following image.

![image](https://cloud.githubusercontent.com/assets/2463397/11517902/f1442ea4-98c7-11e5-89b7-f67807c76d0d.png)

**Comment by LorenzMeier** [comment]
Issues are not suitable for questions.
