### ISSUE TITLE
Pixhawk inconsistent boot-up behavior with master and beta

### ISSUE THREAD

**Issue by aharmat** [PX4/Firmware#3316]
We're running pixhawk with PX4, using stable firmware the boot-up behaves as expected. With both master and beta firmware, one of three things happens:

1. Boot-up behaves as normal
2. Pixhawk boots normally (based on noise), one or more ESCs keep beeping with motors twitching
3. Pixhawk emits a continuous tone, one or more ESCs keep beeping with motors twitching.

There is no apparent pattern to these behaviors, cycling the power eventually gets us to normal boot-up. The quad flies normally after that. Any idea what's wrong?

This issue seems similar to #2921, but the solution referenced there (#2967) has been merged into master over a month ago.

Thanks,

Adam

**Comment by LorenzMeier** [comment]
We're not aware of any recent issues - what vehicle configuration are you using? Are you flashing via QGroundControl?

**Comment by aharmat** [comment]
We are using a hexacopter + configuration, flashing via QGroundControl. Does this sound like an ESC calibration issue?

**Comment by LorenzMeier** [comment]
Outdated.
