### ISSUE TITLE
MAV_CMD_GET_HOME_POSITION sets up stream instead of sending single home position

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3330]
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L317

This seems incorrect. APM Stack sends a single home position in response to this command. Spec doesn't say anything about starting a stream of home positions.

**Comment by LorenzMeier** [comment]
That's intended to avoid comm drops creating issues. Can change if QGC side has retransmit implemented.
