### ISSUE TITLE
Mission: Takeoff then Waypoint, vehicle skips takeoff location

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3332]
- Run from QGC with master SITL
- Load mission file
- Send to vehicle
- Back to Fly view
- Change flight mode to Mission
- Arm

Two problems:
- At the point you change the flight mode to Mission the vehicle sends an error level mavlink message about takeoff. This happens before you arm.
- When you arm, the vehicle takes off and heads in the direction between the two waypoints. The at some point it changes trajectory towards the final waypoint, skipping the takeoff waypoint entirely.

If you run a mission with just a single takeoff item it works correctly and the vehicle flies to the takeoff location.

[TakeoffBug.px4.mission.txt](https://github.com/PX4/Firmware/files/52738/TakeoffBug.px4.mission.txt)

**Comment by LorenzMeier** [comment]
Fixed by @sanderux.
