### ISSUE TITLE
NuttX read() API on serial ports

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3335]
@davids5 I experienced a weird situation on non-blocking reads from a serial port in a construct like this:

``` C

int ret;

do {
  ret = read(fd, &buf[0], maxlen);
} while (ret > 0);
```

Either I'm terribly confused and don't see my structural mistake here or the port kept returning ret > 0, which resulted in the loop never returning.

**Comment by davids5** [comment]
I am assuming this is a simplified example (no buffer concatenation etc or errno checking) and that the use of poll (select) was not considered...

I am thinking there might be something else affecting this (stack corruption),  Where is the code? I will step it and see.
