### ISSUE TITLE
Building failed ..... wrong include path?

### ISSUE THREAD

**Issue by ChaoyuChen** [PX4/Firmware#3357]
Hello,

I used a PC with ubuntu 15.10 desktop as my building machine, and then followed the steps on the [GitBook](http://dev.px4.io/starting-installing-linux.html) to set up the building environment -- except  `gcc-arm-none-eabi`. Because `apt-get` cannot find the version *4.8.3-18ubuntu2+12*, I download the `.deb` file from https://launchpad.net/ubuntu/wily/amd64/gcc-arm-none-eabi/4.8.3-18ubuntu2+12 and used `dpkg -i` to install it manually. The following is the version information:

>$ arm-none-eabi-gcc --version
> arm-none-eabi-gcc (4.8.3-18ubuntu2+12) 4.8.3
> Copyright (C) 2013 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

However, my building was failed. The error message was

> [ 23%] Building CXX object src/drivers/mb12xx/CMakeFiles/drivers__mb12xx.dir/mb12xx.cpp.obj
> /Firmware/src/drivers/mb12xx/mb12xx.cpp:58:18: fatal error: vector: No such file or directory
> #include <vector>
>                   ^
> compilation terminated.
>src/drivers/mb12xx/CMakeFiles/drivers__mb12xx.dir/build.make:54: recipe for target 'src/drivers/mb12xx/CMakeFiles/drivers__mb12xx.dir/mb12xx.cpp.obj' failed

The symptom`vector: No such file or directory` looks due to wrong include path setting, because `vector` is a header file included by `gcc-arm-none-eabi`. I am wondering whether I missed or mixed up anything.

By the way, a similar issue was posted at another site (https://groups.google.com/forum/embed/#!topic/px4users/Df4VpKbeCQM), but on that page the issue is still hanging up there. Please help us to solve this problem, thanks!

**Comment by LorenzMeier** [comment]
Uninstall that version and install this: ```sudo apt-get install gcc-arm-none-eabi```. Docs will be updated.
