### ISSUE TITLE
Question regarding dynamics model in BlockLocalPositionEstimator

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#3370]
Might be that I do not understand all the math or the code behind BlockLocalPositionEstimator. Maybe one of you guys can help me out here with a short answer. As far as I understood, BlockLocalPositionEstimator uses accelerator data to update the covariance matrix by speeds, not integrating to position. Is that assumption correct?

**Comment by mhkabir** [comment]
@jgoppert

**Comment by jgoppert** [comment]
@ecmnet The acceleration data is used to predict the evolution of velocity and position, via integration. The position and velocity are then corrected by other sensors.

**Comment by ecmnet** [comment]
@jgoppert Thank you for the info. I clearly understand the integration of accelerator data to velocity in BlockLocalPositionEstimator; but I am curious how the integration to position should work...

**Comment by LorenzMeier** [comment]
Outdated.
