### ISSUE TITLE
Allow small VTOL operation without airspeed sensor

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3372]
This is highly wanted and probably needed for the Caipiroshka.

**Comment by sanderux** [comment]
@tumbili 
Would this not be inherent when VT_ARSP_TRANS is set to 0? 
https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/tailsitter.cpp#L180

**Comment by melisab** [comment]
I was wondering if replacing airspeed sensor means that we can rely on mc altitude control to see if the plane has achieved a sufficient lift to safely declare that it's in FW mode.

**Comment by SimonWilks** [comment]
Now that's an interesting idea :) I wonder if this could at least be used as a sanity check for airspeed failure detection ( #3746  ).

**Comment by sanderux** [comment]
@tumbili @AndreasAntener could we safely increase the altitude setpoint for FW by something significant and check if transition has occurred by reaching this altitude? as @SimonWilks stated, this could serve for both the lack of, and a malfunctioning airspeed sensor.

**Comment by tumbili** [comment]
@LorenzMeier Is this about allowing at least to hover or about allowing both regimes?
We could just use gps speed for the transitions or open loop based on time.

**Comment by sanderux** [comment]
@simonwilks did you mean to close this issue?

**Comment by SimonWilks** [comment]
No. Sorry ;)

**Comment by LorenzMeier** [comment]
Full operation of course. A VTOL in hover only is just a very bad quad.

**Comment by tumbili** [comment]
Implemented in #4770
