### ISSUE TITLE
Revisit motor output mapping for VTOL

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3373]
Right now we use exclusively the MAIN outputs for the multi rotor motors and AUX for the servos. We should move that to everything on main with two different output rates on the Caipiroshka so we can effectively leverage Pixracer.

http://dev.px4.io/hardware-pixracer.html

**Comment by sanderux** [comment]
Until this is done, perhaps add "&& _armed->armed" to
https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/standard.cpp#L303

this would make the standard VTOL a bit safer. If you want i can field test this.

**Comment by LorenzMeier** [comment]
That would be much appreciated!

**Comment by sanderux** [comment]
Tested, works.
PR https://github.com/PX4/Firmware/pull/3392

**Comment by LorenzMeier** [comment]
Fixed.
