### ISSUE TITLE
Intermittent failure to generate PWM signals after arming

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#3374]
Observed with both AUAV-X2 in a VTOL config, and on PixRacer quadcopter. Sometimes motors don't spin after arming. Verified no PWM output from PixRacer when this occurs.

**Comment by LorenzMeier** [comment]
Do you have safety disabled on the X2?

**Comment by kd0aij** [comment]
No the X2 has a safety switch. Can't reproduce the problem on my PixRacer with either beta or master. @pkcomoud says his motors never start on beta, intermittent on master.

**Comment by LorenzMeier** [comment]
Since master == beta right now that report is confusing. Probably some init related issue in the FMU driver.

**Comment by kd0aij** [comment]
Re: https://gitter.im/PX4/Firmware?at=5676be13f31bbe91555b647d
My testing shows the same PWM output on bootup with radio on and off. Signal goes high for about 300msec before pulsetrain begins. Perhaps it should initialize to low?

**Comment by pkocmoud** [comment]
I think we had a user with this issue. I was told that was resolved by a code change by Lorenz. Should this be closed?

**Comment by kd0aij** [comment]
I haven't flown the X2 VTOL in a while, and since you're not seeing it anymore will close this for now.
