### ISSUE TITLE
Rate-limit altitude range (prevent steps)

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3384]
We should rate-limit the altitude change similar to the horizontal acceleration to avoid sudden throttle responses. A slight low-pass with very little phase delay on the user input might be enough (also on the X / Y direction, since we still have an initial step).

**Comment by AndreasAntener** [comment]
This got implemented via https://github.com/PX4/Firmware/commit/7817924aeff4862b89356216df84a021fb9443b3
