### ISSUE TITLE
MC: Takeoff always results in slight yaw in SITL

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3394]
@thomasgubler Is this related to your yaw fix? I checked and its not a declination issue - the yaw setpoint is non-zero on takeoff waypoints, which I don't understand yet fully.

**Comment by thomasgubler** [comment]
Unless you are flying with MIS_YAWMODE != 0 this is not related.

**Comment by LorenzMeier** [comment]
We are by default facing the next waypoint.

**Comment by thomasgubler** [comment]
ah ok I see, MIS_YAWMODE == 1 per default. Then this could be related. Although I did not touch the takeoff behaviour (which is "do nothing" https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L531 )

**Comment by thomasgubler** [comment]
For me it's non-zero because of https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1634

**Comment by LorenzMeier** [comment]
Fixed.
