### ISSUE TITLE
VTOL ALTCTL transition: no throttle value

### ISSUE THREAD

**Issue by melisab** [PX4/Firmware#3400]
After completing transition in standard VTOL in ALTCTL mode the plane started dropping and pilot cannot control the fw throttle for awhile.

http://logs.uaventure.com/view/ZEkEPTKrDpNocfQrvUp7h6
http://logs.uaventure.com/view/gKmtA9YSR7jc9quZ6RSSoX

**Comment by LorenzMeier** [comment]
Thanks for sharing these logs! We are looking into these.

**Comment by LorenzMeier** [comment]
@tumbili Initial analysis shows that the system indeed commanded zero throttle. I'm not sure yet why.

**Comment by melisab** [comment]
Just want to add another thing from my observation. In ALTCTL the plane also cannot maintain its altitude during transition; i.e. mc throttle shot up during transition.

**Comment by melisab** [comment]
Hi! I started flying the same VTOL plane again. Encounter the same issue in  POS CTL. I was wondering if the issue has been found out with recent firmware? #11628
