### ISSUE TITLE
VTOL: Support transition command for missions

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3414]
@AndreasAntener How hard would it be to finish that off? I think it has been pending for some time and shouldn't be a major hurdle.

**Comment by LorenzMeier** [comment]
Seems to be quite popular these days: https://github.com/mavlink/mavlink/pull/487

**Comment by sanderux** [comment]
@tumbili I have mission transitioning in SITL, see https://github.com/PX4/Firmware/pull/3426
the transition itself is still weird. I think there might be a problem in https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_type.cpp#L81 as i do get the failure text during transition.
