### ISSUE TITLE
Firmware make error appears： region Flash overflowed by 8696 bytes

### ISSUE THREAD

**Issue by jamesdeep** [PX4/Firmware#3417]
![qq 20160102194134](https://cloud.githubusercontent.com/assets/14329360/12074366/1f008e48-b18a-11e5-9440-73863f257a4e.png)

I make the Firmware Project accroding to the video shown in the official website(https://pixhawk.org/dev/toolchain_installation_win) ,and then problems appears after make,just as the image shown above ,can you help me out of the problem?I have tried these twice,the result is same.THX.
PS:WIN7

**Comment by LorenzMeier** [comment]
Fixed in ba90ba14b0dcbcf4de425db4254662ce93e3e965.
