### ISSUE TITLE
mavros can't communicate to jmavsim(DrTon version) on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by lishidetiankong** [PX4/Firmware#3421]
Hello developers of pixhawk:
      Now, I try to use hil mode to test px4 hign level logic, so I want to use mavros and jmavsim together with pixhawk hardware to implement the test process, and monitor with QGC2.8.0
     (1)  Firstly,  I use jmavsim and pixhawk without mavros, this process work successfully, I can use RC control pixhawk and fly in the jmavsim. 
     
     (2)Secondly, I test connect pixhawk to mavros without jmavsim(I modify px4.launch as below two line shown
	<arg name="fcu_url" default="/dev/ttyACM0:57600" />
	<arg name="gcs_url" default="udp://:14556@127.0.0.1:14550" />)
       And this process work successfully too, because of no jmavsim paticipate in, so I can't watch how px4 fly ,Only could watch some message using QGC
        When i listen to the process usding"rostopic echo /mavros/imu/data" , I can see the data fresh on the screen.
      
     (3)Next, I want implent this structure
                                  setpoint_demo.py(optional)
              QGC < - > ROS/Mavros < - > JMAVSim < - > Pixhawk(hardware)
      But , I meet a key problem, that is mavros can't communicate to jmavsim(DrTon version)
      when I input : 
ubuntu@ubuntu-Aspire-VN7-592G:~/catkin_ws$  roslaunch mavros px4.launch

I use rostopic echo -n1 /diagnostics  on anthor console, MAVROS tell me no connection  _* ~ *_ 

MAVROS tell me below , can't  get heartbeat message, and wait forever

ubuntu@ubuntu-Aspire-VN7-592G:~/catkin_ws$  roslaunch mavros px4.launch
... logging to /home/peng/.ros/log/15efc30a-b1d0-11e5-9ba4-3065ec8cddd0/roslaunch-peng-Aspire-VN7-592G-12581.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://peng-Aspire-VN7-592G:53732/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0

...

[ INFO] [1451794401.292824391]: Plugin vision_speed_estimate loaded and initialized
[ INFO] [1451794401.305226938]: Plugin waypoint loaded and initialized
[ INFO] [1451794401.305368425]: Autostarting mavlink via USB on PX4
[ INFO] [1451794401.305445442]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1451794401.305479635]: Built-in MAVLink dialect: ardupilotmega
[ INFO] [1451794401.305518167]: MAVROS started. MY ID [1, 240], TARGET ID [1, 1]

Can anyone help me!!! Thank you very much

**Comment by lishidetiankong** [comment]
I can make sure the target ID of mavlink on the pixhawk is the same with px4.launch of mavros

**Comment by LorenzMeier** [comment]
Please follow these instructions:
http://dev.px4.io/simulation-ros-interface.html

And make sure to use latest PX4 master.
