### ISSUE TITLE
Add support for ground-truth attitude to Gazebo SITL

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#3424]
We should be able to get a direct ground-truth attitude from the simulation.

**Comment by mhkabir** [comment]
@LorenzMeier Could you quickly outline what's to be done for this one? I'm happy to take this up and implement it. We especially need this for our satellite simulation.

**Comment by LorenzMeier** [comment]
It should send http://mavlink.org/messages/common#ATT_POS_MOCAP and publish that onboard. The vehicle should send this in turn back to the GCS.

**Comment by mhkabir** [comment]
@LorenzMeier OK. Where do I grab the attitude data from the sim?

**Comment by LorenzMeier** [comment]
there is a mavlink plugin CPP file in the plugin dir. You'll see that everything is sent there. Just add it there.

**Comment by LorenzMeier** [comment]
Done!
