### ISSUE TITLE
Add all supported frames to documentation

### ISSUE THREAD

**Issue by DavidsWONG** [PX4/Firmware#3428]
why i can't find quad x8？
how can i add it myself？
thanks，

**Comment by DavidsWONG** [comment]
also I can not find Y6 frame！how can i do it myself。the Documentation of pixhawk.org show none tip for it.

**Comment by LorenzMeier** [comment]
Just scroll down in QGroundControl. What you're looking for is the Octarotor X coaxial.

**Comment by LorenzMeier** [comment]
Need to add all frames to docs.

**Comment by DavidsWONG** [comment]
@LorenzMeier   
I found 19 frames of QGroundControl 2.8.0. But I can't found the frame named Octarotor X coaxial.

**Comment by SimonWilks** [comment]
@DavidsWONG do you not see this one in your selection? The image of the plane that goes along with it is obviously wrong but that's the one you'll need.
![coax_selection](https://cloud.githubusercontent.com/assets/10983630/12110098/f45f7720-b388-11e5-80d2-930845a84ac3.png)

**Comment by LorenzMeier** [comment]
Fixed through QGC's auto-generated list now.
