### ISSUE TITLE
VTOL: Enforce transition switch

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3432]
AUX1 check

**Comment by LorenzMeier** [comment]
@tumbili Check the switch here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.cpp#L524

**Comment by sanderux** [comment]
@LorenzMeier some people might not have a transition switch configured when tuning the quad. (setting a knob for PID tuning). Or have another reason for not assigning the switch.

**Comment by sanderux** [comment]
@AndreasAntener considering my comment; yes or no on this?

**Comment by AndreasAntener** [comment]
On a different matter: we should make this an actual switch (instead of an aux channel) and evaluate it also in the RC main state handling. At the moment the flight modes don't get re-evaluated when you flick the transition switch.

**Comment by AndreasAntener** [comment]
And I don't think it's much of a deal breaker if you need this switch. People who do PID tuning with a knob sure have a 16chan radio

**Comment by LorenzMeier** [comment]
Done.
