### ISSUE TITLE
Position control is not moving in the direction it's pointing

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3447]
I haven't analyzed it yet, but we had this on multiple quads now. If I just give pitch input forwards in POSCTL it also drifts to the left. When going backwards it drifts the same amount back.

Occurred here in the end as well: http://logs.uaventure.com/view/ypvNzJezx2hifXsHeS22uD

**Comment by estechnical** [comment]
I think I have also seen this behaviour and wondered whether it was something I have done wrong. I have never seen any evidence other than "that looks like it's flying a little bit sideways" when it should be going forwards.

**Comment by LorenzMeier** [comment]
That's not present with ECL / EKF2.
