### ISSUE TITLE
nuttx_next_cmake branch doesn't compile (gcc 4.9.3)

### ISSUE THREAD

**Issue by blandry** [PX4/Firmware#3454]
@davids5 requested that I file this. Will let Lorenz judge if it is relevant since it doesn't relates to master. When compiling /nuttx_next_cmake with gcc 4.9.3 on OSX we get the following error:

    [ 50%] Building CXX object src/modules/navigator/CMakeFiles/modules__navigator.dir/mission_block.cpp.obj
    In file included from /Users/benoitlandry/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/bits/char_traits.h:380:0,
                 from /Users/benoitlandry/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/string:40,
                 from /Users/benoitlandry/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/stdexcept:39,
                 from /Users/benoitlandry/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/array:38,
                 from /Users/benoitlandry/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/tuple:39,
                 from /Users/benoitlandry/gcc-arm-none-eabi-4_9-2015q3/arm-none-eabi/include/c++/4.9.3/functional:55,
                 from /Users/benoitlandry/Code/Firmware_solo/src/include/../platforms/px4_subscriber.h:42,
                 from /Users/benoitlandry/Code/Firmware_solo/src/include/../platforms/px4_nodehandle.h:42,
                 from /Users/benoitlandry/Code/Firmware_solo/src/include/px4.h:46,
                 from /Users/benoitlandry/Code/Firmware_solo/src/platforms/nuttx/px4_nuttx_impl.cpp:40:
    /Users/benoitlandry/Code/Firmware_solo/build_px4fmu-v2_default/px4fmu-v2/NuttX/nuttx-export/include/cxx/cstdint:75:11: error: 
    'uint_least32_t' is already declared in this scope using ::uint_least32_t;
           ^
    compilation terminated due to -Wfatal-errors.

**Comment by LorenzMeier** [comment]
It would need to rebase against master. The work on nuttx_next stopped before being completed as your organization did communicate it wanted to focus on other areas. There is little value in trying to use the WIP without putting up the bandwidth to actually finish it.
