### ISSUE TITLE
Altitude control reset

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3476]
@tumbili This issue is to track the altitude hold reset logic fails we've seen.
http://logs.uaventure.com/view/Z9gCEDujtGeJCTEj7dfkd7#Local_Z_PLOT

**Comment by ecmnet** [comment]
Isn't this topic already addressed in issue #3348?

**Comment by LorenzMeier** [comment]
Yes - closing the duplicate.
