### ISSUE TITLE
HIL spits out continues stream of warnings

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3493]
- Using latest firmware master and master QGC
- Boot QGC and connect for an XPlane HIL session
- Connect to HIL using the widget

Firmware spits out continuous stream of:
WARN  reset: NaN in states, resetting
telem> [ekf] ref: LA 0.0000,LO 0.0000,ALT 0.00
WARN  reset: NaN in states, resetting
telem> [ekf] ref: LA 0.0000,LO 0.0000,ALT 0.00
WARN  navigator timed out
WARN  reset: NaN in states, resetting

**Comment by jmullen** [comment]
Did you have a resolution to this error? I'm having the same issue, latest QQC, using XPlane 10 HIL session, I get a vomit of errors saying:

Critical: [ekf check] NaN in states, resetting
Info: [ekf] ref: LA 32.2043,LO -100.0420,ALT 743.12

No amount of googling has come up with a resolution to this issue.

**Comment by DonLakeFlyer** [comment]
I figured Lorenz fixed it since he closed the Issue

**Comment by jmullen** [comment]
The issue is still persisting after pulling the head.

**Comment by LorenzMeier** [comment]
@jmullen I have looked into it but its not fixed yet. QGC is saturating the link.

**Comment by LorenzMeier** [comment]
Doing the testing now..

**Comment by nsblackwell** [comment]
I'm running into this as well -- any updates?

**Comment by LorenzMeier** [comment]
Closing as stale.
