### ISSUE TITLE
RPi2 autopilot baseline Linux configuration

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#3509]
Opening this to track our work on getting the POSIX port running on RPi2/Rpi0 hardware combined with the currently available interface shields from ErleRobotics and Emlid.
#### RPi header pinout :

![pinoutraspberry-1](https://cloud.githubusercontent.com/assets/5557676/12321268/2e75f5f0-bad3-11e5-8ec2-097bc3c663a1.jpeg)
#### Buses :
- SPI : `/dev/spidev0.1`, `/dev/spidev0.0`
- I2C : `/dev/i2c-1`
- UART : `/dev/ttyAMA0`
#### Linux Image and Kernel :

http://docs.emlid.com/navio/Downloads/Real-time-Linux-RPi2/
# Shields :
## Navio 2 :

Target Board : RPi 2
### Sensors :
- MPU9250 IMU
- LSM9DS1 IMU
- MS5611 Barometer
- STM32Fxx coprocessor (similar to PX4IO)
- Ublox M8N GNSS reciever
## Navio + :

Target Board : RPi 2
### Sensors :
- MPU9250 IMU
- MS5611 Barometer
- PCA9685 PWM driver
- Ublox M8N GNSS reciever
## Erle-Brain 2:

Target Board : RPi 2
### Sensors :
- MPU9250 IMU (SPI, `/dev/spidev0.1`)
- MS5611 Barometer (SPI, `/dev/spidev0.0`)
- PCA9685 PWM driver (I2C, `0x40`)
### Docs and support:
- [Erle-Brain 2 docs](http://erlerobotics.com/docs/Artificial_Brains_and_Autopilots/Erle-Brain_2/Intro.html)
- [Erle Robotics support](http://forum.erlerobotics.com/)
## PXFmini:

Target Board : RPi0, RPi 2
### Sensors :
- MPU9250 IMU (SPI,  `/dev/spidev0.1`)
- MS5611 Barometer (SPI,  `/dev/spidev0.0`)
- PCA9685 PWM drivwqer (I2C, `0x40`)
### Docs and support:
- [PXFmini docs](http://erlerobotics.com/docs/Artificial_Brains_and_Autopilots/Autopilot_shields/PXFmini/Intro.html)
- [Erle Robotics support](http://forum.erlerobotics.com/)
## Datasheets (for all board parts) :
- [MPU-9250](http://store.invensense.com/datasheets/invensense/MPU9250REV1.0.pdf)
- [MS5611](http://www.meas-spec.com/downloads/MS5611-01BA03.pdf)
- [PCA9685](http://www.nxp.com/documents/data_sheet/PCA9685.pdf)
- [ADS1115](http://www.ti.com/lit/gpn/ads1115)
- [U-blox NEO-M8](http://www.u-blox.com/images/downloads/Product_Docs/NEO-M8_DataSheet_%28UBX-13003366%29.pdf)
- [MB85RC04](http://www.fujitsu.com/downloads/MICRO/fsa/pdf/products/memory/fram/MB85RC04V-DS501-00016-2v0-E.pdf)

**Comment by LorenzMeier** [comment]
Thanks for digging through the docs!

**Comment by LorenzMeier** [comment]
@ivereninov It would be fantastic to get a NAVIO 2 to Kabir. We have very much a focus on ports this month.

**Comment by vmayoral** [comment]
Thanks @mhkabir for putting this together. A few additional bits about Erle-Brain 2 and PXFmini:

## Erle-Brain 2:
Target Board : RPi 2

### Sensors :
- MPU9250 IMU (SPI, `/dev/spidev0.1`)
- MS5611 Barometer (SPI, `/dev/spidev0.0`)
- PCA9685 PWM driver (I2C,` 0x40`)

### Buses :
- SPI : `/dev/spidev0.1`, `/dev/spidev0.0`
- I2C : `/dev/i2c-1`
- UART : `/dev/ttyAMA0`

### Docs and support:
- [Erle-Brain 2 docs](http://erlerobotics.com/docs/Artificial_Brains_and_Autopilots/Erle-Brain_2/Intro.html)
- [Erle Robotics support](http://forum.erlerobotics.com/)

## PXFmini:
Target Board : RPi0, RPi 2

### Sensors :
- MPU9250 IMU (SPI, `/dev/spidev0.1`)
- MS5611 Barometer (SPI, `/dev/spidev0.0`)
- PCA9685 PWM drivwqer (I2C,` 0x40`)

### Buses :
- SPI : `/dev/spidev0.1`, `/dev/spidev0.0`
- I2C : `/dev/i2c-1`
- UART : `/dev/ttyAMA0`

### Docs and support:
- [PXFmini docs](http://erlerobotics.com/docs/Artificial_Brains_and_Autopilots/Autopilot_shields/PXFmini/Intro.html)
- [Erle Robotics support](http://forum.erlerobotics.com/)

**Comment by bo-rc** [comment]
Following! I want to contribute. Let me know what i can do. Thanks!

**Comment by mhkabir** [comment]
Native build instructions are up here : https://pixhawk.org/modules/linux/rpi2
You would require my branch from here : <TODO>

Compilation is relatively fast, even natively, so this setup works out OK for now. The rpi2 build target is stripped down for now.

For cross-compiling, we need a 4.8 cross-toolchain, which I don't think the Pi Foundation provides. Help ? @vmayoral @Clouded @ivereninov

**Comment by mhkabir** [comment]
Current state with native build : 
```
pi@navio-rpi:~/PX4/Firmware$ 
[init] shell id: 1995776000
[init] task name: mainapp

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

Ready to fly.

pxh> 
```

**Comment by mhkabir** [comment]
@vmayoral @bo-rc @Clouded Everyone please see #3527

The cross-compiler and native build targets work fine now.

**Comment by abencomo** [comment]
Hi Kabir,

Do you think we can give this a try on the RPi2 with the Navio+?

**Comment by mhkabir** [comment]
@abencomo Yes you can :) Feel free to jump in! Just don't expect any hardware to work just yet.

**Comment by bo-rc** [comment]
@mhkabir Are we going to take assignments for the drivers?

**Comment by gelazanskas** [comment]
+1, waiting for PX4 to work with Navio 2

**Comment by maxekman** [comment]
Following the with great interest!

Just wanted to mention that the link to the RT Linux by Emlid points to the older Navio (1) version, the Navio 2 version (for RPi 3) is here: http://docs.emlid.com/navio2/Navio-APM/configuring-raspberry-pi/

**Comment by awright424** [comment]
I would also like to know when I can try this out my on rpi2/3

**Comment by LorenzMeier** [comment]
Available on master.
