### ISSUE TITLE
cmake 3.3.1 error in check_cmake.sh

### ISSUE THREAD

**Issue by sunxfancy** [PX4/Firmware#3510]
My cmake 3.3.1 checks error, it thinks cmake not install.
I think we should use cmake's macro to check the version, not in script...

or use this line install :
```
if [[ $cmake_ver == *"2.8."* ]] || [[ $cmake_ver == *"2.9."* ]] || [[ $cmake_ver == *"3.0."* ]] || [[ $cmake_ver == *"3.1."* ]]
then
  exit 1;
fi
```

**Comment by LorenzMeier** [comment]
The CMake min version changes the behaviour of the build, so we cannot use that yet. Happy to accept a PR which sets the right policies. I'll fix the issue above by adding a space to the check line. Fixed in dd58dcf.
