### ISSUE TITLE
Off-board: sending local x,y,z from RPi

### ISSUE THREAD

**Issue by ArtemVass** [PX4/Firmware#3515]
Hello,
I use RPi to compute local position indoors but I stuck on sending those to PixHawk as Mavlink packets. I use MAVLINK_MSG_ID_LOCAL_POSITION_NED 32 to transmit coordinates but I see no effect in MAVLinkInspector. By the way, setpoint messages are working fine.

**Comment by sanderux** [comment]
did you enable MAV_DATA_STREAM_POSITION?

**Comment by ArtemVass** [comment]
According to official docs:
THIS INTERFACE IS DEPRECATED AS OF JULY 2015. Please use MESSAGE_INTERVAL instead. A data stream is not a fixed set of messages, but rather a recommendation to the autopilot software. Individual autopilots may or may not obey the recommended messages.

Would be great if you could show the way to enable it!

**Comment by sanderux** [comment]
Are you not getting data on POSITION_TARGET_LOCAL_NED?

**Comment by ArtemVass** [comment]
Well, I do. I got data on both LOCAL_POSITION_NED(I get x,y,z where x,y are always 0 and z is a barometer measurement) and POSITION_TARGET_LOCAL_NED. So, I have no idea, what's wrong.

**Comment by mhkabir** [comment]
Use VISION_POSITION_ESTIMATE or ATT_POS_MOCAP  to send your estimates.
