### ISSUE TITLE
FMUv4 voltage scaling

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3528]
@kd0aij Do you have a power module? Is the scaling wrong?
https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensors.cpp#L855

**Comment by kd0aij** [comment]
If we're talking about the new 8S ACSP4, I'm sure the scaling is different from the 3DR module.
I'll validate this when I get a chance to install an R12 and ACSP4 in a quad. I think Phil has already calculated and verified the scale factor.

**Comment by LorenzMeier** [comment]
@pkocmoud Users report incorrect voltage readings. So I really need to know what the right scales are (and this is another thing that dropped, because I don't recall signing off on the final scaling values or having a chance of discussing it with the community).

**Comment by kd0aij** [comment]
I'm seeing voltage_battery=0 in SYS_STATUS with ACSP4 connected using only one cable.
The BATTERY_STATUS message is all zero and -1, so it must not be getting updated.

**Comment by LorenzMeier** [comment]
Normal customers seem to get voltage out. Can't comment without hardware.

**Comment by kd0aij** [comment]
just measured voltage sense output of 742.7mV for input of 10.01V to ACSP4
ratio is .0742
full scale would be about 44.5V
8S is 8*4.2 = 33.6V max

But the firmware shows vehicle_status.voltage_battery = 0

**Comment by LorenzMeier** [comment]
What is the scaling for current?

**Comment by LorenzMeier** [comment]
I fixed it myself now in b2237ce.
