### ISSUE TITLE
Check S.BUS / S.BUS2 on Pixhawk

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3530]
@kd0aij We might have broken it during the Pixracer integration. Or user just used a bad build.

**Comment by kd0aij** [comment]
Just flashed rc_kill_sw2 on my X2 Aeroquad and the X6R radio looks just fine

**Comment by LorenzMeier** [comment]
Confirmed to be working on Pixhawk.

**Comment by LorenzMeier** [comment]
S.BUS 2 confirmed working. Now moving on to S.BUS 1 with FASSTest 12.

**Comment by LorenzMeier** [comment]
Is not supported by the TX. I think this is user error and an improperly configured TX.
