### ISSUE TITLE
yaw drift in multicopter attitude control

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#3534]
I don't think any PID parameters have changed in this setup, but in recent flights it has not been holding heading very well
![yaw_drift](https://cloud.githubusercontent.com/assets/2300221/12395459/f7e5f37a-bdbe-11e5-956f-eac97d354d74.png)

log: http://logs.uaventure.com/view/KAkQvSbUDpeabvQqYhEV7J

**Comment by kd0aij** [comment]
Forgot to mention that I'm also seeing a large lag in yaw response. The copter continues to yaw after I release the stick, as though it is a poorly tracked heading setpoint which I'm controlling, instead of the actual yaw rate.

**Comment by jgoppert** [comment]
This might be the same bug that is visible is SITL that causes the yaw to wander. It seems to be related to INAV. @kd0aij, can you try flying with LPE to confirm the bug is within INAV?

**Comment by priseborough** [comment]
I observed the same issue when I flew today with EKF2

**Comment by LorenzMeier** [comment]
@priseborough Can you share a log?

**Comment by LorenzMeier** [comment]
On http://logs.uaventure.com and provide the link via Skype or here.

**Comment by priseborough** [comment]
http://logs.uaventure.com/view/xM8RPz26NeFtmcR8Cnm5RL

**Comment by LorenzMeier** [comment]
Logged in #3600.
