### ISSUE TITLE
Level calibration issue

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3536]
If the board rotation parameters are non-zero the algorithm does not wait for the horizon to settle after the parameters have been zeroed. Either we wait or we don't zero them and just consider them in the final result.

**Comment by LorenzMeier** [comment]
Its designed to not wait if the rotation is zero. Are you saying it also doesn't wait if its non-zero?

**Comment by tumbili** [comment]
Possible fix in #3550
