### ISSUE TITLE
Unable to takeoff in ASSIST MODE

### ISSUE THREAD

**Issue by owenqyzhang** [PX4/Firmware#3538]
The drone can takeoff and fly in MANUAL mode, but when switched to ALTITUDE/POSITION CONTROL MODE, the motors won't spin at all.

**Comment by andre-nguyen** [comment]
Do you have an error message in qgroundcontrol?

**Comment by owenqyzhang** [comment]
No, nothing showed in QGC, when switching modes, the QGC showed the modes right, but cannot start the motors

**Comment by AndreasAntener** [comment]
This is currently how it is. https://github.com/PX4/Firmware/issues/3385 or something similar needs to be implemented.

**Comment by LorenzMeier** [comment]
Fixed it.
