### ISSUE TITLE
Gazebo SITL POSCTL instability

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3542]
The position control performance in Gazebo SITL seems to be impaired, at least on my machine. This leads to overshooting the waypoints (or manual commands) and "toilet bowling".

This needs further profiling and investigating.

![selection_001](https://cloud.githubusercontent.com/assets/1419688/12414369/697442a4-be95-11e5-8ce2-2093ba7ea504.png)

**Comment by tumbili** [comment]
@julianoes Good place to add that we need to check if the simulator puts a delay on the gps signal. Otherwise we would be compensating for a delay which is not there.

**Comment by julianoes** [comment]
@tumbili Oh good go know. Can you point me to the place where the delay is compensated for?

**Comment by LorenzMeier** [comment]
@julianoes @tumbili Can you convert all configs to EKF2 tomorrow and quickly test them? Including VTOL transitions.

**Comment by tumbili** [comment]
Done, closing!
