### ISSUE TITLE
sitl_gazebo compiling on Ubuntu

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3554]
sitl_gazebo requires /usr/include/OGRE/ to be added in the include paths in the CMakeList.txt, If not it will complain about missing includes

**Comment by julianoes** [comment]
Can you give a pointer to where in code this goes? I'm not sure what you mean, sorry.

**Comment by julianoes** [comment]
Found more info here: https://github.com/PX4/Firmware/issues/3475

**Comment by sanderux** [comment]
add it here: https://github.com/PX4/sitl_gazebo/blob/master/CMakeLists.txt#L23

**Comment by sanderux** [comment]
this seems to have been fixed somehow
