### ISSUE TITLE
MC: Landing ground detection needs improvements

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3560]
2 corner cases to track after #3526
- sometimes the velocity change when hitting the ground triggers the free fall logic, maybe we need to be more allowing there (effect, it bounces around on the ground, see log)
- ground detection with a relatively slow landing speed of 0.5m/s can trigger in air. the standard vtol is heavily affected in wind because it gets additional lift and seems to get stuck at the same altitude sometimes on slow landings

http://logs.uaventure.com/view/9HR7JtSCDwyikcCybanS2V#Thrust_PLOT

**Comment by AndreasAntener** [comment]
The behaviour was improved on master recently but the issues still exist.

**Comment by dagar** [comment]
@Stifael @AndreasAntener any change here?

**Comment by Stifael** [comment]
https://github.com/PX4/Firmware/issues/6730

**Comment by Stifael** [comment]
I will close it since it is discussed here #6730
