### ISSUE TITLE
Support DO_CMD_SPEED

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3563]
We're currently not allowing to set the current airspeed param, but it would be a quick change. @MikaelFerland.

**Comment by tubeme** [comment]
Good command that we need !! Thank you Mr.Meier.

**Comment by MikaelFerland** [comment]
Yes, it could be very nice to support that.
Thanks

**Comment by LorenzMeier** [comment]
Implementation here: https://github.com/PX4/Firmware/pull/3567

**Comment by MikaelFerland** [comment]
Thank you Lorenz, it was fast. It will try to test it this weekend.

**Comment by tubeme** [comment]
It is -15C and 50 cm of snow here. The first day I have the opportunity I will fly and test it.

**Comment by LorenzMeier** [comment]
Closing in favour of #3567.
