### ISSUE TITLE
MC, VTOL: corner cases in yaw handling during setpoint changes (mission)

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3564]
We've seen the following cases:
- takeoff: when switching from climbing to moving to the waypoint, it yaws into a (random) direction first
- transition: before the transition starts, it sometimes waits for a bit and yaws forth and back
- transition: at the moment of commanding the transition the yaw setpoint spikes

![screen shot 2016-01-22 at 10 33 47](https://cloud.githubusercontent.com/assets/5750020/12507216/a643b78a-c0f4-11e5-8865-8a864f97c30b.png)
![screen shot 2016-01-22 at 10 35 17](https://cloud.githubusercontent.com/assets/5750020/12507219/a8fde1da-c0f4-11e5-9df0-ba8aef15af48.png)

http://logs.uaventure.com/view/pry8kgGojZtXxnqGQPx2SU

**Comment by LorenzMeier** [comment]
I pushed two fixes:
https://github.com/PX4/Firmware/commit/737fe1fc7f689456722a56cbd21bbb1844771931
and
https://github.com/PX4/Firmware/commit/081da8bb7f37c0a6a7323d85e19c0fd5b4283eeb

These were both definitely needed, as they represent architecture corner cases for VTOL. I'm not sure this fixes everything, but it would be good if @tumbili Could test this tomorrow morning in SITL.

**Comment by LorenzMeier** [comment]
One more log:
http://logs.uaventure.com/view/8aaJzVRXvEnGfvLP63L5Pd

**Comment by LorenzMeier** [comment]
You might need to fix this as well or first to unblock this:
https://github.com/PX4/Firmware/pull/3582

I suggest to set up a call with Andreas first.

**Comment by CornerOfSkyline** [comment]
I found that the reset_yawsetpoint was not actived during the transition, the mc attitude control will try to control the yaw.

https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1819

Though here set the reset_yaw_sp = true, but it did not work in the control loop.We need to reset the yaw setpoint before to publish the attitude sp

**Comment by AndreasAntener** [comment]
Fixed via #3598
