### ISSUE TITLE
Pixracer: Baro spike on param read

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3568]
![screen shot 2016-01-22 at 17 27 29](https://cloud.githubusercontent.com/assets/1208119/12516384/7ed04946-c12d-11e5-8cf3-70cf6a58c229.png)

@tumbili @priseborough This is a race occurring on the SPI bus between the flash and the MS5611 sensor. All solvable, but I need to plough through it. Consequence of the new board architecture.

**Comment by kd0aij** [comment]
I'm seeing a spike on "param set", but not "param show" on PixRacer R12

**Comment by LorenzMeier** [comment]
Happens if you connect QGC, which does a save as part of its sync.

**Comment by LorenzMeier** [comment]
The fix for this will be to ensure the sensor driver is performing all sample -> read operations atomic.

**Comment by LorenzMeier** [comment]
Fixed on master.
