### ISSUE TITLE
Revisit the VFR_HUD message content

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3569]
In the 20160118 dev call an issue to track requested additions / changes in the VFR_HUD mavlink message was discussed. (https://pixhawk.ethz.ch/mavlink/#VFR_HUD)

Among others the following was noted;
- Altitude should be available as local, amsl and relative
- Battery voltage 
- Flight mode
- Distance to home
- Current mission WP nr
- Distance to next WP

**Comment by sanderux** [comment]
@tumbili do you know / can you mention the members of that call that had idea's on this?

**Comment by LorenzMeier** [comment]
We can't change messages without breaking the API. Closing this for now. The right forum for new MAVLink messages would be the MAVLink Google group or http://discuss.dronecode.org.
