### ISSUE TITLE
Crash post-mortem discussion

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3570]
The following mavlink log shows a vehicle that was operating with what appears te be a corrupt sdcard. 
[disaster.mavlink.zip](https://github.com/PX4/Firmware/files/101813/disaster.mavlink.zip)

The warnings are shown in this image:
![image](https://cloud.githubusercontent.com/assets/14801663/12529839/71f4743c-c1c7-11e5-8b96-4542142926e5.png)

It seems the vehicle did notice there was no valid mission and decided to loiter. The attempt to hold position failed. The mavlink log, seconds after entering mission mode,  shows the vehice as tilted left forward while the gps data shows the vehicle was moving as if it were tilted in the opposite direction.

![image](https://cloud.githubusercontent.com/assets/14801663/12529925/20ce3fe8-c1cc-11e5-85ab-2e30df996f4e.png)

**Comment by LorenzMeier** [comment]
Parameters are not stored on the microSD card. They are entirely isolated from anything happening there.

**Comment by sanderux** [comment]
@LorenzMeier Do you have any idea on how the sensor could become reversed? I'm trying to figure out if it is related to the dataman and corrupt SD card.

**Comment by sanderux** [comment]
This is the flight path at the moment it should have been loitering
![image](https://cloud.githubusercontent.com/assets/14801663/12536117/0d98727a-c29b-11e5-97f8-ae77b1e2144d.png)

**Comment by sanderux** [comment]
And this is the sensor reading at that moment
![image](https://cloud.githubusercontent.com/assets/14801663/12536128/83298ccc-c29b-11e5-9c88-7caf1c39ba4d.png)

**Comment by LorenzMeier** [comment]
It started to log successfully on the microSD card. I suspect therefore potentially a power related or mechanical issue. Unfortunately that's not transmitted at high enough rate via telemetry. Note the failure of the first magnetometer. If the frame was badly calibrated the failover to the 2nd mag might not have been enough to recover.

**Comment by sanderux** [comment]
That would still not explain the reversal. This reversal appears to have happened at the moment it switched to mission or the pilot would never have been able to fly manual. Could that in any way be related to the corrupt sd?

**Comment by LorenzMeier** [comment]
It switched to the internal mag at that point. If its environment was changed (something magnetic added in its vincinity) after calibration it could reverse the heading.

**Comment by sanderux** [comment]
In that case there is nothing the firmware could have done to prevent this.
I would suggest a thorough analysis if a similar event is reported in the future.

I think we can close this one for now.
