### ISSUE TITLE
Review RTL performance

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3575]
@julianoes @tumbili In this log the user reported that he had to abort RTL. I'm not sure yet what was exactly going on.

**Comment by LorenzMeier** [comment]
RTL failure:
http://logs.uaventure.com/view/u4aZuZJYjeZuS3PwdGYBCF

Mission successful:
http://logs.uaventure.com/view/Rj4TSTuEZU3Y2mvwPeRjaJ

**Comment by LorenzMeier** [comment]
@tumbili If we are missing data here to do the analysis properly (e.g. the home position) we should pimp our tools.

**Comment by AndreasAntener** [comment]
We probably hit the same issue, triggering RTL via command after offboard flight. The climb to RTL height worked as expected but returning to home didn't behave.
http://logs.uaventure.com/view/4Am2auDFHwDXtCmc8CPEzR

**Comment by LorenzMeier** [comment]
@julianoes @tumbili This is our absolute first priority. We need to nail this ASAP.

**Comment by LorenzMeier** [comment]
@julianoes This is another log (linked above already): http://logs.uaventure.com/view/u4aZuZJYjeZuS3PwdGYBCF

**Comment by LorenzMeier** [comment]
@julianoes @tumbili Since it affects mostly RTL I'm wondering if its related to home position yaw handling.

**Comment by LorenzMeier** [comment]
@kd0aij Could you share a log of your yaw tracking issue here as well?

**Comment by kd0aij** [comment]
https://github.com/PX4/Firmware/issues/3534#issue-127252193

**Comment by AndreasAntener** [comment]
Fixed on master via c9b1fb154d3e6ea1bbb28401688811a59c0f6543
