### ISSUE TITLE
gps driver call orb_publish() without orb_advertise()

### ISSUE THREAD

**Issue by LONELY-WOLF** [PX4/Firmware#3576]
Driver calls orb_advertise() only for UBX mode and fake GPS. If other mode is detected correctly driver locks on it but nothing happens cause orb_advertise() wasn't called. So receiver sends correct data and driver never switches to next mode but user sees nothing.

**Comment by LorenzMeier** [comment]
Thanks for reporting! Assuming that you have already a proposed fix, could you send a pull request for that?

**Comment by LONELY-WOLF** [comment]
Choose one

**Comment by LorenzMeier** [comment]
Thanks!
