### ISSUE TITLE
VTOL: Transition command likely interpreted as 3D waypoint

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3581]
This log shows that an invalid setpoint was published at the point of transition:
http://logs.uaventure.com/view/pry8kgGojZtXxnqGQPx2SU

I'm suspecting that this was the transition command being mishandled.

**Comment by CornerOfSkyline** [comment]
http://logs.uaventure.com/view/zsJADRamhsLdsadvFNacYd

**Comment by LorenzMeier** [comment]
This has been covered.
