### ISSUE TITLE
jMAVSim SITL keeps freezing

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3584]
The graphics of jMAVSim keep freezing for > 1s on my i7 laptop even though neither CPU nor RAM are maxed out.

This needs to be investigated/profiled.

**Comment by ecmnet** [comment]
@julianoes I guess this issue does not address the timing problem of jMAVSim?

**Comment by julianoes** [comment]
This seems to be related to my graphics/screen setup when QGC is displayed in parallel to jMAVSim.
