### ISSUE TITLE
Standard VTOL: Ensure that outputs run at 400 Hz

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3609]
@AndreasAntener @tumbili I have reports that the outputs only operate at 50 Hz right now. It would be good to verify. Running ```pwm info``` and looking at the rates should be enough to do so.

**Comment by AndreasAntener** [comment]
Looks like it's not set in the config.

**Comment by LorenzMeier** [comment]
Ok, I did already cut the release but we should set it.

**Comment by AndreasAntener** [comment]
Ah we should make a pass over all configs and make them use the p:PWM_* parameter syntax..

**Comment by LorenzMeier** [comment]
Yes - but it would already be good to just fix up the standard VTOL and get this to master quickly, then fix the rest.
