### ISSUE TITLE
MC Position control delay

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3610]
There is a delay when controlling the horizontal position with rc sticks in POSCTRL.
We may have to limit the maximum velocity error.

**Comment by tumbili** [comment]
Ok, just checked the logs. This is actually only happening if the max roll and pitch values are set to small values. So the quad cannot reach the desired velocity and once you let go of the sticks it takes a certain time for the vel sp to become smaller than the actual velocity.

**Comment by LorenzMeier** [comment]
Thanks! Would you advise different defaults?

**Comment by tumbili** [comment]
@LorenzMeier No, I was using the 450 of Christop and he was on 10 degrees :-)
