### ISSUE TITLE
two errors appear when i make all with px4-toolchain eclipse in windows, i don't know how to handle it

### ISSUE THREAD

**Issue by JohnPanheixia** [PX4/Firmware#3611]
20:44:49 **** Build of configuration Default for project Firmware ****
make all 
git submodule init
Submodule 'NuttX' () registered for path 'NuttX'
Submodule 'Tools/gencpp' () registered for path 'Tools/gencpp'
Submodule 'Tools/genmsg' () registered for path 'Tools/genmsg'
Submodule 'Tools/jMAVSim' () registered for path 'Tools/jMAVSim'
Submodule 'Tools/sitl_gazebo' () registered for path 'Tools/sitl_gazebo'
Submodule 'cmake/cmake_hexagon' () registered for path 'cmake/cmake_hexagon'
Submodule 'mavlink/include/mavlink/v1.0' () registered for path 'mavlink/include/mavlink/v1.0'
Submodule 'src/lib/DriverFramework' () registered for path 'src/lib/DriverFramework'
Submodule 'src/lib/dspal' () registered for path 'src/lib/dspal'
Submodule 'src/lib/ecl' () registered for path 'src/lib/ecl'
Submodule 'src/lib/matrix' () registered for path 'src/lib/matrix'
Submodule 'src/modules/uavcan/libuavcan' () registered for path 'src/modules/uavcan/libuavcan'
Submodule 'unittests/googletest' () registered for path 'unittests/googletest'
Tools/check_submodules.sh 
Git submodule config valid.
Checked NuttX submodule, correct version found
Checked Tools/gencpp submodule, correct version found
Checked Tools/genmsg submodule, correct version found
Checked Tools/jMAVSim submodule, correct version found
Checked Tools/sitl_gazebo submodule, correct version found
Checked cmake/cmake_hexagon submodule, correct version found
Checked mavlink/include/mavlink/v1.0 submodule, correct version found
Checked src/lib/DriverFramework submodule, correct version found
Checked src/lib/dspal submodule, correct version found
Checked src/lib/ecl submodule, correct version found
Checked src/lib/matrix submodule, correct version found
Checked src/modules/uavcan/libuavcan submodule, correct version found
Checked unittests/googletest submodule, correct version found
make -C /C/px4/Firmware/build_px4fmu-v2_default -j4 --no-print-directory 
[  0%] Built target __nuttx_patch_px4io-v2
[  0%] Built target mixer_gen
[  0%] Built target git_genmsg
[  0%] Built target git_nuttx
[  0%] Built target git_gencpp
[  0%] Built target __nuttx_patch_px4fmu-v2
Running from the source directory
Traceback (most recent call last):
  File "dsdl_compiler/libuavcan_dsdlc", line 59, in <module>
    from libuavcan_dsdl_compiler import run as dsdlc_run
  File "c:\px4\Firmware\src\modules\uavcan\libuavcan\libuavcan\dsdl_compiler\libuavcan_dsdl_compiler\__init__.py", line 17, in <module>
    from uavcan import dsdl
ImportError: No module named uavcan
[  0%] Built target git_matrix
make[3]: *** [src/modules/uavcan/libuavcan/libuavcan/CMakeFiles/libuavcan_dsdlc] Error 1
make[2]: *** [src/modules/uavcan/libuavcan/libuavcan/CMakeFiles/libuavcan_dsdlc.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  0%] Built target git_mavlink
[  1%] Built target git_uavcan
make[1]: *** [all] Error 2
make: *** [px4fmu-v2_default] Error 2

20:46:57 Build Finished (took 2m:8s.217ms)

who can help me?

**Comment by LorenzMeier** [comment]
As our documentation says we're not supporting Windows. Please install a Ubuntu VM:
http://dev.px4.io/starting-installing-windows.html
