### ISSUE TITLE
an error has occourred when i enter"git clone https://github.com/PX4/Firmware.git" in terminal in ubuntu with VMware

### ISSUE THREAD

**Issue by JohnPanheixia** [PX4/Firmware#3616]
fatal: unable to access 'https://github.com/PX4/Firmware,git': Could not resolve host:github.com
i can visit github.com with Firefox in Nanjing,China
Who can help me?Thanks a lot!

**Comment by LorenzMeier** [comment]
You have a typo in there: The URL is wrong. Please copy the correct URL from here: https://github.com/PX4/Firmware
