### ISSUE TITLE
Special handling for manual control inputs for large heading errors

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3620]
As soon as the heading error becomes large (often the case for VTOL in high winds) the manual roll and pitch controls do not lead to the reaction the user would expect. This is because the roll and pitch sequence comes after the yaw sequence in the euler formulation we are using (we are generating the attitude setpoint quaternion from euler angles).
However, this is tricky for the user and should be fixed.

**Comment by LorenzMeier** [comment]
I didn't realize we still had this. Indeed something to fix right away.

Given that the user is not providing yaw angle set points anyway the whole method should be replaced. The user intent does never include yaw angles.

**Comment by tumbili** [comment]
Fixed in #4564
