### ISSUE TITLE
PWM Start up states

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#3625]
@LorenzMeier, @kd0aij , @pkocmoud 
When developing [Add Input Capture capabilities to FMU] (https://github.com/PX4/Firmware/pull/3607) I was scrutinizing the inital conditions on the FMU V2 HW, today I looked at the FMU V4 HW.

Here is FMUV2 on master

![image](https://cloud.githubusercontent.com/assets/1945821/12653543/1c91d856-c594-11e5-9067-67e3061d32a8.png)

There are 3 things to note:
1) The AUX lines are high at start up.
2) The blip on chan 5
3) glitches on transition to PWM

I wanted to have the aux channels start low. So I changed the 
```#define GPIO_GPIOn_INPUT	(GPIO_INPUT|GPIO_PULLUP|GPIO_PORTE|GPIO_PIN14)```
to
```#define GPIO_GPIO0_INPUT	(GPIO_INPUT|GPIO_PULLDOWN|GPIO_PORTE|GPIO_PIN14)```

On V2 hardware the inputs still were high. The reason I believe is the TXS0108E-Q1 8-Bit Bi-directional, Level-Shifting, Voltage Translator. When a B side input is connected to an input or left floating it wins over the A side pull down. (I attached a EMAX ES08A as a load and it still starts high)

![image](https://cloud.githubusercontent.com/assets/1945821/12653960/ea90c45a-c595-11e5-8abe-a2e4c6d38ec0.png)

Secondly The blip on Chan 5 is caused by this [line] (https://github.com/PX4/Firmware/blob/master/src/drivers/boards/px4fmu-v2/px4fmu2_init.c#L236) of code. Does anyone know why this was added [from here] (https://github.com/PX4/Firmware/commit/dbe58d6165cfc392e81b86b2d1f7f0e7ab60706f) ?

The final issue I would like to share is the glitches on master when the gopio(s) transitions to PWM mode. Prior to the 1 Ms pulse.

Master:

![image](https://cloud.githubusercontent.com/assets/1945821/12654790/d3e01e78-c599-11e5-8c8d-048db4cef58b.png)

Remedies 

On [Add Input Capture capabilities to FMU] (https://github.com/PX4/Firmware/pull/3607) V2 HW has been reduced to one .1875 us glitch
![image](https://cloud.githubusercontent.com/assets/1945821/12654916/6e007124-c59a-11e5-8d87-638b65f3ba65.png)
Zoomed in:
![image](https://cloud.githubusercontent.com/assets/1945821/12654960/a8b50398-c59a-11e5-986d-083109d3d7c0.png)

This remaining glitch is caused by nuttx and I believe I can fix it for V2 HW - I just need to review the IO structure on the STM32 and the nuttx gpio config code to see if my solution is not going to add other problems..

On FMUV4 Hardware we can change to using ```#define GPIO_GPIO0_INPUT	(GPIO_INPUT|GPIO_PULLDOWN|GPIO_PORTE|GPIO_PIN14)```
 and it will work to initialize from boot the AUX channels low.

Then on V4 HW there would be no glitches (except for #2) listed above. But that can be fixed easily.

**Comment by LorenzMeier** [comment]
@davids5 This line: https://github.com/PX4/Firmware/blob/master/src/drivers/boards/px4fmu-v2/px4fmu2_init.c#L236

Is because of Lidar PWM power control. But probably done in a wrong way and I'd like to factor it out.

**Comment by davids5** [comment]
@LorenzMeier,

Thanks for unraveling the mystery. Yes it is in the wrong place. The driver should use an IOCTL on the FMU or if it is time critical take ownership of the pin.  

On a related note: I wonder it the statup code change  from  https://github.com/PX4/Firmware/commit/2e8accc6ffd5e1c2f37d31b09d6968a1e4af31ba might have caused [Lidar via PWM stopped working] (https://github.com/PX4/Firmware/issues/3628#issuecomment-176675687)

**Comment by davids5** [comment]
@LorenzMeier - @tridge has a valid point about removing the default_value and replacing the init witn rCCRn(timer) = 0;

This will ensure a channel that is enabled and not configured will not begin an output of any pulse train.

**Comment by LorenzMeier** [comment]
I've already merged that. Can you rebase, strip that setting entirely and configure to 0? I will look tomorrow into the pin config for the 5th pin and into fitting that into this PR to put this all to rest.

**Comment by davids5** [comment]
@LorenzMeier - PR for just this change against master. https://github.com/PX4/Firmware/pull/3632 pushed

**Comment by davids5** [comment]
@LorenzMeier Rebased https://github.com/PX4/Firmware/pull/3607 to also use a default rate of 0
@tridge - these changes have been rebased at 7958dae

**Comment by LorenzMeier** [comment]
Fixed on master.
