### ISSUE TITLE
Lidar via PWM stopped working, needs a reset to get it going

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3628]
Not sure at which point it broke

**Comment by SimonWilks** [comment]
It is working on an earlier version of master from 31. Dec. so it broke sometime after that.

**Comment by SimonWilks** [comment]
@davids5 you were right, reverting 2e8accc6ffd5e1c2f37d31b09d6968a1e4af31ba fixed the issue. 

This is also fixed in #3607

**Comment by AndreasAntener** [comment]
Fixed on master
