### ISSUE TITLE
UAVCAN interfaced external sensors broken

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#3629]
Some changes in commander seem to prevent arming when external sensors come online late. I'm currently tracking this down.

QGC displays the error message "Preflight checks complete, reboot before arming." A reboot, obviously, doesn't fix the issue.

Also, the issue isn't reported back to GCS, so the failure reporting is broken too.

@pavel-kirienko

**Comment by mhkabir** [comment]
Looks like we never get out of ```ARMING_STATE_STANDBY_ERROR``` although sensor comes online later.

**Comment by LorenzMeier** [comment]
Then extending the hot plug timeout should be enough to fix it.

**Comment by pavel-kirienko** [comment]
Not reproducible on latest master. The testing setup included 4 Zubax Orel ESC and 1 Zubax GNSS 2. I tried to re-configure and recalibrate the vehicle from scratch (wiped out all parameters), everything worked smoothly, at the end PX4 can arm successfully.

**Comment by pavel-kirienko** [comment]
Closing because the problem was caused by bad cables.

**Comment by mhkabir** [comment]
@pavel-kirienko @LorenzMeier OK, so this was not cables. Reopening. 

I have zero errors on the CAN interface now; Issue still occurs for me on a fresh system, recalibrated and everything.

```
[ERROR] [1455095525.661711420]: FCU: Preflight check resolved, reboot before arming
```
Cannot arm.

**Comment by mhkabir** [comment]
Okay, I figured out the issue. 
This was not even related to UAVCAN. The system had low battery, so it didn't go to standby. We probably need better reporting here, but not related to this. Closing.
