### ISSUE TITLE
Acceptance radius confusion for user

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3638]
There is a radius in the mission item and there is a parameter. This is confusing for the user and we have to re-check what the system actually does. During our test we had the feeling that the plane was ignoring the parameter. Logs to come.

**Comment by LorenzMeier** [comment]
For planes the radius is only a maximum: It will choose the minimum it can fly or this one. But if you set it to 10m and it can only turn in 60m it will switch at 60m.

**Comment by LorenzMeier** [comment]
Generally this should not be shown to users. They should just draw lines.

**Comment by tumbili** [comment]
@LorenzMeier Is this the loiter radius or what?

**Comment by LorenzMeier** [comment]
I can explain tomorrow on the whiteboard how the navigation works. But fundamentally you do not get to choose as a user when it switches the waypoint.

**Comment by LorenzMeier** [comment]
This will be fixed in:
https://github.com/mavlink/qgroundcontrol/issues/2743
and
https://github.com/mavlink/qgroundcontrol/issues/2744

**Comment by LorenzMeier** [comment]
Fixed in QGC.
