### ISSUE TITLE
Plane idle throttle on takeoff

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3640]
When you switch to mission on the ground the plane doesn't have idle throttle. As soon as a takeoff is detected ONCE (e.g by shaking the plane) the idle throttle is there. Logs and better description to come.

**Comment by LorenzMeier** [comment]
If you remove the check here for modes and execute this in all modes:
https://github.com/PX4/Firmware/blob/master/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp#L1950

It might just work.

**Comment by LorenzMeier** [comment]
Applied to master, closing.
