### ISSUE TITLE
SITL gazebo simulation question

### ISSUE THREAD

**Issue by tuofeichen** [PX4/Firmware#3642]
Hey guys,
Noob here to PX4 and just setup the sitl gazebo simulator using the make posix_sitl_default in the Firmware. Get the communication going and everything works fine. I'm using a small offboard ROS node with mavros plugin setpoint_velocity to send velocity command but what I'm wondering is, 

Why does the drone drift a lot when I'm only sending a upward z direction velocity? Is the gazebo model ideal with no wind? Or is there anything about how px4 low level control/setpoint_velocity command I'm not aware of?

Specifically how does px4 handle the setpoint_velocity command? Does it have a one to one mapping between speed input and rotor speed (this would be odd with different frame size and motors and propellers)? or does it adjust the rotor speed based on IMU feedback until it reaches the desired speed?

Also, I wonder what the setpoint_velocity = 0 0 0 0 0 0 will do , if there's no GPS or px4flow or anything that can help it loiter?

Thank you so much!

Best Regards,
Francis

**Comment by gokoreas** [comment]
The drift maybe due to the barometer data

To reduce it, changing the parameter of the INAV weights may change how the vehicle will move

I guess if you set the setpoint_velocity as you said will not necessarily control it self to stay around a fixed point and may drift

you will have to control the quad or use the setpoint_position to stay it in a fixed point

**Comment by LorenzMeier** [comment]
@tuofeichen @gokoreas Are you using master?

**Comment by tuofeichen** [comment]
Hi @LorenzMeier 

Yeah, the Firmware and SITL I'm using is master. I also have a feeling that my computer is too slow to run gazebo, because when I ran jmavsim, it works most of the time. I was using a virtual machine and recently I installed the dualboot and I will see if things get better.

Still, would appreciate you explain a little bit how px4 handle the setpoint_velocity command, and how does the IMU estimate velocity. Because I did see the message published from `mavros /local_position/velocity` and I wonder if that's usually reliable. 

Thanks

**Comment by tuofeichen** [comment]
Update: stream velocity not fast enough causes the problem. Already solved.

**Comment by andre-nguyen** [comment]
How fast are you sending the setpoints now?

**Comment by tuofeichen** [comment]
sending it every 10ms should be fine, careless mistake on my side, set the `ros::Rate loop_rate` to be 10 originally, seeing that 10ms in documentations. And never thought about that again. Setting it to 100 (hz) solved the problem.

**Comment by andre-nguyen** [comment]
Interesting, I'll try adding that tip in the documentation when I can.
