### ISSUE TITLE
Extend camera trigger to distance based mode and expose in QGC

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3645]

**Comment by NaterGator** [comment]
Percent forward overlap is another useful triggering mode but requires knowledge of the camera parameters and distance to terrain.

If you can make the assumption that the camera position is normally nadir and the terrain is flat the problem simplifies to roughly distance based triggering with a little more robustness.  It may be worth implementing at the same time.

**Comment by birchera** [comment]
An implementation of the distance based triggering has been proposed in https://github.com/PX4/Firmware/pull/3774

The distance can be adapted in QGC.

In my opinion handling the overlap and camera parameters like e.g. FoV, resolution would rather belong in a mission planning feature in QGC. From these parameters you could then derive the value for the triggering distance parameter.

**Comment by LorenzMeier** [comment]
Done!
