### ISSUE TITLE
Set 1500 as PWM disarmed value for fixed-wing control surfaces

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3649]
.. FW and VTOL configs

**Comment by LorenzMeier** [comment]
Master has a fix in which does not send a PWM pulse any more on enabling the interface. That should silence the control surface twitch. So only VTOLs should have the issue because of the PWM_MIN setting. However, if configured / assigned correctly it might even work now already.

**Comment by AndreasAntener** [comment]
Oh, actually since none of the FW configs define min/max/disarmed for other than motor channel they shouldn't move anymore? So maybe it makes more sense to remove the AUX PWM settings from all the vtol configs instead of setting disarmed to 1500. Will bench test tomorrow.

**Comment by LorenzMeier** [comment]
Put on master.
