### ISSUE TITLE
Can't connect Mission Planner with Pixhawk via 3dr telem radio

### ISSUE THREAD

**Issue by Phoenix5862** [PX4/Firmware#3654]
When I used APM on my Pixhawk everything was fine. Could connect them and so on. But now I have to use PX4. But the problem is that I can't connect the Mission Planner with Pixhawk. The two radio modules "see" each other(solid green), but when I press the connect button(with baudrate: 57600) i get a timeout. What could be the reason for it?

**Comment by LorenzMeier** [comment]
Use QGroundControl.
