### ISSUE TITLE
Message "waypoint X below home" after mission upload is mostly wrong

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3656]

**Comment by AndreasAntener** [comment]
@sanderux would be cool if you could have a look at this and include in your feedback update :)

**Comment by sanderux** [comment]
For my own reference:
Ignore mission frame items
https://github.com/PX4/Firmware/blob/9a8e94bb68d2c78ea1bd9d62ac993d937b797a31/src/modules/navigator/mission_feasibility_checker.cpp#L198

**Comment by sanderux** [comment]
@AndreasAntener do you have a mission that will replicate this bug in sitl? I cannot reproduce on current master
