### ISSUE TITLE
VTOL: RTL on aborted transitions in auto

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3663]

**Comment by sanderux** [comment]
For my own reference:
format command
https://github.com/PX4/Firmware/blob/15b72045ceda4db2bc76c1fb2366cdb6a55d02d3/src/modules/commander/commander.cpp#L804-L807
issue command
https://github.com/PX4/Firmware/blob/15b72045ceda4db2bc76c1fb2366cdb6a55d02d3/src/modules/navigator/mission_block.cpp#L113-L117
here (only mission mode?)
https://github.com/PX4/Firmware/blob/bde7eea4388a8017031da5c89c313ec18adddca4/src/modules/vtol_att_control/vtol_att_control_main.cpp#L455

**Comment by sanderux** [comment]
@AndreasAntener @LorenzMeier do you think the failsafe should trigger flight termination or just switch vehicle_status to MAIN_STATE_AUTO_RTL?

**Comment by LorenzMeier** [comment]
I don't think you propose to crash the plane if the transition failed, do you?

**Comment by sanderux** [comment]
As i read it, flight termination has param2==1 for RTL :)

**Comment by sanderux** [comment]
I think it should consider failsafe procedures as transition from manual mode might fail with gps lock. Or should failsafe only be triggered in mission mode?
