### ISSUE TITLE
SITL ekf2 vs default

### ISSUE THREAD

**Issue by tuofeichen** [PX4/Firmware#3668]
Hey guys,
I'm running SITL using the `make posix_sitl_default` in the Firmware directory right now, and I'm curious what's the difference between `posix_sitl_default` and `posix_sitl_ekf2`, I looked at the parameter.xml in both folder and they seemed to be identical? 

Thank you so much.

Best
Francis

**Comment by LorenzMeier** [comment]
The EKF2 SITL has been added to use the EKF2 estimator in all cases. The other SITL configs have been moved since to EKF2 and most likely that special config will be removed in the near future.
