### ISSUE TITLE
Gazebo fails to start on first boot on Mac OS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3677]

**Comment by sanderux** [comment]
This also happens on Ubuntu.

**Comment by ecmnet** [comment]
I still face issues using gazebo7 in simple mode (without ROS) on OSX. Refer to [https://groups.google.com/forum/#!topic/px4users/1hw475MBKpw](url)

**Comment by LorenzMeier** [comment]
This seems to be model database URI related, similar to this:
http://answers.ros.org/question/65402/gazebo-fail-to-connect-to-master-in-30-seconds-it-does-not-run-from-the-very-first-time/

**Comment by LorenzMeier** [comment]
FIxed.
