### ISSUE TITLE
LPE not working when ACC integration switched off

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#3695]
Position estimation does not work at all when LPE_INTEGRATE is set to zero to disable acc integration.

**Comment by jgoppert** [comment]
Thanks for reporting this, I'm looking into it. Do you have any logs? Can you try this PR https://github.com/PX4/Firmware/pull/3748?

**Comment by jgoppert** [comment]
LPE_INTEGRATE is now removed. There is still a bool controlling it in the source code, but performance is definetly worse with it set false.
