### ISSUE TITLE
Revisit over-demanding yaw strategy for VTOL's

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3702]
VTOL's can suffer from over-demanding yaw in high wind conditions.
When saturation occurs the vehicle looses altitude and some roll/pitch control.
When the limits of the drive are reached the system should favor altitude and roll/pitch over yaw.
It could be incorporated in: https://github.com/PX4/Firmware/pull/3706

There might also be a relation to:
https://github.com/PX4/Firmware/blob/6a98c6ca630a1fcacdf4c24bfec9d0b2c65201f9/src/modules/systemlib/mixer/mixer_multirotor.cpp#L338

**Comment by LorenzMeier** [comment]
If you hit that your system is likely just too underpowered. You can't have the cake and eat it. It would mean you have no yaw authority at all and your attitude control is marginal.

**Comment by sanderux** [comment]
@LorenzMeier 
I am currently 2.4:1 powered. I tried 40kph crosswind on the tail (no config would be able to hold that). the priority at that point seemed to go to maintaining yaw in favor of altitude. at 40kph front wind it was hovering nicely at 60% throttle

**Comment by sanderux** [comment]
here's a log of manual hover and loiter with nose in 40kph wind: http://logs.uaventure.com/view/YRzDvtPrWutTwj4vgdJT4R#AS_Pitch_PLOT

here's a log of the same 40kph wings while i turn the vehicle sideways to the wind (cross wind): http://logs.uaventure.com/view/ysBvQKS4jAfkxYLqA8TSWd

**Comment by sanderux** [comment]
Solved by yaw timeout and weathervane
