### ISSUE TITLE
SITL Param dump

### ISSUE THREAD

**Issue by tuofeichen** [PX4/Firmware#3705]
Hey guys,
I was wondering when I do a `mavros param dump` when running SITL, the parameter lists don't seem to be complete. Specifically, it seems like its not dumping all the INAV parameter, altitude Q estimator and so forth. Whereas when I actually run it on px4, the dumped parameter included all those. 

Looking at the build folder, those parameters are defined in 'parameters.xml', is there a reason behind its not dumping it in mavros? (maybe not want us to change those parameters?) Because I was trying to load some of my hardware parameter into SITL just to see what happens (for instance INAV ones), and mavros node output a warning saying those parameters not defined. 

Thank you
SITL parameters:
`
#NOTE: 06.02.2016 12:19:33
BAT_CAPACITY,-1.0
BAT_C_SCALING,-1.0
BAT_N_CELLS,3
BAT_V_CHARGED,4.199999809265137
BAT_V_EMPTY,3.4000000953674316
BAT_V_LOAD_DROP,0.07000000029802322
BAT_V_SCALING,-1.0
CAL_ACC0_ID,1376264
CAL_ACC0_XOFF,0.009999999776482582
CAL_ACC0_XSCALE,1.0099999904632568
CAL_ACC0_YOFF,-0.009999999776482582
CAL_ACC0_YSCALE,1.0099999904632568
CAL_ACC0_ZOFF,0.009999999776482582
CAL_ACC0_ZSCALE,1.0099999904632568
CAL_ACC1_ID,1310728
CAL_ACC1_XOFF,0.009999999776482582
CAL_ACC1_XSCALE,1.0
CAL_ACC1_YOFF,0.0
CAL_ACC1_YSCALE,1.0
CAL_ACC1_ZOFF,0.0
CAL_ACC1_ZSCALE,1.0
CAL_ACC_PRIME,0
CAL_BARO_PRIME,0
CAL_GYRO0_ID,2293768
CAL_GYRO0_XOFF,0.009999999776482582
CAL_GYRO0_XSCALE,1.0
CAL_GYRO0_YOFF,0.0
CAL_GYRO0_YSCALE,1.0
CAL_GYRO0_ZOFF,0.0
CAL_GYRO0_ZSCALE,1.0
CAL_GYRO_PRIME,0
CAL_MAG0_ID,196616
CAL_MAG0_ROT,-1
CAL_MAG0_XOFF,0.009999999776482582
CAL_MAG0_XSCALE,1.0
CAL_MAG0_YOFF,0.0
CAL_MAG0_YSCALE,1.0
CAL_MAG0_ZOFF,0.0
CAL_MAG0_ZSCALE,1.0
CAL_MAG1_ID,0
CAL_MAG1_ROT,-1
CAL_MAG2_ID,0
CAL_MAG2_ROT,-1
CAL_MAG_PRIME,0
CBRK_AIRSPD_CHK,0
CBRK_ENGINEFAIL,284953
CBRK_GPSFAIL,240024
CBRK_RATE_CTRL,0
CBRK_SUPPLY_CHK,0
CBRK_USB_CHK,0
COM_AUTOS_PAR,1
COM_DISARM_LAND,0
COM_DL_LOSS_EN,0
COM_DL_LOSS_T,10
COM_DL_REG_T,0
COM_EF_C2T,5.0
COM_EF_THROT,0.5
COM_EF_TIME,10.0
COM_HOME_H_T,5.0
COM_HOME_V_T,10.0
COM_RC_IN_MODE,1
COM_RC_LOSS_T,0.5
EKF2_ACC_B_NOISE,9.999999747378752e-05
EKF2_ACC_NOISE,0.25
EKF2_ASP_DELAY,200.0
EKF2_BARO_DELAY,0.0
EKF2_BARO_GATE,3.0
EKF2_BARO_NOISE,3.0
EKF2_GPS_CHECK,21
EKF2_GPS_DELAY,200.0
EKF2_GPS_P_GATE,3.0
EKF2_GPS_P_NOISE,1.0
EKF2_GPS_V_GATE,3.0
EKF2_GPS_V_NOISE,0.5
EKF2_GYR_B_NOISE,7.000000186963007e-05
EKF2_GYR_NOISE,0.0010000000474974513
EKF2_GYR_S_NOISE,0.003000000026077032
EKF2_HDG_GATE,3.0
EKF2_HEAD_NOISE,0.17000000178813934
EKF2_MAG_B_NOISE,0.02500000037252903
EKF2_MAG_DECL,0.0
EKF2_MAG_DELAY,0.0
EKF2_MAG_GATE,3.0
EKF2_MAG_NOISE,0.05000000074505806
EKF2_NOAID_NOISE,10.0
EKF2_REQ_EPH,5.0
EKF2_REQ_EPV,8.0
EKF2_REQ_GDOP,2.5
EKF2_REQ_HDRIFT,0.30000001192092896
EKF2_REQ_NSATS,6
EKF2_REQ_SACC,1.0
EKF2_REQ_VDRIFT,0.5
EKF2_WIND_NOISE,0.10000000149011612
GF_ACTION,1
GF_ALTMODE,0
GF_COUNT,-1
GF_MAX_HOR_DIST,-1
GF_MAX_VER_DIST,-1
GF_SOURCE,0
LNDMC_ROT_MAX,20.0
LNDMC_THR_MAX,0.15000000596046448
LNDMC_XY_VEL_MAX,1.5
LNDMC_Z_VEL_MAX,0.699999988079071
LPE_ENABLED,1
MAV_COMP_ID,1
MAV_FWDEXTSP,1
MAV_RADIO_ID,0
MAV_SYS_ID,1
MAV_TEST_PAR,1
MAV_TYPE,2
MAV_USEHILGPS,0
MC_ACRO_P_MAX,360.0
MC_ACRO_R_MAX,360.0
MC_ACRO_Y_MAX,360.0
MC_PITCHRATE_D,0.003000000026077032
MC_PITCHRATE_FF,0.0
MC_PITCHRATE_I,0.05000000074505806
MC_PITCHRATE_MAX,220.0
MC_PITCHRATE_P,0.15000000596046448
MC_PITCH_P,7.0
MC_PITCH_TC,0.20000000298023224
MC_RATT_TH,1.0
MC_ROLLRATE_D,0.003000000026077032
MC_ROLLRATE_FF,0.0
MC_ROLLRATE_I,0.05000000074505806
MC_ROLLRATE_MAX,220.0
MC_ROLLRATE_P,0.15000000596046448
MC_ROLL_P,7.0
MC_ROLL_TC,0.20000000298023224
MC_YAWRATE_D,0.0
MC_YAWRATE_FF,0.0
MC_YAWRATE_I,0.10000000149011612
MC_YAWRATE_MAX,120.0
MC_YAWRATE_P,0.3499999940395355
MC_YAWRAUTO_MAX,45.0
MC_YAW_FF,0.5
MC_YAW_P,2.799999952316284
MIS_ALTMODE,1
MIS_DIST_1WP,900.0
MIS_ONBOARD_EN,1
MIS_TAKEOFF_ALT,5.0
MIS_YAWMODE,1
MPC_ACC_HOR_MAX,4.0
MPC_HOLD_MAX_XY,0.5
MPC_HOLD_MAX_Z,2.0
MPC_HOLD_XY_DZ,0.10000000149011612
MPC_HOLD_Z_DZ,0.10000000149011612
MPC_LAND_SPEED,0.5
MPC_MANTHR_MAX,0.8999999761581421
MPC_MANTHR_MIN,0.07999999821186066
MPC_MAN_P_MAX,35.0
MPC_MAN_R_MAX,35.0
MPC_MAN_Y_MAX,120.0
MPC_THR_MAX,0.8999999761581421
MPC_THR_MIN,0.11999999731779099
MPC_TILTMAX_AIR,45.0
MPC_TILTMAX_LND,12.0
MPC_TKO_SPEED,1.5
MPC_VELD_LP,5.0
MPC_XY_FF,0.10000000149011612
MPC_XY_P,0.4000000059604645
MPC_XY_VEL_D,0.004999999888241291
MPC_XY_VEL_I,0.019999999552965164
MPC_XY_VEL_MAX,5.0
MPC_XY_VEL_P,0.20000000298023224
MPC_Z_FF,0.5
MPC_Z_P,1.0
MPC_Z_VEL_D,0.0
MPC_Z_VEL_I,0.019999999552965164
MPC_Z_VEL_MAX,2.0
MPC_Z_VEL_P,0.4000000059604645
NAV_ACC_RAD,2.0
NAV_AH_ALT,600.0
NAV_AH_LAT,-265847810
NAV_AH_LON,1518423250
NAV_DLL_AH_T,120.0
NAV_DLL_CHSK,0
NAV_DLL_CH_ALT,600.0
NAV_DLL_CH_LAT,-266072120
NAV_DLL_CH_LON,1518453890
NAV_DLL_CH_T,120.0
NAV_DLL_N,2
NAV_DLL_OBC,0
NAV_GPSF_LT,30.0
NAV_GPSF_P,0.0
NAV_GPSF_R,15.0
NAV_GPSF_TR,0.699999988079071
NAV_LOITER_RAD,50.0
NAV_RCL_LT,120.0
NAV_RCL_OBC,0
PWM_AUX_DISARMED,1000
PWM_AUX_MAX,2000
PWM_AUX_MIN,1000
PWM_DISARMED,0
PWM_MAX,2000
PWM_MIN,1000
RC10_DZ,0.0
RC10_MAX,2000.0
RC10_MIN,1000.0
RC10_REV,1.0
RC10_TRIM,1500.0
RC11_DZ,0.0
RC11_MAX,2000.0
RC11_MIN,1000.0
RC11_REV,1.0
RC11_TRIM,1500.0
RC12_DZ,0.0
RC12_MAX,2000.0
RC12_MIN,1000.0
RC12_REV,1.0
RC12_TRIM,1500.0
RC13_DZ,0.0
RC13_MAX,2000.0
RC13_MIN,1000.0
RC13_REV,1.0
RC13_TRIM,1500.0
RC14_DZ,0.0
RC14_MAX,2000.0
RC14_MIN,1000.0
RC14_REV,1.0
RC14_TRIM,1500.0
RC15_DZ,0.0
RC15_MAX,2000.0
RC15_MIN,1000.0
RC15_REV,1.0
RC15_TRIM,1500.0
RC16_DZ,0.0
RC16_MAX,2000.0
RC16_MIN,1000.0
RC16_REV,1.0
RC16_TRIM,1500.0
RC17_DZ,0.0
RC17_MAX,2000.0
RC17_MIN,1000.0
RC17_REV,1.0
RC17_TRIM,1500.0
RC18_DZ,0.0
RC18_MAX,2000.0
RC18_MIN,1000.0
RC18_REV,1.0
RC18_TRIM,1500.0
RC1_DZ,10.0
RC1_MAX,2000.0
RC1_MIN,1000.0
RC1_REV,1.0
RC1_TRIM,1500.0
RC2_DZ,10.0
RC2_MAX,2000.0
RC2_MIN,1000.0
RC2_REV,1.0
RC2_TRIM,1500.0
RC3_DZ,10.0
RC3_MAX,2000.0
RC3_MIN,1000.0
RC3_REV,1.0
RC3_TRIM,1500.0
RC4_DZ,10.0
RC4_MAX,2000.0
RC4_MIN,1000.0
RC4_REV,1.0
RC4_TRIM,1500.0
RC5_DZ,10.0
RC5_MAX,2000.0
RC5_MIN,1000.0
RC5_REV,1.0
RC5_TRIM,1500.0
RC6_DZ,10.0
RC6_MAX,2000.0
RC6_MIN,1000.0
RC6_REV,1.0
RC6_TRIM,1500.0
RC7_DZ,10.0
RC7_MAX,2000.0
RC7_MIN,1000.0
RC7_REV,1.0
RC7_TRIM,1500.0
RC8_DZ,10.0
RC8_MAX,2000.0
RC8_MIN,1000.0
RC8_REV,1.0
RC8_TRIM,1500.0
RC9_DZ,0.0
RC9_MAX,2000.0
RC9_MIN,1000.0
RC9_REV,1.0
RC9_TRIM,1500.0
RC_ACRO_TH,0.5
RC_ASSIST_TH,0.25
RC_AUTO_TH,0.75
RC_CHAN_CNT,0
RC_FAILS_THR,0
RC_KILLSWITCH_TH,0.25
RC_LOITER_TH,0.5
RC_MAP_ACRO_SW,0
RC_MAP_AUX1,0
RC_MAP_AUX2,0
RC_MAP_AUX3,0
RC_MAP_FAILSAFE,0
RC_MAP_FLAPS,0
RC_MAP_KILL_SW,0
RC_MAP_LOITER_SW,0
RC_MAP_MODE_SW,0
RC_MAP_OFFB_SW,0
RC_MAP_PARAM1,0
RC_MAP_PARAM2,0
RC_MAP_PARAM3,0
RC_MAP_PITCH,0
RC_MAP_POSCTL_SW,0
RC_MAP_RATT_SW,0
RC_MAP_RETURN_SW,0
RC_MAP_ROLL,0
RC_MAP_THROTTLE,0
RC_MAP_YAW,0
RC_OFFB_TH,0.5
RC_POSCTL_TH,0.5
RC_RATT_TH,0.5
RC_RETURN_TH,0.5
RC_TH_USER,1
RTL_DESCEND_ALT,10.0
RTL_LAND_DELAY,-1.0
RTL_RETURN_ALT,30.0
SDLOG_EXT,-1
SDLOG_GPSTIME,1
SDLOG_RATE,-1
SENS_BARO_QNH,1013.25
SENS_BOARD_ROT,0
SENS_BOARD_X_OFF,0.0
SENS_BOARD_Y_OFF,0.0
SENS_BOARD_Z_OFF,0.0
SENS_DPRES_ANSC,0.0
SENS_DPRES_OFF,0.0
SENS_FLOW_ROT,0
SYS_AUTOCONFIG,0
SYS_AUTOSTART,4010
SYS_PARAM_VER,1
SYS_RESTART_TYPE,2
TRIG_MODE,0
UAVCAN_ENABLE,0
VT_OPT_RECOV_EN,0
VT_TYPE,0
`

Pixhawk parameters:
`
#NOTE: 06.02.2016 13:07:53
ATT_ACC_COMP,2
ATT_BIAS_MAX,0.05000000074505806
ATT_EXT_HDG_M,0
ATT_MAG_DECL,0.0
ATT_MAG_DECL_A,1
ATT_VIBE_THRESH,0.20000000298023224
ATT_W_ACC,0.20000000298023224
ATT_W_EXT_HDG,0.10000000149011612
ATT_W_GYRO_BIAS,0.10000000149011612
ATT_W_MAG,0.10000000149011612
BAT_CAPACITY,-1.0
BAT_C_SCALING,0.012400000356137753
BAT_N_CELLS,4
BAT_V_CHARGED,4.199999809265137
BAT_V_EMPTY,3.0
BAT_V_LOAD_DROP,0.07000000029802322
BAT_V_SCALE_IO,10000
BAT_V_SCALING,-1.0
CAL_ACC0_ID,1246218
CAL_ACC0_XOFF,0.029535770416259766
CAL_ACC0_XSCALE,1.0087862014770508
CAL_ACC0_YOFF,0.060115814208984375
CAL_ACC0_YSCALE,1.0113418102264404
CAL_ACC0_ZOFF,0.05053234100341797
CAL_ACC0_ZSCALE,0.994357168674469
CAL_ACC1_ID,1114634
CAL_ACC1_XOFF,1.2232937812805176
CAL_ACC1_XSCALE,1.013627290725708
CAL_ACC1_YOFF,1.5038394927978516
CAL_ACC1_YSCALE,1.0284616947174072
CAL_ACC1_ZOFF,0.8631200790405273
CAL_ACC1_ZSCALE,1.0203559398651123
CAL_ACC_PRIME,1246218
CAL_BARO_PRIME,0
CAL_GYRO0_ID,2163722
CAL_GYRO0_XOFF,-0.008675982244312763
CAL_GYRO0_XSCALE,1.0
CAL_GYRO0_YOFF,0.062290288507938385
CAL_GYRO0_YSCALE,1.0
CAL_GYRO0_ZOFF,0.0008486656006425619
CAL_GYRO0_ZSCALE,1.0
CAL_GYRO1_ID,2228490
CAL_GYRO1_XOFF,0.04203926771879196
CAL_GYRO1_XSCALE,1.0
CAL_GYRO1_YOFF,-0.03402772173285484
CAL_GYRO1_YSCALE,1.0
CAL_GYRO1_ZOFF,0.014216999523341656
CAL_GYRO1_ZSCALE,1.0
CAL_GYRO_PRIME,2163722
CAL_MAG0_ID,131594
CAL_MAG0_ROT,-1
CAL_MAG0_XOFF,-0.4456094205379486
CAL_MAG0_XSCALE,1.0
CAL_MAG0_YOFF,-0.7272418141365051
CAL_MAG0_YSCALE,1.0
CAL_MAG0_ZOFF,0.1640162616968155
CAL_MAG0_ZSCALE,1.0
CAL_MAG1_ID,0
CAL_MAG1_ROT,-1
CAL_MAG2_ID,0
CAL_MAG2_ROT,-1
CAL_MAG_PRIME,131594
CBRK_AIRSPD_CHK,0
CBRK_BUZZER,0
CBRK_ENGINEFAIL,284953
CBRK_FLIGHTTERM,121212
CBRK_GPSFAIL,240024
CBRK_IO_SAFETY,0
CBRK_NO_VISION,0
CBRK_RATE_CTRL,0
CBRK_SUPPLY_CHK,0
CBRK_USB_CHK,0
COM_AUTOS_PAR,1
COM_DISARM_LAND,0
COM_DL_LOSS_EN,0
COM_DL_LOSS_T,10
COM_DL_REG_T,0
COM_EF_C2T,5.0
COM_EF_THROT,0.5
COM_EF_TIME,10.0
COM_HOME_H_T,5.0
COM_HOME_V_T,10.0
COM_RC_IN_MODE,0
COM_RC_LOSS_T,0.5
GF_ACTION,1
GF_ALTMODE,0
GF_COUNT,-1
GF_MAX_HOR_DIST,-1
GF_MAX_VER_DIST,-1
GF_SOURCE,0
INAV_DELAY_GPS,0.20000000298023224
INAV_DISAB_MOCAP,0.0
INAV_ENABLED,1
INAV_FLOW_DIST_X,0.0
INAV_FLOW_DIST_Y,0.0
INAV_FLOW_K,0.15000000596046448
INAV_FLOW_Q_MIN,0.30000001192092896
INAV_LAND_DISP,0.699999988079071
INAV_LAND_T,3.0
INAV_LAND_THR,0.20000000298023224
INAV_LIDAR_ERR,0.5
INAV_LIDAR_FILT,0.05000000074505806
INAV_W_ACC_BIAS,0.05000000074505806
INAV_W_GPS_FLOW,0.10000000149011612
INAV_W_MOC_P,10.0
INAV_W_XY_FLOW,9.0
INAV_W_XY_GPS_P,1.0
INAV_W_XY_GPS_V,2.0
INAV_W_XY_RES_V,0.5
INAV_W_XY_VIS_P,7.0
INAV_W_XY_VIS_V,0.0
INAV_W_Z_BARO,0.5
INAV_W_Z_GPS_P,0.004999999888241291
INAV_W_Z_GPS_V,0.0
INAV_W_Z_LIDAR,3.0
INAV_W_Z_VIS_P,5.0
LED_RGB_MAXBRT,15
LNDMC_ROT_MAX,20.0
LNDMC_THR_MAX,0.15000000596046448
LNDMC_XY_VEL_MAX,1.5
LNDMC_Z_VEL_MAX,0.699999988079071
MAV_COMP_ID,1
MAV_FWDEXTSP,1
MAV_RADIO_ID,0
MAV_SYS_ID,1
MAV_TEST_PAR,1
MAV_TYPE,2
MAV_USEHILGPS,0
MC_ACRO_P_MAX,360.0
MC_ACRO_R_MAX,360.0
MC_ACRO_Y_MAX,360.0
MC_PITCHRATE_D,0.003000000026077032
MC_PITCHRATE_FF,0.0
MC_PITCHRATE_I,0.05000000074505806
MC_PITCHRATE_MAX,220.0
MC_PITCHRATE_P,0.15000000596046448
MC_PITCH_P,7.0
MC_PITCH_TC,0.20000000298023224
MC_RATT_TH,1.0
MC_ROLLRATE_D,0.009999999776482582
MC_ROLLRATE_FF,0.0
MC_ROLLRATE_I,0.05000000074505806
MC_ROLLRATE_MAX,220.0
MC_ROLLRATE_P,0.15000000596046448
MC_ROLL_P,7.0
MC_ROLL_TC,0.20000000298023224
MC_YAWRATE_D,0.0
MC_YAWRATE_FF,0.0
MC_YAWRATE_I,0.10000000149011612
MC_YAWRATE_MAX,60.0
MC_YAWRATE_P,0.30000001192092896
MC_YAW_FF,0.5
MC_YAW_P,2.799999952316284
MIS_ALTMODE,1
MIS_DIST_1WP,900.0
MIS_ONBOARD_EN,1
MIS_TAKEOFF_ALT,2.5
MIS_YAWMODE,1
MPC_ACC_HOR_MAX,4.0
MPC_HOLD_MAX_XY,0.5
MPC_HOLD_MAX_Z,0.5
MPC_HOLD_XY_DZ,0.10000000149011612
MPC_HOLD_Z_DZ,0.10000000149011612
MPC_LAND_SPEED,0.5
MPC_MANTHR_MAX,0.5
MPC_MANTHR_MIN,0.05000000074505806
MPC_MAN_P_MAX,35.0
MPC_MAN_R_MAX,35.0
MPC_MAN_Y_MAX,60.0
MPC_THR_MAX,0.8999999761581421
MPC_THR_MIN,0.11999999731779099
MPC_TILTMAX_AIR,45.0
MPC_TILTMAX_LND,12.0
MPC_TKO_JMPSPD,2.0
MPC_TKO_SPEED,1.5
MPC_VELD_LP,5.0
MPC_XY_FF,0.5
MPC_XY_P,1.0
MPC_XY_VEL_D,0.009999999776482582
MPC_XY_VEL_I,0.019999999552965164
MPC_XY_VEL_MAX,5.0
MPC_XY_VEL_P,0.10000000149011612
MPC_Z_FF,0.5
MPC_Z_P,1.0
MPC_Z_VEL_D,0.0
MPC_Z_VEL_I,0.019999999552965164
MPC_Z_VEL_MAX,2.0
MPC_Z_VEL_P,0.20000000298023224
NAV_ACC_RAD,2.0
NAV_AH_ALT,600.0
NAV_AH_LAT,-265847810
NAV_AH_LON,1518423250
NAV_DLL_AH_T,120.0
NAV_DLL_CHSK,0
NAV_DLL_CH_ALT,600.0
NAV_DLL_CH_LAT,-266072120
NAV_DLL_CH_LON,1518453890
NAV_DLL_CH_T,120.0
NAV_DLL_N,2
NAV_DLL_OBC,0
NAV_GPSF_LT,30.0
NAV_GPSF_P,0.0
NAV_GPSF_R,15.0
NAV_GPSF_TR,0.699999988079071
NAV_LOITER_RAD,50.0
NAV_RCL_LT,120.0
NAV_RCL_OBC,0
PWM_AUX_DISARMED,1000
PWM_AUX_MAX,2000
PWM_AUX_MIN,1000
PWM_AUX_REV1,0
PWM_AUX_REV2,0
PWM_AUX_REV3,0
PWM_AUX_REV4,0
PWM_AUX_REV5,0
PWM_AUX_REV6,0
PWM_DISARMED,900
PWM_MAIN_REV1,0
PWM_MAIN_REV2,0
PWM_MAIN_REV3,0
PWM_MAIN_REV4,0
PWM_MAIN_REV5,0
PWM_MAIN_REV6,0
PWM_MAIN_REV7,0
PWM_MAIN_REV8,0
PWM_MAX,1950
PWM_MIN,1230
PWM_SBUS_MODE,0
RC10_DZ,0.0
RC10_MAX,2000.0
RC10_MIN,1000.0
RC10_REV,1.0
RC10_TRIM,1500.0
RC11_DZ,0.0
RC11_MAX,2000.0
RC11_MIN,1000.0
RC11_REV,1.0
RC11_TRIM,1500.0
RC12_DZ,0.0
RC12_MAX,2000.0
RC12_MIN,1000.0
RC12_REV,1.0
RC12_TRIM,1500.0
RC13_DZ,0.0
RC13_MAX,2000.0
RC13_MIN,1000.0
RC13_REV,1.0
RC13_TRIM,1500.0
RC14_DZ,0.0
RC14_MAX,2000.0
RC14_MIN,1000.0
RC14_REV,1.0
RC14_TRIM,1500.0
RC15_DZ,0.0
RC15_MAX,2000.0
RC15_MIN,1000.0
RC15_REV,1.0
RC15_TRIM,1500.0
RC16_DZ,0.0
RC16_MAX,2000.0
RC16_MIN,1000.0
RC16_REV,1.0
RC16_TRIM,1500.0
RC17_DZ,0.0
RC17_MAX,2000.0
RC17_MIN,1000.0
RC17_REV,1.0
RC17_TRIM,1500.0
RC18_DZ,0.0
RC18_MAX,2000.0
RC18_MIN,1000.0
RC18_REV,1.0
RC18_TRIM,1500.0
RC1_DZ,10.0
RC1_MAX,2014.0
RC1_MIN,990.0
RC1_REV,1.0
RC1_TRIM,990.0
RC2_DZ,10.0
RC2_MAX,2015.0
RC2_MIN,991.0
RC2_REV,1.0
RC2_TRIM,1501.0
RC3_DZ,10.0
RC3_MAX,2016.0
RC3_MIN,992.0
RC3_REV,1.0
RC3_TRIM,1505.0
RC4_DZ,10.0
RC4_MAX,2016.0
RC4_MIN,992.0
RC4_REV,1.0
RC4_TRIM,1504.0
RC5_DZ,10.0
RC5_MAX,2000.0
RC5_MIN,1000.0
RC5_REV,1.0
RC5_TRIM,1500.0
RC6_DZ,10.0
RC6_MAX,2016.0
RC6_MIN,991.0
RC6_REV,1.0
RC6_TRIM,1503.0
RC7_DZ,10.0
RC7_MAX,2000.0
RC7_MIN,1000.0
RC7_REV,1.0
RC7_TRIM,1500.0
RC8_DZ,10.0
RC8_MAX,2000.0
RC8_MIN,1000.0
RC8_REV,1.0
RC8_TRIM,1500.0
RC9_DZ,0.0
RC9_MAX,2000.0
RC9_MIN,1000.0
RC9_REV,1.0
RC9_TRIM,1500.0
RC_ACRO_TH,0.5
RC_ASSIST_TH,0.3283315896987915
RC_AUTO_TH,0.6526612639427185
RC_CHAN_CNT,8
RC_DSM_BIND,-1
RC_FAILS_THR,0
RC_LOITER_TH,0.3474595248699188
RC_MAP_ACRO_SW,0
RC_MAP_AUX1,0
RC_MAP_AUX2,0
RC_MAP_AUX3,0
RC_MAP_FAILSAFE,0
RC_MAP_FLAPS,0
RC_MAP_LOITER_SW,6
RC_MAP_MODE_SW,5
RC_MAP_OFFB_SW,0
RC_MAP_PARAM1,0
RC_MAP_PARAM2,0
RC_MAP_PARAM3,0
RC_MAP_PITCH,3
RC_MAP_POSCTL_SW,7
RC_MAP_RATT_SW,0
RC_MAP_RETURN_SW,0
RC_MAP_ROLL,2
RC_MAP_THROTTLE,1
RC_MAP_YAW,4
RC_OFFB_TH,0.5
RC_POSCTL_TH,0.4814477860927582
RC_RATT_TH,0.5
RC_RETURN_TH,0.5
RC_RSSI_PWM_CHAN,0
RC_RSSI_PWM_MAX,1000
RC_RSSI_PWM_MIN,2000
RC_TH_USER,1
RTL_DESCEND_ALT,30.0
RTL_LAND_DELAY,60.0
RTL_RETURN_ALT,10.0
SDLOG_EXT,-1
SDLOG_GPSTIME,1
SDLOG_RATE,-1
SENS_BARO_QNH,1013.25
SENS_BOARD_ROT,0
SENS_BOARD_X_OFF,0.6722664833068848
SENS_BOARD_Y_OFF,-1.0588234663009644
SENS_BOARD_Z_OFF,0.0
SENS_DPRES_ANSC,0.0
SENS_DPRES_OFF,0.0
SENS_EN_LL40LS,0
SENS_FLOW_ROT,0
SYS_AUTOCONFIG,0
SYS_AUTOSTART,4011
SYS_COMPANION,921600
SYS_PARAM_VER,1
SYS_RESTART_TYPE,0
SYS_USE_IO,1
TRIG_MODE,0
TRIM_PITCH,0.0
TRIM_ROLL,0.0
TRIM_YAW,0.0
UAVCAN_ENABLE,0
VT_TYPE,0
`

Best
Francis

**Comment by LorenzMeier** [comment]
SITL uses already the new estimator (EKF2). The programs you reference are not running - so its all working as it should. You need to change the start script in posix-configs/SITL if you like to use those instead.

**Comment by tuofeichen** [comment]
Hey Lorenz,
Thanks for the prompt reply. I guess I was asking a lot of this type of
questions because sometimes I'm not sure how px4 handles mavros in general.
And since I'm working with mavros for controlling the flight dynamics, is
there anywhere source-code-wise (in the px4 firmware I would imagine) I
should look into? In addition, I assume understanding mavlink is also going
to be helpful?

This is a good overall introduction, but I would like to go a little deeper
in terms of understanding.
https://pixhawk.org/dev/ros/mavros_offboard

This is not technically an issue so I just replied here instead of creating
a new one. Again, complete noob here and thanks for your help!

Best
Francis
