### ISSUE TITLE
VTOL: implement a parameter enforcing auto takeoff and land are always in vtol mode

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3712]
Most VTOL airframes (like tailsitters and some tiltrotors and quadplanes) are not capable of fixed wing takeoff or landing because they lack proper landing gear. A LAND command (from mission, failsafe, switch or offboard) would result in undesired behavior.

A parameter like VT_ENFORCE_VTOL should be added to indicate the vehicle will never attempt to takeoff or land in fixed wing mode unless there is no other choice (failed back transition, out of power).

**Comment by AndreasAntener** [comment]
Got implemented
