### ISSUE TITLE
integration3: pthread_attr_setstacksize not working

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3718]
@mcharleb 

mavlink doesn't start on the Linux side on the Snapdragon. Where needs this fixing?

```
pxh> mavlink start
ERROR pthread_attr_setstacksize returned error
```

**Comment by mcharleb** [comment]
@julianoes The same error occurs for SITL build so it should be easy to debug. Looking at it now.

**Comment by mcharleb** [comment]
Fixed on integration3.
