### ISSUE TITLE
Drop baro readout rate, validate influence on existing estimators

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3722]
We should drop the baro readout rate to help with thermal drift. The constant to reduce is MS5611_CONVERSION_INTERVAL. Related to: https://github.com/PX4/ecl/issues/44

**Comment by LorenzMeier** [comment]
@CarlOlsson: This is something for you

**Comment by CarlOlsson** [comment]
Ok I will make some tests with reduced readout rate and post the results

**Comment by LorenzMeier** [comment]
@CarlOlsson Did we get anywhere with this? Its still pretty important for baro accuracy.

**Comment by LorenzMeier** [comment]
Done in 2c6a8c0.
