### ISSUE TITLE
integration3: terminal on Snapdragon broken after shutdown

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3725]
When the mainapp is stopped using Ctrl+C on the Snapdragon it leaves the linux shell scrambled.

A workaround for now is to type exit and enter a new shell.

**Comment by mcharleb** [comment]
Better workaround is to run:

stty sane

**Comment by mcharleb** [comment]
The following code seems to be the culprit:

                // change input mode so that we can manage shell
                struct termios term;
                tcgetattr(0, &term);
                term.c_lflag &= ~ICANON;
                term.c_lflag &= ~ECHO;
                tcsetattr(0, TCSANOW, &term);
                setbuf(stdin, NULL);

Removing it allows terminal to shut down correctly.

**Comment by LorenzMeier** [comment]
Its not a solution to kill the arrow-up handling. The solution is to re-instate the previous shell state.

**Comment by mcharleb** [comment]
Pushed fix to integration3

**Comment by julianoes** [comment]
Tested, works. Thanks @mcharleb.
