### ISSUE TITLE
On-board application list

### ISSUE THREAD

**Issue by tuofeichen** [PX4/Firmware#3727]
Hi @LorenzMeier,
I don't know who's maintaining the pixhawk website, but I wonder if we can update this page since some new applications have been added and not all of them are  documented.  I think it would be helpful so that people knows what applications are already available and can potentially change things in startup script as needed. : )

https://pixhawk.org/firmware/apps/start

P.S. I didn't find relevant information on the dev.px4.io either. But lemme know if I missed anything.

Thank you. 

Best Regards
Francis

**Comment by julianoes** [comment]
@tuofeichen new developer information should go into http://dev.px4.io. The old wiki is deprecated.
Feel free to make pull request for it in https://github.com/PX4/Devguide.

**Comment by LorenzMeier** [comment]
Outdated.
