### ISSUE TITLE
Submodules: don't reset on make

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3733]
Git reseting the submodule on make is just not intuitive.

This would be what gets me every time:

1. I add and commit something in a submodule.
2. Now before I want to push it from the submodule and before commiting it in Firmware, I like to compile and test it one more time to make sure I don't push any rubbish.
3. I do make and run it.
4. I realize the bug I was trying to fix in the first place and start debugging again.
5. At some point I realize that my fix has gone from the source :facepunch: 

Arrgh, I'm a developer, I know git, and I don't want ```make``` messing with it!

This being said, a warning is fine but it shouldn't magically change my files.
Also ```git status``` tells me perfectly fine that I still need to add and commit my updated submodule, it's like any other unstaged file.

**Comment by davids5** [comment]
Will setting [GIT_SUBMODULES_ARE_EVIL] (https://github.com/PX4/Firmware/blob/master/Tools/check_submodules.sh#L3)
Solve your problem?

**Comment by LorenzMeier** [comment]
It must be a corner case of the version check script. Its not intended to work that way and it does work great for the cases where you are missing commits by asking if you would like to update.

**Comment by julianoes** [comment]
This just got me again.

I did: 

```
make clean
cd src/lib/DriverFramework
git checkout some_pull_request_branch
cd -
make
```

And the checked out commit in src/lib/DriverFramework is gone.

**Comment by LorenzMeier** [comment]
The issue is the make clean step. If you do this the system has no way of knowing wether you did a fresh clone (requiring init) or not. It would need to keep its own registry which would never reset by anything the user does, which is also a risk.

I'm on the fence of calling this an usage issue just requiring a printout to remind you to not do this. Because if we don't wipe out all files on make clean, we get ourselves into the stale file problem.

**Comment by julianoes** [comment]
I don't understand, I'm doing my changes **after** the make clean.

**Comment by LorenzMeier** [comment]
Yes, but your directory looks the same as a freshly cloned one.

**Comment by julianoes** [comment]
Yes, but the submodules are already there, so no need to mess with them.

**Comment by LorenzMeier** [comment]
How about you write a script checking their init status? :P.

**Comment by julianoes** [comment]
Sure, I'm just wondering where the current check happens.

Is it based on this https://github.com/PX4/Firmware/blob/master/Tools/check_submodules.sh#L9 ?

**Comment by LorenzMeier** [comment]
No, the one biting you is in the Makefile:
https://github.com/PX4/Firmware/blob/d2041b0ef3ffec1fc606c1389b1b74f1cf51beb7/Makefile#L112

**Comment by julianoes** [comment]
I was able to fix my issue using check_submodules. I don't know what the line in Makefile does.

**Comment by julianoes** [comment]
I removed that line, so now I expect it to work.

**Comment by julianoes** [comment]
This has been fixed, closing.
