### ISSUE TITLE
PWM outputs stay unpowered when disabling safety and no disarmed value is set

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3735]
@davids5 @LorenzMeier 
If I have no disarmed value set for FW controls (VTOL config on AUX pins) they are not getting powered when safety is disabled. Only after arming.

Ref: #3731

**Comment by LorenzMeier** [comment]
It looks like this never got implemented properly for the FMU driver. @kd0aij Is looking into it.

**Comment by LorenzMeier** [comment]
Fixed on master.
