### ISSUE TITLE
Secure Mavlink

### ISSUE THREAD

**Issue by jimdsouza** [PX4/Firmware#3747]
I've been using this firmware on my Pixhawk and noticed that anyone with a gcs can access my UAV.

Is there a feature planned to implement authentication (with/without) encryption on the Mavlink between the drone and the GCS?

**Comment by LorenzMeier** [comment]
Yes, there is a MAVLink 2.0 testing version which adds authentication. Would you be able to lend a hand with the development work needed to validate it?

**Comment by jimdsouza** [comment]
Sure. I was going to try to do just that on a fork of the firmware. But working with the main team on it is better than that. How do I start?

**Comment by LorenzMeier** [comment]
Fork the repository on Github, create a new branch off master, update MAVLink, then send a pull request for review & integration.

MAVLink 2.0 update:
http://discuss.dronecode.org/t/mavlink-2-0-progress-tracking/23/4

Associated GCS issue:
https://github.com/mavlink/qgroundcontrol/issues/2800

**Comment by jimdsouza** [comment]
Okay, thanks!

**Comment by jimdsouza** [comment]
Sorry, I'm new to this project and github. Just to reiterate, I fork PX4/Firmware, and I fork diydrones/mavlink. I then branch the former and use the mavlink2-wip branch in diydrones/mavlink to update the branch of PX4/Firmware. I then test the code and send in a pull request to PX4/Firmware.

Is that correct?

**Comment by LorenzMeier** [comment]
You generate the C-library for MAVLink using the mavlink fork and put the files in Firmware/mavlink/... in the right location, then you build it.

**Comment by jimdsouza** [comment]
I built it. Should I send a pull request?

**Comment by LorenzMeier** [comment]
Yes please! Can you upload a ZIP file with the generated MAVLink files somewhere? Then Don can have a go in QGroundControl as well. @DonLakeFlyer FYI

**Comment by jimdsouza** [comment]
Sure! You can download it from [here](http://jimdsouza.com/mavlink2.zip).

**Comment by LorenzMeier** [comment]
@jimdsouza MAVLink 2.0 is now on master. If you would like to implement signing a PR would be appreciated.

**Comment by jimdsouza** [comment]
Thanks, I'll try it. Not sure what you mean by signing a PR.

**Comment by LorenzMeier** [comment]
We haven't enabled signing of messages yet. If you implement that, please send a pull request.

**Comment by jimdsouza** [comment]
Sure, I'll give it go.
