### ISSUE TITLE
Aux PWM at 1500 on multirotor boot.

### ISSUE THREAD

**Issue by Gregsky** [PX4/Firmware#3749]
Aux PWM at 1500 on multirotor boot causes the retractable landing gear to randomly retract, the PWM_AUX_DISARMED is set to 1000.

**Comment by LorenzMeier** [comment]
On which AUX channel do you have your gear switch connected?

**Comment by gregswf** [comment]
I've got my RC8 maped to AUX1 an RC6 maped to AUX2, AUX1 is landing gear AUX2 is gimbal pitch.

**Comment by LorenzMeier** [comment]
Is this still an issue?
