### ISSUE TITLE
Auto-test script setup

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3750]
We should create a script which commands a mission via MAVLink to the SITL engine (via MAVLink) and then tracks the progress and adherence to the mission.

Ideally this would be done in DroneKit, which might need some fixes to comply with the upstream MAVLink spec.
http://dronekit.io

@liamstask Where is your Dronekit consolidation effort standing?

**Comment by sanderux** [comment]
@LorenzMeier i have some experience on this. What is the script for?

**Comment by LorenzMeier** [comment]
To ensure that a complete mission can still be flown end-to-end.

**Comment by LorenzMeier** [comment]
Done
