### ISSUE TITLE
Wrong function definition

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Firmware#3759]
Dear, 

There is a inconsistency between .h & .cpp for the `position_estimator_inav` module between the `inertial_filter.h` & `inertial_filter.cpp` files.

Indeed, the x[] data is defined as x[3] in the [header](https://github.com/PX4/Firmware/blob/4b659f199560e2f7213428d3d13a7d9f570f47bf/src/modules/position_estimator_inav/inertial_filter.h#L11-L13) and x[2] in the code [here](
https://github.com/PX4/Firmware/blob/4b659f199560e2f7213428d3d13a7d9f570f47bf/src/modules/position_estimator_inav/inertial_filter.cpp#L12) and [here](https://github.com/PX4/Firmware/blob/4b659f199560e2f7213428d3d13a7d9f570f47bf/src/modules/position_estimator_inav/inertial_filter.cpp#L24)

**Comment by julianoes** [comment]
Thanks @AlexisTM, fixed in #3761.
