### ISSUE TITLE
Can't takeoff in altitude control in SITL 

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3769]
Once in the air, altitude control works fine, however, I'm unable to takeoff. Is this intended?
I looked at ATTITUDE_TARGET.thrust and it remains 0 when on ground.

I've been trying this in jMAVSim.

**Comment by LorenzMeier** [comment]
It's as designed. The question is if we are too strict with this.

**Comment by julianoes** [comment]
Well there you have one user who is really confused about this as in "it doesn't fly".

**Comment by AndreasAntener** [comment]
After doing takeoff/landing my idea was this: https://github.com/PX4/Firmware/issues/3385

**Comment by julianoes** [comment]
This has changed, hasn't it?

**Comment by LorenzMeier** [comment]
Fixed.
