### ISSUE TITLE
No RC control when in failsafe

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3775]
Here's a log from a (vtol) flight that went into failsafe due to low  battery voltage (it was set a bit too high).
http://logs.uaventure.com/view/3msrKYiSjKrDvKKckveA4e

The as there was no autoland engaged the plane went into loiter.
I was unable to retake control of the plane by switching the mode switch on the RC, i had to switch the mode on the GCS to regain control

**Comment by sanderux** [comment]
RX issue due to TX signal loss. Devention RX will not allow mode switching after switching to RTL

**Comment by kd0aij** [comment]
would this have been a fly-away if no GCS were connected?

**Comment by sanderux** [comment]
yes, well, it would loiter until empty bat. but it's my RX, that sets channel 5 to 2000 at signal loss but doesnt recover when reconnected. I will replace the RX
