### ISSUE TITLE
Travis CI for OSX 5x slower than Ubuntu

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#3778]
Do we know why this is happening? It is a pain to have to wait 30 + minutes for CI. If we could figure out what is wrong and get it on par with ubuntu it would speed up development quite a bit.

**Comment by dagar** [comment]
The answer is probably just "it's slow", but I'll take a look. One option is having the build do much less on OSX. Do the nuttx builds ever break on one platform, but not the other? Maybe OSX only needs to be building posix.

**Comment by LorenzMeier** [comment]
Yes, POSIX only would be enough on OS X. That would allow us to skip the arm compiler install, which should speed it up dramatically. Please only comment out, not remove those bits though, thanks!

**Comment by DonLakeFlyer** [comment]
Same thing with QGC OSX builds, make me crazy!
