### ISSUE TITLE
RC switches are not considered updated on UORB at boot (flight mode, vtol transition, etc)

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3794]
You can boot with the transition switch in FW mode, but it will ignore this and arm in MC mode. Only after you flick the switch forth and back it will switch to FW

**Comment by sanderux** [comment]
It reads to me like it does update the state at launch: https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_att_control_main.cpp#L706

What vtol type did you notice this in?

**Comment by sanderux** [comment]
Mode switch also doesn't listen to switch setting at boot. mavlink does see the rc channel value.

**Comment by sanderux** [comment]
Turns out flight mode at boot (alt hold in this case) was rejected because altitude was not valid yet.
We could consider a mavlink log there
