### ISSUE TITLE
Yaw setpoint from manual can be kept when switching to auto

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3795]
To reproduce:
- have a mission with takeoff wp (30m)
- manual, hover at some altitude (5m)
- full yaw
- switch to mission during yaw

It will then keep yawing slowly during the mission flight (and do a nice pirouette)
http://logs.uaventure.com/view/wqG48Vi97iHGiKfNeWWymN

**Comment by LorenzMeier** [comment]
Fixed.
