### ISSUE TITLE
Use PX4 Flight Stack can not switch Mission mode (rejected 176)

### ISSUE THREAD

**Issue by Linja0314** [PX4/Firmware#3802]
Hi 

I use Pixhawk and build  PX4 Flight Stack stable version,and i try follow http://px4.io/docs/missions/ 
and http://dev.px4.io/concept-flight-modes.html  to setup my drone, 
if i switch Loiter , mission , position  mode , that can not work,and I sure my GPS is work on my drone

does anyone know how to solve this ? many thx

**Comment by LorenzMeier** [comment]
Yes, you did you not have proper GPS lock and/or you had no mission loaded. Wait for the RGB led to turn green, then you can.
