### ISSUE TITLE
VTOL transition altitude issues

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3808]
@AndreasAntener @tumbili 
4 missions flown on ada's 20160218 tree. The behavior was consistent but there was still a big altitude drop in forward transition and a rise in altitude in back transition.
I was able to solve the wobble that occurred after back transition by lowering MPC_Z_VEL_MAX. It appears that the altitude rise after back transition, and the consequent error in altitude setpoint for the MC caused wobbling behavior when the max z velocity was set too high. 

Unfortunately the SD card failed halfway through the mission (only recorded a single identical byte). So i only have half a mission log: http://logs.uaventure.com/view/KiMU9DGHtyYpx3ipGMfNok

The mission was set to 25m, after transition it dropped +- 9m as shown below:
![forward trans 20160219](https://cloud.githubusercontent.com/assets/14801663/13186080/9d841b4c-d744-11e5-9256-f33d42f49bb3.png)

**Comment by tubeme** [comment]
We observe the same loss in height during transition in 1.1.3.

**Comment by AndreasAntener** [comment]
@sanderux It looks like you need to tune your FW pitch. It tries to command pitch up to catch the drop but the elevator it commands is only very little. Increase FW_PR_FF and FW_PR_P. Have a look at what I set in the 13005 config. Roll is better but could also be a bit tighter.

<img width="1370" alt="screen shot 2016-02-20 at 10 57 33" src="https://cloud.githubusercontent.com/assets/5750020/13196018/d1cbf81a-d7c2-11e5-930c-28ac37bd97e7.png">


@tubeme could you try beta now? And if you want even better altitude hold set FW_T_SPDWEIGHT to 0 to give altitude priority over height. I got pretty good results with that.

**Comment by sanderux** [comment]
@AndreasAntener Yes they were quite low, so that might be it. I'll test fly when weather permits. thanks
