### ISSUE TITLE
Circle flight mode

### ISSUE THREAD

**Issue by Gregsky** [PX4/Firmware#3810]
One of the functions of PX4 controlled machine is to carry a camera it would be useful to have a circle flight mode activated with a switch.

**Comment by lishidetiankong** [comment]
I agree with you, I think you should refer to APM Circle Mode!!!

**Comment by liang-tang** [comment]
yes, and i made it.

**Comment by liang-tang** [comment]
I had make it accroding to APM Circle Mode, it works well yet. and i added follow flight mode,but it works not good........

**Comment by gregswf** [comment]
Isn't acceleration controlled already?
Would it work if there was an app calulating the gps cords on a circle of a given radius and a center point and feeding the cords as way points to the autopilot?
Then the auto pilot takes care of the speed acceleration and navigation to a waypoint?
Each waypoint would have a target heading calculated to point the circle centre.

**Comment by gregswf** [comment]
I think the yaw rotation velocity would have to be calculated too.

**Comment by liang-tang** [comment]
it's unsmooth to make a circle just via way points, but local position cords of circle can be calculated by mc_pos_control.

**Comment by uavfans** [comment]
liang-tang  name is so familiar

**Comment by szechyjs** [comment]
I would love to have the circle mode functionality of ardupilot.

http://copter.ardupilot.com/wiki/circle-mode/

**Comment by liang-tang** [comment]
i had ported the code to px4 from ardupilot, and i would commit it in a few days.

**Comment by gregswf** [comment]
@ Liang-tang, that's awesome, I can't wait to test it

**Comment by DonLakeFlyer** [comment]
Make sure to let me know when this goes in so I can update QGC.

**Comment by dagar** [comment]
Planned for v1.5.0 #3810
