### ISSUE TITLE
VTOL failsafe FW fall detection

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3823]
A quadplane should use it's ability to act as a parachute when tecs detects a major error (i.e. falling). 
@tumbili what param should be monitored from tecs and what threshold do you suggest?

**Comment by LorenzMeier** [comment]
The better detector than TECS might be the landing detector with this PR:
https://github.com/PX4/Firmware/pull/3619

**Comment by sanderux** [comment]
implemented a basic version in https://github.com/PX4/Firmware/pull/4522
