### ISSUE TITLE
SITL standard vtol, implement EKF

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3849]
and investigate strange behavior in auto mode
![vtol mission cruise](https://cloud.githubusercontent.com/assets/14801663/13305165/aa153472-db59-11e5-8fa9-bb49bb71b178.png)

[23_33_44.px4log.tar.gz](https://github.com/PX4/Firmware/files/145672/23_33_44.px4log.tar.gz)

**Comment by LorenzMeier** [comment]
Fixed with EKF2.
