### ISSUE TITLE
Need to split the acro switch into MC acro and FW stab

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3858]
Currently the same switch is used for both modes. This is bad for VTOL if you fly in manual but switch fixed-wing stabilized on later. As soon as you transition back to multicopter you'll be in acro. Happened to me a few times already, it's challenging ;)

**Comment by LorenzMeier** [comment]
:dash: Sounds fun! We need to have an informed discussion about flight modes anyway.

**Comment by tubeme** [comment]
This was confusing for me too so that's why we use the FW perm stab in the VTOL. If it is with one switch at least it should work in the same direction in both modes...

**Comment by LorenzMeier** [comment]
Release 1.5 will handle flight mode cleanup.

**Comment by kd0aij** [comment]
bugfix here: https://github.com/PX4/Firmware/pull/5288
Looks to me like the transition logic was screwed up in commander.

**Comment by AndreasAntener** [comment]
Fixed in #6567

**Comment by dagar** [comment]
@AndreasAntener could we now get rid of fw_permanent_stab or does it exist for a different reason?

**Comment by AndreasAntener** [comment]
Only works if you assign the manual switch now in the old style, because that makes stabilized the default (btw, which is also the default for us in MC to be consistent).
