### ISSUE TITLE
Gazebo standard vtol simulation broken

### ISSUE THREAD

**Issue by DroneDude123** [PX4/Firmware#3860]
The gazebo simulation is broken for the standard vtol simulation. The aircraft will not transition properly.

Steps to reproduce:
1. make posix_sitl_default gazebo_standard_vtol
2. In qgroundcontrol, load the mission at the bottom of this message. This mission consists of the following wavpoints (Takeoff, Wavpoint, Vtol Transition (Plane), Wavpoint). 
3. Switch to mission mode in QGroundControl.
4. Arm aircraft.

The aircraft will take off just fine, but it will pitch up wildly during transition and go unstable.

**Comment by DroneDude123** [comment]
[simple_vtol_mission.mission.txt](https://github.com/PX4/Firmware/files/146906/simple_vtol_mission.mission.txt)

**Comment by LorenzMeier** [comment]
Fixed on master.
