### ISSUE TITLE
Startup mode

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#3866]
I'd like the ability to startup into a non manual mode (fixed wing [airspeed](https://github.com/PX4/Firmware/pull/3861) mode). Is there a way to do this currently?
If not I was thinking of adding the ability to set the mode with a commander argument and then adding it to the end of my airframe init script. Alternatively it could be a param.

**Comment by LorenzMeier** [comment]
Already allowed non-manual on master. You can just add it. It uncovered corner cases though.

**Comment by dagar** [comment]
Are you referring to arming in non manual https://github.com/PX4/Firmware/issues/3853 or something else?
I'm talking about already being in airspeed mode by the end of bootup, preventing the user from ever seeing man or stab.

**Comment by LorenzMeier** [comment]
Yes, you can do that today on master
