### ISSUE TITLE
Bring travis builds in sync

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3867]
The Mac OS build seems to have different warnings enabled. This makes travis fail for me even though it compiles fine on my system, see: https://travis-ci.org/PX4/Firmware/builds/112058279.

**Comment by dagar** [comment]
This might just be different versions of clang. What do you have locally @julianoes 

travis-ci reports

    g++ --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.0 (clang-700.0.72)
    Target: x86_64-apple-darwin14.5.0

**Comment by julianoes** [comment]
Well it also compiles fine for the travis Ubuntu build, it's just the Mac OS that is different.

Locally I have:
```
g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
```

**Comment by dagar** [comment]
I found the problem. Wextra is being set after Wno-sign-compare which is why it's being overridden and reenabled by clang. I'll fix it.
