### ISSUE TITLE
ALTCTL arming: State of throttle state machine uninitialised

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3868]
@jgoppert This is to track the issue you found.

**Comment by dagar** [comment]
Could you describe what you saw?

**Comment by LorenzMeier** [comment]
Throttle is locked on zero until you switch to manual and back.

**Comment by AndreasAntener** [comment]
alt and posctl in landed block throttle in the pos controller.
Maybe I have missed something, but from what James experienced this is not actually an issue but the implementation is not transparent. After going into manual it is likely in takeoff so switching back in altctl will then suddenly allow throttle.

we need to fix this: https://github.com/PX4/Firmware/issues/3385
