### ISSUE TITLE
VTOL back transition mission behavior

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3871]
When performing a back transition from a mission the MC tries to return to the path.
For a smoother transition it would be better to ignore the deviation and continue towards the next waypoint.

![mission transition](https://cloud.githubusercontent.com/assets/14801663/13368059/8fb2fe9a-dce7-11e5-8ba4-d06f1ee316c7.png)

**Comment by LorenzMeier** [comment]
I think that's a non-issue. You are just looking at the aesthetics of the line, but what counts is if the vehicle did stick to the mission. You probably will want to reduce the L1 radius / length for the SITL VTOL, which will make it comply far better with the mission.

**Comment by sanderux** [comment]
I would add that this also happens in larger real missions: http://logs.uaventure.com/view/djVcLjJZChq3QsUmoBsrWh

**Comment by LorenzMeier** [comment]
It doesn't really matter. The mission logic is to track the lines between waypoints. Taking shortcuts is dangerous and unexpected.

**Comment by sanderux** [comment]
So is the FW plotting a path to start loitering? it seems to start deviating right before transition. If this is the case it could consider the upcoming transition.
