### ISSUE TITLE
VTOL: No PWM signal to aux ports on current master 

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3873]
On current master the pusher ESC does not initialize and after switching to FW (disarmed) the servos do not respond. The servo's also do not go to initial position at boot. The MC does arm at this point.

It seems like there is no signal going to the aux outputs

**Comment by sanderux** [comment]
@LorenzMeier @AndreasAntener @tumbili FYI

**Comment by sanderux** [comment]
The latest branch i tested before current master was vtol_pusher. When uploading this firmware (after several reboots to test) it did work directly on that branch.

**Comment by LorenzMeier** [comment]
Fixed on master since this morning.

**Comment by sanderux** [comment]
Confirmed, works
