### ISSUE TITLE
Add min/max/increment/unit/decimal meta data to main parameters

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3879]
@kd0aij This will fix the Android UI for you: We need to add meta data like in this commit to all major params:
https://github.com/PX4/Firmware/commit/e3853ed4e536860cc3b2f4e688f0c20eb2e2151b

```
@unit m/s
@min 0.0
@max 100.0
@increment 0.5
@decimal 2
```

**Comment by LorenzMeier** [comment]
@sanderux Can you help with that for VTOL params?

**Comment by kd0aij** [comment]
@LorenzMeier Thanks. Will there be additional buttons for increment/decrement of each individual parameter, or will there be a new screen for tuning groups of parameters?

**Comment by LorenzMeier** [comment]
It will just make using the tablet easier with a better value selector, which will apply to existing and potential new tuning screens.
