### ISSUE TITLE
Broken PWM Outputs for VTOL Master

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3889]
When using master on my 13001 Caipiroshka my ESCs do not receive the disarmed signal and nothing happens on arming.
"pwm info" gives:
```
device: /dev/pwm_output0
channel 1: 0 us (alternative rate: 400 Hz failsafe: 0, disarmed: 900 us, min: 1080 us, max: 2000 us)
channel 2: 0 us (alternative rate: 400 Hz failsafe: 0, disarmed: 900 us, min: 1080 us, max: 2000 us)
channel 3: 0 us (alternative rate: 400 Hz failsafe: 0, disarmed: 900 us, min: 1000 us, max: 2000 us)
channel 4: 0 us (alternative rate: 400 Hz failsafe: 0, disarmed: 900 us, min: 1000 us, max: 2000 us)
channel 5: 0 us (default rate: 50 Hz failsafe: 0, disarmed: 0 us, min: 1000 us, max: 2000 us)
channel 6: 0 us (default rate: 50 Hz failsafe: 0, disarmed: 0 us, min: 1000 us, max: 2000 us)
channel group 0: channels 1 2 3 4
channel group 1: channels 5 6

```

Obviously the pwm values should be 900 us and not 0 us.

**Comment by tumbili** [comment]
@kd0aij I was told to point the gun at you ;-)

**Comment by kd0aij** [comment]
fmuv1,2 or 4? At one time the kill switch was turning PWM off, but that was in "lockdown" mode.

**Comment by tumbili** [comment]
fmuv4, so Pixracer

**Comment by tumbili** [comment]
@kd0aij

**Comment by kd0aij** [comment]
sounds like your config is broken too though :-)
My VTOL is fmuv2

**Comment by tumbili** [comment]
Hm, any idea where to look?

**Comment by kd0aij** [comment]
do you have the kill switch mapped?

**Comment by kd0aij** [comment]
and your problem is similar to the one I had with channel 6 being dead, but that seemed to be a mixer textfile parsing problem.

**Comment by tumbili** [comment]
Let me check

**Comment by tumbili** [comment]
No, kill switch is not mapped

**Comment by kd0aij** [comment]
Why would arming work on a PixRacer quad, but not on VTOL? There should be no difference, should there?

**Comment by kd0aij** [comment]
There is a circuit breaker to disable the safety switch, if you don't want to use one.

**Comment by kd0aij** [comment]
This was the PR for the "painless" addition of safety switch handling: https://github.com/PX4/Firmware/pull/3827
I tested it on my PixRacer quad, and it worked there after a few false starts.

**Comment by tumbili** [comment]
Fixed, on master.
