### ISSUE TITLE
MPC Final approach land speed

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3894]
Implement parameter to set final approach altitude and land speed.
This would allow slower descend rate for the final x meters.

@LorenzMeier I propose this with a default value of 1.5m above home and around 60% land speed. Any thoughts?

**Comment by ecmnet** [comment]
What about setting the landing speed dynamically based on the altitude? I had some good results by setting the speed to 0.5 * altitude beginning with 2m and let it drop some cm above ground.

**Comment by sanderux** [comment]
I think that would only provide good results with sonar or lidar. without that you would risk touching the ground and tipping over as baro/gps altitude is not that acurate

**Comment by ecmnet** [comment]
True, I had lidar running.

**Comment by AndreasAntener** [comment]
@sanderux what you just said applies in general for this. A slow landing speed by default is good enough IMHO. A 2 phased landing approach should either be implemented with a range finder or if you fly a mission descend to a lower altitude already before the actual landing.

**Comment by sanderux** [comment]
@AndreasAntener Of course you could set a lower altitude before initiating the land. but in practice people (like me) are lazy. To land a VTOL for instance it already requires 3 mission items; Last waypoint before transition, transition and then land. Adding a forth just to decrease the land speed seems a bit much.

Most airframes can easily descend  2~3 m/s but that would give quite a big impact on landing. A RTL event by efault would even initiate a land at 60m altitude, at the current setting it would take 2 full minutes to land. If we add this parameter i think a lot of people will use that to set a higher default landing speed and safe the trouble of having to set a lot of mission items.

did i convince you? :)

**Comment by sanderux** [comment]
As for the inaccurate altitude estimation, the final approach altitude could default to 3 or 4 meters above the landing site.

**Comment by AndreasAntener** [comment]
No :) I'm not arguing about the feature, I'd like to have it. But it's unsafe to assume ground height when you actually don't know it. The landing point could be anywhere. Even with a terrain model I wouldn't do it. The only option for me here is to do that with a range finder and I would gladly support you in adding this.

**Comment by sanderux** [comment]
Granted, it's not ideal when start and end point are not on the same altitude. however; i think 9%% of the time we land on or near the same location (or at least the same altitude). Anyone who does missions landing in different locations should indeed use a range finder and we could note this when changing the land speed and/or final approach params.

The code would not assume anything, it would simply lower descent rate at a given altitude above home altitude. It doesn't change anything to the current settings, only those that specifically set this would benefit and they probably know (or have been told) what it means.

thnks for your support, i'll get to work on it :)

**Comment by dagar** [comment]
What's the conclusion here? I'd like to optionally be able to enable this.

**Comment by dagar** [comment]
Implemented.
