### ISSUE TITLE
NuttX_next_cmake branch: add ps command

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#3900]
The "ps" command depends upon having the procfs file system configured into the system:

See http://www.nuttx.org/Documentation/NuttShell.html#cmdps

**Comment by davids5** [comment]
@kd0aij  procfs added in https://github.com/PX4/Firmware/commit/ba002f9 and mounted in https://github.com/PX4/Firmware/commit/8315458e9082bea6aebe9cbb381509572aa6c85b and ps now works.
