### ISSUE TITLE
Pixracer mag cal fails on current master

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3905]
it does work on stable

```
[cal] up orientation detected
[cal] Rotate vehicle around the detected orientati
[cal] Continue rotation for 7 seconds
[cal] up side done, rotate to a different side
[cal] up side done, rotate to a different side
[cal] ERROR: Replace board
ERROR: Replace board, fault in mag 0
Excessive offsets:   0.0532,  -0.5191,  -0.4636
[cal] calibration failed: mag
```

**Comment by LorenzMeier** [comment]
Those offsets are almost hitting the absolute maximum values. Are you sure this board is fine? I widened them further on master, but in general an offset like that is indication of something not being quite right. The last case we had like that was a mag with bad solder connection.

**Comment by LorenzMeier** [comment]
Closing this. The error message is real. If it still doesn't work, replace your board.

**Comment by LorenzMeier** [comment]
@pkocmoud @nickarsov This is the 2nd Pixracer with this issue. The first was "fixed" with some hot air onto the mag.

**Comment by sanderux** [comment]
![mag cal](https://cloud.githubusercontent.com/assets/14801663/13447421/b4ef2dbe-e01b-11e5-9520-9496f3c9396d.png)

**Comment by kd0aij** [comment]
@LorenzMeier What could be wrong with PixRacer to cause the external mag cal problem?

**Comment by LorenzMeier** [comment]
There was never an issue with the external mag. The indications were all correct.
