### ISSUE TITLE
Significant overshoot in position control with 3DR Iris+, default gains

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#3910]
http://logs.uaventure.com/view/j7HnB9uzyxBv3dD4x4mkrj#Local_X_PLOT

**Comment by sanderux** [comment]
Your MC_PITCHRATE_D is almost twice the default value

**Comment by jgoppert** [comment]
Thanks for catching that! I will retest.

**Comment by jgoppert** [comment]
My max velocity was just too high.
