### ISSUE TITLE
VTOL transition altitude

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3926]
Consistent problems with increasing altitude during transition:
http://logs.uaventure.com/view/NfbHqPWzcNNTaRE5KTechg
http://logs.uaventure.com/view/hMnRrAhpzmQmnYGaTZ94M4
http://logs.uaventure.com/view/UA7KfExFy7DAuvXt4z6TwQ

This was in +- 8m/s wind, airspeed sensor had spikes now and then.

**Comment by sanderux** [comment]
![transition increasing alt](https://cloud.githubusercontent.com/assets/14801663/13548566/920c6f48-e2f3-11e5-8874-3a87d7b372b2.png)

Here's a plot of alt,  airspeed and pusher throttle. I think it is tecs that wants to convert kinetic energy to potential energy. @tumbili ?

**Comment by AndreasAntener** [comment]
Duplicate: https://github.com/PX4/Firmware/issues/3843

**Comment by AndreasAntener** [comment]
TECS is not active yet during the transition.

**Comment by sanderux** [comment]
Yep, just noticed that. any idea where this comes from?
