### ISSUE TITLE
log entries disappeared

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#3928]
10 old tree: (11mb log)
http://logs.uaventure.com/view/NfbHqPWzcNNTaRE5KTechg

recent tree: (190kb log)
http://logs.uaventure.com/view/KFFN5vsKZ82pGXcncQnGd3

No more aux outputs at least

**Comment by sanderux** [comment]
need to check revision
@tumbili what was the commit for the fix for this?

**Comment by AndreasAntener** [comment]
just rebase on master
