### ISSUE TITLE
Arm command from QGC causes "Unsupported command 400"

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3932]
Armed my 250 PixRacer using QGC tablet ui. Vehicle did arm, but firmware also spit out "Unsupported command 400" which is the arm command which did work.

**Comment by LorenzMeier** [comment]
Do you recall what flight mode this was in?

**Comment by DonLakeFlyer** [comment]
Hmm. Most likely Manual.

**Comment by LorenzMeier** [comment]
Fixed.
