### ISSUE TITLE
Adjust Pitch Sensitivity in QGC caused large twitch then recover

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3933]
- Flying 250 PixRacer
- Hovering in PosCtl
- Wanted to adjust Pitch Sensitivity to make vehicle less twitchy
- Slid the slider a slot to the right
- Vehicle did a large mid-air twitch then recovered

Quite disconcerting

**Comment by dagar** [comment]
@DonLakeFlyer Can you post a log the next time you see anything like this? Quite a lot has changed in PX4 multicopter since this has been opened.
