### ISSUE TITLE
VTOL RTL with landing in FW lands diagonally

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3936]
because it will transition to MC somewhere along the loiter circle, then start to land at home. But unlike missions it won't first shift the landing location (home).

Solution to keep the way it currently works:
Add 2 new states in RTL after LOITER that will only be used for VTOLs:
- back transition
- move to land

A simpler solution, but changes the behaviour:
- 1 new state: back transition before loiter

Maybe we even want both options. And the user can select.

**Comment by sanderux** [comment]
I think both loiter and land should be in MC mode. The default loiter radius in FW is dangerous as the area could be close to obstacles like buildings or trees.

**Comment by AndreasAntener** [comment]
Sounds good, I think we can make that the default behavior.

We should even consider setting RTL_LAND_DELAY to 0 by default now so it actually does land. Because a) the landing works great now, and b) if it triggers RTL because of a real problem this usually isn't resolved while loitering at home (speaking from experience, and then you have to let your batteries run flat..).

**Comment by sanderux** [comment]
Agreed, i'll get to work

**Comment by AndreasAntener** [comment]
@sanderux FYI, I just implemented this, will make a PR soon.

**Comment by sanderux** [comment]
@AndreasAntener i have the same behavior in the VTOL_LAND command. do you have a PR or shall i have a look at it?

**Comment by AndreasAntener** [comment]
I'll open the PR this afternoon
