### ISSUE TITLE
High vibration alert during compass cal

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3937]
Would be nice if these alerts where turned off during calibrations which require moving the vehicle around.

**Comment by kd0aij** [comment]
Hard to believe there's any "vibration" at all when doing a calibration.

**Comment by tubeme** [comment]
I get "high vibration" warning every time while calibrating the compass between step 1 and 2, ie when I flip the plane upside down. Always! Probably ATT_VIBE_THRESH is too low by default. We regularly get high vibration warnings while flying as well without any noticeable vibrations (visually as well as in the Log graphics.)

**Comment by mhkabir** [comment]
I get vibration warnings these days pretty randomly, even when just gently (smoothly) exciting the system in my hand. Did something change recently, because this didn't happen before.

**Comment by LorenzMeier** [comment]
Fixed.
