### ISSUE TITLE
mavlink UDP broadcast doesn't work on Snapdragon

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3939]
Currently, the UDP broadcast of a mavlink instance running on the Linux side on the Snapdragon fails.

This needs investigation.

**Comment by liamstask** [comment]
cannot repro this locally (I'm on master @ `v1.1.3-686-gef8d074`), broadcast works as expected. if you're not connected successfully to a network, it may fail with `Network not reachable` but once connected it's all good.

**Comment by julianoes** [comment]
@liamstask I've seen the same thing yesterday. Are you connecting to a Wifi or creating one on the Snapdragon?

**Comment by liamstask** [comment]
snapdragon is in station mode via `/usr/local/qr-linux/wificonfig.sh -s station`, so connecting to an existing network.

**Comment by julianoes** [comment]
@liamstask ok same setup for me.

**Comment by julianoes** [comment]
In @bugobliterator 's case it doesn't work but that's using AP mode, so the Snapdragon is the access point.

**Comment by LorenzMeier** [comment]
@julianoes Any news on this one, proper fix?

**Comment by julianoes** [comment]
Raised this but have not gotten a solution yet.

**Comment by julianoes** [comment]
Fixed in #4105.
