### ISSUE TITLE
New Simple Flight Mode Assignment bug 

### ISSUE THREAD

**Issue by GervaisK** [PX4/Firmware#3943]
With the new "Simple Flight Mode assignment" its very easy to assign modes to switch positions. However, PX4 doesn´t accept all choices. Example shown: Although _Altitude Control_ is chosen and showing up below, it doesn´t appear in the headline and the copter doesn´t change to _Altitude_, it stays in _Position Control_.

![discrepancy](https://cloud.githubusercontent.com/assets/17418003/13584148/62692ac4-e4b5-11e5-9b7a-8e2cd2531f76.jpg)

Further: Users are confused, that chosen _Stabilize_ is shown as _Manual_ in the headline.

**Comment by DonLakeFlyer** [comment]
The view in QGC (left arrow) is simulating flight mode selection based on channel values so you can test your settings. The firmware may in turn reject the mode change (the right arrow) so the toolbar may not change abd keep in sync. So these may not always be in sync.

**Comment by GervaisK** [comment]
True and QGC doesn´t report the change as well as the Copter doesn´t. So I´m convinced that the mode did not change.

**Comment by DonLakeFlyer** [comment]
QGC will only report flight modes changes by talking if the flight mode actually changes. It won't report simulated changes in Flight Mode config screen. As far as I can tell from the discussion things are working as they are supposed to. It may be confusing, but I'm not sure how else to show the user whether there flight mode settings are working other than simulating flight mode changes.

**Comment by GervaisK** [comment]
Don, QGC is working correct. The New assignment doesn´t.

**Comment by DonLakeFlyer** [comment]
Oh, sorry.

> Further: Users are confused, that chosen Stabilize is shown as Manual in the headline.

This is a QGC problem. It's trying to get fancy by changing naming based in multi-rotor/fixed wing. I don' think that will really work though. Can you put in a QGC issue for that.

**Comment by GervaisK** [comment]
Yes,thx.

**Comment by LorenzMeier** [comment]
Matching QGC issue: https://github.com/mavlink/qgroundcontrol/issues/2969
