### ISSUE TITLE
PX4 UM: Cannot find Icons

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#3949]
Hi guys,

I'm writing the Users Manual and I need to find this icons:

![quadrotor_x_assignment](https://cloud.githubusercontent.com/assets/12617619/13605170/efb0baca-e54e-11e5-83ea-8fc079cbd8d5.png)

I found the new style icons in the QGC github tree:

![a233260a-bb8e-11e5-9c67-5d6208b7f109](https://cloud.githubusercontent.com/assets/12617619/13605197/04398008-e54f-11e5-8192-9de14346816b.png)

But for the setup explanation i need the ones with directions and motor numbers.

Any help will be appreciated.

**Comment by dagar** [comment]
@tubeme there's now an effort to automatically generate some of this documentation. https://github.com/PX4/Firmware/pull/7019

**Comment by tubeme** [comment]
@dagar Thanks I follow the #7019
