### ISSUE TITLE
PX4 UM: Parameters Refference

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#3950]
Hello,

I'm writing the UM of PX4 and I have the following problem. Somebody depreciated all the old docs and Index from pixhawk.org. The index page is still available but it is hidden. 

So it is a very good Idea if somebody from the core team can implement the Parameters reference page in the new Users Manual tree in the Advanced Configuration Section. 

https://pixhawk.org/firmware/parameters

It is automatically generated so I cannot create it. It is madness if I have to manually change the Parameters Reference Page when new parameters are added in the development process.

Thanks

**Comment by dagar** [comment]
Fixed! https://dev.px4.io/parameter_reference.html

**Comment by tubeme** [comment]
@dagar Please can you make the Shortcut list on top of the parameters reference the same way it was in the original page?

**Comment by dagar** [comment]
Check the little thing in the top right. It should expand into a table of contents.

**Comment by tubeme** [comment]
Cool! :)
