### ISSUE TITLE
Loiter mode not working

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3964]
* Using master SITL
* Create a simple takeoff and waypoint missing in QGC
* Send, Arm, Change to Mission flight mode
* Select Auto: Loiter from the flight mode drop down

Firmware says unknown flight mode

**Comment by DonLakeFlyer** [comment]
Also see this: https://github.com/mavlink/qgroundcontrol/issues/2969

**Comment by AndreasAntener** [comment]
@DonLakeFlyer I'm using QGC 2.9.4 and firmware 1.2.0 (a few weeks back). In QGC this is called "Auto: Pause" for me, is that new? And it's working. But I know the bug you encountered, had this too a while back but don't remember with what combination anymore.

**Comment by DonLakeFlyer** [comment]
Yes "Auto: Pause" is Loiter. No idea when that changed! I don't really like the new Auto: foo naming of things. Doesn't really add much value.

**Comment by LorenzMeier** [comment]
Its necessary to do it that way because Loiter keeps APM users thinking its position control mode.

**Comment by tops4u** [comment]
@LorenzMeier Do I understand you correctly that in fact it would still be "Loiter" as in APM. If there is no mission present Auto Mission / Auto Pause would in fact loiter in place. If a Mission is present it would try to follow the mission but would be immediately be paused resulting in a Loiter as well. The Difference would be that if in Mission it would really pause/resume the Mission if switched directly to/from Mission Mode. If using any other mode it would reset the mission progress... Correct?

**Comment by AndreasAntener** [comment]
@tops4u no, Loiter in APM is position control in PX4. And the mission progress is not reset when using any other mode.

**Comment by AndreasAntener** [comment]
@DonLakeFlyer does it go into failsafe in your case (no joystick connected)? It could revert back to the mode `NAVIGATION_STATE_AUTO_RTGS` which would then show as unknown.

**Comment by DonLakeFlyer** [comment]
Yes it does go into failsafe

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Fixed in c29bfcd and on QGC master (mode indication for RTGS).
