### ISSUE TITLE
snapdragon params not being retrieved in QGC

### ISSUE THREAD

**Issue by liamstask** [PX4/Firmware#3965]
have not investigated yet, so not sure where this is failing but params are not being retrieved when the vehicle connects.

my setup is slightly non-standard in that I have hard coded my host machine's IP into `_src_addr` in `mavlink_main.cpp` and set `_src_addr_initialized = true;` to prevent subsequent broadcast's from going out. otherwise, communication with QGC appears normal.

cc @julianoes

**Comment by LorenzMeier** [comment]
Fixed, thanks!
