### ISSUE TITLE
Mission land sequence outputs strange messages

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3966]
Using master SITL
* Create simple takeoff/waypoint/land mission
* Start the mission and let it complete

After it lands, you get:
* Critical: mission finished loitering
* Critical: failsafe mode on
* Critical: no RTL when landed
* Critical: RTL: completed, landed
* You are left in Auto: Return to land mode

**Comment by DonLakeFlyer** [comment]
More strangeness. If your mission ends at a waypoint (not a land item) it will still do an RTL after it hits the last waypoint!

**Comment by LorenzMeier** [comment]
Only if you have no RC control, which is perfectly fine / correct. Use a joystick to avoid that.

**Comment by AndreasAntener** [comment]
The message sequence is unfortunately the logic outcome of the states it goes through, I don't think that's a problem.
For your second issue, instead of having a joystick, enable data com loss: COM_DL_LOSS_EN

**Comment by DonLakeFlyer** [comment]
> Only if you have no RC control, which is perfectly fine / correct. Use a joystick to avoid that.

How do I controll the vehicle with only a tablet?

**Comment by AndreasAntener** [comment]
@DonLakeFlyer see my last comment, try COM_RC_IN_MODE = 1 and COM_DL_LOSS_EN = 1

**Comment by LorenzMeier** [comment]
I have that already on master, closing.
