### ISSUE TITLE
MC_PITCHRATE_I is missing a digit

### ISSUE THREAD

**Issue by sn0west** [PX4/Firmware#3968]
@DonLakeFlyer said it's a firmware thing...

MC_PITCHRATE_I has only 3 digit x.xx instead of 4 like MC_ROLLRATE_I x.xxx. 
Could you please fix that, so I can have a better scaling for MC_PITCHRATE_I.

![bildschirmfoto 2016-03-09 um 12 48 13](https://cloud.githubusercontent.com/assets/9918649/13663104/814f355a-e69f-11e5-97a8-e29c701cae88.png)

QGC 2.9.4 Daily Build that I downloaded the 29.02.16

**Comment by LorenzMeier** [comment]
Fixed in 6b89ce0b7f677c85748db97b889972031b8b1248. Thanks! You need to flash master onto the autopilot via QGC or get a QGC update in the next days to get new meta data which contains the fix.
