### ISSUE TITLE
AUTO MISSION - only one time possible

### ISSUE THREAD

**Issue by sn0west** [PX4/Firmware#3978]
A mission can only be activated once. Why? 
I do activate it by switch and when the mission is finished with a land, I desarm the copter, switch back to stabilized, arm it and want to start the mission but it only take off and stay in pause mode. Why?

**Comment by sn0west** [comment]
Normal or not? Anyone on this?

**Comment by dagar** [comment]
It's not just you. In the next version of QGroundControl you'll be able to click a waypoint to restart the mission.
When would you like the mission to reset?

**Comment by DonLakeFlyer** [comment]
I think it should reset after you've landed.

**Comment by sn0west** [comment]
The copter doesn't desarm, after landing. So I don't know what makes more sense. To desarm after landing and the reset the mission or after landing. But then you actually still in thr mission. So in my opinion it's better to disarm after landing and then reset it.

**Comment by AndreasAntener** [comment]
I'd suggest we reset when disarming, a mission could include a landing.

**Comment by DonLakeFlyer** [comment]
> The copter doesn't desarm, after landing.

There is a parameter to turn that on. It's is not currently the default, but it should be.

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you look into this?

**Comment by AndreasAntener** [comment]
Fixed on master, mission reset when disarming.
