### ISSUE TITLE
PixRacer Mag Calibration fails after the 9250 MAG support was added.

### ISSUE THREAD

**Issue by pkocmoud** [PX4/Firmware#3982]
With the addition of the new MAG source, a dynamic method for determining if a MAG is healthy needs to be implemented.

![image](https://cloud.githubusercontent.com/assets/7053372/13709241/7801a116-e778-11e5-8cfe-28180d172d5d.png)

**Comment by kd0aij** [comment]
@pkocmoud  fix to allow you to calibrate the 9250 mag
https://github.com/PX4/Firmware/pull/3988

**Comment by LorenzMeier** [comment]
Worked around on master.
