### ISSUE TITLE
SITL (jMAVSIM)  broken on master

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3983]
@tumbili Would be great if you could have a look as soon as feasible.

To repro:
```
make posix jmavsim
pxh> commander takeoff
```

**Comment by AndreasAntener** [comment]
@LorenzMeier also gazebo SITL stopped working for me on master, Iris and Standard VTOL. Takeoff makes it crash pretty much right away.

**Comment by AndreasAntener** [comment]
https://github.com/PX4/Firmware/issues/3990

**Comment by LorenzMeier** [comment]
Fixed
