### ISSUE TITLE
Flight Mode, RC Channel parameter meta data cleanup

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#3987]
* Flight mode names should not be in "ALL CAPS". 
* "Rc Channel ##" seems a bit noisy as well. Why not just "Channel ##", or even just "##"?

As short as possible, but still conferring correct meaning to user is key here. The reason is that long strings for these causes issues on small displays like phones. So whatever can be done would be appreciated.

Once the naming is worked out, QGC needs to change to be consistent with flight mode naming for the flight mode drop down.

Related to these QGC issues: 
https://github.com/mavlink/qgroundcontrol/issues/2993
https://github.com/mavlink/qgroundcontrol/issues/2969

**Comment by dagar** [comment]
Ideas:
AUTO:PAUSE -> Hold
AUTO:RTL -> Home
AUTO:MISSION -> Nav
ALTCTL -> Altitude
POSCTL -> for fixedwing position doesn't really make sense, maybe Heading or Track

**Comment by DonLakeFlyer** [comment]
I'd try to be as close to ArduPilot as possible since there are a decent number of people coming across now. Which means the main confusing is around Loiter/PosCtl.

**Comment by LorenzMeier** [comment]
There are more DJI users and we want to steal from their user base, not from APMs.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Changed on master to:
```
 * @value 0 Manual
 * @value 1 Altitude
 * @value 2 Position
 * @value 3 Mission
 * @value 4 Hold
 * @value 10 Takeoff
 * @value 11 Land
 * @value 5 Return
 * @value 6 Acro
 * @value 7 Offboard
 * @value 8 Stabilized
 * @value 9 Rattitude
```
Please close this once you have the renaming in QGC In.

**Comment by LorenzMeier** [comment]
Ah and I shortened the channels.

**Comment by DonLakeFlyer** [comment]
Awesome. I'll update QGC. Great point on DJI.

**Comment by DonLakeFlyer** [comment]
Also did you bump to minor version number so it will override older meta data?

**Comment by LorenzMeier** [comment]
I just did on master. No pull against QGC in yet. Probably makes most sense if you do this.

**Comment by DonLakeFlyer** [comment]
The minor version number bump is in the firmware parameter python parser, not QGC. Whenever you have parameter meta data changes which you want to override previous meta data you need to bump that minor number.

**Comment by LorenzMeier** [comment]
And that's what I did. Someone still needs to copy the file across, because your primary user base is using Android, and those don't get it from the Firmware.

**Comment by DonLakeFlyer** [comment]
Ah, yeah. Good point. We need to change that so meta data can download from the web based on vehicle settings.
