### ISSUE TITLE
Gazebo SITL broken

### ISSUE THREAD

**Issue by crzx5** [PX4/Firmware#3990]
Iris model takes off, then immediately crashes.

**Comment by locustcox** [comment]
+1. To replicate:

First run make posix_sitl_default gazebo
Then, type "commander takeoff"
The quadrotor will shoot up into the sky, fall back down, bounce, and repeat a few times before finally flipping over.

**Comment by LorenzMeier** [comment]
Duplicate of #3983, closing.
