### ISSUE TITLE
Bat_V_Scaling assignment / Battery Voltage calibration doesn´t work.

### ISSUE THREAD

**Issue by GervaisK** [PX4/Firmware#3992]
No matter, what is changed @ BAT_V_Scaling, Voltage display doesn´t change. 

![1 bat voltage calibration](https://cloud.githubusercontent.com/assets/17418003/13721595/375e3688-e82c-11e5-92c6-14bda953b252.jpg)

![2 bat voltage calibration](https://cloud.githubusercontent.com/assets/17418003/13721597/3b69f582-e82c-11e5-8607-e9360b3a866e.jpg)

**Comment by LorenzMeier** [comment]
The negative -1 value is to indicate "default". If you use a positive number it will change.

**Comment by GervaisK** [comment]
Ok,thx. Since this is not obvious, could we set a 0.011 (or whatever is assigned, for me its 0.0109 there ?

**Comment by LorenzMeier** [comment]
No, because it varies per board, and the default value tells it to use the board default. What we could do is to create a documentation page for it.
