### ISSUE TITLE
param @unit cleanup

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#3996]
I'm going to review all param @unit usage to enable QGroundControl unit conversions. https://github.com/mavlink/qgroundcontrol/pull/3007

@DonLakeFlyer @LorenzMeier  Let's discuss what we'd like to use because there's a lot of inconsistency.

deg/degree/degrees/degrees * 1e7
m/meter/meters
s/second/seconds/ms/milliseconds/us
m/s/s m/s^2
Hz 1/s
% percentage

When to use None or blank?
@unit SD?

Is there a better way to handle boolean?
 * @unit enum
 * @value 0 Disabled
 * @value 1 Enabled
 * @min 0
 * @max 1

**Comment by DonLakeFlyer** [comment]
deg, m, sec, ms, us, m/s/s, hz, %

You could mark @unit boolean and I can pick that up and turn it into a an enum on the QGC side.

**Comment by dagar** [comment]
Thanks, I'll start doing this

     @unit boolean

equivalent to

     @unit enum
     @value 0 Disabled
     @value 1 Enabled
     @min 0
     @max 1

**Comment by LorenzMeier** [comment]
Closing this as the pull is in. Please send more PRs if you find more stuff.
