### ISSUE TITLE
Voltage indication wrong for Pixracer when running with ACSP4

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4001]
@kd0aij It would be great if you could do some bench tests on the voltage output and adjust the scaling value here: https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensors.cpp#L868

**Comment by kd0aij** [comment]
rechecked the scale factor. My test equipment says the voltage reading has better than 1% accuracy

**Comment by timoski** [comment]
There is a bug at line 929. https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensors.cpp#L929.
It sets the scaling for the voltage but should be the scaling for the current!

**Comment by kd0aij** [comment]
That bug would only be exposed if the configuration were not for PX4FMUxxx or AEROCORE. And then only if the current scaling parameter were negative. It's an easy one to fix though; a PR would have been less effort than writing this comment :)

**Comment by kd0aij** [comment]
https://github.com/PX4/Firmware/pull/4143

**Comment by julianoes** [comment]
Can now be closed, right?
