### ISSUE TITLE
IO doesn't load again if mixer file has 8 outputs 

### ISSUE THREAD

**Issue by holesond** [PX4/Firmware#4006]
Almost the same problem as #2113, results in boot incomplete. I used the IOpass.main.mix file (for a rover). Removing the last 3 lines from IOpass.main.mix (reducing to 7 channels) and saving it on the MicroSD card into etc/mixers solves the problem for me.  Pixhawk firmware version 1.2.0.

**Comment by LorenzMeier** [comment]
Thanks for reporting!

**Comment by LorenzMeier** [comment]
We fixed this on master.
