### ISSUE TITLE
MC: Support for retracts

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#4007]
AFAIK electric retracts are currently not supported for Multicopters. When Starting or Landing in Auto Mode (Mission or while RTL) support for retracts would be desirable. I.e. if RTL is issued because of RC Problems the pilot my not be able to lower Retracts while RTL. Same goes for Mission Mode where the Retracts can not be programmed in the Mission. 

Proposal to make an AUX Output assignable to support retracts (as it is currently done for Gimbal or Shutter control). AUTO Modes would then control this Output after takeoff and prior to landing.

**Comment by marcmarcet** [comment]
Hi,

I'm pretty new to pixhawk, but just to confim, there is no way to setup retracts? (I'm using qgroundcontrol) for example, if I conect them to AUX 4? I have managed to configure them this way with APM, but I'm trying to do it now with PX4

**Comment by tops4u** [comment]
See above Issue #4276 , this is foreseen for Version 1.5 of PX 4.
