### ISSUE TITLE
Rename vision_position_estimate to generic_position_estimate

### ISSUE THREAD

**Issue by locustcox** [PX4/Firmware#4028]
This is a request for future versions of px4 firmware/mavros/mavlink. 

It would be nice to have a generic position estimate topic to broadcast position estimates that do not provide velocity or a z estimate. 

E.g. A pose2D estimate coming from laser_scan_matcher running in ROS. A pose2D only gives x,y, and heading estimates (which makes sense, since a 2D lidar can't give a z estimate).

**Comment by mhkabir** [comment]
Yep, we can do this definitely. This is on my list of refactoring as part of work on EKF2. We'll also support using the full covariance from the external source.
