### ISSUE TITLE
att_estimator_q rate estimation noise

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#4031]
plot of pitchRate from gyro0,1 and attitude estimator (2016-02-20, FMUv4, git version 0a4d0f6e):
![rateestimationnoise](https://cloud.githubusercontent.com/assets/2300221/13864389/b4534bfe-ec66-11e5-8480-5434b7f3cb26.png)

**Comment by kd0aij** [comment]
something is very wrong with a later log (2016-03-11, FMUv4, git version b7a2e5aa):
![rateestimationnoise](https://cloud.githubusercontent.com/assets/2300221/13864502/71e1a0c6-ec67-11e5-8dd1-4817551633c9.png)

**Comment by jgoppert** [comment]
Were you running a position estimator at the time? I've seen some bad attitude estimation result from acc comp when my position estimator had a bad parameter.

**Comment by LorenzMeier** [comment]
Would be a good idea to disable acceleration compensation for a test. And to test EKF2 in comparison.

**Comment by kd0aij** [comment]
After fixing the bugs in sdlog2, I find that the Q attitude estimator appears to predict the future:

![rateestimation](https://cloud.githubusercontent.com/assets/2300221/13886417/5efa46bc-ecfc-11e5-989e-5347f809307a.png)

**Comment by kd0aij** [comment]
actual flight with more accurate timestamping in sdlog2:

![rateestimation](https://cloud.githubusercontent.com/assets/2300221/13892233/97e4c370-ed1b-11e5-8cea-4739e0cd50a8.png)

perhaps there is a feedforward or derivative term in the rate estimation which is a bit too large

**Comment by kd0aij** [comment]
hovering with pitchRate near zero:

![hovering](https://cloud.githubusercontent.com/assets/2300221/13892571/d00d6584-ed1d-11e5-90ca-1d06ab18258a.png)

**Comment by LorenzMeier** [comment]
Does rate control feel better when you switch the Q estimator to just pass on the best voted gyro rate instead?

**Comment by kd0aij** [comment]
I haven't tried that. By "switch" you mean modify the code?

**Comment by LorenzMeier** [comment]
Yes, in attitude_estimator_q copying the gyro values (and subtracting the offset) instead of using the filter's own estimate.

**Comment by kd0aij** [comment]
I'll give that a try. Regarding detailed analysis of the signals, wasn't there a complete rework of sdlog2 underway last summer? I don't trust the sdlog2 timestamps or the plots generated by FlightPlot.

**Comment by LorenzMeier** [comment]
The rework went to the back burner due to lots of other ongoing things. Its essentially ready for integration and you would be most welcome to pick it up. We won't be able to pick it up for another 4-8 weeks until I have staffed all open positions.

**Comment by kd0aij** [comment]
I'd be willing to work on that; I have a number of things on hold that require good quality logs. Is there a branch in PX4/Firmware?

**Comment by LorenzMeier** [comment]
This is ready for testing: https://github.com/PX4/Firmware/pull/2780. The most recent flight plot version should be able to read and graph the resulting file.

**Comment by kd0aij** [comment]
@LorenzMeier I tried to rebase https://github.com/PX4/Firmware/pull/2780 on current master, but there were many conflicts. WIll it require a CMake expert solve that problem?

**Comment by jgoppert** [comment]
If you want me to take a look, let me know.

**Comment by kd0aij** [comment]
@jgoppert I'd appreciate advice on how to get https://github.com/PX4/Firmware/pull/2780 rebased on current master, since I'd like to use the new logging on FMuV4 to test ACRO mode performance

**Comment by dagar** [comment]
@kd0aij squashing it together and merging to master wasn't so bad, but something is still broken. I pushed the branch uORB_autogeneration_rebase to the main repo. Do you want to try and get it working?

https://github.com/PX4/Firmware/compare/uORB_autogeneration_rebase?expand=1

**Comment by LorenzMeier** [comment]
Fixed.
