### ISSUE TITLE
Geofence with polygon seem no more supported

### ISSUE THREAD

**Issue by MikaelFerland** [PX4/Firmware#4040]
@dagar Do you think that can we make it work again? Because it pretty useful to build a limit around a mission.

**Comment by dagar** [comment]
It's still there, but not exposed in QGC. Have you tried this? https://pixhawk.org/users/geofence

**Comment by MikaelFerland** [comment]
Yes, I tried this abd I searched for GF_ON in QGC in parameter list. Do I
have to activate it in the startup file in the px4? Do the path will be
create as well when GF_ON will be set to 1?

**Comment by dagar** [comment]
GF_ON was replaced with GF_ACTION. Can you try it again with GF_ACTION set to 1 which will log the geofence violation in the mavlink console.

**Comment by MikaelFerland** [comment]
Ok perfect, I will test it tomorrow during flight. Thank you for the update. :smile:

**Comment by MikaelFerland** [comment]
Ok, I've tested the geofence, but I got "Critical: Geofence violation for waypoint 2" error when I add a change speed waypoint. This have been done here https://github.com/PX4/Firmware/pull/3567.

**Comment by dagar** [comment]
Should be a quick fix to update the mission feasibility checker for NAV_CMD_DO_*.

https://github.com/PX4/Firmware/blob/b323908fc508c400549a8feaae7085c99818b21f/src/modules/navigator/mission_feasibility_checker.cpp#L165

**Comment by MikaelFerland** [comment]
You are kind of very effective, I was looking how I could implement that, but you have already done done fix so. Thank you.
