### ISSUE TITLE
Setpoint_raw does not appear to be working properly

### ISSUE THREAD

**Issue by locustcox** [PX4/Firmware#4049]
Hello, 

I'm trying to control both Vx, Vy, and Pz using the mavros setpoint_raw plugin.

In my test application, I do the following:
1. Advertise a setpoint_raw/local msg.
2. Set the target_mask to ignore all except IGNORE_PZ, IGNORE_VX, and IGNORE_VY.
3. Start streaming setpoints.
4. Sucessfully put the quadrotor into offboard mode and arm.

At this point, the quadrotor just sits there and ignores my setpoints. The only way I can get it to work is if I remove the IGNORE_VZ, and start streaming Vz as well. However, I thought the point of setpoint_raw was to allow mixing so that the altitude controller could be used for Z, and the velocity controller could be used for X and Y.

Perhaps there's just a misunderstanding on my point as to what goes on behind the scenes on of setpoint_raw? If there is a better way to do this (including any additional code that should be written/modified on the ROS or PX4 side), please let me know.

Thanks!

**Comment by LorenzMeier** [comment]
Sorry we didn't see this earlier - closing as stale.
