### ISSUE TITLE
VTOL Auto Mode: Discontinuity in Set Position When Switching to Auto Mode

### ISSUE THREAD

**Issue by nkhoit** [PX4/Firmware#4050]
There is a discontinuity in setting the position when flipping into Auto mode. You can see a peak in roll angle SP before the motors are on in the attached logs. 

Plots: http://logs.uaventure.com/view/zE2mhs594poGAfypyR2HFC
Log: http://logs.uaventure.com/logmuncher/charts/zE2mhs594poGAfypyR2HFC/logmuncher.log

**Comment by sanderux** [comment]
From your plot it seems you have another mode in between switching from manual to auto. i think it is related to that, can you verify?
