### ISSUE TITLE
PWM arming ramp not working anymore

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#4056]
@julianoes do you have a quad sitting around? Addressing the author of `pwm_limit.c` :)

I'm puzzled by the arming ramp because it seems it should do the ramp but actually all my logs tell me something else. It starts right off with a high PWM value.

![screen shot 2016-03-22 at 14 44 41](https://cloud.githubusercontent.com/assets/5750020/13953520/a39165ba-f03c-11e5-893e-8d0e007d5f28.png)

**Comment by kd0aij** [comment]
seems related to https://github.com/PX4/Firmware/issues/3976

**Comment by julianoes** [comment]
@AndreasAntener this has been fixed recently, or am I wrong?

**Comment by AndreasAntener** [comment]
I wouldn't know, did you check a recent master log? :)

**Comment by julianoes** [comment]
Nevermind then :)

**Comment by mhkabir** [comment]
Closing as stale.
