### ISSUE TITLE
EKF about angular acceleration !!

### ISSUE THREAD

**Issue by bdai1412** [PX4/Firmware#4062]
Does anyone knows the theory of this formula : wak =[wax;way;waz]+Ji(-cross([wax;way;waz],J[wax;way;waz]))*dt, where 'wak' means the value of angular acceleration on time k. '[wax; way; waz]' means angular acceleration on time k-1. 'Ji' is the Inverse matrix of the Inertia 'J'.
the whole code can be find in px4\Firmware\src\modules\attitude_estimator_ekf/AttitudeEKF.m

**Comment by LorenzMeier** [comment]
This is not a software issue - please refer to the matlab files in the same directory.
