### ISSUE TITLE
Disarming inflight on CUSTOM_MODE_ENABLED

### ISSUE THREAD

**Issue by pickledgator** [PX4/Firmware#4066]
In commander.cpp, there's a required check for an arming transition and I'm noticing that sending command longs with the CUSTOM_MODE_ENABLED flag is tripping the arming transition to disarm in flight. Specifically, line 673 of commander.cpp: 

```
bool cmd_arm = base_mode & MAV_MODE_FLAG_SAFETY_ARMED;
arming_ret = arm_disarm(cmd_arm, mavlink_fd, "set mode command");
```

Should this check be wrapped in an if statement like the rest of the base_mode checks so that it only executes if a MAV_MODE_FLAG_SAFETY_ARMED flag is sent as param1?

**Comment by dagar** [comment]
It's a bitfield which contains the arming state. You can first copy it from the HEARTBEAT before sending MAV_CMD_DO_SET_MODE. There are other messages you can use for initiating takeoff, land, mission, rtl, loiter which don't involve this.

**Comment by julianoes** [comment]
Related to: https://github.com/mavlink/mavlink/pull/629

**Comment by julianoes** [comment]
Since the mavlink change went in, I should remove this:
https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L721

**Comment by dagar** [comment]
Yes! Thank you.
