### ISSUE TITLE
Tuning sliders (e.g Position control sensitivity) don´t keep their position, return to left att.

### ISSUE THREAD

**Issue by GervaisK** [PX4/Firmware#4067]
No problem to adjust them, but once you leave the tuning page and return, they are back @ left position.
Furthermore, it would be great, if it would be possible to assign them by choice to an Aux channel (potentiometer), so in flight tuning would be easier.

**Comment by DonLakeFlyer** [comment]
This is in QGC I assume. This should be a QGC issue.

**Comment by GervaisK** [comment]
Thx. Do I have to close this, and place it @ QGC issues, or wait till its sure ?

**Comment by DonLakeFlyer** [comment]
Tuning sliders are just changing parameters, so nothing to do with firmware directly. You'll need to close this and reopen on the QGC side.
