### ISSUE TITLE
Safety Page (Failsafe Action) : No (visible) option to disable RTH

### ISSUE THREAD

**Issue by GervaisK** [PX4/Firmware#4069]
There are situations where RTH action (climb and return) is not desired, or even dangerous (e.g. @ flights within GNSS shaded environments  or with obstacles above, testflights within urban envionments,vulgo backyard)
 
The PX4 stack doesn´t (visibly) offer disabling of RTH (anymore ?) . 

**If LAND would be offered as Failsafe action** (on RC Transmitter loss, and/or telemetry signal time out), the above mentioned wouldn´t matter. 

PS: Again, I´m not sure if this is an PX4 stack or an QGC issue.

**Comment by LorenzMeier** [comment]
Yes, we need to fix up the UI in a number of ways to make this easier to configure.

**Comment by LorenzMeier** [comment]
Fixed.
