### ISSUE TITLE
VTOL still increases altitude during front transition

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4079]
http://logs.uaventure.com/view/JRG4pRghKoV3RK8eS3o75k#Local_Z_PLOT

Note: this log also has a yaw issue during front trans but thats unrelated (from vtol_takeoff command)

**Comment by sanderux** [comment]
In SITL the climb can be "solved" by setting VT_FW_PITCH_TRIM to -0.25
/cc @AndreasAntener

**Comment by AndreasAntener** [comment]
This log shows that the Z velocity setpoints during transitions are negative, -1.2 m/s. That's the reason it climbs. Most likely this has something todo with the vtol takeoff/land items.

**Comment by sanderux** [comment]
SITL on master also climbs, if you set transition airspeed to 20 it will climb 20m and then timeout

**Comment by sanderux** [comment]
This is from SITL on master: 
Red = Pitch, Green = PitchSP
![image](https://cloud.githubusercontent.com/assets/14801663/14062528/8ef1ddec-f3a2-11e5-9560-06defd811a75.png)

**Comment by tumbili** [comment]
@sanderux Is this still up to date? Do you experience this problem in real flight?

**Comment by sanderux** [comment]
Not on the first prototype of the deltaquad. Maybe on the new one. Fw pos ctl still needs to be enabled. Ada made a start with that

**Comment by tumbili** [comment]
Fixed in #4521
