### ISSUE TITLE
Feature request additional plane flight mode

### ISSUE THREAD

**Issue by jcooper21** [PX4/Firmware#4082]
I would like to add to this to discussion.  A flight mode similar to FBWA in APM would be highly beneficial. This should almost be the a default mode as a novice person has a high chance of crashing planes without pitch and roll being limited and a stall prevention active. It makes it easy and stress free to fly which is important all around from beginner to Proffessional.

**Comment by LorenzMeier** [comment]
Just use altitude control (or position control for higher levels of assistance).

**Comment by dagar** [comment]
I believe FBWA = stabilize and FBWB = altitude control.
