### ISSUE TITLE
MC: Won't start after arming (1.2 Stable)

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#4083]
Second time yesterday I had the problem, that after pushing the Safety Switch and after Arming by RC Command (both confirmed by the Buzzer) on a AUAV-X2 Board I wanted to take off. But while pushing Throttle up just nothing happened. Several Arm/Disarming did not help. Only remove Power and a complete Reboot let the Kopter take off. Sadly no GroundStation was connected. Take off was attempted in all cases in Stabilized Mode, ESC are properly connected and stopped Beeping the PWM Signal Lost after Boot was complete. PX4 1.2 Stable was running. 

Log Files attached. Maybe it would be an Improvement to Save Messages also in case of a non successful flight, as only the successful Flight after Powercycling was logged with a Messages Log. 

[UnableToFlyLogs.zip](https://github.com/PX4/Firmware/files/190483/UnableToFlyLogs.zip)

**Comment by LorenzMeier** [comment]
@tops4u Yes, the log was related to your issue.

**Comment by LorenzMeier** [comment]
@tumbili The issue he has is likely related to the land detection state when arming outside of manual. Can you have a look at this with @julianoes ? It looks like he had the same issues yesterday.

**Comment by LorenzMeier** [comment]
@tumbili To repro: arm in althold, then try to take off.

**Comment by tops4u** [comment]
Just to comment, I'm pretty sure that the FM Switch was in Stab Mode while Arming, since I check all Switches when switching on Transmitter and powering vehicle. Possibly I moved the Vehicle after pushing the safety Switch, but surely before Arming via RC.

**Comment by xn365** [comment]
[https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1274]
When we disarmed in non-manual modes,we are in landed state.Vertical position setpoint always set to zero in landed state,so we cant take off in non-manual modes.

**Comment by LorenzMeier** [comment]
@xn365 Thanks! I have a patch I'll send in a sec which should address this.

**Comment by LorenzMeier** [comment]
This is all fixed.
