### ISSUE TITLE
BirdsEyeView FireFLY6 VTOL yaws automatically in hover

### ISSUE THREAD

**Issue by kPanesar** [PX4/Firmware#4090]
@tumbili I did a quick hover test with the FireFLY6 on the PX4 flight stack. The FireFLY6 keeps yawing to the right (like spinning vigorously in hover) and I'm not sure why. While examining the [log](http://logs.uaventure.com/view/X7gL7i6frhVpVbezqH9HEK#Actuators_PLOT) I see that while 3 of the motors are spinning at a high rpm, the other three are not. 

I can see all the RC channel values properly in QGC. Also, I have channel 1 mapped to throttle but the log shows channel 3 changing.Not exactly sure if it's a configuration error or a bug.

**Comment by mhkabir** [comment]
Can you give us a flight log please? It's likely an estimation issue.

**Comment by kPanesar** [comment]
@mhkabir Yes, it's linked in the description.

**Comment by LorenzMeier** [comment]
@kPanesar Your log looks like the motor assignment or prop directions are wrong. Did you confirm against the build instructions here?

https://pixhawk.org/platforms/vtol/birdseyeview_firefly

**Comment by kPanesar** [comment]
@LorenzMeier Hmm all the motors are spinning in the right direction with the top propellers spinning CCW and the bottom ones spinning CW. I also thought about having the motor ports mixed up somehow but it seems unlikely as I'm able to roll left and right and pitch forwards and backwards fine. Could the motor ports still be incorrect?

**Comment by LorenzMeier** [comment]
Sure, anything could be mixed up given your output.

**Comment by kPanesar** [comment]
@LorenzMeier Alright, I'll take a look at the motor assignments again and get back to you hopefully this coming Saturday.

**Comment by kPanesar** [comment]
Update: I did indeed have the motors mixed up. I was able to do a stable hover with the default parameter values (the ones for the high-efficiency bundle cause oscillations). Thanks for your help, everyone!
