### ISSUE TITLE
Add mission items to sdlog

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4094]
It would be nice to have the ability to log / extract the mission that was loaded

**Comment by sanderux** [comment]
@AndreasAntener are you still panning to implement this?

**Comment by dagar** [comment]
You can get a lot of through this GPSP. What else would you like to see?
We should make sure whatever you need is in logger.

**Comment by sanderux** [comment]
Mission commands and altitude

**Comment by dagar** [comment]
I'm guessing you're aware of GPSP type and altitude, but want to see what the actual mission item values were before going through navigator?

**Comment by sanderux** [comment]
yes, but mostly i want to see commands and plot the way the mission was, also if it fails

**Comment by dagar** [comment]
How could this fit in with logger? We never publish the mission items.

**Comment by AndreasAntener** [comment]
I guess we should add a new topic and log message. And also add a new log message for commands if we're already on ;)

**Comment by dagar** [comment]
Is what we have in logger sufficient?
