### ISSUE TITLE
Add file meta info for release builds and branches

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4097]
@dagar This is to track the discussion about meta data for builds. The idea from @DonLakeFlyer is that we create a JSON file in Travis which then can be fetched by QGC and displays individual releases and current branches for users. This will make it a lot easier for users to understand what version they are using.

**Comment by DonLakeFlyer** [comment]
Here is the dissussion: https://github.com/mavlink/qgroundcontrol/issues/2797

**Comment by dagar** [comment]
What do you want to include?

current master/beta/stable + releases (vX.Y.Z tags)?

**Comment by LorenzMeier** [comment]
Yes, exactly that.

**Comment by dagar** [comment]
@DonLakeFlyer @LorenzMeier did we ever settle on the format?
