### ISSUE TITLE
MAVLink app: mavlink_pub orb_advert's declared on stack don't work

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4098]
@jgoppert This is to track the issue you had with logging. I'll try to repro.

**Comment by LorenzMeier** [comment]
@jgoppert This might be a QGC issue.

**Comment by jgoppert** [comment]
Thanks for looking into it. I was using 2.9.4.

**Comment by LorenzMeier** [comment]
This is working for me on current master with current master QGC.

**Comment by jgoppert** [comment]
Yeah, works for me now too, odd. Thanks.

**Comment by jgoppert** [comment]
This hasn't gone away, it just works in SITL. I suspect when LPE was modified for the new format, that there is some issue on nuttx with putting the mavlink pub in a class that is created on the stack? Any ideas @LorenzMeier? I'm going to try putting pub declaration in global context and see if that works. 

```c++
__EXPORT void mavlink_vasprintf(int severity, orb_advert_t *mavlink_log_pub, const char *fmt, ...)
{
	// TODO: add compile check for maxlen

	if (!fmt) {
		return;
	}

	if (mavlink_log_pub == NULL) {
		return;
	}

	struct mavlink_log_s log_msg;

	log_msg.severity = severity;

	va_list ap;

	va_start(ap, fmt);

	vsnprintf((char *)log_msg.text, sizeof(log_msg.text), fmt, ap);

	va_end(ap);

	if (*mavlink_log_pub != NULL) {
		orb_publish(ORB_ID(mavlink_log), *mavlink_log_pub, &log_msg);

	} else {
		*mavlink_log_pub = orb_advertise(ORB_ID(mavlink_log), &log_msg);
	}
}
```

**Comment by jgoppert** [comment]
@LorenzMeier Yeah, moving it from the class to the lpe cpp file in global context fixed it, just a heads up, might happen elsewhere.

**Comment by julianoes** [comment]
@jgoppert: do you have an explanation? I don't understand why this happens. Which platforms does it effect?

**Comment by LorenzMeier** [comment]
Without having read the diff I'm pretty sure its because James allocated the publications in a different thread context than where they were used to publish.
