### ISSUE TITLE
Track down "configuration error" messages

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4102]
@kd0aij Pointers appreciated!

We're trying to find all remaining cases where the system refuses the arm without really telling the user why.

**Comment by LorenzMeier** [comment]
User report:
![error_zps2e1dagz8](https://cloud.githubusercontent.com/assets/1208119/14105933/c3275700-f5ae-11e5-980c-f1268400f464.JPG)

**Comment by tumbili** [comment]
@LorenzMeier Is this in SITL or in real?

**Comment by LorenzMeier** [comment]
On a VTOL system by @geoffreybainathsah.

**Comment by geoffreybainathsah** [comment]
Hi Guys
to clearify this.
I have a 3DR pixhawk, GPS unit, 3DR power module and digital airspeed sensor
Futaba R7008 runnin on sbus (mode2)
I went through all the sensor steps and managed to get everything green.
After connecting the lipo battery and trying to arm i get the messae "config error"
![error2](https://cloud.githubusercontent.com/assets/17955516/14123710/8d1aa12e-f60a-11e5-935e-9c49e2050102.JPG)

**Comment by tumbili** [comment]
@sanderux You think you could try to reproduce this?

**Comment by sanderux** [comment]
I will try, have not seen it before though. @geoffreybainathsah could you export your params and upload here as zip?

**Comment by geoffreybainathsah** [comment]
thanks for lookin at this guys
uploading a ZIP is not supported but i managed to upload it to outlook one drive
<iframe src="https://onedrive.live.com/embed?cid=A3E2D1820187FC2A&resid=A3E2D1820187FC2A%21817&authkey=AMfFMQWr4OXqTEA" width="98" height="120" frameborder="0" scrolling="no"></iframe>

**Comment by LorenzMeier** [comment]
Fixed this.
