### ISSUE TITLE
VTOL: Quad Throttle problem.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#4103]
We had about 10 smooth transitions today. After the latest corrections to the transitions it performed very well.

But we still have a problem with the throttle response in quad mode. It is obvious right after back transition.

We fly only Manual for now.

We push the throttle to max at the end of the flight, because the quad started dipping. I see that the ThrottleSP responds to the Throttle RC input. But then when I check the "us" that the pwm OUT is giving the motors... it is waaaay too low on the basis of what the SP is.

![throttle problem](https://cloud.githubusercontent.com/assets/12617619/14105326/96cb1548-f5b3-11e5-8e07-514120471bd5.png)

![throttle problem zoom](https://cloud.githubusercontent.com/assets/12617619/14105327/9a86a166-f5b3-11e5-827d-961499a89959.png)

I see it gave the most 1600us to the ESC of the quad with exception of two spikes. Which is not OK.

![us output](https://cloud.githubusercontent.com/assets/12617619/14105328/9f8fe5dc-f5b3-11e5-9708-28839f3dbb2b.png)

![us output zoom](https://cloud.githubusercontent.com/assets/12617619/14105333/a44fa4b8-f5b3-11e5-9cc4-f00a36a798db.png)

Here is the Log file:

http://logs.uaventure.com/view/z4iXLcNEGGdCXiDtejPC5R

We have still some oscillations in the pitch of the plane so don't pay attention to this.

Otherwise the VTOL performs waaaay better this time. Thanks to all of you!!!

Truly thank you 

Vasil

**Comment by tumbili** [comment]
@tubeme The problem is that you ran into complete saturation. The mixer is allowed to reduce thrust in order to get some authority on pitch/roll axis so I guess this is what happened.
BTW, you can't just look at one pwm output, you need to take the average of all 4 outputs which will give you the actual thrust value.

**Comment by sanderux** [comment]
@tubeme i think the cause of your saturation is motor number 3 (front left)
Do you have a thrust stand? if so, measure the thrust of all your motors, i think you will see this motor only provides half the thrust of your other motors.

I say this based on the fact that you told me the CG is correct.

**Comment by sanderux** [comment]
![image](https://cloud.githubusercontent.com/assets/14801663/14106289/7240c7de-f5b0-11e5-94af-b474b280dc43.png)

**Comment by tubeme** [comment]
@sanderux You were very correct. Thanks again for that. It turned out that ESC #3 was not giving enough throttle. I re-calibrated the ESC's a couple of times with QGC without success #3 was giving lower throttle curve. I could not confirm if the ESC could be calibrated manually with RC because during the try I fried somehow all my 5 ESC's. Anyway we put brand new ESCs and the problem disappeared. And it gave even further stability. So rock solid quad! And another 10 perfect transitions. Next we will do a strong weather transition test with a gusty wind.

We've had a Stall Test crash though so I will make another issue for it.

**Comment by sanderux** [comment]
@tubeme glad to have been of help. you will probably need to re-tune your pid's now

**Comment by tubeme** [comment]
@sanderux I did retouch the PIDs yes indeed :)
