### ISSUE TITLE
'min_out' get wrong initialization value as 0.0f in mixer_multirotor.cpp

### ISSUE THREAD

**Issue by perceptive558** [PX4/Firmware#4128]
Hi everyone, I have a confusion here, In the mixer_multirotor.cpp (https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/mixer/mixer_multirotor.cpp#230),
Line 230 and Line 231 give declarations to ‘min_out’ and ‘max_out’, and from Line 243 to Line 260, we would find the greatest and smallest value of ‘out’. However, there is **NO** chance that the ‘min_out’ could greater than zero. Then, is there any chance that the situations of Line 276 and Line 292 could happen? 

I think, change the initialized value of 'min_out' to 1.0f would fix this problem.

**Comment by LorenzMeier** [comment]
@tumbili Please inspect.

**Comment by tumbili** [comment]
Fixed
