### ISSUE TITLE
A confusion on the 'idle_speed' value in mixer_multirotor.cpp

### ISSUE THREAD

**Issue by perceptive558** [PX4/Firmware#4129]
https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/mixer/mixer_multirotor.cpp#L365
outputs[i] = constrain(_idle_speed + (outputs[i] (1.0f - _idle_speed)), _idle_speed, 1.0f);
if we look into this constrain,
_idle_speed < _idle_speed + (outputs[i] (1.0f - _idle_speed)) < 1.0f
Can be writed in this form:
0 < (outputs[i] * (1.0f - _idle_speed)) < (1.0f - _idle_speed)
If _idle_speed not equal to 1.0f, then the former equation can be writed as:
0 < outputs[i] < 1.0f
I do not know whether this result is the one desired

**Comment by LorenzMeier** [comment]
@tumbili Please inspect.

**Comment by tumbili** [comment]
@perceptive558 you have shown that the original outputs which are calculated are between zero and one. This is ok and the reason why we constrain them at the end.
