### ISSUE TITLE
PX4/Devguide

### ISSUE THREAD

**Issue by sgh055** [PX4/Firmware#4132]
@mhkabir Hi, open issue

I want to information about I2C

but PX4 Development Guide's I2C section is blocked.

if you have an information for I2C, please help me.

Thanks!

**Comment by mhkabir** [comment]
Not quite what I meant. Please see https://github.com/PX4/Devguide/issues/125 opened to track the documentation effort. It's not blocked, it's simply not there.

**Comment by sgh055** [comment]
@mhkabir ah! I see, Sorry
