### ISSUE TITLE
Strange takeoff behavior on mission 

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4145]
When executing a just uploaded mission, sometimes, the takeoff tries to move laterally towards a waypoint. I have seen this behavior in SITL too. Rebooting solves the problem.
I think it happens when having armed it and then upload a new mission

I will try to find a log and also try to reproduce.

**Comment by tumbili** [comment]
@sanderux Let me know if you were able to repro it, curious to see the log.

**Comment by tumbili** [comment]
@sanderux Ok, I was also able to repro this.

**Comment by sanderux** [comment]
@tumbili any idea? could it be the new mission reset code?

**Comment by tumbili** [comment]
@sanderux I don't know yet, not able to simulate anymore now. Terminal tells me that the socket bind for QGC failed.

**Comment by tumbili** [comment]
Do you have a log with you?
Can be a SITL log.

**Comment by sanderux** [comment]
No i dont, i have a real life log on the deltaquad

**Comment by sanderux** [comment]
can search for it tonight

**Comment by sanderux** [comment]
Havent seen this behavior anymore
