### ISSUE TITLE
Add navigator to Snapdragon

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#4157]
The navigator module is not yet running on the Snapdragon. I need to add that.

**Comment by LorenzMeier** [comment]
@julianoes Is there any particular challenge with this?

**Comment by julianoes** [comment]
@LorenzMeier It depends on the dataman which doesn't compile for QURT just yet. And then we'll have to verify the file gets created, etc.

**Comment by jywilson** [comment]
@julianoes Is there something you need for dataman, in the way of file I/O functions that we currently don't support?

**Comment by julianoes** [comment]
@jywilson I don't think so. It should be straightforward. I'll give it a try soon.

**Comment by julianoes** [comment]
I tried this and it turns out the navigator needs dataman which in turn uses `lseek()` which doesn't seem to be available on the DSP side.

For now, I'm going to propse to run the navigator on the Linux side.

**Comment by LorenzMeier** [comment]
That seems perfectly fine.
