### ISSUE TITLE
Signal lost "action on breach!" for Rc and Datalink

### ISSUE THREAD

**Issue by AlexisPotvin** [PX4/Firmware#4160]
Could it be possible to implement a specific action when you trigger a signal lost both for the RC and Datalink. As an example, the "Action on breach" for the GeoFence gives us the option to execute : None, Warning, Loiter, Return Home, Flight Termination.

**Comment by dagar** [comment]
There are separate settings for loss of RC and datalink to do this. Take a look at Settings -> Safety in QGroundControl.
