### ISSUE TITLE
Restricted area function

### ISSUE THREAD

**Issue by liang-tang** [PX4/Firmware#4167]
One of the important functions of PX4 controlled machine is Flight restriction, we can't let vehicle flight in restricted area,it's Forbidden and unsafe.So, can we add restricted area function for PX4?

**Comment by liang-tang** [comment]
@LorenzMeier

**Comment by TSC21** [comment]
https://pixhawk.ethz.ch/mavlink/#SAFETY_SET_ALLOWED_AREA

**Comment by TSC21** [comment]
There's a plugin on (mavros)[] to set it: https://github.com/mavlink/mavros/blob/master/mavros/src/plugins/safety_area.cpp

But I don't think this is implemented on Firmware yet. In any case, this is geofencing related.

**Comment by liang-tang** [comment]
yes, we can add airport coordinates(to ROMFS?) to set flight restriction area.

**Comment by dagar** [comment]
The current geofence system could be extended to do this. How would you want to specify the forbidden area? How many zones would you need to define?

**Comment by liang-tang** [comment]
657 forbidden area(large/medium airport ,15913 bytes) i collected, and store in ROMFS,

**Comment by TSC21** [comment]
So basically https://github.com/mavlink/mavros/pull/689 defines allowed areas, as a geofence. Probably we can consider that everything out of that area is a no-flight zone @liang-tang? Or maybe we can define a new Mavlink message to restricted flight areas - could be synced automatically to the online restricted UAV flight areas data.

**Comment by LorenzMeier** [comment]
I'm closing this since we have a beta airman integration as PR up now.
