### ISSUE TITLE
support global setpoints (SET_POSITION_TARGET_GLOBAL_INT)

### ISSUE THREAD

**Issue by dustingooding** [PX4/Firmware#4186]
http://mavlink.org/messages/common#SET_POSITION_TARGET_GLOBAL_INT

This will give users the ability to command GPS-based setpoints instead of just local-based.

Currently, only SET_POSITION_TARGET_LOCAL_NED is supported (https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L184).

**Comment by dagar** [comment]
You can use MAV_CMD_DO_REPOSITION for this.
