### ISSUE TITLE
Questions about external heading implementation in attitude_estimator

### ISSUE THREAD

**Issue by chengshy** [PX4/Firmware#4188]
I am reading attitude_estimator_q code recently and want to understand the implementation of the filter. I am confused about this external heading support implementation https://github.com/PX4/Firmware/blob/master/src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp#L485-L491, especially `v(1.0f, 0.0f, 0.4f)` part. 

I checked the commit history and found this part was originally added in attitude_estimator_ekf. However, I didn't find more documents about this implementation. Could anyone explain this to me or show me the paper I should look into?

Thanks

**Comment by tumbili** [comment]
@chengshy I assume the vector 'v' is some kind of magnetic field vector. I agree that it's not well documented.
@mhkabir Could you help him out here?

**Comment by mhkabir** [comment]
That's actually not from me. @LorenzMeier introduced that originally in the
old attitude EKF. I just adapted it to attitude_estimator_q.

He would be better able to answer your question.

**Comment by chengshy** [comment]
@tumbili @mhkabir Thanks for help. So we are using the external heading for roll pitch estimation as well? @LorenzMeier Would you like to help me out here?

**Comment by pickledgator** [comment]
I was playing around with this today and was also having trouble understanding the implementation. Namely, since when vision is enabled, the heading doesn't seem to converge to the correct value. Eg, when sending a 1,0,0,0 quaternion, the attitude converges to a non-zero yaw angle.

**Comment by mhkabir** [comment]
Does it change at all when you send the unit quaternion?

**Comment by pickledgator** [comment]
Looks like my external vision quaternion was in the wrong reference frame (rotated about X by 90 deg), so despite that a direct mapping from quat->rpy produces the correct yaw value even when roll=90 deg, it looks like that breaks the currently implemented yaw projection/extraction logic.

**Comment by mhkabir** [comment]
I heard reports about a singularity in the yaw projection DCM, but it
wasn't confirmed. Likely because the angle it occurred at was rather
difficult to achieve in flight.

Would you mind having a look and seeing if you can find anything bad with
the math?

**Comment by tuofeichen** [comment]
hey guys,
I'm still confused about the magic number. Any idea what's it about ?

`math::Vector<3> v(1.0f, 0.0f, 0.4f); `

**Comment by LorenzMeier** [comment]
Closing as stale.
