### ISSUE TITLE
Accidentally left some "_mavlink_fd"s in BlockLocalPositionEstimator.cpp

### ISSUE THREAD

**Issue by locustcox** [PX4/Firmware#4189]
Hey @julianoes,

See: https://github.com/PX4/Firmware/blob/master/src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp#L476

Also, lines 489, 506, & 1539.

Obviously, this presents compile-time errors since "_mavlink_fd was not declared in this scope." Just an FYI.

**Comment by LorenzMeier** [comment]
Thanks! This was either fixed or did not really exist on master.

**Comment by locustcox** [comment]
Yep, looks like it was fixed.
