### ISSUE TITLE
CMake Error:   HEXAGON_SDK_ROOT not set

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#4203]
Hi

The rpi2 build target seems to be broken in master:
```
$ make posix_rpi2_release
-- posix-rpi2-release
CMake Error at cmake/toolchains/Toolchain-arm-linux-gnueabihf.cmake:21 (message):
  HEXAGON_SDK_ROOT not set
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:204 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
ninja -C /home/beat/px4/src/Firmware/build_posix_rpi2_release
ninja: Entering directory `/home/beat/px4/src/Firmware/build_posix_rpi2_release'
ninja: fatal: chdir to '/home/beat/px4/src/Firmware/build_posix_rpi2_release' - No such file or directory
Makefile:185: recipe for target 'posix_rpi2_release' failed
make: *** [posix_rpi2_release] Error 1
```

Can you look into this @julianoes ?

**Comment by julianoes** [comment]
HEXAGON_SDK_ROOT is only needed when compiling for the Snapdragon, so that's confusing.

@bo-rc, @rosshop any ideas what is wrong here?

**Comment by mhkabir** [comment]
It's not choosing the Rpi2 cross toolchain properly for some reason. Let me check.

**Comment by nacho-carnicero** [comment]
Hi!

Any news on how to solve this topic? I'm stuck as well with the same error!
Thanks!
Nacho.

**Comment by gelazanskas** [comment]
Same here!

**Comment by LorenzMeier** [comment]
@mcharleb @jywilson It would be really, really good to resolve this. As Qualcomm is handing out more boards this is affecting *a lot* of people.

**Comment by mcharleb** [comment]
cmake/toolchains/Toolchain-arm-linux-gnueabihf.cmake should not need to be used for Snapdragon Flight builds. The Snapdragon Flight builds for the apps proc should use: cmake_hexagon/toolchain/Toolchain-arm-linux-gnueabihf.cmake

That way, cmake/toolchains/Toolchain-arm-linux-gnueabihf.cmake does not need to depend on HEXAGON_SDK_ROOT

**Comment by nacho-carnicero** [comment]
Thanks for answering, but the problem here has to do with Raspberry Pi builds, and not with Snapdragon Flight builds. According to @mhkabir the build target is not choosing the RPI2 toolchain, any hints where this can come from?

**Comment by mhkabir** [comment]
OK, found the problem. Fix coming up.

**Comment by mhkabir** [comment]
All interested, please see #4404.

**Comment by julianoes** [comment]
I'm pretty sure this is fixed now, closing.
