### ISSUE TITLE
Tricopter default yaw servo rate is too high

### ISSUE THREAD

**Issue by matanhavi** [PX4/Firmware#4207]
The tail servos usually can't run at PWM rate of 400Hz, analog servo 50Hz is the max. digital servos its about 200-300Hz

The problem that all the PWM on channels 1234 are the same 400Hz.
Need to add new mixer configuration for tricopter that will use other control group for the servo at lower rate

**Comment by dagar** [comment]
@matanhavi if I throw this together are you able to test?

**Comment by dagar** [comment]
@matanhavi you need to move the servo to a different rate group.
