### ISSUE TITLE
Simplify calibration process for end user

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#4214]
It would be good to align our calibration procedure to some of the other autopilots out there like dji and parrot. In general it takes too long for end users right now.

**Comment by dagar** [comment]
On the call I believe you said about using SVD, but that wouldn't be feasible for a pixhawk. Could we offload that to QGC?

**Comment by jgoppert** [comment]
Yeah, we could use SVD on QGC, but I think if you assume the ellipsoid is aligned with the primary axis of the sensors that the math gets simplified, and you might not need SVD. We would still probably need a pseudo-inverse though, but I think someone must have figured out an easy way to do this on microprocessors.

**Comment by dagar** [comment]
I think this is covered by https://github.com/PX4/Firmware/issues/6472 and https://github.com/PX4/Firmware/issues/6465
