### ISSUE TITLE
dronekit and modes from pymavlink

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#4224]
I have received an increased number of requests to look into the PX4 integration in DroneKit, one of the problems that is bugging people is that we are facing a mode problem when connecting

```
`>>> Exception in message handler for HEARTBEAT
```

DroneKit is using the [`mode_mapping_bynumber` helper from **mavutil.py**](https://github.com/mavlink/mavlink/blob/master/pymavlink/mavutil.py#L1416-L1433) and we seem to be facing modes not defined there.

I don't have much much time to spend debugging this I'm looking for help from the PX4 community, there are plenty issues on our dronekit repo but this should be the official

https://github.com/dronekit/dronekit-python/issues/606

**Comment by dagar** [comment]
The PX4 custom modes mavlink values are defined here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/px4_custom_mode.h#L46

**Comment by LorenzMeier** [comment]
@mrpollo Status?

**Comment by dagar** [comment]
Wasn't this resolved? @sanderux

**Comment by sanderux** [comment]
I added and got merged a PR in both dronekit and pymavlink but mavutil needs to release a new version on pip before this will be operational. Not sure what the status is there

**Comment by dagar** [comment]
Any idea who takes care of that?

**Comment by sanderux** [comment]
i think tridge
