### ISSUE TITLE
With no RC connected, random input is seen

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#4225]
See: http://logs.uaventure.com/view/dH6czHZCHJ67hXQkJpLLfk#RC_Raw_PLOT
As soon as I hook up the receiver it's fine. It's on an older Pixhawk that only serves as HIL Pixhawk tough..

**Comment by AndreasAntener** [comment]
That's on current master.

**Comment by LorenzMeier** [comment]
Fixed.
