### ISSUE TITLE
MAVLink SD file open fails

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4295]
@julianoes Something is not quite right yet with the MAVLink file log:
```
WARN  Failed to open MAVLink log: /fs/microsd/msgs_2016_04_18_20_53_39.txt�� errno=22
```

**Comment by LorenzMeier** [comment]
The unprintable chars are particularly noteworthy.

**Comment by julianoes** [comment]
Strange, I don't think that I touched this part.

**Comment by LorenzMeier** [comment]
So it turns out my SD file system was trashed. I need to find a way to store less MAVLInk log files on it.
