### ISSUE TITLE
slow yaw in gazebo simulation

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#4297]
I have just pulled master and I wanted to reproduce https://github.com/PX4/Firmware/issues/4191. Now however, yaw is very slow in the gazebo simulation (make posix gazebo_iris_opt_flow and make posix_sitl_default gazebo) but it works in jmavsim. I use gazebo verison 6.5.1.

**Comment by ChristophTobler** [comment]
@LorenzMeier Seems to be this one https://github.com/PX4/sitl_gazebo/commit/51f69f61ad45b521ae2b57878345c71a13f485dd or what was the reason for that?
But even when I do: git checkout 58b61d68a618 (8 commits before) the simulation feels a bit weird. E.g. Altitude Control does not really work -> the iris goes up and down

**Comment by ChristophTobler** [comment]
this commit slows down yaw: https://github.com/PX4/sitl_gazebo/commit/63cc44d84f4391133fdabb07e87da50aec5a5944

**Comment by LorenzMeier** [comment]
Can you submit a PR to fix it? Or at least share the exact diff? Thanks!

**Comment by ChristophTobler** [comment]
this is the exact diff. But I can also submit a PR.

**Comment by LorenzMeier** [comment]
Stale / fixed.
