### ISSUE TITLE
Snapdragon: Start logger before estimator outputs data

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#4299]
Especially for a replay we need to make sure that we are not missing any data from the sensors. Right now the logger is the last app to start.

**Comment by julianoes** [comment]
@tumbili this means we are logging all the time?

**Comment by tumbili** [comment]
Yes, for replay we are not waiting to be armed.

**Comment by tumbili** [comment]
@julianoes Also we need to make sure that the dsp apps are not running before the logger runs on the posix side.

**Comment by mcharleb** [comment]
I can add a wait_on_topic command to block until a topic is published. This would require the logger to publish an "logger_running" topic.
