### ISSUE TITLE
Estimators Clarification.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#4309]
Hi guys,

I read the rc init.d scripts and have something I cannot understand:

From: Firmware/ROMFS/px4fmu_common/init.d/rc.fw_apps

we have the default estimator for FW is EKF.

From MC Firmware/ROMFS/px4fmu_common/init.d/rc.mc_apps we have:

3 options INAV, LPE, and the third EKF2.

So now my question is what is the situation for  VTOL?

From: Firmware/ROMFS/px4fmu_common/init.d/rc.vtol_apps

I see estimators only for the MC mode of the VTOL. What is the estimator when the VTOL is in FW? I don't see ekf as option nor we start the ekf in the VTOL.

Can somebody clarify the situation?

Also I cannot understand something. Is EKF2 attitude and position estimator at the same time? This is how I understand it BTW...

**Comment by devbharat** [comment]
Yes EKF2 estimates both attitude and position.

**Comment by julianoes** [comment]
@tubeme: Can you please put \`\`\` around your pasted code? Otherwise, it's hard to read.

**Comment by tubeme** [comment]
@julianoes Sorry for the mess... Couldn't format it. Now it is better.

**Comment by julianoes** [comment]
See this page: http://dev.px4.io/advanced-switching_state_estimators.html

@tumbili: what about VTOL?

**Comment by tubeme** [comment]
I saw this page. Actually it was added just after I posted this issue...

But again did not find the answer there about VTOL?

**Comment by tumbili** [comment]
```
For multirotors and VTOL use the parameter SYS_MC_EST_GROUP to chose between the following configurations.
At the moment only the depriciated EKF estimator is used for planes (non VTOL). It will soon be replaced by EKF2. 
```

It is written like this in the dev guide.
