### ISSUE TITLE
Update Racer Quad gains

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4315]
@kd0aij @pkocmoud Could you work out a new default set for the generic 250 config and help us getting it in the v1.3.0 release?

I honestly don't understand where the blocker is for getting them validated and out to the community.

**Comment by kd0aij** [comment]
The problem I have is that my 250 gains seem to be far too high for the few people that have tried them. So it seems they won't make good defaults.

**Comment by kd0aij** [comment]
@pkocmoud Can you try the gains posted here: https://gitter.im/kd0aij/dual_FC_S250AQ?at=571528bb548df1be102dfda3 on your S250? Maybe the Spedix can handle higher gains thant the QAV250

**Comment by LorenzMeier** [comment]
I don't believe we really understand this yet. I'm pushing this out to next release.
