### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by Michvw** [PX4/Firmware#4320]
I just spend an entire afternoon looking why my nsh terminal wouldn't work on my PX4.
Turns out i just needed to get the SD card out and everything works fine.
This is nowhere described in the PX4 documentation i could find on the web. It might be a good idea to add it.

**Comment by julianoes** [comment]
Thanks for raising this. I agree that this is very much automagic behavior!

I created an issue in the Devguide to track it: https://github.com/PX4/DriverFramework/issues/58.

**Comment by mhkabir** [comment]
It was clearly mentioned here : http://dev.px4.io/advanced-system-console.html
