### ISSUE TITLE
Flight Termination not working

### ISSUE THREAD

**Issue by AlexisPotvin** [PX4/Firmware#4331]
We tested the flight termination action from a Geofence violation with a radius Geofence. When we breach the geofence, we recieved the message : "Critical: Geofence violation: flight termination", but the UAV did react. In fact it complet the mission. We retry the same Geofence with other action such as warning and RTL and those were working properly.

**Comment by dagar** [comment]
You have to set CBRK_FLIGHTTERM to 0 for flight termination. 
https://pixhawk.org/firmware/parameters#circuit_breaker

Be careful...
