### ISSUE TITLE
Plot and upload charts on Jenkins

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#4339]
Options:
- Upload logs to Log Muncher
- Define plots per test and generate charts on Jenkins, then upload to S3

**Comment by dagar** [comment]
Could the log muncher code run on jenkins? If it's mostly a script that consumes a px4log and spits out an html page and plots. Jenkins can store artifacts per build and handle the hosting.

**Comment by AndreasAntener** [comment]
Yes, I was thinking more in this direction, should be no problem. Jenkins is not really meant to host a lot of data, so upload to S3 is no problem, but need to see how to link it properly

**Comment by AndreasAntener** [comment]
Closing this as there is a new effort running: https://github.com/PX4/Firmware/issues/5954
