### ISSUE TITLE
System hangs on RTL call from RC in single channel mode selection

### ISSUE THREAD

**Issue by gianni-carbone** [PX4/Firmware#4364]
Helo,
after the last firmware update I suffer a serious problem. If I try to switch in Return To Land mode when non GPS signal available the system completely hangs.
The system does normally work when a GPS valid signal is present.
The problem is serious cause if the system is in flight in manual mode with no GPS lock and accidentally the RTL switch is selected the system HANGS whit result of a crash.
firmware: px4fmu-v2_default
Regards GC

**Comment by LorenzMeier** [comment]
This was on stable, correct? We have reworked this part of the flight mode assignment on master.

**Comment by gianni-carbone** [comment]
It was on the github source at the moment of writing message (after the time of compiling) I don't know if the issue is present on stable version.
