### ISSUE TITLE
EKF2 replay logging is broken.

### ISSUE THREAD

**Issue by priseborough** [PX4/Firmware#4378]
Every 10th or so value of RPL1.t is zero which breaks replay.

**Comment by devbharat** [comment]
@tumbili is the fix up somewhere ?

**Comment by devbharat** [comment]
I broke the replay message in separate parts for different sensors, had them all in the union except the one for IMU, which was its own struct. That solved it for me, not sure if its the best solution.

**Comment by devbharat** [comment]
I finally have ekf2_replay working with vision on master. Something is weird though, I have to overwrite the length of LOG_ATT_MSG in ekf2_replay like this:

    // data message
    int length;
    if(header[2] != LOG_ATT_MSG){
        length = _formats[header[2]].length;
    } else {
        length = 55;  // ATT has length 55, force it!
    }
    if (::read(fd, &data[0], length - 3) != length - 3) {
        PX4_INFO("Done!");
        _task_should_exit = true;
        continue;
    }

as the **_formats[header[2]].length** value for LOG_ATT_MSG is somehow 0, which would otherwise crash the app.

**Comment by tumbili** [comment]
@devbharat Try master now without your workaround.

**Comment by devbharat** [comment]
Are you re

**Comment by tumbili** [comment]
@devbharat Yes, I tried and I get no messages like that.

**Comment by devbharat** [comment]
OK, I'll diff the sdlog2 app with master and check then

**Comment by zubair123khan** [comment]
hello guys, i need to replay a log and when i am running replay on it, its throwing me error that no rule to make this file, although i am in right directory. 
please help me out with this..
