### ISSUE TITLE
Drive the submodule checks from the cmake - remove redundant list in Tools/check_submodules.sh

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#4386]
This for the nuttx_next_cmake merged from master....

remove the module list from here
https://github.com/PX4/Firmware/blob/nuttx_next_cmake_master/Tools/check_submodules.sh#L77-L91

Is is best driven by:

https://github.com/PX4/Firmware/blob/nuttx_next_cmake_master/CMakeLists.txt#L255-L266

and tested in px4_add_git_submodule
https://github.com/PX4/Firmware/blob/nuttx_next_cmake_master/cmake/common/px4_base.cmake#L148-L150

**Comment by dagar** [comment]
Actually, I think this needs to be handled by the Makefile. During the cmake configure it won't tolerate its configuration changing, like if one of the submodules contains a CMakeLists.

**Comment by davids5** [comment]
@dagar - The only point was there should only be 1 list.  I will leave the magic up to you :)

**Comment by dagar** [comment]
Done!
