### ISSUE TITLE
Optimize travis again - gain by orb message generation and a symlink?

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#4387]
To not use up all the Flash on smaller devices  - The nuttx_next_cmake (_master) scopes the parameters generation based on the modules used by a target.  So this build step is needed per target and is currently done per target.

But is seams there may be a gain **possible** in orb message generation and a symlink - Needs investigation

**Comment by dagar** [comment]
I did a quick test and the entire orb generation (headers and source) only takes about 2-3 seconds per target.
