### ISSUE TITLE
Development Environment on Linux

### ISSUE THREAD

**Issue by sgh055** [PX4/Firmware#4389]
Hi, I have some problem.

I followed Development Environment on Linux(http://dev.px4.io/starting-installing-linux.html#development-environment-on-linux). but When I make px4-v2, I got a error message.
How can i fix that? I installed all of them

This message.
![image](https://cloud.githubusercontent.com/assets/15629613/14873395/f8e50d26-0d30-11e6-8d19-f7147df4ee4f.png)

**Comment by kd0aij** [comment]
Are you sure you got everything installed? It looks like you didn't install
gcc.

**Comment by sgh055** [comment]
![image](https://cloud.githubusercontent.com/assets/15629613/14874141/48f4e244-0d38-11e6-808a-b688613eaba3.png)

@kd0aij this??

**Comment by kd0aij** [comment]
No, try "arm-none-eabi-gcc --version"

**Comment by sgh055** [comment]
![image](https://cloud.githubusercontent.com/assets/15629613/14875117/2c53f77e-0d42-11e6-95ad-383eb5ecb120.png)
@kd0aij  I try to command, they say "No such file or directory" 

however, file or directory exist.
![image](https://cloud.githubusercontent.com/assets/15629613/14875148/7074cff0-0d42-11e6-9cc9-b959a733967c.png)

**Comment by Inspirati** [comment]
What's with the 'ardupilot', are you sure you've got the correct codebase?

**Comment by mhkabir** [comment]
Nice catch @Inspirati. Looks like he's trying to build ArduCopter and following the PX4 build steps.
