### ISSUE TITLE
Advanced Mixer Page dissapear.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#4418]
Hello,

There was a page in the old .org site for the Mixing where I got the information on Control Groups etc.

I have bookmarked this page so depsite the old site was not working I was using it. But it disapear now and I cannot load it. So there is no reference on the control groups anywhere.

Any pointers?

**Comment by LorenzMeier** [comment]
dev.px4.io mixing

**Comment by tubeme** [comment]
I mean this document:

http://blog.csdn.net/olillian/article/details/50778494

It is no longer available. And it is the only doc with the control groups described.

**Comment by LorenzMeier** [comment]
Anything missing would need to be ported to the new docs.

**Comment by tubeme** [comment]
OK I got your point.
