### ISSUE TITLE
QGC/PX4 not communicating correctly

### ISSUE THREAD

**Issue by srees** [PX4/Firmware#4425]
Behavior is similar to that caused on a linux system when e2fd2f4 was implemented, same as #3707, has come up again. 

Fresh build of PX4 firmware on Ubuntu VM, latest QGC running on Mac host, different IP addresses.
QGC detects the launch of 'make posix gazebo' but immediately loses communication with it. Telem logs from the make command indicate connection is still active (closing/relaunching QGC is reflected with 'data link#0 lost/regained), but nothing is coming through to QGC. QGC reports that 'vehicle did not respond to request for parameters'.

**Comment by LorenzMeier** [comment]
This is actually intentional since it caused havoc in local networks. You would need to remove the -t parameter here: https://github.com/PX4/Firmware/blob/master/posix-configs/SITL/init/rcS_gazebo_iris#L54

I don't have a one-size-fits-all solution yet.

**Comment by srees** [comment]
That's helpful to know, thanks. Is there documentation somewhere of what the command switches (parameters) do for mavlink? I can't seem to find that.

**Comment by srees** [comment]
Nevermind, found usage at the end of mavlink_main.cpp

warnx("usage: mavlink {start|stop|stream} [-d device] [-u network_port] [-o remote_port] [-t partner_ip] [-b baudrate]\n\t[-r rate][-m mode] [-s stream] [-f] [-p] [-v] [-w] [-x]");

**Comment by srees** [comment]
So if I understand this right, QGC will work fine if it is running on the same host as the SITL simulation is running?

**Comment by LorenzMeier** [comment]
That's correct.
