### ISSUE TITLE
Calibration PX4Flow

### ISSUE THREAD

**Issue by quentin1002** [PX4/Firmware#4431]
Hi everybody, 

I followed this [tutorial](http://ardupilot.org/copter/docs/common-px4flow-overview.html) in order to calibrate my PX4Flow, used along with a pixhawk PX4 board. Neverless the consistency check is not giving me a relevant result. Here is what I get performing the x-gyro test. In white is the HIGH_RES_IMU_xgyro and in pink is the OPTICAL_FLOW_RAD_Integrated_xgyro. As you can see there is a scaling effect that I can't solve...
![screenshot from 2016-05-04 16 15 03](https://cloud.githubusercontent.com/assets/15336020/15008621/2339d948-1214-11e6-8a4f-743d050db935.png)

Thanks in advance for your help,
Quentin

**Comment by proficnc** [comment]
Are you doing this in bright sunlight?  Low light will give bad results.

**Comment by quentin1002** [comment]
Yes I am doing with good light, though interior, and the image quality is around 240

**Comment by proficnc** [comment]
If indoor, ensure your lights are incandescent

**Comment by quentin1002** [comment]
in your opinion, light is the only reason? Because I just tried to add an additional light (no effect), move outside of the office with direct sun light (no effet). I also tried to vary the pattern of the floor and the height.... I still have the IMU pic 3 times higher than the OF's.

**Comment by proficnc** [comment]
No, just worth checking the basics.

What calibration settings are you using?

**Comment by quentin1002** [comment]
What do you mean by settings? I am using QGroundControl V2.9.1. 

The PX4 was calibrated following the 4 steps of QGC and regarding the px4flow is used the video mode only to focus the image. My board is used at around 1m from the ground....

**Comment by proficnc** [comment]
Which instructions are you following?

**Comment by quentin1002** [comment]
The "official" [one](https://pixhawk.org/modules/px4flow)

**Comment by proficnc** [comment]
Ok, I'm not familiar with using flow with px4 flight, but setting up for Ardupilot is described well here.

http://ardupilot.org/copter/docs/common-px4flow-overview.html

**Comment by LorenzMeier** [comment]
Please use the official instructions from the hardware site, not any 3rd party instructions which are often stale wrt to the official release firmware. The reason you're confused is that you need to read up on the message spec: the sensor is sending the integrated velocity, not angular rate.
