### ISSUE TITLE
Beeping and red light flashing, unknown reason

### ISSUE THREAD

**Issue by gregswf** [PX4/Firmware#4436]
I flashed the master and I've noticed that the led starts flashig red and sound alarm starts just like for battery low but the battery is ok, Qgc doesn't report low voltage or low battery or anything.
Sometimes it happens during the flight sometimes on the  ground.
Please have a look at the log.
http://logs.uaventure.com/view/9UnF4ddXJqyuT9AnyBrHDA#AS_Pitch_PLOT

**Comment by LorenzMeier** [comment]
This is fixed on master and beta, thanks for reporting! It was a missing filter on the battery alarm threshold.

**Comment by gregswf** [comment]
Thank you Lorenz 😊
