### ISSUE TITLE
Inspect manual control lost inspection

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4468]
Message is coming through on switching RC back on

**Comment by mhkabir** [comment]
Also happens when using a joystick

**Comment by tommises** [comment]
I am getting this message each time I change any parameter.

**Comment by CarlOlsson** [comment]
QGC is still constantly spamming with manual control lost messages on 1.5.3

**Comment by dagar** [comment]
Was this resolved?

**Comment by LorenzMeier** [comment]
Yes
