### ISSUE TITLE
Battery current offset got lost during refactor

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#4487]
@julianoes 
This offset is not considered anymore: https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensors.cpp#L322, please check the version before you pulled the battery out of the sensors app.

**Comment by LorenzMeier** [comment]
Seems like that was a refactor from hell 8). If you run git blame you can see how many lines I already had to fix (and then to fix again because I committed more mistakes).

**Comment by julianoes** [comment]
@AndreasAntener Sorry, I'll chase that up!

**Comment by jgoppert** [comment]
Could this be related to https://github.com/PX4/Firmware/issues/4567?

**Comment by AndreasAntener** [comment]
@jgoppert no this one is about a new setting for power modules that come with a fixed offset on the current signal.

**Comment by jgoppert** [comment]
Any chance the acsp4 from auav that I have needs this param to correct the current to the extent that it would cause #4567?

**Comment by AndreasAntener** [comment]
I don't know what settings they need, they don't specify it on their page so I'm assuming defaults should work? The offset I've only seen on one module so far (from Drotek)

**Comment by LorenzMeier** [comment]
PR open for this.
