### ISSUE TITLE
Local Takeoff

### ISSUE THREAD

**Issue by tuofeichen** [PX4/Firmware#4490]
Hey guys,
I was wondering if a local takeoff based on local position estimate (LPE) is implemented any where in the Firmware. I can send setpoint when the drone is on the ground, but at that point only a valid z estimate is present (since we're using optical flow moment). I will still try it later today, but just wondering if this feature is already implemented somewhere in the firmware. 

Thanks
Francis

**Comment by tuofeichen** [comment]
nvm, can achieve on mavros side using setpoint

**Comment by vinhk** [comment]
@tuofeichen But how can you detect x,y when there is likely that no data for x,y since optical flow is very close to the ground?

**Comment by tuofeichen** [comment]
@vinhk , One hack is you can send velocity setpoint and let the drone jump off quickly, and as soon as the optical flow become valid, it will hover. 

I'm switching to visual SLAM at this point now, so the x, y is not constrained by the distance to the ground anymore.

**Comment by vinhk** [comment]
@tuofeichen what topic did you use to make the velocity setpoint?

**Comment by vinhk** [comment]
this I supposed ?
'/mavros/setpoint_velocity/cmd_vel'

**Comment by vinhk** [comment]
`/mavros/local_position/velocity`

**Comment by tuofeichen** [comment]
yeah, I think so, or whatever the most recent version of mavros is.

**Comment by vinhk** [comment]
Is there a difference btween ` /mavros/setpoint_velocity/cmd_vel ` and 

` /mavros/local_position/velocity `

**Comment by tuofeichen** [comment]
yeah, setpoint_velocity publish the setpoint* to* the pixhawk.
local_position is the LPE or whatever estimator you're using's estimate of
the local position/velocity of the drone, so it comes *from* the px4.

**Comment by vinhk** [comment]
I see. I like to implement your idea of aggressive takeoff to a certain attitude so that it does not drift before it get to read optical flow data.

**Comment by vinhk** [comment]
So in order to make it takeoff aggressively, I should use the setpoint_velocity?
but it is a subscribed topic. 
![screenshot from 2016-07-15 12 36 58](https://cloud.githubusercontent.com/assets/17210431/16881591/ea9f6af0-4a88-11e6-98c6-be80b7d5bd9f.png)

**Comment by tuofeichen** [comment]
yes that's correct

**Comment by vinhk** [comment]
would you be willing to share your old code sir?

**Comment by vinhk** [comment]
I would like to takeoff fast and then stop once height is achieved.

**Comment by vinhk** [comment]
would you be able to help me with implementing this method of aggressive takeoff and then hover once data is received?

**Comment by tuofeichen** [comment]
Hey,
I doubt I have the implementation with me at this point, also I changed the
Firmware code a bit as well so I don't think you're gonna get it plug and
play. The tutorial on the dev website is pretty good, the structure at
least. with some slight modification you should be able to get it to work.
The key is always make sure your optical flow and rangefinder actually
gives you the right data. (suggest doing some handheld testing for the
position estimate before implementing offboard)

http://dev.px4.io/ros-mavros-offboard.html

**Comment by vinhk** [comment]
could you help me with getting the data from the `mavros/px4flow/raw/optical_flow_rad` topic?
I am having trouble implementing a subscriber for it.

**Comment by tuofeichen** [comment]
You need to plug in the flow module to your computer and download a px4flow
ros package to get that topic, the pixhawk connection doesn't provide that.
Also that's just for debugging purposes. You don't need to subscribe to
that topic, the i2c between flow and the pixhawk will provide position
estimate in the px4 firmware already.

**Comment by vinhk** [comment]
I see. Yeah, I am thinking about maybe I can use the takeoff service where I can use the ultrasound sensor on the PX4Flow to get to the desire altitude and from there change the mode from OFFBOARD to POSCTL. Would this work?

**Comment by tuofeichen** [comment]
no... takeoff service to my understanding needs GPS.

**Comment by vinhk** [comment]
oh no. :(

**Comment by vinhk** [comment]
I am wondering what did you use to have it takeoff vertically using Mavros?

**Comment by tuofeichen** [comment]
you can send a position setpoint or velocity setpoint of z > 0.

**Comment by vinhk** [comment]
I actually have a video of the testing using local position setpoint
https://www.youtube.com/watch?v=tApfAn-GJH4

**Comment by vinhk** [comment]
velocity set point I am unsure of.

**Comment by tuofeichen** [comment]
Most likely your position estimate is not correct. I suggest you log the
mavros/local_position and handheld the drone to maybe walk a known
trajectory and see if you get meaningful result.

**Comment by vinhk** [comment]
by logging, I am unfamiliar with that. Do you mean print data using rostopic ?

**Comment by mhkabir** [comment]
http://dev.px4.io/flight_log_analysis.html

The primary reason you keep running into issues is that you haven't studied the system basics and jumped straight into GPS-denied offboard control, which is a challenging proposition in itself. I would suggest that you first read up a bit on the system, and check out the PX4 devguide. You should also be prepared to jump into the code to achieve your goal.

If you're discussing something unrelated to the core flightstack bugs, I would suggest the PX4 Discuss : http://discuss.px4.io/

**Comment by vinhk** [comment]
Okay, I'll do that.
