### ISSUE TITLE
Hold mode during landing leads to the vehicle dropping down

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#4491]
When flying a mission during land mode I tried to put the vehicle in hold mode. That lead to the vehicle falling down by about 5 meters and after that recovering back to the alt it should have been. Almost felt like throttle integrator was to zero.

Explanation: The altitude setpoint during landing is way off the current altitude (because descend velocity is limited). Once we switch into hold the altitude setpoint is not reset but has to come up again first.
![height_loss_release](https://cloud.githubusercontent.com/assets/7610489/15125515/94e09010-162d-11e6-9a88-18c86da13564.png)

**Comment by tumbili** [comment]
Log: http://logs.uaventure.com/view/s7Lnr8CYrvuRk887Qki876

**Comment by LorenzMeier** [comment]
So entering hold should reset the alt SP immediately?

**Comment by tumbili** [comment]
@LorenzMeier Yeah, I would say so.

**Comment by tumbili** [comment]
@LorenzMeier I think this should be reproducible in SITL.

**Comment by LorenzMeier** [comment]
@tumbili Can you look into this tomorrow?

**Comment by LorenzMeier** [comment]
@tumbili This is fixed on master. Please re-test outdoors, SITL looked good.
