### ISSUE TITLE
Multicopter position controller integrates error when sitting idle without being airborne

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4498]
@tumbili The issue seems that when armed and in hold flight mode a position setpoint integral is building up, which then first needs to be unwound when taking off in takeoff mode.

http://logs.uaventure.com/view/pvEC9wamaU8QcmDwExzFw5

Particularly here:
http://logs.uaventure.com/view/pvEC9wamaU8QcmDwExzFw5#Local_X_PLOT

**Comment by LorenzMeier** [comment]
@tumbili Can you please set your priority on this one? I think we need to fix this for 1.3.0 immediately.

**Comment by tumbili** [comment]
The problem here is that the navigator publishes zero values for lat/lon in the position setpoint.
Another potential problem (not the main issue) is that we don't reset position setpoints in non-manual modes when we are landed. This is addressed here https://github.com/PX4/Firmware/pull/4514

**Comment by LorenzMeier** [comment]
Do we know if it publishes a zero SP?

**Comment by tumbili** [comment]
@LorenzMeier At least my printf tells me that. Lat/lon are both zero and I verified that the topic updates.

**Comment by LorenzMeier** [comment]
ok, thanks!

**Comment by LorenzMeier** [comment]
Fixed in a700b02.
