### ISSUE TITLE
WARN reset: stale sensor data, resetting

### ISSUE THREAD

**Issue by ozgurerbulan** [PX4/Firmware#4507]
I am using px4 for an unmanned ground vehicle which is a modified power wheelchair. I got this error sometimes and when it happens px4 cuts the pwm output for an half second then it keeps moving. How can I fix that? I am using latest stable firmware and ground rover airframe.

**Comment by LorenzMeier** [comment]
Are you operating indoor and with GPS? Or do you run custom software or drivers which create a lot of load? It sounds like you have erratic sensor readings.
