### ISSUE TITLE
Logging should include roll SP in position control mode

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#4511]
It seems that for fixed wings the attitude controller does not control the roll axis well in position control mode. In the image below position control mode is active when the red line is at 2.
![pos_hold_att_problem](https://cloud.githubusercontent.com/assets/7610489/15206474/becc1fae-181f-11e6-88ce-d229edcb5a85.png)

**Comment by LorenzMeier** [comment]
@tumbili You're confused by the logging. When the user moves the roll stick his actual input is not logged. Only when he re-centers the controls.

**Comment by tumbili** [comment]
@LorenzMeier Yeah I just realized that as well

**Comment by dagar** [comment]
We should flesh out the details of the stick mapper (https://github.com/PX4/Firmware/issues/2822) and I'll start working on it.

**Comment by tumbili** [comment]
Fixed in master
