### ISSUE TITLE
In the SITL gazebo simu, the MAV runs away.

### ISSUE THREAD

**Issue by Userskii** [PX4/Firmware#4516]
I updated the firmware on Monday then on Wednesday. However after the latest update. After running $ make posix_sitl_default gazebo, the iris does not rise up vertically. It runs away. Did I do something wrong?

**Comment by julianoes** [comment]
Thanks for raising. I can reproduce this as well when doing `commander takeoff`. It seems to be broken.

**Comment by julianoes** [comment]
@Userskii In the meantime, you should be able to use `make posix jmavsim`.

**Comment by julianoes** [comment]
I'm looking into it.

**Comment by julianoes** [comment]
@LorenzMeier: `git bisect` points to 8960ab3402a87b182d17ab1b3cb165115e0f4bad

**Comment by julianoes** [comment]
Is this connected to https://github.com/PX4/Firmware/pull/4514?

**Comment by julianoes** [comment]
This would fix it for now #4533.

**Comment by Userskii** [comment]
I tested and it works. Thanks.
