### ISSUE TITLE
Replay of ulog files

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4544]
@bkueng @dagar Now that we can log the whole system I would love to get going with an app able to replay a log into the system. That would not be too hard to generate and extremely powerful.

**Comment by dagar** [comment]
Interesting idea. Do we only replay "input" messages? gps, sensors, manual_input, etc.

**Comment by LorenzMeier** [comment]
We replay by default everything, but we should have a blacklist so that you can disable the messages of the module you're intending to test.

**Comment by kd0aij** [comment]
What datarate will be required to log everything, and will we be limiting
the logging rate for high-rate sensors? We'll need to increase the limit on
file descriptors to log all topics, and perhaps allocate more stack space.

**Comment by bkueng** [comment]
done in https://github.com/PX4/Firmware/pull/4817

**Comment by junhohan** [comment]
A Great feature! @bkueng saved me!!
