### ISSUE TITLE
ver.c Cleanup

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#4561]
1.  Rework https://github.com/PX4/Firmware/blob/master/src/systemcmds/ver/ver.c#L66 to work like the PX4_GIT_TAG_STR is generated from the last NuttX tag
2. Consolidate all the unique_id like mcu_unique_id to use boardctl(BOARDIOC_UNIQUEID) (produce the same format as uavcan requires with a wrapper to keep ver command format the same

**Comment by davids5** [comment]
on nuttx_v3 need to expand support for new procs

**Comment by dagar** [comment]
Add something for fmu-v3?

**Comment by davids5** [comment]
As it is fmu-v3 does not have a BOARD_NAME it "inherits" fmu-v2 and uses is different Linker script. We may be able to  to undef BOARD_NAME and redefine it. Then ripple that to the startup script

**Comment by LorenzMeier** [comment]
Done.
