### ISSUE TITLE
Safety Button Disabled on v4 Firmware

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#4568]
The v4 firmware seems to allow the vehicle to arm without the safety button being pressed. I don't think this is intended behavior, and if it is I would propose it be changed for safety concerns.

**Comment by kd0aij** [comment]
Yes, the disable is explicitly coded (in rcS, I think) and can't be overridden with the CBRK parameter.

**Comment by LorenzMeier** [comment]
The reason for that is because we initially didn't offer a safety switch. We needed to force it to the value for all v4 users during one release, now we can remove this again, as nobody will be surprised now when setting up a new airframe.

**Comment by LorenzMeier** [comment]
Fixed on 6274d6b.
