### ISSUE TITLE
ROI Implementation and Gimbal Integration

### ISSUE THREAD

**Issue by thedevleon** [PX4/Firmware#4584]
This is sort of 2 issues in one. If wanted, I can split this into two issues.
#### The current state (at the time this issue was created)
1. Sadly, nothing in regards to ROI is implemented. Neither the MAV_ROI enum and nor MAV_CMD_NAV_ROI or MAV_CMD_DO_SET_ROI are parsed by the commander.
2. Since those are not implemented, there is no current way to use the current vehicle ROI to control a gimbal (have it point to it).

Thus, I propose the following changes:
- [x] Implement the `MAV_ROI` enum in the `vehicle_command` topic
- [x] Create a new uORB topic for the vehicle ROI (named `vehicle_roi`<sup id="a3">[3](#f3)</sup>)
- [x] Implement the parsing of `MAV_CMD_NAV_ROI` and `MAV_CMD_DO_SET_ROI` in `commander.cpp` and the advertising of the ROI on the `vehicle_roi` topic
- [x] Rename the current gimbal driver to something else like GimbalRC or RCGimbal<sup id="a1">[1](#f1)</sup>
- [x] Create a proper gimbal driver that will subscribe to the `vehicle_roi` topic and send `MAV_CMD_DO_MOUNT_CONFIGURE` and `MAV_CMD_DO_MOUNT_CONTROL` commands to the gimbal<sup id="a2">[2](#f2)</sup>
##### Applications
- POI can be easily implemented in GQC (it just needs to set the ROI via `MAV_CMD_NAV_ROI` or `MAV_CMD_DO_SET_ROI`, the actual control will be done via the gimbal driver)
- The camera can be easily aimed in the Follow Target mode, by just setting the ROI to the target.
##### Rough Progress
- [x] [ROI Implementation](https://github.com/PX4/Firmware/pull/4585)
- [ ] [Gimbal Driver Implementation](https://github.com/PX4/Firmware/pull/4624)
- [ ] Update Documentation
- [ ] Make Follow Me (Follow Target) use ROI to aim gimbal
- [x] QGC Implementation
##### Footnotes

<b id="f1">1</b> The current giimbal driver doesn't actually communicate with a gimbal via MavLink, but rather interprets the `MAV_CMD_DO_MOUNT_CONFIGURE` and `MAV_CMD_DO_MOUNT_CONTROL` commands, calculates pitch, roll and yaw and advertises them on the `actuator_controls_2` topic, to be used by a mixer, which then can be used to control a gimbal via it's RC inputs. [↩](#a1)

<b id="f2">2</b> Most gimbals now natively support MavLink (like the Storm32) and (as specified and intended by the MavLink specification) understand the `MAV_CMD_DO_MOUNT_CONFIGURE` and `MAV_CMD_DO_MOUNT_CONTROL` commands in the `COMMAND_LONG` message to operate the gimbal. If a gimbal does not support MavLink, the old gimbal driver can still be used to interpret those messages and control the gimbal via RC instead.
[↩](#a2)

<b id="f3">3</b> The `vehicle_roi` topic will have to store the following:
- ROI type (as defined by the `MAV_ROI` enum)
- Mission index to point to (for the MAV_ROI_WPINDEX mode)
- Target index to point to (for the MAV_ROI_TARGET mode)
- X, Y and U (for the MAV_ROI_LOCATION mode)
  [↩](#a3)

**Comment by LorenzMeier** [comment]
@thedevleon Your proposal sounds excellent and correct regarding the vehicle architecture. It would be fantastic if you would be willing to start to work on it.

**Comment by lvale** [comment]
@thedevleon Be aware that Mavlink parsing by gimbal controllers is not guaranteed, as some implement specific serial protocols (like AlexMos and also STorM32-both serial and mavlink)

**Comment by thedevleon** [comment]
I agree @lvale. That's why I was saying that this is a 2 part issue.
The implementation, parsing and publishing of the ROI via uORB would be one thing, and the actual gimbal driver handling the communication (and limitations) would be the other :)

**Comment by thedevleon** [comment]
There has been more development on this by me :) Please head over to #4624 for more info, as I changed things a bit as I went along.
It's already 90% done :D

**Comment by dagar** [comment]
Implemented.
