### ISSUE TITLE
px4fmu-v2_default - Channel mapping has no effect for AUX channel pass throught

### ISSUE THREAD

**Issue by gianni-carbone** [PX4/Firmware#4600]
Channel mapping settled by qgroundcontrol has no effect for AUX channel pass through
AUX1 and AUX2 has fixed PWM
Other AUX channels are inactive

**Comment by LorenzMeier** [comment]
Looking into this.

**Comment by dagar** [comment]
Fixed?

**Comment by mhkabir** [comment]
I think this is fixed. It will also be cross-tested during my trigger overhauling, so I will handle it there if still present.
