### ISSUE TITLE
VTOL decreases altitude during transition to fw

### ISSUE THREAD

**Issue by nkhoit** [PX4/Firmware#4612]
http://logs.uaventure.com/view/aNd5eCeXsfm4Bfn8WLh2ML#Local_Z_PLOT

A look at LPSP.VZ shows the climb rate controller commanded a negative climb rate of 2 m/s which is equal to our MPC_Z_VEL_MAX. 

![altitude_drop](https://cloud.githubusercontent.com/assets/1168541/15485491/aa09b0bc-210d-11e6-9745-ed7d1afc45ac.png)

**Comment by tubeme** [comment]
We've had this phenomenon in Altitude mode transition two weeks ago. But no problems in Stabilized at the same time. In the coming days, when we have a weather window, we will fly test it again and will report with LOG graphics as well.

**Comment by sanderux** [comment]
@nkhoit what kind of vehicle are you flying?

**Comment by sanderux** [comment]
Also, i see you have added a custom param VT_MC_TO_FW_PIT that is set to -6
And you have FW_PSP_OFF set to -6 too, in most cases you would want that positive, realy depends on your airframe
