### ISSUE TITLE
Pixracer out of memory

### ISSUE THREAD

**Issue by birchera** [PX4/Firmware#4644]
While testing EKF2 with pixracer on a fixed-wing, we encountered problems with memory. Running all the standard modules and only 7kB stack for logging, we were not able to do any calibrations, due to the lack of memory. Disabling the position controller allowed us to do the calibration. However, when re-enabled the position controller, some modules also don't run correctly during flight.

![screenshot from 2016-05-26 11 33 58](https://cloud.githubusercontent.com/assets/2298059/15570314/c882282e-2335-11e6-9d69-7eb822e66845.png)

FYI @tumbili @priseborough @CarlOlsson

**Comment by julianoes** [comment]
Nothing seems excessive except that 4 mavlink instances are running. Are they all needed?

**Comment by birchera** [comment]
I made a couple more tests and it turns out that every time I flash (ea138cfd380c06179d2e89cdd8167637dbd96d54 with EKF2 enabled), different errors occur:
* Pixracer is spontaneously rebooting, every other 30s
* Cutecom connection is suddenly closing and cannot be reopened until rebooting
* Calibration is not possible, reason given in QGC: Out of memory
* Cutecom connection is closing upon calibration
Without reflashing, errors seemed repeatable so far.

When starting with the old estimator, none of these have occurred.

**Comment by julianoes** [comment]
@birchera: interesting. Don't you get a stack trace when Pixracer reboots?

**Comment by LorenzMeier** [comment]
@priseborough This is something worthwhile to keep an eye on. It could point to stack smashing or out of mem.

**Comment by LorenzMeier** [comment]
This is the right command to hunt some of that down: ```arm-none-eabi-nm --size-sort --print-size --radix=dec build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx | grep " [bBdD] "```

**Comment by LorenzMeier** [comment]
Related issue:
https://github.com/PX4/Firmware/issues/4677

If you disable UAVCAN and the Snapdragon drivers in the build you should be able to free up 3K.

**Comment by LorenzMeier** [comment]
@birchera I should have fixed this on master. Can you re-try?

**Comment by birchera** [comment]
Thanks Lorenz! On fixed-wing, pixracer, EKF2, we have now ~26K free memory, which should be sufficient.

**Comment by tumbili** [comment]
@birchera  what size  of  logbuffer  are  you  using  now?

**Comment by birchera** [comment]
Standard 12K
