### ISSUE TITLE
SITL not taking off

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#4646]
SITL doesn't seem to be working anymore.

From my investigation, the sensors module is timing out because no gyro data is published.

The accelsim::_measure() call is stopped when this line happens:
https://github.com/PX4/Firmware/blob/master/src/platforms/posix/drivers/accelsim/accelsim.cpp#L1087

**Comment by julianoes** [comment]
The first commit where this fails is:
https://github.com/PX4/DriverFramework/commit/c96a07455efadc68476eb181d4d5cf87df1f4eeb

**Comment by mcharleb** [comment]
@julianoes What can I do to help debug this?

**Comment by julianoes** [comment]
@mcharleb please review https://github.com/PX4/DriverFramework/pull/85
