### ISSUE TITLE
servo center adjustment

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#4650]
It would be nice to be able to tweak the servo center slightly at runtime. Sometimes it's hard to center servos perfectly, especially field replacements.

It's not clear to me what the best solution is. We could modify the active mixer (mavlink ftp), new mavlink cmd, use params, etc. I think a simple param for each servo channel would get the job done, but correcting the mixer might make more sense?

**Comment by tubeme** [comment]
Very good idea!

**Comment by edsellar** [comment]
I've run into this issue so many times. Definitely a great idea!

**Comment by kd0aij** [comment]
I vote for exposing the mixer parameters to allow setting center *and endpoints* to provide the same functionality that one normally has with an RC transmitter.

What is "mavlink ftp"? Would you copy a new mixer into RAM, then invoke "mixer load"? That sounds pretty awkward to implement, since you'd have to edit a mixer file somewhere first.

**Comment by dagar** [comment]
The other piece of the mavlink ftp idea is a simple editor in QGC and one
button to transfer and load the new mixer.

**Comment by dagar** [comment]
Yet another idea - onboard calibration.
With the basic mixer in place you could be walked through each output and asked to hold center and then each extreme.

**Comment by kd0aij** [comment]
It appears that the servo center point is implicitly the midpoint between pwm_min and pwm_max:
https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/pwm_limit/pwm_limit.c#L181

That would make the center point dependent on the endpoints.

**Comment by LorenzMeier** [comment]
I think we should introduce parameters (like the reverse params) for this purpose. Best would be to use the mixer, but we should take one step at a time.

**Comment by dagar** [comment]
Once we have that in place we could add a simple setup screen in QGC using the metadata from the airframe.
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/2101_fw_AERT#L7

**Comment by LorenzMeier** [comment]
Let me handle that here. Your time is way better spent with CI. I know what I have to do here.

**Comment by dagar** [comment]
Sounds good to me!
Thanks Lorenz

**Comment by dagar** [comment]
@bartosz-wawrzacz implementation here - https://github.com/PX4/Firmware/issues/4650

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/pull/5720
