### ISSUE TITLE
Snapdragon: Check adsp image version

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#4653]
We should check if the version of the static adsp image is recent enough when starting PX4 on Snapdragon (and before running things on the DSP).

Pointers:

> The new app is version_test.
> 
> cd dspal/test
> make load
> 
> On target run version_test

**Comment by mcharleb** [comment]
If the adsp image is missing symbols that PX4 is using, then the library load on the DSP will fail. The version check may have to be run as a separate executable before PX4

**Comment by julianoes** [comment]
@mcharleb I see your point but how often will this be the case that there are new and therefore missing symbols?
