### ISSUE TITLE
Standard VTOL airframe reports MAV_TYPE as MAV_TYPE_QUADROTOR

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#4660]
Instead of MAV_TYPE_VTOL_QUADROTOR. Which in turn causes QGC to show the wrong things. I didn't check all the other VTOL types for correctness. But those should be checked as well.

**Comment by LorenzMeier** [comment]
Which airframe did you select?

**Comment by DonLakeFlyer** [comment]
Standard VTOL

**Comment by LorenzMeier** [comment]
It reports two different VTOL types - what is going on with QGC?

Console is correct on PX4:

<img width="776" alt="screen shot 2016-05-27 at 20 09 25" src="https://cloud.githubusercontent.com/assets/1208119/15616960/f8636f64-2446-11e6-82db-3bbc301727da.png">


Param value is incorrect in QGC:

<img width="1241" alt="screen shot 2016-05-27 at 20 08 09" src="https://cloud.githubusercontent.com/assets/1208119/15616964/fe2df798-2446-11e6-8f48-439964f69d6e.png">


Value via MAVLink is correct:

<img width="692" alt="screen shot 2016-05-27 at 20 07 01" src="https://cloud.githubusercontent.com/assets/1208119/15616885/a52672ce-2446-11e6-996c-0127d9ae2c5f.png">

**Comment by dagar** [comment]
This is probably why setting the airframe to a fixed wing for the first time results in the safety screen still showing multicopter icons and settings after the auto reboot and reconnect.

**Comment by LorenzMeier** [comment]
I filed an issue for QGC and will close this one.

**Comment by LorenzMeier** [comment]
https://github.com/mavlink/qgroundcontrol/issues/3422

**Comment by DonLakeFlyer** [comment]
QGC pays no attention to the MAV_TYPE parameter. It gets MAV_TYPE from the heartbeat and sets it once from there.

**Comment by DonLakeFlyer** [comment]
> This is probably why setting the airframe to a fixed wing for the first time results in the safety screen still showing multicopter icons and settings after the auto reboot and reconnect.

Nope (MAV_TYPE from hearbeat). Does that repro on latest builds. If so can yo uput and issue in?

**Comment by DonLakeFlyer** [comment]
When you change airframe from QGC and then the board reboots the first heartbeat QGC gets will have a MAV_TYPE of the old type and then the second heartbeat it gets will have the correct new MAV_TYPE. QGC constructs the Vehicle from the first heartbeat with the incorrect MAV_TYPE and then all hell breaks loose from then on.

**Comment by dagar** [comment]
We can either move mavlink to the end of the init script or use the boot_complete command the mavlink app already has.

**Comment by LorenzMeier** [comment]
@dagar @DonLakeFlyer This should fix it. I didn't get to test it yet: https://github.com/PX4/Firmware/pull/4666
