### ISSUE TITLE
Plane model for Gazebo

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4671]
@hsu This is to track the bug fixing of the plane model in Gazebo. @tfoote @tumbili @CarlOlsson FYI.

**Comment by hsu** [comment]
I need help understanding the collision shapes used for the [plane model](https://github.com/PX4/sitl_gazebo/blob/master/models/plane/plane.sdf)

![plane_collisions](https://cloud.githubusercontent.com/assets/138109/15692832/a1f3d022-2745-11e6-8d6c-f09c2e29a4fe.png)

why they are very different from the visual.  Thanks.

**Comment by hsu** [comment]
Change to collision models to stabilize contacts

https://github.com/PX4/sitl_gazebo/pull/23

**Comment by LorenzMeier** [comment]
The collision model is just inexperience / hacking on our part. I guess we should look at doing a clean new model.

**Comment by hsu** [comment]
got it. If you like, I can take a rough pass at the collision shape. I take it's not super critical how the plane makes contact with surrounding environments, except mabye 1+ box-shaped collision shape that envelopes the whole visual model with stable contacts with the ground? Do you plan to use the wheels for runway / taxiway operations?

**Comment by LorenzMeier** [comment]
Finished / working.
