### ISSUE TITLE
Validate PX4 SITL for ROS, add 3D sensor

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4675]
@vilhjalmur89 Could you please validate the instructions here on Monday:

http://dev.px4.io/simulation-ros-interface.html

And report here if anything doesn't work?

**Comment by vilhjalmur89** [comment]
It seems to work

**Comment by LorenzMeier** [comment]
Ok -can you move your workflow to it?

**Comment by dagar** [comment]
Closing, please reopen if still needed.
