### ISSUE TITLE
Master doesn't initiate vtol channels

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4682]
Current master does not send any signal on the aux ports when configured as vtol standard delta

**Comment by sanderux** [comment]
Latest known working currently is https://github.com/PX4/Firmware/pull/4522

**Comment by sanderux** [comment]
Could be ram related and possibly fixed on current master after @LorenzMeier's fix.
Will test this evening

**Comment by LorenzMeier** [comment]
Did you get a chance to test?

**Comment by sanderux** [comment]
Tested, aux channels actuate again.
