### ISSUE TITLE
Airspeed sensor auto calibration

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4694]
As discussed in devcall 20160530 i will add an automated boot-time calibration mode for the airspeed sensor. It will be disabled by default and should only be enabled after a succesful manual calibration after any hardware change.
- Auto calibration will not ask the user to blow on the airspeed sensor, instead it will attempt to calibrate and issue a warning if the pressure is not constant. It would be recommended when using this procedure to equip the pitot tube with a cover and a 'remove before flight' label.

Assumptions
- Instead of using a parameter in the sensor category i propose to use a circuit breaker that is set by default.
- I propose to add an autoCalibration bool to https://github.com/PX4/Firmware/blob/master/src/modules/commander/airspeed_calibration.cpp#L74
- I propose to call this procedure from here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L1520

@tumbili do you agree?

**Comment by LorenzMeier** [comment]
I'm closing this in favor of replacing it with a sensirion unit.
