### ISSUE TITLE
The landing waypoint set failed

### ISSUE THREAD

**Issue by zengdechi** [PX4/Firmware#4700]
in mission_feasibility_checker.cpp ,fw_pos_ctrl_status could not get correct parameter.This led directly to the landing waypoint set failed. how to fixed this bug?

**Comment by dagar** [comment]
I'll try to reproduce this in HIL.

**Comment by zengdechi** [comment]
@dagar  now,if I choose HILstar(XPlane) in QGC,the sensors can not  calibrate. why?

**Comment by dagar** [comment]
The autopilot sensors aren't used in HIL. The data comes from the simulator.

**Comment by dagar** [comment]
This was fixed in #4835
