### ISSUE TITLE
SITL sending multiple MISSION_COUNT responses to MISSION_REQUEST_LIST

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#4721]
Using daily QGC and master firmware:
1) Boot SITL
2) Boot QGC
3) QGC will send MISSION_REQUEST_LIST
4) SITL will send multiple MISSION_COUNT messages (item count=0 which is correct)

You can see this from QGC error messages or you can turn on MissionManagerLog to see as well the single request from QGC and the multiple MISSION_COUNT's coming back.

**Comment by dagar** [comment]
Resolved?

**Comment by LorenzMeier** [comment]
Yes
