### ISSUE TITLE
Bugs in the yaw calculation of snapdragon flight.

### ISSUE THREAD

**Issue by SamChenzx** [PX4/Firmware#4725]
My P2 snapdragon flight still can't fly though rotation parameter has been set. Today I attempted to use the mag in MPU9250, the result is heading will slowly circle clockwise. If HMC5883 in 3DR GPS module is used, didn't circle but if I rotate quadrotor 90 degrees clockwise every time, it slowly try to turn to the origin direction before it turned. I've tried to invert y direction or invert x direction at HMC5883.cpp https://github.com/PX4/DriverFramework/blob/791c584969b2f84b2921c8c8c373962c677cefdb/drivers/hmc5883/HMC5883.cpp#L237, still the same as the follow plots:
<img width="1440" alt="screen shot 2016-06-02 at 10 08 56 pm" src="https://cloud.githubusercontent.com/assets/10758544/15769609/8584c4d2-2911-11e6-9114-947bf9a3e078.png">

<img width="1440" alt="screen shot 2016-06-02 at 9 59 04 pm" src="https://cloud.githubusercontent.com/assets/10758544/15769612/8d27babe-2911-11e6-9037-0e9a3f79d4b0.png">

<img width="1440" alt="screen shot 2016-06-02 at 9 50 06 pm" src="https://cloud.githubusercontent.com/assets/10758544/15769614/90cad16a-2911-11e6-9ce4-3a1d72812f46.png">

<img width="1440" alt="screen shot 2016-06-02 at 9 15 30 pm" src="https://cloud.githubusercontent.com/assets/10758544/15769617/943315ba-2911-11e6-9ebe-4f1897b289d2.png">

<img width="1440" alt="screen shot 2016-06-02 at 9 36 22 pm" src="https://cloud.githubusercontent.com/assets/10758544/15769619/97939eb4-2911-11e6-9681-3f618e8a636f.png">

**Comment by mhkabir** [comment]
@SamChenzx Please don't open multiple issues for the same topic. Let's continue the discussion on https://github.com/PX4/Firmware/issues/4652.
