### ISSUE TITLE
langding bug of fixwing

### ISSUE THREAD

**Issue by zengdechi** [PX4/Firmware#4745]
Today I broke my model.In Hil,landingslope.flare_relative_alt() always equal zero. it lead to can not limt throttle.

**Comment by dagar** [comment]
Which version of the firmware are you using?

**Comment by zengdechi** [comment]
I download the source code from github on May 24.

**Comment by dagar** [comment]
I've reproduced this locally. I'll try to fix it tomorrow.

**Comment by LorenzMeier** [comment]
@dagar This will enable SITL with planes: https://github.com/PX4/Firmware/pull/4798

**Comment by dagar** [comment]
@zengdechi this has been fixed in master.

**Comment by LorenzMeier** [comment]
Thanks for fixing it @dagar
