### ISSUE TITLE
Circling flight mode

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4752]
@tumbili We need to introduce a circle flight mode for multicopters which allows to orbit a given position. This should either be enabled by setting the origin and radius in the UI (in a mission, or in the LOITER / HOLD mode) or by flicking a switch on the remote, which re-maps the sticks to move the drone along the circle and adjust the radius.

**Comment by tubeme** [comment]
Movie mode! Perfect idea!

**Comment by tumbili** [comment]
Implemented in #4792
