### ISSUE TITLE
param SYS_MC_EST_GROUP not available in px4fmu-v2_ekf2

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#4757]
Once you have flashed px4fmu-v2_ekf2 on to Pixhawk, you can't actually change the param `SYS_MC_EST_GROUP` to `2` because the param can't be found.

The param should always get compiled in, not sure why this isn't the case.

**Comment by LorenzMeier** [comment]
Because the param has no function for that development version. I'll close this. The param will be active in standard pixhawk once we replaced EKF1 with EKF2.

**Comment by julianoes** [comment]
Hm, I must have mistyped something or been confused. I just played through this and the param is available for both and seems to work. Sorry about that.
