### ISSUE TITLE
SITL takeoff problem

### ISSUE THREAD

**Issue by marianobianchi** [PX4/Firmware#4765]
When running "make posix_sitl_default gazebo" and then execute "commander takeoff 1" in the px4 console everything works correctly.

On the other hand, if I run these commands in different consoles:
* Console 1:
  * source <ROS_WORKSPACE>/devel/setup.bash
  * source <FIRMWARE_REPO_PATH>/integrationtests/setup_gazebo_ros.bash <FIRMWARE_REPO_PATH>
  * roslaunch px4 posix_sitl.launch
* Console 2:
  * source <ROS_WORKSPACE>/devel/setup.bash
  * roslaunch mavros px4.launch fcu_url:=udp://localhost:14540@localhost:14557
* Console 3:
  * source <ROS_WORKSPACE>/devel/setup.bash
  * rosservice call /mavros/cmd/arming true
  * rosservice call /mavros/cmd/takeoff 0 0 0 0 1

I expected to have the same result as running "takeoff" in the px4 console but instead the UAV took off inclined to one side. Then it crash in the ground and stayed upside down. I attach some photos to clarify my poor english (sorry!)

![felt_to_the_ground](https://cloud.githubusercontent.com/assets/1700075/15877223/06f54cf0-2ce9-11e6-98e6-279335786427.png)

![upside_down](https://cloud.githubusercontent.com/assets/1700075/15877229/1b13004c-2ce9-11e6-8561-f198cf59e292.png)

![inclined](https://cloud.githubusercontent.com/assets/1700075/15877463/5539c41c-2cea-11e6-850f-b9a50353c344.jpg)

Am I doing something wrong?

**Comment by LorenzMeier** [comment]
I think the culprit is your takeoff command. You're telling the drone to fly to africa (latitude and longitude 0, 0). You need to send it either NaN to ignore those or send the current position.

**Comment by marianobianchi** [comment]
Ohh, i'm sorry... I thought /mavros/cmd/takeoff was a takeoff at current position (using current position as 0,0 for longitude, latitude).

I will try to learn how to debug so i don't bother you with these kind of questions.... If you have some advice on how to debug I will thank you pretty much

**Comment by marianobianchi** [comment]
@LorenzMeier, I tried running "rosrun mavros mavcmd takeoffcur 0 0 1" to avoid giving current coordinates. I get a message "Taking-off from current coord: Lat: 47.397742 Long: 8.5455941" but I still get the same behaviour as before.
