### ISSUE TITLE
VTOL does not loiter if no WP after transition

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#4769]
Tested a mission that consists of a takeoff waypoint and a VTOL transition waypoint to fw flight.
After the transition the navigator announces loiter mode due to completed mission but the plane just keeps on flying in a straight line.
@AndreasAntener FYI

**Comment by sanderux** [comment]
transition sets a virtual waypoint in front of the vehicle (far in front), perhaps that causes this behavior?
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L340-L350

**Comment by dagar** [comment]
Fixed?

**Comment by dagar** [comment]
I believe this is resolved. Please reopen if I'm incorrect.
