### ISSUE TITLE
Complete STL files for X8 Delta VTOL

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4774]
@sanderux I have the main body - could you export your mounts so we can add them?

<img width="979" alt="screen shot 2016-06-08 at 13 20 18" src="https://cloud.githubusercontent.com/assets/1208119/15892786/00966716-2d7c-11e6-9f7c-3909238228c6.png">

**Comment by sanderux** [comment]
@LorenzMeier module designs are coming, here's a sneak preview of the motor mounts we designed, (this is the first prototype:
![image](https://cloud.githubusercontent.com/assets/14801663/15949314/c5ff6b94-2ea6-11e6-9b2e-e4f5fb3135db.png)

If you have a 3d scanner i would very much like a scan of the wing joiners
