### ISSUE TITLE
TBS Caipi parameters

### ISSUE THREAD

**Issue by sirPerna** [PX4/Firmware#4795]
I tested PX4 on my caipi now for a few months and it works great! The attached parameters worked best for me. Is it possible they become the default parameters for Caipi flying wing? I use the 3s power setup. 
[Caipi PX4.txt](https://github.com/PX4/Firmware/files/309159/Caipi.PX4.txt)

**Comment by dagar** [comment]
Can you put the important params you want to change in this file https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/3100_tbs_caipirinha and post a test flight to logmuncher?

http://logs.uaventure.com/

**Comment by sirPerna** [comment]
How can I reverse PWM outputs? I added this:
 	param set PWM_MAIN_REV0 1
  	param set PWM_MAIN_REV1 1
It doesn't seem to accept it.

**Comment by LorenzMeier** [comment]
Set them via QGroundControl instead. Make sure to not have any text files on your SD card.

**Comment by sirPerna** [comment]
So it's not possible to reverse the PWM outputs modifying following file? 
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/3100_tbs_caipirinha

**Comment by LorenzMeier** [comment]
ah, sorry, in the autostart file its possible and correct.

**Comment by IeiuniumLux** [comment]
In v1.8.0 the PWM_MAIN_REV* params are not longer listed/displayed in QGC v3.3.2.  Does this mean that we now need to manually set them up in [the init file](https://github.com/PX4/Firmware/blob/7a82c777b28c49b3476be3da716984e6bdc987a9/ROMFS/px4fmu_common/init.d/3033_wingwing) and build the firmware?

**Comment by LorenzMeier** [comment]
They should load in QGC. Did you look in the PWM Outputs group?

**Comment by IeiuniumLux** [comment]
Yes, I did.  Only the AUX and DIS are listed.
