### ISSUE TITLE
BAT_V_SCALING and BAT_C_SCALING disappeared w/o ROMFS vehicle updates

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#4799]
I just tried to fly my 3dr iris on master, but the battery voltage is reading 10.2 when it should be 12.5 volts. I looked at the firmware on master and saw that all of the params set fot he battery in the iris ROMFS have now disappeared.

**Comment by dagar** [comment]
BAT_V_SCALING -> BAT_CNT_V_VOLT
    BAT_C_SCALING -> BAT_CNT_V_CURR
    BAT_C_OFFSET -> BAT_V_OFFS_CURR

I've seen this happen a few times so I was trying to think of something we could do to catch it. Maybe we could default `param set` to fail if not found. Then if we had a nuttx sim build it could run through loading all airframe configs. The other option is just being more careful...

**Comment by jgoppert** [comment]
Yeah, sending a message to the use would be best via mavlink info.

**Comment by jgoppert** [comment]
Resolved for me on master.
