### ISSUE TITLE
Set yaw setpoints in waypoint navigation

### ISSUE THREAD

**Issue by ndepal** [PX4/Firmware#4803]
PX4 supports multiple yaw modes for multicopter waypoint navigation as described here: https://pixhawk.org/users/multirotor_yaw_modes

I need finer control on the drones yaw behavior. Specifically, I need to be able to control where the drone is facing at all times. E.g. I want to be able to fly to an object and then around it, always facing it.
Thus it would be useful to be able to set a yaw setpoint in a waypoint, which is interpolated between waypoints.

As far as I can see, this is not currently possible. Is this something that could be implemented?

I suppose I could forgo using waypoints altogether and send position/yaw setpoints over mavlink with offboard control, but it seems like this would be a useful feature for waypoint navigation.

**Comment by dagar** [comment]
Still needed?

**Comment by ndepal** [comment]
Nope, heading towards ROI solves this for me.
