### ISSUE TITLE
MavlinkReceiver memory corruption.

### ISSUE THREAD

**Issue by lovettchris** [PX4/Firmware#4823]
MavlinkReceiver::handle_message_request_data_stream walks into deleted memory when you send the "stop" bit on a stream.  It also fails to restart the stream because it deletes the stream when you send the stop command.  The fix for this is here: 
[1e0e56b6c632ae93df5a86ec5cd6dbb244ce728c](https://github.com/lovettchris/Firmware/commit/1e0e56b6c632ae93df5a86ec5cd6dbb244ce728c)

PS: the stop bit is the last parameter on msg id 66, REQUEST_DATA_STREAM, named "start_stop" with description: 1 to start sending, 0 to stop sending.

**Comment by mhkabir** [comment]
@lovettchris It would be awesome if you could send in a PR with that commit for ease of tracking and review. Thanks!

**Comment by lovettchris** [comment]
Done ☺

https://github.com/PX4/Firmware/pull/4824
