### ISSUE TITLE
Takeoff possibly broken in SITL on stable branch

### ISSUE THREAD

**Issue by MHageH** [PX4/Firmware#4833]
I used the general procedure, but instead of using the master branch, I tried to take off in SITL in the stable branch

```
$ git clone https://github.com/PX4/Firmware.git --verbose ; 
$ cd Firmware;
$ git checkout stable
$ git pull origin stable
$ git submodule update --init --recursive 
$ make -j4 posix_sitl_default jmavsim
```

The quad becomes unstable when it takes off the ground. 
The takeoff is fine on the master branch tho.

**Comment by TobiMiller** [comment]
Did you try autotakeoff command in reallife? i have the same behaviour there. 3 crashes and i thought it is my code. but now with stable stack as SITL i know it seems to be a firmware thing. I think this is critical for a stable firmware.

**Comment by MHageH** [comment]
@TobiMiller Actually for the real hardware, I flashed the latest firmware provided from qgroundcontrol, not directly from the stable branch on PX4/master.
I directly use the C UART Interface to arm and fly without ever passing by auto takeoff or qgroundcontrol : [footage](http://sendvid.com/ziebmszp). 
Altho this happens on the stable branch, it doesn't on the master one.

**Comment by LorenzMeier** [comment]
There is not enough context here - what does not work for you?

**Comment by MHageH** [comment]
@LorenzMeier When you do a ``` make posix_sitl_default jmavsim ``` on the [stable](https://github.com/PX4/Firmware/tree/stable) branch, everything works fine, except when you try to do a ```commander takeoff``` from the NuttX shell, the quad crashes.
Is there any difference between the [stable releases](https://github.com/PX4/Firmware/releases), the PX4 [stable] (http://px4-travis.s3.amazonaws.com/Firmware/stable/index.html) firmware (used by QGroundControl) and the  [stable](https://github.com/PX4/Firmware/tree/stable) branch of PX4 ?

**Comment by LorenzMeier** [comment]
No, those are all in sync. There will be a stable release within the next days.

**Comment by MHageH** [comment]
@LorenzMeier Could you please check if you can reproduce this bug? It doesn't happen at all with the master branch.

**Comment by dagar** [comment]
@MHageH is this still a problem?

**Comment by MHageH** [comment]
@dagar I've test it again, the drone takes off to a stable position. You may close this issue.
