### ISSUE TITLE
MissionCheck.py can't connect

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#4847]
@sanderux I've started looking at putting SITL MissionCheck in the builds, but so far I've been unable to connect. Is this still working for you?

    dronekit.APIException: Timeout in initializing connection.

**Comment by sanderux** [comment]
Hi @dagar 
I havent tried it recently but you could try to disable the "waitconnected" param in the connect function.
I will have a look next week when i have some more time

**Comment by LorenzMeier** [comment]
Should be fine now.
