### ISSUE TITLE
dronekit log analyzer

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#4848]
Investigate using dronekit-la for PX4 testing.
https://github.com/dronekit/dronekit-la

@sanderux @LorenzMeier I'm just getting started with DroneKit. Is there work to be done for PX4 DroneKit compatibility?

**Comment by ecmnet** [comment]
@dagar Would be interesting to make MAVGCL a frontend for the JSON results

**Comment by dagar** [comment]
I like the idea, but dronekit-la is too Ardupilot specific.
