### ISSUE TITLE
Avionics Power Low, Refused Spektrum Bind Command, 

### ISSUE THREAD

**Issue by JPluess** [PX4/Firmware#4856]
dear development team, 

1. i have a power module that provides 5.19v. and this makes up for 4.9v for the inside of the px4, 
there is a feature that bloks arming? i wish to disable this feature, 

the website states the voltage ratings for:

    Normal Operation Maximum Ratings

    Under these conditions all power sources will be used in this order to power the system.

    Power module input (4.1V to 5.7V) [refers to the voltage coming into Pixhawk from the power module]

    Servo rail input (4.1V to 5.7V)

    USB power input (4.1V to 5.7V)

http://ardupilot.org/copter/docs/common-powering-the-pixhawk.html

![bild 3](https://cloud.githubusercontent.com/assets/7995240/16203839/79e7e320-371c-11e6-936f-426b88fb8adb.png)

2. The bind command is refused, satelite receiver wont go into bind mode.  see image.

![bild 3ss](https://cloud.githubusercontent.com/assets/7995240/16203831/741b1304-371c-11e6-94cf-b76bacad61f9.png)

can somebody take a minute to look at this question? thanks alot
joel

**Comment by LorenzMeier** [comment]
Please flash current master (during the Firmware upgrade tick the advanced checkbox and choose the development version), re-do the airframe config (this will force you to calibrate sensors again) and report back. The power information you have was indeed based on outdated information. Better values are explained here: https://pixhawk.org/modules/pixhawk#voltage_ratings.

The voltage does not actually prevent you from arming. What other error message are you getting? Click on the exclamation mark.

Which autopilot are you using?

One last resort item you can try is to hold down the safety switch while applying power, which will force an IO processor reset.

**Comment by JPluess** [comment]
![bild 5](https://cloud.githubusercontent.com/assets/7995240/16227691/785e22c6-37b2-11e6-8e1c-2a19d1332999.png)

![bild 6](https://cloud.githubusercontent.com/assets/7995240/16227690/78535a44-37b2-11e6-8951-99ed5af4360d.png)

well the bindcommand seems to be an issue on the beta version aswell, how about this. 

i have autopilot version 2.4.8

about the avionics power low error i will respond soon

**Comment by LorenzMeier** [comment]
Your issue is what the autopilot tells you: The sensors are not set up correctly. Can you please re-do the airframe configuration and re-do the sensor calibration?

**Comment by LorenzMeier** [comment]
We already have an issue for the sensor message: https://github.com/PX4/Firmware/issues/4695

The Spektrum binding works according to your output. You need to make sure to put your Transmitter into the right mode as well, as it will only pair if you do that on both ends correctly.

**Comment by JPluess** [comment]
i have now flashed the development verison and spektrum bind is still not working. 
![bild 9](https://cloud.githubusercontent.com/assets/7995240/16228251/35dfbeec-37b6-11e6-85a3-b0ef35da82b4.png)

allright i have redone the sensor calibration, it wont arm, see message below, 4.87V, i know it does arm if i use a powermodule that gives a little more voltage, but taking it out, is difficult. 

the airfraime, i have set to this: 
![bild 8](https://cloud.githubusercontent.com/assets/7995240/16228228/0bc0a73e-37b6-11e6-80a7-11a53d81a3d1.png)

**Comment by LorenzMeier** [comment]
Are you trying to arm while you are on USB power? That is not allowed. Its possible that the low power message (which does not prevent you from arming, its just a warning) overlays the USB power warning. If you are on USB, try disconnecting the cable.

**Comment by JPluess** [comment]
No actually i have a 3dr radio wired to the px4, and all commands are sent by 433mhz,

**Comment by JPluess** [comment]
have you tried to arm one of yours on a adjustable voltage supply? so it should arm down to 4.8v? or even down to 4.1?

**Comment by JPluess** [comment]
so what now? any news?

**Comment by JPluess** [comment]
do you need any more information

**Comment by agribov** [comment]
I have this issue as well. I'm powering my Pixhawk through a BEC on the servo rail, and about 50% of the time, when I try to arm it it gives me the "Avionics power low" shout-out, and the other 50% of the time it just arms. Usually it arms right after giving me the error.

Is there any way we can manually lower the avionics power threshold, or resolve this issue?

**Comment by LorenzMeier** [comment]
We have since reworked this quite a bit. Early boards have a HW issue preventing bind, but in recent board everything works as expected with binding.

**Comment by 1JonaB1** [comment]
I have the same problem any tipps ?

**Comment by JPluess** [comment]
I had to change the powermodule
