### ISSUE TITLE
build system performance issues

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#4871]
@LorenzMeier @bkueng @julianoes @tumbili 
Document your travis-ci, semaphoreci, etc issues here, especially performance related. I generally work on these things at night when they seem to be reasonably fast, but if the performance isn't acceptable during a typical development day document it here and I'll consider the options.

With the build environment containerized it would be easy to distribute the load between travis-ci, semaphoreci, circleci, and optionally jenkins.

I've also contacted travis-ci.

TODO
 - [x] travis-ci OSX cache homebrew
 - [x] travis-ci OSX cache pip
 - [ ] semaphoreci enable caching
 - [ ] circleci enable caching

**Comment by dagar** [comment]
Travis-ci OSX consistently has problems - https://www.traviscistatus.com/incidents/nf3tg08pqg2d

**Comment by dagar** [comment]
@PX4/dev-team - Consider using your own PX4/Firmware fork for pull requests instead of pushing a new branch to the main PX4/Firmware repo. When you push a branch to the main repo travis-ci builds both the branch and the result of the merge. If you use a fork it only builds the result of the merge. This will help reduce our load on travis-ci and improve the build system for everyone. 
This has the side benefit of reducing branches off the main repo.

**Comment by dagar** [comment]
@LorenzMeier could you help me with homebrew caching on travis-ci or put me in touch with another OSX developer?
The current OSX build spends the majority of its time on homebrew. Can you do a fetch into a travis-ci cached directory and offline install?

**Comment by dagar** [comment]
Travis-ci support was helpful. I paid tier would give guaranteed concurrent jobs, but once we get a machine it's the same. I've stripped down the travis-ci build as much as I can.

**Comment by dagar** [comment]
Travis-ci seems to be ~ 8-10 minutes per build now. If we want to reduce that any further (5 minute goal?) I think we'll need to start looking at our own hosting.

@LorenzMeier ping me if you see more problems or want to pursue other options.

**Comment by sanderux** [comment]
@dagar I have a qemu hypervisor (proxmox) in a hostingcenter 
do you have specs needed for running our own? or an image i could run as a test?

**Comment by dagar** [comment]
Thanks @sanderux, but if you're paying per usage I suspect a virtualized compile machine is going to be quite expensive.

We have docker images for the dev environments (https://hub.docker.com/r/px4io/px4-dev-base/), otherwise it's just ubuntu + instructions (http://dev.px4.io/starting-installing-linux.html).

**Comment by sanderux** [comment]
@dagar the hardware is mine, the only thing i pay for is data but i dont think that will exceed what i'm already paying for.
If i give you root to a vps, what environment would you prefer?

**Comment by dagar** [comment]
Thanks Sander. Just stock Ubuntu 16.04 server, then I'd install jenkins and
docker. The web interface would need to be public to connect to github.

**Comment by sanderux** [comment]
I'll pm you login details over skype.

**Comment by sanderux** [comment]
How much disk, ram and cpu cores? I'd say 20g 4g and 4 cores? I have more than enough of all

**Comment by dagar** [comment]
20GB disk is probably sufficient. The more memory and cpu you can throw at it the better. 4GB ram and 4 cores is roughly what travis-ci provides, although I suspect those cores are pretty heavily shared.

**Comment by sanderux** [comment]
8gb/6cores setup. auth is in your mail.
let me know how you get on, if it works and improves performance we can set it permanently

**Comment by dagar** [comment]
Thanks Sander!

**Comment by sanderux** [comment]
i saw it quickly reached full mem when compiling, upped it to 10gig
