### ISSUE TITLE
derivative block bug with cutoff frequency setup

### ISSUE THREAD

**Issue by langxm1223** [PX4/Firmware#4892]
In the mc_pos_control_main.cpp line 1313,

```
_vel_err_d(0) = _vel_x_deriv.update(-_vel(0));
```

here it invokes the update function from BlockLowPass class.
However, I did not find any setup process of the cutoff frequency params of the low pass filter.
It leads to the 0 value of the _vel_err_d, since the following a, b are both 0 in src/lib/controllib/blocks.cpp

```
    float b = 2 * float(M_PI) * getFCut() * getDt();
    float a = b / (1 + b);
    setState(a * input + (1 - a)*getState());
    return getState();
```

Or it is setup somewhere else?
Thanks.

**Comment by dagar** [comment]
@langxm1223 it's the param MPC_VELD_LP. 
https://pixhawk.org/firmware/parameters
