### ISSUE TITLE
QGC Spektrum bind command not working on fmu-v4, but OK on fmu-v2

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#4901]
Setting the RC_DSM_BIND parameter to >= 0 via QGC inititates the bind function on fmu-v4, but the Spektrum bind button on the QGC Radio Cal panel has no effect. The opposite is true on fmu-v2

**Comment by kd0aij** [comment]
QGC must be issuing the command "px4io bind xxx", and fmu-v2 must not be monitoring the RC_DSM_BIND parameter.

**Comment by LorenzMeier** [comment]
The FMU and IO drivers should both listen on the vehicle command for binding.

**Comment by kd0aij** [comment]
I'll incorporate that into https://github.com/PX4/Firmware/pull/4891
