### ISSUE TITLE
Snapdragon: replay log has drops

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#4908]
Recent flight testing with Snappy yielded replay logs with drops/timeouts. As far as I know this was working (better) before and therefore needs git bisecting.

**Comment by Simonnnnnnn** [comment]
ur snappy already can fly ?

**Comment by julianoes** [comment]
@Simonnnnnnn yes, sure can :)

**Comment by julianoes** [comment]
It looks like we're not looking at logging drops as such but rather timing issues. Needs more investigation.

**Comment by julianoes** [comment]
On a closer look I can see that sdlog2 which runs on the Linux side sometimes misses updates from the (m)uORB.

**Comment by LorenzMeier** [comment]
Can you raise that with @mcharleb and look at the total load of the px4 process?

If it's significantly less than 100% it hints at an issue with muorb.

**Comment by julianoes** [comment]
@LorenzMeier I've already checked the load of the mainapp process and it was around 30%. I'm gonna try to debug it with some simple plain subscriber to see if I can reproduce it.

**Comment by julianoes** [comment]
Strangely, htop shows that one core is used 30% while the mainapp consumes around 100%.

**Comment by julianoes** [comment]
I wrote a simple subscriber that uses poll. It never misses a replay message (except on startup) while sdlog2 keeps missing one or two every now and then, maybe around twice a minute.

**Comment by julianoes** [comment]
The issue doesn't really seem to be CPU load dependant as it also happens if only sdlog2 (and uorb, muorb) is running on the Linux side.

**Comment by LorenzMeier** [comment]
@julianoes Make sure nothing is skipped here:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L1477-L1483

This should not happen in replay or all logging mode, it is expected to happen in normal logging mode.

**Comment by LorenzMeier** [comment]
Also make sure that the priority is set correctly - if unsure set to max:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L328-L343

**Comment by LorenzMeier** [comment]
@bkueng What is the state on the new logger for EKF2 replay?

**Comment by bkueng** [comment]
It works once #4917 and #4817 get merged.

**Comment by julianoes** [comment]
> @julianoes Make sure nothing is skipped here:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L1477-L1483

Nothing skipped there.

> Also make sure that the priority is set correctly - if unsure set to max:
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L328-L343

`SCHED_PRIORITY_MAX` fixes it but that's probably a bad idea for logging. I'm wondering what could cause the drops.

**Comment by julianoes** [comment]
There are even drops with `SCHED_PRIORITY_MAX` just a lot less frequent.

**Comment by LorenzMeier** [comment]
On Snapdragon running the logger on Linux at high prio is fine. This is just something that should not be done on the DSP / STM32. I find it still confusing that  you see drops. That again means going back into muORB.

**Comment by julianoes** [comment]
It is confusing, there could be several things that are influencing this.

E.g. I see a lot less missed updates on my bench setup which doesn't have a external GPS/mag connected.

**Comment by julianoes** [comment]
There must also be some power saving going on, at least on the Linux side. A simple `usleep(1000)` loop  leads to waits > 5000 at least once a second without high CPU load. Once I run `stress -c 4`, everything is running as expected.

**Comment by LorenzMeier** [comment]
That makes sense. We even see that on i7 boards, I just forgot, sorry. Can you work out the best way to force the right operation of the core and potentially also CPU affinity and get this going?

**Comment by julianoes** [comment]
Considerably improved with #5003. There are still some drops every now and then but that should be bearable. Closing for now.
