### ISSUE TITLE
Unable to use pos control when not using GPS

### ISSUE THREAD

**Issue by pickledgator** [PX4/Firmware#4929]
A new commit has broken the ability to utilize position control nav state when gps_failure flag is true. This should probably be checking for valid_lpos or valid_gpos flags instead of only checking for gps_failure.

https://github.com/PX4/Firmware/blob/8a12dee125c37a3e48104877efd0f109d90b039b/src/modules/commander/state_machine_helper.cpp#L674

**Comment by mhkabir** [comment]
Yup :) Would you mind sending in a PR?

**Comment by dagar** [comment]
The fixed wing position controller needs global position for POSCTRL. You could use status->is_rotary_wing. I believe it properly changes with VTOL transitions.

**Comment by julianoes** [comment]
@pickledgator can you please test #5058.

**Comment by pickledgator** [comment]
Solves issue. Thanks for the PR, have been busy.

**Comment by julianoes** [comment]
https://github.com/PX4/Firmware/pull/5058 is pushed.
