### ISSUE TITLE
Quadplane: Needs new gains to deal with wing flex

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4933]
@sanderux We have tuned down yaw significantly after observing a yaw-roll coupling which is because yawing generates torque which flexes the wings. This seems to have sufficiently improved the situation that no hardware change to the wing mounts seems necessary.

**Comment by LorenzMeier** [comment]
@tumbili Can you please send a PR with updated gains after a log analysis round.

@sanderux It would be great if you could validate these with test flights.

**Comment by tumbili** [comment]
http://logs.uaventure.com/view/iQVKp6rz27Q5cWFmUQescM

**Comment by tumbili** [comment]
See #4936
