### ISSUE TITLE
FW takeoff mode doesn't work

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#4937]
In SITL gazebo plane if you select takeoff mode it accepts the takeoff setpoint immediately and takes off directly in loiter.

https://github.com/PX4/Firmware/pull/4932

**Comment by LorenzMeier** [comment]
Is this still present?

**Comment by dagar** [comment]
It basically "works" now, but it's accepting the takeoff waypoint early. The proper fix for FW is sending MAV_CMD_NAV_TAKEOFF with an offset appropriate for a plane takeoff.

**Comment by dagar** [comment]
Actually, I'd still like to fix it properly, but I'll push the milestone.

**Comment by dagar** [comment]
Currently working with runway takeoff.
