### ISSUE TITLE
Camera trigger: Need to use the proper API for actuators

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4941]
@birchera The current approach of accessing PWM pins directly is suboptimal as it can conflict with the FMU driver's management of GPIO and PWM outputs. It would be good to coordinate on how to properly layer this.

**Comment by birchera** [comment]
Had a look and will change the implementation according to how you set it up. -> Will only use pins 5 and 6 for triggering and initialize it according to the chosen interface.

Not sure if we can do it this week, but certainly next.

**Comment by dagar** [comment]
@mhkabir was this addressed by your recent work?

**Comment by mhkabir** [comment]
Yes.
