### ISSUE TITLE
Also log vehicle status RC loss flag

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#4948]
because only that will tell if the manual input was lost

**Comment by julianoes** [comment]
@AndreasAntener: that one is not enough, right?
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2_messages.h#L194

**Comment by AndreasAntener** [comment]
@julianoes no because it only relates to an actual RC, but not to what the commander sees as RC input, which could also be a joystick

**Comment by julianoes** [comment]
@AndreasAntener ah right!

**Comment by dagar** [comment]
No longer relevant with logger?

**Comment by dagar** [comment]
Fixed by new logger.
