### ISSUE TITLE
BMP280 over i2c

### ISSUE THREAD

**Issue by edsellar** [PX4/Firmware#4953]
I've taken a look at the BMP280 driver and see that the i2c portion is partially there. Is this something that will be continued or that someone could just point me in the direction to complete. I'm happy to do so, just a little direction would be appreciated as this would be a new topic for me. Plenty of BMP280 devices around here but all on i2c.

Ed

**Comment by LorenzMeier** [comment]
Sorry that you didn't get an answer earlier, drivers are in Firmware/src/drivers. Closing as stale.
