### ISSUE TITLE
jMAVSim: mavlink_receiver.cpp:publish  hil_sensors combine but can not receive!

### ISSUE THREAD

**Issue by RizHuang** [PX4/Firmware#4954]
in mavlink_receiver.cpp there is 
`   /\* publish combined sensor topic */
        if (_sensors_pub == nullptr) {
            _sensors_pub = orb_advertise(ORB_ID(sensor_combined), &hil_sensors);

```
    } else {
        orb_publish(ORB_ID(sensor_combined), _sensors_pub, &hil_sensors);
    }`
```

But can not receive from position_estimator.cpp

**Comment by LorenzMeier** [comment]
Have you checked that you are receiving HIL sensors?

**Comment by RizHuang** [comment]
yes ! I am sure I have receive HIL sensors !

**Comment by RizHuang** [comment]
I tested with the Firmware master branch code  and jMASim master code .

**Comment by RizHuang** [comment]
I find something wrong here in the position_estimator_inav.cpp . 
before the main task , there is a poll use to waiting 3s for baro data to caculate baro offset . if i comment these code  and direct give the baro_offset , it work well

**Comment by dagar** [comment]
Is this working now?

**Comment by dagar** [comment]
Hi @RizHuang can you try this again and reopen if it's still an issue?
