### ISSUE TITLE
Latest master (d96810f) has compilation errors for px4fmu-v2_default

### ISSUE THREAD

**Issue by vvranjek** [PX4/Firmware#4968]
It appears that the following types are missing in the `vehicle_gps_position.msg ` 
```
uint64 timestamp_position
uint64 timestamp_time
uint64 timestamp_variance
uint64 timestamp_velocity
```

After I added those I went on to compile and there were quite a few problems in ekf2. Some missing/undefined types such as `ext_vision_message` , `ev_delay_ms` and others. I couldn't go on to "fix" the problem as there were errors I couldn't have resolved. I did the `git submodule update --init --recursive` after merge/checkout.

Could there be anything else I am missing or maybe you forgot to commit submodule updates or something similar?

**Comment by mhkabir** [comment]
Master being broken is practically impossible, thanks to continuous integration. 

Are you on an absolutely clean pull of master? Run  ```make clean```, ```make submodulesclean``` and ```git clean - dfx``` to make sure.

**Comment by vvranjek** [comment]
`make clean` and `make submodulesclean` did it for me, thanks! Case closed.
