### ISSUE TITLE
tailsitter - an extra minus in the ROLL

### ISSUE THREAD

**Issue by ivand58** [PX4/Firmware#4980]
In vtol->tailsitter, in FIXED_WING (and back transition) the roll elevon signal is inverted.
According to [LorenzMeier](http://discuss.px4.io/t/why-the-roll-elevon-is-inverted/622) this inversion should me moved somewhere (I guess in the mixer, in the text file which defines the mixing rules): 

> That's something that has crept in and will be refactored.

**Comment by dagar** [comment]
Similar in vtol standard - https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/standard.cpp#L440

**Comment by dagar** [comment]
Duplicate #4797
