### ISSUE TITLE
Waypoint not reached in FW

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4982]
Mission on current master:
Kept loitering around waypoint 1, never proceeded to the next waypoint.
Log: http://logs.uaventure.com/view/DwRTKb7jKf5LHXH553s6n7

Mission:
![image](https://cloud.githubusercontent.com/assets/14801663/16569219/ff109214-4233-11e6-9670-96ca185e7988.png)

/cc @LorenzMeier @tumbili @AndreasAntener

**Comment by sanderux** [comment]
@julianoes any help appreciated

**Comment by dagar** [comment]
So it's stuck in a position setpoint after takeoff. The next time the setpoint is updated is RTL.
Here's the state of the code for this flight - https://github.com/PX4/Firmware/blob/d96810f250d60481193cf15b7e99cd49d5106028/src/modules/navigator/mission.cpp#L510

**Comment by sanderux** [comment]
Considering it is not reproducible in sitl, could it be a memory issue?

**Comment by sanderux** [comment]
I've been able to reproduce, it is likely due to coming out of transition inside the acceptance radius of the vtol_land command.

Steps to reproduce:
VT_ARSP_TRANS = 15
VT_TRANS_THR = 0.3
Load mission file: [VTOL_LAND loiter.mission.zip](https://github.com/PX4/Firmware/files/357993/VTOL_LAND.loiter.mission.zip)

Result:
![selection_025](https://cloud.githubusercontent.com/assets/14801663/16745038/613f24a2-47b4-11e6-95b3-078b0118e9b8.png)

**Comment by sanderux** [comment]
Update: after more then 50 SITL flights i have only been able to reproduce this twice.
Both times the behavior appear directly after setting a complete new mission, however, many more times this did not result in the same behavior.

still looking into what could cause this behavior.

**Comment by dagar** [comment]
Looking through the code it still seems like you're getting stuck here - https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L193

Did you get any additional information during your 2 reproduces? With the new logger you could add full logging of vehicle_status, fw_pos_ctrl_status, etc and reconstruct the acceptance radius navigator uses.

**Comment by sanderux** [comment]
Both reproduces were on the same firmware used with the actual mission failure, i don't think advanced logging was part of that. I could enable it and try to reproduce again but i have failed the last 30+ times.

With no solid way to reproduce it will also be very hard to analyze / fix.

**Comment by sanderux** [comment]
I will try to manipulate some values in the waypoint_reached code to see if i can manually trigger the anomaly and go from there.

**Comment by dagar** [comment]
You can verify it's the same behavior by breaking that, but I'm wondering if there's some race condition where you're not getting the proper vstatus, or fw_pos_ctrl_status.

**Comment by sanderux** [comment]
@julianoes i'm not getting much further on this, could you have a look?

**Comment by julianoes** [comment]
@sanderux sorry I don't have bandwidth to look into this right now. I haven't played with any VTOL stuff so I'd have to work my way in.

I'm sure @tumbili can help much better here.

**Comment by sanderux** [comment]
On current master i get consistent results that do not exhibit the same behavior but are likely related:
![image](https://cloud.githubusercontent.com/assets/14801663/17080785/4f029ffc-513d-11e6-9c88-a1888c1b2c93.png)

**Comment by sanderux** [comment]
Another instance of a waypoint not reached: http://logs.uaventure.com/view/52Y2vFerC3bbEXdA5YvWVS

This time it was a regular waypoint, it circled it before reaching it before considering it reached

**Comment by dagar** [comment]
Circling to hit the altitude?

**Comment by sanderux** [comment]
could be, but on the initial reported error the altitude was never a problem.
It did occur directly after lowering thrust and thereby loosing a lot of altitude.

**Comment by AndreasAntener** [comment]
@dagar we might have 2 issues here, but on master right now the default acceptance radius for Z is too little in the VTOL case. We set it to 3m for MC mode, so I have also 3m now in FW for Z. I guess we need a separate parameter for FW alt acc rad

**Comment by dagar** [comment]
Alright, that's an easy fix, but it's unfortunate if we need duplicate parameters. Are there other instances like this?

**Comment by LorenzMeier** [comment]
Closing this in favour of the PR.
