### ISSUE TITLE
ppm issue

### ISSUE THREAD

**Issue by alexFab** [PX4/Firmware#4983]
i try to get openLRS with PX4 to work, but no success so far. I found a [post ](http://diydrones.com/forum/topics/apm-ppm-from-openlrsng?commentId=705844%3AComment%3A1737913)where someone describes the problem.

> Actually OpenLRS produces a very short 'low' pulse on the serial PPM, like 50 µs. For some systems this is not an issue, as the important data is the time between two pulses, not the pulses themselves.
> But for APM (and Pixhawk), this is too short. [....] normal 300 µs low pulses and this works fine

Is it possible to fix this in the current version? or is this issue known?

**Comment by alexFab** [comment]
the main developer of openLRS pointed out that this Timing issue is fixed log time ago. so this is no longer the Problem. [see](http://www.rcgroups.com/forums/showpost.php?p=35179054&postcount=8554)

**Comment by alexFab** [comment]
px4 doesn't recognize my openLRS RX (submicroLRS). But [this](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/generate-ppm-signal/Generate_PPM_signal_nodelay.ino) simple ppm simulator works fine with px4. 
ppm signal from openLRS looks pretty much the same like ppm from simulator but inverted. 

this issue is also open @openLRS openLRSng/openLRSng#113

**Comment by LorenzMeier** [comment]
Can you attach plots and data from your logic analyser? We support non-inverted and inverted PPM.

**Comment by alexFab** [comment]
openlrs - doesn't work with px4
![openlrs](https://cloud.githubusercontent.com/assets/16255054/16611795/dfc8e452-4363-11e6-9312-c7c8ebaac4bf.jpg)

simulator - works with px4
![simulator](https://cloud.githubusercontent.com/assets/16255054/16611796/e285fa5e-4363-11e6-909f-df86b7ea6c0e.jpg)

**Comment by LorenzMeier** [comment]
Can you please show 2 cycles / bursts? The pauses between the signals also do matter.

**Comment by alexFab** [comment]
not at the moment, maybe later today. but the pauses between the signals are configurable in openLRS ([Minimum PPM sync time](https://github.com/openLRSng/openLRSngWiki/wiki/Settings-Guide#receiver-settings)). on the screenshots the pauses are something like 4300us. I did also tests with 3000us.

**Comment by alexFab** [comment]
from: ([Minimum PPM sync time](https://github.com/openLRSng/openLRSngWiki/wiki/Settings-Guide#receiver-settings))

> The minimum time between PPM frames on the PPM output. The default value works fine for many systems but fickle systems such as Ardupilot require a longer sync time (ardupilot 3.1 and better works ok with 3000, some older versions apparently want 4200).

**Comment by alexFab** [comment]
did some measurements again. and realized there are different offsets on rc-in. the screenshots above are made while the devices are not connected, so without the offset voltage, things looks different if the devices are connected.  After rebooting, before rc-in sees a vaild ppm-signal it has this Signal:

![rc-in_nothing_before](https://cloud.githubusercontent.com/assets/16255054/16631209/50d90bc2-43be-11e6-9bde-f4713b4a7f73.jpg)

rc-in with connected openLRS  it looks like this:
![rc-in_openlrs-befor](https://cloud.githubusercontent.com/assets/16255054/16631212/50d9f564-43be-11e6-9607-f1233f590ab7.jpg)

rc-in with connected ppm simulator (detected by px4),
![rc-in_simmulator](https://cloud.githubusercontent.com/assets/16255054/16631207/50d7c640-43be-11e6-9421-4523b86532e8.jpg)

rc-in without any connection. the offset has changed now to 3.3V-DC
![rc-in_alone_after_simconnection](https://cloud.githubusercontent.com/assets/16255054/16631210/50d9172a-43be-11e6-869c-6d5092872a10.jpg)

rc-in with the 3.3V-DC offset and connected openLRS receiver.
![rc-in_openlrs](https://cloud.githubusercontent.com/assets/16255054/16631208/50d8fdb2-43be-11e6-8682-1b6e38d36861.jpg)

openLRS standalone
![openlrs_alone](https://cloud.githubusercontent.com/assets/16255054/16631211/50d97b5c-43be-11e6-961e-7df2a569ca3f.jpg)

simulator standalone
![sim_alone](https://cloud.githubusercontent.com/assets/16255054/16631213/50ee6134-43be-11e6-93a9-1fcd4c1de90b.jpg)

**Comment by alexFab** [comment]
I also try apm on pixRacer. No more offset voltage on the rc-pin but in the moment i connect the ppm pin from openLRS with the rc-in pin the signal max voltage drops from 3.3V to 1V. I guess this is to low.

**Comment by alexFab** [comment]
finally i was able to get openLRS with px4 on pixRacer to work.

openLRS produces a ppm signal Upp 3.3V at least the submicroLRS receiver. But px4 needs ppm Upp 5V. 

here my hardware solution, but i would prefer the software solution on PX4 side ;)

![rjqdw](https://cloud.githubusercontent.com/assets/16255054/16666545/6bce6128-4488-11e6-9844-7b29ce07776d.png)

**Comment by LorenzMeier** [comment]
That conclusion doesn't seem to be correct. All the hardware we've using outputs 3.3V. Did you by chance invert the signal with this schematic?

**Comment by alexFab** [comment]
yes, signal inversion is a side affect of this logic level converter.

**Comment by gregd72002** [comment]
Hi, I stumbled upon the same issue. Is there a way to get Pixracer accept inverted PPM signal as RC-in?

**Comment by LorenzMeier** [comment]
Closing since stale.

**Comment by Deca** [comment]
I've the same issue, voltage drop on ppm when connected to rcin and the pixracer don't receive any signal, anyone found a solution?

**Comment by t413** [comment]
Thank you @alexFab! I made a N3904 inverter as you suggested and it worked like a charm. CPPM from my OpenLRS receiver works great. Here's what my inverter looks like: (pre heat shrink)

![img_5234](https://cloud.githubusercontent.com/assets/326829/26564532/d1e582ca-4496-11e7-8f7a-9a5ee86effd9.JPG)

**Comment by Siytek** [comment]
So just to confirm, PX4 does not support inverted PPM? TBS Crossfire also outputs an inverted PPM, which is not recognised by PX4.

No problem to make a little hardware inverter if necessary but a software solution would avoid adding the extra point of failure to the system.

**Comment by LorenzMeier** [comment]
It does support it. I would need to review why the decoder is rejecting it. From a HW perspective it should all work. @Siytek do you have the embedded software skills required to inspect the decoder?

https://github.com/PX4/Firmware/blob/4453e4201b7a245cff52beeb38a293161aea4c48/src/modules/systemlib/ppm_decode.c

**Comment by Siytek** [comment]
Hi Lorenz, I am up for taking a look at it although I will not claim to have the skills! I think the first thing to do is to scope my PPM signal and make sure it conforms to the parameters given in ppm_decode.c - I will get this done and post the results as soon as I get chance.

**Comment by LorenzMeier** [comment]
I've updated the link to where the decoding is actually happening: https://github.com/PX4/Firmware/blob/master/src/drivers/stm32/drv_hrt.c#L448-L601

**Comment by Siytek** [comment]
Where is the value for `ppm.next_channel` obtained? The only place I could find a value for it was when it is reset on line 520 in drv_hrt.c

**Comment by Siytek** [comment]
Also when the state machine is ACTIVE it doesn't seem to do anything with the calculated interval value? Isn't it supposed to store it in the ppm buffer for usage at this point?

**Comment by Siytek** [comment]
My PPM on the scope:

![ppm_xfire](https://user-images.githubusercontent.com/13923284/29140585-dfcef864-7d42-11e7-9805-346edc2aa908.jpg)

Starting pulse = 9.36ms
Channels ≈ 1.2ms

**Comment by AlexFa** [comment]
can someone confirm that px4 handles inverted PPM now correctly? Without a hardware-inverter?

**Comment by Siytek** [comment]
Hi @alexFab, I was being stupid with my wiring and now I have put it right all is working fine with PPM. As for inverted PPM, your signal shown in your screen shot 'OpenLRS alone' looks the same as mine (not inverted). If you are running 8 channels, you can see in your screen shot 8 short peaks for each channel and a long peak for the start signal. Its a little misleading as there is so little time spent in the low state, its easy to mistake it for inverted!

![scopes_jpg](https://user-images.githubusercontent.com/13923284/29228225-da7d8b48-7ed0-11e7-93eb-dfbf26c0cbd1.jpg)

Are you sure your circuit is not acting as some kind of buffer, which could be correcting the problem, rather than the fact that it inverts the signal? I used to use Orange OpenLRS before I got my TBS Crossfire, I don't remember entirely but I think I used to use it with PPM and I never had any problems.
