### ISSUE TITLE
Oscillation occurs when switch from Follow Me to Position

### ISSUE THREAD

**Issue by whyscience** [PX4/Firmware#4984]
Hi 
 I fly in Follow Me mode ,when I switch to Position mode ,there will be oscillation in attitude like this 
![screenshot from 2016-07-05 14 27 23](https://cloud.githubusercontent.com/assets/3918941/16575828/bb8329e6-42bd-11e6-8466-1cbcca64eb8a.png)
Or when the quadcopter is near the target , there will be no response to RC control , or it just flew away.
I test the latest firmware and V1.3 ,they have the same problem .
Anyone could help me with it ?

**Comment by dagar** [comment]
@Stifael would the mc position controller handle this better now?

**Comment by Stifael** [comment]
@dagar. I dont think so, did not get to it to look into follow me and how it is implemented.

**Comment by dagar** [comment]
@whyscience have you tried this recently? There's been a lot of work on the MC position controller.

**Comment by TSC21** [comment]
Stale
