### ISSUE TITLE
Python module & scripts to convert ULog files

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#4988]
The following repo contains scripts for ULog files: https://github.com/PX4/pyulog

Among other things it contains a CSV conversion script.
@kd0aij fyi

**Comment by julianoes** [comment]
@bkueng Nice work!

**Comment by kd0aij** [comment]
@bkueng Thanks, the scripts work for me.
But I noticed that parameter changes are no longer being logged as described here: https://github.com/PX4/Firmware/pull/4400#issuecomment-216083028
Was that intentionally removed, or just lost?

**Comment by bkueng** [comment]
@kd0aij no that's a regression. But I just tested, it still works for me in SITL, I can see the changes in FlightPlot and with `params.py`.

**Comment by kd0aij** [comment]
Sorry, I was confused: From looking at multiple logs it is obvious that I changed the parameter while disarmed :)

**Comment by bkueng** [comment]
good to hear!
