### ISSUE TITLE
new logger: folders always named sess_nnn 

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#5009]
Is there a parameter which disables naming with gps date/time?

**Comment by bkueng** [comment]
It's the `-t` parameter. Just leave it away for filenames like `sess000/log000.ulg`

**Comment by kd0aij** [comment]
Thanks. I see that in rcS on master we use "-t" for sdlog2 but not for logger. Do you think they should be the same?

**Comment by bkueng** [comment]
Yes I think we should add it for the new logger as well.

**Comment by kd0aij** [comment]
https://github.com/PX4/Firmware/pull/5010
