### ISSUE TITLE
Iris Airframe reads power incorrectly, can't fly

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#5016]
Steps:
- I started ArduPilot on my Iris
- Flashed master PX4
- Set aiframe to Iris
- Beeps like crazy because voltage is reading too low even though battery is full

I was able to work around this somehow last time this happened to me. I did some combination of param reset, set airframe again and it suddenly started working. Now I can't seem to get past it.

**Comment by sanderux** [comment]
@LorenzMeier  could this be related to the new voltage divider param?

**Comment by LorenzMeier** [comment]
Fixed if you reconfigure the airframe.
