### ISSUE TITLE
Strange behavior when uploading mission while in mission mode

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#5033]
At least in SITL the VTOL_TAKEOFF command does not transition when the mission is uploaded while in mission mode, it also ascends much faster. I think more problems can arise when this happens.

**Comment by AndreasAntener** [comment]
I have a different behaviour on my mission code but the same basic problem. Will try to sync with master and solve this.

**Comment by dagar** [comment]
I believe this is resolved? Reopen if not.
