### ISSUE TITLE
PX4FMU driver: minor typo

### ISSUE THREAD

**Issue by akru** [PX4/Firmware#5037]
I'm not sure but It's seems like a typo:
https://github.com/PX4/Firmware/blob/master/src/drivers/px4fmu/fmu.cpp#L1322

```c
...
		} else {
			// Scan the next protocol
			set_rc_scan_state(RC_SCAN_SUMD);
		}
...
```

in the case statement
https://github.com/PX4/Firmware/blob/master/src/drivers/px4fmu/fmu.cpp#L1288

```c
	case RC_SCAN_SUMD:
		if (_rc_scan_begin == 0) {
```

**Comment by julianoes** [comment]
I don't understand. What would you change to what?

**Comment by akru** [comment]
```diff
@@ -1319,10 +1319,9 @@ PX4FMU::cycle()
 
                } else {
                        // Scan the next protocol
-                       set_rc_scan_state(RC_SCAN_SUMD);
+                       set_rc_scan_state(RC_SCAN_PPM);
                }
 
-               set_rc_scan_state(RC_SCAN_PPM);
                break;
```

**Comment by kd0aij** [comment]
That looks like a necessary fix. I guess SUMD has never been tested? Because it looks like the extraneous line 1325 would switch to PPM even if SUMD were detected.

**Comment by akru** [comment]
https://github.com/PX4/Firmware/blob/master/src/drivers/px4fmu/fmu.cpp#L1325
looks like temporary hook for SUMD disabling. So SUMD correctly works now?

**Comment by kd0aij** [comment]
@akru I'm unable to test that case, since I don't have any Graupner equipment.

**Comment by julianoes** [comment]
@akru thanks for reporting! A fix has been merged.
