### ISSUE TITLE
MC pos control: switching from MANUAL into ALTCTL

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#5045]
@kd0aij Currently when you are switching from manual to ALTCTL the controller will start with params.hover_thrust. This makes the transition not nice, I believe I can see this in SITL and here as well. http://discuss.px4.io/t/pixracer-barometer-issue-px4-vs-arducopter/692
In my opinion the approach before was better which initialized the integrator with the thrust value when switching into ALTCTL. Even if the user was switching into ALTCTL when the vehicle was either falling or climbing the controller was always fast enough to increase or decrease the integrator.

**Comment by tumbili** [comment]
@kd0aij I'm talking about this here https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1593

**Comment by kd0aij** [comment]
The current setting works well for me if MPC_THR_HOVER is set correctly, but I have no objection to changing it back if you feel the old method is more robust. I think all of my transitions from manual to altctl have been performed when hovering, not climbing or descending. But if the throttle stick isn't centered at transition, we can expect a change in vertical speed on transition anyway.

**Comment by tumbili** [comment]
@kd0aij How about using the parameter if it's value is non-zero and having the default parameter value of zero?

**Comment by kd0aij** [comment]
I'd avoid adding that complexity, and just change the one line of code. It should have no impact on people who switch from manual to altctl when hovering, and I doubt that I'd notice any difference if I were to change modes in a dynamic situation.

**Comment by mhkabir** [comment]
This has been fixed in the recent controller refactor.
