### ISSUE TITLE
Can't do git submodule update

### ISSUE THREAD

**Issue by mcharleb** [PX4/Firmware#5053]
$ cd Firmware
$ git pull
$ git submodule update --init --recursive mavlink/include/mavlink/v2.0
fatal: reference is not a tree: 1e2920c68df46c25b7a14ca6cc47a478c6081d81
Unable to checkout '1e2920c68df46c25b7a14ca6cc47a478c6081d81' in submodule path 'mavlink/include/mavlink/v2.0'

**Comment by mhkabir** [comment]
Run ```git submodule sync``` or alternatively ```make submodulesclean```

**Comment by mcharleb** [comment]
@mhkabir That worked, thanks!
