### ISSUE TITLE
Sensors can not be calibrated on MindPX

### ISSUE THREAD

**Issue by dengzhijie** [PX4/Firmware#5070]
We found a problem in the v1.4.1rc1/v1.4.1rc2 on MindPX. Sensors could not be calibrated,when I clicked the sensor's name and choose OK to calibrate,it did not show any  information.But we could calibrate  without any problem in v1.4.0 and before. It seems to be influenced by recent changes,and we are checking the code.

**Comment by bkueng** [comment]
Thanks for reporting. Can you try latest master? There were some fixes regarding calibration in the last few days.

**Comment by airmind** [comment]
@bkueng The latest master has been tested on MindPX, and could not resolve this issue. @dengzhijie did you try different QGC version?

**Comment by dengzhijie** [comment]
I've tryed the laeted master on MindPX,and it did not work.I also tryed different QGC versions on diffierent PC,but sensors still could not be calibrated.

**Comment by bkueng** [comment]
Sorry, I can't reproduce, as I don't have a MindPX. If you say it works with v1.4.0, can you do a `git bisect` to find where it stopped working?

**Comment by dengzhijie** [comment]
@bkueng We checked the code,and resolved the problem.Due to MAVLINK app needs more FDs,and we did not update the code timely, the problem appeared.
Really thanks to your help!

**Comment by bkueng** [comment]
Glad to read that it works now!
