### ISSUE TITLE
setting active waypoint and mission feasibility checker

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#5078]
If you change the active waypoint (MISSION_SET_CURRENT) the mission feasibility will check your current distance from the first waypoint and possibly refuse the mission.

![screenshot from 2016-07-15 20-05-32](https://cloud.githubusercontent.com/assets/84712/16891461/c068348a-4ac7-11e6-8521-006293738bc4.png)

**Comment by LorenzMeier** [comment]
Can you re-test on master? We should have fixed that, but not sure.

**Comment by dagar** [comment]
@LorenzMeier have you tried gazebo plane recently?

My gazebo seems to be borken and I can't takeoff. Possibly because of this? I've completely reset to master and cleaned everything.

    [Err] [Plugin.hh:165] Failed to load plugin libLiftDragPlugin.so: libLiftDragPlugin.so: cannot open shared object file: No such file or directory
    [Err] [Plugin.hh:165] Failed to load plugin libLiftDragPlugin.so: libLiftDragPlugin.so: cannot open shared object file: No such file or directory
    [Err] [Plugin.hh:165] Failed to load plugin libLiftDragPlugin.so: libLiftDragPlugin.so: cannot open shared object file: No such file or directory
    [Err] [Plugin.hh:165] Failed to load plugin libLiftDragPlugin.so: libLiftDragPlugin.so: cannot open shared object file: No such file or directory

**Comment by LorenzMeier** [comment]
Check the CMakeLists.txt in src/Tools/sitl_gazebo. It excludes the plugin if you're using a Gazebo version earlier than 7.0. We might need to either fix the plugin dir of Gazebo or just unconditionally re-enable this.

**Comment by dagar** [comment]
Temporarily fixed by removing the version check here - https://github.com/PX4/sitl_gazebo/blob/master/CMakeLists.txt#L192

**Comment by dagar** [comment]
@LorenzMeier @jgoppert what's the proper fix for gazebo plane? Is the version check backwards? Only enable the LiftDragPlugin plugin for gazebo >= 7?

**Comment by LorenzMeier** [comment]
I'd say we always enable. Some LINUX distributions are missing the proper plugins (or the path setup for them).

**Comment by dagar** [comment]
No longer a problem on current master.
