### ISSUE TITLE
px4fmu-v2 sendors rotation direction

### ISSUE THREAD

**Issue by xiaoyuLi-China0372** [PX4/Firmware#5104]
@LorenzMeier 
In the file "ROMFS/px4fmu_common/init.d/rc.sensors":
    
else
		# FMUv2
		if mpu6000 start
		then
		fi

		if l3gd20 start
		then
		fi

		if lsm303d start
		then
		fi
fi

In above file, the mpu6000 and l3gd20h are not rotated (-R number), but the PCB layout in the "PX4FMUv2.4.5.pdf" , their X direction are different from the body's X direction. why not?

**Comment by julianoes** [comment]
The l3gd20 has a default orientation set here:
https://github.com/PX4/Firmware/blob/master/src/drivers/l3gd20/l3gd20.cpp#L193

For the mpu6000, the swapping for the default case happens here:
https://github.com/PX4/Firmware/blob/master/src/drivers/mpu6000/mpu6000.cpp#L1835

I agree that this is not all consistent but I would argue it's correct.

**Comment by xiaoyuLi-China0372** [comment]
@julianoes 
Thanks very much, it resolved my doubt. And it is indeed correct.
