### ISSUE TITLE
QGC Camera Setup fails due to optional params

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#5109]
If you connect to a vehicle with TRIG_MODE disabled the rest of the camera parameters do not come from the vehicle. This causes the QGC ui to fail in various way. If you then enable TRIG_MODE you have to reboot the vehicle in order to setup the rest of the camera settings for example. Can the camera parameters be changed to be non-optional so we can provide a good user experience for these settings?

**Comment by LorenzMeier** [comment]
Fixed.
