### ISSUE TITLE
GPS doesn't work on 1.4.1 master

### ISSUE THREAD

**Issue by mhc994** [PX4/Firmware#5112]
When I use latest code on branch master, GPS can't find any satellite.
When I use code on branch beta or stable, GPS works fine.
I tried with two GPS module, an u-blox M8N and an u-blox 7N.And the Hardware is pixhawk 2.4.6.

**Comment by bkueng** [comment]
Can you provide further information? what's the output of `gps status`? And `gps stop`, `gps start` ?

**Comment by dagar** [comment]
@mhc994 can you provide more information?

**Comment by mhc994** [comment]
I tried another FMU and the GPS worked well.Maybe there is something wrong with my hardware.
Sorry for forgetting to close this issue.
