### ISSUE TITLE
EKF2 baro innovation variance jumps

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#5115]
@priseborough @CarlOlsson I noticed in a recent log that the baro innovation variance looks fishy.
It seems to jump between two regimes. I'm not aware of the latest changes that went into the estimator but it could also be a logging issue.
I'll look at this as soon as possible but maybe you already have an idea.

![ekf2_innov_problem](https://cloud.githubusercontent.com/assets/7610489/17021216/d0c8558e-4f46-11e6-9001-45fe8aa2e28d.png)

The log is here http://logs.uaventure.com/view/uTTPh2WZuRtDc4SJcZ5V5e#Power_PLOT

**Comment by CarlOlsson** [comment]
We are currently using version 16bdbebdc6c97bbd58bd9de1f12791ecc5421e3a of ecl without this issue.

![1](https://cloud.githubusercontent.com/assets/7795133/17025579/d1a0c0a2-4f5c-11e6-95b2-b83f436d56dc.png)

However we will update to newest one in a couple of days and will report back then.

**Comment by CarlOlsson** [comment]
Yes we also have the issue now after the latest subtree update:
**Before subtree update**
![bsu1](https://cloud.githubusercontent.com/assets/7795133/17356253/abd94e76-5956-11e6-8d88-2c074116e868.png)
![bsu2](https://cloud.githubusercontent.com/assets/7795133/17356254/ac8e23e6-5956-11e6-9bf5-c7d09f1fd924.png)
***After subtree update*
![su1](https://cloud.githubusercontent.com/assets/7795133/17356264/b824bc92-5956-11e6-8f44-3b5c6e8ca22f.png)
![su2](https://cloud.githubusercontent.com/assets/7795133/17356265/b905c35e-5956-11e6-8586-4e4bab7997ad.png)

Green lines are forward transition, red lines backwards transition. We switch GPS module when transitioning but this should of course not influence the mag so the PzI looks really strange after subtree update

**Comment by priseborough** [comment]
This needs to be checked using the replay facility to determine if it is a reporting bug or something more serious. Can someone please provide a replay log without dropouts.

**Comment by CarlOlsson** [comment]
I will upload one here tomorrow

**Comment by tumbili** [comment]
@CarlOlsson Did you manage to record a log?

**Comment by CarlOlsson** [comment]
Not yesterday in flight because of [several strange stuff](https://github.com/PX4/Firmware/issues/5245) going on, but I have been looking into it now. I just recorded three logs on the bench with standard logging and the issue is present every time, however I also did three logs with RPL logging and the issue is gone so it seems like a logging bug.

**Comment by CarlOlsson** [comment]
And it seems to be related to GPS.
Here is a plot from a standard logging with the airplane standing on the bench and gps turned off (*gps stop* in nutshell)
![figure_1](https://cloud.githubusercontent.com/assets/7795133/17433639/1b80d69e-5b06-11e6-941c-3223668c439d.png)
Here is a plot of the same thing but with fake gps activated
![figure_2](https://cloud.githubusercontent.com/assets/7795133/17433656/367a7ba8-5b06-11e6-8ffe-73ae046ee5cd.png)

**Comment by tumbili** [comment]
@CarlOlsson That's a good hint

**Comment by tumbili** [comment]
@CarlOlsson Found the issue, I'm going to make a PR.

**Comment by CarlOlsson** [comment]
sweet(Y)

**Comment by tumbili** [comment]
Addressed in https://github.com/PX4/ecl/pull/180
