### ISSUE TITLE
Detecting attitude stuck fault

### ISSUE THREAD

**Issue by mkschreder** [PX4/Firmware#5116]
What would be a good way to detect cases when drone bumps against a wall and can not be controlled effectively? For example then I would like to disable integral action on the pid controller to avoid windup and crash. How fault tolerant is px4 to that kind of thing?

**Comment by LorenzMeier** [comment]
Depends on your tuning right now. If your frame is properly balanced and with small integral gains the anti-windup will already keep it from doing something stupid.
