### ISSUE TITLE
Standard VTOL is missing the first waypoint in SITL

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#5142]
The airplane passes through the waypoint, turns back and catches it in the second try
![screenshot from 2016-07-26 10 10 52](https://cloud.githubusercontent.com/assets/7795133/17131921/c3293862-531f-11e6-9499-ec402fdbf0f8.png)

![screenshot from 2016-07-26 10 55 31](https://cloud.githubusercontent.com/assets/7795133/17131922/c41a78ee-531f-11e6-862e-843e470afdcc.png)

Log is here:
http://logs.uaventure.com/view/VTvRoF8bjbgjKwU2WrZhpG

**Comment by sanderux** [comment]
@CarlOlsson your first waypoint is too close, it is still in transition at that time

**Comment by CarlOlsson** [comment]
Ok thanks for the explanation!
