### ISSUE TITLE
GPS fusion timeout while replaying

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#5143]
There seem to be something broken in replay on current master 4fa59c3cde0fc0ad5d015c91b186d564894fb321

If I record a replay log in SITL with standard VTOL and replay the log file I get GPS fusion timeouts

log is here:
http://logs.uaventure.com/view/zTZEXPSzkPgdN7YdG7eA7R
```
pxh> INFO  [ekf2_replay] Replay in progress... 

INFO  [ekf2_replay] Log data will be written to ./build_posix_sitl_replay/src/firmware/posix/rootfs/replay_replayed.px4log

INFO  [lib__ecl] EKF using pressure height - commencing alignment
INFO  [lib__ecl] EKF alignment complete
INFO  [lib__ecl] EKF gps is good - setting origin
INFO  [lib__ecl] EKF commencing GPS aiding
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
INFO  [ekf2_replay] Done!
```

**Comment by CarlOlsson** [comment]
![figure_3](https://cloud.githubusercontent.com/assets/7795133/17139187/ae3d6e68-5343-11e6-84b4-44fe9b251a65.png)

**Comment by CarlOlsson** [comment]
Here is a comparison of exactly the same mission flown in SITL, on with replay logging enabled and replayed and the other standard logging.

**Standard**
![sitl1](https://cloud.githubusercontent.com/assets/7795133/17324017/b4c7790c-58a4-11e6-8662-33c3f09020e4.png)
![sitl2](https://cloud.githubusercontent.com/assets/7795133/17324020/b797e0c2-58a4-11e6-9652-d7bc4191fdca.png)

**Replayed**

**Comment by CarlOlsson** [comment]
@tumbili 
This is the plot from a standard sitl flight with EKF2_MAG_TYPE = 1
![sitl3](https://cloud.githubusercontent.com/assets/7795133/17336567/112758f4-58df-11e6-80dc-294b286a0e7e.png)

**Comment by CarlOlsson** [comment]
It looks like SITL is broken on master 033e9e140d0fb38d4cf85441682a65fcae0723f8
Here is the log file:
http://logs.uaventure.com/view/6SBJD4LkNhnmCLVK4ZiRHc

**Comment by CarlOlsson** [comment]
It seems like there are several issues present here.

1) Position innovations diverge in a **standard logging** SITL mission

2) While replaying a RPL log generated in SITL the same thing happens but I also get warning messages  about GPS fusion timeouts.

3) GPS fusion timeout also occur while replaying logs generated from a physical platform.
Here is a plot from a flight with standard logging
![figure_3](https://cloud.githubusercontent.com/assets/7795133/17515074/8efe6590-5e36-11e6-81cd-af80dea274fe.png)
Everything looks good except the known issue of switching gps module
Here is a plot of almost exactly the same flight done directly afterwords and then replayed.
![figure_2](https://cloud.githubusercontent.com/assets/7795133/17515098/b5581aec-5e36-11e6-9194-bc6cc0caf7ee.png)
I have noticed that if I set 
EKF2_GPS_V_NOISE = 1.5
EKF2_GPS_P_NOISE = 1.5
It looks a bit better for some reason:
![figure_1](https://cloud.githubusercontent.com/assets/7795133/17515119/d5129ede-5e36-11e6-9175-9d85b5bd28e2.png)

@tumbili @LorenzMeier If you have any suggestions on how to debug this please let me know

**Comment by CarlOlsson** [comment]
Summery of tests so far, the [same mission](https://github.com/PX4/Firmware/files/413579/mission.txt) was flown in all tests

Replayed logs generated in SITL on my computer, estimator diverges
![replay_replayed_carl](https://cloud.githubusercontent.com/assets/7795133/17594323/358a0be0-5fe9-11e6-8c12-daaf694c54dc.png)

Replayed logs generated in SITL on our beast (12 core computer) unclear what the problem is
![replay_replayed_thebeast](https://cloud.githubusercontent.com/assets/7795133/17594388/70311270-5fe9-11e6-9d26-d741a2e3db76.png)

Standard logging from 3 different laptops, all running Ubuntu 14.04 LTS
![standard_bharat](https://cloud.githubusercontent.com/assets/7795133/17594443/9bd78e86-5fe9-11e6-8e85-0bdd4a48d94d.png)
![standard_carl](https://cloud.githubusercontent.com/assets/7795133/17594442/9bd37ac6-5fe9-11e6-9d17-da8462479fa0.png)
![standard_michal](https://cloud.githubusercontent.com/assets/7795133/17594444/9bd88e94-5fe9-11e6-9a6e-3e1935bce2dc.png)

Standard logging from the beast
![standard_thebeast](https://cloud.githubusercontent.com/assets/7795133/17594459/a7aaf6c6-5fe9-11e6-8217-f317392c44ec.png)

Please tell me if anything is unclear, if I should perform more tests or if you have any idea of where to start look for the issues.

**Comment by tumbili** [comment]
@CarlOlsson I can look into this but it must clearly be related so SITL. I'm using replay regularly on master and no issues.

**Comment by tumbili** [comment]
@CarlOlsson Clearly you can see in the plots that there are two resets taking place (position / height jump).
That is the reason why you are getting the gps timeout messages. The estimator refuses gps measurements and after the variance of the corresponding states has grown and reached the threshold the filter does a reset.

**Comment by CarlOlsson** [comment]
Thanks @tumbili  for the info that you are using replay on a real system, that is very relevant since I can't. See point 3 above. Could you upload a replay.px4log that you can replay and I can try it on my computer?

**Comment by tumbili** [comment]
@CarlOlsson Please post the log :-)

**Comment by CarlOlsson** [comment]
Hehe ops, here it is:
http://logs.uaventure.com/view/K3fbyTrttBLojq3KjQ2Pk7

**Comment by tumbili** [comment]
@CarlOlsson Hi Carl, when I try to replay your log on master then I get this

```
INFO  [lib__ecl] EKF using pressure height - commencing alignment
INFO  [lib__ecl] EKF alignment complete
INFO  [lib__ecl] EKF gps is good - setting origin
INFO  [lib__ecl] EKF commencing GPS aiding
ERROR [lib__ecl] EKF airspeed fusion numerical error - covariance reset
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
INFO  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [ekf2_replay] Done!
```
Either something is wrong in the replay or the airspeed fusion does something strange. We can have a closer look at this together.

**Comment by CarlOlsson** [comment]
@tumbili Hi Roman, If I replay the file with current master of both firmware and ecl I get:
```
INFO  [lib__ecl] EKF using pressure height - commencing alignment
INFO  [lib__ecl] EKF alignment complete
INFO  [lib__ecl] EKF gps is good - setting origin
INFO  [lib__ecl] EKF commencing GPS aiding
INFO  [ekf2_replay] Done!
```
If I do the same but with EKF2_ARSP_THR = 6.0 I get:
```
INFO  [lib__ecl] EKF using pressure height - commencing alignment
INFO  [lib__ecl] EKF alignment complete
INFO  [lib__ecl] EKF gps is good - setting origin
INFO  [lib__ecl] EKF commencing GPS aiding
WARN  [lib__ecl] EKF GPS fusion timout - resetting to GPS
INFO  [ekf2_replay] Done!
```

Since we have been flying with the airspeed fusion hundreds of times without problems I would say it is a replay issue, however will probably have time to check on the exact same system and the same code later today. If everything is fine when using normal logging we should definitely meet up and have a look :)

**Comment by tumbili** [comment]
@CarlOlsson Sorry, I must have been using a wrong version of master, I noticed that the condition to fuse airspeed was always set to false. I need to try again.

**Comment by priseborough** [comment]
@CarlOlsson, the log you provided had EKF2_ARSP_THR set to 0 which disables airspeed fusion. When I run the replay without airspeed fusion, the performance is marginal with large magnetometer innovations and position innovations, but the position does not diverge.

position innovations
![screen shot 2016-10-27 at 10 31 08 am](https://cloud.githubusercontent.com/assets/3596952/19748903/88e7358c-9c30-11e6-9222-a4a0271280a4.png)

magnetometer innovations
![screen shot 2016-10-27 at 10 32 26 am](https://cloud.githubusercontent.com/assets/3596952/19748923/b0ffe30c-9c30-11e6-95e8-a8f60b15d844.png)

This is probably due to a combination of large magnetometer interference - see large variation in field length:
![screen shot 2016-10-27 at 10 34 20 am](https://cloud.githubusercontent.com/assets/3596952/19748950/f001f112-9c30-11e6-99f4-59d33648c245.png)

And large g transients which are exceeding the GPS motion filter manoeuvre design limit of 4g:
![screen shot 2016-10-27 at 10 38 21 am](https://cloud.githubusercontent.com/assets/3596952/19749042/800e4cf6-9c31-11e6-9c52-2447d16a9518.png)

When I run it with an airspeed threshold of 10 m/s, the position does diverge. Inspecting the GPS speed and airspeed it looks like the airspeed sensor is very badly calibrated. 
![screen shot 2016-10-27 at 10 39 59 am](https://cloud.githubusercontent.com/assets/3596952/19749070/babae9ea-9c31-11e6-8b3f-2155dc43692e.png)

A loss of velocity and position accuracy due to the large airspeed errors has been observed in-flight on this airframe before. See: https://github.com/PX4/ecl/issues/205.

Updating the ecl reference to latest master which includes a patch to prevent airspeed fusion affecting non-wind states unless dead-reckoning (see: https://github.com/PX4/ecl/pull/206 ) eliminates the loss of position fusion. These are the position innovations with EKF2_ARSP_THR = 10.0

![screen shot 2016-10-27 at 10 45 26 am](https://cloud.githubusercontent.com/assets/3596952/19749168/7d48eaf2-9c32-11e6-8552-036ee08caf8c.png)

These are the wind estimates:
![screen shot 2016-10-27 at 10 46 21 am](https://cloud.githubusercontent.com/assets/3596952/19749179/9e164202-9c32-11e6-9548-e38245e161c3.png)

**Comment by priseborough** [comment]
I could not find any evidence that the replay was handling airspeed fusion incorrectly. The GPS rejection in the log was due to bad sensor data and a vulnerability in the ecl EKF which has been fixed.

**Comment by CarlOlsson** [comment]
@priseborough 
Hi Paul,

I have now flown the Phantom wing maybe 15 times and the estimator is performing all fine. However, as soon as I do a replay log and replay it the estimator diverges, in the way I have explained in this issue. Could you please check if this only happens for me?
Replay log [here](http://logs.uaventure.com/view/SFtP25pmMJwTwRNwYZtoxd).

Normal logging
![figure_1](https://cloud.githubusercontent.com/assets/7795133/20248327/1619b8d0-a9e2-11e6-8636-fdc5d08df185.png)

Replayed flight
![figure_2](https://cloud.githubusercontent.com/assets/7795133/20248326/16170bb2-a9e2-11e6-806a-30c2bbebbeb0.png)

**Comment by priseborough** [comment]
What version of the software were you using for the flight? The EST5 message labels are incorrect.

**Comment by CarlOlsson** [comment]
@priseborough 
Thanks Paul,

The log is the same as the one I posted [here](https://github.com/PX4/Firmware/pull/5763)
So it was with latest ecl master but also with the sidesilp in. That is strange because if I replay it with 
EKF2_GPS_CHECK = 0 the estimator still "diverges":
![figure_1](https://cloud.githubusercontent.com/assets/7795133/20256771/de0c49bc-aa45-11e6-9903-44e922df9120.png)

EKF2_GPS_CHECK = 21
![figure_2](https://cloud.githubusercontent.com/assets/7795133/20256774/e745332c-aa45-11e6-9ee1-a5b2da32b041.png)

Does it look differently for you?

**Comment by priseborough** [comment]
I am testing using master at 5ad329b with EKF2_GPS_CHECK = 0 and it is not resetting the position. I always do a make clean before running replay to wipe the old replay_params.txt file. Please provide a commit hash if you want me to confirm results.
