### ISSUE TITLE
Snapdragon Flight Board Problems

### ISSUE THREAD

**Issue by VictorSu2** [PX4/Firmware#5145]
I build and upload the px4 project onto the flight board.
But the adb shows following error message:

> sh: 1: cannot create /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor: Directory nonexistent
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:136:failed to create tls key/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:112:listener using ion heap: -1
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:225::error: -5: 0 == (nErr = dlerr)
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:228:adsp dlopen error: px4muorb undefined PLT symbol _FDtest (682) /libpx4muorb_skel.soERROR [platforms__posix__px4_layer] krait update param 297 failed
> 
> ______  __   __    ___ 
> | ___ \ \ \ / /   /   |
> | |_/ /  \ V /   / /| |
> |  __/   /   \  / /_| |
> | |     / /^\ \ \___  |
> \_|     \/   \/     |_/
> 
> mainapp starting.
> 
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:225::error: -5: 0 == (nErr = dlerr)
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:228:adsp dlopen error: px4muorb undefined PLT symbol _FDtest (682) /libpx4muorb_skel.soERROR [muorb] Initialize Error calling the uorb fastrpc initalize method..
> ERROR [muorb] ERROR: FastRpcWrapper Not Initialized
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:225::error: -5: 0 == (nErr = dlerr)
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:228:adsp dlopen error: px4muorb undefined PLT symbol _FDtest (682) /libpx4muorb_skel.soINFO  [sdlog2] [blackbox] /root/log/sess004
> INFO  [sdlog2] [blackbox] recording: log001.px4log
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:225::error: -5: 0 == (nErr = dlerr)
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:228:adsp dlopen error: px4muorb undefined PLT symbol _FDtest (682) /libpx4muorb_skel.so  SDLOG_PRIO_BOOST: curr: 2/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:225::error: -5: 0 == (nErr = dlerr)
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:228:adsp dlopen error: px4muorb undefined PLT symbol _FDtest (682) /libpx4muorb_skel.soERROR [platforms__posix__px4_layer] krait update param 642 failed
>  -> new: 3
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:225::error: -5: 0 == (nErr = dlerr)
> /home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:228:adsp dlopen error: px4muorb undefined PLT symbol _FDtest (682) /libpx4muorb_skel.soINFO  [dataman] Unkown restart, data manager file '/home/linaro/dataman' size is 103090 bytes
> INFO  [mavlink] mode: Normal, data rate: 1000000 B/s on udp port 14556 remote port 14550
> pxh> INFO  [mavlink] using network interface wlan0, IP: 192.168.1.1
> INFO  [mavlink] with broadcast IP: 192.168.1.255

Does it mean I need to upgrade the BSP and aDSP firmware of the SOC?
What steps I need to do on this link http://dev.px4.io/advanced-snapdragon.html ?

Thanks

**Comment by julianoes** [comment]
> undefined PLT symbol _FDtest (682) /libpx4muorb_skel.soERROR [muorb] Initialize Error calling the uorb fastrpc initalize method..

Check this out: http://dev.px4.io/advanced-snapdragon.html

I strongly recommend to update BSP and the adsp image.
