### ISSUE TITLE
Not all mavlink data is displayed through telemetry.

### ISSUE THREAD

**Issue by agribov** [PX4/Firmware#5165]
Hello,
When I have my Flow unit connected, and connect the Pixhawk through USB, I can go to the "analyze" tab of QGC and it will show me various Mavlink data, including about 8 labeled Optical_flow_XXXXX. When I go to the same screen through telemetry, those are missing.

**Comment by mhkabir** [comment]
Telemetry doesn't have enough bandwidth to display all data.
We only send a subset of messages at a low rate : https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L1892-L1914
