### ISSUE TITLE
MANUAL CONTROL lost message on param set (and save)

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5170]
Every time QGC sends a param value to Pixracer, I get the message "MANUAL CONTROL lost". Presumably something is blocking the manual control timeout check.

**Comment by dagar** [comment]
Have you determined that it's not on the QGC side?

**Comment by LorenzMeier** [comment]
I expect that the param change triggers a save operation or similar which is stalling the check. This should be fine if it happens in the right thread, however, we should make sure the previous architecture still matches all intentions.

**Comment by julianoes** [comment]
@dagar it's not the QGC side. It also happens if you just do a `param save` using nsh.

**Comment by julianoes** [comment]
@LorenzMeier this is what happens during `param save`:
https://github.com/PX4/Firmware/blob/master/src/drivers/stm32/drv_hrt.c#L459

**Comment by julianoes** [comment]
Basically what happens is that the PPM encode on Pixracer looses sync because everything is locked while we write to the FRAM because the BUS is shared with the baro.

My changes make the locked times shorter and therefore alleviate the problem, however, the global locking to write params is still wrong, and as the [comment in the code](https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/param/param.c#L840) there suggests, only the SPI bus should be locked.

I filed a separate issue for that #5188.
