### ISSUE TITLE
Pixracer safety button LED pattern wrong

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5171]
The LED pattern on Pixracer seems wrong to me. To be consistent with Pixhawk it should be double blinking while disarmed, and always on if armed. Right now it's just always on.

**Comment by kd0aij** [comment]
are you sure safety isn't disabled?

**Comment by julianoes** [comment]
It probably is disabled, however the pattern should still be correct, even if the safety button doesn't need to be pressed and safety is always off.

**Comment by kd0aij** [comment]
I see; I never noticed this since I don't install the button if I plan to disable it :)

**Comment by julianoes** [comment]
Sure, I wanted to use it, but through some firmware flashing of different versions, it suddenly was disabled.
