### ISSUE TITLE
Re-tune softer defaults for copters

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5180]
@julianoes This is for the defaults discussion. We should make sure to not de-tune the controllers as much in the inner loops but to tune the user response.

The gains became more aggressive since v1.2.0

```
-PARAM_DEFINE_FLOAT(MPC_ACC_HOR_MAX, 4.0f);
+PARAM_DEFINE_FLOAT(MPC_ACC_HOR_MAX, 10.0f);
-PARAM_DEFINE_FLOAT(MPC_XY_P, 1.0f);
+PARAM_DEFINE_FLOAT(MPC_XY_P, 1.25f);
-PARAM_DEFINE_FLOAT(MPC_XY_VEL_P, 0.1f);
+PARAM_DEFINE_FLOAT(MPC_XY_VEL_P, 0.09f);
```

**Comment by julianoes** [comment]
I'm not too familiar with the params above but I would certainly reduce MPC_XY_VEL_MAX from 8 to 5.

https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_params.c#L312

**Comment by LorenzMeier** [comment]
You're looking at the MAX, not the DEFAULT, which is 5: https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_params.c#L283-L297

**Comment by julianoes** [comment]
Aha!

**Comment by LorenzMeier** [comment]
Ongoing discussion with user feedback:
http://discuss.px4.io/t/v1-4-1-release-testing/759/10

**Comment by LorenzMeier** [comment]
@AndreasAntener @tumbili Another important test flight area which would help VTOLs with better overall understanding / tuning guides / defaults.

**Comment by LorenzMeier** [comment]
@kd0aij @pkocmoud Thoughts?

**Comment by pkocmoud** [comment]
I will try this tonight and feedback.

**Comment by LorenzMeier** [comment]
Done on master.
