### ISSUE TITLE
taisitter gazebo link failed or continue communication lost

### ISSUE THREAD

**Issue by jilinggui** [PX4/Firmware#5186]
make posix_sitl_default tailsitter_gazebo ,the gazebo start up but when link QGC , the qgc continuelly dispaly COMMUNICATION LOST，and  the system terminal dispaly：
INFO  [platforms__posix__px4_layer] simulator is slow. Delay added: 11845 us
INFO  [platforms__posix__px4_layer] simulator is slow. Delay added: 13518 us
INFO  [platforms__posix__px4_layer] simulator is slow. Delay added: 16737 us

what happen？
my system is ubuntu 14.04, and the use gazebo6.

**Comment by julianoes** [comment]
Does this happen every time or just once? What are the steps to reproduce it?

**Comment by jilinggui** [comment]
every time  i connect to QGC via udp, it always connect failed ,or after a few seconds it communication lost.system terminal always dispaly INFO [platforms__posix__px4_layer] simulator is slow. Delay added: 11845 us ..

**Comment by julianoes** [comment]
Do you do anything other than the defaults?

**Comment by julianoes** [comment]
What version are you on? I don't have this make target.

**Comment by jilinggui** [comment]
sorry , it is "make posix_sitl_default gazebo_tailsitter",i made a mistake

**Comment by julianoes** [comment]
```
INFO [platforms__posix__px4_layer] simulator is slow. Delay added: 11845 us
INFO [platforms__posix__px4_layer] simulator is slow. Delay added: 13518 us
INFO [platforms__posix__px4_layer] simulator is slow. Delay added: 16737 us
```

This just means that your computer can't keep up. If you see it way too often, you'll have to make sure nothing else runs on the computer or find a faster one I'm afraid.

**Comment by julianoes** [comment]
Another indicator if the simulation is fast enough is the "Real time factor" shown in Gazebo in the bottom right.

I see the performance issues with the tailsitter on my machine too, but I don't have any communication problems.

Is the communication only lost or also regained?

**Comment by jilinggui** [comment]
it never regained unless i disconnect it. in addtion, when i execute "take off "conmmand ,then set mode "mission", the vehicle becomme crazy.

**Comment by julianoes** [comment]
so it only looses the communication once then? Do you still see output in QGC or not?

**Comment by jilinggui** [comment]
my ubuntu run Under the virtual machine

**Comment by jilinggui** [comment]
yes .when i set the mode "mission",QGC dispaly "Error during mission communicaiton with vehicle:vehicle did not respond to mission item communiction:MISSION＿ITEM" .

**Comment by julianoes** [comment]
> yes .when i set the mode "mission",QGC dispaly "Error during mission communicaiton with vehicle:vehicle did not respond to mission item communiction:MISSION＿ITEM" .

Aha, we'll any chance something crashes in that case?

So for the rest it works, I assume?

**Comment by jilinggui** [comment]
but most of the time I haven't had time to execute "mission"command ,the connection has lost.

**Comment by mhkabir** [comment]
Stale.
