### ISSUE TITLE
Block SPI bus while using FRAM instead of everything on Pixracer

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5188]
Since the FRAM and the baro are on the SPI bus on Pixracer, there needs to be some locking to prevent the two from crashing on the bus.

Currently, this is done by blocking "everything" while doing a `param save`, see:
https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/param/param.c#L840

As the comment suggests, it would be better to only lock the bus.

**Comment by bkueng** [comment]
What I noticed recently is the following:
![sampling_irregularity_param_change](https://cloud.githubusercontent.com/assets/281593/17321843/de0decb0-589a-11e6-8ee0-95da31aec4f2.png)
After a param change via QGC, the scheduling of sensor sampling is messed up for ~1/2sec. I think it's during the param save and probably related to disabling the IRQ's (the plot is with 623b99327d0ac9d47af applied).

**Comment by julianoes** [comment]
@bkueng I agree, it's still far from optimal. I got more "manual control lost" messages yesterday. Presumably because I had changed more params from the default.

**Comment by LorenzMeier** [comment]
We have improved this a bit already (current testing suggests performance is sufficient), but the better architecture is still pending.
