### ISSUE TITLE
V1.4.1RC4: Landing detector not working properly in all situations

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#5211]
After triggering auto-landing the vehicle landed on a slope surface. Doing so, I face a strange sequence of state changes:

![chart](https://cloud.githubusercontent.com/assets/7580193/17358067/2a3259f8-5960-11e6-9d94-7c4f54783e58.png)

**Comment by julianoes** [comment]
Can you share a log for this please?

**Comment by ecmnet** [comment]
Another short landing test shows that failsafe was triggered again, after landing was detected:

![chart](https://cloud.githubusercontent.com/assets/7580193/17372193/0bc9643c-59a3-11e6-93b0-625ea6906d33.png)

For this the log is: http://logs.uaventure.com/view/FLCCUajbQcMbRZYCqtJ8M8

**Comment by julianoes** [comment]
I looked at all the data that could trigger a take-off detected and I can't see which one would have triggered it. If you can debug this further with some printfs that would be helpful.

**Comment by ecmnet** [comment]
Maybe this issue occurs, because the vehicle is still wobbling (roll rate, pitch rate) on sloppy surfaces due to the relative high thrust during auto-landing.  The takeoff is detected about 1/2 second after landing. Maybe a time hysteresis would help here.

**Comment by ecmnet** [comment]
@julianoes Additionally I've found out, that after auto-landing, the state is switched back to position hold (the state was in when triggering auto-landing):

![chart](https://cloud.githubusercontent.com/assets/7580193/17435201/756b9294-5b0f-11e6-9872-0c9dfc9b8e8e.png)

Additionally RollRate and PitchRate were quite high during landing.

**Comment by dagar** [comment]
Any update?

**Comment by ecmnet** [comment]
Fixed for me with current master

**Comment by mhkabir** [comment]
Thanks.
