### ISSUE TITLE
V1.4.1RC4: LPE Position hold not stable

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#5212]
@jgoppert @tumbili Another issue regarding LPE: I left the vehicle unarmed for a while. After takeoff, I switched to althold, then to position hold. Both modes were quite unstable. Very interesting was position hold. The behavior was as if the pos gains were too high (massive control reaction in both directions, roll and pitch). (But when switching to pos hold shortly after a reboot, it works fine). Initially I noticed, that position as well as LPOS.Z have drifted a lot while being unarmed on ground (Bottom clearance was about 5.8m)

I assume, that raw flow information is compensated by altitude above ground. How is the altitude above ground determined? Is it dependent on terrain estimation? 

Log: http://logs.uaventure.com/view/iMqiBYS28xwjQH99CZjqBJ

Note also, that this did not occur with 1.4.1RC1.

Update: LPOS.Z usually is set to zero when arming. In this case not - as far as I can see. 
Refer to  https://github.com/PX4/Firmware/issues/4878 regarding LPOS.Z reset.

**Comment by jgoppert** [comment]
So this is without gps using flow outdoors?

**Comment by jgoppert** [comment]
Your gains don't match the recommendations I made here to prevent excessive tilting when using optical flow position hold outdoors: http://dev.px4.io/optical-flow-outdoors.html

**Comment by jgoppert** [comment]
@ecmnet If altitude above ground had drifted off and wasn't fixed on reset it could contribute to the problems you described. If it think it is higher above ground than it is, then position movements will be exaggerated in the estimator. The flow is basically: ground_distance_moved = altitude * flow_in_radians ( l = r*theta)

**Comment by ecmnet** [comment]
@jgoppert This issue does not occur any more, when the reset of LPOS.Z is omitted in the way I mentioned in https://github.com/PX4/Firmware/issues/4878. Regarding the gains: Defaults work quite perfect.

I am closing this issue with reference to  https://github.com/PX4/Firmware/issues/4878.
