### ISSUE TITLE
"make posix gazebo_iris_opt_flow" not working.

### ISSUE THREAD

**Issue by rs1990** [PX4/Firmware#5223]
Hello,

Iv been trying to get the simulator working but everytime i run make posix gazebo_iris_opt_flow i end up with the following error,

swapnil@UTARIROS08:~/catkin_ws/src/px4_firmware/Firmware$ make posix gazebo_iris_opt_flow
PX4 CONFIG: posix_sitl_default
[  1%] [  1%] Built target git_gencpp
Built target prebuild_targets
[  1%] [  2%] Built target git_genmsg
Built target git_uavcan
[  2%] Built target git_mavlink
[  3%] [  3%] Built target git_jmavsim
Built target git_matrix
[  5%] Built target df_driver_framework
[  5%] Built target git_driverframework
[  5%] Built target git_ecl
[  5%] [  6%] Built target git_gazebo
Built target xml_gen
[  7%] Built target mixer_gen
[ 31%] Built target msg_gen
[ 31%] [ 31%] Built target generate_topic_listener
Built target platforms__common
[ 32%] Built target drivers__boards__sitl
[ 33%] Built target drivers__gps
[ 35%] Built target drivers__device
[ 35%] Built target drivers__pwm_out_sim
[ 36%] Built target platforms__posix__drivers__adcsim
[ 44%] Built target systemcmds__tests
[ 44%] Built target platforms__posix__drivers__accelsim
[ 44%] Built target platforms__posix__drivers__airspeedsim
[ 44%] Built target platforms__posix__drivers__barosim
[ 44%] Built target platforms__posix__drivers__gyrosim
[ 45%] Built target platforms__posix__drivers__gpssim
[ 45%] Built target platforms__posix__drivers__ledsim
[ 46%] Built target platforms__posix__drivers__tonealrmsim
[ 46%] Built target platforms__posix__drivers__rgbledsim
[ 46%] Built target systemcmds__esc_calib
[ 47%] Built target platforms__posix__px4_layer
[ 47%] [ 50%] [ 52%] Built target systemcmds__param
Built target platforms__posix__work_queue
Built target systemcmds__mixer
[ 53%] [ 53%] Built target systemcmds__reboot
Built target systemcmds__sd_bench
[ 53%] [ 54%] Built target systemcmds__perf
Built target systemcmds__topic_listener
[ 54%] [ 54%] [ 54%] Built target systemcmds__ver
Built target systemcmds__top
Built target systemcmds__motor_ramp
[ 54%] Built target modules__attitude_estimator_q
[ 54%] [ 54%] Built target modules__attitude_estimator_ekf
Built target modules__dataman
[ 54%] Built target modules__ekf2
[ 58%] Built target modules__commander
[ 59%] [ 59%] Built target lib__external_lgpl
Built target modules__ekf_att_pos_estimator
[ 60%] Built target modules__land_detector
[ 61%] Built target modules__mc_att_control_multiplatform
[ 66%] [ 68%] Built target lib__ecl
Built target modules__uORB
[ 68%] Built target modules__mc_pos_control
[ 69%] Built target modules__mc_att_control
[ 69%] Built target modules__param
[ 70%] Built target modules__mc_pos_control_multiplatform
[ 71%] Built target modules__position_estimator_inav
[ 77%] [ 77%] Built target modules__local_position_estimator
Built target modules__mavlink
[ 81%] Built target modules__navigator
[ 82%] Built target modules__sdlog2
[ 82%] Built target modules__replay
[ 82%] Built target modules__sensors
[ 83%] Built target modules__simulator
[ 84%] Built target modules__systemlib__mixer
[ 85%] Built target modules__vtol_att_control
[ 90%] Built target modules__systemlib
[ 90%] Built target lib__conversion
[ 91%] Built target lib__controllib
[ 91%] [ 91%] Built target lib__geo_lookup
Built target lib__DriverFramework__framework
[ 92%] [ 92%] Built target lib__geo
Built target lib__mathlib__math__filter
[ 93%] Built target lib__mathlib
[ 93%] Built target lib__launchdetection
[ 94%] Built target lib__rc
[ 94%] Built target lib__tailsitter_recovery
[ 94%] Built target lib__runway_takeoff
[ 94%] Built target lib__terrain_estimation
[ 94%] Built target examples__px4_simple_app
[ 95%] Built target drivers__sf0x__sf0x_tests
[ 96%] Built target lib__rc__rc_tests
[ 97%] Built target modules__commander__commander_tests
[ 97%] [ 97%] Built target modules__controllib_test
Built target modules__unit_test
[ 98%] Built target modules__uORB__uORB_tests
[100%] [100%] [100%] Built target modules__logger
Built target modules__fw_pos_control_l1
Built target modules__fw_att_control
[100%] Built target px4
SITL ARGS
rc_script: posix-configs/SITL/init/rcS
debugger: none
program: gazebo
model: iris_opt_flow
build_path: /home/swapnil/catkin_ws/src/px4_firmware/Firmware/build_posix_sitl_default
make[5]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[8]: *** No rule to make target `/home/swapnil/catkin_ws/src/px4_firmware/Firmware/Tools/sitl_gazebo/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by `MotorSpeed.pb.cc'.  Stop.
make[7]: *** [CMakeFiles/mav_msgs.dir/all] Error 2
make[7]: *** Waiting for unfinished jobs....
[  4%] Built target sdf
make[6]: *** [all] Error 2
make[5]: *** [gazebo_build] Error 2
make[4]: *** [src/firmware/posix/CMakeFiles/gazebo_iris_opt_flow] Error 2
make[3]: *** [src/firmware/posix/CMakeFiles/gazebo_iris_opt_flow.dir/all] Error 2
make[2]: *** [src/firmware/posix/CMakeFiles/gazebo_iris_opt_flow.dir/rule] Error 2
make[1]: *** [gazebo_iris_opt_flow] Error 2
make: *** [posix_sitl_default] Error 2
swapnil@UTARIROS08:~/catkin_ws/src/px4_firmware/Firmware$ 

could someone help me please ? Thanks a lot. Im using ubuntu 14.04 and i have gazebo 7 installed.

**Comment by LorenzMeier** [comment]
You don't have protobuf installed. Please follow the installation instructions in the first section here: http://dev.px4.io/starting-installing-linux.html#installation
