### ISSUE TITLE
Logging for standard VTOL is broken in SITL

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#5254]
@jgoppert 
After this commit 699b6a2cb340f4b6ec3979ae7748ff9c56cfdb89 standard_vtol is not producing any logs anymore in SITL.

**Comment by LorenzMeier** [comment]
@CarlOlsson The log output location might have changed. @jgoppert Please advise.

**Comment by CarlOlsson** [comment]
Oh you are right, maybe I was a bit to quick in my conclusion. Will give it another look

**Comment by LorenzMeier** [comment]
The system does print the log location once logging starts. You should be able to figure it out from there.

**Comment by jgoppert** [comment]
I can confirm this is working on my machine.

```bash
~/git/Firmware$ ls build_posix_sitl_default/tmp/rootfs/fs/microsd/
dataman  log  msgs_2016_08_05_17_01_49.txt
```

**Comment by LorenzMeier** [comment]
@CarlOlsson I've reverted the logging / path change, so the path on master will be back to default. However, the file path will change again at a later point.

**Comment by CarlOlsson** [comment]
Yes I can also confirm that it was working on my computer before you reverted the commit. Closing here
