### ISSUE TITLE
Pixracer: servos not active when _safety_off

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#5260]
Not sure whether this is the intended behavior

**Comment by kd0aij** [comment]
apparently this was due to PWM_DISARMED defaulting to zero for the standard AERT plane config.

**Comment by LorenzMeier** [comment]
They actually should be active, only throttle should be locked in that state.

**Comment by kd0aij** [comment]
@LorenzMeier I think parameters PWM_MIN/MAX/DISARMED should all be set in rc.fw_defaults. Currently only PWM_AUX variables are being set there, but 2101_fw_AERT just copies the PWM_xxx parameter values to bash variables of the same name. 

Was it intentional to use bash variables which shadow parameter values? That has been a source of confusion for me.

**Comment by kd0aij** [comment]
bump

**Comment by kd0aij** [comment]
closed pending further discussion
