### ISSUE TITLE
Camera trigger on-command is broken

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#5261]
Lots of changes for PWM control went in, and something seems to have broken GPIO triggering.

Running
```camera_trigger stop``` and ```camera_trigger start``` via mavlink NSH (yay!) gets it working again, so the functionality is OK, but it doesn't enable on command, even though the shell ```info``` shows it as being "enabled"

**Comment by LorenzMeier** [comment]
Thanks for reporting and sorry for the breakage. It would be fantastic if you could have a look. Seems like it should be an easy fix.

**Comment by mhkabir** [comment]
Found it. FMU driver clashes with it for some reason if started after trigger. It works if I start the trigger after the FMU driver.

**Comment by mhkabir** [comment]
This is fine on master because the trigger pins are set to AUX 5,6 (handled by ```fmu mode_pwm4```). I was having the issue because of my custom config which had them set on 1,2. 

Should be fine as long as people stick to the defaults.
