### ISSUE TITLE
LPSP.Z decrease or increase in the vtol front transition period problem.

### ISSUE THREAD

**Issue by CornerOfSkyline** [PX4/Firmware#5270]
There is a strange  behaviour in the vtol front transition in auto mission. When the previous waypoint's altitude is different with the vtol transilate command point(one normal waypoint + command point) and next waypoint's altitude. The LPSP.Z will increase (previous is higher) or descrease (previous is lower) in the transition period. The LPSP.Z setpoint will cause the mc controller to control the vtol altitude increase or decrease in transition.

**Comment by sanderux** [comment]
Confirmed in SITL, so far ruled out FOH update and i don't see any such behavior commanded from navigator. switching position estimator doesnt seem to help

**Comment by AndreasAntener** [comment]
Fixed on master
