### ISSUE TITLE
MAVLink-UAVCAN bridge is not working properly

### ISSUE THREAD

**Issue by pavel-kirienko** [PX4/Firmware#5277]
See https://github.com/PX4/Firmware/pull/5271#issuecomment-238280605

@mhkabir @bendyer

**Comment by pavel-kirienko** [comment]
What needs to be done so far:

1. Get Lorenz enable the support for setting the source component ID for outgoing MAVLink messages (https://github.com/PX4/Firmware/pull/5271#issuecomment-238368758).
2. Route `uavcan.protocol.NodeStatus` messages via the MAVLink-UAVCAN bridge, transforming them into MAVLink heartbeat messages.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Current state with UAVCAN enabled:

<img width="1392" alt="screen shot 2016-11-13 at 19 25 42" src="https://cloud.githubusercontent.com/assets/1208119/20247936/b3ea2a80-a9d9-11e6-8357-9ed281f96f67.png">

**Comment by LorenzMeier** [comment]
@mhkabir @pavel-kirienko Can you re-test on master?

**Comment by pavel-kirienko** [comment]
There were reports of `Dynamic ID / Update` being silently reset to `Motors / Update`, which I couldn't reproduce. Can anyone confirm that?

Re testing, I should probably be able to do it later.

**Comment by LorenzMeier** [comment]
@pavel-kirienko I can't see how this should be happening. But I did clean up the enable params here: https://github.com/PX4/Firmware/pull/5866

**Comment by LorenzMeier** [comment]
Seems to be all fixed.
