### ISSUE TITLE
new logger: excessive RAM usage

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#5283]
starting the new logger with a buffer size of 12K uses up more than 23K of available RAM in v1.4.1

**Comment by bkueng** [comment]
Yes I noticed, but never investigated deeper. One large block is `_subscriptions`, which uses ~2.3KB and the stack sizes (3.2 + 1). Did you have a closer look?

**Comment by kd0aij** [comment]
The net effect is that one must use a buffer of 8K or less in v1.4.1 but all of our testing has been with a 12K buffer. Since I've been getting dropouts with 12K, this doesn't look good.

**Comment by LorenzMeier** [comment]
Fixed.
