### ISSUE TITLE
hdop is not eph

### ISSUE THREAD

**Issue by LONELY-WOLF** [PX4/Firmware#5286]
Mavlink now reports hdop as eph and vdop as epv.
Here: https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_messages.cpp#L1080
It's not useful if you have precise GPS receiver. Our Ashtech GPS gives us 0 or 1. Before those changes it reported EPH/EPV in cm.

**Comment by LorenzMeier** [comment]
We did that to be consistent with existing deployment in the field. Please feel free to propose an extended MAVLink message with these fields added, but in the scope of the existing message definition it will stay as is.

**Comment by sanderux** [comment]
@LONELY-WOLF how are you connecting your Ashtech receiver?

**Comment by kd0aij** [comment]
Is it correct that right now, QGC displays hdop and vdop, but LPE requires
eph < 3.0 (LPE_EPH_MAX)?
Is it possible to see eph and epv using QGC?
