### ISSUE TITLE
hardware in the loop test problem

### ISSUE THREAD

**Issue by metusa** [PX4/Firmware#5305]
Hi
I have a problem with hil test. I have changed the SYS_AUTOSTART parameter to 1001. Then I run the jMAVSim in HITL mode and start the QGC(v.2.9.7). I send the missions to vehicle. But when I armed the system, it just rises indefinitely not going to waypoints. I have also done the sensor calibration.

**Comment by julianoes** [comment]
@metusa thanks for reporting. @bkueng and I were able to reproduce the problem. A fix is in the works in  #5716
