### ISSUE TITLE
SITL runs send incorrect firmware version

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#5308]
Which then causes QGC to pop the error about needed 1.4 or above to run correctly.

**Comment by LorenzMeier** [comment]
Can you update from master and re-run? If it doesn't work with an incremental build, can you run ```make clean``` and report the result of that?

It reports 1.4.1dev for me correctly.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Ping?

**Comment by DonLakeFlyer** [comment]
Didn't work for me. It sent version 1.1.3dev

**Comment by bkueng** [comment]
done in https://github.com/mavlink/qgroundcontrol/pull/4086
