### ISSUE TITLE
1.4.1 VTOL How to program transition switch?

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#5314]
Hi,

Just about to try the 1.4.1 and I cannot seem to find a way to program a transition switch.

In the release statement I see "VTOL: Dedicated transition switch for manual operation." But I dont see it in QGC. I use today's build of QGC.

AUX1 does not work anymore like in 1.3.4

Any ideas?

**Comment by tubeme** [comment]
I must say 1.3.4 is ROCK SOLID! in all weather conditions. :) I must say BIG Thank you for the good work.

**Comment by kd0aij** [comment]
The transition switch mapping was changed recently: https://github.com/PX4/Firmware/pull/5101
and I don't think QGC supports it yet. You'll have to manually assign the switch.

**Comment by tubeme** [comment]
So how do i program the switch?

**Comment by tubeme** [comment]
Thanks I changed it in the config.txt it works..
