### ISSUE TITLE
v1.4.1 release, Pixracer, LPE rejects ALTCTL even with LPE_GPS_ON=0

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#5316]

**Comment by jgoppert** [comment]
Looking into this, any logs?

**Comment by kd0aij** [comment]
No, I tested by connecting QGC via wireless telemetry (outdoors) and changing TX mode switch from manual to ALTCTL. QGC reported that the mode switch was rejected, so I didn't even arm.

**Comment by kd0aij** [comment]
this looks OK on latest master

**Comment by saeidkazemi** [comment]
hi
We have some unknown problems to compile your code and we would be pleased if you could help us to fix it.
I have dealt with the problem of Position Control Mode actually the system rejects this mode.
We do not have GPS and want to run the Position Control with optical Flow Sensor.
We cannot find the LPE-GPS-on in Qground to turn it off, so how can we turn off the GPS?
We set the sys_group in LPE mode but again it rejects the position control mode. Do you know the reason?

Pixhawk version 2

**Comment by jgoppert** [comment]
Please set sys_mc_est_group to lpe and reboot.

**Comment by saeidkazemi** [comment]
actually we did tat but again we had the same problem
our Firmware link is:
https://github.com/mhkabir/Firmware/

and also our flight controller is pixhawk 2

**Comment by mhkabir** [comment]
Why are you using my fork instead of master?

**Comment by saeidkazemi** [comment]
what do you mean by fork exactly?

**Comment by mhkabir** [comment]
Why are you not using https://github.com/PX4/Firmware/ ?

**Comment by saeidkazemi** [comment]
actually we used that firmware and we set sys_mc_est_group in LPE mode then we reboot the pixhawk and again we didn't have LPE-GPS-ON

**Comment by jgoppert** [comment]
If you are using px4fmu-v2 make sure you use : make px4fmu-v2_lpe upload
