### ISSUE TITLE
Barometer can not be used in hil mode after downloading new firmware 

### ISSUE THREAD

**Issue by DeanJJJ** [PX4/Firmware#5320]
Barometer can not be used in hil mode after downloading new firmware . Why does it happen and how to fix it? 
pls!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hridaybavle** [comment]
Hi, 
I am having the same problem, pixhawk does not publish any absolute pressure value after updating the firmware. Did you find any solution?

**Comment by DeanJJJ** [comment]
Hi,
my problem was QGC can not detect "fake" barometer in hil (simulation) mode, in flight mode, there is pressure value output but no pressure_alt
