### ISSUE TITLE
Unable to run make with targets given in PX4 Devguide

### ISSUE THREAD

**Issue by han-so1omon** [PX4/Firmware#5329]
From the px4/Firmware directory, I have run `cmake .`. Then, I try to run `make eagle_default` followed by `make eagle_default upload`. However, the `eagle_default` target is not available. I have previously cloned the PX4/Firmware repository and have run `git submodule update --init --recursive`. Why is this target not available?

**Comment by bartslinger** [comment]
See [https://github.com/PX4/Firmware/tree/master/cmake/configs](url) for a list of available targets

**Comment by dagar** [comment]
@han-so1omon try updating your git repo or do a fresh clone.
http://dev.px4.io/starting-building.html
