### ISSUE TITLE
Parameter change does not make sound.

### ISSUE THREAD

**Issue by agribov** [PX4/Firmware#5331]
After updating to 1.4.1 I noticed that my copter doesn't beep when I change a parameter. Was that on purpose? I found it incredibly useful to confirm the parameter changes.

**Comment by dagar** [comment]
@LorenzMeier was this intentional? If not I'll look into fixing it.

**Comment by dagar** [comment]
@agribov yes this was an intentional change. QGC should let you know if a param change fails.
