### ISSUE TITLE
Build error occured 'cause of a warning. (make posix_sitl_default jmavsim)

### ISSUE THREAD

**Issue by junhohan** [PX4/Firmware#5348]
I got an error when run below. (on Mac OS X)

    $ make posix_sitl_default jmavsim

The error is like this.

> ../src/modules/systemlib/print_load_posix.c: In function ‘print_load’:
> ../src/modules/systemlib/print_load_posix.c:117:20: error: variable ‘basic_info’ set but not used [-Werror=unused-but-set-variable]
>   task_basic_info_t basic_info;
>                     ^~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> cc1: all warnings being treated as errors
> [15/86] Building CXX object src/lib/te...estimation.dir/terrain_estimator.cpp.o
> ninja: build stopped: subcommand failed.
> make: *** [posix_sitl_default] Error 1

There is a varable not used in "print_load_posix.c".

    task_basic_info_t basic_info
    basic_info = (task_basic_info_t)tinfo;

I think this should be deleted under the "-Werror=unused-variable"  option.

**Comment by bkueng** [comment]
yes, you're right. see #5364

**Comment by Unity-W** [comment]
i meet the same problem,but
where is the "I think this should be deleted under the "-Werror=unused-variable" option."
I can't find it
