### ISSUE TITLE
Quad tailsitter VTOL SITL - crash after transition

### ISSUE THREAD

**Issue by antsgbl** [PX4/Firmware#5382]
Gazebo SITL of quad tailsitter vtol. 

make posix_sitl_default gazebo_tailsitter
phx> commander takeoff
phx> commander mode altctl
phx> commander transition

will cause the tailsitter to fall off the sky and crash, whereas the same in standard-vtol will cause the plane to circle holding altitude. 

[screen grab](https://www.youtube.com/watch?v=fbMwxMpIXBY)

Whereas the same in standard vtol will cause the plane to circle holding altitude.

**Comment by julianoes** [comment]
Can you check @tumbili?

**Comment by LorenzMeier** [comment]
Fixed with better gains.
