### ISSUE TITLE
Add MAVLink support to motor test

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5386]
Current command line implementation:
https://github.com/PX4/Firmware/blob/master/src/systemcmds/motor_test/motor_test.c

The right location to add the MAVLink -> uORB translation:
https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L373

the topic should be advertised there (which also publishes) and then orb_unadvertise() should be called to free the resources. No global advertisement handle should be retained.

**Comment by mhkabir** [comment]
This is already implemented.
