### ISSUE TITLE
Snapdragon Flight upload error: "waiting for bootloader..."

### ISSUE THREAD

**Issue by julien10** [PX4/Firmware#5391]
I'm trying to upload the Hello Sky example app on the Snapdragon Flight, following the guide at http://dev.px4.io/tutorial-hello-sky.html
When I try to make upload, it gets stuck at:
`Loaded firmware for 9,0, size: 1025348 bytes, waiting for the bootloader...
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.`

I have tried to unplug and replug, and also `reboot2fastboot`, but it did not change anything.
Is there something different with the Snapdragon Flight?

**Comment by julianoes** [comment]
Are you following these steps to upload it?
http://dev.px4.io/starting-building.html#qurt--snapdragon-based-boards

It seems like you are trying to upload something to a Pixhawk/Pixracer from the output.

**Comment by julien10** [comment]
No, I was using the Pixhawk commands, I did not realise there were different, my bad! 
So I just have to build and then upload using `make eagle_default upload`, or do I also have to modify a cmake file (as they show in the tutorial)?

**Comment by julianoes** [comment]
No, you just use what's in dev.px4.io. Which tutorial do you mean?

**Comment by julien10** [comment]
http://dev.px4.io/tutorial-hello-sky.html#step-3-register-the-application-in-nuttshell-and-build-it
