### ISSUE TITLE
SITL gazebo flip at takeoff

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#5415]
When I use the `no_sim=1 make posix_sitl_default gazebo` and insert the iris (actually any quad) it flips at takeoff (`commander takeoff`).

@jgoppert @LorenzMeier I saw that this changed 3 days ago #5400. So when I change the parameter SENS_BOARD_ROT back to 8, it works.

**Comment by LorenzMeier** [comment]
You need to make sure that you update sitl_gazebo, as the equivalent of the board rotation has been done in the interface: https://github.com/PX4/sitl_gazebo/commit/2ae68838fff2fcaf02e95f7d27a0cafae58d9b89

So now no model needs the rotation setup.

**Comment by ChristophTobler** [comment]
Yup... my sitl_gazebo was not up to date...
