### ISSUE TITLE
Release1.4.1,how to switch mode from MC TO FW?

### ISSUE THREAD

**Issue by jarilq** [PX4/Firmware#5417]
1.3.4,I can set RC AUX1 as switch button，but 1.4.1，AUX1 not useful，which button I can set for Switch MC mode to FW mode and reverse it？can you give some idea or instructions to set mode transition？ @LorenzMeier

**Comment by sanderux** [comment]
it changed to RC_MAP_TRANS_SW
You need to set the value to the channel you want to use.
