### ISSUE TITLE
QGroundControl supports newer PX4 firmware

### ISSUE THREAD

**Issue by Stifael** [PX4/Firmware#5419]
Starting QGroundControl, a pop-up window shows following error despite using newest firmware version:
"QGroundControl supports PX4 Pro firmware Version 1.4.1 and above. You are using a version prior to that which will lead to unpredictable results. Please upgrade your firmware."

**Comment by kd0aij** [comment]
Same error message here too:
```
pxh> ver all
HW arch: SITL
FW git-hash: 9d861f021cb1f4f968dcac5a691bed41f0ba1eb2
FW version: v1.5.0-19-g9d861f0 (1.5.0 0), 17104896
```

**Comment by DonLakeFlyer** [comment]
Dup of #5308
