### ISSUE TITLE
Bias saturation in LPE correctionLogic

### ISSUE THREAD

**Issue by HidenoriKobayashi** [PX4/Firmware#5420]
Could anyone explain why the code below is needed? It seems to me the bias is only put in local variables and the function returns without using them. Shouldn't this saturation be propagated back to dx?

https://github.com/PX4/Firmware/blob/master/src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp#L610

**Comment by LorenzMeier** [comment]
@jgoppert Can you look?

**Comment by jgoppert** [comment]
Yes, definitely should be setting the result to dx, will fix. @HidenoriKobayashi thanks for finding this.

**Comment by jgoppert** [comment]
Fixed.
