### ISSUE TITLE
Change defaults for GF_MAV_HOR_DIST and GF_MAV_VER_DIST to 0

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#5430]
Also set min metadata to 0. Description says these are enabled if > 0. So a 0 default makes more sense. The current -1 default causes problems with QGC metric to feet conversion. Since it converts -1 meters to feet which looks like crap as a trigger for not enabled.

**Comment by DonLakeFlyer** [comment]
This makes for confusing geofence setup in the new geofence editor.

**Comment by dagar** [comment]
Makes sense I'll change it. I also have a few other minor geofence tweaks from the last time I used it.
