### ISSUE TITLE
Camera PWM trigger issues

### ISSUE THREAD

**Issue by jcooper21** [PX4/Firmware#5437]
@dagar @DonLakeFlyer I am not sure if this issue should be in PX4 firmware or QGC.  The main issue is we cannot set our PWM values when setting up camera trigger type in QGC.  All we can select is seagull QX1 and I do not have that camera to fly to test out survey.  We need to be able to setup our PWM values for different cameras manually as seen in mission planner.  We are missing our servo limits, Push and do not push values.

![mission-planner-map-x-v2](https://cloud.githubusercontent.com/assets/14355782/18212593/42d9f80e-7101-11e6-8a74-3c6339360428.png)

**Comment by dagar** [comment]
@kellysteich @birchera Thoughts on adding this to camera_trigger?

**Comment by AndreasAntener** [comment]
From a design perspective, the PWM camera interface implementation we have now should not be a MAP2 impl. but have a few parameters to specify PWM limits (neutral, on, off, shutter, AF, etc.).

Or, it needs to be abstracted more (for the architects under us ;)): the camera interface only considers how to output the control values (where it will have a PWM impl.). Then adding another interface that can be implemented to specify what values are used (where it will have a MAP2 impl.).

**Comment by jcooper21** [comment]
@DonLakeFlyer @dagar I think on the QGC side this has to be supported either way as part of the APM compatibility otherwise no APM users will use QGC for surveying. Given it has to be built into QGC it would be great if PX4 firmware allowed for the same functionality.

**Comment by DonLakeFlyer** [comment]
@jcooper21 Can you add a QGC issue with the same images for me to implement the ArduPIlot support?

**Comment by jcooper21** [comment]
@dagar any chance this can fit into the PX4 1.5 release?

**Comment by dagar** [comment]
I'm traveling this week, but if it's really as simple as pushed PWM value for duration, not pushed otherwise I can implement it when I get back. I'd have to lean on you for testing though as I don't have one of these devices. Interested?

**Comment by jcooper21** [comment]
Ya that sounds good.

**Comment by dagar** [comment]
Great!
Can you link to the device you use? What are reasonable defaults for pushed on, not pushed, and duration? What's "AC-T" mode?

**Comment by jcooper21** [comment]
I use a few different devices linked below. The push, not pushed and duration values change for each device so we just need a blank field to input our numbers in. The AC-T is just a seagull feature so they set the ouch value to activate the the mode. 

http://www.seagulluav.com/seagull-map-x-support/#1445895077368-fc8aa683-2ecb

http://vp-systems.eu/order_cr.html

http://www.tuffwing.com/store/store.html

**Comment by dagar** [comment]
@jcooper21 I'm just trying to figure out how to make this cleanly fit with what we already have (MAP2).

**Comment by jcooper21** [comment]
What you currently have with map2 will not work.  Currently its setup incorrectly for most users.

**Comment by dagar** [comment]
I think I know what you mean, but please elaborate. Which part is setup incorrect for most users?

Currently I'm creating another type of trigger (next to gpio and seagull) that's just simple PWM values on for duration, then off. Does that sound correct? I don't have or use any of these devices so you're going to have to be very specific if I've misinterpreted.

**Comment by jcooper21** [comment]
That sounds correct another drop down for PWM and then be able to input values into the PWM fields as shown in the screenshot.  That will work perfectly.  Are you integrating the Camera feedback at the sametime?

**Comment by dagar** [comment]
Are the hard coded values for Seagull correct or should it be configurable?

#define PWM_CAMERA_DISARMED			900
#define PWM_CAMERA_ON				1100
#define PWM_CAMERA_AUTOFOCUS_SHOOT	1300
#define PWM_CAMERA_NEUTRAL			1500
#define PWM_CAMERA_INSTANT_SHOOT	1700
#define PWM_CAMERA_OFF				1900
#define PWM_2_CAMERA_KEEP_ALIVE		1700
#define PWM_2_CAMERA_ON_OFF			1900

I'm just trying to determine if Seagull is a special case of PWM or can be within the same class.

**Comment by jcooper21** [comment]
Those setting work for for seagull sony cameras but not for others for example camera on/off does not exist for other manufacturers even with seagull cables and instant shot can be changed to another mode if it was available and that is at a 1800 PWM value.

**Comment by dagar** [comment]
So it sounds like we probably want a dropdown of predefined Seagull cables, but I'll leave that alone for now and just do a completely separate trigger type (within camera_trigger) for simple PWM on (duration) / off.

2 new params
TRIG_PWM_ON - PWM on value in us
TRIG_PWM_OFF - PWM off value in us
TRIG_ACT_TIME (already there).

**Comment by mhkabir** [comment]
Closing in favour of #6961.
