### ISSUE TITLE
QGroundControl unable to receive Mavlink messages

### ISSUE THREAD

**Issue by bharath374** [PX4/Firmware#5438]
QGroundControl does not receive any Mavlink communication or telemetry data from Snapdragon flight anymore (other than a generic heartbeat). Communications from QGC to the Snapdragon Flight target are fine, only the other way does not seem to work. The issue seems to have been introduced here: https://github.com/PX4/Firmware/commit/15e50b26dc5f3cf773bb1824a265dc28bd383279

The issue seems to be that "orb_exists" always returns "true" until "orb_subscribe_multi" is called, but 
"orb_subscribe_multi" never has a chance to get called since "orb_exists" always returns "true".

@LorenzMeier

**Comment by LorenzMeier** [comment]
@bharath374 Can you test this fix locally? https://github.com/PX4/Firmware/pull/5450 We should also sync on the drone type we want to use for Snapdragon so we can finalise testing.

**Comment by bharath374** [comment]
@LorenzMeier Tried it out, works!

**Comment by LorenzMeier** [comment]
Applied. Closing.
