### ISSUE TITLE
SITL gazebo: Tools/sitl_gazebo/models/iris/iris.sdf not updated

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5465]
The simulation in gazebo seems broken on master.

Steps to reproduce:

```
make posix gazebo
```

Then try to takeoff using:

```
pxh> commander takeoff
```

**Comment by julianoes** [comment]
Bisect points to 010c9e937b23988b222de6a1f714b57690f7742f

**Comment by jgoppert** [comment]
This is odd, how did the SITL CI pass?

**Comment by bkueng** [comment]
This works fine for me, I use gazebo 6.5.1.

**Comment by julianoes** [comment]
It seems to be only my my Ubuntu 16.04 with gazebo7. Mac with gazebo7 is ok.

**Comment by LorenzMeier** [comment]
Works fine on Mac here as well after all clean actions (make and git). I'm on stack_abstraction which is a branch addressing a few OS-specific stack size issues. It might be worthwhile for you to try as well.

**Comment by julianoes** [comment]
Did a fresh checkout of Firmware and all is good again :confused:.

**Comment by julianoes** [comment]
The file Tools/sitl_gazebo/models/iris/iris.sdf was not re-generated/updated.

The following resolved the problem:
```
cd Tools/sitl_gazebo
git clean -d -f -x
```

**Comment by dagar** [comment]
@julianoes Try `make distclean` next time. I use it when jumping between branches with big changes, especially when submodules have been added/deleted/url changed.

**Comment by julianoes** [comment]
This should be fixed by https://github.com/PX4/sitl_gazebo/pull/57, see https://github.com/PX4/sitl_gazebo/pull/57/commits/d9b9f5b96012bc90be2ceb05483788f6ae62dabd.
