### ISSUE TITLE
LPE position is reset to (0,0) when vision position resumed after timeout

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#5478]
@jgoppert Using an on-board vision system and PX4flow, I experience the following behavior, which I consider as inconsistent: After e.g. a vision time-out position is estimated on flow only, which is perfect. When visioning resumes, it is re-initialized, which means, that `_visionOrigin` is set to the mean of the first 20 samples. Assuming the vehicle does not move, the next vision correction is performed with an absolute position of (0,0) (which is an implicit reset of the position). This ignores that fact, that during vision timeout, flow position was valid - and could result in a wrong vehicle movement (e.g. in pos hold). Wouldn't it make more sense, to determine the vision bias during initialization relative to the current position instead of (0,0) - at least if the position is valid?

**Comment by jgoppert** [comment]
Fixed on master.
