### ISSUE TITLE
First log of new day written to the wrong directory

### ISSUE THREAD

**Issue by tstellanova** [PX4/Firmware#5481]
With latest px4/firmware master:
- Log some flights on Saturday 2016-09-10. These flights are logged to the correct directory "2016-09-10". Leave this directory in place (do not delete).
- Fly one flight on Sunday 2016-09-11.  The log file is written to the same directory as Saturday's flights, which is incorrect.
- Fly another flight on Sunday. This log file is written to the correct directory "2016-09-11".

Note that I have always-on logging enabled rather than "start logging on Arm".

**Comment by mhkabir** [comment]
This is most likely fixed with new logger.
