### ISSUE TITLE
pre-commit hook differs from `make check_format`

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5484]
I ran into the following case where the git pre-commit hook triggers but `make check_format` is all happy:

```
git commit
src/modules/mavlink/mavlink_mission.cpp:270: space before tab in indent.
+ 		} else {

make check_format 
Checking formatting with astyle
Format checks passed
```

FYI @AndreasAntener

**Comment by AndreasAntener** [comment]
Awesome, isn't it ;)

The pre-commit hook includes the default git whitespace check which complained here. I guess we should included that in our check script instead.

**Comment by julianoes** [comment]
Ah got, and yes it's cool! :smile:

**Comment by dagar** [comment]
@julianoes does this catch it? #5503

**Comment by dagar** [comment]
Merging #5503 because it's trivial. Let me know if it's not enough.

**Comment by julianoes** [comment]
Great, thanks @dagar!
