### ISSUE TITLE
mavros/state single message and connected: false

### ISSUE THREAD

**Issue by pietrop88** [PX4/Firmware#5512]
Hi everybody,

I installed mavros on a Edison board that is connected to the Pixhawk.
Mavros is able to stream the messages in the /mavros/local_position/pose and /mavros/imu/data topics. I also successfully connected qGroundControl with the Pixhawk through UDP.
The problem is when I check the mavros/state topic: I can only see one message and the field "connected" inside the message is set to false. 
I am also not able to set the flight mode to OFFBOARD (I check my code with the simulation environment and it works).

**Comment by paphatdev** [comment]
I have same proble.
Did you solved it?
