### ISSUE TITLE
Takeoff Denied after arming

### ISSUE THREAD

**Issue by anujkumargupta** [PX4/Firmware#5513]
Hi, I am facing these 2 issues .so please help me out.

1. I am trying to connect my pixhawk with qgc using virtual joystick. In manual mode it armed successfully but after giving the takeoff command it says takeoff denied , disarm and retry.I tried again the same thing and i also calibrated all the sensors again but it shows same problem again and again.

2. I am trying to fly in mission mode or position mode . I planned a mission but whenever i try to switch the flight mode to mission from manual it says "set flight mode command temporarily rejected". Even in the planning tab after sending the position to the vehicle , the mavlink shows "Not yet ready for mission, No position lock".

Thanks

**Comment by mhkabir** [comment]
The problem is that you have no position lock. Make sure your GPS has a 3D fix. 

Both those issues stem from there.

**Comment by anujkumargupta** [comment]
Thanks
When i am trying to fly in manual mode then it takeoff problem occurs. Is gps required in manual mode also??

**Comment by mhkabir** [comment]
Takeoff is an auto manueovre which requires a position estimate.

If you're in manual, you're going to have to take off 'manually', by definition.

**Comment by anujkumargupta** [comment]
I am taking it off manually after arming by clicking on the takeoff button as shown in pic.
Thanks

![screenshot from 2016-09-20 14 19 35](https://cloud.githubusercontent.com/assets/22234294/18663746/6ae600b4-7f3d-11e6-9386-a3ee3de13efd.png)

**Comment by mhkabir** [comment]
That is not a "manual" takeoff.

"Manual" means YOU control it using a transmitter/joystick/whatever and raise the throttle till the vehicle starts climbing.

**Comment by anujkumargupta** [comment]
Is it possible to to that using virtual joystick ??
If yes then how??
I tried to gave throttle after arming but the altitude is not increasing.
Thanks

**Comment by anujkumargupta** [comment]
Is it possible to to that using virtual joystick ??
If yes then how??
I tried to gave throttle after arming but the altitude is not increasing.
Thanks
