### ISSUE TITLE
nsh_parse NULL dereference 

### ISSUE THREAD

**Issue by lovettchris** [PX4/Firmware#5519]
These lines crash the nsh_script execution if a variable is referenced in your script that doesn't exist.  Notice there is no NULL check on the var_value.  This is inside nsh_parse.

char *var_value = getenv(var_name_start);
*var_name_end = tmp_char;
res_size += strlen(var_value);

How do you go about fixing Nuttx bugs ?

**Comment by davids5** [comment]
Please do a PR against PX4/NuttX

**Comment by LorenzMeier** [comment]
@davids5 Can you check if this persists upstream?

**Comment by dagar** [comment]
@lovettchris was this fixed? Is it still an issue with PX4 master?

**Comment by davids5** [comment]
The code fragment above does not exist in the the version of NuttX tied to PX4 master or in upstream Nuttx.
