### ISSUE TITLE
Building errors with px4fmu-v2_default on Windows

### ISSUE THREAD

**Issue by alpha17** [PX4/Firmware#5525]
As I'm trying to build an example like the one on the development guide, I got some problem when using the make px4fmu-v2_default instruction. The errors are emphasized in the console window as you can see below:
![1](https://cloud.githubusercontent.com/assets/7569503/18702824/0754da3c-8016-11e6-93af-ec4aace3c87f.PNG)

Using Windows as my OS. Very new to PX4. Hope this isn't a stupid question. But I just can solve it by myself.  I will be grateful for any help from anyone.

**Comment by julianoes** [comment]
Hi @alpha17, have you seen the note that Windows is not officially supported here:
http://dev.px4.io/starting-installing-windows.html

I would recommend to try it on a Linux in VirtualBox or try Bash On Windows.

**Comment by dagar** [comment]
@LorenzMeier @julianoes it's going to be annoying, but realistically we need a single windows build or it's just going to keep breaking all the time.

**Comment by alpha17** [comment]
Thanks for your advice and adjustment on the title, @julianoes! I did read that part in the devguide before. But I thought I should give it a try on Windows first. Will get a Linux OS installed in these couple days and see if there's any problem.

**Comment by alpha17** [comment]
Built the project without error using Ubuntu. Thanks again,  @julianoes!

**Comment by julianoes** [comment]
Cool, thanks for the feedback!
