### ISSUE TITLE
SENS_BOARD_ROT other than 0 cause incorrent result

### ISSUE THREAD

**Issue by chobitsfan** [PX4/Firmware#5547]
In 3dr solo SENS_BOARD_ROT = 12 (pitch 180)
It works OK in v1.3.4
but it does not work in v1.4.4 and v1.5(orientation is incorrect when display in QGC)

**Comment by julianoes** [comment]
@bkueng did you maybe touch this in the sensors refactor?

**Comment by LorenzMeier** [comment]
Code review says that the change was consistent and correct.

@chobitsfan Have you configured the vehicle fresh again and validated things are correct?

**Comment by chobitsfan** [comment]
thank you :)

It happens after I build & upload master to solo
I set airframe to dji f450 to reset parameters, and set back to solo (incorrect orientation)
I use git checkout to v1.4.4, build & upload, reset all parameters (incorrect orientation)
then I git checkout to v1.3.4, build & upload, reset all parameters (everything ok)

I will do it again (tomorrow, after tornado pass)
I will flash it to v1.3.4, choose another airframe to reset parameters, then choose 3dr solo.
then I will flash it to v1.4.4, choose another airframe to reset parameters, then choose 3dr solo.

**Comment by chobitsfan** [comment]
I have tested it again
I flash solo with stable (v1.4.1) and master, both show incorrect orientation in QGC
I check out v1.3.4, build & upload, correct orientation

**Comment by limhyon** [comment]
Hi,
I have exactly same problem with @chobitsfan .
I flashed latest github master, and select vehicle configuration to 3DR solo.
It says, the IMU orientation is "Pitch 180" however, when I calibrate the accelerometer,
it show wrong orientation (for example, stand normal shows it is reversed).

**Comment by limhyon** [comment]
I didn't isolate the problem whether this is becasue QGC problem or PX4 problem.
But ROTATION_YAW_270 in calibration menu gives correct result.

**Comment by LorenzMeier** [comment]
Closing this as stale.
