### ISSUE TITLE
FOH alt mode does not work for transition waypoints

### ISSUE THREAD

**Issue by devbharat** [PX4/Firmware#5562]
The gradient calculation for increment the altitude setpoint [here](https://github.com/PX4/Firmware/blob/92d160c431ab8e2721e95855f865748d9f5cc22f/src/modules/navigator/mission.cpp#L968-L977) after transition waypoint gets screwed because of [this function](https://github.com/PX4/Firmware/blob/92d160c431ab8e2721e95855f865748d9f5cc22f/src/modules/navigator/mission_block.cpp#L421-L432).

![f7e9ef2c-848b-11e6-87f0-42b76b69ce70](https://cloud.githubusercontent.com/assets/3105122/18922559/773807aa-85a9-11e6-8843-768874a73f1a.png)

**Comment by LorenzMeier** [comment]
Did you see that this has already been fixed on master?

**Comment by dagar** [comment]
We could lazily initialize the previous altitude for FOH here instead of returning.
https://github.com/PX4/Firmware/blob/92d160c431ab8e2721e95855f865748d9f5cc22f/src/modules/navigator/mission.cpp#L920

**Comment by devbharat** [comment]
Sorry about that https://github.com/PX4/Firmware/pull/5299 fixed it.
