### ISSUE TITLE
Commander: wait with auto-disarming if not flown

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5565]
We should make the timeout for auto-disarming longer if the vehicle has not yet taken off. This will make it more convenient, especially with small auto-disarming timeouts where the vehicle keeps auto-disarming when you're trying to take off.

This was suggested by @xiaoyuLi-China0372 in #5540.

**Comment by mhkabir** [comment]
Yes, this would be very nice. With the default 2 seconds, it disarms even before the motor ramp up is finished, which is rather disorienting, because you're expecting the motors to come up to power, and it gets killed before that.

**Comment by julianoes** [comment]
Fixed with #5567.
