### ISSUE TITLE
Snapdragon FC build problem

### ISSUE THREAD

**Issue by anujkumargupta** [PX4/Firmware#5568]
Hi i am using snapdragon FC  on ubuntu 14.04 64 bit and trying to flash the px4 filmware in it but after running the command make eagle default it throws some linking error 
Actually it asking for some libraries which is present in sysroot lib folder but in make file it is looking in my root directory and there is no lib file
I copied a lib file from sysroot to my root (/lib/) folder then it find that lib but again start asking for some other one 
So please tell where i can change the path where the make file is searching for lib files.

Scanning dependencies of target px4
[ 98%] [ 98%] Building C object src/firmware/posix/CMakeFiles/px4.dir/px4muorb_stub.c.obj
Building CXX object src/firmware/posix/CMakeFiles/px4.dir/__/__/platforms/posix/main.cpp.obj
Linking CXX executable px4
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find /lib/libpthread.so.0
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find /usr/lib/libpthread_nonshared.a
collect2: error: ld returned 1 exit status
Thanks

**Comment by julianoes** [comment]
Please no duplicate issues, I'm already looking into it in #5557.
