### ISSUE TITLE
Bebop 2: take mount angle of AK8963 into account

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5571]
According to @EwoudSmeur int #5236.
> Turns out the magnetometer is located on the gps board, which is angled wrt. the IMU.

We should take the rotation into account to get better calibration results.

**Comment by LorenzMeier** [comment]
@eyeam3 Needs extension here: https://github.com/PX4/Firmware/blob/3b889375947463aede2b6a35c2f43a86f06b9b5d/src/lib/conversion/rotation.h#L83

And then setting `SENS_BOARD_ROT` to the appropriate enum value.
