### ISSUE TITLE
Attitude representation cleanup: use quaternions

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#558]
Now it's possible to use attitude setpoint as euler angles, rotation matrix and quaternion. But this feature is not fully supported yet, and adding code to support each representation will not make code too compliated.

I think we should use one representation for setpoint - quaternion. It's much more compact than rotation matrix and can be easily converted to rotation matrix or euler angles, also it can be logged directly.

So, what should be done:
 - vehicle_attitude_setpoint topic: quaternion ONLY
 - vehicle_attitude topic: mandatory quaternion and maybe euler angles to avoid recalculating it in different apps
 - sdlog2: attitude and attitude setpoint quaternions logging
 - FlightPlot: quaternion to euler angles and rot matrix component processor

It's all doesn't look hard if we will have quaternion<->rot matrix<->euler angles translation functions.

**Comment by LorenzMeier** [comment]
Doing that on master.
