### ISSUE TITLE
How to use the mavros and gazebo to simulation the muitcopters

### ISSUE THREAD

**Issue by kiti1013** [PX4/Firmware#5583]
I am a green hand in ROS, when I try to use mavros and gazebo to launch a simulaton according to dev guide， but some file isn't exist。such as setup_gazebo_ros.bash.... so who can help me how to do it in the ture way.

**Comment by julianoes** [comment]
The documentation is indeed outdated, let's track this issue here: https://github.com/PX4/Devguide/issues/46.
