### ISSUE TITLE
UAVCAN Compass Yaw

### ISSUE THREAD

**Issue by jcooper21** [PX4/Firmware#5587]
With PX4 and a Zubax GPS it is impossible to have the flight control yawed and the compass facing straight. If the flight controller is yawed the compass has to be yawed in the same direction for a proper calibration and flight.

**Comment by LorenzMeier** [comment]
@mhkabir @pavel-kirienko Can you comment on that?

**Comment by pavel-kirienko** [comment]
Yes, the description is correct.

If we want to fix this, we'll need to add necessary transformation of the magnetic field vector in the UAVCAN --> uORB compass bridge.

**Comment by mhkabir** [comment]
New API fixed this sometime back.
