### ISSUE TITLE
LOCAL_POSITION_NED Cant Init After Arming

### ISSUE THREAD

**Issue by meteor0530** [PX4/Firmware#5593]
Hi,

I recently updated the PX4 firmware through QGC 3.0.0. I used GPS for position estimate, then I used mavlink inspector to monitor the local_position_ned, and I found after I armed the FCU the position didnt initialize(x,y,z cant become 0). I used OFFBOARD to control the multicopter, then it turned over.how can I fix it?

Any help is appreciated.

**Comment by julianoes** [comment]
Duplicate of #5604.
