### ISSUE TITLE
Airspeed temperature dependency analysis

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#5595]
@LorenzMeier first shot at logging temperature data. Looks like I need to allow the negative values for the test. But I was wondering why one sensor gives a higher reading while the other one goes down? Both sensors were calibrated inside and covered. Also they show a different temperature. Are we sure that the voltage correction that happens in the driver is correct (both setups have a slightly different system voltage)? Maybe I need a different procedure to measure and log the raw values, maybe with generated airspeed.

pixfalcon-auva-inside
![pixfalcon-auva-inside_log_0_2016-9-28-15-19-16 px4log](https://cloud.githubusercontent.com/assets/5750020/19071317/bbdee998-8a2f-11e6-896c-d1839a505e3a.png)

pixfalcon-auva-outside
![pixfalcon-auva-outside_log_1_2016-9-28-15-21-20 px4log](https://cloud.githubusercontent.com/assets/5750020/19071314/bbd9f884-8a2f-11e6-9fe9-e1288aaf5fc3.png)

dropix-3dr-inside
![dropix-3dr-inside_log_7_unknowndate px4log](https://cloud.githubusercontent.com/assets/5750020/19071316/bbddaba0-8a2f-11e6-9de8-d2ca93186873.png)

dropix-3dr-outside
![dropix-3dr-outside_log_8_unknowndate px4log](https://cloud.githubusercontent.com/assets/5750020/19071315/bbdd7568-8a2f-11e6-8518-dfb3516f7bb5.png)

Ref: #4616

**Comment by sanderux** [comment]
Here's what happens when the sensor is mounted behind the air intake on a vtol:
![selection_008](https://cloud.githubusercontent.com/assets/14801663/19073020/ec84f3ae-8a38-11e6-840d-a64825772336.png)
http://logs.uaventure.com/view/jg2rHZDRmAboYLiqyFVuge

Here's what happens after a few flights:
![selection_009](https://cloud.githubusercontent.com/assets/14801663/19073180/e090fd1c-8a39-11e6-8a2d-a1e95ad16b85.png)
http://logs.uaventure.com/view/DwRTKb7jKf5LHXH553s6n7

Here's what happens in africa with bad cooling and wrong angle:
![selection_010](https://cloud.githubusercontent.com/assets/14801663/19073334/ba427612-8a3a-11e6-82a4-8bb7b895c5d5.png)
http://logs.uaventure.com/view/5MFXSfPmYwrUFxuCDnQj7T

**Comment by AndreasAntener** [comment]
@LorenzMeier @priseborough I'd appreciate feedback on this. It is possible that my measuring method makes no sense for what we want to find out (temperature dependency and possible method to compensate, or at least enforce a recalibration if needed) and that we should actually somehow generate constant airspeed for the test than just recording the offset.

Here's what I got: the following charts show the differential pressure (in Pa) and temperature as they are returned by the sensor and in addition the 5v corrected values (the correction that happens in the driver). I tested with the default 3DR (calibration offset ~6Pa) sensor and with the new one from AUAV (calibration offset ~60Pa).

The pitot tubes were lightly covered on both setups. The sensors are outside the body. Both setups were calibrated inside powered with the main battery. Inside temperature guessed around 25 degree, outside temperature roughly 10 degree.

**Test 1: cool down outside**

Dropix with 3DR sensor:
<img width="1372" alt="dropix 2" src="https://cloud.githubusercontent.com/assets/5750020/19129660/5f96a7f6-8b48-11e6-80ed-cd3899d39b78.png">

Pixfalcon with AUAV sensor:
<img width="1370" alt="pixfalcon 2" src="https://cloud.githubusercontent.com/assets/5750020/19129658/5dd726b6-8b48-11e6-9c13-02a2a9fc8b32.png">

**Test 2: start logging inside, only a brief moment outside**

Legend:

1. opening hallway door (cold air starts to flow in)
2. carrying vehicle outside
3. placing on the ground outside
4. carrying vehicle inside
5. placing vehicle on the ground inside
6. closing hallway door

Dropix with 3DR sensor:
<img width="1366" alt="dropix" src="https://cloud.githubusercontent.com/assets/5750020/19129649/59bbb092-8b48-11e6-9b51-f3b81a4a1421.png">

Pixfalcon with AUAV sensor:
<img width="1365" alt="pixfalcon" src="https://cloud.githubusercontent.com/assets/5750020/19129654/5b07519a-8b48-11e6-995b-42d71b424cb7.png">

**Observations**
- both setups react into opposite directions with the temperature change
- the change is very noticeable going outside but not really when coming back in
- the 3DR sensor slowly changes with temperature where as the AUAV sensor shows change in a much smaller timeframe

This makes me believe that the 2 setups must have a difference I'm not aware of and that I need a different test setup/method :)

**Comment by LorenzMeier** [comment]
Awesome data! Its possible that both sensors respond differently to temperature. @tumbili Could you maybe fit a polynomial and try compensating in the driver? I would not be surprised if you get a correct fit for both if you calibrate both that way.

**Comment by tubeme** [comment]
Any progress in this research? We continue to have nasty problems with the airspeed related to temperature. There are cases where we get a 15m/s difference between morning and afternoon flights in California where the temp difference is huge between morning and afternoon. Everybody is waiting for the new 55 chip which states that has temp compensation, and indeed it has a totally different way of compensation than the old 45 chip. But sadly there is no delivery yet of this new chip, and nobody says when it is going to be available. For all the current 45 chips it is totally unreliable. And as I remember a discussion with @Lorenz one or two years ago this is probably the most important reading for the autopilot. Especially for the VTOL transition.  So what we can do in this situation?? Is there a mathematical way to compensate somehow this differences?

We got hold of couple of airspeed sensors from real small planes. On some chips they just use heater to give the sensor a constant temperature. On others they don't.

**Comment by sanderux** [comment]
@tubeme https://docs.px4.io/en/advanced_config/vtol_without_airspeed_sensor.html

**Comment by tubeme** [comment]
Thanks @sanderux We are preparing a machine for this use allready and we will try it. Are the TECS going to work in this scenario and prevent stalls during long mission flights? Is there a way to detect stall without the airspeed and trigger some reaction during flight in guided modes?

**Comment by LorenzMeier** [comment]
We will test next week a sensor from SENSIRION. That should also help.

**Comment by sanderux** [comment]
@tubeme i have found that tecs responds quite well when you have good min/max pitch angles set.

**Comment by tubeme** [comment]
@LorenzMeier Which one? https://www.soselectronic.com/products/freescale/mpx-5500-dp-9006. Do you have a PCB for the test? We might buy some samples as well. Is there a driver for the PX4 or are you going to bench test it only in a lab? Thanks.

**Comment by tubeme** [comment]
@sanderux Thanks for the info, we will find out in real conditions. :) Hope the plane will survive...

**Comment by tubeme** [comment]
I have the MS5525 sensor for tests and it does not run under the current master. Is there anything that should be preset somewhere in the firmware in order for the FW to recognize it? Probably it need different driver?

**Comment by dagar** [comment]
Closing this as I think we're close to moving on from the ms4525.

**Comment by njoubert** [comment]
@tubeme I know this issue is closed, but you linked to a MPX5500 sensor. I'm looking at that sensor, but I don't think that can make a useful airspeed sensor. with a pressure range from 0 to 500kPa, it's got two orders of magnitude higher maximum pressure range than any of the other sensors we use for airspeed on PX4. Did you link to the wrong sensor?
