### ISSUE TITLE
Home point not set due to recent commit

### ISSUE THREAD

**Issue by bartslinger** [PX4/Firmware#5596]
On stable, the drone sets the home point as soon as it gets a good gps position. This works in HITL (with xplane) and in the real world. On master, the home point does not get set. After disabling the changes made by https://github.com/PX4/Firmware/commit/50b8ed0a89d2a6022cc518df65fa6bc57375f393 , it does set the home point as before.

**Comment by bartslinger** [comment]
I'll try although I am a bit scared of the commander.cpp monster

**Comment by julianoes** [comment]
> I'll try although I am a bit scared of the commander.cpp monster

Hehe, but you've already narrowed it down a lot by finding the change that causes it :smile:.

**Comment by bartslinger** [comment]
Turned out to be something else, originating from QGC. It sometimes sent out NaN on acceleration measurements.
