### ISSUE TITLE
INAV estimated position cant reset after arming

### ISSUE THREAD

**Issue by meteor0530** [PX4/Firmware#5604]
Hi,

My system is OSX, I recently updated the PX4 firmware through QGC 3.0.0. I used INAV estimator and GPS for position estimate, then I used mavlink inspector to monitor the local_position_ned, and found after I armed the FCU the position didn't reset (x,y,z cant become 0). how can I fix it?

Any help is appreciated.

**Comment by julianoes** [comment]
Hi, I don't think the local position resets on arming. It only "resets" when the estimator initializes.

What does reset on arming however, is the home position.

**Comment by meteor0530** [comment]
Thanks, maybe my description was unclear. when I used the pervious version of the firmware, the x,y,z coodinates in LOCAL_POSITON_NED reset to 0 after I armed. After I updated the firmware, it didin't work.
And I  don't understand the meaning of the home position, which kind of position does the LOCAL_POSITION_NED belong to?

**Comment by julianoes** [comment]
Ok, I might be wrong. @tumbili can you help?

**Comment by tumbili** [comment]
@meteor0530 @julianoes INAV sets it's reference origin [here](https://github.com/PX4/Firmware/blob/master/src/modules/position_estimator_inav/position_estimator_inav_main.cpp#L869) and I don't see any dependency on arming there. Basically the origin is set as soon as the gps quality is sufficient.
When it does that you should get this message in QGC

[inav] init ref: ...

Are you sure that you are using INAV?

**Comment by mhkabir** [comment]
> armed the FCU the position didn't reset (x,y,z cant become 0). how can I fix it?

It is not supposed to. The local frame reference should never be reset.

**Comment by meteor0530** [comment]
@tumbili  @julianoes 
I am sure im using INAV for estimate position. 
I use an older version of QGC (2.2.0) to download firmware. After arming in LOCAL_POSITION_NED x,y,z reset to 0.
![111](https://cloud.githubusercontent.com/assets/22593986/19111465/4aa7bd32-8b32-11e6-913c-358e92d00b04.JPG)
![222](https://cloud.githubusercontent.com/assets/22593986/19111469/4e1f30e4-8b32-11e6-9dc5-10ef0822205d.JPG)

**Comment by AndreasAntener** [comment]
@meteor0530 this was the case in a (very) old firmware state but was found to be wrong and then fixed. If you are working with local position setpoints (offboard or on board) you don't want to handle a sudden reference reset on arming.

**Comment by meteor0530** [comment]
@AndreasAntener 
I am used to switch to OFFBOARD after arming, so I think reference reset before OFFBOARD is convenient.
If I move my UAV to another position, how can I define this posiiton as the new origin?

**Comment by AndreasAntener** [comment]
It's easy to just keep your own reference from the point in time where you need it.
