### ISSUE TITLE
Snapdragon: remove termios workarounds

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5605]
The Qurt OS on Snapdragon has now support for the termios calls which means we can remove some of the Qurt specific code.

See https://github.com/ATLFlight/dspal/pull/10.

**Comment by mcharleb** [comment]
@julianoes This is another issue we are unlikely to fix given that the workaround seems to be sufficient. Please close unless someone has the bandwith to work on it and you think its a priority.

**Comment by julianoes** [comment]
I went ahead with this before answering :) #7041.
