### ISSUE TITLE
option for slower TELEM

### ISSUE THREAD

**Issue by gregd72002** [PX4/Firmware#5611]
Certain data links require slower mavlink telemetry than 57600. Can we introduce other options (i.e. 28800 or even 19200)?

The SYS_COMPANION config only allows 57600 and higher. Any reason for this?

**Comment by bkueng** [comment]
I don't see a reason against it. Can you create a pull request?

**Comment by gregd72002** [comment]
Pull request created: https://github.com/PX4/Firmware/pull/5630

**Comment by bkueng** [comment]
This got merged, thanks for the PR
