### ISSUE TITLE
Interfacing the Simulation to ROS gazebo error

### ISSUE THREAD

**Issue by kiti1013** [PX4/Firmware#5621]
I follow the developer guide to run the simulation，when I run the command 

`roslaunch gazebo_ros empty_world.launch world_name:=$(pwd)/Tools/sitl_gazebo/worlds/iris.world
`
 the terminal prompt 
[gazebo-1] process has died [pid 4680, exit code 134, cmd /opt/ros/indigo/lib/gazebo_ros/gzserver -e ode /home/astera/Tools/sitl_gazebo/worlds/iris.world __name:=gazebo __log:=/home/astera/.ros/log/6e8dd0d8-8d26-11e6-845f-8c89a509c310/gazebo-1.log].
[gazebo-1] process has died [pid 4680, exit code 134, cmd /opt/ros/indigo/lib/gazebo_ros/gzserver -e ode /home/astera/Tools/sitl_gazebo/worlds/iris.world __name:=gazebo __log:=/home/astera/.ros/log/6e8dd0d8-8d26-11e6-845f-8c89a509c310/gazebo-1.log].
[gazebo-1] process has died [pid 4680, exit code 134, cmd /opt/ros/indigo/lib/gazebo_ros/gzserver -e ode /home/astera/Tools/sitl_gazebo/worlds/iris.world __name:=gazebo __log:=/home/astera/.ros/log/6e8dd0d8-8d26-11e6-845f-8c89a509c310/gazebo-1.log].

my os  ubuntu 14.04 
    ros  indigo
   gazbo 6.6 （sudo apt-get install ros-indigo-gazebo6-ros）

**Comment by julianoes** [comment]
Hi @kiti1013,
any chance you get more output on why they all die? Are you able to use the normal gazebo simulation without ROS using `make posix gazebo`?

**Comment by kiti1013** [comment]
i can  use gazebo simlation normalily without ros

**Comment by julianoes** [comment]
@kiti1013: try running one of the commands that fail on it's own, presumably do:
```
roscore
```

and then
```
opt/ros/indigo/lib/gazebo_ros/gzserver -e ode /home/astera/Tools/sitl_gazebo/worlds/iris.world __name:=gazebo __log:=/home/astera/.ros/log/6e8dd0d8-8d26-11e6-845f-8c89a509c310/gazebo-1.log
```

or check the launch file for what it starts. This should give you more output on what's happening.

**Comment by Hanslen** [comment]
I have the same problem, is there any solution?

**Comment by zhaoxiaowei1013** [comment]
@Hanslen do you what to run a muti copter to simulation？

**Comment by julianoes** [comment]
@Hanslen this is an old thread. Please re-open a new issue and add detailed a description about what your issue is.
