### ISSUE TITLE
Roll/Pitch/Yaw setpoints not logged in STABILIZE mode

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#5623]
http://logs.uaventure.com/view/XyiLq9cLLKzhboT9rpZsmd
Firmware v1.4.4

**Comment by dagar** [comment]
@kd0aij 
I was just looking at a recent log that had attitude and rate setpoints during FW stabilize mode. Can you confirm?

**Comment by kd0aij** [comment]
I have a logfile from 17 October with:

Hardware Version	PX4FMU_V4
Firmware Version	6be0eb76b6c9a42d67fb7965b17f477083b0f6f0

that has vehicle_attitude_setpoint_0.roll/pitch/yaw_body and vehicle_rates_setpoint logged in nav_state 0

So I'll close this
