### ISSUE TITLE
1.5.0 RC1 is reported as 1.4.4 rc1

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#5625]
In the logs and in QGroundControl.

Flashed 1.5.0 RC1 many times to various HW. The same story.

**Comment by DonLakeFlyer** [comment]
I thought @dagar was saying this was a url problem to the stable builds. But I also though that he said he repushed them and fixed it.

**Comment by dagar** [comment]
I'll try to figure out what's going on.

**Comment by dagar** [comment]
Sigh, let me guess px4fmu-v4?

**Comment by dagar** [comment]
This was a completely different problem, hidden beneath the previous problem. PX4 master fixed, beta will be fixed shortly.

**Comment by tubeme** [comment]
It is px4fmu-v2.

**Comment by dagar** [comment]
So px4fmu-v4 was definitely wrong because it wasn't uploading. Let me see if there's yet another issue with the versioning itself.

**Comment by davids5** [comment]
> This was a completely different problem, hidden beneath the previous problem. PX4 master fixed, beta will be fixed shortly.

@dagar What is the root cause or commit that fixed this?

**Comment by dagar** [comment]
@davids5 - https://github.com/PX4/Firmware/commit/e9e15ba3d1d3ae954dc5e27e1c01b50e63f06ca8#diff-b67911656ef5d18c4ae36cb6741b7965

Before that someone hadn't broken travis-ci uploads.
