### ISSUE TITLE
Barometric Altimeter Calibration.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#5627]
Part of our flights are at see level. We have a lot of logs like this.

![baro altitude](https://cloud.githubusercontent.com/assets/12617619/19233889/0f16a3ba-8ef1-11e6-9c5b-e962209bca35.png)

If PX4 is on the ground and has a GPS lock, the GPS altitude reading should be pretty stable and correct, given the machine is not moving. This could be used to some how calibrate the barometric sensor, prior flight. Or at least give us the option to calibrate it manually.

**Comment by AndreasAntener** [comment]
Try SENS_BARO_QNH (https://en.wikipedia.org/wiki/QNH)
And you should be looking at GPOS.Alt, not the raw baro alt (which is btw more stable than your GPS altitude that is clearly drifting on the ground).

**Comment by tubeme** [comment]
Yes it is the QNH we have to adjust. But I thought there could be another way for calibration.

I prefer to see raw data from the sensors during our tests. That is why I look at Barometric sensor data rather than GPOS.Alt 

And you are correct the GPS alt is drifting and not stable for calibration purposes. Probably the RTK GPS systems will allow this to happen because they are very precise in 3d space.
