### ISSUE TITLE
Fix preflightCheck calls and remove default value for last argument

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#5631]
- remove default argument here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.h#L70 (this was already the reason for the last preflight check bugs)
- fix calls in commander

**Comment by sanderux** [comment]
@AndreasAntener i don't believe i changed this. do you need the default removed for reportFailures?

**Comment by sanderux** [comment]
The default was added in this commit: https://github.com/PX4/Firmware/commit/5fcfdb759c2a83c3e13235b0f71d8d6299d46c33#diff-390f83af28dcf517efab5f9cb487194cR70

**Comment by AndreasAntener** [comment]
> @AndreasAntener i don't believe i changed this. do you need the default removed for reportFailures?

> c4eabbd#diff-a2bcb238e25d8a97ab2aee48f54dbc48R386

Yes, the default should be removed (and yes that wasn't you ;)), but your change missed to update all preflightCheck calls which are now wrong because of the new argument and the fact that the last argument has a default value masks that problem.
