### ISSUE TITLE
NULL pointer dereference in sched_note_stop

### ISSUE THREAD

**Issue by chungkim** [PX4/Firmware#5644]
At line 125 of src/modules/systemlib/cpuload.c (master branch), there are times when "system_load.tasks[i].tcb" is NULL but it is dereferenced by "system_load.tasks[i].tcb->pid".  This results in reading an arbitrary value from a low address (that is, the offset of pid).  This happens because sched_note_stop can be called by NuttX before cpuload_initialize_once is called to initialize system_load.tasks.  Tested with PX4/NuttX @ 154289bbf80738c97e5c062729b6904e858c3cef on Pixhawk PX4FMU-v2.

Adding the following check between lines 124 and 125 resolved the issue for me:

`if (system_load.tasks[i].tcb == NULL) continue;`

**Comment by LorenzMeier** [comment]
Fixed in https://github.com/PX4/Firmware/commit/569cceb059a70bbb6aabe4809f4c1d77509eb923.
