### ISSUE TITLE
Problem Using D-GPS

### ISSUE THREAD

**Issue by meteor0530** [PX4/Firmware#5649]
Hi

I updated the PX4 firmware through QGC 3.0.1. I used INAV and D-GPS for position estimate, and used a external compass. when I switch to POSCTRL using RC, the multirotor started to rotate around a point and the radius increased slowly. However, when I used the same compass with a GPS, everything went well. Does it mean D-GPS cant be used in px4?

Any help is appreciated.

**Comment by julianoes** [comment]
Hi, can you please elaborate what kind of D-GPS you're using?
@bkueng can probably help better.

**Comment by meteor0530** [comment]
@julianoes 
OEM615 using GPS-RTK

**Comment by bkueng** [comment]
@meteor0530 does it provide the same output format in RTK mode? If not, it is currently not compatible.
Can you share a log?

**Comment by meteor0530** [comment]
Both GPS and D-GPS provide GPGGA format
when I used D-GPS, I monitored the position in mavlink inspector and it was nice

**Comment by meteor0530** [comment]
@julianoes @bkueng 
Can PX4 use double GPS for localization?

**Comment by julianoes** [comment]
What do you mean with "double GPS". PX4 supports interfacing to two GPS modules. However, I don't think that has much to do with D-GPS or RTK.

**Comment by bkueng** [comment]
So the GPS driver and communication seems to work then. It seems your problem lies elsewhere and you need to share a flight log for us be able to help you.

**Comment by meteor0530** [comment]
@bkueng 
how to upload a .px4log file?

**Comment by julianoes** [comment]
http://logs.uaventure.com/

**Comment by meteor0530** [comment]
already uploaded, waiting for reply. thanks!

**Comment by LorenzMeier** [comment]
Closing due to no further feedback.
