### ISSUE TITLE
Starting additional applications

### ISSUE THREAD

**Issue by pietrop88** [PX4/Firmware#5652]
Hi,

I added the [`px4_mavling_debug`](http://dev.px4.io/advanced-debug-values.html) application to the [`nuttx_px4fmu-v2_default.cmake`](https://github.com/PX4/Firmware/blob/master/cmake/configs/nuttx_px4fmu-v2_default.cmake) file and I am able to run it if I connect to the pixhawk console. 
Now I want to start `px4_mavlink_debug` automatically after the main system boot.
Following the [guide](http://dev.px4.io/advanced-system-startup.html#starting-additional-applications), I added the command `px4_mavlink_debug start` to the `extras.txt` file in `/etc` folder of the sd card.
Rebooting the pixhawk, it connects to qgroundcontrol after a long time interval (~30 s) and I am not able to see the variable `velx` in the Analyze widget of qgroundcontrol.
I also add `px4_mavlink_debug start` to [`rc.mc_apps`](https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.mc_apps) file but I obtained the same result.

Can you help me?

**Comment by julianoes** [comment]
Can you share the code of you `px4_mavling_debug` module? Without seeing it, I'm tapping and guessing in the dark.
