### ISSUE TITLE
Px4fmu-v1/2 out of flash space on master

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#5654]

**Comment by jgoppert** [comment]
Are there any apps we can drop, seems to be 160 bytes over the limit after the latest ecl update.

**Comment by davids5** [comment]
FYI px4fmu-v2 also

**Comment by dagar** [comment]
GCC 4.9 buys us a small amount. Bottle drop and rover_steering_control can go on px4fmu-v1.

**Comment by julianoes** [comment]
@dagar: I think we should go to GCC 5.4.1 because the gdb of 4.9 segfaults trying to read the elf files.
See #5650.

**Comment by davids5** [comment]
Just some added data point:

I have not vetted GCC 5.4.1 on all SoC.

If you use gdb from 4.8.4 with 4.9.3 it works.

**Comment by davids5** [comment]
@julianoes 

Have you ever found the root cause of the 4.9.3 gdb seg fault? I wonder if we have an invalid debug config flag set?

**Comment by julianoes** [comment]
> Have you ever found the root cause of the 4.9.3 gdb seg fault? I wonder if we have an invalid debug config flag set?

I have no idea, sorry.

**Comment by julianoes** [comment]
This is resolved I'd say.
