### ISSUE TITLE
v1.5.0 firmware always failed to load onboard files via qgc

### ISSUE THREAD

**Issue by Duansir** [PX4/Firmware#5664]
The latest firmware v1.5.0 always failed to load onboard files when i used qgroundcontrol，it maybe a bug。Hope someone to test it。

**Comment by nanthony21** [comment]
I get this with 1.4.4 on a pixracer too. "Error: Timeout waiting for ack: Command failed(0)"

**Comment by LorenzMeier** [comment]
I think its actually a QGC bug. It is not supported at this point. Please use the log download menu item to download logs. Reported here: https://github.com/mavlink/qgroundcontrol/issues/4143
