### ISSUE TITLE
Running the px4 app without usb

### ISSUE THREAD

**Issue by anujkumargupta** [PX4/Firmware#5667]
Hi 
I am working on Snapdragon
Can i run the px4 app on snapdragon board using wifi (without USB)

Actually i am running this using usb on FC ./px4 mainapp.config but as soon as i remove my usb the app stop running and communication was lost between QGC and FC.(Fc is also connected with WIFI and can able to ping the device)

Thanks

**Comment by ndepal** [comment]
You should be able to run it by going into the device via SSH. Have you tried that?

**Comment by julianoes** [comment]
@anujkumargupta You can either try to use the autostart as described in the Devguide. Or alternatively, just open a screen session and start it there. It should then survive when you disconnect USB and you can re-attach it later if you need to.

**Comment by narendrakc-path** [comment]
Thanks @julianoes and @ndepal , Your both solutions works perfectly but i tried to going into the device using ssh but for that i need the root id and password but i did not find it any where.

**Comment by mhkabir** [comment]
IIRC "root" and "linaro" (password).
