### ISSUE TITLE
When i compiler firmware by eclipse in the Linux ,could i set a breakpoint or compile a single file?

### ISSUE THREAD

**Issue by xuqintao** [PX4/Firmware#5670]
If you can do this, it will be very efficient。i really need your help .

**Comment by julianoes** [comment]
@xuqintao is this for SITL or debugging on a Pixhawk?

**Comment by xuqintao** [comment]
@julianoes   yes， do you konw can do this?

**Comment by mhkabir** [comment]
@xuqinato Please answer the question about what you're trying to do this for? - 
i. SITL
ii. Debugging on a Pixhawk

**Comment by xuqintao** [comment]
@mhkabir  debugging on a Pixhawk.

**Comment by julianoes** [comment]
There used to be instructions to use the black magic probe for breakpoint or stepping through debugging, see:
https://pixhawk.org/dev/jtag/black_magic_probe
https://pixhawk.org/dev/jtag/start?s[]=arm&s[]=none&s[]=eabi&s[]=gdb
https://pixhawk.org/dev/gdb_cheatsheet?s[]=arm&s[]=none&s[]=eabi&s[]=gdb

**Comment by xuqintao** [comment]
@julianoes  thanks.  Can we open and compile project files by Eclipse in Linux? i can not do that ,and i want to make sure it .

**Comment by julianoes** [comment]
Yes you can use eclipse, try:
https://github.com/PX4/Firmware/blob/master/eclipse.project
https://github.com/PX4/Firmware/blob/master/eclipse.cproject

**Comment by xuqintao** [comment]
@julianoes OK，thank you very much.

**Comment by julianoes** [comment]
@xuqintao no worries.
