### ISSUE TITLE
Default open loop loiter params don't seem right.

### ISSUE THREAD

**Issue by nanthony21** [PX4/Firmware#5676]
The default roll in open loop loiter following a gps failure is 15deg, shouldn't it be 0?
Also 70% thrust seems a bit high to me, depends on the vehicle though.

**Comment by julianoes** [comment]
0 degrees would go straight but loiter should really do a circle, so 15 degrees would make sense.

**Comment by nanthony21** [comment]
![openloopparams](https://cloud.githubusercontent.com/assets/8433487/19599253/88619744-9765-11e6-9479-67461ce32edd.png)

Here's what I have under "GPS FAILURE NAVIGATION" the 70% thrust is at the bottom.

Circling makes sense for fixed wing, but for a multicopter it can cause the vehicle to randomly fly off during a hover or takeoff, which is exactly what I've experienced.

**Comment by dagar** [comment]
The open loop loiter isn't enabled anymore. MC should land immediately with GPS failure.
