### ISSUE TITLE
VTOL: Tailsitter auto land not always working

### ISSUE THREAD

**Issue by applededipan** [PX4/Firmware#5678]
VTOL: Tailsitter: I test the vtol in mission mode these days, the plane sometimes can land on the landing spot, sometimes it can not or just float away, Dose anybody know why?

**Comment by julianoes** [comment]
Could you share a log? Can you comment @CarlOlsson?

**Comment by applededipan** [comment]
ok, i will share logs later. i am wondering that if the position controller work during landing phase?

**Comment by julianoes** [comment]
@applededipan I think the catch is that the roll/pitch is limited during the land phase in order to be level when landing. However, this can have the effect that it drifts off in wind and can't keep up.

**Comment by applededipan** [comment]
I think so! and I find that the position controller and altitude controller are still working during landing, Am I right?

**Comment by applededipan** [comment]
I think so! and I find that the position controller and altitude controller are still working during landing, Am I right? @julianoes

**Comment by julianoes** [comment]
I think so, yes.

**Comment by applededipan** [comment]
as i tune the roll/pitch limit a bit larger, it works better now! thanks for your help!!! @julianoes
