### ISSUE TITLE
Mission: Immediate command triggering after un-pausing

### ISSUE THREAD

**Issue by mswingtra** [PX4/Firmware#5691]
When flying a mission with VTOL, and current active waypoint is either VTOL Takeoff or VTOL Land, if you pause a mission and then un-pause it, aircraft will do transition immediately without regard to the acceptance radius. 

I can imagine this issue will concern any waypoint that contains some command in it. Essentially, this command is triggered right after un-pausing a mission.

**Comment by AndreasAntener** [comment]
Should be fixed with #5614

**Comment by dagar** [comment]
Fixed in #5614
