### ISSUE TITLE
Switch default to ulog

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5692]
@bkueng We need to switch to ulog and log streaming by default to avoid being spread out thin between different logging systems. Could you look into the memory needs of the new logger tomorrow and see if you can squeeze it into the resource constrained platforms?

**Comment by bkueng** [comment]
Will do that. But before switching, it would be nice to have a FlightPlot binary release. @LorenzMeier @AndreasAntener what's the status of https://github.com/PX4/FlightPlot/issues/1?

**Comment by mhkabir** [comment]
@bkueng @LorenzMeier What do you think about this? I think we can completely move over to the new logger?

**Comment by LorenzMeier** [comment]
Done
