### ISSUE TITLE
How to control drones with companion computer?

### ISSUE THREAD

**Issue by zhahaoyu** [PX4/Firmware#5700]
Hi, I would like to add a RPi on on top of the pixhawk FMU I have. I am trying to figure out how to control the drone directly with the RPi. Am I supposed to use MAVlink and override the RC input to control the drone?

**Comment by art-mx** [comment]
Does this help? http://dev.px4.io/pixhawk-companion-computer.html

**Comment by julianoes** [comment]
@zhahaoyu The link should help. For more questions please ask in http://discuss.px4.io/.
