### ISSUE TITLE
The release v1.4.4 has inconsistent commit with the branch v1.4.4

### ISSUE THREAD

**Issue by gaochangyu** [PX4/Firmware#5712]
Hi, all
Today I found that the release v1.4.4 is on commit 60c2aa1 while the brach v1.4.4 has come to commit e73218c. I'm using the code at release v1.4.4 and because of the change in SITL, I don't want to migrate my code to work with higher version.
So, Can somebody explain why the brach v1.4.4 has moved so much forward?

**Comment by dagar** [comment]
We don't usually have branches for each release, I believe it was an error. Please use the v1.4.4 tag instead. 60c2aa165feee1cb421a546670fca1344366839c

**Comment by gaochangyu** [comment]
Thanks!

**Comment by kd0aij** [comment]
This confused me too; I was working on a local branch based off v1.4.4 and
suddenly the diff got very large. I don't see how I could accidentally
create a branch in PX4/Firmware though, since I was working in my own fork.
