### ISSUE TITLE
drivers/vmount: InputRc not initialized in Mavlink mode

### ISSUE THREAD

**Issue by mbraunecker** [PX4/Firmware#5746]
When I only use Rc input (MNT_MODE_IN=1) I am able to control the gimbal.
But setting MNT_MODE_IN=2 and MNT_MAN_CONTROL=1 ignores any Rc input (no ROI set, armed).

I solved it by adding

    if (_manual_control) {
        int ret = _manual_control->initialize();
        if (ret) {
            PX4_ERR("failed to initialize rc input");
            return ret;
        }
    }

to InputMavlinkROI::initialize() and InputMavlinkCmdMount::initialize()

**Comment by LorenzMeier** [comment]
@julianoes @bkueng Can you pull this in?
