### ISSUE TITLE
Mismatched #define in rc_parameter_map.h

### ISSUE THREAD

**Issue by bitblit11** [PX4/Firmware#5748]
uORB/rc_parameter_map.h has a define/static const that defines PARAM_ID_LEN to 16.  However, the rc_parameter_map_s.param_id is 51 bytes in length, not 16.  Suggest changing the 16 to 51, and replacing the hard coded 51 with the macro/static const to ensure the disconnect doesn't occur again.

**Comment by dagar** [comment]
According to the comment it's for 3 params + null termination. 3 * 16 + 3 = 51
https://github.com/PX4/Firmware/blob/master/msg/rc_parameter_map.msg#L6
