### ISSUE TITLE
macosx dependency on Xcode 8

### ISSUE THREAD

**Issue by Ole2mail** [PX4/Firmware#5757]
hello all.
just managed to compile default make for Firmware having Xcode dependency fixed to 6.

any ideas why do we strict to Xcode 8 (the one involving to have AppStore etc?
[xcode6.patch.txt](https://github.com/PX4/Firmware/files/553622/xcode6.patch.txt)
[xcode6-2.patch.txt](https://github.com/PX4/Firmware/files/553667/xcode6-2.patch.txt)

**Comment by LorenzMeier** [comment]
Can you share the output of ```make posix jmavsim```?

**Comment by micheda** [comment]
Hi Lorenz,

same situation here and the patch worked, output of `make posix jmavsim`:
[typescript.txt](https://github.com/PX4/Firmware/files/669130/typescript.txt)

**Comment by julianoes** [comment]
The tests are based on XCode 8 and we don't have the bandwidth to support anything else. Thanks for the patch in case someone else runs in the same issue.
