### ISSUE TITLE
Pixhawk can't recognized in Mac 

### ISSUE THREAD

**Issue by CrazyPopLin** [PX4/Firmware#5770]
I am use Mac to flash new arducopter 3.4_dev into pixhawk, when I upload the new firmware. After it compiled successfully, need to un-plug usb to upload. After un-plug and plugin, it upload fine. Look like below:  
>
50583400 00ac2600 00100000 00ffffff ffffffff ffffffff ffffffff ffffffff d4eb8a56 8fa437f5 c7f321de 77aeb047 9449a6b1 269744a4 10f6e598 fea1c213 7b2c46e3 3ea9585d 80d61d41 187df398 3d9d33c4 f735ce02 3ba83210 2c391284 6f9b6ef5 f32362fe b1b7361c 79c4fcba fd81b0e0 eceb21e0 d5acfcf1 bb6e4ad4 e111eb70 13b767df 774b44db e8bc75bc 7a615be3 8c93429f bc3b7e62 f6109b37 ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff type: PX4
idtype: =00
vid: 000026ac
pid: 00000010
coa: 1OuKVo+kN/XH8yHed66wR5RJprEml0SkEPblmP6hwhN7LEbjPqlYXYDWHUEYffOYPZ0zxPc1zgI7qDIQLDkShG+bbvXzI2L+sbc2HHnE/Lr9gbDg7Osh4NWs/PG7bkrU4RHrcBO3Z993S0Tb6Lx1vHphW+OMk0KfvDt+YvYQmzc=
>
sn: 003d002e3334511632353634
chip: 20016419
>
Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.
> 

After firmware uploaded, Pixhawk LED no flash at all, just nothing. Half hour ago, I can upload and the pixhawk works fine. It just suddenly not work.    
In the **System information**, no usb detected, usually it will display like **PX4 FUM v2.x**.   
When I display the device in terminal, nothing shows. But when I un-plug and plug in again, I can see **/tty.usbmodern1**, it just disappear after maybe 2 seconds.   
I also erase the micro SD, it performance at same. I switch to Windows for mission connection, can't upload firmware always. cause no usb detected.   

Any suggestions will appreciate.

**Comment by LorenzMeier** [comment]
This is the wrong issue tracker for Arducopter.
