### ISSUE TITLE
[-Werror=missing-braces]

### ISSUE THREAD

**Issue by buaayly** [PX4/Firmware#5803]
When I compiled the firmware, I got the error as following, 

/src/modules/uavcan/uavcan_main.cpp:1263:3: error: missing braces around initializer for 'const char* [4]' [-Werror=missing-braces]
compilation terminated due to -Wfatal-errors.
cc1plus.exe: all warnings being treated as errors
make[3]: *** [src/modules/uavcan/CMakeFiles/modules__uavcan.dir/uavcan_main.cpp.obj] Error 1
make[2]: *** [src/modules/uavcan/CMakeFiles/modules__uavcan.dir/all] Error 2

How can I solve this problem?

**Comment by bkueng** [comment]
Can you test  #5805?

**Comment by s3erjaeh** [comment]
I had the same problem. You must update the gcc compiler, this is a bug in gcc. On Windows you simply download the gcc here: https://launchpadlibrarian.net/287101671/gcc-arm-none-eabi-5_4-2016q3-20160926-win32.exe 
After installation you copy the folders bin,lib and share to the px4 Toolchain folder (px4\toolchain) and override the existing gcc compilers. This will fix the issue.

**Comment by buaayly** [comment]
Thanks s3erjaeh! It works!

**Comment by buaayly** [comment]
bkueng.
I updated my gcc, and the problem was solved. So I can not test the #5805 now, sorry.
