### ISSUE TITLE
Manual control lost message without RC connected

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#5807]
Master fw 25be7aa7cf30b633afd1abeb30f15547719f1471
I calibrated airspeed without ever powering on the radio transmitter, constantly got "manual control lost" message in QGC, so maybe this is more a QGC issue

**Comment by LorenzMeier** [comment]
Did you have a joystick connected?

**Comment by CarlOlsson** [comment]
No I did not have a joystick connected

**Comment by bigbellmercy** [comment]
Hi! I am undergoing the similar problem.
In fw v1.4.4 stable, the "manual control lost" happens also.
In fw v1.2 it does not happens when I tested.
It happens more frequently when XBEE modules are connected.
The RSSI value in QGC fluctuates under low value when it happens.

**Comment by bigbellmercy** [comment]
And I suspect the RSSI value is correct because the Futaba RC transceiver send only RC IN signal to Pixhawk. It does not send RSSI info to Pixhawk.

**Comment by julianoes** [comment]
Does it also happen when you set a parameter? RC lost tends to trigger if something takes a long time and the commander has a timeout (and therefore detects an RC loss because the timestamp of the last RC is far back).

**Comment by bigbellmercy** [comment]
It happens all the time when I turn on RC controller irrespective of parameter changing.

**Comment by julianoes** [comment]
@bigbellmercy your issue seems to be different from the one original issue reported here.
Please file a separate issue and describe it in detail.

**Comment by bigbellmercy** [comment]
@julianoes You are right. I solved my problem. The cause was the signal noise in RC IN signal. By twisting the three wires (VCC, GND, RC_IN), it was fixed. The RC IN PWM signal seems to be sensitive to noise because its high data rate. Thanks~

**Comment by julianoes** [comment]
@bigbellmercy thanks for the heads-up, glad it's resolved.
