### ISSUE TITLE
 Graupner GR 16 receiver and sumd protocol

### ISSUE THREAD

**Issue by Benoit3** [PX4/Firmware#5817]
My goal is to fit a small piper cub model with a pixhawk and ArduPlane 3.7.1

I decided to connect the Pixhawk and the GR 16 receiver with the pixhawk DSM interface , the sumd interface and the receiver's setting SUMDOF08.

But the pixhawk stays in failsafe with these settings. I did some check with a GR12L and it was ok.

After some investigations, I found that on power on, the GR 16 receiver was sending frames with failsafe flag on (=> frame are starting with A8h 81h and not A8h 01h for a normal frame) up to the connection establishment with the transmitter. After that if the connection is lost again, sumd frame are not transmitted.

This is not the case on GR12L : there is not sumd frame transmitted between power on an transmitter connection establishment.

After digging into the code I found that sumd frame with falisafe bit on ( beginning with A8h 81h) was not recognized as sumd frame (file sumd.c). I think in this case the algorithm concludes that the sumd protocol is not used and lock on another one : this is the reason of my problem.

After modification of sumd.c , sumd.h and controls.c , it is possible to :

    recognize and decode sumd frame with failsafe bit on
    set or clear the pixhawk failsafe status with this information.

The issue seems to be solved.

Here are the diff of modification done ::

diff original/sumd.h modifie/sumd.h
96a97
>  * @param failsafe pointer to a boolean where the decoded failsafe flag is written back to
105c106
< 			 uint16_t *channels, uint16_t max_chan_count);

---
> 			 uint16_t *channels, bool *failsafe, uint16_t max_chan_count);

diff original/sumd.c modifie/sumd.c
112c112
< int sumd_decode(uint8_t byte, uint8_t *rssi, uint8_t *rx_count, uint16_t *channel_count, uint16_t *channels,

---
> int sumd_decode(uint8_t byte, uint8_t *rssi, uint8_t *rx_count, uint16_t *channel_count, uint16_t *channels, bool *failsafe,
146c146
< 		if (byte == SUMD_ID_SUMD || byte == SUMD_ID_SUMH) {

---
> 		if (byte == SUMD_ID_SUMD || byte == SUMD_ID_FAILSAFE || byte == SUMD_ID_SUMH) {
312a313,315
> 
> 			/* failsafe flag */
> 			*failsafe= ( _rxpacket.status == SUMD_ID_FAILSAFE );

diff original/controls.c modifie/controls.c
136a137
> 	bool sumd_failsafe_flag;
145c146
< 						    &sumd_channel_count, r_raw_rc_values, PX4IO_RC_INPUT_CHANNELS));

---
> 						    &sumd_channel_count,  r_raw_rc_values, &sumd_failsafe_flag, PX4IO_RC_INPUT_CHANNELS));
155c156
< 		r_raw_rc_flags &= ~(PX4IO_P_RAW_RC_FLAGS_FAILSAFE);

---
> 		if (sumd_failsafe_flag) r_raw_rc_flags |= (PX4IO_P_RAW_RC_FLAGS_FAILSAFE); else r_raw_rc_flags &= ~(PX4IO_P_RAW_RC_FLAGS_FAILSAFE);

It seems that files ::
modules/PX4Firmware/unittests/sumd_test.cpp
modules/PX4Firmware/src/drivers/px4fmu/fmu.cpp

may need to be updates as they use sumd_decode() but they are not used to generate pixhawk binaries.

How is possible the modification to be embedded in the master of PX4firmware and later adupilot?

Here are proposal of corrected files for ArduPlane-3.7.1

[controls.c.txt](https://github.com/PX4/Firmware/files/576146/controls.c.txt)
[sumd.c.txt](https://github.com/PX4/Firmware/files/576147/sumd.c.txt)
[sumd.h.txt](https://github.com/PX4/Firmware/files/576149/sumd.h.txt)

**Comment by LorenzMeier** [comment]
Thanks for fixing!
