### ISSUE TITLE
Use LPE estimator to test Auto_takeoff with flow (with GPS off),it will fly over the altitude of set point.

### ISSUE THREAD

**Issue by liaoytal** [PX4/Firmware#5823]
I had a test flight with px4 stable branch 1.4.4 + LPE estimator.
Switching to state MAIN_STATE_AUTO_TAKEOFF to test Auto-takeoff with optical flow(no GPS).
I set the altitude of the takeoff to 0.3m. (min_clearance =0.1m,get_acceptance_radius =0.2m).

The multicopter will fly over altitude of the set point(about 1m) then lower the altitude to 0.3m.

log:
http://logs.uaventure.com/view/SU8fjxdbTHrE2MJyvdBbUg#top

**Comment by jgoppert** [comment]
Auto takeoff is now supported on master. It uses the land detector to estimate the position while the camera is out of focus on the ground. When you takeoff, it then hopefully gets flow data and everything works. If not, it will fallback to failsafe.
