### ISSUE TITLE
VTOL Takeoff weathervane

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#5830]
Allowing VTOL to weathervane seems to be great, but it can be abrupt at takeoff depending on the wind. I think we should only allow it with some altitude.

**Comment by dagar** [comment]
@sanderux @AndreasAntener other than the first few seconds after takeoff and aligning to transition in the desired direction is there any reason we shouldn't have weathervane always on (optionally)? From what I've seen in logs it looks strictly better.

**Comment by sanderux** [comment]
I have no objection to the param, but i would not like to enable it by default. A VTOL that hovers for any other reason than takeoff or land will likely be carrying a camera and heading is quite important for that.

VTOL_TAKEOFF and VTOL_LAND has a weathervane param already. That would only leave a regular transition command suffering from bad behavior after it completes transition and still has too much velocity. Perhaps a param that enables weatervane for the first waypoint after back transition would be an idea.

**Comment by sanderux** [comment]
ref; https://github.com/PX4/Firmware/issues/5306#issuecomment-259250341

**Comment by dagar** [comment]
Disagree on the any other reason part, but yes it would definitely be off by default.

Any thoughts on requiring some altitude first?

**Comment by sanderux** [comment]
I dont see yawing directly after takeoff as a problem. Indeed it shows the user clearly where it will transition towards.

**Comment by dagar** [comment]
The problem is if part of the vehicle is still touching the ground.

**Comment by dagar** [comment]
Current situation seems fine with a bit of user education.
