### ISSUE TITLE
Sense if SiK (3DR Radio) Firmware supports MAVLink 2

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5833]
If the user is using an SiK radio (or other radio) and its Firmware is not recent (how do we tell these radios support MAVLink 2?) PX4 should not announce MAVLink 2 capability through that channel.

**Comment by luqi940101** [comment]
If I am using an SiK radio, which version of the Firmware should I upload to Pixhawk? Thanks.

**Comment by dagar** [comment]
Done?

**Comment by LorenzMeier** [comment]
Should, yes
