### ISSUE TITLE
SERVO_OUTPUT_RAW causes payload size mismatch error in jMavSim

### ISSUE THREAD

**Issue by sytelus** [PX4/Firmware#5837]
As per 1.0 specs there should be 16 servo fields in SERVO_OUTPUT_RAW so that payload size is 37. However PX4 sends message with only 8 servo fields so that payload size is only 21. This cause exception in jMavSim that gets silently ignored because jMavSim validates if payload is 37 bytes.

Further looking in to this, I found that common.xml in MavLink defines the SERVO_OUTPUT_RAW message with <extension/> element. Apparently no other messages use <extension/> element. I tried to find any documentation on what this element means but couldn't locate anything useful. I think jMavSim doesn't handle <extension/> correctly and falsely assumes that all 16 fields must be present.

Can anyone suggest what <extension/> element mean? How should jMavSim handle this?

**Comment by dagar** [comment]
9-16 are extensions (mavlink 2)
https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L2611

**Comment by lovettchris** [comment]
I added support for extensions in jMAVLib, see change [e14581e8c994690607a17450f36dd1f1dea818c1](https://github.com/PX4/jMAVlib/commit/e14581e8c994690607a17450f36dd1f1dea818c1).

**Comment by sytelus** [comment]
closing this was fixed by lovittchris

**Comment by kd0aij** [comment]
@lovettchris Do you need to update the jMAVlib submodule reference in jMAVSim?

**Comment by lovettchris** [comment]
Yes, and I just submitted a push request on jMAVSim to do that.  You can do it yourself by doing this:
cd jMAVlib
git fetch
git checkout e14581e8c994690607a17450f36dd1f1dea818c1
