### ISSUE TITLE
Preflight checking of navigation health is weak

### ISSUE THREAD

**Issue by priseborough** [PX4/Firmware#5842]
Preflight checking does not make use of the EKF health data and dual sensors to detect sensor faults that would lead to loss of flight control after takeoff. The following should be added to PreflightCheck.cpp:

- Check of EKF horizontal and vertical velocity and position innovations.
- Check of EKF yaw innovation
- Check of EKF IMU bias estimates
- Where multiple IMU's are fitted, check for differences between accel and gyro readings

**Comment by priseborough** [comment]
I've created a prototype here: https://github.com/priseborough/Firmware/tree/pr-preFlightChecks

The next step is to enable pre-flight logging via parameter setting and enable adjustment of the thresholds via parameters.

I'm still trying to work out a way of accessing multiple instances of the IMU.

**Comment by priseborough** [comment]
This will need to be reworked to move the processing into the sensors app because the preflight check is one-shot, but we need averaged/filtered values. I've made a start here: https://github.com/priseborough/Firmware/tree/sensorDataValidation-wip

**Comment by LorenzMeier** [comment]
@bkueng Can you support this effort on the comms side? @dogmaphobic We will need your support for visuals in QGC.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Let us know if you have any canned pre-flight check visuals in QGC already we could be using.

**Comment by dogmaphobic** [comment]
I'll talk to Don and see about it. As of now, I have no idea where this would go.

**Comment by AndreasAntener** [comment]
We also had a quick look into this recently, the SYS_STATUS would contain sensor flags based on the enum `MAV_SYS_STATUS_SENSOR` here: https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L399

But AFAIK they are never used/filled in PX4. Then I saw that Don already started pulling those in: https://github.com/mavlink/qgroundcontrol/pull/4206

Would those fields be sufficient to report or does it need more?

**Comment by priseborough** [comment]
I've got it to a point where it is working on the bench (I can change sensor offsets and get it to fail) so have submitted a PR so we can get some review and discusion.

**Comment by priseborough** [comment]
Creating a message that captures the data used for pre-flght checking would enable the same data to be both logged each time the check is run and also sent to the ground.
