### ISSUE TITLE
Protection against fly-aways due to navigation yaw errors is weak

### ISSUE THREAD

**Issue by priseborough** [PX4/Firmware#5843]
An inflight check of velocity and magnetometer innovations is required to check for large yaw errors that at the moment will lead to a fly-away if a hovering type vehicle (eg multi-rotor) is left in a position or velocity control mode.

A typical scenario is takeoff in a multi-rotor wit.h an incorrect compass calibration or orientation

A  check is required to put the vehicle into a non-GPS mode failsafe condition if there is a combined failure of the magnetic yaw and GPS velocity innovation tests.

A 'fail-operative' (as opposed to a fail-safe) behaviour is also achievable. Some possibilities here include:

1) Implementation of a multiple-hypothesis 3-state yaw estimator. States used would be NE velocity and yaw angle. GPS velocity would be used as the observation and IMU data rotated into earth frame using tilt from the main filter and yaw from 3-state filter would be used. This is essentially a 2D implementation of the traditional  velocity aiding technique for attitude estimation. If the main filters innovation test failed, the yaw would be re-initialsed using the estimate from the 3-state filter with the smallest innovations. Eventually all hypothesis would converge onto the same yaw estimate. This technique could also be used to enable operation in high latitude regions where magnetic heading is unreliable.

2) The difference between GPS course over ground angle and inertial course over ground angle could be used to reset the yaw angle. This is significantly simpler to implement than 1) and uses less resources, but does not makes it harder to set statistical confidence levels.

**Comment by stephanbro** [comment]
@priseborough I saw an interesting paper [here](www.mdpi.com/1424-8220/14/11/20008/pdf) where inclination can be used to validate the magnetometers health.

I've implemented something similar in the past using a lookup table, similar to the existing declination table, and comparing it with the current inclination. I could re-create an implementation if you think that could be useful.

**Comment by priseborough** [comment]
It would be useful once the vehicle is in up and away flight, but on the ground and at low altitudes, there can be significant sources of external magnetic anomaly due to steel in building structures and vehicles.

**Comment by stephanbro** [comment]
There are definitely issues with external magnetic fields from the things you mentioned, but also rebar in the ground as well. The previous implementation I mentioned worked well to deal with the low altitudes as well. The resolution of the inclination table would be the same as the declination table, 1 degree increments, so the GPS positioning accuracy can be quite low.

**Comment by priseborough** [comment]
This has been addressed by https://github.com/PX4/Firmware/pull/6750 and https://github.com/PX4/ecl/pull/294
