### ISSUE TITLE
FW takeoff acceptance criteria

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#5848]
I've seen a few different people make this same mistake independently. Plan a full mission with takeoff, waypoints, land. Takeoff manually for some reason and then switch to mission in air and not understand why it's diving to hit the takeoff waypoint. 

@AndreasAntener @LorenzMeier any objection to modifying FW takeoff to accept any altitude > setpoint + acceptance alt? That should allow a regular planned takeoff to still respect the waypoint.

**Comment by LorenzMeier** [comment]
Seems ok, yes.
