### ISSUE TITLE
How to check which Firmware release (version) is flashed on my Pixhawk FC

### ISSUE THREAD

**Issue by aitjellal** [PX4/Firmware#5854]
Dear All,
I need to check which Firmware release (version) is flashed on my Pixhawk FC.
- I can access my Pixhawk using both : Qgroundcontrol and MAVROS
- no NuttShell
best regards

**Comment by julianoes** [comment]
In QGC you should open the mavlink inspector widget and look out for http://mavlink.org/messages/common#AUTOPILOT_VERSION or if you can access mavlink shell using Tools/mavlink_shell.py (instead of QGC), then you can use the command `ver all`.

**Comment by aitjellal** [comment]
Thank you @julianoes ,
I still could not solve the problem:
1 -  Using python script:
I have downloaded the Firmware source and  compiled using CatKin then
when I try to start the python script:  it does not connect. This is what I get. (my pixhawk Baud is set to 921600)
`$ python mavlink_shell.py -b 921600 /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AL01OWID-if00-port0`
` Using MAVLink 1.0`            
`Connecting to MAVLINK...`

it stays like this. 

2 - Using QgroundControl: 
I could not find "AUTOPILOT_VERSION " on the mavlink inspector widget. Here is a screen-shot of my QGC (version 2.7.1)
![inspektor_mavlink](https://cloud.githubusercontent.com/assets/8266764/20281492/01050164-aab1-11e6-91fc-b570782e4d5e.jpg)

**Comment by LorenzMeier** [comment]
Your QGC is hopelessly outdated and so is your PX4 version. Upgrade to PX4 1.4.4 or later and QGC 3.1 or later. The autopilot version field will work then. You can also run `ver all` on the shell.

**Comment by eduardkieser** [comment]
Hi I also need to find out the fw version flashed to my Pixhawk 4, but I suspect that things my have changed somewaht since this solution was posted because I dont see an AUTOPILOT_VERSION message in the mavlink inspector of QGC.

**Comment by HadesGuy** [comment]
Same here. 
Using version  QGC 4.2.4 
Please give some insight. 
Thanks

**Comment by julianoes** [comment]
Please don't necrobump. Create a new issue instead and provide details.
