### ISSUE TITLE
compass calibration error : out of memory.

### ISSUE THREAD

**Issue by haitanyise** [PX4/Firmware#5857]
![image](https://cloud.githubusercontent.com/assets/14901732/20291449/4da614ac-ab21-11e6-8de1-f9b6e5fa8f02.png)
 firmware: v1.5.0  hardware: PX4FMU_V4.
When I use uavcan GPS, compass error of calibration.

**Comment by pavel-kirienko** [comment]
As a quick workaround, you could disable dynamic node ID allocation by setting `UAVCAN_ENABLE` to 1, and assign the node ID of your GNSS receiver manually.

**Comment by LorenzMeier** [comment]
@haitanyise Try again with current master, not the 1.5 RC.

**Comment by haitanyise** [comment]
I tryed the latest master branch today and  found new problems.
1. can't download onboard sd card file.

**Comment by haitanyise** [comment]
I tryed the latest master branch today and  found new problems.
1.Can't download onboard sd card file.
2.Uavcan cannot allocate dynamic ID.
3.Vtol airframe sensors can't calibration properly.
![image](https://cloud.githubusercontent.com/assets/14901732/20430717/e8e094c2-add0-11e6-801b-9848ce8c4e46.png)

**Comment by LorenzMeier** [comment]
We optimised RAM and it should be fine now.
