### ISSUE TITLE
RAM usage on VTOL

### ISSUE THREAD

**Issue by eyeam3** [PX4/Firmware#5867]
I ran into some issues regarding RAM usage when using a VTOL airframe in combination with UAVCAN. If I switch to a generic quadrotor as airframe, I did not have these issues.

Subsequently, a comparison of memory usage on VTOL and multirotor when the UAVCAN is not activated.
Generic VTOL:
```
             total       used       free    largest
Mem:        235872     208096      27776      23872
```
Generic quadrotor:
```
             total       used       free    largest
Mem:        235872     189968      45904      45728
```

**Comment by mhkabir** [comment]
Related : https://github.com/PX4/Firmware/issues/5857

**Comment by dagar** [comment]
@eyeam3 did you run out of memory on VTOL with uavcan? Sorry if this is obvious, but VTOL is always going to use more memory than MC, as it's also running the FW controllers and the VTOL controller.

**Comment by dagar** [comment]
We're actively watching this now. 
https://github.com/PX4/Firmware/issues/7146
