### ISSUE TITLE
Firmware make erro during "running dsdl compiler"

### ISSUE THREAD

**Issue by gjhave** [PX4/Firmware#5874]
Hello guys:
      As the topic and picture below, I need your help! I just clone the code yestoday.

![11](https://cloud.githubusercontent.com/assets/23455362/20415734/33d867fe-ad75-11e6-97cf-bdfca2aa628b.png)

**Comment by dagar** [comment]
Can you retry after a full clean? In my experience building on windows frequently has intermittent problems like this. I recommend you use Ubuntu in Virtualbox or VMWare.

    make distclean
    make px4fmu-v2_default

**Comment by dagar** [comment]
@gjhave Any update?

**Comment by gjhave** [comment]
@dagar  Yes, I tried building in Ubuntu with a VMWare. It works, Thank you for your support！
