### ISSUE TITLE
Can not download sd card file

### ISSUE THREAD

**Issue by haitanyise** [PX4/Firmware#5881]
I tryed the latest master branch yesterday and found new problems.
1.Can't download onboard sd card file.
2.Uavcan cannot allocate dynamic ID.
3.Vtol airframe sensors can't calibration properly.
![image](https://cloud.githubusercontent.com/assets/14901732/20452313/d4dca648-ae41-11e6-8fb3-80e531b0da30.png)

**Comment by dagar** [comment]
1. Can you try the daily build of QGC. It has new log download functionality.
 2. @LorenzMeier @pavel-kirienko Any ideas for this? 

    > Uavcan cannot allocate dynamic ID.

3. Can you provide more information? Any error messages?

**Comment by pavel-kirienko** [comment]
> Uavcan cannot allocate dynamic ID.

I'm not sure what exactly does this mean. Dynamic node ID allocation server is failing to start or what?

**Comment by haitanyise** [comment]
I set  UAVCAN_ENABLE :Dynamic ID/Update, and when pixhawk start, there is no allocation of fixed note ID.
![image](https://cloud.githubusercontent.com/assets/14901732/20637738/4a511902-b3cb-11e6-984d-9b0bda1f2a18.png)
![image](https://cloud.githubusercontent.com/assets/14901732/20637755/aaba570e-b3cb-11e6-9486-622593c0946c.png)
![Uploading image.png…]()

**Comment by haitanyise** [comment]
![image](https://cloud.githubusercontent.com/assets/14901732/20637760/dc584e38-b3cb-11e6-9891-1008fbd91165.png)

**Comment by haitanyise** [comment]
@pavel-kirienko

**Comment by pavel-kirienko** [comment]
I'm not sure what behavior you expected to see. There is no such thing as
allocation of fixed node ID - "fixed" means that allocation is not needed.
PX4 always uses node ID of 1 for itself.
