### ISSUE TITLE
RPi3: high cpu utilisation when auto start

### ISSUE THREAD

**Issue by lhc610github** [PX4/Firmware#5887]
Hi I have successfully running PX4 with Navio2 on RPi3.
Now i have issues with auto starting this program as soon as the RPi3 has booted.:
added the binary execution to rc.local
cd /home/pi && ./px4 px4.config > startup.log
It can successfully start the px4 program, but cpu utilisation is much higher than just start this program from shell or ssh. I couldn’t figure out . Could this be a linux distro problem (emlid RT kernel raspbian) or anything didn’t taken care of in PX4 code.
Thanks in advance.
 ![fig 1](https://files.gitter.im/PX4/Hardware/Jb4h/B_Z_D_1LX4Y8_2_Y_WUZ_NQ.jpg)
fig 1 is auto start PX4 by rc.local
 ![fig 2](https://files.gitter.im/PX4/Hardware/WYsP/S_2F2D_EVXQOU4__16RQ_TX.jpg)
this fig is start PX4 from shell or ssh

**Comment by bkueng** [comment]
I was able to reproduce, use the following line to fix it:
```
cd /home/pi && ./px4 -d px4.config > px4.log
```
Note the `-d` which starts px4 in daemon mode.

I added instructions to the DevGuide in https://github.com/PX4/Devguide/pull/68
