### ISSUE TITLE
Quadcopter (offboard control) never reach Z destination, Quad stays above the desired Z

### ISSUE THREAD

**Issue by aitjellal** [PX4/Firmware#5889]
Dear All,
I have an issue with tunning my Quadcopter PID parameters.
I tried many releases 
( I did not try the 1.5.0 rc and 1.4.4  because with theses releases the Quadcopter crash immediately after takeoff. Not a severe crash. The Quadcopter fly in +Y  and keep flying. I set the desired point xyz=(0, 0, 1)  ).

Quadcopter (offboard control) never reach Z coordinte destination, The quadcopter fly above.
Suppose I set the desired  Z=1.0 m
The quadcopter will fly to 1.30m and stay there and never fly down. Or 
recalibrating ESC ==> The Quadcopter  will fly to 1.15m and stay there and never fly down.

Tunning the ESC Speed-Controller each time a recharge the battery or change the battery  helped a little bit.

Any help on how to solve the problem is appreciated.
best regards.

**Comment by LorenzMeier** [comment]
I think you need to tune your controller, but we can't help with that remotely. Closing.
