### ISSUE TITLE
tune PID parameter

### ISSUE THREAD

**Issue by applededipan** [PX4/Firmware#5894]
i have a six rotor aircraft on hand, the weight is about 10Kg, the wheelbase is about 1680MM, the default pid parameter dose not work well, so can anybody give me some advice about tuning the pid parameter?

**Comment by AlexisTM** [comment]
What do you mean by not working? 

What is the problem? What is the multicopter behavior? Is it too aggressive or drunk copter?

**Comment by ardente** [comment]
哥们。你是哪的呀？你的问法太中式化了 😁

**Comment by julianoes** [comment]
It's always a good idea to share a log and/or video. Otherwise it is very hard to give advice.

(And please stick to English here, thanks).

**Comment by applededipan** [comment]
i see @julianoes

**Comment by applededipan** [comment]
it didn't work well, not "not working", it was  too aggressive, but now it's better. Thanks!!!

**Comment by applededipan** [comment]
it didn't work well, not "not working", it was too aggressive, but now it's better. Thank you!!! @AlexisTM

**Comment by applededipan** [comment]
shandong @ardente

**Comment by AlexisTM** [comment]
@applededipan The log download function (new in last QGroundControl version) allow you to download the log (.px4log file). You upload the log to [Log Muncher](http://logs.uaventure.com/) and it will plot relevant data!

![image](https://cloud.githubusercontent.com/assets/6976744/20659845/7050e764-b546-11e6-883e-70b3222e7251.png)

To tune the PID, you can go in the "tuning section" of qGroundControl. NOTE : Correctly read the informations. I would suggest putting `Roll` & `Pitch Sensitivity` to the right, `Attitude Control Sensitivity` to the left and `Position Control Sensitivity` to the left.

**Comment by AlexisTM** [comment]
@applededipan What are your current parameters (Multicopter Attitude Control) ?

**Comment by LorenzMeier** [comment]
Closing as stale.
