### ISSUE TITLE
Drifting heading with constant pitch/roll (last stable release)

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Firmware#5897]
Dear,

I noticed the heading is drifting when we apply a "constant" pitch to the Pixhawk.

To reproduce : 

* Open qGroundControl
* Connect the Pixhawk
* Go to the "fly" section
* Rotate the pitch or the roll of the Pixhawk, keep it, and you will see the heading drifting.

**Comment by LorenzMeier** [comment]
This does not really exist if your board is calibrated correctly and its sensors are working. We're flying all sorts of boards and none has these issues. Please contact your manufacturer for assistance.

**Comment by AlexisTM** [comment]
Hi,

Thanks for your comment, I recalibrated the Pixhawk and the problem goes away.
