### ISSUE TITLE
Fixedwing: Set SYS_MC_EST param correctly for Fixedwing

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5915]
So that post-flight analysis tools correctly tell you that you used the correct estimator. Should be done in ROMFS/.../fw.defaults

**Comment by bkueng** [comment]
@LorenzMeier I fixed this in pyulog [0], because the parameter is specifically only for Multicopters, as per param description. What do you think?

[0] https://github.com/PX4/pyulog/commit/abcdc4aa38d0732cd9539e039fb0149892f90850
