### ISSUE TITLE
Fixed Wing Offboard Ignores Attitude Setpoint

### ISSUE THREAD

**Issue by aivian** [PX4/Firmware#5927]
The fixed wing controller ignores attitude setpoints in offboard mode. I originally filed this over on mavros, but later found the problem in the px4 firmware (https://github.com/mavlink/mavros/issues/630)

I've tentatively traced it to the fixed-wing attitude controller which generates attitude targets from the manual inputs whenever climb rate control is disabled (line 959, https://github.com/PX4/Firmware/blob/master/src/modules/fw_att_control/fw_att_control_main.cpp)

adding another condition for offboard mode fixes it, but I'm not familiar enough with the controller structure to know if that is likely to introduces problems elsewhere.

Original:
`if (!_vcontrol_mode.flag_control_climb_rate_enabled) {`

With additional condition:
`if (!_vcontrol_mode.flag_control_climb_rate_enabled && !_vcontrol_mode.flag_control_offboard_enabled) {`

**Comment by dagar** [comment]
@fiji3119 FYI

**Comment by dagar** [comment]
That's part of it, but you'll also want to prevent fw_pos_ctrl_l1 from publishing like MC does here - https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L2201

**Comment by aivian** [comment]
Ah, thanks. It did work after only the first few changes, weird. I guess the two setpoints were fighting for the controller's attention.
