### ISSUE TITLE
Altitude estimation error of LPE. In OFFBOARD control with VICON.

### ISSUE THREAD

**Issue by Youngdong-Clark-Son** [PX4/Firmware#5945]
Hi.

I am using the most updated firmware and new to PX4.

I am trying to fly multi-rotor with VICON.

I am sending vicon data with 100hz and the difference between LPE and VICON is negligible.

I checked it and flew a vehicle with setpoint_position and the result is as following.

![kakaotalk_photo_2016-12-03-15-25-45](https://cloud.githubusercontent.com/assets/22541895/20857354/c5d73b82-b96c-11e6-910b-054e87d23e7a.jpeg)

The flight performance was bad due to the big error of 'z'. The position error between LPE and VICON is negligible as I said. But the velocity error is weird especially in 'z'. The velocity plot of VICON was plotted just using the Euler method of VICON data (e. g.  v(k) = (z(k+1)-z(k))/dt ).

The outdoor flight performance was much greater when I did position hold. Something is wrong.

Any idea how to increase the flight performance?

Thanks.

Additionally, attitude data of VICON and mavros.
![kakaotalk_photo_2016-12-03-15-31-44](https://cloud.githubusercontent.com/assets/22541895/20857377/9f936c10-b96d-11e6-8287-37d70d53005a.jpeg)

**Comment by jgoppert** [comment]
It seems that LPE is tracking vicon altitude. Are you sure you are sending the vicon altitude in the correct coordinate frame (NED). It appears that vicon altitude is +Z (which would be beneath the ground).

If this isn't the issue, and you want LPE to track the euler approximation for the velocity more, you could increase the process noise (PN_V). This is the process noise for the equation that d/dt(V) = A. This will make the state more uncertain and the kalman corrections will have more impact.

When changing these values, I would try to carry the vehicle around manually before trying a test flight.

**Comment by Youngdong-Clark-Son** [comment]
Thank @jgoppert for the reply.

Can I ask one more question?

You said the correct coordinate frame of the Vicon is 'NED'. But as you can see the graph of mine, when I sent positive altitude setpoint, the vehicle took off and landed with negative altitude setpoint. Moreover, as shown in [http://dev.px4.io/ros-mavros-offboard.html](url), this setpoint of altitude is also positive for take off. This page said that 

> Even though the px4 flight stack operates in the aerospace NED coordinate frame, mavros translates these coordinates to the standard ENU frame and vice-versa.

Then do I need to send the Vicon data with 'NED' format? I think the problem of now is not for the frame, but for the wrong velocity estimation.

Anyway, I will try to increase the process noise of LPE and post results. Thank you!

**Comment by Youngdong-Clark-Son** [comment]
Thanks to @jgoppert , I succeeded to fly with OFFBOARD. The flight result is as shown. To make FCU follow the velocities of Vicon, I increased the process noise(PN_V) of velocity propagation so that FCU heavily depends on the exact Vicon data.
![img_0170](https://cloud.githubusercontent.com/assets/22541895/20873907/fd2e4984-baef-11e6-9a90-50ebfd829541.JPG)
![img_0171](https://cloud.githubusercontent.com/assets/22541895/20873912/0a9fc48a-baf0-11e6-985e-4750fa0e2b50.JPG)
![img_0172](https://cloud.githubusercontent.com/assets/22541895/20873924/242b94ba-baf0-11e6-9c61-a8e39349eca3.JPG)

  Imu data and Vicon data for attitude are almost same. The position data shows that the flight was very successful though some fluctuation still occurs in 'z'. I think this can be reduced by modulating the position controller gains.

  Still, I wonder why LPE makes messages 'reinit P (0, 0) negative' when I increase PN_V more than 0.6. I am currently using the value of 0.6. But this also makes the same message 'reinit P (0, 0) negative' at first. So I need to reduce it to about 0.4 and increase again to remove warning messages.

  The recommended range of PN_V is from 0(minimum) to 1.0(maximum). As the increased value makes the velocity estimation more accurate, I guess it is better to make PN_V near 1.0.

Thank @jgoppert for the amazing support.

**Comment by weiweikong** [comment]
@Youngdong-Clark-Son @jgoppert  I saw your experiments with VICON and LPE is quite well. 

- Have you ever encountered the situation as shown in following figure

 
![logmuncher](https://cloud.githubusercontent.com/assets/2463397/21315870/14c7968c-c639-11e6-97e5-072571d547cb.png)

As the blue box shown, there is a strange overshoot at the very beginning when I swithed the UAV to OFFBOARD mode. Then the UAV maneuver back to normal.

- Have you ever 
- How did you send the VICION data to PX4? by `mocap` or `vision_pose'
- Did you publish the `set_position` all the time before switching to OFFBOARD mode?


The detail log was uploaded at http://logs.uaventure.com/view/PTMjRcANNg6y5fex4SU8Aj.

**Comment by abdullahmohiuddin** [comment]
Hi @Clark-Youngdong-Son , I was having similar problems specially in X-axis, so I did the same thing as you did, I plotted the euler velocity that I obtained from Position estimation that I get from LPE ( from px4logs). There are some differences. So, if I do what you did with PN_V , I would be relying on Mocap position or LPE position for euler velocity estimation?
