### ISSUE TITLE
Intel Aero tuning

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5955]
@bkueng @MaEtUgR Please run another tuning session on beta / this tag:

https://github.com/PX4/Firmware/releases/tag/v1.5.1rc3

Main areas for improvement (the current performance is already acceptable, but we know we can do better):

- Yaw rate / position tracking is not great
- Roll / pitch tracking could still be a bit better
- Position hold (MPC_POS XY and VEL gains)
- Altitude hold (MPC_POS_Z and VEL_Z gains)

**Comment by LorenzMeier** [comment]
@simonegu FYI - this should fit somehow into Monday if possible.

**Comment by LorenzMeier** [comment]
@lucasdemarchi @lfrodrigues FYI.

**Comment by lfrodrigues** [comment]
@LorenzMeier ?

**Comment by MaEtUgR** [comment]
ok, it's on top of the list

**Comment by bkueng** [comment]
@MaEtUgR @julianoes log files of the test flights are here:
acro + manual: http://logs.px4.io/plot_app?log=6699704e-c84b-454a-8e0c-eb0b199c4e30
manual + position: http://logs.px4.io/plot_app?log=60252e13-2a75-4a18-aa2c-c6babe43d0ae

In general the altitude hold was not good, this is something that needs to be looked at

**Comment by MaEtUgR** [comment]
@LorenzMeier We went out tuning, yaw tracking rate and attitude improved (wasn't tuned last time), roll and pitch tracking was already tuned (gain on maximum value but we increased the rate limit). The position controller does work normally well on the Aero with the biggest problem in my opinion being altitude sags.

While fiddling around with the pos controller to get a better feel for tuning in sitl I found some unexpected behaviour... I'll see if #5971 already fixed it or else it's worth an issue.

**Comment by MaEtUgR** [comment]
The unexpected behaviour I found will be fixed by #5980 .

**Comment by lucasdemarchi** [comment]
> Altitude hold (MPC_POS_Z and VEL_Z gains

Is there a PR with that tuning that I missed?

**Comment by LorenzMeier** [comment]
Reopening until that is in. @MaEtUgR ?

**Comment by MaEtUgR** [comment]
No, there wasn't any change on this gains yet.
If it's not sufficient I and @bkueng maybe need to do another testflight.

**Comment by LorenzMeier** [comment]
As discussed I find the flight performance still underwhelming - that was before @bkueng mounted the tube on the autopilot's pressure line.

**Comment by LorenzMeier** [comment]
And the system load issues will also have contributed to the degradation:
https://github.com/PX4/Firmware/issues/6037

**Comment by LorenzMeier** [comment]
Done
