### ISSUE TITLE
FW auto land switch yaw to wheel controller

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#5970]
Large yaw actuation during FW landing flare.

http://logs.uaventure.com/view/XDxR5X5pVEjYNULpojSQdB

![land2](https://cloud.githubusercontent.com/assets/84712/20872759/3934d320-ba6f-11e6-9dda-a251a1ef1b4e.png)

The main problem is the switch to the wheel controller here - https://github.com/PX4/Firmware/blob/master/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp#L1622
@AndreasAntener @tumbili I think one of you implemented the wheel controller and landing?
How should we solve this? I thought about hiding the switch behind runway takeoff enable, but there are plenty of little planes with steerable landing gear that you might want to hand launch. Should we try to detect touchdown?

The next question is why did the yaw setpoint drop 0 (_target_bearing) instead of maintain yaw?

Reported here - http://discuss.px4.io/t/issues-with-landing-rudder-on-flying-wing/1863/13

**Comment by dagar** [comment]
@AndreasAntener @tumbili @LorenzMeier thoughts on the following
 - enable/disable the wheel controller based on RWTO_TKOFF
 - enable/disable the wheel controller based on a new param
 - try to detect touchdown before enabling (probably more work with testing)

I'll also figure out what happened with the yaw setpoint at flare, which could be the only thing to actually fix here.

**Comment by dagar** [comment]
@Kjkinney reported the issue and is willing to help test solutions.

**Comment by AndreasAntener** [comment]
I had a quick look in the source but couldn't find an obvious reason for the strange yaw setpoint.

**Comment by dagar** [comment]
Reproducible in SITL.

**Comment by dagar** [comment]
The problem here is that it's possible to skip over heading hold, but then in flare the uninitialized _target_bearing is used as the yaw setpoint while the wheel controller is enabled.

![image](https://cloud.githubusercontent.com/assets/84712/22670221/44a0fb04-ec96-11e6-91ae-8cfdc2e9f87f.png)


We can fix this by setting _target_bearing properly, but does heading hold as horizontal distance to the landing waypoint make sense? It seems like progress along the glide slope or simply right before flare would be more appropriate.
