### ISSUE TITLE
Unsupported baro pollrate set to 150Hz in sensor_init.cpp

### ISSUE THREAD

**Issue by sharvashish** [PX4/Firmware#5975]
Hi guys,

In sensor_init.cpp, polling rate of baro is set to 150Hz which is unsupported by MS5611(default max: 40Hz) and BMP280, by: `h_baro.ioctl(SENSORIOCSPOLLRATE, 150);`
This command also returns ERROR, as it is supposed to happen.

Moreover voter timeout for baro needs to be set to a decent value, the way it is done for mag in sensors.cpp by: `_mag.voter.set_timeout(300000);`

**Comment by LorenzMeier** [comment]
Thanks for reporting! The baro voting already got fixed.

**Comment by sharvashish** [comment]
That's great.

**Comment by dagar** [comment]
Fixed?

**Comment by dagar** [comment]
The poll rate is no longer set by sensors. Please reopen if this isn't actually resolved.
