### ISSUE TITLE
X-Plane simulation not working on v1.5.1rc3

### ISSUE THREAD

**Issue by vvranjek** [PX4/Firmware#5976]
Hi,

I wanted to give the latest rc3 a try today and I was unable to get it running with X-Plane 10 simulator. It connects with no problems, but when I want to start the mission/take-off nothing happens. Just like the simulator doesn't receive any data. It was working on v1.5.0, just before I tried the stock v1.5.1rc3. Airframe of choice: HILstar.

Can someone confirm this please?

Cheers

**Comment by vvranjek** [comment]
Just found out, I am not the only one. http://discuss.px4.io/t/xplain-10-and-1-5-1rc1/1794

**Comment by vvranjek** [comment]
Found the solution! qGCS didn't understand the updated mavlink messages properly. Updated qGCS to the latest daily build and it works just fine.

**Comment by dagar** [comment]
Thanks for positing the solution.
