### ISSUE TITLE
Intel Aero: Inspect mag interference

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5978]
It has a big issue with the mag. @jgoppert That explains why LPE is struggling. @lfelipe @lucasdemarchi I checked and we should be using the mag in the GPS. It should not be so influenced by current.

![mag_norm](https://cloud.githubusercontent.com/assets/1208119/20892127/2b7173f8-bb0d-11e6-85f4-cdd9094f31a1.png)

**Comment by LorenzMeier** [comment]
This might be enough to fix it: https://github.com/PX4/Firmware/pull/5979

The proper fix is to use the right priorities in all drivers. But this is the safer, quick option for the release.

**Comment by lucasdemarchi** [comment]
I didn't know start order matters. Isn't there a parameter to select primary compass?

**Comment by LorenzMeier** [comment]
It happens on publication (ORB_PRIO_HIGH). I bet that this is inconsistent in one of the drivers, leading to the result.
