### ISSUE TITLE
PWM_AUX_DISARMED not working

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#5989]
In current 1.5.1 RC3 I set PWM_AUX_DISARMED to 900. After Power-On is done I get a PWM of roughly 1500 on AUX-1 Pin. After arming the RC Signal is passed through. 

MIN_AUX is set to 900 to, MAX_AUX is set to 2000. I assume this is a bug.

**Comment by LorenzMeier** [comment]
Indeed, there was a setup flag missing. Can you try this one?
https://github.com/PX4/Firmware/pull/5990

**Comment by tops4u** [comment]
@LorenzMeier Thanks, I'll try tomorrow.

**Comment by tops4u** [comment]
@LorenzMeier I don't think this made it in 1.5.1 Final? At least this is not fixed there. Is it in the current Master?

**Comment by LorenzMeier** [comment]
I never intended to put it into 1.5.1. You need to test this very branch.

**Comment by tops4u** [comment]
@LorenzMeier Currently I don't have a running Build infrastructure up an running. I assume there is no prebuilt package I can download of this branch (at least I did not figure out on GitHub how to do that).

**Comment by LorenzMeier** [comment]
What autopilot HW are you using?

**Comment by tops4u** [comment]
AUAV-X2 (FMUv2 I think)

**Comment by LorenzMeier** [comment]
For Pixracer:
[nuttx-px4fmu-v4-default.px4.zip](https://github.com/PX4/Firmware/files/637798/nuttx-px4fmu-v4-default.px4.zip)

For Pixhawk / AUAV-X2:
[nuttx-px4fmu-v2-default.px4.zip](https://github.com/PX4/Firmware/files/637799/nuttx-px4fmu-v2-default.px4.zip)

**Comment by tops4u** [comment]
I'll check later today. Thanks for the builds.

**Comment by LorenzMeier** [comment]
Would be great to have your testing on this.

**Comment by tops4u** [comment]
@LorenzMeier Apologies I haven't had time yesterday to test as I'm no professional Pilot (work & family). I should find some time today to test it.

**Comment by LorenzMeier** [comment]
Great, let me know how you go.

**Comment by tops4u** [comment]
@LorenzMeier sorry this does not work. Got a Red-Blue Blinking State. The console showed this: 

> INFO  [init] Mixer: /etc/mixers/hexa_x.main.mix on /dev/pwm_output0 
> INFO  [init] Mixer: /etc/mixers/pass.aux.mix on /dev/pwm_output1 
> ERROR [pwm] PARAM 'PWM_AUX_DISARMED
> ' NAME NOT FOUND

Is there an additional Line Break?

**Comment by LorenzMeier** [comment]
Fixed on master.
