### ISSUE TITLE
New Logger not functioning on Pixhawk mini

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#6004]
running 1.5.1-stable on pixhawk mini
able to arm and fly but no log recorded on sd card
flight: https://youtu.be/CDstI6IEuc0

screenshots of parameter and sd content below

![new_logger](https://cloud.githubusercontent.com/assets/13203106/21021367/05c86914-bd2d-11e6-8656-93ffda4a2d5e.JPG)

![no_log](https://cloud.githubusercontent.com/assets/13203106/21021372/0c96dd52-bd2d-11e6-8bf0-27d6824a30b2.JPG)

**Comment by bkueng** [comment]
Did you flash the px4fmu-v2 target? The `logger` module is not built there because of flash restrictions.

**Comment by kd0aij** [comment]
The fmu-v3 target should work for Pixhawk1 compatibles that have rev3
silicon, and it does have the new logger.
