### ISSUE TITLE
syslink: Unbalanced use of semaphore

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#6005]
@dennisss 

In visiting all semaphore use cases for an upcoming nuttx change I found this:

https://github.com/PX4/Firmware/blame/master/src/modules/syslink/syslink_main.cpp#L423

https://github.com/PX4/Firmware/blame/master/src/modules/syslink/syslink_main.cpp#L143-L145

We should remove it, if not needed or fix it if it is need. Please also indicate if it's use case is a  signal
(cross thread) or a mutex

**Comment by dennisss** [comment]
@davids5 , forgot about that one! It was originally intended as a signal for async acknowledgments similar to the other semaphore in that module. I'm removing the unbalanced one in favor of a better same-thread approach. This issue should close once that's in.
