### ISSUE TITLE
about : batt_smbus,is there any plan to add function? thanks!

### ISSUE THREAD

**Issue by yechenglei** [PX4/Firmware#6007]
Hi, i want to add function , return when no power. Recently，do you add function to smart battery? Have any advice for me？ thanks！

**Comment by LorenzMeier** [comment]
This is in the codebase for over two years. You can use it for common smart battery types.

**Comment by yechenglei** [comment]
thank you , yes ,i can use it ,but the module of smart battery is not added to the boot in the code,and   in upper application layer,Will  more new function  be added to in the future

**Comment by LorenzMeier** [comment]
The 3DR Solo is using it with the PX4 middleware to run a smart battery. Everything is there. You can just use it.
