### ISSUE TITLE
FPV racers: undesirable yaw behavior with internal magnetometer

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#6027]
observed on both v1.5.1rc4 and recent master
![log1_yawissue](https://cloud.githubusercontent.com/assets/2300221/21081045/47f5e1a4-bf7b-11e6-9558-cd08e5cc7c60.png)
http://logs.px4.io/plot_app?log=d3b324da-5504-48ff-b613-e05be010063e

![log2_yawissue](https://cloud.githubusercontent.com/assets/2300221/21081046/4aec70a8-bf7b-11e6-8a8c-edaba38a35e0.png)
http://logs.px4.io/plot_app?log=21664518-008c-48f7-9340-1e3adf34e4aa

**Comment by kd0aij** [comment]
This behavior results from using the internal magnetometer, which develops a 90 degree error in heading at hover thrust levels. With LPE, the effect is immediate: the copter yaws (smoothly) 90 degrees to the left on takeoff. With EKF2, there is a delay (15 to 30 seconds in the above plots), then a much more abrupt yaw reaction, which sometimes exceeds 90 degrees. 

In this Spedix S250AQ, the Pixracer is hardmounted to the power distribution board (using the standard mounting holes) and 6mm standoffs. Longer standoffs could be used, but there would still be a relatively large thrust related error in the mag reading. It may be preferable to just disable the magnetometer for applications not using GPS and external mag.

**Comment by LorenzMeier** [comment]
@kd0aij Here is a short writeup how you probably should solve this for all angles, not just yaw: https://github.com/PX4/Firmware/issues/6029

**Comment by LorenzMeier** [comment]
I'm closing this one as #6029 tracks this already.
