### ISSUE TITLE
Ensure OS and Flight app versions are reported correctly

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6028]
@bkueng We need to ensure that the OS and flight app version is reported correctly in these locations:

  * ```ver all``` on the console
  * via MAVLink
  * via `logger` on http://review.px4.io

The goal is to have a table in our flight reporting tool which allows us to make statements like "NuttX 7.4 has 100 flight hours across all airframes". The related issue for the table is: https://github.com/PX4/flight_review/issues/8

We might need a second table with the flight hours accumulation. Described here: https://github.com/PX4/flight_review/issues/9

**Comment by dagar** [comment]
Done?

**Comment by bkueng** [comment]
Yes, except for the NuttX version. @davids5 ?

**Comment by LorenzMeier** [comment]
Fixed
