### ISSUE TITLE
Intel Aero CPU load & timings

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6037]
@lucasdemarchi @lfelipe The normal timing for PX4 is looking like this:

<img width="844" alt="screen shot 2016-12-12 at 17 49 11" src="https://cloud.githubusercontent.com/assets/1208119/21107912/a0c49442-c093-11e6-8f9a-eecb1bbe3ea5.png">

From this log:
http://review.px4.io/plot_app?log=1253eec0-17f1-4051-b858-dce51b268928

Aero looks quite different:
http://logs.px4.io/plot_app?log=a24d89aa-d930-4894-9c6e-65ae449476ba

<img width="844" alt="screen shot 2016-12-12 at 17 54 00" src="https://cloud.githubusercontent.com/assets/1208119/21108056/045efbb4-c094-11e6-8095-217c18f02cc3.png">

We need to work out what is inducing the load and churn on Aero. Its not the logging subsystem but must be something else.

**Comment by LorenzMeier** [comment]
@bkueng Any creative ideas?

**Comment by LorenzMeier** [comment]
@davids5 Any ideas from your side?

**Comment by bkueng** [comment]
One explanation for the generally high CPU is log streaming, in particular sending of the UART bytes. I asked @davids5, and we need UART TX DMA for this.
I'm not quite sure about the increases, but it could simply be that logging rate increases on arming, meaning more bytes need to be sent.

**Comment by lucasdemarchi** [comment]
@bkueng we need logger disabled by default and the mavlink rate back to the value it was before. So basically I think it's about reverting

**Comment by LorenzMeier** [comment]
@lucasdemarchi Could you do that, connect the mavlink shell and run top? If it drops then back to 60% load we should be fine. If not its something else.

**Comment by davids5** [comment]
@LorenzMeier - I think I would need HW to dig into this.

**Comment by LorenzMeier** [comment]
@lucasdemarchi Did you end up doing that experiment? `top` via MAVLink shell would tell you about the load.

**Comment by lucasdemarchi** [comment]
@LorenzMeier I can do it... when I have the hw again.

**Comment by lucasdemarchi** [comment]
@LorenzMeier running top on nsh doesn't show such high CPU load. It decreases ~5% reverting the patches I mentioned, but it was already on 50% load.  This is bench testing, not actually flying.

**Comment by LorenzMeier** [comment]
Fixed.
