### ISSUE TITLE
Set up Mailgun on Jenkins

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6040]
@AndreasAntener @dagar Can we set up Mailgun (https://www.mailgun.com) on our Jenkins instance? That should resolve the broken email sending and would be quite enabling.

**Comment by dagar** [comment]
Done. 
I'm not sure how noisy jenkins is by default, but I guess we'll see.

**Comment by dagar** [comment]
Not quite, need to add a proper subdomain to use it this way. @LorenzMeier I'll email you the details.

**Comment by LorenzMeier** [comment]
Done!
