### ISSUE TITLE
HIL_CONTROL message not sent in v1.5.2

### ISSUE THREAD

**Issue by mzahana** [PX4/Firmware#6051]
Hi,

I am developing HIL interface with Pixhawk. I have been using v.1.4.4. To use HIL for quadcopter, I set the Quadrotor HIL X airframe from QGC. Then, send the HIL sensor and GPS messages to Pixhawk from the Simulator, VREP. Finally, I get back the HIL_CONTROL message from Pixhawk in order to use for control in the simulator. All worked fine in v1.4.4. When I upgraded to v1.5.2, that didn't work. In MAVLink inspector from QGC, I could neither see the HIL_CONTROL nor HIL_ACTUATOR_CONTROL messages. Is there a different way in v1.5.2 to activate HIL mode in order to get these messages?

Thanks.

**Comment by julianoes** [comment]
Could it be something about whether it's armed or disarmed? There was this change #5987 .

**Comment by mzahana** [comment]
I also tried when the vehicle is armed, but the same issue is there.

**Comment by mzahana** [comment]
For the recent version, v1.5.2, do I need to send a command to px4 to tell it to go into HIL mode?

**Comment by v01d** [comment]
Maybe related to #5976 ?

**Comment by mzahana** [comment]
It is not clear to me what the problem is!

**Comment by v01d** [comment]
I guess it is due to this: https://github.com/PX4/Firmware/commit/010c9e937b23988b222de6a1f714b57690f7742f

**Comment by julianoes** [comment]
@v01d you're right, we adapted the mavlink message because the previous one was used incorrectly.

**Comment by mzahana** [comment]
Does that mean the HIL mode has to be enabled, before the HIL_ACTUAOT_CONTROL is streamed?

**Comment by v01d** [comment]
@mzahana By reading the code it would seem that HIL needs to be enabled by setting the bit MAV_MODE_FLAG_HIL_ENABLED in the "set mode" command. Using mavros I'm not sure who should set this bit. I'm guessing that QGC sets it using the HIL config widget. Since V-Rep is not supported, I wonder if QGC still supports setting this mode. Otherwise, it should be possible to do it manually using mavros tools.

**Comment by LorenzMeier** [comment]
Closing as it got replaced by HIL_ACTUATOR_CONTROL.

**Comment by mzahana** [comment]
Lorenz: could you please confirm whether HIL_ACTUATOR_CONTORL needs to be activated before it is sent or not? 

It was not sent by Pixhawk either!

**Comment by LorenzMeier** [comment]
It's sent if the system is in a HIL config and HIL got enabled.

**Comment by mzahana** [comment]
Thanks. Could you please clarify how to enable HIL  given that it is already in HIL config? Is there some MAVLINK command?

**Comment by mzahana** [comment]
I could get HIL_ACTUATOR_CONTROL in recent firmware (1.5.1+). The vehicle has to be armed before the topic is published. Thanks.
