### ISSUE TITLE
RC_RSSI & Pixracer

### ISSUE THREAD

**Issue by urlu75** [PX4/Firmware#6072]
Hello,

I tried different PX4 firmware and the last one with my pixracer and I was not able to get these parameters : RC_RSSI_PWM_* on QGroundControl (or mission planner) as it is describe here https://pixhawk.org/users/rc_rssi.
When I use the search function for RSSI or RC_RSSI param, empty result.
RSSI is map on channel 12 (PPM RX) and don't fond how to set this up. 

Any idea on what's going on ? Is it an issue or just normal ?

thanks

**Comment by LorenzMeier** [comment]
Right now this is only supported on Pixhawk.

**Comment by urlu75** [comment]
any plan to enhance the RSSI management on pixracer  (RSSI over RC channel) ?
