### ISSUE TITLE
Serial port mapping for FMUv5

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6085]
@davids5 Unless that's already done we should do serial port mapping for FMUv5 - essentially replacing all hardcoded ports where required with a variable and then mapping those per FMUv2/3/4 or v5 as required.

**Comment by LorenzMeier** [comment]
I've started with a list.

**Comment by davids5** [comment]
Where?

**Comment by LorenzMeier** [comment]
On master.
