### ISSUE TITLE
Ensure all CI systems run on arm-none-eabi-gcc 5.4 q3_2016

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6089]
@dagar Since we have now fault logging and generally good in-system instrumentation we should make sure all our CI systems are on GCC 5.4 and we offer instructions for Linux and Mac OS how to install that exact version.

**Comment by dagar** [comment]
Will do once I'm back next week.

**Comment by dagar** [comment]
Updating to gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2

Should we do anything to keep older versions working?

**Comment by dagar** [comment]
Updated to 5.4 here - https://github.com/PX4/Firmware/pull/6183

**Comment by dagar** [comment]
@LorenzMeier builds have been updated to 5.4, but we should probably clarify what's officially supported and if we want to make an effort to keep older GCC working.

**Comment by mcharleb** [comment]
@LorenzMeier My current work is on a Yocto Morty based build using GCC 6.2

**Comment by LorenzMeier** [comment]
Yep, but you're not building NuttX with that.
