### ISSUE TITLE
Fixedwing example code does not compile

### ISSUE THREAD

**Issue by vtran609** [PX4/Firmware#6094]
The fixedwing code in the examples folder does not compile and breaks at the header at the math.hpp and params.h

**Comment by dagar** [comment]
@vtran609 It's not really maintained. Would you like to get it working and then added to the builds so we can keep it working?

**Comment by vtran609** [comment]
I will upload a working version when I get one to work

**Comment by dagar** [comment]
Thanks!

**Comment by dagar** [comment]
Fixed.
