### ISSUE TITLE
sf1xx problem

### ISSUE THREAD

**Issue by lovettchris** [PX4/Firmware#6098]
There is an unconditional "sf1xx start" in rc.sensors, line 314, then there's another sf1xx start in rcS line 659 that is conditional on a non-zero setting of SENS_EN_SF1XX.  So if you set this to something other than zero this second start fails and causes rcS to abort, which results in no mavlink USB connection :-)  We should only have one of these, it makese sense to live in rc.sensors, and the  check for non-zero SENS_EN_SF1XX also makes sense... so I'd recommend we move the rcS code to rc.sensors...

**Comment by LorenzMeier** [comment]
Fixed in 4b99a8f, thanks!

**Comment by lovettchris** [comment]
perfect, thanks!  I see sensor stuff creeping into rcS, what is the guidance on when to use rc.sensors and when not to ?

**Comment by mzahana** [comment]
can this be merged into a stable version that can downloaded by QGC directly?
