### ISSUE TITLE
Baro fail when starting sitl

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/Firmware#6120]
the red message `ERROR [sensors] Baro #0 fail:  STALE!` when starting sitl occurs apart from the changes in `/src/lib/ecl/validation/data_validator_group.cpp` from the following [commit](https://github.com/PX4/ecl/commit/6f78ef408425d5b9bc7e0eaceb1af9e5fd73b424).

As I see it this can come from an introduced bug in the commit OR a faulty simulator baro that doesn't really get validated by the new correct implementation...

**Comment by LorenzMeier** [comment]
I think its because SITL can take longer to initialise. We need to somehow relax things there a bit.

**Comment by bkueng** [comment]
It could also be because there is no noise on the simulated baro. Looking at `listener sensor_baro`, the values are constant before takeoff.

**Comment by julianoes** [comment]
It also happens on landing, and in Gazebo and jMAVSim.

**Comment by LorenzMeier** [comment]
The baro had no simulated noise. So the detection was correct. Fixed here:
https://github.com/PX4/Firmware/pull/6162
