### ISSUE TITLE
PX4 parameter generation generates parameters for the full code

### ISSUE THREAD

**Issue by mazahner** [PX4/Firmware#6121]
Dear PX4 Team

The current Parameter generation scheme generates parameters (in the xml) for the full codebase in Firmware/src.

the relevant parameters are only filtered out when writing to px3_parameters.h/.c 

The parameter generation currently fails in the xml step, if two modules define the same parameter, even though one of them would not be in scope (in the .cmake file)
Is there any intent on making the xml generation more selective based on the scope? Would you accept such a PR?
Best, markus

**Comment by LorenzMeier** [comment]
A PR for this would be fantastic. Certainly something we would like to do.

**Comment by dagar** [comment]
@mazahner are you interested in adding support for this? We could certainly help point you in the right direction and test/review.

**Comment by mazahner** [comment]
I think i have a solution working that works for me, but for testing in the various envionments it would be awesome to get some support. let me create a PR so you can give me some feedback.

**Comment by mazahner** [comment]
PR sent

**Comment by LorenzMeier** [comment]
Thanks! Fixed on master.

**Comment by LorenzMeier** [comment]
@dagar @davids5 This also made the param generation step a lot faster. Will help with CI runs.
