### ISSUE TITLE
External vision problem

### ISSUE THREAD

**Issue by zzzzzq** [PX4/Firmware#6124]
Hi! 
I am using PX4 on a indoor vision project. But it seems that this version of PX4 have some problem with external vision. The orientation and the pose of the multicoptor have nothing with external vision. The orientation is all of the estimation of NED magnetic frame, which is very inaccurate in my case. Can anyone help me......

**Comment by LorenzMeier** [comment]
You need to enable LPE manually in cmake/config/px4fmu-v2_default or (if you have more recent hardware) you can build px4fmu-v3_default and flash it. Then you still need to set the SYS_EST parameter to LPE+attitude estimator Q.
