### ISSUE TITLE
BlockLocalPositionEstimator.cpp contains an unused variable: EST_SRC_TIMEOUT 

### ISSUE THREAD

**Issue by jywilson** [PX4/Firmware#6125]
@jgoppert  @LorenzMeier 

The version of this file in master contains an unused variable on line 12.  We build for Snapdragon with -Wunused-const-variable so this is breaking our build.  

Can you check into this?

Thanks,
Jim W.

**Comment by LorenzMeier** [comment]
Fixed in 54ab5cde2f. Thanks!
