### ISSUE TITLE
Land waypoint does not get executed

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6131]
@julianoes @AndreasAntener Our flight test team reports the land waypoint does not get executed. This is one of the logs:
http://review.px4.io/plot_app?log=caf379c8-5a27-48b7-b6e6-5a70656035d6

**Comment by LorenzMeier** [comment]
<img width="1120" alt="screen shot 2016-12-25 at 21 57 20" src="https://cloud.githubusercontent.com/assets/1208119/21472871/66d38b58-caed-11e6-9e1c-7d2f66d9110d.png">

@DonLakeFlyer I think this report was because of user error. The default value of 50 meters for the land waypoint is confusing users

**Comment by DonLakeFlyer** [comment]
What is Altitude supposed to mean on that command?

**Comment by LorenzMeier** [comment]
The intended target altitude right now. It might require a compound command for multicopters with an approach waypoint and a land location waypoint. The target altitude is important because it tells the vehicle when to expect ground contact (e.g. go slow).

If you come down from 50 meters you don't want to come down with 1 m/s for the full 40 meters. But if you come down with 3 m/s on the ground you're going to hit hard. So what you want is to come down slow the last 10 meters.

This will be less of a concern when all vehicles have distance sensors, but right now they don't.

From a UX perspective you might want to combine two waypoints - the final location and the approach waypoint. And do the same for fixed wing.
