### ISSUE TITLE
dsm.c debugging output

### ISSUE THREAD

**Issue by firwar** [PX4/Firmware#6144]
Line 699 of dsm.c should be "values[i]" not "values[0]" for DSM_DEBUG. 

https://github.com/PX4/Firmware/blob/42093a5ee1822b002783cf8d413e37677642d0e3/src/lib/rc/dsm.c

**Comment by LorenzMeier** [comment]
Thanks! Would you mind sending a Github Pull request?

**Comment by LorenzMeier** [comment]
Fixed in 72eafe7e72.
