### ISSUE TITLE
INT32 param cast failing?

### ISSUE THREAD

**Issue by pickledgator** [PX4/Firmware#6159]
Having some funky problems with int32 parameters that are cast from mavlink to a param getting corrupted. 

[Specifically, param.c](https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/param/param.c#L558-L561):
```
case PARAM_TYPE_INT32:
    params_changed = params_changed || s->val.i != *(int32_t *)val;
    printf("in param.c %f %d\n", *(float *)val, *(int32_t *)val);
    s->val.i = *(int32_t *)val;
    break;
```

The float parameters seem to cast fine, but *(int32_t *)val is not converting float values to ints properly. I'm on OSX 10.12.2 | Apple LLVM version 8.0.0 (clang-800.0.42.1), maybe a clang update broke this?

Console print from above yields:
```>> in param.c 1.000000 1065353216```

**Comment by LorenzMeier** [comment]
Are you aware that the MAVLink spec calls for a binary transfer of the param (not casted value, which looses precision)? What software component is sending the param on the other end?

http://qgroundcontrol.org/mavlink/parameter_protocol

**Comment by pickledgator** [comment]
Thanks Lorenz, using the param union solved it. That was the part that I was missing on the send side.
