### ISSUE TITLE
Need to structure parallel builds on Semaphore better

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6190]
@dagar The build errors we keep getting with Semaphore seem to be a race condition inherent to Docker:
https://github.com/docker/docker/issues/21215

Either the 2016-12-26 image is bad (its the one it was trying to fetch) or we run into a race condition here.

**Comment by dagar** [comment]
It looks like semaphore parallel jobs must be on the same machine. I'll try centralizing the pull in the setup section.

**Comment by dagar** [comment]
Nope, it's the actually docker run. This really limits semaphore's usefulness for us.

**Comment by dagar** [comment]
I've recombined firmware/bootloaders and tests/astyle.

**Comment by dagar** [comment]
I think I'm at an impasse for getting this working on semaphore. I haven't found a way to work around parallel threads with any docker layer overlap, and all of our images now share base layers. This also means no splitting nuttx builds across multiple threads. 

I'll try contacting semaphore support, but I'm not expecting much.

**Comment by dagar** [comment]
Nuttx builds currently split into qgc_firmware and alt_firmware and they're 12-15 minutes each.
https://github.com/PX4/Firmware/blob/master/Makefile#L204

We could try splitting them further.
