### ISSUE TITLE
sensor cal problem with SITL?

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#6207]
Just installed gazebo 7 on Ubuntu 15.10:
seems to start up OK, but won't arm.

"make posix_sitl_default gazebo" 
PREFLIGHT FAIL: ACCELS INCONSISTENT - CHECK CAL

https://gist.github.com/kd0aij/5668c0e2824d416f49626424e24f3343

**Comment by LorenzMeier** [comment]
Yes, this was indeed wrong. I have a fix for you here: https://github.com/PX4/Firmware/pull/6213

Can you test?

**Comment by kd0aij** [comment]
Still get the "accels inconsistent" message with both jmavsim and gazebo7 (tried both posix_sitl_default and posix_sitl_ekf2). Quadcopter flies as expected in jmavsim, but rotors don't spin in gazebo7 even though I'm now able to arm. 

Is this "user error" or does gazebo not like Ubuntu 16.04?

**Comment by dagar** [comment]
I believe this is fixed, I've been using gazebo sitl.
