### ISSUE TITLE
Switching to mission mode from manual in mid-air goes to launch detection in v1.5.2.

### ISSUE THREAD

**Issue by vvranjek** [PX4/Firmware#6211]
Since the update to v1.5.2 i realized this new thing that I am not sure is a feature or a bug...

I fly a FW and use a catapult to launch it. I used to often have manual control during take off (or any time actually) and then switch to mission mode during flight and it would go to the last waypoint. Now when I switch to mission mode it doesn't know that it is in mid-air and switches to "#Launch detection running".

I this some kind of new feature and I have some parameters wrong, or a bug?

**Comment by dagar** [comment]
Can you check your launch detection parameters? https://pixhawk.org/firmware/parameters#launch_detection

If that doesn't explain it please share a log.

**Comment by dagar** [comment]
@vvranjek any update?

**Comment by dagar** [comment]
I'll review this and test as part of https://github.com/PX4/Firmware/pull/6725.

**Comment by LorenzMeier** [comment]
Fixed in PR.
