### ISSUE TITLE
Unreliable wifi connection on pixracer

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#6227]
If I try to connect a device to a Pixracer over wifi the green bar in QGC indicating the status of loaded parameters will not reach 100% so I am not able to configure anything and the connection constantly drops and connects again.
This is with 1.5.3 release and with current master 9178bb73712bf824c41c8deebc632f409b3cfa3a

I have tried with two different Pixracers, two different wifi modules, Iphone, Ipad and Laptop, all with the same results.

However, If I flash [v1.4.4 release](https://github.com/PX4/Firmware/releases/tag/v1.4.4) it seems to work perfectly.

**Comment by LorenzMeier** [comment]
You need to update your QGC version to a recent daily build. Its an incompatibility with the wireless modem.

**Comment by CarlOlsson** [comment]
Yes you are right, now it works on my laptop. I guess the patch will also come in an update soon to QGC for iOS.
