### ISSUE TITLE
LPE: Landing in ALTHOLD mode difficult due to accelerator measurements at touch down

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#6242]
@jgoppert I have a quite soft vibration damping installed to achieve an acceleration noise of about 0.1g - 0.15g in Z-Axis, which seems to work perfectly during flight and gives awesome altitude hold accuracy. But when landing in ALTHOLD, the accelerator measurements are very high (and seem to vibrate) at touch down. As a result the vehicle 'jumps' a bit and would sometimes crash if I do not reduce throttle at once (or use the kill switch).

ACC.Z:

![chart_2](https://cloud.githubusercontent.com/assets/7580193/21607011/a29e059c-d1b3-11e6-92b8-48335bbbb00b.png)

LPOS.Z and LPOS.VZ:

![chart_1](https://cloud.githubusercontent.com/assets/7580193/21607013/a4423a8a-d1b3-11e6-86c1-1a1dd019fef8.png)

I do not want to make the vibration damping harder in my case, but would like to improve the landing experience in ALTHOLD (and POSHOLD). Any idea to make that more stable within LPE? Would it help to introduce a limit on ACC.Z?

**Comment by whyscience** [comment]
what's the tool you use to plot ?

**Comment by ecmnet** [comment]
Not relevant anymore with increased spring constant in damping

**Comment by mhkabir** [comment]
@ecmnet, would to mind sharing a picture of your damping solution? :)

**Comment by ecmnet** [comment]
@mhkabir Nothing special about it. It's a question of the angles and the foam :-)

![damping](https://cloud.githubusercontent.com/assets/7580193/21648074/ff84e886-d29c-11e6-968b-0705a2bb2468.png)


I am still looking for cable wire springs for loads of about 20g.
