### ISSUE TITLE
VTOL Attitude setpoint published twice.

### ISSUE THREAD

**Issue by bartslinger** [PX4/Firmware#6246]
I'm currently digging into the VTOL code and noticed the following:

At this line, the attitude setpoint is published with `publish_att_sp()` (inside some if statements):
https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_att_control_main.cpp#L787

Immediately after the if/else statement, the `publish_att_sp()` is called again:
https://github.com/PX4/Firmware/blob/master/src/modules/vtol_att_control/vtol_att_control_main.cpp#L795

Maybe I missed something, but I think the first call is unnecessary.

**Comment by tumbili** [comment]
@bartslinger Yes, that is correct. I thought this was fixed in master actually, seems I was wrong.
