### ISSUE TITLE
Tailsitter unable to simulation.

### ISSUE THREAD

**Issue by haitanyise** [PX4/Firmware#6249]
when i execute the commander "make posix_sitl_ekf2 gazebo_tailsitter", and switch to mission mode in qgc, the vehicle has no reaction, what happened? someone can help me? thanks.
![image](https://cloud.githubusercontent.com/assets/14901732/21629690/9d768d02-d265-11e6-845c-1fea5f67f3c8.png)

**Comment by mhkabir** [comment]
Is this still and issue?

**Comment by LorenzMeier** [comment]
Fixed.
