### ISSUE TITLE
px4flow is broken in gazebo SITL

### ISSUE THREAD

**Issue by svpcom** [PX4/Firmware#6251]
When I'm using ``make posix_sitl_default gazebo_iris_opt_flow`` and switch to posctl after takeoff, drone accelerates and moving outside of asphalt plane (where it stopping due to ground texture loss).
It seems is something wrong with flow sensor orientation.

http://discuss.px4.io/t/unstable-flight-in-sitl-gazebo-with-optical-flow-sensor

**Comment by jgoppert** [comment]
I've answered this in the discuss thread. Please close this if that solution works for you. It was likely due to an old flow submodule.

**Comment by svpcom** [comment]
It works, thanks!
