### ISSUE TITLE
SITL home altitude

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6274]
I am testing some relative vs absolute altitude mission items but there seems to be an issue with SITL and the absolute altitude. LPE correctly sees 488m altitude but commander only sees 9cm absolute alt.

```
INFO  [local_position_estimator] [lpe] gps init lat  47.40 lon   8.55 alt 488.1 m
INFO  [local_position_estimator] [lpe] baro init 0 m std 7 cm
INFO  [commander] home: 47.3977432, 8.5455942, 0.09
```

Anyone know why?
@dagar @jgoppert @LorenzMeier

**Comment by dagar** [comment]
What was reported over mavlink?

**Comment by sanderux** [comment]
0.09

**Comment by sanderux** [comment]
@dagar to be more specific:

GLOBAL_POSITION_INT.alt: 90 (9cm)
HOME_POSITION.altitude: 90 (9cm)
GPS_RAW_INT.alt: 488 (m)

**Comment by dagar** [comment]
This is LPE publishing global position altitude. Any idea what's happening 

@jgoppert Any idea why LPE isn't using GPS altitude? You can see it with default gazebo iris on master.

    % make posix_sitl_default gazebo_iris

    INFO  [local_position_estimator] [lpe] gps init lat  47.40 lon   8.55 alt **488.1 m**
    INFO  [local_position_estimator] [lpe] baro init 0 m std 7 cm
    INFO  [commander] home: 47.3977432, 8.5455942, **0.10**

	pxh> listener vehicle_gps_position
	TOPIC: vehicle_gps_position #1
	timestamp: 50205987
	lat: 473977420
	lon: 85455937
	alt: 488104
	alt_ellipsoid: 0
	s_variance_m_s:   0.0000
	c_variance_rad:   0.0000
	fix_type: 3
	eph:   1.0000
	epv:   1.0000
	hdop:   0.0000
	vdop:   0.0000
	noise_per_ms: 0
	jamming_indicator: 0
	vel_m_s:   0.0000
	vel_n_m_s:   0.0000
	vel_e_m_s:   0.0000
	vel_d_m_s:   0.0000
	cog_rad:   0.0000
	vel_ned_valid: False
	time_utc_usec: 0
	satellites_used: 10

	pxh> listener vehicle_global_position
	TOPIC: vehicle_global_position #1
	timestamp: 158955349
	time_utc_usec: 0
	lat:  47.3977
	lon:   8.5456
	alt:   0.1093
	delta_lat_lon:   0.0000   0.0000 
	delta_alt:   0.0000
	lat_lon_reset_counter: 0
	alt_reset_counter: 0
	vel_n:  -0.0031
	vel_e:  -0.0014
	vel_d:  -0.0463
	yaw:   1.5427
	eph:   0.3028
	epv:   0.0544
	terrain_alt:   0.1039
	terrain_alt_valid: True
	dead_reckoning: False
	pressure_alt:   0.1544

	pxh> listener home_position
	TOPIC: home_position #1
	timestamp: 3412337
	lat:  47.3977
	lon:   8.5456
	alt:   0.1014
	x:  -0.0004
	y:  -0.0002
	z:   0.0000
	yaw:   1.5752
	direction_x:   0.0000
	direction_y:   0.0000
	direction_z:   0.0000

**Comment by dagar** [comment]
@sanderux have you seen this recently?
