### ISSUE TITLE
Unable to build source code after fetching PR#4792

### ISSUE THREAD

**Issue by aysh-shariff** [PX4/Firmware#6287]
I tried **make submodulesclean**, but the errors persist.

![screenshot from 2017-01-10 09_02_05](https://cloud.githubusercontent.com/assets/23332983/21798279/c80f5672-d713-11e6-8341-fc44ab68d185.png)
![screenshot from 2017-01-10 09_02_15](https://cloud.githubusercontent.com/assets/23332983/21798280/c8106440-d713-11e6-9935-c41255547177.png)

**Comment by mhkabir** [comment]
Run `git clean - dfx`

**Comment by aysh-shariff** [comment]
Doesn't help. Same errors.

**Comment by aysh-shariff** [comment]
![screenshot from 2017-01-10 16 52 38](https://cloud.githubusercontent.com/assets/23332983/21813069/423f03ca-d755-11e6-91d5-cdba21701539.png)
![Uploading Screenshot from 2017-01-10 16:51:54.png…]()

**Comment by aysh-shariff** [comment]
![screenshot from 2017-01-10 16 52 38](https://cloud.githubusercontent.com/assets/23332983/21813101/6847dfc4-d755-11e6-98bf-983247a462c5.png)
![screenshot from 2017-01-10 16 51 54](https://cloud.githubusercontent.com/assets/23332983/21813102/684832c6-d755-11e6-8cbc-c940f93e2285.png)

**Comment by kd0aij** [comment]
what does "git status" show?

**Comment by aysh-shariff** [comment]
nothing to commit, working directory clean

**Comment by kd0aij** [comment]
that's not the full output, is it?

**Comment by aysh-shariff** [comment]
On branch orbit_test
nothing to commit, working directory clean



I fetched PR #4792 and checkedout to orbit_test branch

**Comment by kd0aij** [comment]
then try checking the PR branch out directly

**Comment by aysh-shariff** [comment]
Tat doesnt fix it.

**Comment by kd0aij** [comment]
Strange. That works for me. What might be different about your build environment?

**Comment by aysh-shariff** [comment]
I'm not sure what's wrong. I cloned the latest master.... 
Also, I did try manually copying over the changes but tat doesn't work obviously.

**Comment by kd0aij** [comment]
what are your OS and toolchain versions?

**Comment by aysh-shariff** [comment]
Ubuntu 14.04.1
How do I check the toolchain version ?

**Comment by kd0aij** [comment]
arm-none-eabi-gcc --version
The instructions for installation are here: http://dev.px4.io/starting-installing-linux-boutique.html#toolchain-installation

**Comment by aysh-shariff** [comment]
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977]

**Comment by kd0aij** [comment]
that looks OK. Maybe cmake is different? Mine reports:
```
$ cmake --version
cmake version 3.5.1
```

**Comment by aysh-shariff** [comment]
cmake version 3.2.2

**Comment by aysh-shariff** [comment]
Can tat be a problem ? I am able to build the source code fine except for this PR. Don't want to mess with the build env...

**Comment by kd0aij** [comment]
@dagar This is beyond me, Any ideas what's going on here?

**Comment by dagar** [comment]
How did you pull #4792? It doesn't merge cleanly with master and needs to be rebased (manually), so I'm guessing you're in a bad state. 
@aysh-shariff could you go through the diff in #4792 and manually reapply it to a new branch of off current master? If you're not comfortable doing that I can later tonight.

**Comment by aysh-shariff** [comment]
I guess that's the problem. For manually applying the changes, I did tat for the vehicle_command.msg file but the other file had too many changes. I was short on time so just tried replacing the entire file instead which clearly didn't work.

**Comment by kd0aij** [comment]
@aysh-shariff I though all you did was checkout the branch directly from PX4/Firmware

**Comment by dagar** [comment]
I'll take a look later. The MC position controller should be functionally the same as it was during that PR, but it was refactored, so it's just a matter of finding where the orbit code now belongs.

@aysh-shariff I'll close this issue now and ping you from #4792 once it's rebased and ready to test.

**Comment by aysh-shariff** [comment]
@kd0aij I did tat as well. When tat didn't work I tried manually applying the changes

**Comment by aysh-shariff** [comment]
@dagar Tat would be great! 
Thnx!
