### ISSUE TITLE
autopilot thinks airplane is upside down

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#6288]
When trying to set up a new fixed wing (1.5.3) after calibration the autopilot sometimes thinks it is upside down.
![img_9759](https://cloud.githubusercontent.com/assets/7795133/21799632/583cf60e-d71a-11e6-979e-d2657ecb6cf7.PNG)
However when doing all calibrations the images are displayed correctly for accelerometer and compass and the IMU, external compass orientations are all set correctly. This have happened two times and was fixed by resetting all params to defauls and recalibrating everything and rebooting.

**Comment by kd0aij** [comment]
Can you reproduce this, then check whether the autopilot orientation parameter is corrupted?

**Comment by LorenzMeier** [comment]
Is it possible you got confused when it asked you for the board orientation during the calibration?

**Comment by CarlOlsson** [comment]
No I dubble checked the orientations several times and recalibrated everything with the same results. I also checked every time I calibrated mag and accel that the correct images went green in QGC. If It happens again I will force start the logging over NSH.

**Comment by bartslinger** [comment]
I vaguely remember I had something similar before, but don't know which version that was. I rebooted the pixhawk and re-did the level-horizon calibration and that fixed it for me.

**Comment by CarlOlsson** [comment]
For me it was not possible to do the level horizon calibration since I got a warning message telling me that I had "[excess roll angle](https://github.com/PX4/Firmware/blob/master/src/modules/commander/accelerometer_calibration.cpp#L708)"

**Comment by dagar** [comment]
@CarlOlsson did you ever figure out what was going on here? There's not much to go on. I've personally never seen this.

**Comment by dagar** [comment]
If you're able to reproduce please open a new issue with logging. Unfortunately there's not much to go on here.

**Comment by dagar** [comment]
@tjbordelon can you open a new issue describing your setup and upload a log?
