### ISSUE TITLE
Remove mixer offsets or add documentation for TBS Caipirinha

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#6289]
Following up the discussion [here](http://discuss.px4.io/t/servos-not-at-1500us-in-manual-mode/2148/2)

For a user it is not obvious why there is an offset pre-prgrammed into the mixer file of the TBS Caipirinha.

**Comment by LorenzMeier** [comment]
Feel free to propose a new PR with a default tune and setup for the caipirinha. This was done do account for the off-center elevons it has by default, but we might know better by now.
