### ISSUE TITLE
PWM_MIN vs PWM_AUX_MIN?

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#6291]
Is it intended to have both [PWM_MIN](https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensor_params.c#L3233) and [PWM_AUX_MIN](https://github.com/PX4/Firmware/blob/master/src/modules/sensors/sensor_params.c#L3288) parameters?
In that case we should update the description because it says the same

**Comment by LorenzMeier** [comment]
Thanks. Description fixed in a890247.
