### ISSUE TITLE
PX4 simulator kills all processes which contain 'px4' in name

### ISSUE THREAD

**Issue by jdzerve** [PX4/Firmware#6310]
There is a very appalling multiple instance detection built in px4 simulator.
It contains command "pgrep px4 && pkill px4"
This effectively kills all processes which happen to have 'px4' in their name.
simple solution would be to add anchors:
pkill '^px4$' so that it would match only 'px4' and not 'apx44'
Of course more sophisticated lock file based scheme would be much nicer.

**Comment by dagar** [comment]
Thanks @jdzerve . Could you open a pull request that fixes it to your liking?
https://github.com/PX4/Firmware/blob/master/Tools/sitl_run.sh#L61
It needs to work on OSX and Linux.

**Comment by jdzerve** [comment]
Created Pull request for this: https://github.com/PX4/Firmware/pull/6319
