### ISSUE TITLE
ADC_5V_RAIL_SENSE board_config.h need to provide R divider for scaling.

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#6325]
@LorenzMeier - in /src/drivers/stm32/adc/adc.cpp

What is the background here?
On V2 HW  VDD_5V_IN that is divided with 10K and 10K?
The comment says  2:1 - that makes sense.

But why is 6.6 is used as the full scale value on the  VDD_5V_IN?

```
	// it is 2:1 scaled
	system_power.voltage5V_v = _samples[i].am_data * (6.6f / 4096);
```

**Comment by davids5** [comment]
For FMUv5 HW adc.cpp needs to use ADC_SCALED_V5 ad the sense.

**Comment by LorenzMeier** [comment]
Because the HW uses 6.6V as input range.
