### ISSUE TITLE
Flow out-of-focus takeoff support

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6347]
Current discussion state:

- Report flow as valid or special mode if landed (if flow data is coming in)
- Report sonar / altimeter as zero if landed (if altimeter data is coming in)
- Once non-landed time-out after 2-3 seconds if either flow or sonar / altimeter do not become valid
- Ensure position controller goes into failsafe if timing out
- Takeoff should takeoff action, not user-driven altitude (so the system clears the minimum altitude quickly)

**Comment by LorenzMeier** [comment]
@ChristophTobler @priseborough @tumbili

**Comment by ChristophTobler** [comment]
About flow failsafe: 
* In the simulation it does switch to ```WARN  [commander] failsafe mode on``` after not getting valid measurements (fly outside of asphalt) after a few seconds. But then it just switches to altitude mode (obviously it can not return when it does not have a position information). I guess it should handle that case by just landing?
* Do what is mentioned above. Then there seems to be a bug when returning to the asphalt manually. It does not always switch back to ```WARN  [commander] failsafe mode off```

**Comment by LorenzMeier** [comment]
Yep, we should add auto-land as an option instead of falling back to manual and we should find and fix the issue which is not making it return.

**Comment by mhkabir** [comment]
@jgoppert You will be interested in this. We should also consolidate the hack in LPE which we currently use to do the out-of-focus takeoffs.

**Comment by jgoppert** [comment]
Any reason not to implement a fake landing measurement like LPE does. This gives agl = 0, vx=0, vy=0 when landed. During takeoff the measurement goes away and the vehicle is in the air. Then the covariance matrix for x, y is growing. If it gets too large it publishes that position is invalid. So you get a timeout that is adaptive based on the measurements that you have. I think this is the best option.

**Comment by jgoppert** [comment]
@priseborough That change looks reasonable to me. The only other thing you might want to do is add a measurement of agl = 0 to keep the terrain state and altitude state the same.

**Comment by priseborough** [comment]
What I did with the APM implementation was add a parameter which was the expected on-ground range measurement. In the absence of range data it would use the expected on-ground value if not in-air. This allowed for the variation in landing gear height between copters.

**Comment by jgoppert** [comment]
I think both estimators have working solutions for this now.

**Comment by mhkabir** [comment]
I'm not sure if this is solved. @ChristophTobler?

**Comment by ChristophTobler** [comment]
Yes, this is solved. Thanks
