### ISSUE TITLE
Dronekit driven CI

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6361]
We need to enable Dronekit driven CI (we have a baseline, it needs completion). Most notably:

  * Add the comparison of ground-truth and estimated vehicle attitude and position
  * Add trajectory checking
  * Once that is in, add more complex missions
  * Add command to run all this on a local machine

**Comment by sanderux** [comment]
@dagar, perhaps easiest to port this script to dronekit:
https://github.com/PX4/Firmware/blob/master/integrationtests/python_src/px4_it/mavros/mission_test.py

**Comment by dagar** [comment]
Going with Dronecore instead.
