### ISSUE TITLE
Altitude loss in back transition results in overshoot

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6367]
![image](https://cloud.githubusercontent.com/assets/14801663/22031569/4cb77454-dce1-11e6-8b57-2ca3f5facb56.png)

**Comment by dagar** [comment]
Full log?
Is 15 seconds your back transition timeout?

**Comment by sanderux** [comment]
The problem is narrowing down to likely be this: https://github.com/PX4/Firmware/pull/5980
The vehicle lost a lot of altitude during backtrans due to difference in level quad/plane
![image](https://cloud.githubusercontent.com/assets/14801663/22037540/dbcb19c8-dcf7-11e6-9866-bb36f78c9d18.png)

Log: http://logs.uaventure.com/view/B5wvQbkXPAmDKpZJ49qGei

**Comment by dagar** [comment]
The better solution is update the VTOL architecture to use fw_pos_ctrl to maintain altitude during back transition. With what we currently have you should try changing the pitch setpoint during back transition to be FW_PSP_OFF and don't reset the fw_att integrators at transition.
