### ISSUE TITLE
EKF2 performance poor in gazebo SITL with GPS

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#6388]
Here is a 3-way comparison on master of EKF2, IEKF, and LPE for a SITL box mission with varying altitude. EKF2 fails on the first turn even before the climb. I think we might want to add an EKF2 multirotor test mission. I know the original thinking was that it was some server cpu limitation, but I can't get it to work locally either.

Maybe EKF2 could benefit from some noise tuning for SITL. For IEKF, I used [Allan variance plots](https://github.com/jgoppert/iekf_analysis/blob/master/SITL%20Noise%20Identification.ipynb)  for SITL and a [pixhawk](https://github.com/jgoppert/iekf_analysis/blob/master/Pixhawk%20Noise%20Identification.ipynb) for real life and really got great results. LPE is just using the same gains found manually from  flight testing.

EKF2: http://logs.px4.io/plot_app?log=bd702929-6e9c-452f-b2b3-398e53c9cfb3

![image](https://cloud.githubusercontent.com/assets/473772/22097165/a2080984-dded-11e6-9515-ff3ea03303aa.png)

IEKF: http://logs.px4.io/plot_app?log=6c99fd56-0863-4e24-bf72-6b67adb27392

![image](https://cloud.githubusercontent.com/assets/473772/22097178/b363f47c-dded-11e6-8531-b1775b9b9f44.png)

LPE: http://logs.px4.io/plot_app?log=3fbb051c-aeb8-44af-bff3-459c4e771fb1

![image](https://cloud.githubusercontent.com/assets/473772/22097187/bfcb04bc-dded-11e6-8ab6-16fbadb88216.png)

**Comment by tumbili** [comment]
@jgoppert What kind of gps delay are you using in your tests and do we know the delay that is added in gazebo? I remember that I once opened an issue because gazebo did not delay the gps signal.

**Comment by jgoppert** [comment]
Yes, that is true. Currently sitl gps is undelayed and has no noise. We should look into fixing that.  Shouldn't be too hard.

**Comment by jgoppert** [comment]
Yes, that is true. Currently sitl gps is undelayed and has no noise. We should look into fixing that.  Shouldn't be too hard.

**Comment by jgoppert** [comment]
I add GPS delay and noise to sim here: https://github.com/PX4/sitl_gazebo/pull/82

**Comment by jgoppert** [comment]
Resolved.
