### ISSUE TITLE
`make posix_sitl_default gazebo_tailsitter`, Error opening commands file

### ISSUE THREAD

**Issue by gbmhunter** [PX4/Firmware#6390]
On running the command `make posix_sitl_default gazebo_tailsitter` (as detailed at the bottom of https://dev.px4.io/simulation-gazebo.html) on the master branch, I get the following error:
````
commands file: /home/gbmhunter/src_master/Firmware/posix-configs/SITL/init/lpe/tailsitter
ERROR [Unknown] Error opening commands file, does not exist: /home/gbmhunter/src_master/Firmware/posix-configs/SITL/init/lpe/tailsitter
````

**Comment by dagar** [comment]
I'll fix this, but for now try `make posix_sitl_ekf2 gazebo_tailsitter`.

**Comment by LorenzMeier** [comment]
We use EKF2 by default now.
