### ISSUE TITLE
NuttX config maintenance

### ISSUE THREAD

**Issue by lucasdemarchi** [PX4/Firmware#6398]
I asked this on gitter some time ago with not responses and today we were bit by it with the aerofc board.
See https://github.com/PX4/Firmware/pull/6397 

How are the nuttx configuration files for the different boards maintained?

I thought the `reconfigure_nuttx_*` target was supposed to do that, but it doesn't work. Removing the call to "make oldconfig" works, but it produces a configuration so different that I wonder if this is really the way you are doing it.

And talking about different configuration, if I do this it would contain the fix from the PR above, but just because that's the default value for that entry.

Trying for another board like px4fmu-v2 didn't help: lots of difference from what's in tree.

**Comment by lucasdemarchi** [comment]
@davids5 @LorenzMeier see above

**Comment by davids5** [comment]
See https://github.com/PX4/Firmware/pull/6397#issuecomment-273943550 for directions.
