### ISSUE TITLE
Mavlink messages do not get relayed to GCS

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6404]
It seems when sending a mavlink statustext message from a board computer PX4 does not relay the message to the ground station. The question is if this should be implemented and how.

Considerations would be the use of a target_system and default behavior when such an ID is omitted.

In dronekit i tried:
```
msg = vehicle.message_factory.statustext_encode(6,"Test message")
vehicle.send_mavlink(msg)
```
I also tried
```
vehicle._master.mav.statustext_send(6,"Test message")
```
Neither works

**Comment by AndreasAntener** [comment]
Did you try setting the forwarding flag `-f` on the mavlink instance that has telemetry attached?

**Comment by sanderux** [comment]
The is no active management on that side, it's just relaying serial to UDP

**Comment by AndreasAntener** [comment]
I'm not sure what you are saying. How does the setup look?

**Comment by sanderux** [comment]
I'll pm you

**Comment by mhkabir** [comment]
Closing as devcall discussion indicated that this is not an issue.
