### ISSUE TITLE
ESC can't start

### ISSUE THREAD

**Issue by sunshine-yan** [PX4/Firmware#6415]
Hi,
ESC can't start. I have tried to replace the "snapdragm_pwm_out start -d /dev/tty-2" with "uart_esc start -D /dev/tty-2". However,ESC still can't start. Is snapdragm_pwm_out about the ESC starting? 
The situation is as follows：
![pf4gfk5a g2uci fwwjcmg](https://cloud.githubusercontent.com/assets/13762974/22181811/19e0ee38-e0cf-11e6-9601-3e5f8e0f3d57.png)

**Comment by LorenzMeier** [comment]
@jywilson @bharath374 @mcharleb Advice?

**Comment by sunshine-yan** [comment]
@LorenzMeier This is the ESC:
![9ihcvo fi8m uxdihccsvjq](https://cloud.githubusercontent.com/assets/13762974/22182261/faf1ab0e-e0db-11e6-9459-243d71571f12.png)

**Comment by mhkabir** [comment]
Closing in favour of https://github.com/PX4/Firmware/issues/6962
