### ISSUE TITLE
EKF2 - GPS fusion fault?

### ISSUE THREAD

**Issue by pfkrp** [PX4/Firmware#6443]
Hi guys,
after a few days of testing EKF2 something odd happened. While executing some simple mission, just after take off, my copter started to run away. At first I thought that I made something wrong during mission planning because it seemed as if the copter began heading in the direction of second WP, but it accelerated and passed the WP about 8m from that. I took over control but it was too late and it had hard landing. I have examined the log and don't know what to think of it. In estimator_status there were several GPS glitches reported, problems with velocity and position estimates. No filter_fault_flags, no gps_check_fail_flags. Seems that the estimator 'knew' that something was wrong but did nothing about it. 
A few days later I was testing again. Everything was okay, but after approx 5 flights the same happened. Both logs look the same, there is a huge drift of estimated position. From what I observed I can say that GPS position and GPS velocity (up to 12m/s despite MPC_XY_VEL_MAX = 1m/s) where correct. 
The issue seems to be similar to [#6388](https://github.com/PX4/Firmware/issues/6388) but in real flights, not in SITL. 
I cannot upload whole logs due to some agreements that I'm involved in but I'd just like to report the strange behaviour and release the brain storm.

**FIRST FLIGHT**
![10](https://cloud.githubusercontent.com/assets/25376455/22353063/0480fe86-e41f-11e6-8a65-7b408f740ae3.png)
![11](https://cloud.githubusercontent.com/assets/25376455/22353086/1e482aa6-e41f-11e6-9832-a9d35fd22626.png)
![12](https://cloud.githubusercontent.com/assets/25376455/22353089/209ff87e-e41f-11e6-9f12-8809829eefde.png)
![13](https://cloud.githubusercontent.com/assets/25376455/22353092/24de10ec-e41f-11e6-9b78-9e5f7debccc8.png)
![14](https://cloud.githubusercontent.com/assets/25376455/22353095/28d8243a-e41f-11e6-8a5f-b88f2a5d7d79.png)
![15](https://cloud.githubusercontent.com/assets/25376455/22353097/2d12de46-e41f-11e6-929e-08b6d66ef1a1.png)
![16](https://cloud.githubusercontent.com/assets/25376455/22353104/32faeaba-e41f-11e6-98ca-9eaaa881cdf6.png)
![17](https://cloud.githubusercontent.com/assets/25376455/22353108/35a6c41e-e41f-11e6-8b16-c3e0f98ddee4.png)
![18](https://cloud.githubusercontent.com/assets/25376455/22353111/38ea4592-e41f-11e6-9a69-231fb1a6a2a6.png)
![19](https://cloud.githubusercontent.com/assets/25376455/22353112/3bae7f32-e41f-11e6-9e10-52f05f9da660.png)
![110](https://cloud.githubusercontent.com/assets/25376455/22353143/5c27b562-e41f-11e6-9c0c-d664841625e7.png)
![111](https://cloud.githubusercontent.com/assets/25376455/22353145/5fa35db8-e41f-11e6-8909-c6443f7528b0.png)
![112](https://cloud.githubusercontent.com/assets/25376455/22353150/621fd5bc-e41f-11e6-9302-d14003e322b5.png)
![113](https://cloud.githubusercontent.com/assets/25376455/22353151/64422b88-e41f-11e6-9760-7666226d7494.png)
![114](https://cloud.githubusercontent.com/assets/25376455/22353454/daab89e4-e420-11e6-90d2-57607e0532ac.png)
![115](https://cloud.githubusercontent.com/assets/25376455/22353156/6bf0cf42-e41f-11e6-8a4d-8acc24b95a84.png)
![116](https://cloud.githubusercontent.com/assets/25376455/22353159/6e60fb9e-e41f-11e6-8cf8-b23f381941db.png)
![117](https://cloud.githubusercontent.com/assets/25376455/22353160/705d5d5c-e41f-11e6-99c6-a45f4482f96f.png)
![118](https://cloud.githubusercontent.com/assets/25376455/22353161/7230c420-e41f-11e6-9f3e-d368d7cdf79c.png)
![119](https://cloud.githubusercontent.com/assets/25376455/22353164/74178742-e41f-11e6-8158-6fa3c29011e4.png)
![120](https://cloud.githubusercontent.com/assets/25376455/22353166/76445c3e-e41f-11e6-8942-d788178313b5.png)
![121](https://cloud.githubusercontent.com/assets/25376455/22353168/7859bfe6-e41f-11e6-9276-b323a864c351.png)
![122](https://cloud.githubusercontent.com/assets/25376455/22353169/7a4b060c-e41f-11e6-9282-590880986d26.png)
![123](https://cloud.githubusercontent.com/assets/25376455/22353172/7c80ebc6-e41f-11e6-870d-d897fcfa0af7.png)
![124](https://cloud.githubusercontent.com/assets/25376455/22353174/7e8df0e4-e41f-11e6-9508-001a54f340dd.png)
![125](https://cloud.githubusercontent.com/assets/25376455/22353176/80d3da76-e41f-11e6-95ca-8525eeac5853.png)

**SECOND FLIGHT**
![20](https://cloud.githubusercontent.com/assets/25376455/22353269/fbcb1212-e41f-11e6-8792-a72247b944db.png)
![21](https://cloud.githubusercontent.com/assets/25376455/22353273/feb78230-e41f-11e6-9c54-c753ac192531.png)
![22](https://cloud.githubusercontent.com/assets/25376455/22353523/3739a61e-e421-11e6-853c-0b192865a452.png)
![23](https://cloud.githubusercontent.com/assets/25376455/22353281/0431691a-e420-11e6-9331-8542b1760186.png)
![24](https://cloud.githubusercontent.com/assets/25376455/22353283/0784c918-e420-11e6-9c25-3df92e30c06d.png)
![25](https://cloud.githubusercontent.com/assets/25376455/22353286/0b81994c-e420-11e6-842b-f374ca40abf6.png)
![26](https://cloud.githubusercontent.com/assets/25376455/22353285/0b63192c-e420-11e6-9388-ec428e8d6688.png)
![27](https://cloud.githubusercontent.com/assets/25376455/22353291/15ccca34-e420-11e6-9322-ca1764989e08.png)
![28](https://cloud.githubusercontent.com/assets/25376455/22353295/1921876a-e420-11e6-8f1f-20ad30563523.png)
![29](https://cloud.githubusercontent.com/assets/25376455/22353298/1b379b66-e420-11e6-8bdd-61ac90bddf35.png)
![210](https://cloud.githubusercontent.com/assets/25376455/22353324/320c2abe-e420-11e6-85ba-f4b6780ad87e.png)
![211](https://cloud.githubusercontent.com/assets/25376455/22353331/356b0b30-e420-11e6-91b8-e7e825610d8f.png)
![212](https://cloud.githubusercontent.com/assets/25376455/22353334/3711d766-e420-11e6-8184-6ef1fe0863ca.png)
![213](https://cloud.githubusercontent.com/assets/25376455/22353529/3f596cf8-e421-11e6-899f-a4f2afbdf994.png)
![214](https://cloud.githubusercontent.com/assets/25376455/22353340/3ad8c3d2-e420-11e6-99ab-a9560a2f317e.png)
![215](https://cloud.githubusercontent.com/assets/25376455/22353343/3c50ddbc-e420-11e6-8271-1d97d398c2e2.png)
![216](https://cloud.githubusercontent.com/assets/25376455/22353345/3dd914d8-e420-11e6-8c49-6c4ccf80b10b.png)
![217](https://cloud.githubusercontent.com/assets/25376455/22353348/3f6b1292-e420-11e6-970e-9d74f3ce094f.png)
![218](https://cloud.githubusercontent.com/assets/25376455/22353349/40e4393c-e420-11e6-9d76-d66739556615.png)
![219](https://cloud.githubusercontent.com/assets/25376455/22353352/42e16638-e420-11e6-8a18-ebfbcfc67907.png)
![220](https://cloud.githubusercontent.com/assets/25376455/22353354/44e5778a-e420-11e6-8551-e8ceae29cfc6.png)
![221](https://cloud.githubusercontent.com/assets/25376455/22353355/46e71aa2-e420-11e6-96ba-19904d666903.png)
![222](https://cloud.githubusercontent.com/assets/25376455/22353357/487afc8a-e420-11e6-9282-028f332e79b8.png)
![223](https://cloud.githubusercontent.com/assets/25376455/22353360/4a49edbe-e420-11e6-8b19-5870e506079a.png)
![224](https://cloud.githubusercontent.com/assets/25376455/22353362/4c6ea8b4-e420-11e6-8b42-d42db6e0e9b8.png)
![225](https://cloud.githubusercontent.com/assets/25376455/22353365/4e6edad0-e420-11e6-8c9f-a46fd5f9e7a7.png)

**Comment by tumbili** [comment]
@pfkrp Could you please add plots of the estimator innovations?
It's this topic https://github.com/PX4/Firmware/blob/master/msg/ekf2_innovations.msg

**Comment by bkueng** [comment]
Here's a recent log from our flight test people where something similar happened: http://logs.px4.io/plot_app?log=4fa1b2b4-8b19-4f77-815b-81fb8855834c

**Comment by priseborough** [comment]
I can't do ekf analysis based on screen shots, please provide the log file.

**Comment by pfkrp** [comment]
@tumbili @priseborough Could you please email me on pfkrp0@gmail.com ?

**Comment by pkocmoud** [comment]
While bench testing sitting still with GPS connected a Pixracer several days ago, I watched the ship icon drift considerably in a straight line on the QGC map. After a couple seconds, It jumped instantly back to where it started and I saw "EKF GPS fusion timeout - reset to GPS" warning. Not sure it is related but I thought it was odd. If you think this is related, I can spend more time seeking this condition?

**Comment by tumbili** [comment]
@pkocmoud You wouldn't have a log of that would you?

**Comment by Antiheavy** [comment]
I've seen a similar issue on several occasions and marked it up to bad GPS.  All I can provide is a few anecdotes that may or may-not be helpful:

1) Had an aircraft with a Pixracer and a very-very cheap "ublox m8n" (likely a knock-off) GPS/Mag.  On several occasions the aircraft position on the Qgc map would jump around and looked a lot like the first x-y plot shown at the top of this thread.  It "seemed" like it had a very good GPS position with lots of sats. This same aircraft had flown dozens of times previously without issue.  After a couple outings where this was happening the cheap GPS was replaced with a much better MRO brand M8N unit and never saw the issue again on that aircraft (replaced the wires to the GPS too).

2) Had a different aircraft, again with a Pixracer and MRO M8N GPS.  Aircraft had previously flow great then one day starting behaving very badly with position and heading jumping all over the place.  Discovered that the wires going to the GPS/Mag had been damaged and may have been shorting on a metal screw.  Not sure if the GPS or Mag wires were the ones shorting or what was going on exactly.  Replaced the wires and haven't seen the issue again on that aircraft.

3) I've seen drift like this when set up on a bench inside and I have a very poor in-and-out GPS lock.

**Comment by brdgtannj** [comment]
@pfkrp I've been noticing the same issues!  What version of the PX4 firmware have you been using?  Mine only started doing this recently, so I'm wondering if it had something to do with when I merged the newest commits from Master.  I'm going to do a couple of builds to test this out, but my last big update was from Jan. 14th.

**Comment by pfkrp** [comment]
@brdgtannj Check how your magnitude of magnetic field behaves. It seemed that it was my problem when I compared to the other flights that were successful. It was caused by grounded metal shield in the vicinity of the gps module. Since removal of the shield I haven't observed that problem and the magnitude of magnetic field looks flat as it should.

**Comment by LorenzMeier** [comment]
We've changed so much (and improved so much) that I expect this to be solved on a correctly calibrated setup. Please re-open if it persists.

**Comment by tstellanova** [comment]
Seeing something similar flying an S1000 octo:  
http://logs.px4.io/plot_app?log=d6944989-20ef-4007-bf1e-ca0b3732347f

Multiple warnings:
`2:24:865 | WARNING | [lib__ecl] EKF GPS fusion timeout - reset to GPS`

Have tried two different GPS units (ublox M8N, M8T) with the same results.
Looking at the code it appears this warning shows up when EKF decides GPS data is now valid. I'll look at whether GPS data stalled somehow, but it should not have.

**Comment by LorenzMeier** [comment]
It looks more like an inertial sensor issue / EKF2 tuning issue for your specific airframe. You have a relatively high angular rate noise: http://logs.px4.io/plot_app?log=d6944989-20ef-4007-bf1e-ca0b3732347f#Nav-Raw-Angular-Speed-Gyroscope

**Comment by dagar** [comment]
Output from `./Tools/ecl_ekf/process_logdata_ekf.py`

[Uploading d6944989-20ef-4007-bf1e-ca0b3732347f.ulg.pdf…]()
It looks like the compass is at least part of the problem.

![image](https://user-images.githubusercontent.com/84712/28088766-c716d6fc-6654-11e7-820d-263d0ab7fefc.png)
