### ISSUE TITLE
FW auto land with intermittent terrain data

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#6456]
Fixed wing crash reported by @Flying_Forfun on px4 discuss during auto land with a lidar light. Unfortunately no sdlog is available, which is another bug.

During fixed wing auto land the terrain data becomes intermittant and due to the confusion the vehicle starts climbing, initiates flare at > 60m and stalls during the portion where the pitch setpoint is forced (https://github.com/PX4/Firmware/blob/master/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp#L1668)

@AndreasAntener @tumbili what do you think?

http://discuss.px4.io/t/cant-switch-out-of-mission-mode-during-a-mission/2294

![land_crash](https://cloud.githubusercontent.com/assets/84712/22395451/86f50838-e50c-11e6-8730-acf069fd84dd.png)

**Comment by LorenzMeier** [comment]
That whole feature is highly experimental and not application-hardened. It will need some love and whoever picks it up needs a bit of time. We do have a lidar in Gazebo (mounted to the optical flow iris), so the best would be to start with a pull request for sitl_gazebo which adds it to the plane model and starting testing there.

**Comment by dagar** [comment]
From a proper log for reference.

![bad_flare3](https://cloud.githubusercontent.com/assets/84712/22791671/30fb60b6-eeb8-11e6-9b05-9afa70493d42.png)

When the altitude setpoint (green) drops to ~190m the vehicle is landing, but again flares early.

The FW position controller should be aborting landing if the the terrain data is reported invalid (not logged), but only if the last update is > 1s. These dropouts are much shorter.

**Comment by dagar** [comment]
@LorenzMeier do you think an appropriate fix here would be EKF2 tuning (EKF2_RNG_NOISE, EKF2_RNG_GATE), better handling of terrain data in fw_pos_ctrl, or both?
