### ISSUE TITLE
QGC overlook warning

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#6478]
Apparently I'm not the only one overlooking the warning and searching elsewhere. Maybe warning needs to be more in your face ;)
![qgc_warning](https://cloud.githubusercontent.com/assets/14769636/22420322/39db8748-e6e2-11e6-8a82-59fff8f1c6f7.png)

**Comment by DonLakeFlyer** [comment]
QGC warnings should pop up in a window just below the toolbar as well. Did you get a warning that didn't pop a window? If so, can you come up with steps to reproduce and put the issue on QGC github?

**Comment by mhkabir** [comment]
@ChristophTobler please open a new one in the QGC tracker if this is still an issue.
