### ISSUE TITLE
Pitch sp is interpreted on takeoff as delay

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6479]

**Comment by dagar** [comment]
We could consider dropping the pitch setpoint from the takeoff mission item and using a parameter instead. https://github.com/PX4/Firmware/issues/6787
In practice, it's a dangerously easy thing to accidentally screw up in QGC and all the other aspects of FW takeoff/landing are already PX4 parameters.

**Comment by LorenzMeier** [comment]
Your proposal makes sense. But at least this is fixed on master.
