### ISSUE TITLE
Battery failsafe action can be interrupted unintentionally

### ISSUE THREAD

**Issue by nkhoit** [PX4/Firmware#6488]
Currently if a critical battery failsafe action is being performed, it's pretty easy to unintentionally kick it out of a battery failsafe without realizing it.
It's related to what's happening here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L2481
Meant to deal with geofence violations it seems but also triggers on battery failsafe.

**Comment by dagar** [comment]
Another instance of this - https://github.com/PX4/Firmware/issues/6444

**Comment by dagar** [comment]
Should be fixed by https://github.com/PX4/Firmware/pull/7025.
