### ISSUE TITLE
HIL_CONTROLS question

### ISSUE THREAD

**Issue by lovettchris** [PX4/Firmware#6495]
Is this comment wrong in the code (mavlink_messages.cpp, line 2247) :

    /* scale PWM out PWM_DEFAULT_MIN..PWM_DEFAULT_MAX us to -1..1 for rotors */
    out[i] = (act.output[i] - PWM_DEFAULT_MIN) / (PWM_DEFAULT_MAX - PWM_DEFAULT_MIN);

I'm seeing values ranging from 0 to 1, not -1 to 1.

**Comment by LorenzMeier** [comment]
For which model?

**Comment by lovettchris** [comment]
HIL Quadrocopter X.

**Comment by LorenzMeier** [comment]
Ok, so the simple answer is: The comment lies: Rotors should be scaled 0..1 such that we leave the option for inverted operation (which some systems would support).

**Comment by LorenzMeier** [comment]
Comment fixed in 44c8857354.
