### ISSUE TITLE
Temperature calibration docs

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6514]
@priseborough @bkueng We need the documentation on http://dev.px4.io - please log in to Gitbook and edit: https://www.gitbook.com/book/px4/devguide/details

https://github.com/PX4/Firmware/pull/6508

**Comment by mhkabir** [comment]
![screenshot from 2017-02-04 12-41-28](https://cloud.githubusercontent.com/assets/5557676/22616675/bdd5d8a2-ead7-11e6-9a33-0fc8c8c0cec9.png)

**Comment by priseborough** [comment]
I've created a .md file outline here: 

https://www.gitbook.com/book/px4/devguide/edit#/edit/master/sensor-thermal-calibration.md?_k=cto1im

This will be filled out next week.

**Comment by mhkabir** [comment]
https://dev.px4.io/sensor-thermal-calibration.html
