### ISSUE TITLE
Error on px4io-v2/board_config.h ?

### ISSUE THREAD

**Issue by matanhavi** [PX4/Firmware#6516]
I am not sure, but think that there some error on  px4io-v2/board_config.h
The line: 
[#define GPIO_PPM_IN		(GPIO_ALT|GPIO_CNF_INPULLUP|GPIO_PORTE|GPIO_PIN9)](https://github.com/PX4/Firmware/blob/master/src/drivers/boards/px4io-v2/board_config.h#L129)

says the IO chip has PORT E, but the chip don't have such port.

Its seems that there are two location on the code that refer to this macro:
1) fmu.cpp, (correct if I am wrong) the io code doesn't use it
2) drv_hrt - that seems to configure wrong pin. but because GPIO_PPM is also defined, and initialized there is no issue. 

I might be wrong, and its some kind of trick, and I am not sure if and how it effect the current code, and currently don't have PPM remote to check that.

**Comment by davids5** [comment]
@matanhavi 

Thank you for reporting this.

**Comment by mhkabir** [comment]
Fixed! Thanks @matanhavi.
