### ISSUE TITLE
Mc not holding position during takeoff

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6533]
Since a few weeks master isnt holding position during takeoff
Also it no longer responds to a level command making mission flight impossible and dangerous

@LorenzMeier @dagar @tumbili @AndreasAntener

**Comment by sanderux** [comment]
I'm in senegal making it hard to debug, log will follow

**Comment by sanderux** [comment]
Log: http://logs.uaventure.com/view/tLhQrFFedHMEQHxCdqNrae#Local_X_PLOT
Note the drift in pos x/y

**Comment by AndreasAntener** [comment]
Pretty sure that was because of motor saturation. It didn't do a takeoff but instead navigated to the waypoint normally (high Z velocity setpoint). What do you mean with `level command`?

**Comment by sanderux** [comment]
Hm, it did hit the sky pretty quick failing to agnowledge the takeoff speed. I'll see whats going on there. 

Level horizon doesnt respond in qgc on tablet or pc, usb or 3g telem

**Comment by sanderux** [comment]
This does expose another debatable issue, apperantly altitude takes precedence over horizontal position.

**Comment by AndreasAntener** [comment]
Yes this is an issue and already a long standing discussion. Let me see if/where we track this already.

Can you open an issue on the level horizon? I've heard that from someone on gitter too.
