### ISSUE TITLE
Intel Aero Barometer offset + noise

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#6545]
@lucasdemarchi This issues replaces https://github.com/intel-aero/meta-intel-aero/issues/18

**Comment by lucasdemarchi** [comment]
#6548  fixes the huge offset you see.

**Comment by ChristophTobler** [comment]
I can confirm that https://github.com/PX4/Firmware/pull/6548#pullrequestreview-20959539 fixes the offset. The noise remains though

**Comment by davids5** [comment]
The noise is due that fact the MS56xx is on the same SPI bus as the the other sensors.
![image](https://cloud.githubusercontent.com/assets/1945821/22789784/3c463d0e-ee88-11e6-9eb0-d1cc2038fbcb.png)

The baro should be moved to from SPI3 to SPI2 or better yet it's own spi bus.

**Comment by lucasdemarchi** [comment]
Baro and mag are physically on the same **I2C** bus, with no way to move it
elsewhere.

A patch was already merged to disable the mag, so right now we are only
talking to the baro.

**Comment by davids5** [comment]
Sorry I look at the there aero  board config.

**Comment by LorenzMeier** [comment]
Fixed.
