### ISSUE TITLE
FLASH_BASED_PARAMS - multiple writes because Autosave is permanent 

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#6556]
@LorenzMeier 

Along the way the ```param save``` command was not required and all ```param set``` operations lead to write to backing storage.

The flash is  written to for every change. A fresh boot after "param reset"  results in X * number of param writes to flash. When the param save command was needed before this would be 1 write operation. 

Also the bodies of param_lock/unlock have been commented out. The looks dangerous.

**Comment by LorenzMeier** [comment]
Param lock was never implemented and the param set commands are only executing writes if the param changes. I don't see an issue here.
