### ISSUE TITLE
unable to arm pixracer after first cycle

### ISSUE THREAD

**Issue by maciek01** [PX4/Firmware#6566]
after plugging the battery i can arm it and take off just once.

when i disarm and try again i get the following error:

DISARMED by arm/disarm component command

firmware is 1.5.5

no other indication of what component prevented arming. battery is fully charged.

appreciate any help

maciek

**Comment by mhkabir** [comment]
Can you try the latest release please?

**Comment by maciek01** [comment]
things are back to normal on a new board 1.5.5 (the old one fried). Also upgraded to 1.6rc - still good.
thanks
