### ISSUE TITLE
sdlog2 python script usage is wrong.

### ISSUE THREAD

**Issue by GregoireH** [PX4/Firmware#6596]
The usage of the log analysis tool sdlog2_dump.py is stating that we should specify field using a dot '.' whereas it should be using underscore '_'.

eg. using this
python sdlog2_dump.py log006.px4log -t TIME -m TIME -m IMU -m SENS_BaroAlt,BaroTemp > log.csv
instead of this
python sdlog2_dump.py log006.px4log -t TIME -m TIME -m IMU -m SENS.BaroAlt,BaroTemp > log.csv
Best

**Comment by DaveSprague** [comment]
Agreed, just spend an hour trying to figure out why the sdlog2_dump.py script wasn't working at all.

It's line 306 in the code where it specifies the separater between MSG name and the first FIELD name as "_"

I'm still not getting any actual data in the csv file output but at least now I get the header line.

Attached is the .BIN file I'm trying to convert to a csv

**Comment by bellahduan** [comment]
@DaveSprague  hi, Sorry to disturb you . but i am confused . the log download from QGC is ***.px4log . but it can not use to analysis . Is there any way to solve the problem?
thank u so much .

**Comment by bellahduan** [comment]
@DaveSprague 
![image](https://user-images.githubusercontent.com/26474851/31373675-9410856c-adcd-11e7-923f-3a9a354d7c2f.png)
