### ISSUE TITLE
RC lost with no GPS

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#6617]
What's the correct behaviour for FW (manual) if RC lost and there's no GPS?

http://logs.uaventure.com/view/JEX9QEMwru3u9ditd8vMp6
This is a VTOL that only lost RC briefly, but went into DESCEND nav state (navigator LAND), but without GPS fw_pos_ctrl doesn't run, and most of the landing position setpoint wouldn't work.

Should it be NAVIGATION_STATE_AUTO_LANDGPSFAIL? Or a version of FW land that works without global position?

**Comment by sanderux** [comment]
The behavior suggested: spiral down at 0 throttle for FW, or land as MC in case of VTOL

**Comment by dagar** [comment]
Fixed
