### ISSUE TITLE
Landing initialization

### ISSUE THREAD

**Issue by Stifael** [PX4/Firmware#6623]
1.) Currently ground contact and landing are set to 0 at initialization, which is wrong since at start, when not armed, they both should be 1. 
![landing_initalization](https://cloud.githubusercontent.com/assets/13449161/23129627/ae0d697c-f783-11e6-9028-5bb48316ba96.png)

2.) Currently only landed or groundcontact can occur simultaneously. This is confusing since the state-name "landed" implies that it also has "groundcontact". One solution is to change the name "groundcontact" to "maybe_landed" or we change the logic such that both states can be true.

**Comment by dagar** [comment]
Update?
