### ISSUE TITLE
Local_position_ned values always 0 for x and y coordinates.

### ISSUE THREAD

**Issue by vidullan** [PX4/Firmware#6624]
I have a pixhawk (px4 mini) connected to a rasp pi using the serial interface running firmware 1.5.4.

When I try this example code that is meant to receive local_position_ned I get z values, velocity values, and attitude values, but the x and y local position values are always 0. Also the pixhawk seems to accept offboard mode (the log says so) but I cannot set the local_position_target_ned as it is always 0 as well.

https://github.com/mavlink/c_uart_interface_example

We are operating indoors so is this caused by the lack of GPS signal? If so, is there a way to get local position estimates without GPS?

**Comment by mhkabir** [comment]
> is this caused by the lack of GPS signal?

Yes.

> If so, is there a way to get local position estimates without GPS?

There any many ways, like optical flow and visual odometry. You need to read up. Please open a discussion at http://discuss.px4.io/ for questions like this.
