### ISSUE TITLE
Non-satisfactory flight test results

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6641]
@MaEtUgR @Stifael Some of the recently merged work got negative feedback from our QA team:
http://review.px4.io/plot_app?log=f72bdea3-c111-422c-99e6-8d8ab3cb1b0d

They were testing this:

<img width="1002" alt="screen shot 2017-02-22 at 23 05 41" src="https://cloud.githubusercontent.com/assets/1208119/23234773/797c6290-f953-11e6-9b0a-70c15f73aab4.png">

**Comment by santiago3dr** [comment]
couple flights; good performance
http://review.px4.io/plot_app?log=6ef60043-b047-4ecb-88f8-d908b4f8daf8
http://review.px4.io/plot_app?log=060c9780-1d50-46e2-a5ef-a89e7195cb0f

**Comment by LorenzMeier** [comment]
@tumbili The flight tests suggest the EKF performance degraded. Any ideas?

**Comment by tumbili** [comment]
@LorenzMeier The updates from ecl were about range sensor and optical flow fusion so I don't expect this to be related.

**Comment by MaEtUgR** [comment]
My change simply allows to detect landed with a stick position that is not 5% from the bottom but 15%. If I remember right it was already like this at some time in the past. Now you even have a parameter (LNDMC_MAN_DWNTHR) to tweak or disable this on the newest master.

**Comment by Stifael** [comment]
can we close this?
