### ISSUE TITLE
'.data' will not fit in region 'flash' overflowed by 412 bytes

### ISSUE THREAD

**Issue by AlexMalo** [PX4/Firmware#6655]
I can build the default px4fmu-v2_default without problems, but when I try to add an example uncommenting a line in the cmake/configs/nuttx_px4fmu-v2_default.cmake file 

	#examples/math_demo
	# Tutorial code from
	# https://px4.io/dev/px4_simple_app
	examples/px4_simple_app

I get the following error.

-- Build files have been written to: /Users/badalex2/src/Firmware/build_px4fmu-v2_default
[530/531] Linking CXX executable src/firmware/nuttx/firmware_nuttx
FAILED: src/firmware/nuttx/firmware_nuttx 
: && /usr/local/bin/arm-none-eabi-g++   -g -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -fcheck-new -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -Wfloat-equal -Wpointer-arith -Wmissing-declarations -Wno-unused-parameter -Werror=format-security -Werror=array-bounds -Wfatal-errors -Werror=unused-variable -Werror=reorder -Werror=uninitialized -Werror=init-self -Werror=unused-but-set-variable -Wformat=1 -Wdouble-promotion -Werror=double-promotion -Wno-missing-field-initializers -fvisibility=hidden -include visibility.h -mcpu=cortex-m4 -mthumb -march=armv7e-m -mfpu=fpv4-sp-d16 -mfloat-abi=hard -nodefaultlibs -nostdlib -Os -fno-strict-aliasing -fomit-frame-pointer -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf -O2 -g -DNDEBUG  -Wl,--warn-common -Wl,--gc-sections   -T/Users/badalex2/src/Firmware/build_px4fmu-v2_default/px4fmu-v2/NuttX/nuttx/nuttx-export/build/ld.script -Wl,-Map=/Users/badalex2/src/Firmware/build_px4fmu-v2_default/px4fmu-v2/main.map src/firmware/nuttx/CMakeFiles/firmware_nuttx.dir/builtin_commands.c.obj  -o src/firmware/nuttx/firmware_nuttx -L/Users/badalex2/src/Firmware/build_px4fmu-v2_default/px4fmu-v2/NuttX/nuttx/nuttx-export/libs  -L/Users/badalex2/src/Firmware/build_px4fmu-v2_default/external/Install/lib -Wl,--warn-common -Wl,--gc-sections -Wl,--start-group src/drivers/device/libdrivers__device.a src/drivers/stm32/libdrivers__stm32.a src/drivers/stm32/adc/libdrivers__stm32__adc.a src/drivers/stm32/tone_alarm/libdrivers__stm32__tone_alarm.a src/drivers/led/libdrivers__led.a src/drivers/px4fmu/libdrivers__px4fmu.a src/drivers/px4io/libdrivers__px4io.a src/drivers/boards/px4fmu-v2/libdrivers__boards__px4fmu-v2.a src/drivers/rgbled/libdrivers__rgbled.a src/drivers/mpu6000/libdrivers__mpu6000.a src/drivers/mpu9250/libdrivers__mpu9250.a src/drivers/lsm303d/libdrivers__lsm303d.a src/drivers/l3gd20/libdrivers__l3gd20.a src/drivers/hmc5883/libdrivers__hmc5883.a src/drivers/ms5611/libdrivers__ms5611.a src/drivers/sf0x/libdrivers__sf0x.a src/drivers/trone/libdrivers__trone.a src/drivers/gps/libdrivers__gps.a src/drivers/pwm_out_sim/libdrivers__pwm_out_sim.a src/drivers/airspeed/libdrivers__airspeed.a src/drivers/ets_airspeed/libdrivers__ets_airspeed.a src/drivers/meas_airspeed/libdrivers__meas_airspeed.a src/modules/sensors/libmodules__sensors.a src/drivers/px4flow/libdrivers__px4flow.a src/drivers/pwm_input/libdrivers__pwm_input.a src/drivers/camera_trigger/libdrivers__camera_trigger.a src/drivers/bst/libdrivers__bst.a src/drivers/lis3mdl/libdrivers__lis3mdl.a src/drivers/ulanding/libdrivers__ulanding.a src/systemcmds/bl_update/libsystemcmds__bl_update.a src/systemcmds/config/libsystemcmds__config.a src/systemcmds/hardfault_log/libsystemcmds__hardfault_log.a src/systemcmds/mixer/libsystemcmds__mixer.a src/systemcmds/mtd/libsystemcmds__mtd.a src/systemcmds/nshterm/libsystemcmds__nshterm.a src/systemcmds/param/libsystemcmds__param.a src/systemcmds/perf/libsystemcmds__perf.a src/systemcmds/pwm/libsystemcmds__pwm.a src/systemcmds/reboot/libsystemcmds__reboot.a src/systemcmds/top/libsystemcmds__top.a src/systemcmds/ver/libsystemcmds__ver.a src/modules/commander/libmodules__commander.a src/modules/load_mon/libmodules__load_mon.a src/modules/navigator/libmodules__navigator.a src/modules/mavlink/libmodules__mavlink.a src/modules/gpio_led/libmodules__gpio_led.a src/modules/uavcan/libmodules__uavcan.a src/modules/land_detector/libmodules__land_detector.a src/modules/ekf2/libmodules__ekf2.a src/modules/fw_pos_control_l1/libmodules__fw_pos_control_l1.a src/modules/fw_att_control/libmodules__fw_att_control.a src/modules/mc_att_control/libmodules__mc_att_control.a src/modules/mc_pos_control/libmodules__mc_pos_control.a src/modules/vtol_att_control/libmodules__vtol_att_control.a src/modules/sdlog2/libmodules__sdlog2.a src/modules/param/libmodules__param.a src/modules/systemlib/libmodules__systemlib.a src/modules/systemlib/mixer/libmodules__systemlib__mixer.a src/modules/uORB/libmodules__uORB.a src/modules/dataman/libmodules__dataman.a src/lib/controllib/liblib__controllib.a src/lib/mathlib/liblib__mathlib.a src/lib/mathlib/math/filter/liblib__mathlib__math__filter.a src/lib/ecl/liblib__ecl.a src/lib/external_lgpl/liblib__external_lgpl.a src/lib/geo/liblib__geo.a src/lib/geo_lookup/liblib__geo_lookup.a src/lib/conversion/liblib__conversion.a src/lib/launchdetection/liblib__launchdetection.a src/lib/terrain_estimation/liblib__terrain_estimation.a src/lib/runway_takeoff/liblib__runway_takeoff.a src/lib/tailsitter_recovery/liblib__tailsitter_recovery.a src/lib/version/liblib__version.a src/lib/DriverFramework/framework/liblib__DriverFramework__framework.a src/platforms/nuttx/libplatforms__nuttx.a src/platforms/common/libplatforms__common.a src/platforms/nuttx/px4_layer/libplatforms__nuttx__px4_layer.a src/examples/px4_simple_app/libexamples__px4_simple_app.a src/modules/uavcan/libuavcan/libuavcan/libuavcan.a src/modules/uavcan/libuavcan/libuavcan_drivers/stm32/driver/libuavcan_stm32_driver.a -lapps -lnuttx -lm -lgcc src/firmware/nuttx/libromfs.a -Wl,--end-group libmsg_gen.a src/lib/DriverFramework/framework/src/libdf_driver_framework.a && :
/usr/local/Cellar/gcc-arm-none-eabi/20160928/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: src/firmware/nuttx/firmware_nuttx section `.data' will not fit in region `flash'
/usr/local/Cellar/gcc-arm-none-eabi/20160928/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: region `flash' overflowed by 412 bytes
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make: *** [px4fmu-v2_default] Error 1

**Comment by davids5** [comment]
You will need to disable something else in ```cmake/configs/nuttx_px4fmu-v2_default.cmake``` to make room. The other option is a v3 build if your board has newer silicon and can use the second MB.

**Comment by AlexMalo** [comment]
Thanks!
