### ISSUE TITLE
null checking in param_get function

### ISSUE THREAD

**Issue by jeyong** [PX4/Firmware#6659]
Hi,
when I review param_get function in param.c and param_shmem.c, null checking looks unusual.
`
	const void *v = param_get_value_ptr(param);

	if (val != NULL) {
		memcpy(val, v, param_size(param));
		result = 0;
	}
`

I think v should be checked not val.
`
if(v != NULL) {
`
What do you think?

**Comment by dagar** [comment]
Actually it should be checking that both src and dst are valid pointers.

**Comment by jeyong** [comment]
Yep.
I think it should be checked before used.
So val is checked in entry of function. But that place is for v.

**Comment by LorenzMeier** [comment]
@bkueng Can you look into this?
