### ISSUE TITLE
Param not saved - (storage is FRAM)

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6660]
We crashed one of our prototypes today due to a parameter that didnt store.
The param is question was PWM_AUX2_REV, the following happened;

A new FC as mounted and a bench test was done.
Elevons needed reversing so they were set through QGC.
After setting a bench test was done on the elevons and they performed as required.
Then we went to the field and started a transition, the plane crashed right after transition.
Post-mortem analysis indicated PWM_AUX1_REV was set to 1 but PWM_AUX2_REV was at 0
We managed to test the params on the original wings and indeed the response was incorrect.

The deduced bug is that the param was loaded in memory but it failed to write to flash. QGC showed no warning upon storing the param.

![dq5 crash](https://cloud.githubusercontent.com/assets/14801663/23313426/f00ca6ac-fabd-11e6-86f7-601e444cee40.jpeg)

**Comment by davids5** [comment]
@sanderux - what board config is this on?

**Comment by sanderux** [comment]
Dropix px4-fmu-v2

**Comment by davids5** [comment]
@sanderux,

Just to to confirm does the HW has a RAMTROM FRAM on it and is the config the px4fmu-v2_default build?

I ask because there are "flash based param" in other HW configs and the title may need to be changed to help guide in debugging this.

**Comment by sanderux** [comment]
Yeah i'm not sure. I'll check. It is the fmuv2 default build
But the bug is more a request to verify the param stored in whatever storage it resides

**Comment by sanderux** [comment]
@davids5  I cant find the specs for the type of storage.
It;s this one: https://drotek.com/shop/en/drotek-parts/478-dropix-flight-controller.html

**Comment by kd0aij** [comment]
FM25V01 FRAM: https://github.com/drotek/Dropix/blob/master/Hardware/Dropix.PDF

**Comment by davids5** [comment]
@kd0aij - thanks for the print

**Comment by LorenzMeier** [comment]
There is also the possibility that the param did not get transmitted, potentially because of an input validation issue in the UI.

**Comment by sanderux** [comment]
I am 100 percent sure the params did get applied before reboot as i bench tested the elevon responses both through transmitter and stabilize responses.
