### ISSUE TITLE
Quadchute needs max tilt angles

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6661]
In relation to https://github.com/PX4/Firmware/issues/6660 it has become clear that quadchute cannot recover a plane from a nose dive in every circumstance. It seems evident that some monitoring on max tilt angles must be performed.

**Comment by dagar** [comment]
Where should the line be?
Exceeding FW_P_LIM_MIN/FW_P_LIM_MIN + buffer for some small time limit?

Or more intelligently within the controller if attitude error continues increasing.

**Comment by dagar** [comment]
Implemented.
