### ISSUE TITLE
cannot run make posix_sitl_default gazebo

### ISSUE THREAD

**Issue by tonyvanhain** [PX4/Firmware#6672]
I think the newest update to the firmware have a bug in it where i cannot run the package, and it hangs my laptop everytime I want to run the command make posix_sitl_default gazebo. Does anyone else have this problem as well?

**Comment by mhkabir** [comment]
Where does it hang?

**Comment by dagar** [comment]
@tonyvanhain please share the console output or provide a screenshot.
Another quick thing to try is running without the gui.

    HEADLESS=1 make posix_sitl_default gazebo

**Comment by tonyvanhain** [comment]
@dagar it still wont run properly using the command you given unfortunately

@dagar @mhkabir Here is the console part where it hangs:
![image](https://cloud.githubusercontent.com/assets/21217602/23336806/e96e214a-fc0c-11e6-8810-0ca3bedaa1ff.png), 

I can still run the simulation using make posix_sitl_default jmavsim, but I can't run it now using gazebo

**Comment by tonyvanhain** [comment]
[ 52%] Building CXX object CMakeFiles/LiftDragPlugin.dir/src/liftdrag_plugin/liftdrag_plugin.cpp.o
[ 54%] Building CXX object CMakeFiles/gazebo_geotagged_images_plugin.dir/src/gazebo_geotagged_images_plugin.cpp.o
[ 56%] Building CXX object CMakeFiles/rotors_gazebo_wind_plugin.dir/src/gazebo_wind_plugin.cpp.o
[ 58%] Building CXX object CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o

After checking, the error seems to be caused when trying to build the files above, anyone can help with it?Building the files above causes my laptop to hang

**Comment by mhkabir** [comment]
Do you have enough RAM on your computer? I've seen similar odd behavior
(hangs, freezes, compiler crashes) on systems with <= 4GB RAM.

As a workaround, you can try calling the make target with -j1 to limit
parallel compilation.

**Comment by tonyvanhain** [comment]
@mhkabir  My laptop only uses 4GB, the weird thing is that a week ago I was able to run that command using the laptop that I am using right now, but then I deleted the src folder as a whole and then re-do the steps on the px4 site(https://dev.px4.io/starting-building.html ), particularly the steps where it downloads the firmware from the repo. Can that be the issue?

**Comment by tonyvanhain** [comment]
I already tried to reinstall ubuntu as a whole, and the problem still persist, can anyone help or also had this situation before?

**Comment by tonyvanhain** [comment]
this is what i got when I try to run make posix_sitl_default gazebo
[  0%] Built target git_matrix
[  1%] Built target git_mavlink
[  1%] Built target git_uavcan
[  1%] Built target prebuild_targets
[  1%] Built target git_genmsg
[  1%] Built target git_gencpp
[  1%] Built target git_jmavsim
[  3%] Built target df_driver_framework
[  3%] Built target git_ecl
[  4%] Built target git_driverframework
[  4%] Built target git_gazebo
[  5%] Built target xml_gen
[  5%] Built target mixer_gen
[  5%] Built target ver_gen
[  5%] Performing build step for 'sitl_gazebo'
-- install-prefix: /usr
[ 24%] Built target msg_gen
[ 24%] Built target generate_topic_listener
[ 24%] Built target platforms__common
[ 24%] Built target drivers__boards__sitl
[ 25%] Built target drivers__camera_trigger
[ 30%] Built target systemcmds__tests
[ 31%] Built target drivers__gps
[ 33%] Built target drivers__device
[ 33%] Built target drivers__pwm_out_sim
[ 34%] Built target drivers__vmount
[ 35%] Built target platforms__posix__drivers__accelsim
[ 35%] Built target platforms__posix__drivers__adcsim
[ 35%] Built target platforms__posix__drivers__airspeedsim
[ 36%] Built target platforms__posix__drivers__barosim
[ 36%] Built target platforms__posix__drivers__gpssim
[ 37%] Built target platforms__posix__drivers__gyrosim
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   signals
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
[ 37%] Built target platforms__posix__drivers__rgbledsim
[ 37%] Built target platforms__posix__drivers__ledsim
[ 38%] Built target platforms__posix__drivers__tonealrmsim
-- Boost version: 1.58.0
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
[ 42%] Built target platforms__posix__work_queue
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
[ 42%] Built target systemcmds__esc_calib
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
[ 43%] Built target platforms__posix__px4_layer
[ 44%] Built target systemcmds__perf
[ 45%] Built target systemcmds__mixer
[ 45%] Built target systemcmds__param
[ 45%] Built target systemcmds__reboot
[ 46%] Built target systemcmds__sd_bench
[ 46%] Built target systemcmds__topic_listener
[ 47%] Built target systemcmds__ver
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
[ 48%] Built target systemcmds__motor_ramp
[ 48%] Built target systemcmds__top
[ 48%] Built target modules__attitude_estimator_q
-- Building klt_feature_tracker without catkin
-- catkin DISABLED
Gazebo version: 7.5
[ 48%] Built target modules__dataman
[ 51%] Built target modules__commander
[ 52%] Built target modules__ekf2
[ 54%] Built target modules__uORB
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
[ 54%] Built target lib__external_lgpl
[ 58%] Built target lib__ecl
[ 60%] Built target modules__land_detector
[ 61%] Built target modules__logger
[ 61%] Built target modules__mc_pos_control
[ 63%] Built target modules__mavlink
[ 64%] Built target modules__mc_att_control
[ 64%] Built target modules__param
[ 65%] Built target modules__position_estimator_inav
-- Configuring done
[ 68%] Built target modules__navigator
[ 68%] Built target modules__replay
[ 69%] Built target modules__sdlog2
[ 70%] Built target modules__sensors
[ 71%] Built target modules__simulator
[ 73%] Built target modules__local_position_estimator
[ 76%] Built target modules__systemlib
[ 77%] Built target modules__systemlib__mixer
[ 78%] Built target modules__vtol_att_control
[ 78%] Built target lib__DriverFramework__framework
[ 78%] Built target lib__conversion
[ 80%] Built target lib__controllib
[ 80%] Built target lib__geo_lookup
[ 81%] Built target lib__geo
[ 82%] Built target lib__launchdetection
[ 83%] Built target lib__rc
[ 83%] Built target lib__mathlib
[ 84%] Built target lib__mathlib__math__filter
[ 84%] Built target lib__runway_takeoff
[ 85%] Built target lib__tailsitter_recovery
[ 85%] Built target lib__terrain_estimation
[ 86%] Built target lib__version
[ 86%] Built target examples__px4_simple_app
[ 87%] Built target examples__mc_att_control_multiplatform
[ 88%] Built target examples__mc_pos_control_multiplatform
-- Generating done
-- Build files have been written to: /home/anthonyivan/src/Firmware/build_posix_sitl_default/build_gazebo
[ 89%] Built target examples__ekf_att_pos_estimator
[ 89%] Built target examples__fixedwing_control
[  2%] Running C++ protocol buffer compiler on msgs/Wind.proto
[ 90%] Built target drivers__sf0x__sf0x_tests
[  4%] Running C++ protocol buffer compiler on msgs/Float.proto
[ 91%] Built target examples__attitude_estimator_ekf
[  6%] Running C++ protocol buffer compiler on msgs/SensorImu.proto
[ 91%] Built target lib__rc__rc_tests
[  8%] Running C++ protocol buffer compiler on msgs/opticalFlow.proto
[ 10%] Running C++ protocol buffer compiler on msgs/lidar.proto
[ 13%] Running C++ protocol buffer compiler on msgs/CommandMotorSpeed.proto
[ 15%] Running C++ protocol buffer compiler on msgs/MotorSpeed.proto
[ 17%] Built target sdf
Scanning dependencies of target mav_msgs
[ 92%] Built target modules__commander__commander_tests
[ 93%] Built target modules__mc_pos_control__mc_pos_control_tests
Scanning dependencies of target klt_feature_tracker
[ 93%] Built target modules__controllib_test
[ 19%] Building CXX object OpticalFlow/klt_feature_tracker/CMakeFiles/klt_feature_tracker.dir/src/trackFeatures.cpp.o
[ 94%] Built target modules__unit_test
[ 21%] Building CXX object CMakeFiles/mav_msgs.dir/Float.pb.cc.o
[ 94%] Built target modules__uORB__uORB_tests
[ 23%] Building CXX object CMakeFiles/mav_msgs.dir/SensorImu.pb.cc.o
[ 95%] Built target modules__mavlink__mavlink_tests
[ 26%] Building CXX object CMakeFiles/mav_msgs.dir/opticalFlow.pb.cc.o
[ 30%] Building CXX object CMakeFiles/mav_msgs.dir/CommandMotorSpeed.pb.cc.o
[ 30%] Building CXX object CMakeFiles/mav_msgs.dir/lidar.pb.cc.o
[ 96%] Built target modules__events
[ 32%] Building CXX object CMakeFiles/mav_msgs.dir/MotorSpeed.pb.cc.o
[ 34%] Linking CXX static library libklt_feature_tracker.a
[ 34%] Built target klt_feature_tracker
[ 36%] Building CXX object CMakeFiles/mav_msgs.dir/Wind.pb.cc.o
[ 96%] Built target modules__fw_att_control
Scanning dependencies of target OpticalFlow
[ 97%] Built target modules__fw_pos_control_l1
[ 39%] Building CXX object OpticalFlow/CMakeFiles/OpticalFlow.dir/src/optical_flow.cpp.o
[ 41%] Building CXX object OpticalFlow/CMakeFiles/OpticalFlow.dir/src/px4flow.cpp.o
[ 43%] Building CXX object OpticalFlow/CMakeFiles/OpticalFlow.dir/src/flow_px4.cpp.o
[ 98%] Built target px4_none
[ 45%] Building CXX object OpticalFlow/CMakeFiles/OpticalFlow.dir/src/flow_opencv.cpp.o
[ 98%] Built target px4
[ 47%] Linking CXX shared library libmav_msgs.so
[ 50%] Linking CXX shared library libOpticalFlow.so
[ 50%] Built target OpticalFlow
[ 50%] Built target mav_msgs
Scanning dependencies of target gazebo_geotagged_images_plugin
Scanning dependencies of target LiftDragPlugin
[ 52%] Building CXX object CMakeFiles/gazebo_geotagged_images_plugin.dir/src/gazebo_geotagged_images_plugin.cpp.o
Scanning dependencies of target rotors_gazebo_wind_plugin
Scanning dependencies of target rotors_gazebo_controller_interface
[ 54%] Building CXX object CMakeFiles/LiftDragPlugin.dir/src/liftdrag_plugin/liftdrag_plugin.cpp.o
[ 56%] Building CXX object CMakeFiles/rotors_gazebo_wind_plugin.dir/src/gazebo_wind_plugin.cpp.o
[ 58%] Building CXX object CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o
^CCMakeFiles/rotors_gazebo_controller_interface.dir/build.make:62: recipe for target 'CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o' failed
make[7]: *** [CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o] Interrupt
make[7]: *** wait: No child processes.  Stop.
make[7]: *** wait: No child processes.  Stop.
make[7]: *** Waiting for unfinished jobs....
make[7]: *** wait: No child processes.  Stop.
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/rotors_gazebo_controller_interface.dir/all' failed
make[6]: *** [CMakeFiles/rotors_gazebo_controller_interface.dir/all] Interrupt
make[7]: *** Waiting for unfinished jobs....
make[7]: *** wait: No child processes.  Stop.
make[7]: *** wait: No child processes.  Stop.
make[7]: *** Waiting for unfinished jobs....
make[7]: *** wait: No child processes.  Stop.
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/rotors_gazebo_wind_plugin.dir/all' failed
make[6]: *** [CMakeFiles/rotors_gazebo_wind_plugin.dir/all] Error 2
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/gazebo_geotagged_images_plugin.dir/all' failed
make[6]: *** [CMakeFiles/gazebo_geotagged_images_plugin.dir/all] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/LiftDragPlugin.dir/all' failed
make[6]: *** [CMakeFiles/LiftDragPlugin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[5]: *** [all] Interrupt
src/firmware/posix/CMakeFiles/sitl_gazebo.dir/build.make:110: recipe for target 'external/Stamp/sitl_gazebo/sitl_gazebo-build' failed
make[4]: *** [external/Stamp/sitl_gazebo/sitl_gazebo-build] Interrupt
CMakeFiles/Makefile2:7861: recipe for target 'src/firmware/posix/CMakeFiles/sitl_gazebo.dir/all' failed
make[3]: *** [src/firmware/posix/CMakeFiles/sitl_gazebo.dir/all] Interrupt
CMakeFiles/Makefile2:11576: recipe for target 'src/firmware/posix/CMakeFiles/gazebo.dir/rule' failed
make[2]: *** [src/firmware/posix/CMakeFiles/gazebo.dir/rule] Interrupt
Makefile:3978: recipe for target 'gazebo' failed
make[1]: *** [gazebo] Interrupt
Makefile:139: recipe for target 'posix_sitl_default' failed
make: *** [posix_sitl_default] Interrupt

I interrupt the process because if I don't the hang will begin afterward and I have to force shutdown my laptop

**Comment by tonyvanhain** [comment]
I have upgraded my RAM, and the issues seems to have been solved. Thank you @mhkabir for the suggestion.
