### ISSUE TITLE
enabling mpu9250 and hmc5883 on navio2

### ISSUE THREAD

**Issue by nicolaerosia** [PX4/Firmware#6685]
Is there a reason why mpu9250 and hmc5583 are not being used on Navio2 ?
https://github.com/PX4/Firmware/blob/master/posix-configs/rpi/px4.config#L9-L10
Could someone please shed some light on this?

Thank you

**Comment by LorenzMeier** [comment]
Probably merely an artefact of the testing setup. You should be able to enable them instead. I would need to check if the wrappers are set up correctly for multi-sensors on Navio - you might want to enable only one set by default to start.

**Comment by nicolaerosia** [comment]
@mhkabir I believe you have Navio2. Could you please comment on this? Thanks!

**Comment by mhkabir** [comment]
I don't have anything setup right now.

Why don't you test it and let us know? :)
