### ISSUE TITLE
ll40ls doesn't appear on nsh

### ISSUE THREAD

**Issue by marv3** [PX4/Firmware#6686]
Hey, I'm trying to interface a Lidar Lite v3 with a pixhawk. I'm using the latest release of px4 firmware (v1.5.5) and I tried with the beta version (1.6 rc1) too, but when I try to test the lidar with nsh, ll40ls doesn't appear in the "help" list.  nsh only displays the message "Command not found"

Please, help!!
THANKS.

**Comment by dagar** [comment]
Hi @marv3 
ll40ls was temporarily removed from the px4fmu-v2_default build due to flash constraints, but it's back in now.

**Comment by vinhk** [comment]
@marv3 were you able to see it working? I am using QGC and it does not display data from Lidar Lite V3.
