### ISSUE TITLE
PX4 on Pixhawk does not boot after selecting MAVLINK as camera trigger interface

### ISSUE THREAD

**Issue by jdzerve** [PX4/Firmware#6689]
Scenario on Pixhawk hardware:
- Select Trigger mode "Time based always on"
- Select Triggrer interface "MAVLINK ..."

After powercycle the autopilot does not boot.
Only workaround I found is to flash it with Ardupilot and then back to PX4.

Reproducable on master@3961c46

**Comment by mhkabir** [comment]
Closing in favour of https://github.com/PX4/Firmware/issues/6961. Thanks for reporting.
