### ISSUE TITLE
Problem when running multiple SITL

### ISSUE THREAD

**Issue by kiti1013** [PX4/Firmware#6690]
I want to run multiple copters in gazebo with ros
when i run this command `./sitl_multiple_run.sh `
it will produce some error in ~/src/Firmware/build_posix_sitl_default/instance_1 ~/src/Firmware/build_posix_sitl_default/instance_2
the out.log show me
data path: /home/astera/src/Firmware/Tools/..
commands file: rcS
ERROR [Unknown] Error opening commands file, does not exist: rcS
Restoring terminal

how to do with it 
and who can tell me  how to run a multiple copters gazebo simlation  
i can run a single copter in gazebo with ROS，
use the following steps
```
make posix_sitl_default gazebo
roslaunch mavros px4.launch fcu_url:="udp://:14540@127.0.0.1:14557"
rosrun uavctrl uavctrl_node
```

**Comment by mhkabir** [comment]
Duplicate : https://github.com/PX4/Firmware/issues/6699
