### ISSUE TITLE
ll40ls nsh reading issue 

### ISSUE THREAD

**Issue by marv3** [PX4/Firmware#6691]
Hey, I'm using a Lidar Lite v3 but when I try to test this(ll40ls test i2c), nsh displays:

ll40ls: inmediate read failed: try again.

I tried a lot of times and it doesn't work.
Can you help me? Please.

THANKS.

#UPDATE 1: When I try using "ll40ls info i2c" there is a distance parameter which displays the measured distance (I tried in two different positions). But, this "distance" doesn't change if I change the position of the lidar (to measure other distance), when I try with "ll40ls info i2c" the display for "distance" is the same.
HELP! and thanks again.

**Comment by LorenzMeier** [comment]
http://discuss.px4.io/t/poshold-with-optical-flow-works-weird/2432/9

This has a few tips. It sounds like a setup / wiring issue.
