### ISSUE TITLE
Communication between STMF4 and STMF1

### ISSUE THREAD

**Issue by Embeddedkuba** [PX4/Firmware#6692]
Hi there,
Currently I want to erase code from stmf100 and send simple message to stmf4.
Is there a possibility to send a frame from STMf100 to STMF4 without changing code on STMF4? 
I know that there is a uart connection, but I can't find a method reading frames on STMF4. Is there any? 
This is a packet of data to communicate:
`  333 struct IOPacket {
  334         uint8_t         count_code;		//jw
  335         uint8_t         crc;			// crc :D 
  336         uint8_t         page;			// organizacja rejestrow w strony >>patrz poniżej
  337         uint8_t         offset;			//
  338         uint16_t        regs[PKT_MAX_REGS];	
  339 };
`
What can I send from stmF1 to get any answer?

**Comment by LorenzMeier** [comment]
This is not a real issue of the system, so I'm closing this. You will need to answer such high-level implementation questions on the forums or yourself.
