### ISSUE TITLE
Using parentheses for clarity on if statement

### ISSUE THREAD

**Issue by jeyong** [PX4/Firmware#6696]
It's just for coding style.
When I review source code, it takes time to understand this statements. I was a little confused.

/src/systemcmds/pwm/pwm.c

`
if (set_mask & 1 << i)
`
I know it's not bug. But I think it needs parentheses for clarity.

`
if (set_mask & (1 << i) )
`

What do you think?

**Comment by dagar** [comment]
Hi @jeyong 

Yes readability is quite important. Code is written once, but read many times. Feel free to open a pull request making changes like this, although you should only make changes if you're able to test it before and after (even trivial ones).
In the build system we run astyle and clang-tidy to maintain code style and readability. If you find a way to automatically fix and enforce parentheses usage like this with those tools we could add it to the build system.

Thanks
