### ISSUE TITLE
PR #6074 has broken the ekf2 replay

### ISSUE THREAD

**Issue by priseborough** [PX4/Firmware#6701]
The changes made to other modules to accomodate the revised uORB were not make to the ekf2 replay.

**Comment by bkueng** [comment]
@priseborough I have a fix, I'll probably push it today

**Comment by priseborough** [comment]
TXS

**Comment by priseborough** [comment]
@LorenzMeier That fact that this has been closed indicates a decision to no longer support the sdlog2 replay format. If you can confirm this, then I will remove the sdlog2 replay info in the wiki.

**Comment by LorenzMeier** [comment]
Please do. We are phasing out the old logger.
