### ISSUE TITLE
tar -jxf gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2

### ISSUE THREAD

**Issue by potato77** [PX4/Firmware#6707]
I am installing the toolchain.
I used the command tar -jxf gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2.
Then,
![default](https://cloud.githubusercontent.com/assets/11450591/23489388/0f9b88c6-ff2d-11e6-95c6-65b235b5f48f.PNG)
why i cant install the gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2

**Comment by potato77** [comment]
can i use the command     **sudo apt install gcc-arm-none-eabi**  to install it?

**Comment by kiti1013** [comment]
`wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2`

**Comment by davids5** [comment]
We are using 
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]

```wget https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/gcc-arm-none-eabi-5_4-2016q2-20160622-linux.tar.bz2```
