### ISSUE TITLE
EFK2 Airspeed sensor parameter name inconstancy

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Firmware#6708]
Dear, 

There is some inconsistency between the airspeed parameter names. It has 3 names : `ASP`, `ARSP` and `EAS`. 

* EKF2_ASP_DELAY - Airspeed delay
* EKF2_ARSP_THR - Airspeed fusion threshold
* EKF2_EAS_NOISE - Airspeed noise

Also there is the Vision estimate inconsistency for two params.

Vision estimation is always `_EV_`, but for the noises it is `_EVP_` and `_EVA_`. To follow the rule GPS params are written, it should `_EV_P_` and `_EV_A_`
 
* EKF2_EVP_NOISE to  EKF2_EV_P_NOISE
* EKF2_EVA_NOISE  to  EKF2_EV_A_NOISE

**Comment by dagar** [comment]
I'm happy to do the rename for consistency, but then users silently lose their configuration when upgrading (if they've touched these).
@priseborough @LorenzMeier Thoughts?

**Comment by priseborough** [comment]
I would avoid changing parameter names now for the reason @dagar gives. The exception might be if the parameter name is misleading, which is not the case for these examples. What is more important is that the description for each parameter is clear and complete.

**Comment by dagar** [comment]
I think we'll have to close this and try to name things more consistently going forward.
