### ISSUE TITLE
Pixhawk Pro lockup after mag cal

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#6712]
I just flashed latest master on a pixhawk v3 pro and noticed the following behavior:
1) Selected airframe -> reboot
2) Calibrated gyro, calibrated accel
3) Did the mag calibration (internal only) and got a message like "Mag 1 fail: TOUT"
Shortly after the board seemed to lock up (LED was solid red) and QGC lost connection.
When I rebooted the board the sensors were still calibrated but the airframe parameter was set to 0.
The second time I tried it everything was ok.

**Comment by sanderux** [comment]
Can't reproduce on my pixhawk pro

**Comment by sanderux** [comment]
Manually changing the CAL+MAG_XOFF did indeed crash the FC

**Comment by sanderux** [comment]
@klopezal could you have a look

**Comment by LorenzMeier** [comment]
@klopezal Can you re-try this on a current board?

**Comment by klopezal** [comment]
Can't reproduce with V1.3 modifications, but I'd like to instrument to make sure it is not a hidden problem.

**Comment by LorenzMeier** [comment]
Since the HW is not widely deployed and its unclear if this still persists moving out to next release.

**Comment by klopezal** [comment]
Unable to reproduce on V1.2 with jumper, waiting for V1.3 to validate and close.
