### ISSUE TITLE
PX4 and ping command

### ISSUE THREAD

**Issue by shening** [PX4/Firmware#6721]
Hi I was wondering if the Mavlink ping command was implemented on the PX4 in order to measure GCS to aircraft connection latency 

PING (  )
https://pixhawk.ethz.ch/mavlink/ 
A ping message either requesting or responding to a ping. This allows to measure the system latencies, including serial port, radio modem and UDP connections.

Thank you,

Sebastian

**Comment by dagar** [comment]
It's not implemented in PX4, but it shouldn't be that hard to add. If you're interested in adding this I'd be happy to point you in the right direction.

http://mavlink.org/messages/common#PING

You would add a simple function in the PX4 mavlink module here - https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L704

``` C
void
MavlinkReceiver::handle_message_ping(mavlink_message_t *msg)
{
    // send ping reply
}

```

**Comment by mhkabir** [comment]
We should then expose the ping statics per-link via `mavlink status`.

I've been meaning to do this for a while, but if @shening is interested in doing it, that's awesome!

**Comment by dagar** [comment]
Would love to have this is you're interested in implementing. Pull requests welcome!

**Comment by weiminshen99** [comment]
Hi, All,

Could you please tell me if this has been implemented yet? I just stated flying multiple UAVs and it would be great to have this handy. Thanks in advance. 

Wingman

**Comment by weiminshen99** [comment]
Hi, @dagar,
I am interested in implementing this because I need it badly for my multi-PX4 swarms. Please let me know how.  Do I need to open a new issue on this? Thanks!

**Comment by dagar** [comment]
@weiminshen99 it looks partially implemented. https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1718-L1728

Yes please open a new issue to discuss.
