### ISSUE TITLE
FW RTL return broken due to LNDMC_ALT_MAX

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#6726]
RTL on FW is skipping the return stage because the land detector max altitude isn't populated.

Land detector doesn't seem like the right place to publish an maximum altitude limit.

**Comment by LorenzMeier** [comment]
The land detector will be renamed to vehicle_model. Then it makes much more sense and it becomes more obvious that this is the right location to group this.

**Comment by tubeme** [comment]
Is this applicable to 1.6.0 RC1?

**Comment by LorenzMeier** [comment]
No its not.

**Comment by LorenzMeier** [comment]
Fixed in: https://github.com/PX4/Firmware/pull/6732
