### ISSUE TITLE
How to remove lsm303d_accel driver 

### ISSUE THREAD

**Issue by winszenYoung** [PX4/Firmware#6734]
I have a problem with my pixhawk.
My pixhawk lsm303d_accel sensor is dead.
So I try to remove lsm303d accel driver .
But I fail to remove. 

Can you help me?
How to remove lsm303d accel driver?

**Comment by mhkabir** [comment]
We will not help support broken hardware setups.

**Comment by LorenzMeier** [comment]
@winszenYoung It will automatically not start if its broken. However, if the sensor is not really dead but half-working, you should consider retiring this board. Its not safe to fly.
