### ISSUE TITLE
Pixhawk 3 prototype when powered via USB, accel and gyro failures

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#6741]
After a certain idling time (few minutes), failures from mpu9250

**Comment by LorenzMeier** [comment]
@davids5 Can you take a look?

**Comment by davids5** [comment]
@AndreasAntener - Is this the same px4fmu-v4pro?

**Comment by AndreasAntener** [comment]
Yes.

**Comment by davids5** [comment]
@AndreasAntener - Closing this for now. Please reopen if the reworked HW exhibits the same behavior.
