### ISSUE TITLE
Yaw timeout in missions doesn't work anymore

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#6758]
@dagar why was this needed: https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L391-L393 ?

This causes the yaw timer to update in every iteration and therefore the timeout not to work anymore.

**Comment by dagar** [comment]
I believe it was for NAV_CMD_LOITER_TO_ALT where you need to be on the loiter and exit at the right point. I'll need to review the entire thing alongside this PR (https://github.com/PX4/Firmware/pull/6756) to find a fix.
