### ISSUE TITLE
The red light  flashes all the time after downloading the firmware by PX4 console and PX4 eclipse.

### ISSUE THREAD

**Issue by STAR805671782** [PX4/Firmware#6761]
When I download the firmware by mission planner ,the pixhawk run properly. But when I download the firmware  by PX4 console and PX4 eclipse like this blog http://blog.csdn.net/oqqenvy12/article/details/52035127?_t=t    The red light on pixhawk is always flashing.Then I can do nothing and the pixhawk doesn't work.......why?  My development environment is wrong? My computer system is 64-bit and windows 10 system .

**Comment by LorenzMeier** [comment]
The blog post is likely outdated. Use the official development instructions from here: http://dev.px4.io
