### ISSUE TITLE
use stlinkv2 to debug with GDB and openocd

### ISSUE THREAD

**Issue by kiti1013** [PX4/Firmware#6768]
i use
 `openocd -f interface/stlink-v2.cfg -f target/stm32f4x.cfg
` 
to contect the pixhawk fmu 
and 
run `/usr/local/bin/arm-none-eabi-gdb build_px4fmu-v2_default/src/firmware/nuttx/firmware_nuttx
`to  run gdb 
but how to debug for the fmu  how to run the code step by setp

**Comment by dagar** [comment]
@kiti1013 were you able to get this working?
