### ISSUE TITLE
Snapdragon Flight parameter synchronization is broken

### ISSUE THREAD

**Issue by jywilson** [PX4/Firmware#6778]
The qurt and posix builds generate separate parameter.xml files.  Since the current parameter synchronization mechanism uses an index to update the parameter representation in memory on the aDSP and AppsProc, attempting to update a parameter in the AppsProc will cause the wrong parameter to be updated in the aDSP.

**Comment by Stifael** [comment]
https://github.com/PX4/Firmware/issues/6261

**Comment by LorenzMeier** [comment]
@jywilson @mcharleb We need the params on both sides to be synced. That's super important because anything else is very non-intuitive.

**Comment by bkueng** [comment]
@jywilson the different parameters.xml can come from the [cmake scoping](https://github.com/PX4/Firmware/blob/master/cmake/common/px4_base.cmake#L1081) if the two builds use different modules.

**Comment by jywilson** [comment]
@LorenzMeier I agree.  This is probably responsible for the QGC crash reported here: https://github.com/mavlink/qgroundcontrol/issues/4738

More comments on this problem here: https://github.com/PX4/Firmware/issues/6765

**Comment by jywilson** [comment]
I am working top resolve this issue now.  

@LorenzMeier Can you assign it to me?  I can't seem to find a way to assign this to myself on my own.

**Comment by jywilson** [comment]
This issue is fixed in this PR:
https://github.com/PX4/Firmware/pull/6883

**Comment by jywilson** [comment]
A fix for this issue is now on master.
