### ISSUE TITLE
what is the use of the remaining fields of the firmware file？such as the "airframe_xml" fiels

### ISSUE THREAD

**Issue by zouboan** [PX4/Firmware#6781]
The px_uploader.py only upload the image fields from the firmware file（px4fmu-v4_default.px4）,The question is what is the use of the remaining fields of the firmware file？such as the "airframe_xml" fiels,It doesn't seem to be  upload to the PX4 at all

**Comment by LorenzMeier** [comment]
The .px4 file is a complete binary with meta data which is used by various other systems.
