### ISSUE TITLE
It seems the format of px4fmu-v4_default.px4 does not match the px4fmu-v4.prototype?

### ISSUE THREAD

**Issue by zouboan** [PX4/Firmware#6782]
There's no "airframe_xml" fields at all in the px4fmu-v4.prototype,but the px_mkfw.py use fellow code:
	desc['airframe_xml_size'] = len(bytes)
	desc['airframe_xml'] = base64.b64encode(zlib.compress(bytes,9)).decode('utf-8')
and there's  "airframe_xml" fields in the px4fmu-v4_default.px4,why?

**Comment by LorenzMeier** [comment]
Prototype means its an input. It's not a final config.
