### ISSUE TITLE
MulticopterLandDetector Bug

### ISSUE THREAD

**Issue by xn365** [PX4/Firmware#6789]
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L273
same as
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L281
_get_takeoff_throttle() always  return _params.manual_stick_up_position_takeoff_threshold;

**Comment by Stifael** [comment]
And why that? It only returns the threshold when manual and altitude is enabled
