### ISSUE TITLE
LandDetector Bug

### ISSUE THREAD

**Issue by xn365** [PX4/Firmware#6818]
Can't take off after the first flight in Altitude mode.
Because of this line:
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/LandDetector.cpp#L206
This line will never works until we leave landed state:
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L214
So,if we arm in altitude mode ,this line will be the only chance to takeoff:
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L239
It's looks good for the first time to takeoff.
But,when we landed and disarmed after the first flight.
_min_trust_start !=0 after we landed,because we returned from https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L204  ,and we did not reset "_min_trust_start"  to zero.
In this case ,we can't takeoff after the first flight if we are in altitude mode with no position lock.

Maybe we could never takeoff if we are in altitude mode and have position locked?

**Comment by MaEtUgR** [comment]
should be fixed by https://github.com/PX4/Firmware/pull/7081
if not, please reopen
