### ISSUE TITLE
cant enter the nsh mode

### ISSUE THREAD

**Issue by potato77** [PX4/Firmware#6824]
i follow the devguide and enter "screen /dev/ttyACM0 BAUDRATE 8N1"
and it shows a new console. but i cant enter any words.

![1](https://cloud.githubusercontent.com/assets/11450591/23942464/5c3509c6-09a7-11e7-92c7-f61f9023ebcc.PNG)

How to fix it? Thank you in advance!

any help would be appreciated!

**Comment by d3z0rian** [comment]
Did you replaced the "BAUDRATE" word for the board baudrate in number?
Serial: Pixhawk v1 / Pixracer use 57600 baud
Serial: Snapdragon Flight uses 115200 baud

**Comment by potato77** [comment]
@d3z0rian

yes

**Comment by mhkabir** [comment]
Since this is a VM, there may be issues with accessing the port on the host machine. Not sure how we can help with this directly.

**Comment by mhkabir** [comment]
If this still persists, try removing modemmanager, and making sure your user is in the dialout group.
