### ISSUE TITLE
error of install homebrew on MAC os

### ISSUE THREAD

**Issue by potato77** [PX4/Firmware#6831]
QideMacBook-Air:~ Qi$ brew tap osrf/simulaton
Updating Homebrew...
==> Tapping osrf/simulaton
Cloning into '/usr/local/Homebrew/Library/Taps/osrf/homebrew-simulaton'...
Username for 'https://github.com': fatmoonqyp@126.com
Password for 'https://fatmoonqyp@126.com@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/osrf/homebrew-simulaton/' not found
Error: Failure while executing: git clone https://github.com/osrf/homebrew-simulaton /usr/local/Homebrew/Library/Taps/osrf/homebrew-simulaton --depth=1

why this error happen?

**Comment by dennisss** [comment]
Misspelled `osrf/simulaton`, should be `osrf/simulation` (note the last `i`). If you are on a newer version of Mac, this may also be useful to you: https://github.com/osrf/homebrew-simulation/pull/198
