### ISSUE TITLE
att_pos_mocap gives no messges

### ISSUE THREAD

**Issue by bhairavmehta95** [PX4/Firmware#6837]
I am using the mavros mocap pose estimate plugin to feed Px4 VICON data as state estimation.

Yet when yet I use the listener att_pos_mocap command in the PX4 shell, nothing shows up.

I have made no modifications to the code, so I was wondering if someone could help me out.

**Comment by karanchawla** [comment]
I am having quite the opposite issue, though I'm receiving `att_pos_mocap` msg on the topic I am unable to switch to position control for inav. Any clues about this? 
As for your problem how are you sending `att_mocap_pos` with PX4, indoor fake GPS?

**Comment by mhkabir** [comment]
@bhairavmehta95 Does the mavros instance connect with PX4 correctly? Is this on Snapdragon?

**Comment by mhkabir** [comment]
And everyone having issues please post logs @karanchawla @bhairavmehta95.
