### ISSUE TITLE
Txt file not changing baud rate for Pixfalcon

### ISSUE THREAD

**Issue by gckgck** [PX4/Firmware#6869]
Hi all I know this related question have been posted in previous threads but I did not manage to find any solutions for it.
I am trying to change the baud rate for Pixfalcon from 57600 to 921600 since there are some delay when i am trying to send messages to it through multiple nodes at the same time. I tried adding a extra.txt file in the etc folder with various commands in it. (no telem2 in Pixfalcon to use Qgroundcontrol to change SYS COM)
Version 1:
mavlink stop-all
set MAVLINK_F "-r 1200 -d /dev/ttyS0"
mavlink start -r 20000 -m config -b 921600 -d /dev/ttyS1

Version 2:
mavlink stop-all
mavlink start -d /dev/ttyS1 -b 921600 -r 3000
mavlink start -d /dev/ttyACM0

I then changed the baud rate through the browser with the link
http://192.168.4.1/setparameters?baud=921600.
However doing so gave me the error
[ INFO] [1490094284.176297811]: CON: Got HEARTBEAT, connected. FCU: INVALID
[ WARN] [1490094286.178662038]: VER: broadcast request timeout, retries left 4
[ WARN] [1490094287.180176029]: VER: broadcast request timeout, retries left 3
[ WARN] [1490094288.178617605]: VER: unicast request timeout, retries left 2
[ WARN] [1490094289.177899120]: VER: unicast request timeout, retries left 1
[ WARN] [1490094290.179989010]: VER: unicast request timeout, retries left 0
[ WARN] [1490094291.178454197]: VER: your FCU don't support AUTOPILOT_VERSION, switched to default capabilities
when I tried connecting to Pixfalcon.

I think that the txt file is not executing the commands in it properly, do anyone have any idea on how to solve this problem? Thanks for the help in advance!

**Comment by mhkabir** [comment]
It should be on your microsd, under `/etc/extras.txt`, not "extra.txt".
