### ISSUE TITLE
LPE GPS Fusion bitmask bug

### ISSUE THREAD

**Issue by deksprime** [PX4/Firmware#6879]
Although I am unable to reproduce the issue, there is a problem with the latest master LPE fusion bitmask. When I exclude the GPS from the LPE fusion bitmask , the GPS is completely gone. I see that the GPS receiver is present and QGC doesn't say 'Gps receiver missing'. I use the px4fmu-v2_lpe and build it from source. I have came across this problem throughout many GPS receivers and/or Pixhawk 1s, but right now I am unable to reproduce the error. I have flashed firmware with ekf2 (default) and GPS is OK.

**Comment by mhkabir** [comment]
I don't see how this can happen. Let us know if you can reproduce it again.
