### ISSUE TITLE
PX4 fixed wing reporting unreasonable alt/distance errors in recent QGC daily builds

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#6884]
With recent QGC daily builds I am seeing strange altitude/distance errors being reported back.  This happens with multiple PX4 builds that include the fixes to HIL sim PRs.  I'm running Xplane10 HILstar model on a pixracer.  Details further below.

Any ideas? 

@DonLakeFlyer did you mention elsewhere some recent changes to MISSION_ITEM_INT support in QGC?

Fixed wing landings are always rejected with very large numbers.  I get this error every time.  Same error happens in real life too, not just HIL sim:
![image](https://cloud.githubusercontent.com/assets/12117027/24278405/9f242102-1011-11e7-9482-8a8f971ebc08.png)
and
![image](https://cloud.githubusercontent.com/assets/12117027/24278385/8b658e12-1011-11e7-8392-b8cf3da3adb6.png)

rare, but sometimes get very large numbers for waypoint parameters returned from PX4:
![image](https://cloud.githubusercontent.com/assets/12117027/24278554/79af4b80-1012-11e7-88a9-a5d09e95f33b.png)

Maximum altitude above home is on the dark side of the moon!  (only got this one once so far)
![image](https://cloud.githubusercontent.com/assets/12117027/24278598/b1bf99f8-1012-11e7-97ff-d811fa8bd47f.png)

**Comment by DonLakeFlyer** [comment]
Ah, I finally gave myself the hint I needed. I was setting alt using the _INT format as well. But when round tripped I pulled alt back from _INT format so it looked like everything was working correctly through QGC. The bug is on the QGC side.
