### ISSUE TITLE
pixhawk 2.1 mag calibration failure with external

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#6898]
http://discuss.px4.io/t/pixhawk-2-mag-calibration-failure-with-here-gps-module/2869

Start the individual calibration steps by clicking one of the buttons to the left.

    [cal] calibration started: 2 mag
    [cal] Skipped scale calibration, sensor 1
    [cal] Skipped scale calibration, sensor 2
    [cal] Mag 3 no device id, abort
    [cal] calibration failed: mag

If I remove the module, then I can calibrate the compass without issues.

**Comment by dagar** [comment]
Either need to update PX4 to handle 4 mags, or realistically we probably don't need 3 internal mags.

**Comment by tubeme** [comment]
Is this the X2.1??

**Comment by dagar** [comment]
Yes

**Comment by LorenzMeier** [comment]
Fixed in https://github.com/PX4/Firmware/pull/7080
