### ISSUE TITLE
Pixracer: MANUAL CONTROL LOST on param save

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#6902]
When landing, the flight duration param is set, leading to a param save. On pixracer, this causes a manual control loss and failsafe mode switch. The following shows the order of events (timestamps in ms), on #6901 branch:
```
nsh> WARN  [land_detector] param land set 24929
WARN  [land_detector] param land set 24929 done
INFO  [commander] Landing detected
WARN  [modules__systemlib] entering param_save_default 25229 
WARN  [commander] MANUAL CONTROL LOST (at t=25739ms)
INFO  [commander_tests] no RC
WARN  [commander] failsafe mode on
INFO  [commander] Takeoff detected
WARN  [modules__systemlib] param_save_default done 26424
WARN  [commander] failsafe mode off
```

And this shows the sampling is thrown off during param save (timestamps do not match the above output):
![manual_control_loss_pixracer_sampling](https://cloud.githubusercontent.com/assets/281593/24350573/f94da35a-12e2-11e7-967d-cc24eaa3d383.png)

Happens both on master (8810f70fdcf036b with nuttx semaphore patch) and with https://github.com/PX4/Firmware/pull/6901

This is not a prio inversion/inheritance problem, all task priorities stay the same. The problem is that we disable interrupts during save, apparently for too long, throwing off RC and sensor sampling, done here: https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/param/param.c#L922. If I comment out this lock, the problem disappears.

@davids5 can you look into that?

**Comment by davids5** [comment]
@bkueng https://github.com/PX4/Firmware/pull/7036 - would you please test as suggested.

**Comment by LorenzMeier** [comment]
Closing as the fix was merged.
