### ISSUE TITLE
Level horizon from QGC doesn't survive reboot

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6905]
When leveling horizon the new offsets get applied but return to previous state after a reboot. 
(aka no param write)

@LorenzMeier do you know who to assign?

**Comment by bkueng** [comment]
@sanderux I just tested level calibration with QGC several times with pixracer, and it stays persistent every time. Is it reproducible for you? Which HW? And do you have the same problem on the #6901 branch?

**Comment by sanderux** [comment]
Its on a dropix (fmuv2)
it's consistent over multiple FC's
I'm now working on a more critical issue https://github.com/PX4/Firmware/issues/6911
after that i'll try your suggestion

**Comment by sanderux** [comment]
@bkueng the issue seems already resolved on master, i could only reproduce it in the branch we were flying (somewhere jan)

**Comment by bkueng** [comment]
Ok, I'm closing it then.
