### ISSUE TITLE
Confusions about topics in gazebo_mavlink_interface.cpp.

### ISSUE THREAD

**Issue by yajingwang94** [PX4/Firmware#6909]
Hi, 

I find in the `gazebo_mavlink_interface.cpp` that the `control information` has two sources:
-1.  from `udp_port 14560 `(which is bind with the `socket` of `simulator` module) ;
-2.  from topic `/HilControl` ;

When I searched for the information of `/HilControl` topic, I failed to find its publisher:
![screenshot from 2017-03-28 16-21-24](https://cloud.githubusercontent.com/assets/18362945/24395926/f734dc0e-13d3-11e7-8d12-79be6ea65565.png)

What's more, I find the `gazebo_mavlink_interface` also subscribe to several topics: `/imu`, `/lidar`, `/opticalFlow.`  Do they have someone who already publishes them? Did I miss anything important? 

And, there are "hil" in names of these topics, do they have something to do with hardware in the loop simulation?

Thanks for the time.

**Comment by dagar** [comment]
@ziyangli did you figure this out?

**Comment by TSC21** [comment]
Though SITL uses HIL msgs, those are not related with using HIL.
