### ISSUE TITLE
Noise(?) in PWM signal

### ISSUE THREAD

**Issue by Clark-Youngdong-Son** [PX4/Firmware#6912]
Hello all.

I am sorry if this 'issue' board is not appropriate for question.

Device : PixhawkMini
Firmware : px4fmu-v2_lpe

I am changing the firmware to apply my own controller(model-based) which outputs (thrust(N), 3-axis moment(N.m)).

Before changing the controller, I am checking the PWM signal flow to find out where I can change PWM values directly.

I found that the file "fmu.cpp" calls functions "mix" and "pwm_limit_calc".
In the last line of the function "pwm_limit_calc", I added a line `effective_pwm[0]=1400` to rotate one motor with desired velocity.
It works well since the rostopic "rc/out" shows same value as 1400.

However, the value does not always maintain 1400, showing 1395, 1386, or other values.
The following script shows the phenomenon.

`header: 
  seq: 2564
  stamp: 
    secs: 1490704761
    nsecs: 102663376
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1300, 1000, 1000, 1000, 1500, 1500, 0, 0]
---
header: 
  seq: 2565
  stamp: 
    secs: 1490704761
    nsecs: 166788376
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1300, 1000, 1000, 1000, 1500, 1500, 0, 0]
---
header: 
  seq: 2566
  stamp: 
    secs: 1490704761
    nsecs: 211253936
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1300, 1000, 1000, 1000, 1500, 1500, 0, 0]
---
header: 
  seq: 2567
  stamp: 
    secs: 1490704761
    nsecs: 259376936
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1300, 1000, 1000, 1000, 1500, 1500, 0, 0]
---
**header: 
  seq: 2568
  stamp: 
    secs: 1490704761
    nsecs: 326525336
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1178, 1061, 1240, 1000, 1500, 1500, 0, 0]**
---
header: 
  seq: 2569
  stamp: 
    secs: 1490704761
    nsecs: 371479336
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1300, 1000, 1000, 1000, 1500, 1500, 0, 0]
---
header: 
  seq: 2570
  stamp: 
    secs: 1490704761
    nsecs: 415743272
  frame_id: ''
channels: [0, 0, 0, 0, 0, 0, 0, 0, 1300, 1000, 1000, 1000, 1500, 1500, 0, 0]
---

At the seq:2568, the value is changed to 1178.

Please let me know why this weird thing happens. 

1. Is there any other functions which have authority to designate PWM values?

Moreover, whenever I upload my modified firmware, the channels are changed. For now, you can see first eight channels are empty with zero values, and the last eight channels are designated to send PWM values.

2. How can I assign first eight channels to show PWM values in mavros?

Thank you for your time.

**Comment by dagar** [comment]
@Clark-Youngdong-Son can you use http://discuss.px4.io/ for questions? I think you'll need to share some of your code for someone to be able to help you.
