### ISSUE TITLE
Pixhawk Mini: RC Input is not detected if using GCC 4.9 in Mac OS

### ISSUE THREAD

**Issue by d3z0rian** [PX4/Firmware#6918]
RC Input is not detected if master for px4fmu-v3_default is compiled with Toolchain 4.9.3 in Mac OS.

Not working with 4.9.3:
![image](https://cloud.githubusercontent.com/assets/5013954/24428957/f759741a-13c4-11e7-9ef4-c87ae1394d4f.png)
![image](https://cloud.githubusercontent.com/assets/5013954/24428987/15c64338-13c5-11e7-876e-e5f73381b855.png)

Working with 5.4.1:
![image](https://cloud.githubusercontent.com/assets/5013954/24429032/410d66b6-13c5-11e7-9d80-a4d88a1cf07b.png)
![image](https://cloud.githubusercontent.com/assets/5013954/24429052/5074b79e-13c5-11e7-8c4f-cb79aae434a0.png)

Autopilot: Pixhawk Mini
Mac OS: Sierra 10.12.3

For Linux there are instructions to install GCC 4.9 or 5.4:
https://dev.px4.io/starting-installing-linux-boutique.html#toolchain-installation

For MacOS, instructions don't specify a version but in my case, it installed 4.9.3
https://dev.px4.io/starting-installing-mac.html#homebrew-installation

I uninstalled GCC running:
`brew uninstall gcc-arm-none-eabi`

And Installed GCC 5.4.1 running:
`brew install gcc-arm-none-eabi-54`

I don't know in which cases I should use 4.9 or 5.4, also there are newer versions (https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads), but for now I will use 5.4

**Comment by yl5006** [comment]
I have same problem in linux

**Comment by dagar** [comment]
The official builds are using GCC 5.4.
