### ISSUE TITLE
Qualcomm (Snapdragon) ESC control problem?

### ISSUE THREAD

**Issue by Seanmatthews** [PX4/Firmware#6929]
**Some upfront info:**
* Using the Snapdragon Flight development kit with the Qualcomm ESC controller
* Using RC controller DX6e
* Installed toolchain according to https://github.com/ATLFlight/cross_toolchain
* Flashed board with: https://support.intrinsyc.com/projects/snapdragon-flight/files
* Hexagon version: https://developer.qualcomm.com/download/hexagon/hexagon-sdk-v3-linux.bin
* Installed Intrinsyc-provided fc_addon: https://support.intrinsyc.com/projects/snapdragon-flight/files 
* Using px4.config for 210qc

What I've found with this configuration is that the PX4 app built with `make eagle_default` does not activate the ESC controller (none of the four blue blinking LEDs). However, when built with `make eagle_legacy_default` is used to build the firmware, the PX4 app does activate the ESC controller. See the debug outputs for both below.

My questions are:
1. Should this repo be built with `make eagle_legacy_default` for the Snapdragon Flight with Qualcomm ESC controller? Should the other build method work at all?
2. If the other build method should work, what should I do differently?
3. What are the essential differences between using the legacy and non-legacy drivers? What am I losing by using the legacy drivers?

Debug output from firmware built with `make eagle_default`:
> DMSS is connected. Running mini-dm...
> [08500/00]  00:45.312  HAP:63:adsp memory mapped   0155  shmem_qurt.c
> [08500/00]  00:45.355  HAP:61:In dspal_entry  0220  main.cpp
> [08500/00]  00:45.355  HAP:61:adsp memory mapped   0155  shmem_qurt.c
> [08500/00]  00:45.356  HAP:4152:TEST px4muorb_topic_advertised of [mavlink_log] on remote side...  0167  px4muorb.cpp
> [08500/00]  00:45.491  HAP:61:attempting to open the ADSP command file: /dev/fs/px4.config  0184  main.cpp
> [08500/00]  00:45.492  HAP:61:reading commands from /dev/fs/px4.config   0191  main.cpp
> [08500/03]  00:45.495  HAP:54:Error subscribing to qshell_req topic  0079  qshell.cpp
> [08500/03]  00:47.092  HAP:61:Parameter UART_ESC_BAUDRTE not found.  0513  param.c
> [08500/00]  00:48.291  HAP:61:2936459 Reset MPU9250   0089  MPU9250.cpp
> [08500/00]  00:48.355  HAP:60:3000684 IMU temperature initialized to: 57.116341   0521  MPU9250.cpp
> [08500/00]  00:48.356  HAP:61:3002141 additional sensor configuration succeeded   0187  BMP280.cpp
> [08500/02]  00:48.380  HAP:49197:LED: getHandle fail   0279  commander_helper.cpp
> [08500/02]  00:48.380  HAP:49197:LED init failed  1372  commander.cpp
> [08500/02]  00:48.380  HAP:49197:Buzzer: px4_open fail   0132  commander_helper.cpp
> [08500/02]  00:48.380  HAP:49197:Buzzer init failed  1376  commander.cpp
> [08500/02]  00:48.382  HAP:49197:Preflight checks always pass on Snapdragon.  0534  PreflightCheck.cpp
> [08500/00]  00:49.450  HAP:61:PX4 Devices:  0560  vdev.cpp
> [08500/00]  00:49.450  HAP:61:DF Devices:  0573  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /dev/imu0  0583  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /dev/baro0  0583  vdev.cpp
> [08500/00]  00:49.450  HAP:61:Files:  0609  vdev.cpp
> [08500/00]  00:49.450  HAP:61:Active Tasks:  0314  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   dspal      2097663  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   hpwork     2097661  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   lpwork     2097660  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   wkr_hrt    2097659  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   sensors    2097656  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   commander  2097655  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   ekf2       2114038  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   mc_pos_control 2589173  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:   mc_att_control 2114036  0318  px4_qurt_tasks.cpp
> [08500/00]  00:49.450  HAP:61:Devices:  0593  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/_obj_  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_accel0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_gyro0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/parameter_update0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_mag0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/input_rc0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/rc_parameter_map0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_baro0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/differential_pressure0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_control_mode0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/actuator_controls_00  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_correction0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_combined0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/sensor_preflight0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/led_control0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_status0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/actuator_armed0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/safety0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/mission_result0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/geofence_result0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/manual_control_setpoint0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/offboard_control_mode0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_global_position0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_local_position0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_attitude0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_land_detected0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_gps_position0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_command0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/battery_status0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/subsystem_info0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/position_setpoint_triplet0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/system_power0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vtol_vehicle_status0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/cpuload0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_status_flags0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/commander_state0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/airspeed0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/optical_flow0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/distance_sensor0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_vision_position0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_vision_attitude0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/estimator_status0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/wind_estimate0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/ekf2_innovations0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/ekf2_timestamps0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/control_state0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_attitude_setpoint0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_local_position_setpoint0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_global_velocity_setpoint0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/home_position0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/vehicle_rates_setpoint0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/multirotor_motor_limits0  0599  vdev.cpp
> [08500/00]  00:49.450  HAP:61:   /obj/mc_att_ctrl_status0  0599  vdev.cpp
> [08500/00]  00:54.395  HAP:8235:EKF aligned, (pressure height, IMU buf: 21, OBS buf: 16)  0067  control.cpp
> 

Debug output from firmware built with `make eagle_legacy_default`:

> DMSS is connected. Running mini-dm...
> [08500/03]  01:34.176  HAP:63:HAP_debug_v2 weak ref not found, return _rtld_sym_zero@_rtld_objmain  0294  symbol.c
> [08500/03]  01:34.177  HAP:63:HAP_debug_v2 weak ref not found, return _rtld_sym_zero@_rtld_objmain  0294  symbol.c
> [08500/03]  01:34.177  HAP:63:HAP_debug_v2 weak ref not found, return _rtld_sym_zero@_rtld_objmain  0294  symbol.c
> [08500/03]  01:34.177  HAP:63:HAP_debug_v2 weak ref not found, return _rtld_sym_zero@_rtld_objmain  0294  symbol.c
> [08500/00]  01:34.191  HAP:61:In dspal_entry  0220  main.cpp
> [08500/00]  01:34.305  HAP:61:attempting to open the ADSP command file: /dev/fs/px4.config  0184  main.cpp
> [08500/00]  01:34.305  HAP:61:reading commands from /dev/fs/px4.config   0191  main.cpp
> [08500/02]  01:35.546  HAP:61:Error: Parameter UART_ESC_BAUDRTE not found.  0470  param.c
> [08500/00]  01:36.727  HAP:61:2535828 Reset MPU9250   0089  MPU9250.cpp
> [08500/00]  01:36.791  HAP:60:2600081 IMU temperature initialized to: 52.462605   0516  MPU9250.cpp
> [08500/00]  01:36.793  HAP:61:2602002 additional sensor configuration succeeded   0187  BMP280.cpp
> [08500/02]  01:36.806  HAP:8237:LED: getHandle fail   0269  commander_helper.cpp
> [08500/02]  01:36.806  HAP:8237:LED init failed  1341  commander.cpp
> [08500/02]  01:36.806  HAP:8237:Buzzer: px4_open fail   0132  commander_helper.cpp
> [08500/02]  01:36.806  HAP:8237:Buzzer init failed  1345  commander.cpp
> [08500/02]  01:36.808  HAP:8237:Preflight checks always pass on Snapdragon.  0392  PreflightCheck.cpp
> [08500/00]  01:36.815  HAP:4139:EKF IMU buffer length = 21  0365  estimator_interface.cpp
> [08500/00]  01:36.815  HAP:4139:EKF observation buffer length = 16  0366  estimator_interface.cpp
> [08500/02]  01:36.875  HAP:40:task_main_trampoline  0421  uart_esc_main.cpp
> [08500/00]  01:36.875  HAP:40:enter uart_esc task_main  0277  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:39:task_main_trampoline  0178  rc_receiver_main.cpp
> [08500/02]  01:36.875  HAP:39:enter rc_receiver task_main  0184  rc_receiver_main.cpp
> [08500/02]  01:36.875  HAP:40:uart_esc_main parameters_update  0150  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:UART_ESC_MODEL 2  0155  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:UART_ESC_BAUD 250000  0160  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:UART_ESC_MOTOR1 4  0166  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:UART_ESC_MOTOR2 2  0166  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:UART_ESC_MOTOR3 1  0166  uart_esc_main.cpp
> [08500/00]  01:36.875  configuring UART for 4-wire mode, DAL id: 0x2001008  0852  DalUart.c
> [08500/02]  01:36.875  HAP:40:UART_ESC_MOTOR4 3  0166  uart_esc_main.cpp
> [08500/00]  01:36.875  configuring UART for 4-wire mode, DAL id: 0x2001005  0852  DalUart.c
> [08500/02]  01:36.875  HAP:40:initialized ESC Model: ESC_210QC Device: /dev/tty-2 baudrate: 250000bps  0214  uart_esc.cpp
> [08500/00]  01:36.875  HAP:40:Initializing mixer from config file in /dev/fs/mixer_config.mix  0204  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:unable to open the specified file path  0167  file.c
> [08500/02]  01:36.875  HAP:40:Unable to open mixer config file  0228  uart_esc_main.cpp
> [08500/02]  01:36.875  HAP:40:mixer config file not found, successfully initialized default quad x mixer  0249  uart_esc_main.cpp
> [08500/02]  01:36.895  HAP:39:RC timeout expired  0118  spektrum_rc.cpp
> [08500/02]  01:36.932  HAP:8237:REJECT AUTO MISSION  3717  commander.cpp
> [08500/00]  01:37.875  HAP:61:PX4 Devices:  0535  vdev.cpp
> [08500/00]  01:37.875  HAP:61:DF Devices:  0548  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /dev/imu0  0558  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /dev/baro0  0558  vdev.cpp
> [08500/00]  01:37.875  HAP:61:Files:  0584  vdev.cpp
> [08500/00]  01:37.875  HAP:61:Active Tasks:  0314  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   dspal      2097663  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   hpwork     2097661  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   lpwork     2097660  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   wkr_hrt    2097659  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   qshell     2097657  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   sensors    2097656  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   commander  2097655  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   ekf2       2105846  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   mc_pos_control 2572789  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   mc_att_control 2105844  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   uart_esc_main 2097651  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:   rc_receiver_main 2097650  0318  px4_qurt_tasks.cpp
> [08500/00]  01:37.875  HAP:61:Devices:  0568  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/_obj_  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/qshell_req0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/parameter_update0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/sensor_accel0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/sensor_gyro0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/sensor_mag0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/input_rc0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/differential_pressure0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_control_mode0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/rc_parameter_map0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/manual_control_setpoint0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/actuator_controls_00  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/sensor_combined0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_status0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/actuator_armed0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/safety0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/mission_result0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/geofence_result0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/offboard_control_mode0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_global_position0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_local_position0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_attitude0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_land_detected0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_gps_position0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_command0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/battery_status0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/subsystem_info0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/position_setpoint_triplet0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/system_power0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vtol_vehicle_status0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/cpuload0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/commander_state0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/airspeed0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/optical_flow0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/distance_sensor0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vision_position_estimate0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/estimator_status0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/wind_estimate0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/ekf2_innovations0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/sensor_baro0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/control_state0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_attitude_setpoint0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_local_position_setpoint0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_global_velocity_setpoint0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/vehicle_rates_setpoint0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/multirotor_motor_limits0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/rc_channels0  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/actuator_controls_30  0574  vdev.cpp
> [08500/00]  01:37.875  HAP:61:   /obj/mavlink_log0  0574  vdev.cpp
> [08500/00]  01:38.498  HAP:4139:EKF using pressure height - commencing alignment  0412  ekf.cpp
> [08500/00]  01:43.015  HAP:4139:EKF alignment complete  0064  control.cpp
> [08500/02]  03:45.382  HAP:8237:REJECT AUTO MISSION  3717  commander.cpp

**Comment by LorenzMeier** [comment]
@mcharleb could you chime in?

**Comment by mcharleb** [comment]
@Seanmatthews The only drivers for the Qualcomm ESCs are the legacy (binary) drivers. We may have open versions in the future but not currently so eagle_legacy_default is what you want. All the drivers were initially binary thus the "legacy" name. You can compare cmake/configs for the qurt_sdflight_default.cmake and qurt_sdflight_legacy modules to see the differences. You can add any modules you like but will need the platforms/qurt/fc_addon/uart_esc module for the Qualcomm ESC. @jywilson  Let me know if I missed anything.

**Comment by mhkabir** [comment]
Closing in favour of https://github.com/PX4/Firmware/issues/6962
