### ISSUE TITLE
Disable flightmode change on rc input for non-MC vehicles

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#6938]
This is a very bad idea for fixed wings / vtols:
https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L2525-L2546

I understand the logic for MC's but any accidental touch of a stick could send a plane flying a mission of into an unknown direction.

**Comment by LorenzMeier** [comment]
I think we can discuss if this needs to be configurable, but the basic statement is not true. Fixed wing in position control will hold direction and altitude, so the override analogy works the very same way.

**Comment by sanderux** [comment]
Would an airplane not continue to fly straight when such an override occurs? I believe this might be a problem when it goes unnoticed during a mission. The plane could fly quite far possibly beyond reach. Or it could fly in to something like a tree or building if the pilot isnt concious of the fact that control was returned during a mission.

**Comment by sanderux** [comment]
@LorenzMeier we discussed this in the dev call, consensus there was to make it a parameter. I'll add a PR for this if you want.

**Comment by LorenzMeier** [comment]
Thanks, that would be much appreciated!

**Comment by sanderux** [comment]
done https://github.com/PX4/Firmware/pull/7025
