### ISSUE TITLE
How to log flight data from gazebo simulator?

### ISSUE THREAD

**Issue by vinhk** [PX4/Firmware#6948]
Is there a way to log flight data of gazebo iris with optical flow?

I am using the `make posix gazebo_iris_opt_flow` for flight simulation. I am hoping there is a way to log flight data similar to how pixhawk .px4 log files are created in the SD card.

Thank you

**Comment by mhkabir** [comment]
They are created in the filesystem (rootfs) created in the build folder. (build_posix_sitl_default) Use grep to search for them.
