### ISSUE TITLE
I can't make the flow noise model .

### ISSUE THREAD

**Issue by suruonuo** [PX4/Firmware#6952]
I have some troubles in correcting the optical flow parameters, According the  Flow+Noise+Modelling.pdf ,I  can't  collect the  normal data for model。 the param v and h is very difficult control。

**Comment by dagar** [comment]
Hi @suruonuo 
Can you use http://discuss.px4.io/ for PX4 questions? Github is for reporting bugs and requesting features in the autopilot firmware.
