### ISSUE TITLE
How to test out PX4 firmware modified code without Pixhawk board? 

### ISSUE THREAD

**Issue by vinhk** [PX4/Firmware#6966]
Is there a way to test out PX4 firmware modified code using Gazebo? I would like to see the performance of the quadcopter. I know there is a mavros gazebo simulator. But how can I verified that the code that I modified on Px4 Firmware is working correctly?

Thank you

**Comment by LorenzMeier** [comment]
How about you start with http://dev.px4.io and look through the SITL / Simulation section?
