### ISSUE TITLE
Throttle Percentage in FW Mode Doesn't Register in FW Mode via MinimOSD.

### ISSUE THREAD

**Issue by rollysing** [PX4/Firmware#6974]
I use MInimOSD in Telem2 with both QuadRanger and DeltaQuad airframes with v1.5.x. The throttle percentage displays during MC mode but goes to 0% when transitioned to FW mode. It only starts registering again after switching back to MC mode. (see attached).

MC Mode
![mc mode](https://cloud.githubusercontent.com/assets/20650795/24675299/9e56f3b4-194c-11e7-9aae-f8b3fefd20b6.JPG)

FW Mode
![fw mode](https://cloud.githubusercontent.com/assets/20650795/24675303/a48bf2a2-194c-11e7-952d-f7ce2f1ce3bd.JPG)

Also, just in case it may be related, the Flight Mode displayed is Manual and doesn't change with the actual flight as it's reported in QGC.

Is this just a setting/ parameter issue or something else in the code?

You can see it in action at about 2:23 of this video:
https://www.youtube.com/edit?o=U&video_id=uKt34DzFWXM

**Comment by dagar** [comment]
I believe this is Mavlink VFR_HUD only publishing throttle from the first actuator group. https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_messages.cpp#L1022
It either needs to be aware of VTOL and publish the correct throttle, or use attitude setpoint thrust.
