### ISSUE TITLE
Gyro calibration fails if gyro0 update rate is faster than others

### ISSUE THREAD

**Issue by NaterGator** [PX4/Firmware#6998]
Mostly I just wanted to get this issue logged so I don't forget. Currently working on bringup of a new board that is using gyros that operate significantly faster than the rest of redundant MEMS sensors. 

The gyro calibration data capture loop [paces timing](https://github.com/PX4/Firmware/blob/94ef3db4079e52e6d9d541d766c9a7d08acfb6d8/src/modules/commander/gyro_calibration.cpp#L105-L106) based on the update rate of the first gyro, which in this case means the other gyros are starved for sufficient samples and the [calibration fails](https://github.com/PX4/Firmware/blob/94ef3db4079e52e6d9d541d766c9a7d08acfb6d8/src/modules/commander/gyro_calibration.cpp#L178-L187) reality checking while generating results.

**Comment by mhkabir** [comment]
Done.
