### ISSUE TITLE
cannot find px4fmu-v2_lpe

### ISSUE THREAD

**Issue by nancy03610** [PX4/Firmware#6999]
I want to use local position estimator with pure optical flow. And I read some people's common says that you should upload px4fmu-v2_lpe. But I cannot find this file in the firmware. After all, I can find the px4fmu-v2_default, so I uploaded it instead. Is it the latest version of px4fmu-v2_lpe? However, I cannot get optical flow to work with it in LPE, and cannot find any param about enable optical flow. If I still need px4fmu-v2_lpe, where can I download it?

**Comment by dagar** [comment]
Hi @nancy03610 

Here's a link to the px4fmu-v2 build with LPE. https://s3.amazonaws.com/px4-travis/Firmware/master/px4fmu-v2_lpe.px4

We haven't updated QGC to handle this extra px4fmu-v2 build yet.
