### ISSUE TITLE
How can I tune Px4 with Px4Flow data to give better hovering?

### ISSUE THREAD

**Issue by vinhk** [PX4/Firmware#7002]
I am able to see Px4Flow data into the Pixhawk but there is still hovering issue as it tends to drift. I am hoping there is a documentation similar to one in Arducopter: http://ardupilot.org/copter/docs/common-px4flow-overview.html

**Comment by ChristophTobler** [comment]
You have to tune the position controller. `MPC_Z_VEL_P/I/D` etc.

**Comment by vinhk** [comment]
@ChristophTobler is there a way to do testing like so 
![screenshot from 2017-04-10 23 28 35](https://cloud.githubusercontent.com/assets/17210431/24891716/94d60fca-1e45-11e7-9075-563791a6517f.png)

Where users get to walk their quad around without propeller and do row for 1 session and pitch for another session. Those file will be use to log as above picture is shown. This would make tuning much easier.

**Comment by tomatac** [comment]
What firmware are you using?
Do you use LPE? If so what is your LPE_FUSION setting?
I am geting POSITION CONTROL REJECTED (Firmware 1.6 - LPE version, PX4FLOW + Lidar Lite 3).

**Comment by vinhk** [comment]
@tomatac I am using LPE as well but currently unable to see data from pwm lidar lite v3. For LPE_FUSION, I have it at 242 i think. I have been through your issue forum about rejecting mode for position control. I am not sure why. Mine is not rejecting but it drifts

**Comment by mhkabir** [comment]
@vinhk Use the i2c interface of Lidar Lite v3. It now works well. You might need to modify the startup script to test.

**Comment by vinhk** [comment]
@mhkabir which startup script part should I modified?

**Comment by tomatac** [comment]
Does the raw data from the Lidar get recorded in the flight log? I using PWM.

**Comment by mhkabir** [comment]
PWM for Lidar Lite is currently broken.

**Comment by tomatac** [comment]
Is it broken in 1.6 or the master? Is there a version where it works?
