### ISSUE TITLE
how to disable GPS in Gazebo simulator?

### ISSUE THREAD

**Issue by vinhk** [PX4/Firmware#7005]
Is there a way to disable gazebo GPS functionality?

**Comment by mhkabir** [comment]
`gpssim stop`

**Comment by Coderx7** [comment]
@mhkabir Hi, please excuse my ignorance but where should we enter this command? when I enter it in terminal it says
```
Command 'gpssim' not found, did you mean:

  command 'gpsim' from deb gpsim
  command 'lpssim' from deb mcrl2

Try: sudo apt install <deb name>

```

**Comment by rrajnidhi** [comment]
Hi Did u found the answer for stoping GPS simulaion on GAZEBO ?

**Comment by Coderx7** [comment]
@rrajnidhi Hi, I searched alot after this and it seems the only way to have control over the gps simulation, is to use HITL mode, which basically means, to add your FCU, and then using QGC e.g disable its GPS, then Gazebo will use the sensors available on the FCU and simulate everything else. 
I could not find any SITL solution where we can simply disable/enable GPS in gazebo. that would be great. I'm not sure if its possible or HITL is the only way.

**Comment by rrajnidhi** [comment]
@Coderx7 thanks a lot for the idea, will try that way too.

**Comment by Jaeyoung-Lim** [comment]
@rrajnidhi @Coderx7 You can simply remove the gps from the model: https://github.com/PX4/PX4-SITL_gazebo/blob/25138e803ee8525ee5fe4e6d511506e88e3f819c/models/iris/iris.sdf.jinja#L421-L429

**Comment by Coderx7** [comment]
@Jaeyoung-Lim Thanks a lot , I'll give it a try and see if that solves it ( I recall messing around but I'm not sure if I did this already or not, nonetheless, thanks a lot greatly appreciate it)
