### ISSUE TITLE
ATT.Pitch became more and more big, vehicle position draft

### ISSUE THREAD

**Issue by liang-tang** [PX4/Firmware#7021]
ATT.Pitch  got big and big, from 0.025 to 0.1 almost in five minutes, the vehicle horizontal position draft more and more quickly , so any issure with my multicopter? 
(software version: 1.5.5
hardware pixhawk)
![screenshot from 2017-04-11 18-48-02](https://cloud.githubusercontent.com/assets/16251761/24905922/465565f0-1ee8-11e7-8a8b-daa02a9b9403.png)

**Comment by liang-tang** [comment]
Log
http://logs.uaventure.com/view/nwpou7XbSC97DMy226bfYU

**Comment by bresch** [comment]
Did you check if your compass is correctly pointing towards the magnetic North?

**Comment by liang-tang** [comment]
i haven't check it ... how can i  comfirm this issure caused by compass direction.?

**Comment by bresch** [comment]
Let me explain a bit: the attitude estimation and control look fine. The pitch reference is moving with the X position error. My guess is that your position controller is correcting in the wrong direction. (However, I'm surprised that it does not diverge faster and why it is only visible on one axis).
So, to verify this, just go outside and compare the heading displayed by QGC with the compass of your smartphone or with a known geographic reference.

And if you are sure that you can swith back to manual and pilot it manually, you can try to move the pitch stick of your remote to see if the quad position diverge (be careful to switch back quickly to manual). If you are not sure to be able to do this, don't try.

**Comment by liang-tang** [comment]
thanks a lot, i will check it before takeoff.

**Comment by bresch** [comment]
@liang-tang  Any news?

**Comment by liang-tang** [comment]
everything works well.
