### ISSUE TITLE
Got Waypoint below home warning with v3.1.3

### ISSUE THREAD

**Issue by ashwanisihag** [PX4/Firmware#7023]

**Comment by dagar** [comment]
@ashwanisihag can you provide logs or screenshots? Was this in simulation or flying outdoors? Did you check the altitude of your waypoints?

**Comment by LorenzMeier** [comment]
This is not a PX4 release number.

**Comment by ashwanisihag** [comment]
This is qGroundControl number and PX4 with latest firmware. 
Regards
--------------------------------------------
On Wed, 12/4/17, Lorenz Meier <notifications@github.com> wrote:

 Subject: Re: [PX4/Firmware] Got Waypoint below home warning with v3.1.3 (#7023)
 To: "PX4/Firmware" <Firmware@noreply.github.com>
 Cc: "ashwanisihag" <ashwanisihag@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Wednesday, 12 April, 2017, 5:14 AM
 
 This is not a PX4 release
 number.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ashwanisihag** [comment]
Hi,

I was flying outdoor, set all altitudes as 8 meters, suddenly when it was approaching way point first, it landed and warning came that "waypoint below home".

Will test once more to duplicate it.

Regards

--------------------------------------------
On Tue, 11/4/17, Daniel Agar <notifications@github.com> wrote:

 Subject: Re: [PX4/Firmware] Got Waypoint below home warning with v3.1.3 (#7023)
 To: "PX4/Firmware" <Firmware@noreply.github.com>
 Cc: "ashwanisihag" <ashwanisihag@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, 11 April, 2017, 9:53 PM
 
 @ashwanisihag can you
 provide logs or screenshots? Was this in simulation or
 flying outdoors? Did you check the altitude of your
 waypoints?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
