### ISSUE TITLE
Possible Bug in HIL_STATE_QUATERNION handling

### ISSUE THREAD

**Issue by mzahana** [PX4/Firmware#7033]
Hi,
@TSC21 and I are developing HIL plugins in MAVROS. This is to allow any ROS-compatible simulator to be used in HIL setup.

In the decoding of HIL_STATE_QUATERNION msg, in PX4 firmware, specifically the ```vehicle_global_position```,
https://github.com/PX4/Firmware/blob/ecb2511a7bbad094bff23dd95036eda0656778f0/src/modules/simulator/simulator_mavlink.cpp#L402-L413
altitude is divided by ```1E3```, but ```lat/lon``` are not scaled down properly. In the msg definition,
https://github.com/PX4/Firmware/blob/912ed98a28022504ef3ec4bf1bce0fe041f83ac4/msg/vehicle_global_position.msg

```lat/lon/alt``` are assumed to be in deg/deg/meters. And, they are supposed to be received in deg 1E7 and meters 1E3 according to 
https://pixhawk.ethz.ch/mavlink/#HIL_STATE_QUATERNION

So, I guess that 
https://github.com/PX4/Firmware/blob/ecb2511a7bbad094bff23dd95036eda0656778f0/src/modules/simulator/simulator_mavlink.cpp#L407-L408
should be divided by 1E7.

Also the ```vehicle_global_position``` msg does not have ```timestamp``` field,

So, possibly another mistake here,
https://github.com/PX4/Firmware/blob/ecb2511a7bbad094bff23dd95036eda0656778f0/src/modules/simulator/simulator_mavlink.cpp#L404

Thanks.

**Comment by mhkabir** [comment]
> Also the vehicle_global_position msg does not have timestamp field,

> So, possibly another mistake here,
https://github.com/PX4/Firmware/blob/ecb2511a7bbad094bff23dd95036eda0656778f0/src/modules/simulator/simulator_mavlink.cpp#L404

Timestamp field is autogenerated. All messages have it.

**Comment by mzahana** [comment]
I see. What about lat/lon scaling?

**Comment by mhkabir** [comment]
Yes, that looks incorrect. Can you please send in a pull request?

**Comment by mzahana** [comment]
A PR is created https://github.com/PX4/Firmware/pull/7039

**Comment by mzahana** [comment]
#7039
