### ISSUE TITLE
Update local_position/odom at higher rate

### ISSUE THREAD

**Issue by marcelinomalmeidan** [PX4/Firmware#7034]
Hi,

I am currently using the Snapdragon Flight with LPE to fuse data from Vicon with the onboard sensors.
It seems like the estimation is working (somewhat), but I can't debug very well because all I get in local_position/odom through MAVROS is an update at 2Hz.
Is there any way to change the update rate of this topic? I've seen that the SITL example with gazebo updates the same topic at 250Hz, which is a lot better to use.

Is there any way of changing the update rate of this topic?

**Comment by jgoppert** [comment]
On my system it runs at about 30 hz. On the real vehicle. You can set the rate in the startup script using the "mavlink stream" command. Also make sure you have the baudrate for your onboard computer set to 921600.
