### ISSUE TITLE
Snapdragon Flight params sync and save does not work

### ISSUE THREAD

**Issue by bharath374** [PX4/Firmware#7035]
The following issues were observed on a very recent test of the latest PX4 code with the Snapdragon Flight platform:
- Parameters that get updated from QGroundControl do not persist across reboots. And no parameter file gets created in the /usr/share/data/adsp folder on target.
- Parameters do not sync between the apps processor and aDSP. When a parameter is updated from QGroundControl, it does not seem to reach the flight stack on the aDSP.

**Comment by LorenzMeier** [comment]
Since this is passing through muORB it would be great if someone at Qualcomm could look into this. I also think that @darioxz can help with this in the long-run. It would be great if you could share your Jenkins setup with him, as he is building a whole hardware-test farm with Jenkins right now.

**Comment by jywilson** [comment]
@LorenzMeier I am looking at this now.  It's a top priority problem for us.  

I will update this post as I make progress.

**Comment by jywilson** [comment]
@LorenzMeier 
This problem is fixed in PR: https://github.com/PX4/Firmware/pull/7084

**Comment by LorenzMeier** [comment]
Fixed.
