### ISSUE TITLE
Is QGC master code ready for EKF2 testing using Px4Flow for stable hovering?

### ISSUE THREAD

**Issue by vinhk** [PX4/Firmware#7045]
I am wondering if the master firmware in QGC is ready to use EKF2 for stable hovering test with Px4FLow. If not, then how about Github master firmware. Please clarify this for me so I can test this today.
Thank you

**Comment by mhkabir** [comment]
There is no "QGC master" and "Github master". There is just "master" which refers to the latest code. @ChristophTobler will be able to confirm whether we have full EKF2 optical flow support on master.

Please refrain from opening multiple issues for the same topic, or we will close them.
