### ISSUE TITLE
HILstar (Xplane) model throwing sensor errors with recent PX4 Master

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#7050]
I just started HIL testing recent PX4 Master firmware (with small fixed wing tweaks).  The Xplane HIL mostly works and I can get it to fly, however, I get a lot of sensor errors thrown in QGC.  I change the plane model and calibrated the sensors and then changed back to HILstar(Xplane) - still get these sensor errors.  Pics below.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/12117027/25055449/76a71f2c-2128-11e7-840d-64300e22b5c1.png)

![image](https://cloud.githubusercontent.com/assets/12117027/25056110/627001f0-212c-11e7-94bf-b3bbe9f1994f.png)
![image](https://cloud.githubusercontent.com/assets/12117027/25056197/e7874362-212c-11e7-9f94-48fb44cd157b.png)

**Comment by dagar** [comment]
The first screenshot is QGC checking params that aren't set. Open another issue over there.

The timeout is from the PX4 sensors module and already relaxed for HIL> https://github.com/PX4/Firmware/blob/master/src/modules/sensors/voted_sensors_update.cpp#L86

@bkueng can we further increase the accel and gyro timeout for HIL?

**Comment by DonLakeFlyer** [comment]
I won't go into a rant about how this optional param stuff has been making be crazy for years.

**Comment by bkueng** [comment]
> @bkueng can we further increase the accel and gyro timeout for HIL?

Sure. Increase to however large is needed. But if there's really so much jitter, flight behavior will be affected negatively.

**Comment by dagar** [comment]
Does it happen continuously, or just after the initial connection?

**Comment by Antiheavy** [comment]
Sensor TOUT warnings happen:

- sometimes with initial connection, but not always.

- almost always when attempting to Arm/takeoff.
![image](https://cloud.githubusercontent.com/assets/12117027/25152910/3fbad8b6-2450-11e7-93a3-7759b6381529.png)

- occasionally throughout the HIL flight, sometimes when uploading missions.
![image](https://cloud.githubusercontent.com/assets/12117027/25153035/b68a393c-2450-11e7-832a-9de2243b06c5.png)

- often when landing in HIL:
![image](https://cloud.githubusercontent.com/assets/12117027/25153634/d9e4edd0-2452-11e7-99a8-0e6ec4143087.png)


- almost always when disconnecting from the HIL sim (expected i suppose?).
