### ISSUE TITLE
Flow Quality drops when change mode.

### ISSUE THREAD

**Issue by nancy03610** [PX4/Firmware#7053]
I am using px4flow+sonar. I did a flight test today. My quad couldn't hold position but drifted away. 
I set LPE_FUSION to fuse optical flow, fuse land detector, pub agl as lpos down, flow gyro compensation and fuse baro. I took off with manual mode then turned to position mode and stabilized mode. Neither of them could help me hold the position. I did this test outdoor, and there was a little wind.
What I thought may cause this was in the log every time I changed flight mode there was a drop in flow quality. See the picture below.
![screen shot 2017-04-15 at 11 23 13 am](https://cloud.githubusercontent.com/assets/26383945/25060367/f82513a6-21cd-11e7-9c72-227df2c922cc.png)
I don't know what cause this problem or how to fix this. Is there any other param I can set to get a success result in position hold?
Here is my log: http://logs.uaventure.com/view/tQT6sPLamBBEnzSA4MMCTR
@jgoppert @mhkabir

**Comment by jgoppert** [comment]
When you changed modes it was causing an oscillation, this is why flow quality degraded. You can't have large rotation rates. You can tray lowering roll/pitch rate max.

http://logs.uaventure.com/view/tQT6sPLamBBEnzSA4MMCTR#IMU_Gyro_PLOT
