### ISSUE TITLE
I can't run make posix_sitl_default gazebo

### ISSUE THREAD

**Issue by chuyueqiang** [PX4/Firmware#7058]
hi,everybody.i want to do the gazebo simulation inferfacing to ROS,what i do is follow the page [https://dev.px4.io/simulation-ros-interface.html](url) ,but when i do the command 
`no_sim make posix_sitl_default gazebo`
the console output
![image](https://cloud.githubusercontent.com/assets/13418725/25071034/02db4ba4-22e0-11e7-895c-67bae1f028ce.png)
the OS is ubuntu x64 14.04
ROS rev is indigo
gazebo rev is 7
so,please help me to slove the problem,thank you

**Comment by mhkabir** [comment]
You're missing protobuf.

Fix : 
`sudo apt-get install libprotobuf-dev`.
