### ISSUE TITLE
no_sim=1 make posix_sitl_default gazebo not work

### ISSUE THREAD

**Issue by chuyueqiang** [PX4/Firmware#7059]
hi,everybody.i want to do the gazebo simulation inferfacing to ROS,what i do is follow the page https://dev.px4.io/simulation-ros-interface.html ,but when i do the command
no_sim=1 make posix_sitl_default gazebo
the console output
![image](https://cloud.githubusercontent.com/assets/13418725/25071145/9baa9996-22e2-11e7-8231-06f4b02bc123.png)

the OS is ubuntu x64 14.04
ROS rev is indigo
gazebo rev is 7
i have already installed libprotobuf-dev,but it still not work
so,please help me to slove the problem,thank you

**Comment by mhkabir** [comment]
Try `sudo apt-get install protobuf-compiler` in addition.

**Comment by mhkabir** [comment]
Did you even follow this page? https://dev.px4.io/starting-installing-linux.html

**Comment by chuyueqiang** [comment]
@mhkabir yes,all the page command i have done.and the protobuf-compiler i have already installed.but i try again just now,it also doesn't work.

**Comment by dagar** [comment]
Did you install the dependencies before you tried to build the first time? I'm wondering if the gazebo build is stuck without having found the protobuf compiler. Try rebooting to make sure your path is updated. Then in the PX4 source do `make distclean`, then try to build again.

**Comment by mhkabir** [comment]
@chuyueqiang Updates? Otherwise we will close this.

**Comment by LorenzMeier** [comment]
Should be fine.
