### ISSUE TITLE
tailsitter drop down

### ISSUE THREAD

**Issue by MikeWellC** [PX4/Firmware#7066]
http://logs.px4.io/plot_app?log=3afcc56c-5b9d-415c-ab46-43c8fe700b6e
my tailsitter fell from the air,I adjusted this parameter FW_P_TC to 0.4 and then drop down.I have some questions.
1.What is the relationship between the magnetic field and the thrust?
I understand that thrust should not affect the magnetic field.is it?
2.What is the reason my tailsitter is falling off?
3.How should I adjust the parameters?

**Comment by dagar** [comment]
Hi @MikeWellC, sorry for the delayed response.

Have you had successful tailsitter flights?

Is this extreme vibration from your motor?

![image](https://user-images.githubusercontent.com/84712/27597536-a4d79ff6-5b30-11e7-8ea5-37f4599bf858.png)

**Comment by MikeWellC** [comment]
thank  @you，I found the reason that my pixhawk was loose and vibrated inside the tailsitter。

**Comment by MikeWellC** [comment]
Hi @dagar, thank you，I found the reason that my pixhawk was loose and vibrated inside the tailsitter。

**Comment by dagar** [comment]
Glad to hear you found the problem.
