### ISSUE TITLE
px4fmu_V2 upgrade issue: nsh: vmount: command not found

### ISSUE THREAD

**Issue by lovettchris** [PX4/Firmware#7085]
When I upgrade the firmware on my Pixhawk v2 to the latest bits (sync'd today), clean clone, & build of master branch, make px4fmu-v2_default, I get the following boot error:
```
ERROR [param] Parameter MNT_MODE_IN not found
nsh: vmount: command not found
```
This happens on multiple pixhawks.  If I go back to latest stable build using QGroundControl then it boots fine.

Curiously if I add the drivers/vmount driver in the cmake/configs/nuttx_px4fmu-v2_default.cmake, then it boots fine.  So what do I need to do to make it boot without this driver since it is supposed to be commented out now... ?

**Comment by bkueng** [comment]
Fix is in  #7088, if there's enough Flash.
