### ISSUE TITLE
FCU:[lpe] gps fault 0.00120141 0.904114 0.156308 0.10

### ISSUE THREAD

**Issue by chuyueqiang** [PX4/Firmware#7089]
hi,everybody,i just simulate the in the ros and gazebo,use the command
make posix_sitl_default gazebo
then i use the QGC to make the MAV arm and takeoff, but after send the takeoff command the MAV takeoff and dropped ,the mavros log shows FCU:[lpe] gps fault 0.00120141 0.904114 0.156308 0.10
please help me ,thank you!

**Comment by dagar** [comment]
Can you try running without the gazebo gui?

    HEADLESS=1 make posix_sitl_default gazebo_iris

**Comment by jgoppert** [comment]
Do you have a log? The gps fault is just saying the gps error is higher than expected.

**Comment by LorenzMeier** [comment]
Closing as stale.
