### ISSUE TITLE
Latest 1.6.0 RC release not supported on Pixhawk 3 Pro board (Drotek)

### ISSUE THREAD

**Issue by HuguesD** [PX4/Firmware#7105]
Hello,

Just got a recently produced Pixhawk 3 Pro board from Drotek. The following error happens when attempting to load the firmware (px4fmu-v4_default.px4)
"downloaded firmware board id does not match hardware board id: 11!=13"

I'm aware that board id 11 is a pixracer board. Board id of the Drotek PixhawkV3 is 13. what firmware is compatible with this board id 13 ?

![sans titre 1](https://cloud.githubusercontent.com/assets/13796161/25304707/e7b505ae-276c-11e7-9ed4-e4464fdcd543.jpg)

**Comment by mhkabir** [comment]
You need the `px4fmu-v4pro_default` target. `v4` is Pixracer.

**Comment by HuguesD** [comment]
Hello Kabir,

 

Thx. 

where can I find this version of the firmware, It is not on Github with the other PX4 firmwares ?

 

De : Kabir Mohammed [mailto:notifications@github.com] 
Envoyé : samedi 22 avril 2017 15:16
À : PX4/Firmware
Cc : HuguesD; Author
Objet : Re: [PX4/Firmware] Latest 1.6.0 RC release not supported on Pixhawk 3 Pro board (Drotek) (#7105)

 

You need the px4fmu-v4pro_default target. v4 is Pixracer.

**Comment by mhkabir** [comment]
The Pixhawk 3 Pro is not fully supported by the user-facing side of things yet. It is a developer system and is actively being worked on and fixed.

You can build and flash the firmware from the repo. Instructions here : https://dev.px4.io/en/

**Comment by HuguesD** [comment]
thx
