### ISSUE TITLE
Test and document camera test trigger

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#7109]
We should make sure that this button in QGC daily works:

![f7c1481a-2026-11e7-85f2-75d55a8858bd](https://cloud.githubusercontent.com/assets/1208119/25314056/82bd9cbc-283c-11e7-8fd4-3d1c1a52cc2e.png)

I have verified that the command arrives here:
https://github.com/PX4/Firmware/blob/3fda79ef8b05493ded0037c6bc5305f2b2563f72/src/modules/mavlink/mavlink_receiver.cpp#L171-L184

Needs further tracing through the system to ensure its being properly published and handled in the trigger module.

**Comment by LorenzMeier** [comment]
When this gets fixed it should work again: https://github.com/mavlink/qgroundcontrol/issues/5045

**Comment by mhkabir** [comment]
Fixed.

**Comment by mhkabir** [comment]
Reopening till I get the docs in.

**Comment by LorenzMeier** [comment]
@mhkabir Where is this standing?

**Comment by mhkabir** [comment]
This is done from my side : https://dev.px4.io/en/tutorials/camera_trigger.html

I still need a new geotagging implementation in QGC with the new logger to document that part.

**Comment by LorenzMeier** [comment]
I'm closing this since the geotagging is handled in a different issue.
