### ISSUE TITLE
Geotagging with new logger

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#7118]
We will need to update QGC and the geotagging scripts in Tools to work with the new logger, now that it is the new default.

@dagar @bkueng Would you be able to have a look at what needs to be done? Python is not my forte. :P

**Comment by LorenzMeier** [comment]
@DonLakeFlyer What is the geotagging workflow like right now? Can you point @bkueng at the right location in QGC for what needs to be changed?

**Comment by LorenzMeier** [comment]
Duplicate of #7164 now.
