### ISSUE TITLE
about stm32 CCM

### ISSUE THREAD

**Issue by zouboan** [PX4/Firmware#7126]
In mainpage of nuttx
http://www.nuttx.org/doku.php?id=wiki:howtos:stm32-ccm-alloc

**The STM32 F2, F3, and F4 families have a special block of SRAM available call CCM (Core Coupled Memory). This memory has the drawback that it cannot be used for STM32 DMA operations.

By default, the CCM memory is lumped in with the rest of memory when the NuttX heaps are created. But this can be a problem because it will be a toss of the coin if non-DMA-able CCM memory or other DMA-able memory gets returned when malloc() is called. That usually does not matter but it certainly does make a difference if you are allocating memory that will be used for DMA! In that case, getting CCM memory for you DMA buffer will cause a failure.
CONFIG_STM32_CCMEXCLUDE

There is a configuration option called CONFIG_STM32_CCMEXCLUDE that can be used to exclude CCM memory from the heap. That solves the problem of getting CCM memory when you want to allocate a DMA buffer. But then what do you do with the CCM memory? Do you let it go unused?
CCM Allocator

In order to make use of the CCM memory, a CCM memory allocator is available. This memory allocator is automatically enabled when the following options are set:

    CONFIG_STM32_CCMEXCLUDE - CCM memory is excluded from the normally heap, and
    CONFIG_MM_MULTIHEAP - Support for multiple heaps is enabled.

Under those conditions, the CCM memory allocator is enabled and the allocator interfaces prototyped in the arch/arm/src/stm32/stm32_ccm.h are available (NOTE: These interfaces are, technically, not prototyped since they are really provided via C pre-processor macros).** 

PX4 using DMA1 and DMA2 but  didn't do anything about CCM
why?

**Comment by davids5** [comment]
See https://github.com/PX4/Firmware/blob/master/src/drivers/boards/common/board_dma_alloc.c#L98

All other DMA is also done to static buffers not in the CCM. 

There is also a preflight check done in the SD card driver but the memory is from the board_dma_alloc.so DMA is always used.
