### ISSUE TITLE
Mavlink publishing of current repeat count of a MAV_CMD_DO_JUMP

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#7130]
Before any GCS can integrate or display this information it needs to be published.
I dont think this information is currently available or supported in the mavlink protocol

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/issues/3874

**Comment by dagar** [comment]
Closing as duplicate of https://github.com/PX4/Firmware/issues/3874.
