### ISSUE TITLE
VTOL - motors from turning off in FW 

### ISSUE THREAD

**Issue by OJdoesIt** [PX4/Firmware#7131]
My aircraft has a Y3 motor config. While in Manual mode (for testing), when I switch from MC -> FW, all the motors turn off. If I move the throttle, the front motors start to spin again, basically reacts to the throttle. When I switch back to MC, all the motors automatically turn back on.
How can I prevent the motors from turning off when in FW mode? I'm also using QGC.

**Comment by dagar** [comment]
Which airframe did you choose?

**Comment by OJdoesIt** [comment]
I am using my custom airframe, which used mixer adapted from Eflite Convergence. But instead of elevons, I use ailerons. I also made the adjustment within the mixer.

**Comment by dagar** [comment]
Rereading your comment again, that's exactly what should be happening. Manual mode FW is like RC, with all the controls passed through. If you used a mode like altitude control then the throttle would be automatically set to maintain airspeed and altitude.

**Comment by OJdoesIt** [comment]
I just tested by switching to Altitude mode and and the motors stop spinning in FW. The throttle stick has no effect neither. Is there a parameter I'm missing?

**Comment by dagar** [comment]
No throttle at all in manual MC? The motors are still spinning at idle though?

In FW altitude control mode the throttle will stay at idle (a param) if the vehicle thinks it's landed. The throttle stick is now sending airspeed commands.

**Comment by OJdoesIt** [comment]
I just tested the manual MC and it works. I just didn't work when I had no GPS signal. I'll test the FW issue and get back to you.

**Comment by dagar** [comment]
It sounds like this is more of an issue with the autopilot not providing good feedback? If you can post thorough details we can improve it.
