### ISSUE TITLE
Missing camera triggers in distance based triggering

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#7136]
It seems PX4 is occasionally missing camera triggers in distance base triggering.  We've seen this happen both in real flight testing and also in HIL simulation.   FMUv4 based hardware, MAVlink compatible camera on Telem2.  Any ideas why we might be seeing this or what we could look into to further diagnose?

Actual flight:
![image](https://cloud.githubusercontent.com/assets/12117027/25442205/0a7aefae-2a6a-11e7-86d5-4c1679aa50e3.png)

HIL sim flight:
![image](https://cloud.githubusercontent.com/assets/12117027/25442113/c59bf09a-2a69-11e7-9cfd-1df6f4121f2e.png)

Another HIL sim flight:
![image](https://cloud.githubusercontent.com/assets/12117027/25442265/304f0968-2a6a-11e7-87fb-ee949297c0dc.png)

**Comment by mhkabir** [comment]
Is this in mission mode ?

**Comment by mhkabir** [comment]
It would be good to debug this over a call or IM. Can we Skype?

**Comment by Antiheavy** [comment]
yep

**Comment by mhkabir** [comment]
I'm 'kabiriris' on Skype.

**Comment by dagar** [comment]
Are these plots from autopilot logs or camera?

**Comment by LorenzMeier** [comment]
Adding to Daniel: Can you share an autopilot log from one of these plots?

**Comment by Antiheavy** [comment]
The plots above are from our camera log.  Attached are the SDcard logs from the two HIL missions above.

[HIL-logs-maybe-missing-camera-triggers.zip](https://github.com/PX4/Firmware/files/959743/HIL-logs-maybe-missing-camera-triggers.zip)

**Comment by mhkabir** [comment]
> The plots above are from our camera log.

Hmm, that seems suspect. We could potentially be losing trigger packets over the link, and thus they come up as 'missing' triggers. I will add logging for the trigger uORB message on a branch (we don't log those ATM) and send you a link/binaries for testing in HIL. You would need to use the new logger.

**Comment by mhkabir** [comment]
Ok we aren't really missing trigger events on the PX4 side. This is the trigger sequence number plotted against time. I realised that @Antiheavy's sdlog2 logs also have the trigger events logged. I added it at some point and then forgot :P  

![image](https://cloud.githubusercontent.com/assets/5557676/25458527/8c053168-2ada-11e7-9493-443631a9021d.png)

**Comment by LorenzMeier** [comment]
@mhkabir So the conclusion is that we're not dropping trigger events but some drop on the way to the ground?

**Comment by LorenzMeier** [comment]
@Antiheavy Are you manually enabling the "CAMERA_TRIGGER" trigger message somewhere? If you do, how does the line look like? What is your telemetry link?

**Comment by mhkabir** [comment]
@LorenzMeier after the discussion with @Antiheavy, it seems that the companion link to the camera gets throttled because it's running only at 57600 baud.

**Comment by Antiheavy** [comment]
Our camera talks to the FMUv4 over telem2 UART that we have set to Companion 57600.  We look for DO_DIGICAM_CONTROL messages and execute triggers based on those.  Next week we hope to set up a test to figure out exactly where the messages are getting lost.  Will report back when we know more.

**Comment by mhkabir** [comment]
You must have some customization on your firmware side to send `DO_DIGICAM_CONTROL` messages?

You should use the `CAMERA_TRIGGER` message instead, which should be sent without throttling and by default : https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L2043-L2044

**Comment by dagar** [comment]
I don't think this is a PX4 issue. Let's followup on skype for mavlink debugging.

**Comment by Antiheavy** [comment]
For what it is worth, we found the telem2 serial buffer was overflowing with the default telemetry.  Dialing back the data rate and number of messages seems to have fixed this - at least in HIL sim.  We will fly it soon.

**Comment by mhkabir** [comment]
@Antiheavy We also added a display for camera trigger points in PX4 Flight Review (logs.px4.io) now, so you can actually see where the triggering system commands a shot if you upload the log.
