### ISSUE TITLE
VTOL optimize cpu usage

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#7146]
FW pos ctl isnt running during MC or transition:
https://github.com/PX4/Firmware/blob/545458a6872fd5f748a891c36900f0ab1e6a9140/src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp#L1095-L1099

FW att ctl doesnt run completely during MC or transition:
https://github.com/PX4/Firmware/blob/c5e0bf1c2f4f2cfbc3aa95bfbb14c7b45778b1e0/src/modules/fw_att_control/fw_att_control_main.cpp#L903-L905

But MC pos and att stay active throughout the flight, this results in unnecessarily high cpu consumption:
![image](https://cloud.githubusercontent.com/assets/14801663/25506665/0c8a8de2-2ba8-11e7-8b87-e73adf665909.png)

I propose we employ a similar method in MC att and pos ctl to reduce the load

**Comment by dagar** [comment]
@sanderux let's think about this as part of https://github.com/PX4/Firmware/issues/6856 and https://github.com/PX4/Firmware/issues/4845

I'm far more concerned with peak usage at critical times like transition.
