### ISSUE TITLE
ulog is not working properly on MindPX v2.8

### ISSUE THREAD

**Issue by mzahana** [PX4/Firmware#7150]
Hi,

I am using MindPX v2.8 that is bought very recently. I am using it on Hexarotor, and it flies ok. However, I am not able to record ulog file when I choose the new logger option in QGC. A log file exists on the SD card but cannot be processed by Flight Review or EKF analysis tools.
Is it not supported on MindPX?
 I am using latest  PX4 master as of now. Thanks.

**Comment by mzahana** [comment]
@dagar were you able to reproduce the issue?

**Comment by mzahana** [comment]
Another note is, I used QGC to download the logs, which are not working anyway, and didn't use QGC to erase them. However, when I pulled out the SD card and plugged it to my PC, I see no logs in the SD card! Does QGC erase logs automatically after downloading?

**Comment by mzahana** [comment]
Here is a pic of the SD card. The ```log``` folder is empty !
<img width="767" alt="screen shot 2017-04-28 at 8 25 39 pm" src="https://cloud.githubusercontent.com/assets/8803307/25539659/e160ad8c-2c50-11e7-8692-c1af2950b721.png">

**Comment by TSC21** [comment]
I will try to reproduce this ASAP

**Comment by LorenzMeier** [comment]
You need to use a recent version from master to use the new logger, because it was off by default on MindPx.

**Comment by mzahana** [comment]
How recent is recent? I tried this couple of days ago and did not work.
Anyway will try with  latest master again.

**Comment by mzahana** [comment]
* yesterday, I changed SD card, and used master branch that is couple of days old from the time of this comment, and got *ulog working.
* now, i just updated to latest master, and got *ulog too.

I am guessing it is an SD card problem, although it's a new SD that cam with MindPX!
