### ISSUE TITLE
Lidar-Lite V3 - PWM interface not working

### ISSUE THREAD

**Issue by tomatac** [PX4/Firmware#7158]
I am trying to achieve position control using a PX4FLOW and a Lidar-Lite V3 and it looks like the PWM interface is not working. I used the latest master branch as of today APR/29.
I followed these instructions: https://pixhawk.org/peripherals/rangefinder
I checked the wiring and I updated the wiring diagram for Lidar-Lite V3 (see the picture below).
To test/debug the Lidar-lite connectivity on nsh I tried:

nsh> pwm_input start
ERROR [pwm_input] driver already started

nsh> pwm_input test
Showing samples for 5 seconds

nsh> ll40ls start pwm
ERROR [ll40ls] driver already started

nsh> ll40ls test pwm
ERROR [ll40ls] immediate read failed
ERROR [ll40ls] Task exited with errno=11

nsh> ll40ls info pwm
state @ 20010120
ll40ls_pwm_read: 124635 events, 8477306us elapsed, 68us avg, min 29us max 2522us 154.253us rms
ll40ls_pwm_read_errors: 124635 events
ll40ls_pwm_zero_resets: 0 events
WARN  [ll40ls] poll interval:  50 ticks
WARN  [ll40ls] distance: 0.000m

![lidar-lite v3 pwm wiring](https://cloud.githubusercontent.com/assets/15964070/25561078/5319caf4-2d18-11e7-9b81-5533fa0bbf88.png)

**Comment by mhkabir** [comment]
Do you have a BEC connected on the servo rails to power the Lidar?

**Comment by tomatac** [comment]
No. I do not have any other servo. Do I need to add a zener diode if I only power the Lidar Sensor on the servo rail? Is there a schematic on the recommended wiring for the servo rail? Thanks!

**Comment by mhkabir** [comment]
You shouldn't need anything else. Just plug in the BEC on the servo rail. 
Also, you could just use i2c; The v3 Lidars work fine with it.
