### ISSUE TITLE
make: *** [posix_sitl_default] Error 2

### ISSUE THREAD

**Issue by lxgen** [PX4/Firmware#7174]
When I type ' make posix_sitl_default', an issue is caused.It shows as follows:
/bin/sh: 1: cmake: not found
/bin/sh: 1: cd: can't cd to /mnt/c/Users/l_xgen/Firmware/build_posix_sitl_default
make: *** [posix_sitl_default] Error 2

**Comment by mcharleb** [comment]
You need to have cmake installed. See https://dev.px4.io/en/setup/dev_env_linux.html

**Comment by DeanJJJ** [comment]
could you pls tell me where  I can download this file for ubuntu 14.04 and gazebo 7?

**Comment by DeanJJJ** [comment]
@mcharleb could you pls tell me where I can download this file for ubuntu 14.04 and gazebo 7?

**Comment by lovetuliper** [comment]
@lxgen  Have you solved this problem? I encountered the same problem.
