### ISSUE TITLE
Bit-banding for atomic flag access on STM32

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#7183]
By using bit-banding we could avoid having to lock the OS for flag accesses to avoid read-modify-write issues: http://www.micromouseonline.com/2010/07/14/bit-banding-in-the-stm32/

**Comment by LorenzMeier** [comment]
Starting point would be to replace these: https://github.com/PX4/Firmware/pull/7181/commits/93bcde197ddf4b9eea31cc3b82dd8a37c3bae5dd#diff-8c9290622c738995a6aa1c57f5d7706dR206

**Comment by davids5** [comment]
I woulsd avoid BB at it is not supported on all STM32's 
How about built in atomic  https://gcc.gnu.org/onlinedocs/gcc-4.6.1/gcc/Atomic-Builtins.html know to work on ARM

**Comment by bkueng** [comment]
BB is indeed not portable. I already looked into atomic operations (for RCU) and planned to introduce a general API for PX4 based on GCC's builtins. They are supported by Clang as well.
