### ISSUE TITLE
Losing GPS does not trigger fail safe

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#7185]
On latest master, failsafe when losing GPS does not work. A few test cases:
* When I unclick `use GPS` for the EKF2_AID_MASK (in air), the only thing appearing is `WARN  [navigator] global position timeout` after a few seconds but nothing happens. The quad just starts to drift.
* When I stop sending GPS (in air), nothing happens. The quad just starts to drift.
* When the home position was set but has no GPS anymore (on ground), I can still takeoff. Then the quad drifts

I guess the EKF reports local position as still valid?

**Comment by ChristophTobler** [comment]
@priseborough FYI

**Comment by ChristophTobler** [comment]
for the first case `_ekf.local_position_is_valid()` reports invalid, hence the navigator warning. For the other two cases local position is still valid.

**Comment by ChristophTobler** [comment]
Ok, so I don't think it's the estimator but commander/navigator because I was disabling GPS here https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L572. With `gpssim stop` the local and global position are invalid but landing does not work.

**Comment by ChristophTobler** [comment]
The error seems to be in here https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L3779

**Comment by ChristophTobler** [comment]
@priseborough It will never enter https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L3786.  `required_accuracy * 2.5f` is too big because `local_position->eph` will only increase to about `6`. After https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L438-L448 it is `0`.

It works if I remove the `2.5` multiplier but I´m not sure if this is very robust.

**Comment by priseborough** [comment]
OK, I see the problem, will submit a PR soon.
