### ISSUE TITLE
BUG:PX4PIO sem_wait call off Interrupt 

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#7187]
![image](https://cloud.githubusercontent.com/assets/1945821/25716539/1a2c62ac-309b-11e7-9842-6a9c19098540.png)

Foreground needs to atomically save malloc info's minfo.fordblks to    r_page_status[PX4IO_P_STATUS_FREEMEM]  (or a shadow used to update) r_page_status[PX4IO_P_STATUS_FREEMEM]

**Comment by LorenzMeier** [comment]
Fixed!
