### ISSUE TITLE
Problem of px4 about check out tag on Eclipse of Ubuntu

### ISSUE THREAD

**Issue by fightinghui** [PX4/Firmware#7193]
I have one problem of px4 about check out repository on Eclipse of Ubuntu.I want to change  Firmware from v1.3.0RC1 to v1.4.1 in git repository. However,when I check out v1.4.1,it tell me to have check out conflicts.I look for some methods on the Internet,But it does not solve this problem. I still have no idea to do something.Please help me !I'm looking forward to your reply.Thanks!
![photo](https://cloud.githubusercontent.com/assets/18191338/25754597/6c2b84ea-31f2-11e7-8400-ca6975ea4f3a.jpg)

**Comment by dagar** [comment]
Why are you checking out these particular old stable versions? You can ignore all of these conflicts (reset or stash).
On the command line you'd just add force (git checkout -f v1.4.1), then do `make distclean` which will update all the submodules and get rid of old build artifacts.
