### ISSUE TITLE
Time sync issue in SITL simulation - mavros topics are published starting to Jan/01/1970

### ISSUE THREAD

**Issue by tomatac** [PX4/Firmware#7197]
Mavros topics are published starting to Jan/01/1970 instead of using the current time on the host computer. How can we correct this issue?
Do I need to add a command in the …/posix-configs/SITL/init/lpe/iris startup file to activate synchronization?
Also by default mavros is set to use the fcu time (/mavros/time/time_ref_source: fcu). Is it better to set it mavros to sync time with the host computer?

**Comment by aykutkabaoglu** [comment]
any update?
