### ISSUE TITLE
Generic Quad X - Boot Up Problem

### ISSUE THREAD

**Issue by cagdas001** [PX4/Firmware#7198]
The device does not boot up after selected the Generic Quad X as the airframe in the latest stable release. There is no problem on other frame types, the only problem is with Generic Quad X.

**Comment by dagar** [comment]
Are you able to connect a console and see where it's getting stuck?

**Comment by cagdas001** [comment]
Since I calibrated everything and mounted on the frame, I don't want to reset the board again. When you set Generic Quad X, the device does not open at all and therefore you can't connect it to QGC, you can't install the firmware again. I think it may be related to the bootloader. Because I was able to install ArduCopter firmware with the MissionPlanner.

But I can say there is no problem in beta and dev releases. I had tried them also.

**Comment by dagar** [comment]
Oh, in that case this will be resolved shortly. Use dev (master) for now, it's going to become the next release version very soon.
