### ISSUE TITLE
Please have a look at my px4flow test logs

### ISSUE THREAD

**Issue by nancy03610** [PX4/Firmware#7207]
@jgoppert @mhkabir I am using px4flow to do hovering. I do a lot of tests indoor and outdoor. My problem is sometimes I just cannot enter the position hold mode. I suppose that when I switch to position mode, the local position set point doesn't change means that it is trying to hold the position. Am I right? In my tests, all the setups are same. I can understand that sometimes the flow quality is not good causing the falls, but sometimes everything seems good to me, while the LPSP changes. I cannot find any explanation for that. Is there any requirement for position hold? 

Here are some of my test logs:

This is one relatively successful test outdoor: 
http://logs.uaventure.com/view/CnsqRVDuGcoNLjHrLNqi5C

These are indoor tests:
http://logs.uaventure.com/view/RCzaUZ4PeMuAqr5zGh3zoY
http://logs.uaventure.com/view/9n6FoBZe5xrkWoT6FMCZLH
http://logs.uaventure.com/view/Qow9Td9UM9Z6NFN9eSLKfH
http://logs.uaventure.com/view/9PUxJ3EvLo9ErE4BWCpqTQ

These are outdoor tests:
http://logs.uaventure.com/view/eNWbJn8ZPFYa5HD99bfLUi
http://logs.uaventure.com/view/o85N9MvvFw5ZE4aWoMzV3a

**Comment by TSC21** [comment]
There were some changes on the Flow code that may improve the quality of the readings and avoid drops on the position lock. Please update your PX4Flow firmware and let us know how it goes.
