### ISSUE TITLE
Problem with getting Tricopter SITL running - Gazebo plugins - Series link problem

### ISSUE THREAD

**Issue by ganeshrk95** [PX4/Firmware#7214]
I'm trying to do a SITL simulation of a Tricopter (with tiltrotor servo) in Y+ configuration on Gazebo. I have successfully created a Solidworks model and have generated a SDF file. I have written the plugins into the SDF file using iris.sdf as a reference model. 

In my model, there is a tail servo which actuates the back motor (for yaw). The back rotor (Prop) is connected to this servo link. When I arm, I cannot get the back rotor to arm. I think this is because the base_link(chassis)>Servo Joint>Back rotor are in series and the default plugin (gazebo_multirotor_base_plugin.cpp) only supports child links (the rotors) of a single base_link. Is there any way I can bypass this? 

In this file attached the Joint tree is as follows:

->base_link(Chassis)
----->rotor_1(Front_right)
----->rotor_2(Front_left)
------>rotor_4(servo link)
------------->rotor_3(Back rotor)

Note: Base_Link>rotor_4>rotor_3 is the series of actuated link that could be the issue preventing arm

The plugin 'rosbag' calls 'librotors_gazebo_multirotor_base_plugin.so'. What is the purpose of this plugin? And why is base_link given as input to this?

[BoomCopterV3.5_new.pdf](https://github.com/PX4/Firmware/files/991049/BoomCopterV3.5_new.pdf)

**Comment by dagar** [comment]
Hi @ganeshrk95 
I'm interested in this, but it's really more of a gazebo question. We need to limit PX4 Firmware issues to bugs and feature requests in the firmware itself.

If you opened this as a pull request in https://github.com/PX4/sitl_gazebo we can ask for input from people that have a good understanding of gazebo.
