### ISSUE TITLE
Linux Kernel

### ISSUE THREAD

**Issue by Darkus3** [PX4/Firmware#7224]
Hi ! 
![screenshot from 2017-05-12 10 16 30](https://cloud.githubusercontent.com/assets/3934435/25989467/81e8e0d4-36fc-11e7-9ebb-93d993f153a7.png)

I followed the graph and found nicely the RTOS kernel which is based on nuttX. But didn't find the Linux Kernel which control the camera and storage.

Do you knoy where is it located ?

Thank you for your help

**Comment by mhkabir** [comment]
https://github.com/torvalds/linux :)
