### ISSUE TITLE
Unable to add a new airframe

### ISSUE THREAD

**Issue by AlexMalo** [PX4/Firmware#7227]
I defined the files that you require in the directories init.d  and mixers, with the formats specified, under  ROMFS/px4fmu_common/ directory, using as template one of the files already in the directory. I see the new airframe in airframes.xml. However, when I run QGroundControl I do not see the airframe. How can I choose it? What I am missing?
Thanks
Alejandro Malo
[2107_wilga.txt](https://github.com/PX4/Firmware/files/997835/2107_wilga.txt)
[highfixedwing.main.mix.txt](https://github.com/PX4/Firmware/files/997837/highfixedwing.main.mix.txt)

**Comment by LorenzMeier** [comment]
You need to flash the binary through QGroundControl so that it does pick up the new metadata.

**Comment by LorenzMeier** [comment]
I added additional instructions on this page: https://dev.px4.io/en/airframes/adding_a_new_frame.html

**Comment by AlexMalo** [comment]
Thank you.
