### ISSUE TITLE
Problem by uploading to the board 

### ISSUE THREAD

**Issue by gesemeliab** [PX4/Firmware#7229]
I have a PX4IO V1.3 and i'm trying to upload my first app, but when i hit "make px4fmu-v2_default upload"
it gives me this:
WARNING: Firmware not suitable for this board (board_type=5 board_id=9)
Found board 5,0 bootloader rev 3 on /dev/serial/by-id/usb-3D_Robotics_PX4_FMU_v1.6_0-if00
help please!

**Comment by LorenzMeier** [comment]
You need to use the build target px4fmu-v1_default
