### ISSUE TITLE
STABILIZED to AUTO.LAND drops actuator outputs to min PWM

### ISSUE THREAD

**Issue by lamping7** [PX4/Firmware#7231]
Upon triggering AUTO.LAND from STABILIZED, the FC drops all actuator outputs to min PWM, removes thrust, causing instability before re-applying thrust to regain altitude.

Log: http://review.px4.io/plot_app?log=61623410-7cb8-401d-8a95-9f08a6c91440

**Comment by LorenzMeier** [comment]
I've looked into this and your log is oddly incomplete. I will need to dig a little deeper into it.

**Comment by LorenzMeier** [comment]
Can you re-test this with RC3? The log shows big errors on the estimator side but is too incomplete to judge what the issue is or if this is just the log.

Try also to replace the microSD card with a better model / brand.

**Comment by lamping7** [comment]
I will not be able to test for a few weeks.

**Comment by lamping7** [comment]
I don't recall this happening in the most recent flights. I'll re-open if I see this when flying resumes in the Spring.
