### ISSUE TITLE
log autopilot serial number

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#7255]
In reviewing logs it's occasionally meaningful to be able to identify specific hardware. Unless I've missed it I don't see a serial number logged anywhere.

**Comment by bkueng** [comment]
It's already logged: https://github.com/PX4/Firmware/blob/master/src/modules/logger/logger.cpp#L1653
and displayed in flight review.

**Comment by dagar** [comment]
Thanks, I was looking in Flightplot.
