### ISSUE TITLE
[commander] home: 47.3977420, 8.5455937, 488.10 not my home

### ISSUE THREAD

**Issue by AlexMalo** [PX4/Firmware#7271]
Hi,
I am running posix_sitl_default. But when I try to program waypoints, the waypoints are in Mexico, but the home still in Zürich.
How can I change the home latitude and longitude? I have already modified the local position estimator and navigator parameters, but still get the above parameters plus/minus 1*10^-7 for the longitude and latitude and 0.1 for the altitude. 

When I try to upload my waypoints to the  QGroundControl, it tells me that my first waypoint is too far.
Thanks.

**Comment by dagar** [comment]
You need to tell the simulator where to start. 
Set these environments variables.

    PX4_HOME_LAT
    PX4_HOME_LON,
    PX4_HOME_ALT

**Comment by AlexMalo** [comment]
Thank you!
