### ISSUE TITLE
Timestamp.hpp in px4flow source code missed

### ISSUE THREAD

**Issue by nancy03610** [PX4/Firmware#7278]
Hello, everyone. I am trying to build Flow-master.

And I got this error:

/src/Flow-master/src/lib/uavcan/libuavcan/include/uavcan/time.hpp:12:32: fatal error: uavcan/Timestamp.hpp: No such file or directory

So I look into the source code. In time.hpp, there is one line: #include <uavcan/Timestamp.hpp>
But I really didn't find this Timestamp.hpp in the direction mentioned.

How can I fix this??

**Comment by pavel-kirienko** [comment]
The DSDL compiler for libuavcan was supposed to generate `Timestamp.hpp` at build time, but for some reason it didn't. Please review your build process, perhaps something is broken.
