### ISSUE TITLE
FW_LND_USETER

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#7289]
[FW_LND_USETER](https://dev.px4.io/en/advanced/parameter_reference.html#FW_LND_USETER) description says:

> Use terrain estimate during landing

Can we add a comment to this parameter:

> If set (and valid) the terrain altitude from GPS is used to determine the ground altitude during landing.

**Comment by tubeme** [comment]
I think it is the Baro Altitude used for the landing and not the GPS Alt. I don't know if we use GPOS.Alt for the landing...

**Comment by hamishwillee** [comment]
@tubeme - either way, the current docs are clearly not correct/sufficient. 

This information was from @dagar - can you confirm what is correct?

**Comment by hamishwillee** [comment]
Thanks @dagar

**Comment by see3peoh** [comment]
Is this affected by having a lidar on board? Terrain estimator is disabled by default now, is it simply best to not use it? If so, how does the lidar assist in terrain estimation landing?

**Comment by santiago3dr** [comment]
this issue was resolved prior to 1.8.0 release
here's the pr that addressed it
https://github.com/PX4/Firmware/pull/8412
