### ISSUE TITLE
pixracer wont save configure with qgc

### ISSUE THREAD

**Issue by stlfatboy** [PX4/Firmware#7294]
sometime setup airframe will not take effect.

**Comment by stlfatboy** [comment]
px4 1.5.5 with qgc3.0.1

**Comment by stlfatboy** [comment]
also with qgc 3.1.3

**Comment by LorenzMeier** [comment]
Thanks for reporting, but cross-testing suggests this is working. I'm closing this as a hardware failure. Please contact the vendor.
