### ISSUE TITLE
Flight Mode: HORIZON (Feature request)

### ISSUE THREAD

**Issue by netinetwalker** [PX4/Firmware#730]
It comes from multiwii ... 
HORIZON - A mixture between ACRO and ANGLE modes. Combining the stabilising effect with calm rc sticks and acrobatics with busy rc sticks 
STABLE MODE mode when PITCH/ROLL sticks are centered. ACRO MODE mode when full PITCH or ROLL sticks are applied, allowing flips. 

on multiwii 0%-80% stabilized   ... 80-100% acro
on tau labs its a smouth transition

return from 80-100% to 0%-80%
on multiwii it feels like if i return between 0-80 it takes 1 secound to go back to stabilized
on tau labs it should be a smouth transition...

http://www.multiwii.com/wiki/index.php?title=Flightmodes <- Horizen Mode
https://github.com/TauLabs/TauLabs/wiki/Flightmode-Settings <- Horizen Mode
http://diydrones.com/profiles/blogs/tau-labs-has-multiwii-style-horizon-mode

It would be nice to have this mixed flight mode on the px4 stack ...

**Comment by netinetwalker** [comment]
anyone looking at this?

**Comment by SimonWilks** [comment]
Perhaps this is similar to what you are looking for?
https://github.com/PX4/Firmware/pull/2390#issuecomment-118644553

It's merged into master and available on the stable release already too.
There is a video link in that discussion thread that shows it working.

**Comment by kd0aij** [comment]
Simon, if PR2390 has been merged to master, why is it still open?

**Comment by sjwilks** [comment]
Well Mark, my mistake. I guess it's not in master then.

**Comment by LorenzMeier** [comment]
Closed, as fixed a long time ago.
