### ISSUE TITLE
land_detector detects takeoff/landing with motors disconnected

### ISSUE THREAD

**Issue by nicolaerosia** [PX4/Firmware#7319]
Hello,

As I'm preparing for my first flight, I'm trying to check as many things as I can and I've stumbled upon this issue.
Worth mentioning is that propellers are not attached.

If I do commander arm, raise the throttle, then land_detector detects takeoff, and landing when I lower the throttle.

Log here: http://logs.px4.io/plot_app?log=3381ef1b-73e3-4cc7-afa6-a24028f7dabc
[16_34_54.zip](https://github.com/PX4/Firmware/files/1039092/16_34_54.zip)

Update 1: Here is another log, outside, with GPS, only one IMU+MAG enabled (mpu9250): http://logs.px4.io/plot_app?log=5e54e3d1-ff68-421b-b189-3100a0b199f4
[17_13_43-mpu9250-gps.zip](https://github.com/PX4/Firmware/files/1039152/17_13_43-mpu9250-gps.zip)

Any ideas?

**Comment by dagar** [comment]
Manual input is a factor for manual modes.
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L207

**Comment by mhkabir** [comment]
This is not really a bug. The system assumes that it's taking off because it has no other feedback to make a decision with. GPS isn't accurate enough to make that decision either.

**Comment by nicolaerosia** [comment]
Can't we use the accelerometer somehow?

**Comment by bresch** [comment]
Having a false positive in the takeoff detector is not a big problem. However, a detection with an accelerometer (in addition to the manual input) might lead to some false negatives which are much more unwanted. A proper tuning of the takeoff thrust value is then a good conservative solution.

**Comment by LorenzMeier** [comment]
This all works as designed.
