### ISSUE TITLE
Arming without Current sensor.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#7323]
Hello guys,

There is protection in the PX4 for good, which does not allow to arm the PX4 if there is no voltage and amp sensor connected. But we are building a machine with a 14S and really does not have a way to measure the current because it is in the 500A+ range. We will make voltage sensor for the tests and my question in advance before the tests is - is there a problem not having the Amp sensor attached and only the Voltage sensor? Will we be able to arm, or should we change CBRK_SUPPLY_CHK  in order to disable the check? And if we disable the check then will we be able to still measure the voltage?

Any ideas?

**Comment by dagar** [comment]
Voltage sensor only is fine. Be safe!
