### ISSUE TITLE
GPS coordinate in GPS-denied environments

### ISSUE THREAD

**Issue by Changliu52** [PX4/Firmware#7335]
Considering the scenario, that if the PX4 was equipped with GPS, SLAM and OpticalFLow. In operation, the system is powered on outdoor with valid GPS, then it flys into a building, so the GPS was blocked, but SLAM and Opticalflow were able to maintain a valid local pose.

In this case, I am not sure if the GPS coordinate is still predicted based on local pose? or the local frame and the global frame are completely separate?

**Comment by mhkabir** [comment]
Yes the global coordinates are converted to local coordinates in most cases. 

We are also working on making sure that the system uses local coordinates for absolutely everything, so that we can fully support GPS denied navigation throughout the flight stack.
