### ISSUE TITLE
Different attitude and position estimation  algorithm

### ISSUE THREAD

**Issue by xmutrue** [PX4/Firmware#7343]
Dears:

Does  AttposEKF of estimator_22states.cpp in the InertialNav still work well for attitude and position estimation on vehicle ? 

 Now it seems that the algorithm used in new version firmware of pixhawk or ardupilot are ECL(https://github.com/PX4/ecl),  not  estimator_22states.cpp(https://github.com/priseborough/InertialNav).

Thanks

**Comment by mhkabir** [comment]
Probably still works, but we won't support it.

**Comment by xmutrue** [comment]
Is  ECL  or   attitude_estimator_q  plus  position_estimator_inav  better than the  estimator_22states  when we do the estimation of fixwing or multicopter uav ?
