### ISSUE TITLE
pca9685 build failed.

### ISSUE THREAD

**Issue by cctsao1008** [PX4/Firmware#7349]
Scanning dependencies of target drivers__frsky_telemetry
[ 55%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/devices/src/ashtech.cpp.obj
[ 55%] Built target drivers__meas_airspeed
[ 56%] Building C object src/drivers/frsky_telemetry/CMakeFiles/drivers__frsky_telemetry.dir/frsky_data.c.obj
[ 56%] Building CXX object src/drivers/pca9685/CMakeFiles/drivers__pca9685.dir/pca9685.cpp.obj
Scanning dependencies of target drivers__led
[ 56%] Building CXX object src/drivers/led/CMakeFiles/drivers__led.dir/led.cpp.obj
/media/build/EXT41/px4/Firmware/src/drivers/pca9685/pca9685.cpp:139:32: error: 'NUM_ACTUATOR_CONTROLS' was not declared in this scope
  uint16_t      _current_values[NUM_ACTUATOR_CONTROLS]; /**< stores the current pwm output
                                ^
compilation terminated due to -Wfatal-errors.
make[3]: *** [src/drivers/pca9685/CMakeFiles/drivers__pca9685.dir/pca9685.cpp.obj] Error 1
make[2]: *** [src/drivers/pca9685/CMakeFiles/drivers__pca9685.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 56%] [ 56%] Building C object src/drivers/frsky_telemetry/CMakeFiles/drivers__frsky_telemetry.dir/sPort_data.c.obj
Building C object src/drivers/frsky_telemetry/CMakeFiles/drivers__frsky_telemetry.dir/frsky_telemetry.c.obj
Linking CXX static library libdrivers__led.a
[ 56%] Built target drivers__led
[ 56%] Building CXX object src/drivers/gps/CMakeFiles/drivers__gps.dir/devices/src/ubx.cpp.obj
Linking C static library libdrivers__frsky_telemetry.a
[ 56%] Built target drivers__frsky_telemetry
Linking CXX static library libdrivers__gps.a
[ 56%] Built target drivers__gps
make[1]: *** [all] Error 2
make: *** [px4fmu-v2_default] Error 2

**Comment by LorenzMeier** [comment]
Fixed in ad05a6a7ec. If its not too hard to figure out how to fix it a pull request would be appreciated in the future. Thanks!
