### ISSUE TITLE
Names of assisted modes inconsistent

### ISSUE THREAD

**Issue by Finwood** [PX4/Firmware#7354]
Both altitude and position control appear in code (and thus also in generated documentation) both as ALTCTL / POSCTL and ALTCT**R**L / POSCT**R**L. Thus not a big problem, this makes keyword search on the documentation pages a bit awkward.

*What is the preferred abbreviation?*

**Comment by dagar** [comment]
This is where the naming comes from - https://github.com/PX4/Firmware/blob/master/msg/vehicle_status.msg#L17

    uint8 NAVIGATION_STATE_ALTCTL = 1		# Altitude control mode
    uint8 NAVIGATION_STATE_POSCTL = 2		# Position control mode
