### ISSUE TITLE
AUAV X2.1: 1.6.0 stable, reporting as 1.6.0dev

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#7355]
After flashing the 1.6.0 stable on AUAV x2.1, the board is recognized as ID 33, QGC flashes the correct X2.1 FW, but then in the summary info it is reported as 1.6.0dev.

**Comment by LorenzMeier** [comment]
Thanks, there was indeed a mixup with the tag. It is fixed now and should reflect in the next minutes. https://github.com/PX4/Firmware/releases/tag/v1.6.1
