### ISSUE TITLE
Mission takeoff with rotary wing rejected due to (horizontal) acceptance radius

### ISSUE THREAD

**Issue by Finwood** [PX4/Firmware#7379]
With a "high" (20 meters) NAV_ACC_RAD setting, takeoff for multicopter missions gets annoying. The [Mission Feasibility Checker](/PX4/Firmware/blob/master/src/modules/navigator/mission_feasibility_checker.cpp#L139) rejects takeoff altitudes below 21 meters, which is not always desired.

We should use the altitude acceptance radius NAV_MC_ALT_RAD for this check.

**Comment by dagar** [comment]
Fixed.
