### ISSUE TITLE
Issue with px4_add_module()

### ISSUE THREAD

**Issue by devbharat** [PX4/Firmware#7387]
Doesn't `target_include_directories()` require `INTERFACE|PUBLIC|PRIVATE` as an [argument](https://cmake.org/cmake/help/v3.3/command/target_include_directories.html)? The definition of px4_add_module [here](https://github.com/PX4/Firmware/blob/5ee79648b7e709c0c31e4369f3f77ae39f1c7567/cmake/common/px4_base.cmake#L248) skips it.

```
if(INCLUDES)
	target_include_directories(${MODULE} ${INCLUDES})
endif()
```

It exits with "_target_include_directories called with invalid arguments_"

**Comment by dagar** [comment]
Do we actually need this functionality or would it make more sense to directly call include_directories() in that CMakeLists.txt?

**Comment by devbharat** [comment]
Of course we could directly call target_include_directories() in the specific CMakeLists file, but I thought there was a point to all these px4 abstractions.

**Comment by dagar** [comment]
In this case it really is just a wrapper and I'd rather strip away the additional complexity.

**Comment by dagar** [comment]
That being said, I did the quick fix recently. https://github.com/PX4/Firmware/blob/master/cmake/common/px4_base.cmake#L248
