### ISSUE TITLE
Bottle_drop not generating any AUX output

### ISSUE THREAD

**Issue by myeabhishek** [PX4/Firmware#7412]
Hi Guys,
I am using bottle_drop module in PX4 to drop a payload from a moving Multicopter. I am using "bottle_drop drop" command from NSH shell to drop the payload. The problem is that I am not receiving any PWM output on any of the AUX pins required for my release mechanism on issuing this command. 

I have enabled and started this module for multicopters as I understand it was intended for fixed wings. Even then it should have no problem in generating a PWM output at the required time when this command is given. 

Please help!

**Comment by LorenzMeier** [comment]
You need to create a mixer that connects the payload actuator control group with the PWM outputs.

**Comment by LorenzMeier** [comment]
I'm closing this. Please post if you don't find in http://dev.px4.io how to add that mixer.
