### ISSUE TITLE
How to log IMU at 1000 Hz?

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#7416]
It is often useful to log IMU data at a high rate, say 1000 Hz.
I tried increase the publishing rate of the mpu9250 driver by changing 
```
MPU9250_ACCEL_MAX_OUTPUT_RATE 280
```
To
```
MPU9250_ACCEL_MAX_OUTPUT_RATE 1000
```
However, using "uorb top" I see that the topic is actually only publishing at 377 Hz.
Anyone know how to make the driver publish faster? 
(I also switched off all unnecessary modules to save CPU)

**Comment by LorenzMeier** [comment]
You need to set the rate higher than the actual rate you want as you otherwise will skip samples if the rate is equal. Set it to 1200 and re-test.

**Comment by jgoppert** [comment]
@CarlOlsson have you made any progress here? I'm also running into the same issue and wanted to know what rate you were able to achieve, and if the cpu load was reasonable.

**Comment by CarlOlsson** [comment]
Hi,
As soon as I increased the rate I could not connect at all in mavlink shell so could not test it properly. Now I am gone for a week so will have to pick it up when I'm back. But please tell me if you figure something out!

**Comment by ksschwabe** [comment]
@CarlOlsson Are you doing this using the DriverFramework (using a Snapdragon, RaspPi, or SITL)?

In the df_mpu9250_wrapper.cpp in the _publish function, there are the following lines of code:
```
	// The driver empties the FIFO buffer at 1kHz, however we only need to publish at 250Hz.
	// Therefore, only publish every forth time.
	++_publish_count;

	if (_publish_count < 4) {
		return 0;
	}
```

This means that although the MPU might be giving you data at 1000Hz, it is only being published at a quarter of that rate. (@LorenzMeier: This hard-coding of publishing only every forth message isn't very nice. Perhaps this framework should be changed as hinted at in this discussion https://github.com/PX4/Firmware/issues/7438)

If you are doing this on the PixHawk using the standard /Firmware/src/drivers/mpu9250 driver, then in the publish() function there is the line
```
bool accel_notify = _accel_int.put(arb.timestamp, aval, aval_integrated, arb.integral_dt);
```
which when accel_notify is set to true, it allows the driver to publish. This is determined by the MPU9250_ACCEL_MAX_OUTPUT_RATE that is set at the top of the file.
```
if (accel_notify && !(_pub_blocked)) {
		/* log the time of this report */
		perf_begin(_controller_latency_perf);
		/* publish it */
		orb_publish(ORB_ID(sensor_accel), _accel_topic, &arb);
	}
```

(Similar lines of code exist for the gyro).

If you want to ignore the filtering on the accelerometer and the gyro and just publish every single measurement, then just hard code
```
// Force accel and gyro to be published in every loop
	accel_notify = true;
	gyro_notify = true;

```

before the lines
```
/* notify anyone waiting for data */
	if (accel_notify) {
		poll_notify(POLLIN);
	}

	if (gyro_notify) {
		_gyro->parent_poll_notify();
	}

	if (accel_notify && !(_pub_blocked)) {
		/* log the time of this report */
		perf_begin(_controller_latency_perf);
		/* publish it */
		orb_publish(ORB_ID(sensor_accel), _accel_topic, &arb);
	}

	if (gyro_notify && !(_pub_blocked)) {
		/* publish it */
		orb_publish(ORB_ID(sensor_gyro), _gyro->_gyro_topic, &grb);
	}
```
 
**Please note:** this is definitely a HACK to be able to get the IMU data out at +/-1000Hz. I don't know what consequence this might have on the flight controller, please be careful if you intend to fly with these modifications!

**Comment by CarlOlsson** [comment]
Thanks! @ksschwabe 
I am using it on Pixracer and except for some dropouts in the logs it works fine :)

**Comment by FreshGresh** [comment]
For those like me looking for the same info with newer PX4 firmware: the parameter list now has increased options. Checkout documentation on SDLOG_PROFILE in the full parameter list. You may want 3 (system ID) or possibly 4 (high rate).

**Comment by bresch** [comment]
@FreshGresh There is also FIFO logging available; this allows to log the gyro and accel data at full speed (e.g.: 8kHz on some IMUs): https://docs.px4.io/master/en/log/flight_review.html#raw-high-rate-imu-data-plots
