### ISSUE TITLE
Inspect SITL on Mac OS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#7419]
I have this log which crashes the vehicle in SITL. I noticed that the motors are fairly unbalanced:
http://review.px4.io/plot_app?log=874dca50-6f34-454f-b8ad-c1daa0713028

**Comment by LorenzMeier** [comment]
Currently I believe this is clock skew related.

**Comment by LorenzMeier** [comment]
Yep, definitely is. It is ok for the first 15 seconds and then becomes unbearable. I need to trace down where that is originating.

@priseborough We also need to inspect the EKF.

**Comment by priseborough** [comment]
The estimator innovations were within limits until after the high frequency oscillation started.

**Comment by LorenzMeier** [comment]
Fixed this last week on master.
