### ISSUE TITLE
upload failed

### ISSUE THREAD

**Issue by potato77** [PX4/Firmware#7456]
version:1.5.5
I change the file `nuttx_px4fmu-v2_default.cmake` in  `cmake\configs`.
origin 

> 	#modules/attitude_estimator_q
> 	#modules/position_estimator_inav
> 	#modules/local_position_estimator
> 	modules/ekf2

after

> 	modules/attitude_estimator_q
> 	modules/position_estimator_inav
> 	modules/local_position_estimator
> 	modules/ekf2

the error is 

![default](https://user-images.githubusercontent.com/11450591/27422060-70b50940-575f-11e7-8e81-d70a38a46d7e.png)

**Comment by LorenzMeier** [comment]
You can't enable all modules. There is on your board only enough flash for either-or.
