### ISSUE TITLE
pixhawk pro quadcopter flyaway

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#7463]
http://logs.px4.io/plot_app?log=00b0b048-39bd-45cd-910b-c3d54b0f39ad

![image](https://user-images.githubusercontent.com/84712/27490566-c541ba8c-580c-11e7-9737-46f6a609d4b8.png)

EKF plots

[00b0b048-39bd-45cd-910b-c3d54b0f39ad.ulg.pdf](https://github.com/PX4/Firmware/files/1098398/00b0b048-39bd-45cd-910b-c3d54b0f39ad.ulg.pdf)

``` bash
 % ./process_logdata_ekf.py ~/Downloads/00b0b048-39bd-45cd-910b-c3d54b0f39ad.ulg 
found estimator_status data
found ekf2_innovation data
found sensor_preflight data
log finishes while in-air at 827.3 sec
Using test criteria loaded from check_level_dict.csv
Traceback (most recent call last):
  File "./process_logdata_ekf.py", line 1407, in <module>
    test_results['filter_fault_status'][0] = 'Fail'
KeyError: 'filter_fault_status'
```

@santiago @priseborough @bkueng

**Comment by dagar** [comment]
As a precaution I reverted `-fno-math-errno`.

**Comment by LorenzMeier** [comment]
Testing so far suggests that this fixed it. We need to HITL test the math changes.
