### ISSUE TITLE
Using sonar MB1242 in LPE 

### ISSUE THREAD

**Issue by lyhsteven** [PX4/Firmware#7465]
Hello guys,
We want to use sonar MB1242 to measure the altitude in LPE. To make it happened, I've already done these:
1. I uncomment the drivers/mb12xx in cmake/configs/nuttx_px4fmu-v2_default.cmake
2. I turn the param SENS_EN_MB12XX from 0 to 1 in src/modules/sensors/sensor_params.c and also in QGC
3. I don't know how much to set LPE_FUSION for I set it 174
But it still doesn't work.
Could anyone  give me some advice, I'll be appreciate to that.

**Comment by deksprime** [comment]
Which interface are you using for  the sonar to the FCU? Maybe you are trying to use an interface which is not supported in the driver.

**Comment by lyhsteven** [comment]
I got it. It also needed to edit in rcs that turn **if param compare SENS_EN_MB12XX 1**, then it will work.
