### ISSUE TITLE
Group vehicles of a particular frame type together in the airframe reference

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#7473]
@bkueng Would be good to rearrange the [airframe reference](https://docs.px4.io/en/airframe_reference.html) generation tool such that all vehicles of a particular type are grouped - e.g. all planes, all vtol, all rovers etc. At the moment they are mixed.

It would also be great to create an anchor we can use to link to each of these sections.

**Comment by bkueng** [comment]
Sounds good. We already have a type to image name mapping [here](https://github.com/PX4/Firmware/blob/master/Tools/px4airframes/srcparser.py#L25), we can do the same to get the group. Do you want to do this?

**Comment by hamishwillee** [comment]
Yes. Let's continue discussion in #7482

**Comment by LorenzMeier** [comment]
Done.
