### ISSUE TITLE
New parameter requires make clean

### ISSUE THREAD

**Issue by jlecoeur** [PX4/Firmware#7475]
When adding a new parameter XXX (using `control::BlockParamFloat`), I get this error on startup: 
```shell
ERROR [lib__controllib] error finding param: XXX
```

This error disappeared after I did `make clean` and rebuilt everything.

I haven't looked at how parameters are dealt with by the build system, but it would be better if adding new parameters did not require a full re-compile.

**Comment by dagar** [comment]
Where did you add the parameter?

Have you tried the latest master? There was a broken parameter dependency the was fixed recently.

**Comment by jlecoeur** [comment]
Oops my bad, I updated my branch and the problem is gone.
Thanks!
