### ISSUE TITLE
https://github.com/PX4/Firmware/blob/master/src/drivers/px4flow/px4flow.cpp#L514

### ISSUE THREAD

**Issue by limhyon** [PX4/Firmware#7478]
Hi,
Why this px4flow.cpp app accept only pixel_flow_x_integral?

**Comment by AlexisTM** [comment]
What do you mean?

**Comment by limhyon** [comment]
https://github.com/PX4/Firmware/blob/master/src/drivers/px4flow/px4flow.cpp#L514
Most of values from f_integral, not f.
Is ther any reason?

**Comment by mhkabir** [comment]
Taking the integral allows us to not miss any data between the transfer periods.
