### ISSUE TITLE
Setting mag rotation requires a restart

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#7480]
@bkueng @mhkabir  In the current code I only got correct heading after rebooting the autopilot. Can you confirm this?

**Comment by tubeme** [comment]
I can confirm this.

**Comment by mhkabir** [comment]
@LorenzMeier Yes this is the intended behaviour. I think we will need to make QGC force a restart after setting the mag rotation to avoid users from not rebooting and flying.

**Comment by dagar** [comment]
Where's the issue?

**Comment by LorenzMeier** [comment]
I'm closing this since QGC 3.2 has that already in.
