### ISSUE TITLE
Simulation in Airframes reference - what do the MAIN mean

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#7483]
https://docs.px4.io/en/airframe_reference.html#simulation

@bkueng Regarding:
![image](https://user-images.githubusercontent.com/5368500/27572828-9f64fcdc-5b51-11e7-8bc3-ffa3457b0f89.png)

1. Image is plane, but one of the simulations is quad
2. For quad the MAIN values above will be wrong.
3. What do the values for MAIN mean in a simulation?

**Comment by bkueng** [comment]
>  Image is plane, but one of the simulations is quad

I suggest we remove the image.

>    For quad the MAIN values above will be wrong.

The outputs should be added here: https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/1001_rc_quad_x.hil

>    What do the values for MAIN mean in a simulation?

It's the channel for the mavlink message: the index of `controls` in [HIL_ACTUATOR_CONTROLS](http://mavlink.org/messages/common#HIL_ACTUATOR_CONTROLS)

**Comment by dagar** [comment]
These might actually be better as a Simulation entry under the regular categories. The number of categories is kind of overwhelming.

![image](https://user-images.githubusercontent.com/84712/27603460-2e060976-5b44-11e7-8031-8c1864b1c9de.png)

Would we be better off with a much simpler set of groups?
Something like initially selecting the vehicle from maybe 8 generic groups, then on the side you see the specific airframe with metadata. I'm getting pretty off topic for a firmware issue.

**Comment by hamishwillee** [comment]
@bkueng We've progressed a little in https://github.com/PX4/Firmware/pull/7482 by splitting the simulation into different "classes" . BUT still need to know how to get rid of the plane image for the quad section - your help appreciated. This item can now be closed.

@dagar In #7482 you will see that for the docs we now have a "class" (e.g. vehicle type like VTOL). This means that as you have suggested the simulation gets split by class to the right place. 

How QGC does this should be raised in QGC right?

> These might actually be better as a Simulation entry under the regular categories.
 
As a user in QGC I think I prefer to have them all grouped together under "Simulation". The problem is that then the icon will be wrong for at least some vehicles.

My reasoning is that I probably want to see what is available when I want to simulate, rather than hunt in vehicle types. I'd feel differently if we had simulation options for every frame.

> Would we be better off with a much simpler set of groups?

Of course, if it can be done reasonably :-) ONe option might be to do as we have in the docs and split to vehicle type first - copter, vtol, plane, boat, other ...

**Comment by bkueng** [comment]
> BUT still need to know how to get rid of the plane image for the quad section

It comes from here: https://github.com/PX4/Firmware/blob/master/Tools/px4airframes/srcparser.py#L54 and uses this image: https://github.com/PX4/Devguide/blob/master/assets/airframes/types/AirframeSimulation.svg

> Of course, if it can be done reasonably :-) ONe option might be to do as we have in the docs and split to vehicle type first - copter, vtol, plane, boat, other ...

+1
