### ISSUE TITLE
PX4 1.6.1: Brutal oscillation in Position mode.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#7488]
Hello guys,

We are trying our VTOL only in quad mode with the 1.6.1. The machine is flying very well in Manual and Altitude modes. But switching to Position was accompanied by very very nasty osculations. I'm clueless of what might cause the problem. Having hard time to analyze the ULOG with Flight Plot (I'm used to the old LOG format).

I noticed that there is huge jump in the Vel.X SP but cannot find the reason for it:
![quad problem on pos](https://user-images.githubusercontent.com/12617619/27586319-86c29d64-5b48-11e7-9427-28de3503aa86.png)

Here is the log:
http://review.px4.io/plot_app?log=936c8873-10f8-43c6-ad79-0faa1e98299f

Any Ideas?

**Comment by tubeme** [comment]
Also I noticed a couple of messages in Flight plot around the time of the Position switching:

![image](https://user-images.githubusercontent.com/12617619/27586550-6c98e532-5b49-11e7-8546-87840d80a722.png)

**Comment by dagar** [comment]
It's an EKF issue, although those ekf2 low on stack messages are an unrelated warning. The important ones are "EKF GPS fusion timeout".

At a glance it's something to do with your mag.

![screen shot 2017-06-27 at 10 22 58](https://user-images.githubusercontent.com/84712/27592536-b62d4796-5b22-11e7-8863-fc16c102c9c3.png)

**Comment by lamping7** [comment]
I'm not sure if this is helpful, but we saw the same issue in our logs today running v1.6.3 (px4fmu-v3) on a Pixhawk 2.1 w/ HERE GNSS. We were performing some tuning flights for our MC in Stabilized mode, so there was no effect on flight, but similar errors were present. Here are links to 2 logs that have the "EKF GPS fusion timeout" warning. 
http://review.px4.io/plot_app?log=6007ff57-aa44-4631-9dfe-c7cdec8af339
http://review.px4.io/plot_app?log=edb665d3-fb10-4f93-b990-974731c852ab

Our teams next step is to fly in AUTO/Position modes, so figuring out the cause of this is of great importance.

I'm also seeing some logging dropouts, but that is a separate issue.

**Comment by dagar** [comment]
@lamping7 there are position and velocity innovation test failures in both of your logs, but it's not yet clear to me why. At a minimum set EKF2_GPS_DELAY to 110 if you're using a ublox m8.
![image](https://user-images.githubusercontent.com/84712/27614791-edeb9ee0-5b71-11e7-8d9b-f83989a0fb7b.png)

**Comment by lamping7** [comment]
@dagar Thanks for the tip! I'll give that a shot as the HERE has a M8N chip. I'm not entirely sure how the EKF2_GPS_DELAY and EKF2_ASP_DELAY params became non-default, but I'll adjust and see if I can replicate the issues. Much appreciated.

**Comment by tubeme** [comment]
Can we apply the same delays as a test? Ours are 200.

**Comment by lamping7** [comment]
Did some more flying and the error bit didn't set. Thanks again.

**Comment by tubeme** [comment]
It is better with the new defaults. We changed the GPS as well, so it is working now.
