### ISSUE TITLE
ULOG Flight Plot: Ground Speed

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#7489]
Sorry for the silly question but I really cannot find a way to see the ground speed in Flight Plot with the new ULOG format.

We are doing MS5525 tests and I need the ground speed to compare it to the airspeed and I'm struggling in Flight Plot.

Can you point me to the parameter I should load in Flight Plot for Ground Speed?

Thanks

**Comment by dagar** [comment]
In FlightPlot use the velocities from vehicle_global_position and Abs.

![image](https://user-images.githubusercontent.com/84712/27603256-91d183be-5b43-11e7-9c12-f2a52d90f868.png)

If you have suggestions for flight review you can open issues here. https://github.com/PX4/flight_review

**Comment by tubeme** [comment]
@dagar Thanks!
