### ISSUE TITLE
MODE: Unsupported FCU while testing ros package

### ISSUE THREAD

**Issue by anudeepsekhar** [PX4/Firmware#7492]
im testing https://github.com/SujithSizon/ifor_o... on my drone with pixhawk connected via ftdi cable

on qgc sys_companion was set to 921600

here is my launch file

```
<launch>

<arg name="fcu_url" default= "/dev/ttyUSB0:921600"/>
<arg name="gcs_url" default="udp://:14556@192.168.1.5:14550" />
<arg name="tgt_system" default="1" />
<arg name="tgt_component" default="1" />


<node name="mavros" pkg="mavros" type="mavros_node" output="screen" required="true" clear_params="true">
	<param name="fcu_url" value="$(arg fcu_url)" />
	<param name="gcs_url" value="$(arg gcs_url)" />
	<param name="target_system_id" value="$(arg tgt_system)" />
	<param name="target_component_id" value="$(arg tgt_component)" />
	<param name="conn_heartbeat" value="5.0" />
	<param name="conn_timeout" value="5.0" />
	<param name="startup_px4_usb_quirk" value="true" />
	<param name="mocap/use_tf" value="true"/>
	<param name="mocap/use_pose" value="false"/>

	<rosparam command="load" file="$(find mavros)/launch/px4_pluginlists.yaml" />
	<rosparam command="load" file="$(find mavros)/launch/px4_config.yaml" />
</node>

<!--node name="ifor_offb2_node" pkg="ifor_offb2" type="ifor_offb2_node" output="screen">
</node-->

</launch>
```

here is the error output

> serf@serf-ubbu:~/catkin_ifor_ws$ roslaunch ifor_offb2 ifor_offb2_sim.launch
> ... logging to /home/sujith/.ros/log/466c714a-f7ac-11e6-a85a-201a069ba36f/roslaunch-sujith-ubbu-4366.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://sujith-ubbu:34754/
> 
> SUMMARY
> ========
> 
> CLEAR PARAMETERS
>  * /mavros/
> 
> PARAMETERS
>  * /mavros/cmd/use_comp_id_system_control: False
>  * /mavros/conn/heartbeat_rate: 1.0
>  * /mavros/conn/system_time_rate: 1.0
>  * /mavros/conn/timeout: 10.0
>  * /mavros/conn/timesync_rate: 10.0
>  * /mavros/conn_heartbeat: 5.0
>  * /mavros/conn_timeout: 5.0
>  * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
>  * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
>  * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
>  * /mavros/distance_sensor/hrlv_ez4_pub/orientation: ROLL_180
>  * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
>  * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
>  * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
>  * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
>  * /mavros/distance_sensor/laser_1_sub/id: 3
>  * /mavros/distance_sensor/laser_1_sub/orientation: ROLL_180
>  * /mavros/distance_sensor/laser_1_sub/subscriber: True
>  * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
>  * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
>  * /mavros/distance_sensor/lidarlite_pub/id: 1
>  * /mavros/distance_sensor/lidarlite_pub/orientation: ROLL_180
>  * /mavros/distance_sensor/lidarlite_pub/send_tf: True
>  * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
>  * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
>  * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
>  * /mavros/distance_sensor/sonar_1_sub/id: 2
>  * /mavros/distance_sensor/sonar_1_sub/orientation: ROLL_180
>  * /mavros/distance_sensor/sonar_1_sub/subscriber: True
>  * /mavros/fcu_url: /dev/ttyUSB0:57600
>  * /mavros/gcs_url: udp://:14556@192....
>  * /mavros/global_position/frame_id: fcu
>  * /mavros/global_position/rot_covariance: 99999.0
>  * /mavros/global_position/tf/child_frame_id: fcu_utm
>  * /mavros/global_position/tf/frame_id: local_origin
>  * /mavros/global_position/tf/send: False
>  * /mavros/image/frame_id: px4flow
>  * /mavros/imu/angular_velocity_stdev: 0.000349065850399
>  * /mavros/imu/frame_id: fcu
>  * /mavros/imu/linear_acceleration_stdev: 0.0003
>  * /mavros/imu/magnetic_stdev: 0.0
>  * /mavros/imu/orientation_stdev: 1.0
>  * /mavros/local_position/frame_id: fcu
>  * /mavros/local_position/tf/child_frame_id: fcu
>  * /mavros/local_position/tf/frame_id: local_origin
>  * /mavros/local_position/tf/send: False
>  * /mavros/local_position/tf/send_fcu: False
>  * /mavros/mission/pull_after_gcs: True
>  * /mavros/mocap/use_pose: False
>  * /mavros/mocap/use_tf: True
>  * /mavros/plugin_blacklist: ['safety_area', '...
>  * /mavros/plugin_whitelist: []
>  * /mavros/px4flow/frame_id: px4flow
>  * /mavros/px4flow/ranger_fov: 0.0
>  * /mavros/px4flow/ranger_max_range: 5.0
>  * /mavros/px4flow/ranger_min_range: 0.3
>  * /mavros/safety_area/p1/x: 1.0
>  * /mavros/safety_area/p1/y: 1.0
>  * /mavros/safety_area/p1/z: 1.0
>  * /mavros/safety_area/p2/x: -1.0
>  * /mavros/safety_area/p2/y: -1.0
>  * /mavros/safety_area/p2/z: -1.0
>  * /mavros/setpoint_accel/send_force: False
>  * /mavros/setpoint_attitude/reverse_throttle: False
>  * /mavros/setpoint_attitude/tf/child_frame_id: attitude
>  * /mavros/setpoint_attitude/tf/frame_id: local_origin
>  * /mavros/setpoint_attitude/tf/listen: False
>  * /mavros/setpoint_attitude/tf/rate_limit: 10.0
>  * /mavros/setpoint_position/tf/child_frame_id: setpoint
>  * /mavros/setpoint_position/tf/frame_id: local_origin
>  * /mavros/setpoint_position/tf/listen: False
>  * /mavros/setpoint_position/tf/rate_limit: 50.0
>  * /mavros/startup_px4_usb_quirk: True
>  * /mavros/sys/disable_diag: False
>  * /mavros/sys/min_voltage: 10.0
>  * /mavros/target_component_id: 1
>  * /mavros/target_system_id: 1
>  * /mavros/tdr_radio/low_rssi: 40
>  * /mavros/time/time_ref_source: fcu
>  * /mavros/time/timesync_avg_alpha: 0.6
>  * /mavros/vibration/frame_id: vibration
>  * /mavros/vision_pose/tf/child_frame_id: vision
>  * /mavros/vision_pose/tf/frame_id: local_origin
>  * /mavros/vision_pose/tf/listen: False
>  * /mavros/vision_pose/tf/rate_limit: 10.0
>  * /mavros/vision_speed/listen_twist: False
>  * /rosdistro: indigo
>  * /rosversion: 1.11.20
> 
> NODES
>   /
>     ifor_offb2_node (ifor_offb2/ifor_offb2_node)
>     mavros (mavros/mavros_node)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> core service [/rosout] found
> process[mavros-1]: started with pid [4385]
> process[ifor_offb2_node-2]: started with pid [4386]
> 
> [ifor] test set_mission!
> 
> Breakpoint Start
> [ INFO] [1487623163.156503781]: FCU URL: /dev/ttyUSB0:57600
> [ INFO] [1487623163.156705257]: serial0: device: /dev/ttyUSB0 @ 57600 bps
> [ INFO] [1487623163.157237047]: GCS URL: udp://:14556@192.168.1.5:14550
> [ INFO] [1487623163.157366761]: udp1: Bind address: 0.0.0.0:14556
> [ INFO] [1487623163.157427312]: udp1: Remote address: 192.168.1.5:14550
> [ INFO] [1487623163.193419339]: Plugin 3dr_radio loaded and initialized
> [ INFO] [1487623163.196660315]: Plugin actuator_control loaded and initialized
> [ INFO] [1487623163.197856503]: Plugin altitude loaded and initialized
> [ INFO] [1487623163.246939729]: Plugin cam_imu_sync loaded and initialized
> [ INFO] [1487623163.252800740]: Plugin command loaded and initialized
> [ INFO] [1487623163.252858652]: Plugin distance_sensor blacklisted
> [ INFO] [1487623163.261287695]: Plugin ftp loaded and initialized
> [ INFO] [1487623163.270479690]: Plugin global_position loaded and initialized
> [ INFO] [1487623163.271227488]: Plugin hil_controls loaded and initialized
> [ INFO] [1487623163.271266062]: Plugin image_pub blacklisted
> [ INFO] [1487623163.282174590]: Plugin imu_pub loaded and initialized
> [ INFO] [1487623163.289392481]: Plugin local_position loaded and initialized
> [ INFO] [1487623163.290210752]: Plugin manual_control loaded and initialized
> [ INFO] [1487623163.295340977]: Plugin mocap_pose_estimate loaded and initialized
> [ INFO] [1487623163.298095037]: Plugin param loaded and initialized
> [ INFO] [1487623163.303814321]: Plugin px4flow loaded and initialized
> [ INFO] [1487623163.308999712]: Plugin rc_io loaded and initialized
> [ INFO] [1487623163.309165119]: Plugin safety_area blacklisted
> [ INFO] [1487623163.315203583]: Plugin setpoint_accel loaded and initialized
> [ INFO] [1487623163.330421777]: Plugin setpoint_attitude loaded and initialized
> [ INFO] [1487623163.337432637]: Plugin setpoint_position loaded and initialized
> [ INFO] [1487623163.351500556]: Plugin setpoint_raw loaded and initialized
> [ INFO] [1487623163.354667402]: Plugin setpoint_velocity loaded and initialized
> [ INFO] [1487623163.361353356]: Plugin sys_status loaded and initialized
> [ INFO] [1487623163.365031065]: Plugin sys_time loaded and initialized
> [ INFO] [1487623163.366439474]: Plugin vfr_hud loaded and initialized
> [ INFO] [1487623163.366496505]: Plugin vibration blacklisted
> [ INFO] [1487623163.378667528]: Plugin vision_pose_estimate loaded and initialized
> [ INFO] [1487623163.382559340]: Plugin vision_speed_estimate loaded and initialized
> [ INFO] [1487623163.386606565]: Plugin waypoint loaded and initialized
> [ INFO] [1487623163.386680579]: Autostarting mavlink via USB on PX4
> [ INFO] [1487623163.386739021]: Built-in SIMD instructions: SSE, SSE2
> [ INFO] [1487623163.386777317]: Built-in MAVLink package version: 2016.5.20
> [ INFO] [1487623163.386798265]: Built-in MAVLink dialect: ardupilotmega
> [ INFO] [1487623163.386814579]: MAVROS started. MY ID 1.240, TARGET ID 1.1
> [ERROR] [1487623169.335451643]: MODE: Unsupported FCU

Also tried commenting out arming and setmode code and did rosrun mavros mavsis mode -c OFFBOARD

which again resulted in [Error] ......... MODE: Unsupported FCU

**Comment by TobiMiller** [comment]
are you using the PX4 Stack? what happens when you start 
`roslaunch mavros px4.launch`
?

**Comment by TSC21** [comment]
@anudeepsekhar can you please paste the output of `rostopic echo -n1 /diagnostics` and `rosrun mavros checkid` after you run the node? From what usually happens, `[Error] ......... MODE: Unsupported FCU` may appear after a bad connection, so I'm asking to show the output of `diagnostics` to be sure. If that's the case, may be bad wiring or faulty FTDI module/cable.

**Comment by TSC21** [comment]
@anudeepsekhar updates?

**Comment by anudeepsekhar** [comment]
@TSC21 sorry for the late reply i will paste the output of the diagnostics by tomorrow morning as i am currently away from my lab.

**Comment by anudeepsekhar** [comment]
@TSC21 When we checked the connection and re soldered the connections the off-board was working and the issue is solved now. It was a wiring issue.
