### ISSUE TITLE
HIL broken in 1.6 for multi rotors

### ISSUE THREAD

**Issue by sytelus** [PX4/Firmware#7516]
Something has happened after 1.5.5 Stable Release. In jMavSim with HIL using firmware releases after 1.5.5, I can arm/disarm quadrotor but it never takesoff from the ground. Sometime I see message "takeoff detected" even though quadrotor is still on the ground and not moving. I just tested out 1.6.3 stable release and can reproduce issue consistently on two Pixhawk v2 devices. The issue doesn't occur in 1.5.5 Stable Release.

**Comment by sytelus** [comment]
Hi, any update on this? There are several users in AirSim is trying out PX4 and hitting wall with this issue. It looks like vehicle is quite shaky in last working release 1.5.5/

**Comment by bkueng** [comment]
Hi @sytelus. Can you tell us exactly how you start HIL, including airframe config etc? I just used HIL on a Pixracer with master and jMAVSim a few days ago and it works fine.

**Comment by LorenzMeier** [comment]
I verified it also here - working perfectly fine with jMAVSim on Mac OS.

<img width="999" alt="screen shot 2017-07-29 at 18 02 50" src="https://user-images.githubusercontent.com/1208119/28746247-cfd6b57c-7488-11e7-8358-5d320b0778fc.png">

I'm currently working on code and docs to make it easier to set up.
https://github.com/PX4/Firmware/pull/7697
