### ISSUE TITLE
There may be a bug in hmc5883.cpp

### ISSUE THREAD

**Issue by lcxjason** [PX4/Firmware#7528]
In the function set_range(unsigned range):
Current code:
if (range < 1) {
  _range_bits = 0x00;
  _range_scale = 1.0f / 1370.0f;
  _range_ga = 0.88f;

} else if (range <= 1) {
  _range_bits = 0x01;
  _range_scale = 1.0f / 1090.0f;
  _range_ga = 1.3f;
}
I think it should be
 else if(range<=1.5f) {range_bits = 0x01...}

**Comment by LorenzMeier** [comment]
Thanks! Fixed in c89bd5c8fd878ccdf06c84da457543e1558e93d3.
