### ISSUE TITLE
how can I generate IR or bytecode for each source code file?

### ISSUE THREAD

**Issue by Tigerly** [PX4/Firmware#7533]
I'm trying to generate call graph (need to compile and generate IR or bytecode first) for the PX4 source code by using LLVM clang.
e.g.,
..PX4/Firmware/src/modules/navigator$ clang++ -S -emit-llvm land.cpp -o - | opt -analyze -dot-callgraph

However, it seems the source code files cannot be compiled normally.
It always says "land.cpp:47:10: fatal error: 'systemlib/err.h' file not found #include <systemlib/err.h>"
if I change this header file's path, it will complain other header files.

My question is:
How can I generate IR or bytecode for the PX4 souce code (e.g., land.cpp in PX4/Firmware/src/modules/navigator)

Thanks in advance!

**Comment by dagar** [comment]
Try it within the SITL posix build.

`make posix_sitl_default`

Then within the build directory you can see how land.cpp is actually built in `build_posix_sitl_default/compile_commands.json`.

**Comment by dagar** [comment]
Please reopen if this didn't answer your question.
