### ISSUE TITLE
Starting a mission / taking off should not arm the vehicle if conditions are not met

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#7543]
Related to: https://github.com/mavlink/qgroundcontrol/issues/5388

**Comment by dagar** [comment]
This is how/why I implemented MAV_CMD_MISSION_START and COM_ARM_MIS_REQ for a slightly different reason.
I'd be interested in implementing any other ideas for locking this down.

**Comment by LorenzMeier** [comment]
Should we deprecate the other interface?

**Comment by dagar** [comment]
What's the other interface?

**Comment by LorenzMeier** [comment]
Sequential execution. I'm hacking on Firmware and QGC trying to fix this right now.

**Comment by LorenzMeier** [comment]
Turns out its entirely a QGC issue and the fix is here: https://github.com/mavlink/qgroundcontrol/pull/5415
