### ISSUE TITLE
Unexpected back transition

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#7544]
From flight test team, FYI @dagar http://logs.px4.io/plot_app?log=78d033a5-d3e8-4e18-a73f-3602f21e78ab

@bresch Can you please have a look as well?

**Comment by dagar** [comment]
It was initiated by a brief loss of RC.

![image](https://user-images.githubusercontent.com/84712/27939293-cad6c61a-6291-11e7-935e-3d670a82b09e.png)

The vtol controller directly handles the transition switch. It should probably be centralized with the rest of the switch handling.

**Comment by LorenzMeier** [comment]
I think its architecturally ok. The manual control state should not update when RC is lost.

**Comment by dagar** [comment]
We don't log manual_control_setpoint, but in this case the RC inputs changed before the signal_lost was set. Is this just the configuration of the RC receiver?
@santiago3dr

![image](https://user-images.githubusercontent.com/84712/27959728-95b2ec24-62f6-11e7-954f-65ea059f5622.png)

**Comment by LorenzMeier** [comment]
RC loss.
