### ISSUE TITLE
Inconsistent RTL state 

### ISSUE THREAD

**Issue by jianyang1** [PX4/Firmware#7567]
When RTL is being activated, instead of changing the position setpoint to Home, its first changes the position setpoint to the place where is where commend from. Only after its reaching that location, the setpoint is changed to Home position.

In Case of de-activate RTL once and than re-activate it again at any point, the setpoint is changing directly to Home position as it should

Produced on SITL using 1.6.3

http://review.px4.io/plot_app?log=843cd12c-8a4c-48c0-b75c-626258cc04bb
![rtl](https://user-images.githubusercontent.com/30023254/27994853-4e6b21cc-64ce-11e7-9001-cd9b10e3a8d5.png)

**Comment by dagar** [comment]
The first stage of RTL is to climb (if needed) to RTL_RETURN_ALT in place.

You can see what RTL is doing here - https://github.com/PX4/Firmware/blob/master/src/modules/navigator/rtl.cpp#L129

**Comment by jianyang1** [comment]
i understand, yet i think reaching to RTL_RETURN_ALT should be enough for changing the set point to home.
its still keep flying towards this irrelevant x,y poition even after climbing to RTL_RETURN_ALT

**Comment by BazookaJoe1900** [comment]
@dagar and @jianyang1  just by looking at the plot I see issue, the gap from the position to the target is not "closed" on some points as it should.

**Comment by Stich123** [comment]
What about this issue?
I tried to recreate it but couldn't, did it resolve in the latest version? @dagar

**Comment by BazookaJoe1900** [comment]
The issue still exist, its not stall...

**Comment by santiago3dr** [comment]
this issue was resolved prior to 1.8.0 release
here's the pr that addressed it
#8412
