### ISSUE TITLE
The buzzer keeps ringing after power on

### ISSUE THREAD

**Issue by lvyanxuan** [PX4/Firmware#7590]
I have burn the latest firmware，but found that the buzzer kept ringing after power on. It won't stop until i press the safety switch. Is there anything wrong with the new firmware?

**Comment by tubeme** [comment]
What you mean by the latest?? I just flashed 1.6.4 stable with the QGC and it works perfectly well. Probably the initial loading is a bit slow on power up but other than that works OK.

**Comment by LorenzMeier** [comment]
Can you reset the parameters and configure again?

<img width="1198" alt="screen shot 2017-07-11 at 13 24 24" src="https://user-images.githubusercontent.com/1208119/28066194-4b929560-663c-11e7-8c33-6f45f3abc9dc.png">

**Comment by lvyanxuan** [comment]
The QGC version is V3.2.0. And the Firmware version is 1.6.4dev. it might also be an error, Because I choose the stable version when i burn it.
I have tried to reset the parameters, but it just keeps ringing.

**Comment by LorenzMeier** [comment]
Can you take a video of the setup?

**Comment by lvyanxuan** [comment]
Do you mean showing you all the parameters?

**Comment by lvyanxuan** [comment]
Oh it was because that i did't insert the SD card...Thank you for your help.
