### ISSUE TITLE
1.6.4 Stable reported as 1.6.4dev 

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#7592]
With the latest QGC master. We flash Stable.

**Comment by LorenzMeier** [comment]
Thanks. We need to fix this once and for all. @dagar We need to change our CI tooling to re-build all branches that a tag applies to.

**Comment by dagar** [comment]
I'll take a look, but the shortterm fix is likely going to be following a particular workflow working within the constraints of travis-ci/semaphore. With jenkins we could re-build based on branches containing tags if needed.

What's your workflow now? When and where do you tag (and push), and then how are you updating beta and stable?

**Comment by dagar** [comment]
Should have been fixed. I'll double check that it's completely resolved for v1.7.0.
