### ISSUE TITLE
v1.6.4: Pause is not working

### ISSUE THREAD

**Issue by jianyang1** [PX4/Firmware#7594]
tested v1.6.4 on SITL, Pause commend seem to be not responding at all

**Comment by LorenzMeier** [comment]
Checking.

**Comment by tubeme** [comment]
Works just checked.

**Comment by LorenzMeier** [comment]
It does not work when you are in a mission. I fixed that in dbc7d805f2. If you flash the current developer version it should be fine again.

**Comment by jianyang1** [comment]
Thanks, works just fine now.
I think its should be included in the stable release as well, that’s a serious safety issue right now
