### ISSUE TITLE
Snapdragon flight spektrum not receiving

### ISSUE THREAD

**Issue by damul** [PX4/Firmware#7615]
Hi, 

I cloned PX4/Firmware master branch.
I installed Hexagon SDK 3.0 and other tools with ATLFlight/cross-toolchain.

Building and uploading PX4 is successful with "make eagle_default" and "make eagle_default upload".
I can connect to PX4 with QGC, but radio is not responding. 

With deployed firmware from intrinsyc (3.1.3_PX4.zip from support.intrinsyc)
spektrum data was received.

What can I do for this problem?

**Comment by r0gelion** [comment]
Hi @damul ,

When using eagle_default connect the receiver to J12 instead of J15.

**Comment by damul** [comment]
Hi, @r0gelion.
Thank you for your answer. 
Is the pin map same as J15? (Is it Ok to just move connector to J12?)
Where can I find the information?

**Comment by r0gelion** [comment]
Hi,

You can find the information [here](https://dev.px4.io/en/flight_controller/snapdragon_flight.html) at RC Wiring section

**Comment by damul** [comment]
Thank you. I missed exact number.
