### ISSUE TITLE
Flash PX4 onto Crazyflie 2 problem

### ISSUE THREAD

**Issue by ageofish** [PX4/Firmware#7624]
I tried to flash PX4 onto my crazyflie 2, I tried master, stable and beta (via QGroundControl or manually), all of these finished flashing (erase, program, verify), but CF wasn’t able to connect with QGC. It seems the flie is still in boot loading mode (green M1 light blinks), QGC firmware tab detected the flie and suggest flashing:

Found device: PX4 FMU V2
connected to boot loader:
version: 5
Board ID: 12
Flash size: 1032192

I tried using the latest PX4 firmware, master, stable, and beta, none were able to connect after flashing.
On the other hand, I had a older piece of code “50ecee9d” Wed Jun 7 14:19:57 2017 that I can flash and connect with QGC, calibrate and so on.
Is this a known issue? Or did I miss something obvious?

<img width="169" alt="9ad1fb9b-9438-40be-9e0b-46fedc485e04" src="https://user-images.githubusercontent.com/241359/28243821-c6186b08-6a0a-11e7-84fb-22854ed15d8f.png">

<img width="501" alt="a60c7e48-bb42-4bb2-953e-7d8d916e8834" src="https://user-images.githubusercontent.com/241359/28243826-d277ec20-6a0a-11e7-80f5-5e659caed042.png">

**Comment by YuhangWUST** [comment]
I have the same problem just like you. I'm Looking for the solution, and I haven't found it yet. Do you have any idea about this?

**Comment by dagar** [comment]
@dennisss do you know anything about this?

**Comment by YuhangWUST** [comment]
@ageofish I have already used the older piece code and succeeded flash and connect with QGC and so on, but cf2 cant connect with android QGC or official crazyflie phone app  and cant fly. Have you solved it?

**Comment by ageofish** [comment]
Just saw the replies. Yes, I also found older commits on stable branch that works.
And I did a "binary search" on the commit history, it seems 1be089cf started to break the "stable" branch, maybe someone can take a look to see exactly why?

And what's interesting is that if I start with a working commit, and flash anything after 1be089cf, it still works until another certain commit. Then if I start with a non-working commit, flashing anything after 1be089cf does not work. Painful discovery, but hopefully someone with more knowledge will know exactly why given the hints.

**Comment by dennisss** [comment]
I think the issue is right here: https://github.com/PX4/Firmware/commit/fc30f2906fd8b8dc5fe52c38a887e9e4e56b2e0a, some odd timing issue with the magnetometer resets

**Comment by YuhangWUST** [comment]
Thank for your help. It works. But there seems to be another problem, We use the latest firmware, can now connect to the computer side of the QGC ground station for debugging, but can not take off, and not connected to the mobile terminal QGC ground station, but the crazyflie official app can be connected, Between them seems to be able to communicate, because when I put the throttle down and the direction of the bar Right, M2, M3 bright blue light, and M1 extinguished, but it still can not take off. How can i solve this problem?

**Comment by dennisss** [comment]
@YuhangWUST I see what you mean now. I've retested with a clean build and saw that one more little fix was needed. See https://github.com/PX4/Firmware/pull/7658
