### ISSUE TITLE
I want to know code means in ecl_l1_pos_controller.cpp

### ISSUE THREAD

**Issue by lahyeon** [PX4/Firmware#7629]
line205 in ecl_l1_pos_controller.cpp
	
"_lateral_accel = _K_L1 * ground_speed * ground_speed / _L1_distance * sinf(eta);"

I want to know this code means.

**Comment by bresch** [comment]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.212.9789&rep=rep1&type=pdf
See eq. (1)

**Comment by lahyeon** [comment]
I appreciate your help! 👍
