### ISSUE TITLE
Laser Altimeter and terrain follow.

### ISSUE THREAD

**Issue by russdelaneyuk** [PX4/Firmware#7630]
When using a laser altimeter and the "Terrain" option in mission planner, We have found that if the drone transits over water (pond) the drone will enter RTL.
This is due to the reduced range of the Laser Alt over water, it appears to see the loss of laser range as a terrain error (RTL)

Is there a way or addition that can be made to effectively continue mission in the event of? Using Baro only?
Thanks in advance
Laser Alt used SF11c

**Comment by mhkabir** [comment]
This issue tracker is for PX4. Please use QGroundControl and flash the PX4 Firmware if you want support from us.
