### ISSUE TITLE
Pixhawk does not connect to QGC [when using XBee link]

### ISSUE THREAD

**Issue by samacumen** [PX4/Firmware#7633]
I replaced my working Telemetry (433Hz) radio link between Pixhawk (v.1.6.4) and QGroundControl (v3.2) with Xbee Pro link. My setup looks as follows:

XBee Pro S1 configured at 57600 baud, 8N1.

Xbee1 (PC) <=> Xbee2 (PC): Works great! The setup is OK.
QGC (Xbee Pro) <=> Pixhawk (Xbee Pro, connected via TELEM 1 (**Not working**)!

On the Pixhawk side TELEM1 pin, I have connected **5V,GND, TX and RX** to respective Xbee connections.
 
After testing, I find that the heartbeat is being sent from the QGC side (RX led blinks on Xbee at PC) and is being received at the Pixhawk (Xbee) side. RSSI led on both ends are green, as some data is exchanged. However, looks like no data is being sent from Pixhawk Xbee to the QGC Xbee. This results in no incoming heartbeats, thus no connection is established on QGC side.

I have also seen this issue on various forums but no one seems to have figured out, for e.g. 
http://diydrones.com/forum/topics/xbee-as-telemetry-module-for-pixhawk-does-not-work

To me it looks like only when Pixhawk is introduced, this tends to be happening. Any help is welcome!

**Comment by LorenzMeier** [comment]
This is related to your link and not a software issue. Please ask the manufacturer of your link.
