### ISSUE TITLE
OFFBOARD mode horizontal velocity

### ISSUE THREAD

**Issue by lyhsteven** [PX4/Firmware#7639]
I am now doing SLAM in offboard mode via vision, I wonder know if someone can help that which param is controlling the horizontal velocity in offboard mode. For my uav flys too fast to the target point.
I would so glad.

**Comment by andrea-nisti** [comment]
Try this `MPC_XY_VEL_MA`

**Comment by lyhsteven** [comment]
@andrea-nisti Thanks, I will test it.

**Comment by lyhsteven** [comment]
Hey @andrea-nisti, I have tested the param `MPC_XY_VEL_MAX`, but It seems not work.

**Comment by andrea-nisti** [comment]
Which value did you put and what velocity did the robot achieved?

**Comment by lyhsteven** [comment]
@andrea-nisti I turned the velue `MPC_XY_VEL_MAX` from 8(default) to 1, and I use the UAV in offboard mode. When I gave a target point to the UAV, it reached the target very fast, I didn't know what happened.

**Comment by andrea-nisti** [comment]
By very fast you mean more than 1 m/s ?

**Comment by TSC21** [comment]
@lyhsteven is this solved to you?

**Comment by lyhsteven** [comment]
@TSC21 I've tested it in my UAV, it worked in `MISSIOM MODE`, but still not in `OFFBOARD`. It may has some problems in my code, I will check it and then give an answer. So we can close the question first. 
Thx.
