### ISSUE TITLE
Is End-To-End Ethernet (Ad Hoc) Control of Pixhawk controller over Wifi possible?

### ISSUE THREAD

**Issue by StephanSalas** [PX4/Firmware#7652]
I would like to build an ad-hoc network from my PC via VPN to an on-board computer that directly controls the Pixhawk controller.

Is this possible?

**Comment by dagar** [comment]
The common way to do this is with an esp8266 or companion computer running linux connected to the pixhawk via serial. There are many network serial bridges available.

Bringing up networking directly in NuttX is possible, but a lot more work.

**Comment by StephanSalas** [comment]
I am currently exploring both these options. I will comment further with a guide if possible.
