### ISSUE TITLE
MISSION_ITEM_REACHED is not sent

### ISSUE THREAD

**Issue by imrhch** [PX4/Firmware#7679]
When mission point is reached, Mission::set_mission_item_reached() is called from Mission::on_active(), setting mission_result.reached to true.
But later in the Mission::on_active(),the set_mission_items() (https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L195) is called and the "reached" flag is reset to false here
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L1364 (called from https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L799)

This happens before the "reached" flag is checked in the MavlinkMissionManager::send() and since the mission_result.reached is false (https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_mission.cpp#L350) the message is not sent

I have a feeling that firmware version from last year didn't have this problem.

**Comment by LorenzMeier** [comment]
I'm getting this here in HITL successfully. Please re-open if I missed something.

<img width="999" alt="screen shot 2017-07-29 at 18 02 50" src="https://user-images.githubusercontent.com/1208119/28746225-37a38e88-7488-11e7-9494-a6caac489a44.png">

**Comment by imrhch** [comment]
I'm sorry for inacurate report. I was bit confused that MISSION_ITEM_REACHED is sent when the whole mission is done (I expected it to be sent in every mission point), which may be expected feature. And particularly I missed the MISSION_CURRENT which works perfectly O:)
So thank you very much for directing me.
