### ISSUE TITLE
add MAVLink FLIGHT_INFORMATION support

### ISSUE THREAD

**Issue by jianyang1** [PX4/Firmware#7706]
It would be great if `FLIGHT_INFORMATION` could be implement in PX4 using `MAV_CMD_REQUEST_FLIGHT_INFORMATION` in order to calculate flight time from drone messages 

right now QGC has flight timer support (https://github.com/mavlink/qgroundcontrol/pull/5100 )- but exiting the software will reset that timer which doesnt make this widget so reliable

**Comment by TSC21** [comment]
@jianyang1 do you plan to implement this?
