### ISSUE TITLE
qgroundcontrol log file. Look at the graph and let me know the problem.

### ISSUE THREAD

**Issue by seungri1** [PX4/Firmware#7712]
**Bug Report** or **Feature Request**

For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](slack.px4.io). Issue reports need to contain the items below:

 - Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/flight-reporting.html))
 - Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/)
 - Expected behavior and actual behavior.
 - Steps to reproduce the problem.
 - Specifications like the version of the project, operating system, or hardware.

**Comment by mhkabir** [comment]
Please share the log.
