### ISSUE TITLE
Cannot control airplane with radio AT9s in HIL with Xplane 10

### ISSUE THREAD

**Issue by bsowlin** [PX4/Firmware#7736]
I tried to do HIL by following this link: https://dev.px4.io/en/simulation/hitl.html
I selected HiLStar17 in Xplane 10. I connected Xplane 10 with QGC 3.2.2 (around 19 Hz) by using Pixhawk (PX4 firmware 1.6.5). Everything worked well until I armed on my radio, airplane in Xplane 10 just go automaticly roll right for eternity ignore my command from radio. What should I do to fix this? help me please. Thank you.

**Comment by pgorczak** [comment]
I've encountered the same problems. My current workaround is using firmware v1.5.5 as mentioned in https://github.com/PX4/Firmware/issues/5651#issuecomment-324216864. X-Plane HiL just doesn't seem to work with newer firmwares.
