### ISSUE TITLE
Feature: MAVROS fast-RTPS support

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#7759]
This would be a resulting implementation and support after a talk with @vilhjalmur89, @bkueng and @JaimeMartin held two weeks ago - https://github.com/mavlink/mavros/issues/768.

**Comment by avinash-palleti** [comment]
Please check the WIP repo https://github.com/avinash-palleti/mavros/tree/rtps to integrate fast-RTPS support into MAVROS and provide feedback.

**Comment by TSC21** [comment]
This is no longer going to MAVROS. We now have https://github.com/PX4/px4_ros_com
