### ISSUE TITLE
motor_test not part of the nsh commands ?

### ISSUE THREAD

**Issue by gjkunde** [PX4/Firmware#7760]
Dear All,

I selected a 6 rotor airframe and downloaded the firmware for
pixhawk 2.1  but I seem to not see motor_test when I am logged into nsh. 

What could be the reason and how would I test the wiring without the motor_test
command ?

**Comment by LorenzMeier** [comment]
Most people just arm the airframe and hold a strip of paper against the motor to see which way it flips (and hence check if rotation is correct). In terms of wiring: Using the wiring diagrams this is usually easy to get right on first try.

I've added `motor_test` now to the FMUv3 target: `make px4fmu-v3_default upload`.

**Comment by gjkunde** [comment]
There seems to be a problem with that, I will open a new issue for this is closed ?
