### ISSUE TITLE
Px4flow initial value wrong and does not change in flight

### ISSUE THREAD

**Issue by amanchandra333** [PX4/Firmware#7797]
I am using Pixhawk 2 with px4fmu-v2_lpe firmware. I am trying to integrate px4flow with it. When I give the takeoff command from qgroundcontrol (OFFBOARD flight mode), the drone flies away and crashes. I checked the height received using mavros under the topic /mavros/local_position/pose and it was around 0.5 meters.

[Here ](https://logs.px4.io/plot_app?log=4b3ec543-fb4c-4123-82ba-b3ab56c9e566) is the link to the flight data plots.

**Comment by mhkabir** [comment]
Looks like the estimator diverged. Can you please try flying with EKF2 with optical flow fusion enabled and some rangefinder connected (https://dev.px4.io/en/tutorials/optical_flow.html)?
