### ISSUE TITLE
Look at the problem and find the problem. Please.

### ISSUE THREAD

**Issue by seungri1** [PX4/Firmware#7807]
https://logs.px4.io/plot_app?log=0e563fd9-beca-4983-93df-8fcbe7a6e503

Look at the problem and find the problem. Please.

**Comment by LorenzMeier** [comment]
Could you please provide a proper issue description? "It doesn't work" is not good enough and we don't have time to reverse-engineer what issue you had. Please tell us what we should be looking for and what you observed.

**Comment by LorenzMeier** [comment]
Closing as stale.

**Comment by LorenzMeier** [comment]
The very high gyro noise is also an issue: https://logs.px4.io/plot_app?log=0e563fd9-beca-4983-93df-8fcbe7a6e503#Nav-Raw-Angular-Speed-Gyroscope
