### ISSUE TITLE
Feature: provide HIL interface with Gazebo

### ISSUE THREAD

**Issue by TSC21** [PX4/Firmware#7810]
mavlink/mavros#684 is merged, so a interface can be created with Gazebo, similar to what is done with `rotors_simulator` but using MAVROS as the bridge. Will PR as soon as I have a stable solution.

**Comment by whyscience** [comment]
Exciting!

**Comment by mzahana** [comment]
@TSC21 are you able to do HIL with Gazebo?

**Comment by TSC21** [comment]
No. Still working on it.

**Comment by hamishwillee** [comment]
@TSC21 Let me know/when/if you get this done so we can document it. HIL is a bit of a pain currently so having an ongoing supported solution would be really nice.

**Comment by TSC21** [comment]
This is done without the need of ROS
