### ISSUE TITLE
Flight Performance issue with Intel Aero on master

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#7811]
When flying the Aero in posctrl on master, it's not stable: when descending it twitches and has sudden altitude drops. @LorenzMeier and @MaEtUgR think there's a problem with the land detector.

I don't have a useful log, but it's easily reproducible.

@Stifael can you look into that?

**Comment by MaEtUgR** [comment]
I'm pretty sure this was the first stage of landing detection kicking in regularly.

**Comment by Stifael** [comment]
@bkueng, what was the landspeed that you used during the flight?

**Comment by bkueng** [comment]
I did not change any params, so either default or the one set by the airframe

**Comment by MaEtUgR** [comment]
I quickly checked `LAND_SPEED` and it seems to be 0.5m/s on the aero we tested.
