### ISSUE TITLE
Rename VDev to CDev

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#7817]
This pattern is becoming quite common. Would it make sense to rename VDev to CDev or otherwise find an acceptable common name?

![image](https://user-images.githubusercontent.com/84712/29467346-22e514c2-840e-11e7-9115-6c4afd16dc2a.png)

Do we have any basic documentation that specifies when you need to use px4_{open, close, read, write, poll} vs the regular version? There's lots of confusion here.

@davids5 @mcharleb Thoughts?

**Comment by mcharleb** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORBDevices.hpp#L71

You can't have both VDev and CDev be called the same thing when they are used concurrently in NuttX

**Comment by mcharleb** [comment]
https://github.com/PX4/Firmware/blob/master/src/modules/uORB/uORBDevices.hpp#L49

**Comment by mcharleb** [comment]
CDev is an in-kernel character driver. VDev is a userspace virtual device.

**Comment by dagar** [comment]
Yes, but why does that matter from the perspective of PX4? VDev isn't even built on NuttX.

The other thing to keep in mind is that for the vast majority of devices the /dev entry is barely used within PX4 and never by the rest of the system. Nearly all drivers directly publish output as uORB messages, and for the next driver framework iteration I'd like to drop the character device entirely.

**Comment by mcharleb** [comment]
VDev IS used on Nuttx via the links I provided above.

**Comment by mcharleb** [comment]
Based on your proposed roadmap, I'd leave VDev, and try to remove all uses of CDev

**Comment by dagar** [comment]
That's still NuttX using CDev in place of VDev. They already provide nearly an identical interface, and merging them would allow us to fairly easily use the existing NuttX drivers cross platform.

Here's why I find this compelling. https://github.com/PX4/Firmware/pull/7864

**Comment by dagar** [comment]
Done.

**Comment by mcharleb** [comment]
@dagar The device lookup code should be profiled since it's an array lookup. Shold be ok as long as number of devices is small.

**Comment by dagar** [comment]
@bkueng recently changed it to a map for devices. We could do the same for the file map (still a static array).

**Comment by bkueng** [comment]
Most operations are using `get_vdev`, which has constant runtime, so that's good. `px4_open` is linear, but it's only heavily used during startup, for a couple of hundred items, so I think that's ok for now as well.
