### ISSUE TITLE
Quite different outputs between actuator 0,1 and 2,3

### ISSUE THREAD

**Issue by meteor0530** [PX4/Firmware#7823]
Hi,
I used px4flow and EKF2 for my quad to hold the position. When I switched to POSCTRL, the vehicle could keep stable for several seconds and then it began to vibrated and rotate in yaw. I found from the log that the actuator outputs 0,1 were smaller than 2,3, and motor 3,4 were overheated.
I have already calibrated the ESC and I don't know why it coming.
https://logs.px4.io/plot_app?log=57ad5a44-4bf8-43f2-9cac-534c595580fa

**Comment by LorenzMeier** [comment]
Make sure that all motors are level on the frame and make sure your center of gravity is correct. You have a problem with your mechanical layout.
https://logs.px4.io/plot_app?log=57ad5a44-4bf8-43f2-9cac-534c595580fa#Nav-Actuator-Outputs-Main
