### ISSUE TITLE
Actuator control doens't work with in mavros

### ISSUE THREAD

**Issue by andresR8** [PX4/Firmware#7854]
**Bug Report**

 - I would like to control the main outputs  using Actuator control group 0 and aux ports with a different Actuator control group( i.e. 2 or 3). I've configured correctly the main.mix and .aux.mix files. I can´t get any aux output when I published the actuator_control topic in mavros with the same group cofigured in .aux.mix file.

 - Steps to reproduce the problem: 
 --1. Configure the *.aux.mix to get input from a group different to 0
 --2 . In mavros, publish the topic actuator control with a group_mix configured previously.

* I guess the problem is that the number of group mix has not been taken into account here: https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1088 

 - PX4 v1.6.5dev , Pixhawk 2.4.6 ,  RaspberryPi3 UbuntuMate+ROS.

**Comment by TSC21** [comment]
This has nothing to do with mavros. You will have to wait for https://github.com/PX4/Firmware/pull/7477 to get merged
