### ISSUE TITLE
Master branch on Pixhawk v2 not started

### ISSUE THREAD

**Issue by whyscience** [PX4/Firmware#7857]
Try both compile from master branch and from QGC firmware flash, My pixhawk won't start and no beeping.
Tried on both Ubuntu 14.04 and 16.04, both gcc-arm-none-eabi-4_9 and 5_4.
Try v1.6.5, everything is OK.

**Comment by whyscience** [comment]
Do a test

![screenshot from 2017-08-24 11-51-28](https://user-images.githubusercontent.com/3918941/29648970-dc5db5f8-88c3-11e7-9a32-829112db7014.png)

- checkout t7,compile and flash, pixhawk will start
- checkout t5,compile and flash, pixhawk will NOT start
- checkout master(SHA ca24c8e2), pixhawk will NOT start
,- check out master, revert t5 (SHA 553c6492), pixhawk will start

so, it's very clear SHA 553c6492 cause this.

https://github.com/PX4/Firmware/commit/553c64925292d0fc99b46d9514eb6646472033e7


> px4fmu-v2:Init GPIO_VDD_3V3_SENSORS_EN off at reset


  Insure a 0.0 voltage initial condition on VDD_3V3_SENSORS
  By starting the GPIO_VDD_3V3_SENSORS_EN, low and deferring
  the GPIO init of the slave selects and drdy signals until
  board_app_initialize. We get ~ 80 ms of power off time
  with 0.00 voltage applied to the sensors.


![screenshot from 2017-08-24 12-03-28](https://user-images.githubusercontent.com/3918941/29649038-4410366c-88c4-11e7-9f8f-40f369c8f124.png)

**Comment by whyscience** [comment]
don't know the true reason, waiting for an answer

**Comment by TSC21** [comment]
@davids5 can you advise here?

**Comment by davids5** [comment]
@whyscience Thank you for the very detailed testing. 

I have a few questions that may help to figure this out.

When you say "Pixhawk v2", is that a Pixhawk 2 (AKA the cube) OR an Pixhawk (AKA FMUv2)?

What build command are you using?
make px4fmu???? 

What HW Brand and version is the board (have a link)? 

What other hardware connected to the FMU?

Is this on USB power or battery or both?

Do you have an FTDI debug cable you can connect? [Connecting via FTDI 3.3V Cable](https://dev.px4.io/en/debug/system_console.html)

If so please capture the output of the build that will not start.

With a build that runs can you use QGC's  to get the output of the `ver all` command?
Or use the MAVLink Shell [see](https://dev.px4.io/en/debug/system_console.html)

**Comment by whyscience** [comment]
- Pixhawk v2 means V2.4.6, the Pixhawk or px4fmu-v2
- command: `make px4fmu-v2_default upload`
- HW Brand: CUAV Pixhawk , this https://item.taobao.com/item.htm?spm=a1z10.5-c-s.w4002-16371268457.22.41f58d4cM5wP6g&id=38408494918
- Just the saftety switch/Telem/GPS  connected to the FMU
- USB power or/and battery both tried.
- I attach a FTDI to serial5, nothing come out. On a normal start,there is a lot info print.

**Comment by davids5** [comment]
@whyscience 
Thank you for the clarification and added information.
 
Please post the output `ver all` from a check out of master with 553c649 reverted.

**Comment by whyscience** [comment]
# startup info 

> WARN  [platforms__common] Reboot NOW.
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
[i] microSD mounted: /fs/microsd 
[hardfault_log] Fault Log is Armed
INFO  [param] selected parameter default file /fs/mtd_params
rgbled on I2C bus 2 at 0x55 (bus: 100 KHz, max: 100 KHz)
MS5611_SPI on SPI bus 4 at 14 (20000 KHz)
WARN  [ms5611] no device on bus 4
MS5611_SPI on SPI bus 1 at 3 (20000 KHz)
WARN  [bst] no devices found
INFO  [ver] match: PX4FMU_V2
WARN  [hmc5883] no device on bus 1 (type: 2)
WARN  [lis3mdl] no device on bus 2
WARN  [hmc5883] no device on bus 2 (type: 1)
MPU6000 on SPI bus 1 at 4 (1000 KHz)
WARN  [mpu6000] no device on bus 5
WARN  [mpu9250] probe failed! 104
WARN  [mpu9250] no device on bus 3
WARN  [mpu9250] probe failed! 255
WARN  [mpu9250] no device on bus 4
L3GD20 on SPI bus 1 at 1 (11000 KHz)
LSM303D on SPI bus 1 at 2 (11000 KHz)
ERROR [sdp3x_airspeed] reset failed
WARN  [sdp3x_airspeed] trying SDP3X 2
ERROR [sdp3x_airspeed] reset failed
WARN  [sdp3x_airspeed] SDP3X init fail
WARN  [sdp3x_airspeed] no SDP3X airspeed sensor connected
ERROR [sdp3x_airspeed] reset failed
WARN  [sdp3x_airspeed] trying SDP3X 2
ERROR [sdp3x_airspeed] reset failed
WARN  [sdp3x_airspeed] SDP3X init fail
WARN  [sdp3x_airspeed] no SDP3X airspeed sensor connected
WARN  [ms5525_airspeed] trying MS5525 address 2
WARN  [ms5525_airspeed] MS5525 init fail
WARN  [ms5525_airspeed] no MS5525 airspeed sensor connected
WARN  [ms4525_airspeed] init fail
WARN  [ms4525_airspeed] no MS4525 airspeed sensor connected
WARN  [ms4525_airspeed] init fail
WARN  [ms4525_airspeed] no MS4525 airspeed sensor connected
WARN  [ets_airspeed] no ETS airspeed sensor connected
WARN  [ets_airspeed] no ETS airspeed sensor connected
INFO  [load_mon] stack check enabled
ERROR [param] Parameter UAVCAN_ENABLE not found
INFO  [px4io] default PWM output device
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [mavlink] mode: OSD, data rate: 1000 B/s on /dev/ttyS2 @ 57600B
ERROR [param] Parameter UAVCAN_ENABLE not found
INFO  [ver] match: PX4FMU_V2
px4flow [215:100]
WARN  [px4flow] scanning I2C buses for device..
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
INFO  [logger] logger started (mode=all)
No autostart ID found 

# ver all info
> nsh> ver all
HW arch: PX4FMU_V2
FW git-hash: 3e46801d0f7948b97f87217499967f947c6c796c
FW version: 0.0.0 0 (0)
OS: NuttX
OS version: Release 7.18.0 (118620415)
OS git-hash: 8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06
Build datetime: Aug 25 2017 14:16:00
Build uri: localhost
Toolchain: GNU GCC, 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977]
MFGUID: 3337353833355107003f0045
MCU: STM32F42x, rev. 3
UID: 3F0045:33355107:33373538 
nsh>

**Comment by davids5** [comment]
@whyscience - On master do you get nothing at all on the console from a power cycle? What are the light showing?

**Comment by davids5** [comment]
@PX4TestFlights and I have run master on many different versions of the HW. 
I retested the px4fmu-v2_default on FMUv2 2.4.6 HW with MCU: STM32F42x, rev. 3 and MCU: STM32F42x, rev. y with the errata. It runs fine for me on both.

Since the commit that is causing your board to not boot is related to switching off the sensor power on boot, then on 80 ms later.  I can only guess that a) the board you have is not compatible. b) it is possible the mfg tried to power the CUP from the sensor power regulator, or c) the board is defective. 

If you have a scope, you may be able to see the cpu power cutting out after the bootloader runs.   

Also as a side note:

> MCU: STM32F42x, rev. 3

The above indicates that your board is capable of running the px4fmu-v3_default. Have you tried that build?

**Comment by whyscience** [comment]
![screenshot from 2017-08-26 09-24-19](https://user-images.githubusercontent.com/3918941/29737465-67ff1f34-8a40-11e7-9580-36064775df3a.png)
![screenshot from 2017-08-26 09-24-00](https://user-images.githubusercontent.com/3918941/29737464-67fec2fa-8a40-11e7-92e3-a0247930a09a.png)

These two are blinking
the blue(act) one is slow,
the B/E is fast

**Comment by davids5** [comment]
Fast blinking on the B/E LED on the right - indicates the board is in the bootloader. If it stays blinking for more than 5 second that means the download failed. Can you capture the screen output of the make px4fmu-v2_defualt upload command and post it here. 

If after 5 second, the light stays on solid that is a bus init failure. But since you have no output it sound like it is stuck in bootloader mode.

**Comment by davids5** [comment]
I just did a full DL and it worked fine.

```
nsh> ver all
HW arch: PX4FMU_V2
FW git-hash: 4e48d41c3daf650cb6f43531e2ea6cdf09d871a0
FW version: 1.6.5 0 (17171712)
OS: NuttX
OS version: Release 7.18.0 (118620415)
OS git-hash: 8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06
Build datetime: Aug 25 2017 16:29:13
Build uri: localhost
Toolchain: GNU GCC, 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]
MFGUID: 303533333036510400410026
MCU: STM32F42x, rev. 3
UID: 410026:30365104:30353333
```

**Comment by whyscience** [comment]
Upload process is just as usual.
It stays blinking all the time, no stop.

**Comment by davids5** [comment]
@whyscience  can you post this for your board?

```
1/1] uploading Firmware/build_px4fmu-v2_default/src/firmware/nuttx/px4fmu-v2_default.px4
Loaded firmware for 9,0, size: 1015608 bytes, waiting for the bootloader...
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.
Found board 9,0 bootloader rev 5 on /dev/serial/by-id/usb-3D_Robotics_PX4_BL_FMU_v2.x_0-if00
ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff type: ÿÿÿÿ
idtype: =FF
vid: ffffffff
pid: ffffffff
coa: //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8=

sn: 004100263036510430353333
chip: 20016419
family: STM32F42x
revision: 3
flash 2080768

Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.
```

**Comment by whyscience** [comment]
> Loaded firmware for 9,0, size: 1020676 bytes, waiting for the bootloader...
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.
Found board 9,0 bootloader rev 4 on /dev/serial/by-id/usb-3D_Robotics_PX4_BL_FMU_v2.x_0-if00
50583400 00ac2600 00100000 00ffffff ffffffff ffffffff ffffffff ffffffff b04fba15 82ad9a27 bd3cabae b612cc62 0c88d5a5 6efcc534 237cef7a 192d6374 0c2be783 1eaf9ca6 7e6b01f7 324bc681 7776e4a0 d4cb2c81 9eec5345 9990388c 62892119 69cbed84 909601e3 45dbb552 1c619c32 7fa53b87 9efce0af 0b4e3ab0 48c6d3c6 839ed255 0fe731dd 7edfb043 0554358f ed6df41f 97e0fe1e 21881ad2 ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff type: PX4
idtype: =00
vid: 000026ac
pid: 00000010
coa: sE+6FYKtmie9PKuuthLMYgyI1aVu/MU0I3zvehktY3QMK+eDHq+cpn5rAfcyS8aBd3bkoNTLLIGe7FNFmZA4jGKJIRlpy+2EkJYB40XbtVIcYZwyf6U7h5784K8LTjqwSMbTxoOe0lUP5zHdft+wQwVUNY/tbfQfl+D+HiGIGtI=

sn: 003a002c3133471831383530

Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.

[100%] Built target upload

**Comment by whyscience** [comment]
I notice that, there is no 

> chip: 20016419
family: STM32F42x
revision: 3
flash 2080768

**Comment by yl5006** [comment]
I have same problem

**Comment by whyscience** [comment]
@yl5006  Do you use the CUAV version?

**Comment by yl5006** [comment]
@whyscience yes I think it is

**Comment by yl5006** [comment]
It rebooting all the time but not start

**Comment by davids5** [comment]
@whyscience @yl5006 - the bootloader on the HW you have is OLD. It is rev 4 not rev 5.  

https://github.com/PX4/Bootloader/commit/a90981156cc074bfb642013df9dba4c44a4ef2a3

This is why the the messages are different.  But it does not explain the reboot or the hang. 

The hardware seems to be incompatible with the FMUv2 spec.  I am afraid without a schematic or a board I can not be of much help.  I would suggest you use a JTAG debugger to find where the problem is.

**Comment by yl5006** [comment]
GPIO_VDD_3V3_SENSORS_EN when set to low ，the Mic5332 may be reset power ，and the fmu lost power

**Comment by davids5** [comment]
@yl5006 - Are you confirming that the MCU is powered from the MIC5332 channel that is controlled by  VDD_3V3_SENSORS_EN?

This is how it should be wired:
![image](https://user-images.githubusercontent.com/1945821/29852491-0a6db7ca-8cd6-11e7-8108-e1ed6f85970d.png)

Note VOUT2 the FMU-VDD is gated by EN2 and it should be tied to VDD_5V_IN
and VOUT1 the VDD_3V2_SENSOR is gated by VDD_3V3_SENSORS_EN

**Comment by whyscience** [comment]
I can't.
Actually I know little about the hardware.
The CUAV Pixhawk is modified and so called optimezed one.
Maybe they change the PCB. 
I will contact them and try to figure out.

**Comment by yl5006** [comment]
How to populate R603 and R635？ both do not populated？

**Comment by gamoreno** [comment]
I have the same problem, and the same commit is the one causing it. I have a Holybro Pixhawk https://www.getfpv.com/holybro-px4-2-4-6-pixhawk-flight-controller-set.html
This is the info when I upload the firmware:
Found board 9,0 bootloader rev 5 on /dev/serial/by-id/usb-3D_Robotics_PX4_BL_FMU_v2.x_0-if00
ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff type: ÿÿÿÿ
idtype: =FF
vid: ffffffff
pid: ffffffff
coa: //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8=

sn: 0032001c3435511130323534
chip: 20016419
family: STM32F42x
revision: 3
flash 2080768

Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.

**Comment by whyscience** [comment]
The final solution is remove R635
或者中文：悍掉R635
