### ISSUE TITLE
Failed to flash board through terminal and QT 

### ISSUE THREAD

**Issue by CastleUAVStudio** [PX4/Firmware#7869]
I tried to flash Pixhawk version:4 ID:9
so I do
`make px4fmu-v2_ekf2 upload`
successfully erase, program, verify, rebooting. However no '[100%] Built target upload' sign, and no welcome sound etc.
<img width="294" alt="2017-08-27 7 11 47" src="https://user-images.githubusercontent.com/25762383/29745830-3a588ff8-8af8-11e7-80a1-5cfd62c61335.png">
I tried on terminal, and tried on QT, same happened.
<img width="440" alt="2017-08-27 7 21 14" src="https://user-images.githubusercontent.com/25762383/29745834-58c4fdd2-8af8-11e7-8b2a-20c228bd2a6f.png">

However I can use QGC to download firmware and flash the board.

Really need a help here.

**Comment by LorenzMeier** [comment]
Please use `make px4fmu-v2_default upload` instead. The EKF2 target is deprecated and will be removed.

**Comment by TSC21** [comment]
What is your autopilot hw? Pixhawk, Pixhawk 2, Pixhawk Mini, PixRacer,...?
