### ISSUE TITLE
GPS Failure parameters not used

### ISSUE THREAD

**Issue by nicolaerosia** [PX4/Firmware#7879]
It seems that these parameters are never used: https://github.com/PX4/Firmware/blob/master/src/modules/navigator/gpsfailure_params.c

Can someone double check? Was this some WIP that got lost?

**Comment by nicolaerosia** [comment]
Nevermind, I did not know this was possible:
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/gpsfailure.cpp#L61-L64
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/navigator_main.cpp#L101

**Comment by dagar** [comment]
Working on restoring it here. https://github.com/PX4/Firmware/pull/7762
