### ISSUE TITLE
modules to consider retiring

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#7895]
There are a few modules in examples (ekf_att_pos_estimator, mc_att_control_multiplatform, mc_pos_control_multiplatform) that are still in every build, changed somewhat regularly as uORB messages and the system evolves, but never actually tested. As a result it's quite likely at least some functionality within them has regressed.

If there's any value in keeping these around I think preserving their last known working state is more valuable than keeping them compiling, but possibly broken.

I propose retiring these modules either by moving them to a new external repository (setup as out-of-tree modules) or deleting them entirely.

The retired modules repository might be a good stepping stone for phasing out things like sdlog2.

**Comment by tops4u** [comment]
Maybe if there is Space SF1xx Driver could be included in the standard build, as this takes little Space?

**Comment by dagar** [comment]
@tops4u sf1xx is pretty small, we could readd it to px4fmu-v2_default.

**Comment by tops4u** [comment]
@dagar is SF1xx going to be included in 1.7?

**Comment by dagar** [comment]
Partially done as part of v1.7.0.
