### ISSUE TITLE
Even though it is normal, dataman worker thread can not be created

### ISSUE THREAD

**Issue by jeonghwan-lee** [PX4/Firmware#7898]
**Bug Report**

The  px4_task_spawn_cmd function passes a value greater than or equal to 0 in the normal case and a value of -1 if an error occurs.
When the dataman start function in dataman.cpp file is running,  call the px4_task_spawn_cmd function.
Therefore, in the source code below, the comparison statement that determines the error should be modified to a value less than zero.

// Now
`if ((task = px4_task_spawn_cmd("dataman", SCHED_DEFAULT, SCHED_PRIORITY_DEFAULT - 10, 1200, task_main, nullptr))  <= 0) {`

// Modified
`if ((task = px4_task_spawn_cmd("dataman", SCHED_DEFAULT, SCHED_PRIORITY_DEFAULT - 10, 1200, task_main, nullptr)) < 0) {`

**Comment by bkueng** [comment]
Thanks for the report. Fixed in https://github.com/PX4/Firmware/pull/7909
