### ISSUE TITLE
Lpe Version: Pixhawk thinks he's flipped and rotated

### ISSUE THREAD

**Issue by FriendlyDwarf** [PX4/Firmware#7921]
Hey,
i ran into this issue while updating the Firmware to the current px4fmu-v2_lpe version.
After the update QGroundControl showed the Copter flipped (roll180) and rotated (yaw270), but there should be no change in the Orientation.

Is this intended?

Steps to reproduce:
-place pixhawk unrotated and set orientation to NONE
-load current px4fmu-v2_lpe.px4
-copter should be shown flipped and rotated in QGC

Specs: 
-i used bash on win10 and the current master to build the firmware, QGC to upload
-my copter still uses the build in sensors
-since i first assumed a mistake on my side, i reset all parameter before i retried, but still the same result

**Comment by LorenzMeier** [comment]
Sorry for the late answer - please use EKF2 as LPE is currently not being actively maintained. We're bringing more and more of the vision and MOCAP interfaces over.
