### ISSUE TITLE
VTOL Standard - Back transition velocity setpoint reset

### ISSUE THREAD

**Issue by bresch** [PX4/Firmware#7925]
During a back-transition, the Multicopter Position Controller continuously resets its velocity setpoint to the actual ground speed, constrained by the maximum allowed velocity in MC mode 
https://github.com/PX4/Firmware/blob/0c38f89b23215713c39987b215025cd6ad753bff/src/modules/mc_pos_control/mc_pos_control_main.cpp#L2244-L2251
However, I saw in a recent log that this value is sometimes reset to zero:
![vtol_mcpc_vel_reset](https://user-images.githubusercontent.com/14822839/30073364-d28ea466-926d-11e7-936a-d2ea86d89796.png)

@sanderux @dagar

**Comment by MikeWellC** [comment]
HI,I also saw it
![sdfsdfsdfsdfsdf](https://user-images.githubusercontent.com/13517580/30149638-fa7e6cf4-93da-11e7-9817-454295574260.png)

**Comment by RomanBapst** [comment]
@Stifael @MaEtUgR Do you have any idea why this happens?

**Comment by sanderux** [comment]
@bresch was this mission mode? it might do that when overshooting the position setpoint
By the way, i think _vehicle_status.is_rotary_wing is true during backtransition so the code you reference would not be running.

**Comment by Stifael** [comment]
@RomanBapst no. But from the plot is does not look like that the septoint for speed is continuously reset.
