### ISSUE TITLE
Possibility of dataman database corruption

### ISSUE THREAD

**Issue by jeonghwan-lee** [PX4/Firmware#7927]
**Bug Report**

If you look at the count variable, which is a parameter of the dataman .read(_file_read, _ram_read, _ram_flash_read) and .write(_file_write, _ram_write, _ram_flash_write)  functions, the parameter count is compared with the variable(g_per_item_size[item]) that stores the maximum length information in each function.

- For example, in the case of the write(_file_write, _ram_write, _ram_flash_write)  functions
    : The parameter count is the length of the actual data to be stored in the dataman database, but is compared with the maximum length including the 4-byte header length. If the count value contains an additional length that is less than or equal to the 4-byte header length in addition to the actual data length to be stored, the database can be broken by an additional length.
    Thus, the comparison of all read and write functions should be modified as follows.

    // Now
   `/* Make sure caller has not given us more data than we can handle */`
   `if(count > g_per_item_size[item]) {`
        `return-E2BIG;`
    `}`
    
    // Modified
   `/* Make sure caller has not given us more data than we can handle */`
   `if((count+DM_SECTOR_HDR_SIZE) > g_per_item_size[item]) {`
        `return-E2BIG;`
    `}`

    The modified comparison above should be applied to all read and write functions in dataman.cpp file.

**Comment by zehortigoza** [comment]
Makes sense, can you send a PR fixing it? Or someone else should do it?
