### ISSUE TITLE
Full Parameter Load fails

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#7961]
**Bug Report**

I was trying Arducopter and saved all Parameters from 1.6.2dev in a file. After Re-Installing PX4 1.6.5dev (Master) I tried to reload all saved Parameters. This is not possible as the modification of certain parameters trigger a restart request. It seams that at this Point the Parameter Loading fails or stops. Redoing loading after a reset did not help in my situation.

Currently I ended up with a partially loaded Parameter List. For example Accelerometer 0 was correctly initialised and Temperature Coefficients are loaded, but Gyro Data was missing as well as the rest of all TC Data (Gyro, Baro, etc). 

I'm not sure if this is a QGC or PX4 Issue. QGC used is a daily build from 18.7.

**Comment by dagar** [comment]
Do you know how far it got? We might ultimately need to handle it on the QGC side, but we should first figure out exactly what's happening.

**Comment by tops4u** [comment]
@dagar I can retry, as I figured still a lot of Parameters missing in my current Config (for ex most of the ThermalCompensation Data, as well as some of the Basic Attitude Tuning Params). Would a Import an Re-Export be helpfull in order to check the differences? 
Should 1.6.2 Load into a 1.6.5dev be possible?

**Comment by tops4u** [comment]
Here is what I did. I used an Pixracer and set it to default Values and upgraded to 1.6.5 Stable. 

After 1 Load and boot. Boot the following Parameters were exported. There was a Gyro Error.
After the 2nd Load and boot the following Parameters were exported and the Gyro Error gone. 
After the third, I did not check, but here are the three Files that have been exported afterwards.
Resulting Parameters
[Archiv.zip](https://github.com/PX4/Firmware/files/1307798/Archiv.zip)

Used Input:
[680Konfig.bak.params.zip](https://github.com/PX4/Firmware/files/1307809/680Konfig.bak.params.zip)

**Comment by tops4u** [comment]
Forgot, here what QGC says:

![qgc-paramfail](https://user-images.githubusercontent.com/6877067/30524035-41be05d4-9bec-11e7-8176-2e1eb42be778.png)

**Comment by dagar** [comment]
That actually makes more sense. On the fresh setup all those params aren't used/marked active until you calibrate. QGC doesn't "see" them and then doesn't load.

I need to look at the relevant QGC code, but I think it could be trying to set them regardless, and only then complaining if it fails.

**Comment by dagar** [comment]
@DonLakeFlyer what do you think about the last comment? Could the QGC parameter manager try a PARAM_SET in this situation?

**Comment by tops4u** [comment]
@dagar I would say that when loading Parameters from a File QGC should always try to write them and also disregard Params with a Reboot Flag until all are loaded.

**Comment by DonLakeFlyer** [comment]
I'd have to look at the failure path. I think it would be ok. The reboot thing is red herring that has no affect other than popping the message. Can you put an issue in for QGC?

**Comment by tops4u** [comment]
This is now logged as QGC Issue : https://github.com/mavlink/qgroundcontrol/issues/5672
