### ISSUE TITLE
PX4IO calling `new` off ISR from DMA

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#7971]
Found this by changing DEBUGASSERT to ASSERT in [sem_wait](https://github.com/PX4-NuttX/nuttx/blob/8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06/sched/semaphore/sem_wait.c#L87)
![i449 cimgpsh_orig](https://user-images.githubusercontent.com/1945821/30500964-4bc7c660-99fc-11e7-8cad-2d10964c4efb.png)

**Comment by LorenzMeier** [comment]
Fixed in https://github.com/PX4/Firmware/pull/8206. Closing this in favour of the PR.
