### ISSUE TITLE
mocap/pose and local_position/pose not same

### ISSUE THREAD

**Issue by b-rohit** [PX4/Firmware#7992]
I have connected rpi to pixhawk on telem2 port and publishing mocap data on `/mocap/pose` topic. The position value for ` z` is not same for `mocap/pose` and `local_position/pose`.
for mocap /pose>>
```
---
header: 
  seq: 1526
  stamp: 
    secs: 1505918137
    nsecs: 129957914
  frame_id: fcu
pose: 
  position: 
    x: 5.30004
    y: 1.2797
    **z: 1.96025**
  orientation: 
    x: 0.901538723658
    y: 0.425992599711
    z: -0.0661677012611
    w: 0.037149294027
---
```
local_position/pose
```
header: 
  seq: 1962
  stamp: 
    secs: 1505918137
    nsecs:  67410240
  frame_id: fcu
pose: 
  position: 
    x: 5.30003929138
    y: 1.27970004082
    **z: -0.049612943083**
  orientation: 
    x: 0.00923220180577
    y: -0.00385768606231
    z: -0.888187765534
    w: -0.459371736031
---

```
2. on roslauch mavros window , I keep getting following messages> 
```
[ INFO] [1505918071.621063490]: FCU: [lpe] mocap position init:  1.28,  5.30, -1.96 m 
[ INFO] [1505918071.671072088]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918071.720345636]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918071.770876366]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918071.822297508]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918071.870953039]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918071.922953865]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918071.971344190]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918072.023350910]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918072.070452714]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918072.120236745]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1505918072.172328734]: FCU: [lpe] reinit P (0, 0) negative

```

**Comment by TobiMiller** [comment]
you need to set your height usage from barometer to mocap/vision ;)

**Comment by b-rohit** [comment]
@TobiMiller Can I achieve that by changing value of the parameter LPE_FUSION ?

**Comment by TobiMiller** [comment]
oh. you use lpe. try EKF2 and use the parameter EKF2_HGT_MODE

**Comment by b-rohit** [comment]
@TobiMiller I am aware that `mocap` is only tested with `LPE` .

**Comment by b-rohit** [comment]
I flew the drone 2 times today with mocap and it is very unstable. find logs here [logs1](https://logs.px4.io/plot_app?log=b4013090-7578-4315-be91-52d86187efd2) [logs2](https://logs.px4.io/plot_app?log=5ed74a8a-e39c-4fe9-9ba6-0ff9c66cdb91).  I keep getting following logs on roslaunch console

```
`[ INFO] [1508319837.645686588]: FCU: [lpe] mocap position init:  0.92,  0.37, -0.88 m 
[ INFO] [1508319837.697792949]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319837.746900766]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319837.796136994]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319837.844418005]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319837.896508119]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319837.946234558]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319837.997116121]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319838.046806681]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319838.100463979]: FCU: [lpe] reinit P (0, 0) negative
[ INFO] [1508319838.144437062]: FCU: [lpe] reinit P (0, 0) negative
`
```

**Comment by TobiMiller** [comment]
go with ekf2 ;) i use it with no problems. the problems i discovered are fixed and was partly my failure

**Comment by evercltech** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ricardo@hotchipsandsalsa.com
    Domain evercl.com has exceeded the max emails per hour (202/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:61253)
	by apollo.graphium.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-ff8b-rr=evercl.com@sgmail.github.com>)
	id 1eoU6f-0007ij-8y
	for rr@evercl.com; Wed, 21 Feb 2018 08:06:45 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=NwJBKiK+EVZ8kTX63K8w12fxt90=; b=xPzoKzR/Nb1FVXFG
	4U3QSrmhjDgWl73oFRyF+CA/2O9LIGZjbXAnAFxRvLrwDgcZ3mZtHu6LmeEEs4nT
	v5zWP6nakMaXNQshKojhUnFF82kIR431kWpthzxCpBummnDlHzusrPvQcBMA8l4w
	3WOez8epOypfVj8iBUYRH4GpM14=
Received: by filter0282p1iad2.sendgrid.net with SMTP id filter0282p1iad2-18902-5A8D6DEA-48
        2018-02-21 13:02:34.864634229 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id e7Sjv2bsSx6fqLXspLFaEg
	for <rr@evercl.com>; Wed, 21 Feb 2018 13:02:34.620 +0000 (UTC)
Date: Wed, 21 Feb 2018 13:02:34 +0000 (UTC)

**Comment by Abelteklu** [comment]
I'm having the same issue. Both in EKF2 and LPE. Has anyone solved this?
