### ISSUE TITLE
master_new_archs_nuttx_upgrade build issues

### ISSUE THREAD

**Issue by davids5** [PX4/Firmware#7999]
@dagar master_new_archs_nuttx_upgrade

- [x] build issues VN
- [x] V not working
- [x] Hardlink edit not working edit file in build is not reflected in src
- [x] check nuttx deps
- [x] edit a defconfig does not rebuild

**Comment by dagar** [comment]
Can you expand on hardlink edit not working?

**Comment by davids5** [comment]
@dagar updated

**Comment by dagar** [comment]
Hardlink copy was accidentally disabled (likely from testing OSX).

Touching defconfig and triggering a rebuild is working for me (with and without hardlink edit). Are you talking about through menuconfig?

**Comment by davids5** [comment]
@dagar - no it was a disable of a I2C I was testing.

**Comment by dagar** [comment]
Verbose mode readded. You can use V=1 or VERBOSE=1.

**Comment by davids5** [comment]
@dagar - still some defconfig issues 

defconfig changes not in build

make clean
make px4fmu-v3_default

vim `# CONFIG_NSH_DISABLE_FREE not used`  => `CONFIG_NSH_DISABLE_FREE=y`

make px4fmu-v3_default

```
cat build/px4fmu-v3_default/NuttX/nuttx/.config | grep FREE
CONFIG_NSH_DISABLE_FREE=y
```
```
nsh> ?
help usage:  help [-v] [<cmd>]

  [           date        free        mount       rmdir       true
  ?           df          help        mv          set         umount
  break       echo        kill        mw          sh          unset
  cat         exec        ls          ps          sleep       usleep
  cd          exit        mkdir       pwd         test
  cp          false       mkfatfs     rm          time
```

**Comment by dagar** [comment]
It's rebuilding for me.

	 % make px4fmu-v3_default   
	ninja: no work to do.

	 % vim nuttx-configs/px4fmu-v3/nsh/defconfig

	 % make px4fmu-v3_default                     
	 [868/868] Creating nuttx_px4fmu-v3_default.px4

	% grep -nr CONFIG_NSH_DISABLE_FREE build/px4fmu-v3_default 
	build/px4fmu-v3_default/NuttX/nuttx/.config:1555:CONFIG_NSH_DISABLE_FREE=y

**Comment by davids5** [comment]
@dagar but when you run that version `free` should be gone and it is not.

**Comment by dagar** [comment]
Oh okay, so it's rebuilding everything, but for each NuttX lib it's simply make in each directory. NuttX itself doesn't recognize that dependency.

**Comment by dagar** [comment]
I believe all of these issues are resolved.
