### ISSUE TITLE
contents of extras.txt not executed upon boot-up of pixhawk mini

### ISSUE THREAD

**Issue by cs147** [PX4/Firmware#8147]
Hello all,
I am using a Pixhawk Mini. On `/fs/microsd/extras.txt`, I put `mavlink stream -d /dev/ttyACM0 -s HIGHRES_IMU -r 200` (as specified [here](https://dev.px4.io/en/advanced/system_startup.html))

When the board boots up, the IMU rate is 50 hz. If I type this into the command line of the system console after the Pixhawk Mini boots up, the IMU rate is increased. So the contents of `extras.txt` are not being executed. Is this a boot-up error? How can I debug this?

**Comment by bkueng** [comment]
Note that the path is `/fs/microsd/etc/extras.txt`, not `/fs/microsd/extras.txt`.

**Comment by cs147** [comment]
@bkueng Sorry I typed it in wrong here. Yes, it is in `/etc` folder

**Comment by SubMishMar** [comment]
Where exactly is the etc folder?

**Comment by cs147** [comment]
@SubMishMar `/fs/microsd/etc/`

**Comment by SubMishMar** [comment]
Thanks! but my sd card is empty!

**Comment by bkueng** [comment]
@cs147 I just tested on a Pixracer, and the command is executed. Are you using Windows to edit the file? If so make sure that you use Unix line-endings.
Alternatively you can create the file directly on the system console:
```
cd /fs/microsd/etc
echo "mavlink stream -d /dev/ttyACM0 -s HIGHRES_IMU -r 200" > extras.txt
```

@SubMishMar you need to create the folder `etc` on the SD card

**Comment by cs147** [comment]
@LorenzMeier This issue is not closed

@bkueng I did exactly what you said by creating the file directly on the system cosnole. It still does not get executed upon startup
