### ISSUE TITLE
MP: Missing Documentation for Position Control Parameters

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8167]
**Feature Request**

https://docs.px4.io/en/advanced_config/pid_tuning_guide_multicopter.html Explains PID Configuration of the Attitude Controller. Documentation for the Position Controller is missing as to how to tune Acceleration Parameters etc. is missing to date. 

As I have the problem, that currently my Multicopter in PosCTL has a strange Hick-Up when decelerating (Stick from roughly 75 - 100 Pitch snapped back to middle 50%). It seems to me like a PosCLT Tuning Problem as in Stabilized its flying well. This Documentation is missing.

**Comment by tops4u** [comment]
Also check #8848

**Comment by hamishwillee** [comment]
@Stifael @dagar Could you recommend the best person to advise on creating PosCTL tuning documentation (or why this is not needed). 
I haven't been tracking documentation labels - will try to do so from now.

**Comment by Stifael** [comment]
It is needed. It will be part of the document that I sent you...
