### ISSUE TITLE
things to check before v1.7.0

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#8171]
- [x] cmake Makefile issues not present with the Ninja generator (check PX4 NuttX builds)
 - [x] windows build (https://github.com/PX4/Firmware/pull/8284)
 - [x] Nuttx stable branch naming (px4_firmware_nuttx-master -> ?)
 - [x] CI builds and metadata s3 deployment in sync with QGroundControl
 - [x] check consistent tagging and version reporting (PX4 command line, QGC, flight review)
 - [x] nuttx builtins dependencies (https://github.com/PX4/Firmware/pull/8043, https://github.com/PX4/Firmware/pull/8172#discussion_r146274240)
 - [x] check pixhawk mini flashing (see if mpu9250 is needed in px4fmu-v2_default) (https://github.com/mavlink/qgroundcontrol/issues/5792)
 - [x] https://github.com/PX4/Firmware/issues/8197#event-1323271550
 - [x] fix firmware build as a submodule (catkin) https://github.com/PX4/Firmware/issues/8255

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/pull/8284

**Comment by LorenzMeier** [comment]
Pixhawk mini flashing is standing - @bkueng could you please take a stab at that with @dagar?

**Comment by dagar** [comment]
I'm not sure if this is new, but it's concerning. Recent snapdragon log from the test team had many instances of most topics.

https://logs.px4.io/plot_app?log=2943d850-0853-40f3-b129-63f6e4c1e29e
https://logs.px4.io/plot_app?log=b6a86822-c2d5-496c-9261-c757e3604992

![pasted image at 2017_11_17 01_28 pm](https://user-images.githubusercontent.com/84712/33100564-de6f42c0-cee2-11e7-9d4b-1e333cee1cea.png)

**Comment by LorenzMeier** [comment]
@MaEtUgR Could you comment on wether Windows builds right now? Is your toolchain ready to be released?

**Comment by MaEtUgR** [comment]
@LorenzMeier I didn't try the "original" old windows toolchain but last time I checked (already pretty long time ago) the build was broken. The new Toolchain is not ready yet, see https://github.com/PX4/Firmware/issues/8357 where I'll also post progress. I would not make the current release dependent on that. Correct me if I'm wrong but in my eyes Windows support is not just recently a problem otherwise I would have used it before.
