### ISSUE TITLE
HIL: can't arm with latest versions

### ISSUE THREAD

**Issue by gamoreno** [PX4/Firmware#8176]
With the firmware up to version 1.6.3, I could follow the following procedure to do HIL:
-plug in Pixhawk v2 to USB and wait until LED breathing blue
-start jMAVSim and wait unilt LED breathing green
-on an nsh terminal, issue the command: commander arm
and the drone would arm.

I cannot test latest standard releases due to issue #7857, but if I try with the latest master (with a workaround for that issue), I cannot arm anymore. I get the error:
WARN  [commander] HITL: Connect to simulator before arming.
WARN  [commander] arming failed

I noticed that 61b0a81bf9823aa56fa4f5cc3d0fc0da5d00b559 changed the condition in the if statement that shows this error. If I change the following line in commander.cpp
```
status.hil_state == vehicle_status_s::HIL_STATE_ON)
```
to
```
status.hil_state != vehicle_status_s::HIL_STATE_ON)
```
it works as before. Is it possible that this condition is wrong now? or has the procedure to start a HIL simulation changed?

**Comment by bkueng** [comment]
This is indeed wrong now. But since the commit removed the `startup_in_hil` flag, this whole check does not make sense anymore. I think we can just remove it.
I'm surprised that the preflight checks don't fail. They should fail if there is no gyro available.
