### ISSUE TITLE
Consider SF1xx Driver for 1.7 Release

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8177]
**Feature Request**

Take SF1xx Driver back in the Build for 1.7. The Driver is very small and those LIDAR are currently interesting especially the SF20/LW20 as it is small and light. 

@dagar do you take care?

**Comment by dagar** [comment]
I'll need to remove something else to make it fit. I'm fairly certain we can drop the mpu9250 and not impact anyone.

**Comment by tops4u** [comment]
@dagar could you add 1.7 Release label to this in order to get it in the DevCall?

**Comment by dagar** [comment]
PR https://github.com/PX4/Firmware/pull/8185

**Comment by tops4u** [comment]
Checked in current Master and works. Thanks.
