### ISSUE TITLE
VTOL crash on V4Pro

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#8186]
vtol crash 24/October

crash log:
https://review.px4.io/plot_app?log=da864870-aa30-4133-be64-c766e2e0e9e7

previous successful flights on same platform:
https://review.px4.io/plot_app?log=1fa2997a-b9d8-4039-af2e-dad379be803c
https://review.px4.io/plot_app?log=deacbcaa-61ed-41c2-80d2-9b636b66a983

Flight conditions:
aprox 27°C degrees
moderate winds, 4~5 m/s

Sequence of events:
auto take-off in MC
failed auto-transition to FW
retook manual control in stabilized and successfully engaged manual transition to FW
engaged mission; vtol headed in correct direction to first waypoint

after a few waypoints, vtol started to veer off coarse and switched back to MC
switched MC to stabilized at which point it was hard to control and started to dip in pitch and roll violently while losing altitude

@dagar

**Comment by dagar** [comment]
Multiple primary IMU timeouts.
![image](https://user-images.githubusercontent.com/84712/32017478-d914e982-b994-11e7-8a82-8ddac1de2a3d.png)


![image](https://user-images.githubusercontent.com/84712/32017506-f26ca550-b994-11e7-84ae-ab8f10794968.png)

Primary IMU (mpu6000 driver) reporting bad transfers.

![image](https://user-images.githubusercontent.com/84712/32017568-2119452a-b995-11e7-971d-0fe39ce3980d.png)

**Comment by dagar** [comment]
The selected sensor changed as a result of the timeout, but then reverted, timed out again, etc.

![image](https://user-images.githubusercontent.com/84712/32017762-bed4a46c-b995-11e7-83ea-1b1ac1fbcb8d.png)

To start with we need to take a look at the sensor voting and switching logic.
@priseborough @LorenzMeier

**Comment by priseborough** [comment]
I'm not familiar with that part of the code, but the requirement for handling timeouts and other hard faults with duplex inputs should be to switch if the current active sensor instance faults to the next instance that is not faulted. The switch should be sticky so that the new active instance is kept until it faults, in which case the selector goes to the next instance that is passing.

**Comment by priseborough** [comment]
The estimator will need to be made aware of the switch so that it can reset the IMU bias states and associated covariances.

**Comment by priseborough** [comment]
I will submit a PR adding the method to the ecl enabling the bias states and variances to be reset. If the sensor combined message can provide a uint8  indicating the source sensor index, then I can use that in ekf2_main.cpp to call the reset function.

**Comment by priseborough** [comment]
Here's the supporting changes for ecl https://github.com/PX4/ecl/pull/348

When changes to the sensor module have been made, I'll put together the required ekf2_main changes.

**Comment by bkueng** [comment]
@priseborough you can use the existing `sensor_selection` topic. And the failover logic is already in ecl: https://github.com/PX4/ecl/blob/master/validation/data_validator_group.cpp#L148

**Comment by mrpollo** [comment]
any update on this one? are we good to close this?

**Comment by priseborough** [comment]
It's resolved
