### ISSUE TITLE
Travis is not returning current master commit

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8197]
Travis is returning commit 69231ea but there are 2 new commits [merged to master](https://github.com/PX4/Firmware/commits/master).

To reproduce you can load master from QGC or you can see what Travis is returning here:
http://px4-travis.s3.amazonaws.com/Firmware/master/px4fmu-v4_default.px4

@dagar

**Comment by r0gelion** [comment]
Now is returning the latest commit (4416c4d)

I don't know what changed but it's working now.

**Comment by r0gelion** [comment]
Now is returning commit 29af234 but current master is 459a71a

**Comment by dagar** [comment]
Thanks, could you share exactly where you're seeing these?

**Comment by r0gelion** [comment]
Here:
http://px4-travis.s3.amazonaws.com/Firmware/master/px4fmu-v4pro_default.px4
http://px4-travis.s3.amazonaws.com/Firmware/master/px4fmu-v4_default.px4
http://px4-travis.s3.amazonaws.com/Firmware/master/px4fmu-v3_default.px4
http://px4-travis.s3.amazonaws.com/Firmware/master/px4fmu-v2_default.px4

**Comment by dagar** [comment]
I believe it's actually a build system issue. If the build fails on master (something people don't directly watch) it might not update.

![image](https://user-images.githubusercontent.com/84712/32336903-ef071340-bfc6-11e7-88e8-3a29a215f15b.png)

For now I'll keep an eye on it and make sure these master builds are properly getting deployed. Soon I'd like to migrate to our own CI system (http://ci.px4.io/blue/organizations/jenkins/) to fix a lot of these problems that are out of our control.

This is current master I've forced to rebuild. https://semaphoreci.com/px4/firmware/branches/master/builds/1878

**Comment by dagar** [comment]
Caused by intermittent semaphoreci failure.

CI improvements (especially stability!) will be a focus after v1.7.0.
