### ISSUE TITLE
Battery remaining inversed when compensating for load

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#8198]
The battery remaining function is broken on today's master.
It increases drastically when under load (if anything it should decrease). Tested with and without setting internal resistance, both behave the same. The voltage reading does read as expected.

![image](https://user-images.githubusercontent.com/14801663/32076325-dbcfdca2-ba9f-11e7-9cff-0fab8f5b43d2.png)

Log from other flight same behavior:
https://logs.px4.io/plot_app?log=7f323da0-8f75-46f1-aba9-f0a68150b691

ping @LorenzMeier @dagar

**Comment by sanderux** [comment]
ping @davids5

**Comment by dagar** [comment]
For VTOL this would make sense if you're relying on the normalized throttle usage (https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/battery.cpp#L179), but I see you have BAT_R_INTERNAL set.

**Comment by LorenzMeier** [comment]
@sanderux This is still persisting, right?

**Comment by sanderux** [comment]
yes

**Comment by sanderux** [comment]
@dagar it happens with with and without r_internal

**Comment by MaEtUgR** [comment]
@sanderux I'm currently revising the battery estimation. It's broken in several ways according to my opinion. Not sure if your case is covered in my fixes, let's investigeate.

On the first glance it looks to me as if your battery estimation is always corrected using the thrust and for the factor of how much this is done you can use the parameter `BAT_V_LOAD_DROP`. You even say it does not change when setting an internal resistance.

What you should also know is that the current estimation always adjusts the empty voltage compared to the measurement itself which results in rescaling the whole calculation... If you feel like and have time you can test my pr as soon as I fixed the CI stuff and pushed the newest enhancements today.

**Comment by sanderux** [comment]
I re-checked all the math and found that it was indeed related to internal resistance that was likely wrong for this lipo. Initially i thought it was not related as it exhibited the same behavior when bat_IR was disabled. but on the bench test it did not (perhaps param didnt save in field test).

Closing for now.

**Comment by nskjoung** [comment]
@sanderux i'm be in a same situation. how does it clear?

**Comment by MaEtUgR** [comment]
@nskjoung I think his conclusion was that the internal resistance parameter was not set correctly and hence the measurement got overcompensated. If you want to try supposedly better battery estimation please try #8153 . It will likely just not be in 1.7 because it requires a lot of testing.
