### ISSUE TITLE
SITL takes 10 seconds to get position lock

### ISSUE THREAD

**Issue by imcnanie** [PX4/Firmware#8221]
**Bug Report**

This makes development very annoying. Is there a hard-coded delay somewhere causing this to happen? How can we speed it up?

**Comment by TSC21** [comment]
What's your system setup and hw specifications? It may only mean you have low spec system.

**Comment by imcnanie** [comment]
Intel® Core™ i7-2630QM CPU @ 2.00GHz × 8 Nvidia graphics. But it's a laptop. What's intense about position lock? I can still arm and fly around in stabilize.

**Comment by ndepal** [comment]
EKF2 takes noticeably longer to initialize than LPE. If you don't care about the estimator, you can switch to LPE.

**Comment by dagar** [comment]
Still an issue?
