### ISSUE TITLE
1.7 Release notes

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#8225]
Let's start adding the release notes for 1.7 here

**Comment by tops4u** [comment]
Added Support for Lightware SF20/LW20 I2C connected Lidars.

**Comment by Ahrovan** [comment]
Please provide changes and development details for version 1.7

**Comment by AlexisTM** [comment]
Solved bugs for the ECL library (EKF2) which impacted the PX4Flow #8102

**Comment by dagar** [comment]
@jlecoeur do you want to add something high level about the mixer updates? Migration for users that had custom mixers, etc.

**Comment by jlecoeur** [comment]
Auto-generate multirotor mixers from files that describe their geometry. See here <link to dev guide page to be done https://github.com/PX4/Devguide/issues/349 > how to migrate or add custom mixers.

**Comment by scott-eddy** [comment]
FMU can now be run as a task #7640

**Comment by mrpollo** [comment]
Preliminary changelog https://gist.github.com/mrpollo/0b4e8985e829de1961a47909376a2b85

**Comment by mrpollo** [comment]
https://github.com/PX4/Firmware/releases/tag/v1.7.0
