### ISSUE TITLE
F450 with Pixracer didn't follow the mission, started climbing.

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8246]
Took off manually, good hover in position mode launched the mission and the unit started getting altitude but did not follow the mission.

https://logs.px4.io/plot_app?log=907d2032-92a3-43c8-9a71-1c18b0792194

**Comment by korigod** [comment]
Setpoint triplets were empty, it looks like there was no mission onboard. Did you noticed `[commander] REJECT AUTO MISSION` warning? Vehicle never launched the mission, it switched to AUTO.LOITER instead.

**Comment by SayanR1** [comment]
The vehicle did have a Mission on board, after landing the unit I double checked in QGC and ti was there.

**Comment by dagar** [comment]
I'm thinking this might be more of a usability issue? There are many cases where it's not clear if the mission shown in QGC is synced and accepted by the vehicle.

**Comment by r0gelion** [comment]
I'm closing this issue, if this happens again, I will re-open it.
