### ISSUE TITLE
Protocol splitter is not sending any messages on UART

### ISSUE THREAD

**Issue by avinash-palleti** [PX4/Firmware#8262]
Few changes are required to compile and enable protocol_splitter which are done in below branch,
https://github.com/avinash-palleti/Firmware/tree/rtps

With above changes it is expected that protocol_splitter has to send both mavlink and RTPS on UART. But it is not sending any messages, deamon running on host is receiving 0 bytes.

Not able to collect logs as mavlink-router is also not functional.

**Comment by bkueng** [comment]
This got fixed in https://github.com/PX4/Firmware/pull/8328
