### ISSUE TITLE
MC: Possible to Arm without GPS Lock

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8269]
**Bug Report**

It is possible to Arm the Vehicle within about 20secs from Booting without having a valid GPS lock. This is most probably due to a check in the PrearmChecks that does not enforce GPS Check for EKF (when COM_ARM_WO_GPS is disabled) within 20secs after booting. 

It is possible to arm an takeoff during this timewindow without GPS Lock even when having Valid EKF Thresholds for GPS Signal and COM_AMR_WO_GPS set to false.

**Comment by acfloria** [comment]
If GPS is required for arming is specified by the [COM_ARM_WO_GPS](https://docs.px4.io/en/advanced_config/parameter_reference.html) parameter.

**Comment by tops4u** [comment]
Yes, I agree. But check the last segment of PreflightCheck.cpp

Line 778 defines that if there is no Lock, _time_last_no_gps_lock = time since boot when there is no lock yet. 

And 788 enforces GPS check within EKF Limits only when _time_last_no_gps_lock is > 20 secs. 

So in case there was no Lock and less than 20 secs after boot Arming is attempted there will be no Check if there is a GPS Lock. 

COM_ARM_WO_GPS did not change this behaviour in my test.

**Comment by tops4u** [comment]
I did some tests with COM_ARM_WO_GPS set to FALSE

Here the Screenshot where I was able to ARM within the 20secs Window after Boot I was covering the GPS with a ESD Bag and my Hand (it lost the Lock), then rebooted the FMU and armed:
![armingwithin20secswo_gps](https://user-images.githubusercontent.com/6877067/32970585-eb2348e6-cbe9-11e7-93d8-b15ff8599617.png)

Messages in QGC:
![armingwithin20secswo_gps2](https://user-images.githubusercontent.com/6877067/32970590-f33bab04-cbe9-11e7-8c39-46bc16bd5f56.png)

After the 20sec Window is expired the PreflightCheck complains correctly, that there is no GPS available. BUT: It is not possible to recover from this, even when there is GPS available still there is the same Prearm Failure preventing to Arm. Only Reseting the FMU will allow arming. 
![persistentpreflightcheckfails](https://user-images.githubusercontent.com/6877067/32970634-1e8fafe4-cbea-11e7-9ed5-b341b17f5475.png)

**Comment by dagar** [comment]
Improvements here. https://github.com/PX4/Firmware/pull/8374

**Comment by priseborough** [comment]
Having a GPS lock does not mean the vehicle will arm. The EKF has to have passed it's internal GPS quality checks and started using GPS. 

I will rework the 20 second startup check logic.

**Comment by priseborough** [comment]
I've reworked the checks and pushed the fix to https://github.com/PX4/Firmware/pull/8374

**Comment by tops4u** [comment]
Checked and looks ok for me. Thanks
