### ISSUE TITLE
krait update param failed

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#8280]
I tried running PX4 on a Snapdragon Flight (`make eagle_legacy_default`). It builds using https://github.com/PX4/Firmware/pull/8279.

When I run `./px4 mainapp.config`, I get
http://pasted.co/4034af78
mini-dm
http://pasted.co/05edbbf5

**Comment by ChristophTobler** [comment]
similar to https://github.com/PX4/Firmware/issues/7364. There the aDSP crashed, right?

**Comment by dagar** [comment]
@darioxz I think we need to get one of these added to the CI system. It's way too easy to silently break.

**Comment by ChristophTobler** [comment]
There is no error when using `eagle_default`.

FYI @mcharleb

**Comment by ChristophTobler** [comment]
v1.6.5 is still working

**Comment by LorenzMeier** [comment]
@ChristophTobler This is likely the result of parameters being present on the Linux side that are not present on DSP or vice-versa. @dagar this is one of the reasons why I'm not a big fan of "cleanups" as long as we've not solidified the underlying architecture to take care of "enabled parameters" in a fundamental fashion.

**Comment by LorenzMeier** [comment]
@ChristophTobler Please try a commit from 3 weeks ago and work your way in.

**Comment by dagar** [comment]
> @dagar this is one of the reasons why I'm not a big fan of "cleanups" as long as we've not solidified the underlying architecture to take care of "enabled parameters" in a fundamental fashion.

I don't think this is related to enabled parameters (and that big PR was never merged), but I see your point.

I'm wondering if it's something with the parameter culling combined with out of source modules (FC_ADDON)? @ChristophTobler can you diff the parameters.xml in each build (posix + qurt)?

**Comment by ChristophTobler** [comment]
fixed in https://github.com/PX4/Firmware/pull/8325
