### ISSUE TITLE
param save performance

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#8294]
Investigate bson encoder write performance, and likely start buffering writes.

 - perf counters (https://github.com/PX4/Firmware/pull/8391)
    - save, find, get, commit, failures
 - throttle param changed publications (1Hz?)
 - look for param abusers
   - some modules are updating params multiple times
   - review all param_commit usage (remove notifications wherever possible)
   - modules don't need to poll parameters_update
 - bson_encoder file -> buffer, then write buffer (even a small buffer drastically decreases param export time)

**Comment by zarathustr** [comment]
Nice work!

**Comment by dagar** [comment]
Fixed.
