### ISSUE TITLE
LPE with External Vision Position crash into ceiling while in Altitude Control

### ISSUE THREAD

**Issue by Ekci** [PX4/Firmware#8295]
Logs here: [link](https://logs.px4.io/plot_app?log=d0e992b7-5855-45eb-87a4-2bd08147d201)

I am currently working on indoor navigating using External Vision Position (mavros). Normal flight looks like this: I arm, take off, hover at around 1 meter at which points my camera starts to report position, change to alt hold and then to offboard which engages navigation to point (0,0) at 1.8 meters.

We had few flights without any problem (we are still tuning) but last flight ended with crashing into ceiling after switching to alt hold. Question is: what LPE altitude control is using as alt reading? Why we were able to fly in alt hold without any problem (even when we were loosing external position)?

I realized that my local position estimator was not "following" external one but why it was ignoring my baro and range sensor?

**Comment by TobiMiller** [comment]
Use EKF2. i know in docs it is recommend to use LPE but i think it is outdated. change the parameter for altitude fusion from baro to vision. if it dosnt help. try to send a setpoint and set the flightmode to offboard. i experienced a similar problem with pos. hold and thought that this flightmodes only works with gps

**Comment by TSC21** [comment]
@TobiMiller why do you say it is outdated? What it really needs is proper tuning

**Comment by TobiMiller** [comment]
@TSC21 it is recommend to use LPE. out of the box EKF2 worked better for me. thats why i thought this recommendation is maybe from times before ekf2 ;)

**Comment by TSC21** [comment]
Befor ekf2 had vision support

**Comment by Ekci** [comment]
I'm confused, what's better to use now? LPE or EKF2?
Anyway, I was able to stabilize indoors for around 30 minuts using LPE. My problem is last crash when changing to alt hold...

**Comment by TSC21** [comment]
Set `LPE_FUSION` bitmask so it can also fuse baro. Then set `LPE_BAR_Z` to an high value.

**Comment by TSC21** [comment]
The problem was the Z estimation.

**Comment by Ekci** [comment]
Yeah, that's wat I was thinking. What about Lidar? Is there a way to fuse it?

**Comment by TSC21** [comment]
It should automatically fuse. You don't need to set a parameter.

**Comment by Ekci** [comment]
Ok, so why the Z estimate was that off if Lidar was on and even External Vision Position turned on before switching to alt hold? You can clearly see that Vision Position Z was around 1.5 meters when we change modes. I agree that we should have given it more time to fuse but I was sure that Z will be correct because of the Lidar.

**Comment by TSC21** [comment]
Try setting `pub agl as lpos down` on `LPE_FUSION`.

**Comment by TSC21** [comment]
Also try to decrease `LPE_VIS_Z` (Vision z standard deviation)

**Comment by Ekci** [comment]
Ok, I will try it next time. Thank you for helping here, I will close this issue for now.
