### ISSUE TITLE
F450 frame with Pixhawk mini crash - v1.7.0-rc1

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8299]
Using F450 frame with Pixhawk mini autopilot, loaded v1.7.0-rc1

The vehicle was flying in mission mode and when going to the second waypoint it stopped to follow the mission, it didn't respond to RTL command (by RC) and it crashed.

https://logs.px4.io/plot_app?log=57cd3193-b22d-478a-8c10-c0ff0f9a5178

@dagar @LorenzMeier

**Comment by dagar** [comment]
What was the crash like? Did the battery get so low the ESCs finally shut off? Do these numbers look believable?

![image](https://user-images.githubusercontent.com/84712/32869541-860b0142-ca45-11e7-930b-c9155628ee82.png)

**Comment by r0gelion** [comment]
The ESC's didn't cut, the vehicle flew to a side and crashed. The battery got hit and a cell is dead but cannot assure if it died before or after the crash.

**Comment by dagar** [comment]
Oh, I see the flight was upfront.

![image](https://user-images.githubusercontent.com/84712/32921059-03a3b8ba-cafa-11e7-8e7b-286a6e3c1cb0.png)

The red line is the mode. It starts in position control, the mission, and is already in RTL before you lost RC.

**Comment by dagar** [comment]
I still think it's a battery issue where it was so low it couldn't maintain altitude during the RTL and crashed. Until it's unable to maintain it was on a straight path back to home.

The RTL was triggered by low battery.
![image](https://user-images.githubusercontent.com/84712/32921236-cfecabac-cafa-11e7-9676-afa1c0dfb881.png)

![image](https://user-images.githubusercontent.com/84712/32921259-e9edc2de-cafa-11e7-887d-7f1a48017f03.png)

Shortly after 2:40 you start losing altitude during the RTL and the impact happens at about 2:50. The battery flat lines, even though the commanded thrust goes to maximum.

![image](https://user-images.githubusercontent.com/84712/32921343-4b95f952-cafb-11e7-9e22-4c8ba16923ef.png)

**Comment by dagar** [comment]
You should change the low battery action (COM_LOW_BAT_ACT) to 3 "Return to land at critically low level, land at current position if reaching dangerously low levels". 

At the critical threshold (default 7%) the vehicle will do an emergency land instead of the RTL.

**Comment by r0gelion** [comment]
We will follow your recommendation.

I'm closing this issue.

Thanks!
