### ISSUE TITLE
Adding PX4 precompiled 1.6.5 Firmwares 

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Firmware#8326]
**Feature Request**

As the Firmware 1.7.0 is in release candidate phase; it might be good to publish all the precompiled Firmware 1.6.5 release in the release as it is one of the widely used.

**Comment by dagar** [comment]
We still have them in the CI system. I'll look at posting them to the github releases.

**Comment by dagar** [comment]
How's that? https://github.com/PX4/Firmware/releases/tag/v1.6.5

**Comment by AlexisTM** [comment]
Wonderful, thanks :)

**Comment by dagar** [comment]
The CI system is currently in flux, but once it settles we can automate this.
