### ISSUE TITLE
SITL compilation bug

### ISSUE THREAD

**Issue by hiro64** [PX4/Firmware#8330]
I just cloned the newest version and I am trying to compile the SITL simulation with Gazebo by running `make posix_sitl_default gazebo`. However, I am receiving some errors related to the mavlink libraries. It seems the mavlink_msg_hil_actuator_controls.h file from the mavlink folder is not being included. One of the errors when running make is below:

> Firmware/Tools/sitl_gazebo/src/gazebo_mavlink_interface.cpp:903:8: error:
> MAVLINK_MSG_ID_HIL_ACTUATOR_CONTROLS’ was not declared in this scope
> case MAVLINK_MSG_ID_HIL_ACTUATOR_CONTROLS:

I tried it with last week's master and got the same error, but I compiled it with no problems back in September, so I assume something must have happened in the meantime.

**Comment by TSC21** [comment]
Did you update all the submodules accordingly?

**Comment by hiro64** [comment]
Yes, I ran `git submodule update --init --recursive` and they were updated with no problems.

**Comment by TokyoClod** [comment]
i find the latest version Firmware missing the iris.sdf in [https://github.com/PX4/sitl_gazebo/tree/b052c97f7c3a2c39ab8ec06ae79c66431f16c659/models/iris](url)

**Comment by TSC21** [comment]
@hiro64 it looks like you are don't have the Mavlink submodule updated. Try `make distclean`, then `git submodule sync --recursive` and then `git submodule update --init --recursive`.

**Comment by hiro64** [comment]
@TSC21 I cloned it again into a new folder and ran these commands but it ended up going through the same problem... could it be something in my machine?
