### ISSUE TITLE
merge FMUv2 and FMUv3 board support

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#8342]
FMUv3 started as FMUv2 + full 2mb flash + PX4 additional modules, then added support for detecting pixhawk variants (cube 2.1, pixhawk mini, etc). Due to the pixhawk mini shipping with an old bootloader it must be made function with the regular FMUv2 binary (which now needs runtime version detection).

TODO
 - FMUv3 must go back to being FMUv2 with full 2mb flash and additional PX4 drivers (no board support changes)
 - merge src/drivers/boards/px4fmu-v2 and src/drivers/boards/px4fmu-v3
 - squeeze all pixhawk mini dependencies (mpu9250)

**Comment by LorenzMeier** [comment]
Done! Thanks @dagar
