### ISSUE TITLE
The use of hard link copy operation for Nuttx blocks building on guest OS within host volume

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#8362]
The Nuttx build uses hard links for Linux builds: https://github.com/PX4/Firmware/blob/master/platforms/nuttx/NuttX/CMakeLists.txt#L30

This doesn't work for guest OS build environments (Ubuntu in VMWare) when accessing the source on a host volume. Looking for ideas on how to make an exception for these build environments (they are fairly special so I don't think it's a common problem).

**Comment by dagar** [comment]
Yes, this is a feature that helps when debugging NuttX in an IDE and modifying the source (that's actually the copy), then losing your change when rebuilding.

How does it fail on your setup?
