### ISSUE TITLE
Potential critical NuttX alignment issue

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#8367]
The full report is here and I'm including it to ensure that we're not forgetting about it:
https://bitbucket.org/nuttx/nuttx/issues/78/possible-bss-override-by-stack-coloration

@davids5 @dagar I would appreciate your review.

Thanks!

**Comment by matanhavi** [comment]
Note that for what I seen so far, for px4fmu there should be no issue, because the last var on the bss is _io_timer_channel_stats_, which is 4 byte aligned.
I have seen the issue because I didn't set BOARD_HAS_CAPTURE, '_once_' var has become the last one, and its uint8_t

**Comment by BazookaJoe1900** [comment]
Note that for what I seen so far, for px4fmu there should be no issue, because the last var on the bss is io_timer_channel_stats, which is 4 byte aligned.
I have seen the issue because I didn't set BOARD_HAS_CAPTURE, 'once' var has become the last one, and its uint8_t

**Comment by dagar** [comment]
Add ALIGN to the linker scripts? https://github.com/PX4/Firmware/blob/master/nuttx-configs/px4fmu-v2/scripts/ld.script#L143

**Comment by BazookaJoe1900** [comment]
Yes, I think that adding
. = ALIGN(4);
Should to the work.
Can you confirm?

**Comment by davids5** [comment]
I will check and confirm it in the AM tomorrow.

**Comment by LorenzMeier** [comment]
@davids5 Did you have a chance to have a look?

**Comment by davids5** [comment]
@LorenzMeier yes. Current build is not affected, but I will do a PR to avoid any future issues.

**Comment by LorenzMeier** [comment]
Moving to v1.8.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/8382.

**Comment by matanhavi** [comment]
@davids5 Thanks!

**Comment by BazookaJoe1900** [comment]
@davids5 Thanks!
