### ISSUE TITLE
FW crash v1.7.0-rc2

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8380]
Phantom flying wing with Pixhawk mini autopilot running v1.7.0-rc2 (V3).

After 6 successful flights, during the 7th flight, the pilot took off in manual mode, switched to Auto and the plane accelerated to maximum thrust uncontrollably; once switched back into manual the pilot reported only partial control, attempted to land manually but crashed due to the vast acceleration and only partial control over the craft.

[Log](https://review.px4.io/plot_app?log=6fb19372-e027-4b23-b0e8-5425d409f5f3)

[Video](https://youtu.be/3qIzzh4hfUs)

@dagar

**Comment by dagar** [comment]
I saw this log a couple days ago. The major thing that stands out is that the pitch demand is being ignored. There's also a sizable roll offset.

![image](https://user-images.githubusercontent.com/84712/33303553-c5b6e4b0-d3d1-11e7-982a-2a0d717c048d.png)
 
The other minor thing is that the maximum roll max is set to 0 (unconstrained). Resetting to the default should be fine.

![image](https://user-images.githubusercontent.com/84712/33303605-1852d774-d3d2-11e7-885b-b7e369906b0c.png)

How badly damaged was the vehicle? I suspect some kind of mechanical failure. Servos, linkages, control surfaces, or possibly even the battery coming loose and moving around.

**Comment by bresch** [comment]
@r0gelion Link of the log is broken. Could you update it please?

**Comment by bkueng** [comment]
@bresch Works again. Sorry I messed up an upgrade.

**Comment by bresch** [comment]
@bkueng Thanks!

**Comment by acfloria** [comment]
@r0gelion It is probably not related to the crash but which airspeed sensor are you using?
I am asking because this value is quite high: `SENS_DPRES_OFF, 122.68370819091797`

**Comment by r0gelion** [comment]
@acfloria this is the airspeed used.

![img_20171204_102102](https://user-images.githubusercontent.com/5013954/33569786-a81cd186-d8df-11e7-8f7b-d2ae0ec5e2a5.jpg)


Thanks!

**Comment by dagar** [comment]
@acfloria in my experience that's a pretty typical offset for an MS4525.

**Comment by dagar** [comment]
Most likely mechanical failure.
