### ISSUE TITLE
Issue with "make posix jmavsim"

### ISSUE THREAD

**Issue by vinhk** [PX4/Firmware#8388]
Hi,

I get this error when I run it on my terminal:
```

/bin/sh: 1: cmake: not found
/bin/sh: 1: cd: can't cd to /home/vinh/src/Firmware/build/posix_sitl_default
make: *** [posix_sitl_default] Error 2
```
This is the [tutorial](https://dev.px4.io/en/setup/building_px4.html)

**Comment by dagar** [comment]
You need to install cmake. The instructions on the dev guide will walk you through installing all the dependencies.  https://dev.px4.io/en/setup/dev_env.html
