### ISSUE TITLE
RTL issues with multiCopter

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#8389]
If engaging RTL multiple times in the same flight, the second+ instance of RTL goes towards a previously set path by the first RTL engagement.
Couple examples:
https://review.px4.io/plot_app?log=ed176590-4352-4516-b5ed-3892436d6477
https://review.px4.io/plot_app?log=d9c63fd1-1224-4be7-8985-932a2f670c78

@dagar

**Comment by LorenzMeier** [comment]
I think we need to fix this pre-release

**Comment by sanderux** [comment]
I cant reproduce this in SITL, also i don't see this behavior in the logs posted but they are a bit hard to read.

**Comment by LorenzMeier** [comment]
@Stifael Could you have a look?

**Comment by Stifael** [comment]
I am also not able to reproduce it. so far I looked at the first log, and it seems that navigator sends out the correct setpoints.

**Comment by LorenzMeier** [comment]
@santiago3dr Could you please try to reproduce this?

**Comment by santiago3dr** [comment]
reproduced with pixracer (V4) running current master b21af47
https://logs.px4.io/plot_app?log=0a53df91-c2fe-4040-b0c1-451cacef2d09

of the 3 instances rtl was engaged, 1 and 2 took direct path home while the third attempt headed towards a path previously set by a prior instance of rtl
![rtl](https://user-images.githubusercontent.com/13203106/33575784-a060441a-d8f2-11e7-9389-66fea6977822.JPG)

**Comment by Stifael** [comment]
@santiago3dr thanks. it is a much simpler log and I think I just found a pattern

**Comment by Stifael** [comment]
I can reproduce it now

**Comment by Stifael** [comment]
here is a PR which solves the issue. 
https://github.com/PX4/Firmware/pull/8412

**Comment by dagar** [comment]
Fixed! Thanks Dennis.
