### ISSUE TITLE
ECL__Lib EKF stopping navigation -> Meaning?

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8401]
**Bug Report**

In various Logs I have seen this message, but I don't actually know what it means and what its implications are. Could you clarify the meaning and probably change the Message to something more understandable?

![ecl](https://user-images.githubusercontent.com/6877067/33516522-69606e6a-d774-11e7-874b-7893092ffcef.jpg)

**Comment by dagar** [comment]
At the beginning of the log it's harmless (and needs to be fixed).
ECL issue created here. https://github.com/PX4/ecl/issues/363

**Comment by dagar** [comment]
@priseborough FYI

**Comment by tops4u** [comment]
@dagar sorry for the duplicate, I was looking for the message in the Code and was not aware that lib ecl was a subproject of PX4. Shall I close this?

**Comment by dagar** [comment]
Not a problem. We can leave it open for tracking because even after ECL is updated the reference in Firmware needs to be updated as well.

**Comment by priseborough** [comment]
Will be fixed when https://github.com/PX4/Firmware/pull/8405 is merged.

**Comment by LorenzMeier** [comment]
Removed that. Thanks!
