### ISSUE TITLE
MC: LowBat RTL Performed at 5m Alt instead of 50m!

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8408]
**Bug Report** 

I was doing some testing, when I ran into a LowBattery RTL. But instead of climbing to the Preset Alt of 50m in such a case, the Copter just turned face to me an returned at roughly 5m Altitude! 

Log here: https://logs.px4.io/plot_app?log=d55046af-324a-4e6e-91ee-205b1f34bfc3

Landing was smooth an luckily the Street lantern was about 5m away. 

Just to note I'm still running on 1.7 RC1 (about 20 days old) - a quick search through the Commit list revealed nothing that would deal with such a problem. 

Addition: Just seen RTL_MIN_DIST is set to 5m but according LocalPos X/Y both have been > 10m.

**Comment by dagar** [comment]
That's for reporting in detail. This was a bug in master (briefly) and it looks like the fix was only a few commits after the one you flew.
https://github.com/PX4/Firmware/commit/98cbd445261238f5dfc0c036e0058b2a4508b7bc

**Comment by tops4u** [comment]
@Dagar :Thanks. Time for an Update I think.
