### ISSUE TITLE
Release v1.7 sign-off

### ISSUE THREAD

**Issue by mrpollo** [PX4/Firmware#8419]
Is your team ready for a release?

* [x] Project / Founder - @LorenzMeier
* [x] Communication Architecture - @bkueng , @julianoes 
* [ ] UI / UX - @dogmaphobic, @DonLakeFlyer  
* [ ] Multicopter Flight Control - @Stifael, @MaEtUgR
* [x] VTOL Flight Control - @tumbili, @AndreasAntener, @sanderux @bresch
    * [x] VTOL standard
    * [x] VTOL tailsitter
    * [x] VTOL tiltrotor
* [x] Fixed Wing Flight Control - @dagar, @priseborough 
* [ ] Racers - @anton-matosov 
* [x] OS / drivers - @davids5 
* [x] UAVCAN / Industrial - @pavel-kirienko 
* [x] State Estimation - @jgoppert, @priseborough 
* [x] VIO - @mhkabir, @ChristophTobler 
* [ ] ~Obstacle Avoidance - @vilhjalmur89~ - not implemented in mainline codebase yet.
* [ ] Snapdragon - @mcharleb 
* [ ] Intel Aero - @lucasdemarchi, @simonegu 
* [x] Raspberry Pi / Navio - @bkueng 
* [ ] Parrot Bebop - @eyeam3 
* [x] Airmind MindPX / MindRacer - @iZhangHui 
* [x] Test team - @r0gelion, @mrpollo

**Comment by mrpollo** [comment]
Here's the v1.6 release sign-off issue https://github.com/PX4/Firmware/issues/7258

**Comment by sanderux** [comment]
Can we get a final release candidate for testing?

**Comment by iZhangHui** [comment]
MindPX/MindRacer pass our flight testing, and we are ready for v1.7 release.

**Comment by mrpollo** [comment]
v1.7.0 was released, thanks to everyone here for their help pushing this one out

https://github.com/PX4/Firmware/releases/tag/v1.7.0
