### ISSUE TITLE
Anyone use PC with wifi router to control snapdragon drone with wifi receiver? Without use of a RC?

### ISSUE THREAD

**Issue by koshea7** [PX4/Firmware#8429]
**Bug Report** or **Feature Request**

For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](slack.px4.io). Issue reports need to contain the items below:

 - Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/flight-reporting.html))
 - Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/)
 - Expected behavior and actual behavior.
 - Steps to reproduce the problem.
 - Specifications like the version of the project, operating system, or hardware.

**Comment by dagar** [comment]
I've done this with a pixracer over wifi and it can work okay. At the very least I strongly recommend you start with RC. If the telem link proves to be reliable you can consider using it without RC.

Please use http://discuss.px4.io/ for general questions.
