### ISSUE TITLE
Parameterize loiter ascend/descend speed?

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#8437]
@dagar 
When changing the altitude set point in tecs we add a [feed forward term](https://github.com/PX4/ecl/blob/dea0c8bb6a6f27743a56b284ddb290a94334d2bb/tecs/tecs.cpp#L269-L269) in order to provide tight tracking and keep the pitch integrator from winding up. However, if the commanded altitude change is a step, e.g. from a loiter wp, then the feed forward term in tecs will be ineffective since the height rate set point will be [saturated by the maximum climb rat](https://github.com/PX4/ecl/blob/dea0c8bb6a6f27743a56b284ddb290a94334d2bb/tecs/tecs.cpp#L275)e. 
Is this intended?
My question is if we should, instead of giving tecs a step input when changing altitude, add a slew rate e.g. in fw_pos_control such that tecs does not have to limit the climb speed internally. A parameter would then control the loiter ascend speed, if that one is set to be lower than the maximum ascend speed, the altitude tracking will be improved since the feed forward term will be effective also in loiter.

**Comment by dagar** [comment]
Yes we should finally do something about this (it comes up every so often). I'm just not sure if we should handle it in the fixed wing position controller or directly in TECS.

Could we do it maintaining the commanded airspeed? Look at the resulting behaviour with speed weight 2 for example.

@priseborough what do you think?
