### ISSUE TITLE
Bokeh application is not working

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8458]
Bokeh application is not working, log viewer is not working.

[Log example](https://logs.px4.io/plot_app?log=1431e7f7-82a4-4a13-a0ba-162e6f492671)

@LorenzMeier

**Comment by bkueng** [comment]
There was an exception on the server in the spectral plotting, which I cannot reproduce locally. Strange enough restarting the server program fixed it as well. Anyway I worked around it with https://github.com/PX4/flight_review/commit/4ee62b9b63084d8ffbf0e4a15c1208501cc357e2.

I also improved the error handling for such cases: https://github.com/PX4/flight_review/commit/70631a40a0b2e3bf0130c47b3c8971d61f5bd008

FYI @joaeba
