### ISSUE TITLE
Unable to retrieve v1.6.1 of PX4. 

### ISSUE THREAD

**Issue by myeabhishek** [PX4/Firmware#8470]
Hi Team,

I am using the following version of PX4 for one of my drones. I want to replicate the same for my other drones, however, I am not able to retrieve this particular version of PX4. This is not listed among any releases and I am not able to clone and build it as well. Can you please guide me on how get this version or build it if required?

HW arch: PX4FMU_V2
FW git-hash: 50ecee9df817ebc414d606b5b551aab08d86b598
FW version: 1.6.1 0 (17170688)
OS: NuttX
OS version: Release 7.10.0 (118489343)
OS git-hash: 8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06
Build datetime: Jun  8 2017 13:24:52
Build uri: localhost
Toolchain: GNU GCC, 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
MFGUID: 3531393531345118002f001b
MCU: STM32F42x, rev. 1
WARNING   WARNING   WARNING!
Revision 1 has a silicon errata:
This device can only utilize a maximum of 1MB flash safely!
https://pixhawk.org/help/errata
UID: 2F001B:31345118:35313935

**Comment by dagar** [comment]
Here's a link to the v1.6.1 px4fmu-v2 binary, but I'd still recommend you upgrade to the latest stable.

https://s3.amazonaws.com/px4-travis/Firmware/v1.6.1/px4fmu-v2_default.px4
