### ISSUE TITLE
Upgrade Failure v1.7.0 Stable Release

### ISSUE THREAD

**Issue by rollysing** [PX4/Firmware#8477]
Upgrade failed following procedure for v1.7.0 stable release firmware. The video was made recreating the issue by reverting back  to v1.6.3. I have been able to successfully revert back to v1.6.5 Stable since the video. Video of the failure is below. Timeline description as follows:

0:25 Shows COM Port recognized in Windows 8.1 Pro prior to upgrade
0:46 Firmware version
0:56 Start of upgrade
1:15 Clipped to shorten video right before it says Upgrade Complete
1:34 Device Manager keeps blinking for PX4 FMU COM Port because it just connects then immediately disconnects and just stuck in this loop. The usual tones indicating upgrade is completing doesn't happen.
1:56 Closed QGC and unplugged USB cable to restart it to let it boot completely, per popup message.
1:56 Plugged in USB but COM Port still stuck in loop.
2:28 Zoomed in on Pixhawk to show all the lights blinking. Noting right B/E blinking rapid Red and left constant Red; ACT blinking Blue.

https://youtu.be/3AwHMFB3_TM

**Comment by dagar** [comment]
@rollysing see https://github.com/PX4/Firmware/pull/8478
