### ISSUE TITLE
Add support for "frame" argument in "COMMAND_INT" version of MAV_CMD_DO_REPOSITION

### ISSUE THREAD

**Issue by shylent** [PX4/Firmware#8502]
MAV_CMD_DO_REPOSITION works as documented (in http://mavlink.org/messages/common) when used as COMMAND_LONG. However, COMMAND_INT has a `frame` argument, which could apply to this command:
* if user specifies MAV_FRAME_GLOBAL_RELATIVE_ALT_INT (6), param7 (altitude) is interpreted as relative to home position
* if user specifies MAV_FRAME_GLOBAL_INT (5), param7 (altitude) is interpred as AMSL (same as with the COMMAND_LONG version)

Right now, altitude is always interpreted as AMSL, which can be worked around if one wants to work in terms of relative altitude, but such workaround seems to be quite indirect.

I've worked around it as follows (ROS-specific stuff follows, sorry): I need to reposition to some _relative altitude_ Z. I take relative altitude from `/mavros/altitude`, subtract it from AMSL altitude from the same `/mavros/altitude` thus getting the offset between the two (or, alternatively, the AMSL altitude of the home point). Adding the offset to Z, I get its AMSL equivalent.

**Comment by dagar** [comment]
This might be a good excuse to generalize MAV_FRAME (https://mavlink.io/en/messages/common.html#MAV_FRAME) usage across navigator.

It would make DO_REPOSITION more useful, and it's a stepping stone to local coordinate frame mission support. @Stifael FYI
