### ISSUE TITLE
error compiling master for Aerotenna ocpoc

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8510]
I got an error when trying to compile posix_ocpoc_ubuntu target.

[Error](http://pasted.co/b7acbe7c)

Using Ubuntu 16.04 LTS

**Comment by davidaroyer** [comment]
It looks like you're just missing a python package. Here's the error:
```

Required python packages not installed.

On a GNU/Linux or MacOS system please run:
  sudo pip install numpy toml

On Windows please run:
  easy_install numpy toml
```

**Comment by r0gelion** [comment]
Thank you, that fixed the problem.
