### ISSUE TITLE
Zero offset of SDP3x conflicts with uncalibrated airspeed status

### ISSUE THREAD

**Issue by svpcom** [PX4/Firmware#8511]
If airspeed sensor (SDP3x) has zero offset then SENS_DPRES_OFF sets to 0.0 which is
handled as default (uncalibrated) value. For example qgroundcontrol shows airspeed sensor in bad state.  Do we need to set it to some small value (for example 0.001) or select other value for uncalibrated state?

**Comment by LorenzMeier** [comment]
Short-term setting it to a very small value would fix this. Does it really indicate you 0 when you calibrate it? I find that the offset is virtually zero, but still can be calibrated to be completely zero.

**Comment by svpcom** [comment]
Yes, in my case it completely zero.

**Comment by dagar** [comment]
Interesting problem to have!

I think what we really need is a proper interface for sensor status to send QGC. Right now it directly checks these parameters. @DonLakeFlyer FYI

**Comment by LorenzMeier** [comment]
Fixed here: https://github.com/PX4/Firmware/commit/ddf0ecfc3801b63f0849d5ba37a523746c53d8b4
