### ISSUE TITLE
Add a new topic

### ISSUE THREAD

**Issue by KatelynLiu** [PX4/Firmware#8516]
**Can't subscribe any data**

I want to add a new external IMU by uart, so I write a driver for the IMU and add the driver as a moudle under src/drivers. In the driver, I advertise and publish the topic, but there's a wired problem:  If I subscribe the topic in the driver too( using another handle ), I can receive the right message from the topic, but if I subscribe the topic in another file, there's no data from the topic, and the function px4_poll() returns 0.
I'd appreciate if you can help me solve this problem.

**Comment by LorenzMeier** [comment]
We can't solve problems without seeing your code. Please send a pull request and we can continue the discussion there.
