### ISSUE TITLE
ekf2 failed to set home when ekf2_aid_mask is setup as gps+vpe position(9)

### ISSUE THREAD

**Issue by EliaTarasov** [PX4/Firmware#8518]
PX4 version: master
When EKF2_AID_MASK is setup as fuse GPS and Vision Position at the same time, then home pos is failed to be setup. However adding vision position fusion in flight works ok. Is it possible to setup home pos using GPS and Vision Position at the same time?

**Comment by dagar** [comment]
Do you have a log showing this?

**Comment by EliaTarasov** [comment]
Yes sure.
AID_MASK 1: https://logs.px4.io/plot_app?log=0637d591-63a8-4354-a4d6-cfd4510392ce
AID_MASK 9: https://logs.px4.io/plot_app?log=56b14d7e-2518-4f55-b7c3-432e385b50cd
Thanks in advance!

**Comment by ChristophTobler** [comment]
@EliaTarasov What commit are you using? I just tried with latest master and it works in SITL (I saw you tested in SITL as well).

Can you write down instructions to reproduce it?

**Comment by ChristophTobler** [comment]
@EliaTarasov Please reopen and add instructions if this is still an issue.

**Comment by EliaTarasov** [comment]
Confirmed, latest master works ok.
