### ISSUE TITLE
Pixhackv3 sensor position issue with 1.7.x

### ISSUE THREAD

**Issue by urlu75** [PX4/Firmware#8523]
**Bug Report** 

Accell sensor with 1.7.x are not correct. To calibrate them correctly, I have to change the orientation of the board : roll 180 and yaw 270. With that the frame position is correctly detected.
But then, compass calibration is not successful.

Everything is perfectly detected and calibrated with 1.6.5 without any change in the board orientation.

**Comment by dagar** [comment]
PX4 v1.7.0 added board detection for px4fmu-v2/v3 boards that actually had differences. We need to figure out how the Pixhawkv3 should be handled, and how it's currently detected.

Could you run `ver all` on the console?
Do you have a schematic for the Pixhackv3? I mainly want to know about the sensors.

**Comment by urlu75** [comment]
here is the `ver all`

`
NuttShell (NSH)
nsh> ver all
HW arch: PX4FMU_V2
HW type: V2M
HW version: 0x0009000A
HW revision: 0x00000000
FW git-hash: 7dab5d438027c0b43c8b269b403a21e92dec7061
FW version: Release 1.7.2 (17236735)
OS: NuttX
OS version: Release 7.22.0 (118882559)
OS git-hash: b18053574bf41712cef93e31bf178518f451a350
Build datetime: Dec 21 2017 08:04:32
Build uri: localhost
Toolchain: GNU GCC, 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
MFGUID: 3030383034355113002e0030
MCU: STM32F42x, rev. 3
UID: 2E0030:34355113:30303830 
`

I don't have a schematic for this board, will try to find it.
As it is perfectly working with 1.6.5, would it be possible to guess sensors information ?

**Comment by dagar** [comment]
It's being detected as a pixhawk mini (`HW type: V2M`). The px4fmu-v2 version detection is relatively new. We'll likely need to get our hands on a schematic to figure out how to handle this board.

@davids5 FYI

**Comment by LorenzMeier** [comment]
@urlu75 What sensors are on this board? What do you get with 1.6.5 here?

<img width="1120" alt="screen shot 2018-01-01 at 16 47 41" src="https://user-images.githubusercontent.com/1208119/34468910-8252b2dc-ef13-11e7-97b2-dbc2b826c69f.png">

**Comment by LorenzMeier** [comment]
Please try this binary which is based on this branch: https://github.com/PX4/Firmware/pull/8553

[px4fmu-v3_default.px4.zip](https://github.com/PX4/Firmware/files/1596218/px4fmu-v3_default.px4.zip)

**Comment by urlu75** [comment]
The board is detected as a v2, I tried v2 and v3 FW.

Bellow is the device list with px4fmu-v3_default.px4 1.6.5
<img width="1316" alt="px4 1 6 5" src="https://user-images.githubusercontent.com/19515081/34566674-aecc34c0-f15f-11e7-9f16-74c58097c3e5.png">

with px4fmu-v3_default.px4 1.7.2
<img width="1317" alt="px4 1 7 2" src="https://user-images.githubusercontent.com/19515081/34566685-bd7e6204-f15f-11e7-9d68-4b006a895d66.png">


and with the FW you sent. Seems better, no more warning about gyro but alignement is still not good
<img width="1313" alt="px4 new" src="https://user-images.githubusercontent.com/19515081/34566705-db9573ae-f15f-11e7-943c-3e097d11c6fa.png">

I sent an email to CUAV to request the schematic but no answer yet.

**Comment by urlu75** [comment]
If it's help, found what's look like to be the PCB schematic

https://github.com/cuav/CUAV_Hardware/tree/master/Pixhack_V3

**Comment by LorenzMeier** [comment]
Is this issue still pending?

**Comment by dagar** [comment]
@urlu75 could you quickly verify the internal sensors and orientations on a pixhack v3?

**Comment by urlu75** [comment]
yes but ... how do you do that, what would you need ?

**Comment by davids5** [comment]
@urlu75 please test with https://github.com/PX4/Firmware/pull/10231 All sensors are now detected. The rotations may need to be adusted.

**Comment by urlu75** [comment]
just flash with last dev fw: 3 accel, 3 gyro and 2 mag. seems all good, thanks !
<img width="1440" alt="capture d ecran 2018-08-16 a 15 47 41" src="https://user-images.githubusercontent.com/19515081/44212780-8bdf3080-a16c-11e8-9de5-525950bb1827.png">
