### ISSUE TITLE
[Bug] Brake twitching on huge multicopter( wheelbase >800mm) for new V1.7.2 code

### ISSUE THREAD

**Issue by whyscience** [PX4/Firmware#8527]
Log is here: https://logs.px4.io/plot_app?log=e9e92a61-7db0-487c-99cc-ad68b171e0d7

![image](https://user-images.githubusercontent.com/3918941/34346586-21142976-ea34-11e7-99d0-82a3bb9adf00.png)

![image](https://user-images.githubusercontent.com/3918941/34346590-2ae66644-ea34-11e7-816f-c8d1fff704ca.png)

Using the default params, the wheelbase is 800mm and 1200mm, when the drone brakes, it brakes twice or triple, as shown in the log.
On DJI F450, it's OK.

**Comment by whyscience** [comment]
- Another log: https://logs.px4.io/plot_app?log=6d4f4e0d-7707-44b9-a673-057fbb2a4a15
- The video is here: https://youtu.be/tuYLPnBJfkk

**Comment by LorenzMeier** [comment]
The controller goes into saturation on the outputs:
https://logs.px4.io/plot_app?log=6d4f4e0d-7707-44b9-a673-057fbb2a4a15#Nav-Actuator-Outputs-Main

This is not a Firmware issue, but a tuning issue on your airframe. We have improved the control performance in V1.7 and you might need to adjust your attitude / rate control gains.

**Comment by whyscience** [comment]
OK, thanks.

**Comment by whyscience** [comment]
@LorenzMeier  I still have a doubt, there is only one saturation in the log, but in the video, it twitched more than one time, the corresponded log didn't go to saturation. 
![bokeh_plot](https://user-images.githubusercontent.com/3918941/34357710-4e3f3e5e-ea84-11e7-86f1-4ab8e9cbc433.png)

**Comment by LorenzMeier** [comment]
Your system is in [marginal stability](https://en.wikipedia.org/wiki/PID_controller#Stability) and you need to tune it. The parameter reference has some explanations, but in general familiarity with PID controllers is required.

I can see that you have not tuned the PID gains at all for your airframe and used the default gains. This *will not work* (it never works for any flight controller). If you fly a big drone you absolutely need to tune the control loops. The defaults only work for default-sized drones.

Tuning gain reference is here:
https://dev.px4.io/en/advanced/parameter_reference.html#multicopter-attitude-control

If you do not know how to tune you can drop me an email to lorenz@px4.io and I can put you in touch with people in the community that offer commercial support. You can alternatively post to http://discuss.px4.io for help from the community.

This is not a software issue but an issue with your airframe setup, so we will not continue to analyse it here. Thanks!

**Comment by whyscience** [comment]
Thanks again.
