### ISSUE TITLE
can't find RC_MAP_OFFB_SW 

### ISSUE THREAD

**Issue by tiralonghipol** [PX4/Firmware#8534]
Hi. I'm struggle to find this parameter inside  QGroundControl, and none of the tutorials I'm following is specific in this parameter.
Any idea?
I'm trying to send Mavros messages to the Pixhawk autopilot via usb.

Thanks!

**Comment by LorenzMeier** [comment]
<img width="1120" alt="find_param" src="https://user-images.githubusercontent.com/1208119/34456305-8c272da0-ed93-11e7-941b-f9c64513c8ea.png">

@hamishwillee I think we need a "find param page"

**Comment by LorenzMeier** [comment]
issue for that: https://github.com/PX4/px4_user_guide/issues/122

Closing this one as fixed.
