### ISSUE TITLE
ll40ls for rpi3

### ISSUE THREAD

**Issue by belaidH** [PX4/Firmware#8538]
is the ll40ls compatible with the posix platform (rpi3) because when I compile I get error about (nuttx/clock.h and nuttx/wqueue.h).

**Comment by dagar** [comment]
You'll need to go through and fix those issues. Remove the nuttx headers first, then readd generic headers as needed.

**Comment by LorenzMeier** [comment]
Or in other words: It is reasonably easy and a pull request would be appreciated.

**Comment by belaidH** [comment]
sorry I am not an expert. So I just have to remove the headers ? because after that several problems concerning the variable or function 'work' appear .

**Comment by dagar** [comment]
@belaidH yes remove those headers, and in that case add `#include <px4_workqueue.h>`.

**Comment by belaidH** [comment]
Okey thank you. I will try it

**Comment by belaidH** [comment]
I think now it's okay for the workqueue. but I get an other error 
about the irqstate_t on the LidarLiteI2C.cpp file (I would use the I2C of the rpi). 

![capture du 2018-01-01 11-59-19](https://user-images.githubusercontent.com/34583606/34467222-457694be-eeeb-11e7-821a-1f794b3da741.png)

**Comment by dagar** [comment]
@belaidH you can replace the critical sections with ATOMIC_ENTER/ATOMIC_LEAVE.

On NuttX it's the same thing - https://github.com/PX4/Firmware/blob/master/src/drivers/device/nuttx/cdev_platform.hpp#L10
On other platforms it's a lock - https://github.com/PX4/Firmware/blob/master/src/drivers/device/posix/cdev_platform.hpp#L6

**Comment by belaidH** [comment]
@dagar thank you. after some tries it's compiled. Is there manip to start the ll40ls after launching the ./px4 because I don't see his topic when I use the "uorb top" command.

**Comment by dagar** [comment]
Does it work if you start it manually `ll40ls start`?

Once you're sure it's working you could add it to the raspberry pi configs here. https://github.com/PX4/Firmware/tree/master/posix-configs/rpi

**Comment by belaidH** [comment]
@dagar when I try this  there is an error "Error opening fd".

**Comment by dagar** [comment]
If you open a pull request I can review and cross test. The I2C might be wrong for the raspberrypi as well. 

On Linux the i2c buses map to `/dev/i2c-X`.

**Comment by belaidH** [comment]
okey, this is my pull requests  https://github.com/belaidH/Firmware/pulls

**Comment by dagar** [comment]
Can you open as a pull request against the main PX4 Firmware repository? https://github.com/PX4/Firmware

**Comment by belaidH** [comment]
yes, I did it.  https://github.com/PX4/Firmware/pull/8579

**Comment by dagar** [comment]
Done!
