### ISSUE TITLE
mRO Boot Loop

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#8544]
Fix is here: https://github.com/PX4/Bootloader/pull/94

**Comment by tops4u** [comment]
To be precise, this also happened on my FMUv2 Units once they have been updated with a current v5 Bootloader. With v4 it did not happen.

**Comment by LorenzMeier** [comment]
Solved: https://github.com/PX4/Bootloader/commit/0bebcc36d13180ef172ee4665bc54df39a99a5fb

**Comment by LorenzMeier** [comment]
We will notify known manufacturers (Dronecode members)
