### ISSUE TITLE
Build System does not build uORB headers for example apps

### ISSUE THREAD

**Issue by hamishwillee** [PX4/Firmware#8562]
The helloworld example (and probably others) can be built "stand alone" or as part of a full build. If built stand-alone from a clean system the build fails because the uORB headers have not yet been generated. 

The build system should detect if headers are present, and if not either generate them or warn that they need to be generated. I assume this should be done as some sort of "global" check?

Some discussions:
- http://discuss.px4.io/t/no-such-file-or-directory-uorb-topics-sensor-combined-h/1336/8
- https://px4.slack.com/archives/C581ST17V/p1514839763000075

**Comment by LorenzMeier** [comment]
@bkueng Could you please investigate?

**Comment by bkueng** [comment]
@hamishwillee I don't quite understand what is meant with "stand alone". The [dev-guide](https://dev.px4.io/en/tutorials/tutorial_hello_sky.html) does not mention that, and I don't see how uORB should be of any use if you only have your own single app.

**Comment by hamishwillee** [comment]
@bkueng I'm just the messenger here. I *think* the use case was that they built the app without having first build the whole of PX4. As you say, perhaps that is "not supported" so we can just close this.

Probably worth you looking at the discussion on slack and seeing if I have misinterpreted what is happening.

**Comment by bkueng** [comment]
Hmm, reading slack I still don't understand the use case. If you want a reduced build, I suggest copying an existing cmake target and remove most of the modules. That will still give you a valid build as long as you don't remove uORB.

**Comment by hamishwillee** [comment]
I'm going to close this then. The user has a link and can reopen with more detail if they can provide it.
