### ISSUE TITLE
FW_ARSPD_MODE param meta data confusing

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#8563]
So I went to fix this QGC bug: https://github.com/mavlink/qgroundcontrol/issues/5478. Here is what you see in the parameter editor:
<img width="321" alt="screen shot 2018-01-02 at 5 30 30 pm" src="https://user-images.githubusercontent.com/5876851/34506573-ef55e050-efe2-11e7-8087-4932f2b8763b.png">

It's confusing as to what Enabled/Disabled means. I would suggest switching the meta data to enum strings which are more descriptive. Something like:
* No airspeed sensor
* Airspeed sensor installed

Or something like that.

**Comment by DonLakeFlyer** [comment]
Or in other words the concept of "Enabling" something in order to "Disable" it is odd.

**Comment by dagar** [comment]
This happened when it went from a parameter with 3 options to a bool.
