### ISSUE TITLE
getchar() doesn't block on Linux

### ISSUE THREAD

**Issue by bgat** [PX4/Firmware#8580]
**Bug Report**

PX4's command prompt input is driven by getchar(), which doesn't seem to be blocking properly on Linux. There are two unexpected side-effects:

* the EOF returned gets echoed to the screen, which is invisible to interactive users but shouts loudly at systemd (pull request coming shortly)
* the scheduler thinks the system is CPU-bound

Sticking a poll() in front of the getchar() in platforms/posix/main.cpp doesn't fix the problem, because it seems that stdin is always POLLIN-ready. (?)

**Comment by bkueng** [comment]
Do you need the shell when starting with systemd? If not you can start px4 with the `-d` param: `./px4 -d px4.config`, which disables the shell.
