### ISSUE TITLE
Eagle: Auto and RTL non responsive

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#8603]
Running master c0c0666
Auto and RTL do not respond despite having good gps lock
Flight in position mode without issues
https://logs.px4.io/plot_app?log=474076d1-969e-41fd-bcf7-eaa0489c3038
https://logs.px4.io/plot_app?log=f9593388-cbae-48b9-a55d-4884dd162644

Logs not showing error messages

**Comment by dagar** [comment]
Can you expand on what you mean by auto and RTL not responding?

These baro spikes are also a bit concerning, but not your main issue.
![image](https://user-images.githubusercontent.com/84712/34635585-cec8e074-f25f-11e7-8adb-92c373c665c8.png)

**Comment by santiago3dr** [comment]
this issue has been resolved and both platforms work on 1.8.0 stable
