### ISSUE TITLE
Advertise a topic

### ISSUE THREAD

**Issue by KatelynLiu** [PX4/Firmware#8607]
**The Communication with QgroundControl will lost at once advertise a topic**

I add a module named "xsens" in "src/drivers", which is a driver of a external IMU. And I run the code already, it worked well. When I add the "advertise" lines, the program can be compiled. However when I run the program by using QgroundControl, the commuication lost will show up. I wonder why and how to solve this problem.
Looking forward to your help.

For convenience, I attach my core code: [https://github.com/KatelynLiu/Firmware/blob/master/src/drivers/xsens/xsens.cpp](http://url)

**Comment by zarathustr** [comment]
I do not know which is the so called ORB id "xsens_accel". Is that the one you defined yourself? By the way, if this is simply for sensor sampling, the code won't be fully worked on PX4
