### ISSUE TITLE
MinorBug: Preflight Check Spaming after Sensor Calibration

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8621]
**Bug Report**

After having performed a Magnetometer Calibration, Preflight Check complained about bad GPS Accuracy every 1.xy secs and spaming the Messages. 

![preflightcheckspam](https://user-images.githubusercontent.com/6877067/34655028-2ce024e2-f404-11e7-8777-f66a065753d9.png)

**Comment by dagar** [comment]
Should be fixed here. https://github.com/PX4/Firmware/pull/8622
If you'd like to test please follow the Jenkins build link under build results and then click artifacts for the corresponding binary.

**Comment by tops4u** [comment]
Oh, this was Quick. 18 Minutes from Report to Fix 🥇
