### ISSUE TITLE
Support for ICM-20948 as external I2C Compass

### ISSUE THREAD

**Issue by caomuqing** [PX4/Firmware#8624]
Feature Request

The HERE GNSS module from Hex Technology comes with ICM20948 as an external compass, replacing the already EOL HMC5983 compass. Can we request adding support for that?
Thanks!

**Comment by LorenzMeier** [comment]
Sure! Not hard, but we don't have hardware with any of our core developers right now.

**Comment by caomuqing** [comment]
Thanks Lorenz, I can ask to send samples to developers. May I ask who we should send to, and the shipping address?

**Comment by LorenzMeier** [comment]
Can you send me an email to lorenz@px4.io? Thanks!

**Comment by mrlarsendk** [comment]
Hi @LorenzMeier,

Are there any status updates on this issue? Do you have the hardware at hand?

Best regards,
Michael

**Comment by albert21martins** [comment]
Hi I have also a PX4 2.1 and a Here with this compass. Is there a pre-release where we could work and integrate in the release 1.7.3 stable?

**Comment by LorenzMeier** [comment]
Closing as duplicate.
