### ISSUE TITLE
px4flow not fused in lpe 

### ISSUE THREAD

**Issue by yousafbinfarrukh** [PX4/Firmware#8626]
Hey all,

I'm working on a project, using pixhawk flight controller on an sk450 kit. I'm using px4fmu-v2_lpe build. But when I enable the fusion of optical flow, the values of local position remain close to zero. However, when I connect the px4flow with the computer and analyze the local position, they seem to be just right. I've not yet flown the bot for I don't want to risk it. I can switch to the position control. But moving the quadcopter manually doesn't affect much.  
Regards

**Comment by mhkabir** [comment]
Pleased use EKF2. It is the default navigation estimator we will support for optical flow navigation.
