### ISSUE TITLE
Can I take ADS-B data on SITL(PX4)?

### ISSUE THREAD

**Issue by CrazyDominic** [PX4/Firmware#8649]
Can I take ADS-B data on SITL(PX4)?
If it can be, can multiple drones on the simulator send and receive ADS-B data?

**Comment by hamishwillee** [comment]
I don't think so - certainly it is not mentioned [here](https://docs.px4.io/en/advanced_features/rtk-gps.html).

Please ask technical support questions in the correct channel: https://docs.px4.io/en/#support

**Comment by CrazyDominic** [comment]
@hamishwillee OK Thanks!
