### ISSUE TITLE
VTOL: Back transition after the end Nasty Pitch up.

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#8655]
Hi guys,

We have a strange problem with the back transition with our delta-quad.

The problem is only in Position mode. No such problem when in Altitude or Stabalized modes.

After the back transition is finished the MC sharply makes a putch up command.

We have MPC_DEC_HOR_MAX and MPC_ACC_HOR_MAX set to 2 but still this kick back.

![back transition pitch up](https://user-images.githubusercontent.com/12617619/34802898-dab458ec-f678-11e7-8a15-421c1d4597c1.png)

Here is the log:
https://logs.px4.io/plot_app?log=a11fdda4-1d23-48c2-8596-f5c5a16e23ba

Any Ideas?

**Comment by dagar** [comment]
Any difference in mission mode?

**Comment by tubeme** [comment]
Mission mode is the same! So probably it is in the Position controller.

**Comment by tubeme** [comment]
Also wonder why there is no Pitch nor Roll Set Points during the transition.

We fly without airspeed sensor!

**Comment by dagar** [comment]
I believe it's the way the multicopter position controller is reinitialized and seeded during transition. As a temporary improvement you can reduce MC_PITCHRATE_MAX.

**Comment by sanderux** [comment]
This is because your velocity when coming out of backtransition is still 6m/s while your mpc_xy_vel_max is set to 4. Increase your back transition duration or use reverse thrust to brake actively

**Comment by tubeme** [comment]
@sanderux Thanks a lot!
