### ISSUE TITLE
I need to help about Multi-vehicle ...

### ISSUE THREAD

**Issue by CrazyDominic** [PX4/Firmware#8660]
This below picture is my ubuntu...

I command "roslaunch px4 multi_uav_mavros_sitl.launch" on my terminal.

After that, Gazebo is popped up and I can show 3drones model.
But, I have only one terminal that is just showed "pxh>".

My question is this. Why can I see just one terminal? In my think, this one terminal has 3 simulators.

How to command each drone?

![2018-01-12 10-58-05](https://user-images.githubusercontent.com/23605855/34856278-8e2f33e2-f787-11e7-988f-206f6af447e1.png)

**Comment by hamishwillee** [comment]
Please ask technical questions here: http://discuss.px4.io/
