### ISSUE TITLE
VTOL: Front transition Ramp Up problem

### ISSUE THREAD

**Issue by tubeme** [PX4/Firmware#8664]
@dagar and @sanderux 

Because we fly without airspeed sensor, during the front transition everything is timing. So in Position / Auto modes the the ramp up of the front transition pusher motor is something like this:

![front throttle ramp up current](https://user-images.githubusercontent.com/12617619/34873084-62c895e4-f79c-11e7-97cb-1526e298d88d.png)

Visible from the graph:

![front ramp up](https://user-images.githubusercontent.com/12617619/34873091-6e5ae268-f79c-11e7-8788-74f9bb3bbf27.png)

![front max thr reached](https://user-images.githubusercontent.com/12617619/34873103-7a0af90e-f79c-11e7-896a-b15879b6a3e0.png)

In the Log:

https://logs.px4.io/plot_app?log=4d974849-6f42-4b03-945d-8e0eb96e2f29

I could not find a way to make the ramp up of the pusher motor like this during the transition:

![front throttle ramp up new](https://user-images.githubusercontent.com/12617619/34873149-abf2f930-f79c-11e7-8178-12448650436d.png)

I found a parameter for the back transition ramp up:

VT_B_TRANS_RAMP which is the reverse to what I want to achieve.

Am I missing something?

Can I use VT_TRANS_P2_DUR to make it 1-2 seconds to achieve this?

**Comment by tubeme** [comment]
May be is not a bad idea to have a VT_F_TRANS_RAMP parameter for the front transition ramp up as well.

**Comment by tubeme** [comment]
This is not a proper ramp up for Front transition for VTOL in Position and Mission Modes.

![front ramp up07](https://user-images.githubusercontent.com/12617619/34922184-0e133d56-f995-11e7-92f8-e805b5281f67.png)

This is like having the real plane ramp up from 0 to full throttle from the beginning of the runway to the end of it.

With VT_TRANS_THR=0.7 every time after the transition the plane is almost at stall. It is seen from the throttle demand after the transition.

**Comment by tubeme** [comment]
@sanderux Any ideas about the front ramp up? I could not find a way to control it.

**Comment by sanderux** [comment]
you need to set VT_F_TRANS_DUR to 1 (thats the ramp-up time for front transition)

**Comment by sanderux** [comment]
also 5 seconds is probably too little for a deltaquad

**Comment by tubeme** [comment]
Strange... 
Here is from parameters reference...

VT_F_TRANS_DUR
(FLOAT) | 
Duration of a front transition
Comment: 
Time in seconds used for a transition

Thanks for the info I will note it.
