### ISSUE TITLE
Docker image for qurt / snapdragon

### ISSUE THREAD

**Issue by potaito** [PX4/Firmware#8687]
**Feature Request**

I am working on the snapdragon fight and wanted to add a make target like `make eagle_default` to Continuous Integration. 

The script `Tools/docker_run.sh` then tries to fetch a container from the user lorenzmeier
https://github.com/PX4/Firmware/blob/18b83f2960879a71d19b456f5823d0abb2950290/Tools/docker_run.sh#L13

which is not public. Was it even public at one point? Is there a licensing problem with having the Hexagon SDK in a public docker container? Is someone already working on bringing it back? @LorenzMeier @dagar Do you have any info? :)

The error I get is
```
$ ./Tools/docker_run.sh 'make eagle_default'

guessing PX4_DOCKER_REPO based on input
PX4_DOCKER_REPO: lorenzmeier/px4-dev-snapdragon:2017-07-28
Unable to find image 'lorenzmeier/px4-dev-snapdragon:2017-07-28' locally
docker: Error response from daemon: pull access denied for lorenzmeier/px4-dev-snapdragon, repository does not exist or may require 'docker login'.
See 'docker run --help'.

```

**Comment by dagar** [comment]
It's private and used by the CI system. The SDK is free, but you need to agree to the EULA.
