### ISSUE TITLE
LPE local position drifts from GPS position in position hold mode

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [PX4/Firmware#8692]
We are trying to develop autonomous system using GPS and Vision fusion and after few weeks working only with vision we have realized that there's a problem with GPS position. Local position is not following absolute position from gps. Logs are here:

[logs](https://logs.px4.io/plot_app?log=87d618e2-fc5a-4ef3-849b-8fed68e0183a)

I think that all parameters are correct and it should work. `lpe_fusion` parameters is set to `173` which is `10101101_2`. According to [source code](https://github.com/PX4/Firmware/blob/master/src/modules/local_position_estimator/params.c) gps fusion is on.

Could you tell me if that's a bug or something is wrong with our config?

**Comment by TSC21** [comment]
@Ekci there is currently an issue with GPS fusion that is tracked and should be fixed soon.

**Comment by TSC21** [comment]
Also do you mind sharing some more logs where you have vision+gps+baro fused, vision+baro fused and gps+baro fused so to compare between each? That would help debug the problem. Thanks

**Comment by Ekci** [comment]
Oh, thank you clearing that up. Yes I will do some flying indoors (without gps) and outdoors this week and update here.

**Comment by ArkadiuszNiemiec** [comment]
Now that it's finally spring here we went back to testing:
I have build a new version of LPE Firmware (1.7.X) and after first flight I can say that something changed. With GPS + vision fusion enabled (but without any vision position published) there was no issue with position hold.
I have not found any info about it in the changelog so I will update here after some flights with vision position and with and without GPS enabled.

**Comment by santiago3dr** [comment]
@ArkadiuszNiemiec have you tested this on 1.8.0?

**Comment by TSC21** [comment]
Closing as stale. Reopen if it persists.
