### ISSUE TITLE
HIL GPS Triggers "Unknown Armed" Flight Mode

### ISSUE THREAD

**Issue by axdhill** [PX4/Firmware#8694]
**Bug Report** 

I'm passing indoor position measurements via offboard computer using the telemetry port of my Pixhawk 2.1 running PX4 1.7.3 stable. The position measurements are streamed as fake GPS coordinates. The message types sent are:
`HEARTBEAT`
`LOCAL_POSITION_NED`
`HIL_GPS`
`GPS_INPUT`
The expected behavior is that px4 sees the incoming mavlink stream for indoor positioning (HIL GPS is enabled in PX4). 

In 1.7.3 stable, QGC sees the flight mode as flipping constantly from the correct mode (Stabilized, Unarmed) to "Unknown Armed." The copter is not actually armed. I can use the RC to really arm it and take off manually, and HOLD mode functions as expected (multicopter locks in position). However, I cannot use QGC to automatically takeoff - I assume because the flight mode is constantly flipping between Stabilized/Unknown and Armed/Unarmed.

In 1.6.5 this did not happen - the flight mode remained as expected even when GPS was fed in through telemetry.

**Comment by axdhill** [comment]
![px4_problem](https://user-images.githubusercontent.com/21051548/34961911-fcae5ed4-fa06-11e7-818e-23c3f2ca0bf5.gif)

**Comment by santiago3dr** [comment]
this might be related to issue #8613
