### ISSUE TITLE
VTOL: Reject position control / Hold / Mission after succeed GPS lock.

### ISSUE THREAD

**Issue by svpcom** [PX4/Firmware#8696]
I've found a strange issue with v1.7.3: PX4 reject to switch to POSCTL, HOLD  or Mission.
GPS is running and got 3D lock. When I try to start mission from QGroundControl is shows message: "vehicle is not ready". I've tried to recalibrate all sensors, but it didn't help. All sensors status are good. 

HW is mRo pixhawk with fmuv3 (2MB) firmware.
Frame is: VTOL quad delta

https://logs.px4.io/plot_app?log=60f77638-9a48-4aac-95a8-66cf25eb19ae

**Comment by dagar** [comment]
I'm not sure why yet, but you never had a global position estimate.

**Comment by dagar** [comment]
![image](https://user-images.githubusercontent.com/84712/34965635-978d95ca-fa23-11e7-876a-8108af3d4561.png)

**Comment by svpcom** [comment]
I've got it. Yes i'm testing partially inside (on the balcony). But (IMHO) ground station should show more clear GPS status and provide messages why vehicle should not do some action. Because now most of users will panic in such case.

**Comment by dagar** [comment]
I couldn't agree more. https://github.com/PX4/Firmware/issues/8697

**Comment by RomanBapst** [comment]
@svpcom @dagar I'm going to close this because the main issue is addressed in #8697 
@svpcom If you want to give feedback as a user you can do that in #8697
