### ISSUE TITLE
Add LOITER state to FAILSAFE RTL

### ISSUE THREAD

**Issue by TickTock-** [PX4/Firmware#871]
When RTL is initiated via FAILSAFE, it should first go to LOITER for a programmable time before starting the RTL sequence.  A negative value in the parameter would indicate to *never* RTL and just LOITER indefinitely on FAILSAFE.

**Comment by severinleuenberger** [comment]
We would appreciate this enhancement as well, and most likely it will be a requirement to get a permission trough FOCA (GALLO) in Switzerland.

**Comment by anton** [comment]
@julianoes I think you highlighted the wrong nick just now.
