### ISSUE TITLE
tfmini not working on V4 hardware

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#8713]
https://github.com/PX4/Firmware/pull/8548 doesn't work for me on a Pixracer or Intel Aero...
I have tried on a Pixhawk (v3 target) and there it worked. On Pixracer and Intel Aero, I get
```
ERROR [tfmini] immediate read failed
ERROR [tfmini] Task exited with errno=11
```
Any Ideas @ayushgaud?

I was disabling mavlink on those ports https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L545-L554

**Comment by dagar** [comment]
Which serial port is it connected to? https://github.com/PX4/Firmware/blob/master/src/drivers/distance_sensor/tfmini/tfmini.cpp#L84

**Comment by ayushgaud** [comment]
I think it could be because of the hard coded serial port address. You may
try modifying it according to your platform.

**Comment by ChristophTobler** [comment]
Sorry, forget to mention that I actually did that...
I used `tfmini start /dev/ttyS3` on the Intel Aero (which should be the telemetry port) and `tfmini start /dev/ttyS1` on the Pixracer (TELEM1, if I remember correctly)

**Comment by dagar** [comment]
@ChristophTobler did you stop mavlink on those interfaces (or prevent it from starting)?

**Comment by ChristophTobler** [comment]
@dagar I stopped the instances mentioned in the first comment. That should be enough right?
Can I stop a stream on a specific device (e.g. `/dev/ttyS1`) without stopping mavlink completely (`mavlink stop`)?

**Comment by ChristophTobler** [comment]
fix in https://github.com/PX4/Firmware/pull/8726.
