### ISSUE TITLE
No FS-RTL when in LOITER state

### ISSUE THREAD

**Issue by TickTock-** [PX4/Firmware#873]
If I am flying and put the craft into LOITER (no mission loaded) and turn off the radio, the aircraft stays in LOITER.  I assume this is a side effect of the popular thinking that the current mission should continue on loss of radio signal.  However, I'm not sure this is what we want if we happen to be in the LOITER state when the radio signal was lost.  Certainly if I have not loaded a mission, I would want the aircraft to begin RTL upon FS.  If I have paused a mission, it isn't clear to me if we should proceed with the mission or begin RTL but I don't think we should stay indefinitely in LOITER.

**Comment by LorenzMeier** [comment]
Implemented.
