### ISSUE TITLE
make px4fmu-v2_default upload hangs in docker

### ISSUE THREAD

**Issue by mymbrooks** [PX4/Firmware#8741]
**Bug Report** or **Feature Request**

For general questions please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](slack.px4.io). Issue reports need to contain the items below:

 - Download the flight log file from the vehicle ([tutorial](https://docs.px4.io/en/flight-reporting.html))
 - Share the link to a log showing the problem on [PX4 Flight Review](http://logs.px4.io/)
 - Expected behavior and actual behavior.
 - Steps to reproduce the problem.
 - Specifications like the version of the project, operating system, or hardware.

I use docker image --- px4-dev-nuttx.Hardware is pikhawk 1.

docker --version
Docker version 18.01.0-ce, build 03596f5

Host 
Ubuntu 16.04 x64

Docker run command:
docker run -it --privileged \
	-v /media/wangsen/LinuxData/Tools/PX4/Firmware:/home/user/Firmware:rw \
	-v /tmp/.X11-unix:/tmp/.X11-unix:ro \
	-e DISPLAY=:0 \
	--name=px4-dev-nuttx px4io/px4-dev-nuttx /bin/bash

I can successful build with command : make px4fmu-v2_default
But the upload is always hangs on : 
[1/1] uploading /home/user/Firmware/build/px4fmu-v2_default/px4fmu-v2_default.px4
Loaded firmware for 9,0, size: 1027561 bytes, waiting for the bootloader...

I also tried : 
docker run -it --name=px4-dev-nuttx --device=/dev/ttyPixhawk:/dev/ttyPixhawk px4io/px4-dev-nuttx /bin/bash

and lsusb on host : 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 003: ID 093a:2510 Pixart Imaging, Inc. Optical Mouse
Bus 003 Device 002: ID 1c4f:0002 SiGma Micro Keyboard TRACER Gamma Ivory
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 007: ID 26ac:0011  
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by dagar** [comment]
I believe this is because the bootloader presents a different USB id to the system.

**Comment by mymbrooks** [comment]
@dagar Is it possible to build and upload in docker?

**Comment by dagar** [comment]
@mymbrooks yes if you pass the device through to docker.

**Comment by alnI3S** [comment]
Hi @dagar,

I have "Waiting for bootloader.." hangs even I use --privileged flag to run docker container to access devices.

I've noticed that the name of the device is different in host or in the container:
 - lsusb in host outputs: `Bus 003 Device 011: ID 3162:004b Holybro Durandal-BL`
 - lsusb in the conatiner outputs: `Bus 003 Device 012: ID 3162:004b Holybro PX4 DurandalV1`

So what should I change to make it works?
