### ISSUE TITLE
What mode can I Disarm the Intel RTF in ?

### ISSUE THREAD

**Issue by RohanKurane** [PX4/Firmware#8744]
Per @LorenzMeier  I am opening this bug here - 

I arm and takeoff the Intel RTF in Loiter mode.
Then I -
    Try to Disarm - but it says the mode in invalid
    I change to Land mode and then try to disarm but it still says the mode in invalid.

What mode(s) can I do a Disarm in ?
What is the correct procedure - Arm and Takeoff followed by Land and Disarm ?

Is there a table that tells which modes can I Arm and Disarm in (mutually exclusive table)?

@zehortigoza @lucasdemarchi @DonLakeFlyer @LorenzMeier

**Comment by dagar** [comment]
Could you provide specific detail? How are you arming/disarming? Using the RC controller, QGroundControl, or some other mechanism? Where are you seeing the invalid mode message?

Do you have any flight logs? https://logs.px4.io/

**Comment by RohanKurane** [comment]
I arm using QGC to arm, disarm, change mode etc. The invalid mode message is displayed on QGC at the top when I try to disarm in Loiter or Land mode (after hitting takeoff). 
I can get logs. 

In the meantime, can you tell me the proper steps - 
Arm in Loiter mode
Takeoff
<fly>
Change to Land mode
Disarm
Is this correct ?

**Comment by mhkabir** [comment]
Are you using the PX4 Flight Stack?

**Comment by RohanKurane** [comment]
@mhkabir  Yes I am

**Comment by RohanKurane** [comment]
@mhkabir Do you know a list of modes I can arm and disarm in ?

**Comment by zehortigoza** [comment]
Take a look at this example: https://github.com/intel/mavlink-router/blob/master/examples/px4-offboard-mode.cpp you need to check if PX4 have detected the land to be able to disarm. You can also test your code with PX4 simulators(airsim is the easiest to install)
