### ISSUE TITLE
The priority setting when adding a driver

### ISSUE THREAD

**Issue by KatelynLiu** [PX4/Firmware#8760]
**How to set the priority** 
I add a new driver under Firmware/src/drivers. However, before I made the driver autostart, it can work correctly. And when I start it by QGroundControl Mavlink Console, it can publish the topic as well as other module can subscribe it. 
When I add 'start' in init.d/rCS, it can only publish the first message although it publish in a loop.  If I change the priority in the `_mti300_task = px4_task_spawn_cmd( "mti300" , 
				      SCHED_DEFAULT,
				       SCHED_PRIORITY_MAX - 10,
				       2000,
				       (px4_main_t)&mti300::task_main_trampoline,
				       nullptr);`
the pixhawk maybe even lose communicaton with the QGroundControl. 
I guess the problem is the priority, but I don't know how to set the proper priority. 
How to make my own driver work as other driver like GPS? 
Looking forward to your help.

**Comment by bkueng** [comment]
Hi
I cannot say much without seeing the code, so if you can provide it, that will help. If you lose communication it can mean that you have a busy loop in the driver, or it crashes.
