### ISSUE TITLE
Typo in Quad+ toml file 

### ISSUE THREAD

**Issue by cglusky** [PX4/Firmware#8822]
Just reading through some of the new changes to the multi mixer files.  Think  this line is supposed to be read "rear"...

https://github.com/PX4/Firmware/blob/64f032441c3579d07287d5e3bac424dbf9d7ab4f/src/lib/mixer/geometries/quad_plus.toml#L28

**Comment by dagar** [comment]
Thanks Coby. Would you like to submit a PR fixing it?

**Comment by cglusky** [comment]
Yes, I can do that.

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/9008
