### ISSUE TITLE
batt_smbus is broken

### ISSUE THREAD

**Issue by AlexKlimaj** [PX4/Firmware#8834]
Trying to compile batt_smbus in the latest master and there are numerous compile errors. 

Can we bring this up to date and make it more generic by removing the 3dr solo information?

**Comment by dagar** [comment]
Surprisingly it's not included in any configs. Would you like to post the errors to work through getting it working again? Once it's working we can add it to the larger build targets (px4fmu-v3, v4, etc).

**Comment by AlexKlimaj** [comment]
Yeah, here is the first one. 

> ../../src/drivers/batt_smbus/batt_smbus.cpp: In member function 'int BATT_SMBUS::write_reg(uint8_t, uint16_t)':
../../src/drivers/batt_smbus/batt_smbus.cpp:749:31: error: 'debug' was not declared in this scope
   debug("Register write error");

And the second one

> ../../src/drivers/batt_smbus/batt_smbus.cpp: In member function 'uint8_t BATT_SMBUS::get_PEC(uint8_t, bool, const uint8_t*, uint8_t) const':
../../src/drivers/batt_smbus/batt_smbus.cpp:846:44: error: passing 'const BATT_SMBUS' as 'this' argument discards qualifiers [-fpermissive]
  tmp_buff[0] = (uint8_t)get_device_address() << 1;

I got it to compile by commenting out the debug calls, GETPEC function, and its calls.

**Comment by dagar** [comment]
Ok, this looks pretty straightforward to recover.

**Comment by dagar** [comment]
@AlexKlimaj do you want to open a pull request adding this to the board you care about and fixing the first few issues? From there I'll jump in and fix the remaining failures.

**Comment by AlexKlimaj** [comment]
I started working on it yesterday. It seems that the UORB battery messaging has changed since it was last used. I am also writing it for a TI BQ40Z50-R1/R2.

**Comment by dagar** [comment]
Please give https://github.com/PX4/Firmware/pull/8840 a try. I believe it will publish to the 2nd instance of battery_status (battery_status1), so we may need to add something to disable/ignore the default ADC battery status handling.

**Comment by AlexKlimaj** [comment]
I can try it today. I found yesterday that setting BAT_SOURCE to 1 will set the battery ADC's to be ignored. It's in sensors.cpp.

**Comment by dagar** [comment]
Ah, right BAT_SOURCE. That's a bit of a hacky workaround, but we can properly expand the usage of that param to work correctly here.

**Comment by AlexKlimaj** [comment]
I've created https://github.com/PX4/Firmware/pull/8854
