### ISSUE TITLE
Mavlink command routing to companion computer

### ISSUE THREAD

**Issue by myeabhishek** [PX4/Firmware#8866]
I want to MAV_CMD mavlink messages coming from Ground control system to my companion computer connected to Pixhawk via telem 2. Basically I want to handle some of the commands on ROS for example camera controlling commands. 

Can you please tell me how can I route mavlink messages coming from QGC to companion computer or if it has been done already?

**Comment by CarlOlsson** [comment]
Start the mavlink app with forwarding active (-f flag) in order to route messages between QGC and an on board computer via the autopilot.

**Comment by hamishwillee** [comment]
On most pixhawk boards this is automatically enabled using SYS_COMPANION -
 https://dev.px4.io/en/companion_computer/pixhawk_companion.html#pixhawk-setup

I "think" the code for this is in https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS

**Comment by myeabhishek** [comment]
So the forwarding is enabled now. Can you please tell me under which rostopic will I get MAV_CMD data?

**Comment by hamishwillee** [comment]
I can't. I suggest you raise question on the discussion forums.

**Comment by lamping7** [comment]
There is no ROS topic for this. https://github.com/mavlink/mavros/issues/943

**Comment by LorenzMeier** [comment]
I'm closing this - please use http://discuss.px4.io for discussions. Thanks!
