### ISSUE TITLE
Log files are corrupted while running landing_target_estimator

### ISSUE THREAD

**Issue by Haukanes** [PX4/Firmware#8877]
Logging is corrupted while running **landing_target_estimator** on Pixhawk 3 pro.

Link to a corrupted ulg-file:
https://drive.google.com/open?id=14-G4SMnJahB05vPmnaAYSnPGib5vQ1El

**Comment by dagar** [comment]
@bkueng could you take a look?

**Comment by mhkabir** [comment]
Can confirm this too.

**Comment by dagar** [comment]
@mhkabir pixhawk as well? I'm wondering about SITL.

**Comment by Haukanes** [comment]
SITL logging works fine on gazebo_iris_irlock.

**Comment by bkueng** [comment]
This is an interesting one. Fix is here: https://github.com/PX4/Firmware/pull/8884
