### ISSUE TITLE
uORB replace all IOCTL usage

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#8891]
We need a uORB mechanism to completely replace the use of IOCTLs for sensor drivers. The main thing is device id, and calibration get/set. The rest are nearly unused outside of the driver itself (a few small exceptions).

If we move this to uORB the vast majority of sensor drivers wouldn't actually need any IOCTLs or even a CDev.

@LorenzMeier thoughts?

**Comment by dagar** [comment]
Do we need a ROS services equivalent? http://wiki.ros.org/Services
@RomanBapst

**Comment by LorenzMeier** [comment]
@dagar Yep.

**Comment by dagar** [comment]
@thomasgubler @bkueng @RomanBapst any thoughts on this?

It's also an opportunity to recover quite a lot of flash. The majority of IOCTL code is manually duplicated, including across very similar devices.

**Comment by bkueng** [comment]
I agree, a ROS services equivalent would be benefitial.

**Comment by dagar** [comment]
Moving to v1.10.0

**Comment by dagar** [comment]
Slowing getting there.

**Comment by dagar** [comment]
Almost there. Should be completely done by v1.12.0.
https://github.com/PX4/Firmware/pull/14237

**Comment by dagar** [comment]
Done!
