### ISSUE TITLE
mission_type = 7 bug

### ISSUE THREAD

**Issue by Jeblas** [PX4/Firmware#8894]
**Bug Report** 

- Using an Intel Aero RTF drone with nuttex-aero-v1-default.px4 firmware
- Link to the original QGC issue: https://github.com/mavlink/qgroundcontrol/issues/6077
> that the vehicle is sending MISSION_ITEM messages to QGC with mission_type set to 7. Two problems there:
> - It should be 0, which indicates a regular old mission item
> - 7 as a value for MISSION_TYPE doesn't even exist.

**Comment by LorenzMeier** [comment]
@anitha-suresh Could you look into this?

**Comment by LorenzMeier** [comment]
@anitha-suresh This is still an issue.
