### ISSUE TITLE
uorb_graph is missing some connection

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#8901]
Some publishers are missing from the graph, its happens when the module uses 'uORB::Publication'
For examples:
vehicle_local_position publisher form ekf2
https://github.com/PX4/Firmware/blob/f932217fdc706e5ac02769b41444e4e9a7e3e4a4/src/modules/ekf2/ekf2_main.cpp#L336

I have noticed to few more, but not much.
I guess that for subscribers it happens too with 'uORB::Subscription'

**Comment by hamishwillee** [comment]
@bkueng Assigned to you because I assumed this was about https://dev.px4.io/en/middleware/uorb_graph.html ...  but it might not be.

**Comment by bkueng** [comment]
I'm aware of that, and as I wrote in https://github.com/PX4/Firmware/pull/8393, I planned to do some refactoring for these classes, before adding them to the graph.

**Comment by hamishwillee** [comment]
@bkueng Assume you are still keeping an eye on this one.

**Comment by bkueng** [comment]
Yes
