### ISSUE TITLE
When SDLOG_MODE = 2 or 1 (from boot) Not all parameters are recorded

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#8903]
Due to early start of the logger, not all parameters are recorded when SDLOG_MODE = 2 or 1.
Its might be better to delay the logger start, or do other method to make sure that all modules are started before starting the log.

**Comment by dagar** [comment]
@BazookaJoe1900 could you give this a try? https://github.com/PX4/Firmware/pull/8904
