### ISSUE TITLE
Actuator Control logging frequency in System Identification mode seems too small

### ISSUE THREAD

**Issue by neom89** [PX4/Firmware#8911]
Hi! I am trying to perform a realistic system identification using **actuator_controls_0_0** and **sensor_combined_0** data so that I can get a respectable PID gains using Matlab. 

I set the SDLOG_PROFILE to 3 which is the System Identification mode but on analyzing the data I can see that actuator_controls_0_0 is recorded at only 10 Hz (approx) whereas sensors_combined_0 is logged at 250 Hz (approx). I know that the attitude control runs at a minimum of 50 Hz. Is there parameter to increase the logging frequency of actuator controller? Ideally, can I log all the actuator control values through some parameter?

**Comment by dagar** [comment]
Did you reboot after changing SDLOG_PROFILE?

**Comment by vmishra9** [comment]
Thanks for the reply @dagar . SDLOG_PROFILE = 3 (System Identification mode) is the default setting.

**Comment by dagar** [comment]
@vmishra9 SDLOG_PROFILE is now a bitmask.

3 = default + ekf replay
![image](https://user-images.githubusercontent.com/84712/36360376-5e0369d6-14f1-11e8-9a07-a3652f9a9f7a.png)

Enabling system identification would be 11.
![image](https://user-images.githubusercontent.com/84712/36360385-713f5078-14f1-11e8-972e-c8d9aad91392.png)

**Comment by vmishra9** [comment]
ok. Changed SDLOG_PROFILE to 11 and now I have both sensors_combined and actuator_controls at 250 Hz (approx.)

One more question though, in sensors_combined, is **gyro_rad[i]** data angular velocity or delta angle ? I am confused because it has a name gyro_rad and not gyro_rad_s.

**Comment by dagar** [comment]
It's angular velocity (averaged over gyro_integral_dt).

**Comment by tecdee** [comment]
@neom89 Pls how did you carry out your system identification? I have a custom drone which I have built using px4. I am trying to obtain a model so that I can design more precise PID gains. Please help. Thanks.
