### ISSUE TITLE
[SITL crash] px4 node crashes on startup

### ISSUE THREAD

**Issue by TobiMiller** [PX4/Firmware#8925]
Hey,

i can successfully compile with "make posix_sitl_default gazebo". the px4 node crashes when i run "roslaunch px4 mavros_posix_sitl.launch". 

Is this a known problem? 

i have compiled protobuf v3 for cartographer. i returned to protobuf v2.6.1 from source because the px4 firmware doesnt compile with v3.  

what exactly means the symlink error?

![crash_px4_node](https://user-images.githubusercontent.com/32275/36423491-73378652-1640-11e8-8c9c-28ffacd9c0f3.png)

**Comment by lamping7** [comment]
Delete the three symlinks in the .ros directory that point to the firmware:
1. ROMFS
2. posix-configs
3. test_data

So, `cd /home/tobias/.ros/` then `rm` the three symbolic links
Then try again.

**Comment by TobiMiller** [comment]
Thanks a lot. That was the problem. as easy as that.
