### ISSUE TITLE
accelerometer_timestamp_relative is always '0'

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/Firmware#8926]
I am not sure if its a bug or not.
Looking at plots of sensors_combined message, I can see that accelerometer_timestamp_relative is always 0.
I am not sure about the logic that related to this var, and if it just log issue.
I can say that magnetometer_timestamp_relative and baro_timestamp_relative are not constant 0.

**Comment by bkueng** [comment]
The accel timestamp is relative to the gyro timestamp. And because they come from the same driver with the same publication rate, it's always 0.

**Comment by BazookaJoe1900** [comment]
@bkueng  Thanks.
