### ISSUE TITLE
Unstable sensors cause Critical problem

### ISSUE THREAD

**Issue by Ahrovan** [PX4/Firmware#8927]
Bug Report

I used Pixhawk hardware's (listed below), but in Most of the time see "PREFLIGHT FAIL" message for MAG,GYRO,ACCEL and in one case cause crashed.

[log uploaded (Pixhawk LITE 2.4.6)](https://logs.px4.io/plot_app?log=b0be3ceb-c180-40b9-9cc4-d31ef1c1920a)

```
[commander] PREFLIGHT FAIL: ACCEL #1 UNCALIBRATED
[commander] PREFLIGHT FAIL: GYRO #1 UNCALIBRATED
[commander] PREFLIGHT FAIL: MAG SENSORS INCONSISTENT
[commander] PREFLIGHT FAIL: MAG #1 UNCALIBRATED
```

 - All boards calibrated with USB cable, in some case with WiFi module

The hardware's list (all with PX4 Firmware v1.7.3 + gps module m8n):

- Pixhawk 2.4.6 (maybe 3DR original version)
- Pixhawk 2.4.6 (Copy version)
- Pixhawk LITE 2.4.6

**Comment by LorenzMeier** [comment]
@dagar Is this related to the open detection PR?

**Comment by Ahrovan** [comment]
@LorenzMeier Probably a mistake occurred in your reply :)

**Comment by LorenzMeier** [comment]
No it's not.

**Comment by Ahrovan** [comment]
@dagar @LorenzMeier What is your opinion about this problem? Do you need more information for troubleshooting? I try with another pixhawk and send log file today.

**Comment by dagar** [comment]
@Ahrovan it's possible your issue is related to https://github.com/PX4/Firmware/pull/8703, https://github.com/PX4/Firmware/issues/8643. I've discussed with @davids5 and have a potential fix to implement and test later tonight.

Could you expand on exactly what you did? When did you calibrate relative to flashing? How are you powering the pixhawk? Did you command a restart from QGroundControl (including selecting an airframe) or the reboot command in nuttx?

**Comment by dagar** [comment]
Could you try https://github.com/PX4/Firmware/pull/9074?

**Comment by Ahrovan** [comment]
@dagar The problem persists with the latest version (v1.8.2 Stable Release)

**Comment by hansbonini** [comment]
Same problem on 1.9-dev

**Comment by julianoes** [comment]
@hansbonini and @Ahrovan could you answer to this:

> Could you expand on exactly what you did? When did you calibrate relative to flashing? How are you powering the pixhawk? Did you command a restart from QGroundControl (including selecting an airframe) or the reboot command in nuttx?

And can you try latest master?

**Comment by julianoes** [comment]
Closing because no one followed up.

**Comment by Ahrovan** [comment]
I'm a follower. But there is no feedback from developers

**Comment by hamishwillee** [comment]
@Ahrovan This request was waiting on a response here from you or @hansbonini:
 https://github.com/PX4/Firmware/issues/8927#issuecomment-509977006

If you're happy to act as the stakeholder on the reporter side (?) I'm sure @julianoes is more than happy to reopen and continue investigation
