### ISSUE TITLE
Battery Estimation Initialization on some Platforms like Intel Aero Fails

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/Firmware#8930]
After merging #8153 there seem to be certain platforms on which the initialization of the battery estimate seems to fail. The result is that if you start up the platform even with a full battery you are not allowed to take off because the low battery states are already engaged and you can by definition not get out of them again.

Reported cases are:
- @ndepal Unkown Platform
- @santiago3dr Intel Areo
- @ChristophTobler Intel Aero

I have access to an Intel Aero so I should be able to test. And I already have the suspition that these platforms report a very low/invalid voltage in the beginning and after that it the low battery states can not recover anymore.

**Comment by santiago3dr** [comment]
This looks to also have affected the OcPoc
Upon bootup and connection to qgroundcontrol, i get a low/critical battery warning despite battery being fully charged and shown at 100%
![ocpoc](https://user-images.githubusercontent.com/13203106/36494885-49d5eb84-16e8-11e8-8775-b7eb69e5de81.JPG)

**Comment by lbegani** [comment]
I am also facing the same issue with Aero, find the log here - https://logs.px4.io/plot_app?log=ea64f182-b898-4a4b-8f76-85638f99610e
