### ISSUE TITLE
Snapdragon: broken communication with QGroundControl

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#8931]
Running current master or stable firmware, snapdragon fc does not fully connect to qgroundcontrol.

I can partially connect to qgcbut get error shown below upon connecting:
![1](https://user-images.githubusercontent.com/13203106/36503365-c5516c0c-1701-11e8-9d92-b519a7daa172.JPG)

Unable to upload mission file, get this error:
![2](https://user-images.githubusercontent.com/13203106/36503382-cb48bf02-1701-11e8-98be-36901cca725d.JPG)

Have flashed stable firmware on the snapdragon, attempted stable build of qgroundcontrol to no avail.
No sure if this is on the firmware side or qgc

**Comment by LorenzMeier** [comment]
@ChristophTobler Do you have this issue on your end as well?

**Comment by ChristophTobler** [comment]
Just tried with current master and QGC v3.3.0: It doesn't connect to QGC and the msg is (repeatedly)
```
Info: [pm] unknown param ID: xxxx
```

**Comment by santiago3dr** [comment]
I'm not sure if this is firmware relevant but with 1.7.4 beta, and QGroundControl 3.3.1 stable , i am able to connect, calibrate and read/write a mission file.

Having similar issues with the Intel Aero, see #9259
