### ISSUE TITLE
/mavros/vision_pose/pose not showing up in /mavros/local_position/pose

### ISSUE THREAD

**Issue by SubMishMar** [PX4/Firmware#8955]
I am using LPE_FUSION to send vision position and yaw to the pxhawk FCU but the data in the above mentioned rostopics are very different. In fact the /mavros/local_position/pose echoes some constant garbage which doesnt change as  /mavros/vision_pose/pose changes . Any lead on how to fix this issue? I followed the following tutorial: https://dev.px4.io/en/ros/external_position_estimation.html
but seems it is not working for me

**Comment by TSC21** [comment]
@SubMishMar you probably saw that there is an issue template for reporting issues, bugs, etc. Please follow it so we are able to help you.

**Comment by MulixBF** [comment]
Hello. 

I am facing similar issue. [Video](https://youtu.be/KX2sJIWfB6U)
I am using default PX4 settings except for:

```SYS_MC_EXT_GROUP: local_position_estimator
ATT_EXT_HDG_M: Vision```

For the reasons beyond my control I have to use old PX4 version:

```pxh> ver all
HW arch: 
SITLFW git-hash: 61120d895b1cfa3798aa6bb2ce4056421ef4de6e
FW version: v1.5.5-2-g61120d8 (1.5.5 0), 17106176
OS version:  (255)
Build datetime: Nov 15 2017 23:24:39
Toolchain: 5.4.0 20160609
UNKNOWN MCU
UID: 0:1:2```

I am running SITL simulation in gazebo on Ubuntu Linux 16.04 with ROS kinetic installed from official repoes.

**Comment by vuanhduy** [comment]
Hi @MulixBF,

How do you feed the mocap information into your gazebo?

**Comment by mhkabir** [comment]
Closing as no information provided.
