### ISSUE TITLE
The filter for the D-term should be enabled by default

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#8962]
@bkueng We should find a way to enable your improvement by default.

**Comment by bkueng** [comment]
Agreed. I thought we should first do the driver sampling refactoring (https://github.com/PX4/Firmware/pull/8731), before discussing filter defaults. @RomanBapst also wanted to look into the whole filtering pipeline.

**Comment by LorenzMeier** [comment]
@bkueng What is the status now (10 days later)? Given the time that has passed, is doing more effort realistic or should we get a sane default in? I believe we can choose a filter cutoff that is far from the dynamic limits of pretty much any vehicle and will not impair flight performance.

**Comment by bkueng** [comment]
Personally I'm not yet confident enough to say which defaults make sense. I wanted to do some more tests on different vehicles (like the aero fc), which I can do next time I have one available (within the next week or so).
@MaEtUgR also wanted to do some testing on his vehicle(s).
