### ISSUE TITLE
Port mpu9250 to linux

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#8963]
@dagar still working on this?

**Comment by dagar** [comment]
Not actively, but the idea is to keep pushing enough into `drivers/device` that the final "porting" will be close to trivial. Find and replace a few key things with platform agnostic versions, drop portions now handled by the base class, drop nuttx specific headers.

If there's an immediate need for this I suspect we could get it done in an afternoon.

**Comment by mcsauder** [comment]
No reason to wait... This is a positive direction... Let's get to work...  Temp fix merge requests already in queue... additional merge requests to follow... :)

**Comment by dagar** [comment]
Initial pieces here. https://github.com/PX4/Firmware/tree/pr-mpu9250
