### ISSUE TITLE
PixRacer: battery failsafe tones broken

### ISSUE THREAD

**Issue by SayanR1** [PX4/Firmware#8983]
Running Master 38e5a06 Battery failsafe triggers Rtl but no tones can be heard from the autopilot; all other tones seem to be working

log: https://review.px4.io/plot_app?log=b30fdb6b-7927-4cbf-8329-ecb0fc12e0d1

@santiago3dr was able to reproduce with today's Master 198708b

log: https://logs.px4.io/plot_app?log=47fdca0e-ab26-4b93-8b63-d2a13ed22e5e

**Comment by santiago3dr** [comment]
looks to be working on beta 1.7.4
