### ISSUE TITLE
tailsitter  fly forward and fall suddenly

### ISSUE THREAD

**Issue by MikeWellC** [PX4/Firmware#8997]
In position mode,tailsiter fly forward , but fall sudenly. 
RC alt chanel(rc_channels_0.channels[3]) no action，Why vehicle_local_position_setpoint decrised.

https://logs.px4.io/plot_app?log=e395b143-1e01-4195-b385-77ca6ab75ef7

**Comment by RomanBapst** [comment]
Sample problem as in #9032
