### ISSUE TITLE
Unexpected position setpoint during loiter mode after pause

### ISSUE THREAD

**Issue by JohnSnowball** [PX4/Firmware#9003]
**Bug Report**
Standard vtol, normal flight.
During RTL, I paused the plane for a few seconds to watch, then I tape on the "land" command, however, it goes straight forward and hits a tree.
I checked log, after the "land" command is sent, an unexpected position setpoint is created, while mission setpoint type is not valid.
Here is the log:
https://logs.px4.io/plot_app?log=4cbc668e-2688-41a0-a09c-8f9758fc70c0 

log screen shot is here:
![image](https://user-images.githubusercontent.com/18409502/36932576-c757a744-1f05-11e8-99d4-fb1f4de48d57.png)

**Comment by JohnSnowball** [comment]
this confused me a lot, as I have done many times in simulation, but could not reproduce this bug, why in that time, the plane doesn't go into landing flight mode, instead it stayed in loiter mode(repositioning) and flies to an unknown position? 
@julianoes @DrTon  I really need your help.

**Comment by julianoes** [comment]
@JohnSnowball thanks for the report. I have to defer VTOL questions to @RomanBapst.

**Comment by JohnSnowball** [comment]
I found it comes from an unexpected "rally" point command from QGC.
