### ISSUE TITLE
generic airframes

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#9004]
We should have a wide range of generic airframes at different sizes. Many of our specific airframes are actually fairly generic, and users rarely have the same thing.

I also don't think we should carry exact configurations for something that isn't well defined. Either available off the shelf or with a very specific build log.
 - https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/13008_QuadRanger
 - https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/13001_caipirinha_vtol
 - https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/13010_claire

MC
 - different sizes for quad
  - 180, 250, 330, 450, etc
 - drop effectively generic options like flamewheel 330, 450, zmr250
 - variations with vmount and uavcan should be configurable via parameters on top of defaults, rather than new airframes

FW
 - a few common sizes and configurations

VTOL
 - tailsitter
   - duo, tri, quad
 - quadplane
   - quadranger 
 - tiltrotor
   - not sure if there are generics here?

I'd like to see a generic option as the default for each frame type.

![screenshot from 2018-03-03 12-21-40](https://user-images.githubusercontent.com/84712/36937207-da04f0c2-1edd-11e8-8a42-5d9de04b8220.png)
![screenshot from 2018-03-03 12-22-13](https://user-images.githubusercontent.com/84712/36937209-dc451c40-1edd-11e8-8ea6-c89e296f2ad0.png)
![screenshot from 2018-03-03 12-22-30](https://user-images.githubusercontent.com/84712/36937210-dc5e5cdc-1edd-11e8-99e2-fe3be31c39f0.png)
![screenshot from 2018-03-03 12-22-54](https://user-images.githubusercontent.com/84712/36937211-dc8a4cfc-1edd-11e8-88a4-fe92700381d9.png)

**Comment by dagar** [comment]
We should also get rid of this.

![image](https://user-images.githubusercontent.com/84712/36937224-15f172fe-1ede-11e8-9a40-5900989d23b2.png)

**Comment by hamishwillee** [comment]
I think this makes a lot of sense. Will users understand how to map best "generic" case to use for (say) flamewheel 330? 

> variations with vmount and uavcan should be configurable via parameters on top of defaults, rather than new airframes

Any variation that requires setting parameters might be a lot harder for users?

**Comment by dagar** [comment]
> Any variation that requires setting parameters might be a lot harder for users?

I was thinking the opposite. It's not like most users wishing to use vmount will have the exact airframe that offers vmount.
Parameters can also be broken out into accessible high level QGC gui configuration.

**Comment by hamishwillee** [comment]
I was imagining a scenario where I purchased an RTF DJI flamewheel - previously I could just select an airframe and now I have to additionally set some parameters. Very happy to accept I know nothing about this :-)

**Comment by philipoe** [comment]
I also agree the airframe groups need to be changed, at least for the fixed-wing planes. I openened https://github.com/PX4/Firmware/issues/9118 a couple of days ago because I had not seen this discussion.
