### ISSUE TITLE
HoTT Telemetry and SUMD

### ISSUE THREAD

**Issue by Ralfde** [PX4/Firmware#9021]
The HoTT Telemetry does not work with the acutal receiver firmware any more, because the telemetry can and should now be send faster.
SUMD does make problems, too.
Does anybody have a chance to look into it, especially the telemetry issue?

**Comment by AndreasAntener** [comment]
Could you describe the problems with SUMD?

**Comment by Ralfde** [comment]
Got SUMD frames being decoded by the Spektrum driver as well, which gave the flight controller incorrect radio controller stick positions intermittently.

**Comment by Ralfde** [comment]
To who could I mail also the new SUMD3 protocoll?
