### ISSUE TITLE
Throttle spike on arming

### ISSUE THREAD

**Issue by Vavooon** [PX4/Firmware#9022]
In rare cases after arming throttle level is higher for a second, then goes back to normal values.
I noticed it first time when I used 1.7 firmware, however there is similar topic from previous year http://discuss.px4.io/t/slight-higher-idle-throttle-when-first-arm/2471 .
In related issue was mentioned that MPC_THR_MIN could affect but after I lowered the parameter nothing has changed.
Here's the log https://logs.px4.io/plot_app?log=7c0b159c-bf28-48dc-8677-b3ccd1c2d25b1 .

I've also noticed that it happens after first arm.

**Comment by michael1874888** [comment]
Have you solved the problem?
We have faced the same problem recently.

**Comment by Vavooon** [comment]
@michael1874888 Not yet, just waiting for some response.
How high is throttle level in your case? Is it close to hover or just a bit bigger than idle level?

**Comment by michael1874888** [comment]
Our drone would fly very high at the beginning, and it became normal in few seconds.
We thought that it is cause by the firmware version, it might be a bug in the newest version.
After we degrade to PX4 firmware to 1.6.5 and it became normal.

**Comment by RomanBapst** [comment]
@Vavooon The link to the log you provided is broken. Please provide a functional link please.

**Comment by Vavooon** [comment]
https://logs.px4.io/plot_app?log=f23bc221-f07d-403f-a4f8-61d80e7957aa
And here's raw file
https://drive.google.com/open?id=1H-7zfCWeuLMOSyWP0_bZQR7Rilzm5kDJ

**Comment by fabrizioschiano** [comment]
Has anyone solved this problem? I am having the same issue

**Comment by bresch** [comment]
> Has anyone solved this problem? I am having the same issue

Do you have this issue using master? If yes, please re-open a new issue.
