### ISSUE TITLE
pwm test has no effect after version 1.5.x

### ISSUE THREAD

**Issue by nanthony21** [PX4/Firmware#9052]
I have been unable to use the `pwm` app in nutshell to test my outputs. After building various versions of the source I've found that this issue began sometime between 1.5.5 and 1.6.0rc1. I should note that the outputs work fine for normal operation, it is just the nutshell app that isn't working.

The procedure I use to test whether or not it works is the following:
1: Plug in usb for communication with QGC
2: Plug in battery to power up the ESC's
3: Type `mc_att_control stop` into nutshell.
4: Type `pwm test -c 1 -p 1100` into nutshell and see if a motor starts up.

I'm using a Pixracer on a Quadrotor X airframe.

One thing I notice that seems relevant is that on a version that works (1.5.5 and below) when I type `mc_att_control stop` then the `SERVO_OUTPUT_RAW` mavlink messages stops going out. On a non-working version (1.6.0 and up) the `SERVO_OUTPUT_RAW` message continues at 20 Hz even after disabling the attitude controller.

**Comment by RomanBapst** [comment]
This is the same issue as #8850 

pwm test is not working on px4fmu. The problem is that you get disarmed pulses from the fmu between the commanded pulses.
