### ISSUE TITLE
Commander Failure Handling Cleanup

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#9085]
This issue tracks the planning and implementation of the commander failure mode cleanup as discussed in the technical dev-call 03/14/2018

Deadline for putting together list of cleanup tasks: 2018-04-20

**Comment by dagar** [comment]
Notes: https://docs.google.com/document/d/1nY-JmViSy03ZDkTIYYVG4mjXUTPJiUKJlpm5H5BBAuI/edit

**Comment by thomasgubler** [comment]
➤ Thomas Gubler commented:

@Beat Küng I assign this to you since you are from us probably in the best position to contribute to the google doc
