### ISSUE TITLE
QGroundControl daily: No airspeed sensor calibration available

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#9120]
Flashed Beta 1.7.4 and i am not given the option to calibrate airspeed sensor
![capture](https://user-images.githubusercontent.com/13203106/37671909-fd4810f6-2c29-11e8-8e8f-ec3f3e0099b9.JPG)

Was able to successfully calibrate all other sensors

Airspeed calibration looks to be available on qgroundcontrol stable 3.3.0
![image](https://user-images.githubusercontent.com/13203106/37673167-c75a1b80-2c2c-11e8-9ca7-30c8d97a76e3.png)

Running a Pixhawk mini (v3 build) on a Phantom Flying Wing

**Comment by dagar** [comment]
See https://github.com/mavlink/qgroundcontrol/pull/6270

**Comment by dagar** [comment]
@santiago3dr this is fixed in QGC daily. https://github.com/mavlink/qgroundcontrol/pull/6272

**Comment by santiago3dr** [comment]
great!
thanks
