### ISSUE TITLE
Multi Copter land after loss of position failsafe doesn't disarm

### ISSUE THREAD

**Issue by priseborough** [PX4/Firmware#9137]
SITL testing using master at commit 7830d35 and with the magnetometer data rotated 90 degrees in yaw inside the ekf2_main.cpp file has show that although the post takeoff failsafe transition into land mode occurs as expected, the vehicle does not disarm automatically after landing. If landing is commanded from the console it does disarm.

Detected during testing of https://github.com/PX4/Firmware/pull/8771

Log file here: https://logs.px4.io/plot_app?log=92090f9f-1e16-45ea-879e-8ef535d949ab

**Comment by julianoes** [comment]
I can't read the logfile but I assume that the auto-disarm was not set for the SITL model and therefore it would not auto-disarm. Leaving this closed.
