### ISSUE TITLE
System is arming (or thinks it is arming) even with Critical warnings (specifically "MAG SENSORS INCONSISTENT")

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#9155]
PX4 1.7.3, installed on a Pixracer, using QGC v3.3.0.  The pixracer is sitting on my desk connected to QGC over USB.  I have a valid GPS fix.  I try to Arm and it seems to let me even with the following Critical warnings:

![image](https://user-images.githubusercontent.com/12117027/37870373-286b900a-2f9a-11e8-899c-df73285b022e.png)
![image](https://user-images.githubusercontent.com/12117027/37870636-a02dc7b0-2fa0-11e8-9ecb-5f0d4e639795.png)

Is this right?

**Comment by Antiheavy** [comment]
however, once i fixed the compass rotation problem (that was giving the "MAG SENSORS INCONSISTENT" warning), then the system properly prevents arming:
![image](https://user-images.githubusercontent.com/12117027/37870470-b9d6d2a0-2f9c-11e8-9abb-7de54986f459.png)

**Comment by dagar** [comment]
Working on a fix here - https://github.com/PX4/Firmware/tree/pr-commander_preflight

**Comment by taileron** [comment]
I think it´s not so bad to allow arming for stabilized flights and reject only e.g. auto mission or rtl that is directly dependant to the sensor´s errors

**Comment by dagar** [comment]
@taileron I agree, but it needs to be done explicitly and I'm not entirely sure how we'd want to go about that.

Some of these requirements we could determine from the system configuration. For example if the user has and RC or data link loss failsafe configured for RTL then at arming time the system could require a valid global position estimate and valid home position.

**Comment by taileron** [comment]
@dagar some errors disappear when the fc runs a minute but mostly it is necessary to reboot the system to get rid of conditions that could prevent arming.
so what´s about to have the possibility or do it automatic: repeat the preflight check after 40 ... 120 sec when temperatures and reference voltages are more stable and more gps satellites than directly after boot, deleting all previous preflight errors + nsh "commander check" with current sensor values
