### ISSUE TITLE
Bottle_drop not working in v1.5.4

### ISSUE THREAD

**Issue by myeabhishek** [PX4/Firmware#9170]
Hi Team,

I am not able to make bottle_drop work in v1.5.4. I think the issue is with setting the mixer file. Can someone please guide me on how to set the mixer in this particular version? 

I know how to set the mixer with newer version but unfortunately that approach isn't working.

**Comment by LorenzMeier** [comment]
Support for the old outback challenge code has been phased out. This is not an issue but an informed decision of the maintenance team.

**Comment by hamishwillee** [comment]
@LorenzMeier Should the source then be removed from the tree? https://github.com/PX4/Firmware/tree/master/src/examples/bottle_drop

**Comment by myeabhishek** [comment]
I am not able to set the mixer for actuator_control_group2 in v1.5.4. I am able to get it to work in newer versions. Can someone help me with that?
