### ISSUE TITLE
Feature Request: Display VTOL status (MC, Transition, FW) on QGC

### ISSUE THREAD

**Issue by jingego** [PX4/Firmware#9188]
is it possible to have the QGC displaying the VTOL status(MC, in Transition, FW)? I think this is crucial to have a successful flight of VTOL, especially for tail-sitter.

**Comment by dagar** [comment]
This is already implemented in newer QGC. https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html

**Comment by jingego** [comment]
@dagar is there any documentation to know how to display the VTOL status in Fly view? I upgrade the QGC but can not find. 
do you mean use analyze to watch EXTENDED_SYS_STATE?

**Comment by dagar** [comment]
It will be in the top bar next to armed. I can send you a screenshot later if needed.

**Comment by jingego** [comment]
got it! I will try it tomorrow~many thanks!
