### ISSUE TITLE
PX4 Ping Message Protocol

### ISSUE THREAD

**Issue by weiminshen99** [PX4/Firmware#9233]
Inspired by #6721, has someone implemented the complete PING protocol among PX4s and QGC? The current code does only a part of the job: https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1718-L1728

According to the spec in http://mavlink.org/messages/common#PING, a ping message should be either requesting or responding to a ping. This allows to measure the system latencies, including serial port, radio modem and UDP connections. It is particularly useful when multiple UAVs and PX4s are flying in a swarm formation. Given the fact that more and more people are interested in multiple-UAVs, could someone please take the lead and implement the complete protocol? Thank you very much in advance!

**Comment by dagar** [comment]
Don't this just need the time and sequence filled in before broadcast?

**Comment by mhkabir** [comment]
Yep. And a way to expose ping stats via `mavlink status`. 

I already have a working branch for this. Let me share it via a PR after some cleanup.

**Comment by weiminshen99** [comment]
Hi, @mhkabir,
Thank you and that is great! I see you already made some enhancement milestones.
I do have a question about this protocol. According to the spec, which says that the target_system is "0: request ping from all receiving systems, if greater than 0: message is a ping response and number is the system id of the requesting system". If this is the only thing it does, then how do people ping from one particular UAV to another particular UAV?

**Comment by mhkabir** [comment]
You can send a PING message with 0 and then check the returned PING for the sysid of the UAV you are interested in.

**Comment by weiminshen99** [comment]
I see. Thanks!

**Comment by mhkabir** [comment]
WIP branch is here : https://github.com/PX4/Firmware/tree/pr-ping-protocol. QGC does not seem to respond to pings, so I need help on that side to add support for returning pings. 

@DonLakeFlyer How hard would it be to add a PING response functionality in QGC?

**Comment by dagar** [comment]
Implemented.
