### ISSUE TITLE
[Question] How to customize/control battery power in simulation

### ISSUE THREAD

**Issue by DuongHieuMAI** [PX4/Firmware#9249]
**Question** 
Hello guys,

I wonder if there were any ways to customize/control the battery in simulation.
My situation :    
    - First download toolchain :https://raw.githubusercontent.com/PX4/Devguide/master/build_scripts/ubuntu_sim_common_deps.sh
    - Then run it: source ubuntu_sim_common_deps.sh
    - Using **jmavsim** by running: make posix_sitl_default jmavsim in ~/src/Firmware 
    - Run **QGroundcontrol** from: https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/master/QGroundControl.AppImage

But during the flight, battery power goes down to 51% and stop there. No more decreasing at all.
Could you please tell me how to change this value or control/customize battery power in this case?
I have to modify in QGroundControl parameters or make changes in Firmware source?

Thank you very much,
Wish you all the best

**Comment by hamishwillee** [comment]
The best place to ask this question is either the discussion forum or slack: https://dev.px4.io/en/#support

Feel free to cross post the answer here though, and I can get the documentation updated.
