### ISSUE TITLE
Bug Report:Compiled code error

### ISSUE THREAD

**Issue by BreederBai** [PX4/Firmware#9250]
When I compile the latest source code to generate V2 firmware, the following error occurs.How can I solve this problem, or that the latest source code no longer supports V2 firmware?
![image](https://user-images.githubusercontent.com/27894314/38400994-9d7c08ee-3985-11e8-836c-f737a473403b.png)

**Comment by hamishwillee** [comment]
Use the supported version of the compiler - https://dev.px4.io/en/setup/dev_env_linux_ubuntu.html#nuttx-based-hardware
