### ISSUE TITLE
Low Battery Alarm Visual / Audio Feedback Not Working

### ISSUE THREAD

**Issue by blu006** [PX4/Firmware#9252]
The logs show that a low battery alarm was active, but I didn't get any indication of low battery when using only visual / audio feedback.  (I don't have a telemetry module)

Here is a log with the battery warning:
https://logs.px4.io/plot_app?log=1161c3da-e394-40af-8425-edb0d2ad09d7

Here is the log after I flew the model with the same battery a second time without noticing that the battery was low:
https://logs.px4.io/plot_app?log=39612523-88fd-41b1-8b7e-0c96d29536c7

I can also provide a youtube video if necessary -- I don't really want to show my face to the public.

**Comment by santiago3dr** [comment]
I beleive this has been addressed in 1.7.4 beta for a while now
https://github.com/PX4/Firmware/issues/8983

low battery alarm is audible on the pixracer (v4), should also be working on v2 baords
