### ISSUE TITLE
When quadrotor moves horizontally,  the quadrotor drops continuously until touching the ground.

### ISSUE THREAD

**Issue by newmsg** [PX4/Firmware#9265]
Hello, I bought a pixhawk2 from taobao.com, and I use it to assemble a quadrotor. And I updated the latest firmware.
But when I use RC to control the quadrotor moving horizontally, the quadrotor drops continuously until touching the ground! 
If I pull up throttle simultaneously, the quadrotor would not drop.

Does anyone have an idea to fix this problem? 
I think maybe we should compensate the change of barometric pressure when quadrotors move horizontally to fix the problem.

**Comment by bresch** [comment]
@newmsg In which mode are you? Altitude? Position?
If you're not in those modes, then it's normal.

Please provide a log file and reopen this issue in you want more help.
