### ISSUE TITLE
A New External IMU Containing ADI Sensors Has Been Released to Support PX4 Firmware

### ISSUE THREAD

**Issue by zarathustr** [PX4/Firmware#9297]
Hi Guys!

Recently we released one new external IMU with ADI analog inertial sensors in China. The sensor readouts are sampled synchronously at 10KHz via an onboard ADC. Later processing like calibration of temperature drift, biases, misalignments, factors has been conducted in-factory. The current price now is 1999 RMB (317.7707 USD) for basic version and 2999 RMB (476.7355 USD) for medium version. The advanced version will be released soon which contains onboard INS/GPS/Baro/Vision fusion supporting more robust navigation for flights.

We are happy that the PX4 team welcomes the new product and we will upload the open-source driver of the IMU soon. The code reads the IMU at the frequency of 1000Hz via the SPI connection with software CRC support according to relatively long-range transmission. The IMU has been tested to be much more effective than low-grade ones like MPU6000, ICM-20689 and etc. on the real-world electronic or gasoline quadrotors, where the mechanical jitters are quite distinct. It has also been tested with a 10-meter-wide fixed-wing plane for long-endurance flight.

The English version website is now under construction and anyone who interested can contact me directly or turn to Jinger Zeng for further acquisition. Thanks!

**Comment by LorenzMeier** [comment]
Looking forward to it!

**Comment by zarathustr** [comment]
The flight experience has been improved. As is known, the Pixhawk, Pixhawk 3 Pro and Pixhawk 4 all have onboard external SPI connector. The IMU is applied to these platforms with sampling frequency of 1000Hz. 

The following is a typical sampling via the PX4 with 3 ADXRS620 gyros
![image](https://user-images.githubusercontent.com/15649421/39091429-63c8a5be-4626-11e8-92d7-e4b79014cbee.png)

With the onboard MPU6000 and external IMU, two test flights have been conducted. For the first one, the MPU6000 is used for computing attitude. The control performances are shown as follows:

![image](https://user-images.githubusercontent.com/15649421/39091497-9d24107c-4627-11e8-9a9e-c1fe2e4caa8a.png)

![image](https://user-images.githubusercontent.com/15649421/39091499-a6edec0e-4627-11e8-9923-2ba42b94c53b.png)

![image](https://user-images.githubusercontent.com/15649421/39091503-af37bd4a-4627-11e8-8a17-1461c09b475a.png)

![image](https://user-images.githubusercontent.com/15649421/39091505-b70323b6-4627-11e8-9c38-42cf754dd97c.png)

**While for the external IMU, the performances are:**

![image](https://user-images.githubusercontent.com/15649421/39091514-e9205314-4627-11e8-87c1-4f53345cb7ab.png)

![image](https://user-images.githubusercontent.com/15649421/39091521-f7968756-4627-11e8-864b-5bc8994c46a3.png)

![image](https://user-images.githubusercontent.com/15649421/39091524-02aaabe0-4628-11e8-83d2-3d4c4777b12c.png)

![image](https://user-images.githubusercontent.com/15649421/39091527-09ee2b02-4628-11e8-94c4-8201c2de82d6.png)

Note that here during the two flights, the parameters are default and the quadrotor is operated at the same position so the comparison is fair. It is obvious that the attitude rates control using ADI IMU is better which leads to better controlling behaviour on the roll and pitch. The basic version containing 3 ADXRS620 gyros and two ADXL203 accelerometers will be priced at 1999 RMB (317.7707 USD) while for the medium version it would be 2999 RMB (476.7355 USD) which replaces the yaw gyro with ADXRS642. **All the sensors have been factory calibrated** including factors, misalignment, biases and temperature drift. We hope that this is going to improve the flight experience in the future!

PS: The test PX4 ulog files can be downloaded on: [website](https://github.com/zarathustr/ext_imu_test)

**Comment by julianoes** [comment]
Please re-open if something needs to be done here.
