### ISSUE TITLE
Mistype of the description for the parameter VT_FW_ALT_ERR

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/Firmware#9314]
The description for the parameter VT_FW_ALT_ERR, displayed in QGroundControl, has a mistype.
This description comes from PX4 according to a [post](https://github.com/mavlink/qgroundcontrol/issues/6362).
It'd rather to be changed from 'copared' to 'compared'. Thanks!

Environments:
PX4 v1.7.3 in Pixhakw2.1, QGroundControl v3.3.1

**Comment by hamishwillee** [comment]
Hi @bigbellmercy , that's right. You can always just search for and edit the parameter in master branch and submit a PR to fix.

I've done that in https://github.com/PX4/Firmware/pull/9315

**Comment by bigbellmercy** [comment]
Hi~ @hamishwillee, I'd try it in later chance. Thanks!
