### ISSUE TITLE
when i make posix_sitl_default jmavsim I meet a problem:

### ISSUE THREAD

**Issue by LLlkaiwen** [PX4/Firmware#9327]
when i make posix_sitl_default jmavsim I meet a problem:

com.jogamp.opengl.GLException: J3D-Renderer-1: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.sw], current: 3.0 (Compat profile, compat[ES2], FBO, software) - 3.0 Mesa 17.2.8

so how can i sovle it

**Comment by hamishwillee** [comment]
This issue occurs if you try run jMAVSim in a VM (virtualbox or VMWare). @dagar - told you it was a P.I.T.A.

**Comment by hamishwillee** [comment]
But it might be caused by something that has been introduced in the VM or in the Ubuntu image. This used to work, but I just tried older tag 1.7.1 and found the same failure.
