### ISSUE TITLE
gamepad wishlist

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#9329]
- throttle allow mapping full range [-1, 1] (cars, etc)
 - ideally VTOL transition should toggle from one state to the other
 - arm/disarm require at least 1 second

More advanced configuration
 - allow mapping throttle to other buttons as a +-% change, which frees up the stick for gimbal use

**Comment by dagar** [comment]
@RomanBapst @MaEtUgR This obviously doesn't cover everything, but it's a few relatively easy short term fixes. Feel free to extend the list.

**Comment by dagar** [comment]
- show thumbsticks in the Joystick tab
   - this is minor, but would give the user a better idea about what's going on and provide some necessary configuration (how the throttle is handled)

**Comment by dagar** [comment]
This was intended to be a QGC issue, although there will also be a PX4 issue later for different pieces.
https://github.com/mavlink/qgroundcontrol/issues/6367

**Comment by MaEtUgR** [comment]
That went fast. It all sounds useful to me, I can probably work on the [-1,1] problem with the throttle (https://github.com/PX4/Firmware/issues/9331)
