### ISSUE TITLE
Nxphlite - UART4/TELEM2 output starts only when USB connected

### ISSUE THREAD

**Issue by dk7xe** [PX4/Firmware#9335]
**Bug Report**

With PX4 version from April 12th the Mavlink datastream starts on UART4/TELEM2 only in case a second connection is made via USB.
TELEM2 / SYS_COMPANION is set to Normal Telemetry 57600 baud.
![nxphlite_version](https://user-images.githubusercontent.com/3907200/38973752-aa06c320-43a7-11e8-9c26-7fd1cd8c2d45.PNG)

Rolling back to a version from 13th of February solved the issue. At that time no DMA support was implemented.

**Comment by davids5** [comment]
@dk7xe - Please retest on https://github.com/PX4/Firmware/commits/leitwert-nxphlite-serial-dma 7fbca79724b9b4d41f4867c32493bdc3a6e7e043 

If you have a radio connected. Ensure you pull down Pin 5 on the radio and P10-4 on the FMU. Observe the LED if it is solid red the radio is in bootload mode.

**Comment by davids5** [comment]
This was resolved with the serial and usb int storm fixes.
