### ISSUE TITLE
Virtual Joystick issue in HITL Simulation

### ISSUE THREAD

**Issue by barzanisar** [PX4/Firmware#9346]
Issue 1) I am using Pixracer in HITL. I followed instructions on https://dev.px4.io/en/simulation/hitl.html?q  to perform HITL simulation. I wanted to use virtual joystick, which I enabled from Application Settings > General and set COM_RC_IN_MODE parameter to "virtual RC by joystick"

However when I fly in any mode requiring RC input, the vehicle keeps yawing even though my joysticks are centered as shown below:
![image](https://user-images.githubusercontent.com/26625030/39050748-c8b0c9e2-44a6-11e8-993a-faec8700e2cd.png)

Issue 2) When I move the left joystick up/down, the vehicle yaws, whereas moving left joystick right/left , vehicle pitches. For right joystick, up/down is throttle and left/right is roll. This is not the same as normal mode 2 joysticks/ RCs. How can we change this?

I tried both Gazebo and Jmavsim and I tried both the latest master and stable release v1.7.3 of Firmware.

@dagar

**Comment by dagar** [comment]
Do you mean physical (usb) joystick? QGC on screen thumbsticks are also sent over mavlink.

Related - https://github.com/PX4/Firmware/issues/9318

**Comment by barzanisar** [comment]
@dagar I mean QGC on screen thumbsticks

**Comment by thomasgubler** [comment]
I think this might be a QGC issue? @dogmaphobic
