### ISSUE TITLE
Changing EKF2 parameters for handheld testings

### ISSUE THREAD

**Issue by jdiament95** [PX4/Firmware#9351]
I assume that the estimated kalman filter synthesizes sensor measurements with a predictive model of how the quadrotor should behave. Is there a way to tune the filter such that it relies exclusively on sensor data? This would be helpful for handheld testing when the movement of the drone doesn't correspond at all to commands from the RC transmitter.

**Comment by mhkabir** [comment]
The EKF does not use a dynamic model of the vehicle for estimation.
