### ISSUE TITLE
Pixhawk bricked after trying some custom code

### ISSUE THREAD

**Issue by Loic-W** [PX4/Firmware#9366]
Hello !
I was trying to experiment some custom modules on my Pixhawk and when using it, it would sometimes force the Pixhawk to reboot until that time when it bricked it.

When powering it, it is behaving like in the first 10 seconds of this video : https://www.youtube.com/watch?v=wU8Ljm4xp_8

I've tried holding the power switch before powering and then releasing once powered on to reload the firmware from FMU but it doesn't work.

Any advice on how to proceed ?

Thanks in advance for the help !
Loïc

**Comment by Antiheavy** [comment]
Try flashing APM firmware and then try flashing back to PX4 firmware. That trick sometimes works when I “brick” an autopilot.

**Comment by dagar** [comment]
FYI usually the reason that trick works is it completely wipes the parameters.

@Loic-W Try connecting a serial console. https://dev.px4.io/en/debug/system_console.html

**Comment by Loic-W** [comment]
It seems that flashing APM solved the issue. 
I wanted to connect a serial console first but I can't put my hand on my cable ! I'll try next time if it happens again.
Anyway, thanks a lot for your help !
