### ISSUE TITLE
incremental build issue in ROMFS

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#9369]
There's an incremental build issue when removing an aiframe file and also removing the CMakeLists.txt entry, you get:
```
ninja: error: '../../ROMFS/px4fmu_common/init.d/4040_reaper', needed by 'genromfs/px4fmu_common/init.d/rcS', missing and no known rule to make it
```

**Comment by dagar** [comment]
This is actually kind of tricky with cmake being oblivious to the files that are pruned. I'll see what I can come up with.

**Comment by bkueng** [comment]
Should be good with #10011
