### ISSUE TITLE
EKF2 IMU timestamping

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#9371]
@priseborough A question about EKF2 IMU timestamping, why is setIMUData using hrt_absolute_time() instead of the timestamp from the sensors_combined message?

The correct accel/gyro timestamp should be `sensors.timestamp + sensors.<accel/gyro>_timestamp_relative`

https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_main.cpp#L699
https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_main.cpp#L679-L684

Every other measurement is fused w.r.t IMU time, but the "real" IMU timestamp seems to not be propagated correctly.

The IMUSample struct seems to say that the `time_usec` field should be the measurement timestamp :
https://github.com/PX4/ecl/blob/a14434d6dc88384577cf3a0ae0921f8826706c64/EKF/common.h#L100-L106

**Comment by priseborough** [comment]
From memory in the initial implementation the exisiting messages did not have the time stamp information required and I also remember issues on the snapdragon board with the relative time stamp when the new driver framework was first created.

We should correct it as you suggest.

**Comment by CarlOlsson** [comment]
This is still a todo right?

**Comment by dagar** [comment]
How about this? https://github.com/PX4/Firmware/pull/11396

**Comment by dagar** [comment]
Implemented in https://github.com/PX4/Firmware/pull/11396.
