### ISSUE TITLE
Follow-Me broken

### ISSUE THREAD

**Issue by Stifael** [PX4/Firmware#9376]
I am trying to port legacy follow-me into flighttask. However, I was not able to run  follow-me with the legacy code. I am wondering anyway who is using this feature...
I ported now the logic into flighttask (the broken one). I am also not planing on trying to fix it, because I rather prefer to drop it entirely and replace it with a new implementation.

**Comment by hamishwillee** [comment]
@Stifael DroneCore uses this - example code [here](https://docs.dronecore.io/en/examples/follow_me.html) and [guide here](https://docs.dronecore.io/en/guide/follow_me.html).

As you probably already know:
- Only works for MC
- You can't use QGC at the same time as dronecore for followme. As soon as it sees the Follow Me mode on PX4 it starts sending location updates (conflicting with Dronecore). 
- Our example code uses a faked position source that behaves like a real one.

**Comment by Stifael** [comment]
@hamishwillee
I used dronecore to verify the working. About two weeks ago the follow-me at least worked to an extend that the vehicle followed the fake position. However, this is not the case anymore. Would be good if someone else can check it as well

**Comment by Stifael** [comment]
yep, I forgot to close qgc. So it seems to behave the same as before.

**Comment by hamishwillee** [comment]
@Stifael Happy days - sorry, took me this long to get to this. 

Good news, QGC daily build now has a setting to turn off the GCS updates for follow me, so you can use it to observe follow me behaviour: https://github.com/mavlink/qgroundcontrol/pull/6380#issuecomment-385382988
