### ISSUE TITLE
[load_mon] init low on stack!(268 byte left)

### ISSUE THREAD

**Issue by wkyoun** [PX4/Firmware#9389]
@LorenzMeier  @dagar  @mhkabir @priseborough 

PX4 Quadrotor |-
-- | --

Airframe: | DJI Flame Wheel F450Quadrotor x (4011)
-- | --
Hardware: | PX4FMU_V2
Software Version: | 305859f3branch: master
OS Version: | NuttX, v7.22.0
Estimator: | EKF2

https://review.px4.io/plot_app?log=a24cc6ed-4da0-488e-b9de-6194c273dfdd

Would you please let me know what caused the this following warning message and how to fix it?
(We have changed the SD card in order to remove the undesirable dropout)

![default](https://user-images.githubusercontent.com/13333754/39460572-6888078c-4d3f-11e8-96fc-7d1619da5b5d.PNG)

**Comment by bkueng** [comment]
Do you see this repeatedly or just after changing the airframe/configuration?

BTW your setup is extremely noisy (https://review.px4.io/plot_app?log=a24cc6ed-4da0-488e-b9de-6194c273dfdd#Nav-Raw-Acceleration), I'm surprised that this flies.

**Comment by wkyoun** [comment]
@bkueng

Yes, I was trying to implement your commit for second GPS(telem 2)

The following log was the log for the same vehicle.

https://logs.px4.io/plot_app?log=3027489e-bfee-44b4-9dff-97ed295723b3

https://review.px4.io/plot_app?log=9366072f-4c3c-4764-a423-c3af96eed63b

https://review.px4.io/plot_app?log=a33c93f2-b05a-48a4-9cac-4ea56a1688ce

**Comment by bkueng** [comment]
Do you have other local changes?

You can set [CONFIG_USERMAIN_STACKSIZE](https://github.com/PX4/Firmware/blob/master/platforms/nuttx/nuttx-configs/px4fmu-v2/nsh/defconfig#L836) to 2600, then use `make clean` and flash again.

**Comment by wkyoun** [comment]
@bkueng 

Yes, I have implemented local changes.

Do this following warning message influence other module performances?(EKF2 or Control)
```[load_mon] init low on stack!(268 byte left)```

**Comment by bkueng** [comment]
> Do this following warning message influence other module performances?

No, not at all, it's only a warning.

**Comment by v01d** [comment]
I'm getting this same warning periodically.

**Comment by tstellanova** [comment]
I'm consistently getting this with Pixhawk 4 running  v1.8.0, on maybe 25% of reboots. It appears that it is `init` that is running low on stack: 

`top` without low stack warning:
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   3 init                        11439  0.000  2120/ 2484 100 (100)  w:sem  3
```
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   3 init                        12569  0.000  2168/ 2484 100 (100)  w:sem  3
```

`top` with low stack warning:
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   3 init                        12874  0.000  2216/ 2484 100 (100)  w:sem  3
```
This corresponds to the console warning:
`WARN  [load_mon] init low on stack! (268 bytes left)`

I am not changing anything in e.g. init scripts before rebooting.

**Comment by tstellanova** [comment]
Increasing init's stack (`CONFIG_USERMAIN_STACKSIZE`) seems to alleviate the problem, similar to https://github.com/PX4/Firmware/commit/d7580aa676b502b755281a0c7a7e5780b1df9066

**Comment by bigbellmercy** [comment]
In my case, this 'init low on stack!' message happened after changing the airframe from the generic quad x to DJI F330 in PX4 v1.8.2 on Pixhawk2.1.

**Comment by bigbellmercy** [comment]
> Do you have other local changes?
> 
> You can set [CONFIG_USERMAIN_STACKSIZE](https://github.com/PX4/Firmware/blob/master/platforms/nuttx/nuttx-configs/px4fmu-v2/nsh/defconfig#L836) to 2600, then use `make clean` and flash again.

The link above does not exist anymore, so, instead, use the link below:
[CONFIG_USERMAIN_STACKSIZE](https://github.com/PX4/Firmware/blob/f13bbacd5277123d6af2cb5ed21587c220031353/platforms/nuttx/nuttx-configs/px4fmu-v2/nsh/defconfig#L836)

**Comment by dagar** [comment]
This should be resolved on master.
