### ISSUE TITLE
make px3fmu-v2_default failed

### ISSUE THREAD

**Issue by ShawnYimPaul** [PX4/Firmware#9390]
I am new to this and I just  installed ubuntu 16.04 and did something follow devpx4 site and I got problem when running make px4fmu-v2_default, here is the error that I got

[2/623] Building px4io-v2
[1/180] Copying NuttX config px4io-v2 and configuring
FAILED: cd /home/shawn/src/Firmware/build/px4io-v2_default/NuttX/nuttx/tools && /usr/bin/cmake -E copy /home/shawn/src/Firmware/platforms/nuttx/nuttx-configs/px4io-v2/nsh/defconfig /home/shawn/src/Firmware/build/px4io-v2_default/NuttX/nuttx/.config && /usr/bin/cmake -E remove -f /home/shawn/src/Firmware/build/px4io-v2_default/NuttX/nuttx/include/nuttx/config.h && /usr/bin/cmake -E make_directory /home/shawn/src/Firmware/build/px4io-v2_default/NuttX/nuttx/configs/px4io-v2/src && cd /home/shawn/src/Firmware && cp -aRfl platforms/nuttx/nuttx-configs/px4io-v2 build/px4io-v2_default/NuttX/nuttx/configs
/bin/sh: 1: cd: can't cd to /home/shawn/src/Firmware/build/px4io-v2_default/NuttX/nuttx/tools
ninja: build stopped: subcommand failed.
Makefile:153: recipe for target 'px4io-v2_default' failed
make[1]: *** [px4io-v2_default] Error 1
[3/623] Copying NuttX config px4fmu-v2 and configuring
FAILED: cd /home/shawn/src/Firmware/build/px4fmu-v2_default/NuttX/nuttx/tools && /usr/bin/cmake -E copy /home/shawn/src/Firmware/platforms/nuttx/nuttx-configs/px4fmu-v2/nsh/defconfig /home/shawn/src/Firmware/build/px4fmu-v2_default/NuttX/nuttx/.config && /usr/bin/cmake -E remove -f /home/shawn/src/Firmware/build/px4fmu-v2_default/NuttX/nuttx/include/nuttx/config.h && /usr/bin/cmake -E make_directory /home/shawn/src/Firmware/build/px4fmu-v2_default/NuttX/nuttx/configs/px4fmu-v2/src && cd /home/shawn/src/Firmware && cp -aRfl platforms/nuttx/nuttx-configs/px4fmu-v2 build/px4fmu-v2_default/NuttX/nuttx/configs
/bin/sh: 1: cd: can't cd to /home/shawn/src/Firmware/build/px4fmu-v2_default/NuttX/nuttx/tools
FAILED: cd /home/shawn/src/Firmware && make --no-print-directory px4io-v2_default
[3/623] Generating git hash header
FAILED: cd /home/shawn/src/Firmware && /usr/bin/python /home/shawn/src/Firmware/src/lib/version/px_update_git_header.py /home/shawn/src/Firmware/build/px4fmu-v2_default/build_git_version.h > /home/shawn/src/Firmware/build/px4fmu-v2_default/git_header.log
Traceback (most recent call last):
  File "/home/shawn/src/Firmware/src/lib/version/px_update_git_header.py", line 30, in <module>
    cwd='platforms/nuttx/NuttX/nuttx', stderr=subprocess.STDOUT).decode('utf-8').strip().replace("nuttx-","v")
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'describe', '--always', '--tags', '--match', 'nuttx-*', '--dirty']' returned non-zero exit status 128
ninja: build stopped: subcommand failed.
Makefile:153: recipe for target 'px4fmu-v2_default' failed
make: *** [px4fmu-v2_default] Error 1

**Comment by mcsauder** [comment]
Hi @ShawnYimPaul , 

Did you initialize and update your submodules?  
`git submodule update --init --recursive`
Nuttx is a submodule, so it might be that you simply didn't properly initialize prior to trying to build.  Hopefully this helps!

-Mark
