### ISSUE TITLE
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by rahulsharma11** [PX4/Firmware#9409]
Hi, I have just upgrade to Ubuntu18. From then whenever i build the px4 firmware i got the error-
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Is this really due to Ubuntu Upgradation? How can i solve it?
Thanks

**Comment by dagar** [comment]
Yes this is likely Ubuntu updated related.

What are you running exactly? PX4 itself shouldn't be using gtk3, is that from gazebo?

**Comment by rahulsharma11** [comment]
Hi, Its not from gazebo. I am building px4fmu-v2_default.

**Comment by dagar** [comment]
Exactly when do you see the error? Screenshot?

**Comment by dagar** [comment]
Weird. Did you do a fresh install of Ubuntu 18.04 or an upgrade from an older release?

**Comment by rahulsharma11** [comment]
I upgraded from previous 17.10

**Comment by rahulsharma11** [comment]
Hi,
Any suggestion?

**Comment by benVolatiles** [comment]
I get the same error after updating to Ubuntu 18.04 when building our firmware (completely unrelated to PX4) too, so I'd say this is a bug in Ubuntu.

The firmware build is completely unaffected by this nuisance.

**Comment by rahulsharma11** [comment]
Ok. Thanks for the confirmation.

**Comment by imambungo** [comment]
I solved the same issue by adding the following line in `.bashrc` file in my home folder:

    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0

Make sure you have `libgtk3-nocsd.so.0` in `/usr/lib/x86_64-linux-gnu/`
If you didn't have it, try `sudo apt-get install gtk3-nocsd`

**Comment by worstprogrammerCN** [comment]
> I solved the same issue by adding the following line in `.bashrc` file in my home folder:
> 
> ```
> export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0
> ```
> Make sure you have `libgtk3-nocsd.so.0` in `/usr/lib/x86_64-linux-gnu/`
> If you didn't have it, try `sudo apt-get install gtk3-nocsd`

That works for me. Besides, you can run ```find /usr -name libgtk3-nocsd.so.0 -print``` to find it.

**Comment by imambungo** [comment]
Happy to help :blush:

**Comment by neokos90** [comment]
I had the same problem and this solve helped me too. Thanks!

**Comment by wizardion** [comment]
It is helped with me too! Thanks!

**Comment by SPlatten** [comment]
I was running Ubuntu 16.04 in a virtual machine on iMAC, I stupidly updated to 18.04 and now I'm getting these issues, unfortunately none of the fixes I've found so far have helped and I don't have the folder /usr/lib/x86_64-linux-gnu, could this be because I'm on an iMAC ?

**Comment by Bost** [comment]
See also https://github.com/lutris/lutris/issues/905#issuecomment-514185518

**Comment by Syed-Mohammad-Nasir-Hussain** [comment]
There are lot of .bashrc files,which one has to be selected and moreover when trying to edit and save file its saying you dont have access for writing the file
