### ISSUE TITLE
EKF2 with optical flow drifts without flow data

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#9414]
So I have been bench-testing a vehicle with a PX4Flow sensor + EKF2. `EKF2_AID_MASK` is set to fuse Flow and GPS. `EKF2_OF_QMIN` is set to 50.

When the vehicle is on the ground (PX4Flow lens blocked), the position estimate from EKF2 keeps drifting around, even the though the flow module returns 0 `quality` and 0 `integrated_x` and `integrated_y`. Here is a log from boot : https://logs.px4.io/plot_app?log=6628dc88-c567-4796-95a6-f0815ab1a535

Would be great if you could have a look @priseborough @ChristophTobler!

**Comment by priseborough** [comment]
This is by design. Flow is always fused, but if on ground and quality metric is too low, motion compensated flow data is set to zero. See reply in https://github.com/PX4/Firmware/issues/9398.

**Comment by MerlotQ** [comment]
Is the px4flow still being used as an angular compensator? Why not use linear velocities directly to the speed control loop?
