### ISSUE TITLE
when plane disarmed , motor is disarmed ,but rudders are not disarmed

### ISSUE THREAD

**Issue by MikeWellC** [PX4/Firmware#9426]
hi
when plane is disarmed , why rudders are active? 
I don't want this，what can i do ?
thanks!

**Comment by santiago3dr** [comment]
The safety switch enables/disables servo control.
Being able to run servos is important for a ground test prior to arming.

**Comment by LorenzMeier** [comment]
So in other words: If you use the PX4 safety switch on the plane you can disable everything. So no need to change anything.
