### ISSUE TITLE
MC output not started after back-transition

### ISSUE THREAD

**Issue by JohnSnowball** [PX4/Firmware#9437]
**Bug Report**
A standard vtol, mission finished, two points:
1. At the second half of the front-transition, the plane had a big roll angle, maybe at that time, the right side of multicopter motors were dead.
2. After back-transition, multicopter motors not started immediately! It kept low output(PWM1080) for about 8 seconds, then cranshed.
I checked roll/roll-setpoint and lp_vz/lpsp_vz, both setpoints are correct, but control outputs are not as expected. Normally, MC outputs will raise immediately right at the momentof back-transition.
![image](https://user-images.githubusercontent.com/18409502/39733627-3f8b9904-52a6-11e8-94b7-77acd931e4e7.png)

As a result of no output, the plane turned over:
![image](https://user-images.githubusercontent.com/18409502/39733902-68e066a8-52a7-11e8-85e6-7baf531df5fe.png)

Here is the log link:
https://logs.px4.io/plot_app?log=e2a365fa-51d7-4a92-a333-0236be161a6c
T-log file is not good since data-link were lost during flight.

**Comment by RomanBapst** [comment]
@JohnSnowball What was the problem?
