### ISSUE TITLE
PX4 SITL catkin build failing

### ISSUE THREAD

**Issue by jbourne15** [PX4/Firmware#9447]
I am following the instructions from here https://dev.px4.io/en/setup/dev_env_linux.html#gazebo-with-ros but when the script gets to catkin build it throws an error.  I don't know if this is relevant but I had already installed this successfully on the same computer, but after deleting the files and reinstalling I am getting that the catkin build fails.

Here is my log file.
[build.make.000.log](https://github.com/PX4/Firmware/files/1992424/build.make.000.log)

thanks for the help

**Comment by TSC21** [comment]
You need to update your submodules. Try `git submodule update --init --recursive`. Then `catkin clean --all -y` and `catkin build` it again.

**Comment by jbourne15** [comment]
Still getting the same catkin build error (from the src/Firmware directory).

log file:
[build.make.001.log](https://github.com/PX4/Firmware/files/1993794/build.make.001.log)

**Comment by dagar** [comment]
I believe this is fixed ecl side. https://github.com/PX4/ecl/pull/447

**Comment by jbourne15** [comment]
@dagar I am installing this again and I am getting the following errors:

> fatal error: ecl.h: No such file or directory compilation terminated.

> fatal error: geo/geo.h: No such file or directory

Log file:
[build.make.002.log](https://github.com/PX4/Firmware/files/2115358/build.make.002.log)

I have made sure that I have the latest firmware  with the [change](https://github.com/PX4/ecl/pull/447) you mentioned earlier and have ran `git submodule update --init --recursive` and `catkin clean --all -y`.  Thanks for any help.

**Comment by dagar** [comment]
@jbourne15 I don't know why catkin cmake isn't respecting the variable (path to ecl.h). Can you move over to https://github.com/PX4/Firmware/pull/9679 and continue the discussion?
