### ISSUE TITLE
1.8beta  80 (17301632) Mag #0 fail

### ISSUE THREAD

**Issue by jstrebel** [PX4/Firmware#9470]
**Bug Report**
Tried to test 1.8 beta with QGC daily build 05-14 d28323333.
Hardware:
![bildschirmfoto 2018-05-16 um 16 45 55](https://user-images.githubusercontent.com/2244311/40126364-72a23c52-592d-11e8-9a20-a71371ddc08f.jpg)
![bildschirmfoto 2018-05-16 um 16 34 54](https://user-images.githubusercontent.com/2244311/40126365-72cd5202-592d-11e8-9fb6-1d189bd4cf73.jpg)
[system_log_1.8.0 80 (17301632).txt](https://github.com/PX4/Firmware/files/2009714/system_log_1.8.0.80.17301632.txt)

 pixhawk v2, GPS with magentometer ublox NEO-M8N.
Beside the info you see in the attached log file I get in the QGC error window:
(attached two screenshots)
I am willing to help. Just tell me what you need.
Jakob

**Comment by LorenzMeier** [comment]
@jstrebel Could you provide the full log file?

**Comment by bkueng** [comment]
@jstrebel did you see @LorenzMeier 's comment? And can you provide the output of `sensors status`?

**Comment by jstrebel** [comment]
My apology. I missed the questions. I did not start logging. In the meantime I did yesterday some tests using the latest 1.8 beta and the daily built GQC  4.Jun. Have not seen this Message again. I will do some more test probably tomorrow.

**Comment by jstrebel** [comment]
@dagar @bkueng 
Did 3 flights today with the newest 1.8beta. All went ok.
https://review.px4.io/plot_app?log=9cb17ba1-378e-492b-b659-4a82084f17e3
