### ISSUE TITLE
Bug Report: Aberrant Yaw and Loss of Altitude causing Crash

### ISSUE THREAD

**Issue by eliaswaddington** [PX4/Firmware#9475]
**Bug Report**

https://logs.px4.io/plot_app?log=a82e2108-6d41-4f1a-931a-7f14f96c333e

While flying, I encountered the issue in the log above. As I was flying, the vehicle began to yaw anti-clockwise, followed by a loss of power and responsiveness. In the log above, I attempted to switch the vehicle to stabilized mode to give full power to the motors, however it did not save the quadrotor and did some damage to one landing gear. 
This was the second time this type of problem happened. The first (on the same vehicle), I was high enough to recover the 15 meter altitude loss and land safely. 

What I've found so far: At about 9:05, a yaw deviation started and though the angular rate setpoint moved to correct it, the vehicle did not turn in the correct orientation. According to the UAVCAN measured response of the ESCs, the motors were spinning correctly to counter this yaw. 

What caused this? Was it as simple as not having enough thrust to stay in the air while yawing? If so, why does the vehicle prioritize yaw heading over maintaining altitude?

**Comment by bresch** [comment]
Hi @eliaswaddington . After looking at the log file, I see that the average hover throttle is ~80%. Your system seems to be highly underpowered (ideally, it should be <60%). This also correlates with the fact that the roll/pitch tracking is bad and I'm not surprised that you can't yaw properly.

If possible, you should first make hardware modifications (stronger propulsion system, lower TOW) before making software changes.

Good luck!
