### ISSUE TITLE
LPE- mocap fused but local_pose not synchronize

### ISSUE THREAD

**Issue by glennliu** [PX4/Firmware#9479]
Hi 

I'm using PX4+Odroid+mavros with Optitrack system. Mocap data is published to PX4 through onboard Odroid Xu4's UART. In my first test, I control the drone manually with mocap data streamed to PX4. local_pose and mocap_pose plot are showed as below,
 
**mocap_x Vs local_pose_x**
![x](https://user-images.githubusercontent.com/8009679/40184215-3fbcf818-5a22-11e8-9fc5-4b4f4c46e155.png)

**mocap_y Vs local_pose_y**
![y](https://user-images.githubusercontent.com/8009679/40184258-56daacac-5a22-11e8-8b07-33e8365629ce.png)

**mocap_z Vs local_pose_z**
![z](https://user-images.githubusercontent.com/8009679/40184268-6063a9cc-5a22-11e8-98a9-ea438fcb7430.png)

 As it shows, local_pose cannot follow mocap_pose data, which means it doesn't receive good estimation. I tried decrease LPE_VIC_P, LPE_VIS_Z to minimum value. LPE_PN_V is increased to maximum value. But it doesn't improve much. However, when drone is static on the ground. local_pose can follow mocap_pose nicely. 
So, my question is how to receive good estimation in flying? 

The main specification are:
Firmware: PX4 1.7.2
Flight controller: MindRacer
LPE_FUSE = 4
Companion link= 921600
Estimator: LPE
Full log attached:
[log_34_2018-5-16-13-13-50.zip](https://github.com/PX4/Firmware/files/2013594/log_34_2018-5-16-13-13-50.zip)

Thanks in advance

**Comment by glennliu** [comment]
Tried to increase mocap steram rate to 60hz. Results didn't change much.
![mocap_60hz](https://user-images.githubusercontent.com/8009679/40214997-8fb8048e-5a90-11e8-975f-e6171abf6b86.png)

**Comment by glennliu** [comment]
I put the drone on the ground static at different position. Local_pose can follow mocap_pose well. It just take a bit long response time.
![static](https://user-images.githubusercontent.com/8009679/40215695-84ad93d4-5a94-11e8-891d-90efc836d6da.png)

**Comment by glennliu** [comment]
Turns out its an wifi issue. Cause I used 5G wifi on Odroid to transmit mocap data.
When I tried ethernet to transmit mocap, results looks correct

![ethernet_mocap](https://user-images.githubusercontent.com/8009679/40275511-786b9b4e-5c23-11e8-9634-f95e845e8a7d.png)

**Comment by jgoppert** [comment]
Seems resolved.
