### ISSUE TITLE
Detected 0 radio channels. To operate PX4, you need at least 5 channels

### ISSUE THREAD

**Issue by cesarengineer** [PX4/Firmware#9480]
I have a pixhawk 3 PRO and have not been able to do RC radio calibration. I get this message "Detected 0 radio channels. To operate PX4, you need at least 5 channels" wondering if this issue has been solved or how it can be fixed? it looks like some kind of HW problem?. Any help will be appreciated thanks.

**Comment by hamishwillee** [comment]
Hi @cesarengineer As per the [reporting issue instructions](https://docs.px4.io/en/#reporting-bugs--issues) best to discuss on the forums first. If it looks like a bug, you'll be directed to post an issue here. 
It is distracting/time wasting to post here - effectively spam.

In addition, if this was to be posted here, you would need to provide a lot more information about your setup - you don't even say what receiver you are using or how it is connected up and powered. It isn't clear what you have tried already - do you know if the receiver and transmitter have been bound together?

I am closing this for now.
