### ISSUE TITLE
Console output on Mac OS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#9495]
@MaEtUgR M
FYI

> Makefile colors do not work e.g. \033[0;34mFormatting with astyle \033[m
> Certain terminal combinations like cygwin - mintty - xterm - bash do not escape colors by default.
> Solution: Force interpretation of backslash escapes with the parameter -e of echo.

This change introduce a new issue in MacOS console:
```
bash-3.2$ make format
-e \033[0;94mFormatting with astyle \033[m
```

PR that introduces this: https://github.com/PX4/Firmware/pull/9441#issuecomment-390569527

**Comment by LorenzMeier** [comment]
Fixed!

**Comment by MaEtUgR** [comment]
@LorenzMeier ok, thanks. Would be interesting how, I don't see any change. Still glad the problem doesn't seem to persist.
