### ISSUE TITLE
OneShot125 wit Hexacopter configuration

### ISSUE THREAD

**Issue by limhyon** [PX4/Firmware#9499]
**Bug Report**

PWM_RATE = 0,
and setup general hexa X configuration.
Motor 5,6 has 5~6usec shorter PWM.
HW = PX4FMU-V4, pixracer.

Can anyone thes this?

**Comment by bkueng** [comment]
I guess it's because motors 5 and 6 are on different timer channels. @davids5 do you know more? Could it be due to timer inaccuracies?

**Comment by davids5** [comment]
One shot is only supported on a quad. This is because chan 1-4 are are one timer and 5-6 are on a separate timer. So synchronization is not possible.
