### ISSUE TITLE
String evaluation problem

### ISSUE THREAD

**Issue by limhyon** [PX4/Firmware#9501]
https://github.com/PX4/Firmware/blob/f09f30586674958801f7724c39f96ac14fc9cab0/ROMFS/px4fmu_common/init.d/rcS#L563

Some text evaluation problem will occur
Should be changed to this x$MAVLINK_F

test with

set MAVLINK_F "-d /dev/ttyS1 -r 20000 -b 921600 -m onboard"

in autostart script.

**Comment by bkueng** [comment]
Yes it should be:
```
if [ "x$MAVLINK_F" == xdefault ]
```

Can you create a PR please?
