### ISSUE TITLE
"make posix_sitl_default gazebo" with error 

### ISSUE THREAD

**Issue by xup682u03** [PX4/Firmware#9502]
I'm trying to use mavros to control PX4 in gazebo under ubuntu mate.
When I try to run "make posix_sitl_default gazebo", it failed everytime.
I google a lot and rebuild the whole system once but it didn't work.

The following is my error message:

![s__6782983](https://user-images.githubusercontent.com/39234690/40351123-3dcc1e52-5dde-11e8-9d60-089bf38fc99f.jpg)

![s__6782982](https://user-images.githubusercontent.com/39234690/40351137-476e8580-5dde-11e8-89ec-002a1e8af055.jpg)
 

It confused me for a long while.
Thanks in advance.

**Comment by hamishwillee** [comment]
Are you on a Ubuntu machine or within a virtual environment?

Is this current master Firmware?

Did you run one of the scripts here https://dev.px4.io/en/setup/dev_env_linux.html to set up your developer environment?

**Comment by LorenzMeier** [comment]
I'm closing this since the system `gz` program segfaulted. This has nothing to do with PX4 or the toolchain but is a Linux installation issue. Please install the latest Linux updates or updated version.

**Comment by xup682u03** [comment]
@hamishwillee 
Oops, forgot to mention.
I'm using ubuntu on RPI3. 
I will set up the developer environment and report the result. thanks.

**Comment by xup682u03** [comment]
@LorenzMeier 
Hi, thanks for reply.
Do you mean `sudo apt-get update`?

**Comment by xup682u03** [comment]
@hamishwillee 
Hi, this is the latest situation after `source ubuntu_sim_ros_gazebo.sh`.

![111](https://user-images.githubusercontent.com/39234690/40425809-03a612c0-5ecc-11e8-9e4d-d17760162d52.jpg)


Error in `gz': double free or corruption (out):  0x014ec748 ***
![222](https://user-images.githubusercontent.com/39234690/40425813-072abeaa-5ecc-11e8-9d07-f807296c3892.jpg)


ninja: build stopped" subcommand failed. 
Makefile:147 recipe for target 'posix_sitl_default' failed
![333](https://user-images.githubusercontent.com/39234690/40425827-0cc0b176-5ecc-11e8-8fd6-45fcc13fdef6.jpg)

**Comment by TSC21** [comment]
@xup682u03 I don't think it's reasonable to actually run Gazebo in a RPi at all. I do advise you to use it on a standard x86 machine, as you will face obvious problems of performance to run this on a RPi. Closing this now.
