### ISSUE TITLE
Vehicle Setup Tutorials

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#951]
We would need additional vehicle setup tutorials.
http://pixhawk.org/platforms/multicopters/start
http://pixhawk.org/platforms/planes/start

This is part of the core developers roadmap for PX4:
http://pixhawk.org/roadmap

**Comment by LorenzMeier** [comment]
@tumbili need a setup video for copter and plane, some time the week after next week.

**Comment by mhkabir** [comment]
I'm happy to help with this however I can :)

**Comment by LorenzMeier** [comment]
@tumbili here is a rough first idea for the setup tutorial:

SETUP VIDEO:

- Start with a close up scene showing the autopilot box content, explain where front is, where the front of the GPS is and that the orientation matters
- Switch to a plane with everything mounted and notebook and person in the view. Go through the airframe config (switching between full-size screen capture and video as well as picture-in-picture)
- Show the same for a quad
- Do the RC config, sensor config. Explain the steps and the caveats
- Finally switch to a view showing operator and plane and explain how to cross-check all travel directions of all elevons, still indoors
- Blend to a view showing the quad outdoors and a careful hover test

FLIGHT VIDEO:

- Move to the flying field, show the operator, perform some pre-flight checks
- Explain the behaviour of the different flight modes and how to test them
- Explain what will happen on multicopter and plane takeoff
- Take off in ALTCTL with both, show FPV footage from both, switch to the same mission in auto and comment the behaviour

PLATFORM INTEGRATION VIDEO

- PID block diagrams explained
- Explain tuning strategy
- Explain optional sensors

**Comment by LorenzMeier** [comment]
@DonLakeFlyer @dogmaphobic Any comments? Our ambition is to do fine without video, but a very basic intuition will be required.

**Comment by DonLakeFlyer** [comment]
The one last thing which can be confusing with fixed wing is setting trims. You need to do it right from the first step to get it right:
1) Zero all trims and sub-trims prior to RC Cal. Do the best you can to level surfaces using pushrod adjustment but not trim/sub-trim.
2) Fly in manual and adjust trims to level flight.
3) Land
4) Go back to RC Cal. Click the Copy trims.
5) At this point I’m no sure what to do? Do you now zero out your radio trims again?

**Comment by LorenzMeier** [comment]
I'm calling this "done" within the scope of a minimum viable product state with this video:
https://www.youtube.com/watch?v=91VGmdSlbo4

Obviously we need more of those, but this is what I wanted to get people going.
