### ISSUE TITLE
Wrong Voltage Divider for FMUv5

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#9526]
On FMUv5 the default voltage divider is 10.133333333f (via `BOARD_BATTERY1_V_DIV`), which is correct when using it with a Pixracer Power Board, but it's incorrect when using the provided Power Module. In that case it needs to be around 18.2.

I did not check the current, but it's likely wrong too.

**Comment by LorenzMeier** [comment]
After investigating the maximum voltage we can support with this divider I believe the current spec on FMUv5 is too limited and we need to go to a higher default divider to support 12S setups.

@bkueng Could you please change the divider to the correct value for the supplied power module and make sure we update our documentation accordingly?

Thanks!
