### ISSUE TITLE
fmu_v5 NSH some commands force an instant reboot

### ISSUE THREAD

**Issue by ryanjAA** [PX4/Firmware#9532]
Certain NSH commands via QGC on Master and Beta send it to an instant reboot.

For instance ver all works fine, tests all, etc but any of the airspeed commands send it to a reboot. Plugged in directly via usb only and only one airspeed (sdp3x) at a time plugged in (to i2c a). Even with no airspeed plugged in it does the same thing, reboots.

**Comment by dagar** [comment]
@DanielePettenuzzo any ideas? All currently supported differential pressure sensors (airspeed) are i2c.

**Comment by ryanjAA** [comment]
I am wrong, that command doent reboot it but it also wont let the sdp3x start.

**Comment by DanielePettenuzzo** [comment]
@ryanjAA if you connect the sensor to i2c-a and start the driver what message do you get on the console?
sdp3x_airspeed start -b 4

**Comment by ryanjAA** [comment]
Two firmware flashs and all set. Maybe something lingering from whatever firmware was sent over on it? I was playing with some can units but it’s working now. If it happens again I won’t reflash. I’ll keeep it and figure out why if it sticks but so far have several airspeed units working.

**Comment by ryanjAA** [comment]
So I guess to close this then it’s the argc checks. Maybe we should get that in the docs or add them to all commands.

**Comment by DanielePettenuzzo** [comment]
@ryanjAA for the px4 firmware are you using latest master?

**Comment by ryanjAA** [comment]
@DanielePettenuzzo Yes. Latest master.

**Comment by LorenzMeier** [comment]
@bkueng Sounds like argc handling needs an audit.

**Comment by dagar** [comment]
> @bkueng Sounds like argc handling needs an audit.

The driver boilerplate is all copypasta and would greatly benefit from ModuleBase or similar.

**Comment by ryanjAA** [comment]
@bkueng I am out of the office for at least another week (no Pix 4 with me either) but so far the airspeed tests with no arguments were doing it. The ver command did not but it probably just needs someone to go through each one with out an argument to see what happens if no other way to check. I’m happy to do so but it won’t be possible for a week or so.

**Comment by bkueng** [comment]
@ryanjAA I went through all commands and fixed the ones affected in #9589.

**Comment by garfieldG** [comment]
Hi,

seems like there are some untouched places where the issue isn't handled, such as https://github.com/PX4/Firmware/blob/27e75920bd560b7d8de295db45aba8cf036cd98d/src/drivers/imu/l3gd20/l3gd20.cpp#L1358

**Comment by bkueng** [comment]
@garfieldG right, this driver is not enabled on Pixhawk 4. Fixed in #9647
