### ISSUE TITLE
General support for rover research platform

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#9533]
**Is your feature request related to a problem? Please describe.**
There is initial support for Rover in PX4 but it needs further polishing and integration. It would be great to have a polished, well-documented setup that suits basic research purposes.

**Describe the solution you'd like**
A complete airframe config for rovers, including a full CI integration tests.

**Additional context**
PX4 can create great value for this application and we need to make it more accessible.

**Comment by zlite** [comment]
Sign me up for this one, too

**Comment by dagar** [comment]
There's been good progress in this area.
