### ISSUE TITLE
FMU LEDs not working properly on Pixhawk 4

### ISSUE THREAD

**Issue by DanielePettenuzzo** [PX4/Firmware#9537]
During boot up Power LED is blinking (GREEN LED) and other two LEDs are off. After booting the Power LED turns off and the ACT LED is on (BLUE LED). When I arm the ACT and B/E LEDS (BLUE and RED LEDS) both start blinking.

I checked in the board config for fmu-v5 and the pins for the three LEDs are assigned correctly, although it seems like these are not used because even if I set them as floating inputs the LED behavior is exactly the same.

**Comment by DanielePettenuzzo** [comment]
FYI @LorenzMeier @bkueng

**Comment by LorenzMeier** [comment]
Fix PR is up.
