### ISSUE TITLE
FW Mission Start - Wheel increases to max deflection (max pwm value)

### ISSUE THREAD

**Issue by ryanjAA** [PX4/Firmware#9540]
When starting a mission the nose wheel servo instantly increases to ~2000 pwm and there is no time to recover (turns much too much) - need to actually decrease max angles at which the servo can turn but this is a new issue. Here are three logs with this occurring several times during each log. I was able to fly the missions due to some manual offsetting of the wheel but if left centered it would not work every time.

Using an fmu_v2 during these tests. Logging is on from boot so there is a lot of nothing prior.

https://review.px4.io/plot_app?log=02711563-1bd4-40ee-8107-16fa14017b9e

https://review.px4.io/plot_app?log=0285460d-d71f-422b-9d55-b42bccc66cbb

https://review.px4.io/plot_app?log=732a5f97-563d-4141-ae9b-c4c8691277af

**Comment by ryanjAA** [comment]
@dagar

**Comment by ryanjAA** [comment]
I’d be interested to know if anyone else has experienced anything similar.

**Comment by LorenzMeier** [comment]
@ryanjAA We will resolve this within the week as part of the v1.8 sprint.

**Comment by ryanjAA** [comment]
@LorenzMeier great! looking forward to testing when resolved.

**Comment by LorenzMeier** [comment]
@dagar Could you look into this?

**Comment by dagar** [comment]
https://review.px4.io/plot_app?log=0285460d-d71f-422b-9d55-b42bccc66cbb
![image](https://user-images.githubusercontent.com/84712/41189192-d43ebc98-6b97-11e8-9e2f-5536c1e932b1.png)

@ryanjAA can you try setting FW_W_RMAX to something reasonable (maybe 30 degrees/s)?

**Comment by ryanjAA** [comment]
@dagar The first log (https://review.px4.io/plot_app?log=02711563-1bd4-40ee-8107-16fa14017b9e) did have FW_W_RMAX set to 30 (see [and](https://review.px4.io/download?log=02711563-1bd4-40ee-8107-16fa14017b9e&type=1) and was changed at minute 35 to 1 and then 0 to see the result (see attached photo) so the wheel issue was occurring when set like that (at 30). Only changing it to something unlimited (0) was enabling the post manual offset of the servo linkage to then correct for takeoff but this was very much happening at the 30 deg/s. The following logs are flights after the this initial one and show that even when setting to some other number, it is still present.

![bokeh_plot](https://user-images.githubusercontent.com/31726584/41191829-d45cf23a-6bba-11e8-9060-edd8021c3915.png)

**Comment by ryanjAA** [comment]
Flew master today and all was fine. 

https://review.px4.io/plot_app?log=e6d82fe3-9b3b-4f4b-b8c6-5af1e930e1a9
