### ISSUE TITLE
Tighten GPS fix check

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#9549]
**Describe the bug**
The u-blox M8N module over-estimates its accuracy in a multipath or indoor setups.

**To Reproduce**
Run a u-blox M8 inside a house and observe the reported accuracy. 

**Expected behavior**
We need a way to distinguish good reception on a plain field from bad reception inside a house.

**Log Files and Screenshots**

Log file is at the home of the user, so not suitable to share publicly.

<img width="818" alt="screen shot 2018-05-28 at 12 37 51" src="https://user-images.githubusercontent.com/1208119/40610781-0791c3ba-6274-11e8-931a-79446f31778a.png">

<img width="808" alt="screen shot 2018-05-28 at 12 38 00" src="https://user-images.githubusercontent.com/1208119/40610795-0f16d33c-6274-11e8-8b1d-6b70fb3223e4.png">

Here is what we use so far to infer if the fix is good enough:
https://github.com/PX4/GpsDrivers/blob/master/src/ubx.cpp#L984

**Comment by priseborough** [comment]
We have a range of EKF internal checks that that can be tightened or enabled. See EKF2_GPS_CHECK parameter which is a bitmask that enables the various checks and the various EKF2_REQ_* parameters that control the check thresholds. 

Some of those checks such as EKF2_REQ_HDRIFT, EKF2_REQ_VDRIFT are not enabled by default because they require the vehicle to be static, but can detect a bad GPS solution independent of the accuracy reported by the receiver.

There are also a number of GPs quality metrics which are reported by the UBlox receiver that we don't use.

**Comment by thomasgubler** [comment]
TODO: produce log to be able to tune this. E.g. sport center/gymnasium,warehouse

**Comment by RomanBapst** [comment]
I've seen similar behavior when hovering under a tree with both gps and optical flow enabled. In that case the drone drifted around quite a bit and I had to interact. With just optical flow enabled it was rock solid.

**Comment by RomanBapst** [comment]
@priseborough @thomasgubler I will produce a replay log hovering under that tree. It has a thick, green canopy.

**Comment by RomanBapst** [comment]
@priseborough Here is a replay log of me flying under a tree. The vehicle was actually armed under the tree directly. As you can see on the map from flight review the gps initialised a fair distance away from the tree and then converged to the correct position. When I took off in position control mode the drone started drifting towards the stem immediately and I had to correct via the RC. After a while it stabilized a bit but the horizontal drift was still much bigger than with only optical flow enabled.
https://logs.px4.io/plot_app?log=61bd525d-8527-452a-856c-a8d1ace144bf

**Comment by priseborough** [comment]
I've started experimenting with the exisiting preflight GPS checks supported by ekf2 and the filtered position drift levels checked by setting EKF2_GPS_CHECK to 53 were fluctuating between 0.15 and 0.3 m/s. The threshold value controlled by EKF2_REQ_HDRIFT is currently defaulted to 0.3 m/s, but could be reduced to 0.1 m/s. Other parameters that could be changed include:

EKF2_REQ_EPH 5.0 -> 3.0
EKF2_REQ_EPV 8.0 -> 5.0
EKF2_REQ_SACC 1.0 -> 0.5

To prevent the EKF2_REQ_HDRIFT check frustrating users, it will need to be modified to temporarily suspend calculation of the  position derivative when the vehicle is picked up and carried.

**Comment by thomasgubler** [comment]
Depending on merge of: https://github.com/PX4/Firmware/pull/9999
