### ISSUE TITLE
Help, I dont know how to debug LPE

### ISSUE THREAD

**Issue by zungam** [PX4/Firmware#9560]
Hello, this is not a bug, Im a newbie and Ive scanned the internet for documentation, but I cant find it, so this is the last place I go for help. Please help.

I am trying to use an external position system (visual odometry) for vision in my SITL using LPE as fuser and Dronekit for communication. I just want to debug the LPE fuser, but I dont know where to do it. I need to check if the PX4 actually receives my position or not. My debug approach so far, has been to see if I get the drone to fall over by spamming the SITL with very noisy vision data using Mavlink-VISION_POSITION_ESTIMATE-messages, but the drone seem to be really stable. I think it is getting nice GPS signals, and sticking to it. So there is no way for me to tell if SITL really receives my vision position or not.

Im using Airsim. 

My params:
LPE_FUSION to only gps and land detector.
LPE_VIS_XY to 0.01
LPE_VIS_Z to 0.01
ATT_EXT_HDG_M 1

So, how can I get the px4 SITL console to print out the VISION position before it gets fused into LPE?

**Update:**
I ment to say I set LPE_FUSION to only gps, land detector and _vision_.
Im using LPE because I read that EKF2 is not supporting vision. Is that right?

**Comment by hamishwillee** [comment]
@zungam I don't know the answer to your question, but is there any reason you can't use EKF2 instead of LPE? EKF is the default estimator, and the answers for questions are therefore easier to find. I'd also be considering DroneCore over DroneKit for working with PX4, if only because if you have a problem with DroneCore on PX4 there is active support. 

The best place to ask questions like this are listed here: https://docs.px4.io/en/#support

**Comment by TSC21** [comment]
@zungam after reading your explanation I ended up not understanding what are you trying to debug in the end. You want to check if the flight controller is receiving `VISION_POSITION_ESTIMATE`, right? But then, you just set the `LPE_FUSION` to fuse GPS and the Land Detector only. So, do you want to evaluate the vision fusion or not? If yes, you need to set the bitmask index 2 also.
Currently, by default, the `VISION_POSITION_ESTIMATE` msgs are published in a loopback, so you just have to open QGC and check the Mavlink Inspector.

**Comment by zungam** [comment]
@hamishwillee Im using LPE because i read around that EKF2 doesnt support vision fusion at this point? Is this true, or has it been updated? Thanks for the advice on DroneCore, I will switch to it!

@TSC21, Im so sorry I forgot to write that I set LPE_FUSION to vision. 
I will try to open QGC and check the Mavlink Inspector, I had no clue where to look, so thankyou

**Comment by LorenzMeier** [comment]
The information on EKF2 is outdated - do we have outdated documentation somewhere.

**Comment by hamishwillee** [comment]
@zungam Can you please tell me where it said that EKF2 doesnt support vision fusion? If it is in our docs I can correct that. 

The docs on EKF that say we do support optical flow are https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.html#optical-flow and https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.html#external-vision-system

@LorenzMeier There is a bigger hole here, which I will need some help to patch: https://github.com/PX4/px4_user_guide/issues/251

**Comment by zungam** [comment]
@hamishwillee, why do you think the DroneCore [docs`](https://docs.dronecore.io/en/getting_started/faq.html) says that indoor is not supported? I understand that GPS is required, however does DroneCore support sending VISION_POSITION_ESTIMATE messages?

**Comment by TSC21** [comment]
> @hamishwillee, why do you think the DroneCore docs` says that indoor is not supported? I understand that GPS is required, however does DroneCore support sending VISION_POSITION_ESTIMATE messages?

It's not supported yet. But there's an opened issue already for it: https://github.com/dronecore/DroneCore/issues/32.

**Comment by zungam** [comment]
I believe I got this to work! I switched to EKF2 as you recomended,
Set parameter EKF2_AID_MASK to vision position fusion, vision yaw fusion,
and EKF2_HDG_MODE to Vision,
Dronekit:
msg = vehicle.message_factory.vision_position_estimate_encode(dt.microsecond, x, y, z, roll, pitch, yaw)
vehicle.send_mavlink(msg)
dit it! Now it receives the positions and I can control the drone with vision :) Thanks people

**Comment by TSC21** [comment]
@zungam it should work also with LPE also. Did you tried it also?

**Comment by hamishwillee** [comment]
> @zungam it should work also with LPE. Did you tried it also?

@TSC21 He did, but we pushed him to EKF2, because IMO the documentation is clearer, and as the default estimator there is better support.

**Comment by TSC21** [comment]
That's reasonable. I should look into document better LPE then.

**Comment by hamishwillee** [comment]
>> @hamishwillee, why do you think the DroneCore docs` says that indoor is not supported? I understand that GPS is required, however does DroneCore support sending VISION_POSITION_ESTIMATE messages?

> It's not supported yet. But there's an opened issue already for it: dronecore/DroneCore#32.

Yes. The reason is that we haven't done any testing on it, or put effort into supporting it. There may be health checks to ensure that we have a decent GPS signal - rather than checking we have a valid position estimate.
So this will come at some point and probably could work fairly easily, but it isn't our first priority.

> I believe I got this to work!

Great. That is one benefit of DroneKit - the ability to send custom messages. DroneCore is by contrast a much more controlled API, with deliberately less flexibility/customisation in the front end (there are good reasons for this).

**Comment by hamishwillee** [comment]
> @zungam  By the way, I would update your docs on how to debug with SITL, giving a tutorial on how to print out positions in real time or something, because its not very clear. (ref)

Me too. If you can highlight specific issues or create a document I am happy to test and integrate it.

**Comment by hamishwillee** [comment]
Can we close this?
