### ISSUE TITLE
MAV_CMD_SET_MESSAGE_INTERVAL.param2 = 0 stops stream instead of reset to default

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#9561]
I'm testing using SITL and firmware master. For the new QGC PID tuning support I speed up the rates for MAVLINK_MSG_ID_ATTITUDE and MAVLINK_MSG_ID_ATTITUDE_TARGET using the MAV_CMD_SET_MESSAGE_INTERVAL command. When I up the rates it works. But when I want to reset the rates back to default they instead fall to a rate of 0.

**Comment by DonLakeFlyer** [comment]
From MavlinkReceiver::set_message_interval(int msgId, float interval, int data_rate)
```
	} else {
		// note: mavlink spec says rate == 0 is requesting a default rate but our streams
		// don't publish a default rate so for now let's pick a default rate of zero.
	}
```

Uh, not super useful. Also in looking at the code it is passing something in from param3 which is not in the mavlink spec.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer Please use ATTITUDE_QUATERNION instead because ATTITUDE suffers from gimbal lock and will be deprecated. In terms of other messages: LOCAL_POSITION and the associated _TARGET message will likely be helpful to tune the position controller.

**Comment by DonLakeFlyer** [comment]
> Please use ATTITUDE_QUATERNION instead because ATTITUDE suffers from gimbal lock and will be deprecated.

Got it. QGC code needs a major cleanup and how it uses the various messages which can have attiude information in it: ATTITUDE, ATTITUDE_QUATERNION, VFR_HUD. It's a bit crazy not due to likely back compat for realy really old firmwares.

**Comment by LorenzMeier** [comment]
@bkueng Do you see a quick fix for this?

**Comment by bkueng** [comment]
QGC could use `MAV_CMD_GET_MESSAGE_INTERVAL` beforehand?

Otherwise we could do some refactoring and call https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L2005:L2033 again, but only applied to the requested stream. This would avoid any memory overhead.

**Comment by DonLakeFlyer** [comment]
Would be nice if it worked as spec'ed.
