### ISSUE TITLE
Local Position value detected by GPS was unstable even when not moving 

### ISSUE THREAD

**Issue by b4rryw4ng** [PX4/Firmware#9564]
**Describe the bug**
After carefully calibrate the FCU, flying control unit, and GPS, the local value detected by GPS was terribly unstable, even if we leave it on the ground, the value ranging form 4 to -2 and 0 to -4, the following picture is the screen shot of the Analyze in QGroundControl.
The Drone is controlled through "MAVROS" and the FCU is under offboard mode.
Another Question is that, This few days when we were testing out the drone, the GPS can't calculate the local pose value at all, will this problem be caused by the number of the satellites the GPS detected? Will it be solved if there are more satellites detected by the GPS?

**Expected behavior**
The data would fluctuate in a certain range and be  able to stabilize while flying.

**Log Files and Screenshots**
Screenshot:
https://i.imgur.com/LeNkWVD.png

**Drone (please complete the following information):**
GPS : ublox 7m
Drone: DJI F450

**Comment by ashlynselena** [comment]
@b4rryw4ng Were you able to identify what the problem was? I have a very similar issue
