### ISSUE TITLE
feature request: allow system to show negative airspeed

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#9567]
Currently PX4 does not pass though negative airspeed (or diff pressure?) measurements from the diff pressure sensor module.  This hides potential problems from the users such as:  bad calibration or blocked/pinched or reversed pitot-static lines.  Negative values should be allowed to be sent to the system and ultimately displayed to the user.  These negative values can also be used to detect problems or prevent arming in other parts of the system.

partially related issue: https://github.com/PX4/Firmware/issues/9566

**Comment by Antiheavy** [comment]
@Kjkinney let's ground test this soon.

**Comment by dagar** [comment]
PR https://github.com/PX4/Firmware/pull/9636

**Comment by Antiheavy** [comment]
I think this is working fine in the recent Sentera builds.  I'll close it and we will continue to roll it in as a separate add-on to the sentera builds until it makes it into upstream and we sync.
