### ISSUE TITLE
arming and takeoff with mavros !

### ISSUE THREAD

**Issue by zubair123khan** [PX4/Firmware#9578]
Hello

I am successfully able to launch mavros_posix_sitl.launch, but i am unaware of using mavros command like arming and takeoff. However i tried using rosservice call /mavros/cmd arming and set it to true but its returning me FALSE.
I don't think mavros  launch needs anything else for me to use service call for arming and takeoff.

please guide me on how can i arm and takeoff my iris in gazebo.

Thanks

**Comment by TSC21** [comment]
`rosrun mavros mavsafety arm`
`rosrun mavros mavcmd takeoff 0 0 0 0 5` (being 5 the altitude)

**Comment by zubair123khan** [comment]
Hi 
Thanks for the comment, although I tried these rosrun and it's showing up request failed

**Comment by TSC21** [comment]
So you are probably missing something more fundamental here. Also it's not clear what's your current framework (meaning PX4 Firmware version, etc). Have you tried to launch the SITL simulation without ROS, by issuing `make posix_sitl_default gazebo` and after it opens (and gets a position lock), issue `commander takeoff` on the same window you launched the previous commad?

**Comment by TSC21** [comment]
Please also mark here:
1. your ROS and MAVROS version;
2. you Gazebo version;
Also, try launching QGC and check for the data coming from the vehicle and if there are any log error msgs being reported

**Comment by zubair123khan** [comment]
Did try it , commander take off without ROS is showing no position lock.. I waited for much longer..

**Comment by TSC21** [comment]
> Did try it , commander take off without ROS is showing no position lock.. I waited for much longer..

OK are you able to show us a video/screencapture of the procedure you take to launch the simulation and then the behavior you see on the simulator? Are you using the latest upstream master of PX4 or a recent stable release?

**Comment by zubair123khan** [comment]
This is my console output now without ROS 

-- http://pastebin.com/Hqx4sbxs

**Comment by zubair123khan** [comment]
Here is my screen shot with mavros posix_sitl.launch 

-- http://pasteboard.co/HnN6Yih.png
