### ISSUE TITLE
Preflight Check--Always warning PREFLIGHT Advice/Failure: ACCELS INCONSISTENT - CHECK CAL 

### ISSUE THREAD

**Issue by EVANSONG1220** [PX4/Firmware#9585]
After several flights, px4 always had the warning that I need to check my accelerometers and recalibrate them. The frequency of occurrence is about once a week. Is it normal?  What should I do to avoid this warning?

Sometimes this warning was useful. During this flight, the local vertical velocity had a bias about 0.5m/s. Most of time, even this kind of warning comes out, it doesn't affect my flight performance. How can I tell a difference between a good and bad accelerometer ?
![image](https://user-images.githubusercontent.com/38905757/40902000-0410c06a-6805-11e8-886f-d32b4113d1ef.png)

**Comment by YCH188** [comment]
@EVANSONG1220 Have you solve the problem, I have the same problem.
