### ISSUE TITLE
Support off board commands

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#960]
Offboard roll / pitch / yaw or motor commands seem super popular, but are right now not implemented / enabled. Contributions welcome - please comment if you are willing to work on this and need some guidance in exchange for a pull request for the main project.

Tasks:
- [x] Parse offboard control message in MAVLink
- [x] Accept off board control commands in controller @DrTon 
- [x] Log offboard control messages in sdlog2 app
- [x] Support an auto-arming strategy once these messages are received (e.g. using a circuit breaker, #961)

**Comment by LorenzMeier** [comment]
Probably done when this is done: https://github.com/PX4/Firmware/pull/1983

**Comment by mhkabir** [comment]
Also this : https://github.com/PX4/Firmware/issues/1856

**Comment by LorenzMeier** [comment]
Implemented on master and according to testing currently operational.
