### ISSUE TITLE
Mission starts at closest waypoint

### ISSUE THREAD

**Issue by potaito** [PX4/Firmware#9606]
Behaviour introduced with PR https://github.com/PX4/Firmware/pull/8749.

Opening an issue on @dagar's request.

Description:
1. Takeoff and leave the drone in position hold.
![image1](https://user-images.githubusercontent.com/3762382/40966881-f7b480c4-68b1-11e8-9506-246362cc8d2c.png)

2. Create waypoint mission where some intermediate waypoint is close to the current location.
![image2](https://user-images.githubusercontent.com/3762382/40966937-1a03a8d0-68b2-11e8-9a2b-584ce0f4af44.png)

3. Start mission. The vehicle will jump to the closest waypoint and commence the mission from there, skipping all waypoints before that.
![image3](https://user-images.githubusercontent.com/3762382/40966984-3efca916-68b2-11e8-9bee-16bda4f1a3a4.png)

The changes responsible for this are these two blocks in `mission::on_activation()` and `mission::on_active()`, setting the current waypoint to the closest mission item.

https://github.com/acfloria/Firmware/blob/a70cd4e54567ae774ada1d0197797890c16e717f/src/modules/navigator/mission.cpp#L155-L158

https://github.com/acfloria/Firmware/blob/a70cd4e54567ae774ada1d0197797890c16e717f/src/modules/navigator/mission.cpp#L198-L206

Tested on current master (ca5e22583f9dd81852856a9169523d8135b81db6) with SITL `make posix_sitl_default jmavsim` and default parameters.

**Comment by Antiheavy** [comment]
I agree that for 1.8.0 release this behavior should probably be changed backed to the way it was before for all auto modes except the new RTL_TYPE=2.  However, I think there should be a bigger discussion about if the default mission item handling when uploading a new mission could be improved after 1.8.0.  PX4 resets the mission index to 1 when a new mission is uploaded; this is not how most professional systems have traditionally worked and many users find it frustrating/confusing.  I'd be happy to open a separate "discussion" issue about this for future consideration if people are willing to discuss/debate.

**Comment by LorenzMeier** [comment]
@acfloria @dagar Do you have cycles this weekend to make the change? I really would like to get v1.8 out of the door.

Thanks!

**Comment by LorenzMeier** [comment]
@dagar Any news on this?

**Comment by acfloria** [comment]
I am currently working on it.
