### ISSUE TITLE
unstable PWM out

### ISSUE THREAD

**Issue by jbourne15** [PX4/Firmware#9621]
**Describe the bug**
The pwm signal out goes unstable for a quadcopter at a certain rc input in either manual and stabilized mode. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Drone switched on (no props) and arm in stabilized or manual mode
2. slow increase roll and pitch from rc. Instability appears when roll and pitch at some certain point see figure for example.
3. See error by motor's going unstable and possible stopping due to motor sync.

**Data log**
![pwm_bad_close](https://user-images.githubusercontent.com/10954148/41186265-e18f476a-6b50-11e8-9442-7916fe42551f.jpg)

This figure shows the rc input (channels 0 and 1) and output (channels 0-3). Notice the instability around 98 seconds.  This data was logged through ROS at 50 hz.  

**Drone setup**
- px4 flight stack v1.7.3
- airframe: dji matrice 100 
- [pixhawk 3](https://drotek.com/shop/en/pixhawk-3-pro/821-pixhawk-pro-autopilot.html)
- [MT4004 kv 300](http://store-en.tmotor.com/goods.php?id=438)
- [20A spider esc 2-6cell oneshot125](http://www.michobby.com/product/ztw-spider-pro-premium-20a-hv-opto-2-6s-esc-electronic-speed-control-for-rc-multirotor/)
- let me know if parameters or ROS bag fille would be useful and I'll upload.

**Additional Content**
This problem is repeatable on different pixhawk 3s and different motors.  Also the imu data is stable.

**Comment by LorenzMeier** [comment]
This issue will close automatically in 30 days.

**Comment by jbourne15** [comment]
Here is the log file on Flight Review:
https://logs.px4.io/plot_app?log=4b64b736-0462-47d4-92cc-c93fa8397cf6

Please see the plots: Actuator Outputs (Main) and Actuator Controls 0 around 3:00 for similar behaviour to previous figure.

Also, I can get the same instability through different configurations of roll and pitch.

**Comment by jbourne15** [comment]
Here is another log file of the same quad flying outdoors in offboard mode.  The unstable PWM commands seem to cause the quad to fall out of the sky. Any suggestions?

https://logs.px4.io/plot_app?log=b25b04ae-42d7-452c-a169-47ff13bf8c84

**Comment by jbourne15** [comment]
Downgraded to fw v1.7.2 and the unstable pwm commands still exist. 

here is log: https://logs.px4.io/plot_app?log=6208c07b-0c05-4643-82f9-1429c797c1da

Also I tried arming a pixhawk 3 without any connecting escs/motors and the pwm would eventually go unstable as well.

**Comment by LorenzMeier** [comment]
@jbourne15 It looks like you have an issue due to your gain setup. There seems nothing to be wrong with the system in general, but the specific controller gains you have set on the airframe are an issue. Can you reset to the generic quad config and see what that does?

**Comment by jbourne15** [comment]
@LorenzMeier Ok so I changed the air frame to the Generic Quadrotor x with v1.7.3 firmware, calibrated all the necessary sensors and I am still getting unstable PWM.  Here is the log: https://logs.px4.io/plot_app?log=d18ce47f-b2f2-4572-b53c-e0c47fec00ed

If you notice right before the PWM goes unstable the output signals go down. My guess is that this is due to the integral term building because the quadcopter is just sitting on my desk. 

![bokeh_plot 3](https://user-images.githubusercontent.com/10954148/41362998-0e84db02-6ef0-11e8-9deb-0e0f944f3185.png)

So I turned off all the attitude integral gains but I am still getting unstable PWM, but I have learned that it usually happens at large commands (from the RC) of roll and pitch, I didnt notice this before because of the integral windup.

Here is the log: https://logs.px4.io/plot_app?log=183ff1c7-1a29-4bdc-826d-d6ebc137641c

**Comment by LorenzMeier** [comment]
@jbourne15 Ok, that makes a lot more sense. You're running into the actuator limit handling of the system. If you want to get a nominal response you need to be flying the system. At this level of wound up integrators all bets are off.

**Comment by jbourne15** [comment]
@LorenzMeier  To be clear, are you saying that this error shouldn't happen when I am actually flying and is just a result of me testing on the desk? 

This log shows a flying quadcopter fall due to unstable PWM.
https://logs.px4.io/plot_app?log=b25b04ae-42d7-452c-a169-47ff13bf8c84

Also I am not sure what you mean by "at this level of wound up integrators all bets are off".  In my previous response I zeroed the attitude integrator gains and still got unstable PWM.

thanks

**Comment by jbourne15** [comment]
Just tried this on a Pixhawk 1 with v1.7.3 fw and got unstable PWM.

Here is the log: https://logs.px4.io/plot_app?log=95f86a11-3b13-4dbc-9fd9-e6807c07c927

**Comment by jbourne15** [comment]
@mcsauder thanks for the responds, I ended up uploading to v1.8.0beta firmware and changing to the generic airframe (which I am pretty sure reset the parameters with lower gains for the attitude controllers). Been flying for about a month now and haven't seen this PWM instability issue again.  I am still curious if others can replicate this.
