### ISSUE TITLE
Is the px4 devguide broken?

### ISSUE THREAD

**Issue by cs147** [PX4/Firmware#9662]
This isn't exactly a PX4 firmware bug but just wanted to report it here in case anyone can help fix

dev.px4.io and all associated webpages are down

**Comment by LorenzMeier** [comment]
We switched from Gitbook to Github pages. The website is up.

**Comment by hamishwillee** [comment]
To be very precise we switch hosting from gitbook.com to github pages. The toolchain used is otherwise the same (gitbook client)
