### ISSUE TITLE
Flying with USB connection

### ISSUE THREAD

**Issue by korigod** [PX4/Firmware#9663]
Is it ok to fly with USB-connected companion computer? We used to use UART connection, but it has several disadvantages. The speed is low, also it has less resistance to interference compared to the USB differential pair and it's not possible to flash FMU using the default PX4 bootloader.

So is the `circuit_breaker_engaged_usb_check` introduced to fly with USB or it's only for lab tests and flying with USB is not recommended anyway? What are the disadvantages of flying with USB (except for unsuitable connectors, which can be replaced)? In particular, what is the motivation behind commit 55cf08d by @LorenzMeier?

**Comment by hamishwillee** [comment]
This isn't really a bug, so you should ask it on the [discussion forums](http://dev.px4.io/en/#support)

From the [MAVLInk UART example](https://github.com/mavlink/c_uart_interface_example#hardware-setup):

> Also Note: Using a UART (serial) connection should be preferred over using the USB port for flying systems. The reason being that the driver for the USB port is much more complicated, so the UART is a much more trusted port for flight-critical functions. To learn how this works though the USB port will be fine and instructive."

So I would guess that this will probably work, but if things fall over debugging is going to be much harder.
