### ISSUE TITLE
Gazebo optical flow simulation laggy

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#9666]
It seems like something is creating a lot of load when using the ```gazebo_iris_opt_flow ``` target.
As soon as the drone moves a bit the simulation becomes laggy and freezes for short periods.
Could somebody give this a try on master and see if he/she experiences the same issue?

I'm using Ubuntu 16.04 and I have the NVIDIA proprietary driver activated.

**Comment by TSC21** [comment]
This is mostly because of the uneven ground model. It's computational expensive. It should be changed to something as the asphalt plane.

**Comment by LorenzMeier** [comment]
@thomasgubler @bkueng @dagar This is a v1.8 blocker that needs to be resolved.

**Comment by RomanBapst** [comment]
Fixed by #9675
