### ISSUE TITLE
"[lpe] baro fault, r  negative 9.19  meters, beta  9.35"

### ISSUE THREAD

**Issue by rahulsharma11** [PX4/Firmware#9669]
Hi, While using the latest px4fmu-v3 version with new pixhawk mini. It continously throws the error -
"[lpe] baro fault, r  negative 9.19  meters, beta  9.35"
negative "-" 20 21
"[lpe] baro fault, r  negative 9.28 m, beta  9.55"
meters "m" 35 36
"[lpe] baro fault, r  negative 9.28  meters, beta  9.55"
negative "-" 20 21
"[lpe] baro fault, r  negative 9.47 m, beta  9.94"
meters "m" 35 36
....so on.

sometime it stops by making baro ok but that is unexpected and all of a sudden above erros are being published on the Qground console.

Issue is that whenever i tried to make this on ALT hold, it suddenly drops down.
Don't know why this is happening.
Any suggestion?
Thanks.

**Comment by LorenzMeier** [comment]
Hi - we are not maintaining / supporting LPE any more. Please use EKF2. Thanks!
