### ISSUE TITLE
Store params in fram and changed them using QGC, but they were reset to defaults after restart

### ISSUE THREAD

**Issue by aogrcs** [PX4/Firmware#9683]
Hi
I used fram FM25V01 to store params. And I changed params by QGC, after restart, params were set to defaults. I also tested using console such as param set and param show -c, it did work! Does anyone test this? Thanks!

**Comment by aogrcs** [comment]
I did hardware myself just like PIXRACER, did this cause the problem? Thanks

**Comment by LorenzMeier** [comment]
We have seen fake FRAM parts. This sounds like one.

**Comment by aogrcs** [comment]
It's not the fake one, I used PC6 as spi cs signal, but it was also used for usart6, so I disable it in defconfig, and this did work! Thanks!
