### ISSUE TITLE
a question about run git submodule update --init --recursive

### ISSUE THREAD

**Issue by TomatoAndScallion** [PX4/Firmware#9684]
I have a trouble when I run the order  git submodule update --init --recursive. It display the fallow fatal:
fatal: reference is not a tree: e1c9a4f5064a336295125da25c0542a5cd601dd7
Unable to checkout 'e1c9a4f5064a336295125da25c0542a5cd601dd7' in submodule path 'src/modules/uavcan/libuavcan'.
I don't konw how to solve this problem. Dose some people help me to solve this problem?  Thanks.

**Comment by LorenzMeier** [comment]
Please run `git fetch origin` and `git checkout origin master` and retry.
