### ISSUE TITLE
Poor land detection

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#9696]
@MaEtUgR @bkueng Could you have a look? This is blocking v1.8

A new flight report just got uploaded:
https://review.px4.io/plot_app?log=22cb36a7-2ac1-4cd8-b42c-cea152c7a141

Description: beta18_mc03_pxr(05)
Feedback: take-off in position mode; steady hold; nice tracking; good nav; poor land detection
Rating: Unsatisfactory
Wind Speed: Breeze
Uploader: santiago@3dr.com

Vehicle type: Quadrotor
Airframe: DJI Flame Wheel F450, Quadrotor x
Hardware: PX4FMU_V4
Vehicle UUID: 003200333435510837363434
Software git hash: aa625d9af880e3be7bd2ddd7ed49d10c74c6ada4

**Comment by bkueng** [comment]
@santiago3dr Can you describe what you mean with poor land detection?

**Comment by MaEtUgR** [comment]
The first suspect for any problems with land detection is in my experience the **hover thrust** configuration.
In the log `MPC_THR_HOVER, 0.5` the hover thrust is 50% while the vehicle uses **~38%** to hover in the equilibrium. Not sure from the problem description but it might be that **setting the parameter `MPC_THR_HOVER` to 0.38** already solves the problem or at least helps to improve it.

**Comment by santiago3dr** [comment]
@bkueng 
The issue I encounter is that when the copter touches the ground, sometimes the copter jumps back up about 1 meter and lands again or the other thing that happens is the copter upon touching the ground, lifts two legs and sort of jumps a few times before disarming.

I was not able to reproduce this in today's flights but as soon as I see it again, I'll send you a video clip of said behavior.

**Comment by santiago3dr** [comment]
I was able to reproduce the issue with the new stable release 1.8.0

great land detection:
https://review.px4.io/plot_app?log=9e3e76c7-7ac5-4e17-a624-069706e0d654

poor land detection:
https://logs.px4.io/plot_app?log=406113d2-d981-4794-958f-5fb6b295a2ec

video:
https://drive.google.com/open?id=1ad_aCtLa5KU97Y7FDC6LLEK0hgDC8m2v
