### ISSUE TITLE
How to choose flight modes

### ISSUE THREAD

**Issue by Omar-M-AbdelAziz** [PX4/Firmware#9709]
Hello, 
I have now PIXHAWK 2 and I want to use in my drone to do specific tasks 
So, till now, I can only fly the drone (simulation) using the offboard package https://github.com/Stifael/offboard
However,
What if I want to use other possible flight modes like altitude mode and position mode mentioned in the user guide, how is this possible ?

**Comment by Stifael** [comment]
@Omar-M-AbdelAziz, https://github.com/Stifael/offboard is deprecated. 
If you want to fly offboard, I suggest to checkout https://github.com/dronecore/DroneCore.
