### ISSUE TITLE
"IGN MISSION_ITEM: No transfer" error

### ISSUE THREAD

**Issue by feemi** [PX4/Firmware#9711]
An error occurs after uploading any mission to vehicle.

Which says "IGN MISSION_ITEM: No transfer".

It seems like it sends mission correctly. When i reopen qgc it downloads mission from vehicle successfully.

**Environment**
QGC v3.3.2 or QGC Master
PX4 1.7.4 Beta

**To Reproduce**
1. Drone switched on '...'
2. Uploaded mission '....' (attach QGC mission file)

**Expected behavior**
There should be no error after mission upload

**Comment by tops4u** [comment]
This should be fixed in the 1.8 Release.

**Comment by feemi** [comment]
Can not reproduced on 1.8.0 Release.
