### ISSUE TITLE
Baro spikes in SITL

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#9713]
For some reason the baro data in SITL (gazebo) is very spiky.
![sitl_baro_spikes](https://user-images.githubusercontent.com/7610489/41587894-91ea58a4-73b0-11e8-908a-345874baa8a1.png)

This causes the ekf height checks to fail. @JohannesBrand FYI

**Comment by dagar** [comment]
They're present in the pressure coming straight from the baro simulator driver, so it must be from gazebo.

https://github.com/PX4/sitl_gazebo/blob/10b0597cd20def97074c6c8eade580a7f294e41d/src/gazebo_mavlink_interface.cpp#L509-L516

**Comment by dagar** [comment]
@priseborough could you review the gazebo barometer noise?

https://github.com/PX4/sitl_gazebo/blob/10b0597cd20def97074c6c8eade580a7f294e41d/src/gazebo_mavlink_interface.cpp#L518-L532

**Comment by TSC21** [comment]
This is also having consequences on LPE: https://github.com/PX4/Firmware/issues/9713

**Comment by priseborough** [comment]
rand() returns a integer and x1 and x2 are supposed to be from a uniform random distribution between +- 1.0 so so lines  522 and 523 should be

     x1 = 2.0 * ((double)rand() / (double)RAND_MAX) - 1.0;
     x2 = 2.0 * ((double)rand() / (double)RAND_MAX) - 1.0;

If we had ranf() available to us, that would be a more efficient way of generating x1 and x2.

Use of Gaussian/Normal distributions is common in robotics and flight vehicle simulation, so support for this in the math library would be appropriate.

**Comment by LorenzMeier** [comment]
Can you send a PR? Thanks!

**Comment by priseborough** [comment]
Fixed here: https://github.com/Dronecode/sitl_gazebo/pull/43
