### ISSUE TITLE
Use ekf_att_pos_estimator on multirotors

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#972]
MC with ekf_att_pos_estimator was tested today and shown good performance. One test (circling at 5m/s with ~3m radius) passed much better than position_estimator_inav, no any altitude loss, while inav goes down by 5m during 3-4s of circling. Only noticable issue is significant attitude "noise" when GPS is not very good. Maybe weight for acceleration correction may be lowered.

TODO:
 - Review parameters to reduce attitude noise on bad GPS
 - Implement land detector
 - Implement altitude estimation without GPS (for ALTCTL mode)

**Comment by Zefz** [comment]
With #1595, the land detector has been removed from position estimators and is handled by a separate land_detector module.

I have noticed a glitch in the ekf_att_pos_estimator on a multicopter while flying in Manual mode and getting proper GPS fix mid-flight. The drone twitches when the EKF is dynamic reinitialized with GPS data.

**Comment by Zefz** [comment]
Altitude estimation without GPS is implemented in #1770. There is also no longer any glitches in losing/recovering GPS while flying. I have observed a small twitch in altitude when gaining GPS for the first time while flying in AltHold while PosHold was enabled on the RC (no more than 1 meter).

GPS Glitch protection is probably the only todo remaining in this PR.

**Comment by LorenzMeier** [comment]
New Q estimator made this much less interesting, and since @Zefz did the integration and we're able to test / fly I'm closing this.
