### ISSUE TITLE
A VTOL crash after log stop in the air after 'vtol_att_control low on stack' warning (flight log linked)

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/Firmware#9720]
Hi~ I hope PX4 developers to help finding the reason of crash.

A delta-quad type VTOL drone crashed on the water while in transition flight trials of a developing drone after logging is stopped after 'vtol_att_control low on stack' warning happened  but telemetry log sustained from the logging stop to the crash.

I am not sure this is a bug or not, but upload logs for analysis.

**Environment:**
PX4 v1.7.3, Pixhawk 2.1, QGC v3.3.1, Ubuntu 14.03, DeltaQuad airframe

**Changed parts of source code:**
Mixer script change for two yaw motors that separately mounted.
Multirotor mixer mix() function change (not to include yaw control in quadrotors)
MAVLink stream SERVO_OUTPUT_RAW_1 and ACTUATOR_CONTROL_TARGET_0 were added.
No change in vtol_attitude_control and other modules.

**Flight procedure:**
In manual (stabilized) mode in multicopter phase of VTOL the drone was hovering.
In the state, the transition switch was turned on and it flew in manual (not stabilized) mode of forward transition phase.
When it reaches to fixed-wing mode, the transition switch was tuned off because its altitude became to decline (the lift force is small because its forward thrust is small).
In the second trial of this transition flight the accident happened.

**Peculiar things:**
In previous several flights, the flight mode of fixed-wing phase was stabilized mode and any accident did not happened. But in the accident the mode was manual mode for the first time though I don't know it is related or not to the cause.

**Log flies:**
- a ulog file ([flight log](https://logs.px4.io/plot_app?log=5ddb8655-0658-4c3b-9282-69bc692587f8))
The below files can be given to people who want more:
- a tlog file (telemetry log) :  the file is corrupted by the abrupt disconnection of communication and cannot be loaded by QGC
- a telemetry text log converted from the tlog file
- a global position text log file extracted from the tlog file

**Comment by RomanBapst** [comment]
@dagar This is based on 1.7.3. It did not include the fix for the vtol controller freezing in manual mode
https://github.com/PX4/Firmware/commit/3b0b5645e14e36c1bc7025db81ebbb7d9d8d0007#diff-cd9a46a1bbc9010e5e50fd282544a874

Also it does not include all the fixes we have done after analysis of the in-air log stop crashes, right?

**Comment by RomanBapst** [comment]
Various actions have been undertaken in order to prevent partial log files which have rarely been observed in the past with PX4 1.7. We have not seen any more reports of this kind with PX4 1.8. 
I'm therefore closing this for now.
