### ISSUE TITLE
Pixhawk mini No mag sensor

### ISSUE THREAD

**Issue by OPLew** [PX4/Firmware#9725]
I get no mag sensor as soon as I connect the PX to QGC. And I can't finish the compass calibration.

I use the compass that came with the mini.

Anyone know what I could do. I think the compass needs to be replaced

![pix1](https://user-images.githubusercontent.com/40435923/41670375-69b7afbc-74b4-11e8-83fe-24fb878f4206.PNG)
![pix2](https://user-images.githubusercontent.com/40435923/41670377-69dd4326-74b4-11e8-9c30-1a5bb316a9b9.PNG)

**Comment by pietrodn** [comment]
I'm afraid this is an hardware defect. See [the "known issues" section of the guide](https://github.com/PX4/px4_user_guide/blob/master/en/flight_controller/pixhawk_mini.md), [this issue](https://github.com/PX4/Firmware/issues/7327) and [this other issue](https://github.com/PX4/px4_user_guide/pull/171).
