### ISSUE TITLE
v1.8 in QGC does not detect RC with PH2.1

### ISSUE THREAD

**Issue by asimonov** [PX4/Firmware#9727]
**Describe the bug**
The standard GQC firmware version of 1.8.0 does not work with FrSky RC on Pixhawk 2.1
If we build it from git it works fine with FrSky

**To Reproduce**
Upgrade firmware in QGC
Restart
Drone does not detect RC, it is not shown in QGC

**Expected behavior**
Work as before

**Comment by LorenzMeier** [comment]
Can you please share a log file and also the GIT hash you're building against?

**Comment by asimonov** [comment]
@LorenzMeier there is no log file as we could not arm without RC

there manually built version that works is this: https://github.com/PX4/Firmware/commit/96443b3cf3e3adaec8b2ebb6c83a19a92d40a13f
