### ISSUE TITLE
Sensor calibration fails silently with temperature calibration enabled

### ISSUE THREAD

**Issue by troy-at-skyfront** [PX4/Firmware#9736]
The sensor calibration procedure fails silently when the flight controller has temperature compensation enabled. I followed the Offboard Temperature calibration guide here: https://docs.px4.io/en/advanced_config/sensor_thermal_calibration.html#offboard_calibration

The temperature compensation procedure works well up until step 12. I am able to create graphs and polynomial fits for the accelerometer, gyro and barometer biases with respect to time. However, at step 12, I am unable to generate any new accel or gyro calibration parameters (CAL_ACC*, CAL_GYRO*) -- they are all set to defaults. To be clear, I am able to run through the sensor calibration procedures without error, but no non-default parameters are generated. 

When I disable temperature compensation (TC_A_ENABLE = 0, TC_B_ENABLE = 0, TC_G_ENABLE = 0), I can successfully generate new accel and gyro calibration parameters. 

In order to get temperature compensation to work, I must first calibrate the sensors with temperature compensation disabled. Afterward, I then enable temperature compensation and then load the TC* parameters generated by the previously performed calibration procedure.

- PX4 v1.7.3
- Pixracer by mRobotics

**Comment by mhkabir** [comment]
This is by design. See the section "Compatibility with legacy CAL_* parameters and commander controlled calibration" on the same page.
