### ISSUE TITLE
Disabling  mc_att_control, mc_pos_control and vtol_att_control in nuttx_px4fmu-v2_default.cmake is causing build to fail in FW v1.8.0

### ISSUE THREAD

**Issue by Ankur1014** [PX4/Firmware#9745]
I am using FW v1.8.0 on Ubuntu 16.04. I do not want to build all the modules in nuttx_px4fmu-v2_default.cmake especially the controllers. Hence I am disabling mc_att_control, mc_pos_control and vtol_att_control. However upon doing this firmware build is failing with error in navigator.cpp

**Comment by LorenzMeier** [comment]
Feel free to send a PR to untangle these. Yes, we want modules to not interdependent but right now it is not something we will focus the core dev team on. Happy to accept pull requests or discussing specific changes.
