### ISSUE TITLE
After uploading a "bad" mission, Bad tones (beeps) happen everytime, even when uploading a good mission

### ISSUE THREAD

**Issue by Antiheavy** [PX4/Firmware#9746]
When the vehicle rejects a mission the first time we hear the "bad" tones from the autopilot beeper (this is expected).  Any subsequent uploads of ANY mission (good or bad) the "bad" tones happen.

This is happening on 1.8.0.

I think has been happening for a long time, but we finally just realized it is 100% repeatable.  The way we usually see it is we upload a mission with a landing pattern that is too short and it gets rejected.

**Comment by dagar** [comment]
Something must be wrong with the logic here. 

https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L2069-L2075

Possibly a previous warning that hasn't been cleared.

**Comment by Antiheavy** [comment]
@dagar the tweak we just tried seems to have resolved this issue.  Is it worth making a smaller stand-alone PR here in upstream?

**Comment by Antiheavy** [comment]
@dagar  Did the fix for this make it upstream?

**Comment by dagar** [comment]
No, the more thorough fix is here. https://github.com/PX4/Firmware/pull/9747

**Comment by Antiheavy** [comment]
@dagar the fix for this bug seems like something that should be part of v1.9.0.   thoughts?

**Comment by Antiheavy** [comment]
still valid issue?

**Comment by dagar** [comment]
This isn't fixed in master?

**Comment by Antiheavy** [comment]
Yep, this is fixed in Master.  closing.
