### ISSUE TITLE
Gazebo fixed wing SITL nevers completes landing

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#9755]
Using master firmware, master QGC:
* Create a simple mission with a few waypoints and a landing pattern
* Run it
* When the vehicle comes in to flare it slows way down and the altitude drops to 0 as it gets to the landing point
* The vehicle then speeds back up to full speed and continues past the landing point flying at 0 alt forever

This is a big problem for me since it means I can't test resume mission in QGC.

**Comment by LorenzMeier** [comment]
@dagar Could you have a look?

**Comment by dagar** [comment]
I believe this is a result of the limited or lack of ground friction, overpowered sitl plane model, and throttle settings.

I've been meaning to get a full plane auto mission (runway takeoff, waypoints, loiter, landing) in the CI system.

**Comment by lamping7** [comment]
Does https://github.com/PX4/Firmware/pull/10250 fix this for you @DonLakeFlyer? It's merged in master.
