### ISSUE TITLE
Descending with MPC_LAND_SPEED instead of MPC_Z_VEL_MAX_DN

### ISSUE THREAD

**Issue by ivodre** [PX4/Firmware#9768]
**Describe the bug**
When descending during a mission in simulation the Deltaquad does the whole descend with MPC_LAND_SPEED instead of descending with MPC_Z_VEL_MAX_DN until MPC_LAND_ALT1, and than ramping down to MPC_LAND_SPEED. 

**To Reproduce**
1. Create "multicopter" mission with delta quad in gazebo (e.g. at 30m altitude)
2. Make sure to set reasonable values for MPC_LAND_SPEED, MPC_Z_VEL_MAX_DN, MPC_LAND_ALT1, MPC_LAND_ALT2
2. Start mission

**Expected behavior**
The vehicle climbs with MPC_Z_VEL_MAX_UP, flies at desired altitude and than descends with MPC_LAND_SPEED all the way to the ground. 

**Log Files**
https://logs.px4.io/plot_app?log=70e15793-db80-4ec7-91d8-d1b6af522e70

**Drone (please complete the following information):**
- Gazebo Deltaquad

**Additional context**
We observed this also in real flights

@lamping7

**Comment by dagar** [comment]
@sanderux @RomanBapst

**Comment by dagar** [comment]
Likely an issue with the multicopter position controller rather than VTOL specific.
