### ISSUE TITLE
Add driver for ST LSM9DS1/LSM9DS0

### ISSUE THREAD

**Issue by mkuliberda** [PX4/Firmware#9817]
Hi,

is it possible to add drivers for mentioned above IMUs in the near future?

Thank you in advance,

**Comment by proficnc** [comment]
Isn’t there already a driver for this? We used this chip on the PXF back in 2014...

**Comment by mkuliberda** [comment]
I could find only LSM303 in the repository..

**Comment by mkuliberda** [comment]
Great, thank you very
