### ISSUE TITLE
How to provide home position locally.

### ISSUE THREAD

**Issue by rahulsharma11** [PX4/Firmware#9878]
Hi,
I am flying my single copter indoor without GPS. I am using px4flow with i2c sonar. Its doing auto takeoff upto my defined altitude(1.3m). I have provided mission(if any) in "COM_TAKEOFF_ACT" parameter and uploaded a small mission already.
But it does not do mission and just keep holding position. Does it require gps necessarily for mission? Any suggestion?

**Comment by mhkabir** [comment]
GPS is a requirement for missions currently.
