### ISSUE TITLE
PixHawk 4 (PX4Fmu V5) and Px4Flow

### ISSUE THREAD

**Issue by ecmnet** [PX4/Firmware#9881]
Px4Flow (Standard Firmware, I2C Address 0x42) is not recognized by PixHawk 4 / V1.8.0 stable and master connected to I2C A. It works fine with PixHawk 1.0 (3DR). The driver is not loaded.
Update: I can confirm, it works on I2CB.

**Comment by DanielePettenuzzo** [comment]
@ecmnet 
@RomanBapst and I noticed the same thing today. We can push the fix tomorrow.. currently it only works on I2CB.

**Comment by LorenzMeier** [comment]
@DanielePettenuzzo Ping

**Comment by DanielePettenuzzo** [comment]
@ecmnet sorry for the delay.. this pr should fix your issue: https://github.com/PX4/Firmware/pull/9945

**Comment by DanielePettenuzzo** [comment]
nothing changes in how you start the driver.. just one additional bus is scanned

**Comment by DanielePettenuzzo** [comment]
@ecmnet is this issue solved?

**Comment by ecmnet** [comment]
Yes, it‘s solves
