### ISSUE TITLE
nxphlite commit issues.

### ISSUE THREAD

**Issue by Avysuarez** [PX4/Firmware#9883]
@davids5 The commit 76b3d64 of leitwert-nxphlite-serial-dma, doesn't working. I updated with that commit and the flight controller turn on but doesn't initialized.

**Comment by davids5** [comment]
@Avysuarez The pr https://github.com/PX4/Firmware/pull/9834 now requires the bootloader be used.

You will have to program the bootloader bin file at address 0. 
Then use the px4 uploader `make nxphlite-v3_default upload` OR load the nxphlite-v3_default.bin @ 0x6000

**Comment by r0gelion** [comment]
After loading the bootloader it worked.

Thanks!
