### ISSUE TITLE
u-Blox external gps with snapdragon flight 

### ISSUE THREAD

**Issue by ericjohnson97** [PX4/Firmware#9893]
Over the last couple days I have been trying to get the u-Blox gps module to work with my snapdragon flight board.  I realize the pins on the module don't map to the j9 connector 1 to 1, so I have re arranged the wires so they map correctly. I have also added the file blsp.config to /usr/share/data/adsp with the contents 
```
tty-1 bam-9 2-wire  
tty-2 bam-6 2-wire  
tty-3 bam-8 2-wire  
tty-4 bam-2 2-wire
```
as described [here](https://docs.px4.io/en/flight_controller/snapdragon_flight.html)

in addition I have noticed that when I run `help` on the command line I do not see the gps command. When I manually run the command to start the gps on my drone I get the following 
```
pxh> gps start -d /dev/tty-4
Invalid command: gps
type 'help' for a list of commands
pxh> 
```
I also have a simulated enviorment setup using px4 + gazebo, and I see the gps command when I run help and can run gps commands.

Just wondering if this feature might have broke at some point or if I am doing something wrong.

**Comment by LorenzMeier** [comment]
@RomanBapst Could you please look into this?
