### ISSUE TITLE
Low voltage check will not be updated in FMU v5 1.80 stable firmware

### ISSUE THREAD

**Issue by cuhome** [PX4/Firmware#9915]
My cuav v5 flight control set the low voltage fault protection to 10.5v, I give it 10v voltage, try to unlock, gcs will prompt low battery, then I raise the voltage to 12v, unlock will still prompt the error. If you re-power on, input 12v to the flight controller and you can unlock it normally.

**Comment by dagar** [comment]
By unlock do you mean arm?

**Comment by cuhome** [comment]
yes

**Comment by LorenzMeier** [comment]
This is by design to prevent varying battery levels from giving intermittent results. Please reopen if you see a specific issue, but since a battery on a disarmed vehicle is pretty predictable, this works as intended.
