### ISSUE TITLE
Upload (AUTOPILOT_HOST) address for Raspberry Pi2/3 (with navio board) 

### ISSUE THREAD

**Issue by vkotaru** [PX4/Firmware#9940]
px4 _building the code_  documentation (https://dev.px4.io/en/setup/building_px4.html#raspberry-pi-23-boards)  for Raspberry Pi2/3 boards suggests setting IP (or hostname) for RPi using 

```
 export AUTOPILOT_HOST=192.168.x.x
``` 

however, when we try uploading the firmware to raspberry pi using 

```
 cd Firmware
 make posix_rpi_cross upload
```
throws an error `ssh: Could not resolve hostname navio: Name or service not known`. This is because [posix CMakeLists.txt](https://github.com/PX4/Firmware/blob/master/platforms/posix/CMakeLists.txt) (line 66) uses the address `pi@navio`. 

Changing `pi@navio` to `pi@"$EVN{AUTOPILOT_HOST}"` would be consistent with the documentation and fixes the error. 

Thanks
Prasanth

**Comment by bkueng** [comment]
Hi @vkotaru 

Can you create a pull request with the suggested changes?
Thanks

**Comment by vkotaru** [comment]
Done
