### ISSUE TITLE
Jenkins todo

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#9946]
- split pipeline https://github.com/PX4/Firmware/pull/9692
 - add hardware testing https://github.com/PX4/Firmware/pull/8321
 - upload master/beta/stable binaries directly in pipeline
 - from successful master build upload all metadata (s3 & gitbooks)
   - param
   - airframe
   - modules
   - uorb?
 - doxygen generate and upload
 - better visibility for all output
   - table of mission test results (explanation and links to successful run)
   - static analysis output (clang, cppcheck)
   - binaries for testing
 - CI testing
   - optical flow
   - avoidance
   - wind
   - sensor failures
 - nightly profiling

**Comment by hamishwillee** [comment]
Good list for me - excellent to centralise. If by UORB you mean the [graph here](http://dev.px4.io/en/middleware/uorb_graph.html), then yes please.

**Comment by lamping7** [comment]
I can pick the multi pipeline back up next week. Can you comment over there on its current state when you get a chance to look. The other tasks will take some discussion, but I like the summary you've made.

**Comment by dagar** [comment]
Idea - make the existing test pipelines re-usable in different modes.
 - regular
 - codecoverage (+ upload to codecov.io)
 - address sanitizer
 - thread sanitizer
 - etc

The coverage and sanitizer variants could be limited to master only.
