### ISSUE TITLE
In-air restart for multicopter not working

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#996]
I tried rebooting FMU while flying (hand-held). IO switches off while FMU restarts, so thats fine, but then it doesn't switch back on.

Instead the FMU shows the RGBLED red and starts beeping.

(MAV 001:50) Audio message: IN AIR 

--> FMU reboot

(MAV 001:50) [inav] started 
(MAV 001:50) [mpc] started 
(MAV 001:50) [navigator] started 
(MAV 001:50) [sdlog2] start logging 
(MAV 001:50) [sdlog2] log dir: /fs/microsd/log/sess002 
(MAV 001:50) [sdlog2] log file: log001.bin 
(MAV 001:50) [inav] baro offs: 485.46 
(MAV 001:50) Audio message: LANDED 
(MAV 001:50) [inav] GPS signal found

**Comment by LorenzMeier** [comment]
@julianoes How about finishing off your 2-year old issue yourself? 8).

**Comment by julianoes** [comment]
Gotta test it ;)

**Comment by julianoes** [comment]
Gave this a bench test and it the start up into in-air restart mode works. However, when the FMU is down/rebooting, the motors go to mid or even full throttle instead of shutting off.

**Comment by LorenzMeier** [comment]
Fixed.
