### ISSUE TITLE
[Fixed wing]Need special throttle slew rate for takeoff

### ISSUE THREAD

**Issue by jinchengde** [PX4/Firmware#9967]
FW_THR_SLEW_MAX is used for the fixed wing normally, but in takeoff stage, the throttle slew rate is need more smoothly  than in the air, specially the Throttle ramp period.
even we could use landing gear steer function to keep straight, but if the throttle accelerate too sharp, the plane body will rotate caused by reverse torsion when we switch to mission mode.
So could we have a new parameter for the THR_SLEW_MAX, special for takeoff.

**Comment by ryanjAA** [comment]
We actually see something related (but not torsional) for takeoff at extremely high base elevations. If the throttle is enabled via a mission start and goes to WOT, the prop is often stalled with many of our efficient setups. The plane ends up not moving (very very slowly) but with a more gradual increase in throttle, the increase in speed then moves enough air over the prop to get things working as needed so a takeoff throttle slew rate is a very good idea.
