### ISSUE TITLE
NXPhlite issues.

### ISSUE THREAD

**Issue by Avysuarez** [PX4/Firmware#9973]
@davids5  Has issues maintaining altitude  in position, altitude and Auto. The accuracy of the GPS is very poor. in POS it maintain the position  but in mission it doesn't.

commit 5b0ad4e1.
https://review.px4.io/plot_app?log=ff6f685c-eb1a-412a-93e3-80354cbf602c
https://review.px4.io/plot_app?log=a5824a2a-e8ff-4f00-b7c4-b1018c694652
https://review.px4.io/plot_app?log=1c2da437-5699-4ddc-bf01-1d5ab0814187
https://review.px4.io/plot_app?log=aa719c97-71c4-4d05-aea6-ef6f8a36ce01
https://review.px4.io/plot_app?log=ff6f685c-eb1a-412a-93e3-80354cbf602c
https://review.px4.io/plot_app?log=b0db2ecc-a6c9-42a1-8a49-f8afea1ffa2e

commit 9e4e19d4.
https://review.px4.io/plot_app?log=910de492-f7b7-4fe4-8983-837c3f130218
https://review.px4.io/plot_app?log=42c37087-c863-4423-9f11-c8bb517da99f

**Comment by Tony3dr** [comment]
@davids5, please update the issue when you get a chance.

**Comment by davids5** [comment]
@Tony3dr , @dagar and I are looking in to the root cause. I will add to the PR https://github.com/PX4/Firmware/pull/10280  a commit with the filtering lowered for testing. But dagar suspects the issue is relates to the input rate to the EKF.

**Comment by davids5** [comment]
Please do a **cautious** flight test @PX4/testflights on master. 

Please fly NXPHlite-v3  to test if this issue still is present.

If there are any comms issues* we will need to troubleshoot in real time on slack.

*(There is still  a hadfault when QGC is connected via USB - WIP) 

Use real safety switch on all HW and cross test FMUv4, FMUv2  (2mb)

**Comment by Avysuarez** [comment]
flight running master,(commit 5847ab4).
https://review.px4.io/plot_app?log=177abd89-3e18-44d0-9cd1-9376f2a28246

The thelemetry connection is already working, but has the same issue. the copter doesn't maintain altitud in alt mode with the throttle in 0 the copter it rose to 80 meters. Also the doesn't working the position mode and auto.

**Comment by davids5** [comment]
@dagar would you please have a look at the logs and give me some advice

**Comment by dagar** [comment]
@Avysuarez your GPS was never very good in that flight. Which external unit are you using?

The vehicle never attained a valid local position, global position, or home position.

**Comment by dagar** [comment]
@Avysuarez you could try changing `COM_ARM_WO_GPS` to require valid global position because it lets you arm.

I would try a different GPS unit if you have one available.

**Comment by Avysuarez** [comment]
@dagar Ok, i'll try again

**Comment by Avysuarez** [comment]
@dagar I tested again and the same issue, I waiting 5 minutes before take-off and the gps don't locked. I was change the GPS for one of cuav (ublox m8n).  I flew in stabilized and did respond to the radio and crashed!
https://review.px4.io/plot_app?log=0677d8ff-bb7f-4e68-925e-ed18c62ee2f8

> **(at the moment we do not have a vehicle to test nxphlite!)**

**Comment by igalloway** [comment]
@avysuarez replacement units sent

**Comment by Tony3dr** [comment]
@igalloway can you please share the tracking info? Thanks.

**Comment by davids5** [comment]
@Tony3dr please test current maste on new hw when available.

**Comment by Tony3dr** [comment]
@davids5 the hardware will be received tomorrow afternoon in our office. We will resume NXPhlite testing on Monday. We will let you know how it goes.

**Comment by Avysuarez** [comment]
@davids5 @Tony3dr 
I flew the nxp with the master and flew well in stabilized mode and altitude, but i had issues with the GPS, i was waiting more than 10 minutes and do not lock the position, rejected the position mode. 
The GPS is a ready tosky ublox M8N.
https://review.px4.io/plot_app?log=dd59e88f-559a-4091-bdfd-5aeec11e840d
https://review.px4.io/plot_app?log=9a90fbf9-ddcb-41ef-a4af-f2a39028e230

**Comment by davids5** [comment]
@Avysuarez - Thank you! There is a issue with the board jamming the GPS. Work is being done to determine the cause.  Will let you know when we have something to test. FYI @igalloway @bkueng

**Comment by bkueng** [comment]
The jamming indicator is not particularily high in these logs (around 20), but the reported accuracy is not good enough, which can also be due to the board.

Additional issue: the vibration levels on the vehicle are extremely high (especially in x-y), can you please fix the setup?

**Comment by davids5** [comment]
@bkueng 

Working on the jamming issue: There is a build with a rounded the clock on the SD here https://github.com/PX4/Firmware/pull/10626
