### ISSUE TITLE
Hard crash - "Error- Critical Navigation Failure"

### ISSUE THREAD

**Issue by sticks918** [PX4/Firmware#9976]
Hi all,

Flying a Pixracer and since updating to the latest stable firmware I can no longer fly Missions. Even with a very good GPS fix, the drone will take off and then after several seconds lose GPS fix and require an emergency stop, often crashing spectacularly in the process.

One of the crash logs is here: [https://logs.px4.io/plot_app?log=1eadcfab-43dd-48b9-8efb-a9125dab85d4#Nav-GPS-Uncertainty](http://url)

Another is here: [https://logs.px4.io/plot_app?log=a6d95aad-c078-4406-8688-d6ffa77310cf](http://url)

If it is losing a GPS fix, the logs don't seem to show that so I'm a bit stumped on how to proceed. Any ideas?

Thanks!

**Comment by bkueng** [comment]
Hi @sticks918 

Your vehicle has too high vibrations levels (https://logs.px4.io/plot_app?log=a6d95aad-c078-4406-8688-d6ffa77310cf#Nav-Raw-Acceleration (Z graph should not touch X and Y when hovering) and https://logs.px4.io/plot_app?log=a6d95aad-c078-4406-8688-d6ffa77310cf#Nav-Acceleration-Power-Spectral-Density).
As a result of this the velocity estimation fails: https://logs.px4.io/plot_app?log=a6d95aad-c078-4406-8688-d6ffa77310cf#Nav-Estimator-Watchdog. The GPS itself is fine.

**Comment by sticks918** [comment]
Thanks @bkueng , can you tell me what a reasonable limit might be for the raw acceleration? I'll try to change my controller mount so it's less shakey. 

The pixracer has 2 accelerometers on it, does it use both for calibration & flight or does it just use the primary?

**Comment by bkueng** [comment]
Generally the lower the better. Here's a good example: https://logs.px4.io/plot_app?log=3938c48a-4889-44b7-ac1d-ad2be4629ba9
The frame, motors and props will make a big difference as well. Make sure to use high-quality components and balanced props.

Both accels are calibrated but only one is used, the other is used in case the first one fails.

**Comment by sticks918** [comment]
Great, thanks for the help!
