### ISSUE TITLE
Is there a way to find the external magnetometers supported by PX4 ver 1.8.0?

### ISSUE THREAD

**Issue by ambikaverma** [PX4/Firmware#9979]
I'm working on integrating here+ gnss with intel aero drone with px4 ver 1.8.0 running.

I was looking for magnetometers already supported by ver 1.8.0 but haven't been able to find this information. Is the PX4/Firmware/ROMFS/px4fmu_common/init.d/rc.sensors corresponding to the latest PX4 version? This seems to only list one option for external compass for intel aero. 

if anyone can point to magnetometers/compass currently supported in ver 1.8.0 that will be great.
Thanks!

**Comment by hamishwillee** [comment]
[Docs](https://docs.px4.io/en/gps_compass/) say:

> PX4 can be used with the following compass parts (magnetometers): Bosch BMM 150 MEMS (via I2C bus), HMC5883 / HMC5983 (I2C or SPI), IST8310 (I2C) and LIS3MDL (I2C or SPI).

This is based on the drivers in Firmware here: https://github.com/PX4/Firmware/tree/master/src/drivers/magnetometer

What is actually supported by each board may change due to space considerations etc.
