### ISSUE TITLE
Intel Aero: mission upload broken on master

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#9984]
Flashed master ade70cb and the mission that was previously stored seemed to be deleted.
Attempted to upload mission and got error: (MAV_MISSION_ERROR) & Unable to write on micro SD
![capture](https://user-images.githubusercontent.com/13203106/42965006-946d4abe-8b4d-11e8-9509-6f8419e8183b.JPG)
![capture1](https://user-images.githubusercontent.com/13203106/42965010-9679f442-8b4d-11e8-948b-6451b4c96fdc.JPG)

Log of failed to engage Auto and failed to upload new mission:
https://logs.px4.io/plot_app?log=e93d393e-eb44-48f8-a457-2be20e8b2e96

**Comment by lbegani** [comment]
@santiago3dr  Is it easily reproducible or was it seen only once?

From the log, it seems like navigator has entered some invalid state and hence not saving new mission.

```
Logged Messages

10:00:21WARNING[load_mon] tap_esc low on stack! (228 bytes left)
20:00:30WARNING[load_mon] tap_esc low on stack! (228 bytes left)
30:00:39WARNING[load_mon] tap_esc low on stack! (228 bytes left)
40:00:48WARNING[load_mon] tap_esc low on stack! (228 bytes left)
50:00:57WARNING[load_mon] tap_esc low on stack! (228 bytes left)
60:01:02WARNING[navigator] No valid mission available, refusing takeoff.
70:01:05WARNING[navigator] No valid mission available, loitering.
80:01:24WARNING[load_mon] tap_esc low on stack! (228 bytes left)
90:01:31WARNING[navigator] Invalid mission state.
100:01:31ERROR[navigator] Can't save mission state
110:01:33WARNING[load_mon] tap_esc low on stack! (228 bytes left)

**Comment by santiago3dr** [comment]
I have attempted with daily releases of master and I'm getting this sane error.

**Comment by santiago3dr** [comment]
Reverted to 1.8.0 stable; mission upload goes through successfully so this is definitely on the software size, I'll try to find the specific commit that broke said function.

**Comment by santiago3dr** [comment]
flashed current master ca42483
no change

**Comment by LorenzMeier** [comment]
@anitha-suresh Any chance someone from the team can have a look?
